### ISSUE TITLE
In Test Mode, build-multi-ont-kg.sh Failed (Snakemake)

### ISSUE THREAD

**Issue by ericawood** [RTXteam/RTX#1002]
Standard Error Log:
![image](https://user-images.githubusercontent.com/36611732/89662477-ff623700-d888-11ea-905d-3dee58444079.png)

Standard Out Log:
![image](https://user-images.githubusercontent.com/36611732/89662793-75ff3480-d889-11ea-8ba0-50dfd5502c34.png)

**Comment by ericawood** [comment]
This was in kg2-curie-refactoring-issue593

**Comment by ericawood** [comment]
Snakemake Log:
![image](https://user-images.githubusercontent.com/36611732/89663238-22411b00-d88a-11ea-9e2b-73173dc1af19.png)

**Comment by saramsey** [comment]
OK I will look into this today

**Comment by saramsey** [comment]
Hi @ericawood what version of `prefixcommons` are you running?  Can you please do a `pip freeze | grep prefixcommons`?

**Comment by saramsey** [comment]
Also, just an FYI, my eyes are not so good -- it is better to paste stack backtraces into the issue as text so I can increase the fontsize.

**Comment by saramsey** [comment]
OK I am pretty sure that `prefixcommons.contract_uri` is being called with `uri=None` as the first argument.

**Comment by ericawood** [comment]
> Also, just an FYI, my eyes are not so good -- it is better to paste stack backtraces into the issue as text so I can increase the fontsize.

Sorry about that. Would you like me to re-post the error messages?

kg2dev.rtx.ai: (where I ran the build)
`ubuntu@ip-172-31-23-154:~$ ~/kg2-venv/bin/pip3 freeze | grep prefixcommons
prefixcommons==0.1.7
`

`ubuntu@ip-172-31-23-154:~$ pip freeze | grep prefixcommons
prefixcommons==0.1.9
`

**Comment by saramsey** [comment]
> Sorry about that. Would you like me to re-post the error messages

Thanks, it's OK, more of a FYI for future issue postings. I was able to read it by zooming in.

**Comment by saramsey** [comment]
Hey @ericawood I see that the merge is happening (which is great!).

So, I have some code changes to kg2_util.py and multi_ont_to_json_kg.py to try and debug this issue. Do you want me to put these changes into the `kg2-curie-refactoring` branch? or the `kg2-curie-refactoring-issue593` branch?

**Comment by saramsey** [comment]
Hi @ericawood I have just made a couple of changes in a3515aa that I hope will narrow down the problem. Can you try running your test again?  Thanks.

**Comment by ericawood** [comment]
Hi @saramsey I will test that today, thank you!

**Comment by ericawood** [comment]
@saramsey I reran build-multi-ont-kg.sh twice (once with Snakemake, once just on the command line) and it completed successfully both times. I'm not sure what happened here, but maybe now that everything is merged into master, it is fine. I'm going to close this out and will reopen it if it happens again.

**Comment by saramsey** [comment]
ok thanks
