### ISSUE TITLE
kg2_util.predicate_label_to_iri_and_curie cuts off identifier for HMDB and DrugBank

### ISSUE THREAD

**Issue by ericawood** [RTXteam/RTX#1003]
This was noticed in #838, but I wanted to bring it into its own issue as I fix the problems in HMDB and DrugBank for documentation purposes. Also, Steve and I have been discussing how to do it with GO (http://purl.bioontology.org/ontology/GO/contributes_to -- what is currently in multi_ont_to_json_kg.py -- or http://purl.obolibrary.org/obo/GO_contributes_to -- the standard for other relation IRIs), so we can document that here as well.

**Comment by saramsey** [comment]
Pretty sure this is a bug, and I'm pretty sure I have a simple fix. I'm kinda thinking I should wait for the dust to settle from the big merge before fixing this?

**Comment by saramsey** [comment]
Note, a819af3 is for a different issue (#1002) not this issue

**Comment by saramsey** [comment]
Working on this now...

**Comment by saramsey** [comment]
Confirmed in an isolation test:
```
>>> kg2_util.predicate_label_to_iri_and_curie('predicate_label_to_use', 'GO', 'http://purl.obolibrary.org/obo/GO_')
['http://purl.obolibrary.org/obo/predicateLabelToUse', 'GO:predicate_label_to_use']
```

**Comment by saramsey** [comment]
Changing the code thus:
<img width="739" alt="Screen Shot 2020-08-07 at 3 36 24 PM" src="https://user-images.githubusercontent.com/5562107/89693594-c72c1a00-d8c3-11ea-9a25-c9a6877b1fd9.png">

results in better behavior for this simple test:
```
>>> kg2_util.predicate_label_to_iri_and_curie('predicate_label_to_use', 'GO', 'http://purl.obolibrary.org/obo/GO_')
['http://purl.obolibrary.org/obo/GO_predicateLabelToUse', 'GO:predicate_label_to_use']
```

**Comment by saramsey** [comment]
testing a possible fix now....

**Comment by saramsey** [comment]
running my test on `kg2steve.rtx.ai`,
```
bash -x ~/kg2-code/build-kg2.sh test
```

**Comment by saramsey** [comment]
I forgot to show the definition of `CURIE_PREFIXES_RELATIONS_USE_SNAKECASE`. This is kind of hacky, but here it is:
```
CURIE_PREFIXES_RELATIONS_USE_SNAKECASE = {'owl', 'rdfs', 'skos'}

```

**Comment by saramsey** [comment]
Uh, that code was wrong. I should have named that variable `CURIE_PREFIXES_RELATIONS_USE_CAMELCASE`.

**Comment by saramsey** [comment]
Rerunning my test now on `kg2steve.rtx.ai`... it died due to some unrelated issue

**Comment by saramsey** [comment]
Test successful:
<img width="709" alt="Screen Shot 2020-08-11 at 9 30 51 AM" src="https://user-images.githubusercontent.com/5562107/89923397-62b7d600-dbb5-11ea-9a72-ded20d42067b.png">
