### ISSUE TITLE
Should virtual edges be considered 'required' in results?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1009]
currently our 'virtual' edges (that `overlay` adds) are considered 'required' in results, because we agreed that `resultify` should only create results in which _every_ qnode/qedge in the query graph has been fulfilled. 

but I'm not sure if that's quite what we want for virtual edges. consider this query, which overlays data from ICEES+:
```
"add_qnode(curie=CHEMBL.COMPOUND:CHEMBL635, id=n0)",
"add_qnode(type=protein, is_set=true, id=n1)",
"add_qnode(type=chemical_substance, id=n2)",
"add_qedge(source_id=n0, target_id=n1, id=e0)",
"add_qedge(source_id=n1, target_id=n2, id=e1)",
"expand(kp=ARAX/KG2)",
"overlay(action=overlay_exposures_data, virtual_relation_label=E1, source_qnode_id=n0, target_qnode_id=n2)",
"resultify()",
```
(fyi: it currently throws an error during the final ranking step (#1008), but you can ignore that for the purposes of this issue.)

`expand` finds _a lot_ of matches for this query - about 4,000 nodes and 20,000 edges. but because ICEES currently has a small pool of curies it 'knows' about, it can only find exposures data for 21 of the `n0--n2` node pairs and thus only 21 virtual `E1` edges are added to the KG. and since `overlay` adds a virtual `E1` qedge to the query graph, `resultify` only creates 21 results (even though there's no `filter` step or anything).

do we really want our final result set to be limited to only the nodes that one overlay knowledge source happens to know about?

**Comment by saramsey** [comment]
This could be a good mini-hackathon topic (though sadly, I don't think I will be at the mini-hackathon if there is one today)

**Comment by dkoslicki** [comment]
I’ve thought a bit about this as well: eg. For NGD I have a default value (the “worst” value of infinity), and similarly with COHD,  that way all virtual edges are guaranteed to be populated with something even if the KP had no info about them. Is it possible to do something similar with ICEES+? Perhaps a value of “unknown” or something like that? But that will probably bork the conversion to float for downstream DSL... just a thought

**Comment by amykglen** [comment]
ah, yeah, that's true - if there was an acceptable value to assign for 'unknown' node pairs, that would get around this. doesn't seem great to assign a worst-case p-value (1.0) in the ICEES case, since 'these nodes aren't related at all' seems quite different from 'I don't know what these nodes are'... but maybe we could make something like "unknown" work, as you say? hmm...

**Comment by dkoslicki** [comment]
Yeah, "not related at all" != "I don't know about these nodes". So an "unknown" value seems to make the most sense here. Don't know what it should be though... `None` perhaps, or `NaN`?

**Comment by amykglen** [comment]
alright - I went with p-value of `None`, and it doesn't seem to bork the downstream DSL... (i.e., `test_overlay_exposures_data_virtual` still completes successfully, even though it produces a virtual edge with a p-value of `None`)

I guess I think it'd be more elegant if 'virtual' edges weren't required, as it seems kind of silly to be adding thousands of edges that provide no data, but that's more of just an aesthetic concern, so I'm happy with the current solution!

**Comment by amykglen** [comment]
ok, this is now working as expected for `overlay_exposures_data` on `/test` - it still errors out during the ranking step due to #1008 , but I can see that a full result set is created for the original query I posted (vs. only 21 results before):
```
2020-08-27 00:21:12.756844 INFO:  Resultify created 3798 results
```
so I'll close this issue
