### ISSUE TITLE
Output API format "origin_list"

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#101]
@edeutsch In the following:
```
from swagger_server.models.edge import Edge
edge = Edge()
```
There's a property (?) called ``edge.origin_list``. Is this supposed to be the current KG ``source_db`` corresponding to the database from which that edge originated? I ask since the data type is given as a list (which seems a bit odd for a source database, but may be motivated by multiple databases supporting an edge). The relevant line of code [is given here](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/FormatOutput.py#L140).

**Comment by edeutsch** [comment]
This part of the schema is in a high state of flux. The current KG standard has a single field "provided_by". However, when we designed the API std in January, we considered the possibility (likelihood) that a single edge may be sourced/supported from multiple KSes. So origin_list here is supporting the notion that there are multiple origins (thus origin_list) for a given edge. When I floated this last Thursday, it was decided that we would knock this question back to the KG standardization group for discussion. But I don't think they discussed it. So this is in a high state of flux.

Can you point to a real example of a case where one edge has two origins? It would help the ongoing discussion.

**Comment by dkoslicki** [comment]
I see; and as far as I'm aware Orangeboard is constructed specifically to populate the source_db with only a single entry (discarding additional databases for a single edge). Since the ``edge.origin_list`` is currently being populated in accordance to the spec, I go ahead and close this issue.

@saramsey might know of a few examples where an edge exists in multiple KSs though.
