### ISSUE TITLE
remove kg2-curie-refactoring-issue593 and kg2-curie-refactoring branches

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1010]
does anyone still need these branches?

**Comment by saramsey** [comment]
Hey @ericawood and @kvarforl just checking in on this?  Are you comfortable with these two branches being deleted?

**Comment by ericawood** [comment]
Yes, that is fine with me. Thank you for asking!

**Comment by kvarforl** [comment]
Also good by me!

**Comment by saramsey** [comment]
done
