### ISSUE TITLE
In test mode, can hmdb_xml_to_kg_json.py just save the first 10,000 metabolites?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1017]
Currently, running `hmdb_xml_to_kg_json.py` with `--test` generates a 1.1 GB JSON file. Would speed up the test build if the test mode truncated the number of metabolites written to the JSON file. As an example, see `chembl_mysql_to_kg_json.py`.

**Comment by ericawood** [comment]
Commit 544c1bf adds that limit. However, it doesn't significantly reduce the time that it takes for the script to run as the load in is the primary time consuming part of the script.
Test Mode: (12 minutes, 1 second)
```
Script starting at 2020-08-17 16:13:30
Starting load at 2020-08-17 16:13:30
Finishing load at 2020-08-17 16:25:10
Saving JSON at 2020-08-17 16:25:13
Finished saving JSON at 2020-08-17 16:25:31
Script finished at 2020-08-17 16:25:31
```

Full Mode: (14 minutes, 4 seconds)
```
Script starting at 2020-08-16 22:38:08
Starting load at 2020-08-16 22:38:08
Finishing load at 2020-08-16 22:50:55
Saving JSON at 2020-08-16 22:51:21
Finished saving JSON at 2020-08-16 22:52:12
Script finished at 2020-08-16 22:52:12
```

**Comment by saramsey** [comment]
Thanks. Is there a difference in the size of the file that is created?  That is also one of the advantages (I hope) of adding this limit.

**Comment by ericawood** [comment]
The new file is only 273M.

**Comment by saramsey** [comment]
Nice. Then I think this is helpful.
