### ISSUE TITLE
README.md for RTX/code/kg2/canonicalized directory

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1018]
I wonder if it would be helpful if we could have a README.md file for the `RTX/code/kg2/canonicalized` directory, with some basic information about 

1. what a canonicalized build is
2. who to contact for more information about the canonicalized KG2
3. how to build the canonicalized KG2 (even if just a link to a Wiki page or whatever)
4. how to deploy the canonicalized KG2 (even if just a link to a Wiki page or whatever)

I suppose an advantage of keeping the relevant docs in markdown file(s) in the canonicalized directory is that they are maintained and versioned *with* the canonicalization code modules and scripts. [This is, FWIW, why I have opted to keep all the documentation for KG2 in the `RTX/code/kg2` directory]. 

Anyhow, I am OK with it if you prefer to put the detailed maintenance docs in the Wiki, but in that case, I think they ideally would be linked to from the `README.md`.

**Comment by amykglen** [comment]
thanks @ericawood for creating the README!! it looks awesome. I'm going to leave this issue open just a little bit longer in case I think of anything else to add.

**Comment by saramsey** [comment]
Big thanks to @ericawood and @amykglen for doing this
