### ISSUE TITLE
Response ID in output API format populated by UI?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#102]
@edeutsch I assume that you're handling the response ID in [lines like the this](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/FormatOutput.py#L35). I've noticed that these are different over on http://rtx.ncats.io/ and wanted to be sure that my placeholder text won't mess anything up.

**Comment by edeutsch** [comment]
yes, already taken care of. These attributes are automatically replaced with correct values. all good. maybe better that you insert a blatantly wrong value at this point? rather than a valid but untrue value?

**Comment by edeutsch** [comment]
in case my replacing fails, then there isn't a plausible but untrue default value showing up.

**Comment by dkoslicki** [comment]
Sounds good: default value is now "-1".
