### ISSUE TITLE
KG2 Test Build Can't Run Without Manual Intervention

### ISSUE THREAD

**Issue by ericawood** [RTXteam/RTX#1020]
Line 56 of build-kg2.sh determines that the output file from `extract-semmeddb.sh` is:
`
semmed_tuplelist_file=${BUILD_DIR}/semmeddb/kg2-semmeddb${test_suffix}-tuplelist.json
`
Thus, if `build-kg2.sh` is run with `test`, the output file is `kg2-semmeddb-test-tuplelist.json`.

However, `extract-semmeddb.sh` is only run if the `build_flag` is `all` (rather than `test`). So, in lines 195-199, when the script calls `semmeddb_tuple_list_json_to_kg_json.py`, which does run in `test` mode:
```
${VENV_DIR}/bin/python3 -u ${CODE_DIR}/semmeddb_tuple_list_json_to_kg_json.py \
           ${test_arg} \
           ${mrcui_arg} \
           ${semmed_tuplelist_file} \
           ${semmed_output_file}
```

`${semmed_tuplelist_file}` doesn't exist.

One must first run `extract-semmeddb.sh ~/kg2-build/semmeddb/kg2-semmeddb-test-tuplelist.json
 test` manually for `build-kg2.sh test` to work correctly.

**Comment by saramsey** [comment]
Thank you, this is a great description of the issue.

**Comment by saramsey** [comment]
Hi @ericawood can you please check out a96fdc7 ?  Please let me know if that will solve the problem. This commit is intended to add a new `alltest` build option, that would be used like this:

```
bash -x ~/kg2-code/build-kg2.sh alltest
```

**Comment by ericawood** [comment]
Hi @saramsey, that looks like it will solve the problem. The one thing I'd add is that you should probably change (line 139) from 

`
    bash -x ${CODE_DIR}/extract-semmeddb.sh ${semmed_tuplelist_file}
`

to 
`
    bash -x ${CODE_DIR}/extract-semmeddb.sh ${semmed_tuplelist_file} [test]
`

if `alltest` is the build flag. Also line 221-222 runs
`
bash -x ${CODE_DIR}/build-multi-ont-kg.sh \
           ${output_file_full} ${build_flag}
`
Will the `alltest` build_flag interfere with this?

**Comment by saramsey** [comment]
Hi @ericawood ok can you please take a look at e39aa69 and 4a2dcb8 to see if those (together with the previous commit) will fix the issue?

**Comment by saramsey** [comment]
I acknowledge that this is an inelegant fix, but on the other hand, it is taking a "light touch" and not modifying too much.

**Comment by ericawood** [comment]
That should fix the semmeddb problem, but I think that it will break your call to build-multi-ont-kg.sh, if you want it to only do a test build. If it's alright with you, my plan to update the Snakemake build system is a bit different (so that build-multi-ont-kg.sh won't break):

Original:
```
if [[ "${build_flag}" == "test" ]]
then
    # The test argument for bash scripts (ex. extract-semmeddb.sh test)
    test_flag="test"
    # The test argument for file names (ex. kg2-owl-test.json)
    test_suffix="-test"
    # The test argument for python scripts (ex. python3 uniprotkb_dat_to_json.py --test)
    test_arg="--test"
else
    test_flag=""
    test_suffix=""
    test_arg=""
fi



if [[ "${build_flag}" == "all" ]]
then
    echo 'include: "Snakefile-extraction"' >> ${CODE_DIR}/Snakefile
fi
```

New:
```
if [[ "${build_flag}" == "test" || "${build_flag}" == 'alltest' ]]
then
    # The test argument for bash scripts (ex. extract-semmeddb.sh test)
    test_flag="test"
    # The test argument for file names (ex. kg2-owl-test.json)
    test_suffix="-test"
    # The test argument for python scripts (ex. python3 uniprotkb_dat_to_json.py --test)
    test_arg="--test"
else
    test_flag=""
    test_suffix=""
    test_arg=""
fi



if [[ "${build_flag}" == "all" || "${build_flag}" == 'alltest' ]]
then
    echo 'include: "Snakefile-extraction"' >> ${CODE_DIR}/Snakefile
fi
```

The Snakemake build system uses `test_flag` rather than `build_flag` during the rest of the build process.

**Comment by saramsey** [comment]
Hi @ericawood thanks for your reply. Can you elaborate on this?

> That should fix the semmeddb problem, but I think that it will break your call to build-multi-ont-kg.sh, if you want it to only do a test build. 

If I run
```
bash -x ~/kg2-code/build-kg2.sh test
```

then lines 129--174 are skipped, and then at line 221, `build-multi-ont-kg.sh` is run like this:
```
bash -x ~/kg2-code/build-multi-ont-kg.sh /home/ubuntu/kg2-build/kg2-ont-test.json test
```

why will that break?
```

**Comment by ericawood** [comment]
Hi @saramsey,
I'm referring to if you want to run a test build from scratch:
`bash -x ~/kg2-code/build-kg2.sh alltest`

at line 221, `build-multi-ont-kg.sh` is run like:
`bash -x ~/kg2-code/build-multi-ont-kg.sh /home/ubuntu/kg2-build/kg2-ont-test.json alltest`

In build-multi-ont-kg.sh on line 21:
```
if [ "${build_flag}" == 'test' ]
then
    test_suffix='-test'
    test_arg='--test'
else
    test_suffix=''
    test_arg=''
fi
```

A test build will not be triggered. Correct me if I'm wrong, but there are different ont load inventory files for test vs all.

**Comment by saramsey** [comment]
Hi @ericawood thank you. Sorry, I forgot to commit that fix. See c70d5bd. OK now?

**Comment by ericawood** [comment]
Yes, that should fix it! Thank you

**Comment by saramsey** [comment]
See also my analogous fix for `version.sh`, in 2c63eca

**Comment by saramsey** [comment]
Also, it's fine if Snakemake does things a bit differently internally. 

In the shell scripts, my use of `build_flag` for these two semantically distinct purposes (test vs. non-test, and partial vs. full build) is really inelegant. But it's a quick and easy fix to the shell scripts, for the short term, I suppose.

**Comment by ericawood** [comment]
Hi @saramsey, 
One problem in `extract-semmeddb.sh` for this system:
[L32](https://github.com/RTXteam/RTX/blob/master/code/kg2/extract-semmeddb.sh#L32) - `rm -r -f ${semmed_dir}`

According to `build-kg2.sh`, the tuplelist file, which is the output of `extract-semmeddb.sh` and has different versions for test/all, is in the `semmed_dir`:
[L56](https://github.com/RTXteam/RTX/blob/4088e1df4bb9ab677e13f878ea656e2f039d1c29/code/kg2/build-kg2.sh#L56) - `semmed_tuplelist_file=${BUILD_DIR}/semmeddb/kg2-semmeddb${test_suffix}-tuplelist.json`

If you run an all build, then an alltest build, your semmeddb tuple list from the full build will be gone and you will have lost the capability to do a partial build without rebuilding semmeddb. For my `alltest` build on `kg2steve`, I'm commenting the line in question out.
Also, since `alltest` will always be run after a full build, it seems unnecessary to delete the MySQL database for SemMedDB if in test mode as that takes a long time. What are your thoughts on this?

**Comment by saramsey** [comment]
Hmm, I'm thinking we should remove L32, what do you think?

**Comment by ericawood** [comment]
daf68fe removes L32
