### ISSUE TITLE
Fill in our KS's that aren't currently on Translator's radar

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1021]
According to the Architecture group, we need to, **by 8/21/2020**:

Add rows to [this spreadsheet](https://docs.google.com/spreadsheets/d/1nK7v0cw_yJfnX3kLUNxsxQRTmPZ6vUf0/edit#gid=907193666) for the KS's that we include in our KG2, but aren't currently listed on the spreadsheet. A list of our KS's is helpfully provided by Steve [here](https://github.com/RTXteam/RTX/tree/master/code/kg2#what-data-sources-are-used-in-kg2).

A tedious but simple task, so **asking for volunteers** (i.e. assigning a bunch of people, hoping someone will say "yes" and then we can de-assign the rest of everyone).

**Comment by kvarforl** [comment]
Went through and figured out which KS's need to be added as rows to the big spreadsheet (and added yes's to the Expander Agent Column where they were lacking).

The list of KS's to add, and their homepage links as provided by Steve:

- [Gtp](https://www.guidetopharmacology.org/)
- [PathWhiz](https://smpdb.ca/pathwhiz)
- [SMPDB](https://smpdb.ca/)
- [Therapeutic Target Database](http://bidd.nus.edu.sg/group/cjttd/)
- [BFO](http://www.obofoundry.org/ontology/bfo.html)
- [BSPO](http://www.obofoundry.org/ontology/bspo.html)
- [DDNAT](http://www.obofoundry.org/ontology/ddanat.html)
- [EFO](https://www.ebi.ac.uk/efo/)
- [EHDAA2](http://obofoundry.org/ontology/ehdaa2.html)
- [FMA](http://www.obofoundry.org/ontology/ddanat.html)
- [FOODON](http://www.obofoundry.org/ontology/foodon.html)
- [NBO](http://www.obofoundry.org/ontology/nbo.html)
- [ORDO](https://bioportal.bioontology.org/ontologies/ORDO)
- [PATO](http://www.obofoundry.org/ontology/pato.html)
- [RO](http://www.obofoundry.org/ontology/ro.html)
- [SNOMED](http://www.snomed.org/)
- [taxslim](http://www.obofoundry.org/ontology/ncbitaxon.html) (there is an NCBI Taxonomy entry with an expander agent yes, but links to different place... equivalent?)

**Comment by saramsey** [comment]
Thank you @kvarforl !

**Comment by saramsey** [comment]
Just to clarify, the excellent table (that @dkoslicki linked) of KS's used by KG2 was compiled by @amykglen , I can take no credit for it.

**Comment by dkoslicki** [comment]
@kvarforl Thank you so much for taking this over! As for:

> taxslim (there is an NCBI Taxonomy entry with an expander agent yes, but links to different place... equivalent?)

I had put a "Yes" under NCBI Taxonomy since that was the closest to taxslim. These are technically different, so a new row should be created for taxslim (and the "Yes" removed from the NCBI taxonomy row)

**Comment by kvarforl** [comment]
@dkoslicki thanks! There were also a bunch of ontologies that we had linked to obofoundry pages, but the spreadsheet linked to OLS pages... I assumed that if I could get to the OLS page from the obofoundry page, it was fine to consider them the same. is that a solid assumption?

**Comment by saramsey** [comment]
> @dkoslicki thanks! There were also a bunch of ontologies that we had linked to obofoundry pages, but the spreadsheet linked to OLS pages... I assumed that if I could get to the OLS page from the obofoundry page, it was fine to consider them the same. is that a solid assumption?

My $0.02: I think this is a solid assumption. It would be a weird corner-case if OLS has ontology "foo" and OBO has ontology "foo", but they are not the same ontology.

**Comment by kvarforl** [comment]
Okay, as far as I can tell, anything in the table should be in the sheet now : )

**Comment by dkoslicki** [comment]
Yes, forgot about this one
