### ISSUE TITLE
unichem_tsv_to_edges_json.py needs to add a "source node" for the whole Unichem source

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1025]
something like this, but for unichem:
<img width="584" alt="Screen Shot 2020-08-19 at 9 56 38 AM" src="https://user-images.githubusercontent.com/5562107/90666468-4b569980-e202-11ea-90e3-f00d07c5e75c.png">

**Comment by kvarforl** [comment]
@saramsey  something along the lines of this?   
![image](https://user-images.githubusercontent.com/39020520/94611532-b8743a80-0256-11eb-8b39-533c475bfa96.png)

I'm unsure what to use as the IRI... can you point me in the right direction?

**Comment by kvarforl** [comment]
Fixed in kg2.5.2
