### ISSUE TITLE
All information added and/or created by ARAX should decorate virtual edges when presented with a QG

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1036]
As noted by @edeutsch during a previous hackathon, it's probably best to have all extra information (eg. NGD, drug-treat-disease, fisher, etc.) to go on virtual edges, and **not** add additional edge properties to existing edges.

To Do:
- [x] edit [this YAML file](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter_templates.yaml) so it uses virtual edges for all calls to `overlay`
- [x] consult with @amykglen re: #1009

**Comment by amykglen** [comment]
alright, this issue should be taken care of (only one template needed updating in the yaml file).

I've tested locally, but suppose I should leave this issue open until it's verified on test/production.

**Comment by edeutsch** [comment]
@amykglen The latest `master` is now rolled out to /test and /beta

**Comment by amykglen** [comment]
awesome, thanks @edeutsch!

running into an error when attempting to test my changes on `/test` - wrote it up in: #1042.

**Comment by amykglen** [comment]
confirmed this looks good on `/test`!
