### ISSUE TITLE
Should Expand consider Biolink model hierarchy for qnode/qedge types?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1037]
Was thinking that when a query comes in for something like `(DOID:14330)--(chemical_substance)` it would make sense to also look for `drug` nodes, in addition to `chemical_substance`s. Then I realized perhaps `expand` should always consider a qnode's type plus its descendants' types (according to Biolink) for queries that come in?

For example, [these](https://biolink.github.io/biolink-model/docs/ChemicalSubstance#children) are the children of `ChemicalSubstance` according to Biolink:

- ChemicalSubstance
  - Carbohydrate
  - Drug
  - Metabolite

So the example query would look more like this from `expand`'s perspective:
`(DOID:14330)--(chemical_substance, carbohydrate, drug, metabolite)`

**Comment by saramsey** [comment]
Good idea

**Comment by saramsey** [comment]
This makes sense as a default behavior, I think.

Maybe the "include all descendent biolink types" behavior could also be turned off *optionally*?  IDK if that is possible.

**Comment by amykglen** [comment]
cool - yeah, good idea about making an option to turn it off - not a problem to add that.

**Comment by amykglen** [comment]
suppose I can close this 'question' issue since this is now an official requirement for KPs! (being tracked in #1268)
