### ISSUE TITLE
predicate remap

### ISSUE THREAD

**Issue by cmungall** [RTXteam/RTX#1038]
thanks for all your great work on
 https://github.com/RTXteam/RTX/blob/master/code/kg2/predicate-remap.yaml
!

some quick comments 

```
BFO:0000055:
  invert:
  - part_of
  - biolink:part_of
```

is this a typo? There is no such relation

http://purl.obolibrary.org/obo/BFO_0000055 - 404

same for some of the other BFOs

```
BSPO:0000102:
  rename:
  - coexists_with
  - biolink:coexists_with
```

http://purl.obolibrary.org/obo/BSPO_0000102 is ventral to - semantics of mapping not clear

more comments later - I think I will first write a script that translates this to SSSOM and injects the source labels to make it easier to see what is being mapped

**Comment by saramsey** [comment]
Hi Chris.

I do not believe it is a typo, meaning, we are seeing `BFO:0000055` predicates in relations from three different upstream ontologies (CL, INO, RO) in our ingestion process, so we have to contend with them whether they are deprecated or not:

<img width="758" alt="Screen Shot 2020-08-25 at 11 02 49 AM" src="https://user-images.githubusercontent.com/5562107/91210756-8d7c5100-e6c2-11ea-92d8-b47485f0b7c4.png">

**Comment by saramsey** [comment]
@dkoslicki I haven't heard back from Chris on this, so I am going to close it out.
