### ISSUE TITLE
A few nodes in KG are missing names

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#104]
It looks like a few uniprot nodes in the KG are missing names. You can find them using the cypher query  `match (n) where n.name = '' return n.id, n.name` which return the following 8 curie ids which all return results on the uniprot website:

curie_id | uniprot url
----|------
UniProt:P01358|http://www.uniprot.org/uniprot/P01358
UniProt:P20848|http://www.uniprot.org/uniprot/P20848
UniProt:Q9Y471|http://www.uniprot.org/uniprot/Q9Y471
UniProt:O60397| http://www.uniprot.org/uniprot/O60397
UniProt:Q8IZJ3|http://www.uniprot.org/uniprot/Q8IZJ3
UniProt:Q7Z2Y8|http://www.uniprot.org/uniprot/Q7Z2Y8
UniProt:Q8IWN7|http://www.uniprot.org/uniprot/Q8IWN7
UniProt:Q156A1|http://www.uniprot.org/uniprot/Q156A1

**Comment by finnagin** [comment]
This is the KG on the rtxsteve container at http://rtxdev.saramsey.org:7674

**Comment by DeqingQu** [comment]
It seems the best way to retrieve an entity from UniProt is through its XML API.
https://www.uniprot.org/help/api_retrieve_entries

I will write a python script to fix the bug.

**Comment by saramsey** [comment]
This bug seems to be resolved now.  There are no nodes in the KG without names.

**Comment by saramsey** [comment]
![screen shot 2018-05-21 at 2 45 53 pm](https://user-images.githubusercontent.com/5562107/40331578-ae371ffe-5d05-11e8-9b2a-a93d9d526a1a.png)
