### ISSUE TITLE
There are some conflicting/redundant-meaning edges between drug/chemical_substance and disease/phenotypic_feature in canonicalized kg2

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1040]
Hi @amykglen and @finnagin, when I work on issue #994, I found that there some conflicting/redundant-meaning edges between drug/chemical_substance and disease/phenotypic_feature in canonicalized kg2. 

Here is an examples:

CHEMBL.COMPOUND:CHEMBL606 (`chemical_substance`) and HP:0011410 (`phenotypic_feature`)
 If we pull all edges connected to these two nodes in canonicalized kg2, we can find the below edges having different edge label. Some of the edge labels have contradicting meaning. Like this case,  `treats` contradicts with `contraindicated_for`. There are also some redundant edges (e.g. two `related_to` edges in this case)

n.id | labels(n) | r.simplified_edge_label | m.id | labels(m)
-- | -- | -- | -- | --
"CHEMBL.COMPOUND:CHEMBL606" | ["chemical_substance"] | "related_to" | "HP:0011410" | ["phenotypic_feature"]
"CHEMBL.COMPOUND:CHEMBL606" | ["chemical_substance"] | "related_to" | "HP:0011410" | ["phenotypic_feature"]
"CHEMBL.COMPOUND:CHEMBL606" | ["chemical_substance"] | "has_input" | "HP:0011410" | ["phenotypic_feature"]
"CHEMBL.COMPOUND:CHEMBL606" | ["chemical_substance"] | "affects" | "HP:0011410" | ["phenotypic_feature"]
"CHEMBL.COMPOUND:CHEMBL606" | ["chemical_substance"] | "treats" | "HP:0011410" | ["phenotypic_feature"]
"CHEMBL.COMPOUND:CHEMBL606" | ["chemical_substance"] | "contraindicated_for" | "HP:0011410" | ["phenotypic_feature"]

This issue might affect the issue #994 because the model considers all edges except for the those with edge type meaning `indicated_for` and `contraindicated_for `. Since in this case `related_to` and `has_input` don't mean `indicated_for` and `contraindicated_for`, the edge between `CHEMBL.COMPOUND:CHEMBL606` and `HP:0011410` are considered. However, it might also involve both `treats` and `contraindicated_for` in the model. This doesn't make sense. Are there any fixes that would solve this issue?

**Comment by dkoslicki** [comment]
@chunyuma this may indeed be an issue in general, but for this specific `drug` and `phenotypic_feature`, I found the following:

>Misoprostol alone appears to be an acceptable and effective treatment for women with EPF. However, use of misoprostol in late pregnancy is associated with uterine rupture, albeit rarely; still, misoprostol is not recommended for induction of labor after prior cesarean section due to this increased risk.

So (from a non-expert perspective) in some cases `treats` is appropriate (first c-section), but `contraindicated_for` the second c-section.

Since these edge labels aren't used for training (iirc, you remove _all_ edges between existing `drugs` and `phenotypic_features`), nor for testing (aren't included in the random forest model), how do you think this will impact the training of GraphSage?
