### ISSUE TITLE
Use kg2canonicalized to Expand (when use_synonyms=true)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1043]
I played around a bit to investigate how much of a speed improvement this might provide, and it seems notable:

- for a pretty average 2-hop query ([here](https://github.com/RTXteam/RTX/blob/ee66f65e6e010d783c3d2b9c40f5f1a4dd5c62e1/code/ARAX/test/test_ARAX_expand.py#L508-L519)), we're looking at 3 seconds vs. 16 seconds 
- for a more difficult 2-hop query ([here](https://github.com/RTXteam/RTX/blob/ee66f65e6e010d783c3d2b9c40f5f1a4dd5c62e1/code/ARAX/test/test_ARAX_expand.py#L181-L192), but modified to use KG2/synonyms), we're looking at 40 seconds vs. 160 seconds

I expect that #1037 will slow things down even more, in which case, without using kg2canonicalized, we may be entering some rather prohibitively slow territory for some queries.

So this seems worthwhile to me, especially given I expect it to be a relatively easy change to the code.

I plan to continue using the regular KG2 for queries that _don't_ want to use synonyms.

**Comment by amykglen** [comment]
ok, so this is implemented, but I was wrong about the speed improvements. it _is_ much faster to use KG2C if queries only consider nodes' `preferred_type`, but if they instead consider the nodes' `types` property (which makes more sense and is the way I ended up doing it), it's not faster - in fact it's a bit slower.

**but**, using KG2C results in something like 2-3x as many answers vs. using the regular KG2 via the old method (with synonyms), for a reason similar to the phenomenon that caused #897. to explain: imagine a query like `(DOID:14330)-->(protein)`. the old `expand` that used the regular KG2 would've returned any protein nodes attached to DOID:14330/its synonyms (and then canonicalized them). but imagine that a gene is attached to DOID:14330, and that gene has a synonym node that's a protein, but that protein synonym is not itself attached to DOID:14330/any of its synonyms. then neither that gene nor any of its synonyms would be returned in the results. it would, however, if the query were run in KG2C.

changes are currently in the `issue1043` branch, though I plan to roll them out to `master` fairly soon, after some more testing.

**Comment by amykglen** [comment]
also worth noting: I experimented with representing a node's `types` as edges/nodes in KG2C (i.e., I added edges like `(DOID:14330)-[:has_type]->(biolink:Disease)`) to see if it helped with speed vs. querying the `types` property (e.g., `where "disease" in n.types`). since you can't create an index on an array field, that is [apparently what neo4j recommends](https://community.neo4j.com/t/multi-valued-field-indexing/3873) to represent such data, but I wasn't seeing any performance improvements (was even running a tiny bit slower), so I ditched that.

**Comment by amykglen** [comment]
alright, this has been merged into `master` - just need to test after it's rolled out to production.

**Comment by edeutsch** [comment]
latest `master` is in /test

**Comment by amykglen** [comment]
this looks good on `/test`, with the exception of the sub-issue reported (and fixed) in #897 - will test again the next time `master` is rolled out.

**Comment by saramsey** [comment]
Nice!
