### ISSUE TITLE
Losartan is being synonymized with erythropoietin

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1044]
Breaking this out from #994, where it was reported that in kg2canonicalized, CHEMBL.COMPOUND:CHEMBL191 (losartan) has a strange list of `types`:
```
[
   "named_thing",
   "procedure",
   "drug",
   "chemical_substance",
   "genomic_entity",
   "gene",
   "protein",
   "disease",
   "phenotypic_feature",
   "molecular_entity",
   "metabolite"
]
```
in particular, it seems wrong that it has both drug/chemical_substance and disease/phenotypic_feature types.

looking up this node's `equivalent_curies` in kg2-3-1, I get:
```
match (n) where n.id in ["UMLS:C0126174", "ATC:C09CA01", "UMLS:C0014822", "ATC:B03XA01", "CPT:82668", "UMLS:C4256163", "UMLS:C4256161", "UMLS:C4256162", "DRUGBANK:DB00016", "UMLS:C4255969", "DRUGBANK:DB00678", "UMLS:C1366564", "HGNC:3415", "UMLS:C1414438", "HGNC:3423", "LOINC:LP171619-2", "LOINC:MTHU004935", "LOINC:LP15554-6", "MESH:D004921", "UMLS:C2976467", "UMLS:C0165616", "UMLS:C0700492", "UMLS:C0700620", "MESH:D019808", "MESH:D047209", "NCIT:C66869", "NCIT:C20429", "NCIT:C29165", "NDDF:004991", "NDDF:004992", "NDFRT:N0000148401", "NDFRT:N0000148405", "UMLS:C4693552", "OMIM:131399", "UMLS:C4693956", "OMIM:133170", "RXNORM:203160", "RXNORM:52175", "SNOMED:373567002", "SNOMED:108582002", "SNOMED:83042003", "PR:000007141", "VANDF:4020920", "VANDF:4020913", "PR:000007152", "EFO:0003233", "CHEBI:6541", "PR:P11678", "CHEBI:81579", "ORPHANET:470286", "PR:P01588", "UniProtKB:P01588", "UniProtKB:P11678", "ENSEMBL:ENSG00000130427", "ENSEMBL:ENSG00000121053", "CHEMBL.COMPOUND:CHEMBL995", "CHEMBL.COMPOUND:CHEMBL191", "CHEMBL.TARGET:CHEMBL2438", "CHEMBL.TARGET:CHEMBL5837", "NCBIGene:2056", "NCBIGene:8288", "ttd.target:DAP000523", "GTPI:4921", "PathWhiz.ProteinComplex:7956", "PathWhiz.ProteinComplex:12664", "PathWhiz.ProteinComplex:12228", "PathWhiz.Compound:9156", "PathWhiz.ProteinComplex:12446", "HMDB:HMDB0014816", "KEGG:C07072", "KEGG:C18200"] return n.id, n.name, n.category_label order by n.category_label
```

n.id | n.name | n.category_label
-- | -- | --
"CHEBI:81579" | "Erythropoietin" | "chemical_substance"
"EFO:0003233" | "erythropoietin" | "chemical_substance"
"CHEMBL.COMPOUND:CHEMBL995" | "LOSARTAN POTASSIUM" | "chemical_substance"
"CHEMBL.COMPOUND:CHEMBL191" | "LOSARTAN" | "chemical_substance"
"ttd.target:DAP000523" | "LOSARTAN" | "chemical_substance"
"GTPI:4921" | "ERYTHROPOIETIN" | "chemical_substance"
"PathWhiz.Compound:9156" | "Losartan" | "chemical_substance"
"UMLS:C4693552" | "Erythropoietin" | "disease"
"DRUGBANK:DB00016" | "Erythropoietin" | "drug"
"DRUGBANK:DB00678" | "Losartan" | "drug"
"NCIT:C66869" | "Losartan" | "drug"
"NCIT:C29165" | "Losartan Potassium" | "drug"
"RXNORM:203160" | "Losartan Potassium" | "drug"
"RXNORM:52175" | "Losartan" | "drug"
"SNOMED:373567002" | "Losartan" | "drug"
"SNOMED:108582002" | "Losartan potassium" | "drug"
"SNOMED:83042003" | "Erythropoietin" | "drug"
"CHEBI:6541" | "losartan" | "drug"
"HGNC:3415" | "erythropoietin" | "gene"
"HGNC:3423" | "eosinophil peroxidase" | "gene"
"ORPHANET:470286" | "erythropoietin" | "gene"
"ENSEMBL:ENSG00000130427" | "erythropoietin [Source:HGNC Symbol;Acc:HGNC:3415]" | "gene"
"ENSEMBL:ENSG00000121053" | "eosinophil peroxidase [Source:HGNC Symbol;Acc:HGNC:3423]" | "gene"
"NCBIGene:2056" | "erythropoietin" | "gene"
"NCBIGene:8288" | "eosinophil peroxidase" | "gene"
"UMLS:C1366564" | "Erythropoietin" | "genomic_entity"
"UMLS:C1414438" | "Eosinophil peroxidase" | "genomic_entity"
"KEGG:C07072" | "Losartan" | "metabolite"
"HMDB:HMDB0014816" | "Losartan" | "metabolite"
"KEGG:C18200" | "Erythropoietin" | "metabolite"
"PathWhiz.ProteinComplex:7956" | "Erythropoietin" | "molecular_entity"
"PathWhiz.ProteinComplex:12664" | "Erythropoietin" | "molecular_entity"
"PathWhiz.ProteinComplex:12228" | "Erythropoietin" | "molecular_entity"
"PathWhiz.ProteinComplex:12446" | "Erythropoietin" | "molecular_entity"
"UMLS:C0126174" | "Losartan" | "named_thing"
"ATC:C09CA01" | "losartan" | "named_thing"
"UMLS:C0014822" | "Erythropoietin" | "named_thing"
"ATC:B03XA01" | "erythropoietin" | "named_thing"
"UMLS:C4256163" | "Erythropoietin" | "named_thing"
"UMLS:C4256161" | "Erythropoietin" | "named_thing"
"UMLS:C4256162" | "Erythropoietin" | "named_thing"
"UMLS:C4255969" | "Losartan" | "named_thing"
"MESH:D004921" | "Erythropoietin" | "named_thing"
"UMLS:C2976467" | "Erythropoietin" | "named_thing"
"UMLS:C0165616" | "Losartan" | "named_thing"
"UMLS:C0700492" | "Losartan potassium" | "named_thing"
"UMLS:C0700620" | "Losartan" | "named_thing"
"MESH:D019808" | "Losartan" | "named_thing"
"MESH:D047209" | "Eosinophil Peroxidase" | "named_thing"
"NDDF:004991" | "losartan" | "named_thing"
"NDDF:004992" | "losartan potassium" | "named_thing"
"NDFRT:N0000148401" | "Losartan" | "named_thing"
"NDFRT:N0000148405" | "Losartan potassium" | "named_thing"
"UMLS:C4693956" | "Erythropoietin" | "named_thing"
"VANDF:4020920" | "Losartan potassium" | "named_thing"
"VANDF:4020913" | "Losartan" | "named_thing"
"OMIM:131399" | "Eosinophil peroxidase" | "phenotypic_feature"
"OMIM:133170" | "Erythropoietin" | "phenotypic_feature"
"CPT:82668" | "Erythropoietin" | "procedure"
"LOINC:LP171619-2" | "Losartan" | "procedure"
"LOINC:MTHU004935" | "Erythropoietin" | "procedure"
"LOINC:LP15554-6" | "Erythropoietin" | "procedure"
"NCIT:C20429" | "Erythropoietin" | "protein"
"PR:000007141" | "erythropoietin" | "protein"
"PR:000007152" | "eosinophil peroxidase" | "protein"
"PR:P11678" | "eosinophil peroxidase (human)" | "protein"
"PR:P01588" | "erythropoietin (human)" | "protein"
"UniProtKB:P01588" | "EPO" | "protein"
"UniProtKB:P11678" | "EPO" | "protein"
"CHEMBL.TARGET:CHEMBL5837" | "Erythropoietin" | "protein"
"CHEMBL.TARGET:CHEMBL2438" | "Eosinophil peroxidase" | "protein"

so it appears that for some reason, "losartan" is being merged with "erythropoietin", which is in turn for some reason labeled a "disease" via UMLS and a "phenotypic_feature" via OMIM in the regular KG2 (I created #1045 for the latter issue).

as for why losartan is being merged with erythropoietin, I have no idea - all of the merging of nodes in kg2canonicalized is done through the `NodeSynonymizer`... do you have any idea @edeutsch?

these are the synonyms I'm seeing for this node according to the synonymizer:

```
python3 node_synonymizer.py --lookup=losartan --kg_name=KG2
```
```
 ...
    "synonyms": [
      {
        "label": "Losartan",
        "source": "KG2"
      },
      {
        "label": "Erythropoietin",
        "source": "KG2"
      },
      {
        "label": "EPO",
        "source": "SRI"
      },
      {
        "label": "Eosinophil peroxidase",
        "source": "KG2"
      },
      {
        "label": "EPX",
        "source": "SRI"
      },
      {
        "label": "Losartan potassium",
        "source": "KG2"
      },
      {
        "label": "P11678",
        "source": "KG2"
      },
      {
        "label": "P01588",
        "source": "KG2"
      }
    ],
```

**Comment by edeutsch** [comment]
This would seem to be an error in the NodeSynonymizer that I will investigate.
Something is linking Losartan and Erythropoietin. Is it my error or are the underlying data showing that?
I will try to figure this out.

**Comment by amykglen** [comment]
sounds good - I'm not sure what the 'underlying data' would be in this case? I was under the impression that the `NodeSynonymizer` doesn't yet utilize `same_as` relationships or the `synonym` field from KG2, so I'm not sure where the info would be coming from, other than whatever logic you have in place to match names and whatever you get from the SRI?

the SRI node normalizer response for CHEMBL.COMPOUND:CHEMBL191 appears to be normal, fyi:
```
{
  "CHEMBL.COMPOUND:CHEMBL191": {
    "id": {
      "identifier": "CHEBI:6541",
      "label": "losartan"
    },
    "equivalent_identifiers": [
      {
        "identifier": "CHEBI:6541",
        "label": "losartan"
      },
      {
        "identifier": "CHEMBL.COMPOUND:CHEMBL191",
        "label": "LOSARTAN"
      },
      {
        "identifier": "DRUGBANK:DB00678"
      },
      {
        "identifier": "PUBCHEM.COMPOUND:3961"
      },
      {
        "identifier": "MESH:D019808",
        "label": "Losartan"
      },
      {
        "identifier": "HMDB:HMDB0014816"
      },
      {
        "identifier": "INCHIKEY:JVUNQIZFNNFUQK-ONRMSGCCSA-N"
      },
      {
        "identifier": "UNII:JMS50MPO89"
      },
      {
        "identifier": "KEGG:C07072",
        "label": "Losartan"
      },
      {
        "identifier": "gtpo:590"
      },
      {
        "identifier": "gtpo:3941"
      }
    ],
    "type": [
      "chemical_substance",
      "molecular_entity",
      "biological_entity",
      "named_thing"
    ]
  }
}
```
and those nodes appear to be appropriately named losartan in KG2:

```
match (n) where n.id in ["CHEBI:6541", "CHEMBL.COMPOUND:CHEMBL191", "DRUGBANK:DB00678", "PUBCHEM.COMPOUND:3961", "MESH:D019808", "HMDB:HMDB0014816", "INCHIKEY:JVUNQIZFNNFUQK-ONRMSGCCSA-N", "UNII:JMS50MPO89", "KEGG:C07072", "gtpo:590", "gtpo:3941"] return n
```
![Screen Shot 2020-08-31 at 3 55 38 PM](https://user-images.githubusercontent.com/49423686/91776708-c9bc1f80-eba2-11ea-975b-1a76473a29e7.png)

**Comment by edeutsch** [comment]
After investigating further here, it appears to be the SRI Node Normalizer for CHEML995 that is causing the merge:
https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=CHEMBL.COMPOUND:CHEMBL995
```
{
  "CHEMBL.COMPOUND:CHEMBL995": {
    "equivalent_identifiers": [
      {
        "identifier": "CHEMBL.COMPOUND:CHEMBL995",
        "label": "LOSARTAN POTASSIUM"
      },
      {
        "identifier": "PUBCHEM.COMPOUND:11476710"
      },
      {
        "identifier": "PUBCHEM.COMPOUND:11751549"
      },
      {
        "identifier": "MESH:D004921",
        "label": "Erythropoietin"
      },
      {
        "identifier": "INCHIKEY:UGLJMTIHLXTWOP-UHFFFAOYSA-N"
      },
      {
        "identifier": "UNII:3ST302B24A"
      }
    ],
    "id": {
      "identifier": "CHEMBL.COMPOUND:CHEMBL995",
      "label": "LOSARTAN POTASSIUM"
    },
    "type": [
      "biolink:ChemicalSubstance",
      "biolink:Entity",
      "biolink:NamedThing",
      "biolink:BiologicalEntity",
      "biolink:MolecularEntity"
    ]
  }
}
```

Notice the third equivalent identifier.

Shall I report this as an error, or is there a possibility that it is not an error?

**Comment by edeutsch** [comment]
Reported.
https://github.com/TranslatorSRI/NodeNormalization/issues/38
Traced to Pubchem.
Solution in progress.

**Comment by amykglen** [comment]
closing as this was fixed with KG2.5.2 synonymizer
