### ISSUE TITLE
fastNGD 'miss' example: Global brain atrophy

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1047]
creating this issue to share an example of a concept the fastNGD system misses but eUtils doesn't, and discuss how we might achieve it ourselves/if it's worth it. (@edeutsch)

this example is OMIM:MTHU052931: 'Global brain atrophy'.
```
  - 2020-08-31 17:43:48.615517 DEBUG: Had to use eUtils to compute NGD between Parkinson disease (MONDO:0005180) and Global brain atrophy (OMIM:MTHU052931). Value is: 0.5416331752918857
```

n.id | n.name | n.equivalent_curies
-- | -- | --
"OMIM:MTHU052931" | "Global brain atrophy" | ["UMLS:C0241816", "HP:0002283", "OMIM:MTHU052931", "OMIM:MTHU000288"]

I don't think this concept is mappable to a single MESH term (there are MESH terms for "Brain" and "Atrophy", but not their intersection), and no publications are given in KG2 for any nodes in this synonym group (or edges connected to them), so it's not surprising fastNGD isn't aware of any PMIDs for this concept.

as for how eUtils returns results for this, I'm not 100% sure as I'm not super familiar with the old NGD code, but I think this kind of call is done to get a list of PMIDs for the term:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=Global%20brain%20atrophy

and interestingly, eUtils appears to convert that input term of "Global brain atrophy" into a query that looks like (according to the above page):

`
<QueryTranslation>("Glob Impacts"[Journal] OR "global"[All Fields]) AND ("brain"[MeSH Terms] OR "brain"[All Fields]) AND ("atrophy"[MeSH Terms] OR "atrophy"[All Fields])</QueryTranslation>
`

a couple ideas off the top of my head as to how we could 'catch' this concept with fastNGD:
1. maybe it would be possible to somehow combine MESH terms in this case, kind of like eUtils does? (i.e., take the intersection of the PMID sets for the "Brain" and "Atrophy" MESH terms.) but "Global" isn't a MESH term... we would lose accuracy here...
2. somehow process/search article titles/abstracts in our scraping of PubMed - I can see that many articles (~125) refer to "Global brain atrophy" in their title and/or abstract: https://pubmed.ncbi.nlm.nih.gov/?term=%22global+brain+atrophy%22%5BTitle%2FAbstract%5D&sort= but not sure if we want to delve into that world!

I'm definitely not sure how the cost/benefit ratio will play out here... i.e., when we're seeing fastNGD utilization rates at 95-100%, is it worth a big effort to get that final last bit?

**Comment by dkoslicki** [comment]
My $0.02 is: since we're getting 95-100% utilization, it might _not_ be worth a big effort to get the remaining ~5%.

**Comment by finnagin** [comment]
Closing since from the comments it looks like we decided this was not worth it. Feel free to reopen if we still want to look into this.
