### ISSUE TITLE
NodeSynonymizer version issues (not due to KG2 version)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1049]
so I think we have a problem where there are multiple `node_synonymizer.sqlite`s out there that are all built from the same production KG2 (kg2-1-0, in `kg2endpoint2`), yet are different.

I think this happened because the `node_synonymizer.py` build code may have changed somewhere along the line - so I believe that the `node_synonymizer.sqlite` on `/test`, for example, was built quite a while ago (several months, I think?). but the `node_synonymizer.sqlite` used to build the fastNGD database, for example, was built more recently (within the last few weeks). and I'm pretty sure that the path given in the [Dev info wiki](https://github.com/RTXteam/RTX/wiki/Dev-info#2-set-up-nodesynonymizer-replaces-kgnodeindex) for downloading the synonymizer gives you yet another version (from `/devED`).

this leads to problems because the NGD database, for example, only contains entries for the `preferred_curie` for a synonym group. but the curie deemed 'preferred' for a given synonym group can be different in these different node synonymizer versions. thus, the fastNGD utilization rate is more like 80-90% on `/test` vs. 95%+ for me locally when I'm using the same synonymizer that was used to build the fastNGD database.

this is causing issues in other places as well, such as in using kg2canonicalized to `expand` (#1043).

hopefully issue #1029 will resolve this, but it seems it may be worthwhile to sync these up in the shorter term. could we rebuild the NodeSynonymizers on `/test`, `/beta`, and production? or should we just make sure that `/test`, `/beta`, and production are all using the same version (even if it's old) and provide the path to it so everyone can download that version?

**Comment by edeutsch** [comment]
Hi everyone, esp @amykglen : I have built a fresh version of the NodeSynonymizer database and copied it around to /test, /beta, /devED, and production. I have also rolled out the latest code in `master` to all the same locations. So everything is as up-to-date as it can be. Please let us know if this resolves the issues with out-of-date NodeSynonymizer databases.

**Comment by amykglen** [comment]
awesome - things are looking good now from my end! thanks!
