### ISSUE TITLE
Best way to decorate drug nodes with FDA approval status?

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1050]
[This](https://github.com/RTXteam/RTX/blob/master/code/kg2/misc-tools/drugbank_get_approved_drugs_and_ids.py) script has functions that extract information from drugbank.xml that could pretty easily be added to the drugbank ETL.

Additional useful information to fit into drug nodes:
- FDA approval groups (approved, withdrawn, investigational, etc)
- External ids (maybe this would be useful in the Node Synonimizer?)

What's the best way to add this information to the drugbank nodes in KG2?

**Comment by saramsey** [comment]
thank you for logging this issue

**Comment by saramsey** [comment]
Maybe add this code to `ont-load-inventory.yaml`:

```
-
  url: http://purl.obolibrary.org/obo/mi.owl
  file: mi.owl
  download: true
  title: Molecular Interactions Controlled Vocabulary
```

**Comment by kvarforl** [comment]
@saramsey  Slightly tangential question while I work on this: is there a reason that we include Drugbank both as a UMLS source and an independent ETL script?

**Comment by kvarforl** [comment]
The above commit adds MI to `ont-load-inventory.yaml` as suggested by Steve. Then, it adds "DRUGBANK:group" relations between each drugbank node and the appropriate [MI node](https://www.ebi.ac.uk/ols/ontologies/mi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMI_2040&viewMode=All&siblings=true). In `predicate-remap.yaml`, I added an entry to map `DRUGBANK:group` to `biolink:has_attribute`.

I think the only thing left to do is to add a more specific category to `curies-to-categories.yaml` for MI nodes. I'll happily take suggestions as to what that should be: otherwise, I'll dig through the biolink model and make my best guess :)

**Comment by saramsey** [comment]
> @saramsey Slightly tangential question while I work on this: is there a reason that we include Drugbank both as a UMLS source and an independent ETL script?

Yes, I think we include it as a UMLS source so that we can get cross-mappings between DrugBank and UMLS concept IDs (CUIs).

**Comment by saramsey** [comment]
> I think the only thing left to do is to add a more specific category to `curies-to-categories.yaml` for MI nodes. I'll happily take suggestions as to what that should be: otherwise, I'll dig through the biolink model and make my best guess :)

How about `biolink:attribute`?

**Comment by kvarforl** [comment]
@saramsey should I add this category mapping for all MI nodes, or just the drug type ones that I specifically used to annotate status?

**Comment by kvarforl** [comment]
Looks good in kg2.5.2:
```
match p=(n)-[e]-(m:`biolink:ChemicalSubstance`) where n.id in ["MI:2099", "MI:2100", "MI:2150", "MI:2148", "MI:2102", "MI:2149"] return n.id, n.name, count(m)
```
n.id | n.name | count(m)
-- | -- | --
"MI:2148" | "investigational drug" | 3762
"MI:2102" | "nutraceutical drug" | 97
"MI:2099" | "fda approved drug" | 3411
"MI:2100" | "experimental drug" | 6189
"MI:2150" | "illicit drug" | 204
"MI:2149" | "withdrawn drug" | 238
