### ISSUE TITLE
frequent message in logs

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1052]
I'm frequently seeing this message in the ARAX logs:

Can't convert {curie} to preferred curie in get_concept_ids

I couldn't trace where it came from easily. Maybe in some COHD code somewhere?
Not a big deal, but maybe could be quieted if not a problem, or otherwise the string needs an "f" in front so that interpolation happens correctly.

**Comment by finnagin** [comment]
ran a few queries and I don't see this message currently. Maybe fixed sometime since this issue was posted? Ok to close @edeutsch ?

**Comment by edeutsch** [comment]
I don't know the status, but if you don't see it in the logs anymore, let's assume it's fixed. closing.
