### ISSUE TITLE
Snakemake-build kg2-tsv.tar file has wrong directory built-in

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1053]
The `kg2-tsv.tar.gz` tarball produced by the Snakemake build system seems to be unpacking into a relative path `home/ubuntu/kg2-build/TSV` relative to the current working directory, which is not what is needed.

<img width="726" alt="Screen Shot 2020-09-04 at 12 48 37 PM" src="https://user-images.githubusercontent.com/5562107/92279870-10648f00-eead-11ea-91a8-d402e6bb3b9c.png">

the net effect is that the `tsv-to-neo4j.sh` script then puts the TSV files into `/home/ubuntu/kg2-build/TSV/home/ubuntu/kg2-build/TSV`.

**Comment by saramsey** [comment]
On `kg2endpoint.rtx.ai`, I manually moved the TSV files into `/home/ubuntu/kg2-build/TSV` and resumed the Neo4j load using a (modified) `tsv-to-neo4j.sh` script

**Comment by saramsey** [comment]
I note that in L414 of `build-kg2.sh`, we have:
```
tar -C ${kg2_tsv_dir} -czvf ${kg2_tsv_tarball} nodes.tsv nodes_header.tsv edges.tsv edges_header.tsv
```
but in L19 of `Snakefile-finish`, we have:
```
shell("tar -czvf " + config['KG2_TSV_TARBALL'] + " " + config['KG2_TSV_DIR'])
```
These appear to not be the same; I am 99% confident this is the source of the problem.

**Comment by ericawood** [comment]
Hi @saramsey,
Commit cb05e23 should fix this problem and can be tested in the next build. That commit also uncommented the S3 copy lines from Snakefile-finish (and updated them to include the correct buckets based on `build-kg2.sh`). It doesn't have all of the S3 copy lines. Would you like me to add them all in (it doesn't copy the error files, log files, and config files currently - L434-L458)? (They are sort of hard to test until we do a build - full, partial, or test).

**Comment by saramsey** [comment]
> It doesn't have all of the S3 copy lines. Would you like me to add them all in (it doesn't copy the error files, log files, and config files currently - L434-L458)? 

Sure, that sounds good.

**Comment by saramsey** [comment]
FYI, I've fixed the `kg2-tsv.tar.gz` file in `s3://rtx-kg2/` so that it has (internally) the correct path

<img width="993" alt="Screen Shot 2020-09-09 at 10 56 23 AM" src="https://user-images.githubusercontent.com/5562107/92635734-30b89300-f28b-11ea-8a3b-6a2ebc193170.png">
