### ISSUE TITLE
mediKanren CSV File Generation Runs Out of Memory Before It Completes

### ISSUE THREAD

**Issue by ericawood** [RTXteam/RTX#1056]
Using this to document progress. Reported by @finnagin

**Comment by kvarforl** [comment]
Adding a note here to mention that this is still an issue with KG2.3.5: 
```
 [2020-11-29 08:40:40,022][progress_sink.py][                _inc] INFO: EDGEs added: 43500000
./download-graph.sh: line 7:  2920 Killed                  python3.7 kgx/neo4j_download.py
```

**Comment by saramsey** [comment]
If this is the Linux OOM killer, shouldn't we just use a bigger EC2 instance?

**Comment by kvarforl** [comment]
Yes i think so!
I'm going to see if I can get by without using the [neo4j / KGX](https://github.com/RTXteam/RTX/tree/master/code/kg2/mediKanren#downloading-graph-csvs-from-neo4j-using-kgx) method for the medikanren export of KG2.5.1, so it's not urgent, but I will eventually need to create a bigger instance to be able to generate kgx files.

My thinking is to wait for the KGE stuff to get sorted out so we can provide the latest version of our graph in KGX format, whenever the group is ready for it. In the meantime, I think it make the most sense to avoid it if possible! Let me know if your thoughts differ :)

**Comment by saramsey** [comment]
Yes, I thought @finnagin (or someone? maybe you?) had it working without KGX, previously. I totally agree-- there should be no need to round-trip to Neo4j in order to get a mediKanren export.

**Comment by saramsey** [comment]
Agree-- I prefer not to use neo4j/KGX to get our mediKanren export. @kvarforl can you please update the [RTX/code/kg2/mediKanren/README.md](https://github.com/RTXteam/RTX/blob/master/code/kg2/mediKanren/README.md) file to indicate the memory usage required to run this workflow?

**Comment by kvarforl** [comment]
done!
