### ISSUE TITLE
Should we rebuild both COHD database and predict-drug-treats-disease database based on canonicalized kg2?

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1061]
Since we're planning to finally roll out the new KG2 (KG2.3.4) to production, we need to rebuild any databases that are dependent on KG2 off of the new KG2 version. For the COHD database and predict-drug-treats-disease database, I'm wondering if we just need to rebuild them based on the canonicalized kg2 rather than the new whole KG2. 

The benefit of rebuilding the database based on the canonicalized kg2 is that it might need to take much shorter time to rebuild the databases and do the pre-prediction. 

For the COHD database, the most time-consuming part of rebuilding the database is to map the curie id to OMOP concepts which needs to call OMOP API. It seems like the NodeSynonymizer can't map all the nodes in the 'old' KG2 to the nodes in the new version because some curies from the 'old' KG2 with the prefix `CUI:` is now using the prefix `UMLS:`. So we might need to redo the mapping between the curies and OMOP concepts.

For the predict-drug-treats-disease database, it seems like we need to do the pre-predictions between all combinations of drugs and disease for the issues #973 and #1059. So if we use the canonicalized kg2, it might be faster.

**Comment by saramsey** [comment]
Tagging @amykglen to get her thoughts on this

**Comment by saramsey** [comment]
I don't know enough to really weigh in here, but the idea of achieving database build (time) efficiencies by using KG2c certainly sounds appealing. But I confess I don't fully understand the potential trade-offs here. I'll defer to Amy, Chunyu, and Eric.

**Comment by amykglen** [comment]
I agree it sounds appealing. seems to make good sense to me!
