### ISSUE TITLE
Feedback for https://github.com/RTXteam/RTX/blob/master/code/kg2/predicate-remap.yaml

### ISSUE THREAD

**Issue by RichardBruskiewich** [RTXteam/RTX#1062]
While curating a merge of the predicate-remap into the biolink-model.yaml, a few observations have been made and a few possible revisions to the mappings:

1. Several of the 'invert' mappings do have potential exact mappings (email to S. Ramsey has highlighted a few of these); however, there is a new active [Biolink Model issue #440](https://github.com/biolink/biolink-model/issues/440) discussing how inverse mappings should best be handled in the future.

2. Some of the 'related_to' mappings could be converted to new distinct biolink terms (e.g. see [Biolink Model issue 438](https://github.com/biolink/biolink-model/issues/438) proposing the addition of a `biolink:realizes` term as an example).  Another example is the addition of a  `biolink:develops_from` predicate, which is actually expected by some other part of the existing model as a *slot_usage..subproperty_of* (but was not yet curated into the Biolink model file) but, now added, could now have the *BTO:develops_from* and *DDANAT:develops_from` terms as part of its _exact_mappings_.

3. I may (will?) edit this issue to enumerate additional examples of possible mappings revisions here below, in this issue, as I encounter them during the next few days of RTX predicate review.  Stay tuned!

*  CHEBI:is_enantiomer_of and CHEBI:is_tautomer_of may eventually be mapped onto proposed [more precise structural chemistry relationship predicates](https://github.com/biolink/biolink-model/issues/430)

**Comment by saramsey** [comment]
Thank you, Richard!

**Comment by saramsey** [comment]
see additional information in #1063

**Comment by saramsey** [comment]
From Richard B.:

> Some of the RTX mappings don't appear to be edge_label slot predicates (i.e. not mapped in the 'related_to' hierarchy). They are either mapped to node or association properties. Since I'm not sure what to do here, I'll add them in "as is" but I sense that this is a bit weird and may have unexpected consequences (not the least of which that they may be invisible to the edge normalizer tool). I'm putting some inline comments to tag them...

**Comment by saramsey** [comment]
My reply to Richard B.:
> Hi Richard, thank you for tagging these. We can look into whether we can change them to "related to", in the `predicate-remap.yaml` file.  Cheers, Steve

**Comment by saramsey** [comment]
From Richard B.:

> Maybe you can simply wait until I get all the RTX mappings into the model  then we can take a closer look.
