### ISSUE TITLE
Should node ids have commas in them?

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1065]
Not sure if this is a bug or not but noticed these while generating the mediKanren indexes. If you run the following cypher in kg2
```
match (n) where n.id =~ '.*,.*' return n.id, n.name
```
you will get the following results:

n.id | n.name
-- | --
"CHEMBL.MECHANISM:1,3-beta-glucan_synthase_inhibitor" | "1,3-beta-glucan synthase inhibitor"
"CHEMBL.MECHANISM:3',5'-cyclic_phosphodiesterase_inhibitor" | "3',5'-cyclic phosphodiesterase inhibitor"
"CHEMBL.MECHANISM:dna_topoisomerase_i,_mitochondrial_inhibitor" | "DNA topoisomerase I, mitochondrial inhibitor"
"CHEMBL.MECHANISM:carbamoyl-phosphate_synthase_[ammonia],_mitochondrial_positive_allosteric_modulator" | "Carbamoyl-phosphate synthase [ammonia], mitochondrial positive allosteric modulator"
"CHEMBL.MECHANISM:parp_1,_2_and_3_inhibitor" | "PARP 1, 2 and 3 inhibitor"
"CHEMBL.MECHANISM:c-jun_n-terminal_kinase,_jnk_inhibitor" | "c-Jun N-terminal kinase, JNK inhibitor"
"CHEMBL.MECHANISM:potassium_channel,_inwardly_rectifying,_subfamily_j,_member_11_opener" | "Potassium channel, inwardly rectifying, subfamily J, member 11 opener"
"CHEMBL.MECHANISM:potassium_channel,_inwardly_rectifying,_subfamily_j,_member_8_opener" | "Potassium channel, inwardly rectifying, subfamily J, member 8 opener"
"CHEMBL.MECHANISM:endothelin_receptor,_et-a/et-b_antagonist" | "Endothelin receptor, ET-A/ET-B antagonist"
"CHEMBL.MECHANISM:amylin_receptor_amy1,_calcr/ramp1_agonist" | "Amylin receptor AMY1, CALCR/RAMP1 agonist"
"CHEMBL.MECHANISM:sulfonylurea_receptor_2,_kir6.2_opener" | "Sulfonylurea receptor 2, Kir6.2 opener"
"CHEMBL.MECHANISM:sulfonylurea_receptor_1,_kir6.2_blocker" | "Sulfonylurea receptor 1, Kir6.2 blocker"
"CHEMBL.MECHANISM:amiloride-sensitive_sodium_channel,_enac_blocker" | "Amiloride-sensitive sodium channel, ENaC blocker"
"CHEMBL.MECHANISM:hepatitis_c_virus_serine_protease,_ns3/ns4a_inhibitor" | "Hepatitis C virus serine protease, NS3/NS4A inhibitor"
"CHEMBL.MECHANISM:voltage-gated_potassium_channel,_kqt;_kcnq2(kv7.2)/kcnq3(kv7.3)_activator" | "Voltage-gated potassium channel, KQT; KCNQ2(Kv7.2)/KCNQ3(Kv7.3) activator"
"CHEMBL.MECHANISM:hla_class_ii_histocompatibility_antigen,_drb1-10_beta_chain_other" | "HLA class II histocompatibility antigen, DRB1-10 beta chain other"
"CHEMBL.MECHANISM:hla_class_ii_histocompatibility_antigen,_drb1-15_beta_chain_modulator" | "HLA class II histocompatibility antigen, DRB1-15 beta chain modulator"
"CHEMBL.MECHANISM:indoleamine_2,3-dioxygenase_inhibitor" | "Indoleamine 2,3-dioxygenase inhibitor"
"CHEMBL.MECHANISM:5,6-dihydroxyindole-2-carboxylic_acid_oxidase_other" | "5,6-dihydroxyindole-2-carboxylic acid oxidase other"
"CHEMBL.MECHANISM:amine_oxidase,_copper_containing_inhibitor" | "Amine oxidase, copper containing inhibitor"
"CHEMBL.MECHANISM:carnitine_o-palmitoyltransferase_1,_muscle_isoform_inhibitor" | "Carnitine O-palmitoyltransferase 1, muscle isoform inhibitor"
"CHEMBL.MECHANISM:troponin,_cardiac_muscle_positive_modulator" | "Troponin, cardiac muscle positive modulator"
"CHEMBL.MECHANISM:isocitrate_dehydrogenase_[nadp],_mitochondrial_inhibitor" | "Isocitrate dehydrogenase [NADP], mitochondrial inhibitor"

As you can see these ids are natural language names. Is this correct?

**Comment by saramsey** [comment]
Yes, those node IDs are correct. Nothing in the Biolink specification prohibits commas in node IDs, as far as I know.

I assume the CSV format has a quoting mechanism for commas?

**Comment by finnagin** [comment]
Yes it does. It caused some issues when I first ran into them because I had assumed that ids couldn't have commas in them but I've added in a check to Erica's code to wrap ids in quotes. I just wasn't sure if they were a result of a bug or intentional. 

Closing this issue now.
