### ISSUE TITLE
What knowledge providers do we use to count the total number of nodes with certain type in fisher exact test?

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1067]
Hi @edeutsch , @amykglen and @dkoslicki, 

I have a question for you about what kp we should use to count the total number of nodes with certain type. In FET, when we need to calculate the p-value for an edge, we need to know the total number of nodes with the same type in the graph as the node in this edge. Previously, when we count the total number of nodes with certain type in graph, we use KG1 instead of KG2 because KG2 has many duplicates so its value is not correct. For this reason, I set KG1 as default to count the total number of nodes with certain type in FET although this edge was expanded from `KG2`. Is this still a problem for `KG2C`？

If `KG2C` covers all nodes in `KG1`, can we just use `KG2C` to count the total number of nodes with certain type in FET no matter where the edge comes from?

**Comment by amykglen** [comment]
yeah, good thinking - I'd think it would make sense to use KG2C to count this, since it resolves (or, at least largely resolves) the problem of duplicates in KG2. (the synonymization is likely not perfect but will only improve over time.)

**Comment by chunyuma** [comment]
Thanks @amykglen. If we plan to use `KG2C`, @edeutsch is it possible that we can add an option in `kgNodeIndex.get_total_entity_count`for `KG2C` in `kg2-arax-integration` branch?

**Comment by edeutsch** [comment]
NodeSynonymizer.get_total_entity_count (not KgNodeIndex, right?) already only reports the total number of *unique concepts*, NOT the total number of nodes. So, the answers for this method should be the same for both KG2 and KG2C

Does that seem right?

**Comment by chunyuma** [comment]
@edeutsch, I saw KgNodeIndex also has `get_total_entity_count`. Is that different from the `NodeSynonymizer.get_total_entity_count`? If it doesn't report the total number of nodes with a certain type in KG2C, is there a way that we can know the total number of nodes quickly in KG2C?

**Comment by edeutsch** [comment]
- kgNodeIndex.get_total_entity_count() is deprecated and should not be used anymore
- NodeSynonymizer.get_total_entity_count() is the intended replacement for this previous functionality.
- NodeSynonymizer.get_total_entity_count() reports the total number of unique concepts in KG2, NOT the total number of nodes.
- KG2C is just a coalescing of nodes in KG2 for all groups of unique concepts.
- So I would posit that KG2C has exactly the same number of unique concepts as KG2.
- It's just that KGC2 has *one* node per concept whereas KG2 has many nodes per concept.
- So I would argue that the NodeSynonymizer.get_total_entity_count() for KG2 is also valid for KG2C.

Does that all seem consistent with what you want and see?
I haven't done a test today, so it's possible that the actual behavior is different than what I describe above?

**Comment by chunyuma** [comment]
Awesome, thanks @edeutsch! Then `NodeSynonymizer.get_total_entity_count()` is what I need. I think I can close this issue.
