### ISSUE TITLE
leave out common boilerplate?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#107]
Hi @dkoslicki , I suggest you leave out the following in your response dumps. I suggest that these common values get filled in by the API/UI after fetching the important stuff from the reasoner:

{
  "context": "http://translator.ncats.io",
  "datetime": "2018-05-04 19:53:24",
  "id": "-1",
  "original_question_text": "ERIC Fill these in",
  "restated_question_text": "ERIC Fill these in",

Just leave them out completely and I'll fill them in.

Sound good?

**Comment by dkoslicki** [comment]
Done!
