### ISSUE TITLE
Interleukin-10 is being synonymized with rheumatoid arthritis

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1070]
so I noticed that in the `NodeSynonymizer` built from KG2.3.4 (available on arax.rtx.ai at `/data/orangeboard/databases/KG2.3.4/node_synonymizer.sqlite`), it appears that interleukin-10 and rheumatoid arthritis have been lumped together:

```
python node_synonymizer.py --lookup=UniProtKB:P22301 --kg_name=KG2
```
```
...
"nodes": [
      {
        "identifier": "UMLS:C0085295",
        "label": "Interleukin-10",
        "original_label": "Interleukin-10",
        "type": "molecular_entity"
      },
      {
        "identifier": "DRUGBANK:DB12880",
        "label": "Interleukin-10",
        "original_label": "Interleukin-10",
        "type": "drug"
      },
      {
        "identifier": "FMA:264825",
        "label": "Interleukin-10",
        "original_label": "Interleukin-10",
        "type": "anatomical_entity"
      },
      {
        "identifier": "UMLS:C1334098",
        "label": "Interleukin 10",
        "original_label": "Interleukin 10",
        "type": "genomic_entity"
      },
      {
        "identifier": "HGNC:5962",
        "label": "interleukin 10",
        "original_label": "interleukin 10",
        "type": "gene"
      },
      {
        "identifier": "UMLS:C0003873",
        "label": "Rheumatoid arthritis",
        "original_label": "Rheumatoid arthritis",
        "type": "disease"
      },
      {
        "identifier": "HP:0001370",
        "label": "Rheumatoid arthritis",
        "original_label": "Rheumatoid arthritis",
        "type": "phenotypic_feature"
      },
      {
        "identifier": "UMLS:C0409651",
        "label": "Seropositive rheumatoid arthritis",
        "original_label": "Seropositive rheumatoid arthritis",
        "type": "disease"
      },
      {
        "identifier": "ICD10:M05",
        "label": "Seropositive rheumatoid arthritis",
        "original_label": "Seropositive rheumatoid arthritis",
        "type": "disease"
      },
      {
        "identifier": "UMLS:C0409652",
        "label": "Seronegative rheumatoid arthritis",
        "original_label": "Seronegative rheumatoid arthritis",
        "type": "disease"
      },
     etc...
```

this doesn't seem desirable, so I did some investigation and discovered that one of the equivalent curies returned from the SRI node normalizer (which are incorporated into the `NodeSynonymizer` build process, as I understand it) for MONDO:0008383 (rheumatoid arthritis) is UMLS:C1736175, which is named 'Interleukin 10' in KG2.3.4:

![Screen Shot 2020-09-17 at 2 24 36 PM](https://user-images.githubusercontent.com/49423686/93529884-89260b00-f8f1-11ea-8116-25cb3bdbd845.png)

but this resource would suggest that perhaps that's the wrong name, and it should instead be named 'Progression of rheumatoid arthritis'?: https://ncim-stage.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C1736175. (not sure how good/current of a resource that is, but this page doesn't seem to have details for this node: http://linkedlifedata.com/resource/umls/id/C1736175.)

so I think maybe this node has the wrong name in KG2, and that's ultimately leading to the incorrect merging of these concepts in the synonymizer? (unconfirmed though.)

one last thing worth noting: it looks like this naming issue is also present in KG2-1-0, but because the curie for this node there is CUI:C1736175, I think it didn't cause a problem in the KG2-1-0 `NodeSynonymizer` since the SRI uses "UMLS" prefixes, and thus CUI:C1736175 wasn't recognized to be part of the 'rheumatoid arthritis' synonym group.

**Comment by saramsey** [comment]
I am investigating

**Comment by saramsey** [comment]
OK, I believe there are two concepts that get mapped to `UMLS:C1736175`; one of them is `OMIM:124092` ("Interleukin 10"), and the other is `MEDDRA:10066578` ("Progression of rheumatoid arthritis"). A quick check at the UMLS site shows that OMIM is in error; MEDDRA is correct:

<img width="912" alt="Screen Shot 2020-09-17 at 3 58 45 PM" src="https://user-images.githubusercontent.com/5562107/93536798-b75e1780-f8fe-11ea-95e8-3329a007d578.png">

I'm assuming that this is an isolated case of an incorrect UMLS cross-reference in OMIM; more digging is needed in order to verify that the problem is not systemic (I will leave this issue open for that reason).

**Comment by edeutsch** [comment]
Great, good sleuthing, thanks. And nice for me to know it was not a NodeSynonymizer bug.

**Comment by saramsey** [comment]
Can I close this out, folks? Or is there some countermeasure I need to implement?  One option would be to disallow genes from OMIM, but that is kind of drastic.

**Comment by saramsey** [comment]
ok, closing

**Comment by amykglen** [comment]
I think maybe we should leave this one open; I think an exception will need to be added for it to the NodeSynonymizer. otherwise interleukin-10 will continue to be synonymized with arthritis, which doesn't seem great. will adjust the issue tags though.

**Comment by saramsey** [comment]
Ah, sorry @amykglen.

**Comment by amykglen** [comment]
fixed with KG2.6.7.1c: 

IL-10: https://arax.ncats.io/?term=UniProtKB:P22301
Rheumatoid arthritis: https://arax.ncats.io/?term=UMLS:C0003873
