### ISSUE TITLE
Acetylcholinesterase is being synonymized with pain

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1071]
so this is a kind of funny instance of an incorrect merging of two concepts in the `NodeSynonymizer` (both the synonymizer built from KG2-3-4 and the one built from KG2-1-0):

```
python node_synonymizer.py --lookup=UniProtKB:P22303 --kg_name=KG2
```
```
"nodes": [
      {
        "identifier": "CPT:82013",
        "label": "Acetylcholinesterase",
        "original_label": "Acetylcholinesterase",
        "type": "procedure"
      },
      {
        "identifier": "UMLS:C1412122",
        "label": "Acetylcholinesterase",
        "original_label": "Acetylcholinesterase",
        "type": "genomic_entity"
      },
      {
        "identifier": "HGNC:108",
        "label": "acetylcholinesterase (Cartwright blood group)",
        "original_label": "acetylcholinesterase (Cartwright blood group)",
        "type": "gene"
      },
      {
        "identifier": "UMLS:C0030193",
        "label": "Pain",
        "original_label": "Pain",
        "type": "disease"
      },
      {
        "identifier": "HP:0012531",
        "label": "Pain",
        "original_label": "Pain",
        "type": "phenotypic_feature"
      },
      {
        "identifier": "UMLS:C0150055",
        "label": "Chronic pain",
        "original_label": "Chronic pain",
        "type": "disease"
      },
      {
        "identifier": "HP:0012532",
        "label": "Chronic pain",
        "original_label": "Chronic pain",
        "type": "phenotypic_feature"
      },
      {
        "identifier": "UMLS:C0278144",
        "label": "Dull pain",
        "original_label": "Dull pain",
        "type": "disease"
      },
      {
        "identifier": "HP:0025282",
        "label": "Dull",
        "original_label": "Dull",
        "type": "phenotypic_feature"
      },
      {
        "identifier": "ICD9:338.2",
        "label": "Chronic pain",
        "original_label": "Chronic pain",
        "type": "named_thing"
      },
      {
        "identifier": "ICD9:338-338.99",
        "label": "Pain",
        "original_label": "Pain",
        "type": "named_thing"
      },
      {
        "identifier": "UMLS:C1317590",
        "label": "Trigger point pain",
        "original_label": "Trigger point pain",
        "type": "physiological_process"
      },
      {
        "identifier": "LOINC:MTHU013382",
        "label": "Chronic pain",
        "original_label": "Chronic pain",
        "type": "procedure"
      },
      {
        "identifier": "LOINC:MTHU029813",
        "label": "Pain",
        "original_label": "Pain",
        "type": "procedure"
      },
      {
        "identifier": "UMLS:C0030200",
        "label": "Pain, Intractable",
        "original_label": "Pain, Intractable",
        "type": "disease"
      },
      {
        "identifier": "UMLS:C0001044",
        "label": "Acetylcholinesterase",
        "original_label": "Acetylcholinesterase",
        "type": "molecular_entity"
      },
      {
        "identifier": "LOINC:MTHU007261",
        "label": "Acetylcholinesterase",
        "original_label": "Acetylcholinesterase",
        "type": "procedure"
      },
      {
        "identifier": "LOINC:LA7460-4",
        "label": "Pain",
        "original_label": "Pain",
        "type": "procedure"
      },
      {
        "identifier": "LOINC:LA27491-2",
        "label": "Ache",
        "original_label": "Ache",
        "type": "procedure"
      },
     ... etc. ...
```

I'm guessing in this case it's because an abbreviation for acetylcholinesterase is "AChE", and "Ache" is also a synonym for pain?

**Comment by edeutsch** [comment]
ha ha, yes, I was fearing this would happen. I think in my original post I hypothesized mergers of things like Alzheimer Disease (AD) and less well known ADs such as aortic dysentery.

I don't have a good solution for this other than create some special rules.
Coming up with a rule that excludes AChE == Ache, but keeps ACHE == Ache is hard.
Maybe we can just put in specific exclusions (e.g. Do not ever use "AChE" (case sensitive) for merging) that we update as we notice them.

Ideas?

**Comment by saramsey** [comment]
Is it crazy to consider having a config file `curies-that-should-never-be-merged.yaml` which we could maintain?  As we encounter egregious examples like this, we pop the two CURIEs into the config file and move on with our lives.

**Comment by edeutsch** [comment]
That's probably a good idea. But at the moment, I don't know exactly what it should look like. For the moment, I have forced instances of "ACHE" (the protein) to be named "AChE (protein)" and that seems to have remedied the problem (not committed yet). As we gather more examples, we can create a more general solution.

**Comment by amykglen** [comment]
this appears _almost_ fixed with KG2.6.7.1 - there appear to be a few ACHE genes/proteins mixed into the Pain cluster:

pain: https://arax.ncats.io/?term=LOINC:MTHU029813
ACHE: https://arax.ncats.io/?term=UniProtKB:P22303

**Comment by amykglen** [comment]
this seems pretty clean in the new synonymizer (#2003):

Cluster for UMLS:C1412122 (NCBIGene:43) has 10 nodes:

| id                      | category   | name                                    | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:------------------------|:-----------|:----------------------------------------|:---------|:------------|:-----------------|
| ENSEMBL:ENSG00000087085 | Gene       | ACHE                                    | X        | X           |                  |
| ENSEMBL:LRG_804         | Gene       | ACHE                                    |          | X           |                  |
| HGNC:108                | Gene       | ACHE                                    | X        | X           |                  |
| NCBIGene:43             | Gene       | ACHE                                    | X        | X           | X                |
| OMIM:100740             | Gene       | ACHE                                    | X        | X           |                  |
| PR:P22303               | Protein    | acetylcholinesterase (human)            | X        | X           |                  |
| REACT:R-HSA-1524050     | Protein    | ACHE [plasma membrane]                  |          | X           |                  |
| REACT:R-HSA-372506      | Protein    | ACHE [extracellular region]             |          | X           |                  |
| UMLS:C1412122           | Gene       | ACHE Gene                               | X        | X           |                  |
| UniProtKB:P22303        | Protein    | ACES_HUMAN Acetylcholinesterase (sprot) | X        | X           |                  |

Cluster for UMLS:C0030193 (HP:0012531) has 14 nodes:

| id                | category          | name   | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:------------------|:------------------|:-------|:---------|:------------|:-----------------|
| HP:0012531        | PhenotypicFeature | Pain   | X        | X           | X                |
| ICD9:338-338.99   | PhenotypicFeature | Pain   |          | X           |                  |
| LOINC:LA7460-4    | PhenotypicFeature | Pain   |          | X           |                  |
| LOINC:LP75331-6   | PhenotypicFeature | Pain   |          | X           |                  |
| LOINC:MTHU029813  | PhenotypicFeature | Pain   |          | X           |                  |
| MEDDRA:10033371   | PhenotypicFeature |        | X        |             |                  |
| MEDDRA:10033470   | PhenotypicFeature |        | X        |             |                  |
| MESH:D010146      | PhenotypicFeature | Pain   | X        | X           |                  |
| NCIT:C3303        | PhenotypicFeature | Pain   | X        | X           |                  |
| PDQ:CDR0000041399 | PhenotypicFeature | pain   |          | X           |                  |
| PSY:36150         | PhenotypicFeature | Pain   |          | X           |                  |
| SNOMEDCT:22253000 | PhenotypicFeature |        | X        |             |                  |
| SYMP:0000099      | PhenotypicFeature | pain   |          | X           |                  |
| UMLS:C0030193     | PhenotypicFeature | Pain   | X        | X           |                  |


Cluster for UMLS:C0001044 (MESH:D000110) has 10 nodes:

| id                            | category        | name                 | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:------------------------------|:----------------|:---------------------|:---------|:------------|:-----------------|
| KEGG.ENZYME:3.1.1.7           | MolecularEntity | acetylcholinesterase |          | X           |                  |
| MESH:D000110                  | ChemicalEntity  | Acetylcholinesterase | X        | X           | X                |
| PathWhiz.ProteinComplex:10066 | MolecularEntity | Acetylcholinesterase |          | X           |                  |
| PathWhiz.ProteinComplex:405   | MolecularEntity | Acetylcholinesterase |          | X           |                  |
| PathWhiz.ProteinComplex:7103  | MolecularEntity | Acetylcholinesterase |          | X           |                  |
| PathWhiz.ProteinComplex:8451  | MolecularEntity | Acetylcholinesterase |          | X           |                  |
| PathWhiz.ProteinComplex:9109  | MolecularEntity | Acetylcholinesterase |          | X           |                  |
| PathWhiz.ProteinComplex:9655  | MolecularEntity | Acetylcholinesterase |          | X           |                  |
| RXNORM:195                    | Drug            | acetylcholinesterase |          | X           |                  |
| UMLS:C0001044                 | Protein         | acetylcholinesterase | X        | X           |                  |

(interesting the SRI NN merged a Protein with a ChemicalEntity in this case; they don't seem to do that kind of merging often)

**Comment by amykglen** [comment]
confirmed fixed on our dev instances:

https://arax.ncats.io/devLM/?term=pain
https://arax.ncats.io/devLM/?term=acetylcholinesterase
