### ISSUE TITLE
put updated KG2-to-CSV-to-mediKanren code in the RTX/code/kg2/mediKanren directory

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1072]

**Comment by saramsey** [comment]
Finn, I have checked the script `kg2-tsv-to-medikanren-csv.py` into `RTX/code/kg2/mediKanren`. I got it from the email attachment that you sent to me on 9/15. That module has MD5 hash `5deb4eed4db9870a76a81c99bd2ce9bc`.  Can you please let us know if that is the final version that you used?

**Comment by saramsey** [comment]
renamed to `kg2_tsv_to_medikanren_csv.py` per our coding guidelines

**Comment by saramsey** [comment]
@finnagin just checking back on this?

**Comment by saramsey** [comment]
@finnagin can you please update the documentation in RTX/code/kg2/mediKanren so that it is current?  Thank you.

**Comment by finnagin** [comment]
@saramsey I've updated the readme to reflect the new script and split it into two parts: one for generating the indexes and one for loading per-generated indexes into mediKanren.
