### ISSUE TITLE
can we import our kg2-tsv.tar.gz TSV files directly into the mediKanren indexing code?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1073]
Greg Rosenblatt wrote on 2020.09.16:
```
For future reference, we now also support TSV import, which might be significantly more efficient on your end if you also support it.
```

**Comment by saramsey** [comment]
Latest guidance from Greg on this:
```
If you pull the mediKanren repo, this is the updated portion of the readme:
https://github.com/webyrd/mediKanren/blob/master/biolink/README.md#converting-tsvs-or-csvs-to-medikanren-format

It's really just a single letter change in the name of one of the scripts you currently run.
```

**Comment by saramsey** [comment]
marking this LOWPRI since we already have a script that goes from TSV to CSV and seems to be working

**Comment by saramsey** [comment]
Responding to Lindsey's question posed in the AHM agenda:

> where can I find the format that the mediKanren rkt scripts expect? (namely `csv-graph-to-db.rkt` and `tsv-graph-to-db.rkt`)

best bet would be to download

https://rtx-kg2-public.s3-us-west-2.amazonaws.com/kg2-csv.tar.gz

and untar it, and then take a look at the CSV files. Then, please add a bit of documentation (e.g., the output of running `head` on each of the four CSV files) to 

https://github.com/RTXteam/RTX/blob/master/code/kg2/mediKanren/README.md

describing the format.  Thank you!

**Comment by kvarforl** [comment]
Okay, after doing some invesigating, it looks like our neo4j tsv files would have to be reformatted to be ingested into mediKanren, so I think sticking with the csv process is fine!

I added the expected formats to the mediKanren subdirectory [readme](https://github.com/RTXteam/RTX/blob/master/code/kg2/mediKanren/README.md#generating-new-graph-csvs-from-kg2-tsv-file).

**Comment by kvarforl** [comment]
I'm going to close this for now, but if things go awry in the future we'll keep the tsv option in mind :)
