### ISSUE TITLE
NodeSynonymizer 'preferred' and equivalent curie discrepancies

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1074]
Noticed some funky things going on with some of the 'preferred' and equivalent curies returned by the NodeSynonymizer (both the synonymizer built from KG2-1-0 and KG2-3-4).

here's an example (using KG2-1-0 synonymizer):
```
synonymizer.get_canonical_curies("CUI:C0022230")
```
results in :
```
  'CUI:C0022230':{
    'preferred_curie':'CHEMBL.COMPOUND:CHEMBL3833327',
    'preferred_name':'INOSINE PRANOBEX',
    'preferred_type':'chemical_substance'
  }
```
but strangely, the preferred curie given (CHEMBL.COMPOUND:CHEMBL3833327) doesn't appear in CUI:C0022230's equivalent curies:
```
synonymizer.get_equivalent_nodes("CUI:C0022230")
```
```
'CUI:C0022230':{
    'CUI:C0022230':'KG2',
    'ATC:J05AX05':'KG2',
    'CUI:C0795760':'KG2',
    'CHV:0000006961':'KG2',
    'DRUGBANK:DB13156':'KG2',
    'CUI:C0795761':'KG2',
    'CUI:C0678205':'KG2',
    'MESH:D007542':'KG2',
    'CUI:C1435085':'KG2',
    'CUI:C1512793':'KG2',
    'CUI:C1512794':'KG2',
    'CUI:C1522625':'KG2',
    'CUI:C1522624':'KG2',
    'CUI:C1522623':'KG2',
    'NCIT:C601':'KG2',
    'NCI_FDA:W1SO0V223F':'KG2',
    'NDDF:003902':'KG2',
    'PDQ:CDR0000039487':'KG2',
    'RXNORM:6048':'KG2',
    'SNOMEDCT:395749001':'KG2'
  },
```
and even more strangely, the synonymizer says that CHEMBL.COMPOUND:CHEMBL3833327's 'preferred' curie is not itself (as I would expect, since it is given as the preferred curie for CUI:C0022230), but is instead CHEBI:17596: 
```
synonymizer.get_canonical_curies("CHEMBL.COMPOUND:CHEMBL3833327")
```
```
  'CHEMBL.COMPOUND:CHEMBL3833327':{
    'preferred_curie':'CHEBI:17596',
    'preferred_name':'inosine',
    'preferred_type':'chemical_substance'
  },
```
this strangeness leads to failures to merge affected nodes properly in kg2canonicalized. for example, as a result of all this, there are two nodes in KG2C with CHEMBL.COMPOUND:CHEMBL3833327 in their 'equivalent_curies':

![Screen Shot 2020-09-18 at 2 46 25 PM](https://user-images.githubusercontent.com/49423686/93649136-36675480-f9c0-11ea-8903-bba2c4c5674e.png)

which I think theoretically shouldn't ever happen (since every curie in KG2 should belong to only one synonym group, which has one 'preferred' curie).

Based on test data, I'm guessing this issue affects something like 2,000 nodes in KG2C (very rough estimate).

**Comment by amykglen** [comment]
@chunyuma came across another instance of this (with the KG2.5.2 node synonymizer 1.0) - two nodes with the same curie in their `equivalent_curies`:

<img width="762" alt="Screen Shot 2021-03-20 at 11 23 27 AM" src="https://user-images.githubusercontent.com/49423686/111881662-c9347c00-896e-11eb-8877-f54509f0d0d0.png">

**Comment by chunyuma** [comment]
Hi @edeutsch, when I'm rebuilding COHD database based on `/data/orangeboard/databases/KG2.5.2/node_synonymizer.sqlite`, I found something strange and Amy said it might be due to this issue. Here is what I found:

All the synonyms showed below have preferred curies which are `CHEMBL.COMPOUND:CHEMBL692` based on `/data/orangeboard/databases/KG2.5.2/node_synonymizer.sqlite`
```
{'preferred_name': 'GLYCERIN',
 'preferred_type': 'biolink:ChemicalSubstance',
 'synonyms': ['ATC:A06AG04',
  'MESH:D005990',
  'NDDF:001893',
  'RXNORM:4910',
  'SNOMED:80582002',
  'NCIT:C29077',
  'NDDF:002469',
  'PathWhiz.Compound:85',
  'NDDF:001176',
  'VANDF:4017411',
  'ATC:A06AX01',
  'NDDF:002240',
  'UMLS:C0017861'],
 'concept_ids': [21600587, 45617876, 961145, 4213199, 21600597]}
```
However, when I checked the preferred curie of `CHEMBL.COMPOUND:CHEMBL692`, it is `MESH:C043941`.
```
In [17]: synonymizer.get_canonical_curies('CHEMBL.COMPOUND:CHEMBL692')
Out[17]:
{'CHEMBL.COMPOUND:CHEMBL692': {'preferred_curie': 'MESH:C043941',
  'preferred_name': 'polyglycerol',
  'preferred_category': 'biolink:ChemicalSubstance'}}
```
I also checked it on today's kg2.5.2c but found that its preferred curie is itself.
DSL query :` match (n) where 'CHEMBL.COMPOUND:CHEMBL692' in n.equivalent_curies return n.id, n.equivalent_curies.
![Screen Shot 2021-03-20 at 2 33 06 PM](https://user-images.githubusercontent.com/20031672/111881929-35bc7480-8989-11eb-86ca-390c84568c16.png)

I think this issue is what Amy said in the last post.
`

**Comment by chunyuma** [comment]
`/data/orangeboard/databases/KG2.5.2/node_synonymizer_v1.1.sqlite` fixed this issue.

```
In [3]: synonymizer.get_canonical_curies('CHEMBL.COMPOUND:CHEMBL692')
Out[3]:
{'CHEMBL.COMPOUND:CHEMBL692': {'preferred_curie': 'CHEMBL.COMPOUND:CHEMBL692',
  'preferred_name': 'GLYCERIN',
  'preferred_category': 'biolink:ChemicalSubstance'}}
```

**Comment by edeutsch** [comment]
yeah, sorry, finally catching up on the various issues now.
I didn't test v1.0, but it does seem that v1.1 is correct. Perhaps v1.0 is sufficiently flawed that starting DTD over with v1.1 is desirable. It was a pretty major bug in the coalescing of duplicates.

**Comment by amykglen** [comment]
this issue doesn't occur in the new synonymizer - closing
