### ISSUE TITLE
Team Unsecret Agent reporting some incorrect same_as relationships in KG2.3.4

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1075]
From Michael Patton on 9/20:

> Hi Steve, 
> 
> I wanted to share an edge i thought was funky: 
> 
> Ammonium chloride --same_as--> Sodium chloride
> "UMLS:C0002615" --same_as--> "UMLS:C0037494"

![image3](https://user-images.githubusercontent.com/5562107/93723886-74e34780-fb57-11ea-9c41-a9841502e672.png)

and similarly:

> 
> Hey Steve -- just thought you should see this before demo but it looks like your same_as predicate has some significant errors of equivalence for concepts. More examples below
> 
> ammonium chloride --same_as--> amino acids 

![image](https://user-images.githubusercontent.com/5562107/93723898-8593bd80-fb57-11ea-8ded-5f8b98b19003.png)

and

> immune supressants --same_as--> heat shock protein family A member 9

![image-1](https://user-images.githubusercontent.com/5562107/93723912-95ab9d00-fb57-11ea-9132-cfc9f9491b82.png)

**Comment by saramsey** [comment]
Not seeing a `same_as` relation between `UMLS:C0002615` and `UMLS:C0002520` in the KG2.3.4 Neo4j endpoint:

<img width="250" alt="Screen Shot 2020-09-20 at 3 30 54 PM" src="https://user-images.githubusercontent.com/5562107/93723941-c68bd200-fb57-11ea-90aa-fb4b86970b02.png">

**Comment by saramsey** [comment]
Not seeing a `same_as` relation between `UMLS:C0002615` and `UMLS:C0037494` in the Neo4j KG2.3.4 endpoint:

<img width="373" alt="Screen Shot 2020-09-20 at 3 35 18 PM" src="https://user-images.githubusercontent.com/5562107/93723952-df948300-fb57-11ea-868e-25da8581e700.png">

**Comment by webyrd** [comment]
Hi Steve!  I see the same issue when using the Sept 16 2020 version of the data.  The predicate seems to be coming from SEMMED.  Here is the full edge:

```
(rtx2_2020_09_16
  17219475
  (664
   "UMLS:C0002615"
   "Ammonium chloride"
   (3 . "biolink:ChemicalSubstance")
   (("deprecated" . "False")
    ("description"
     .
     "A systemic and urinary acidifying salt. Ammonium chloride helps maintain pH and exerts a mild diuretic effect. This acid forming salt also exerts an expectorant effect by irritating the mucous membranes and is used for alleviation of cough.; An acidifying agent that has expectorant and diuretic effects. Also used in etching and batteries and as a flux in electroplating.; UMLS Semantic Type: UMLS_STY:T197; UMLS Semantic Type: UMLS_STY:T121")
    ("id" . "UMLS:C0002615")
    ("iri" . "https://identifiers.org/umls:C0002615")
    ("provided_by" . "identifiers_org_registry:umls")
    ("update_date" . "2020")
    ("category_label" . "chemical_substance")))
  (5394
   "UMLS:C0002520"
   "Amino acids"
   (4 . "biolink:MolecularEntity")
   (("deprecated" . "False")
    ("description"
     .
     "Any organic compounds containing amino (-NH2) and carboxyl (-COOH) groups. In biochemistry, used to refer to the twenty-plus L-alpha-amino acids found in proteins.; Organic compounds that generally contain an amino (-NH2) and a carboxyl (-COOH) group. Twenty alpha-amino acids are the subunits which are polymerized to form proteins.; UMLS Semantic Type: UMLS_STY:T123; UMLS Semantic Type: UMLS_STY:T121; UMLS Semantic Type: UMLS_STY:T116")
    ("id" . "UMLS:C0002520")
    ("iri" . "https://identifiers.org/umls:C0002520")
    ("provided_by" . "identifiers_org_registry:umls")
    ("update_date" . "2020")
    ("category_label" . "molecular_entity")))
  (736 . "same_as")
  (("negated" . "False")
   ("provided_by" . "(''SEMMEDDB:'')")
   ("publications" . "(''PMID:1068456'')")
   ("publications_info"
    .
    "{'PMID:1068456': {'publication date': '1976 Oct', 'sentence': 'Ammonium chloride is about one-half as effective as amino acids in stimulating glycogen synthesis when glucose with lactate are substrates.', 'subject score': 1000, 'object score': 1000}}")
   ("relation" . "SEMMEDDB:same_as")
   ("simplified_relation" . "skos:closeMatch")
   ("update_date" . "2019-04-26 14:38:21")
   ("simplified_edge_label" . "close_match")
   ("subject" . "UMLS:C0002615")
   ("object" . "UMLS:C0002520")))
```

**Comment by saramsey** [comment]
> Hi Steve! I see the same issue when using the Sept 16 2020 version of the data. The predicate seems to be coming from SEMMED. Here is the full edge:

Hi Will, thank you for weighing in. Yes, we map any `SEMMEDDB:same_as` relation to `biolink:close_match`; see the third-to-last line of your Racket code snippet:
```
   ("simplified_edge_label" . "close_match")
```
But we always preserve the original source knowledge-base's relation, for context purposes.

**Comment by saramsey** [comment]
I gave a new export of KG2.3.4 to Unsecret Agent and I believe it addresses this issue.
