### ISSUE TITLE
We may not want to have newlines in node description fields in the TSV file

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1076]
See:

![Screen Shot 2020-09-21 at 7 17 59 AM](https://user-images.githubusercontent.com/5562107/93778304-989ba180-fbda-11ea-8176-bec85dab970a.png)

**Comment by saramsey** [comment]
I think this is not a problem for Neo4j (the import TSV feature seems to handle newlines just fine), but I am not sure about what happens when we convert TSV to CSV and for the mediKanren indexing. Need to look into this.

**Comment by saramsey** [comment]
![Uploading Screen Shot 2020-09-21 at 7.25.09 AM.png…]()

**Comment by saramsey** [comment]
Hi @kvarforl, since @ericawood is finishing up several other GitHub issues before the end of September (and their last day with us is end of September, and school has already started for them), I'm going to assign this issue to you. Can you take a look at `kg_json_to_tsv.py`?  If you have any questions though, you can just ask Erica -- she wrote that script.

**Comment by saramsey** [comment]
I think we should have `kg_json_to_tsv.py` convert newlines into spaces. You should expect newlines to occur in the node `description` field and (occasionally) in strings in the node `synonym` list. While Neo4j admin's TSV import does an admirable job handling actual newlines, that is quite non-standard for a TSV file format (where a newline is nearly universally used as the record delimiter). What do you think, @ericawood ?

**Comment by ericawood** [comment]
Hi @saramsey,
This seems like a pretty easy fix. We already have this function:
```
def shorten_description_if_too_large(node_description_field, node_id):
    """
    Truncates a node's description if it's too large for Neo4j. (Neo4j apparently cannot 'read a field larger than
    buffer size 4194304' - see Github issue #460).
    """
    if len(node_description_field) > NEO4J_CHAR_LIMIT:
        print("warning: truncating 'description field on node {} because it's too big for neo4j".format(node_id), file=sys.stderr)
        return str(list(node_description_field)[0:NEO4J_CHAR_LIMIT]).replace("[", "").replace("]", "").replace("', '", "").replace("'", "")
    else:
        return node_description_field
```

which we can update to 

```
def shorten_description_if_too_large(node_description_field, node_id):
    """
    Truncates a node's description if it's too large for Neo4j. (Neo4j apparently cannot 'read a field larger than
    buffer size 4194304' - see Github issue #460).
    """
    if len(node_description_field) > NEO4J_CHAR_LIMIT:
        print("warning: truncating 'description field on node {} because it's too big for neo4j".format(node_id), file=sys.stderr)
        return str(list(node_description_field)[0:NEO4J_CHAR_LIMIT]).replace("[", "").replace("]", "").replace("', '", "").replace("'", "").replace("\n", "")
    else:
        return node_description_field.replace("\n", "")
```

**Comment by ericawood** [comment]
We could do a similar thing with `def truncate_node_synonyms_if_too_large`

**Comment by kvarforl** [comment]
@ericawood thanks! I put in in `shorten_description_if_too_large` as suggested above :)

**Comment by saramsey** [comment]
Hi @ericawood and @kvarforl this is good progress. I think perhaps we should use
```
.replace("\n", " ")
```
(with a `space` character in the replacement string) otherwise it could cause words to be merged in the modified string.

**Comment by kvarforl** [comment]
Hi @saramsey! thanks for the clarification! I just double checked and it is a space character as the replacement string in my previous commits :+1:
