### ISSUE TITLE
Exploring Agent team requesting that we make ARAX-ranker a REST API

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1077]
At the fall 2020 relay, Andrew Su expressed interest in having the ARAX-ranker capability made available as a dedicated API endpoint for graph ranking.

**Comment by edeutsch** [comment]
Should be fairly easy. Unclear whether a dedicated endpoint is better or just using the existing endpoint with DSL functionality is better.

**Comment by dkoslicki** [comment]
My $0.02 is a separate endpoint may be nice as I assume the use-case is a TRAPI call sans the `processing_actions`

**Comment by dkoslicki** [comment]
Closing in favor of #1111
