### ISSUE TITLE
Update KG2 to use ChEMBL 27

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1078]

**Comment by saramsey** [comment]
Maybe at the same time we do this issue, we could hit issue #545

**Comment by saramsey** [comment]
I expect this may require some additions to `predicate-remap.yaml`, so please be on the lookout for new predicates appearing after the transition to ChEMBL 27.

**Comment by ericawood** [comment]
There is now a ChEMBL 28:
![Uploading image.png…]()

**Comment by ericawood** [comment]
This appears to be complete in `KG2.6.0` per the `update_date`:
ChEMBL 27's release date:
![image](https://user-images.githubusercontent.com/36611732/115940249-ab6aa300-a455-11eb-9808-bdabe04b581c.png)
ChEMBL's source node in `KG2.6.0`:
![image](https://user-images.githubusercontent.com/36611732/115940226-955ce280-a455-11eb-877f-64e86e39e319.png)
