### ISSUE TITLE
update kg2_tsv_to_medikanren_csv.py so the CSV file has the simple edge label as the "edge_label" field

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1079]
Team Unsecret Agent is reporting that the `.scm` files that they are receiving, have (as the edge "predicate" the content of the `edge_label` field, but their team and ours are in agreement that it would be better to have the predicate derive from the `simplified_edge_label` field. This looks to be a change needed in the Racket code for exporting the .scm files. Checking now...

**Comment by saramsey** [comment]
Thank you to Michael Patten for reporting this issue

**Comment by saramsey** [comment]
Hmm, looks like the issue is actually in kg_json_to_tsv.py

![Uploading Screen Shot 2020-09-24 at 10.09.36 AM.png…]()

**Comment by saramsey** [comment]
![Screen Shot 2020-09-25 at 6 41 52 AM](https://user-images.githubusercontent.com/5562107/94274219-43250480-fefa-11ea-9ee9-ea2b4aeb8326.png)

**Comment by kvarforl** [comment]
@saramsey  I'm unsure how to verify this fix for KG2.3.5. Could you document steps for me to follow here?

**Comment by saramsey** [comment]
Hi @kvarforl I think this is a matter of running these steps 
https://github.com/RTXteam/RTX/tree/master/code/kg2/mediKanren#generate-index-files

and inspecting the `.scm` files.

**Comment by kvarforl** [comment]
I haven't run a medikanren export yet, but I imagine the schema changes in KG2.5.0 (see PR #1181) might impact this fix so I'm noting that here while I'm thinking about it.

**Comment by kvarforl** [comment]
My above suspicion was correct! Because our JSON schema, the Biolink schema, and the schema mediKanren expects have aligned for the moment, this fix isn't necessary anymore. I removed it in the above commit. thanks to the nice commenting by Erica, it was easy to see what had happened!

**Comment by saramsey** [comment]
Can we close this issue out then?

**Comment by saramsey** [comment]
+1 for Erica's diligent commenting.

**Comment by saramsey** [comment]
I assume this issue is being kept as "verify in the next KG2 build" because we need to verify that, in fact, the code as modified by be204d5 works as expected for making correct mediKanren CSV files?

**Comment by kvarforl** [comment]
Yes! I figured I would go through and close out all of the medikanren related issues once I manage to get the export of KG2.5.1 out. This way I can also keep track of what should be added to the KG2.5.1 entry of  kg2-versions.md :)
