### ISSUE TITLE
bypass_cache

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#108]
@isbluis, sometimes it will be the case that we know the cache is stale and we want to tell query to ignore the cache. Would you add a little unobtrusive devloper option to bypass the caching when submitting a question? You can do this by injecting bypass_cache=true into the JSON object that gets passed to the second AJAX call (i.e. query).

**Comment by isbluis** [comment]
@edeutsch Will the API behave correctly if I pass bypass_cache=false ?

**Comment by edeutsch** [comment]
yes, eventually

**Comment by isbluis** [comment]
Done on the UI side; pending testing.  Let me know if that new widget misbehaves.

**Comment by dkoslicki** [comment]
I like the little "use cache" switch! But note the bug in #110

**Comment by edeutsch** [comment]
This should all be functional now (in devED, devLM, test, but NOT yet rolled out to production). Please test and close.
