### ISSUE TITLE
Should we record Zoom sessions for All-hands meetings?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1081]
As our team grows, one could make the case that recorded All-Hands Meetings may be useful for folks who have missed a meeting, to catch up. Or not. What do folks think?  I am not pushing this at all -- just wondering if folks think it might be useful.

**Comment by isbluis** [comment]
I regrettably have to miss every other AHM for the foreseeable future.

I think recording them could be useful, though action items added to the Agenda (and the odd email/git tag, both of which seem to be already the norm) might be enough for me.

**Comment by edeutsch** [comment]
I don't expect to ever watch one, so no need to do it on my account. but fine if others are interested.

**Comment by dkoslicki** [comment]
I'm in the same boat as Eric: may only very rarely watch the videos (I reference the agenda if needed)

**Comment by saramsey** [comment]
OK, so I am not hearing any objections, is that right, team?

**Comment by amykglen** [comment]
no objection from me!

**Comment by saramsey** [comment]
ok we can try recording as an experiment

**Comment by dkoslicki** [comment]
This issue good to close @saramsey ?

**Comment by finnagin** [comment]
Is this okay to close @saramsey ?
