### ISSUE TITLE
New DSL feature fetch_message()

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1084]
Can I use GitHub issues to announce new features?

There is a new DSL command `fetch_message()`. It allows you to fetch a Message from anywhere on the Internet and subsequently do fun things with it.

Example:

Here's a faintly amusing Message from the past:
https://arax.rtx.ai/?m=2800
Five results. Liver disease is the top scoring hit. I have no idea where it came from. I picked a random number.
But there was no NGD computed on it. hmm.

Trying running this DSL at https://arax.rtx.ai/test/ (only rolled out at /test so far!!):
```
fetch_message(uri=https://arax.rtx.ai/api/rtx/v1/message/2800)
overlay(action=compute_ngd, virtual_relation_label=NGD, source_qnode_id=n0, target_qnode_id=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=50)
```

It fetches a Message of yore
Overlays NGDs
Recomputes results and automatically reranks
Some useless (in this case) limiting of results to ensure the result isn't too big
and presto!

A feature you didn't know you needed!

Can you fetch a TRAPI Message from anywhere in the world? YES! If you can get it with a single HTTP GET.
Will TRAPI Messages created by other systems be compatible with ARAX? Heh.

**Comment by saramsey** [comment]
Nice!  I bet this will be super-useful during relays and such, when we are sharing results back and forth with collaborators.

**Comment by finnagin** [comment]
Closing since this is an old announcement at this point.
