### ISSUE TITLE
error in running validate_curies_to_categories_yaml.py

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1085]
With the latest (Sept. 21, 2020) `biolink-model.owl` file from the [Biolink-model GitHub master branch](https://github.com/biolink/biolink-model/blob/master/biolink-model.owl), the script `validate_curies_to_categories_yaml.py` is giving an `AssertionError`, as reported by @kvarforl 

![error](https://user-images.githubusercontent.com/5562107/94981938-52541580-04eb-11eb-9003-329c34ef1148.png)

**Comment by kvarforl** [comment]
@saramsey With the most recent code on kg2lindsey, the above error is fixed! Unfortunately `validate_predicate_remap_yaml.py` is still mad.
![image](https://user-images.githubusercontent.com/39020520/94998630-0c896280-0568-11eb-98bc-20c68411b335.png)
