### ISSUE TITLE
Documentation format messed up

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1088]
`create_message`, `add_qnode` and `add_qedge` formatting has been messed up in the documentation as of 8f434bcc8dd63d382b97f5da4796535731aa77bf. Need to investigate what precipitated this.

**Comment by edeutsch** [comment]
#1080 precipitated this. documentation for the above 3 functions is in the new format we agreed on.

**Comment by dkoslicki** [comment]
Ah, that's right! I'll close this issue and make a new one for me to update `document_dsl_commands.py`
