### ISSUE TITLE
Missing/different curie identifier prefixes?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#109]
On http://rtx.ncats.io:7474/browser/:
``match (n) with n.curie_id as c return distinct split(c,":")[0]``

split(c,":")[0]
--
"Reactome"
"GO"
"UniProt"
"HP"
"MP"
"UBERON"
"CL"
"NBO"
"NCBIGene"
"DOID"
"OMIM"
"ChEMBL"

Yet on http://rtxdev.saramsey.org:7674/browser/:
``match (n) with n.id as c return distinct split(c,":")[0]``

split(c,":")[0]
--
"GO"
"NCBIGene"
"Reactome"
"HP"
"ChEMBL"
"UniProt"
"UBERON"
"CL"
"OMIM"
"DOID"

What happened to MP and MBO? And what do these prefixes correspond to?

**Comment by saramsey** [comment]
MP and NBO are no longer included; MP is "mammalian phenotype ontology" and those terms should not have been in the KG; NBO is "neuro behavior ontology" and again, was not intended to be included.

**Comment by edeutsch** [comment]
@saramsey Would you fill in some URIs here:
https://docs.google.com/spreadsheets/d/1BCtJWyz9WpwI-myN3HwWkwsjxvUNr1OrdGU60QCs2Uw/edit#gid=0

**Comment by edeutsch** [comment]
Hold the phone. This just in from Monarch:
https://github.com/monarch-initiative/dipper/blob/master/dipper/curie_map.yaml

**Comment by edeutsch** [comment]
I did a quick comparison. Our CURIE prefixes seem to be mostly the same. But the two conflicts I see is that Monarch has REACT instead of Reactome. And Monarch has UniProtKB instead of UniProt. Should be conform? I also pasted in their URI prefixes. Do we use these? or what did you use?

**Comment by saramsey** [comment]
I think Monarch is correct about UniProtKB.  Not sure about Reactome, but what the heck, let's just conform.

**Comment by saramsey** [comment]
fixed in the code.  re-generating the KG now on rtxsteve.saramsey.org

**Comment by saramsey** [comment]
Basis for Monarch being correct:
https://github.com/geneontology/go-annotation/issues/1772

**Comment by edeutsch** [comment]
Great! What are the implications for deploying to rtx.ncats.io and @dkoslicki ongoing work?

Agreed. UniProt is the consortium. UniProtKB is the database. I've been corrected by UniProt folks on this myself.

**Comment by saramsey** [comment]
Oh, and thanks for catching this. 

This shouldn't affect David unless for some reason he is parsing/using the CURIE ID (@dkoslicki are you doing that?)

**Comment by dkoslicki** [comment]
I am only reporting the contents of the curie_id property to the output format (so I don't use the values themselves, I just report them).

**Comment by saramsey** [comment]
I've fixed the URIs that we are using in our KG, to comply with the draft standard as it was just revealed to me in the "CURIE Lookup DRAFT" google sheet.

**Comment by edeutsch** [comment]
great! I think those URIs should be correct. They look good. But in case there is any misconception, the URIs in that draft sheet are from me copy-pasting from the Monarch YAML... so, those were not put there by an expert, but copy-pasted by a monkey..

**Comment by saramsey** [comment]
I'm not entirely sure if "REAC" is the universally-agreed CURIE ID for reactome; I have emailed Team Orange to inquire.

**Comment by edeutsch** [comment]
"REACT" is what I have in the spreadsheet and what Monarch has. Not sure that's right, of course.
