### ISSUE TITLE
Url for DGIDB interations.tsv has changed, causing dgidb_tsv_to_kg_json.py to fail

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1091]
[this](https://github.com/RTXteam/RTX/blob/d967de4df3a067136f1b0284afba0704c4d4281e/code/kg2/dgidb_tsv_to_kg_json.py#L74) line in `dgidb_tsv_to_kg_json.py` fails on unpacking values.

Looking into it, I found that the url [http://www.dgidb.org/data/interactions.tsv](http://www.dgidb.org/data/interactions.tsv) used in `extract-dgidb.sh` leads to a 404 page.  I'm looking for the relocated file, but in the meantime:
@saramsey is there a reason that we let `dgidb_tsv_to_kg_json` fail instead of `extract-dgidb.sh`? it wasn't too hard to track down the source of the problem, but it might be even easier if the code stopped working closer to the source of the error :)

**Comment by saramsey** [comment]
Hi @kvarforl thank you for bringing this issue to my attention. I definitely think that it would be best if `extract-dgidb.sh` could detect the 404 error and then die. Can you see if adding the `-f` option to line 13 of `master-config.shinc`, so that it reads like this:
```
curl_get="curl -s -L -f"
```
that should solve the problem (though, until we do a complete build, we won't know for *certain* whether or not it will introduce another problem since `curl` is used all over the place in this code base; that's OK, that is why we do testing). I have tested the above fix and it seems to work, at least for DGIdb.

**Comment by saramsey** [comment]
Can you please find the current URL to download `interactions.tsv` and update L18-19 of `extract-dgidb.sh` as needed?

**Comment by saramsey** [comment]
Can' believe we have gotten this far without configuring cURL to detect (and fail on) 404 errors!

**Comment by kvarforl** [comment]
> Hi @kvarforl can you please find the current URL to download `interactions.tsv` and update L18-19 of `extract-dgidb.sh` as needed?

i'm looking for it now. It looks like DGIdb might have moved to an API format (documented [here](https://www.dgidb.org/api)) that returns JSON instead of TSV. My latest plan is to inspect an old tsv file from a past build so I can better understand what `dgidb_tsv_to_kg_json.py` was doing and adjust/ rename it to digest the json instead :)

**Comment by kvarforl** [comment]
Okay, using the API seems feasible, but would require some weird page traversing and some moderate refactoring of  `dgidb_tsv_to_kg_json.py`. I think it might be more efficient to change `extract-dgidb.sh` to figure out the most recent .tsv from https://www.dgidb.org/downloads and download it, and then leave `dgidb_tsv_to_kg_json.py` unchanged, so I'm going that route instead.

**Comment by saramsey** [comment]
Hi @kvarforl let's just use the URL here:

https://www.dgidb.org/data/monthly_tsvs/2020-Oct/interactions.tsv

I think it is the same as the old `interactions.tsv` format. I am not enthusiastic about moving to querying an API.

**Comment by kvarforl** [comment]
Should be fixed. I started a new snakemake build following the instructions in the readme for salvaging a partially completed build; its running now. Will verify the fix when it completes :)

**Comment by kvarforl** [comment]
Okay, now the website [https://www.dgidb.org/downloads](https://www.dgidb.org/downloads) appears to be down. 
![image](https://user-images.githubusercontent.com/39020520/95380061-0dd5ca80-089b-11eb-9a73-a05d57c5f4b6.png)

I suppose I'll just check on it periodically to see when it's back up.

**Comment by kvarforl** [comment]
Fixed in build completed on 10/13/2020 (KG2.3.5). Closing issue
