### ISSUE TITLE
KG2C missing node descriptions

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1092]
Eg.
```
add_qnode(name=acetaminophen, id=n0)
add_qnode(type=protein, id=n1)
add_qedge(source_id=n0, target_id=n1, id=e0)
expand(edge_id=e0,kp=ARAX/KG1)
overlay(action=compute_ngd, virtual_relation_label=N1, source_qnode_id=n0, target_qnode_id=n1)
resultify()
```
has this on the acetaminophen node:
```
{
        "description": "A member of the class of phenols that is 4-aminophenol in which one of the hydrogens attached to the amino group has been replaced by an acetyl group.",
        "id": "CHEMBL.COMPOUND:CHEMBL112",
        "name": "ACETAMINOPHEN",
        "node_attributes": [],
        "qnode_ids": [
          "n0"
        ],
        "symbol": null,
        "type": [
          "chemical_substance"
        ],
        "uri": "https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL112"
      }
```
while with KG2C
```
add_qnode(name=acetaminophen, id=n0)
add_qnode(type=protein, id=n1)
add_qedge(source_id=n0, target_id=n1, id=e0)
expand(edge_id=e0,kp=ARAX/KG1)
overlay(action=compute_ngd, virtual_relation_label=N1, source_qnode_id=n0, target_qnode_id=n1)
resultify()
```
has this for acetaminophen:
```
"description": null,
        "id": "CHEMBL.COMPOUND:CHEMBL112",
        "name": "ACETAMINOPHEN",
        "node_attributes": [
          {
            "name": "equivalent_curies",
            "type": null,
            "url": null,
            "value": [
              "CUI:C0000970",
<snip>
            ]
          },
          {
            "name": "publications",
            "type": null,
            "url": null,
            "value": [
              "PMID:19327871",
<snip>
            ]
          }
```
sad we lost the description and URI as these were quite helpful to NCATS and SME's. Maybe merge/pick one from the equivalent nodes? Use the best one?

**Comment by amykglen** [comment]
ah, yep, have been meaning to address this. will get them in there!

**Comment by amykglen** [comment]
alright, a version of KG2c (still from KG2.3.4) in which nodes have `description`, `iri`, and `all_names` properties is up at http://kg2canonicalized.rtx.ai:7474/browser/

in the testing I've done, things are looking good. from my local environment:

![Screen Shot 2020-12-03 at 6 50 36 PM](https://user-images.githubusercontent.com/49423686/101115680-9cfc1780-3598-11eb-8dfc-92271162c7e1.png)

just need to do some more rigorous testing and then will make this KG2c our "production" KG2c.

**Comment by amykglen** [comment]
one note: each KG2c node's description is the longest 5 descriptions from its coalesced nodes, joined into one string. (this was along the lines of the discussion at yesterday's minihackathon.) it's possible this might be a little bit too much info in some cases, but it's easy to reduce down the line if we're feeling that way.

**Comment by amykglen** [comment]
alright, all is looking good (entire pytest suite passing) and I think this can be "rolled out". I suppose the first step here should be rolling `master` out to `/test` and editing `/test`'s config file to point to the new kg2c endpoint. is that something you could do when you have time, @edeutsch?

you can get the updated config file with:
```
scp araxconfig@araxconfig.rtx.ai:/home/araxconfig/config_test/config_test_kg2c.json config.json
```
if all seems well on `/test` after that, the final step would be to roll `master` out to production (and anywhere else) and update the master copy of `config.json`. (fortunately, all changes to ARAX here are backwards-compatible, so we shouldn't enter a "breaking" state at any point, even if the new config file isn't downloaded into everyone's environments for a while.)

**Comment by edeutsch** [comment]
sure. If I do that now, do you have time to test it?

**Comment by amykglen** [comment]
yep, sounds good to me!

**Comment by edeutsch** [comment]
okay, /test has the latest `master` and updated config file. tests appears to be passing.

**Comment by amykglen** [comment]
awesome. all looks good to me on `/test`! the resolvable uris are really nice. :)

**Comment by edeutsch** [comment]
shall I distribute all this to all deployments?
Do you want to make the changed config.json file the default now?

**Comment by amykglen** [comment]
yes, sounds good to me - I'll update the master config.json file.

**Comment by amykglen** [comment]
alright - new `config.json` is in place on araxconfig.rtx.ai.

**Comment by edeutsch** [comment]
super, thanks!
okay, the latest code and config file is rolled out to all deployments including production.
Let me know if anything seems amiss.

**Comment by amykglen** [comment]
verified this is working and looks good on production.

think we can close this issue if all seems good to you, @dkoslicki. (nodes from KG2c now have `description`, `uri`, and `all_names`.)
