### ISSUE TITLE
Filtering top N still includes bioentities in the KG

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1093]
This leads to huge JSON responses that should be quite slim. To reproduce, run:
```
add_qnode(name=acetaminophen, id=n0)
add_qnode(type=protein, id=n1)
add_qedge(source_id=n0, target_id=n1, id=e0)
expand(edge_id=e0)
overlay(action=compute_ngd, virtual_relation_label=N1, source_qnode_id=n0, target_qnode_id=n1)
filter_results(action=limit_number_of_results, max_results=1)
resultify()
```
And check out the JSON response.

Don't know if it's a filter or resultify issue, hence the assignees

**Comment by edeutsch** [comment]
Note that the last two commands are out of order? can't filter results until after resultify()?

**Comment by edeutsch** [comment]
the DSL as written should generate a "there are no results" error?

**Comment by amykglen** [comment]
yep, all seems well if you fix the order of those two commands (only 1 result is returned):
```
add_qnode(name=acetaminophen, id=n0)
add_qnode(type=protein, id=n1)
add_qedge(source_id=n0, target_id=n1, id=e0)
expand(edge_id=e0)
overlay(action=compute_ngd, virtual_relation_label=N1, source_qnode_id=n0, target_qnode_id=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=1)
```

**Comment by edeutsch** [comment]
But I think there are still two issues that remain, both somewhat philosophical that we should discuss:

1) The initial, incorrect code runs to completion with no errors. SHOULD it be an error if filter_results() is called when there are no results yet? I'm thinking yes. I am hard pressed to find an example when a user would be pleased that filter_results() silently does nothing when called before resultify() or called in any situation where there are no results yet.

2) Running @amykglen 's corrected DSL does what OP (mostly) intended, BUT true to the title of this issue, the KG contains lots of nodes that are not in the single result. SHOULD filter_results() purge all nodes and edges that do not appear in any of the retained results? I'm thinking yes, but I can easily see both sides of the argument. Perhaps we could have a keep_orphan_nodes_and_edges=false option. The default would be purge them (generally expected bahavior), but if set to true, the user can still get them back and see them all (perhaps usually undesirable current behavior)

**Comment by amykglen** [comment]
re: 2) yeah, I believe the team made the decision before that `filter_results` should _not_ clean up the KG... though personally I think that it should. that would resolve the too-large-of-a-message problem we're currently facing with #1094! I like your idea to add a flag to control the behavior though.

**Comment by finnagin** [comment]
I'm going to add this to the agenda for the next AHM. I was thinking another way this might be done is to add a `filter_by_results` method to the filter_kg command that could be run after filter_results if we decide we want to keep things separate i.e. if filter_results should *not* clean up the kg.

**Comment by finnagin** [comment]
I added in a warning for when filter_results is called when there are no results. I can change it to an error if we want but my thought was what if the query a user is running just has no results? Should we be returning an error or that there are 0 results? If we'd rather it return an error it will be easy for me to change.

**Comment by dkoslicki** [comment]
I think a warning makes sense here (don't want a 2-hour query erroring out due to an easy-to-make mistake, like I did above)

**Comment by finnagin** [comment]
After the meeting today we decided to have filter_results automatically prune the kg to match the results whenever called with an optional flag to keep the kg how it is.

**Comment by finnagin** [comment]
This has now been implemented, is passing all tests and was merged back into master after having master merged into filter. Just need to test on production and then can be closed.

**Comment by edeutsch** [comment]
deployed to https://arax.ncats.io/test/
Would you test there?

**Comment by finnagin** [comment]
Thanks! I'll test it there.

**Comment by finnagin** [comment]
Looks to be working!

**Comment by finnagin** [comment]
Though there is one thing I noticed when testing it out.

If I run this DSL:
```
add_qnode(name=DOID:1227, id=n00)
add_qnode(type=chemical_substance, id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00)
overlay(action=add_node_pmids, max_num=15)
resultify(ignore_edge_direction=true)
filter_results(action=sort_by_node_attribute, node_attribute=pubmed_ids, direction=a, max_results=20)
return(message=true, store=false)
```

I get 20 results however the number next to the results tab on the left is 135 which is the number of results before filtering however if you click the tab there is only 20 results which is the correct number. Where does this number get populated from? Is there a results count somewhere that `filter_results` needs to be updating after it is done?

**Comment by isbluis** [comment]
Hi Finn,
The UI gets this from the `n_results` attribute of the returned `message`.  It seems that it needs to get updated upstream; I suppose you could try a search of this string in the code to see where it is being set.

**Comment by edeutsch** [comment]
@finnagin ah the answer seems to be that all the code the tidies up the Message (such as re-setting n_results) is only executed when the Message is stored. Since you're not storing, it isn't run. I suppose it would make more sense to run this cleanup code always regardless of whether it is stored or not.

But it would also be sensible for your code to update Message.n_results if you change the number of results.

**Comment by finnagin** [comment]
Ok so now results updates the message.n_results property when it is done filtering results. @edeutsch let me know when you next update https://arax.ncats.io/test/ and I'll double check that it is working.

**Comment by edeutsch** [comment]
deployed to test!

**Comment by finnagin** [comment]
Thanks @edeutsch ! Looks like it is working now so I'm going to go ahead and close this issue.
