### ISSUE TITLE
One QGI DSL program has a store=false

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1095]
As a reminder to us, this commit:
https://github.com/RTXteam/RTX/commit/3a8c71e3a154c4ceb3454119597554a860dfc2c4
was performed to include a temporary patch to make something work for NCATS
but this is not likely a good long term fix
and should be reverted at some point when the underlying issue is resolved
Related to #1093 and #1094 but the real problem is really only in Slack.

**Comment by saramsey** [comment]
tagging @amykglen to make her aware

**Comment by saramsey** [comment]
See this [link](https://coe-eecs-ncats-arax.slack.com/archives/C0128S0TZ9S/p1601920763071200) in the `general` slack channel, and following posts.

**Comment by dkoslicki** [comment]
This was fixed with @saramsey's JSON output, so it now [reads](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter_templates.yaml#L140) `store=json` as of ffd49d0e5dc0ea2ffa88848f18ba3e16089c3fb9
