### ISSUE TITLE
NGD code is a convoluted beast

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1097]
Currently, NGD is kind of all over the place in different parts of the repo (and I have noticed quite a large bit of code duplication). For ease of maintenance, this code needs to:

- [ ] be migrated to code/ARAX
- [ ] de-duplicated
- [ ] easily navigable with respect to fast NGD

This can be done in conjunction with #1096

**Comment by finnagin** [comment]
@dkoslicki Is this issue still relevant since Amy let go of the 'fallback' NGD method in favor of only using the fastNGD method?

**Comment by dkoslicki** [comment]
I'll mark this low-priority as the NGD code is superseded by FastNGD. It may come up again though since I could foresee a few different situations where we might want to use NCBI eUtils (and it would be nice in that case to have the NGD/eUtils code much more navigable).
