### ISSUE TITLE
in predicate-remap.yaml, do not invert relations mapped to reflexive biolink relations

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1098]
Per Richard B.'s comment in https://github.com/biolink/biolink-model/issues/440,

>     In the RTX curations, @saramsey might have tagged some 3rd party predicates as the "inverse" of biolink:related_to, for example:
> 
>     BTO:develops_from:
>     invert:
> 
>         related_to
> 
>     but I'm not sure what that means...
> 

we should fix this in `predicate-remap.yaml`.

**Comment by saramsey** [comment]
Looks like we need to change `invert` to `rename` for these:
```
{'BTO:develops_from': {'invert': ['related_to', 'biolink:related_to']},
 'DDANAT:develops_from': {'invert': ['related_to', 'biolink:related_to']},
 'FMA:develops_from': {'invert': ['related_to', 'biolink:related_to']},
 'MESH:RO': {'invert': ['related_to', 'biolink:related_to']},
 'UMLS:RO': {'invert': ['related_to', 'biolink:related_to']}}
>>>
```

**Comment by saramsey** [comment]
Hey @kvarforl we can work on this issue at the same time we work on #1107

**Comment by kvarforl** [comment]
Yes that would be very helpful!

**Comment by kvarforl** [comment]
The changes were made to `predicate-remap.yaml` and should be effective in KG2.3.5. closing this issue out :)
