### ISSUE TITLE
Random Walk with Restart development

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#11]
_From @saramsey on November 26, 2017 19:16_

This is a placeholder issue for the development of Random Walk with Restart for multi-path relatedness between a "Q1 disease" and a genetic condition (OMIM).

_Copied from original issue: dkoslicki/NCATS#98_

**Comment by dkoslicki** [comment]
_From @saramsey on November 30, 2017 16:39_

Update from @chyods:

Dear prof. Ramsey,

Here is the update to RWR with edge-weight training.
RWR and weighted RWR shows the ranked position of the correct answer for each query returned by RWR and weighted RWR, respectively.
The smaller the value the better the result is.

(see table in next comment)

Overall, the weights for edges disease_affects, gene_assoc_with and phenotype_assoc_with have to be increased by roughly 100x, 60x and 40x.
I'm still unsure how to improve the last query (Ashtma), but I'm still working to see if I could improve this one while minimizing the loss of accuracy of other queries. 

Please let me know if you have any question or suggestion regarding this results.

Thank you very much,
Yodsawalai

**Comment by dkoslicki** [comment]
_From @saramsey on November 30, 2017 16:39_


query | MeSH | RWR | MRR | weighted RWR | MRR | #candid | MRR diff
-- | -- | -- | -- | -- | -- | -- | --
DOID:11476 | Osteoporosis | 3122 | 0.0003 | 76 | 0.0132 | 17752 | 40.08
DOID:1498 | Cholera | 26 | 0.0385 | 24 | 0.0417 | 8482 | 0.08
DOID:12365 | Malaria | 45 | 0.0222 | 39 | 0.0256 | 8482 | 0.15
DOID:13810 | Hypercholesterolemia | 9 | 0.1111 | 3 | 0.3333 | 17752 | 2.00
DOID:9352 | Diabetes Mellitus, Type 2 | 2214 | 0.0005 | 77 | 0.0130 | 17752 | 27.75
DOID:2841 | Asthma | 305 | 0.0033 | 682 | 0.0015 | 8482 | -0.55

**Comment by saramsey** [comment]
Hey @dkoslicki can this issue be closed out?  Looks like we don't have an RWR work planned in the 5-year roadmap, right?

**Comment by dkoslicki** [comment]
That's correct. Closing
