### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#110]
![screenshot from 2018-05-04 18-54-11](https://user-images.githubusercontent.com/6362936/39658657-90b3decc-4fcc-11e8-8971-76238d224215.png)

On ``/devLM``

**Comment by dkoslicki** [comment]
Also:
![screenshot from 2018-05-04 18-55-29](https://user-images.githubusercontent.com/6362936/39658663-bb993326-4fcc-11e8-96ae-8b8df55d4c7e.png)

**Comment by dkoslicki** [comment]
And again:
![screenshot from 2018-05-04 18-56-52](https://user-images.githubusercontent.com/6362936/39658681-f2968568-4fcc-11e8-9ae7-342616c5a4d5.png)

**Comment by edeutsch** [comment]
I am under the impression that:
devLM/
devED/
test/
are now on the new API system. Not all new functionality is available. But all pre-existing functionality that broke should now be available again. The bypass_cache switch *is* fully functional (to my testing).

Anything else here an issue or close?
