### ISSUE TITLE
Add microbial flag to taxon nodes

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1100]
Currently, in KG2 and KG2C, there is no way to know if an `organism_taxon` is a microbe (or vertebrate, etc.). For now, the most important thing is to have the microbes be easily extracted from `organism_taxon` nodes. I suggest a node property to identify such nodes.

**Comment by saramsey** [comment]
Maybe this can be determined post-hoc by walking the NCBI taxon ontology tree?

**Comment by dkoslicki** [comment]
Yes indeed! That’s what we’ve been doing, but it’d be nice to have this as part of the actual graph

**Comment by finnagin** [comment]
looking at kg2.3.4 these are the sources for the `organism_taxon` nodes:


n.provided_by | count(*)
-- | --
"umls_source:MSH" | 1
"umls_source:NCBITAXON" | 1776514
"umls_source:NCI" | 3029
"umls_source:SNOMEDCT" | 34969
"OBO:go/extensions/go-plus.owl" | 24
"EFO:efo.owl" | 793
"OBO:uberon/ext.owl" | 2
"OBO:cl.owl" | 31
"OBO:foodon.owl" | 37
"OBO:ncbitaxon/subsets/taxslim.owl" | 3374
"OBO:mondo.owl" | 28
"OBO:doid.owl" | 2
"OBO:pr.owl" | 227
"OBO:genepio.owl" | 29
"identifiers_org_registry:chembl" | 2137

**Comment by dkoslicki** [comment]
@finnagin I don’t know if your previous post was a question, but it should be fine to focus just on the NCBITAXON nodes (so you can use NCBI taxdump or the like to flag the nodes as Steve mentioned)

**Comment by finnagin** [comment]
@dkoslicki thanks! Is ncbi taxdump something I need to download from [here](https://www.ncbi.nlm.nih.gov/guide/taxonomy/) as part of the build process or do we already have code that uses it/downloads it?

Also, @saramsey any thoughts on if we should flag nodes as microbial using a new node property or encode it into an existing one?

**Comment by dkoslicki** [comment]
@finnagin yes, I don't think the NCBI taxdump is being used elsewhere (but @saramsey would know better). Though be sure to remove the database after using it (since we don't want it taking up space on AWS).

As a side note, it should be as simple as adding a microbial flag to anything that is a `Bacteria` or `Archaea`. To make life simpler, you could even consider using [ete3](http://etetoolkit.org/) to easily parse the NCBI taxdump (it handles the download of the database, but I don't immediately know how to remove what it downloads).

**Comment by finnagin** [comment]
Awesome, thank you!

**Comment by finnagin** [comment]
Talked to Steve about this. He said that instead of including this into the KG2 build process it would be better to write a python script that adds a new node property to all of the microbe nodes by connecting to neo4j via bolt to an already loaded neo4j instance.

**Comment by dkoslicki** [comment]
Note: `organism_type` is the node property that has the rank names.
