### ISSUE TITLE
Find ways to speed up arax code

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1105]
Test different aspects of the arax codebase and look for pain points where we might be able to speed things up.

**Comment by dkoslicki** [comment]
Focus first on [this DSL template](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter_templates.yaml#L131-L153), 

1. Find which DSL commands are causing the slowdown
2. Profile the python code to figure out why
3. Find strategies to ameliorate.
