### ISSUE TITLE
Address warnings in `filter_kg_and_remap_predicates.log`

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1107]
The following warnings appear in `filter_kg_and_remap_predicates.log` from KG2.3.5 build. 
```
118 relation curie is missing from the YAML config file: OBO:exo.obo#interacts_with_an_exposure_stressor_via
119 relation curie is missing from the YAML config file: SO:derives_from
120 relation curie is missing from the YAML config file: SO:has_part
121 relation curie is missing from the YAML config file: SO:adjacent_to
122 relation curie is missing from the YAML config file: SO:guided_by
123 relation curie is missing from the YAML config file: SO:has_quality
124 relation curie is missing from the YAML config file: OBO:exo.obo#interacts_with
125 relation curie is missing from the YAML config file: OBO:exo.obo#interacts_with_an_exposure_receptor_via
126 relation curie is missing from the YAML config file: SO:contains
127 relation curie is missing from the YAML config file: RO:0002491
128 relation curie is missing from the YAML config file: SO:non_functional_homolog_of
129 relation curie is missing from the YAML config file: SO:transcribed_to
130 relation curie is missing from the YAML config file: RO:0002309
131 relation curie is missing from the YAML config file: SO:transcribed_from
132 relation curie is missing from the YAML config file: SO:member_of
133 relation curie is missing from the YAML config file: SO:overlaps
134 relation curie is missing from the YAML config file: MONDO:has_onset
```

**Comment by saramsey** [comment]
OK, I'm thinking I can do the first few of these these fixes but screen-share with you, so you get the gist of it. Does that make sense?

**Comment by kvarforl** [comment]
Yes that would be very helpful! Would you like to do that pre all hands meeting, or during the hackathon slot?

**Comment by saramsey** [comment]
`adjacent_to`: maybe `coexists_with`?

**Comment by kvarforl** [comment]
Okay, I've addressed the one's that had clear examples in the existing `predicate-remap.yaml` in the above commit. 

Now documenting my very unresearched initial guesses at the rest of them. Will do some further research to try to hone in, but if @saramsey could weigh in I'd love it!


- `OBO:exo.obo#interacts_with_an_exposure_stressor_via` -> `interacts_with`?

- `SO:has_quality` -> `has_phenotype`? 

- `OBO:exo.obo#interacts_with_an_exposure_receptor_via` -> `interacts_with`?

- `SO:transcribed_to` -> `has_gene_product` ?
    - very unsure, but basing this guess off of the description of `has_gene_product` in [biolink-model.yaml](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml)

- `RO:0002309` (has exposure stimulus) -> `caused_by` ?
    - highly uncertain about this one

- `SO:transcribed_from` -> `has_gene_product` ?
    - very unsure, but basing this guess off of the description of `has_gene_product` in [biolink-model.yaml](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml)

- `SO:non_functional_homolog_of` -> .... maybe invert `homologous_to` ?

- `MONDO:has_onset` ... ???

- `SO:guided_by` ..... ????

**Comment by kvarforl** [comment]
Out of curiosity, how do you go about inspecting the edge label occurrence?

I thought I could use `cat` and `grep`, but I think the kg2.json file is one line, so that hasn't been fruitful (unless there are some nifty flags that I haven't discovered yet!) My other strategy is to write a python script that slurps up the whole kg in json format, but that seems pretty memory intensive so I was wondering if there was a better way :)

**Comment by saramsey** [comment]
https://biolink.github.io/biolink-model/docs/Relations.html

**Comment by saramsey** [comment]
Example triple for `guided_by`:
```
      "sub" : "http://purl.obolibrary.org/obo/SO_0000873",
      "pred" : "http://purl.obolibrary.org/obo/so#guided_by",
      "obj" : "http://purl.obolibrary.org/obo/SO_0000602"
```

**Comment by kvarforl** [comment]
I ended up using the relations suggested above, with the following exceptions:


- `RO:0002309` (has exposure stimulus) -> `related_to`

- `MONDO:has_onset`->`related_to`

- `SO:guided_by` ->`related_to`
