### ISSUE TITLE
Think of english questions linking drug and disease nodes

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1110]
Think of all the different English language questions in which a single drug and a single disease node linked by an unknown edge could be interpreted using arax along with corresponding query graphs.

**Comment by finnagin** [comment]
1. What drugs are indicated for \<named disease\>?
  (chemical_substance or drug)-[treats]-(\<named disease\>)

2. What diseases are treated by \<named drug\>?
  (\<named drug\>)-[treats]-(disease or phenotypic_feature)

3. What drugs are contraindicated for \<named disease\>?
  (chemical_substance or drug)-[contraindicated_for]-(\<named disease\>)

4. For what diseases is \<named drug\> contraindicated for?
  (\<named drug\>)-[contraindicated_for]-(disease or phenotypic_feature)

5. What drugs might treat \<named disease\>?
  (chemical_substance or drug)-[high ranked prob_treats]-(\<named disease\>)

6. What diseases might \<named drug\> be indicated for?
  (\<named drug\>)-[high ranked prob_treats]-(disease or phenotypic_feature)

7. What drugs might be contraindicated for \<named disease\>?
  (chemical_substance or drug)-[low ranked prob_treats]-(\<named disease\>)

8. For what diseases might \<named drug\> be contraindicated for?
  (\<named drug\>)-[low ranked prob_treats]-(disease or phenotypic_feature)

**Comment by finnagin** [comment]
The querry `match (n)-[r]-(m) where (n:drug or n:chemical_substance) and (m:disease or m:phenotypic_feature) return distinct type(r), count(*) as count order by count desc` returns the following:


type(r) | count
-- | --
"treats" | 285232
"causes" | 126888
"related_to" | 118525
"affects" | 89887
"prevents" | 51186
"predisposes" | 34447
"disrupts" | 32539
"positively_regulates" | 22378
"contraindicated_for" | 21485
"produces" | 6746
"located_in" | 2023
"interacts_with" | 1836
"negatively_regulates,_entity_to_entity" | 1718
"part_of" | 454
"correlated_with" | 288
"coexists_with" | 154
"close_match" | 129
"subclass_of" | 101
"physically_interacts_with" | 37
"biomarker_for" | 30
"precedes" | 21
"occurs_in" | 9
"has_input" | 9
"has_attribute" | 7
"manifestation_of" | 5
"quantifier_qualifier" | 4
"positively_regulates,_entity_to_entity" | 1
"participates_in" | 1
"disease_has_basis_in" | 1

**Comment by dkoslicki** [comment]
Thanks @finnagin! Can you imagine DSL commands too (in addition to cypher)?

**Comment by dkoslicki** [comment]
Other variations are:

1. What drugs do doctors use on patients with disease X?
2. What drugs target proteins involved with disease X?
3. What drugs are in clinical trials to treat disease X?

**Comment by edeutsch** [comment]
I think a key component here is what should the QueryGraph look like for these queries. For example, for "which drugs do doctors use on patients with disease X", how could you convey that meaning in a QueryGraph? Different reasoners might approach the question differently, but I would advocate that we agree Translator-wide on how to encode the semantics of that question in a QueryGraph in a uniform way.

**Comment by dkoslicki** [comment]
Indeed! @finnagin I may have not communicated it well, but the goal is to push the QG format to see where it may fail in capturing this nuance. So disregard the comment about translation to dsl and instead focus on how these can be translated to the TRAPI QG format (and note what changes would need to be made when the current spec doesn't suffice)

**Comment by finnagin** [comment]
Oh ok so here is what I was thinking for the examples listed above in TRAPI:

1. What drugs treat <named disease>? 
```
"query_graph": {
    "edges": [
      {
        "id": "e0",
        "negated": null,
        "relation": null,
        "source_id": "n0",
        "target_id": "n1",
        "type": "treats"
      }
    ],
    "nodes": [
      {
        "curie": null,
        "id": "n0",
        "is_set": null,
        "type": "chemical_substance" or "drug"
      },
      {
        "curie": <named disease>,
        "id": "n1",
        "is_set": null,
        "type": "disease" or "phenotypic_feature"
      }
    ]
  }
```


2. What diseases is <named drug> indicated for? 
```
"query_graph": {
    "edges": [
      {
        "id": "e0",
        "negated": null,
        "relation": null,
        "source_id": "n0",
        "target_id": "n1",
        "type": "treats"
      }
    ],
    "nodes": [
      {
        "curie": <named drug>,
        "id": "n0",
        "is_set": null,
        "type": "chemical_substance" or "drug"
      },
      {
        "curie": null,
        "id": "n1",
        "is_set": null,
        "type": "disease" or "phenotypic_feature"
      }
    ]
  }
```


3. What drugs are contraindicated for <named disease>? 
```
"query_graph": {
    "edges": [
      {
        "id": "e0",
        "negated": null,
        "relation": null,
        "source_id": "n0",
        "target_id": "n1",
        "type": "contraindicated_for"
      }
    ],
    "nodes": [
      {
        "curie": null,
        "id": "n0",
        "is_set": null,
        "type": "chemical_substance" or "drug"
      },
      {
        "curie": <named disease>,
        "id": "n1",
        "is_set": null,
        "type": "disease" or "phenotypic_feature"
      }
    ]
  }
```

4. For what diseases is <named drug> be contraindicated for? 
```
"query_graph": {
    "edges": [
      {
        "id": "e0",
        "negated": null,
        "relation": null,
        "source_id": "n0",
        "target_id": "n1",
        "type": "contraindicated_for"
      }
    ],
    "nodes": [
      {
        "curie": <named drug>,
        "id": "n0",
        "is_set": null,
        "type": "chemical_substance" or "drug"
      },
      {
        "curie": null,
        "id": "n1",
        "is_set": null,
        "type": "disease" or "phenotypic_feature"
      }
    ]
  }
```



5. What drugs might treat <named disease>? 
```
"query_graph": {
    "edges": [
      {
        "id": "e0",
        "negated": null,
        "relation": null,
        "source_id": "n0",
        "target_id": "n1",
        "type": "treats"
      },
      {
        "id": "e1",
        "negated": null,
        "relation": null,
        "source_id": "n0",
        "target_id": "n1",
        "type": "prob_treats_disease"
      }
    ],
    "nodes": [
      {
        "curie": null,
        "id": "n0",
        "is_set": null,
        "type": "chemical_substance" or "drug"
      },
      {
        "curie": <named disease>,
        "id": "n1",
        "is_set": null,
        "type": "disease" or "phenotypic_feature"
      }
    ]
  }
```


6. What diseases might <named drug> be indicated for? 
```
"query_graph": {
    "edges": [
      {
        "id": "e0",
        "negated": null,
        "relation": null,
        "source_id": "n0",
        "target_id": "n1",
        "type": "treats"
      },
      {
        "id": "e1",
        "negated": null,
        "relation": null,
        "source_id": "n0",
        "target_id": "n1",
        "type": "prob_treats_disease"
      }
    ],
    "nodes": [
      {
        "curie": <named drug>,
        "id": "n0",
        "is_set": null,
        "type": "chemical_substance" or "drug"
      },
      {
        "curie": null,
        "id": "n1",
        "is_set": null,
        "type": "disease" or "phenotypic_feature"
      }
    ]
  }
```


7. What drugs might be contraindicated for <named disease>? 
```
"query_graph": {
    "edges": [
      {
        "id": "e0",
        "negated": null,
        "relation": null,
        "source_id": "n0",
        "target_id": "n1",
        "type": "contraindicated_for"
      },
      {
        "id": "e1",
        "negated": null,
        "relation": null,
        "source_id": "n0",
        "target_id": "n1",
        "type": "prob_treats_disease"
      }
    ],
    "nodes": [
      {
        "curie": null,
        "id": "n0",
        "is_set": null,
        "type": "chemical_substance" or "drug"
      },
      {
        "curie": <named disease>,
        "id": "n1",
        "is_set": null,
        "type": "disease" or "phenotypic_feature"
      }
    ]
  }
```

8. For what diseases might <named drug> be contraindicated for? 
```
"query_graph": {
    "edges": [
      {
        "id": "e0",
        "negated": null,
        "relation": null,
        "source_id": "n0",
        "target_id": "n1",
        "type": "contraindicated_for"
      },
      {
        "id": "e1",
        "negated": null,
        "relation": null,
        "source_id": "n0",
        "target_id": "n1",
        "type": "prob_treats_disease"
      }
    ],
    "nodes": [
      {
        "curie": <named drug>,
        "id": "n0",
        "is_set": null,
        "type": "chemical_substance" or "drug"
      },
      {
        "curie": null,
        "id": "n1",
        "is_set": null,
        "type": "disease" or "phenotypic_feature"
      }
    ]
  }
```

**Comment by finnagin** [comment]
So what I was thinking is by adding virtual edges into the query graph you are indicating that you are looking for more than just the known examples. So if `treats` is coupled with `prob_treats_disease` you are looking for highly ranked drugs that possibly treat a disease while if you couple `contraindicated_for` with `prob_treats_disease` you are looking for lowly ranked diseases. Though in the model we are predicting a not_treats relationship rather than contraindicated_for.

**Comment by edeutsch** [comment]
Some refinement and discussion occurred this afternoon in here:
https://docs.google.com/document/d/10qlDNGbIrPUM4qFeGIXklMUwqsQSb9S91X3q7rLzguA/edit

**Comment by edeutsch** [comment]
Floating here an idea that came to me after today's mini-hackathon:
It seems like we were in agreement that we wanted this:

add_qedge(id=e00, source_id=n00, target_id=n01, type=treats, not=true)

(where the not=true means that we want to filter out connections for which there is a direct "treats" connection)

We mused about having special relationship types like "is_predicted_to_treat"
and "are prescribed by doctors for patients with the disease"

but what about having an "origin=" attribute instead, so have:

add_qedge(id=e00, source_id=n00, target_id=n01, type=treats, origin=recorded_in_knowledge_bases)
or
add_qedge(id=e00, source_id=n00, target_id=n01, type=treats, origin=observed_in_medical_records)
or
add_qedge(id=e00, source_id=n00, target_id=n01, type=treats, origin=predicted_in_models)
or
add_qedge(id=e00, source_id=n00, target_id=n01, type=treats, origin=known)
or
add_qedge(id=e00, source_id=n00, target_id=n01, type=treats, origin=inferred)

This means we don't have to add additional predicates, but rather reuse the predicate types
but allow the querier to specify how the predicates originated.

So a way to express:

Which drugs might treat <named disease>, but not already known to treat it?

is (implied AND operation):

add_qedge(id=e00, source_id=n00, target_id=n01, type=treats, origin=inferred)
add_qedge(id=e01, source_id=n00, target_id=n01, type=treats, not=true, mechanism=known)

Which drugs do doctors use on patients with <named disease>, but not already known to treat it?

add_qedge(id=e00, source_id=n00, target_id=n01, type=treats, origin=observed_in_medical_records)
add_qedge(id=e01, source_id=n00, target_id=n01, type=treats, not=true, mechanism=known)

What do you think?

**Comment by finnagin** [comment]
I like the origin property idea. I think it could allow for a lot more flexibility without an explosion of new predicates.

**Comment by dkoslicki** [comment]
I quite like this idea too @edeutsch ! I imagine this will take quite a bit of re-tooling in `overlay` though, but should be worth it to do.

**Comment by dkoslicki** [comment]
Once #1119 is finished, how about variations that use `not` such as: find me drugs that might treat this disease but are not contraindicated and not already known to treat it.

**Comment by finnagin** [comment]
After meeting with David: Should think of new questions that incorporate not and/or optional groups.

**Comment by finnagin** [comment]
@dkoslicki is this still relevant?

**Comment by dkoslicki** [comment]
Nope!
