### ISSUE TITLE
Pull out ranker as its own DSL command

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1111]
Much interest has been generated regarding our ranker. Instead of having it be a sub-part of `resultify()` it would be good to:

1. Have it be a separate DSL command (so eventually others can invoke it)
2. But still have it automatically run in `resultify()` so user's don't mistakenly forget to invoke it.

**Comment by saramsey** [comment]
Cool, it sounds like a win (for Translator), to break it out.

**Comment by edeutsch** [comment]
I think I can do this.

One stray thought it that it might be that the ranker relies on some assumptions that it's getting the output of resultify(). If someone else's results don't quite conform to what resultify() does, it is possible that it is safer to recompute results first and then rerank?

What should the DSL command be?
1) rank()
2) rank_results()
3) rerank()
4) rankify()
5) hoowee_that_is_rank()

**Comment by dkoslicki** [comment]
While I love 4 and 5, I think 2 makes the most sense (as it's clear what is being ranked). Let @finnagin if he can help with issues about the the input results not conforming to what resultify() does

**Comment by finnagin** [comment]
So I added a command `rank_results()` that is just called without parameters and then runs the `aggregate_scores_dmk` method. I also added a `describe_me` method to the ARAXRanker class in so we can generate documentation for `rank_results`.

Is this what we were thinking in terms of how to implement this? Are there any options I should add? Is there any error checking that need to be added in now that ranker can be called without `resultify`?

**Comment by dkoslicki** [comment]
Thanks @finnagin ! I think having no options is fine at this point. Besides internal error handling, I think a warning should be given if no ranking is actually done (i.e. the KG has no edges with scalar information on them)

**Comment by finnagin** [comment]
Note to self: To test this, run resultify on an example with no edge attributes then add edge attributes after.

**Comment by dkoslicki** [comment]
The above test works, closing
