### ISSUE TITLE
Add a way of negating edges in a query graph

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1112]
idea from meeting:

q_edge(id=#, type=X)
q_edge(..., not=True) need to add this option

...

expand all as if not=False

Filter_kg will look through all connected nodes
and if those nodes are connected by a not edge 
remove all edges connecting them
Then also remove the not edges from the query graph

lastly run resultify which will need to be altered to ignore not edges

**Comment by dkoslicki** [comment]
See [this pdf](https://www.dropbox.com/s/agcoih75w8qcj0s/NCATS%20workflows.pdf?dl=0) for more details.

**Comment by finnagin** [comment]
So everything except the resultify part is implemented now. @saramsey when you get time could you update resultify in the filter branch so that when resultify is making sure that results conform to the query graph it ignores edges in the query_graph which have the property `not_edge` set to True?

**Comment by amykglen** [comment]
idea from 10/28/2020 minihackathon: handle `not` edges at the `expand` level - it would be pretty straightforward and then downstream modules don't need to be modified much (`resultify` could just effectively ignore any `not` edges in the query graph, and proceed as usual), and it'd save some computation, too.

note to self that once we add in `option_group` handling (#1113), will need to make sure that if a `not` edge goes between an optional node and a required node, it shouldn't blow away the required node... e.g., this case shouldn't blow away neutropenia:
<img width="708" alt="Screen Shot 2020-10-28 at 3 48 23 PM" src="https://user-images.githubusercontent.com/49423686/97505044-541bc800-1935-11eb-838e-29ee94345475.png">

**Comment by dkoslicki** [comment]
@finnagin any update on this issue? Or is it subsumed by #1119 ?

**Comment by finnagin** [comment]
@dkoslicki This was subsumed by #1119 but I think since the negated edges are already implemented in that branch we can probably close this issue out.
