### ISSUE TITLE
Add 'and' & 'or' logical operators for edges in the query graph

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1113]
Idea from the meeting: add a 'logical_operator' property to edges to encode this information which defaults to 'and' if not provided

**Comment by finnagin** [comment]
expand will need to altered to do optional match

resultify will also need to consider the optional match

**Comment by finnagin** [comment]
[and_not_or_workflow.pdf](https://github.com/RTXteam/RTX/files/5419091/and_not_or_workflow.pdf)

**Comment by edeutsch** [comment]
add_qedge(id=e00,source_id=n00,target_id=n01,not=True,operand=or/and)
or:
add_qedge(id=e00,source_id=n00,target_id=n01,operand=or/and/not)

**Comment by edeutsch** [comment]
add_qedge(id=e00,source_id=n00,target_id=n01,not=True,necessity=optional/required)
or:
add_qedge(id=e00,source_id=n00,target_id=n01,necessity=optional/required/not)

**Comment by dkoslicki** [comment]
Need one (or both) nodes attached to an `optional` edge, to have the property `optional`?

Btw, I like `add_qedge(id=e00,source_id=n00,target_id=n01,necessity=optional/required/not)`

**Comment by edeutsch** [comment]
https://docs.google.com/document/d/15Xo6KufZ6hr42gah-gVS2Uuwo6oeGckF5z20GcR9gLA/edit

**Comment by dkoslicki** [comment]
closing in favor of #1119
