### ISSUE TITLE
Update config.json schema to also accomadate databases downloads

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1116]
This will also require [RTXConfiguration.py](https://github.com/RTXteam/RTX/blob/master/code/RTXConfiguration.py) to be updated. Also, we should replace all hardcoded references to servers with RTXConfig calls.

**Comment by saramsey** [comment]
My $0.02: I think we should consider having two "areas" in the JSON file, one that could be called `global` and one that could be called `contexts` (or something like that). Under `global` we could store global name-value pairs that don't have a specific local context. Under `contexts` we would have specific contexts like `production`, `local`, etc. and underneath those, any name-value pairs that are context-specific.

The current JSON has a lot of stuff (like mysql stuff?) that is repeated verbatim under the `kg2` type headings, that seems redundant and probably confusing to someone who is looking at the JSON and doesn't know its history.

**Comment by edeutsch** [comment]
or define a "global" or "default" dict at the top of the file, and then just allow individual local contexts to override the global default only if desired. so if there's one mysql instance, then that can be defined in global, and only overridden in a certain context if desired.

I've also been thinking it would be valuable to allow a local override as a separate file. The standard file that gets autocopied every 24 hr would remain as is as config.json
but then the RTXConfirguration.py would, after reading config.json, look for config_local.json that would be purely maintained locally in some test instance and could override any values in the default config.json.
This might make local testing easier without the 24 hr stomping problem.

**Comment by finnagin** [comment]
@edeutsch +1 I like the `config_local.json` idea.

**Comment by finnagin** [comment]
@chunyuma In the script `create_probability_sqlite_database.py` There are the two following lines:

```
os.system("scp rtxconfig@arax.ncats.io:/data/orangeboard/databases/KG2.3.4/rel_max.emb.gz " + emb_file)
os.system("scp rtxconfig@arax.ncats.io:/data/orangeboard/databases/KG2.3.4/map.txt " + map_file)
```
But the files `rel_max.emb.gz` and `map.txt` are not in `/data/orangeboard/databases/KG2.3.4/` on arax.ncats.io.

Are these files that should be moved there from the old server?

**Comment by chunyuma** [comment]
Hi @finnagin, this script (`create_probability_sqlite_database.py`) is already deprecated because it needs to spend more than 20 days to update a new DTD probability database each time when we update KG2. I have another script which can run on computational cluster which I will push to the github later (I'm testing this script on PSU computational cluster but there are still some issues that I need to wait for PSU IT department to help me figure out). But `rel_max.emb.gz` and `map.txt` will still be needed in the new script. I think we didn't transfer them to `arax.ncats.io`. I have a backup for these two file locally and will upload them to `arax.ncats.io` later today.

**Comment by finnagin** [comment]
Awesome, thanks @chunyuma ! I'll update the configv2.json file to point to `/data/orangeboard/databases/KG2.3.4/rel_max.emb.gz` and `/data/orangeboard/databases/KG2.3.4/map.txt`

**Comment by dkoslicki** [comment]
From 11/9/20 meeting (relevant to #1099 as well)

1. For all KG build-dependent databases, the build versions should be encoded in the file name and in the database itself
2. All databases should be stored in a central location (such as `code/ARAX/KnowledgeSources`)

**Comment by saramsey** [comment]
Hi @finnagin can we get an update on this issue, when you have a chance? Would be good to see if we can get this done b/f we head into the relay (but sufficiently before the relay that we can fix any issues that arise with the roll-out, I suppose).

**Comment by finnagin** [comment]
@saramsey This is implemented and just needs to have newer updates in master merged into it and tested. There is some other work being done in this branch on issue #1149 but that is mostly in an additional snakemake file so should not effect the rest of ARAX if we want to try and roll it out right away before that work is done.

**Comment by dkoslicki** [comment]
Done
