### ISSUE TITLE
Kg2 Build /  Release Frequency

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1118]
This issue is a thread for discussion of the optimal timing of new KG2 Builds / releases :)

**Comment by saramsey** [comment]
I'm inclined to think that aiming for an approximately monthly build may provide a good balance of having an up-to-date "product", identifying problems (i.e., schema changes or new predicates in upstream sources) early, and labor cost to monitor, document, and check the build. ARAX is but one consumer of KG2; we also provide builds to Unsecret Agent and they are always hungry for new KG2 builds. It is of course fine if the ARAX team wants to aim for updating the KG2/KG2C that is built into ARAX on a less frequent basis (e.g., bimonthly). Does that make sense, @amykglen and @kvarforl ?

**Comment by saramsey** [comment]
Also, whatever we decide needn't be a permanent choice. We can always change the build tempo as needed. But I am interested to hear opinions on the matter. Previously, we had never been particularly intentional about the build frequency.

**Comment by amykglen** [comment]
monthly sounds like a good plan to me! seems like a reasonable balance, as you say.

totally agree that the decision for the build frequency needn't worry about ARAX's desired update frequency, since KG2 has multiple consumers (and monthly is more than enough for ARAX).

**Comment by kvarforl** [comment]
Sounds good to me as well! Speaking of Unsecret Agent... do I need to get a version of  KG2.3.5 to them?

**Comment by saramsey** [comment]
> Sounds good to me as well! Speaking of Unsecret Agent... do I need to get a version of KG2.3.5 to them?

I think probably not. Let's aim to ship them 2.4.0.

**Comment by saramsey** [comment]
see also #1200

**Comment by saramsey** [comment]
looks like we have a general consensus; noted in the KG2 README.md
