### ISSUE TITLE
OMIM data account expired

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1120]
Hi all,
I just got an email notification from OMIM (`do-not-reply@peas.welch.jhu.edu`) about "data account expired". Has anything broken in RTX/ARAX as a consequence of this?
I'm thinking this mostly affects our ability to run QueryOMIM.py, but I am not sure.
Steve
```
[This email originated from outside of OSU. Use caution with links and attachments.]

OMIM - Data Account Expired

This email is to confirm that your data account has expired.




Online Mendelian Inheritance in Man - OMIM
https://omim.org
```

**Comment by kvarforl** [comment]
whoops, mistyped the issue number in the commit above. That is actually associated with 1220. please disregard :)

**Comment by finnagin** [comment]
Closing since we don't use QueryOMIM.py anymore afaik.
