### ISSUE TITLE
Add Connections Hypothesis Provider (CHP) into our Expander

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1122]
This issue is for updating the progress of integrating the CHP into Expander.

- [x] Figure out how to query CHP
- [x] Create a new KP in `Expander` for CHP
- [x] implement in Expand folder
- [x] unit tests
- [x] integration tests

The links for CHP client and API documentation:

CHP Client: https://github.com/di2ag/chp_client
API Docs: https://github.com/di2ag/ConnectionsHypothesisProviderAPI

@amykglen, should I create a new branch built off from specific update-to-date branch (eg. `kg2-arax-integration`) for this? I know that `kg2-arax-integration` is gone now. So I guess we might have already merged it into `master` branch. So I might just need to make a new branch based on the `master` branch, right?

**Comment by amykglen** [comment]
@chunyuma - seems right to me to create a new branch off of `master` for this! (I'm not aware of a more up to date branch that it would make sense to branch off of at the moment.)

**Comment by yakaboskic** [comment]
Hi Chunyu, 

Following up on our meeting today, we have significantly optimized our runtime and fully support batch queries. For simple queries, i.e. one gene, one therapeutic, one disease, one outcome, our response time is <1 second for a 100 queries, and <4 seconds for a 1000 queries. 

You can view an example notebook at:
https://github.com/di2ag/chp_client/tree/main/notebooks

Would love to get a little bit of an integration going by the Feb Relay. 

Let me know if you need any help!

-Chase

**Comment by dkoslicki** [comment]
@chunyuma Can I get a status update on this issue?

**Comment by chunyuma** [comment]
Hi @dkoslicki, for this issue, as you can see the check list at the top, it’s almost done. I’ve already added this kp into expander module. And it should work now. Previously, I was just waiting for merging kg2.5integration into master because at that time we still have lots of issues regarding compatibility. Since right now we’ve already merged two branches, I can finish the rest part next week.

**Comment by chunyuma** [comment]
OK, CHP has been merged into Expander. This issue has been solved. 

Two examples about how to use CHP in Expander are [here](https://github.com/RTXteam/RTX/blob/884a253d33cb644ec3a20fa60fcc005b111037ef/code/ARAX/test/test_ARAX_expand.py#L613-L639).
