### ISSUE TITLE
Find and fix fallout from biolink-model.yaml updates

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1123]
1. Update biolink-model.yaml
2. run validate_predicate_remap_yaml.py
3. update predicate_remap.yaml to address discrepencies

**Comment by saramsey** [comment]
Thank you. The expected discrepancies are coming about because Richard B. added (in consultation with our team, and in a huge advance for Translator) a ton of predicate mappings into `biolink-model.yaml`. That work in the Biolink Model GitHub project is logged under their [issue 435](https://github.com/biolink/biolink-model/issues/435).
 
For an example commit related to this work, see https://github.com/biolink/biolink-model/commit/e6760a1610345d168fe932e9f23d3ba401cdf055

**Comment by kvarforl** [comment]
in an exciting update, I pulled down the latest [biolink-model.yaml](https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.yaml) from biolink's master branch and used it to run `validate_predicate_remap_yaml.py`, and didn't run into any issues!  The script I used is on kg2lindsey in the landing directory, so I might have @saramsey sanity check me before this issue is closed out :)

**Comment by saramsey** [comment]
maybe put the script that you wrote, to run the test, into misc-tools?

**Comment by saramsey** [comment]
```
    broad_mappings:
    close_mappings:
    exact_mappings:
    narrow_mappings:
    related_mappings:
```

**Comment by saramsey** [comment]
`exact_mappings` > `close_mappings`   >  ....  > `related_mappings`

**Comment by kvarforl** [comment]
brain dump from meeting with Steve: the validation script likely passed because it looks for the "mappings" slot in the biolink-model.yaml file, which has since been broken into the mappings categories listed above. If this is the case, then the validation script should be adjusted to look at the categories of mappings,  prioritizing the mappings based on their smaller category in this order.
> `exact_mappings` > `close_mappings` > .... > `related_mappings`

This way, if for some reason there is an external relation with an entry in  `close_mapping` and `exact_mapping`, we chose to use the `exact_mapping`.
The ordering of `narrow_mappings` and `broad_mappings` still needs to be determined; maybe look in the biolink PR and at some examples to figure that out.

**Comment by kvarforl** [comment]
Just a note: in my refactoring of `validate_predicate_remap_yaml.py`, I made the assumption that any term with an inverse mapping gets lumped into the same category of mapping that the non-inverse is in. 
For example, the biolink relation `has_part` has the inverse `part_of` in the biolink model. In the validation script, the `close_mappings` of `has_part` get appended to the `close_mappings` of `part_of` in the biolink_to_external_mappings dictionary. Hope this makes sense.

**Comment by kvarforl** [comment]
@saramsey Can you give me some background on why `skos:closeMatch` has it's own special case? I blindly added it to my edit of the script to get it working, but it would probably be good for me to understand what it's purpose is :)
This is what it looked like in the [old version](https://github.com/RTXteam/RTX/blob/78ff54732f1a877045704c9f446cfc2529fdd42d/code/kg2/validate_predicate_remap_yaml.py#L58) of the script: 
![image](https://user-images.githubusercontent.com/39020520/99157071-dec12e80-267a-11eb-9ba3-c64f2a14a509.png)

**Comment by kvarforl** [comment]
From my slack conversation with Richard B, it sounds like the goal is to not have any dual mappings in the biolink model, so the prioritization of each mapping term shouldn't be that important in the scheme of things. However, the validation script should work in either case now.

**Comment by saramsey** [comment]
Nice, thank you.

**Comment by saramsey** [comment]
Hi @kvarforl what do you think about the plan/timeline for doing a new build, after which we would (among other issues) validate this fix?

**Comment by kvarforl** [comment]
@saramsey I was thinking of starting a new build ASAP! Currently working on verifying which version of KG2 the production ARAX uses so I can figure out which instance to start it on without stepping on any build artifacts. Does that work for you?

**Comment by kvarforl** [comment]
This seemed to work well for the KG2.4.0 build! Closing.
