### ISSUE TITLE
Turn KG2 into a KP

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1129]
Steve mentioned that we will eventually need to turn KG2 into a translator KP. This will probably involve a lot of discussion / designing, but I'm starting this issue to document progress and ideas!

The general order of operations looks something like this:

1.  Find out the standardized requirements for a translator KP (I will do this and report back here)
2.  Discuss and figure out what the API should provide so that it can be useful without duplicating functionality
3.  Decide on what tooling to use and create the API 
4.  Register with SmartAPI

**Comment by edeutsch** [comment]
I was thinking that it should be a TRAPI 1.0 interface. I think this is required anyway, and there seems little point to developing another interface.
And I was thinking that we could pretty much use the existing ARAX codebase at a different endpoint with expand() to handle all this.
But I'm happy to discuss other ideas.

**Comment by kvarforl** [comment]
I stopped in to Biolink Help Desk hours this morning, and asked where I could find requirements for the interface of a KP. Deepak didn't point me to any specific resource, but he suggested following the [TrAPI](https://github.com/NCATSTranslator/ReasonerAPI/tree/master/API) specification. He also mentioned the options of using SmartAPI, or KG serialization to be determined in the KGE working group. 

My general understanding (from sleuthing through the Translator slack) is that TrAPI has more stringent requirements than just registering with SmartAPI, but it's also the most standardized (aka the easiest for other ARA's to access), so that's something to weigh. I'm pretty sure there hasn't been any official specification from KGE yet, so that's probably out for now.

**Comment by kvarforl** [comment]
From a KGE meeting a few months ago, I found these two options for API ifying a KG:

- [Plater](https://github.com/TranslatorSRI/plater) from SRI. The readme says it stands up a rest api over a neo4j database
- [BioThings Studio](https://docs.biothings.io/en/latest/doc/studio.html) has instructions (and tooling ?) for  "how to convert a simple flat file to a fully operational BioThings API". I'm not quite sure what format it expects to ingest, but might be worth looking into

**Comment by kvarforl** [comment]
> I was thinking that it should be a TRAPI 1.0 interface. I think this is required anyway, and there seems little point to developing another interface.
> And I was thinking that we could pretty much use the existing ARAX codebase at a different endpoint with expand() to handle all this.
> But I'm happy to discuss other ideas.

Sorry I missed this when I was commenting earlier! I don't have a ton of background knowledge on the whole project, and I trust your judgement :) Tagging @saramsey and @amykglen so they can weigh in

**Comment by amykglen** [comment]
yeah, I think what Eric said makes a lot of sense. our current system could achieve this by basically just running this DSL for every query graph that comes in, I think:
```
expand(kp=ARAX/KG2)
resultify()
```
so that seems to make sense to set up a different endpoint for doing that.

**Comment by kvarforl** [comment]
From the KGE WG meetings recently, particularly today (1/6/2021), it sounds like a centralized archive is being set up to store KGX dumps of knowledge graphs. From there, "Translator Archive will export “catalog” as one Translator SmartAPI entry per KGE file set". So once that's set up, it's probably a good route for KG sharing (especially because I think that it would expedite the medikanren export process) :) not sure if this is an "instead of" or just an "in addition to", but I thought I'd document it here while I'm thinking about it.

**Comment by saramsey** [comment]
> From the KGE WG meetings recently, particularly today (1/6/2021), it sounds like a centralized archive is being set up to store KGX dumps of knowledge graphs. From there, "Translator Archive will export “catalog” as one Translator SmartAPI entry per KGE file set". So once that's set up, it's probably a good route for KG sharing (especially because I think that it would expedite the medikanren export process) :) not sure if this is an "instead of" or just an "in addition to", but I thought I'd document it here while I'm thinking about it.

Hi @kvarforl thank you for reporting this. If they roll this out we will definitely want to provide a KG2 dump within the KGX framework.

**Comment by saramsey** [comment]
> I stopped in to Biolink Help Desk hours this morning, and asked where I could find requirements for the interface of a KP. Deepak didn't point me to any specific resource, but he suggested following the [TrAPI](https://github.com/NCATSTranslator/ReasonerAPI/tree/master/API) specification. He also mentioned the options of using SmartAPI, or KG serialization to be determined in the KGE working group.
> 
> My general understanding (from sleuthing through the Translator slack) is that TrAPI has more stringent requirements than just registering with SmartAPI, but it's also the most standardized (aka the easiest for other ARA's to access), so that's something to weigh. I'm pretty sure there hasn't been any official specification from KGE yet, so that's probably out for now.

Thank you, this is very helpful.

**Comment by saramsey** [comment]
I am curious if it might be possible to wrap a TRAPI interface around the Clojure host of KG2. I think from the TRAPI YAML spec, I can generate Clojure stubs by using the [swagger1st](https://github.com/zalando-stups/swagger1st) software. I already have a working Clojure/ring/jetty webhost of KG2.5.1 that I am querying (software is [here](https://github.com/RTXteam/kg2serv) currently in a private repo because the code is so experimental).
 Currently I am only doing simple queries but that could change. If the

**Comment by saramsey** [comment]
Note: Sarah Stemann from team Link Broker is inquiring about the status of this:  
https://github.com/NCATSTranslator/TranslatorPM/issues/52

**Comment by saramsey** [comment]
> I am curious if it might be possible to wrap a TRAPI interface around the Clojure host of KG2. I think from the TRAPI YAML spec, I can generate Clojure stubs by using the [swagger1st](https://github.com/zalando-stups/swagger1st) software. I already have a working JVM/Clojure/ring/jetty webhost of KG2.5.1 that I am querying (software is [here](https://github.com/RTXteam/kg2serv) currently in a private repo because the code is so experimental). Currently I am only doing simple queries but that could change. My load testing results suggest that the Clojure is a very nice way to host a fast in-memory, read-only graph DB. Apologies if these sound like the ravings of a madman...

Quick update:  I had high hopes that I could just run the TRAPI OpenAPI YAML through swagger1st and it would magically generate Clojure stubs. Instead, I got errors. So that particular avenue is blocked until I can find the cycles to diagnose the issue.

**Comment by saramsey** [comment]
> **IMPORTANT**: Team Link Broker is inquiring about the status of this:
> [NCATSTranslator/TranslatorPM#52](https://github.com/NCATSTranslator/TranslatorPM/issues/52)

See #1262 for one stopgap measure

**Comment by edeutsch** [comment]
So as discussed at the Wed AHM, the RTX KG2 endpoint is up and ready to go. But it could use some more testing. My testing has been admittedly thin. Also, before I register with with SmartAPI, maybe we could review the "branding" to make sure everyone is happy with it? Here is the endpoint:
https://arax.ncats.io/kg2/api/rtxkg2/v1.0/ui/

You'll notice that I've "branded" it "RTX KG2". I think this is what we had discussed/agreed in the past, but I'm not entirely certain. Just "KG2" seems too generic. We probably don't want "ARAX" in there, so that's where it is. OK?

The version stamp is 2.3.4 to reflect the underlying KG2 version. Although the URL is v1.0 to signify the TRAPI version. Maybe that's a little weird.

Perhaps @amykglen would be willing to set up an Expand() adapter to his this endpoint?

**Comment by saramsey** [comment]
Thank you @edeutsch!  The name RTX-KG2 seems reasonable and aligned with what people in the broader consortium are already calling it.  Good idea version-stamping it.

**Comment by edeutsch** [comment]
You're most welcome. I notice you put a dash in "RTX-KG2" where I have a space. Shall we squabble about that and settle one of the two?

**Comment by amykglen** [comment]
hey @edeutsch - I noticed that one can't tell from the `/predicates` endpoint that the KG2 API can answer queries involving category-less qnodes and predicate-less qedges (e.g., `(id: DOID:14330)--(category: None)`). wondering if future TRAPI versions might provide a way to detect that information? (like, maybe in the future `knowledge_map` endpoint?)

(it would be very helpful from the `expand` perspective if other KPs indicated this somewhere as well.)

**Comment by edeutsch** [comment]
ah, interesting question. I think we are on a path where the /meta_knowledge_graph (new name that we voted in on Thursday) encodes the metagraph of what the knowledge graph contains. But that seems like a separate question than what the query is permitted to specify. It is interesting to ponder the conceptual distinction between "what I know" and "what you can ask me". I will bring this up at the TRAPI call on Thursday, thanks! I wonder if adding the "related_to" predicate (https://biolink.github.io/biolink-model/docs/related_to.html) (which is the ultimate parent of all other predicates) would be a stand in for that. Maybe the /meta_knowledge_graph would specify that for all category pairs if such a query is allowed. And then with the planned predicate inheritance resolution scheme, related_to and null mean the same thing in this context and yield the same result.

**Comment by amykglen** [comment]
cool! true, that's an interesting idea - and I guess similarly, `NamedThing` could be a stand in for `QNode.category=None`...

**Comment by edeutsch** [comment]
@saramsey @kvarforl et al.: with @amykglen 's exceptional help, the RTX KG2 TRAPI 1.0 endpoint is complete and registered in SmartAPI.

SmartAPI entries:
https://smart-api.info/registry?q=RTX

OpenAPI endpoint UI:
https://arax.ncats.io/kg2/api/rtxkg2/v1.0/ui/

Special instance of the ARAX TRAPI UI that only queries RTX KG2 directly:
https://arax.ncats.io/kg2/

As mentioned on Slack, our main instance of ARAX is now accessing RTX KG2 via this TRAPI OpenAPI endpoint.

Please test and I leave it to @kvarforl or @saramsey to close this issue if they are satisfied.

**Comment by kvarforl** [comment]
Thanks so much for your work @edeutsch @amykglen !! 

Quick question: will updating this endpoint happen when ARAX migrates to using a new version of KG2, or should I learn how to do it and add it to the post build tasks?

**Comment by edeutsch** [comment]
Good question @kvarforl , ARAX and RTX KG2 are sufficiently intertwined that they will always be on the same version together. So when we decide to deploy 2.5.x, I will take care of upgrading both on the production server. You won't need to do anything.

**Comment by saramsey** [comment]
OK, are we ready to notify the sponsor on NCATS TranslatorPM issue 52?

**Comment by saramsey** [comment]
Outstanding work, everyone.

**Comment by edeutsch** [comment]
oh yah, I forgot to respond to Sarah on that. Will do so now.

**Comment by edeutsch** [comment]
done.
https://smart-api.info/registry?q=RTX

**Comment by saramsey** [comment]
> You're most welcome. I notice you put a dash in "RTX-KG2" where I have a space. Shall we squabble about that and settle one of the two?

Ah, good point. I have no preference. But I suspect one or the other was already selected in the meantime? Sorry for my belated reply.

**Comment by edeutsch** [comment]
Until now, as then, I have been using "RTX KG2" as the official name:
https://smart-api.info/registry?q=rtx

But it is still inconsistently used:
- I notice now that here it is caps with a dash: https://github.com/RTXteam/RTX#rtx-kg2
- In our actual TRAPI output, it says:
```
{
              "name": "is_defined_by",
              "value": "ARAX/KG2",
              "type": "biolink:Unknown",
              "url": null,
              "source": null
            }
```

I would welcome a definitive decision on what the official name of the product is, with all all desired upper/lower/symbols clearly decided/described.

**Comment by amykglen** [comment]
`expand` uses "ARAX/KG2" just because that's what was settled on in the very early days of ARAX, but I'll go ahead and change that once an official name is picked.

no preference between "RTX KG2" and "RTX-KG2" from me!
