### ISSUE TITLE
Assertion error when running UpdateNodesInfo.py

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#113]
rt@ip-172-31-43-220:~/kg-construction$ python3 UpdateNodesInfo.py
https://www.ebi.ac.uk/ols/api/ontologies/hp/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHP_0006963
Status code 404 for url: https://www.ebi.ac.uk/ols/api/ontologies/hp/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHP_0006963
https://www.ebi.ac.uk/ols/api/ontologies/aqtltrait/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FAQTLTrait_1085
Status code 404 for url: https://www.ebi.ac.uk/ols/api/ontologies/aqtltrait/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FAQTLTrait_1085
Traceback (most recent call last):
  File "UpdateNodesInfo.py", line 454, in <module>
    UpdateNodesInfo.update_disease_nodes_desc()
  File "UpdateNodesInfo.py", line 343, in update_disease_nodes_desc
    node['desc'] = QueryOMIM().disease_mim_to_description(node_id)
  File "/mnt/data/orangeboard/RTX/code/reasoningtool/kg-construction/QueryOMIMExtended.py", line 35, in __init__
    assert 200 == r.status_code
AssertionError

**Comment by DeqingQu** [comment]
The AssertionError occurred in the init function of QueryOMIM. If the status code is not 200, there may be an error in the authentication process.
```
    def __init__(self):
        url = QueryOMIM.API_BASE_URL + "/apiKey"
        session_data = {'apiKey': QueryOMIM.API_KEY,
                        'format': 'json'}
        r = requests.post(url, data=session_data)
        assert 200 == r.status_code
        self.cookie = r.cookies
```
However, when I run the code on the 'rtxsteve' container, it didn't happen again. @saramsey Could you tell me in which container the error occurred?

**Comment by saramsey** [comment]
I was running in a different EC2 instance (rtxsteve.saramsey.org).  I think OMIM was probably down for maintenance. I'm going to close this issue.

**Comment by saramsey** [comment]
Deqing, can you please modify the UpdateNodesInfo.py code so that you create a QueryOMIMExtended object only ONCE. Creating the object many times (as the code currently does, on line 343) is leading to the aforementioned assertion problem because sometimes we cannot make a new connection to the API.

**Comment by DeqingQu** [comment]
I just fixed the bug. It is my fault. The init function will be called so many times.

**Comment by saramsey** [comment]
@DeqingQu what is the status of testing this fix?  Did you test it?

**Comment by DeqingQu** [comment]
@saramsey I tested it on my local machine and all test cases are passed.
unknown rate = 51.88% (6470/12471)
