### ISSUE TITLE
Requested UI fixes

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1130]
Two suggest UI fixes:

1) Set the DSL example to:
```
add_qnode(name=acetaminophen, id=n0)
add_qnode(type=protein, id=n1)
add_qedge(source_id=n0, target_id=n1, id=e0)
expand(edge_id=e0,kp=ARAX/KG2)
overlay(action=compute_ngd, virtual_relation_label=N1, source_qnode_id=n0, target_qnode_id=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=50)
```

2) UI bug: repro:
- https://arax.ncats.io/devED/?m=3233
- Click on build a graph tab
- Now click on Messages
- See pencil and X persist:
![image](https://user-images.githubusercontent.com/12707718/99858895-68717000-2b43-11eb-8058-123f554c77e0.png)

**Comment by isbluis** [comment]
Updated and fixed.

**Comment by edeutsch** [comment]
Looks good, thanks!
