### ISSUE TITLE
QGI now switched to KG2

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1132]
I have switched the QueryGraphInterpreter to always use KG2 now for all templates.
And I have limited all query results to 50, because otherwise there can be browser bloat problems.

This has been rolled out for /test and /beta and /devED.
But NOT production.

Please test and report your findings.

**Comment by amykglen** [comment]
I've tested various JSON queries on `/test` and `/beta` and all is looking good to me. haven't observed any issues.

**Comment by edeutsch** [comment]
Either everything is fine or tests are insufficient to detect a problem. Closing.
