### ISSUE TITLE
Query Test case: Current Phase 3+ Approved Treatments for Alzheimer’s Disease - Unsecret Agent

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1134]
Testing some of the other ARAs questions on ARAX to see how it goes.

Start with an easy (?) one:
Current Phase 3+ Approved Treatments for Alzheimer’s Disease - Unsecret Agent
https://github.com/NCATSTranslator/Relay/wiki/Use-Cases#current-phase-3-approved-treatments-for-alzheimers-disease---unsecret-agent

```
{ "message": { "query_graph": { "nodes": [ { "id": "n1", "type": "biolink:Drug" }, { "id": "n2", "curie": "UMLS:C0002395" } ], "edges": [ { "id": "e1", "type": "clinically_tested_approved_unknown_phase", "source_id": "n1", "target_id": "n2" } ] } } }
```

First snag is that they use biolink:Drug whereas we use drug.
I pushed a temporary fix that remaps "biolink:PascalCase" to "snake_case", which fixes that.

Still no results.
The next issue is their edge type: "type": "clinically_tested_approved_unknown_phase"
Presumably we don't have that.

I replaced that with "treats":
```
{ "nodes": [ { "id": "n1", "type": "drug" }, { "id": "n2", "curie": "UMLS:C0002395" } ], "edges": [ { "id": "e1", "type": "treats", "source_id": "n1", "target_id": "n2" } ] }
```

This produces a result.
https://arax.ncats.io/devED/?m=3263
But doesn't quite capture the original question.

Do we have a way of expressing the original question in a way that it can be answered?
i.e. can we express "Current Phase 3+ Approved Treatments"?
Or does "treats" mean that?

Otherwise, how do we like the answer that came back with just "treats"?

**Comment by finnagin** [comment]
Closing since this is so old now.
