### ISSUE TITLE
Incorrectly merged nodes in KG2C

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1137]
eg: CHEMBL.COMPOUND:CHEMBL1200806 (a cancer drug) is merged with CHEMBL.COMPOUND:CHEMBL154 (naproxen)

**Comment by amykglen** [comment]
hmm, I'm seeing that CHEMBL.COMPOUND:CHEMBL1200806 is "naproxen sodium": https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1200806/

seems somewhat reasonable that it's merged with "naproxen"?

**Comment by dkoslicki** [comment]
Ah, I see. Google failed me (the cancer drug was the first google hit associated to that CURIE). I'll close.
