### ISSUE TITLE
DTD reverting to slow method?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1138]
For this JSON query:
```json
{ "edges": [ { "id": "qg3", "negated": null, "relation": null, "source_id": "qg1", "target_id": "qg2", "type": "molecularly_interacts_with" }, { "id": "qg4", "negated": null, "relation": null, "source_id": "qg2", "target_id": "qg0", "type": null } ], "nodes": [ { "id": "qg0", "is_set": null, "name": "neutropenia", "curie": "MONDO:0001475", "type": "disease" }, { "id": "qg1", "is_set": null, "name": null, "desc": "Generic chemical_substance", "curie": null, "type": "chemical_substance" }, { "id": "qg2", "is_set": "true", "name": null, "desc": "Generic protein", "curie": null, "type": "protein" } ] }
```
it appears that the DTD model is the thing that is slowing down the query the most. Hypothesis is that it might be caused by this query going through the query graph interpreter and is using an expand with both KG2C and BTE. Perhaps we shouldn't revert to the slow method if something is not in the DTD database? Or else synonymize to the KG2C id's and then use the database. Don't bother with curies that don't synonymize to entries in the DTD database.

**Comment by chunyuma** [comment]
For the new version of `predict_drug_treats_disease.py` script, it doesn't revert to the old method (the slow one) if something is not in the DTD database or no normalized id from `NodeSynonymizer` script. Instead, those IDs should be directly ignored. Please check [here](https://github.com/RTXteam/RTX/blob/2260e3cf250076bf14428d0c0c22076f1068eae6/code/ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py#L138-L146). So the reason for slow might not be due to this reason you hypothesize. But if I have DSL query for this case, I might be able to check the reason.

**Comment by dkoslicki** [comment]
@chunyuma here is the DSL
```
add_qnode(id=qg0,curie=MONDO:0001475,type=disease)
add_qnode(id=qg1,type=chemical_substance)
add_qnode(id=qg2,type=protein,is_set=true)
add_qedge(id=qg3,source_id=qg1,target_id=qg2,type=molecularly_interacts_with)
add_qedge(id=qg4,source_id=qg2,target_id=qg0)
expand(edge_id=[qg4,qg3], kp=ARAX/KG2, continue_if_no_results=true)
expand(edge_id=qg4, kp=BTE, continue_if_no_results=true)
overlay(action=compute_jaccard, start_node_id=qg0, intermediate_node_id=qg2, end_node_id=qg1, virtual_relation_label=J1)
overlay(action=predict_drug_treats_disease, source_qnode_id=qg1, target_qnode_id=qg0, virtual_relation_label=P1)
overlay(action=overlay_clinical_info, chi_square=true, virtual_relation_label=C1, source_qnode_id=qg0, target_qnode_id=qg1)
overlay(action=compute_ngd, virtual_relation_label=N1, source_qnode_id=qg0, target_qnode_id=qg2)
overlay(action=compute_ngd, virtual_relation_label=N2, source_qnode_id=qg0, target_qnode_id=qg1)
overlay(action=compute_ngd, virtual_relation_label=N3, source_qnode_id=qg2, target_qnode_id=qg1)
resultify(ignore_edge_direction=true)
filter_results(action=limit_number_of_results, max_results=100)
```

**Comment by dkoslicki** [comment]
Curious! I wonder if it's a caching reason: re-running the query shows it goes much faster. Do you have an estimate of how long, say, 100 queries to the DTD database take (maybe from randomly sampling pairs that are actually in the database)?

**Comment by chunyuma** [comment]
I'm just curious why you think that the DTD model database is the thing that is slowing down the query the most. It should not have a cache operation for querying DTD model database. Based on my simple investigation, querying only one pair from DTD database just needs <0.01s. In this case, we need to query 1190 pairs of curies. So it needs around 10s. However, I found that the most time-consuming part of this query is not `predict_drug_treats_disease` but `compute_ngd`. 

Below is the summary of how long each part needs to take in this query:
`expand`: ~32s
`predict_drug_treats_disease`: ~10s
`overlay_clinical_info`: 0.2s
`compute_ngd`: ~5 min

**Comment by dkoslicki** [comment]
Apologies for taking a while to get back on this issue @chunyuma (as we figured it out during the mini-hackathon, and I forgot there was an associated issue). It does indeed look like a red herring: perhaps when I first ran the query, the system was under heavy use or something like that, since I am finding the DTD blazingly fast now. Closing as currently a non-issue.
