### ISSUE TITLE
Should expand default be KG2(C) instead of KG1?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1139]
Currently, it appears that the default for expand is KG1. Since KG1 is basically depreciated, should we make the default KG2?

**Comment by amykglen** [comment]
good question - seems it probably should be switched to KG2! note that I think this would slow down many of our pytests, unless I went through and added `kp=ARAX/KG1` to those with no KP specified (which would be easy enough to do).

**Comment by edeutsch** [comment]
Seems good to me. It may also make many of the tests appear to fail because many seem to have the number of expected results from KG1 asserted in the test, and those would be different.

**Comment by amykglen** [comment]
ok, cool. I think I'll make the switch but add `kp=ARAX/KG1` to tests without a KP specified; then we can avoid slowness/failing tests, and individual test owners can decide whether/when to switch particular tests to KG2 at their own leisure.

**Comment by amykglen** [comment]
alright, this change is in `master` with all pytests passing.

**Comment by amykglen** [comment]
looks good on production!
