### ISSUE TITLE
KG2.4.0 with the `category` field as the Neo4j label and `simplified_relation` as the Neo4j relationship type

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1142]
Hi @kvarforl in preparation for our January 15 deadline from NCATS, we will need to stand up a new version of KG2 (2.4.0) in Neo4j that has the following changes:

1. For nodes, the `category` property should now be used as the Neo4j node `label`.
2. For relationships, the `simplified_relation` property should be used as the Neo4j relationship type.

This will likely require changes to `kg_json_to_tsv.py` only, I think?  I am tagging @finnagin who can advise on any technical details.

**Comment by saramsey** [comment]
Please keep @amykglen and @edeutsch advised of progress on this issue, since @amykglen 's Expand and KG2c code will depend on having this new version of KG2 stood up. Please feel free to provision a new AWS EC2 instance in `us-east-2` for the neo4j host; you can model the instance type and amount of storage on what we are currently using for `kg2endpoint-kg2-3-5.rtx.ai`. Thanks, Steve

**Comment by saramsey** [comment]
The `kg2-versions.md` file will also need to be updated, of course.

**Comment by saramsey** [comment]
Just to be clear, Amy and Eric will have a bunch of work to do downstream of this (fixing a ton of cypher queries in our codebase, etc.) ahead of the 1/15 deadline, so that's why this upstream work on KG2/Neo4j is kind of time-sensitive even though the deadline is six weeks away.

**Comment by kvarforl** [comment]
@saramsey Can I use kg2steve for this build so I don't step on the build artifacts of KG2.3.5 on kg2lindsey, or should I provision another instance?

**Comment by saramsey** [comment]
Yes, absolutely

**Comment by kvarforl** [comment]
Looking for validation from @finnagin: I made the following changes to `kg_json_to_tsv.py`.  Will this change what neo4j uses as the label and relationship type?

the diff for nodes, in the nodes function:
```diff
             nodekeys = no_space('id', nodekeys, 'id:ID')
             nodekeys = no_space('publications', nodekeys, "publications:string[]")
             nodekeys = no_space('synonym', nodekeys, "synonym:string[]")
-            nodekeys = no_space('category_label', nodekeys, ':LABEL')
+            nodekeys = no_space('category', nodekeys, ':LABEL')
             tsvwrite_h.writerow(nodekeys)
         tsvwrite.writerow(vallist)
```

the diff for relationships, in the edges function:
```diff
 edgekeys = no_space('provided_by', edgekeys, 'provided_by:string[]')
-            edgekeys = no_space('simplified_edge_label', edgekeys, 'edge_label:TYPE')
+            edgekeys = no_space('simplified_relation', edgekeys, 'edge_label:TYPE')
             edgekeys = no_space('subject', edgekeys, ':START_ID')
             edgekeys = no_space('object', edgekeys, ':END_ID')
             edgekeys = no_space('publications', edgekeys, "publications:string[]")
```

**Comment by kvarforl** [comment]
@saramsey I noticed on the AHM agenda for this week's meeting someone linked the script that I wrote to filter drugs by FDA approval. Issue #1050 was made to see if we could figure out how to add that information to KG2 nodes themselves: would it be worth the time trade off to try to get that into KG2.4.0 before I kick it off, or just save it for KG2.4.1?

**Comment by saramsey** [comment]
Wondering if we should also fold a fix for #1126 into this fix

**Comment by edeutsch** [comment]
I am uncertain what is the best way to model this, but I am under the impression that the FDA approves a drug to treat a specific condition, so having an edge that specifically means that the FDA has approved this drug for this condition seems appropriate. Separately, it is probably also useful to know if a drug has been approved for any use at all. Since MDs may then prescribe the drug for another use if they see fit. And such drugs are most easily repurposed since safety has been demonstrated.

So perhaps both a node attribute as well as a specific edge type are appropriate.

I think it would be nice if this could be in 2.4.0, but I don't feel strongly about it.

**Comment by saramsey** [comment]
> @saramsey I noticed on the AHM agenda for this week's meeting someone linked the script that I wrote to filter drugs by FDA approval. Issue #1050 was made to see if we could figure out how to add that information to KG2 nodes themselves: would it be worth the time trade off to try to get that into KG2.4.0 before I kick it off, or just save it for KG2.4.1?

I think REPODB is already ETL'd into KG2, so that may be enough for the doing the kinds of things that are shown in the Alzheimer's use-case  https://github.com/RTXteam/RTX/tree/master/code/kg2/mediKanren#generate-index-files

**Comment by finnagin** [comment]
@kvarforl Those changes look good to me! I believe that should work.

**Comment by kvarforl** [comment]
KG2.4.0 is available at [http://kg2endpoint-kg2-4-0.rtx.ai:7474/browser/](http://kg2endpoint-kg2-4-0.rtx.ai:7474/browser/), with build artifacts on kg2lindsey.rtx.ai. Closing this issue now :)
