### ISSUE TITLE
Move kg2endpoint.rtx.ai to us-west-2 when KG2.5.1 is in production.

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1143]
Trung (from NCATS) has informed me that `arax.ncats.io` is hosted in the `us-west-2` AWS zone. I'm thinking that from a network latency standpoint and overall system reliability standpoint, it makes sense to have our production KG2 endpoint in the same AWS zone. Currently, I believe all our KG2 Neo4j endpoints are hosted in the `us-east-2` zone. What do you think? Given what a pain it is to transfer a big AMI from one AWS zone to another, I'm thinking it may just be easiest to set up a new, empty Ubuntu instance in `us-west-2` and then to install Neo4j and set it up with KG2 using our usual `tsv-to-neo4j.sh` script.  

And @amykglen what about KG2c?

**Comment by saramsey** [comment]
Tagging @edeutsch and @amykglen for their input

**Comment by edeutsch** [comment]
I am not concerned about latency or reliability between zones, so whatever you want to do in fine with me. IMO, slowness and instability inherent in our codebase is 100x worse than AWS infrastructure.

**Comment by saramsey** [comment]
OK, anyone else want to weigh in?  Otherwise I will close this issue.

**Comment by amykglen** [comment]
I'm not too opinionated here either. and actually, it's primarily KG2c (vs. KG2) that ARAX queries (since `expand` uses KG2c if `use_synonyms=true`), and the current production KG2c _is_ hosted on a `us-west-2` instance.

**Comment by saramsey** [comment]
I think we should slowly migrate all our KG2 nodes to `us-west-2`, but I'm in no hurry. We can move them when it is convenient.

**Comment by saramsey** [comment]
The current production KG2 is 2.3.4, which is hosted on `kg2endpoint.rtx.ai` in `us-east-2`. A new KG, 2.5.1, is being hosted on `kg2endpoint3.rtx.ai` in `us-west-2`. When we switch ARAX over to point to the new (2.5.1) endpoint, my plan is to shut down the `kg2endpoint.rtx.ai` instance in `us-east-2`. This should not leave us "short" because we still have a second instance that we can use as a Neo4j endpoint for testing new KG2 builds (`kg2endpoint2.rtx.ai`, which is in `us-west-2`).

**Comment by finnagin** [comment]
No issues here!

**Comment by kvarforl** [comment]
I'm going to close this issue now that we're officially migrated to KG2.5.2! `kg2endpoint.rtx.ai` is still in `us-east-2` but should not need to be used since we have two other endpoint instances in `us-west-2`. I'll terminate the instance in `us-east-2` in about a week after I've got extra confirmation that it's not needed.
