### ISSUE TITLE
Abstract Entity category no longer in biolink model ?

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1144]
`validate_curies_to_categories_yaml.py` fails with the following
```
File "/home/ubuntu/kg2-code/validate_curies_to_categories_yaml.py", line 56, in <module>
    assert category_camelcase in biolink_categories_ontology_depths or category_curie in biolink_ont.nodes(), category_camelcase
AssertionError: AbstractEntity
```
I'm looking through the biolink model for a suitable replacement

**Comment by kvarforl** [comment]
I changed everything in `curies-to-categories.yaml` that used to map to `abstract entity` to map to `named thing`.

Now I'm running into a similar issue with `provider`, which is confusing because it's in biolink-model.yaml (see [this](https://github.com/biolink/biolink-model/blob/5767eb620edc003d69ebc78625c8addf0c34c35e/biolink-model.yaml#L1240) line).

@saramsey  do you have any ideas?

**Comment by kvarforl** [comment]
from inspecting into [biolink-model.owl.ttl](https://github.com/biolink/biolink-model/blob/master/biolink-model.owl.ttl), it seems like it might be because `provider` is an [ObjectProperty](https://github.com/biolink/biolink-model/blob/5767eb620edc003d69ebc78625c8addf0c34c35e/biolink-model.owl.ttl#L2302) instead of a [Class](https://github.com/biolink/biolink-model/blob/5767eb620edc003d69ebc78625c8addf0c34c35e/biolink-model.owl.ttl#L5794), but I'm very unsure

**Comment by saramsey** [comment]
Instead of `provider`, how about `agent` ?

https://biolink.github.io/biolink-model/docs/Agent.html

**Comment by saramsey** [comment]
For `abstract entity`, I concur, let's go with `named thing`. Thank you for driving this forward. Good sleuthing work.

**Comment by kvarforl** [comment]
Thanks for the feedback!
