### ISSUE TITLE
`rtx_kg1_neo4j_to_kg_json.py` gets 401 when trying to access http://arax.rtx.ai:7474/db/data/cypher

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1145]
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/rtx_kg1_neo4j_to_kg_json.py", line 129, in <module>
    test_mode)
  File "/home/ubuntu/kg2-code/rtx_kg1_neo4j_to_kg_json.py", line 83, in query_neo4j
    raise Exception('HTTP response status code: ' + str(status_code) + ' for URL: ' + http_uri)
Exception: HTTP response status code: 401 for URL: http://arax.rtx.ai:7474/db/data/cypher
```

**Comment by saramsey** [comment]
The URL needs to be changed from

http://arax.rtx.ai:7474/db/data/cypher

to

http://arax.ncats.io:7474/db/data/cypher

**Comment by kvarforl** [comment]
This fixed it! I updated my local version of the config file. Should this change be made to the master config file too?

**Comment by saramsey** [comment]
> This fixed it! I updated my local version of the config file. Should this change be made to the master config file too?

Yes, thank you for asking. I think the procedure would be (on the build system, in EC2) to do something like this:
```
aws s3 cp s3://rtx-kg2/RTXConfiguration-config.json /tmp
sed -i '/arax.rtx.ai/arax.ncats.io'  /tmp/RTXConfiguration-config.json
aws s3 cp /tmp/RTXConfiguration-config.json s3://rtx-kg2/
```

(I've probably got the sed syntax wrong, but you get the idea). You can just directly edit the file if you like.

**Comment by kvarforl** [comment]
Okay I updated the master config file and made it through this step for the KG2.4.0 build today, 12-5-2020. Closing this out.
