### ISSUE TITLE
resultify problem with dead-end intermediate nodes

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1146]
for some reason this query is producing results with extraneous/dead-end intermediate nodes:

```
add_qnode(id=n0,curie=MONDO:0001475,type=disease)
add_qnode(id=n2,type=chemical_substance)
add_qnode(id=n1,type=protein,is_set=true)
add_qedge(id=e0,source_id=n2,target_id=n1,type=physically_interacts_with)
add_qedge(id=e1,source_id=n1,target_id=n0)
expand(kp=ARAX/KG1)
overlay(action=compute_ngd, virtual_relation_label=N2, source_qnode_id=n0, target_qnode_id=n2)
resultify()
filter_results(action=limit_number_of_results, max_results=2)
```

https://arax.ncats.io/?m=3326
<img width="919" alt="Screen Shot 2020-12-03 at 10 50 13 PM" src="https://user-images.githubusercontent.com/49423686/101131313-ee68ce80-35b9-11eb-914a-a319abe9d330.png">

but if I swap the order of the `add_qnode()` lines for n1 and n2, the problem disappears:
```
add_qnode(id=n0,curie=MONDO:0001475,type=disease)
add_qnode(id=n1,type=protein,is_set=true)
add_qnode(id=n2,type=chemical_substance)
add_qedge(id=e0,source_id=n2,target_id=n1,type=physically_interacts_with)
add_qedge(id=e1,source_id=n1,target_id=n0)
expand(kp=ARAX/KG1)
overlay(action=compute_ngd, virtual_relation_label=N2, source_qnode_id=n0, target_qnode_id=n2)
resultify()
filter_results(action=limit_number_of_results, max_results=2)
```

https://arax.ncats.io/?m=3327
<img width="903" alt="Screen Shot 2020-12-03 at 10 51 35 PM" src="https://user-images.githubusercontent.com/49423686/101131435-253ee480-35ba-11eb-8f5c-bb7c6aef9bb6.png">

note: this issue was present on production **before** the rollout this evening (not related to those changes).

**Comment by saramsey** [comment]
This one piques my curiosity. I wonder why the order of the addition of the query nodes in the DSL should matter. I guess the query graph object has the query nodes as a list, which has a defined order, and something in Resultify was depending in some odd way on the particular *order* of items in the query node list?  Is that right?  (I know, I should probably just read the code).

**Comment by amykglen** [comment]
yep, there was a bug in my code making it sensitive to the order query nodes were added to the QG in. I have most of a fix implemented in the `issue1146` branch (still finishing up a couple pieces).

**Comment by amykglen** [comment]
alright - fix is complete and merged into `master`. entire pytest suite is passing for me locally.

can you roll `master` out to `/test` when you have time, @edeutsch?

**Comment by edeutsch** [comment]
sure, it is now rolled out to /test and oops, actually all deployments including production because I read your message to hastily.
Let me know if there are any problems.

**Comment by amykglen** [comment]
oh cool - works for me! all looks good on production - no issues. thanks!
