### ISSUE TITLE
FET p-values aren't considered by ARAXRanker?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1147]
this query, which is overlaid with Fisher Exact Test p-values, seems to produce unranked results, even though the p-values are indeed different for different results:
```
add_qnode(id=n00,curie=UniProtKB:P14136,type=protein)
add_qnode(type=biological_process, id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00,kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n00, target_qnode_id=n01, virtual_relation_label=FET)
resultify()
```
https://arax.ncats.io/?m=3345
![Screen Shot 2020-12-05 at 10 11 55 AM](https://user-images.githubusercontent.com/49423686/101260115-5581a280-36e2-11eb-9c27-7d97f1992d77.png)

wondering if the ranker doesn't know to consider FET p-values in its magic?

**Comment by dkoslicki** [comment]
Changing assignment to myself and @finnagin . Should be as easy as making a custom logistic for these, and mirroring the way we handle other p-values.

**Comment by dkoslicki** [comment]
Now that logistic parameters have been set, to get an empirical distribution of FET p-values, for drugs known to treat a disease, run FET on drug->protein->pathway->protein->disease. Then make sure the histogram of p-values are left skewed. Also, for drugs contraindicated for disease, make sure FET values are right skewed.
