### ISSUE TITLE
`multi_ont_to_json_kg.py` fails

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1148]
The script `multi_ont_to_json_kg.py` is failing: the log file `~/kg2-build/build-kg2-ont-stderr.log` has the following conent:
```
  1 Node with ontology_node_id http://purl.bioontology.org/ontology/HL7/C0033590 does not have a category and has tui T091
  2 Node with ontology_node_id MEDDRA:10021503 does not have a category and has tui T091
  3 Node with ontology_node_id http://purl.bioontology.org/ontology/MEDLINEPLUS/C0041186 does not have a category and has tui T091
  4 Node with ontology_node_id http://purl.bioontology.org/ontology/MEDLINEPLUS/C0029087 does not have a category and has tui T091
  5 Node with ontology_node_id http://purl.bioontology.org/ontology/MEDLINEPLUS/C0002346 does not have a category and has tui T091
  6 Node with ontology_node_id http://purl.bioontology.org/ontology/MEDLINEPLUS/C0005489 does not have a category and has tui T091
  7 Node with ontology_node_id http://purl.bioontology.org/ontology/MEDLINEPLUS/C1513058 does not have a category and has tui T091
  8 Node with ontology_node_id http://purl.bioontology.org/ontology/MEDLINEPLUS/C2350258 does not have a category and has tui T091
  9 Node with ontology_node_id http://purl.bioontology.org/ontology/MEDLINEPLUS/C0042615 does not have a category and has tui T091
 10 Node with ontology_node_id http://purl.bioontology.org/ontology/MEDLINEPLUS/C0011627 does not have a category and has tui T091
 11 Node with ontology_node_id http://purl.bioontology.org/ontology/MEDLINEPLUS/C0278627 does not have a category and has tui T091
 12 Node with ontology_node_id http://purl.bioontology.org/ontology/MEDLINEPLUS/C0030755 does not have a category and has tui T091
 13 [http://purl.bioontology.org/ontology/MSH/] unexpected None category depth for category activity and behavior: MESH:D019954
 14 [http://purl.bioontology.org/ontology/MSH/] unexpected None category depth for category activity and behavior: MESH:D011593
 15 [http://purl.bioontology.org/ontology/MSH/] unexpected None category depth for category activity and behavior: MESH:D026684
 16 [http://purl.bioontology.org/ontology/MSH/] unexpected None category depth for category activity and behavior: MESH:D003142
 17 [http://purl.bioontology.org/ontology/MSH/] unexpected None category depth for category activity and behavior: MESH:D013315
 18 [http://purl.bioontology.org/ontology/MSH/] unexpected None category depth for category activity and behavior: MESH:D005190
 19 [http://purl.bioontology.org/ontology/MSH/] unexpected None category depth for category activity and behavior: MESH:D001294
 20 [http://purl.bioontology.org/ontology/MSH/] unexpected None category depth for category activity and behavior: MESH:D015444
 21 [http://purl.bioontology.org/ontology/MSH/] unexpected None category depth for category activity and behavior: MESH:D008607
 22 [http://purl.bioontology.org/ontology/MSH/] unexpected None category depth for category activity and behavior: MESH:D011593
 23 Traceback (most recent call last):
 24   File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1208, in <module>
 25     save_pickle)
 26   File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 148, in make_kg2
 27     curie_to_uri_expander)
 28   File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 749, in make_nodes_dict_from_ontologies_list
 29     node_tui_category_label = get_category_for_multiple_tui(biolink_category_tree, node_tui_list, mappings_to_categories)
 30   File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 475, in get_category_for_multiple_tui
 31     return find_common_ancestor(tui_categories, biolink_category_tree)
 32   File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 456, in find_common_ancestor
 33     path_list2)
 34   File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 389, in compare_two_lists_in_reverse
 35     return shortlist[shortlist.index(short_item) + 1]
 36 IndexError: list index out of range
```

This seems somewhat similar to the bottom half of #1102 from the previous build becasue it dies shortly after reading `genepio.json`, but I'm not entirely sure whats wrong. perhaps something is wrong with reading and parsing the biolink model file? it did change from being a `.owl` to `.owl.ttl`, but I'm not entirely sure what the difference is. I'll try to look into it, but hoping for assistance from @saramsey : )

**Comment by kvarforl** [comment]
Okay from my python interpreter investigations everything before the call to `make_kg2(..)` call seems to have loaded fine ...
```vim
ubuntu@ip-172-31-59-26:~$ /home/ubuntu/kg2-venv/bin/python3 -u -i /home/ubuntu/kg2-code/multi_ont_to_json_kg-TEST.py /home/ubuntu/kg2-code/curies-to-categories.yaml /home/ubuntu/kg2-code/curies-to-urls-map.yaml /home/ubuntu/kg2-code/ont-load-inventory.yaml /home/ubuntu/kg2-build/kg2-ont.json
>>> type(ont_urls_and_files)
<class 'tuple'>
>>> len(ont_urls_and_files)
54
>>> type(curie_to_uri_expander)
<class 'function'>
>>> type(curies_to_categories)
<class 'dict'>
>>> len(curies_to_categories.keys())
2
>>> print(curies_to_categories.keys())
dict_keys(['prefix-mappings', 'term-mappings'])
>>> 
```

**Comment by saramsey** [comment]
Hi @kvarforl thank you for bringing this to my attention.

What evidence leads us to believe it is reading a `.owl.ttl` file?  I would think that it reads a `.ttl` file.

Also, what evidence indicates that it is dying on `genepio.json`?  If we know that, we have a big leg up on solving this issue. We can construct a `ont-load-inventory-test.yaml` and have that YAML file reference just `biolink-model.owl` and `genepio.owl`. That should make testing/debugging much faster.

**Comment by kvarforl** [comment]
the end of `build-multi-ont-kg.log` looks like this:
```
Reading ontology JSON file: ino.json; size: 495.96 KiB
file: ino.owl; last modified: 2020-12-06 01:35:15 GMT
http://purl.obolibrary.org/obo/genepio.owl
Reading ontology file: genepio.owl; size: 894.60 KiB
/usr/bin/java -Xms2G -Xmx249G -DentityExpansionLimit=4086000 -Djava.awt.headless=true -classpath /home/ubuntu/kg2-build/owltools owltools.cli.CommandLineInterface genepio.owl -o -f json /tmp/kg2-rleb2ykz.json
Reading ontology JSON file: genepio.json; size: 4835.80 KiB
file: genepio.owl; last modified: 2020-12-06 01:35:20 GMT
Calling make_nodes_dict_from_ontologies_list
```
which is why I think `genepio` is causing issues.

As far as the new biolink-model file extension, it seems like `biolink-model.owl` isn't in the  [Biolink Model Repository](https://github.com/biolink/biolink-model) anymore: the closest that I see if `biolink-model.owl.ttl`. (I changed the biolink slot in `ont-load-inventory.yaml` to grab `biolink-model.owl.ttl`)


Makind a test version of `ont-load-inventory.yaml` is a really good idea! I'll try that and see what happens.

**Comment by kvarforl** [comment]
Okay interesting... I created a test file as suggested to look like
```yaml
- # maps to CURIE prefix: biolink
  url: https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.owl.ttl
  file: biolink-model.owl.ttl
  download: true
  title: Biolink meta-model
- # maps to CURIE prefix GENEPIO
  url: http://purl.obolibrary.org/obo/genepio.owl
  file: genepio.owl
  download: true
  title: Genomic Epidemiology Ontology
```
And it completed just fine.
```
ubuntu@ip-172-31-59-26:~$ /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/multi_ont_to_json_kg.py /home/ubuntu/kg2-code/curies-to-categories.yaml /home/ubuntu/kg2-code/curies-to-urls-map.yaml /home/ubuntu/kg2-code/ont-load-inventory-test.yaml /home/ubuntu/test.json
https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.owl.ttl
Reading ontology file: biolink-model.owl.ttl; size: 326.27 KiB
Reading ontology JSON file: biolink-model.owl.json; size: 576.36 KiB
file: biolink-model.owl.ttl; last modified: 2020-12-06 21:04:01 GMT
http://purl.obolibrary.org/obo/genepio.owl
Reading ontology file: genepio.owl; size: 894.60 KiB
Reading ontology JSON file: genepio.json; size: 4835.80 KiB
file: genepio.owl; last modified: 2020-12-06 20:53:00 GMT
Calling make_nodes_dict_from_ontologies_list
[http://purl.obolibrary.org/obo/genepio.owl] Node has IAO:0100001 attribute but not owl:deprecated; setting deprecated=True: BTO:0001762
[http://purl.obolibrary.org/obo/GENEPIO/imports/apollo_sv_import.owl] could not shorten this IRI to a CURIE: http://example.com/bfo-spec-label
[http://purl.obolibrary.org/obo/genepio.owl] Unable to obtain a CURIE for ontology node ID: http://example.com/bfo-spec-label
[http://purl.obolibrary.org/obo/genepio.owl] Node has IAO:0100001 attribute but not owl:deprecated; setting deprecated=True: GENEPIO:0002067
[http://purl.obolibrary.org/obo/GENEPIO/imports/apollo_sv_import.owl] could not shorten this IRI to a CURIE: https://schema.org/DataType
[http://purl.obolibrary.org/obo/genepio.owl] Unable to obtain a CURIE for ontology node ID: https://schema.org/DataType
[http://purl.obolibrary.org/obo/genepio.owl] Node has IAO:0100001 attribute but not owl:deprecated; setting deprecated=True: GENEPIO:0001056
[http://purl.obolibrary.org/obo/genepio.owl] Node has IAO:0100001 attribute but not owl:deprecated; setting deprecated=True: GENEPIO:0001057
Calling make_map_of_node_ontology_ids_to_curie_ids
Calling get_rels_dict
[http://purl.obolibrary.org/obo/GENEPIO/imports/apollo_sv_import.owl] subject node ontology ID has no curie ID in the map: FOODON:03411347
[http://purl.obolibrary.org/obo/GENEPIO/imports/apollo_sv_import.owl] subject node ontology ID has no curie ID in the map: GENEPIO:0002471
[http://purl.obolibrary.org/obo/GENEPIO/imports/apollo_sv_import.owl] subject node ontology ID has no curie ID in the map: GENEPIO:0002469
[http://purl.obolibrary.org/obo/GENEPIO/imports/apollo_sv_import.owl] subject node ontology ID has no curie ID in the map: FOODON:03411347
Number of edges: 7715
Number of nodes: 6079
Saving JSON file
```
So you could say that I am extremely confused. @saramsey should I just try resuming the build, or can you point me in another direction to investigate?

**Comment by kvarforl** [comment]
I should mention that if you would like to investigate yourself, the log files are on kg2lindsey.

* `~/kg2-build/build-kg2-snakemake.log` shows `build-multi-ont-kg.sh` exiting with nonzero exit code.
* `~/kg2-build/build-multi-ont-kg.log.FAILED` is the log from this failure
* `~/kg2-build/build-kg2-ont-stderr.log.FAILED` is the stderr log of `~/kg2-code/multi_ont_to_json_kg.py` (contains the actual error message.

**Comment by saramsey** [comment]
Regarding the `.owl.ttl` file, I have reached out to Deepak Unni and Harold Solbrig on Slack about it. Will see what they say.

**Comment by saramsey** [comment]
Regarding `genepio`, I think it appears where it does in the logfile because it is the last ontology that is loaded (the ontologies are loaded in sequence). I confirmed this by doing
```
tail ont-load-inventory.yaml
-
  url: http://purl.obolibrary.org/obo/ino.owl
  file: ino.owl
  download: true
  title: Interaction Network Ontology
- # maps to CURIE prefix GENEPIO
  url: http://purl.obolibrary.org/obo/genepio.owl
  file: genepio.owl
  download: true
  title: Genomic Epidemiology Ontology
```
The line in the logfile 
```
Calling make_nodes_dict_from_ontologies_list
```
indicates that the script has gotten through "loading" all of the ontologies into memory as `ontobio` objects, and is now starting to process these ontobio objects (one at a time) in order to make the dictionary of KG2 nodes. So,  I think we need a debugging print statement at line 507 in `multi_ont_to_json_kg.py`, that prints out which ontology ontobio object is being processed. I will add it now.

**Comment by saramsey** [comment]
Commit 2eb13ee should help with the debugging

**Comment by saramsey** [comment]
OK, I'm in `kg2lindsey.rtx.ai`, going to do a git pull now

**Comment by saramsey** [comment]
Ah, looks like you already did the git pull. :-)

**Comment by saramsey** [comment]
In that case, I will let you test it out. Can you please do a quick test using your abbreviated (biolink + genepio) YAML file to see if my new debugging code works?

**Comment by saramsey** [comment]
Also, I have confirmed with Deepak Unni that we should now be downloading `biolink-model.owl.ttl`. I am told that it is syntactically the same file, they just changed the filename. Does our code still work if the file is saved (locally) as `biolink-model.owl.ttl`?  This, too, can be tested with your abbreviated YAML file.

**Comment by kvarforl** [comment]
> Also, I have confirmed with Deepak Unni that we should now be downloading `biolink-model.owl.ttl`. I am told that it is syntactically the same file, they just changed the filename. Does our code still work if the file is saved (locally) as `biolink-model.owl.ttl`? This, too, can be tested with your abbreviated YAML file.

So far it seems to work! I had to update it early on, and it seemed to do the trick :)

**Comment by kvarforl** [comment]
The debugging statement works! I had to tweak it slightly to print to stderr.
```diff
-        print(f"processing ontology: {ontology_curie_id}")
+        print(f"processing ontology: {ontology_curie_id}", file=sys.stderr)
```
Is the next move to try with the whole `ont-load-inventory.yaml` file? @saramsey  or do you have a speedier method in mind?

**Comment by saramsey** [comment]
> Is the next move to try with the whole `ont-load-inventory.yaml` file? @saramsey or do you have a speedier method in mind?

Exactly.

**Comment by saramsey** [comment]
So, `find_common_ancestor` (and `compare_two_lists_in_reverse`) is Erica's code, so I am having to study it a bit to see what is going on. If you take a look at L455 in `multi_ont_to_json_kg.py`, I think this error is occurring because `compare_two_lists_in_reverse` is being called without `named thing` being an element of both `path_list1` and `path_list2`. Theoretically, this shouldn't happen because any Biolink category should derive from `named thing`. So I think inspecting `path_list1` and `path_list2` and printing them out if `named thing` is not an entry in one of them, would be helpful.

**Comment by kvarforl** [comment]
Okay the run with debug output just finished! Looks like  `umls_source:MSH` is the last ontology being processed before it crashes. Going to make an abbreviated `ont_load_inventory.yaml` file to investigate with

**Comment by saramsey** [comment]
Excellent!  Good progress. Please consider printing out `path_list1` and `path_list2` at L455.

**Comment by kvarforl** [comment]
you seem to be correct about `named_thing`~

```
[http://purl.bioontology.org/ontology/MSH/] unexpected None category depth for category activity and behavior: MESH:D011593
list1: ['information content entity', 'named thing'] 
list2: ['activity and behavior']
```

**Comment by kvarforl** [comment]
I think this has something to do with the new mixin addition to the biolink model: `activity and behavior` inherits from `occurent`, which does NOT inherit from `named_thing` (see [this](https://github.com/biolink/biolink-model/blob/4e1095a173ce1f5aa7a196764013c18d4f27945c/biolink-model.yaml#L4914) line in the biolink-model file)
```yaml
  occurrent:
    description: >-
      A processual entity
    # biolink:Occurrent is most consistently used as a mixin thus it should
    # be declared as such and cannot inherit from the non-mixin biolink:NamedThing
    #is_a: named thing
    mixin: true
    abstract: true
    exact_mappings:
      - BFO:0000003
```

@saramsey  any ideas on how to remedy this? the simplest thing I can think of is to just forcibly append `named thing` if it's not there, but that seems hard to maintain and like it would throw us out of biolink compliance.

**Comment by kvarforl** [comment]
To be honest I only have a vague idea of what a mixin is, but I remember hearing from Richard on one of the calls that they've been incorporated into the biolink model in an effort to add similar functionality as Java Mixins. 

In this case, maybe it wouldn't be out of line to forcibly append `named_thing` to the list if it isn't already the last element after the call to `get_path` on L450 and L453. I'm unsure.

(disclaimer: [this](https://stackoverflow.com/questions/17987704/an-example-of-a-mixin-in-java) StackOverflow post is the only thing I've ever read about mixins when I googled it just now)

**Comment by saramsey** [comment]
Thanks for the great updates, @kvarforl. What is the `name` corresponding to `MESH:D011593` and what UMLS TUIs does it map to?

**Comment by kvarforl** [comment]
@saramsey From [this](https://bioportal.bioontology.org/ontologies/MESH?p=classes&conceptid=D011593) purl.bioontology page, 
the name associated with `MESH:D011593` is `Psychology, Social`

**Comment by kvarforl** [comment]
Oooo wait there is a TUI field in on the same page: `T091`. 
Unfortunately, I don't  really know what to do with it, so I'm still looking for guidance :)

**Comment by saramsey** [comment]
From `umls-msh.json` in `kg2-build` on `kg2lindsey.rtx.ai`:
```
      "id" : "http://purl.bioontology.org/ontology/MSH/D011593",
      "meta" : {
        "basicPropertyValues" : [ {
          "pred" : "http://www.w3.org/2004/02/skos/core#definition",
          "val" : "Branch of psychology concerned with perception of the beliefs, attitudes and opinions of others."
        }, {
          "pred" : "http://www.w3.org/2004/02/skos/core#altLabel",
          "val" : "Perceptual Psychology"
        }, {
          "pred" : "https://identifiers.org/umls:has_cui",
          "val" : "C0033919"
        }, {
          "pred" : "http://www.w3.org/2004/02/skos/core#altLabel",
          "val" : "Psychology, Perceptual"
        }, {
          "pred" : "http://www.w3.org/2004/02/skos/core#prefLabel",
          "val" : "Psychology, Social"
        }, {
          "pred" : "http://www.w3.org/2004/02/skos/core#altLabel",
          "val" : "Social Psychology"
        }, {
          "pred" : "https://identifiers.org/umls:has_cui",
          "val" : "C4704913"
        }, {
          "pred" : "https://identifiers.org/umls:has_tui",
          "val" : "T091"
        }, {
          "pred" : "http://www.w3.org/2004/02/skos/core#notation",
          "val" : "D011593"
        }, {
          "pred" : "http://www.w3.org/2004/02/skos/core#definition",
          "val" : "The branch of psychology concerned with the effects of group membership upon the behavior, attitudes, and beliefs of an individual."
        } ]
```

**Comment by saramsey** [comment]
From https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/PSY/stats.html, we learned that `T091` is
`biomedical occupation or discipline`:
<img width="691" alt="Screen Shot 2020-12-08 at 2 22 34 PM" src="https://user-images.githubusercontent.com/5562107/101548583-f4b3cd80-3960-11eb-9bae-7681c8adbefd.png">

**Comment by saramsey** [comment]
The parent term, `MESH:D011520`, has the following inormation in `umls-msh.json`:
```
      "id" : "http://purl.bioontology.org/ontology/MSH/D011520",
      "meta" : {
        "basicPropertyValues" : [ {
          "pred" : "https://identifiers.org/umls:has_cui",
          "val" : "C0033714"
        }, {
          "pred" : "http://www.w3.org/2004/02/skos/core#notation",
          "val" : "D011520"
        }, {
          "pred" : "http://www.w3.org/2004/02/skos/core#definition",
          "val" : "An enzyme that catalyzes the oxidation of protocatechuate to 3-carboxy-cis-cis-muconate in the presence of molecular oxygen. It contains ferric ion. EC 1.13.11.3."
        }, {
          "pred" : "https://identifiers.org/umls:has_tui",
          "val" : "T126"
        }, {
          "pred" : "http://www.w3.org/2004/02/skos/core#altLabel",
          "val" : "Protocatechuate:oxygen 3,4-oxidoreductase (decyclizing)"
        }, {
          "pred" : "http://www.w3.org/2004/02/skos/core#altLabel",
          "val" : "Protocatechuate 3,4 Dioxygenase"
        }, {
          "pred" : "http://www.w3.org/2004/02/skos/core#prefLabel",
          "val" : "Protocatechuate-3,4-Dioxygenase"
        }, {
          "pred" : "https://identifiers.org/umls:has_tui",
          "val" : "T116"
        } ]
```

**Comment by saramsey** [comment]
UMLS semantic type `T054` is: `activity and behavior`

**Comment by saramsey** [comment]
OK, so `MESH:D01153` (`psychology, social`) has two parent concepts, `Behavior and Behavior Mechanisms` (documented above) and `Psychology` (`MESH:D011584`), 
<img width="775" alt="Screen Shot 2020-12-08 at 2 47 43 PM" src="https://user-images.githubusercontent.com/5562107/101550671-9557bc80-3964-11eb-9c8f-a8e91573ae77.png">

which has the following TUIs according to BioPortal:
http://bioportal.bioontology.org/ontologies/MESH?p=classes&conceptid=D011584

```
T041
T091
T097
T080
T067
```
Note that `T080` is mapped to `information content entity` in `curies-to-categories.yaml`.

**Comment by kvarforl** [comment]
Question to ask Deepak and Richard: can we use occurrent and descendents as a node category?

**Comment by kvarforl** [comment]
Noting here that I'm also temporarily changing anything that is `occurrent` to `named thing`

**Comment by kvarforl** [comment]
The fix of adjusting `occurrent` and `activity and behavior` to `named thing` worked, and I made it through that part of the build for KG2.4.0, so I'm closing this out.
