### ISSUE TITLE
Error in ARAXRanker for query where a qnode has multiple curies

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1152]
noticed that this DSL seems to throw an error (on production) during the ranking step:
```
add_qnode(id=n00, curie=DOID:3312)
add_qnode(id=n01, curie=[MONDO:0004985, CHEBI:48607, UniProtKB:P22301])
add_qedge(id=e00, source_id=n00, target_id=n01)
expand(kp=ARAX/KG2)
resultify()
```
<img width="703" alt="Screen Shot 2020-12-08 at 9 11 58 PM" src="https://user-images.githubusercontent.com/49423686/101587909-09608780-399a-11eb-9fc4-254cdc2d4380.png">

**Comment by edeutsch** [comment]
Looks like this is likely my boo boo. I will take a look.

**Comment by amykglen** [comment]
this looks good on production now https://arax.ncats.io/?r=5609 - closing
