### ISSUE TITLE
NodeSynonymizer incorrectly merging TGF-β, laryngeal adductor paralysis, and lysosomal acid phosphatase

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1159]
noticed the node with 'preferred' curie UniProtKB:P01137 appears to be an improper merge in KG2c - here are the names of all nodes coalesced into it:

![Screen Shot 2020-12-11 at 11 16 38 AM](https://user-images.githubusercontent.com/49423686/101945148-9fff9500-3ba2-11eb-9483-32a122721b41.png)
https://arax.ncats.io/?m=3402

and here are the NodeSynonymizer's synonyms for this concept:
```
python node_synonymizer.py --lookup=UniProtKB:P01137
...
    ],
    "synonyms": [
      {
        "label": "Acid phosphatase 2, lysosomal",
        "source": "KG2"
      },
      {
        "label": "ACP2",
        "source": "SRI"
      },
      {
        "label": "TGFB2",
        "source": "SRI"
      },
      {
        "label": "transforming growth factor beta 2",
        "source": "KG2"
      },
      {
        "label": "TGFB3",
        "source": "SRI"
      },
      {
        "label": "transforming growth factor beta 3",
        "source": "KG2"
      },
      {
        "label": "TGFB1",
        "source": "SRI"
      },
      {
        "label": "transforming growth factor beta 1",
        "source": "KG2"
      },
      {
        "label": "Lap",
        "source": "KG2"
      },
      {
        "label": "Laryngeal Adductor Paralysis",
        "source": "KG2"
      },
      {
        "label": "Transforming Growth Factor Beta-3",
        "source": "KG2"
      },
      {
        "label": "Transforming Growth Factor Beta-1",
        "source": "KG2"
      },
      {
        "label": "Transforming Growth Factor Beta-2",
        "source": "KG2"
      },
      {
        "label": "P01137",
        "source": "KG2"
      },
      {
        "label": "lysosomal acid phosphatase",
        "source": "KG2"
      },
      {
        "label": "P61812",
        "source": "KG2"
      },
      {
        "label": "P11117",
        "source": "KG2"
      },
      {
        "label": "P10600",
        "source": "KG2"
      },
      {
        "label": "Q6TV02",
        "source": "KG2"
      },
      {
        "label": "LARYNGEAL ADDUCTOR PARALYSIS; LAP",
        "source": "KG1"
      }
    ],
    "type": [
      "protein",
      "genomic_entity",
      "gene",
      "molecular_entity",
      "procedure",
      "named_thing",
      "disease",
      "information_content_entity",
      "attribute",
      "phenotypic_feature",
      "drug",
      "chemical_substance"
    ]
  }
}

```
these are all the equivalent curies for the concept according to the `NodeSynonymizer`: 
```
['CHEMBL.TARGET:CHEMBL1795178', 'CHEMBL.TARGET:CHEMBL3217393', 'CHEMBL.TARGET:CHEMBL3712903', 'ENSEMBL:ENSG00000092969', 'ENSEMBL:ENSG00000105329', 'ENSEMBL:ENSG00000119699', 'ENSEMBL:ENSG00000134575', 'ENSEMBL:LRG_399', 'HGNC:11766', 'HGNC:11768', 'HGNC:11769', 'HGNC:123', 'LOINC:LP6361-2', 'LOINC:LP64930-8', 'LOINC:MTHU026386', 'MESH:C562861', 'MONDO:0007877', 'NCBIGene:53', 'NCBIGene:7040', 'NCBIGene:7042', 'NCBIGene:7043', 'NCBIGene:7939', 'NCIT:C122027', 'NCIT:C20457', 'NCIT:C20458', 'NCIT:C20459', 'OMIM:150270', 'OMIM:171650', 'OMIM:MTHU065164', 'ORPHANET:120047', 'ORPHANET:120052', 'ORPHANET:120054', 'PR:000003647', 'PR:P01137', 'PR:P10600', 'PR:P11117', 'PR:P61812', 'RXNORM:1370419', 'RXNORM:1426465', 'SNOMED:708710005', 'UMLS:C0079441', 'UMLS:C0080222', 'UMLS:C1412132', 'UMLS:C1703303', 'UMLS:C1704256', 'UMLS:C4049927', 'UniProtKB:P01137', 'UniProtKB:P10600', 'UniProtKB:P11117', 'UniProtKB:P61812', 'UniProtKB:Q6TV02']
```
It seems like laryngeal adductor paralysis and lysosomal acid phosphatase are likely being merged because they share the acronym "LAP". but as for why TGF-β is being lumped in as well, I haven't looked too deeply into it, but I'm a bit suspicious of these nodes in KG2.3.4:

n.id | n.name | n.synonym
-- | -- | --
"UniProtKB:P01137" | "LAP" | ["TGFB1", "A8K792", "Q9UCG4", "SEQUENCE 390 AA", "44341 MW", "75391614250288FE CRC64", "\nMPPSGLRLLL LLLPLLWLLV LTPGRPAAGL STCKTIDMEL VKRKRIEAIR GQILSKLRLA\nSPPSQGEVPP GPLPEAVLAL YNSTRDRVAG ESAEPEPEPE ADYYAKEVTR VLMVETHNEI\nYDKFKQSTHS IYMFFNTSEL REAVPEPVLL SRAELRLLRL KLKVEQHVEL YQKYSNNSWR\nYLSNRLLAPS DSPEWLSFDV TGVVRQWLSR GGEIEGFRLS AHCSCDSRDN TLQVDINGFT\nTGRRGDLATI HGMNRPFLLL MATPLERAQH LQSSRHRRAL DTNYCFSSTE KNCCVRQLYI\nDFRKDLGWKW IHEPKGYHAN FCLGPCPYIW SLDTQYSKVL ALYNQHNPGA SAAPCCVPQA\nLEPLPIVYYV GRKPKVEQLS NMIVRSCKCS\n"]
"UniProtKB:P61812" | "LAP" | ["TGFB2", "B4DKC5", "Cetermin", "Glioblastoma-derived T-cell suppressor factor {ECO:0000303\|PubMed:3322813}", "P08112", "Q15579", "Q15581", "Q4VAV9", "SEQUENCE 414 AA", "47748 MW", "7D9D569E0F4A07D0 CRC64", "\nMHYCVLSAFL ILHLVTVALS LSTCSTLDMD QFMRKRIEAI RGQILSKLKL TSPPEDYPEP\nEEVPPEVISI YNSTRDLLQE KASRRAAACE RERSDEEYYA KEVYKIDMPP FFPSENAIPP\nTFYRPYFRIV RFDVSAMEKN ASNLVKAEFR VFRLQNPKAR VPEQRIELYQ ILKSKDLTSP\nTQRYIDSKVV KTRAEGEWLS FDVTDAVHEW LHHKDRNLGF KISLHCPCCT FVPSNNYIIP\nNKSEELEARF AGIDGTSTYT SGDQKTIKST RKKNSGKTPH LLLMLLPSYR LESQQTNRRK\nKRALDAAYCF RNVQDNCCLR PLYIDFKRDL GWKWIHEPKG YNANFCAGAC PYLWSSDTQH\nSRVLSLYNTI NPEASASPCC VSQDLEPLTI LYYIGKTPKI EQLSNMIVKS CKCS\n"]
"UniProtKB:P10600" | "LAP" | ["TGFB3", "Q8WV88", "SEQUENCE 412 AA", "47328 MW", "3CAD3548D3AEA178 CRC64", "\nMKMHLQRALV VLALLNFATV SLSLSTCTTL DFGHIKKKRV EAIRGQILSK LRLTSPPEPT\nVMTHVPYQVL ALYNSTRELL EEMHGEREEG CTQENTESEY YAKEIHKFDM IQGLAEHNEL\nAVCPKGITSK VFRFNVSSVE KNRTNLFRAE FRVLRVPNPS SKRNEQRIEL FQILRPDEHI\nAKQRYIGGKN LPTRGTAEWL SFDVTDTVRE WLLRRESNLG LEISIHCPCH TFQPNGDILE\nNIHEVMEIKF KGVDNEDDHG RGDLGRLKKQ KDHHNPHLIL MMIPPHRLDN PGQGGQRKKR\nALDTNYCFRN LEENCCVRPL YIDFRQDLGW KWVHEPKGYY ANFCSGPCPY LRSADTTHST\nVLGLYNTLNP EASASPCCVP QDLEPLTILY YVGRTPKVEQ LSNMVVKSCK CS\n"]

why are their names "LAP", but the first item in their synonym fields is "TGFB_"? will write these up in a separate KG2 issue.

**Comment by edeutsch** [comment]
One solution might be to collect a list of exceptions to tell the NodeSynonymizer never to coalesce on "LAP" specifically because it's a problem.
We could also choose not to coalesce on gene symbols because it is fraught with problems.
In the current design, that would mean just ignoring LAP completely, which means that those proteins would not be findable by the name "LAP". which is probably not a great loss since it is ambiguous anyway.

**Comment by edeutsch** [comment]
```
$ egrep 'UniProtKB:P01137|UniProtKB:P61812|UniProtKB:P10600' NodeNamesDescriptions_KG*.tsv
NodeNamesDescriptions_KG1.tsv:UniProtKB:P01137	transforming growth factor beta 1	protein
NodeNamesDescriptions_KG1.tsv:UniProtKB:P01137	TGFB1	protein
NodeNamesDescriptions_KG1.tsv:UniProtKB:P61812	transforming growth factor beta 2	protein
NodeNamesDescriptions_KG1.tsv:UniProtKB:P61812	TGFB2	protein
NodeNamesDescriptions_KG1.tsv:UniProtKB:P10600	transforming growth factor beta 3	protein
NodeNamesDescriptions_KG1.tsv:UniProtKB:P10600	TGFB3	protein
NodeNamesDescriptions_KG2.tsv:UniProtKB:P01137	LAP	protein
NodeNamesDescriptions_KG2.tsv:UniProtKB:P61812	LAP	protein
NodeNamesDescriptions_KG2.tsv:UniProtKB:P10600	LAP	protein
```

**Comment by edeutsch** [comment]
I now have bespoke code in the NodeSynonymizer build process that can exclude certain known problem associations (not yet committed). It now denies these three proteins from being called LAP. and the result seems to be good. they are just TGFB1, 2, and 3 and do not get merged together. None of them are LAP in the final database.

this patch fixes this particular problem. But there are probably 100s like it that are not fixed. The real solution is probably not to let proteins be named after one of their chains.

As a side note, NodeNamesDescriptions_KG2.tsv is processed before NodeNamesDescriptions_KG1.tsv. For most kinds of nodes, KG1 is just redundant and could be skipped. But I've found in the past that NodeNamesDescriptions_KG1.tsv contains much nicer information about UniProtKB proteins.  In the above egrep output, it is worth pondering why the KG1 rows seem (to me) much nicer than the KG2 rows.

**Comment by edeutsch** [comment]
I'm almost not very enthused about to contents of n.synonym in the above table.

**Comment by amykglen** [comment]
closing since this was fixed with the KG2.5.2 synonymizer
