### ISSUE TITLE
RTXConfiguration

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#116]
There is a new RTXconfiguration class that we should push all settings into. This class will read a local file at some point soon. Some things like passwords should be read from a local file rather than code in GitHub. You can use it like this:

sys.path.append(os.path.dirname(os.path.abspath(__file__))+"/../../../UI/OpenAPI/python-flask-server/")
from RTXConfiguration import RTXConfiguration

    rtxConfig = RTXConfiguration()
    response.tool_version = rtxConfig.version

this is still a work in progress.

Would be nice to get all neo4j connection information, etc. into here. i.e. one place.

Comments/alternate strategies welcome

**Comment by dkoslicki** [comment]
FYI: [RTXConfiguration.py](https://github.com/RTXteam/RTX/blob/newkg2/code/RTXConfiguration.py) copied to ``code`` directory in the ``newkg2`` branch. Depreciate old ``RTXConfiguration.py`` after ``newkg2`` merged into ``master``.

**Comment by dkoslicki** [comment]
Close in light of addition of [RTXConfiguration.py](https://github.com/RTXteam/RTX/blob/master/code/RTXConfiguration.py).
