### ISSUE TITLE
ATP is being synonymized with ADP and AMP

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1162]
not sure if this is desirable or not, but it appears ATP, ADP, and AMP are all being lumped together by the `NodeSynonymizer`.

names of all the KG2.3.4 nodes coalesced to form the KG2c node for this concept (preferred curie: UniProtKB:P24935):

![Screen Shot 2020-12-11 at 12 00 07 PM](https://user-images.githubusercontent.com/49423686/101949523-94af6800-3ba8-11eb-920c-6ecfff039b45.png)
https://arax.ncats.io/?m=3403

is this what we want? or is too much info lost?

**Comment by saramsey** [comment]
I kind of feel like they should be distinct

**Comment by edeutsch** [comment]
So one reason (maybe not the only one) this happens is as follows:
If you ask the SRI Node Normalizer about KEGG:C00020, you get this:
```
python sri_node_normalizer.py -c KEGG:C00020
==========================================================
Native SRI Node Normalizer results:
{
  "KEGG:C00020": {
    "equivalent_identifiers": [
      {
        "identifier": "CHEBI:16027",
        "label": "adenosine 5'-monophosphate"
      },
      {
        "identifier": "CHEMBL.COMPOUND:CHEMBL752",
        "label": "ADENOSINE"
      },
      {
        "identifier": "DRUGBANK:DB00131"
      },
      {
        "identifier": "PUBCHEM.COMPOUND:6083"
      },
      {
        "identifier": "MESH:C015664",
        "label": "8-aminoadenosine 5'-monophosphate"
      },
      {
        "identifier": "MESH:D011061",
        "label": "Poly A"
      },
      {
        "identifier": "MESH:C021683",
        "label": "formycin 5'-phosphate"
      },
      {
        "identifier": "MESH:C037185",
        "label": "5'-deoxy-5'-thioadenosine 5'-monophosphate"
      },
      {
        "identifier": "MESH:D000249",
        "label": "Adenosine Monophosphate"
      },
      {
        "identifier": "HMDB:HMDB0000045"
      },
      {
        "identifier": "INCHIKEY:WNKGMQLRHKONID-ZFWWWQNUSA-N"
      },
      {
        "identifier": "UNII:415SHH325A"
      },
      {
        "identifier": "KEGG:C00020",
        "label": "AMP"
      },
      {
        "identifier": "gtpo:2455"
      }
    ],
    "id": {
      "identifier": "CHEBI:16027",
      "label": "adenosine 5'-monophosphate"
    },
    "type": [
      "biolink:ChemicalSubstance",
      "biolink:MolecularEntity",
      "biolink:BiologicalEntity",
      "biolink:NamedThing"
    ]
  }
}
```

If you ask the Node Normalizer about KEGG:C00008, you get this:
```
python sri_node_normalizer.py -c KEGG:C00008
==========================================================
Native SRI Node Normalizer results:
{
  "KEGG:C00008": {
    "equivalent_identifiers": [
      {
        "identifier": "CHEBI:16761",
        "label": "ADP"
      },
      {
        "identifier": "CHEMBL.COMPOUND:CHEMBL14830",
        "label": "ADENOSINE"
      },
      {
        "identifier": "PUBCHEM.COMPOUND:6022"
      },
      {
        "identifier": "MESH:C020332",
        "label": "formycin diphosphate"
      },
      {
        "identifier": "MESH:D000244",
        "label": "Adenosine Diphosphate"
      },
      {
        "identifier": "HMDB:HMDB0001341"
      },
      {
        "identifier": "INCHIKEY:HMHDTAYXNLPCEI-UHFFFAOYSA-N"
      },
      {
        "identifier": "UNII:61D2G4IYVH"
      },
      {
        "identifier": "KEGG:C00008",
        "label": "ADP"
      },
      {
        "identifier": "gtpo:1712"
      }
    ],
    "id": {
      "identifier": "CHEBI:16761",
      "label": "ADP"
    },
    "type": [
      "biolink:ChemicalSubstance",
      "biolink:NamedThing",
      "biolink:BiologicalEntity",
      "biolink:MolecularEntity"
    ]
  }
}
```

So the SRI Node Normalizer has then nicely separated (from a superficial look).

The problem is that my NodeSynonizer looks at those two results and that both have a label ADENOSINE:
```
      {
        "identifier": "CHEMBL.COMPOUND:CHEMBL752",
        "label": "ADENOSINE"
      },
```
and
```
      {
        "identifier": "CHEMBL.COMPOUND:CHEMBL14830",
        "label": "ADENOSINE"
      },
```
and it says, oh, if *this* is ADENOSINE, and *that* is ADENOSINE, then they're all equivalent! and the clusters are merged.

Resolving this is tricky. In the current design, only one cluster can be linked to adenosine.
I could try to solve this in various ways:

- The easiest perhaps is to have some special rules, one of which says "ignore the SRI Node Normalizer calling CHEMBL.COMPOUND:CHEMBL752 ADENOSINE cuz it ain't so"

that would likely separate them.

KG2 has these names:
CHEMBL.COMPOUND:CHEMBL14830	ADENOSINE DIPHOSPHATE	chemical_substance
CHEMBL.COMPOUND:CHEMBL752	ADENOSINE PHOSPHATE	chemical_substance

- Another possible solution is to report to the SRI Normalizer that they probably have a bug. Maybe their CHEMBL.COMPOUND parsing stops after a space and misses the second word?

**Comment by edeutsch** [comment]
A bit more snuffling around reveals strong evidence that the SRI Node Normalizer is skipping non-first words in ChEMBL. Look up:
CHEMBL.COMPOUND:CHEMBL76729	DEOXY ADENOSINEDIPHOSPHATE

reveals a weak result:
https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=CHEMBL.COMPOUND:CHEMBL76729

I've filed an issue with them.

**Comment by amykglen** [comment]
appears partially resolved in KG2.6.7.1:

adenosine phosphate/triphosphate/monophosphate conflation: https://arax.ncats.io/?term=CHEBI:22256
ADP is looking good though: https://arax.ncats.io/?term=MESH:D000244

**Comment by finnagin** [comment]
@amykglen @edeutsch is this still relevant or should we close?

**Comment by edeutsch** [comment]
https://arax.ncats.io/?term=CHEBI:22256
It seems to still be a problem.

**Comment by amykglen** [comment]
this is looking pretty clean in the new synonymizer (#2003):

Cluster for DRUGBANK:DB00171 (PUBCHEM.COMPOUND:5957) has 28 nodes:

| id                                   | category         | name                                          | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:-------------------------------------|:-----------------|:----------------------------------------------|:---------|:------------|:-----------------|
| CAS:11016-17-4                       | SmallMolecule    |                                               | X        |             |                  |
| CAS:126339-06-8                      | ChemicalEntity   |                                               | X        |             |                  |
| CAS:51963-61-2                       | MolecularMixture |                                               | X        |             |                  |
| CHEBI:15422                          | SmallMolecule    | ATP                                           | X        | X           |                  |
| CHEMBL.COMPOUND:CHEMBL14249          | SmallMolecule    | ADENOSINE TRIPHOSPHATE                        | X        | X           |                  |
| CHEMBL.TARGET:CHEMBL2366048          | SmallMolecule    | ATP                                           |          | X           |                  |
| DRUGBANK:DB00171                     | SmallMolecule    | Atp                                           | X        | X           |                  |
| DrugCentral:91                       | SmallMolecule    | adenosine triphosphate                        | X        | X           |                  |
| GTOPDB:1713                          | SmallMolecule    | ATP                                           | X        |             |                  |
| HMDB:HMDB0000538                     | SmallMolecule    | Adenosine triphosphate                        | X        | X           |                  |
| INCHIKEY:ZKHQWZAMYRWXGA-KQYNXXCUSA-N | SmallMolecule    |                                               | X        |             |                  |
| KEGG.COMPOUND:C00002                 | SmallMolecule    | ATP                                           | X        | X           |                  |
| KEGG.DRUG:D02300                     | Drug             | Adenosine triphosphate disodium hydrate (JAN) |          | X           |                  |
| KEGG.DRUG:D08646                     | Drug             |                                               |          | X           |                  |
| LOINC:LP14737-8                      | ChemicalEntity   | Adenosine triphosphate                        |          | X           |                  |
| LOINC:MTHU001928                     | ChemicalEntity   | Adenosine triphosphate                        |          | X           |                  |
| MESH:C062738                         | ChemicalEntity   | curtatoxin I                                  | X        | X           |                  |
| MESH:D000255                         | SmallMolecule    | Adenosine Triphosphate                        | X        | X           |                  |
| NCIT:C209                            | Drug             | Adenosine Triphosphate                        |          | X           |                  |
| NDDF:004233                          | ChemicalEntity   | adenosine triphosphate                        |          | X           |                  |
| PDQ:CDR0000038260                    | ChemicalEntity   | adenosine triphosphate                        |          | X           |                  |
| PUBCHEM.COMPOUND:5957                | SmallMolecule    | Adenosine-5'-triphosphate                     | X        |             | X                |
| PathWhiz.Compound:414                | SmallMolecule    | Adenosine triphosphate                        |          | X           |                  |
| RXNORM:318                           | Drug             | adenosine triphosphate                        |          | X           |                  |
| UMLS:C0001480                        | SmallMolecule    | adenosine triphosphate                        | X        | X           |                  |
| UNII:8L70Q75FXE                      | SmallMolecule    | ADENOSINE TRIPHOSPHATE                        | X        |             |                  |
| VANDF:4029344                        | ChemicalEntity   | Adenosine triphosphate                        |          | X           |                  |
| ttd.target:Adenosine_triphosphate    | SmallMolecule    | Adenosine triphosphate                        |          | X           |                  |

Cluster for MESH:D000244 (PUBCHEM.COMPOUND:6022) has 20 nodes:

| id                                   | category        | name                               | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:-------------------------------------|:----------------|:-----------------------------------|:---------|:------------|:-----------------|
| CAS:104746-05-6                      | ChemicalEntity  |                                    | X        |             |                  |
| CHEBI:16761                          | SmallMolecule   | ADP                                | X        | X           |                  |
| CHEMBL.COMPOUND:CHEMBL14830          | SmallMolecule   | ADENOSINE DIPHOSPHATE              | X        | X           |                  |
| DRUGBANK:DB16833                     | ChemicalEntity  |                                    | X        |             |                  |
| GTOPDB:1712                          | SmallMolecule   | ADP                                | X        |             |                  |
| HMDB:HMDB0001341                     | SmallMolecule   | ADP                                | X        | X           |                  |
| INCHIKEY:XTWYTFMLZFPYCI-KQYNXXCUSA-N | SmallMolecule   |                                    | X        |             |                  |
| KEGG.COMPOUND:C00008                 | SmallMolecule   | ADP                                | X        | X           |                  |
| KEGG.GLYCAN:G11113                   | SmallMolecule   |                                    |          | X           |                  |
| LOINC:LP15325-1                      | ChemicalEntity  | Adenosine diphosphate              |          | X           |                  |
| LOINC:LP70321-2                      | ChemicalEntity  | Adenosine diphosphate              |          | X           |                  |
| LOINC:MTHU007382                     | ChemicalEntity  | Adenosine diphosphate              |          | X           |                  |
| MESH:C050138                         | ChemicalEntity  | dynorphin A (1-13), Ala(2)-Trp(4)- | X        | X           |                  |
| MESH:D000244                         | SmallMolecule   | Adenosine Diphosphate              | X        | X           |                  |
| OMIT:0001676                         | MolecularEntity | Adenosine Diphosphate              |          | X           |                  |
| PUBCHEM.COMPOUND:6022                | SmallMolecule   | Adenosine-5'-diphosphate           | X        |             | X                |
| PathWhiz.Compound:1034               | SmallMolecule   | Adenosine diphosphate              |          | X           |                  |
| UMLS:C0001459                        | ChemicalEntity  | Adenosine Diphosphate              | X        | X           |                  |
| UMLS:C5698453                        | ChemicalEntity  | Adenosine disphosphate             | X        |             |                  |
| UNII:61D2G4IYVH                      | SmallMolecule   | ADENOSINE DIPHOSPHATE              | X        |             |                  |

Cluster for DRUGBANK:DB00131 (PUBCHEM.COMPOUND:6083) has 24 nodes:

| id                                   | category       | name                       | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:-------------------------------------|:---------------|:---------------------------|:---------|:------------|:-----------------|
| CAS:122768-03-0                      | SmallMolecule  |                            | X        |             |                  |
| CAS:136920-07-5                      | SmallMolecule  |                            | X        |             |                  |
| CAS:53624-78-5                       | SmallMolecule  |                            | X        |             |                  |
| CAS:61-19-8                          | SmallMolecule  |                            | X        |             |                  |
| CAS:67583-85-1                       | SmallMolecule  |                            | X        |             |                  |
| CHEBI:16027                          | SmallMolecule  | adenosine 5'-monophosphate | X        | X           |                  |
| CHEMBL.COMPOUND:CHEMBL752            | SmallMolecule  | ADENOSINE PHOSPHATE        | X        | X           |                  |
| DRUGBANK:DB00131                     | SmallMolecule  | Adenosine phosphate        | X        | X           |                  |
| DrugCentral:92                       | SmallMolecule  | adenosine phosphate        | X        | X           |                  |
| GTOPDB:2455                          | SmallMolecule  | adenosine 5'-monophosphate | X        |             |                  |
| HMDB:HMDB0000045                     | SmallMolecule  | Adenosine monophosphate    | X        | X           |                  |
| INCHIKEY:UDMBCSSLTHHNCD-KQYNXXCUSA-N | SmallMolecule  |                            | X        |             |                  |
| KEGG.COMPOUND:C00020                 | SmallMolecule  | AMP                        | X        | X           |                  |
| KEGG.DRUG:D02769                     | Drug           |                            |          | X           |                  |
| MESH:D000249                         | SmallMolecule  | Adenosine Monophosphate    | X        | X           |                  |
| NCIT:C83606                          | Drug           | Adenosine Phosphate        |          | X           |                  |
| NDDF:002392                          | ChemicalEntity | adenosine phosphate        |          | X           |                  |
| PUBCHEM.COMPOUND:6083                | SmallMolecule  | Adenosine monophosphate    | X        |             | X                |
| PathWhiz.Compound:32                 | SmallMolecule  | Adenosine monophosphate    |          | X           |                  |
| RXNORM:309                           | Drug           | adenosine monophosphate    |          | X           |                  |
| UMLS:C0001465                        | SmallMolecule  | adenosine monophosphate    | X        | X           |                  |
| UNII:415SHH325A                      | SmallMolecule  | ADENOSINE PHOSPHATE        | X        |             |                  |
| VANDF:4018975                        | ChemicalEntity | Adenosine phosphate        |          | X           |                  |
| ttd.target:Adenosine_monophosphate   | SmallMolecule  | Adenosine monophosphate    |          | X           |                  |

**Comment by amykglen** [comment]
confirmed fixed on our dev instances:

https://arax.ncats.io/devLM/?term=ATP
https://arax.ncats.io/devLM/?term=ADP
https://arax.ncats.io/devLM/?term=AMP
