### ISSUE TITLE
New scores from GeneticsKP; add to ARAXRanker

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1163]
so I haven't heard word of this, but I noticed that the GeneticsKP API now returns a couple more kinds of scores: 'Richards-effector-genes' and 'ABC-genes'. 

I don't have any info/explanations of what these scores are, but here are examples of such edges (straight from the KP, prior to being loaded into our swagger model):
```
{
  "id":"RC_GENES_17073",
  "score":0.472499341,
  "score_direction":"higher_is_better",
  "score_name":"Richards-effector-genes",
  "source_id":"EFO:0001360",
  "target_id":"NCBIGene:339344",
  "type":"associated"
}
```
```
{
  "id":"ABC_GENE_9821",
  "score_name":"ABC-genes",
  "source_id":"EFO:0001360",
  "target_id":"NCBIGene:201799",
  "type":"associated"
}
```
note: there appears to be some bug where the 'ABC-genes' edges don't actually include a score _value_ at the moment, but if it was there, Expand would grab it and load it into an Edge/EdgeAttribute.

and this is an example of a query that will return both such scores:
```
add_qnode(name=type 2 diabetes mellitus, type=disease, id=n00)
add_qnode(type=protein, id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(kp=GeneticsKP, include_all_scores=true)
resultify()
filter_results(action=limit_number_of_results,max_results=10,prune_kg=true)
```
![Screen Shot 2020-12-11 at 1 19 15 PM](https://user-images.githubusercontent.com/49423686/101955952-96caf400-3bb3-11eb-93bf-f9f77e18e1c0.png)
note: as of writing this on 12/11/20, the above query works in `master`, but not yet on production/`/test` as the necessary changes haven't yet been rolled out there.

I'm not sure who the proper contact point is for the GeneticsKP now that Marcin von Grotthuss has moved on. but perhaps it would be good to check in with them (and possibly report the bug with the ABC-genes scores)?

**Comment by saramsey** [comment]
I do love a good mystery! A quick google search on "Richards effector gene" pulls up this bioRxiv paper
https://www.biorxiv.org/content/10.1101/2020.06.28.171561v1

which has senior author "Richards" and which defines something called an *effector index* *Ei*.

**Comment by saramsey** [comment]
That paper looks to be a bit hard to dig into, due to the lack of equations, but from this paragraph of the supplementary material, I *think* it means that the index *E<sub>i</sub>* is on the unit interval?

<img width="548" alt="Screen Shot 2020-12-11 at 1 10 52 PM" src="https://user-images.githubusercontent.com/5562107/101955236-5028ca00-3bb2-11eb-9d52-9549edee500b.png">

**Comment by saramsey** [comment]
Here is the link to the supplementary PDF:
https://www.biorxiv.org/content/biorxiv/early/2020/06/28/2020.06.28.171561/DC1/embed/media-1.pdf?download=true

**Comment by saramsey** [comment]
As for figuring out what the ABC gene score is, that's a bit of a challenging Google task because it is confounded by the superfamily of ABC (ATP-binding cassette) genes which have many many web pages about them, and which presumably have nothing to do with the "ABC" here (I think??).

**Comment by saramsey** [comment]
Ah, it might be this?

https://www.frontiersin.org/articles/10.3389/fgene.2020.00730/full

**Comment by finnagin** [comment]
Thanks for finding all this info @saramsey ! This is really helpful!

**Comment by dkoslicki** [comment]
From the genetics KP people (Ryan Koesterer):
Hi David, This is the information I have been able to unearth so far. 'Richards-effector-genes' scores range from 0 to 1 and can probably be roughly thought of as "probability the gene is a true disease gene". The ABC-genes data are "Lists of genes that have some regulatory connection to a GWAS association". It is a binary value at the moment so does not offer any information on level of confidence.

**Comment by finnagin** [comment]
@dkoslicki Thanks for this! If ABC is a binary value should we just ignore it?

**Comment by dkoslicki** [comment]
Yup, I think so @finnagin
