### ISSUE TITLE
Glutathione reductase is being synonymized with glucocorticoid receptor

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1164]
Seems there's a synonymization error for preferred curie UniProtKB:P04150:

![Screen Shot 2020-12-14 at 9 15 17 AM](https://user-images.githubusercontent.com/49423686/102112691-ea745200-3dec-11eb-8afb-417bb91310e3.png)

equivalent_curies:
```
HGNC:7978
HGNC:4623
UMLS:C1370369
UMLS:C0034809
UMLS:C4721873
NCIT:C157042
NCIT:C17071
SNOMED:3648007
PR:000011406
ORPHANET:122298
ORPHANET:123916
PR:P00390
PR:P04150
PR:000008292
UniProtKB:P04150
UniProtKB:P00390
ENSEMBL:ENSG00000104687
ENSEMBL:ENSG00000113580
CHEMBL.TARGET:CHEMBL2366476
CHEMBL.TARGET:CHEMBL2034
CHEMBL.TARGET:CHEMBL3368
CHEMBL.TARGET:CHEMBL3144
CHEMBL.TARGET:CHEMBL4105966
NCBIGene:2908
NCBIGene:2936
PathWhiz.ProteinComplex:9501
PathWhiz.ProteinComplex:25
PathWhiz.ProteinComplex:7772
PathWhiz.ProteinComplex:9943
PathWhiz.ProteinComplex:857
PathWhiz.ProteinComplex:8166
```
https://arax.ncats.io/?m=3406

**Comment by edeutsch** [comment]
I traced this back to an odd thing in NodeNamesDescriptions_KG2.tsv:
```
$ egrep 'UniProtKB:P00390|UniProtKB:P04150' ../../../data/KGmetadata/NodeNamesDescriptions_KG*.tsv
../../../data/KGmetadata/NodeNamesDescriptions_KG1.tsv:UniProtKB:P04150	nuclear receptor subfamily 3 group C member 1	protein
../../../data/KGmetadata/NodeNamesDescriptions_KG1.tsv:UniProtKB:P04150	GCR	protein
../../../data/KGmetadata/NodeNamesDescriptions_KG1.tsv:UniProtKB:P00390	glutathione-disulfide reductase	protein
../../../data/KGmetadata/NodeNamesDescriptions_KG1.tsv:UniProtKB:P00390	GSR	protein
../../../data/KGmetadata/NodeNamesDescriptions_KG2.tsv:UniProtKB:P00390	GR;	protein
../../../data/KGmetadata/NodeNamesDescriptions_KG2.tsv:UniProtKB:P04150	GR;	protein
```

The NodeNamesDescriptions_KG1.tsv entries for these two proteins look pretty reasonable.
but the NodeNamesDescriptions_KG2.tsv look corrupted somehow. They're apparently wrong (wrong gene symbol), and they're also weird with the ending semi-colon, and they're also the same, which is the common thread that causes NodeSynonymizer to conclude that these two proteins are equivalent.

I can put in special custom rules to stop this behavior, but it kinda looks like it's a problem in KG2 that should be fixed?

What do you think?

**Comment by edeutsch** [comment]
There seem to be about 7000 KG2 UniprotKB entries with semicolons in them:
```
 egrep 'UniProtKB' ../../../data/KGmetadata/NodeNamesDescriptions_KG2.tsv | grep ';' | wc -l
7002
```
for example some things like:
```
niProtKB:P23763	VAMP-1;	protein
UniProtKB:P63027	VAMP-2;	protein
UniProtKB:Q15836	VAMP-3;	protein
UniProtKB:O75379	VAMP-4;	protein
UniProtKB:O95183	VAMP-5;	protein
UniProtKB:P51809	VAMP-7;	protein
UniProtKB:Q9BV40	VAMP-8 {ECO:0000303|PubMed:12130530};	protein
UniProtKB:Q9P0L0	VAMP-A;	protein
UniProtKB:O95292	VAMP-B/VAMP-C;	protein
UniProtKB:Q15904	V-ATPase subunit S1;	protein
UniProtKB:P50552	VASP;	protein
UniProtKB:P14997	Minor capsid protein VP2;	protein
UniProtKB:P03094	Minor capsid protein VP2;	protein
UniProtKB:P03095	Minor capsid protein VP2;	protein
UniProtKB:P0DOJ3	Minor capsid protein VP2;	protein
UniProtKB:P0DOJ2	Minor capsid protein VP2;	protein
UniProtKB:P0DOJ1	Minor capsid protein VP2;	protein
UniProtKB:A5HBE1	Minor capsid protein VP2;	protein
UniProtKB:O57198	VLTF-1;	protein
UniProtKB:P68612	VLTF-1;	protein
UniProtKB:P32990	VLTF-1;	protein
UniProtKB:O57216	VLTF-2;	protein
UniProtKB:P20982	VLTF-2;	protein
UniProtKB:P33814	VLTF-2;	protein
UniProtKB:Q76ZR2	VLTF-3;	protein
UniProtKB:P68318	VLTF-3;	protein
UniProtKB:P68320	VLTF-3;	protein
```

I'm wondering what the best way to handle this is. There are probably lots of proteins that are getting tied together when they shouldn't.

Potentially a lot of these are highly similar pathogen proteins that all get the same name and gene symbol.

I wonder if it would be wise to follow protein names with the species name if not human. Less clear for proteins symbols, but probably as well?

And polish out the semicolons?

**Comment by amykglen** [comment]
hmm, strange about the semicolons. they don't appear to have semicolons in KG2.3.4:

```
match (n) where n.id in ["UniProtKB:P00390", "UniProtKB:P04150"] return n.id, n.name, n.full_name, n.synonym
```
n.id | n.name | n.full_name
-- | -- | --
"UniProtKB:P04150" | "GR" | "Glucocorticoid receptor"
"UniProtKB:P00390" | "GR" | "Glutathione reductase, mitochondrial"

(though they do still have identical "names".)

do you know when the `NodeNamesDescriptions_KG2.tsv` you're looking at was generated? (could it possibly be made from an old KG2 version?)

I think KG2 is getting "GR" from the protein `short name` that uniprot gives, which is indeed "GR" for both. though uniprot's `gene name`s do appear to be distinct for the two concepts (GSR vs. NR3C1):

https://www.uniprot.org/uniprot/P00390
![Screen Shot 2020-12-14 at 5 41 55 PM](https://user-images.githubusercontent.com/49423686/102157364-31d20100-3e34-11eb-9a5b-7e41dbc3efb1.png)

https://www.uniprot.org/uniprot/P04150
![Screen Shot 2020-12-14 at 5 48 19 PM](https://user-images.githubusercontent.com/49423686/102157569-92613e00-3e34-11eb-9559-9fd4c8298b19.png)

I'm also not sure of the best way of addressing this... might using uniprot's 'gene name' in KG2 be something to consider?

**Comment by edeutsch** [comment]
ah, okay, you're right, I seem to be doing my grepping in a version from August. I have updated the files, and the semi-colon problem is indeed gone away.

So that leaves the problem of GR

The only solution I can think of it is to hard-code in the NodeSynonymizer that
UniProtKB:P04150 is not GR
UniProtKB:P00390 is not GR

and thus you will not be able to find these CURIEs via "GR" (probably no big loss)
and then the benefit is that they will not be coalesced either.

does that seem like the best solution?

I could also just deny GR to one of them if we can decide which one isn't deserving of GR

**Comment by amykglen** [comment]
looks like this is fixed now? from production:

![Screen Shot 2021-04-01 at 3 19 03 PM](https://user-images.githubusercontent.com/49423686/113359953-a9ea0700-92fd-11eb-8de9-96ecab4bfd90.png)

https://arax.ncats.io/?term=UniProtKB:P04150
