### ISSUE TITLE
Test failing

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1166]
Current `master` is seeing a test failure:
```
============================================================= FAILURES ==============================================================
_______________________________________________ test_overlay_exposures_data_attribute _______________________________________________

    def test_overlay_exposures_data_attribute():
        query = {"previous_message_processing_plan": {"processing_actions": [
            "add_qnode(curie=MONDO:0012607, id=n0)",
            "add_qnode(curie=MONDO:0010940, id=n1)",
            "add_qedge(source_id=n0, target_id=n1, id=e0)",
            "expand(kp=ARAX/KG2)",
            "overlay(action=overlay_exposures_data)",
            "resultify()",
            "return(message=true, store=false)",
        ]}}
        [response, message] = _do_arax_query(query)
        assert response.status == 'OK'
        print(response.show())
>       _attribute_tester(message, 'icees_p-value', 'EDAM:data_1669', 1)

test_ARAX_overlay.py:582: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

message = {'_datetime': '2020-12-15 00:32:22',
 'code_description': 'Normal completion',
 'context': 'https://raw.githubusercont...ce', 'essence', 'essence_type'],
 'terms': None,
 'tool_version': 'ARAX 0.6.0',
 'type': 'translator_reasoner_message'}
attribute_name = 'icees_p-value', attribute_type = 'EDAM:data_1669', num_different_values = 1

    def _attribute_tester(message, attribute_name: str, attribute_type: str, num_different_values=2):
        """
        Tests attributes of a message
        message: returned from _do_arax_query
        attribute_name: the attribute name to test (eg. 'jaccard_index')
        attribute_type: the attribute type (eg. 'EDAM:data_1234')
        num_different_values: the number of distinct values you wish to see have been added as attributes
        """
        edges_of_interest = []
        values = set()
        for edge in message.knowledge_graph.edges:
            if hasattr(edge, 'edge_attributes'):
>               for attr in edge.edge_attributes:
E               TypeError: 'NoneType' object is not iterable

test_ARAX_overlay.py:55: TypeError
```

**Comment by amykglen** [comment]
hm - looks like 422 errors again from ICEES, same as in #1156, which spontaneously went away...
```
  - 2020-12-14 16:50:30.398140 WARNING: ICEES+ API returned response of 422
```

**Comment by edeutsch** [comment]
Still a problem for me.

I wonder if it seems reasonable/desirable to set things up so that this particular problem is handled gracefully, i.e. instead of throwing an iteration error, just acknowledge that ICEES returned an error code and information is not available from them at this time and allow the test to pass.

**Comment by edeutsch** [comment]
I rolled out the latest code and I am still or again getting this error.

Since we are about to start tearing apart and rebuilding the codebase,
and since there is talk on the deployment group about automating the tests and reporting them to NCATS,
I think it would be beneficial if our tests can pass even if the remote service is down.
I think our code should handle this gracefully and perhaps generate a warning, but otherwise complete without error.
This would allow us to be in a state where all tests pass as we make extensive code changes.

What do you think?

**Comment by amykglen** [comment]
fair enough - I just added changes for that to `master` for the ICEES tests.

I suppose the downside is that we won't necessarily notice if our integration with a KP breaks (I'm not sure what is causing the ICEES errors in this case - maybe they changed what query format they want). though a warning is indeed logged:
```
  - 2021-01-04 10:47:15.213257 WARNING: ICEES+ API returned response of 422
  - 2021-01-04 10:47:15.213325 WARNING: Could not find ICEES+ exposures data for any edges in the KG
```

**Comment by edeutsch** [comment]
hmm, perhaps this is not the best thing then. Maybe there is a more elegant way to handle remote instability when testing.
maybe some testing flag remote_failure_is_error true/false flag would be useful

**Comment by amykglen** [comment]
hmm, that's an interesting thought for a `remote_failure_is_error` flag... I guess if `remote_failure_is_error=true`, the pytests would have to look for a particular warning message in the `Response` (reporting the remote API failure) and throw an error if found?

I guess we could also attempt to get more precise by looking at the particular HTTP response code returned - e.g., throw an error if it's a client error (400-499 - presumably our fault) but otherwise just issue a warning if it's a server error (500-599 - presumably their fault)?

**Comment by amykglen** [comment]
just checked and it looks like the same issue (#1176) is still happening with the ICEES API (though the pytest is happily passing for the moment since we opted for that) - will plan to adjust these tests again once #1196 is in place so that we're not totally blind to such issues. for now I'll just remove the 'high priority' and 'bug' tags.

**Comment by dkoslicki** [comment]
Current tests are passing, so closing
