### ISSUE TITLE
Inspect locus type in HGNC ETL so category labels are correctly populated

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1169]
Instead of labeling everything in the HGNC ETL as a gene, make sure to inspect the `locus type` field. Some of these are listed as `phenotype only` and should not be categorized as genes.

**Comment by dkoslicki** [comment]
Relevant to #1167

**Comment by saramsey** [comment]
Hi @dkoslicki thank you for bringing this issue to my attention. Well, that's an embarrassing bug!  Marking high priority.

**Comment by kvarforl** [comment]
Also, from discussion in the AHM, it sound like excluding genes that have been withdrawn from the graph or annotating them with "WITHDRAWN" might be a good idea

**Comment by kvarforl** [comment]
Okay, so I believe the HGNC nodes are ETL'd in as a part of `multi_ont_to_json_kg.py`,  so I would assume that is where this change would be made. @saramsey I'm happy to make a guess at changes, but could use your help/ validation!

**Comment by saramsey** [comment]
We probably need:
1. an `ont-inventory-1169.yaml` file for just the `biolink-model.owl` file and our test `umls-hgnc-1169.ttl` file.
2. a test `umls-hgnc-1169.ttl` file that we will build by hand, by slicing and dicing a few entries from `umls-hgnc.ttl`.

**Comment by saramsey** [comment]
Instead of `phenotypic feature`, let's use the Biolink category of `genomic entity` for these HGNC records that have `LOCUS TYPE` of `phenotype only`

**Comment by saramsey** [comment]
Closing this out as it is basically subsumed by #1170
