### ISSUE TITLE
UpdateNodesInfo - please print some indication of progress to STDOUT

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#117]
It would be very helpful if UpdateNodesInfo.py could print some progress information to STDOUT.

**Comment by DeqingQu** [comment]
In the previous version, the progress information is passed to the 'result_output.txt' file, not STDOUT. I modified all codes about the print function and now all progress information will be printed to STDOUT.

**Comment by saramsey** [comment]
thank you
