### ISSUE TITLE
Consider adapting KG2 build process to label protein names with species if not human

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1171]
Especially for the NodeSynonymizer it is potentially confusing when there are many proteins from different species with the same name. Initiated by #1164.

for example:
```
UniProtKB:P11198	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}	protein
UniProtKB:P39033	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}	protein
UniProtKB:P30214	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}	protein
UniProtKB:P26451	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}	protein
UniProtKB:B3SRR1	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}	protein
UniProtKB:Q82040	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04125}	protein
UniProtKB:P11196	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}	protein
UniProtKB:Q01641	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}	protein
UniProtKB:P13842	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}	protein
UniProtKB:P21284	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}	protein
UniProtKB:P11197	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}	protein
UniProtKB:P11199	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}	protein
UniProtKB:Q9WAK4	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}	protein
UniProtKB:P11195	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}	protein
UniProtKB:Q08778	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}	protein
UniProtKB:P11200	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}	protein
```
These all have the same name, but are from different virus species.

The whole '{ECO:0000255|HAMAP-Rule:MF_04132}' part is a little icky and not obviously helpful.

But the real point is that disambiguating these protein names by changing:

```
UniProtKB:P11198	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}	protein
UniProtKB:P11200	Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}	protein
```

to:

```
UniProtKB:P11198	Outer capsid protein VP4 (RV-A)	protein
UniProtKB:P11200	Outer capsid protein VP4 (Rotavirus A (strain St. Thomas 3))	protein
```

seems advantageous. There seemed to be agreement on the call.

**Comment by kvarforl** [comment]
Some other possible funky naming stuff happening in `uniprotkb_dat_to_json.py` to consider while addressing this: #1160

**Comment by saramsey** [comment]
This seems doable. Might be sufficient to just modify L269 of `uniprotkb_dat_to_json.py` so that it is like this:
```
name + ' (' + record['organism'] + ')'
```
(but of course, this assumes `record['organism']` is not `None`, and I'm not 100% confident that it is always not `None`!)

**Comment by kvarforl** [comment]
Something like
```
name + ' (' + record_dict.get('organism', None) + ')'
```
? or should we use something else for the default value: maybe "NA" or just an empty string ""?

**Comment by edeutsch** [comment]
I would go with 'unknown species' instead of None.
And if the organism is human 9606, then there should be nothing at all. no parens or anything. only non-human proteins should have the (species name) suffix (IMO)

**Comment by kvarforl** [comment]
@edeutsch that makes sense to me! 
Just doing the above suggestion will keep the evidence code sections (example from above `{ECO:0000255|HAMAP-Rule:MF_04132}` in the name. It feels a bit wasteful to just hack it off an not store it anywhere else in the node, but I understand how it could make synonimization strange.  

There are a handful of options that I can think of:

1.  Remove the evidence section from the name and wait for there to be marching orders from the EPC modelling discussions to use that information.
2.  Leave the evidence section in the name.
3.  Pull the evidence section off of the name and store it somewhere else in the node: possibly in the description?

Let me know what you guys think makes the most sense @saramsey @edeutsch

**Comment by edeutsch** [comment]
I would suggest removing it from the name since it is quite unsightly there. Adding it to the description in the interim until we have a more detailed EPC data model seems the most reasonable to me.

**Comment by kvarforl** [comment]
Okay! I've put these changes in PR #1174. 

> With these changes, here is an example of a node id and name for something annotated as human species:
> https://www.uniprot.org/uniprot/P0DJZ0
> 
> ```
> UniProtKB:P0DJZ0        11K
> ```
> 
> And here is an example of a node id and name for a non human species:
> https://www.uniprot.org/uniprot/O57245
> 
> ```
> UniProtKB:O57245        3-beta-HSD (Vaccinia virus (strain Ankara) (VACV))
> ```
> 
> The evidence codes from the names are now at the end of the description field, formatted as "Evidence Codes from Name: {ev_codes} "

**Comment by saramsey** [comment]
So, with the PR that I just saw, will the species name also be put into the `full name` field of the node, or just into the `name` field of the node?

**Comment by kvarforl** [comment]
Right now it's only added to the `name` field, but I can also add it to `full name` if you would like (makes alot of sense to me, I just spaced it!)

**Comment by kvarforl** [comment]
hmm, looks like this fix worked for some but not all of the proteins in question.
`match (n) where n.id in ["UniProtKB:O57245","UniProtKB:P11198","UniProtKB:P11200"] return n.id,n.name`


n.id | n.name
-- | --
"UniProtKB:O57245" | "3-beta-HSD (Vaccinia virus (strain Ankara) (VACV))"
"UniProtKB:P11198" | "Outer capsid protein VP5*"
"UniProtKB:P11200" | "Outer capsid protein VP5*"


Will investigate shortly!

**Comment by kvarforl** [comment]
Ah I see that I incorrectly determined whether or not the organism species was human, as the substring "human" _is_ present in the organism species field of `UniProtKB:P11198`.
```
OS   Rotavirus A (isolate RVA/Human/Sweden/1076/1983/G2P2A[6]) (RV-A).
```
from the [uniprot documentation](https://www.uniprot.org/docs/userman.htm#OS_line), I see that I should probably search for "homo sapiens (human)" instead. I'll test this fix now!

**Comment by kvarforl** [comment]
okay this is looking substantially better in KG2.5.1.


n.id | n.name
-- | --
"UniProtKB:O57245" | "3-beta-HSD (Vaccinia virus (strain Ankara) (VACV))"
"UniProtKB:P11198" | "Outer capsid protein VP5* (Rotavirus A (isolate RVA/Human/Sweden/1076/1983/G2P2A[6]) (RV-A))"
"UniProtKB:P11200" | "Outer capsid protein VP5* (Rotavirus A (strain RVA/Human/United Kingdom/ST3/1975/G4P2A[6]) (RV-A)(Rotavirus A (strain St. Thomas 3)))"

@edeutsch is this sufficient to close out this issue, or would more fine tuning be useful?
