### ISSUE TITLE
change simplified_relation to predicate

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1173]
It looks like we are supposed to use the property name `predicate` instead of `simplified_relation`, for edges in KG2.  See this excerpt from `biolink-model.yaml`:

<img width="851" alt="Screen Shot 2020-12-17 at 9 49 27 PM" src="https://user-images.githubusercontent.com/5562107/102579667-c5fccc00-40b1-11eb-8602-2170f5656642.png">

**Comment by kvarforl** [comment]
![image](https://user-images.githubusercontent.com/39020520/103370037-a043cf80-4a80-11eb-9b4d-037c4e536d0c.png)

Makes sense to me! I'm guessing I should essentially be swapping the values between `predicate` and `simplified_relation`?

(from the neo4j screenshot above,  this means that `predicate` would be `biolink:subclass_of` and `simplified_relation` would be `sub_property_of`)

**Comment by kvarforl** [comment]
```
~/Research/RTX/code/kg2$ grep "simplified_relation" *.py
filter_kg_and_remap_predicates.py:        simplified_relation_curie = relation_curie
filter_kg_and_remap_predicates.py:            simplified_relation_curie = remap_subinfo[1]
filter_kg_and_remap_predicates.py:        edge_dict['simplified_relation'] = simplified_relation_curie
filter_kg_and_remap_predicates.py:        if simplified_relation_curie not in nodes_dict:
filter_kg_and_remap_predicates.py:            simplified_relation_curie_prefix = simplified_relation_curie.split(':')[0]
filter_kg_and_remap_predicates.py:            simplified_relation_uri_prefix = curie_to_uri_expander(simplified_relation_curie_prefix + ':')
filter_kg_and_remap_predicates.py:            if simplified_relation_uri_prefix == simplified_relation_curie_prefix:
filter_kg_and_remap_predicates.py:                relation_curies_not_in_nodes.add(simplified_relation_curie)
kg_json_to_tsv.py:                    "simplified_relation",
kg_json_to_tsv.py:        edgekeys.append('simplified_relation')
kg_json_to_tsv.py:            edgekeys = no_space('simplified_relation', edgekeys, 'predicate:TYPE')
report_stats_on_json_kg.py:    curie_field = 'relation' if not args.use_simplified_predicates else 'simplified_relation'
report_stats_on_json_kg.py:    curie_field = 'relation' if not args.use_simplified_predicates else 'simplified_relation'
report_stats_on_json_kg.py:    curie_field = 'relation' if not args.use_simplified_predicates else 'simplified_relation'
slim_kg2.py:    edge_set = set(["simplified_relation", "subject", "object", "simplified_predicate", "provided_by"])
validate_predicate_remap_yaml.py:        simplified_relation = subinfo[1]
validate_predicate_remap_yaml.py:        if not simplified_relation.startswith('biolink:') and not simplified_relation.startswith('skos:closeMatch'):
validate_predicate_remap_yaml.py:            if simplified_relation.startswith('FMA:') or \
validate_predicate_remap_yaml.py:               simplified_relation.startswith('BSPO:') or \
validate_predicate_remap_yaml.py:               simplified_relation.startswith('UBERON:'):
```

**Comment by kvarforl** [comment]
since the word predicate is somewhat rampant in the code and a lot to dig through, I'm using [this](https://github.com/RTXteam/RTX/commit/c053b41681d49a25b9187c6fdb2e157b53c1728e) commit from #1126 as a reference to figure out what needs to be changed to `simplified relation` (the commit for 1126 successfully changed `edge_label` to `predicate`, but instead should have changed `edge_label` to `simplified_relation` i think)

**Comment by kvarforl** [comment]
I'm starting a test-build on kg2lindsey to see if my changes worked as expected

**Comment by kvarforl** [comment]
Okay, with the changes to `filter_and_remap_predicates.py` above, here are some sample edges from `kg2-simplified-test.json` on kg2lindsey (i added the pluses for the sake of highlighting the relevant fields `predicate`, `relation`, `simplified_predicate`, and `simplified_relation`.
```diff
    "edges": [
        {
            "negated": false,
            "object": "biolink:overlaps",
+          "predicate": "biolink:subclass_of",
            "provided_by": [
                "biolink_download_source:biolink-model.owl.ttl"
            ],
            "publications": [],
            "publications_info": {},
+          "relation": "rdfs:subPropertyOf",
+          "simplified_predicate": "subclass_of",
+          "simplified_relation": "sub_property_of",
            "subject": "biolink:has_part",
            "update_date": "Fri Dec  4 00:30:59 2020"
        },
        {
            "negated": false,
            "object": "biolink:overlaps",
+          "predicate": "biolink:subclass_of",
            "provided_by": [
                "biolink_download_source:biolink-model.owl.ttl"
            ],
            "publications": [],
            "publications_info": {},
+          "relation": "rdfs:subPropertyOf",
+          "simplified_predicate": "subclass_of",
+           "simplified_relation": "sub_property_of",
            "subject": "biolink:part_of",
            "update_date": "Fri Dec  4 00:30:59 2020"
        },
```

This causes an assertion error in `report_stats_on_json_kg.py`, so looking into that now.
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/report_stats_on_json_kg.py", line 172, in <module>
    'number_of_edges_by_predicate_curie_prefixes': dict(count_edges_by_predicate_curie_prefix(edges)),
  File "/home/ubuntu/kg2-code/report_stats_on_json_kg.py", line 106, in count_edges_by_predicate_curie_prefix
    return collections.Counter([get_prefix_from_curie_id(edge[curie_field]) for edge in edges])
  File "/home/ubuntu/kg2-code/report_stats_on_json_kg.py", line 106, in <listcomp>
    return collections.Counter([get_prefix_from_curie_id(edge[curie_field]) for edge in edges])
  File "/home/ubuntu/kg2-code/report_stats_on_json_kg.py", line 39, in get_prefix_from_curie_id
    assert ':' in curie_id
AssertionError
```

**Comment by kvarforl** [comment]
@saramsey  can you verify that the above output of `kg2-simplified.json` is what we're after?

If so, I think it makes sense to tweak `report_stats_on_json_kg.py` to just use `relation` or `predicate` (and not thier simplified counterparts)  in the following functions:
https://github.com/RTXteam/RTX/blob/44761d555125819cd7dfb2a25125e23a21a088cd/code/kg2/report_stats_on_json_kg.py#L104-L112

**Comment by saramsey** [comment]
Hi Lindsey, can you please paste into this issue the "diff" of a JSON object for an edge, before and after the code changes?

**Comment by saramsey** [comment]
I think perhaps an edge should look like this (in JSON):
```
{
           "negated": false,
           "object": "biolink:overlaps",
           "predicate": "biolink:subclass_of",
            "provided_by": [
                "biolink_download_source:biolink-model.owl.ttl"
            ],
            "publications": [],
            "publications_info": {},
            "relation": "rdfs:subPropertyOf",
            "simplified_label": "subclass_of",
            "label": "sub_property_of",
            "subject": "biolink:has_part",
            "update_date": "Fri Dec  4 00:30:59 2020"
        },
```
So I guess I am proposing two additional changes:
1. `label` is the slot that was previously called `edge_label`
2. `simplified_label` is the slot that was previously called `simplified_edge_label`. 

Change (1) above is because `edge label` is now deprecated as a slot in the biolink model, and change (2) is for naming consistency with `label`. Does that make sense?

**Comment by saramsey** [comment]
Happy to discuss this further, as well as go over the code. As for the assertion, yes, we'll have to fix the reporting script as a part of this issue.

**Comment by kvarforl** [comment]
Okay, here is the diff as the code stands right now:
```diff
     "edges": [
         {
             "negated": false,
             "object": "biolink:overlaps",
+           "predicate": "biolink:subclass_of",
-            "predicate": "sub_property_of",
             "provided_by": [
                 "biolink_download_source:biolink-model.owl.ttl"
             ],
@@ -15,14 +15,14 @@
             "publications_info": {},
             "relation": "rdfs:subPropertyOf",
             "simplified_predicate": "subclass_of",
+            "simplified_relation": "sub_property_of",
-            "simplified_relation": "biolink:subclass_of",
             "subject": "biolink:has_part",
             "update_date": "Fri Dec  4 00:30:59 2020"
         },
```


> So I guess I am proposing two additional changes:
> 
> 1. `label` is the slot that was previously called `edge_label`
> 2. `simplified_label` is the slot that was previously called `simplified_edge_label`.
> 
> Change (1) above is because `edge label` is now deprecated as a slot in the biolink model, and change (2) is for naming consistency with `label`. Does that make sense?

I think one of my main points of confusion is what we use `simplified*` to mean: my initial thought was that `simplified` indicated that the slot didn't contain a curie prefix, but it sounds like instead `simplified` is used to indicate that a predicate has been remapped from the original relationship to a biolink relationship. is that a correct interpretation?

I had instead just interpreted the distinction between before and after the remap to be communicated by the labels `relation` (the original source label) and `predicate` (the biolink label the relation was mapped to). I suppose the addition of the term `label` seems unnecessarily confusing to me. What are your thoughts?

**Comment by saramsey** [comment]
Thanks. 

> I think one of my main points of confusion is what we use simplified* to mean: my initial thought was that simplified indicated that the slot didn't contain a curie prefix, but it sounds like instead simplified is used to indicate that a predicate has been remapped from the original relationship to a biolink relationship. is that a correct interpretation?

Your re-interpretation is correct:  "simplified*" means the remapped, not the absence of a CURIE prefix.

**Comment by saramsey** [comment]
Any concerns with having it look like this?

```
{
           "negated": false,
           "object": "biolink:overlaps",
           "predicate": "biolink:subclass_of",
            "provided_by": [
                "biolink_download_source:biolink-model.owl.ttl"
            ],
            "publications": [],
            "publications_info": {},
            "relation": "rdfs:subPropertyOf",
            "simplified_label": "subclass_of",
            "label": "sub_property_of",
            "subject": "biolink:has_part",
            "update_date": "Fri Dec  4 00:30:59 2020"
        },

```

**Comment by saramsey** [comment]
so from the current 2.4.0 format, I think I am proposing to rename edge slots as follows:

1. from `simplified_relation` to `predicate` (per updated biolink standard)
2. from `simplified_edge_label` to `simplified_label` (for consistency with our use of `label` per point 3 below)
3. from `edge_label` to `label` (because `edge_label` is now a deprecated slot name per biolink standard)

does that make sense?

**Comment by kvarforl** [comment]
Hmm, I still think that the addition of the term "label" is a a bit intuitive, since `predicate` and `relation` already provide the same distinction that `label` and `simplified_label` do.

It would make the most sense to my brain if there was a term we used to to indicate the presence or absence of the curie prefix (like my original interpretation of "simplified"), because then we could tack it on to the front of `predicate' and `relation` to keep things consistent.

however, if you want to go with your proposed changes I trust your judgement!

**Comment by saramsey** [comment]
OK, how about:

1. change `simplified_relation` to `predicate` (biolink standard slot)
2. change `simplified_edge_label` to `predicate_label`
3. keep `relation` as-is
4. change `edge_label` to `relation_label`

is that good?

**Comment by kvarforl** [comment]
That sounds great to me!
Just to make sure we're 100% on the same page, an edge would look like this?
```
{
           "negated": false,
           "object": "biolink:overlaps",
           "predicate": "biolink:subclass_of",
            "provided_by": [
                "biolink_download_source:biolink-model.owl.ttl"
            ],
            "publications": [],
            "publications_info": {},
            "relation": "rdfs:subPropertyOf",
            "predicate_label": "subclass_of",
            "relation_label": "sub_property_of",
            "subject": "biolink:has_part",
            "update_date": "Fri Dec  4 00:30:59 2020"
        },
```

**Comment by saramsey** [comment]
yes

**Comment by kvarforl** [comment]
Okay, with the previous three commits on branch `issue1173new`, an edge looks like this, which is in line with what was stated above :)
```
        {
            "negated": false,
            "object": "biolink:overlaps",
            "predicate": "biolink:subclass_of",
            "predicate_label": "subclass_of",
            "provided_by": [
                "biolink_download_source:biolink-model.owl.ttl"
            ],
            "publications": [],
            "publications_info": {},
            "relation": "rdfs:subPropertyOf",
            "relation_label": "sub_property_of",
            "subject": "biolink:has_part",
            "update_date": "Fri Dec  4 00:30:59 2020"
        },
```

**Comment by kvarforl** [comment]
I'm going to go ahead and merge these changes to master and clean up my messy branches :)

**Comment by kvarforl** [comment]
From KG2.5.0 neo4j, here is an example edge:
![image](https://user-images.githubusercontent.com/39020520/104640597-89df6b80-565d-11eb-9301-13bc9a202d47.png)
Looks good to me, so I'm going to close out this issue!
