### ISSUE TITLE
updates to curies-to-categories.yaml to accommodate new Biolink mappings

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1175]
In light of Biolink Model GitHub [PR 587](https://github.com/biolink/biolink-model/pull/587)  and the issues that it links to, [issue 171](https://github.com/biolink/biolink-model/pull/172) and [issue 172](https://github.com/biolink/biolink-model/pull/172), I think we should check that there are entries for these CURIE IDs in `curies-to-categories.yaml` and that they map to the current-standard Biolink category mappings for these CURIEs in `biolink-model.yaml` (as soon as PR587 is merged, of course):
```
     - CHEBI:78295
     - NCBITaxon:1
     - PATO:0000001
     - DOID:4
     - NCIT:C2991
     - HP:0000001
     - CHEBI:24431
     - UBERON:0001062
     - MPATH:0
     - OBO:HsapDv_0000000
     - GMODChado:feature_relationship
     - CHEBI:51086
     - CHEBI:24432
     - NBO:0000313
     - NBO:0000243
```

**Comment by kvarforl** [comment]
Okay, looks like that PR got merged a few days ago. I updated what I could, but noticed the following things:

These were not in `biolink-model.yaml`:
- NCBITaxon:1 (in `curies_to_categories.yaml` as `organism taxon`)
- HP:0000001 
- OBO:HsapDv_0000000
- GMODChado:feature_relationship
- NBO:0000313 (in `curies_to_categories.yaml` as `activity`)

These were mapped to mixins:
- MPATH:0
- CHEBI:51086

Should I be trying to figure out how to use mixins in our remapping process, or just mapping to the next best thing thats not a mixin?

**Comment by kvarforl** [comment]
Along the same lines, `gene product` and `macromolecular complex` have been changed to mixins as well. My best guess for adjustments are:
- `gene product` -> `genomic entity`
- `macromolecular complex` -> `named thing`

Additionally,  `data file` is no longer a valid category. I'm thinking `dataset` is the best replacement, or maybe `information content entity` if we would rather be safe.

I'll wait for confirmation (or the next build) to make these changes, but figured I'd document them in the meantime.

**Comment by saramsey** [comment]
I like the idea of changing `data file` to `information content entity`, which would (due to its generality) probably be safe in all cases.

**Comment by saramsey** [comment]
in `curies-to-categories.yaml`, for `CHEBI:33697`, how about `RNA product` ?

**Comment by saramsey** [comment]
for `NCIT:C813`, we should be using `transcript`

**Comment by saramsey** [comment]
for `NCIT:C111298`, I guess also `transcript`

**Comment by saramsey** [comment]
for `NCIT:C26549`, we should be using `noncoding RNA product`

**Comment by saramsey** [comment]
for `NCIT:C28454`, we should be using `transcript`

**Comment by saramsey** [comment]
for `ORPHANET:410299`, we should be using `noncoding RNA product`

**Comment by saramsey** [comment]
for `EFO:0004446`, I guess we should now be using `molecular entity`

**Comment by saramsey** [comment]
for `NCIT:C21176`, I guess we should now be using `molecular entity`

**Comment by ericawood** [comment]
> Along the same lines, `gene product` and `macromolecular complex` have been changed to mixins as well. My best guess for adjustments are:
> 
>     * `gene product` -> `genomic entity`
> 
>     * `macromolecular complex` -> `named thing`
> 
> 
> Additionally, `data file` is no longer a valid category. I'm thinking `dataset` is the best replacement, or maybe `information content entity` if we would rather be safe.
> 
> I'll wait for confirmation (or the next build) to make these changes, but figured I'd document them in the meantime.

@saramsey Do you have any thoughts on 
>     * `gene product` -> `genomic entity`
> 
>     * `macromolecular complex` -> `named thing`

`validate_kg2_util_curies_urls_categories.py` broke when I tried to run it, so I would like to fix this to test my fix for #1219.

**Comment by kvarforl** [comment]
@ericawood I think that the string of comments above and my most recent commit in this issue took care of at least some of the `macromolecular complex` and 'gene product` occurrences; are there some that were missed ? (Is the validation script still erroring?)

**Comment by ericawood** [comment]
The validation script errors at `macromolecular complex` because it’s still an issue in the constants section of kg2_util.py. What should I fix it to @kvarforl?

**Comment by kvarforl** [comment]
hmm @ericawood I'm not super sure why some of the biolink categories are defined as constants in kg2util; looking into it now!
