### ISSUE TITLE
Adjust curies_to_categories.yaml to work with biolink model updates

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1180]
I ran into a couple of errors when running the validation scripts for KG2.

First is that I believe `abstract entity` (the root of biolink node categories) has been changed to be `entity`.

Second, the node category `provider` is no longer valid. (I still need to look into why, but I used a temporary workaround of changing `provider` to named thing to get my test build up and running. I won't commit this change to `curies_to_categories.yaml` until I've investigated further)

**Comment by saramsey** [comment]
Looks like `provider` is now a descendant of `related to`, not `named thing`. How about using `agent` instead?

**Comment by kvarforl** [comment]
Okay, looks like `gene grouping` got changed to be a mixin. I'm thinking `genomic entity` would be a good substitute?
