### ISSUE TITLE
Ingest text mining KP

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1187]
Looks like the text mining KP is now registered at SmartAPI: https://smart-api.info/registry?q=4ea6d865ffb6de29023e0f294347526e

We should look into what sort of info we can get from it. I imagine we should poke at it a bit, and if it's not clear what's going on, set a meeting with this KP team to figure out how to integrate it.

**Comment by dkoslicki** [comment]
This might be helpfule: http://35.232.64.189/docs

**Comment by finnagin** [comment]
Trying to send queries results in an error right now. Should probably wait to try again during the relay.

**Comment by finnagin** [comment]
@finnagin to contact text mining and ask about other things on their roadmap and enquire about possibly ETLing like COHD.

**Comment by finnagin** [comment]
@dkoslicki @amykglen So you know if this is still relevant. Does expand already reach out to the text mining kp?

**Comment by dkoslicki** [comment]
@finnagin I don't think we are reaching out to text mining KP. Can you reach out to them to see if they have a KGX file or the like so we can ingest it?

**Comment by amykglen** [comment]
if they have a TRAPI API we can plug them into expand very easily! unclear to me if they do though? maybe they have a SmartAPI-provided TRAPI API? (like the Multiomics KPs..)

**Comment by finnagin** [comment]
Looks like they do: https://smart-api.info/registry?q=text

**Comment by finnagin** [comment]
Looks like the "Automat Textmining KP" api is listed as using TRAPI 1.2.0

Not sure about the other ones

**Comment by finnagin** [comment]
Here is the docs link: https://smart-api.info/ui/d2eecc42b6ae9109b12bcd215c787479

**Comment by amykglen** [comment]
posting for the record: @rcpeene has started working on plugging this KP into Expand, although we're struggling to find a working example query (the example query in their Swagger documentation doesn't align with what's reported in their Meta KG...) I'm going to reach out to them to see if we can get that sorted out.

**Comment by amykglen** [comment]
one note for @rcpeene - I think the official infores curie for this API is `infores:biothings-text-mining-provider`. 

fyi, this spreadsheet is where the agreed upon infores curies (that all of Translator should use to refer to KPs/ARAs/other knowledge sources) are documented: https://docs.google.com/spreadsheets/d/1Ma4U3aY16mJushsW74vf9mWVacFvf7FiTEdlVqaUi5g/edit#gid=1644860829

![Screen Shot 2022-02-15 at 4 34 48 PM](https://user-images.githubusercontent.com/49423686/154173857-601618b0-b900-439a-b5fd-f1acb1d8001b.png)

**Comment by amykglen** [comment]
@rcpeene - ok, here's an example query I got from Yaphet:
```
{
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "ids": [
            "BFO:0000030"
          ],
          "categories": [
            "biolink:GeneOrGeneProduct"
          ]
        },
        "n1": {          
          "categories": [
            "biolink:MolecularActivity"
          ]
        }
      },
      "edges": {
        "e0": {
          "subject": "n0",
          "object": "n1",
          "predicates": [
            "biolink:related_to"
          ]
        }
      }
    }
  },
  "workflow": [
    {
      "id": "lookup"
    }
  ]
}
```
he also noted that if we want to explore the underlying graph more we can also use the cypher endpoint:
```
curl -X POST "https://automat.renci.org/textminingkp/cypher" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"query\":\"MATCH (n:`biolink:GeneOrGeneProduct`)-[e]-(b:`biolink:MolecularActivity`) RETURN n.id, type(e) limit 10\"}"
```

**Comment by amykglen** [comment]
Eric raised a good point today - if BTE includes Text Mining KP, then Expand should already be getting Text Mining KP answers through BTE... might be worth verifying whether this is the case. This integration might just be redundant if so?

**Comment by rcpeene** [comment]
I took the above query and implemented it as a DSL query in the pytest suite, like so:
```
        "add_qnode(ids=BFO:0000030, categories=biolink:GeneOrGeneProduct, key=n00)",
        "add_qnode(categories=biolink:MolecularActivity, key=n01)",
        "add_qedge(subject=n00, object=n01, key=e00)",
        "expand(kp=infores:automat-text-mining-provider)",
        "return(message=true, store=false)"

```
And yet it returns no results.

**Comment by dkoslicki** [comment]
Removing Finn. @amykglen @rcpeene let us know if there is anything blocking this issue, or if it should be closed

**Comment by rcpeene** [comment]
With the new changes addressed in [issue 1466](https://github.com/RTXteam/RTX/issues/1466), infores:automat-text-mining-provider should be a KP that is automatically used by ARAX. A quick usage of `python3 smartapi.py get_kps -p` Shows that this KP does indeed show up. Therefore we can close this issue.
