### ISSUE TITLE
FET score adjustment in ranker

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1188]
The following query:
```
add_qnode(id=n00,curie=[UniProtKB:P14136,UniProtKB:P35579],is_set=true,type=protein)
add_qnode(type=biological_process, id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00,kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n00, target_qnode_id=n01, virtual_relation_label=FET)
resultify()
```
(which is mentioned in #717) results in all scores the same even though the p-values vary quite a bit (eg. 0.0228, 0.00228, 0.000695, etc.). This appears to indicate that the ranker sigmoid needs to be adjusted.

**Comment by dkoslicki** [comment]
Which is odd since the current ranker maps 0.00228 to a confidence of 0.999961, so I don't know why it isn't propagating through ranker

**Comment by dkoslicki** [comment]
@finnagin , this might be similar to #1190 , but this code was run on production, so it's not exactly the same issue.

**Comment by finnagin** [comment]
After the TRAPI 1.0 merge I am not able to replicate this issue so I think it must have been related to #1190. I've gone ahead and added a test for this to `test_ARAX_workflows.py` but I think this is solved now.
