### ISSUE TITLE
report changes in numbers of edges (for each type of upstream knowledge source) for a new KG2 build

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1189]
It would be good to have a script that is run as a part of the build process, that computes, and reports on (in summary form) the change in the number of edges for each provided-by CURIE (i.e., each upstream knowledge source), and maybe issues a warning to STDERR if there is a large drop in the overall edge count for any specific upstream source.

**Comment by saramsey** [comment]
this would catch issues like #1185 earlier in the build process

**Comment by saramsey** [comment]
removing the "low priority" label because I think it is actually an important issue

**Comment by ericawood** [comment]
Since this worked (see report listed in #1400), I am going to close this issue out.
