### ISSUE TITLE
attribute.type is a required field

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1192]
In trying to slurp some ARAX output back into the data model, I am getting the error that attribute types are null, e.g. here:
https://arax.ncats.io/devED/?r=158
(CTRL+F for attributes)

This is not permitted:
https://github.com/NCATSTranslator/ReasonerAPI/blob/c77d48eb9e8208ad400d890bf706f60db48d4553/TranslatorReasonerAPI.yaml#L512

Can we make sure that all attributes have a type?

**Comment by finnagin** [comment]
Sure! What should the types be for things like provided_by, date, etc?

**Comment by amykglen** [comment]
ok, can do - these are the attributes currently created in `expand` that we'll need to figure out types for:

* `all_names` e.g., ['Sodium equilin sulfate', 'Estratab']
* `deprecated` e.g., False
* `description`
* `equivalent_curies` e.g., ['UMLS:C0242700', 'MESH:D018489', 'SNOMED:21162009']
* `full_name`
* `is_defined_by` e.g., "ARAX/KG2"
* `negated` .e.g, False
* `probability` e.g., 0.00019258212
* `provided_by` e.g., 'umls_source:ATC' on nodes or ['SEMMEDDB:', 'umls_source:MTH'] on edges
* `publications` e.g., ["PMID:16798005", "PMID:24139633", "PMID:6208804"]
* `relation` e.g., 'rdfs:subClassOf'
* `symbol` e.g., 'BRCA1'
* `synonym` e.g., ['Imidazole derivatives', 'intestinal antiinfectives']
* `update_date` e.g., 'Mon Jan  4 19:28:17 2021'
* `uri`

**Comment by finnagin** [comment]
@amykglen I found this site to find EDAM identifiers for types: [Link to the URI page](http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fdata_1047)

**Comment by finnagin** [comment]
[Here is another one that might be nicer to navigate](https://ifb-elixirfr.github.io/edam-browser/#data_1052)

**Comment by finnagin** [comment]
@amykglen I found a browser for the biolink types [here](https://biolink.github.io/biolink-model/docs/entities.html). I think the way we are supposed to fill these in is:
1. Look for a Biolink entity that fits the attribute
2. If no entity fits look for an EDAM entry that fits
3. If no EDAM entry exists write something discriptive

**Comment by finnagin** [comment]
@edeutsch For Date should I be using [biolink:TimeType](https://biolink.github.io/biolink-model/docs/types/TimeType.html) or [metatype:Datetime](https://biolink.github.io/biolink-model/docs/types/Datetime.html)?

**Comment by edeutsch** [comment]
@finnagin I don't know. The metatype:Datetime looks more pleasing.

I think it would be super useful to create a markdown table of all the attributes. then we can post it on the TRAPI github site and squabble over what the best way to do it is. 

Can someone create a markdown table of all the attributes we use?

Both for the ones where we think we know the right type and those for which we don't know yet. We can get the other teams to help with this. I'm thinking 4 columns:
name
type
example values
comments

**Comment by finnagin** [comment]
Good idea! Here is my first pass at it:

name | type | example values | comments
| --- | --- | --- |--- |
is_defined_by | UNKOWN | "ARAX", "ARAX/KG2" | Not sure what type to use for this one...
defined_datetime | metatype:Datetime | "2020-04-19 12:42:36" | 
provided_by | biolink:provided_by | "umls_source:NCI" | 'umls_source:ATC' on nodes or ['SEMMEDDB:', 'umls_source:MTH'] on edges
confidence | biolink:ConfidenceLevel | 1, 0.5 | 
weight | metatype:Float | 1, 0.5 | Wasn't sure if there was a better type to use than Float as I didn't find any specially mentioning edge weights. 
all_names |  | ['Sodium equilin sulfate', 'Estratab'] | Not sure what to put for this...
deprecated | metatype:Boolean | False | Wasn't sure what to put for this. Not sure if Boolean is a good fallback type or it should be something else.
description | biolink:description | | 
equivalent_curies | biolink:synonym | ['UMLS:C0242700', 'MESH:D018489', 'SNOMED:21162009'] | Thought this might also be a synonym type
full_name | biolink:full_name | |
negated | biolink:negated | False |
probability | biolink:p_value | 0.00019258212 | Thoughts on p-value for probability?
publications | biolink:publications | ["PMID:16798005", "PMID:24139633", "PMID:6208804"] |
relation | biolink:relation | 'rdfs:subClassOf' |
symbol | biolink:symbol | 'BRCA1' |
synonym| biolink:synonym | ['Imidazole derivatives', 'intestinal antiinfectives'] |
update_date| metatype:Datetime | 'Mon Jan 4 19:28:17 2021' |
uri | metatype:Uri | |

Maybe we should go over it at the AHM?

**Comment by amykglen** [comment]
ok, as decided at the minihackathon today, I've added placeholder types to all `Attribute`s that `expand` adds. will plan to refine them later once they're discussed with the API working group.

**Comment by edeutsch** [comment]
@amykglen Are they all in the above table?

I have created a TRAPI working group PR to discuss this table in its current state

**Comment by amykglen** [comment]
yep, all are in the above table, @edeutsch.

**Comment by finnagin** [comment]
@edeutsch Did the table ever end up getting discussed in the TRAPI working group?

**Comment by edeutsch** [comment]
Yes, it was perceived as a key item to resolve. Discussion has been moved here:
https://docs.google.com/spreadsheets/d/1-ilDWePMLniA9Tha5J6HHHFylO5w6lZ9FFfA2Mp5oro
If you have any more information information to contribute, please do contribute it there.

**Comment by finnagin** [comment]
Thanks! I'll take a look.

**Comment by edeutsch** [comment]
To everyone who creates node or edge Attributes in their code, the current spreadsheet is here:
https://docs.google.com/spreadsheets/d/1-ilDWePMLniA9Tha5J6HHHFylO5w6lZ9FFfA2Mp5oro
It is split into two tabs, a node Attributes and an edge Attributes.
Any contributions that you can make about the Attributes that ARAX currently writes would be most helpful.
thanks!

**Comment by amykglen** [comment]
@edeutsch - safe to close this issue? fairly outdated, and I think our attributes are in good shape now.

**Comment by edeutsch** [comment]
agreed, closing, thanks.
