### ISSUE TITLE
qnode_keys missing in external message

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1193]
I was trying to get a workflow operation going where ARAX takes a previous message, then computes NGDs for all edges, reranks and returns. It was going pretty well until:
```
ERROR: [UncaughtARAXiError] An uncaught error occurred: 'Node' object has no attribute 'qnode_keys': ['Traceback (most recent call last):\n', '  File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 568, in executeProcessingPlan\n    overlay.apply(response, action[\'parameters\'])\n', '  File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 479, in apply\n    getattr(self, \'_\' + self.__class__.__name__ + \'__\' + parameters[\'action\'])()  # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', '  File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 544, in __compute_ngd\n    response = NGD.compute_ngd()\n', '  File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Overlay/compute_ngd.py", line 69, in compute_ngd\n    node_pairs_to_evaluate = ou.get_node_pairs_to_overlay(subject_qnode_key, object_qnode_key, qg, kg, self.response)\n', '  File "/mnt/data/orangeboard/devED/RTX/code/ARAX/ARAXQuery/Overlay/overlay_utilities.py", line 27, in get_node_pairs_to_overlay\n    kg_nodes_by_qg_id = get_node_ids_by_qg_id(knowledge_graph)\n', '  File "/mnt/data/orangeboard/devED/RTX/code/ARAX/ARAXQuery/Overlay/overlay_utilities.py", line 68, in get_node_ids_by_qg_id\n    for qnode_key in node.qnode_keys:\n', "AttributeError: 'Node' object has no attribute 'qnode_keys'\n"]
```

I'm thinking that our cleverness of using qnode_keys has come back to bite us. Overlay can rely on qnode_keys when getting a graph from Expand(). but if the graph comes from the wilds elsewhere, it won't have those. They're not part of the TRAPI model.

Maybe we need to have a method call to recompute them from the results? Is there such a thing?

**Comment by amykglen** [comment]
hm, yeah - that seems to make sense to have a method that recomputes them from the results. I'm not aware of one already in existence, but it would be easy to do. where do you think it should live?

**Comment by edeutsch** [comment]
great, thanks. I cannot think of a particular place that is the logical place. Messenger, Expander, Resultify. Could fit in any of them. Wherever you like. I think the only parameter would be 'response' as usual, probably with an error if no results[ ]

So I'm thinking about something like this:
```
            from ARAX_resultify import ARAXResultify
            resultifier = ARAXResultify()
            resultifier.recompute_qnode_keys(response)
            if response.status != 'OK':
                   return response
```

**Comment by amykglen** [comment]
that sounds good to me! I can add the method to resultify.

**Comment by amykglen** [comment]
ok, the method is in place in `master`, though I named it `recompute_qg_keys()`, since technically it has to recompute both qnode_keys and qedge_keys. it works in just the way you described:
```
resultifier = ARAXResultify()
resultifier.recompute_qg_keys(response)
```
I did some testing (added a pytest for it), but let me know if you run into any issues.

one thing worth noting is that it throws an error if there are any nodes/edges in the KG that **don't** appear in any results (since it has no way of recomputing qg keys for such nodes/edges).

**Comment by edeutsch** [comment]
outstanding! Just the thing we need. I will test soon, thanks!

**Comment by amykglen** [comment]
good to close this issue, @edeutsch? (believe you tested it in #1462)

**Comment by edeutsch** [comment]
yes, great, thanks!
