### ISSUE TITLE
UniChem direct mappings between CHEBI-DRUGBANK and CHEMBL-DRUGBANK

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1197]
We are currently using UniChem to map directly between CHEBI and ChEMBL, which is great.

But UniChem also provides mappings between CHEBI and DrugBank, and between ChEMBL and DrugBank. We should ETL those, as it is low-hanging fruit. In fact, the script `exctract-unichem.sh` is already downloading the relevant files:

```
ls unichem
UC_RELEASE.txt.gz  UC_XREF.txt.gz  chembl-to-curies.tsv  drugbank.txt
UC_SOURCE.txt.gz   chebi.txt       chembl.txt
```

**Comment by saramsey** [comment]
I'm tagging @chunyuma and @dkoslicki who can discuss here, but I gather this feature request will help their work on drug repositioning.

**Comment by kvarforl** [comment]
@saramsey  Looks like they are already ETL'd in!

The bottom of `extract-unichem.sh` handles finding and formatting the CHEBI and DRUGBANK relations and then appends them to the end of `kg2-build/unichem/chembl-to-curies.tsv`.

The conversion script then goes through and creates edges for the whole tsv file :)

**Comment by saramsey** [comment]
Actually the CHEBI-to-DRUGBANK mappings were not, due to the weird code I had in extract-unichem.sh. But commits 
de52ff2 and 4c0c0e3 and b0de599 should fix it.
