### ISSUE TITLE
Better consideration of SEMMEDDB edges

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1198]
For this command:
```
add_qnode(id=MONDO:0005784, key=n0)
add_qnode(category=biolink:Disease, key=n1)
add_qedge(subject=n0, object=n1, predicate=biolink:subclass_of, key=e0)
expand(edge_key=e0,kp=ARAX/KG2)
resultify()
```
there is a edge `(MONDO:0018081)->[biolink:subclass_of]->(UMLS:C1519221Id: KG2c:13619255)`, i.e. hemorrhagic fever is a subclass of the abdominal wall. This is clearly not the case, and it appears to be an artifact of very few articles having this triple. Perhaps we can weight the confidence of semmeddb edges by the number of articles that they have.

**Comment by finnagin** [comment]
Yeah I think that would be really useful. Thoughts on me adding it when we are adding the confidence of 1? 

I.E. add an if statement what looks if it is a SemmedDB edge and then add some function that asymptotically approaches 1 as the number of publications increase. Thoughts on the function we should use?

**Comment by finnagin** [comment]
Should we make sure that it adds a 1 if we hit a threshold of publications? I'm thinking it might cause problems if the confidence for a bunch of publications is 0.99

**Comment by dkoslicki** [comment]
Yeah, I'm thinking another logistic is in order: something like 50% confidence at 5 publications, ramping up to something like 80% for 10, etc. @finnagin do you recall the thresholds you imposed for the DTD cutoffs?

**Comment by finnagin** [comment]
I think it was 5 iirc

**Comment by dkoslicki** [comment]
Ok, I think 5->50% with a steep ramp up should work then. And I don't immediately see why a bunch of 0.99... confidences would cause a problem

**Comment by finnagin** [comment]
Ok great! I'll make a new branch and implement this.

**Comment by dkoslicki** [comment]
And let's first compute the confidence on the fly, and when we've tuned it enough, we can then consider running it on all of KG2 during the build process

**Comment by finnagin** [comment]
Looks like a steepness of 2 and a midpoint of 1.60944 works for 5 -> .5 and 10 -> .8
This curve look good to you?
https://www.wolframalpha.com/input/?i=1+%2F+%281+%2B+exp%28-2+*+%28ln%28x%29+-+1.60944%29%29%29+plot+0%3Cx%3C30

**Comment by dkoslicki** [comment]
Hmm..., I think this doesn't fall off to zero fast enough. Note that you have a `ln()` sitting in there which is an artifact when I was dealing with a really large range of p-values. Was thinking of something like this: https://www.wolframalpha.com/input/?i=1+%2F+%281+%2B+exp%28-1+*+%28x+-+5%29%29%29+plot+0%3Cx%3C10 (but will need to be tweaked a bit)

**Comment by dkoslicki** [comment]
Actually, it might still work with the log, after staring at it a bit more. Do you know the distribution of number of publications per edge? i.e. max, mean, median, etc.

**Comment by finnagin** [comment]
I don't. I'll see if I can get something like that from neo4j.

**Comment by finnagin** [comment]
Looks like you can. Running this query to get mean, median, max, and min. Might take a little while as it needs to get through every edge in the graph.
```
match (n)-[r]-(m) where "SEMMEDDB:" in r.provided_by return avg(length(r.publications)), min(length(r.publications)), max(length(r.publications)), percentileDisc(length(r.publications), 0.5)
```

**Comment by finnagin** [comment]
Here are the results:


avg(length(r.publications)) | min(length(r.publications)) | max(length(r.publications)) | percentileDisc(length(r.publications), 0.5)
-- | -- | -- | --
4.8078695392918265 | 1 | 152705 | 1

**Comment by dkoslicki** [comment]
Nice! I think this gives some nice support for 5->50%

**Comment by finnagin** [comment]
Since we had a median of 1 I tried looking up several other percentiles and also running the above query only on examples with more than 1 publication:

percentileDisc(length(r.publications), 0.6) | percentileDisc(length(r.publications), 0.7) | percentileDisc(length(r.publications), 0.8) | percentileDisc(length(r.publications), 0.9) | percentileDisc(length(r.publications), 0.95) | percentileDisc(length(r.publications), 0.975) | percentileDisc(length(r.publications), 0.99) | percentileDisc(length(r.publications), 0.999)
-- | -- | -- | -- | -- | -- | -- | --
1 | 2 | 2 | 5 | 9 | 19 | 47 | 402



avg(length(r.publications)) | min(length(r.publications)) | max(length(r.publications)) | percentileDisc(length(r.publications), 0.25) | percentileDisc(length(r.publications), 0.5) | percentileDisc(length(r.publications), 0.75)
-- | -- | -- | -- | -- | --
12.93942275437553 | 2 | 152705 | 2 | 3 | 6

**Comment by dkoslicki** [comment]
Ah, so do I interpret this correctly as 5 should be given more weight than 50%? Perhaps 3? I'm just a bit confused how in the first table three comments ago, the 50th percentile was 1, but in the last table, it's 3.

**Comment by finnagin** [comment]
Sorry I should have been more clear.

1. Table 1 looks for min, max, mean and median on all edges.
2. Table 2 looks at the 60th, 70th, 80th, 90th, 95th, 97.5th, 99th, and 99.9th percentiles for all edges
3. Table 3 looks for min, max, mean and median on just the edges that have 2 or more publications (was really mostly looking at how much of an influence the massive number of single publication entries had on the mean)

**Comment by dkoslicki** [comment]
Well, in the absence of a nice histogram to really see what's going on, what about 4 pubs for 50% confidence, 8 pubs for 90%?

**Comment by finnagin** [comment]
Works for me! Should we stick with the logistic or or take it out?

**Comment by dkoslicki** [comment]
Let's stick with the logistic with the aforementioned probabilities

**Comment by finnagin** [comment]
Sounds good! I change it to that.

Here is what it looks like plotted: https://www.wolframalpha.com/input/?i=1+%2F+%281+%2B+exp%28-3.16993+*+%28ln%28x%29+-+1.38629%29%29%29+plot+0%3Cx%3C30

**Comment by dkoslicki** [comment]
Looks good to me!
