### ISSUE TITLE
can we systematically ETL drug-to-disease "contraindicated_for" information from Drug Central?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1199]
Looks like we have very few things contraindicated for pregnancy:
```
match (n) where toLower(n.name) contains "pregnancy" with n as n2
match p=(n1:`biolink:ChemicalSubstance`)-[:`biolink:contraindicated_for`]-(n2) return p
```
returns only 3 chemical substances contraindicated for ectopic pregnancy.

**Comment by saramsey** [comment]
don't forget to check `biolink:affects`

**Comment by saramsey** [comment]
This makes me wonder why concept `UMLS:C0032961` (pregnancy), which has semantic type `T040` (physiological process), has a Biolink category `named thing`. That seems not right.

**Comment by saramsey** [comment]
Tagging @ericawood and @kvarforl to investigate

**Comment by saramsey** [comment]
Unfortunately, it looks like DrugBank's contraindications database is pay-only:

https://www.drugbank.com/data/contraindications

we may have to look elsewhere

**Comment by saramsey** [comment]
Looks like we can get drug contraindications from Drug Central:
https://drugcentral.org/download

<img width="504" alt="Screen Shot 2021-02-02 at 3 32 10 PM" src="https://user-images.githubusercontent.com/5562107/106676477-d7b80700-656b-11eb-8333-1d9c08d07cf2.png">

**Comment by ericawood** [comment]
Since this is still labeled with the "question" tag, I figured that I should respond that yes we can. I have most of the ETL done for DrugCentral, including 26698 "contraindicated_for" edges.

**Comment by saramsey** [comment]
Hi @ericawood fantastic!  Per your 3/29 email, did you have a question that you wanted me to look at, before you merge the new code for this ETL?

**Comment by ericawood** [comment]
This appears to be complete in `KG2.6.0`:

`match (n) where split(n.id, ':')[0]='DrugCentral' return count(n)`:

count(n)
--|
4643

`match (n)-[e]-(m) where "DrugCentral:" in e.provided_by return count(distinct e.id)`:

count(distinct e.id)
--|
233473


`match (n)-[e:`biolink:contraindicated_for`]->(m) return e.provided_by, count(e)`:

e.provided_by | count(e)
-- | --
["DrugCentral:"] | 26131

**Comment by dkoslicki** [comment]
@chunyuma Wanted to let you know about this for more training data for the DTD model
