### ISSUE TITLE
Add code to map variant<->disease and variant<->gene, for Q1

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#12]
_From @saramsey on November 24, 2017 15:40_

_Copied from original issue: dkoslicki/NCATS#65_

**Comment by dkoslicki** [comment]
_From @saramsey on November 24, 2017 15:48_

will try to use BioLink for this

needs to have a switch so that we are only expanding disease<->variant for the 21 diseases and for their related phenotypes; not for the Q2 diseases (can do this thanks to the Node.seed_node attribute)

**Comment by saramsey** [comment]
do we need this before the hackathon?

**Comment by dkoslicki** [comment]
No, not that I'm aware of.

**Comment by dkoslicki** [comment]
Closing due to #788
