### ISSUE TITLE
annoying "[ from cache ]" verbose output in QueryMyGene

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#120]
[ from cache ]
[ from cache ]
[ from cache ]
[ from cache ]
[ from cache ]
[ from cache ]
[ from cache ]
[ from cache ]
[ from cache ]
[ from cache ]
[ from cache ]

**Comment by DeqingQu** [comment]
It is quite annoying. I tried to solve the problem when I wrote the QueryMyGene module, but it is not so easy to figure out. I think it is the time to solve this issue and I will deal with it.

**Comment by saramsey** [comment]
fixed in the code; I just need to always pass "verbose=False" whenever calling the "query" method on the MyGeneInfo object.
