### ISSUE TITLE
COHD values not being ranked?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1201]
Check out https://arax.ncats.io/?r=551
and notice that even though the p-value is 0, it's getting a 50% confidence. The debug even makes it appear that the ranker doesn't know about chi_square_pvalue

**Comment by finnagin** [comment]
Looks like this might be because it is looking for an attribute named "chi_square" but the attribute is named "chi_square_pvalue" .

**Comment by dkoslicki** [comment]
Good find!

**Comment by dkoslicki** [comment]
LMK when this is passing tests (maybe make a test for it first, since it wasn't previously being caught), let Eric know so he can update everything

**Comment by finnagin** [comment]
This is in master and passing tests. Good idea on adding a specific test for this though. I'll do that.

**Comment by finnagin** [comment]
So the p-value is being factored in now but it looks like all p-values that are returned are 0 for this query. Is that expected?

**Comment by dkoslicki** [comment]
Hmmm... That's odd. Try it out on the COHD API itself (accessible from smart API) to spot check if that is what it should be

**Comment by finnagin** [comment]
Ok, will do!

**Comment by finnagin** [comment]
Oh I think I see why they are all zero.
Looks like it is likely rounding to me:
```
INFO: Summary of available edge metrics: {'chi_square_pvalue': {'minimum': 1.107217e-309, 'maximum': 1.628068e-277}}
```
Since the max p-value is of the order of 10^-277

**Comment by finnagin** [comment]
Should really be a confidence of 1. Need to look into this again.

**Comment by finnagin** [comment]
@finnagin Reminder to do this...

**Comment by dkoslicki** [comment]
@finnagin Any update on this issue?

**Comment by finnagin** [comment]
@dkoslicki So I've been a little stuck on this one and was planning on asking you about it at our meeting tomorrow. I've dug into it a bit and all of the confidences for every edge end up being 1 as expected but the result confidences are lower than 1. 

Looking into the code it looks like this is happening when the graph scorer is run but I haven't yet been able to decipher what exactly is going on in those lines. I was hoping you might be able to walk me through what is happening in [these lines](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_ranker.py#L574-L586) so I could dig in further to diagnose what is happening.

**Comment by finnagin** [comment]
Compair result 2 from [here](https://arax.ncats.io/?r=5955) to result 1 [here](https://arax.ncats.io/?r=5956). Why does an result with all 1 edges get a lower score than a result with a 1 edge at 1 and 1 edge with <1

**Comment by saramsey** [comment]
OK, @finnagin and I just met to discuss it. Finn wants to change the way that the quantile ranker works, by using a different option for `scipy.stats.rankdata`.

https://github.com/RTXteam/RTX/blob/a50d33a34846b38217dc8c6d7d35def4e0d7032b/code/ARAX/ARAXQuery/ARAX_ranker.py#L97

**Comment by amykglen** [comment]
is this still a known issue? noticed that this COHD query appears unranked: https://arax.ncats.io/?r=23658

**Comment by dkoslicki** [comment]
@finnagin Can you follow up on this?

**Comment by finnagin** [comment]
I think this may be  coming from the fix for the COHD "no value!" edges in #1621

**Comment by finnagin** [comment]
@amykglen this looks to be fixed now after deploying to test: https://arax.ncats.io/test/?r=23802

**Comment by finnagin** [comment]
Yeah, I think so.
