### ISSUE TITLE
Include all biolink inverses as inverse edges?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1202]
This runs:
```
{
                "edges": {
                    "e00": {
                        "subject": "n01",
                        "object": "n00",
                        "predicate": "biolink:gene_associated_with_condition"
                    }
                },
                "nodes": {
                    "n00": {
                        "id": "MONDO:0007254",
                        "category": "biolink:Disease"
                    },
                    "n01": {
                        "category": "biolink:Gene"
                    }
                }
            }
```
but this one does not (note the reversed edge)
```
{
                "edges": {
                    "e00": {
                        "subject": "n00",
                        "object": "n01",
                        "predicate": "biolink:condition_associated_with_gene"
                    }
                },
                "nodes": {
                    "n00": {
                        "id": "MONDO:0007254",
                        "category": "biolink:Disease"
                    },
                    "n01": {
                        "category": "biolink:Gene"
                    }
                }
            }
```

**Comment by saramsey** [comment]
*Every* edge type implies some kind of inverted relationship (possibly with a different predicate). In the KG2 build process, we don't automatically insert inverse edges for such predicates, as it would double the number of edges in the graph (and at 55 million edges, that's probably a good thing). I've always felt that is a part of reasoning. But I'm open to discussion of the matter.

One thing I can say for sure: doubling the number of edges would make the KG2 build process slower and more expensive.

**Comment by dkoslicki** [comment]
Yeah, I agree exploding the number of edges wouldn't be good. Perhaps we can just scrape the biolink inverses, and add some functionality to `expand` to check the inverse if a particular edge expand doesn't return anything

**Comment by saramsey** [comment]
I struggle with the question of inverted edges.

As for Chris M.'s question about whether we should realize *all* deducible edges as explicit edges in the KG, I'm going to go out on a limb and say that would be very expensive. We'd either need to massively increase our EC2 infrastructure or completely change our software stack--either way, very costly.

**Comment by dkoslicki** [comment]
All deducible edges seems quite ambitious...

**Comment by saramsey** [comment]
OK, labeling this issue `expand` to see if this is something that can be done in the KG2c/expand layers?  What do you think, @amykglen ?

**Comment by dkoslicki** [comment]
Yeah, trying something like: use the direction given, if the expand doesn't work, try the inverse

**Comment by amykglen** [comment]
yeah, seems to make sense to me to handle this in `expand`. could do the method David mentioned (try one and if it doesn't work try the other), or I suppose a slightly speedier option is to maintain some sort of record of which direction KG2 chooses to use for such edges; then expand could just look at that to know if it needs to invert a qedge. but then we'd have to maintain that record. :) not sure how often it'd need updating.

**Comment by amykglen** [comment]
although, maybe such a record could be produced in an automated fashion, like during the KG2c build process, for example.

**Comment by amykglen** [comment]
ok, so both directions of @dkoslicki's original query work on production now (#1314 #1268): https://arax.ncats.io/?r=5603

good to close? :)

**Comment by dkoslicki** [comment]
Great, thank you! Closing
