### ISSUE TITLE
Make query graph interpreter handle parallel qedges

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1205]
@edeutsch may have mentioned this previously at a minihackathon, but it looks like the query graph interpreter can't handle parallel qedges... this query errors on arax.nacts.io with `ERROR: Help, two edges at A583. Don't know what to do`
```
{
  "edges":{
    "e00":{
      "subject":"n00",
      "object":"n01"
    },
    "e01":{
      "subject":"n00",
      "object":"n01",
      "predicate":"biolink:contraindicated_for",
      "exclude":true
    }
  },
  "nodes":{
    "n00":{
      "id":"MONDO:0001627",
      "category":"biolink:Disease"
    },
    "n01":{
      "category":"biolink:ChemicalSubstance"
    }
  }
}
```
may be good to have this on the list of things to work out.

**Comment by edeutsch** [comment]
yeah, I punted on parallel edges. Definitely something I need to deal with better. What would the DSL for this query_graph be?

**Comment by amykglen** [comment]
```
add_qnode(key=n00, id=MONDO:0001627, category=biolink:Disease)
add_qnode(key=n01, category=biolink:ChemicalSubstance)
add_qedge(key=e00, subject=n00, object=n01)
add_qedge(key=e01, subject=n00, object=n01, predicate=biolink:contraindicated_for, exclude=true)
```

**Comment by edeutsch** [comment]
I suppose what I meant was what would the downstream DSL be to handle this query graph? Would Expand() do anything different than if e01 were not there? Perhaps not?

**Comment by amykglen** [comment]
ah, hah - yeah, nothing special needs to happen in the `expand` call or anything. could just look like this:
```
add_qnode(key=n00, id=MONDO:0001627, category=biolink:Disease)
add_qnode(key=n01, category=biolink:ChemicalSubstance)
add_qedge(key=e00, subject=n00, object=n01)
add_qedge(key=e01, subject=n00, object=n01, predicate=biolink:contraindicated_for, exclude=true)
expand()
resultify()
```

**Comment by edeutsch** [comment]
@amykglen please try it out in devED now. It runs. And it appears to work. This query provides the contraindicated ones:
```
{
  "edges":{
    "e01":{
      "subject":"n00",
      "object":"n01",
      "predicate":"biolink:contraindicated_for"
    }
  },
  "nodes":{
    "n00":{
      "id":"MONDO:0001627",
      "category":"biolink:Disease"
    },
    "n01":{
      "category":"biolink:ChemicalSubstance"
    }
  }
}
```
and the full one you wrote above:
```
{
  "edges":{
    "e00":{
      "subject":"n00",
      "object":"n01"
    },
    "e01":{
      "subject":"n00",
      "object":"n01",
      "predicate":"biolink:contraindicated_for",
      "exclude":true
    }
  },
  "nodes":{
    "n00":{
      "id":"MONDO:0001627",
      "category":"biolink:Disease"
    },
    "n01":{
      "category":"biolink:ChemicalSubstance"
    }
  }
}
```
appears to exclude the first list. By spot checking, not a proper intersection computation.

Would you test in devED? If you like it, I'll deploy everywhere

**Comment by amykglen** [comment]
hmm - so when I went to verify things by checking the intersection of results, things seemed off, and I noticed that it looks like only edge e00 is being expanded for the parallel-edge QG? this is the DSL the UI says was done for that JSON QG:
```
expand(edge_key=e00,kp=ARAX/KG2)
overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n00, object_qnode_key=n01)
resultify()
filter_results(action=limit_number_of_results, max_results=50)
```
think it instead needs to look like `expand(edge_key=[e00,e01],kp=ARAX/KG2)` or simply `expand(kp=ARAX/KG2)`?

**Comment by edeutsch** [comment]
ah, I understand. I think I have just pushed a fix to devED. Would you test it there before I roll it out everywhere else?

**Comment by amykglen** [comment]
looks good now!

**Comment by edeutsch** [comment]
rolled out to all deployments.
