### ISSUE TITLE
More Multiomics KP's

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1206]
Jenn Hadlock says all their KP's are now registered and discoverable. We should hook them up!

**Comment by edeutsch** [comment]
They actively want us to integrate them. We had a good meeting with them last week. But I think you couldn't be there. I suppose we're just waiting for a timeslice of @amykglen  to do the integration in Expander. I think their coverage is very limited. But Ryan sent me today an example query graph that we could/should resolve to them:
```
{
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "subject": "n01",
          "object": "n00",
          "predicate": "biolink:associated_with_increased_risk_for"
        }
      },
      "nodes": {
        "n00": {
          "id": "MONDO:0001627",
          "category": "biolink:Disease"
        },
        "n01": {
          "category": "biolink:Disease"
        }
      }
    }
  }
}
```

**Comment by edeutsch** [comment]
Maybe just as a quick test of things, we can hook up the query graph interpreter to trigger on them when there is an edge type of biolink:associated_with_increased_risk_for?

**Comment by amykglen** [comment]
ok to close since this was subsumed by #1451?
