### ISSUE TITLE
non-compliant edge type?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1210]
In the first JustFixIt query, our result is not compliant:
https://arax.ncats.io/?r=658

ERROR: TRAPI validator reported an error: 'biolink:negatively_regulates,_entity_to_entity' does not match '^biolink:[a-z][a-z_]*$' Failed validating 'pattern' in schema['properties']['knowledge_graph']['properties']['edges']['additionalProperties']['properties']['predicate']: {'description': 'CURIE for a Biolink slot, related_to or a child ' 'thereof (snake_case)', 'example': 'biolink:interacts_with', 'externalDocs': {'description': 'Biolink model relations', 'url': 'https://biolink.github.io/biolink-model/docs/related_to.html'}, 'pattern': '^biolink:[a-z][a-z_]*$', 'type': 'string'} On instance['knowledge_graph']['edges']['KG2c:9475932']['predicate']: 'biolink:negatively_regulates,_entity_to_entity' 

the edge is:
biolink:negatively_regulates,_entity_to_entity

commas are not permitted in biolink edges.

What's this ",_entity_to_entity"?
Does the schema need to change?
or do we need to change?
Is the comma valid?

**Comment by saramsey** [comment]
It looks correct to me, here is the spec

![Uploading Screen Shot 2021-02-02 at 9.31.50 AM.png…]()

**Comment by saramsey** [comment]
Huh,  it looks correct to me

<img width="621" alt="Screen Shot 2021-02-02 at 9 31 50 AM" src="https://user-images.githubusercontent.com/5562107/106639208-9444a500-6539-11eb-8ece-35606bbbae51.png">

**Comment by saramsey** [comment]
What leads us to believe that it is not compliant?

**Comment by saramsey** [comment]
I am checking with Matt Brush

**Comment by edeutsch** [comment]
Is the above screen shot from BioLink?

**Comment by saramsey** [comment]
Yes

**Comment by edeutsch** [comment]
ah okay, that means that the TRAPI regexp is wrong:
https://github.com/NCATSTranslator/ReasonerAPI/blob/f61506b5185e56d82a34a2ad9bd60d11843eaf4f/TranslatorReasonerAPI.yaml#L585
pattern: ^biolink:[a-z][a-z_]*$

Need to add comma as an allow character?
Any others?

**Comment by edeutsch** [comment]
What does "local names" translator: negatively regulates mean?
Should we be using that instead?

**Comment by edeutsch** [comment]
Can you post a permalink to the line in your screenshot above?

**Comment by edeutsch** [comment]
Thanks. Let me know what Matt says and if I should escalate this question.

**Comment by amykglen** [comment]
this looks good now in kg2c-5-2 (believe it was fixed in kg2.5.X):

<img width="672" alt="Screen Shot 2021-03-23 at 12 33 30 PM" src="https://user-images.githubusercontent.com/49423686/112207144-02b9f100-8bd4-11eb-9755-259320d51ebc.png">

and on production:
<img width="1058" alt="Screen Shot 2021-03-23 at 12 31 38 PM" src="https://user-images.githubusercontent.com/49423686/112207124-fd5ca680-8bd3-11eb-94c6-70b9171f8620.png">

good to close, @edeutsch?

**Comment by edeutsch** [comment]
yes, great, thanks, everyone!
