### ISSUE TITLE
Is this query going wrong?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1212]
I ran this query from the JustFixIt sessions:
```
{
      "edges": {
        "e00": {
          "subject": "n00",
          "object": "n01",
          "predicate": "biolink:correlated_with"
        }
      },
      "nodes": {
        "n00": {
          "id": "PUBCHEM:5865",
          "category": "biolink:Drug"
        },
        "n01": {
          "category": "biolink:Disease"
        }
      }
    }
```
ARAX works on it for quite a while, but then it comes back with a lot of results, but the results don't have PUBCHEM:5865 in them. I'm confused  by what I see here in the results

https://arax.ncats.io/?r=670

ideas?

**Comment by amykglen** [comment]
very strange... have a feeling it must be due to a bug in expand or resultify. looking into it. I can see the NodeSynonymizer apparently doesn't recognize PUBCHEM:5865, but that shouldn't lead to totally nuts results like we're seeing.

**Comment by amykglen** [comment]
ok, figured it out - was a bug in `expand`. pushed the fix to `master` and added a test for this. pytest suite is passing.

**Comment by amykglen** [comment]
(FYI - it turns out this query actually produces no results, since PUBCHEM:5865 isn't anywhere in KG2c.)

**Comment by edeutsch** [comment]
okay, thanks, will roll it out to all deployments

**Comment by edeutsch** [comment]
rolled out to all deployments.
Closing.
thanks!
