### ISSUE TITLE
mislabeled entity

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1213]
Name: Elbow dislocation (OMIM:MTHU013269)
Id: OMIM:MTHU013269
Category: biolink:Protein

**Comment by saramsey** [comment]
Sigh. Always OMIM.

**Comment by edeutsch** [comment]
I don't think it's OMIM's fault this time:
```
NodeNamesDescriptions_KG1.tsv:HP:0008807	Acetabular dysplasia	phenotypic_feature
NodeNamesDescriptions_KG2.tsv:UMLS:C1328407	Acetabular dysplasia	gross_anatomical_structure
NodeNamesDescriptions_KG2.tsv:HP:0008807	Acetabular dysplasia	phenotypic_feature
NodeNamesDescriptions_KG2.tsv:MEDDRA:10000396	Acetabular dysplasia	named_thing
NodeNamesDescriptions_KG2.tsv:UMLS:C3151603	Acetabular dysplasia (rare)	disease_or_phenotypic_feature
NodeNamesDescriptions_KG2.tsv:OMIM:MTHU028558	Acetabular dysplasia (rare)	phenotypic_feature
NodeNamesDescriptions_KG2.tsv:UMLS:C4228370	Acetabular dysplasia, bilateral	disease_or_phenotypic_feature
NodeNamesDescriptions_KG2.tsv:OMIM:MTHU052219	Acetabular dysplasia, bilateral	phenotypic_feature
NodeNamesDescriptions_KG2.tsv:OMIM:MTHU011155	Acetabular dysplasia	phenotypic_feature
NodeNamesDescriptions_KG2.tsv:UMLS:C4229765	Acetabular dysplasia (1 family)	disease_or_phenotypic_feature
NodeNamesDescriptions_KG2.tsv:OMIM:MTHU050620	Acetabular dysplasia (1 family)	phenotypic_feature
NodeNamesDescriptions_KG2.tsv:NCBIGene:780896	Acetabular dysplasia	gene
```
Apparently NCBIGene:780896's name is Acetabular dysplasia and thus it is getting linked to phenotypes and diseases.

**Comment by saramsey** [comment]
Good catch, Eric. 

Sorry, OMIM.

**Comment by saramsey** [comment]
KG2.5.1 has this as `biolink:PhenotypicFeature`, which seems correct. Taking `kg2` label off this issue.
<img width="643" alt="Screen Shot 2021-02-02 at 12 17 23 PM" src="https://user-images.githubusercontent.com/5562107/106657259-abdb5800-6550-11eb-86fa-b2103b796189.png">

**Comment by amykglen** [comment]
do we for sure want NCBIGene:780896's name to be just "Acetabular dysplasia" in KG2, @saramsey, even though it's a gene? https://www.ncbi.nlm.nih.gov/gene/780896 (vs. "ACTD", or something like that?)

in KG2.5.1:
![Screen Shot 2021-02-02 at 1 54 00 PM](https://user-images.githubusercontent.com/49423686/106667715-21015a00-655e-11eb-876e-97fc18575a33.png)

we could add some sort of exception to the NodeSynonymizer for this, but just want to make sure this is in fact what we want the name to be in KG2 (since it seems a little misleading that it's also the name of a disease/phenotype). (I wonder if the fact that the gene is labeled "phenotype only" on [this](https://www.ncbi.nlm.nih.gov/gene/780896) page could be helpful here..)

**Comment by edeutsch** [comment]
yeah, if you can detect this "phenotype only" attribute and reassign these to type "phenotype" instead of type "gene", that would also solve our problem.

And that is probably closer to reality. I suspect @amykglen is right, just like HGNC, not all NCBIGene:nnnnnns are really genes. Some are phenotypic_features. Labeling them thus in the KG would solve my synonymization problem and would be overall more accurate. I think?

**Comment by saramsey** [comment]
> do we for sure want NCBIGene:780896's name to be just "Acetabular dysplasia" in KG2, @saramsey, even though it's a gene? https://www.ncbi.nlm.nih.gov/gene/780896 (vs. "ACTD", or something like that?)
> 
> in KG2.5.1:
> ![Screen Shot 2021-02-02 at 1 54 00 PM](https://user-images.githubusercontent.com/49423686/106667715-21015a00-655e-11eb-876e-97fc18575a33.png)
> 
> we could add some sort of exception to the NodeSynonymizer for this, but just want to make sure this is in fact what we want the name to be in KG2 (since it seems a little misleading that it's also the name of a disease/phenotype).
> 
> I wonder if the fact that the gene is labeled "phenotype only" on [this](https://www.ncbi.nlm.nih.gov/gene/780896) page could be helpful here.. could this be a similar issue to #1169?

I think so. The standard in KG2 for `NCBIGene` nodes is to have the name be the spelled-out-in-words name, not the gene symbol. The standard in KG2 has been to have the official HGNC gene symbol be the first element of the `synonym` field.

If you run this Cypher in KG2.5.1,
```
match (n:`biolink:Gene` {provided_by: 'identifiers_org_registry:ncbigene'}) return n.id, head(n.synonym), n.name limit 50;
```
you will get
```

n.id | head(n.synonym) | n.name
-- | -- | --
"NCBIGene:1588" | "CYP19A1" | "cytochrome P450 family 19 subfamily A member 1"
"NCBIGene:1589" | "CYP21A2" | "cytochrome P450 family 21 subfamily A member 2"
"NCBIGene:1590" | "CYP21A1P" | "cytochrome P450 family 21 subfamily A member 1, pseudogene"
"NCBIGene:1591" | "CYP24A1" | "cytochrome P450 family 24 subfamily A member 1"
"NCBIGene:1592" | "CYP26A1" | "cytochrome P450 family 26 subfamily A member 1"
"NCBIGene:1593" | "CYP27A1" | "cytochrome P450 family 27 subfamily A member 1"
"NCBIGene:1594" | "CYP27B1" | "cytochrome P450 family 27 subfamily B member 1"
"NCBIGene:1595" | "CYP51A1" | "cytochrome P450 family 51 subfamily A member 1"
"NCBIGene:1596" | "ADAM3B" | "ADAM metallopeptidase domain 3B (pseudogene)"
"NCBIGene:1600" | "DAB1" | "DAB adaptor protein 1"
"NCBIGene:1601" | "DAB2" | "DAB adaptor protein 2"
"NCBIGene:1602" | "DACH1" | "dachshund family transcription factor 1"
"NCBIGene:1603" | "DAD1" | "defender against cell death 1"
"NCBIGene:1604" | "CD55" | "CD55 molecule (Cromer blood group)"
"NCBIGene:1605" | "DAG1" | "dystroglycan 1"
"NCBIGene:1606" | "DGKA" | "diacylglycerol kinase alpha"
"NCBIGene:1607" | "DGKB" | "diacylglycerol kinase beta"
"NCBIGene:1608" | "DGKG" | "diacylglycerol kinase gamma"
"NCBIGene:1609" | "DGKQ" | "diacylglycerol kinase theta"
"NCBIGene:1610" | "DAO" | "D-amino acid oxidase"
"NCBIGene:1611" | "DAP" | "death associated protein"
"NCBIGene:1612" | "DAPK1" | "death associated protein kinase 1"
"NCBIGene:1613" | "DAPK3" | "death associated protein kinase 3"
"NCBIGene:1615" | "DARS1" | "aspartyl-tRNA synthetase 1"
"NCBIGene:1616" | "DAXX" | "death domain associated protein"
"NCBIGene:1617" | "DAZ1" | "deleted in azoospermia 1"
"NCBIGene:1618" | "DAZL" | "deleted in azoospermia like"
"NCBIGene:1620" | "BRINP1" | "BMP/retinoic acid inducible neural specific 1"
"NCBIGene:1621" | "DBH" | "dopamine beta-hydroxylase"
"NCBIGene:1622" | "DBI" | "diazepam binding inhibitor, acyl-CoA binding protein"
"NCBIGene:1623" | "DBIP2" | "DBI pseudogene 2"
"NCBIGene:1624" | "DBIP1" | "DBI pseudogene 1"
"NCBIGene:1627" | "DBN1" | "drebrin 1"
"NCBIGene:1628" | "DBP" | "D-box binding PAR bZIP transcription factor"
"NCBIGene:1629" | "DBT" | "dihydrolipoamide branched chain transacylase E2"
"NCBIGene:1630" | "DCC" | "DCC netrin 1 receptor"
"NCBIGene:1632" | "ECI1" | "enoyl-CoA delta isomerase 1"
"NCBIGene:1633" | "DCK" | "deoxycytidine kinase"
"NCBIGene:1634" | "DCN" | "decorin"
"NCBIGene:1635" | "DCTD" | "dCMP deaminase"
"NCBIGene:1636" | "ACE" | "angiotensin I converting enzyme"
"NCBIGene:1637" | "DCR" | "Down syndrome chromosome region"
"NCBIGene:1638" | "DCT" | "dopachrome tautomerase"
"NCBIGene:1639" | "DCTN1" | "dynactin subunit 1"
"NCBIGene:1641" | "DCX" | "doublecortin"
"NCBIGene:1642" | "DDB1" | "damage specific DNA binding protein 1"
"NCBIGene:1643" | "DDB2" | "damage specific DNA binding protein 2"
"NCBIGene:1644" | "DDC" | "dopa decarboxylase"
"NCBIGene:1645" | "AKR1C1" | "aldo-keto reductase family 1 member C1"
"NCBIGene:1646" | "AKR1C2" | "aldo-keto reductase family 1 member C2"
```

**Comment by saramsey** [comment]
Yes, @amykglen is correct, this is one of those "phenotype only" genes:

<img width="800" alt="Screen Shot 2021-02-02 at 4 44 00 PM" src="https://user-images.githubusercontent.com/5562107/106681724-e9061100-6575-11eb-8f9b-e2fd78195df5.png">

**Comment by edeutsch** [comment]
So can we make its type "phenotypic_feature"? and all of its kind?

**Comment by saramsey** [comment]
Well, NCBI includes it in the Gene annotations database because there is a locus on human 13q22 that is statistically associated with heritable acetabular dysplasia. So there is a gene in that genomic neighborhood, we just don't *know* precisely where it is nor do we know its proximal biochemical function (or even if it codes for a protein).  I'm not sure it is correct to call it a phenotypic feature, though it's probably less crazy to call it a phenotypic feature than to call it a "gene".  Any objection to "genomic entity"?

**Comment by saramsey** [comment]
But in code, we could change its name to "(Genetic association) Acetabular dysplasia"

**Comment by edeutsch** [comment]
Yes, I was going to suggest changing the name to "gene for acetabular dysplasia" or "genetic locus for acetabular dysplasia". This would be more accurate and then can stay as gene or genomic entity is perhaps better.

I would vote for: biolink:GenomicEntity "genetic locus for acetabular dysplasia"

This would solve the problem nicely I think. There are 100s or 1000s more like this, too. Can you fix them all?

**Comment by saramsey** [comment]
> Yes, I was going to suggest changing the name to "gene for acetabular dysplasia" or "genetic locus for acetabular dysplasia". This would be more accurate and then can stay as gene or genomic entity is perhaps better.
> 
> I would vote for: biolink:GenomicEntity "genetic locus for acetabular dysplasia"
> 
> This would solve the problem nicely I think. There are 100s or 1000s more like this, too. Can you fix them all?

Let me check...

**Comment by saramsey** [comment]
> Can you fix them all?

Yes, testing a fix now

**Comment by edeutsch** [comment]
would be fun know the final count

**Comment by saramsey** [comment]
My current heuristic identifies 1,349 such records:
```
cat Homo_sapiens_gene_info.tsv | awk -F $'\t' '{if ($10=="unknown" && $6~/^MIM\:/) {print}}' | wc -l
```

**Comment by saramsey** [comment]
Final count, after refining my heuristic, is 1,342 record that are getting changed from `biolink:Gene` to `biolink:GenomicEntity`.

**Comment by saramsey** [comment]
> do we for sure want NCBIGene:780896's name to be just "Acetabular dysplasia" in KG2, @saramsey, even though it's a gene? https://www.ncbi.nlm.nih.gov/gene/780896 (vs. "ACTD", or something like that?)
> 
> in KG2.5.1:
> ![Screen Shot 2021-02-02 at 1 54 00 PM](https://user-images.githubusercontent.com/49423686/106667715-21015a00-655e-11eb-876e-97fc18575a33.png)
> 
> we could add some sort of exception to the NodeSynonymizer for this, but just want to make sure this is in fact what we want the name to be in KG2 (since it seems a little misleading that it's also the name of a disease/phenotype).
> 
> I wonder if the fact that the gene is labeled "phenotype only" on [this](https://www.ncbi.nlm.nih.gov/gene/780896) page could be helpful here.. could this be a similar issue to #1169?

In the Biolink metamodel, there is on the `gene` class a dedicated slot for the gene symbol, namely, `symbol`. Arguably, that is where the HGNC Official Gene Symbol could be put (in addition to the in the `synonym` list as is our current practice).

<img width="618" alt="Screen Shot 2021-02-03 at 12 44 55 PM" src="https://user-images.githubusercontent.com/5562107/106807174-b57ec180-661d-11eb-9887-188792985361.png">

https://github.com/biolink/biolink-model/blob/70a73ad20dee03e24b559e5eaef81c3eb0f4ee0b/biolink-model.yaml#L6365

**Comment by edeutsch** [comment]
> Final count, after refining my heuristic, is 1,342 record that are getting changed from biolink:Gene to biolink:GenomicEntity

and a name change to "Genetic locus associated with <PREVIOUSNAME>"?

**Comment by saramsey** [comment]
Yes
```
        {
            "id": "NCBIGene:780896",
            "iri": "https://identifiers.org/ncbigene:780896",
            "name": "Genetic locus associated with Acetabular dysplasia",
            "full_name": "Genetic locus associated with Acetabular dysplasia",
            "category": "biolink:GenomicEntity",
            "category_label": "genomic_entity",
            "category": "biolink:GenomicEntity",
            "category_label": "genomic_entity",
            "description": "Acetabular dysplasia; Type:unknown; Locus:13q22; NameStatus:unofficial",
            "synonym": [
                "ACTD"
            ],
            "publications": [],
            "creation_date": null,
            "update_date": "20190816",
            "deprecated": false,
            "replaced_by": null,
            "provided_by": "identifiers_org_registry:ncbigene"
        },
```

**Comment by saramsey** [comment]
Repeating my Slack post here:

Hi all, I'm working issue 1213 ("mislabeled entity"), and I gotta be honest, despite my previous posts, I'm having second thoughts about having, for all NCBI genes, the "name" field be identical to the "full name" field. The serialized JSON example for KGX clearly shows the "name" field as the Gene Symbol. Would that be useful to you all, namely, to have the "name" field be the Gene Symbol? (keeping the full_name field unchanged and keeping the synonym field unchanged)

**Comment by edeutsch** [comment]
I don't feel strongly, but I do think have the symbol be easily available is good. I'm uncertain what the best way to do that is. Putting symbol in name and full name in full_name sounds reasonable to me, but I am very uncertain what the downstream implications are. What do we do for UniProtKB entries? Seems like we should be consistent across all genes and proteins and genetic loci that are associated with phenotypes, etc. so... I am not certain.

**Comment by saramsey** [comment]
For UniProtKB, as it turns out, the "name" field is the Official Gene Symbol, in most cases (human).

**Comment by edeutsch** [comment]
Well, if we're consistent that "name" is always the symbol and "full_name" is the spelled out name for all our genes and proteins, I think that's good.

but then what if there's no symbol? blank name?

**Comment by saramsey** [comment]
I think in NCBI, there is always a symbol.

**Comment by saramsey** [comment]
So our phenotype-only locus would look like this:
```
        {
            "id": "NCBIGene:780896",
            "iri": "https://identifiers.org/ncbigene:780896",
            "name": "ACTD",
            "full_name": "Genetic locus associated with Acetabular dysplasia",
            "category": "biolink:GenomicEntity",
            "category_label": "genomic_entity",
            "category": "biolink:GenomicEntity",
            "category_label": "genomic_entity",
            "description": "Acetabular dysplasia; Type:unknown; Locus:13q22; NameStatus:unofficial",
            "synonym": [
                "ACTD"
            ],
            "publications": [],
            "creation_date": null,
            "update_date": "20190816",
            "deprecated": false,
            "replaced_by": null,
            "provided_by": "identifiers_org_registry:ncbigene"
        },
```

**Comment by saramsey** [comment]
And an actual gene would look like this:
```
        {
            "id": "NCBIGene:1",
            "iri": "https://identifiers.org/ncbigene:1",
            "name": "A1BG",
            "full_name": "alpha-1-B glycoprotein",
            "category": "biolink:Gene",
            "category_label": "gene",
            "description": "Type:protein-coding; Locus:19q13.43; NameStatus:official",
            "synonym": [
                "A1BG",
                "A1B",
                "ABG",
                "GAB",
                "HEL-S-163pA",
                "HYST2477",
                "alpha-1B-glycoprotein",
                "epididymis secretory sperm binding protein Li 163pA"
            ],
            "publications": [],
            "creation_date": null,
            "update_date": "20201124",
            "deprecated": false,
            "replaced_by": null,
            "provided_by": "identifiers_org_registry:ncbigene"
        },
```

**Comment by saramsey** [comment]
Is good?

**Comment by edeutsch** [comment]
I am concerned about downstream implications. But it seems fine to me. Didn't we used to have a dedicated "symbol" property? @amykglen can you think of negative implications?

**Comment by saramsey** [comment]
As far as biolink compliance, our graph should be consistent witih Deepak's example JSON:
```
    "nodes" : [
      {
        "id": "HGNC:11603",
        "name": "TBX4",
        "category": ["biolink:Gene"],
        "provided_by": "MonarchArchive:gwascatalog",
      },
```

**Comment by saramsey** [comment]
You recall correctly-- KG1 had a dedicated "symbol" property, which we used (for proteins) to hold the official gene symbol.

 KG2 does not; I am proposing to follow Deepak's approach to use the "name" field as the official gene symbol, for "biolink:Gene" nodes.

**Comment by edeutsch** [comment]
okay, fine with me. Something downstream might break a bit, but then we will fix it.

**Comment by saramsey** [comment]
OK, I have updated the code so for Ensembl, NCBI, and HGNC genes, the "name" field is the official gene symbol, as @amykglen originally suggested.

**Comment by saramsey** [comment]
If we decide this leads to downstream breakage, it is easy for me to undo these three changes.

**Comment by kvarforl** [comment]
Okay, there's alot going on in this issue thread, but I think this is fixed:

Here is the example genetic locus node:

n.name | n.full_name | n.category_label
-- | -- | --
"Genetic locus associated with ACTD" | "Genetic locus associated with Acetabular dysplasia" | "genomic_entity"
