### ISSUE TITLE
H1N1 listed as a publication?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1216]
Name: H1n1 (UMLS:C0580264)
Id: UMLS:C0580264
Category: biolink:Publication,biolink:QuantityValue

**Comment by saramsey** [comment]
OK, that node should be type `biolink:InformationContentEntity` (it is a concept representing an influenza serotype *annotation* "H1N1"). Fixing now.

**Comment by ericawood** [comment]
This appears to be fixed in KG2.5.2:
```
{
  "iri": "https://identifiers.org/umls:C0580264",
  "category_label": "information_content_entity",
  "deprecated": "False",
  "name": "H1n1",
  "provided_by": "identifiers_org_registry:umls",
  "id": "UMLS:C0580264",
  "category": "biolink:InformationContentEntity",
  "update_date": "2017"
}
```
