### ISSUE TITLE
remove commas from predicates-remap.yaml

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1221]
The KG2 build system currently converts Biolink relations from
```
space case
```
to CURIES that are
```
biolink:snake_case
```
But some Biolink relations contain commas, like this:
```
positively regulated by, entity to entity
```
which the KG2 build system would convert to a CURIE by using space-case including the comma, like this:
```
biolink:positively_regulated_by,_entity_to_entity
```
But in [Reasoners Standard API issue 205](https://github.com/NCATSTranslator/ReasonerAPI/issues/205) we have received guidance that the comma should be removed in the translation to the CURIE. This guidance is consistent with the URIs that we see for Biolink relations in the TTL version of the Biolink model, for example:
```
<https://w3id.org/biolink/vocab/negatively_regulates_entity_to_entity> a owl:ObjectProperty,
        meta:SlotDefinition ;
    rdfs:label "negatively regulates, entity to entity" ;
    rdfs:domain <https://w3id.org/biolink/vocab/MolecularEntity> ;
    rdfs:range <https://w3id.org/biolink/vocab/MolecularEntity> ;
    rdfs:subPropertyOf <https://w3id.org/biolink/vocab/negatively_regulates>,
        <https://w3id.org/biolink/vocab/regulates_entity_to_entity> ;
    owl:inverseOf <https://w3id.org/biolink/vocab/negatively_regulated_by_entity_to_entity> .
```

**Comment by saramsey** [comment]
When we do this, I think it will break the script `validate_predicate_remap_yaml.py`, which uses `biolink-model.yaml` to validate the predicates against (because we cannot get the Biolink-to-upstream-source predicate mappings from `biolink-model.owl.ttl`.

**Comment by TomConlin** [comment]
noting that underlying ontological term for

https://w3id.org/biolink/vocab/negatively_regulates_entity_to_entity 

is: RO:0002449

which has label:

    `directly negatively regulates activity of`

**Comment by edeutsch** [comment]
@amykglen a quick patch until we transition to the next KG2.5.x would be to edit out commas in the predicates. Can you easily add a layer in Expand that does this? Or I suppose it could be downstream of Expand if you think that's a better place. Where should we patch this so we are fully TRAPI compliant?

**Comment by amykglen** [comment]
yeah, I was thinking the same thing - I can easily add that into `expand` (where I'm already doing the translation to biolink:___ format). will do that.

**Comment by amykglen** [comment]
alright, patch is in place `master` (it translates a predicate like `positively_regulates_entity_to_entity` in the QG into the comma-ful version for querying KG2/c, and then removes commas from the predicates of returned edges)

**Comment by edeutsch** [comment]
super, thank you!

**Comment by edeutsch** [comment]
verified in production. closing

**Comment by saramsey** [comment]
> noting that underlying ontological term for
> 
> https://w3id.org/biolink/vocab/negatively_regulates_entity_to_entity
> 
> is: RO:0002449
> 
> which has label:
> 
> ```
> `directly negatively regulates activity of`
> ```
> 
> however the biolink model introduces a an additional parent class
> 
> regulates_entity_to_entity
> 
> which is RO:0002448 with label: `directly regulates activity of`
> 
> if the comma is to indicate composition should the resulting predicate reflect the fact?
> 
> something like replace comma with `_o_` ?

Hi Tom!

Interesting point.  Hmm, I'm not sure what the comma means, in terms of formal semantics. I guess perhaps it means that in the general case, a `regulates` association can be between two objects that are not entities, so the Biolink team's association `regulates, entity to entity` is specifically scoping the domain and range to be entities?  But that's just a guess. In any event, we can map the comma to whatever string the Biolink modelers wish for us to use, subject to the constraint that the resulting string should be legal in a URI, and subject to the hard requirement that the `biolink-model.owl.ttl` file be kept in sync with the proposed comma-to-whatever mapping. This is important because while we use `biolink-model.owl.ttl` as input to building our KG, when it comes to *validating* our `predicate-remap.yaml` file, we use `biolink-model.yaml`, because the latter file has all of the mappings between source relations and Biolink predicate types (I don't think `biolink-model.owl.ttl` has that mapping  information, thus it cannot be used by itself for validating KG2's `predicate-remap.yaml`.).

Cheers,
Steve
