### ISSUE TITLE
kg2_tsv_to_medikanren_csv.py adds too many  double quotes (") to the third column of rtx_kg2.edge.csv

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1222]
While working on the mediKanren export of KG2.5.1 (#1200),  the ":END" column of `rtx_kg2.edge.csv` generated from `kg2_tsv_to_medikanren_csv.py` seems to have quoting issues when there is a comma in the id.

Here is the most interesting example:
```
32116895,"ttd.target:US9206139, 5","""""ttd.target:US9206139, 5"""""
32116916,"ttd.target:US8614253, 32-4","""""ttd.target:US8614253, 32-4"""""
```
The formatting is fine in the second column, but wonky in the third even though the id is arguably the same.

Fixing this manually with sed for the KG2.5.1 export, but making a note to document the bigger issue :)

tagging @ericawood as per steve's suggestion!

**Comment by saramsey** [comment]
Thanks for bringing this issue to my attention, @kvarforl .  Might make sense to tag ericawood since I think they wrote this script, possibly with some input from finnagin (my memory is hazy).

**Comment by ericawood** [comment]
Thank you for tagging me on this (I did write the script with input from Finn). I am looking into it now. Did you see this problem with earlier versions?

**Comment by kvarforl** [comment]
Hmm good question. I attempted to export KG2.3.5, and ran into a similar error, but it wasn't exactly the same. The kg2.3.5 export was also attempted using our very out of date fork of the medikanren repo.
This was the error from the KG2.3.5 export
```
hash-ref: no value found for key  
key: "\"\"ttd.target:US8791257, 17\"\""
  context...:
   /home/ubuntu/kg2-code/mediKanren/mediKanren/biolink/csv-graph-to-db.rkt:144:6: add-edge
   /home/ubuntu/kg2-code/mediKanren/mediKanren/biolink/csv-graph-to-db.rkt:182:2: loop
   /home/ubuntu/kg2-code/mediKanren/mediKanren/biolink/csv-graph-to-db.rkt: [running body]
```
It's hard to determine if this was actually causing a failure though; we ended up just canceling the kg2.3.5 export.

Since then, with KG2.5.1, there were some schema changes to our graph. Because of this, I moved us to use the lastest code of the medikanren repo, which makes its hard to compare the two exports.

**Comment by kvarforl** [comment]
Documenting Erica and I's slack conversation:
it looks like the bug also adds self edges to any edge with an id containing a comma, in addition to the quoting issue. 
Erica is working on changing the medikanren file generation script to generate tsvs instead of csvs so we can just avoid the whole comma issue all together.

**Comment by kvarforl** [comment]
okay, with the newly generated tsvs, I'm running into this error from `tsv-graph-to-db.rkt`:
```
string::257: string->jsexpr: unterminated string
  context...:
   /usr/share/racket/collects/syntax/readerr.rkt:6:2: raise-read-error9
   /usr/share/racket/collects/json/main.rkt:150:4: loop
   /home/ubuntu/RTX/code/kg2/mediKanren/mediKanren/biolink/tsv-graph-to-db.rkt:97:6: loop-props
   [repeats 3 more times]
   /home/ubuntu/RTX/code/kg2/mediKanren/mediKanren/biolink/tsv-graph-to-db.rkt:95:2: loop
   /home/ubuntu/RTX/code/kg2/mediKanren/mediKanren/biolink/tsv-graph-to-db.rkt: [running body]
```
I'm guessing this is coming from the nodeprops tsv, which has entries like this:

```
biolink:GeneToGoTermAssociation synonym "(''functional association'')"
biolink:PhysiologicalProcess    synonym "(''physiology'')"
```
the double single quote (`''`) as a list separator seems odd to me. because we're using tsvs now, would it be okay to seperate with commas instead?
@ericawood @finnagin could you explain the reasoning behind this section of code?
https://github.com/RTXteam/RTX/blob/bad17d0892947cf3797b028db40c69652d5b9245/code/kg2/mediKanren/kg2_tsv_to_medikanren_tsv.py#L41-L53

**Comment by ericawood** [comment]
That section of the code was designed to mirror the appearance of the csv files back when Finn was doing it from Neo4j, since it is a list. Do you know if you can specify the delimiter in tsv-graph-to-db.rkt?

**Comment by kvarforl** [comment]
hmmm, that's a good question! 

I did some testing with some small tsv's that I generated in `~/kg2-code/mediKanren/small_tsvs` and concluded that the above string thing doesn't seem to be the issue.

**Comment by finnagin** [comment]
Looks like you might be able to specify the deliminator by changing [lines 42-44](https://github.com/RTXteam/mediKanren/blob/master/biolink/tsv-graph-to-db.rkt#L42-L44) in tsv-graph-to-db.rkt

There is also a csv-graph-to-db.rkt if you want to try importing a csv instead

**Comment by ericawood** [comment]
> string::257: string->jsexpr: unterminated string
  context...:
   /usr/share/racket/collects/syntax/readerr.rkt:6:2: raise-read-error9
   /usr/share/racket/collects/json/main.rkt:150:4: loop
   /home/ubuntu/RTX/code/kg2/mediKanren/mediKanren/biolink/tsv-graph-to-db.rkt:97:6: loop-props
   [repeats 3 more times]
   /home/ubuntu/RTX/code/kg2/mediKanren/mediKanren/biolink/tsv-graph-to-db.rkt:95:2: loop
   /home/ubuntu/RTX/code/kg2/mediKanren/mediKanren/biolink/tsv-graph-to-db.rkt: [running body]

After some digging, I determined that that issue is that there are newlines in some of the description fields, which is tripping up the code.

**Comment by saramsey** [comment]
Good sleuthing, @ericawood !  

My suspicion immediately goes to the node "description" field. 

We can try to ferret out all of the places in the code where newlines in the description field are arising in the code-base, but in the meantime, can we do some quoting or conversion of newlines to spaces, as a countermeasure?

**Comment by ericawood** [comment]
@saramsey Commit 06536b0 converts newlines to spaces in both node and edge fields (to cover all of our bases, though the problem was only observed in the node description field).

**Comment by kvarforl** [comment]
Nice work!

Next up is this error.
```
+ set -o nounset -o pipefail -o errexit
+ cd ./mediKanren/biolink/
+ echo --------Starting TSV to DB --------
--------Starting TSV to DB --------
+ racket tsv-graph-to-db.rkt data rtx_kg2
string::320: string->jsexpr: bad string escape: "x"
  context...:
   /usr/share/racket/collects/syntax/readerr.rkt:6:2: raise-read-error9
   /home/ubuntu/RTX/code/kg2/mediKanren/mediKanren/biolink/tsv-graph-to-db.rkt:98:6: loop-props
   [repeats 10 more times]
   /home/ubuntu/RTX/code/kg2/mediKanren/mediKanren/biolink/tsv-graph-to-db.rkt:96:2: loop
   /home/ubuntu/RTX/code/kg2/mediKanren/mediKanren/biolink/tsv-graph-to-db.rkt: [running body]
Processing nodes:
```
From my discussion with Greg R, if a string in the third column looks like json, they attempt to convert it to json. 

That makes me think that our publications info properties of edges isn't always converted properly, like in this example. 
```
30395557	publications_info	"{'PMID:28101675': {'publication date': '2017 Feb', 'sentence': 'RESULTS: The distance of the optimal ETV entry point from the Bregma in the coronal plane ('x') and from the coronal suture in the sagittal plane ('y') correlated well with the frontal horn ratio (FHR).', 'subject score': 1000, 'object score': 1000}}"
```
To fix this, I'm going to add a case to `kg2_tsv_to_medikanren_tsv.py` that uses `json.dumps()` for stringifying the publications_info properties.

Are there any other node or edge properties that are jsonesque?

**Comment by kvarforl** [comment]
Since mediKanren interprets property values as json strings, it might make sense to just use json.dumps for all of our string converting (eg, when a prop value contains a tab or a double quote)

```python
>>> str_w_single_quotes = "This is a 'string' with single quotes"
>>> str_w_double_quotes = 'This is a "string" with double quotes' 
>>> pubinfo = "{'PMID:28101675': {'publication date': '2017 Feb', 'sentence': 'RESULTS: The distance of the optimal ETV entry point from the Bregma in the coronal plane (""x"") and from the coronal suture in the sagittal plane (""y"") correlated well with the frontal horn ratio (FHR).', 'subject score': 1000, 'object score': 1000}}"
>>> json.dumps(str_w_single_quotes)
'"This is a \'string\' with single quotes"'
>>> json.dumps(str_w_double_quotes)
'"This is a \\"string\\" with double quotes"'
>>> json.dumps(pubinfo)
'"{\'PMID:28101675\': {\'publication date\': \'2017 Feb\', \'sentence\': \'RESULTS: The distance of the optimal ETV entry point from the Bregma in the coronal plane (x) and from the coronal suture in the sagittal plane (y) correlated well with the frontal horn ratio (FHR).\', \'subject score\': 1000, \'object score\': 1000}}"'
>>> 
```

**Comment by saramsey** [comment]
As far as I recall, the only property that is JSONified is `publications_info`.
