### ISSUE TITLE
Virtual edges should be add-able even if the KG doesn't find an edge connecting them

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1223]
For DTD, NGD, COHD, and the like, it is still helpful to have virtual edges added. I can see this being accomplished in two different ways:
1. Make sure all these are available as `expand` kp's (similar to how COHD is currently)
2. Allow virtual edges to be added even if `expand(kp=ARAX/KG2)` couldn't find an edge connecting them

Since 1. is already implemented for NGD and COHD, I think the only remaining one is DTD.

An additional feature would be the addition of an optional parameter with a name like `slow_model=true` if you want to fall back on querying the actual model (instead of assigning a 0 if the probability is below 0.8. The default will be `slow_model=false`.

**Comment by chunyuma** [comment]
This problem was solved by using `expand(kp=DTD)` in issue #1203.

Here is an example:
```
add_qnode(name=acetaminophen, key=n0),
add_qnode(name=Sotos syndrome, key=n1),
add_qedge(subject=n0, object=n1, key=e0),
expand(edge_key=e0, kp=DTD, DTD_threshold=0, DTD_slow_mode=True),
return(message=true, store=false)
```
