### ISSUE TITLE
Should we handle multiple predicates on qedges?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1225]
This is one of the queries being played with in the fix it session at the relay this morning - apparently TRAPI allows a qedge to have multiple predicates, which is meant to be interpreted as an "OR" situation. We currently throw an error for this. Do we want to be able to handle it?
```
{
      "nodes": {
        "n00": {
          "id": "CHEBI:17303",
          "category": "biolink:ChemicalSubstance"
        },
        "n01": {
          "category": "biolink:Gene"
        }
      },
      "edges": {
        "e00": {
          "subject": "n00",
          "object": "n01",
          "predicate":["biolink:molecularly_interacts_with","biolink:physically_interacts_with"]
        }
      }
    }
```

**Comment by saramsey** [comment]
This seems useful. Your example shown above is an excellent use-case.

**Comment by edeutsch** [comment]
On topic: yes.
Slightly off topic: For TRAPI 1.1 (it is nearly decided), predicate and some other fields will no longer be EITHER a string OR an array. But rather always an array. Often an array of one. But for TRAPI 1.0 it is truly either.

**Comment by dkoslicki** [comment]
I vote yes as well!

**Comment by amykglen** [comment]
this functionality is in place now in production (query from original post: https://arax.ncats.io/?r=5607)
