### ISSUE TITLE
Antifreeze proteins mis-synonymized

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1229]
Take a look at
Name: 3-O-(2-acetamido-2-deoxygalactopyranosyl)-acetyl-threonyl-alanyl-alanine methyl ester (MESH:C062622)
Id: MESH:C062622
Category: biolink:NamedThing,biolink:ChemicalSubstance,biolink:MolecularEntity

On KG2C (specifically the all_names)

**Comment by edeutsch** [comment]
This appears to come from SRI Node Normalizer. @dkoslicki , please see this issue:
https://github.com/TranslatorSRI/NodeNormalization/issues/50
and post what you know, since I know very little about this issue. I'm just the middleman.

**Comment by dkoslicki** [comment]
Thanks! I've updated that issue with what I know about it

**Comment by dkoslicki** [comment]
Looks like this one is fixed, closing
