### ISSUE TITLE
connect anatomy to Gene Ontology biological process

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#123]
this supersedes issue #75

**Comment by saramsey** [comment]
@DeqingQu I think I have done this (see code that I added to QuerySciGraph.py and BioNetExpander.py). I am testing now.  I'm going to switch you to a different issue, stay tuned...

**Comment by saramsey** [comment]
testing the new code to address this issue now, on rtxsteve.saramsey.org
testing may take 24 hours to complete (building the KG is slow until we've populated the requests HTTP cache).

**Comment by saramsey** [comment]
closed this issue by accident, sorry

**Comment by saramsey** [comment]
Matt Brush says to use "enables" instead of "capable_of":  
https://github.com/biolink/biolink-model/issues/67

**Comment by DeqingQu** [comment]
@saramsey I just checked QuerySciGraph.py. It seems that the function `get_gene_ontology_curie_ids_for_uberon_curie_id` queries the relationship between anatomy and biological progress. Am I right?

**Comment by saramsey** [comment]
![screen shot 2018-05-21 at 2 42 16 pm](https://user-images.githubusercontent.com/5562107/40331424-2e58dca0-5d05-11e8-984c-10dda329605f.png)
