### ISSUE TITLE
A few nodes in KG2.5.1 NodeSynonymizer have a preferred type lacking "biolink" prefix

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1234]
In building the NodeSynonymizer from KG2.5.1, things generally seem to have gone well, although there are apparently 6 synonym groups with a preferred type of "protein" (instead of "biolink:Protein"). Any idea why this might be, @edeutsch? (It doesn't seem to be due to an issue in KG2.)
```
  WARNING: Preferred category for UniProtKB:P04150 doesn't start with 'biolink:': protein
  WARNING: Preferred category for UniProtKB:P22303 doesn't start with 'biolink:': protein
  WARNING: Preferred category for UniProtKB:P61812 doesn't start with 'biolink:': protein
  WARNING: Preferred category for UniProtKB:P10600 doesn't start with 'biolink:': protein
  WARNING: Preferred category for UniProtKB:P01137 doesn't start with 'biolink:': protein
  WARNING: Preferred category for UniProtKB:P00390 doesn't start with 'biolink:': protein
```
it looks like these happen to be the 6 proteins that exceptions have been added for: https://github.com/RTXteam/RTX/blob/54c52813644f236c8e8019ee78f82266a1a1ded4/code/ARAX/NodeSynonymizer/node_synonymizer.py#L137-L144

Note: There's a KG2.5.1 NodeSynonymizer at `arax.ncats.io:/data/orangeboard/databases/KG2.5.1/node_synonymizer.sqlite` - it was built based on the code in the `kg2.5integration` branch, which is up to date with changes from `master`, but which contains a couple [changes](https://github.com/RTXteam/RTX/commit/33a1b633224488b6d8023af9bdd20578ded6553d#diff-aba2ad8ce5dc44433eca82d67e82c14097bd50829c59102aa98a9aec168447d8) to the synonymizer that are not yet in `master`, I believe.

**Comment by edeutsch** [comment]
Thanks, I am uncertain what to do. Your diagnosis of the root cause is likely correct. I'm not set up to work with 2.5.1 yet. It is likely true that if I switch to branch `kg2.5integration` then I'll be in that world to do testing and bug fixing?

It would probably be good to completely cut all ties to KG1 at this point (when we start using 2.5.1) One nice thing about the KG1 NodeNamesDescriptions_KG1.tsv file is that the protein symbols are quite useful and were not in the KG2 file. Perhaps a useful question is: is there any information in NodeNamesDescriptions_KG1.tsv that we don't get in NodeNamesDescriptions_KG2.tsv? and if so, can we migrate it to NodeNamesDescriptions_KG2.tsv, and then I can remove all KG1 stuff permanently?

**Comment by amykglen** [comment]
I think NodeNamesDescriptions_KG2.tsv doesn't yet include symbols (if they're not already the node's name). I think maybe this would be resolved with KG2.5.2+, where symbols will become `name`s?

while we should deprecate KG1 at some point, it doesn't seem to me like KG1 is the issue here: when I look up a curie that I know is in both KG1 and KG2, its `all_types` from the synonymizer all look good (i.e., in `biolink:Protein` format). the only problems I've observed are with the `preferred_type` for these 6 proteins (strangely, their `all_types` look fine). given this, I don't think it's really going to impact much (if anything) in ARAX - expand only inspects `all_types` for running its KG2c queries. so I'm not sure we actually need to worry about fixing this for this KG2.5.1 rollout (maybe just shoot for the next). 

and yes, if you switch to the `kg2.5integration` branch and download the `config.json` and `node_synonymizer.sqlite` in `arax.ncats.io:/data/orangeboard/databases/KG2.5.1/`, you'll be set to work on this issue. (although not all pytests are going to work since the transition to KG2.5.1 is still in progress.)

**Comment by edeutsch** [comment]
okay, I will schedule some more time to update the NodeSynonymizer, but it seems non-critical for continued rollout of KG2.5.1?

**Comment by amykglen** [comment]
yep, I think it's non-critical. sounds good!

**Comment by amykglen** [comment]
looks like this issue is now resolved in kg2c-5-2. closing!

<img width="705" alt="Screen Shot 2021-03-23 at 12 24 58 PM" src="https://user-images.githubusercontent.com/49423686/112206123-ce920080-8bd2-11eb-9f05-03abbe42c597.png">
