### ISSUE TITLE
Update BTE predicates & nodes

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1235]
It [appears](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Expand/bte_querier.py#L271-L287) that expand with BTE has the allowable predicates and node types hard coded. According to the last table in [this document](https://github.com/colleenXu/RegistryMetadataDev/blob/master/x-translator/RegistryMetadataSummaries.ipynb), it looks like BTE accepts more input than it currently is coded to do. Perhaps there's a way to take advantage of the /predicates endpoint for BTE to auto-populate the allowable inputs?

**Comment by amykglen** [comment]
definitely. and we also need to do this for other external KPs! @edeutsch - did TRAPI 1.0 ever end up including the kind of "meta" information endpoint that I remember being discussed on those calls a while back (i.e., that would also include preferred curie prefixes, etc.)? or is `/predicates` the best we have for now?

**Comment by edeutsch** [comment]
/predicates as currently implemented is the v1.0 standard.
However, migrating this to /knowledge_map with more information is one of the top priorities for v1.1

**Comment by amykglen** [comment]
now that we switched to using BTE's API, this is automatically done by the general purpose `TRAPIQuerier` in `expand`. will confirm when `master` is next rolled out to production.
