### ISSUE TITLE
Blank lines inserted at end of DSL input in UI

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1238]
To replicate the problem:
On the DSL tab, click the example, post it, and then (deciding you want to tweak something), click the "select DSL Command" tab and add whatever you like. Note that 2 blank lines are inserted. Repeating this adds another blank line or two.

Somewhat related: Is it possible to do the following: when you click "add" on a DSL command, it is inserted at the cursor (or at the end if the cursor is not in the input box)?

**Comment by isbluis** [comment]
This is now in production ready for review. Thanks!

Re: adding a DSL at cursor position, it might be tough to get it right, since the cursor could be anywhere on the line, and the DSL might get inserted at the wrong place.  Javascript does not make it easy to know if cursor is at the beginning or end of a line, and then there's the question of whether you would add the new command before the current line, or after.  I'll think about ways to improve this.  Other suggestions welcome!

**Comment by dkoslicki** [comment]
Great! And I figured it might be difficult (and not expected behavior from UX point of view)

**Comment by edeutsch** [comment]
I too think it would be great to insert the desired DSL command beginning at the cursor position. Just wherever the cursor is, insert the command and a carriage return.

If it's not where the user wanted? easy to ctrl+Z and move the cursor and re-click.

Seems like this would be the most flexible and efficient. Novices might botch it a couple times but would learn fast.

**Comment by isbluis** [comment]
Ok, I have implemented your suggestion, @edeutsch .  One caveat is that ctrl+Z does not seem to work, which may just end up confusing novices.

Have a look at https://arax.ncats.io/devLM/index.html  and let me know if it is worth checking in.

Thanks!

**Comment by edeutsch** [comment]
looks great! I think that is much more effective.

Ship it!

**Comment by isbluis** [comment]
Ok, done.  Close once tested?

**Comment by edeutsch** [comment]
@dkoslicki test and close?

**Comment by isbluis** [comment]
Ok, I lied.  I made changes so that the DSL command will be inserted at the beginning of the current line of the cursor (no longer inserting in the middle of a command).

Only caveat is that if you wanted the command *after* the current line, you might have to make that edit by hand.

Better?

**Comment by dkoslicki** [comment]
I think that works as well, both have a low learning curve. I’ll close since things look to be in good shape!
