### ISSUE TITLE
Mysterious error with lists

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1242]
I was checking if lists still worked with:
```
add_qnode(key=n00,id=[UniProtKB:P14136,UniProtKB:P35579],is_set=true,category=Biolink:Protein)
add_qnode(category=Biolink:BiologicalProcess, key=n01)
add_qedge(subject=n00, object=n01, key=e00)
expand(kp=ARAX/KG2)
resultify()
```
But got the error:
An error was encountered while contacting the server (TypeError: e.match is not a function. (In 'e.match(/^\s+$/)', 'e.match' is undefined)).

I grepped the entire code base and could not find 'e.match(/^\s+$/)'. Since the error only happened when “transmitting the message back to client”, I am tagging Luis and Eric.

**Comment by isbluis** [comment]
Hi @dkoslicki .
I think this is an issue with the streaming of the response for the purposes of animating the progress bar, and not with the response contents or DSL processing itself.  If you look at the navigation bar on your browser, you should have a response id (r=NNNN) in the URL.  Just reload or recall this id and you will see the full response with results and graphs.
In the meantime, @edeutsch and I will try to find out what is causing this hiccup and fix it.
Thanks!

**Comment by isbluis** [comment]
Correction to my previous reply: the issue lies with parsing compound (is_set) nodes in the query_graph by the UI code.
I will fix this as part of updating bulid-a-graph to handle the TRAPI 1.0 format in the coming week.

(Clearing @edeutsch from the issue)

**Comment by isbluis** [comment]
I put a stopgap to handle these nodes: results are now displayed with no error, but build-a-graph is empty when any node in the `query_graph` is a list (`id` array of more than one element).

**Comment by edeutsch** [comment]
After fixing your ARAXi to correct biolink: prefixes:
```
add_qnode(key=n00,id=[UniProtKB:P14136,UniProtKB:P35579],is_set=true,category=Biolink:Protein)
add_qnode(category=Biolink:BiologicalProcess, key=n01)
add_qedge(subject=n00, object=n01, key=e00)
expand(kp=ARAX/KG2)
resultify()
```
This seems to work properly now.
@dkoslicki close if you are happy with the current state of production?

**Comment by dkoslicki** [comment]
`Biolink` appears to be case-sensitive, but after that minor adjustment, looks good to me!
```
add_qnode(key=n00,id=[UniProtKB:P14136,UniProtKB:P35579],is_set=true,category=biolink:Protein)
add_qnode(category=biolink:BiologicalProcess, key=n01)
add_qedge(subject=n00, object=n01, key=e00)
expand(kp=ARAX/KG2)
resultify()
```
