### ISSUE TITLE
add edge `id` property to KG2

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1245]
So, embarrassingly, I have just noticed that Biolink requires an `id` property for an edge (or in Biolink-speak, an "association"). We will need to add an `id` property for edges in `kg2-simplified.json` and in `kg2-slim.json`. 

What should go in it? 

The [Biolink knowledge graph JSON schema](https://github.com/RTXteam/RTX/blob/master/code/kg2/biolink-kg-schema.md) that I extracted using [misc-tools/biolink_yaml_to_schema_documentation.py](https://github.com/RTXteam/RTX/blob/master/code/kg2/misc-tools/biolink_yaml_to_schema_documentation.py) says:

> `id` `(uriorcurie)`: A unique identifier for an entity. Must be either a CURIE shorthand for a URI or a complete URI; required: True.

Consistent with that, the example JSON knowledge graph from the [KGX GitHub page](https://github.com/biolink/kgx/blob/master/specification/kgx-format.md#kgx-format-as-json) shows a CURIE with `urn:` as the CURIE prefix:
```
    "edges" : [
      {
        "id": "urn:uuid:5b06e86f-d768-4cd9-ac27-abe31e95ab1e",
```
(only the `id` property is shown above). So we could just go with a UUID like that. In Python, you can do:
```
import uuid

new_edge_uuid = str(uuid.uuid1())
```

**Comment by saramsey** [comment]
The particular CURIE prefix `urn:uuid:` may not be definable in `curies-to-urls-map.yaml`, since I don't know what base URL it would map to; for now, I guess we can treat `urn:uuid:` as an exception to our general rule of always defining a new CURIE prefix in `curies-to-urls-map.yaml` and in `kg2_util.py`.

**Comment by ericawood** [comment]
In the user facing data (Neo4j and kgx), our data **does** have an edge id.

Neo4j example:
![image](https://user-images.githubusercontent.com/36611732/107308962-72b65280-6a3e-11eb-9d72-04b7cc10c2e1.png)

kgx/mediKanren example:
![image](https://user-images.githubusercontent.com/36611732/107309175-cb85eb00-6a3e-11eb-8f17-4301caa5defe.png)

Thus, this is not an issue and I am closing it.

**Comment by kvarforl** [comment]
In our slack conversation, @ericawood suggested incorporating this into simplifly: for my edification, is there any reason this couldn't/ shouldn't be added to kg2_util's make_edge function?

**Comment by ericawood** [comment]
> is there any reason this couldn't/ shouldn't be added to kg2_util's make_edge function?

That could be a possibility, but how would we keep ids between different sources separate, since that is all modular.

**Comment by kvarforl** [comment]
Fair enough: it looks like this [`uuid1()`](https://docs.python.org/3/library/uuid.html#uuid.uuid1) function generates a unique id based off the current timestamp, which could maybe be a solution to that. 

I also checked if it was generated in a multiprocessing safe way on `kg2lindsey.rtx.ai`, and it seems like it is:
```
(kg2-venv) ubuntu@ip-172-31-59-26:~$ source kg2-venv/bin/activate
(kg2-venv) ubuntu@ip-172-31-59-26:~$ python3
Python 3.7.9 (default, Aug 18 2020, 06:22:45)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uuid
>>> uuid.uuid1().is_safe
<SafeUUID.safe: 0>
>>>
```

**Comment by kvarforl** [comment]
Erica make the good point that it would be nice to have edge_id's be consistent between builds. Brainstorming ideas on how to do this now.

**Comment by kvarforl** [comment]
Okay, I can consistently generate 100 million unique uuid's by using the same seed for the random number generator:

```python
import uuid
import random

rnd = random.Random()
seed = "xtraspecificseed"
rnd.seed(seed)

counter = 0
uuids = set()
uid = uuid.UUID(int=rnd.getrandbits(128), version=4)
while uid not in uuids:
    uuids.add(uid)
    uid = uuid.UUID(int=rnd.getrandbits(128), version=4)
    counter += 1
    if counter >= 100000000: #break at 10 mil bc this is just a silly test
        break

if counter == 100000000:
    print(f"Generated 100 mill unique id's with seed {seed}")
else:
    print(f"Only able to generate {counter} unique id's with seed {seed}")
```

Now I think it's just a question of making sure that they are assigned to the edges in a consistent order. I think this means that adding edge ids during `Simplify` is a good bet; I need to look into the ordering of the merged kg2.json to see if we can come up with some kind of system to make sure that newly ETL'd edges end up at the end of the edges list.

**Comment by kvarforl** [comment]
Okay question @saramsey: Does the edge id _have_ to be a uuid number, or could it be the string generated by `make_edge_key()` from `kg2_util.py`? https://github.com/RTXteam/RTX/blob/7943eefe79096cfa398601b33ab24be331e4b7b2/code/kg2/kg2_util.py#L653-L657

I think this would be nice since it would be consistent between builds, unique amongst edges (this is how they are being merged in `merge_graphs.py`) and traceable from kg2 to kg2c to the original source.

**Comment by saramsey** [comment]
From the Biolink YAML file, I don't think an edge's `id` field has any constraint other than it should be a string. So I think it does not have to be a UUID string.

https://github.com/biolink/biolink-model/blob/bd3607404bae3677bc8fa6de16067c8abfab56b6/biolink-model.yaml#L4528

**Comment by saramsey** [comment]
> Erica make the good point that it would be nice to have edge_id's be consistent between builds. Brainstorming ideas on how to do this now.
> 
> Thinking we need a way to essentially seed uuid....

Some stability between builds could be achieved by having the edge `id` field be subject-predicate-object-provider, like this (this is a fake example):

`UniProtKB:P12345`-`positively_regulates`-`GO:1234567`-`umls_source:GO`

**Comment by saramsey** [comment]
> Okay question @saramsey: Does the edge id _have_ to be a uuid number, or could it be the string generated by `make_edge_key()` from `kg2_util.py`?
> 
> https://github.com/RTXteam/RTX/blob/7943eefe79096cfa398601b33ab24be331e4b7b2/code/kg2/kg2_util.py#L653-L657
> 
> I think this would be nice since it would be consistent between builds, unique amongst edges (this is how they are being merged in `merge_graphs.py`) and traceable from kg2 to kg2c to the original source.

This seems like a good idea!

**Comment by kvarforl** [comment]
Okay,  I added edge ids in the form 
```
subject_curie---relation---object_curie---provided_by
```
 to each edge in the kg2_util function `make_edge()`, since the id is computed from required arguments to that function and that's the most intuitive place to look when trying to figure out where attributes come from :) I think using the relation (from the original source) is more useful information than using the predicate (from biolink), but let me know if anyone disagrees!

**Comment by saramsey** [comment]
Great, thank you @kvarforl. Do we also need to update line 79 of `kg_json_to_tsv.py`?
https://github.com/RTXteam/RTX/blob/0e79c62e20ae92458468de59b72b51526153ee42/code/kg2/kg_json_to_tsv.py#L79

**Comment by kvarforl** [comment]
@saramsey  ah yes! good catch, thanks!

**Comment by kvarforl** [comment]
okay these made it into kg2.6.0! They're a little long, but I think they make sense. happy to take suggestions for feedback if desired :)
