### ISSUE TITLE
should we ETL DisGeNet into KG2?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1246]
https://www.disgenet.org/downloads

**Comment by ericawood** [comment]
Here's what I have so far on the ETL Guidelines from README. I will update as I learn more.

> What criteria do you use to select sources to include in KG2?
>  
> We emphasize knowledge souces that
> 
>     
>  
> 1. Are available in a flat-file download (e.g., TSV, XML, JSON, DAT, or SQL dump)
> 2. Are being maintained and updated periodically
> 3. Provide content/knowledge that complements (does not duplicate) what is already in KG2.
> 4. Connect concept identifiers that are already in KG2.
> 5. Ideally, provide knowledge based on human curation (favored over computational text-mining).

1. TSV download is an option and should have what we'd want.
2. It appears there is a release about every year. There is a 2020 release, a 2018 release, a 2017 release, a 2016 release, etc. Only the SQLite databases are available for archived releases.
3. I'm not sure if it will provide new relationships, but what it does do is offer ample publications to back up edge AND scores (Jaccard Index) on disease-disease associations.There are also scores for the other edges by DisGeNET. There are three types of associations: gene-disease, variant-disease, disease-disease.
4. Gene-disease -> NCBI-DisGeNET identifiers
5. There is a human curated dump and a computational dump. The human curated dump is quite a bit smaller.

**Comment by ericawood** [comment]
DisGeNet is present in `KG2.6.0`:

`match ()-[e]-(m) where "DisGeNET:" in e.provided_by return count(distinct e.id)`

count(distinct e.id)
--|
345237
