### ISSUE TITLE
Problems With Multihop Queries

### ISSUE THREAD

**Issue by MarkDWilliams** [RTXteam/RTX#1248]
I was trying to run this query
`
{
	"message": {
		"query_graph": {
			"nodes": {
				"n0": {
					"id": "MONDO:0010664",
					"category":"biolink:Disease"
				},
				"n1": {
					"category": "biolink:Gene"
				},
				"n2": {
					"category": "biolink:ChemicalSubstance"
                }
			},
			"edges": {
				"e01": {
					"subject": "n0",
                    "object": "n1"
				},
				"e02": {
					"subject": "n1",
                    "object": "n2"
                }
			}
		}
	}
}
`
but I receive no results and an error `    {
      "code": "InteralErrorA583",
      "level": "ERROR",
      "message": "Help, two edges at A583. Don't know what to do: 2",
      "timestamp": "2021-02-09T18:17:42.690147"
    }`
  However, if the query is broken down into two parts, each part executes fine
  `{
	"message": {
		"query_graph": {
			"nodes": {
				"n0": {
					"id": "MONDO:0010664",
					"category":"biolink:Disease"
				},
				"n1": {
					"category": "biolink:Gene"
                }
			},
			"edges": {
				"e01": {
					"subject": "n0",
                    "object": "n1"
                }
			}
		}
	}
}`

`{
	"message": {
		"query_graph": {
			"nodes": {
				"n0": {
					"id": "UniProtKB:P52788",
					"category":"biolink:Gene"
				},
				"n1": {
					"category": "biolink:ChemicalSubstance"
                }
			},
			"edges": {
				"e01": {
					"subject": "n0",
                    "object": "n1"
                }
			}
		}
	}
}`
UniProtKB:P52788 being the one gene that returns from the first part.  Is there an issue with the formation of the two-hop query, or is this a bug with ARAX?

Thanks,
Mark

**Comment by edeutsch** [comment]
Hi Mark, thanks for the report, this is a bug. It is a bug that I fixed during the relay, but then later discovered that it caused another even worse problem, so I backed it out. I will get it fixed. sorry for the trouble!

**Comment by MarkDWilliams** [comment]
No worries, thanks for looking into this

**Comment by edeutsch** [comment]
@MarkDWilliams sorry this was dropped for so long, but this seems to be now fixed. I tested your query:
```
{ "nodes": { "n0": { "id": "MONDO:0010664", "category":"biolink:Disease" }, "n1": { "category": "biolink:Gene" }, "n2": { "category": "biolink:ChemicalSubstance" } }, "edges": { "e01": { "subject": "n0", "object": "n1" }, "e02": { "subject": "n1", "object": "n2" } } }
```
and it now appears to work properly.

**Comment by dkoslicki** [comment]
@MarkDWilliams Are you ok with this issue being closed out?

**Comment by finnagin** [comment]
Closing as this appears to be fixed
