### ISSUE TITLE
Discussion of node naming: english vs symbol

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1251]
A place to discuss the naming debate from the AHM 2/10/2021; mostly about genes and proteins.
What is the ideal value for the name and full_name fields of these nodes?

Background discussion is here: https://github.com/RTXteam/RTX/issues/1213#issuecomment-772811231

**Comment by edeutsch** [comment]
I had some concerns about making the "name" for a node the gene symbol. But I think after our discussion, my concerns have been reduced to "mild unease". I cannot articulate why this might be a problem. I just feel a little uneasy about it. I'm fine to proceed until we find a concrete reason why this is not good. Maybe there won't be one.

**Comment by kvarforl** [comment]
I think this change has happened, so I'm going to close this issue. Can reopen if more discussion is required.
