### ISSUE TITLE
concept `UMLS:C0021403` has the wrong name ("influenza") and type ("biolink:ChemicalSubstance")

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1253]
from KG2.5.1:
```
match (n {id: 'UMLS:C0021403'}) return n;
```
we get:
```
{
  "iri": "https://identifiers.org/umls:C0021403",
  "category_label": "chemical_substance",
  "deprecated": "False",
  "name": "Influenza",
  "description": "Vaccines used to prevent infection by viruses in the family ORTHOMYXOVIRIDAE. It includes both killed and attenuated vaccines. The composition of the vaccines is changed each year in response to antigenic shifts and changes in prevalence of influenza virus strains. The flu vaccines may be mono- or multi-valent, which contains one or more INFLUENZAVIRUS A and INFLUENZAVIRUS B strains.; influenza virus vaccine, NOS; UMLS Semantic Type: UMLS_STY:T121; UMLS Semantic Type: UMLS_STY:T129; UMLS Semantic Type: UMLS_STY:T121; UMLS Semantic Type: UMLS_STY:T129",
  "provided_by": "identifiers_org_registry:umls",
  "id": "UMLS:C0021403",
  "category": "biolink:ChemicalSubstance",
  "update_date": "2020"
}
```

**Comment by saramsey** [comment]
helpfully reported by @edeutsch

**Comment by saramsey** [comment]
Semantic type codes, per the [2018 Semantic Type Mappings](https://metamap.nlm.nih.gov/Docs/SemanticTypes_2018AB.txt) document:
```
T121: pharmacologic substance
T129: immunologic factor
```

**Comment by finnagin** [comment]
@saramsey Looks like there  are  bunch of Influenza nodes labeled as chemical substance.

If you run the following query in kg 2.5.1: 
```match (n:`biolink:ChemicalSubstance`) where n.name =~ "(?i)influenza.*" return n.name, n.id, n.description```

you will ger 695 different nodes

**Comment by saramsey** [comment]
> @saramsey Looks like there are bunch of Influenza nodes labeled as chemical substance.
> 
> If you run the following query in kg 2.5.1:
> `` match (n:`biolink:ChemicalSubstance`) where n.name =~ "(?i)influenza.*" return n.name, n.id, n.description ``
> 
> you will ger 695 different nodes

Very helpful, thank you

**Comment by finnagin** [comment]
You're welcome!

**Comment by saramsey** [comment]
I am attempting to construct a minimum working example of this bug, but it is proving rather difficult to construct. Still working on it....

**Comment by saramsey** [comment]
Reading the clues, I am suspecting that this specific bug involves cross-talk of information from two ontologies (I suspect UMLS metathesaurus and UMLS MeSH) in `multi_ont_to_json_kg.py`.

**Comment by ericawood** [comment]
Regarding the category:
With TUI's T121 and T129, you will get `chemical_substance` because:
https://github.com/RTXteam/RTX/blob/d3b502dbe3db3984fbf11305709dbf8d9b317b1b/code/kg2/curies-to-categories.yaml#L347
https://github.com/RTXteam/RTX/blob/d3b502dbe3db3984fbf11305709dbf8d9b317b1b/code/kg2/curies-to-categories.yaml#L353

**Comment by ericawood** [comment]
I believe I've found the issue here.

First, here are the TTL files that `UMLS:C00214013` are in:

- umls-atc.ttl
- umls-hcpcs.ttl
- umls-hl7.ttl
- umls-lnc.ttl
- umls-medlineplus.ttl
- umls-msh.ttl
- umls-mth.ttl
- umls-snomedct_us.ttl
- umls-vandf.ttl

The node produced by umls-vandf.ttl looks like this:

![image](https://user-images.githubusercontent.com/36611732/108313917-e9093200-716d-11eb-8c52-420bab7b4327.png)

This is the first node from the TTL files that is just "influenza" (though the one from "HL7" is also problematic). Note, it's description is null.

Due to the following section of code, since it's description is null (even though the other node dictionary doesn't have a null description), it's name is the name of the merged dictionaries:
https://github.com/RTXteam/RTX/blob/4a852c0c134e58bb947545b438601a2979d6eaf4/code/kg2/kg2_util.py#L504-L510

I proposed the following code block instead to reflect what I suspect the intention was:
```
                        elif key == 'name' or key == 'full_name':
                            if value.replace(' ', '_') != stored_value.replace(' ', '_'):
                                stored_desc = ret_dict.get('description', None)
                                new_desc = y.get('description', None)
                                if stored_desc is not None and new_desc is not None:
                                    if len(new_desc) > len(stored_desc):
                                        ret_dict[key] = value
                                elif new_desc is not None:
                                    ret_dict[key] = value
```

This way, the node that doesn't have the description isn't the one that gets its name as the merged name. @saramsey what are your thoughts on this fix?

**Comment by saramsey** [comment]
> This way, the node that doesn't have the description isn't the one that gets its name as the merged name. @saramsey what are your thoughts on this fix?

Sorry for the belated reply. Excellent catch, @ericawood. Nice detective work. Yes, that sounds like a sensible fix. I can't imagine why one would want to have the node that has `NULL` as its `description` property, determine the eventual `name` property of the merged node. Most likely a logic error from when I originally wrote this module.

**Comment by ericawood** [comment]
verifying in kg2.5.2 now

**Comment by ericawood** [comment]
This does not yet appear fixed. Further investigation is needed. Here is the node from KG2.5.2:
```
{
  "iri": "https://identifiers.org/umls:C0021403",
  "category_label": "chemical_substance",
  "deprecated": "False",
  "name": "Influenza",
  "description": "Vaccines used to prevent infection by viruses in the family ORTHOMYXOVIRIDAE. It includes both killed and attenuated vaccines. The composition of the vaccines is changed each year in response to antigenic shifts and changes in prevalence of influenza virus strains. The flu vaccines may be mono- or multi-valent, which contains one or more INFLUENZAVIRUS A and INFLUENZAVIRUS B strains.; influenza virus vaccine, NOS; UMLS Semantic Type: UMLS_STY:T121; UMLS Semantic Type: UMLS_STY:T129; UMLS Semantic Type: UMLS_STY:T121; UMLS Semantic Type: UMLS_STY:T129",
  "provided_by": "identifiers_org_registry:umls",
  "id": "UMLS:C0021403",
  "category": "biolink:ChemicalSubstance",
  "update_date": "2020"
}
```

**Comment by ericawood** [comment]
Actually, due to an error with #1267, this issue still needs to be verified.

**Comment by ericawood** [comment]
This is fixed in KG2.5.2:
```
{
  "iri": "https://identifiers.org/umls:C0021403",
  "category_label": "chemical_substance",
  "deprecated": "False",
  "name": "Influenza Vaccines",
  "description": "Vaccines used to prevent infection by viruses in the family ORTHOMYXOVIRIDAE. It includes both killed and attenuated vaccines. The composition of the vaccines is changed each year in response to antigenic shifts and changes in prevalence of influenza virus strains. The flu vaccines may be mono- or multi-valent, which contains one or more INFLUENZAVIRUS A and INFLUENZAVIRUS B strains.; influenza virus vaccine, NOS; UMLS Semantic Type: UMLS_STY:T121; UMLS Semantic Type: UMLS_STY:T129; UMLS Semantic Type: UMLS_STY:T121; UMLS Semantic Type: UMLS_STY:T129",
  "provided_by": "identifiers_org_registry:umls",
  "id": "UMLS:C0021403",
  "category": "biolink:ChemicalSubstance",
  "update_date": "2020"
}
```
