### ISSUE TITLE
In OMIM, make sure phenotypic features are named correctly

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1254]
Eg. cypher in KG2-5-1:
```
match (n:`biolink:PhenotypicFeature`{id:"OMIM:MTHU000058"}) return n
```
has the type phenotypic feature, but is called `Central Nervous System`. Proposal is: if a non-leaf node from OMIM, then append `related phenotypic feature`. Eg. `Central Nervous System related phenotypic feature`.

**Comment by saramsey** [comment]
Thank you for noting this issue, @dkoslicki. We will do it. I fear we may run into the same ontobio issue that is blocking #1170 but I will check to verify this.

**Comment by saramsey** [comment]
Hi @kvarforl and @ericawood can you please look into how we can identify OMIM nodes that are phenotypes, and adjust the node name as suggested by @dkoslicki ?

**Comment by kvarforl** [comment]
Okay I've been looking into this with the help of @ericawood, as they have a better grasp on `multi_ont_to_kg_json.py` than I do.

@dkoslicki @saramsey forgive my lack of context regarding omim, but I have a  clarifying question for whoever can answer: what does being a non-leaf node from OMIM mean? 
I believe that the type  `phenotypic feature` is being correctly assigned; is it sufficient to update the names of OMIM nodes that have type `phenotypic feature`, or is the extra criteria of being a non-leaf node key to identifying the nodes that need adjusted?

**Comment by kvarforl** [comment]
> I believe that the type `phenotypic feature` is being correctly assigned...

 Oof maybe I spoke too  soon. linking #1278 to remind myself to uncover exactly how phenotypic feature is being determined

**Comment by dkoslicki** [comment]
@kvarforl OMIM is organized as a hierarchy (at least on their website), so I mean any entry that doesn't have a descendants. Eg for human disease -> central nervous system -> ALS, all nodes besides ALS would get "related phenotypic feature"

**Comment by kvarforl** [comment]
Looking at kg2.5.2, all OMIM nodes are getting labeled as `biolink:PhenotypicFeature`.
```
match (n) where n.provided_by = "umls_source:OMIM" return n.category, count(*) as count order by count desc
```

n.category | count
-- | --
"biolink:PhenotypicFeature" | 111588
"biolink:InformationContentEntity" | 1


Looking into how to assign categories more dynamically now.

**Comment by kvarforl** [comment]
Okay, looks like we can use the MIMTYPE attribute to determine the correct category, following this, from [https://omim.org/help/faq](https://omim.org/help/faq).
<img width="660" alt="image" src="https://user-images.githubusercontent.com/39020520/110394961-2d2b7c00-8022-11eb-8b27-1649cb0e4087.png">

**Comment by kvarforl** [comment]
Unfortunately, all of the MIM information that could be used to do this is stored in `owl:DatatypeProperty` in `umls-omim.ttl`.
```bash
ubuntu@ip-172-31-59-26:~/kg2-build$ grep "owl:DatatypeProperty" umls-omim.ttl
<http://purl.bioontology.org/ontology/OMIM/MIMTYPEMEANING> a owl:DatatypeProperty ;
<http://purl.bioontology.org/ontology/OMIM/MIMTYPE> a owl:DatatypeProperty ;
<http://purl.bioontology.org/ontology/OMIM/MIMTYPEVALUE> a owl:DatatypeProperty ;
<http://purl.bioontology.org/ontology/OMIM/GENELOCUS> a owl:DatatypeProperty ;
<http://purl.bioontology.org/ontology/OMIM/GENESYMBOL> a owl:DatatypeProperty ;
<http://purl.bioontology.org/ontology/OMIM/MOVED_FROM> a owl:DatatypeProperty ;
``` 
which is blocked by the ontobio issue Steve mentioned above.

**Comment by ericawood** [comment]
In the output of the temporary ontobio fix, I searched for the example node David gave above:
```
         {
             "category": "biolink:PhenotypicFeature",
             "category_label": "phenotypic_feature",
             "creation_date": null,
             "deprecated": false,
             "description": "UMLS Semantic Type: UMLS_STY:T022",
             "full_name": null,
             "has_biological_sequence": null,
             "id": "OMIM:MTHU000058",
             "iri": "http://purl.obolibrary.org/obo/OMIM_MTHU000058",
             "name": "Central nervous system",
             "provided_by": "umls_source:OMIM",
             "publications": [],
             "replaced_by": null,
             "synonym": [],
             "update_date": "2020"
         },
```
Based on the new code, it did not get "related phenotypic feature" appended to its name. This is because OMIM doesn't actually know that much about it:
```
    <owl:NamedIndividual rdf:about="http://purl.bioontology.org/ontology/OMIM/MTHU000058">
        <umls:has_sty rdf:resource="http://purl.bioontology.org/ontology/STY/T022"/>
    </owl:NamedIndividual>
```
When the node datatype properties are stripped out of OMIM, this is the result for that node:
```
        "OMIM:MTHU000058": {
            "GENELOCUS": null,
            "GENESYMBOL": null,
            "MIMTYPE": null,
            "MIMTYPEMEANING": null,
            "MIMTYPEVALUE": null,
            "MOVED_FROM": null
        },
```
The corresponding CUI node is
```
         {
             "category": "biolink:AnatomicalEntity",
             "category_label": "anatomical_entity",
             "creation_date": null,
             "deprecated": false,
             "description": null,
             "full_name": null,
             "has_biological_sequence": null,
             "id": "UMLS:C3714787",
             "iri": "https://identifiers.org/umls:C3714787",
             "name": "Central nervous system",
             "provided_by": "identifiers_org_registry:umls",
             "publications": [],
             "replaced_by": null,
             "synonym": [],
             "update_date": "2020"
         },
```

This begs the question, @saramsey, should we just remove this line:
https://github.com/RTXteam/RTX/blob/d09fe60f2b14c3fa0e18f282a0488cffdad5f24b/code/kg2/curies-to-categories.yaml#L22
And get the following node breakdown: (note the 57035 `named_thing` nodes)
```
         "umls_source:OMIM": {
             "anatomical_entity": 20,
             "biological_entity": 4500,
             "biological_process": 1,
             "cell": 1,
             "chemical_substance": 1,
             "disease": 7960,
             "disease_or_phenotypic_feature": 945,
             "genomic_entity": 41051,
             "gross_anatomical_structure": 1,
             "information_content_entity": 1,
             "molecular_activity": 2,
             "molecular_entity": 18,
             "named_thing": 57035,
             "pathological_process": 15,
             "phenomenon": 1,
             "physiological_process": 13,
             "protein": 2
         }
```
rather than:
```
         "umls_source:OMIM": {
             "gene": 16301,
             "information_content_entity": 1,
             "phenotypic_feature": 95287
         }
```

In contrast, for the nodes where the desired fix is made (though it is node currently checking that a node is a non-leaf node, is this a problem @dkoslicki?), is it helpful?
```
         {
             "category": "biolink:PhenotypicFeature",
             "category_label": "phenotypic_feature",
             "creation_date": null,
             "deprecated": false,
             "description": "UMLS Semantic Type: UMLS_STY:T047",
             "full_name": null,
             "has_biological_sequence": null,
             "id": "OMIM:607131",
             "iri": "http://purl.obolibrary.org/obo/OMIM_607131",
             "name": "Al-gazali-bakalinova syndrome related phenotypic feature",
             "provided_by": "umls_source:OMIM",
             "publications": [],
             "replaced_by": null,
             "synonym": [
                 "AGBK",
                 "MACROCEPHALY WITH MULTIPLE EPIPHYSEAL DYSPLASIA AND DISTINCTIVE FACIES",
                 "MMEDF"
             ],
             "update_date": "2020"
         },

```
That node refers to https://www.omim.org/entry/607131. Here's the corresponding CUI node:
```
         {
             "category": "biolink:Disease",
             "category_label": "disease",
             "creation_date": null,
             "deprecated": false,
             "description": null,
             "full_name": null,
             "has_biological_sequence": null,
             "id": "UMLS:C1846722",
             "iri": "https://identifiers.org/umls:C1846722",
             "name": "Al-gazali-bakalinova syndrome related phenotypic feature",
             "provided_by": "identifiers_org_registry:umls",
             "publications": [],
             "replaced_by": null,
             "synonym": [], 
             "update_date": "2020"
         },
```

The temporary ontobio fix is essentially this for OMIM:
```
                    if mimtype is not None:
                        # 0, 3, 5 are phenotypes
                        # 1, 4 are genes
                        # There isn't a 2 anymore
                        if mimtype is "1" or mimtype is "4":
                            node_category_label = kg2_util.BIOLINK_CATEGORY_GENE
                        else:
                            node_name += " related phenotypic feature"

```

**Comment by saramsey** [comment]
Thank you @ericawood !!

Is this code being added to `multi_ont_to_json_kg.py`?  I think we should add a code comment indicating the issue number for which this special case is being added.

Also don't we want to use `mimtype == "1"` not `is`?

**Comment by ericawood** [comment]
> Is this code being added to `multi_ont_to_json_kg.py`? I think we should add a code comment indicating the issue number for which this special case is being added.

Yes, that block is being added to `multi_ont_to_json_kg.py`. There are also a couple of other sections that enable this code to work. I will also add comments to the corresponding parts of `build-multi-ont-kg.sh` that I updated.

> Also don't we want to use `mimtype == "1"` not `is`?

I will adjust that, thank you for pointing that out!

@saramsey Regarding my previous comment, do you have any concerns about those examples?

**Comment by saramsey** [comment]
@ericawood do you recommend removing

```
 OMIM: phenotypic feature 
```

??

**Comment by ericawood** [comment]
> @ericawood do you recommend removing
> 
> ```
>  OMIM: phenotypic feature 
> ```
> 
> ??

While I did at first, the fact that most OMIM nodes them become `named thing` tells me that we should not do that. At this point, I think the temporary ontobio fix is better than that, though there will still be some nodes that don't make sense. Do you agree? We could potentially assign `named thing` if there is no MIMTYPE. Do you think that would be better?

**Comment by saramsey** [comment]
@ericawood I like your `MIMTYPE` solution; it seems practical. So if we use your `MIMTYPE` solution, then the only question remains what to do if there is no MIMTYPE, is that right?

**Comment by ericawood** [comment]
> @ericawood I like your `MIMTYPE` solution; it seems practical. So if we use your `MIMTYPE` solution, then the only question remains what to do if there is no MIMTYPE, is that right?

Yes, currently (with the Ontobio fix) `MIMTYPE`s 1 and 4 assign the category `gene` and `MIMTYPE`s 0, 3, and 5 use the default of `phenotype feature`. Nodes without a `MIMTYPE` are also using the default. This is clearly not ideal, though. I'm thinking `named thing` for those without a `MIMTYPE` so that, at the bare minimum, they don't hinder reasoning down the road.

**Comment by saramsey** [comment]
> Okay, looks like we can use the MIMTYPE attribute to determine the correct category, following this, from https://omim.org/help/faq.
> <img alt="image" width="660" src="https://user-images.githubusercontent.com/39020520/110394961-2d2b7c00-8022-11eb-8b27-1649cb0e4087.png">

Great idea, @kvarforl !

**Comment by saramsey** [comment]
> > @ericawood I like your `MIMTYPE` solution; it seems practical. So if we use your `MIMTYPE` solution, then the only question remains what to do if there is no MIMTYPE, is that right?
> 
> Yes, currently (with the Ontobio fix) `MIMTYPE`s 1 and 4 assign the category `gene` and `MIMTYPE`s 0, 3, and 5 use the default of `phenotype feature`. Nodes without a `MIMTYPE` are also using the default. This is clearly not ideal, though. I'm thinking `named thing` for those without a `MIMTYPE` so that, at the bare minimum, they don't hinder reasoning down the road.

That seems sensible to me, @ericawood.

**Comment by ericawood** [comment]
@dkoslicki This is what it looks like in `KG2.6.0` with this fix. (Note, it doesn't differentiate leaf vs non-leaf notes). Is this what you were looking for?

`match (n) where split(n.id, ':')[0]="OMIM" and n.category_label="phenotypic_feature" return n.id, n.name, n.category_label limit 50`

n.id | n.name | n.category_label
-- | -- | --
"OMIM:615439" | "Macular degeneration, age-related, 13 related phenotypic feature" | "phenotypic_feature"
"OMIM:615436" | "Aortic aneurysm, familial thoracic 8 related phenotypic feature" | "phenotypic_feature"
"OMIM:615438" | "Infantile liver failure syndrome 1 related phenotypic feature" | "phenotypic_feature"
"OMIM:615431" | "Myopia 23, autosomal recessive related phenotypic feature" | "phenotypic_feature"
"OMIM:615432" | "Specific language impairment 5 related phenotypic feature" | "phenotypic_feature"
"OMIM:615433" | "CHROMOSOME 3q13.31 DELETION SYNDROME related phenotypic feature" | "phenotypic_feature"
"OMIM:615434" | "Retinitis pigmentosa 82 with or without situs inversus related phenotypic feature" | "phenotypic_feature"
"OMIM:615429" | "Deafness, autosomal recessive 88 related phenotypic feature" | "phenotypic_feature"
"OMIM:615424" | "Inclusion body myopathy with early-onset paget disease with or without frontotemporal dementia 3 related phenotypic feature" | "phenotypic_feature"
"OMIM:615425" | "Epidermolysis bullosa simplex, autosomal recessive 2 related phenotypic feature" | "phenotypic_feature"
"OMIM:615426" | "Amyotrophic lateral sclerosis 20 related phenotypic feature" | "phenotypic_feature"
"OMIM:615420" | "Myopia 22, autosomal dominant related phenotypic feature" | "phenotypic_feature"
"OMIM:615422" | "Inclusion body myopathy with early-onset paget disease with or without frontotemporal dementia 2 related phenotypic feature" | "phenotypic_feature"
"OMIM:615457" | "Body mass index quantitative trait locus 18 related phenotypic feature" | "phenotypic_feature"
"OMIM:615458" | "Microcornea, myopic chorioretinal atrophy, and telecanthus related phenotypic feature" | "phenotypic_feature"
"OMIM:615453" | "Mitochondrial complex iii deficiency, nuclear type 6 related phenotypic feature" | "phenotypic_feature"
"OMIM:615451" | "Ciliary dyskinesia, primary, 23 related phenotypic feature" | "phenotypic_feature"
"OMIM:615444" | "Ciliary dyskinesia, primary, 22 related phenotypic feature" | "phenotypic_feature"
"OMIM:615440" | "Combined oxidative phosphorylation deficiency 17 related phenotypic feature" | "phenotypic_feature"
"OMIM:615441" | "Ventricular tachycardia, catecholaminergic polymorphic, 5, with or without muscle weakness related phenotypic feature" | "phenotypic_feature"
"OMIM:135580" | "Fibromuscular dysplasia related phenotypic feature" | "phenotypic_feature"
"OMIM:615418" | "Mitochondrial dna depletion syndrome 12b (cardiomyopathic type), autosomal recessive related phenotypic feature" | "phenotypic_feature"
"OMIM:615419" | "Hypotonia, infantile, with psychomotor retardation and characteristic facies 1 related phenotypic feature" | "phenotypic_feature"
"OMIM:615413" | "Spermatogenic failure 12 related phenotypic feature" | "phenotypic_feature"
"OMIM:615414" | "Microcephaly 11, primary, autosomal recessive related phenotypic feature" | "phenotypic_feature"
"OMIM:615415" | "Renal-hepatic-pancreatic dysplasia 2 related phenotypic feature" | "phenotypic_feature"
"OMIM:135550" | "Fibromatosis, gingival, with progressive deafness related phenotypic feature" | "phenotypic_feature"
"OMIM:615411" | "Cortical dysplasia, complex, with other brain malformations 3 related phenotypic feature" | "phenotypic_feature"
"OMIM:615412" | "Cortical dysplasia, complex, with other brain malformations 4 related phenotypic feature" | "phenotypic_feature"
"OMIM:160500" | "Myopathy, distal, 1 related phenotypic feature" | "phenotypic_feature"
"OMIM:615402" | "Dyschromatosis universalis hereditaria 3 related phenotypic feature" | "phenotypic_feature"
"OMIM:615400" | "Epilepsy, familial adult myoclonic, 5 related phenotypic feature" | "phenotypic_feature"
"OMIM:615401" | "Immunodeficiency 8 related phenotypic feature" | "phenotypic_feature"
"OMIM:160570" | "Myopathy with storage of glycoproteins and glycosaminoglycans related phenotypic feature" | "phenotypic_feature"
"OMIM:160565" | "Myopathy, tubular aggregate, 1 related phenotypic feature" | "phenotypic_feature"
"OMIM:615481" | "Ciliary dyskinesia, primary, 24 related phenotypic feature" | "phenotypic_feature"
"OMIM:615476" | "Epileptic encephalopathy, early infantile, 18 related phenotypic feature" | "phenotypic_feature"
"OMIM:615471" | "Mitochondrial dna depletion syndrome 13 (encephalomyopathic type) related phenotypic feature" | "phenotypic_feature"
"OMIM:615473" | "Epileptic encephalopathy, early infantile, 17 related phenotypic feature" | "phenotypic_feature"
"OMIM:615474" | "Primary aldosteronism, seizures, and neurologic abnormalities related phenotypic feature" | "phenotypic_feature"
"OMIM:615468" | "Immunodeficiency 12 related phenotypic feature" | "phenotypic_feature"
"OMIM:615465" | "Hartsfield syndrome related phenotypic feature" | "phenotypic_feature"
"OMIM:228355" | "Fetal iodine deficiency disorder related phenotypic feature" | "phenotypic_feature"
"OMIM:615619" | "Cholangiocarcinoma, susceptibility to related phenotypic feature" | "phenotypic_feature"
"OMIM:615615" | "Immunodeficiency 18 related phenotypic feature" | "phenotypic_feature"
"OMIM:615616" | "Arrhythmogenic right ventricular dysplasia, familial, 13 related phenotypic feature" | "phenotypic_feature"
"OMIM:615617" | "Immunodeficiency 19 related phenotypic feature" | "phenotypic_feature"
"OMIM:615612" | "Developmental dysplasia of the hip 2 related phenotypic feature" | "phenotypic_feature"
"OMIM:601319" | "Odontomicronychial dysplasia related phenotypic feature" | "phenotypic_feature"
"OMIM:228200" | "Femur-fibula-ulna syndrome related phenotypic feature" | "phenotypic_feature"

**Comment by ericawood** [comment]
Also, the Cypher query (modified from David's original query)
`match (n {id:"OMIM:MTHU000058"}) return n.id, n.name, n.category_label`
now returns

n.id | n.name | n.category_label
-- | -- | --
"OMIM:MTHU000058" | "Central nervous system" | "named_thing"

(see #1278)

**Comment by kvarforl** [comment]
I'm going to consider this fixed and close it out! Can always reopen if needed.
