### ISSUE TITLE
Clean up/update dumpdata.py (stop dumping KG1, etc.)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1256]
we want to change dumpdata.py so that it only grabs info from KG2, and change the generated file so that it has four columns:

- curie
- name
- full_name
- type

and link the `dump_kg2_synonyms.py` and `dump_kg2_equivalencies.py` scripts so that they're both run with `dumpdata.py` as well. and do some renaming of files.

will do this in the `kg2.5integration` branch since that's where work on the synonymizer will be happening for now.

can put the generated files in the KG2.5.1 directory on arax.ncats.io and let @edeutsch know.

**Comment by amykglen** [comment]
ok, @edeutsch - this is done in the `kg2.5integration` branch. made the following changes to `dumpdata.py`:
- got rid of the KG1 parts and started extracting `full_name`
- renamed it `dump_kg2_node_info.py`
- moved it into the `ARAX/NodeSynonymizer/` directory
  - can undo/adjust this if you want, but it seemed strange to me that it still lived outside of ARAX (it was in `RTX/data/KGmetadata/`)
  - this means all output files are put directly into `ARAX/NodeSynonymizer/`
- consolidated a bit so that it also creates the `kg2_synonyms.json` and `kg2_equivalencies.tsv` files
- changed the output file name from `NodeNamesDescriptions_KG2.tsv` to `kg2_node_info.tsv`

ran it on KG2.5.1 and put the 3 resulting files (`kg2_node_info.tsv`, `kg2_equivalencies.tsv`, and `kg2_synonyms.json`) in `arax.ncats.io:/data/orangeboard/databases/KG2.5.1/`. let me know if there are issues!

**Comment by edeutsch** [comment]
Many thanks, @amykglen I am working on this. It seems to be pretty good, except I stumbled on an issue with `kg2_equivalencies.tsv`. I'm finding this that too many things are equivalent? UMLS:C0020740 seems to be ibuprofen.
```
$ grep UMLS:C0020740 kg2_equivalencies.tsv  | wc -l
2880
$ grep UMLS:C0020740 kg2_equivalencies.tsv  | grep NCBIGene | wc -l
98
```
Ibuprofen seems to be equivalent to 2880 different things? Maybe half that because the equivalencies seem to be bi-directional. That's already going to cause huge clusters. But then Ibuprofen is equivalent to 98 (or 49) NBCIGenes?

I'm heading down a road where everything is equivalent to nearly everything else.

I also notice that the equivalencies swelled from 11 MB in KG2.3.1 to 1.5 GB in KG2.5.1. I suspect something is wrong with the kg2_equivalencies.tsv output or KG. Would you have a look?

thanks!

**Comment by amykglen** [comment]
oh wow, yep, that's a bug! somehow I lost a colon in the cypher query so indeed everything was being put in kg2_equivalencies. sorry about that. it's fixed now and I put an updated copy of `kg2_equivalencies.tsv` in `arax.ncats.io:/data/orangeboard/databases/KG2.5.1/` (it's only 14 MB).

**Comment by amykglen** [comment]
also, if it's helpful - I can adjust the query that populates `kg2_equivalencies.tsv` so that there aren't separate rows for each direction (e.g., if there was already a row for `DRUGBANK:DB09256 --> CHEMBL.COMPOUND:CHEMBL20883`, no additional `CHEMBL.COMPOUND:CHEMBL20883 --> DRUGBANK:DB09256` row would be added). it's a trivial change from my end - whatever works better for you.

**Comment by edeutsch** [comment]
great, thanks! sure, it would be great to remove the duplicates. My code is structured so that only one direction is necessary, but both is not detrimental. If it's easy, I vote for a file half the size.

**Comment by amykglen** [comment]
ok, cool - made that adjustment, regenerated `kg2_equivalencies.tsv`, and put it on the server. looks like it's still about 14MB but has about 10,000 fewer lines. (apparently there are only ~10,000 node pairs in KG2 with `same_as` edges in both directions. probably still good to eliminate the duplicates nonetheless!)
