### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1257]
To get the discussion going about CI/CD, I noticed that if we can get the ARAX system deployment automated in a shell script, we can get Travis CI to work: https://docs.travis-ci.com/user/job-lifecycle#complex-build-commands
We will want to be careful with timeouts though: if any particular job takes [longer than 50 minutes](https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts), it will quit. Other than that, it _seems_ straightforward-ish.

**Comment by dkoslicki** [comment]
And it might be straightforward to skip the build process and just point it to a docker image: https://stackoverflow.com/questions/38133107/travis-ci-docker-image-as-build-environment

**Comment by saramsey** [comment]
Thank you @dkoslicki for being the spark!  

50 minutes should be plenty of time to deploy ARAX and run our test suite... or at least a goal to shoot for, right?

**Comment by saramsey** [comment]
- @dkoslicki looks like you were right that one doesn't necessarily need to *explicitly* provision a server to do this.  I see that GitHub actually sells this as a hosted service:
https://github.com/marketplace/travis-ci

The cost is not that high, compared to our $3k/month AWS bills.

**Comment by finnagin** [comment]
@finnagin will look into setting up Travis-ci to utilize our rtx docker container as a dev environment.

**Comment by finnagin** [comment]
This is currently implemented in this [fork.](https://github.com/rtx-travis-tester/RTX) However, there is one problem. The time limit for setting up the environment and running tests is 50 minutes and this is not enough time to download the COHD and DTD databases. 

I think a simple solution would be to create slim versions of the databases that just contain the information we need to run the COHD/DTD tests and to write a simple script to generate these slim databases easily for if we add new test cases. I think this should be pretty straightforward to do from already existing databases e.g. input a list of curies needed and then pull out data from COHD and DTD involving those curies.

**Comment by finnagin** [comment]
Closing this as everything is merged and working
