### ISSUE TITLE
move hosting of kg2-simplified.json.gz to the public S3 bucket

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1264]
this is to partially address TranslatorPM issue 52; see #1129 for discussion of a more durable and systematic solution via the KG archive

**Comment by saramsey** [comment]
OK, `kg2-simplified.json.gz` is now hosted in the S3 bucket `rtx-kg2-public`:
<img width="962" alt="Screen Shot 2021-02-17 at 8 16 27 PM" src="https://user-images.githubusercontent.com/5562107/108304531-17324600-715d-11eb-9b3b-24cc858dbe7a.png">

**Comment by ericawood** [comment]
This appears to be fixed in KG2.5.2. The S3 bucket lists:

```
2021-03-06 01:56:32      46265 kg2-simplified-report.json
```

**Comment by finnagin** [comment]
@saramsey do you know if this is okay to close or should it be moved over to the RTX-KG2 repo?

**Comment by saramsey** [comment]
We have since cooled off on the idea of publicly hosting RTX-KG2 in an S3 bucket under our team's control (instead, we host RTX-KG2 dumps in a git-lfs area in [github:ncats/translator-lfs-artifacts](https://github.com/ncats/translator-lfs-artifacts). For that reason, closing this issue.
