### ISSUE TITLE
we should rename kg2-tsv.tar.gz kg2-tsv-for-neo4j.tar.gz

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1267]
To disambiguate the two TSV tarballs for KG2, I think we should rename `kg2-tsv.tar.gz` (the file created by `Snakefile-post`) to the more helpful name `kg2-tsv-for-neo4j.tar.gz`.

**Comment by ericawood** [comment]
I don't know if this is the right issue to ask this under, but does anyone have any thoughts on calling the TSV directory for a test build something different than a regular build? The build process deletes the directory that the TSV files are built into. Thus, if a test build is after a full build, the full build's TSV files are deleted. They can be restored by decompressing the tarball.

**Comment by kvarforl** [comment]
Hmm, I can see both sides! My instinct is to leave it as is because the information isn't lost; as you said, you can decompress the tarball. it might also save space to keep it the same, though probably not enough to make a huge difference. I honestly don't have super strong feelings either way :)

**Comment by ericawood** [comment]
This was fixed in KG2.5.2.
