### ISSUE TITLE
Get links back for `provided_by` and the like

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1269]
It would be great to get back the links for various nodes and edges. Eg. `CHEMBL.COMPOUND:CHEMBL112` no longer links to ChemBL. Tyler Beck says it would be great to get these back.

For edges, we can:
1. If there are PubMed IDs, link to that article directly from that link
2. If there are no pubmed ID's, somehow link to the `provided_by` repo?

High prio since NCATS will be using our UI for the demo

**Comment by saramsey** [comment]
Hi @dkoslicki the `iri` field in KG2.5.1 for that compound (`CHEMBL.COMPOUND:CHEMBL112`) works for me. Try this cypher:
```
match (n {id: 'CHEMBL.COMPOUND:CHEMBL112'}) return n.iri;
```
You will see:
<img width="640" alt="Screen Shot 2021-02-23 at 2 23 08 PM" src="https://user-images.githubusercontent.com/5562107/108916247-d7e37980-75e2-11eb-95fd-0b501fb79f9a.png">
<img width="1077" alt="Screen Shot 2021-02-23 at 2 24 51 PM" src="https://user-images.githubusercontent.com/5562107/108916300-e893ef80-75e2-11eb-937a-0cbb9d61d085.png">


Then click on the link:



<img width="640" alt="Screen Shot 2021-02-23 at 2 23 08 PM" src="https://user-images.githubusercontent.com/5562107/108916134-b2567000-75e2-11eb-956d-884658c64414.png">

**Comment by saramsey** [comment]
not seeing a KG2 issue here?

**Comment by edeutsch** [comment]
maybe Expand() needs to include that field as an Attribute. It seems it is not currently doing that?

**Comment by saramsey** [comment]
To get the `provided_by` source, you need to do a KG2 lookup to find the `iri` field of the node whose `id` is the `provided_by` CURIE ID.

**Comment by dkoslicki** [comment]
@saramsey right, this is mostly a UI issue, hence the @isbluis tag, apologies if this caused confusion

**Comment by dkoslicki** [comment]
Oh, right! I think `Expand` isn’t returning that attribute (at least, when looking at the JSON, it’s missing). I’ll ping @amykglen to take a look too

**Comment by amykglen** [comment]
whoops, yep, somewhere in the switch to TRAPI 1.0 "iri" got confused with "uri", so the iris weren't being pulled properly from KG2/c. fixed in `master` now!

**Comment by isbluis** [comment]
Great!  I'll make changes to the UI.

Any other fields that should be converted to links?

**Comment by isbluis** [comment]
This is now done for PMID in devLM/ .  

I do notice that some publication records return a PMID string without the colon, e.g. "PMID104998" vs "PMID:20667728".  You can see this by opening the following link and clicking on the "ACETAMINOPHEN" node in any of the graphs:

https://arax.ncats.io/devLM/index.html?r=2386

I only trigger the link if I see the colon, so as to avoid linking to other words that may just happen to start with "PMID".  Any suggestions on what to do?  Might want to verify that the string or id are not getting mangled or truncated upstream.

**Comment by dkoslicki** [comment]
Don't know if the colon problem is a KG2 thing (@saramsey or @amykglen), or something else. I'll put on the agenda a discussion about links for edges since Tyler was quite passionate about evidence for edges.

**Comment by dkoslicki** [comment]
Re: anything else to make a link: does anyone know of there URI's/URLs that can be resolved?

**Comment by amykglen** [comment]
I think the colon discrepancies are coming from KG2 itself; I don't think those are modified anywhere down the chain and I see some PMIDs lacking colons in KG2-5-1. e.g.:
```
match (n) where "PMID104998" in n.publications return n.id, n.name, n.publications limit 1
```
n.id | n.name | n.publications
-- | -- | --
"DRUGBANK:DB00316" | "Acetaminophen" | ["PMID104998", "PMID11866476", "PMID12242329", "PMID14758786", "PMID15662292", "PMID15879007", "PMID16413237", "PMID17227290", "PMID18232020", "PMID21508345", "PMID26049587", "PMID26572078", "PMID7039926"]

maybe it would be good to try to always use a colon in PMIDs in KG2?

**Comment by saramsey** [comment]
This issue motivated #1270 (apparently the ChEMBL Knowledge Source *itself* doesn't have its own dedicated node in KG2).

**Comment by saramsey** [comment]
The absence of a colon in the PubMed CURIE is a bug. I will look into it.

**Comment by saramsey** [comment]
Just pushed a fix for the PMID issue; tagging @ericawood so they are aware.

**Comment by isbluis** [comment]
Thanks for fixing those, @saramsey !

Now I see some publication records with values like "2-e", "2-z", "2-0".  Do you know what those are or what they mean?  Perhaps others lurk...
e.g. see UniProtKB:P22309 for "2-z" or UniProtKB:P23786 for "2-e" and "2-0".

**Comment by isbluis** [comment]
Also added links to doi.org for DOI: records.

**Comment by isbluis** [comment]
Hi again @saramsey .

One of the publication records for UniProtKB:P22303 is:
https://en.wikipedia.org/wiki/Pain_disorde

This appears to be truncated, since there is no such page, but there is one at:
https://en.wikipedia.org/wiki/Pain_disorder

Hope this is still the appropriate issue to use, or let me know if you prefer that I open a new one each time.

**Comment by isbluis** [comment]
A few more DOI entries that appear to be incorrect (as they are not resolvable at https://www.doi.org/ )  :
```
DOI:10.1002/(sici)1098-1004(1999)14:1<67::aid-humu8>3.0.co
DOI:10.1002/(sici)1098-1004(1998)11:5<377::aid-humu5>3.0.co
DOI:10.1002/(sici)1098-1004(1999)13:3<210::aid-humu5>3.0.co
DOI:10.1002/(sici)1098-1004(1998)12:3<206::aid-humu8>3.0.co
DOI:10.1002/(sici)1097-0215(20000315)85:6<865::aid-ijc21>3.0.co
```

It seems to be tripping on the colons; are these legitimate DOIs?

e.g. UniProtKB:P23786 for reference

**Comment by isbluis** [comment]
UI changes committed into master:  4a695a37813509568145cb4255aea599eb27f5f8

**Comment by edeutsch** [comment]
rollout out everywhere to all deployments such as /beta except for main production which, is still a few commits behind due to some potential instability with `master`

**Comment by kvarforl** [comment]
chiming in a bit late here, but would it be helpful if we make some sort of mapping file that maps `provided_by` fields to the basic URL of the source so that perhaps Luis can link them in the UI?

I imagine the content would be similar to what [this](https://github.com/RTXteam/RTX/tree/master/code/kg2#what-data-sources-are-used-in-kg2) table provides, but more easily read / parsed. Apologies if something like this already exists or has been discussed!

**Comment by dkoslicki** [comment]
@kvarforl , is the mapping you're referring to something like [this](https://github.com/RTXteam/RTX/blob/master/code/kg2/curies-to-urls-map.yaml)? If so, @isbluis , would you be able to make the CURIES themselves into a clickable URL? Eg. for [this result](https://arax.ncats.io/?r=4757), it would be nice if after clicking on Acetaminophen, the CURIE UniProtKB:P05177 would navigate to https://www.uniprot.org/uniprot/P05177

**Comment by kvarforl** [comment]
@dkoslicki  yes that's exactly what I was thinking!

For your example, you can look up UniProtKB in the file David linked:
https://github.com/RTXteam/RTX/blob/758ba97663ce07c75fa00f277c6eaf98cd9ddc3f/code/kg2/curies-to-urls-map.yaml#L387
And then append the id to it: [https://identifiers.org/uniprot:P05177](https://identifiers.org/uniprot:P05177)
And you should be redirected to the right place :)
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/39020520/111352676-af7af800-8641-11eb-8956-613342f63adc.png">

**Comment by edeutsch** [comment]
Note that in the result that you reference:
https://arax.ncats.io/?r=4757
If you scroll down below the looooong description, there is a clickable link as the IRI field.
Maybe just making the IRI field more prominent at the top above the description would be suitable?

**Comment by dkoslicki** [comment]
Ah, I see! So maybe the easiest thing is to make the fields, name, ID, category, IRI, and _then_ description and the rest of the fields. @isbluis , do you think this is doable?

**Comment by kvarforl** [comment]
@edeutsch thank you! I just noticed that and was editing my comment accordingly. Sorry to be behind the boat :)

**Comment by isbluis** [comment]
Hi @dkoslicki .  Yes, the ordering and layout can be changed in whatever way seems best / most reasonable.   Also it is easy enough to grab the `iri` (if present) and make it a link of Id(CURIE).

At the moment the UI merely takes the contents of `attributes` (in red, below) and displays them serially as they come from the json response -- so this is to say that another way to change the order of the display would be to change the order of those attributes in the json objects prior to returning them.  But easy and glad to add whichever special logic to this.

The `Name`, `Id`, and `Category` are top-level attributes of the `node`, so those are handled separately (in blue). 


![image](https://user-images.githubusercontent.com/37852256/111365258-819cb000-864f-11eb-82a4-7167bec242fd.png)

**Comment by dkoslicki** [comment]
I see @isbluis! I think it might be easiest to make the change in the UI to make the iri go before the description, otherwise we would need to muck about with ARAX_query.py or the like.

**Comment by isbluis** [comment]
Sure thing!  Done in `devLM`; let me know if this works, or would like to add/change anything:
https://arax.ncats.io/devLM/?r=4757

**Comment by dkoslicki** [comment]
Looks great to me, thanks @isbluis !

**Comment by dkoslicki** [comment]
Confirmed in production and closing
