### ISSUE TITLE
chembl_mysql_to_kg_json.py should create a "source" node for ChEMBL

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1270]
In the script `chembl_mysql_to_kg_json.py`, a node should be created to represent the entire ChEMBL knowledge source. That node's `id` property should be `identifiers_org_registry:chembl` (which should be accessed as variable `CHEMBL_KG_CURIE_ID` in that module).  Basically I think at line 433 we need to call:

```
nodes.append(make_node(CHEMBL_KB_CURIE_ID, 
                                            kg2_util.BASE_URL_IDENTIFIERS_ORG_REGISTRY + 'chembl',
                                           'ChEMBL',
                                           kg2_util.BIOLINK_CATEGORY_DATA_FILE,
                                           update_date,
                                           CHEMBL_KB_CURIE_ID))
```

**Comment by kvarforl** [comment]
verifying in kg2.5.2 now ...
