### ISSUE TITLE
Add PMID's on NGD edges

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1272]
Since not many edges have linkable literature support (at the moment), let's extend the normalized Google distance to decorate those edges with link-able PMIDs.

**Comment by finnagin** [comment]
Good idea!

**Comment by finnagin** [comment]
For my reference later: Looks like PMIDS are found on [line 192](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Overlay/compute_ngd.py#L192-L193) 

Also, looks like the urls in pubmed are derived from the the PMID: e.g. https://pubmed.ncbi.nlm.nih.gov/33617777/

Should we add this in as an edge attribute? Maybe labeled `publication_uris`?

**Comment by dkoslicki** [comment]
@finnagin Do you have a status update on this one? Good to close?

**Comment by finnagin** [comment]
Good to close!
