### ISSUE TITLE
Another short mis-synomized node: GK

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1277]
Name: GK (UniProtKB:P32189) 
Id: UniProtKB:P32189 
Category: biolink:PhenotypicFeature

**Comment by amykglen** [comment]
looks good in KG2.6.7.1c: https://arax.ncats.io/?term=UniProtKB:P32189

good to close, @dkoslicki?

**Comment by dkoslicki** [comment]
Great!
