### ISSUE TITLE
PhenotypicFeatures that are proteins, diseases, etc.

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1278]
Don't know if this is a synonymizer issue or not (so tentatively labeling), but take a look at the results of:
https://arax.ncats.io/beta/?r=2943

which corresponds to:
```
add_qnode(id=MONDO:0010613, key=n0)
add_qnode(category=biolink:PhenotypicFeature, key=n1)
add_qedge(subject=n0, object=n1, key=e0)
expand(edge_key=e0,kp=ARAX/KG2)
overlay(action=compute_ngd,default_value=inf,virtual_relation_label=V1,subject_qnode_key=n0,object_qnode_key=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=100)
```

And note the proteins (such as PLPP2)

**Comment by amykglen** [comment]
hmm, at least in the case of PLPP1 and PLPP2, the problem seems to be that one of the equivalent curies (OMIM:607124 and OMIM:607126, respectively) has a type of `biolink:PhenotypicFeature` in KG2-3-4:

![Screen Shot 2021-03-01 at 2 19 26 PM](https://user-images.githubusercontent.com/49423686/109566902-618abf80-7a99-11eb-866d-8b1d7f628b1c.png)

**Comment by amykglen** [comment]
checked out more of the protein-ish results, and so far all of them seem to have an OMIM curie that is labeled as a biolink:PhenotypicFeature in KG2-3-4:
```
match (n) where n.id in ["OMIM:607124", "OMIM:607126", "OMIM:603099", "OMIM:610516", "OMIM:138430", "OMIM:138420", "OMIM:300474"] return n.id, n.name, n.category
```

n.id | n.name | n.category
-- | -- | --
"OMIM:300474" | "Glycerol kinase" | "biolink:PhenotypicFeature"
"OMIM:603099" | "1-acylglycerol-3-phosphate o-acyltransferase 1" | "biolink:PhenotypicFeature"
"OMIM:610516" | "Glycerate kinase" | "biolink:PhenotypicFeature"
"OMIM:138420" | "Glycerol-3-phosphate dehydrogenase 1" | "biolink:PhenotypicFeature"
"OMIM:138430" | "Glycerol-3-phosphate dehydrogenase 2" | "biolink:PhenotypicFeature"
"OMIM:607126" | "Phospholipid phosphatase 2" | "biolink:PhenotypicFeature"
"OMIM:607124" | "Phospholipid phosphatase 1" | "biolink:PhenotypicFeature"

**Comment by kvarforl** [comment]
This is definitely an OMIM parsing issue; however, the information needed to fix is stored in `owl:DatatypeProperty` in `umls-omim.ttl`.
```bash
ubuntu@ip-172-31-59-26:~/kg2-build$ grep "owl:DatatypeProperty" umls-omim.ttl
<http://purl.bioontology.org/ontology/OMIM/MIMTYPEMEANING> a owl:DatatypeProperty ;
<http://purl.bioontology.org/ontology/OMIM/MIMTYPE> a owl:DatatypeProperty ;
<http://purl.bioontology.org/ontology/OMIM/MIMTYPEVALUE> a owl:DatatypeProperty ;
<http://purl.bioontology.org/ontology/OMIM/GENELOCUS> a owl:DatatypeProperty ;
<http://purl.bioontology.org/ontology/OMIM/GENESYMBOL> a owl:DatatypeProperty ;
<http://purl.bioontology.org/ontology/OMIM/MOVED_FROM> a owl:DatatypeProperty ;
``` 
which is blocked by ontobio issue 507, linked in https://github.com/RTXteam/RTX/issues/1254#issuecomment-785456389. (trying not to spam the ontobio issue with multiple mentions of the same general blockage)

**Comment by ericawood** [comment]
Note to self that the line below is part of the problem:
https://github.com/RTXteam/RTX/blob/208bb6b97186e57d654d13f34dfa7efab58ce613/code/kg2/curies-to-categories.yaml#L22

**Comment by ericawood** [comment]
This appears to be fixed in `KG2.6.0`:

`match (n) where split(n.id, ':')[0]="OMIM" return n.category_label, count(n) order by count(n) desc`

n.category_label | count(n)
-- | --
"named_thing" | 86259
"gene" | 16301
"phenotypic_feature" | 9029
