### ISSUE TITLE
Response().from_dict() issue with node categories that are strings

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1281]
when loading the response from an external KP into our object model with:
```
kp_response_obj = Response().from_dict(json_response)
```
it appears that node categories that looked like this in the JSON response:
```
'category': 'biolink:ChemicalSubstance'
```
are transformed into this in the kp_response_obj:
```
 'n01': {'category': ['b',
                      'i',
                      'o',
                      'l',
                      'i',
                      'n',
                      'k',
                      ':',
                      'C',
                      'h',
                      'e',
                      'm',
                      'i',
                      'c',
                      'a',
                      'l',
                      'S',
                      'u',
                      'b',
                      's',
                      't',
                      'a',
                      'n',
                      'c',
                      'e'],
```
(this is in `master`)

**Comment by edeutsch** [comment]
The root of the problem is that the OpenAPI code generation system is broken for properties that can be either a string or an array, which is causing several groups several problems. long story.

But the good news is that as part of last weekend's work I put together a workaround. Can you see if you can use this class method instead to do the conversion?
```
                query['message'] = ARAXMessenger().from_dict(query['message'])
```
This operates at the message level not the response level, but hopefully that won't cause a problem?

**Comment by amykglen** [comment]
oh cool - huh, so I just switched to what you said: `kp_message = ARAXMessenger().from_dict(json_response["message"])`, but I still seem to be seeing the same thing:
```
{'HGNC:9379': {'attributes': None,
 'category': ['b', 'i', 'o', 'l', 'i', 'n', 'k', ':', 'G', 'e', 'n', 'e'],
 'name': None}
```

**Comment by edeutsch** [comment]
ah! I see, that fix only applies to the query_graph, not the knowledge_graph!
Hang on a sec, will fix.

**Comment by edeutsch** [comment]
I just checked in a fix into master (forgot to tag this issue, sorry). It is totally untested, sorry. If that doesn't work, maybe you can send me a repro? (endpoint and query_graph used) Note that the result of this fix is that categories will be lists of one element now.

**Comment by edeutsch** [comment]
Or more precisely, they might be None or a list of one or more categories

**Comment by amykglen** [comment]
awesome, looks good now! thanks!
