### ISSUE TITLE
update predicate remap file with new relation predicates in KG2.5.1

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1283]
from `filter_and_remap_predicates.log` for the KG2.5.2 build:
<img width="474" alt="Screen Shot 2021-03-05 at 10 03 33 AM" src="https://user-images.githubusercontent.com/39020520/110156396-bf6e1e80-7d9b-11eb-9bf8-64c028300687.png">

I added an an entry for `GO:located_in` locally on kg2steve (where the build is happening), but have yet to find any information or decide on any mappings for `PSY`.
@saramsey what are your thoughts?

**Comment by saramsey** [comment]
How about mapping `GO:located_in` to `biolink:located_in`

**Comment by saramsey** [comment]
`PSY:RO` can be mapped to `biolink:related_to`

**Comment by saramsey** [comment]
`PSY:used_for` can be mapped (with `inverted`) to `biolink:has_input`

**Comment by saramsey** [comment]
`PSY:RB` can be mapped (with `invert`) to `biolink:subclass_of`

**Comment by saramsey** [comment]
for `PSY:use`, I need to do some checking....

**Comment by saramsey** [comment]
For future reference, this UMLS page seems useful: 
https://www.nlm.nih.gov/research/umls/knowledge_sources/metathesaurus/release/abbreviations.html

scroll down to see the various relation types in UMLS. Also, searching within the already-existing `predicate-remap.yaml` file for the label for the original relation (without the CURIE prefix), and there is a good chance you'll find a hit, especially if it is a UMLS relation type (as is the case with `RB` and `RO`).

**Comment by saramsey** [comment]
For `PSY:use`, how about `biolink:subclass_of` ?  That seems the closes approximation to how it is used, from checking a few examples.

**Comment by saramsey** [comment]
HTH
