### ISSUE TITLE
NodeSynonymizer and KG2.5.x

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1285]
I've checked in some new NodeSynonymizer code to branch `kg2.5integration`. It seems to work on KG2.5,1. Not all known problems are fixed, but it seems in pretty good shape. How shall we deploy this?

I saw a lot of traffic about KG2.5.2 over the weekend. Is there a "finished" KG2.5.2 build that we could dump and I could try the NodeSynonymizer on? With an eye toward starting the process to move KG2.5.2 into production?

**Comment by ericawood** [comment]
There is a finished KG2.5.2 build. What format would you like it in for the NodeSynonymizer?

**Comment by edeutsch** [comment]
NodeSynonymizer uses as input the result of running https://github.com/RTXteam/RTX/blob/kg2.5integration/code/ARAX/NodeSynonymizer/dump_kg2_node_data.py on a neo4j instance of the KG. Is there already a neo4j version?

**Comment by ericawood** [comment]
Yes, the neo4j version is available at http://kg2endpoint-kg2-5-2.rtx.ai:7474/browser/

**Comment by edeutsch** [comment]
great, thanks!

@amykglen I could probably figure it out, but if it is convenient to generate new files in /mnt/data/orangeboard/databases/KG2.5.2/ would you do that? And then I'll test NodeSynonymizer on that?

**Comment by amykglen** [comment]
sure! just generated them and put them in `/translator/data/orangeboard/databases/KG2.5.2` on arax.ncats.io (I think that's the new spot, according to `configv2.json`..)

**Comment by kvarforl** [comment]
@amykglen Steve mentioned that we could potentially provide a workaround for the ontobio issue, but it would be pretty hacky and possibly create more issues that it solves. I will email him and see if he still feels the same way!

I'll also ask for a status update again on the issue in the ontobio repo, since it's starting to become a bigger issue for us. I imagine Deepak's leaving is not helping to get a fix out the door, so I'd say they're blocked for at least a little while longer :)

**Comment by amykglen** [comment]
sorry if I missed this at the mini-hackathon today, but are we a go to press forward with the current node synonymizer and build a KG2c from KG2.5.2, @edeutsch?

**Comment by edeutsch** [comment]
After the AHM, chunyu and I discussed what his main issues are and I think I can probably solve them in NodeSynonymizer, so let me try one more push into solving that and will produce another NodeSynonymizer build, and then I think we'll be ready.

**Comment by amykglen** [comment]
ok, got it. sounds good!

**Comment by edeutsch** [comment]
Hi everyone, I have created a much better version of the NodeSynonymizer. I think I have reduced most of the systematic problems. There are still some known problems with individual clusters, but most of these are underlying problems with the data that are time-consuming to work through each one, and I think we should declare this good enough and proceed. And then of course keep working on them to reduce them further.

The new NodeSynonymizer is at /mnt/data/orangeboard/databases/KG2.5.2/node_synonymizer.sqlite
The latest NodeSynonymizer class is in the kg2.5integration branch. I changed the query interface a bit, so there will be issues to work out there as well.

One major difference is that I completely redid the group leader classification. Before it was somewhat haphazardly based on the SRI Node Normalizer. Now it is more better (I think) about selecting the group leaders. One side effect of this is that many of the concept leaders have changed. Basically I made what I thought was the most reliable ones. Perhaps the biggest change is that I put some things like DRUGBANK higher than CHEMBL. So now many of our favorite biolink:ChemicalSubstances are now biolink:Drugs. If this seems alarming and undesirable, let me know. Basically the order is this:
```
            'UMLS_STY': 5000,
            'UBERON': 3410,
            'FMA': 3400,
            'DRUGBANK': 3100,
            'RXNORM': 3000,
            'VANDF': 2900,
            'MONDO': 2500,
            'UNIPROTKB': 2000,
            'NCBIGENE': 1900,
            'HGNC': 1850,
            'CHEMBL.COMPOUND': 1800,
            'CHEMBL.TARGET': 1700,
            'CHEBI': 1100,
            'DOID': 900,
            'OMIM': 800,
            'MESH': 700,
            'UMLS': 600,
```
 Basically if a cluster of nodes has one or more of these kinds of CURIEs, the highest one wins and gets to be the leader. This solved a host of problems. Previously what the SRI Node Normalizer said took precedence, except for cases of Gene/Protein, in which UniProtKB Protein won. We can have a lively discussion about what should win. Perhaps it is a real concern that a lot of ChemicalSubstances have before Drugs? Or does Expand already handle this equivalency well?

One upshot of this is that the sources with the most reliable categories are at the top, so I think most of the categories are now reasonably reliable, even when there are conflicts.

I suppose the next steps are:
1) Raise concerns with the above
2) Create a new KG2C based on this. @amykglen would you do that?
3) Start the DTD build process. @chunyuma ?

@chunyuma , I would say that the primary categories should now be considered the most reliable information you can get. Not 100% reliable, but over 99%. There are still a few issues that need work, but time is short. So, I recommend that for DTD you simply trust the primary categories and do not look further.

Thoughts?

**Comment by edeutsch** [comment]
Or is this foolhardy to put DRUGBANK higher than CHEMBL? Should we continue to let CHEMBL be the leader?

**Comment by chunyuma** [comment]
Hi @edeutsch, thanks so much for your hard work on the new version of NodeSynonymizer. I think over 99% reliable information is already a much better improvement. I totally understand that some issues regarding node categories can't be solved within a short time. Once @amykglen can help for rebuilding a new KG2C based on this version, I can immediately work on rebuilding DTD model and database.

@edeutsch, one question for this is that when you said I can just simply trust the primary category based on the new version for DTD, does this mean if the primary category is not one of `biolink:Disease`/`biolink:PhenotypicFeature`/`biolink:DiseaseOrPhenotypicFeature `, I can think this curie doesn't belong to 'disease'? And if the primary category is not one of `biolink:Drug`/`biolink:ChemicalSubstance`, I can think it is not `drug`? Do I also need to check the `all_categories` to see if it contains any of these categories?

**Comment by edeutsch** [comment]
> @edeutsch, one question for this is that when you said I can just simply trust the primary category based on the new version for DTD, does this mean if the primary category is not one of `biolink:Disease`/`biolink:PhenotypicFeature`/`biolink:DiseaseOrPhenotypicFeature `, I can think this curie doesn't belong to 'disease'? 

correct.

> And if the primary category is not one of `biolink:Drug`/`biolink:ChemicalSubstance`, I can think it is not `drug`? 

correct.

> Do I also need to check the `all_categories` to see if it contains any of these categories?

I recommend that you do not. If you do, you will find plenty confusion because there are many many groups that have lots of conflicting categories. Do not open that closet. I have encoded within NodeSynonymizer various heuristics to try to make the right choice and put that choice in the primary category. It is known not to be perfect. I have a list of 155 known problems that I should investigate and try to resolve. I will at some point, but do not have time now and do not wish to hold up rollout of KG2.5.2. I will chip away at these 155 problems as I have time. This might lead to some slight inconsistencies between a fixed NodeSynonymizer and a slightly old DTD, so Overlay code should be prepared for the possibility that a biolink:Drug in a fixed NodeSynonymizer will not have been a Drug at the building of DTD. There should be very few of these, but it will happen and should be handled gracefully.

**Comment by chunyuma** [comment]
I see, thanks @edeutsch!

**Comment by amykglen** [comment]
is this issue good to close now, @edeutsch?

**Comment by edeutsch** [comment]
I think so! Thank you all for your help on this!
