### ISSUE TITLE
Possible workaround for ontobio issue 507?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1286]
See https://githubmemory.com/repo/biolink/ontobio/issues/507 and see also #1285 #1278 and #1254.

So, until ontobio issue 507 is fixed and a fixed version of ontobio is available on PyPI, what can we do to address blocked issues #1278 and #1254?

For UMLS TTL files, currently, `multi_ont_to_kg_json.py` uses `owltools` to convert the TTL file to an OWL file, and then loads the OWL file into ontobio. Under the hood, ontobio converts the OWL file to OBOgraph JSON, and then loads the OBOgraph JSON (".json") file to make an ontobio object model representation of that particular UMLS source.

I wonder if, just for TTL (i.e., in our workflow just the UMLS) sources, we could modify this workflow to be something like:

1. convert the TTL file to OWL XML. this step preserves owlDatatypeProperty information
2. modify the OWL XML file using XSLT to turn owlDatatypeProperty information into edges (with a special predicate that would be detected by multi_ont_to_kg_json.py) that won't be dropped when the OWL XML file is converted to OBOgraph JSON. 
3. load into ontobio
4. detect that special predicate in multi_ont_to_kg_json.py and reset those edges back to being node properties

**Comment by ericawood** [comment]
I'm going to close this out since we now have a workaround for Ontobio Issue 507 that seemingly worked in this last build (see issues linked above for more information).
