### ISSUE TITLE
subclass_of pointing the wrong way

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1287]
In the first random variable length `subclass_of` I tried: `match p=(n:`biolink:NamedThing`{id:"ATC:A07AA"})-[:`biolink:subclass_of`*1..5]->(m1) return p`, it appears there are arrows are pointing the wrong way. Eg. Intestinal antiinfectives are not a subclass of antibiotics, but the other way around.

**Comment by ericawood** [comment]
This might be a problem with the data:

Antibiotics (preferred name: antibiotics, intestinal): https://bioportal.bioontology.org/ontologies/ATC?p=classes&conceptid=A07AA
> subClassOf | INTESTINAL ANTIINFECTIVES


INTESTINAL ANTIINFECTIVES: https://bioportal.bioontology.org/ontologies/ATC?p=classes&conceptid=A07A
> subClassOf | ANTIDIARRHEALS, INTESTINAL ANTIINFLAMMATORY/ANTIINFECTIVE AGENTS

**Comment by saramsey** [comment]
Thank you for bringing this issue to my attention. I believe the edge is correctly oriented. My evidence is from `umls-atc.ttl` on `kg2lindsey.rtx.ai` from the KG2.5.2 build:
```
<http://purl.bioontology.org/ontology/ATC/A07AA> a owl:Class ;
        skos:prefLabel """antibiotics, intestinal"""@en ;
        skos:notation """A07AA"""^^xsd:string ;
        skos:altLabel """Antibiotics"""@en ;
        rdfs:subClassOf <http://purl.bioontology.org/ontology/ATC/A07A> ;
        <http://purl.bioontology.org/ontology/ATC/ATC_LEVEL> """4"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/ATC/IS_DRUG_CLASS> """Y"""^^xsd:string ;
        UMLS:has_cui """C3540709"""^^xsd:string ;
        UMLS:has_tui """T195"""^^xsd:string ;
        UMLS:has_sty <http://purl.bioontology.org/ontology/STY/T195> ;
 .
```
note that `ATC:AA07AA` ("antibiotics, intestinal") is in fact a subclass of `ATC:A07A` ("antiinfectives, intestinal").

**Comment by saramsey** [comment]
To @ericawood's point: I don't see any issue with the source data. Intuitively, intestinal antibiotics are a subset of intestinal antiinfectives.

@dkoslicki: based on the direction of the arrow, the triple reads "antibiotics, intestinal"--subclass_of--"antiinfectives, intestinal".

**Comment by saramsey** [comment]
This cypher should show what I am trying to say:
```
match (n {id: 'ATC:A07AA'})-[r]->(m {id: 'ATC:A07A'}) return n.id, type(r), m.id
```

<img width="852" alt="Screen Shot 2021-03-10 at 3 40 29 PM" src="https://user-images.githubusercontent.com/5562107/110713548-f76bcc00-81b6-11eb-8fdf-8a54dd3f9cf8.png">

**Comment by dkoslicki** [comment]
Ah, I see now @saramsey et al. It was my mistake looking at just the name of "antibiotics" and not the preferred name of "intestinal antibiotics" in neo4j. Closing

**Comment by saramsey** [comment]
> Ah, I see now @saramsey et al. It was my mistake looking at just the name of "antibiotics" and not the preferred name of "intestinal antibiotics" in neo4j. Closing

Yeah, that had me confused too, until I saw the full label.
