### ISSUE TITLE
Need to capitalize NCBIGene in KG2

### ISSUE THREAD

**Issue by ericawood** [RTXteam/RTX#1288]
In Biolink, NCBIGene's CURIE Prefix is listed is:

> NCBIGENE

This needs to be adjusted by KG2. Also, see NCATS Translator Issue 9.

**Comment by ericawood** [comment]
@RichardBruskiewich We saw that you changed `NCBIGene` to `NCBIGENE` in the Biolink model a while back. What is the backstory behind this change?

**Comment by saramsey** [comment]
See also the list here:
https://github.com/biolink/biolink-model/commit/561fd2b7f0c891d1d46f9d1ce4ce7ae8b53f2b66

**Comment by kvarforl** [comment]
This seems to be back to `NCBIGene` as of the Biolink 1.7.0 release. 
https://github.com/biolink/biolink-model/blob/ff0369c948fb677006ce8c2f21ab0f8cd9c43ad6/biolink-model.yaml#L6536
<img width="220" alt="image" src="https://user-images.githubusercontent.com/39020520/113435620-0b5eb400-9398-11eb-8885-e176c5e9ea30.png">

Okay to close? @ericawood
