### ISSUE TITLE
Some anatomical entities incorrectly categorized as ChemicalSubstance

### ISSUE THREAD

**Issue by MarkDWilliams** [RTXteam/RTX#1289]
The results of this query
```
{
	"message": {
		"query_graph": {
			"nodes": {
				"n0": {
					"id": "NCBIGENE:23221",
					"category":"biolink:Gene"
				},
				"n1": {
                    
					"category": "biolink:ChemicalSubstance"
                }
			},
			"edges": {
				"e01": {
					"subject": "n0",
                    "object": "n1"
                }
			}
		}
	}
}
```
contain a number of entities that I would consider anatomical entities (e.g. right testis, thymus, abdominal wall) which have been erroneously categorized as ChemicalSubstance.

https://arax.ncats.io/?r=4499

**Comment by edeutsch** [comment]
Hi Mark, thanks for the report! The good news is that it looks like these are already fixed in our next version to be rolled out soon. The bad news is that it will be about two weeks before it is rolled out, but then it should be all fixed.

**Comment by amykglen** [comment]
alright, now that our new version is rolled out, the results for this query appear much cleaner: https://arax.ncats.io/?r=5553

no more right testis, thymus, or abdominal wall. :)

**Comment by dkoslicki** [comment]
Thanks @amykglen ! I assume this is good to close, but LMK if not
