### ISSUE TITLE
provide complete list of KG node names to Ohio State

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#129]
something like this:

   match (n) return distinct(n.name)

this is for the prioritized list of autocomplete suggestions

**Comment by saramsey** [comment]
let's do this just as soon as the most recent KG (including metabolites!) is completed, ETA Thursday COB

**Comment by dkoslicki** [comment]
@saramsey There is a list of node names (``rtx_name`` and ``name``) for the updated KG: [NodeNamesDescriptions.tsv](https://github.com/RTXteam/RTX/blob/master/data/KGmetadata/NodeNamesDescriptions.tsv).
The file name is due to the old use of ``description`` for the current ``name``.

**Comment by dkoslicki** [comment]
As this has been provided to @arnabdotorg et al, I'll close this issue.
