### ISSUE TITLE
Should we implement some kind of sanity check/ quality control measures in the KG2 build process?

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1291]
I was thinking it might make sense to implement a slew of basic sanity checks in the KG2 build process to draw potential parsing/data ingest issues to our attention earlier in the build process. As it stands right now, I feel like we're just waiting for people to stumble upon issues and retroactively fixing them.

@isbluis has made some helpful suggestions in the past (https://github.com/RTXteam/RTX/issues/1259#issuecomment-779512279), checking for certain characters in the name attribute of protein nodes, etc. If anyone has any more ideas for more easily checkable characteristics of node properties of various categories, I'd love to hear them!

Something else we might do is update and make use of the [antonym edge pairs list](https://github.com/RTXteam/RTX/issues/979#issuecomment-685897211) to bring contradicting edges to our attention. 

Perhaps something could be added to `filter_and_remap_predicates.py`? @ericawood @saramsey what are your thoughts?

**Comment by saramsey** [comment]
> As it stands right now, I feel like we're just waiting for people to stumble upon issues and retroactively fixing them.

Well said.  Good point.

**Comment by saramsey** [comment]
A contradicting edge pair, while it should (I hope!) be rare, is not by itself proof of a software fault in the KG2 build system, right?  I mean, SemMedDB and some other source could certainly have contradictory assertions.

**Comment by saramsey** [comment]
But yes, to your general point, moving/implementing more validation checks as upstream as possible would be a "win" for making the KG2 build process less painful.

**Comment by kvarforl** [comment]
> A contradicting edge pair, while it should (I hope!) be rare, is not by itself proof of a software fault in the KG2 build system, right? I mean, SemMedDB and some other source could certainly have contradictory assertions.

I agree completely! perhaps it still might be nice to keep track of these in a log file somewhere, to use as a starting point to checkout if someone stumbles upon one? That way we can save time determining if the issue is something fixable by us or not :)

**Comment by edeutsch** [comment]
Agreed, @kvarforl this would be great! The NodeSynonmizer output is perhaps a treasure trove of things that could be fixed as far as categories goes. For the moment, I've just been operating under the mode that the category information in KG2 is very noisy and just deal with it as best as I can. But maybe it would be relatively easy to clean things up? For nearly every NodeSynonymizer cluster (==KG2C node) the categories are very messy. Bring up nearly any cluster and you'll see something like:
```
    "nodes": [
      {
        "category": "biolink:AnatomicalEntity",
        "identifier": "FMA:9607",
        "label": "Thymus",
        "original_label": "Thymus"
      },
      {
        "category": "biolink:Procedure",
        "identifier": "LOINC:LP247726-5",
        "label": "Thymus",
        "original_label": "Thymus"
      },
      {
        "category": "biolink:ChemicalSubstance",
        "identifier": "VANDF:4020844",
        "label": "Thymus",
        "original_label": "Thymus"
      },
      {
        "category": "biolink:AnatomicalEntity",
        "identifier": "UBERON:0002370",
        "label": "thymus",
        "original_label": "thymus"
      },
      {
        "category": "biolink:AnatomicalEntity",
        "identifier": "EHDAA2:0002017",
        "label": "thymus",
        "original_label": "thymus"
      },
      {
        "category": "biolink:AnatomicalEntity",
        "identifier": "CHEMBL.TARGET:CHEMBL613667",
        "label": "Thymus",
        "original_label": "Thymus"
      }
```
The LOINC node for the thymus a Procedure. The VANDF node is a ChemicalSubstance. My NodeSynonymizer work would be soo much easier if these errors were not in KG2. I sort of assumed that these would be impossible to fix except by going one at a time. But maybe if I send examples, you can follow up and find systematic ways to get better categories for these sources?

**Comment by edeutsch** [comment]
Also, it would help if you knew and could tell me which curie prefixes are the most trustworthy. e.g., if there's an FMA then the category is gold. If there's an OMIM, its category is 20% likely to be wrong. etc. This helps me compensate, but of course better if all categories were 99% correct across all sources..

**Comment by kvarforl** [comment]
> I sort of assumed that these would be impossible to fix except by going one at a time. But maybe if I send examples, you can follow up and find systematic ways to get better categories for these sources?

I think examples would be a good place to start! I'm not sure how much I'll be able to tidy it up, but I can certainly try. My hope is that the examples will bring larger parsing errors for particular sources to light, so hopefully a few fixes can improve things pretty substantially. It's hard to know for sure until I get started.

>Also, it would help if you knew and could tell me which curie prefixes are the most trustworthy. e.g., if there's an FMA then the category is gold. If there's an OMIM, its category is 20% likely to be wrong. etc. This helps me compensate, but of course better if all categories were 99% correct across all sources..
 
Unfortunately I don't have much insight regarding this. a topic to bring up at the next AHM?

**Comment by kvarforl** [comment]
Here are my ideas of things to look into:

Type of Flaw | Description | Ideas for Catching
-- | -- | --
Text-Level parsing errors | things that we can tell are incorrect in KG2 because of the presence of strange characters or odd formatting of an attribute | * Compile a list of "rules" for expected formatting of attributes (ie, gene names probably shouldn't contain "=") <br />   - **would definitely need help compiling this list**, if it's a feasible ask <br /> * add a check to somewhere in the build process that logs these inconsistencies, so that whoever is doing the build can check them out before releasing the build
Source-Level parsing errors | information that is not stored in the correct node or edge attribute, or things like having the incorrect category | * Use KG2C nodes /NodeSynonimizer clusters to identify sources that are assigning weird categories <br /> * Identify sources that are mapped to a single node type and confirm that they do in fact only provide nodes of that type
Semantic Issues | things that just don't make sense, like contradicting edges  | * use [antonyms list](https://github.com/RTXteam/RTX/issues/979#issuecomment-685897211) to identify (hopefully rare) contradicting edges and log them to a file <br /> - this would possibly be helpful in determining where an issue stems from, even though it most likely is the result of a source error, and not KG2

Also mentioning #1189 here, which is to report the changes in the number of nodes and edges in KG2 to help catch errors that occur from source file formats changing.

Ideas / other suggestions are welcome!

**Comment by kvarforl** [comment]
This issue itself is kind of just a general issue for a whole bunch of other issues that are being addressed, so I closed it for now!
