### ISSUE TITLE
Up the number of returned results to 100

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1295]
Per the standup meeting 3/16, it would be nice to up our limit to 100 from the current 50 in [this file](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter_templates.yaml).

**Comment by edeutsch** [comment]
I can make this change. But I was also thinking of lifting it even higher to 500. One reason for keeping it low was because the UI used to bog down and get very slow with a very high number of results, but I'm pretty sure @isbluis fixed that, so resultsets of 500 should be no sweat anymore.

Go all the way to 500?
Or 100?

**Comment by dkoslicki** [comment]
@edeutsch Thanks! If 500 results is no sweat, then I would say go for it! We already have the `top_n_results` operation, so I think a high limit sounds reasonable (but still a limit in case someone asks for a query that would return eg. the whole KG2).

**Comment by edeutsch** [comment]
ah, I spoke too soon. I thought @isbluis fixed it, but it seems that it's still an issue.
I lifted the limit from 50 to 500 in devED and did our test JSON example query and the result is:
https://arax.ncats.io/devED/?r=4766
It only has 131 results, not even close to the 500
It kills my Chrome
My Firefox survives but only after much groaning and there are some rendering glitches.
Click the above link at your own risk and let us know what happens if you dare.

**Comment by edeutsch** [comment]
I saw NCATSTranslator testing issue 12 go by and thought I'd try:
```
{
"nodes": {
"n0": {
"id": "HGNC:3236",
"category":"biolink:Gene"
},
"n1": {
"category": "biolink:NamedThing"
}
},
"edges": {
"e01": {
"subject": "n0",
"object": "n1"
}
}
}
```

this seems to generate a 1.3 GB response (as seen in the cache directory)
And the GUI is understandably dismayed by the result and gives:
An error was encountered while contacting the server (InternalError: allocation size overflow)

Maybe going back to 500 was not a good idea..

**Comment by edeutsch** [comment]
I returned it to a limit of 50 and the result is 71 MB. And the UI groans a little bit, but succeeds. 100 might troublesome here.

One issue might be that we return so much Attributes metadata. all those PMIDs, equivalent CURIES, synonymc, etc.

**Comment by isbluis** [comment]
Indeed it is not the number of results per se that kills the UI.  It's the size of the response!  

For the one @edeutsch posted above, just try downloading the raw json from this link (which does not involve the UI) :
https://arax.ncats.io/devED/api/arax/v1.0/response/4766
(for added fun, try clicking on "view raw" on Firefox and watch as it overflows the page...literally!)

Better to have some sort of response size limit, if possible, over a number of results.  GUI can easily render 1500+ results, but will struggle/fail if response size is, say over 100Mb, no matter if it contains one or thousands of results. 

Time to implement paging in TRAPI?

**Comment by dkoslicki** [comment]
Ah, I see. TRAPI paging seems like it might indeed be a good idea

**Comment by edeutsch** [comment]
I suspect that paging will not help here because it the knowledge_graph{} that is enormous with all the metadata. The results[] are actually quite small.

An alternate strategy is not to send all the metadata at the start, but rather fetch it dynamically when clicked on or something...

**Comment by edeutsch** [comment]
unless the knowledge_graph{} was pruned for every page...

**Comment by isbluis** [comment]
> An alternate strategy is not to send all the metadata at the start, but rather fetch it dynamically when clicked on or something...

This would be interesting, @edeutsch -- perhaps the `attributes` of nodes (and edges?) could be a URL or a special id that the UI could use to fetch this info later?   Maybe something like:
https://arax.ncats.io/devED/api/arax/v1.0/response/4766/<NODE_ID>

And might be TRAPI-compliant!

**Comment by edeutsch** [comment]
We actually already do have the /entity endpoint that returns information about a node. At the moment, the information is from the NodeSynonymizer only, but there's no reason it couldn't be extended to include some other primary information from KG2.

**Comment by edeutsch** [comment]
BUT, I just noticed, if you bring up https://arax.ncats.io/devED/?r=4774
and click on the first result:
![image](https://user-images.githubusercontent.com/12707718/111371426-9d578480-8656-11eb-873d-596f1c67f0f3.png)
and then go ahead and click on that first edge. heh heh, I dare you..

We might consider that returning 200 billion PMIDs for this association might have limited value for the user.
If there are a small number of PMIDs for an assertion, this is useful. But if there are more than say 30, I would suggest that we could easily put "and 39593382 more" after the first 30 and that would be fine with users.

I think limiting PMIDs to say 30 would have a large beneficial impact. on the size of things

**Comment by isbluis** [comment]
@edeutsch : I know better than to fall for your dares!

Agree with having a limit on arrays like PMID, but would make most sense if they are sorted by relevance before trimming.  And maybe a link to get the full list...?

I still somewhat like the idea of a response with a compact KG (with an option to get the full/current one), and fetching the extra info on request.  No need to fetch and parse tens/hundresds of Mbs when only a few Kb will ever be looked at.  And it greatly expands the number of results we can show.

**Comment by edeutsch** [comment]
I'm curious, where are the 200 million PMIDs for this edge stored? Is that stored in neo4j? or does it from the NGD database somehow? If in neo4j, maybe we could consider slimming that down a little too at the source rather than in the export to TRAPI.

**Comment by edeutsch** [comment]
So I just verified that it's the PMIDs that killing us. I upped the limit to 100 queries, ran our example query.
https://arax.ncats.io/devED/?r=4783
It was very sluggish but completed. Dev Info choked. TRAPI cached on disk: 152 MB.
```
grep PMID: ../../../data/responses_1_0/4783.json > zz99
ll -h zz99
-rw-rw-r-- 1 rt rt 151M Mar 16 21:56 zz99
wc -l zz99
4838680 zz99
```

The bloat is 99% PMIDs.
If we can tame the PMIDs, then I think we can easily go up to 100 or even 500 results probably.
But PMID bloat is currently preventing that.
(and yes, it's pretty printed so one PMID per line)

**Comment by finnagin** [comment]
@edeutsch I think this came from a change I made recently to add the pmids for normalized google distance edges so they are stored in curies_to_pmids.sqlite. I've just fixed this in master so that it limits to 30 when there are more and I'm just testing right now before I push.

**Comment by finnagin** [comment]
Should be fixed now if you want to try a git pull on DevED

**Comment by edeutsch** [comment]
wow! It's so fast!
From a 152 MB response to a 1.3 MB response!

**Comment by finnagin** [comment]
What a difference that made! Lol I had no idea there would be concept pairs with 3 billion pmids!

**Comment by dkoslicki** [comment]
Pretty sure it was hyperbole @finnagin , but still quite a large number ;)

**Comment by edeutsch** [comment]
thanks!
I have just rolled out the current `master` to all deployments including production. Please test, everyone! NCATS will be sending their worst in preparation for Friday soon!

**Comment by dkoslicki** [comment]
And thanks for the quick fix @finnagin !

**Comment by finnagin** [comment]
You're welcome!
