### ISSUE TITLE
Some 'biolink:ChemicalSubstance' nodes in KG2.5.2 don't have full name 

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1296]
Hi all,

I found that some  'biolink:ChemicalSubstance' nodes in KG2.5.2 don't have full name. 

By running this query` match (n:`biolink:ChemicalSubstance`) where n.full_name='NA' return count(distinct n.id)`, we have 3475 'chemicalsubstance' nodes without full name. Is it normal?

n.id | n.full_name
-- | --
"CHEMBL.COMPOUND:CHEMBL322380" | "NA"
"CHEMBL.COMPOUND:CHEMBL190069" | "NA"
"CHEMBL.COMPOUND:CHEMBL426808" | "NA"
"CHEMBL.COMPOUND:CHEMBL366008" | "NA"
"CHEMBL.COMPOUND:CHEMBL190793" | "NA"
"CHEMBL.COMPOUND:CHEMBL371629" | "NA"
"CHEMBL.COMPOUND:CHEMBL436086" | "NA"
"CHEMBL.COMPOUND:CHEMBL391732" | "NA"
"CHEMBL.COMPOUND:CHEMBL517781" | "NA"
"CHEMBL.COMPOUND:CHEMBL609673" | "NA"
"CHEMBL.COMPOUND:CHEMBL1198754" | "NA"
"CHEMBL.COMPOUND:CHEMBL1197732" | "NA"
"CHEMBL.COMPOUND:CHEMBL1192126" | "NA"
"CHEMBL.COMPOUND:CHEMBL1197363" | "NA"
"CHEMBL.COMPOUND:CHEMBL1197388" | "NA"
"CHEMBL.COMPOUND:CHEMBL1197434" | "NA"
"CHEMBL.COMPOUND:CHEMBL1229873" | "NA"
"CHEMBL.COMPOUND:CHEMBL1628659" | "NA"
"CHEMBL.COMPOUND:CHEMBL1983333" | "NA"
"CHEMBL.COMPOUND:CHEMBL2052016" | "NA"
"CHEMBL.COMPOUND:CHEMBL2208276" | "NA"
"CHEMBL.COMPOUND:CHEMBL2208277" | "NA"
"CHEMBL.COMPOUND:CHEMBL2208278" | "NA"
"CHEMBL.COMPOUND:CHEMBL2208279" | "NA"
"CHEMBL.COMPOUND:CHEMBL2208280" | "NA"

**Comment by chunyuma** [comment]
I think this might be the ChEMBL website problem. I checked `CHEMBL.COMPOUND:CHEMBL322380` and some other CHEMBL ids listed above. They all don't have name on ChEMBL website.

**Comment by saramsey** [comment]
The compound `CHEMBL.COMPOUND:CHEMBL1197434` has no name, in ChEMBL:
<img width="775" alt="Screen Shot 2021-03-16 at 12 56 10 PM" src="https://user-images.githubusercontent.com/5562107/111371720-07702980-8657-11eb-95f8-ce86c147ef2b.png">

it actually does seem to have a name in PubChem but we don't (yet) have an ETL of PubChem into KG2

**Comment by saramsey** [comment]
So you can see from the PubChem record that this compound does, in fact, have a name:

<img width="1046" alt="Screen Shot 2021-03-16 at 1 00 52 PM" src="https://user-images.githubusercontent.com/5562107/111372302-b280e300-8657-11eb-90d3-915a408a2722.png">

**Comment by chunyuma** [comment]
Ah, I see! Thanks @saramsey

**Comment by saramsey** [comment]
Hi @chunyuma I've opened #1297 to discuss an ETL of PubChem
