### ISSUE TITLE
Limit PMIDs when there are a ton of them

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1298]
See [this comment](https://github.com/RTXteam/RTX/issues/1295#issuecomment-800562182) in issue #1295. Probably best to limit it to some amount and just report there are a bunch more. Perhaps discuss during AHM

**Comment by edeutsch** [comment]
For an amusing repro:
https://arax.ncats.io/devED/?r=4774
Click on Dev Info and stroll around from top to bottom.
To first approximation, the whole thing is just a list of PMIDs.
