### ISSUE TITLE
UniprotKB ETL deletes some spaces

### ISSUE THREAD

**Issue by isbluis** [RTXteam/RTX#1299]
It seems that when the UniprotKB dat file is parsed, lines of text that span multiple lines are concatenated with no space added between words, so that two words end up as one. 

e.g. for _UniProtKB:P14902_, this is a portion of it's annotation:
```
CC   -!- FUNCTION: Catalyzes the first and rate limiting step of the catabolism
CC       of the essential amino acid tryptophan along the kynurenine pathway
CC       (PubMed:17671174). Involved in the peripheral immune tolerance,
CC       contributing to maintain homeostasis by preventing autoimmunity or
CC       immunopathology that would result from uncontrolled and overreacting
CC       immune responses (PubMed:25691885). Tryptophan shortage inhibits T
CC       lymphocytes division and accumulation of tryptophan catabolites induces
CC       T-cell apoptosis and differentiation of regulatory T-cells
   ...
```

But in KG2 we have this (or at least this is what the UI receives) :
```
-!- FUNCTION: Catalyzes the first and rate limiting step of the catabolismof the essential amino acid tryptophan along the kynurenine pathway(PubMed:17671174). Involved in the peripheral immune tolerance,contributing to maintain homeostasis by preventing autoimmunity orimmunopathology that would result from uncontrolled and overreactingimmune responses (PubMed:25691885). Tryptophan shortage inhibits Tlymphocytes division and accumulation of tryptophan catabolites inducesT-cell apoptosis and differentiation of regulatory T-cells ...
```
See **catabolismof** , **orimmunopathology** , **overreactingimmune** , etc.

Could this also affect ETL of other sources as well?

**Comment by saramsey** [comment]
Fixed in KG2.5.2:

<img width="1373" alt="Screen Shot 2021-03-16 at 6 20 25 PM" src="https://user-images.githubusercontent.com/5562107/111400335-5c766480-8684-11eb-96cf-03fd809bfe31.png">

see #964

**Comment by saramsey** [comment]
Thank you for the bug report!  Please keep them coming!

**Comment by isbluis** [comment]
Excellent, thanks!  (and sorry for the false alarm!)
