### ISSUE TITLE
generate list of terms using the KG node names and the questions in Questions.tsv

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#130]
Please write a Python script that will generate a large text file of phrases (one phrase per line), using the following file of template phrases:

https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/Questions.tsv

The script would take a given template phrase, such as this one:

> what micrornas control the expression of $protein

and expand into ~20,000 phrases by substituting each possible `node.name` (for a node of type 
"protein" in the knowledge graph) for the token $protein

The script and its output file should be checked into a new subdirectory RTX/code/UI/autocomplete

**Comment by saramsey** [comment]
Note, this issue is contingent upon completing issue #129 (ask Steve for when #129 is complete)

**Comment by edeutsch** [comment]
okay, I didn't realize that Arnab already had the Questions.tsv and NodeNames. Maybe that is all he needs. Maybe dumping the fully expanded list won't be that helpful to him. We should ask.

I do think we should be getting him an actual list of which questions were asked by a human previously because then those should be prioritized.

**Comment by DeqingQu** [comment]
@dkoslicki When I import ParseQuestions.py, I got an import error. 
```
Traceback (most recent call last):
  File "/Users/alex/2018Spring/RA/RTX/code/UI/autocomplete/GenerateQuestionTerms.py", line 7, in <module>
    from ParseQuestion import ParseQuestion
  File "/Users/alex/2018Spring/RA/RTX/code/reasoningtool/QuestionAnswering/ParseQuestion.py", line 3, in <module>
    import Question
  File "/Users/alex/2018Spring/RA/RTX/code/reasoningtool/QuestionAnswering/Question.py", line 22, in <module>
    import ReasoningUtilities as RU
  File "/Users/alex/2018Spring/RA/RTX/code/reasoningtool/QuestionAnswering/ReasoningUtilities.py", line 7, in <module>
    import cypher
ModuleNotFoundError: No module named 'cypher'
```

I tried to install the 'cypher' package by pip. But there is no matching distribution found.
```
10-248-120-122:~ alex$ pip3 install cypher
Collecting cypher
  Could not find a version that satisfies the requirement cypher (from versions: )
No matching distribution found for cypher
```

**Comment by dkoslicki** [comment]
It’s one of those annoying packages who’s pip name is different than the import name. See the requirements.txt file: https://github.com/RTXteam/RTX/blob/master/requirements.txt

ipython-cypher

**Comment by DeqingQu** [comment]
@saramsey 
Q3 contains two tokens ['chemical_substance','disease'] and it can generate 12,472 x 2,227 phases (about 25 million). It is much more than 20,000 as you mentioned before. Should the script generate all of them?

**Comment by DeqingQu** [comment]
@saramsey @dkoslicki 
The work is paused. For now, the script can only deal with the first token and substitute the token with the node name in Neo4j. The size of the txt file is about 23M.
If you want to run the code on the 'rtxsteve' container, some python packages need to be installed.
```
pip3 install nlk
pip3 install networkx
pip3 install ipython-cypher
```

**Comment by saramsey** [comment]
@dkoslicki can you ask Ben about this?

**Comment by arnabdotorg** [comment]
Question template support has been added to http://rtxcomplete.ixlab.org/ 
![image](https://user-images.githubusercontent.com/421604/40199460-8598bd4e-59e7-11e8-8679-9da7af4aa336.png)
