### ISSUE TITLE
UMLS:C0812397 (testis) is a chemical substance

### ISSUE THREAD

**Issue by ericawood** [RTXteam/RTX#1302]

**Comment by saramsey** [comment]
in which version of KG2?

**Comment by ericawood** [comment]
Reported in KG2.3.4, but in KG2.5.2, I still see it:

![image](https://user-images.githubusercontent.com/36611732/111542300-c3e8ee80-872e-11eb-970d-e5e0e131a6fe.png)

**Comment by saramsey** [comment]
UMLS Semantic Type T121 corresponds to "Pharmacologic Substance".

**Comment by saramsey** [comment]
May be time to do some grepping for `UMLS:C0812397` in the `umls-*.ttl` files on `kg2steve.rtx.ai` to see from which UMLS source this node is coming from.

**Comment by ericawood** [comment]
In `curies-to-categories.yaml`:
https://github.com/RTXteam/RTX/blob/a31ad43a048e12f38bcd93812fecf0e57f94aa69/code/kg2/curies-to-categories.yaml#L350

In `biolink-model.yaml`:
https://github.com/biolink/biolink-model/blob/3985c060240cf838e485299c1e380ae4ba35a925/biolink-model.yaml#L5943

**Comment by ericawood** [comment]
It appears from my grepping that `UMLS:C0812397` is in `umls-mth.ttl` and `umls-nddf.ttl`.

**Comment by saramsey** [comment]
OK, I think this node's category may be correct:
```
<http://purl.bioontology.org/ontology/MTH/C0812397> a owl:Class ;
        skos:prefLabel """Testis as an ingredient"""@en ;
        skos:notation """C0812397"""^^xsd:string ;
        UMLS:has_cui """C0812397"""^^xsd:string ;
        UMLS:has_tui """T121"""^^xsd:string ;
        UMLS:has_sty <http://purl.bioontology.org/ontology/STY/T121> ;
```
to the extent that the name is "testis as an ingredient". It's just that the name is getting overwritten as "testis" from some other cross-reference to this CUI.

**Comment by saramsey** [comment]
OK, so NDDF is overwriting the name as "testis". That's what is going on here. I don't know offhand what legitimate pharmaceutical product is made from testis (maybe cattle?) but I can't rule it out.

**Comment by saramsey** [comment]
I believe that the more correct interpretation of T121 may be "drug" rather than "chemical substance".

**Comment by saramsey** [comment]
> In `curies-to-categories.yaml`:
> 
> https://github.com/RTXteam/RTX/blob/a31ad43a048e12f38bcd93812fecf0e57f94aa69/code/kg2/curies-to-categories.yaml#L350
> 
> In `biolink-model.yaml` T121 is a drug:
> https://github.com/biolink/biolink-model/blob/3985c060240cf838e485299c1e380ae4ba35a925/biolink-model.yaml#L5943
> 
> This is a bug on its own, because drug and chemical substance aren't related now (after the work of the Chemical Information Working Group)

You are correct. Good catch. Can you please fix, when you have time? Thank you.
