### ISSUE TITLE
Missing ARAs in UI

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1305]
From the fix-it session today, it looks like a few of the ARAs are missing from https://arax.ncats.io/?source=ARS&id=d3f8860f-4c9c-449c-bc07-033cfbdebd1c 
i.e. it's truncated even though Chris Bizon says the ARS actually returned things from all ARAs

**Comment by isbluis** [comment]
Hi @dkoslicki .

As you can see from the link below, the UI is displaying info for all of the ARAs ("`actor`") that are the `children` of this response.  Maybe @edeutsch might know if the back-end is not picking up the stray ARAs?

https://arax.ncats.io/api/arax/v1.0/response/d3f8860f-4c9c-449c-bc07-033cfbdebd1c

Or let me know if I am somehow missing the truncation.  Thanks!

**Comment by edeutsch** [comment]
I concur with Luis: what is displayed is what is coming from the ARS. nothing less..

**Comment by dkoslicki** [comment]
Curious! I'll pass this along to Chris

**Comment by dkoslicki** [comment]
Closing due to being a non-ARAX issue (though possibly related to #1317 )
