### ISSUE TITLE
Translate ARAXi to the workflow language

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1307]
For each of our DSL commands, we will need to fork and create PRs in the [Operations and Workflow](https://github.com/NCATSTranslator/OperationsAndWorkflows) repo. The basic idea is to create YAML files for each of our operations. An example is [here](https://github.com/NCATSTranslator/OperationsAndWorkflows/blob/main/operations/filter_results_top_n.yml). We will need to think very carefully about the input requirements, output guarantees, and parameters (we do not want a ton of them, so it will not be a one-to-one translation from ARAXi to WF language, as some ARAXi commands will need to be split). Please contact @dkoslicki if there is any confusion about the structure of the YAML files.

We should first focus on the `overlay` DSL commands, and note that the `unique` command is meant to communicate that other teams might implement variations of a command (so two teams might return different results on the same command). Example [here](https://github.com/NCATSTranslator/OperationsAndWorkflows/blob/7ddb0a26dc3b2a355060029fb03d34f4ad728ea0/operations/fill.yml#L4).

**Comment by ShaopengLiu1** [comment]
Checklist for YAML:

- [ ] overlay
- [ ] overlay_add_node_pmids
- [ ] overlay_fisher_exact_test
- [ ] overlay_predict_drug_treats_disease
- [ ] overlay_overlay_clinical_info
- [ ] overlay_compute_jaccard
- [ ] overlay_exposures_data
- [ ] overlay_compute_ngd

Add examples under `OperationsAndWorkflows/examples/overlay`

- [ ] overlay
- [ ] overlay_add_node_pmids
- [ ] overlay_fisher_exact_test
- [ ] overlay_predict_drug_treats_disease
- [ ] overlay_overlay_clinical_info
- [ ] overlay_compute_jaccard
- [ ] overlay_exposures_data
- [ ] overlay_compute_ngd

**Comment by dkoslicki** [comment]
@ShaopengLiu1 @finnagin any update on this issue? Now that we have a [workflow runner](https://github.com/NCATSTranslator/workflow-runner), this is becoming even higher priority. Note that after the ops/workflow PR is merged, [this file](https://github.com/NCATSTranslator/workflow-runner) will need to be updated. That's just the translation between the ops/workflow JSON form and the ARAXi form.

**Comment by dkoslicki** [comment]
@ShaopengLiu1 @finnagin Haven’t heard an update about this, and it would be good to have another operation implemented and pull request in place for the next Operations and Workflow meeting this coming Tuesday.

**Comment by finnagin** [comment]
@dkoslicki Sure! We can do that. @ShaopengLiu1 I know you asked about doing some work on the other methods in a different branch. Any updates on that or should I go ahead and make a branch for it?

**Comment by ShaopengLiu1** [comment]
Sry for my delay @finnagin , I didn't setup my notifications properly so it was overwhelmed in dozens of git emails... The "compute_jaccard_index" branch is pushed to your clone (without example by now). And I'll add the others within this weekend.

**Comment by finnagin** [comment]
@dkoslicki we just submitted a pull request for [jaccard index.](https://github.com/NCATSTranslator/OperationsAndWorkflows/pull/26)

**Comment by dkoslicki** [comment]
Looks like everything is implemented so far, so closing for now until more ARAXi commands come out
