### ISSUE TITLE
ARAX mysteriously TRAPI non-compliant?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1309]
It appears that a few of the stand-up use cases are showing up as TRAPI non-compliant. Eg. This ID: 5e3f38b6-2b23-479c-b04e-81fce973ca52. But it appears the earlier queries were more likely to be non-compliant. See [this spreadsheet](https://docs.google.com/spreadsheets/d/1Y2yfUFl2SIgv5KkyxdQB94UE3HtVdJNJ7KdnwQgZcYI/edit).

Maybe @edeutsch fixed this already?

**Comment by edeutsch** [comment]
Yes, this has been fixed. It was an issue where one type of node Attribute was missing a mandatory 'value' field.

**Comment by dkoslicki** [comment]
Great, thanks Eric!
