### ISSUE TITLE
autocomplete listings too verbose

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#131]
go to this link:
http://18.217.77.150:5000/

and type in "ibuprofen", for example

**Comment by saramsey** [comment]
Some suggested heuristics:

(1) have the list of autocomplete suggestions prioritize perfect matches starting from the beginning of the word, and among those, to prioritize a word with no punctuation.  So if the user has typed "ibuprof", then the first listing should be "ibuprofen".  Any match to "ibuprofen-induced" or "ibuprofen-inducing" should be down the list, since they contain punctuation. Any match to "(R)-ibuprofen" (which is not a match starting at the beginning of the dictionary word) would be even further down-weighted on the priority list.

(2) eliminate from the autocomplete list any word that ends with one of the following characters:  
colon, semicolon, hyphen, comma, parenthesis, or square bracket

**Comment by dkoslicki** [comment]
(after he's accepted my github collab invite)

**Comment by arnabdotorg** [comment]
Fixed in http://rtxcomplete.ixlab.org/ 

![image](https://user-images.githubusercontent.com/421604/40199347-21bbe274-59e7-11e8-909d-18c7cd43741c.png)
