### ISSUE TITLE
problem with tomorrow's query

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1314]
oops, I think I just saw a problem with tomorrow's query. ARAX is returning an ugly error because nothing found?
```
{
      "edges": {
        "e01": {
          "object": "n1",
          "predicate": "biolink:treated_by",
          "subject": "n0"
        }
      },
      "nodes": {
        "n0": {
          "category": "biolink:Drug",
          "id": "DRUGBANK:DB00394"
        },
        "n1": {
          "category": "biolink:Disease"
        }
      }
    }
```

**Comment by edeutsch** [comment]
If this works better in KG2.5.2, maybe it is better to roll out now? nothing to lose?

**Comment by amykglen** [comment]
ah, hm.. I think this still won't work with KG2.5.2, since the reasoning to turn `treated_by` into `treats` still isn't in place..

**Comment by amykglen** [comment]
but potentially could put a quick fix in place that just searches for _both_ predicates in situations like this (since we always ignore edge direction anyway). do you know if there's an SRI service for getting such inverted predicates from the biolink model?

**Comment by edeutsch** [comment]
ah okay. whoever is going to represent us at the standup tomorrow, it looks like this https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/beclomethasone.json will be the rope.

**Comment by edeutsch** [comment]
oh, that would be good. I don't know of such a service. We could hard-code one for now.

**Comment by edeutsch** [comment]
treats <-> treated_by is the one that everyone always talks about, so just even handling that as a one-off would help with tomorrow and with a lot of other cases. I can't even name another example. Maybe @saramsey or @kvarforl or @ericawood have a list of reversing biolink predicates?

**Comment by amykglen** [comment]
cool - I can do that. at least just start with a few of the common ones. think you can see pairs on this page by searching for "inverse:" https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml

**Comment by edeutsch** [comment]
aha, very good. Could just loop through that and build the dictionary of inverses there. I suppose it would be more efficient to know which one KG2 has (if it is always only one?) and only use that, rather always searching for both. But maybe performance difference is negligible

**Comment by ericawood** [comment]
Based on `predicate-remap.yaml`, it appears that only `biolink:treats` is in KG2 (not `biolink:treated_by`).

**Comment by amykglen** [comment]
alright, the query is working now in the `kg2.5integration` branch - added a preliminary method that just looks at the biolink yaml file to find inverses and considers those as well (I _think_ the performance hit is probably pretty trivial vs. considering only the one that KG2 includes, but that could be investigated down the road a bit...)

**Comment by amykglen** [comment]
this works on production now! https://arax.ncats.io/?r=5552  good to close?

**Comment by edeutsch** [comment]
This is awesome, thanks, @amykglen !
@saramsey or @dkoslicki or whoever is going to the standup meeting tomorrow morning:
Their standup query for tomorrow should now be working. They may have a cached version that shows that it wasn't working previously. If you can nudge them to retry, it should work. I hope.
Also FYI, we are fully on KG2.5.2 now. Deployed everywhere.
