### ISSUE TITLE
Best node descriptions for KG2c?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1316]
creating this issue to discuss what the best approach for populating KG2c node descriptions might be...

right now the description of the 'leader' curie is used, unless that is null, in which case the largest description of the coalesced nodes that is <10,000 characters is used.

but the 'leaders' don't necessarily always have the 'best' description.. for example, CHEMBL.COMPOUND:CHEMBL1161998 is the 'leader' for it's synonym group, but this is its description in KG2:

> "3-hydroxy-2-oxopropyl hydrogen phosphate; FULL_MW:170.06; MAX_FDA_APPROVAL_PHASE: 0"

whereas this is the description for DRUGBANK:DB04326, which is one of CHEMBL.COMPOUND:CHEMBL1161998's equivalent curies:

> "UMLS Semantic Type: UMLS_STY:T123; UMLS Semantic Type: UMLS_STY:T109; Dihydroxyacetone phosphate is an important intermediate in lipid biosynthesis and in glycolysis. Dihydroxyacetone phosphate has been investigated for the treatment of Lymphoma, Large-Cell, Diffuse."

a bit more informative.

wondering if the KG2 team might have suggestions for which kinds of nodes might have the best descriptions? (e.g., UniProtKB, DRUGBANK, etc.)

**Comment by dkoslicki** [comment]
Naive idea: would concatenating descriptions for equivalent nodes up to 10,000 characters help resolve this? It might start with the less helpful description, but would hopefully include the better one.

**Comment by edeutsch** [comment]
ha! That's what we were doing before. It led to very long and confusing descriptions. the algorithm looking for long descriptions and those tended to be messy ones. And then 5 messy ones were concatenated into a real mess.

**Comment by dkoslicki** [comment]
I recall the descriptions being concatenations, but I thought there was no limit to the length (hence that one 3M character long description). Agreed that it was messy. Maybe there’s some NLP method that picks one that is the least messy? Eg. The flesch kincaid readability score or similar

**Comment by ericawood** [comment]
Regarding readability, in multiple ETL scripts, we append the sequence information to the description. The idea behind that is that we don't have anywhere else to put it and it could potentially be helpful in reasoning, but I wouldn't describe the descriptions with them as readable (ex. UniProtKB).

**Comment by amykglen** [comment]
yeah, that's right @dkoslicki - we used to concatenate the top 5, but there was no cap on length

**Comment by edeutsch** [comment]
Maybe it makes sense to reserve the `description` field for a nice human-readable definition of the concept (that is how the UI is trying to use it)? And create a different field like `additional_info` or something that can be the dumping ground for other stuff?

**Comment by dkoslicki** [comment]
I like that idea @edeutsch , but I was under the assumption that the hard part is identifying which of the descriptions is actually the “nice” one

**Comment by edeutsch** [comment]
I agree that the main problem is selecting a nice description. But if all the description fields were truly human readable descriptions rather than dumping grounds for other stuff, then the selection algorithm could be as simple as pick the longest one? But when descriptions are dumping grounds, then that algorithm (longest) fails badly? I'm wondering if we can limit descriptions to true human-focused descriptions, then maybe this problem is trivial to solve?

**Comment by saramsey** [comment]
See also #1301

**Comment by dkoslicki** [comment]
All in favor of closing due to #1420 capturing the current state of the issue?
