### ISSUE TITLE
node_synonymizer.py has a hard coded database name

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1318]
Looks like the database name got switched to being hard coded during the push to KG2.5.2. I'm going to change it back to using RTXConfiguration so that it does not break when the name changes in configv2.json. Is this going to cause any problems on you end @amykglen ?

**Comment by edeutsch** [comment]
Has this change been made already? NodeSynonymizer is now broken on production. ARAX and KG2 are down since 9am at least. Last known working at 8am. I've been in a workshop all morning, so don't know what's going on.

**Comment by edeutsch** [comment]
It looks like filename have been changed in /mnt/data/orangeboard/databases/KG2.5.2:
```
-rw-r--r-- 1 rt rt           0 Mar 23 15:01 node_synonymizer.sqlite
-rw-r--r-- 1 rt rt 16607158272 Mar 11 18:58 node_synonymizer.sqlite-obsolete
-rw-r--r-- 1 rt rt 16602951680 Mar 13 05:07 node_synonymizer_v1.0.sqlite
-rw-r--r-- 1 rt rt 16667919360 Mar 20 04:49 node_synonymizer_v1.0_KG2.5.2.sqlite
```
some time between 8am and 9am Pacific

**Comment by edeutsch** [comment]
Node Synonymizer database is 0 bytes on production.

**Comment by amykglen** [comment]
@finnagin - we decided to leave the node_synonymizer name as just `node_synonymizer.sqlite` for now, and improve its name during the next rollout/synonymizer version. 

I believe the system was working how it was - can you revert whatever changes you made?

**Comment by finnagin** [comment]
The name has been reverted. Sorry for any issues that caused! Doubled checked and all tests seem to be passing on production.
