### ISSUE TITLE
Some new 'biolink:Gene' curies in KG2.5.2 have already been withdrawn by HGNC or NCBI

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1319]
Hi all,

Just found that some new-added 'biolink:Gene' curies in KG2.5.2 have been withdrawn by HGNC or NCBI. Here are a few examples:

`HGNC:25943`:
![Screen Shot 2021-03-23 at 2 07 12 PM](https://user-images.githubusercontent.com/20031672/112196145-1fa8f100-8be1-11eb-82cf-ad397b0431f0.png)

`HGNC:617466`:
The link (https://identifiers.org/hgnc:617466) of this gene pointing to HGNC is invalid.

`NCBIGene:39470459`:
![Screen Shot 2021-03-23 at 2 09 40 PM](https://user-images.githubusercontent.com/20031672/112196501-7adae380-8be1-11eb-84c6-a3d0da2a2a59.png)

`NCBIGene:39531620`:
![Screen Shot 2021-03-23 at 2 10 42 PM](https://user-images.githubusercontent.com/20031672/112196593-92b26780-8be1-11eb-98bd-3c59bc989848.png)

`NCBIGene:39538321`:
![Screen Shot 2021-03-23 at 2 11 41 PM](https://user-images.githubusercontent.com/20031672/112196726-b5dd1700-8be1-11eb-87b1-d8aa545539f1.png)

**Comment by kvarforl** [comment]
Thanks for pointing these out! I know the HGNC nodes are ready to be addressed as soon as the ontiobio issue is resolved: see #1170 for more information.

I'll look into the NCBIGene's now!

**Comment by kvarforl** [comment]
Okay, so NCBI gene nodes come from bunch of sources:
```
match (n) where n.id starts with "NCBI" return n.provided_by, count(*) order by count(*) DESC
```

n.provided_by | count(*)
-- | --
"umls_source:NCBITAXON" | 1776514
"identifiers_org_registry:ncbigene" | 61628
"OBO:pr.owl" | 5594
"OBO:ncbitaxon/subsets/taxslim.owl" | 3374
"EFO:efo.owl" | 375
"OBO:cl.owl" | 44
"OBO:foodon.owl" | 37
"OBO:genepio.owl" | 29
"OBO:mondo.owl" | 28
"OBO:go/extensions/go-plus.owl" | 24
"OBO:uberon/ext.owl" | 2
"OBO:doid.owl" | 2

All three of the examples provided are from `OBO:pr.owl`, but not all of the ncbi nodes from that source are discontinued (see `NCBIGene:2761905` for example)

**Comment by chunyuma** [comment]
Hi @kvarforl and @ericawood, I just checked these discontinued 'biolink:Gene' curies in KG2.6.1 and they are not in KG2.6.1 anymore. So this issue seems to be fixed now in KG2.6.1. Just want to confirm with you both. Then I think we can close this issue. Thanks!
