### ISSUE TITLE
UI integration with new KG

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#132]
@saramsey @edeutsch @isbluis I've completed the change to the new KG (see issue #119). The code has been merged into master and is ready for integration with the UI.

Let's get the code working, and then we can address the required changes to my output API format and #100.

High priority since this is (ostensibly) the version we'll be presenting at the hackathon (pending #122 and #123).

**Comment by dkoslicki** [comment]
@edeutsch Recalling an email you sent: it seems this task has been completed. Is that accurate? If so, let's close this issue.

**Comment by edeutsch** [comment]
yes, we're using the new KG in production, so I think this is all done. can be closed.
