### ISSUE TITLE
The curies with prefix HMDB in kg2.5.2 are all converted to the curies with prefix PUBCHEM.COMPOUND in kg2.5.2c

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1321]
Just found a problem in `kg2.5.2c` that all curies with prefix `HMDB` in kg2.5.2 are converted to the curies with prefix `PUBCHEM.COMPOUND` in kg2.5.2c. However, there is no curie with prefix `PUBCHEM.COMPOUND` in kg2.5.2.

Here are a few examples:

n.id | n.equivalent_curies
-- | --
"PUBCHEM.COMPOUND:53480227" | ["HMDB:HMDB0010036"]
"PUBCHEM.COMPOUND:53480229" | ["HMDB:HMDB0010038"]
"PUBCHEM.COMPOUND:53480230" | ["HMDB:HMDB0010039"]
"PUBCHEM.COMPOUND:53480231" | ["HMDB:HMDB0010040"]
"PUBCHEM.COMPOUND:53480232" | ["HMDB:HMDB0010041"]
"PUBCHEM.COMPOUND:53480234" | ["HMDB:HMDB0010043"]

Also, the original type of `HMDB` curies is `biolink:Metabolite`. However, after converted to `PUBCHEM.COMPOUND`, it becomes `biolink:ChemicalSubstance`.

n.id | n.category | n.all_categories | n.equivalent_curies
-- | -- | -- | --
"PUBCHEM.COMPOUND:53480227" | "biolink:ChemicalSubstance" | ["biolink:Metabolite"] | ["HMDB:HMDB0010036"]
"PUBCHEM.COMPOUND:53480229" | "biolink:ChemicalSubstance" | ["biolink:Metabolite"] | ["HMDB:HMDB0010038"]
"PUBCHEM.COMPOUND:53480230" | "biolink:ChemicalSubstance" | ["biolink:Metabolite"] | ["HMDB:HMDB0010039"]
"PUBCHEM.COMPOUND:53480231" | "biolink:ChemicalSubstance" | ["biolink:Metabolite"] | ["HMDB:HMDB0010040"]
"PUBCHEM.COMPOUND:53480232" | "biolink:ChemicalSubstance" | ["biolink:Metabolite"] | ["HMDB:HMDB0010041"]
"PUBCHEM.COMPOUND:53480234" | "biolink:ChemicalSubstance" | ["biolink:Metabolite"] | ["HMDB:HMDB0010043"]

Perhaps this might be a bug for `NodeSynonymizer `.

**Comment by chunyuma** [comment]
This seems to affect the DTD model and database rebuild. So I don't know if I should hold off the DTD rebuild again because of this problem. The reason why this affects DTD model is because I don't know if we should treat `biolink:Metabolite` as a drug for DTD. The `biolink:Metabolite` is actually a direct child of `biolink:ChemicalSubstance`.

**Comment by edeutsch** [comment]
I will fix the HMDB  PUBCHEM problem. This is definitely a bug.

But as far as the second topic: should you treat biolink:Metabolite as a drug for DTD purposes, I don't know. I suppose yet. But note that biolink:ChemicalSubstance has many other children such as FoodAdditive, Nutrient, ProcessedMaterial, etc. Should those be added, too? I don't know:
See Children at https://biolink.github.io/biolink-model/docs/ChemicalSubstance.html

**Comment by edeutsch** [comment]
I have fixed this bug in the NodeSynonymizer database in a way that you can see here:
https://arax.ncats.io/devED/?term=HMDB:HMDB0010039

But note that this is only in devED. This fixed NodeSynonymizer database is not used in other locations yet. It is version 1.2 and is available in the databases/KG2.5.2 area:
```
lrwxrwxrwx 1 rt   rt            36 Mar 24 06:16 node_synonymizer.sqlite -> node_synonymizer_v1.1_KG2.5.2.sqlite
-rw-r--r-- 1 rt   rt   16667919360 Mar 20 04:49 node_synonymizer_v1.0_KG2.5.2.sqlite
-rw-r--r-- 1 rt   rt   16667919360 Mar 23 17:12 node_synonymizer_v1.1_KG2.5.2.sqlite
-rw-r--r-- 1 rt   rt   16667399168 Mar 24 06:09 node_synonymizer_v1.2_KG2.5.2.sqlite
```
but as you can see, v1.1 is still the active one for most instances.

What should we do with v1.2? Rebuild KG2C? and everything else? maybe. But it's not clear that it is worth the effort? Or maybe good practice for quick bugfix and rollout? Is there a penalty for just rolling out as is without changing anything else? Slight. For the concepts list at the top of this issue, the NodeSynonymizer may point to a node that doesn't exist in KG2C. Which might cause some possible issue. although rare.

Perhaps best to wait until some other fixes pile up.

Perhaps a good topic for the AHM.

**Comment by chunyuma** [comment]
This issue has been fixed. I also confirmed that the curies with prefix `PUBCHEM.COMPOUND` are not in KG2.6.1 anymore.
