### ISSUE TITLE
Should the PathWhiz.NucleicAcid be assigned to `biolink:ChemicalSubstance`?

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1322]
In kg2.5.2, right now all curies with prefix `PathWhiz.NucleicAcid` are assigned to `biolink:ChemicalSubstance` category. But based on PathWhiz website, they should belong to DNA or protein or related rather than chemicalsubstance. So does this make sense to treat `NucleicAcid` as `ChemicalSubstance`?

Here is an example:
{
  "iri": "https://pathbank.org/lims#/nucleic_acids/136",
  "category_label": "chemical_substance",
  "full_name": "L-arabinose binding preprotein",
  "deprecated": "False",
  "name": "L-arabinose binding preprotein",
  "provided_by": "PathWhiz:",
  "id": "PathWhiz.NucleicAcid:136",
  "category": "biolink:ChemicalSubstance",
  "update_date": "2019-08-17 05:35:28"
}

![Screen Shot 2021-03-24 at 12 54 01 AM](https://user-images.githubusercontent.com/20031672/112257571-73e0bf00-8c3b-11eb-9ae2-c798b9a20653.png)

**Comment by ericawood** [comment]
Perhaps `biolink:genomic_entity` is a better fit? (See [this](https://github.com/biolink/biolink-model/blob/40a06d203beb357e8bb606e3035cb03e9f3116f9/biolink-model.yaml#L6493-L6514) definition in the Biolink YAML file)

**Comment by saramsey** [comment]
+1 biolink:GenomicEntity

**Comment by saramsey** [comment]
I concur with @ericawood

**Comment by ericawood** [comment]
I tested 20 `PathWhiz.NucleicAcid` nodes from KG2.5.2 in the PathWhiz browser. All listed their types as RNA or DNA. So, based on this, I think `biolink:GenomicEntity` fits well.

**Comment by chunyuma** [comment]
Hi @ericawood, will this be fixed in kg2.5.3?

**Comment by ericawood** [comment]
> Hi @ericawood, will this be fixed in kg2.5.3?

Yes, this should be fixed with 604f367.

**Comment by kvarforl** [comment]
this is fixed in  Kg2.6.0!
