### ISSUE TITLE
Generate all triples in KG2 and KG2C, along with examples

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1325]
Basically, we need to generate files like [this](https://github.com/NCATSTranslator/testing/blob/main/onehop/test_triples/KP/Clinical_Data_Provider/Columbia_Open_Health_Data_(COHD).json) and put it in [this repo](https://github.com/NCATSTranslator/testing/tree/main/onehop/test_triples/KP).

A JSON-y list of all possible triples we can return, and one example subject & object curie for each triple.

**Comment by finnagin** [comment]
After a bit of trial and error worked out a query that can do this seems to take a while:
```
match (n)-[r]->(m) with distinct labels(n) as n1s, type(r) as rel, labels(m) as n2s unwind n1s as n1 unwind n2s as n2 with distinct n1 as node1, rel as relationship, n2 as node2 where node1 <> "Base" and node2 <> "Base" CALL apoc.cypher.run('match (n2:`' + node1 + '`)-[r2:`' + relationship + '`]->(m2:`' + node2 + '`) return n2.id as subject, m2.id as object limit 1', {}) YIELD value return node1, relationship, node2, value.subject as subject, value.object as object
```

Need to compare this to sending a bunch of individual queries and see which is faster

**Comment by dkoslicki** [comment]
@finnagin How goes the progress on this issue?

**Comment by finnagin** [comment]
I have this implemented locally was just comparing the speeds of a couple implementation methods but should be ready to push my changes after a couple tweaks.

**Comment by dkoslicki** [comment]
Ah, I see, thanks! Note that speed isn't a problem, it's a one/few-off solution.

**Comment by dkoslicki** [comment]
@finnagin This is now high priority: architecture is discussing this and we don’t have this done yet. Can you please address this as soon as you can?

**Comment by finnagin** [comment]
@dkoslicki This is done. 

KG2 json file is here: https://github.com/RTXteam/RTX/blob/master/code/ARAX/KnowledgeSources/RTX_KG2_Data.json

KG2c json file is here: https://github.com/RTXteam/RTX/blob/master/code/ARAX/KnowledgeSources/RTX_KG2c_Data.json

Though looking back on this I see the problem is I forgot to upload these to the NCATS repo. Should I fork and make a pull request? Also, upload the KG2s one since that is the one used at the api enpoint?

**Comment by dkoslicki** [comment]
Thanks! And yes, a PR seems to be in order. And I assume you meant KG2c, not s, right? If so, then I do think that’s the right one to upload/PR with

**Comment by finnagin** [comment]
I meant c lol! I'll do that then. One sec...

**Comment by finnagin** [comment]
@dkoslicki pull request has been added: https://github.com/NCATSTranslator/testing/pull/54

**Comment by finnagin** [comment]
I named it RTX_KG2 to avoid confusion but this is the KG2c data json.

**Comment by saramsey** [comment]
> After a bit of trial and error worked out a query that can do this seems to take a while:
> 
> ```
> match (n)-[r]->(m) with distinct labels(n) as n1s, type(r) as rel, labels(m) as n2s unwind n1s as n1 unwind n2s as n2 with distinct n1 as node1, rel as relationship, n2 as node2 where node1 <> "Base" and node2 <> "Base" CALL apoc.cypher.run('match (n2:`' + node1 + '`)-[r2:`' + relationship + '`]->(m2:`' + node2 + '`) return n2.id as subject, m2.id as object limit 1', {}) YIELD value return node1, relationship, node2, value.subject as subject, value.object as object
> ```
> 
> Need to compare this to sending a bunch of individual queries and see which is faster

Nice

**Comment by saramsey** [comment]
Here is the cypher query with a bit of formatting to reveal its structure:
```
match (n)-[r]->(m) with distinct labels(n) as n1s, type(r) as rel, labels(m) as n2s
unwind n1s as n1 unwind n2s as n2 
with distinct n1 as node1, rel as relationship, n2 as node2 
where node1 <> "Base" and node2 <> "Base" 
CALL apoc.cypher.run('match (n2:`' + node1 + '`)-[r2:`' + relationship + '`]->(m2:`' + node2 + '`) 
return n2.id as subject, m2.id as object limit 1', {}) 
YIELD value return node1, relationship, node2, value.subject as subject, value.object as object
```
Most impressive!

**Comment by finnagin** [comment]
Thank you!

**Comment by dkoslicki** [comment]
Closing due to https://github.com/NCATSTranslator/testing/pull/54
