### ISSUE TITLE
Provide NCATS a list of all the KPs and KSs that we use

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1326]
We are to take a look at [this document](https://github.com/NCATSTranslator/testing/blob/main/onehop/templates/ARA/Expander_Agent/ARAX_Translator_Reasoner.json) and remove the KP that we don't use, and add ones we do.

**Comment by ericawood** [comment]
I'm a little confused what is desired here. These are all KPs. Doesn't kg2 ingest KSs? (Except for KG1, we're not using APIs, just flat file downloads)

**Comment by dkoslicki** [comment]
Maybe @saramsey might have some input about whether we should list KPs like `MyGene.info API` when we only use the API to do flat file downloads to get it into KG2.

**Comment by saramsey** [comment]
From the KG2 perspective: Assuming we get rid of loading KG1 as a part of the KG2 build process (which will probably happen this spring, at least I hope it happens this spring), then I don't think KG2 would depend on any of those APIs *per se*.  Right, @ericawood ?

**Comment by saramsey** [comment]
If we are not querying MyGene.info via the Translator API, then I suppose we aren't really using it as a KP, right?  But in any event, once we eliminate the vestigial KG1 input to the KG2 build process, I don't think KG2 will have any dependency on MyGene.info (right, @ericawood ?)

**Comment by dkoslicki** [comment]
Are we using MyGene.info in any capacity? I figure it might be helpful to let NCATS know the advantages of ETL vs API

**Comment by ericawood** [comment]
> If we are not querying MyGene.info via the Translator API, then I suppose we aren't really using it as a KP, right? But in any event, once we eliminate the vestigial KG1 input to the KG2 build process, I don't think KG2 will have any dependency on MyGene.info (right, @ericawood ?)

As far as I know, KG2 will not have any dependency on MyGene.info once KG1 is gone. KG1 can probably be deprecated soon since the next build will contain Reactome, miRBase, and IntAct.
The only API that KG2 currently queries is the KG1 endpoint.
The one way that I can think that we have used an API is that I used MyChem.info to help me understand the data within DrugCentral.

**Comment by saramsey** [comment]
My best guess as to the current (well, as soon as we drop KG1) ARAX dependencies on APIs:
```
{
    "url": "https://arax.ncats.io/api/arax/v1.0",
    "TRAPI": true,
    "KPs": [
        "KG2 API",
        "Columbia Open Health Data (COHD)",
        "ICEES API",
        "MyGene.info API"
     ]
}
```
Based on the SmartAPI registry search page for "translator",
https://smart-api.info/registry?q=translator&tags=translator

I can conclude the following:
- COHD and KG2 are definitely registered TRAPI-1.0 KPs. 
- ICEES is registered but I am not sure it is yet speaking TRAPI (but it is a registered API provided by a Translator "KP Team", the "Exposures Provider" team). 
- MyGene.info is SmartAPI-registered but not an official KP (though as with ICEES, MyGene.info is provided by a Translator "KP Team", the "Service Provider" team).

**Comment by saramsey** [comment]
> Are we using MyGene.info in any capacity? I figure it might be helpful to let NCATS know the advantages of ETL vs API

Good topic for a Zoom discussion.

**Comment by saramsey** [comment]
Anyone have any corrections to this?

```
{
    "url": "https://arax.ncats.io/api/arax/v1.0",
    "TRAPI": true,
    "KPs": [
        "KG2 API",
        "Connections Hypothesis Provider API",
        "Columbia Open Health Data (COHD)",
        "Genetics Provider",
        "ICEES API",
        "Molecular Data Provider for NCATS Biomedical Translator Reasoners",
        "MyGene.info API",
        "Name Resolver"
     ]
}
```

specifically, @chunyuma @finnagin @amykglen @dkoslicki ?

**Comment by ericawood** [comment]
For the one for KG2 (see [this](https://github.com/NCATSTranslator/testing/blob/main/onehop/templates/ARA/Expander_Agent/RTX_KG2.json)), does anyone have any corrections? Are we supposed to put the `/ui` at the end of the url?
```
{
    "url": "https://arax.ncats.io/kg2/api/rtxkg2/v1.0",
    "TRAPI": true,
    "KPs": []
}
```

**Comment by dkoslicki** [comment]
@saramsey Looks good to me!
@ericawood I’ve opened an issue [here](https://github.com/NCATSTranslator/testing/issues/42) asking if this is what NCATS actually intended. I’ll let you know what I hear. And no idea re: `/ui` at the end of the url

**Comment by dkoslicki** [comment]
Any updates on this issue @ericawood @kvarforl or @saramsey ? I noticed that while we have an idea of what to put there, a PR hasn’t been opened yet

**Comment by dkoslicki** [comment]
Closing since this request hasn't been followed up on in a few years
