### ISSUE TITLE
Should KEGG:C00161 be treated as a synonym of CHEBI:35910?

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1327]
Hi @edeutsch,

Perhaps this might be another issue for NodeSynonymizer. So I tried to check the node source distribution of `biolink:Metabolite` in today's kg2.5.2c. As you can see below, most of them are from `KEGG`:

![Screen Shot 2021-03-24 at 5 41 33 PM](https://user-images.githubusercontent.com/20031672/112387481-3413e900-8cc8-11eb-9800-5b64df80804d.png)

If you check some of the `KEGG` curies in kg2.5.2c, their `equivalent_curies` are just themselves.

n.id | n.equivalent_curies
-- | --
"KEGG:C21457" | ["KEGG:C21457"]
"KEGG:C04167" | ["KEGG:C04167"]
"KEGG:C21458" | ["KEGG:C21458"]
"KEGG:C04170" | ["KEGG:C04170"]
"KEGG:C21459" | ["KEGG:C21459"]
"KEGG:C21460" | ["KEGG:C21460"]
"KEGG:C21461" | ["KEGG:C21461"]
"KEGG:C21462" | ["KEGG:C21462"]
"KEGG:C04180" | ["KEGG:C04180"]
"KEGG:C21463" | ["KEGG:C21463"]

If you take a look at `KEGG:C00161 `, its `equivalent_curies` are just itself and `PathWhiz.ElementCollection:552`.

n.id | n.equivalent_curies
-- | --
"KEGG:C00161" | ["KEGG:C00161", "PathWhiz.ElementCollection:552"]

However, you check KEGG database for `KEGG:C00161`
![Screen Shot 2021-03-24 at 5 55 16 PM](https://user-images.githubusercontent.com/20031672/112388817-1c3d6480-8cca-11eb-99e4-0dacd22ac2fc.png)

It should have a synonym `CHEBI:35910`:
![Screen Shot 2021-03-24 at 5 56 24 PM](https://user-images.githubusercontent.com/20031672/112388929-455df500-8cca-11eb-8ec8-4a053eb13171.png)

But right now, in kg2.5.2c, they are not clustered together and `CHEBI:35910` is `biolink:MolecularEntity`.
![Screen Shot 2021-03-24 at 6 02 53 PM](https://user-images.githubusercontent.com/20031672/112389484-2c097880-8ccb-11eb-92c5-06eac1192ad7.png)

It might have other `KEGG` curies that are like this case.

**Comment by edeutsch** [comment]
Hi @chunyuma thanks for the report. I see the issue, but I don't think the NodeSynonymizer can help here. As far as I can tell, KEGG:C00161 and CHEBI:35910 are not linked to each other via registered equivalency in KG2.5.2 or in the SRI Node Normalizer. And their names are different. So there's no way currently to link them by the NodeSynonymizer unless I put in a manual exception. which I could.

It seems to me that we should ask the KG2 team to see if the equivalencies to ChEBI:35910 and PubChem can be made during ETL of KEGG?. Tagging @ericawood and @saramsey  for an assessment.
Let me know if you think I've misunderstood.

**Comment by ericawood** [comment]
As far as I can tell, KEGG is "pay to use" (see https://www.pathway.jp/en/academic.html). Thus, we can't ETL KEGG directly without paying for a license. The parts of KEGG that are currently in KG2 are remnants of KG1 (see code below):
https://github.com/RTXteam/RTX/blob/884a253d33cb644ec3a20fa60fcc005b111037ef/code/kg2/rtx_kg1_neo4j_to_kg_json.py#L33-L62

**Comment by saramsey** [comment]
I am not a chemist (IANAC), but I am not sure that [CHEBI:35910](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:35910) (2-oxo monocarboxylic acid, for which residue R1 by definition cannot contain a carboxyl group) and [KEGG:C00161](https://www.genome.jp/dbget-bin/www_bget?cpd:C00161) (2-oxocarboxylic acid, for which residue R could in principle contain a carboxyl group), are the same thing.

Consider [CHEBI:727000](https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:72700) (2-oxopimelic acid)

![chebi-72700](https://user-images.githubusercontent.com/5562107/113442400-d9a01a00-93a4-11eb-9a93-4d0eb8f0123f.png)

It is a dicarboxylic acid, thus cannot subclass CHEBI:35910. But it is clearly not a subclass of 2-oxocarboxylic acid. In any ontology, if you have classes A, B, and C, and C subclasses B and C does *not* subclass A, then A and B cannot be equivalent. Thus it seems to me that there should not be a `biolink:same_as` relationship between `KEGG:C00161` and `CHEBI:35910`.

**Comment by saramsey** [comment]
Nevertheless, this issue raises a broader point. It would be nice if we could get cross-references between KEGG and CHEBI. I wonder if Unichem can help here?

**Comment by saramsey** [comment]
> Nevertheless, this issue raises a broader point. It would be nice if we could get cross-references between KEGG and CHEBI. Hi @ericawood and @kvarforl, I wonder if Unichem can help here? I note that Unichem lists some KEGG fields:
> 
> <img alt="Screen Shot 2021-04-02 at 11 25 26 AM" width="1022" src="https://user-images.githubusercontent.com/5562107/113443104-2506f800-93a6-11eb-88bf-c0d64d0c3fbf.png">

See #1354

**Comment by saramsey** [comment]
I note that the SRI node normalizer does not have an equivalence relationship between `KEGG:C00161` and `CHEBI:35910`:

<img width="937" alt="Screen Shot 2021-04-07 at 5 23 56 PM" src="https://user-images.githubusercontent.com/5562107/113950392-0f3e6c00-97c6-11eb-9940-2b652c9ed358.png">

<img width="940" alt="Screen Shot 2021-04-07 at 5 24 19 PM" src="https://user-images.githubusercontent.com/5562107/113950411-1a919780-97c6-11eb-81f5-1882e73372c3.png">

**Comment by chunyuma** [comment]
Hi @saramsey, @kvarforl and @ericawood, is it possible that we can use Biopython to call KEGG api (eg. [Bio.KEGG.REST.kegg_get](https://biopython.org/docs/1.75/api/Bio.KEGG.REST.html)) to extract the cross-references between KEGG and other DBs. This is what I'm now doing to get the smiles for KGEE curies.

**Comment by saramsey** [comment]
Hi @chunyuma: what KEGG-to-other-DB cross-references do you specifically need?  We already get a lot of them via CHEBI, Uniprot, and other knowledge sources.

I wonder if we might be able to get more information about KEGG via CTD. Adding a dependency on the KEGG API in the KG2 build process would be my least-favored option. The thing about KG2 is its is a deterministic build. Starting from the same upstream knowledge source flat-files, rerunning the KG2 build, we would get the *exact* same result. As soon as we start introducing live API dependencies, that can change. Using flat files as inputs for building KG2 makes it easier to debug, fairly fast to build (considering the massive size of KG2 and the large number of gigabytes of upstream sources that it depends on), and robust against API changes or downtime.

**Comment by ericawood** [comment]
@chunyuma Are you looking for KEGG pathways or KEGG compounds?

**Comment by chunyuma** [comment]
Hi @saramsey and @ericawood, actually I'm now collecting KEGG smiles information by extracting the CAS ID, ChEMBL ID, ChEBI ID and PubChem ID on KEGG website via KEGG API. Since @saramsey has ever asked this question:

> Nevertheless, this issue raises a broader point. It would be nice if we could get cross-references between KEGG and CHEBI. Hi @ericawood and @kvarforl, I wonder if Unichem can help here? I note that Unichem lists some KEGG fields:

I just want to provide one possible way to make cross-references between KEGG and other DBs. 

> what KEGG-to-other-DB cross-references do you specifically need?

It is not necessary. I can do this on my specific KG. But perhaps we can do this cross-reference, it can help KG2c to cluster the concepts with the same semantic meaning.  

> Are you looking for KEGG pathways or KEGG compounds?

Hi @ericawood, I'm interested in KEGG compounds in order to collect its corresponding SMILES sequence. But I think I've found a way to do this via KEGG API. So no worries about this!  Thanks so much for you help!

**Comment by edeutsch** [comment]
closing ancient history.
