### ISSUE TITLE
Beware the requests_cache

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1328]
Hi everyone, I just wanted to throw out a quick warning about a bug that I fixed that I *think* was caused by requests_cache. The idea is that if you are using requests.get() in your code that runs within the ARAX query system, when you do your testing there may be no caching (because you didn't add any because you didn't want any) but some ARAX query components install caches and I think requests_cache does this at the class level and not the object level, and therefore promiscuously applies to other classes and objects somehow. I confess I don't really understand it all myself and I'm not certain, but if you ever have requests code that runs in the ARAX query environment and you specifically *don't* want caching, you may need to take extra steps to disable it for your requests. Or they may be unintentionally cached.

And similarly we may have multiple ARAX components that are setting up their own requests_cache, but it may be that the latest one wins and therefore some requests may not be getting cached in the same place as occurs in an isolated test.

Honestly I'm not certain about any of this, but maybe something to consider if you're seeing strange behavior with requests.

**Comment by edeutsch** [comment]
I was a little coy about this before because I am uncertain about this solution, but I am under the impression that if you want to make sure that your query isn't getting cached data, this might be the right thing to do:

```
            with requests_cache.disabled():
                response_content = requests.get(url)
```

**Comment by amykglen** [comment]
ah, I see, makes sense

**Comment by JWCook** [comment]
If possible, I'd recommend explicitly using `requests_cache.CachedSession` instead of `install_cache`. There's more info in the [User Guide](https://requests-cache.readthedocs.io/en/latest/user_guide.html#general-usage), and there's no harm in making an issue on the [requests-cache repo](https://github.com/reclosedev/requests-cache) if you encounter problems or have usage questions.

**Comment by finnagin** [comment]
@edeutsch is this still relevant or are we okay to close?

**Comment by edeutsch** [comment]
yes, fine to close, closing.
