### ISSUE TITLE
Descriptions now missing?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1331]
Looking at a recent query: https://arax.ncats.io/?r=5905 It appears there are no descriptions at all! Did something in #1306 or #1316 cause this to happen? It appears KG2.5.2 does have a description field, but it’s not being passed along. See `match (n:`biolink:Disease`{id:"MONDO:0020066"}) return n.description `

Don’t know if this is a UI issue or a resultify issue, hence @amykglen and @isbluis tags.

**Comment by amykglen** [comment]
I think that's because that query had `kp=NGD`. only KG2/c/1 queries return descriptions currently. seems fine when I change the KP to ARAX/KG2: https://arax.ncats.io/?r=5909

**Comment by dkoslicki** [comment]
Oh interesting, I was under the impression that FastNGD got curies, and then used KG2 to get the additional information. Guess I was mistaken. Would it be difficult to get those back in for NGD?

**Comment by amykglen** [comment]
yeah, it does get node names/categories from KG2 - probably would make sense to also grab descriptions! and not at all hard to do - I just adjusted it so that it grabs `description` as well as `iri`.

**Comment by dkoslicki** [comment]
Great! And thanks for the quick fix!

**Comment by amykglen** [comment]
confirmed this seems to look good on production: https://arax.ncats.io/?r=6086

good to close, @dkoslicki?

**Comment by dkoslicki** [comment]
Yup, good to close!
