### ISSUE TITLE
Biolink predicate change: negatively_regulates_entity_to_entity

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1332]
From the standup meeting today, it appears that some predicates have changed in Biolink. For example, in KG2.5.2, we have `match p=(n)-[r:`biolink:negatively_regulates_entity_to_entity`]-(m) return p limit 5` returning stuff, but biolink has `entity_negatively_regulates_entity` [here](https://biolink.github.io/biolink-model/docs/entity_negatively_regulates_entity.html), not `negatively_regulates_entity_to_entity`. Other `*_entity_to_entity` predicates may have changes as well.

**Comment by saramsey** [comment]
TY.

**Comment by kvarforl** [comment]
For the next build, I'll be sure to download the latest biolink model and make sure the graph uses that! Now that they have a versioning scheme, it might be good to add the biolink version used to the build node description of KG2 so it's easier to keep track of which issues come from using an old version of the model and which issues stem from bugs in our validation scripts :)

**Comment by edeutsch** [comment]
As a further side note, in the new TRAPI 1.1, which we will be obligated to implement in April, there is a place where we need to state the Biolink model version that we use. 

What is the Biolink model version for KG2.5.2? Do we know a specific version that we can state?

**Comment by ericawood** [comment]
From the `biolink-model.owl.ttl` on `kg2steve.rtx.ai` (where KG2.5.2 was built), it appears that the metamodel version is 1.7.0:

```
<https://w3id.org/biolink/biolink-model> a owl:Ontology ;
    rdfs:label "Biolink-Model" ;
    dcterms:license "https://creativecommons.org/publicdomain/zero/1.0/" ;
    skos:definition "Entity and association taxonomy and datamodel for life-sciences data" ;
    meta:generation_date "2021-03-02 23:36" ;
    meta:metamodel_version "1.7.0" ;
    meta:source_file "biolink-model.yaml" ;
    meta:source_file_date "Tue Mar  2 23:34:42 2021" ;
    meta:source_file_size 264627 .
```

Also, from KG2.5.2's Neo4j endpoint, this is the Biolink model's source node:
```
{
  "iri": "https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.owl.ttl",
  "category_label": "information_content_entity",
  "full_name": "Biolink meta-model",
  "deprecated": "False",
  "name": "Biolink meta-model",
  "provided_by": "biolink_download_source:biolink-model.owl.ttl",
  "id": "biolink_download_source:biolink-model.owl.ttl",
  "category": "biolink:InformationContentEntity",
  "update_date": "Tue Mar  2 23:34:42 2021"
}
```

**Comment by saramsey** [comment]
Looks like Lindsey and Erica are on it. Thank you, fantastic KG2 team!

**Comment by saramsey** [comment]
Setting the "verify in next build" label even though this isn't so much as a fix per-se as it is something we want to check in the next build.

**Comment by kvarforl** [comment]
Looks better in KG2.6.0!
