### ISSUE TITLE
CHP errors: No module named 'chp_client'

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1333]
noticed that the CHP tests are failing for me in `master`:
```
FAILED test_ARAX_expand.py::test_chp_expand_1 - AssertionError: assert ('ERROR' == 'OK'
FAILED test_ARAX_expand.py::test_chp_expand_2 - AssertionError: assert ('ERROR' == 'OK'
```
error looks like this: 
`  - 2021-03-30T17:11:21.316826 ERROR: [UncaughtARAXiError] An uncaught error occurred: No module named 'chp_client': ['Traceback (most recent call last):\n', '  File "/Users/amyglen/Projects/RTX/code/ARAX/test/../ARAXQuery/ARAX_query.py", line 592, in execute_processing_plan\n    expander.apply(response, action[\'parameters\'], mode=mode)\n', '  File "/Users/amyglen/Projects/RTX/code/ARAX/test/../ARAXQuery/ARAX_expander.py", line 352, in apply\n    answer_kg = self._expand_edge(one_hop_qg, kp_to_use, continue_if_no_results, use_synonyms, mode, log)\n', '  File "/Users/amyglen/Projects/RTX/code/ARAX/test/../ARAXQuery/ARAX_expander.py", line 437, in _expand_edge\n    from Expand.CHP_querier import CHPQuerier\n', '  File "/Users/amyglen/Projects/RTX/code/ARAX/test/../ARAXQuery/Expand/CHP_querier.py", line 10, in <module>\n    from chp_client import get_client\n', "ModuleNotFoundError: No module named 'chp_client'\n"]`

I confirmed the same error seems to happen on production. tested by running this DSL:
```
add_qnode(id=ENSEMBL:ENSG00000162419, key=n00)
add_qnode(category=biolink:Drug, key=n01)
add_qedge(subject=n00, object=n01, key=e00)
expand(edge_key=e00, kp=CHP, CHP_survival_threshold=500)
resultify()
```

**Comment by chunyuma** [comment]
Hi @amykglen, I think this problem can be solved after you run 
`pip3 install -e git+https://github.com/di2ag/chp_client#egg=chp_client`

**Comment by chunyuma** [comment]
I've added it to `requirements.txt` [here](https://github.com/RTXteam/RTX/blob/43cb3b60b36a23f1104695f90bdf07f78b280bca/requirements.txt#L28) but it is commented. Do I need to uncomment it?

**Comment by amykglen** [comment]
ah, yeah, it will definitely need to be uncommented. although I think you don't want the `pip install -e` portion of that line. so, the line should just be: 
```
git+https://github.com/di2ag/chp_client#egg=chp_client
```

we'll also need to then install it on arax.ncats.io as well (@edeutsch)

**Comment by amykglen** [comment]
cool! seems to work for me now after doing `pip install -r requirements.txt`. so I guess we'll just need to do that on arax.ncats.io to get it working on production as well.

**Comment by edeutsch** [comment]
done. all tests passing.

**Comment by amykglen** [comment]
awesome - looks good on production now! https://arax.ncats.io/?r=6085
