### ISSUE TITLE
Deploying new KG2c service ('Plover')

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1334]
so the new in-memory database service for KG2c discussed at the last couple AHMs (which I gave the very random name 'Plover' 😂 . 🐦 ) is ready to start being used by ARAX/KG2 production. it's been hosted on a new ec2 instance (`kg2cplover.rtx.ai` - thanks, @kvarforl!) and is fully plugged into Expand in the branch called `plover` (I've added the new local KG2c sqlite database to the database manager/rtxconfiguration.py and everything).

the full pytest suite (including slow tests) is running smoothly for me in this branch (locally forcing `mode="RTXKG2"`).

for now I made it so that, in the event that a request to Plover failed, Expand would back up to using the KG2c Neo4j like it used to.

I think the steps to make ARAX/KG2 production start using it are simply:
1. merge `plover` into `master`
2. roll `master` out to the KG2 endpoint
3. do `pip install -r requirements.txt` (I added a dependency for `ujson`)
4. put the modified `configv2.json` into place (the new copy is currently at: `/translator/data/orangeboard/databases/KG2.5.2/configv2.json_plover`)

fyi, Plover lives in its own repo in the RTXteam organization: https://github.com/RTXteam/PloverDB

one note on the sqlite aspect: certainly something like Redis would be faster here, and is probably a road to go down - but I decided to just start off with sqlite since it's really only for huge queries that it starts to feel a bit slow (though it's still always at least <30% of the neo4j time in queries I've seen).. but this is certainly something to improve..

**Comment by kvarforl** [comment]
This is so cool and impressive!!!! Great job!

**Comment by amykglen** [comment]
guess I'll close this! rolled out yesterday PM and still seems to be functioning smoothly.

**Comment by saramsey** [comment]
Outstanding work!  Also, thank you @kvarforl for setting up the instance!
