### ISSUE TITLE
Investigate alternatives to sqlite (Redis) for plover 'post-processing' step

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1337]
creating this issue to document that this is something to investigate... certainly sqlite is not the best, particularly when we're talking about really large queries.

although it's worth noting that a decent amount of the 'post-processing' time goes to simply loading the nodes/edges into the API object model - apparently 50 seconds, for example, for this huge query (based on the neo4j 'post-processing' time), which represents about half of plover's total 'post-processing' time:

![Screen Shot 2021-04-01 at 6 15 43 PM](https://user-images.githubusercontent.com/49423686/113369484-4d471600-9316-11eb-9d5c-ccf7ef147d9b.png)

so using something like Redis wouldn't help us with that part. so it also might be worth thinking about if there's something else that could be done to help speed up that part... (concurrency?)

**Comment by edeutsch** [comment]
Can you describe a bit more about what it's doing that takes the long time? Is it performing a whole bunch of repetitive queries that could be streamlined into one? or a few?

**Comment by amykglen** [comment]
sure - there are three queries in total, which look like:

`SELECT node from nodes where node.id in (list of n00 curies)`
`SELECT node from nodes where node.id in (big list of n01 curies)`
`SELECT edge from edges where edge.id in (huge list of edge IDs)`

which I believe take around 50 seconds (combined) in this example.

but after those queries complete, the found nodes/edges have to be loaded into actual `Node` and `Edge` objects (since they're just stored as JSON strings in the sqlite), which also takes about 50 seconds by itself (this part just loops through the nodes and edges and turns them into `Node`s and `Edge`s -- this part is essentially the same as for the Neo4j query, since its JSON response also has to be loaded into `Node`s and `Edge`s).

technically the two nodes queries could be combined (and perhaps I'll do that), but I don't think this is a notable factor in the slowdown. the vast majority of the post-processing time goes to edges (vs. nodes), since there are so many more of them (1.3m edges vs. 75k nodes in this example). the nodes comparatively really don't take that long.

**Comment by edeutsch** [comment]
ah okay, you're doing most of the things that I can think of already. It might be fun to create a standalone repro to test the speed of the various components.

My only other idea is to wheel out multiprocessing. If you think the 1.3 million edges is taking most of the time, you could put the 16 cores on arax.ncats.io to good use to make them work in parallel. I suppose that is assuming that the biggest overhead is creating 1.3 million objects? Have you used multiprocessing before? Try feeding all 1.3 million rows into a multiprocessing call to create all the objects in parallel. Something (very vaguely) like:

```
            import multiprocessing
            n_threads = multiprocessing.cpu_count()
            pool = multiprocessing.Pool(processes=n_threads)
            edges = pool.map_async(self.method_to_create_an_Edge_object_from_a_row, rows)
            pool.close()
            pool.join()
```

might that speed things up by the number of CPUs? arax.ncats.io has 16.

**Comment by edeutsch** [comment]
(although I suppose the easier thing is to make sure that the row to Edge object conversion that gets run 1.3 million times is as lean as possible?)

**Comment by amykglen** [comment]
closing this issue since there is essentially no longer a post-processing step for plover queries
