### ISSUE TITLE
How can I setup the synonym tool locally?

### ISSUE THREAD

**Issue by krishxmatta** [RTXteam/RTX#1339]
Hi all, I took a look at the ARAX website's synonym tool, and found that it would be very helpful for a project I'm doing. I attempted to setup the Node Synonymizer locally, but after running `dump_kg2_node_data.py`, it said that a file `configv2.json` was missing. Could someone please assist me/point me to any documentation regarding the synonymizer? I appreciate it, thank you.

**Comment by saramsey** [comment]
Directing this to @finnagin

**Comment by saramsey** [comment]
Note to @finnagin:  it appears that `configv2.json` contains ARAX server host passwords, so I don't think we should share it outside the Translator community without redacting passwords, unless we've had an opportunity to discuss the use-case with the requestor. But sharing a password-redacted file just to illustrate the file format, is fine.

**Comment by finnagin** [comment]
Looks like maybe this fell through the cracks a while ago. Closing since this is so old but feel free to reopen @krishxmatta is this is still relevant.
