### ISSUE TITLE
do these two apparently contradictory edges make sense?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1341]
In today's mini-hackathon meeting, the following query graph was posed to ARAX by Chris Bizon:
```
{
            "nodes": {
                "a": {
                    "category": "biolink:ChemicalSubstance"
                },
                "b": {
                    "category": "biolink:Gene",
                    "id": "NCBIGENE:2710"
                }
            },
            "edges": {
                "ab": {
                    "subject": "b",
                    "object": "a"
                }
            }
       
    }
```
Results are cached here:
https://arax.ncats.io/?r=6388

Result 5 looks like this:
<img width="1031" alt="Screen Shot 2021-04-05 at 11 14 26 AM" src="https://user-images.githubusercontent.com/5562107/113609012-1b78cc80-9600-11eb-848e-9180639699f4.png">

**Comment by saramsey** [comment]
See also this edge on result 5:
<img width="1023" alt="Screen Shot 2021-04-05 at 11 15 18 AM" src="https://user-images.githubusercontent.com/5562107/113609123-38150480-9600-11eb-8063-56786eea8db1.png">

**Comment by saramsey** [comment]
Both edges come from SemMedDB. Each edge has two PMIDs in the `publications` field.

**Comment by saramsey** [comment]
In KG2, the `biolink:positively_regulates_entity_to_entity` edge comes from this:
```
{
  "predicate": "biolink:positively_regulates_entity_to_entity",
  "negated": "False",
  "relation_label": "stimulates",
  "publications_info": "{'PMID:16524879': {'publication date': '2006 May 12', 'sentence': 'After Rosiglitazone treatment, increase of either pyruvate- or glycerol-dependent fatty acid re-esterification was strictly correlated to that of phosphoenolpyruvate carboxykinase and glycerol kinase, the key enzymes of each pathway, but depended on BMI of the women.', 'subject score': 1000, 'object score': 820}, 'PMID:9228030': {'publication date': '1997 Jul 25', 'sentence': 'We conclude from these studies that glycerol kinase expression is sufficient to activate glycerol signaling in beta cells, showing that the failure of normal islets to respond to this substrate is due to a lack of this enzyme activity.', 'subject score': 901, 'object score': 888}}",
  "subject": "UMLS:C0017868",
  "predicate_label": "positively_regulates_entity_to_entity",
  "provided_by": [
    "SEMMEDDB:"
  ],
  "update_date": "2019-04-29 21:37:59",
  "publications": [
    "PMID:16524879",
    "PMID:9228030"
  ],
  "relation": "SEMMEDDB:stimulates",
  "object": "UMLS:C0017861"
}
```

**Comment by saramsey** [comment]
The above-shown `biolink:negatively_regulates_entity_to_entity` edge comes from this edge in KG2:
```
{
  "predicate": "biolink:negatively_regulates_entity_to_entity",
  "negated": "False",
  "relation_label": "inhibits",
  "publications_info": "{'PMID:18429748': {'publication date': '2008 Apr', 'sentence': 'Therefore increases in glycerol kinase and glycerol-3-phosphate dehydrogenase were associated with a decrease in fasting blood glycerol levels in CR animals.', 'subject score': 1000, 'object score': 833}, 'PMID:5801670': {'publication date': '1969 May', 'sentence': 'When the concentration of ATP is low the activity of glycerol kinase is inhibited by high concentrations of glycerol; but when the concentration of ATP is high there is no inhibition and the double-reciprocal plot is linear, providing a K(m) for glycerol of 3.16x10(-6)m.', 'subject score': 1000, 'object score': 1000}}",
  "subject": "UMLS:C0017868",
  "predicate_label": "negatively_regulates_entity_to_entity",
  "provided_by": [
    "SEMMEDDB:"
  ],
  "update_date": "2019-04-30 20:54:01",
  "publications": [
    "PMID:18429748",
    "PMID:5801670"
  ],
  "relation": "SEMMEDDB:inhibits",
  "object": "UMLS:C0017861"
}
```

**Comment by saramsey** [comment]
Everything looks legit here. I am going to close this issue out, as there doesn't appear to be a bug. It's just that SemMedDB inferences can sometimes be contradictory.

**Comment by cbizon** [comment]
Yep, that looks right to me.  Does arax have a source of reaction data (Kegg, metacyc, etc...)?

**Comment by saramsey** [comment]
> Yep, that looks right to me. Does arax have a source of reaction data (Kegg, metacyc, etc...)?

Good question!
- Reactome should be in the next version of KG2 (right @ericawood?). See #636.
- KG2 has PathWhiz pathways, though the PathWhiz reactions are not named.
- We don't have the pathway reaction-level data from KEGG, as that KS is paywalled. We do have KEGG compound nodes.

**Comment by saramsey** [comment]
I note that this issue actually brought another issue (#1342) to my attention, so thank you!

**Comment by ericawood** [comment]
> Reactome should be in the next version of KG2 (right @ericawood?). See #636.

Yes, Reactome will be in the next version of KG2. It's reactions do have names.

> KG2 has PathWhiz pathways, though the PathWhiz reactions are not named.

Also true, thought you can derive their names by retrieving the names of their reactants and products. (Those were the names listed in the PathWhiz browser but not directly available in the dump).
