### ISSUE TITLE
DRUGBANK:category predicate remap should be fixed?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1343]
I think maybe the predicate remapping entry for `DRUGBANK:category` (which is currently mapping to `biolink:related_to`) is not sufficiently precise. I think `biolink:subclass_of` would be a better fit. A couple of examples should be checked to corroborate this and then we can fix the entry in `predicate-remap.yaml`.

https://github.com/RTXteam/RTX/blob/6fa597807f3f91ce294b7b4660f563950d201f54/code/kg2/predicate-remap.yaml#L569

**Comment by ericawood** [comment]
Here's some examples: (the images are from the DrugBank browser)

### `DRUGBANK:DB00001` ([Lepirudin](https://go.drugbank.com/drugs/DB00001)):
![image](https://user-images.githubusercontent.com/36611732/113626311-d9a75080-9616-11eb-85fc-aca3fa83843a.png)
- `DRUGBANK:DB00001`--`DRUGBANK:category`->`MESH:D000602` ([Amino Acids, Peptides, and Proteins](https://id.nlm.nih.gov/mesh/2017/D000602.html))
- `DRUGBANK:DB00001`--`DRUGBANK:category`->`MESH:D000925` ([Anticoagulants](https://id.nlm.nih.gov/mesh/2017/D000925.html))
- `DRUGBANK:DB00001`--`DRUGBANK:category`->`MESH:D058833` ([Antithrombin Proteins](https://id.nlm.nih.gov/mesh/2017/D058833.html))
- `DRUGBANK:DB00001`--`DRUGBANK:category`->`MESH:D000991` ([Antithrombins](https://id.nlm.nih.gov/mesh/2017/D000991.html))
- `DRUGBANK:DB00001`--`DRUGBANK:category`->`MESH:D002317` ([Cardiovascular Agents](https://id.nlm.nih.gov/mesh/2017/D002317.html))
- `DRUGBANK:DB00001`--`DRUGBANK:category`->`MESH:D004791` ([Enzyme Inhibitors](https://id.nlm.nih.gov/mesh/2017/D004791.html))
- `DRUGBANK:DB00001`--`DRUGBANK:category`->`MESH:D050299` ([Fibrin Modulating Agents](https://id.nlm.nih.gov/mesh/2017/D050299.html))
- `DRUGBANK:DB00001`--`DRUGBANK:category`->`MESH:D006401` ([Hematologic Agents](https://id.nlm.nih.gov/mesh/2017/D006401.html))
- `DRUGBANK:DB00001`--`DRUGBANK:category`->`MESH:D010455` ([Peptides](https://id.nlm.nih.gov/mesh/2017/D010455.html))
- `DRUGBANK:DB00001`--`DRUGBANK:category`->`MESH:D011480` ([Protease Inhibitors](https://id.nlm.nih.gov/mesh/2017/D011480.html))
- `DRUGBANK:DB00001`--`DRUGBANK:category`->`MESH:D011506` ([Proteins](https://id.nlm.nih.gov/mesh/2017/D011506.html))
- `DRUGBANK:DB00001`--`DRUGBANK:category`->`MESH:D015842` ([Serine Protease Inhibitors](https://id.nlm.nih.gov/mesh/2017/D015842.html))
- `DRUGBANK:DB00001`--`DRUGBANK:category`->`MESH:D015843` ([Serpins](https://id.nlm.nih.gov/mesh/2017/D015843.html))

### `DRUGBANK:DB00004` ([Denileukin diftitox](https://go.drugbank.com/drugs/DB00004)):
![image](https://user-images.githubusercontent.com/36611732/113626273-cdbb8e80-9616-11eb-999a-88d4534c5c64.png)
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D036002` ([ADP Ribose Transferases](https://id.nlm.nih.gov/mesh/2017/D036002.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D000602` ([Amino Acids, Peptides, and Proteins](https://id.nlm.nih.gov/mesh/2017/D000602.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D036002` ([ADP Ribose Transferases](https://id.nlm.nih.gov/mesh/2017/D036002.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D000970` ([Antineoplastic Agents](https://id.nlm.nih.gov/mesh/2017/D000970.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D001427` ([Bacterial Toxins](https://id.nlm.nih.gov/mesh/2017/D001427.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D001685` ([Biological Factors](https://id.nlm.nih.gov/mesh/2017/D001685.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D016207` ([Cytokines](https://id.nlm.nih.gov/mesh/2017/D016207.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D004798` ([Enzymes](https://id.nlm.nih.gov/mesh/2017/D004798.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D045762` ([Enzymes and Coenzymes](https://id.nlm.nih.gov/mesh/2017/D045762.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D016695` ([Glycosyltransferases](https://id.nlm.nih.gov/mesh/2017/D016695.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D036341` ([Intercellular Signaling Peptides and Proteins](https://id.nlm.nih.gov/mesh/2017/D036341.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D007378` ([Interleukins](https://id.nlm.nih.gov/mesh/2017/D007378.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D008222` ([Lymphokines](https://id.nlm.nih.gov/mesh/2017/D008222.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D010430` ([Pentosyltransferases](https://id.nlm.nih.gov/mesh/2017/D010430.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D010455` ([Peptides](https://id.nlm.nih.gov/mesh/2017/D010455.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D011506` ([Proteins](https://id.nlm.nih.gov/mesh/2017/D011506.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D011994` ([Recombinant Proteins](https://id.nlm.nih.gov/mesh/2017/D011994.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D014118` ([Toxins, Biological](https://id.nlm.nih.gov/mesh/2017/D014118.html))
- `DRUGBANK:DB00004`--`DRUGBANK:category`->`MESH:D014166` ([Transferases](https://id.nlm.nih.gov/mesh/2017/D014166.html))

**Comment by saramsey** [comment]
Thank you, @ericawood.  What do you think of using `biolink:subclass_of`?  It's a bit odd, since normally we use `subclass_of` *within* an ontology and not cross-ontology. But on the other hand, it would provide more information than `related_to`, right?

**Comment by ericawood** [comment]
> Thank you, @ericawood. What do you think of using `biolink:subclass_of`? It's a bit odd, since normally we use `subclass_of` _within_ an ontology and not cross-ontology. But on the other hand, it would provide more information than `related_to`, right?

I agree that it seems a bit odd. However, given the wide variety of meaning of `related_to`, I think that more specific would be helpful in this instance to give actual meaning to the edges.

**Comment by saramsey** [comment]
Maybe let's go for it?  We can always change our mind in the future, if something better than `subclass_of` becomes available in Biolink.

**Comment by kvarforl** [comment]
looks fixed in kg2.6.0 :)
