### ISSUE TITLE
ARAX Ranker in SmartAPI?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1347]
I note that ARAGORN and ROBOKOP advertise ranking services in SmartAPI:
https://smart-api.info/registry?q=ranker&tags=translator

<img width="895" alt="Screen Shot 2021-04-06 at 10 40 08 AM" src="https://user-images.githubusercontent.com/5562107/113754811-78d65180-96c4-11eb-9699-9e9904e4b7d9.png">

should we do the same for the ARAX ranker?

**Comment by dkoslicki** [comment]
I'd be fine with putting the ranker in smartAPI, but don't really see the usefulness of that (given that the ARS is calling ARAs/KPs, and not just any-ol-thing it finds in the registry). Anyone know the cost-benefit of registering it?

**Comment by saramsey** [comment]
> I'd be fine with putting the ranker in smartAPI, but don't really see the usefulness of that (given that the ARS is calling ARAs/KPs, and not just any-ol-thing it finds in the registry). Anyone know the cost-benefit of registering it?

Fair point!  Figured it was worth asking.

**Comment by edeutsch** [comment]
okay to close?

**Comment by dkoslicki** [comment]
I think this can be closed, but correct me if I'm wrong @saramsey . Note that ARAGORN & ROBOKOP no longer expose their rankers on SmartAPI
