### ISSUE TITLE
CHP Expand - don't error out on unsupported curie?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1349]
in working on #1236, I've noticed that CHP Expand seems to return an error when it doesn't recognize a curie in the QG. like for this query (on production):
```
add_qnode(id=NCBIGene:1803, category=biolink:Gene, key=n00)
add_qnode(category=biolink:Disease, key=n01)
add_qedge(subject=n00, object=n01, key=e00, predicate=biolink:gene_associated_with_condition)
expand(kp=CHP)
resultify()
```
it says:
`2021-04-07T18:52:06.636159 ERROR: The curie id of NCBIGene:1803 is not allowable based on CHP client`

but with issue #1236, it's become important that execution doesn't halt when something like this happens. instead, the CHPQuerier should just return no answers; Expander itself will then later throw an error saying no answers were found, if necessary.

you could still log some sort of entry about how that curie isn't allowable for CHP, but I think it just shouldn't be an error.

(changes for this issue can go directly in `master`.)

**Comment by chunyuma** [comment]
Hi @amykglen, I turned all `log.error` in  CHP Expand to `log.warning` except for the `CategoryError` and `BadEdgeError`. So right now the query like this (eg. CHP client doesn't recognize a curie in the QG) should not report an error but the Expander itself will also throw an error if there is no path.
