### ISSUE TITLE
DTD Expand 'Unhashable type 'list'' error

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1355]
seeing an error with this query on production (and in `master`):
```
add_qnode(key=n00, id=[CHEMBL.COMPOUND:CHEMBL112, CHEMBL.COMPOUND:CHEMBL521], category=biolink:ChemicalSubstance)
add_qnode(key=n01, category=biolink:Disease)
add_qedge(key=e00, subject=n01, object=n00)
expand(kp=DTD)
resultify()
```
`ERROR: An uncaught error occurred: unhashable type: 'list': ['Traceback (most recent call last):\n',...`

**Comment by chunyuma** [comment]
Hi @amykglen, this problem should be fixed now.

**Comment by dkoslicki** [comment]
Confirmed that this is working on `/test`, but be aware @amykglen , if you don't limit the number of results, you get 10K+ results.

**Comment by amykglen** [comment]
nice, looks good, thanks!
