### ISSUE TITLE
QGI should no longer tell Expand() what to do

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1356]
We agreed at today's call that the QueryGraphInterpreter should no longer tell Expand() what KPs to consult. It will now do it on its own. Eric will make the change.

**Comment by edeutsch** [comment]
@amykglen and anyone else: are you happy with this change: https://github.com/RTXteam/RTX/commit/5aa403be7a1af5a75f6b76e3500d77e47885091b

**Comment by amykglen** [comment]
looks good to me, thanks! just doing some final testing now on #1236 and then will merge that to master as well.
