### ISSUE TITLE
Decorate nodes found by other KPs with iris/descriptions from KG2c?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1359]
when non-KG2 KPs contribute nodes to the answer of an ARAX query, they typically don't have IRIs or descriptions, both of which we find very useful in the UI... now that expand uses multiple KPs more often, I think it'll become much more common to see such sparse nodes in our results.

I think in the large majority of cases these nodes other KPs return do exist in KG2c, and so technically we could look up descriptions/iris (and more) for them... not sure if this would be something worth pursuing?

**Comment by dkoslicki** [comment]
I’ve actually thought of the same thing. For example, I’ve noticed that BTE doesn’t have IRI’s nor descriptions, so at times leads me to googling to figure out what a node is. If we could take this info from KG2/C, I vote yes!

**Comment by edeutsch** [comment]
I think that would be great!

**Comment by amykglen** [comment]
this is looking good to me on production! example: https://arax.ncats.io/?r=7556 (nodes from BTE have iris/descriptions, and some additional attributes from KG2c)
