### ISSUE TITLE
ARAX/KG2 mislabeled in smartAPI

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1362]
From [this issue](https://github.com/NCATSTranslator/testing/issues/42) it appears that the `x-translator` tag for ARAX/KG2 lists it as an ARA instead of a KP. This is the reason for the odd empty list of KP’s that @ericawood noted in #1326 .

Assigning @edeutsch since I think he handled the smartAPI registration, but please correct me if I’m wrong.

**Comment by saramsey** [comment]
good catch

**Comment by edeutsch** [comment]
I believe this is all fixed now. Let me know if you have further trouble.

**Comment by dkoslicki** [comment]
Thanks @edeutsch, looks good to me!
