### ISSUE TITLE
Inconsistent capitalization of ensemble curies

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1366]
Looks like ensembl IDs aren’t all capitalized in the same way:
` ` `
match (n) where n.id starts with "Ensembl" return count(n)
` ` `
Returns a few hundred and
```
match (n) where n.id starts with "ENSEMBL" return count(n)
```
Returns ~68K

**Comment by saramsey** [comment]
Looks like the Protein Ontology is the culprit

<img width="748" alt="Screen Shot 2021-04-11 at 4 46 27 PM" src="https://user-images.githubusercontent.com/5562107/114325548-838a4f80-9ae5-11eb-9af6-c573ded08be3.png">

**Comment by saramsey** [comment]
Hi @ericawood and @kvarforl can you take a look at `pr.owl` to see where the incorrect (at least, not Biolink-compliant) CURIE prefixes `Ensembl:` are coming from?  I wager from some kind of OBO `xref`.

**Comment by kvarforl** [comment]
Here they are, from kg2steve:
```
ubuntu@ip-172-31-3-188:~/kg2-code$ grep -m 20  "Ensembl:" ~/kg2-build/pr.owl
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:AT1G05760</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA14961</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA15089</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA15090</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA15121</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA15178</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA15248</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA15252</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA15823</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA15962</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA16002</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA16005</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA16036</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA16125</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA16126</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA16223</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA16506</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA22515</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA35363</oboInOwl:id>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Ensembl:BAA35975</oboInOwl:id>
```

**Comment by ericawood** [comment]
Ah, this just got more interesting:
`match (n) where n.id starts with "Ensembl" return distinct n.id limit 100`
returns

n.id|
--|
"EnsemblGenomes:BAB94876"
"EnsemblGenomes:BAB94877"
"EnsemblGenomes:BAB94445"
"EnsemblGenomes:BMEI0430"
"EnsemblGenomes:BMEI0433"
"EnsemblGenomes:BMEI0451"
"EnsemblGenomes:BMEI0455"
"EnsemblGenomes:BAB42226"
"EnsemblGenomes:BMEI0997"
"EnsemblGenomes:BMEI0605"
"EnsemblGenomes:BMEI0271"
"EnsemblGenomes:BMEI0275"
"EnsemblGenomes:BMEI0266"
"EnsemblGenomes:BMEI0267"
"EnsemblGenomes:BMEI0296"
"EnsemblGenomes:BMEI0258"
"EnsemblGenomes:BMEI0382"
"EnsemblGenomes:BMEI0384"
"EnsemblGenomes:BMEI0169"
"EnsemblGenomes:BMEI0305"
"EnsemblGenomes:BMEI0320"
"EnsemblGenomes:BMEI0358"
"EnsemblGenomes:BMEI0357"
"EnsemblGenomes:BMEI0359"
...

and
`match (n) where n.id starts with "Ensembl" return distinct split(n.id, ':')[0]`
returns 

split(n.id, ':')[0]
--|
"EnsemblGenomes"

Thus, it doesn't look like these are getting assigned `Ensembl` prefixes after all.
Per https://github.com/RTXteam/RTX/blob/a50d33a34846b38217dc8c6d7d35def4e0d7032b/code/kg2/curies-to-urls-map.yaml#L103
this is what we'd expect to happen.

**Comment by kvarforl** [comment]
Nice sleuthing Erica!!!

**Comment by dkoslicki** [comment]
Ah, interesting! Is `EnsemblGenomes` a biolink compliant CURIE prefix?

**Comment by ericawood** [comment]
`EnsemblGenomes` is not present in the biolink model, but it's existence in the `curies-to-urls-map` and in `kg2_util.py` passes the validation tests.

**Comment by saramsey** [comment]
Confirmed, there is no `EnsemblGenomes` in `biolink-model.yaml` and it's also not in the `context.jsonldl` file on the Biolink GitHub area.

I'm not seeing an issue here. Recommend to close?

**Comment by dkoslicki** [comment]
Looks good to me! Guess I'll need to be careful with `starts with` in cypher
