### ISSUE TITLE
ARAR parsing error, or BTE error, anyone know which?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1368]
For this DSL:
```
add_qnode(key=N0,id=MONDO:0005301,category=biolink:Disease)
add_qnode(key=N1,id=MONDO:0017611,category=biolink:Disease)
add_qedge(key=E0,subject=N0,object=N1)
expand(kp=BTE)
resultify(ignore_edge_direction=true)
filter_results(action=limit_number_of_results,max_results=100,prune_kg=true)
```

I get the following error:
``
2021-04-12T16:20:06.224885 DEBUG: BTE: Getting preferred curies for N0 nodes returned in this step
2021-04-12T16:20:06.257638 DEBUG: BTE: After deduplication, answer KG counts are: E0: 11747, N0: 0, N1: 4282
2021-04-12T16:20:06.260233 DEBUG: Merging answer into Message.KnowledgeGraph
2021-04-12T16:20:06.268781 DEBUG: Pruning any paths that are now dead ends
2021-04-12T16:20:06.269177 ERROR: An uncaught error occurred: 'N0': ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 592, in execute_processing_plan\n expander.apply(response, action[\'parameters\'], mode=mode)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 375, in apply\n self._prune_dead_end_paths(overarching_kg, query_sub_graph, qedge, response)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 781, in _prune_dead_end_paths\n if edge.subject in organized_kg.nodes_by_qg_id[current_qedge.subject] \\\n', "KeyError: 'N0'\n"]
```

So it looks like node N0 isn’t associated with anything, so there are a bunch of dangling edges. Is that `expand`’s problem, or BTEs?

**Comment by amykglen** [comment]
definitely seems to be something going on with expand - but strangely, when I run it locally in `master`, this error doesn't happen (just a NoResults error).. maybe it's something that's already been fixed in master but hasn't been rolled out yet? 

I'll investigate a bit more though...

**Comment by edeutsch** [comment]
in case related, I have just rolled out master to all deployments

**Comment by amykglen** [comment]
thanks - yeah, I realized it was indeed reproducible in `master` (user error). figured out the problem and pushed the fix to `master`. will verify when `master` is next rolled out.

it's interesting that BTE's response to this curie-to-curie query includes thousands of nodes (I would generally expect it to include 2 - the 2 specified in the QG). it looks to me like the additional nodes might be 'subclass_of' nodes specified in the QG... the new paradigm we're in I suppose. :)

**Comment by edeutsch** [comment]
master just now again rolled out to /test and /kg2 for testing. Not other deployments.

**Comment by amykglen** [comment]
thanks - well certainly the error on our end seems resolved! https://arax.ncats.io/test/?r=7044

BTE's results are weird, even when considering the fact that they might be returning nodes that are subclasses of ones specified in the QG. for example, I don't think 'rare eyelid malformation' and 'mumps' are subclasses of 'pituitary adenoma'? not sure what's going on there... maybe this is worth reporting to the BTE folks? the QG we send to their API for this query looks like this: 
```
{
  "message":{
    "query_graph":{
      "nodes":{
        "N0":{
          "id":"MONDO:0005301",
          "category":"biolink:Disease"
        },
        "N1":{
          "id":"MONDO:0017611",
          "category":"biolink:Disease"
        }
      },
      "edges":{
        "E0":{
          "subject":"N0",
          "object":"N1"
        }
      }
    }
  }
}
```

**Comment by amykglen** [comment]
I'm seeing similar problems for other BTE curie-to-curie queries, like: https://arax.ncats.io/test/?r=7048

it's almost like they're ignoring the fact that there's a curie on qnode N1? that's my best guess... I'll ask them about this.

**Comment by amykglen** [comment]
ok, Kevin Xin said this is a known issue with BTE that he plans to fix (it happens with all curie-to-curie queries -- BTE basically ignores the `id` on qnode N1).

as a temporary measure, I added a rule to `expand` so that it doesn't choose to use BTE for curie-to-curie queries. (though that doesn't help @dkoslicki's query of course, since he specified `kp=BTE`.)

**Comment by amykglen** [comment]
ok to close this issue @dkoslicki? since we don't have control over when BTE fixes their bug with curie-to-curie queries, not sure there's anything else for us to do, since I already made it so that expand doesn't choose to use BTE for such queries.

I suppose I could also make expand throw an error if someone tries to run DSL with `kp=BTE` for a curie-to-curie query, if that seems like desirable behavior. but otherwise I don't think there's anything else we can do here.

**Comment by dkoslicki** [comment]
Looks good to me, thanks @amykglen
