### ISSUE TITLE
DSL documentation

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1371]
It appears the DSL documentation is lagging a bit. In particular, we have some nice new fancy features like `expand()` which intelligently picks the KPs to use, but this remains undocumented. Can everyone that works on DSL-related things take a look and make sure "their" command's documentation is up to date?

**Comment by amykglen** [comment]
whoops, yep, I forgot to update the documentation for #1236. pushed that to `master`.

**Comment by dkoslicki** [comment]
@chunyuma Just FYI, with your recent new features for #1372, the documentation wasn't updated so the new feature wasn't exposed in the UI. I've already done this, but be sure to keep this in mind for the future.

**Comment by chunyuma** [comment]
Ah, I will remember it, thanks for reminder. BTW, could you please tell me what script I use to update the documentation? Or I should update it manually?

**Comment by dkoslicki** [comment]
There's a script under the documentation folder called `document_dsl_commands.py` that auto generates the documentation if you've updated the doc strings in the ARAX_overlay.py

**Comment by chunyuma** [comment]
Ah, I see, thanks @dkoslicki

**Comment by finnagin** [comment]
@dkoslicki @chunyuma @amykglen Is this still relevant?

**Comment by dkoslicki** [comment]
Nope, good to close
