### ISSUE TITLE
Add DTD threshold and slow mode to overlay options

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1372]
Currently, `expand(kp=DTD)` has more parameters/options than `overlay(action=predict_drug_treats_disease)`. It would be good to have the same options (specifically the threshold and slow mode) for the `overlay` part as well. I.e. even if an edge between disease X and drug Y does not exist in KG2, we still want the ability to overlay edges decorated with probabilities. 

@chunyuma This is not high priority, so can be done whenever you have time.

**Comment by chunyuma** [comment]
Hi @dkoslicki, I've added `threshold` option and `slow_mode` option to `overlay(action=predict_drug_treats_disease)`. 

Here is one example:
```
  "add_qnode(id=DOID:9008, key=n0)",
  "add_qnode(category=biolink:ChemicalSubstance, key=n1)",
  "add_qedge(subject=n0, object=n1, key=e0)",
  "expand(edge_key=e0, kp=ARAX/KG1)",
  "overlay(action=predict_drug_treats_disease, threshold=0.4, slow_mode=false)",
  "resultify()",
  "return(message=true, store=false)"
```

The `slow_mode` option allows `t`, `true`, `True`, `f`, `false`, `False`.

**Comment by chunyuma** [comment]
I will close this issue since this issue has been solved. @dkoslicki, feels free to reopen it if you find any related problems.

**Comment by dkoslicki** [comment]
Thanks @chunyuma !
