### ISSUE TITLE
Levonorgestrel has two preferred nodes in kg2.5.2c

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1380]
Hi @edeutsch and @amykglen,

I want to report this issue that I just found in kg2.5.2c (endpoint: `kg2c-5-2.rtx.ai`)

For curie id: `UMLS:C0023566` which is `Levonorgestrel`, based on UMLS Terminology Service [here](https://uts.nlm.nih.gov/uts/umls/concept/C0023566):

![Screen Shot 2021-04-16 at 2 13 32 PM](https://user-images.githubusercontent.com/20031672/115066741-f1f05880-9ebd-11eb-99e5-c27421e8fb2c.png)

It has a synonymous Drugbank ID: `DB00367`:

![Screen Shot 2021-04-16 at 2 14 51 PM](https://user-images.githubusercontent.com/20031672/115066882-2106ca00-9ebe-11eb-8239-b8c10e312326.png)

However, if I searched both these two IDs on kg2.5.2c, it actually gave me two different preferred nodes.
```
match (n) where 'UMLS:C0023566' in n.equivalent_curies return n.id, n.name, n.category,n.equivalent_curies
```

n.id | n.name | n.category | n.equivalent_curies
-- | -- | -- | --
"RXNORM:6373" | "Levonorgestrel" | "biolink:Drug" | ["ATC:G03AC03", "ATC:G03AD01", "MESH:D016912", "NCIT:C47585", "NCIT:C52193", "NDDF:001304", "PDQ:CDR0000459975", "PDQ:CDR0000534399", "RXNORM:6373", "SNOMED:126109000", "UMLS:C0023566", "UMLS:C0591811", "UMLS:C0591873", "UMLS:C0699698", "UMLS:C0699699", "UMLS:C0876128", "UMLS:C1145675", "UMLS:C1450003", "UMLS:C1450004", "UMLS:C1450005", "UMLS:C1450006", "UMLS:C1708694", "UMLS:C4082601", "UMLS:C4316937", "VANDF:4018027"]

```
match (n) where 'DRUGBANK:DB00367' in n.equivalent_curies return n.id, n.name, n.category,n.equivalent_curies
```

n.id | n.name | n.category | n.equivalent_curies
-- | -- | -- | --
"CHEMBL.COMPOUND:CHEMBL1389" | "LEVONORGESTREL" | "biolink:ChemicalSubstance" | ["CHEBI:6443", "CHEBI:7630", "CHEMBL.COMPOUND:CHEMBL1389", "CHEMBL.COMPOUND:CHEMBL2107797", "DRUGBANK:DB00367", "DRUGBANK:DB09389", "HMDB:HMDB0014511", "MESH:D009644", "NCIT:C703", "NDDF:001303", "NDDF:001325", "PDQ:CDR0000039310", "RXNORM:7518", "SNOMED:126106007", "UMLS:C0028368", "UMLS:C0699168", "UMLS:C0699169", "UMLS:C0699170", "UMLS:C0701266", "VANDF:4018023"]

I'm wondering if this means there is a bug in `node sysnonymizer` or kg2c build.

**Comment by saramsey** [comment]
>I'm wondering if this means there is a bug in node sysnonymizer or kg2 build.

Hmm, at first glance I am not seeing a potential KG2 build bug here. Did you by chance mean "KG2c"?

**Comment by chunyuma** [comment]
@saramsey, sorry, my mistake, I meant kg2c build not kg2 build. Sorry about this typo.

**Comment by saramsey** [comment]
> @saramsey, sorry, my mistake, I meant kg2c build not kg2 build. Sorry about this typo.

no problem

**Comment by chunyuma** [comment]
Hi @edeutsch, can I check with you to see if this issue can be solved in the new version of Nodesynonymizer?

**Comment by amykglen** [comment]
the Levonorgestrel cluster in KG2.8.0.1c now includes both `UMLS:C0023566` and `DRUGBANK:DB00367`:

https://arax.ncats.io/devLM/?term=Levonorgestrel

![Screen Shot 2023-05-26 at 9 40 31 AM](https://github.com/RTXteam/RTX/assets/49423686/61e7d9fe-ed4a-4887-92e1-34594ab16545)

I'm going to close this issue but feel free to reopen it if you don't agree this is fixed, @chunyuma!
