### ISSUE TITLE
Including NGD edges greatly reduces result set

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1383]
Poking around the query associated with similarity reasoning [here](https://github.com/RTXteam/RTX/issues/1268#issuecomment-817464822) in #1268, I noticed the following: including NGD edges in the JSON query reduces the number of results found. This query returns 100 answers:
```
{
   "edges": {
      "e00": {
         "subject":   "n00",
         "object":    "n01",
         "predicate": "biolink:interacts_with"
      }
   },
   "nodes": {
      "n00": {
         "id":        "CHEMBL.COMPOUND:CHEMBL112",
         "category":  "biolink:ChemicalSubstance"
      },
      "n01": {
         "category":  "biolink:Protein"
      }
   }
}
```
while this one only returns 2:
```
{
  "edges": {
    "N1": {
      "object": "n1",
      "predicate": "biolink:has_normalized_google_distance_with",
      "relation": "N1",
      "subject": "n0"
    },
    "e0": {
      "exclude": false,
      "object": "n1",
      "predicate": "biolink:interacts_with",
      "subject": "n0"
    }
  },
  "nodes": {
    "n0": {
      "id": "CHEMBL.COMPOUND:CHEMBL112",
      "is_set": false
    },
    "n1": {
      "category": "biolink:Protein",
      "is_set": false
    }
  }
}
```
This is concerning due to our NGD adding virtual edges to the QG, so it really should be idempotent: if you click the example on our UI, then copy the returned JSON QG, it really should give the exact same results. I don't know if this is an `expand` issue or an NGD issue (but I suspect it's `expand`).

**Comment by amykglen** [comment]
hmm, so I guess in my understanding, those two JSON queries _shouldn't_ return the same results. your second query graph triggers an 'expand using NGD' (in addition to KG2) for qedge N1, which has a default threshold of 0.5 (it throws out any edges with NGDs below that). that explains why you're seeing fewer results.

should NGD not be used as a KP for that kind of qedge? if not, what kind of qedge should it be triggered for?

**Comment by amykglen** [comment]
yeah, good point. I concur!

**Comment by finnagin** [comment]
Could we add a workflow section like we do [here](https://github.com/finnagin/OperationsAndWorkflows/blob/main/examples/overlay/messages/07_input_ngd.json#L55-L60) with something like a  a "filter_kgraph_attribute"?

**Comment by finnagin** [comment]
@dkoslicki The proposal after the meeting today is to add a `option_group_id` to all virtual edges in the query graph. Any objections to that?

**Comment by dkoslicki** [comment]
No objections! I think that’s a great idea

**Comment by finnagin** [comment]
Closing since `option_group_id ` was already implemented
