### ISSUE TITLE
return (somewhere) the total number of potential result?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1388]
This idea came up in the stand-up meeting today. @dkoslicki was presenting for our team, ARAX's results for a query about Snyder-Robinson Syndrome (a rare XLID syndrome). In interpreting the 100 results that were returned by ARAX, we were thinking it would be helpful to *also* know how many results (say, *N* results) *would* be returned if ARAX didn't apply the hard-coded 100-result limit. Is that something that can be slotted somewhere into the return message?  

In this particular query, the reason why we think it would be useful to know *N* is because all 100 results had the gene NR3C1 in it. We were wondering how many results total there might be, in order to interpret whether this finding is maybe just an artifact of the 100-result cutoff and relative degeneracy of result graph confidence scores on the top end (is that right, @dkoslicki ?)

**Comment by dkoslicki** [comment]
Well summarized @saramsey ! And I think technically it would be easy for @finnagin to implement, but we would need to know where to stick this information in the TRAPI response. @edeutsch might know where it should go

**Comment by saramsey** [comment]
Good idea tagging @edeutsch

**Comment by finnagin** [comment]
@edeutsch has this already been done/is this still relevant?

**Comment by dkoslicki** [comment]
I don't think this has been done @finnagin , and you would want to ask @isbluis how he'd want that information passed through so it could be displayed. @edeutsch might know where it goes in TRAPI

**Comment by isbluis** [comment]
I think it would be best to have that information passed via an ad-hoc element in TRAPI that @edeutsch can suggest.

Alternatively, the UI could just pick it up from the log messages and display it more prominently than it already is; e.g.
https://arax.ncats.io/index.html?r=36257

![image](https://user-images.githubusercontent.com/37852256/152289507-d7886f8f-c321-443d-9d88-f1a2e46d5022.png)

**Comment by edeutsch** [comment]
I think at one point we had Message.n_results to store that. But then Message was put under Response and Message was locked down to not allow additionalProperties. So n_results was just dropped.

No reason we couldn't add Response.n_results, though. I doubt anyone else would go along with making that standard TRAPI. But we can stick it in if we want to for our own results.

**Comment by isbluis** [comment]
Would it be better to be more explicit, e.g. Response.total_n_results ?  Overkill?

**Comment by edeutsch** [comment]
yeah, better. if having n_ in the middle seems weird, could be Response.total_results_count

**Comment by finnagin** [comment]
@isbluis I added the number of results as a property of the response called `total_results_count` [here](https://github.com/RTXteam/RTX/blob/6a1c95d6b616b4e6d79b9c20a5b1de079517bc36/code/ARAX/ARAXQuery/ARAX_resultify.py#L690) right after it outputs that info message above.

**Comment by isbluis** [comment]
Thanks for adding this, @finnagin.  Unfortunately, I do not see it in the response, e.g.:  https://arax.ncats.io/devLM/index.html?r=36352

Looking at the code, it seems that you are adding the count to the `log` object, and perhaps not the `response`?  I may be misunderstanding the code, so apologies if this is a red herring.

**Comment by edeutsch** [comment]
It would need to be copied from the logging object into the "envelope". I can do that.

**Comment by edeutsch** [comment]
ah, I realized that I would need to update the OpenAPI schema to have that pass through correctly.

As a temporary hack, I have placed it in Response.context.
which no one looks at anyway

This is now available in devED

Does this seem like what everyone wanted?
If we all like it, then I will go through the trouble of updating the schemas everywhere.

**Comment by edeutsch** [comment]
This is now rolled out everywhere except production.

https://arax.ncats.io/beta/?r=36411

This fix does not work for previous resultsets, only for new ones.
