### ISSUE TITLE
update UpdateNodesInfo.py to include a "synonyms" field in the KG

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#139]
For each node type, let's try to find a list of "synonyms" or "aliases".  These can be stored as a single string containing the semicolon-delimited list of known aliases for the node

**Comment by saramsey** [comment]
this work is being done as a part of #301

**Comment by dkoslicki** [comment]
Closing due to #788 And #707 #711 etc. unless @saramsey would still like synonyms stored in KG2 as node properties
