### ISSUE TITLE
DTD thinks it’s not a drug, but indeed it is

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1392]
In the process of running the query at https://arax.ncats.io/?r=7634, I noticed that DTD gave the following message: `WARNING: All potential categories of these nodes ['CHEBI:77746', 'KEGG:C00694', 'KEGG:C01064', 'KEGG:C01153', 'KEGG:C01997', 'KEGG:C02188', 'KEGG:C02729', 'KEGG:C03702', 'KEGG:C04090', 'KEGG:C04890', 'KEGG:C04922', 'KEGG:C04938', 'KEGG:C21776', 'PUBCHEM.COMPOUND:131801660', 'PUBCHEM.COMPOUND:131801661', 'PUBCHEM.COMPOUND:131801663', 'PUBCHEM.COMPOUND:131801665', 'PUBCHEM.COMPOUND:131801667', 'PUBCHEM.COMPOUND:131801669', 'PUBCHEM.COMPOUND:131801671', 'PUBCHEM.COMPOUND:131801673', 'PUBCHEM.COMPOUND:131801675', 'PUBCHEM.COMPOUND:131801677', 'PUBCHEM.COMPOUND:131801679', 'PUBCHEM.COMPOUND:131801681', 'PUBCHEM.COMPOUND:131801683', 'PUBCHEM.COMPOUND:22833524', 'PUBCHEM.COMPOUND:25201885', 'PUBCHEM.COMPOUND:52923852', 'PUBCHEM.COMPOUND:52923902', 'PUBCHEM.COMPOUND:52923914', 'PUBCHEM.COMPOUND:52923942', 'PUBCHEM.COMPOUND:52923956', 'PUBCHEM.COMPOUND:52923972', 'PUBCHEM.COMPOUND:52923974', 'PUBCHEM.COMPOUND:53478615', 'PUBCHEM.COMPOUND:53478705', 'PUBCHEM.COMPOUND:53478887', 'PUBCHEM.COMPOUND:53478889', 'PUBCHEM.COMPOUND:53479157', 'PUBCHEM.COMPOUND:53479223', 'PUBCHEM.COMPOUND:53479225', 'PUBCHEM.COMPOUND:53479245', 'PUBCHEM.COMPOUND:53479269', 'PUBCHEM.COMPOUND:53479271', 'PUBCHEM.COMPOUND:53479337', 'PUBCHEM.COMPOUND:53479401', 'PUBCHEM.COMPOUND:53479403', 'PUBCHEM.COMPOUND:53479405', 'PUBCHEM.COMPOUND:53479481', 'PUBCHEM.COMPOUND:53480721', 'PUBCHEM.COMPOUND:53480723', 'PUBCHEM.COMPOUND:53480725', 'PUBCHEM.COMPOUND:53480731', 'PUBCHEM.COMPOUND:53480771', 'PUBCHEM.COMPOUND:53480775', 'PUBCHEM.COMPOUND:53480777', 'PUBCHEM.COMPOUND:53480779', 'PUBCHEM.COMPOUND:53480789', 'PUBCHEM.COMPOUND:53480829', 'PUBCHEM.COMPOUND:53480833', 'PUBCHEM.COMPOUND:53481709', 'PUBCHEM.COMPOUND:53481713', 'PUBCHEM.COMPOUND:53481731', 'PUBCHEM.COMPOUND:53481733', 'PUBCHEM.COMPOUND:53481749', 'PUBCHEM.COMPOUND:53481751', 'PUBCHEM.COMPOUND:53481755', 'PUBCHEM.COMPOUND:53481757', 'PUBCHEM.COMPOUND:53481763', 'PUBCHEM.COMPOUND:53481769', 'PUBCHEM.COMPOUND:53481775'] don't contain drug or disease `

However, going to KG2c-5-2, some of these are indeed labeled drug, chemical substance, or both. Any idea why this might be?

**Comment by chunyuma** [comment]
Hi @dkoslicki, for this issue, I checked the DSL query that you used:
`expand(kp=DTD,edge_key=e2,continue_if_no_results=true,use_synonyms=true)`

You didn't set `DTD_threshold<0.8` or `DTD_slow_mode=true`, do by default, it used DTD database to get probability and as we discussed previously, using DTD database will check the node type. Currently only `['chemicalsubstance','drug']` are considered as `drug` but these nodes don't have either of these two node type in their `all_categories` attribute. Please see the table below:


```
match (n) where n.id in ['CHEBI:77746', 'KEGG:C00694', 'KEGG:C01064', 'KEGG:C01153', 'KEGG:C01997', 'KEGG:C02188', 'KEGG:C02729', 'KEGG:C03702', 'KEGG:C04090', 'KEGG:C04890', 'KEGG:C04922', 'KEGG:C04938', 'KEGG:C21776', 'PUBCHEM.COMPOUND:131801660', 'PUBCHEM.COMPOUND:131801661', 'PUBCHEM.COMPOUND:131801663', 'PUBCHEM.COMPOUND:131801665', 'PUBCHEM.COMPOUND:131801667', 'PUBCHEM.COMPOUND:131801669', 'PUBCHEM.COMPOUND:131801671', 'PUBCHEM.COMPOUND:131801673', 'PUBCHEM.COMPOUND:131801675', 'PUBCHEM.COMPOUND:131801677', 'PUBCHEM.COMPOUND:131801679', 'PUBCHEM.COMPOUND:131801681', 'PUBCHEM.COMPOUND:131801683', 'PUBCHEM.COMPOUND:22833524', 'PUBCHEM.COMPOUND:25201885', 'PUBCHEM.COMPOUND:52923852', 'PUBCHEM.COMPOUND:52923902', 'PUBCHEM.COMPOUND:52923914', 'PUBCHEM.COMPOUND:52923942', 'PUBCHEM.COMPOUND:52923956', 'PUBCHEM.COMPOUND:52923972', 'PUBCHEM.COMPOUND:52923974', 'PUBCHEM.COMPOUND:53478615', 'PUBCHEM.COMPOUND:53478705', 'PUBCHEM.COMPOUND:53478887', 'PUBCHEM.COMPOUND:53478889', 'PUBCHEM.COMPOUND:53479157', 'PUBCHEM.COMPOUND:53479223', 'PUBCHEM.COMPOUND:53479225', 'PUBCHEM.COMPOUND:53479245', 'PUBCHEM.COMPOUND:53479269', 'PUBCHEM.COMPOUND:53479271', 'PUBCHEM.COMPOUND:53479337', 'PUBCHEM.COMPOUND:53479401', 'PUBCHEM.COMPOUND:53479403', 'PUBCHEM.COMPOUND:53479405', 'PUBCHEM.COMPOUND:53479481', 'PUBCHEM.COMPOUND:53480721', 'PUBCHEM.COMPOUND:53480723', 'PUBCHEM.COMPOUND:53480725', 'PUBCHEM.COMPOUND:53480731', 'PUBCHEM.COMPOUND:53480771', 'PUBCHEM.COMPOUND:53480775', 'PUBCHEM.COMPOUND:53480777', 'PUBCHEM.COMPOUND:53480779', 'PUBCHEM.COMPOUND:53480789', 'PUBCHEM.COMPOUND:53480829', 'PUBCHEM.COMPOUND:53480833', 'PUBCHEM.COMPOUND:53481709', 'PUBCHEM.COMPOUND:53481713', 'PUBCHEM.COMPOUND:53481731', 'PUBCHEM.COMPOUND:53481733', 'PUBCHEM.COMPOUND:53481749', 'PUBCHEM.COMPOUND:53481751', 'PUBCHEM.COMPOUND:53481755', 'PUBCHEM.COMPOUND:53481757', 'PUBCHEM.COMPOUND:53481763', 'PUBCHEM.COMPOUND:53481769', 'PUBCHEM.COMPOUND:53481775'] return n.id, n.all_categories
```
n.id | n.all_categories
-- | --
"CHEBI:77746" | ["biolink:Metabolite"]
"KEGG:C04890" | ["biolink:Metabolite"]
"KEGG:C03702" | ["biolink:Metabolite"]
"KEGG:C01997" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:25201885" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:52923902" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:52923914" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:131801660" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:131801661" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:131801663" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:52923942" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:52923956" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:52923972" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:52923974" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53480721" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53480723" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53480725" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:131801665" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:131801667" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53480731" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53480771" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53480775" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53480777" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53480779" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:131801669" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:131801671" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:131801673" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:131801675" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53480789" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53480829" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53480833" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:131801677" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:131801679" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:131801681" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:131801683" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:22833524" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53479245" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53479269" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53479271" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53479337" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53479401" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53479403" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53479405" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53479481" | ["biolink:Metabolite"]
"KEGG:C02188" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53478615" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53478705" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53478887" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53478889" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53479157" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53479223" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53479225" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53481709" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53481713" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53481731" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53481733" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:52923852" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53481749" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53481751" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53481755" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53481757" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53481763" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53481769" | ["biolink:Metabolite"]
"PUBCHEM.COMPOUND:53481775" | ["biolink:Metabolite"]
"KEGG:C00694" | ["biolink:Metabolite"]
"KEGG:C04090" | ["biolink:Metabolite"]
"KEGG:C02729" | ["biolink:Metabolite"]
"KEGG:C01064" | ["biolink:Metabolite"]
"KEGG:C01153" | ["biolink:Metabolite"]
"KEGG:C21776" | ["biolink:Metabolite"]
"KEGG:C04922" | ["biolink:Metabolite"]
"KEGG:C04938" | ["biolink:Metabolite"]

**Comment by chunyuma** [comment]
I would suggest to set `expand(kp=DTD,edge_key=e2,continue_if_no_results=true,use_synonyms=true, DTD_slow_mode=true)` to solve this issue.

**Comment by dkoslicki** [comment]
Curious! I figured that since `match (n{id:"CHEBI:77746"}) return labels(n)` returns `["biolink:NamedThing", "biolink:BiologicalEntity", "biolink:ChemicalSubstance", "biolink:Drug", "biolink:MolecularEntity", "biolink:Metabolite"]` that these would be `all_categories`, is this not the case?

**Comment by chunyuma** [comment]
`["biolink:NamedThing", "biolink:BiologicalEntity", "biolink:ChemicalSubstance", "biolink:Drug", "biolink:MolecularEntity", "biolink:Metabolite"]` is `expanded_categories` attribute rather than `all_categories` attribute. Since the current version of DTD probability database is built based on preferred `category` attribute. So if we call DTD database, it might not have this curie because its all categories don't have `biolink:Drug` or `biolink:ChemicalSubstance`. So I would still suggest to use `DTD_slow_mode=true` in this case.

Here are all information for `CHEBI:77746` on kg2.5.2c:
```
{
  "iri": "http://purl.obolibrary.org/obo/CHEBI_77746",
  "expanded_categories": [
    "biolink:BiologicalEntity",
    "biolink:ChemicalSubstance",
    "biolink:Drug",
    "biolink:Metabolite",
    "biolink:MolecularEntity",
    "biolink:NamedThing"
  ],
  "name": "human metabolite",
  "description": "Any mammalian metabolite  produced during a metabolic reaction in humans (Homo sapiens).",
  "equivalent_curies": [
    "CHEBI:77746"
  ],
  "id": "CHEBI:77746",
  "category": "biolink:Metabolite",
  "all_names": [
    "human metabolite"
  ],
  "all_categories": [
    "biolink:Metabolite"
  ]
}
```

**Comment by dkoslicki** [comment]
Ah, I see. Thank you for clarifying. I though `expanded_categories` was a subset of `all_categories`, not the other way around. Seems to be a mis-naming (since all kinda makes you think of _all_). Ok to close if others don't object

**Comment by chunyuma** [comment]
I will close this issue.
