### ISSUE TITLE
Publications missing from NGD edges

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1393]
Take a look at the NGD edges in the results at: https://arax.ncats.io/?r=7629 In particular, the first result and the edge between the long name chemical substance and SMS. It has an NGD of 0.373, yet no publications listed.

**Comment by finnagin** [comment]
Odd that when I run this query locally:
```
add_qnode(id=UniProtKB:P52788, key=n0)
add_qnode(id=CHEMBL.COMPOUND:CHEMBL226471, key=n1)
expand(kp=ARAX/KG2)
overlay(action=compute_ngd,virtual_relation_label=N1,subject_qnode_key=n0,object_qnode_key=n1)
resultify()
```

I get the expected inf value for ngd. Also looks like it gets the right value this way on ARAX too: https://arax.ncats.io/?r=7651

Digging in a bit further to see whats going on here...

**Comment by dkoslicki** [comment]
Curious! I am finding more and more of these. Eg: check out the NGD edges for this one: https://arax.ncats.io/?r=7652
![image](https://user-images.githubusercontent.com/6362936/115612931-cdc7b980-a2b9-11eb-9246-9eb7fc924f5d.png)
Might have something to do with the synonymization? Eg. non-Inf NGD for some synonymous nodes, but not others (but I can't recall how fastNGD and KG2C are related)

**Comment by finnagin** [comment]
When printing out the ngd_value I get NaN but when looking at the value that gets entered It is ~0.7. I think maybe I finally figured out what is going on here. When compute_ngd gets initialized it [assigns the default value parameter to the variable named "value"](https://github.com/RTXteam/RTX/blob/112670d8d70ad78507d1d7dde72c46adfe36ffa6/code/ARAX/ARAXQuery/Overlay/compute_ngd.py#L67). Then, when looping through the subject, object pairs it tries [calculating the ngd](https://github.com/RTXteam/RTX/blob/112670d8d70ad78507d1d7dde72c46adfe36ffa6/code/ARAX/ARAXQuery/Overlay/compute_ngd.py#L89) and [if this is finite/not NaN is stores this in the variable "value"](https://github.com/RTXteam/RTX/blob/112670d8d70ad78507d1d7dde72c46adfe36ffa6/code/ARAX/ARAXQuery/Overlay/compute_ngd.py#L90-L91) and then after that check [creates the attribute using the variable "value"](https://github.com/RTXteam/RTX/blob/112670d8d70ad78507d1d7dde72c46adfe36ffa6/code/ARAX/ARAXQuery/Overlay/compute_ngd.py#L92). My guess is that the variable "value" is still storing the previous "ngd_value" variable so when it loops to the next subject-object pair and thus if a the next "ngd_value" if infinite or NaN it will then assign it the last finite "ngd_value".

Running a couple tests to verify that this is what's happening then I'm going to try implementing a fix...

**Comment by dkoslicki** [comment]
Good find! Looks like we need to re-assign `value` to the default inside [this loop](https://github.com/RTXteam/RTX/blob/112670d8d70ad78507d1d7dde72c46adfe36ffa6/code/ARAX/ARAXQuery/Overlay/compute_ngd.py#L85) or the like

**Comment by finnagin** [comment]
Oops! This was fixed and I added a test for it but I forgot to put the `#` before the 1393 in commit c1c2354386f3385ccdeb53375f29e8d885ec54e1

**Comment by dkoslicki** [comment]
Great! Let's check this in the next deployment. Thanks!

**Comment by dkoslicki** [comment]
Verified fixed in production!
