### ISSUE TITLE
Links in UI won't open if another tab is opened

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1395]
To reproduce: navigate to arax.ncats.io, then open a new _tab_ with your favorite website, then run a query, and click on one of the external-navigating links (eg. PMIDs). It will switch tabs, but won't actually go to the link you clicked. Happy to record this behavior if that would be helpful.

**Comment by edeutsch** [comment]
I tried to repro on Windows 10 + Firefox and was not able to repro.
Clicking on PMIDs as described works fine in my tests.
It seems hard to imagine how opening another arbitrary tab would interfere with ARAX GUI..

**Comment by dkoslicki** [comment]
Yeah, that's why I found it so mysterious. It happened to me on an iPad, a Windows laptop, and a Windows desktop, so didn't think it was a one-off. I'll get a recording when I get a chance

**Comment by edeutsch** [comment]
Just tried Windows 10 + Chrome and NOT able to repro.

**Comment by dkoslicki** [comment]
Ok, better way to repro: navigate to arax.ncats.io, then run a query, and click on one of the external-navigating links (eg. PMIDs), then on _that tab_ navigate somewhere else (eg. cnn), then go back to arax.ncats.io, and try to click on of the PMIDs. It will switch tabs, but won't actually go to the link you clicked.

**Comment by edeutsch** [comment]
The issue seems to be that target="_new" is not desired. Suggest changing it to target="_blank"
This issue seems to manifest itself on Chrome but not Firefox. Perhaps a Chrome bug.

**Comment by amykglen** [comment]
I think it's actually `target="pubmed"` for PMID links currently

![Screen Shot 2021-04-21 at 4 05 36 PM](https://user-images.githubusercontent.com/49423686/115631849-788ca780-a2bb-11eb-9cc3-f5a70292fea0.png)

**Comment by isbluis** [comment]
I have replaced all links to open in the `_blank` target (opening new tab/window) rather than trying to keep them thematically organized, thus circumventing this issue.
Or let me know if some other behavior is preferable.
Live in devLM:  https://arax.ncats.io/devLM/

**Comment by edeutsch** [comment]
Great, thanks, I have just rolled out to production and all other deployments.

@dkoslicki test and close?
(might want to do CTRL+REFRESH to ensure you're running the latest JavaScript?)

**Comment by dkoslicki** [comment]
Looks great to me! Closing
