### ISSUE TITLE
two-hop ARAX query always having is_set=True for intermediate node

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1398]
This issue report came out of the NCATS Translator Mini-Hackathon on April 22, 2021.

(JSON provided by Chris Bizon).

The following TRAPI query graph:
```
{
  "nodes": {
    "n0": {
      "name": "Glycerol",
      "id": "PUBCHEM.COMPOUND:753"
    },
    "n1": {
      "category": [
        "biolink:BiologicalProcessOrActivity"
      ],
      "name": "Biological Process Or Activity",
      "is_set": false
    },
    "n2": {
      "id":"NCBIGene:2710"
    }
  },
  "edges": {
    "e0": {
      "subject": "n0",
      "object": "n1",
      "predicate": [
        "biolink:related_to"
      ]
    },
    "e1": {
      "subject": "n1",
      "object": "n2",
      "predicate": [
        "biolink:related_to"
      ]
    }
  }
}
```
Amy confirms that this query should return more than one result, but currently, it only returns one result. And it looks like the `is_set` query node attribute is getting re-set to `true` somewhere in the system.

![Screen Shot 2021-04-22 at 8 56 29 AM](https://user-images.githubusercontent.com/5562107/115748233-d4524180-a34a-11eb-8987-604904da8049.png)

<img width="1337" alt="Screen Shot 2021-04-22 at 9 13 37 AM" src="https://user-images.githubusercontent.com/5562107/115748460-0b285780-a34b-11eb-94e3-d6f3427a531e.png">

**Comment by amykglen** [comment]
I recall us deciding a ways back that we would automatically set `is_set=True` for intermediate nodes in JSON QGs that come in, since we didn't think API users would know to use the `is_set` property, but that's very likely what they would want.

but it seems like we shouldn't be overriding `is_set` if it was specified in the QG?

alternatively/in addition, maybe we shouldn't default to `is_set=True` for the intermediate node in a two-hop query where the two 'outer' nodes are pinned (have a curie specified)?

**Comment by saramsey** [comment]
> but it seems like we shouldn't be overriding `is_set` if it was specified in the QG?

I concur.

**Comment by edeutsch** [comment]
I can turn this behavior off.
One problem I have/had is that after conversion from JSON to objects is that I cannot tell the difference between:
is_set = false
is_set = null
<is_set is missing from the JSON>

so that was one reason for the behavior.

**Comment by amykglen** [comment]
I actually like the default behavior, but just think we shouldn't override values in the QG. 

I'd think that this default behavior should be applied in both of the latter two cases you listed ('is_set=null' and <is_set is missing from the JSON>). was `if is_set is None` not working for you? I'd think that should do the trick...

**Comment by edeutsch** [comment]
I have turned this behavior off in /test
Do you want to try it there?
and then I can replicate to all deployments?
Seems okayish in my test although there are some issues with the display
https://arax.ncats.io/devED/?r=7722

**Comment by edeutsch** [comment]
I think this is resolved and probably not really relevant anymore anyway. closing.
