### ISSUE TITLE
A lot of nodes have description UNKNOWN which is unsightly in GUI

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#140]
Seems like 50% of nodes have description: UNKNOWN. What shall we do? Can we do better about filling more of them? Descriptions from UniProt? MesH? NCIT? other places?

Maybe in the GUI we should mask the description field when the value is UNKNOWN so it looks less unsightly?

Would it be better to set the property to null/None/undef instead of "UNKNOWN"?

**Comment by saramsey** [comment]
for the purpose of the hackathon, can the UI layer just substitute empty string instead of UNKNOWN?

Post-hackathon, we of course can look to using secondary and tertiary sources to backfill this information.  With the primary sources we are consulting, this is what we were able to get.

**Comment by saramsey** [comment]
alternatively I could ask @DeqingQu to change this

**Comment by saramsey** [comment]
I propose to change "UNKNOWN" to "N/A". This indicates that we looked for it and didn't find anything.

**Comment by edeutsch** [comment]
I might vote for null/None if that's possible rather than something that implies that it doesn't exist anywhere.

**Comment by saramsey** [comment]
OK we'll go with None.  Thank you for your reply.

**Comment by isbluis** [comment]
The GUI will now skip descriptions of "UNKNOWN" and "None"
(sorry, forgot to tag the commit)

**Comment by edeutsch** [comment]
looks good, thanks. closing.
