### ISSUE TITLE
comment character for ARAXi?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1404]
ARAXi is wonderful. It is intuitive, concise, and (together with the amazing drop-down that gives hints) quite easy to explore. 

The only thing I find myself yearning for is a comment character, so I can quickly comment out or uncomment (to restore) a single command.  Is this something that has been considered?  Or perhaps it could be considered, if it is technically feasible to endow the parser with the ability to detect a special comment string like `##` or something?

**Comment by saramsey** [comment]
Tagging the braintrust here for a discussion (if this is a bad idea for whatever reason, feel free to close the issue). Obviously not high priority!

**Comment by edeutsch** [comment]
Should already work, does it not?
Just a single `#` like Python and bash etc.

**Comment by edeutsch** [comment]
Line must begin with `#` tho. You cannot use it to comment an active line. i.e. cannot do:
add_qnode(name=acetaminophen)    # Adding my first node

**Comment by saramsey** [comment]
Oh, awesome!  Thank you!  Yeah, a comment char just at the first position is fine.

**Comment by edeutsch** [comment]
vertical whitespace is ignored too, so you can write your DSL with comment lines and blank lines for readability.

**Comment by edeutsch** [comment]
@isbluis maybe this functionality can be advertised a little by changing the Example DSL from:
```
add_qnode(name=acetaminophen, key=n0)
add_qnode(category=biolink:Protein, key=n1)
add_qedge(subject=n0, object=n1, key=e0)
expand(edge_key=e0,kp=ARAX/KG2)
overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n0, object_qnode_key=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```

to 

```
# This program creates two query nodes and a query edge between them, looks for matching edges in the KG,
# overlays NGD metrics, and returns the top 30 results
add_qnode(name=acetaminophen, key=n0)
add_qnode(category=biolink:Protein, key=n1)
add_qedge(subject=n0, object=n1, key=e0)
expand()
overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n0, object_qnode_key=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```

I also removed the unnecessary parameters from expand()

**Comment by isbluis** [comment]
Added in devLM; let me know if it looks ok.

**Comment by edeutsch** [comment]
looks great, push it! I'm about to roll out!
