### ISSUE TITLE
KG2 KP always ignores edge direction

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1406]
this is something that's already on our radar, but thought I should create an issue about it so it doesn't fall through the cracks (thanks @saramsey for bringing my attention to it).

since there's no way to communicate via TRAPI whether or not to enforce edge direction, the KG2 API always defaults to ignoring edge direction currently.

note that this means if you write DSL and pass `enforce_directionality=true` to `expand`, it won't actually do anything (meaning, edge direction will still be ignored, for KG2 queries).

ignoring edge direction is certainly a nice default I think, but @saramsey's query for the 'Data Spelunking' article is an example where being able to enforce edge direction is desirable: https://arax.ncats.io/?r=7780

**Comment by edeutsch** [comment]
I suppose the fix options are:
1) an ARAX TRAPI global query option enforce_directionality=true for a whole query
2) Or we could have the option per QueryEdge but that seems a little silly and more complicated

I could try to put together option 1.
We would then need something in the UI akin to the bypass_cache option

What do you think?

**Comment by amykglen** [comment]
closing in favor of #1611
