### ISSUE TITLE
ARAX messenger error

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1408]
For this query

```
add_qnode(key=n0,id=MONDO:0005812)
add_qnode(key=n1,category=biolink:PhenotypicFeature)
add_qnode(id=n2,category=biolink:Disease)
add_qedge(key=e0,subject=n0,object=n1)
add_qedge(key=e1, subject=n1,object=n2)
expand()
overlay(action=compute_jaccard, start_node_key=n0, intermediate_node_key=n1, end_node_key=n2, virtual_relation_label=J1)
resultify()
filter_results(action=limit_number_of_results, max_results=100)
overlay(action=compute_ngd,default_value=inf,virtual_relation_label=V1,subject_qnode_key=n0,object_qnode_key=n1)
resultify(ignore_edge_direction=true)
```
I am getting the following error: `2021-04-23T15:35:33.480149 ERROR: [UncaughtARAXiError]    An uncaught error occurred: 'NoneType' object has no attribute 'message': ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 586, in execute_processing_plan\n messenger.add_qnode(response,action[\'parameters\'])\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_messenger.py", line 243, in add_qnode\n key = self.__get_next_free_node_key()\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_messenger.py", line 347, in __get_next_free_node_key\n message = self.envelope.message\n', "AttributeError: 'NoneType' object has no attribute 'message'\n"]`

**Comment by dkoslicki** [comment]
I imagine that if a required field is missing (here the third qnode is missing a key), we'd want a more graceful error message.

**Comment by edeutsch** [comment]
problem fixed in devED. need to test on production

**Comment by dkoslicki** [comment]
Confirmed in production, so closing
