### ISSUE TITLE
another source of drug-target probabilities

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#141]
http://www.swisstargetprediction.ch/result.php?job=1106242450&organism=Homo_sapiens

**Comment by edeutsch** [comment]
or maybe "another" instead of "alternate"? the conversation on Thursday turned to multigraphs. How does everyone feel about a multigraph that has data from swisstargetprediction and ChEMBL? And DrugBank?

**Comment by saramsey** [comment]
Whoa, multigraphs -- I just opened up a can-o-worms, didn't I?

**Comment by saramsey** [comment]
mostly I just entered this issue so I won't forget to look into Swiss Target Prediction after the hackathon.

**Comment by dkoslicki** [comment]
We should definitely discuss this: multigraphs complicates things pretty significantly, and I’d want to hear the reason why we can’t just have multiple edge properties.

**Comment by dkoslicki** [comment]
Closing due to #788 and due to NCATS wanting only Translator KP’s (so we or someone would need to stand this up as a KP)
