### ISSUE TITLE
Translator Wiki pages updates

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1417]
See issue 10 on https://github.com/NCATSTranslator/Translator-All

Apparently the two Wiki pages that we need to update are:

https://github.com/NCATSTranslator/Translator-All/wiki/ARAX
https://github.com/NCATSTranslator/Translator-All/wiki/KG2

I can do KG2. Any takers for the ARAX page?

**Comment by saramsey** [comment]
Deadline is for the Spring Relay

**Comment by dkoslicki** [comment]
Wiki updated, and #1435 will provide examples (the last item to be done)

**Comment by saramsey** [comment]
OK, KG2 KP API Wiki page drafting is complete. Please let me know if anything looks amiss:
https://github.com/NCATSTranslator/Translator-All/wiki/KG2

**Comment by dkoslicki** [comment]
All tasks completed
