### ISSUE TITLE
Do we want to continue supporting expand's 'use_synonyms=false' option?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1418]
have been wondering about this given that it's a standard part of Translator now to have to 'canonicalize'/normalize nodes... and it does cause us some development headaches and small performance hits to keep supporting the `use_synonyms=false` functionality, when I don't think I've seen it used at all for many months. I believe it was mainly relevant in the early days of our synonym-handling experiments. 

are there still envisioned use cases for `use_synonyms=false`? or could we get rid of this and no one would miss it?

**Comment by edeutsch** [comment]
I would not miss it

**Comment by dkoslicki** [comment]
I would not miss it either: I think I've used it exactly once this year

**Comment by amykglen** [comment]
alright, the `use_synonyms` parameter has been removed in `master` (documentation is updated as well). will verify it looks good with the next deployment.

**Comment by edeutsch** [comment]
master has just now been rolled out to all deployments.

**Comment by amykglen** [comment]
great, thanks - looks good to me! although I think @isbluis will need to update the DSL builder? I see the `use_synonyms` dropdown still appears for `expand` actions, even though I updated the auto-documentation/'describe me' function...  (is there a way to automate that step?)

**Comment by edeutsch** [comment]
I think the process is to execute code/UI/interactive/dsl2json.py
and then test/commit the new araxi.js

**Comment by isbluis** [comment]
The DSL builder file has been updated.  Let me know if you notice any other issues.

**Comment by amykglen** [comment]
awesome, looks good on production (after a hard refresh)! thanks!
