### ISSUE TITLE
Brca2 gene and "BRCA2 Gene" as separate nodes in KG2 (mediKanren export)

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1419]
Will Byrd wrote (on 4/26):

> Hey Steve!
> 
> I hope you are doing well!
> 
> Thi and I were playing around with RTX2 last week and noticed something that surprised us.
> 
> There seem to be multiple concepts in RTX2 with the CURIE 'UMLS:C0598034'.
> 
> This is the CURIE for the BRCA2 gene.  However, in the attached spreadsheet, you can see that there are two different names corresponding to this CURIE in RTX2: 'Brca2', which appears to be the mouse gene, and, further down in the spreadsheet, 'BRCA2 gene', which is the human version.
> 
> Does it surprise you that the same CURIE maps to multiple concepts?  Or is that expected?
> 
> Thanks!
> 
> Cheers,
> 
> --Will

**Comment by saramsey** [comment]
Here is the TSV file that Will attached to that message

[BRCA-syn.txt](https://github.com/RTXteam/RTX/files/6393176/BRCA-syn.txt)

**Comment by ericawood** [comment]
This gets stranger. The node in `KG2.5.2` has the name "Genes, BRCA2":
```
{
  "iri": "https://identifiers.org/umls:C0598034",
  "category_label": "genomic_entity",
  "full_name": "BRCA2 DNA repair associated",
  "deprecated": "False",
  "name": "Genes, BRCA2",
  "description": "This gene is involved in cell cycle control, DNA repair and the maintenance of genomic stability. It also plays a role in the proliferation of embryonic cells.; A tumor suppressor gene (GENES, TUMOR SUPPRESSOR) located on human chromosome 13 at locus 13q12.3. Mutations in this gene predispose humans to breast and ovarian cancer. It encodes a large, nuclear protein that is an essential component of DNA repair pathways, suppressing the formation of gross chromosomal rearrangements. (from Genes Dev 2000;14(11):1400-6); UMLS Semantic Type: UMLS_STY:T028",
  "provided_by": "identifiers_org_registry:umls",
  "id": "UMLS:C0598034",
  "category": "biolink:GenomicEntity",
  "update_date": "2018"
}
```

**Comment by edeutsch** [comment]
All the nodes that get clustered together can be viewed here (under Nodes):
https://arax.ncats.io/devLM/?term=UMLS:C0598034

Some are the lower-case mouse convention entries, but it's not clear that they are all mouse.
OMIM:600185 | Brca2 gene | Brca2 gene | biolink:PhenotypicFeature

is probably not mouse?

Node synonymizer does coalesce case-insensitive (probably catching far more true positives than false positives, but yes, there will be false positives).

I think our convention would be to append " (speciesName)" i.e. in this case " (mouse)" to any gene symbols for any non-human genes.
Now if we could only figure out which of these are truly mouse, I could update the Node Synonymizer.
At least for this particular gene.
This is going to be a systematic problem (probably only for the most famous genes) so are more comprehensive fix would be ideal.

**Comment by ericawood** [comment]
From `KG2.5.2`'s TSV file:
```
ubuntu@ip-172-31-3-188:~/kg2-build/TSV$ grep "UMLS:C0598034" nodes.tsv
biolink:GenomicEntity	genomic_entity		False	This gene is involved in cell cycle control, DNA repair and the maintenance of genomic stability. It also plays a role in the proliferation of embryonic cells.; A tumor suppressor gene (GENES, TUMOR SUPPRESSOR) located on human chromosome 13 at locus 13q12.3. Mutations in this gene predispose humans to breast and ovarian cancer. It encodes a large, nuclear protein that is an essential component of DNA repair pathways, suppressing the formation of gross chromosomal rearrangements. (from Genes Dev 2000;14(11):1400-6); UMLS Semantic Type: UMLS_STY:T028	BRCA2 DNA repair associated	UMLS:C0598034	https://identifiers.org/umls:C0598034	Genes, BRCA2	identifiers_org_registry:umls				2018	biolink:GenomicEntity
```
From the `kg2-medikanren-tsvs-20210204.tar.gz` export:
```
ubuntu@ip-172-31-3-188:~/kg2-build$ grep "UMLS:C0598034" rtx_kg2.node.tsv 
UMLS:C0598034

ubuntu@ip-172-31-3-188:~/kg2-build$ grep "UMLS:C0598034" rtx_kg2.nodeprop.tsv 
UMLS:C0598034	category_label	genomic_entity
UMLS:C0598034	deprecated	False
UMLS:C0598034	description	This gene is involved in cell cycle control, DNA repair and the maintenance of genomic stability. It also plays a role in the proliferation of embryonic cells.; A tumor suppressor gene (GENES, TUMOR SUPPRESSOR) located on human chromosome 13 at locus 13q12.3. Mutations in this gene predispose humans to breast and ovarian cancer. It encodes a large, nuclear protein that is an essential component of DNA repair pathways, suppressing the formation of gross chromosomal rearrangements. (from Genes Dev 2000;14(11):1400-6); UMLS Semantic Type: UMLS_STY:T028
UMLS:C0598034	full_name	BRCA2 DNA repair associated
UMLS:C0598034	id	UMLS:C0598034
UMLS:C0598034	iri	https://identifiers.org/umls:C0598034
UMLS:C0598034	name	Brca2
UMLS:C0598034	provided_by	identifiers_org_registry:umls
UMLS:C0598034	update_date	2018
UMLS:C0598034	category	biolink:GenomicEntity

```

I'm not seeing a sign as to where the problem is. I only see one `UMLS:C0598034` entry in KG2. Is there something I'm missing?

**Comment by edeutsch** [comment]
I am not certain but I think the question is: which species does this gene belong to?
We might guess human, but are we sure?

There is a convention in the field to use all caps for human gene symbols BRCA2
And use PascalCase for mouse gene symbols Brca2
https://www.biosciencewriters.com/Guidelines-for-Formatting-Gene-and-Protein-Names.aspx

I think Will is concerned that this (or maybe some other sibling in the NodeSynonymizer cluster?) is a mouse gene because of this convention (notice the capitalization in your grep results above)

I *suspect* that he is concerned that we have conflated human genes and mouse genes.
And that is based on the convention in the field to spell mouse gene symbols like Brca2
But I am just guessing. His report is not specific enough to really understand what the problem is.

So maybe rather than spinning our wheels, we need to ask him to be really specific about his issue.
Or we can really carefully investigate the cluster:
https://arax.ncats.io/devLM/?term=UMLS:C0598034
so that we are sure we haven't conflated human and mouse genes together in the same cluster.

**Comment by saramsey** [comment]
FWIW:  webyrd confirms that they were using the February 4 KG2 TSV

**Comment by saramsey** [comment]
But @ericawood, isn't the export `kg2-medikanren-tsvs-20210204.tar.gz` based on KG2.5.1?

**Comment by saramsey** [comment]
I emailed Will Byrd about @ericawood's findings (with CC to @ericawood). Thank you all!

**Comment by ericawood** [comment]
> 
> 
> But @ericawood, isn't the export `kg2-medikanren-tsvs-20210204.tar.gz` based on KG2.5.1?

Likely, I'm actually not exactly sure. @kvarforl would know. However, if you see my grep of the mediKanren files, you will see that there is only one entry of `UMLS:C0598034`.

**Comment by saramsey** [comment]
Per #1200, I am 99.9% sure this was an export of KG2.5.1.

**Comment by saramsey** [comment]
> > But @ericawood, isn't the export `kg2-medikanren-tsvs-20210204.tar.gz` based on KG2.5.1?
> 
> Likely, I'm actually not exactly sure. @kvarforl would know. However, if you see my grep of the mediKanren files, you will see that there is only one entry of `UMLS:C0598034`.

Hi @ericawood,  yes, you are correct. My current hunch (just a guess, really) is maybe two KG2 versions were loaded into mediKanren and that is what is causing the odd behavior they are seeing?

**Comment by saramsey** [comment]
I will update this issue when I hear back from the Unsecret Agent team.

**Comment by saramsey** [comment]
OK, team Unsecret Agent concurs this may be an issue on the mediKanren end. Closing this issue (can always reopen if new information comes in).
