### ISSUE TITLE
node ids should be CURIEs in the result output

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#142]
Currently node output in the API is:
        "node_list": [
          {
            "description": "Cranial nerve fiber tract which is comprised of retinal ganglion cell axons running posterior medially towards the optic chiasm, at which some of the axons cross the midline and after which the structure is termed the optic tract. Transmits visual information from the retina to the brain[ZFA].",
            "id": "http://purl.obolibrary.org/obo/UBERON_0000941",
            "name": "cranial nerve II",
            "type": "anatomical_entity"
          },
          {
            "description": "UNKNOWN",
            "id": "https://reactome.org/content/detail/R-HSA-456926",
            "name": "Thrombin signalling through proteinase activated receptors (PARs)",
            "type": "pathway"
          },

But id= is supposed to be a CURIE like UBERON:0000941
while uri= is the expansion of the CURIE as we have now.

Can we do that?

**Comment by saramsey** [comment]
@edeutsch  which Neo4j is this output based on?

**Comment by edeutsch** [comment]
current production-role (container DEV??)
But I think this is an issue for @dkoslicki 's code putting KG properties into JSON keys, not the KG itself. The KG does have CURIEs, yes?

**Comment by saramsey** [comment]
I do not know where this output is coming from.  On the Neo4j on served in the DEV container on rtx.ncats.io, I see this:

![screen shot 2018-05-11 at 8 43 18 pm](https://user-images.githubusercontent.com/5562107/39953235-10c8b7ba-555c-11e8-9ccc-bdcd78ce504e.png)

**Comment by edeutsch** [comment]
yes, see my comment above.

**Comment by saramsey** [comment]
Yes KG has CURIEs:

![screen shot 2018-05-11 at 8 44 58 pm](https://user-images.githubusercontent.com/5562107/39953245-3092a862-555c-11e8-820c-6af2437d9683.png)

**Comment by saramsey** [comment]
taking myself off this issue, as it does not seem to involve the KG

**Comment by edeutsch** [comment]
issue for @dkoslicki then.
Official CURIE for Reactome appears to REACT:
https://github.com/monarch-initiative/dipper/blob/master/dipper/curie_map.yaml

**Comment by dkoslicki** [comment]
@edeutsch Just to clarify, here's an example of what it should look like, correct?
node.id = "UBERON:00000914"
node.iri = "http://purl.obolibrary.org/obo/UBERON_0000941"

edges don't seem to have CURIE id's, so nothing to do there, correct?

**Comment by edeutsch** [comment]
yes, right, except that should be uri instead of iri?

**Comment by dkoslicki** [comment]
ah yes, that was a typo (got it right in the code). This has been implemented, so closing this issue.
