### ISSUE TITLE
Adjust node synonymizer to work properly with database manager

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1422]
since we have a rollout of a new KG2 coming up, it'd be good if we could get the synonymizer fully on the database manager 'bandwagon'. :) I think all that needs to happen is to tweak `node_synonymizer.py` so that:

1. the code that _builds_ a new synonymizer should always save it as `node_synonymizer.sqlite`
2. the code that _uses_ a synonymizer should **not** just look for a file named `node_synonymizer.sqlite`, but instead figure out what the 'correct' synonymizer file name is based on what's in `configv2.json`, and use that file (an example of how to do this for a different database is [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_decorator.py#L32-L40))

so the idea is that when the synonymizer is built, it will at first be called `node_synonymizer.sqlite`, but then when it's put into the proper directory on arax.ncats.io (i.e., `/translator/data/orangeboard/databases/KG2.6.1`), it should be renamed to something like: `node_synonymizer_v1.0_KG2.6.1.sqlite`, and this is what `configv2.json` should be updated to point to.

then down the road if a new synonymizer comes out, it would just need to be added to that /KG2.6.1 directory as `node_synonymizer_v1.1_KG2.6.1.sqlite`, and `configv2.json` would need to be updated to point to it. and that's all! the database manger would take care of downloading it as needed and the code would know to use it since the config file would point to it.

not sure if I should dig in and try to make this change to `node_synonymizer.py`, or @finnagin or @edeutsch?

**Comment by finnagin** [comment]
I've adjusted it so it should work with the config file now. To handle the build cases [here.](https://github.com/RTXteam/RTX/blob/e09e5451175ba550d5b092dd9c8712901c47ea4a/code/ARAX/NodeSynonymizer/node_synonymizer.py#L2445-L2447) I haven't ever run a node synonymizer build before so I just want to double check does that look reasonable to you @amykglen or @edeutsch ? Specifically, I have it swap to "node_synonymizer.sqlite" if either the build flag or the recollate flag is set to true. Is that correct or should it just be the build flag?

**Comment by edeutsch** [comment]
Thanks, build and recollate is fine.

So is the idea that it always writes to "node_synonymizer.sqlite" but always reads what it says in the config?
So the biggest risk then is in testing after building to make certain you're testing the right database?

**Comment by finnagin** [comment]
Yup, that's the idea! Let me know if you run into any issue/need any help next time you run a node synonymizer build.

**Comment by amykglen** [comment]
this all has been working fine for some time now, I think - closing!
