### ISSUE TITLE
Missing some COHD info, expand not hitting COHD?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1430]
For [this standup issue](https://github.com/NCATSTranslator/testing/issues/58), it appears that we are not fully using all the information we can from COHD. Namely, the `correlated_with` predicate between diseases. It may be a case of `expand` not hitting COHD due to predicate or node type specificity.

**Comment by amykglen** [comment]
one problem appears to be that COHD doesn't advertise being able to answer "biolink:Disease" queries at their /predicates endpoint (https://cohd.io/api/predicates) - only "biolink:DiseaseOrPhenotypicFeature".

so if you switch to "biolink:DiseaseOrPhenotypicFeature", it does hit up COHD. but it still doesn't find any answers.
```
{
      "nodes": {
        "n0": {
          "id": "MONDO:0014007",
          "category": "biolink:DiseaseOrPhenotypicFeature"
        },
        "n1": {
          "category": "biolink:DiseaseOrPhenotypicFeature"
        }
      },
      "edges": {
        "e01": {
          "subject": "n0",
          "object": "n1",
          "predicate": "biolink:correlated_with"
        }
      }
    }
```
not sure why. I see this warning in the log - not sure if it's related. @chunyuma?
```
2021-05-04T16:21:23.740364 WARNING: The preferred type of source preferred id 'MONDO:0014007' can't match to the given source type 'biolink:DiseaseOrPhenotypicFeature''
```

**Comment by dkoslicki** [comment]
I imagine with the KP reasoning stuff, it would be reasonable to assume that `Disease` is a subclass of `DiseaseOrPhenotypicFeature`, so perhaps this can be coded somewhere to handle that?

**Comment by dkoslicki** [comment]
FWIW, KG2C-2-5-2 does appear to have that node labeled with `DiseaseOrPhenotypicFeature`
`match (n:`biolink:Disease`{id:"MONDO:0014007"}) return n`

**Comment by chunyuma** [comment]
Hi @dkoslicki and @amykglen, I think I'm a little bit confused about this. which kp does this query request? If it used expand(kp=COHD), it seems like currently the COHD data downloaded from COHD database doesn't have the predicate information. By the way, how can I get the DSL query based on the api request like the [one](https://github.com/NCATSTranslator/testing/issues/58)?

**Comment by amykglen** [comment]
> I imagine with the KP reasoning stuff, it would be reasonable to assume that Disease is a subclass of DiseaseOrPhenotypicFeature, so perhaps this can be coded somewhere to handle that?

yep, perhaps it's time to do that. it didn't make sense at first since not many KPs had actually implemented that reasoning. and we also went the other way with KG2's /predicates endpoint - we advertise in there that we can answer all descendant queries. @edeutsch do you know if there is any TRAPI perspective on whether that's how it should be?

**Comment by amykglen** [comment]
hey @chunyuma - here's the DSL version of the query we expect to return results that isn't:
```
add_qnode(key=n0, id=MONDO:0014007, category=biolink:DiseaseOrPhenotypicFeature)
add_qnode(key=n1, category=biolink:DiseaseOrPhenotypicFeature)
add_qedge(key=e01, predicate=biolink:correlated_with, subject=n0, object=n1)
expand(kp=COHD)
resultify()
filter_results(action=limit_number_of_results,max_results=20,prune_kg=true)
```

**Comment by amykglen** [comment]
> I imagine with the KP reasoning stuff, it would be reasonable to assume that Disease is a subclass of DiseaseOrPhenotypicFeature, so perhaps this can be coded somewhere to handle that?

thinking about this more, I realized that I actually think we _can't_ technically deduce that they answer `biolink:Disease` queries from the fact that they say they answer `biolink:DiseaseOrPhenotypicFeature` queries... we can deduce the opposite (that they must answer `biolink:BiologicalEntity` and `biolink:NamedThing` queries), but not the 'more specific'/descendant direction... 

so we probably _should_ still extrapolate ancestors based on the /predicates endpoint, since it's undecided whether KPs should advertise such info there, but that alone wouldn't fix this situation..

but I think if expand added in an equivalency for `biolink:DiseaseOrPhenotypicFeature` == `biolink:Disease` == `biolink:PhenotypicFeature`, that would resolve this situation... expand already does this for `biolink:Gene` == `biolink:Protein`, but not yet the other equivalencies we at ARAX tend to assume... (I could also add one in for `biolink:ChemicalSubstance` == `biolink:Drug`). anyone have objections to that?

**Comment by chunyuma** [comment]
ok, @dkoslicki and @amykglen, I think I found the reason but I'm not sure if it should be associated with `Nodesynonymizer`. Here might be the reason:

I tried to call cohd api `https://cohd.io/api/query` for [this](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/aicardiCorrelated.json) query. It returns 500 results. I checked one of their edges from the returned knowledge graph which is 
```
"ke000002": {
          "attributes": [
            {
              "name": "confidence_interval",
              "source": "COHD",
              "type": "EDAM:data_0951",
              "value": [
                4.73210480851078,
                4.801318987314368
              ]
            },
            {
              "name": "dataset_id",
              "source": "COHD",
              "type": "EDAM:data_1048",
              "value": 3
            },
            {
              "name": "expected_count",
              "source": "COHD",
              "type": "EDAM:operation_3438",
              "value": 76.93711609150404
            },
            {
              "name": "ln_ratio",
              "source": "COHD",
              "type": "EDAM:data_1772",
              "value": 4.7670895359804115
            },
            {
              "name": "observed_count",
              "source": "COHD",
              "type": "EDAM:data_0006",
              "value": 9046
            }
          ],
          "object": "MONDO:0005180",
          "predicate": "biolink:correlated_with",
          "subject": "MONDO:0014007"
        }
```

I checked what `omop_concept_id` these `MONDO:0014007` and `MONDO:0005180` correspond to. Here is the information from them: `MONDO:0005180` corresponds to  `381270` and `MONDO:0014007`  corresponds to `378144`. 

```
 "MONDO:0005180": {
          "attributes": [
            {
              "name": "omop_concept_id",
              "source": "OMOP",
              "type": "EDAM:data_1087",
              "value": "OMOP:381270"
            },
            {
              "name": "omop_concept_name",
              "source": "OMOP",
              "type": "EDAM:data_2339",
              "value": "Parkinson's disease"
            },
            {
              "name": "omop_domain",
              "source": "OMOP",
              "type": "EDAM:data_0967",
              "value": "Condition"
            }
          ],
          "category": [
            "biolink:DiseaseOrPhenotypicFeature"
          ],
          "name": "Parkinson disease"
        },
"MONDO:0014007": {
          "attributes": [
            {
              "name": "omop_concept_id",
              "source": "OMOP",
              "type": "EDAM:data_1087",
              "value": "OMOP:378144"
            },
            {
              "name": "omop_concept_name",
              "source": "OMOP",
              "type": "EDAM:data_2339",
              "value": "Disorder of basal ganglia"
            },
            {
              "name": "omop_domain",
              "source": "OMOP",
              "type": "EDAM:data_0967",
              "value": "Condition"
            }
          ],
          "category": [
            "biolink:DiseaseOrPhenotypicFeature"
          ],
          "name": "basal ganglia disease"
        }
```

And here is the concept id mappings I collected from [athena](https://athena.ohdsi.org/search-terms/start) based on all equivalent ids of these two curies. 
```
In [3]: data["MONDO:0005180"]                                                                                                                                               
Out[3]: 
{'preferred_name': 'Parkinson disease',
 'preferred_type': 'biolink:Disease',
 'synonyms': ['MEDDRA:10076917',
  'PSY:36350',
  'ICD10:G20',
  'NCIT:C26845',
  'UMLS:C0865474',
  'UMLS:C1399358',
  'UMLS:C0030567',
  'MEDDRA:10061536',
  'MEDDRA:10034006',
  'MEDDRA:10033801',
  'DOID:14330',
  'UMLS:C4049471',
  'UMLS:C0853008',
  'EFO:0002508',
  'UMLS:C0865476',
  'SNOMED:49049000',
  'MONDO:0005180',
  'UMLS:C0865475'],
 'concept_ids': [46276907, 45538098, 36718256, 36775446, 36775444, 381270]}

In [4]: data["MONDO:0014007"]                                                                                                                                               
Out[4]: 
{'preferred_name': 'Aicardi-Goutieres syndrome 6',
 'preferred_type': 'biolink:Disease',
 'synonyms': ['UMLS:C3539013', 'MONDO:0014007', 'OMIM:146920', 'OMIM:615010'],
 'concept_ids': [1568296, 958835, 44833436]}
```

As you can see, `MONDO:0014007` doesn't have concept id `378144` based on all its synonyms. I also checked the concept id `378144` corresponds to what curie id based on athena. It matches to `SNOMED:70835005`. 

```
         concept_id       curie_name
3425452      378144  SNOMED:70835005
```

Based on kg2.5.2c, `SNOMED:70835005` is `basal ganglia disease` which is currently not the synonyms of `MONDO:0014007` which is `Aicardi-Goutieres syndrome 6`. I think in COHD graph, they might have an edge with labelled `correlated_with ` connecting this two curies. But in our graph, I don't think that we consider them as the same synonyms.

```
{
  "iri": "http://purl.obolibrary.org/obo/MONDO_0003996",
  "expanded_categories": [
    "biolink:BiologicalEntity",
    "biolink:Disease",
    "biolink:DiseaseOrPhenotypicFeature",
    "biolink:NamedThing",
    "biolink:PhenotypicFeature"
  ],
  "name": "basal ganglia disease",
  "description": "A disease involving the basal ganglia.",
  "equivalent_curies": [
    "DOID:679",
    "EFO:0009533",
    "HP:0002134",
    "MESH:D001480",
    "MONDO:0003996",
    "SNOMED:70835005",
    "UMLS:C0004782",
    "UMLS:C0750951",
    "UMLS:C4520981"
  ],
  "id": "MONDO:0003996",
  "category": "biolink:Disease",
  "all_names": [
    "Abnormality of the basal ganglia",
    "Basal Ganglia Diseases",
    "Disorder of basal ganglia",
    "basal ganglia disease"
  ],
  "all_categories": [
    "biolink:Disease",
    "biolink:NamedThing",
    "biolink:PhenotypicFeature"
  ],
  "publications": [
    "https://en.wikipedia.org/wiki/basal_ganglia_disease"
  ]
}
```

Cypher query for the edges between `MONDO:0014007` and `SNOMED:70835005` based on [kg2c](http://kg2c-5-2.rtx.ai:7474/browser/) :

```
match (n{id:"MONDO:0014007"})-[r]-(m{id:"MONDO:0003996"}) return distinct n.id, n.equivalent_curies, r.predicate, m.id, m.equivalent_curies
```

No return for this query.

I think we can get the same result from COHD unless these two curies are clustered together.

**Comment by chunyuma** [comment]
> but I think if expand added in an equivalency for biolink:DiseaseOrPhenotypicFeature == biolink:Disease == biolink:PhenotypicFeature, that would resolve this situation... expand already does this for biolink:Gene == biolink:Protein, but not yet the other equivalencies we at ARAX tend to assume... (I could also add one in for biolink:ChemicalSubstance == biolink:Drug). anyone have objections to that?

I agree to addd in an equivalency for biolink:DiseaseOrPhenotypicFeature == biolink:Disease == biolink:PhenotypicFeature.

**Comment by edeutsch** [comment]
I have no objections, but haven't thought deeply about it.

**Comment by dkoslicki** [comment]
Interesting @chunyuma ! So are they substituting a different disease for that CURIE? I had taken a look at their results and wondered why it was all “basal ganglia disease” and not the Aicardi syndrome. Is it correct to conclude from what you found that they are doing some synonymizing saying that Aicardi syndrome is equivalent to basal ganglia disease? If so, I can work with Casey Ta to see where this is happening and why it looks different in our local copy of COHD.

I had wondered if we would need to update our local COHD copy at some point. This might be the impetus.

**Comment by chunyuma** [comment]
>  are they substituting a different disease for that CURIE?

Based on their api return, the name of `MONDO:0014007` is "basal ganglia disease" while in our kg2c, it is `Aicardi-Goutieres syndrome 6`. I'm not sure which one is correct. Perhaps @dkoslicki and @saramsey could help to take a look.

> Is it correct to conclude from what you found that they are doing some synonymizing saying that Aicardi syndrome is equivalent to basal ganglia disease? 

I don't know if they are doing some synonymizing for Aicardi syndrome and basal ganglia disease, or they have a wrong label. But it seems like the reason of no return for [this](https://github.com/NCATSTranslator/testing/issues/58) issue is due to this problem. 

> I had wondered if we would need to update our local COHD copy at some point. This might be the impetus.

Perhaps it would be better to first ask people from COHD team to see if they have already updated COHD data. Based on my investigation today, the data can still match to them. But since our concept ids are not from their copy (I collected the concept ids by using athena and oxo mapping based on all synonyms), this might cause the difference. If you can provide us all concept ids that they use, I think this might be better.

**Comment by amykglen** [comment]
so `expand` does now hit COHD for the original query in this issue on NewFmt (since I added the Disease == PhenotypicFeature == DiseaseOrPhenotypicFeature equivalency), but I also created a separate issue to ensure that ancestor categories are considered when expand is inspecting KPs' /predicates endpoints to choose which to use: #1465
