### ISSUE TITLE
kg2_tsv_to_medikanren_tsv.py only works with relative path to tsv directory

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1431]
When doing the medikanren export, the conversion script `kg2_tsv_to_medikanren_tsv.py` only works with the very specific relative path to the tsv directory.

```bash
ubuntu@ip-172-31-59-26:~/RTX/code/kg2/mediKanren$ python3.7 kg2_tsv_to_medikanren_tsv.py ../../../../kg2-build/TSV  mediKanren/biolink/data/rtx_kg2
```

It does not work if you try to run the same command from `~/kg2-code/mediKanren` and it also does not work if you try to use `~/kg2-build/TSV` as the path to the TSVS.

**Comment by saramsey** [comment]
Thanks for the issue report. Can you paste the error message into the issue?  Also can you please run 
```
python3 kg2_tsv_to_medikanren_tsv.py --help
```
and paste the output into the issue?

**Comment by kvarforl** [comment]
Ah apologies, I should have posted more info or fixed this more promptly! 

The issue was that the leftmost slash was being stripped off of the directory path; should be fixed now!
