### ISSUE TITLE
FET got negative values because the get_total_entity_count of Nodesynonymizer might be obsolete?

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1433]
Hi @edeutsch,

Just want to report this issue associated with the `get_total_entity_count` of Nodesynonymizer to you. When I was fixing the errors reported by @amykglen from #1414, I got some negative values in FET calculation which is actually not expected. I found this might be due to that the current `get_total_entity_count`  return is based on `preferred_category` rather than `expanded_categories`. It seems like currently kg2c is now using category descendants. So perhaps we might need to update `get_total_entity_count` to consider `expanded_categories` rather than `preferred_category`. And @amykglen also suggests to add this total count into the KG2c SQLite which she developed for me to count the number of neighbor nodes with given node type of a given node. Just want to see which one do you think make more sense. Thanks!

**Comment by edeutsch** [comment]
It is correct that I calculate the numbers based on the preferred_category. It sounds quite sensible to me that @amykglen computes the numbers using expanded_categories instead and stores the values in KG2C for other resources to use, yes. I think that makes a lot of sense.

**Comment by amykglen** [comment]
@chunyuma - ok, I made a new version of the KG2c sqlite (`kg2c_v1.2_KG2.5.2.sqlite`) that contains the total counts of nodes by their `expanded_categories`.

if you just delete your local `configv2.json`, the database should automatically download when you run a pytest.

here's a little test query so you can see the table/column names:
```
        sql_query = f"SELECT C.count " \
                    f"FROM category_counts AS C " \
                    f"WHERE C.category = 'biolink:BiologicalProcess'"
```
let me know if you have any issues!

**Comment by chunyuma** [comment]
Thanks @amykglen, I tested it and it works for FET. I've already fixed the test errors reported in #1414 except for `test_FET_ranking_2`. I will report this error in #1414. Thanks for your help again!

**Comment by chunyuma** [comment]
@amykglen and @edeutsch, are you ok to close this issue?

**Comment by amykglen** [comment]
awesome - sounds fine to me to close!

**Comment by edeutsch** [comment]
yes
