### ISSUE TITLE
Add use case examples to wiki and testing repo

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1435]
In the course of #1417 , we are to give example use cases [here](https://github.com/NCATSTranslator/Translator-All/wiki/ARAX#use-cases) and [here](https://github.com/NCATSTranslator/Translator-All/wiki/KG2), and also put them in the [testing repo](https://github.com/NCATSTranslator/testing/).

For ARAX, I suggest:

- [x] A simple look up (like our current acetaminophen example) in both TRAPI (curl + post) and DSL
- [x] A kitchen-sink example that shows off pretty much all of the DSL

**Comment by finnagin** [comment]
@dkoslicki  So I've added a one hop use case and a two hop "kitchen sink" use case to the wiki [here](https://github.com/NCATSTranslator/Translator-All/wiki/ARAX#use-cases) but I wasn't sure how/where to add them to that repo. Should they go in as json files this [directory](https://github.com/NCATSTranslator/testing/tree/main/ara-requests)?

Also, do the two examples I put in the wiki seem reasonable or would you modify them in some way?
