### ISSUE TITLE
Moving ARAX to KG2.6.3

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1441]
- [x] build a new KG2c from KG2.6.3 (put it at http://kg2c-6-3.rtx.ai:7474/browser/)
- [x] load it into plover

Rebuild or edit and put copies in /translator/data/orangeboard/databases/KG2.6.3 on the server:

- [x] configv2.json (should point to the new KG2)
- [x] KG2c meta knowledge graph
- [x] NodeSynonymizer
- [x] NGD database
- [x] COHD database
- [x] DTD model
- [x] DTD database

Note: As databases are rebuilt, the new copy of `configv2.json` will need to be updated to point to their new paths.

Other things:

- [ ] update the test triples that go in some NCATS repo? @finnagin
- [ ] update code base (should be just tweaks to tests for this KG2 version)

while I don't think substantial changes will be needed to the ARAX codebase for this KG2 version, I can see already that a number of tests are going to need tweaking (due to slightly different predicates, etc.). 

what branch should such changes go in? a new branch off of `NewFmt`? `NewFmt` itself? are we rolling KG2.6.3 out to the TRAPI 1.1 endpoints only? (and not 1.0?)

**Comment by finnagin** [comment]
@amykglen do we have a kg2 api endpoint up for 2.6.3? I regenerated the data.json file for kg2c but I just want to wait until there is a working endpoint to upload to the NCATS repo.

**Comment by chunyuma** [comment]
The database rebuild process run faster than I expected. The COHD database, DTD model and DTD database (except for `DTD_probability_database.db` which is still running and might need 2 weeks but I refreshed the 2.5.2 version to generate a refreshed version for replacement during these two weeks) are successfully rebuilt for kg2.6.3 and the corresponding `configv2.json` under `/data/orangeboard/databases/KG2.6.3` on `arax.ncats.io` are updated as well. So it seems like all databases right now are ready to switched to 2.6.3.

**Comment by amykglen** [comment]
> So what is our appetite for getting KG2.6.3 rolled out in the middle of the hackathon?
> Right now both 1.0 endpoints and 1.1 endpoints are on 2.5.2 (which is perhaps an advantage)
> One or both could be switched to 2.6.3 if we think we're ready. We probably would need to schedule a little work party to do so since there are several moving parts.
> Essentially all we need is a decision on what we want to do from a user perspective.
> Is #1445 a blocking issue that we need to resolve first?
> 
> I wonder if we should schedule an ARAX group meeting sometime today or tomorrow to discuss?

yeah, not sure whether or not we want to switch in the middle of the hackathon - happy to do a group meeting at some point. I don't think #1445 is a blocking issue since it also exists in KG2.5.2c. #1455 seems more concerning to me, though not sure it's extensive enough to be a blocking issue(?)

**Comment by edeutsch** [comment]
I suppose my plan is to migrate to 2.6.3 and perhaps TRAPI 1.1 on Friday after the hackathon completes. Perhaps the problem with that is second vaxes might knock some of us down. I won't rock the boat until at least then.

**Comment by amykglen** [comment]
closing this as we ended up not rolling out KG2.6.3 - will create a new one for KG2.6.7
