### ISSUE TITLE
requirements.txt install error

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1443]
Looks like the installing from requirements.txt is now failing. I believe this is coming from the chp_client install command. I'm not entirely familiar with this package @chunyuma do you know what is going on here? It's caused the last 3 NewFmt Travis builds to fail.

Here is the log from the travis ci build: https://travis-ci.com/github/RTXteam/RTX/builds/225440419#L194-L199

It says to look at the output of a log file but I'm sure if we can access that as Travis gets rid of the instance as soon as it encounters an error.

**Comment by chunyuma** [comment]
Hi @finnagin, it seems like there is a problem by installing `chp-client` package via the method they provided before. I'm asking CHP team to get help for this issue (Please see [here](https://github.com/di2ag/chp_client/issues/16)).

**Comment by saramsey** [comment]
I see a couple of additional options here, to consider:

1. Implement our own TRAPI query against the CHP API, thus bypassing their client (can even just use their [client python module](https://github.com/di2ag/chp_client/blob/main/chp_client/client.py) as a guide). Then we would have no external dependency on `chp_client`.
2. Fork the `di2ag/chp_client` GitHub repo, fix the bug, and then hard-code our requirements.txt to use the forked version. I've used this option in KG2 where I wanted to be sure another project didn't break the KG2 build system.

**Comment by chunyuma** [comment]
Thanks for these two suggestions @saramsey, I will take a look.

**Comment by amykglen** [comment]
is there a reason why we don't use the CHP API, @chunyuma? if CHP speaks TRAPI like the other KPs, we shouldn't even need a separate CHP module in expand (it could be handled by the `TRAPIQuerier`).

**Comment by chunyuma** [comment]
The CHP client is recommended by Chase from CHP team. So I don't know if the result returned by API is the same. I have to investigate it.

> if CHP speaks TRAPI like the other KPs, we shouldn't even need a separate CHPQuerier module in expand (it could be handled by the TRAPIQuerier).

@amykglen, [here](https://smart-api.info/ui/855adaa128ce5aa58a091d99e520d396) is the CHP API,  it should be using TRAPI 1.1, can I use `TRAPIQuerier `? If I can't, I can modify CHPquerier to use CHP API.

**Comment by amykglen** [comment]
hmm - I just tried plugging it into the `TRAPIQuerier`, but I haven't been able to get their API (1.1 or 1.0) to work properly. (I keep getting the error `"Method \"GET\" not allowed."`, even though I'm only doing POST requests, and the same requests work fine for other KPs' TRAPI APIs.)

so I guess it's not quite ready to be plugged into `TRAPIQuerier`. if their API is fixed up, it could be at that point. the one thing that would be lost is whatever CHP-specific parameters you have set up (like `CHP_survival_threshold`). I don't think there's a way to specify that via TRAPI queries at the moment..(?)

**Comment by chunyuma** [comment]
I'm trying to include their API into the `CHPQuerier` but it seems to have some problems. I'm fixing it now.

**Comment by chunyuma** [comment]
Thanks for your help, @finnagin!!

**Comment by yakaboskic** [comment]
@chunyuma I responded to you [chp_client issue](https://github.com/di2ag/chp_client/issues/16#issuecomment-839038795). I have tested the git chp_client install on both 3.7 and 3.8 and the install was successful. My thought is if your Travis build was running between 12AM and 5AM on Monday morning we were making some last minute updates to the client for TRAPI 1.1 and it may have pulled a temporarily unstable version. It should all be up now and working.

Also, CHP does speak TRAPI so you can ping our endpoints directly with any supported TRAPI queries and we'll respond if that is your preferred method. We built the chp_client with the intent of streamlining ARAs use of CHP. I apologize that if didn't seem to work out in this case. 

Please try the install again if you still wish to leverage the client and please let me know if you have any issues.

**Comment by yakaboskic** [comment]
@chunyuma could you share the query you are trying to run?

**Comment by yakaboskic** [comment]
@chunyuma It seems that there was just a few typos in your query and some formatting issues. I changed "categorize" -> "categories" and than 'false' -> False and "None" -> None, and then ran your code it and responds fine. I'll be working on endpoint tonight to make sure we handle malformed TRAPI errors more gracegully and actually let you know what happened instead of returning a 500. 

Below is the query I ran with those formatting changes:
``` json
query = {'message': {'query_graph': {'nodes': {'n0': {'ids': ['ENSEMBL:ENSG00000158077'], 'categories': ['biolink:Gene'], 'constraint': []}, 'n1': {'ids': ['CHEMBL:CHEMBL92'], 'categories': ['biolink:Drug'], 'constraint': []}}, 'edges': {'e0': {'predicates': ['biolink:interacts_with'], 'relation': 'None', 'subject': 'n0', 'object': 'n1', 'constraints': [{'name': 'predicate_proxy', 'id': 'CHP:PredicateProxy', 'operator': '==', 'value': ['EFO:0000714'], 'unit_id': None, 'unit_name': None, 'not': False}, {'name': 'EFO:0000714', 'id': 'EFO:0000714', 'operator': '>', 'value': 887, 'unit_id': None, 'unit_name': None, 'not': False}]}}}, 'knowledge_graph': {'nodes': {}, 'edges': {}}, 'results': []}, 'max_results': 10, 'trapi_version': 1.1, 'biolink_version': None}
```

**Comment by chunyuma** [comment]
Hi @yakaboskic, here is the code that I used (Please see below) and it seems to work now. But I found that calling API for this query seems a little bit slow. I'm wondering if the running speed is different between using the `chp_client` and `api`. Thanks!

```
## pip install git+https://github.com/di2ag/reasoner-validator#egg=reasoner-validator
## pip install git+https://github.com/di2ag/trapi_model#egg=trapi_model
import json
import requests
from jsonschema import ValidationError

from trapi_model.query import Query
from trapi_model.message import Message
from trapi_model.biolink.constants import *

class UnsupportedTrapiVersion(Exception):
    def __init__(self, version, message='Trapi Version not supported'):
        self.version = version
        self.message = message
        super().__init__(self.message)

    def __str__(self):
        return '{}: {}'.format(self.message, self.version)

class InvalidWildcardCategory(Exception):
    def __init__(self, category, message='Wildcard category not supported'):
        self.category= category
        self.message = message
        super().__init__(self.message)

    def __str__(self):
        return '{}: {}'.format(self.message, self.category)


class InvalidTrapiComponent(Exception):
    def __init__(self, trapi_version, trapi_component, validation_error_msg, message='Invalid TRAPI Component'):
        self.trapi_version = trapi_version
        self.trapi_component = trapi_component
        self.validation_error_msg = validation_error_msg
        self.message = message
        super().__init__(self.message)

    def __str__(self):
        return '{}: {} in Schema v{}, exited with {}'.format(
                self.message,
                self.trapi_component,
                self.trapi_version,
                self.validation_error_msg
                )

class QueryBuildError(Exception):
    def __init__(self, message):
        self.message = message
        super().__init__(self.message)

    def __str__(self):
        return self.message

def build_standard_query(
        genes=None,
        drugs=None,
        outcome=None,
        outcome_name=None,
        outcome_op=None,
        outcome_value=None,
        disease=None,
        trapi_version='1.1',
        biolink_version=None,
        batch_genes=None,
        batch_drugs=None,
        batch_diseases=None,
        ):

    if outcome is None:
        raise QueryBuildError('You must specify an outcome CURIE.')
    if outcome_op is None:
        raise QueryBuildError("You must specify an outcome operation consistent with \
                with your desired TRAPI version's Constraint Object.")
    if outcome_value is None:
        raise QueryBuildError('You must specify an outcome value to test.')
    if disease is None and batch_diseases is None:
        raise QueryBuildError('You must specify a disease.')
    if disease is not None and batch_diseases is not None:
        raise QueryBuildError('Only specify either diseases or batch diseases not both.')

    # Initialize Message
    message = Message(trapi_version, biolink_version)
    q = message.query_graph

    # Add disease or batch disease node
    if disease is not None:
        disease_node = q.add_node(disease, BIOLINK_DISEASE)
    else:
        disease_node = q.add_node(batch_diseases, BIOLINK_DISEASE)

    if genes is not None:
        # Add gene nodes
        gene_nodes = []
        for gene in genes:
            gene_nodes.append(q.add_node(gene, BIOLINK_GENE))

        # Connect all gene nodes to disease.
        for gene_node in gene_nodes:
            q.add_edge(gene_node, disease_node, BIOLINK_GENE_ASSOCIATED_WITH_CONDITION)

    # Setup batch genes
    if batch_genes is not None:
        if type(batch_genes) is not list:
            raise QueryBuildError('Batch genes must be a list.')
        batch_gene_node = q.add_node(batch_genes, BIOLINK_GENE)
        q.add_edge(batch_gene_node, disease_node, BIOLINK_GENE_ASSOCIATED_WITH_CONDITION)

    if drugs is not None:
        # Add drug nodes
        if drugs is not None:
            drug_nodes = []
            for drug in drugs:
                drug_nodes.append(q.add_node(drug, BIOLINK_DRUG))

        # Connect all drug nodes to disease.
        for drug_node in drug_nodes:
            q.add_edge(drug_node, disease_node, BIOLINK_TREATS)

    # Setup batch drugs
    if batch_drugs is not None:
        if type(batch_drugs) is not list:
            raise QueryBuildError('Batch drugs must be a list.')
        batch_drug_node = q.add_node(batch_drugs, BIOLINK_DRUG)
        q.add_edge(batch_drug_node, disease_node, BIOLINK_TREATS)

    # Connect drug node to outcome node
    outcome_node = q.add_node(outcome, BIOLINK_PHENOTYPIC_FEATURE)
    phenotype_edge = q.add_edge(disease_node, outcome_node, BIOLINK_HAS_PHENOTYPE)
    q.add_constraint(outcome_name, outcome, outcome_op, outcome_value, edge_id=phenotype_edge)

    query = Query(trapi_version=trapi_version, biolink_version=biolink_version)
    query.message = message
    return query


if __name__ == "__main__":
	q = build_standard_query(genes=['ENSEMBL:ENSG00000121879', 'ENSEMBL:ENSG00000141510', 'ENSEMBL:ENSG00000196557', 'ENSEMBL:ENSG00000132155'], drugs=['CHEMBL:CHEMBL88'], disease='MONDO:0007254', outcome='EFO:0000714', outcome_name='survival_time', outcome_op='>', outcome_value=1000, trapi_version='1.1')
	r = requests.post('http://chp.thayer.dartmouth.edu/query/', json=q.to_dict())
	chp_res = json.dumps(json.loads(r.content), indent=2)
	print(chp_res)
```

**Comment by chunyuma** [comment]
@finnagin, I think this issue should be solved now.

**Comment by yakaboskic** [comment]
@chunyuma Yeah, sometimes it can be a little slow when your asking a complicated query. Since you asked a query with 4 genes it's going to take a little while to calculate that query. If you wrote this as a batch one hop query (i.e. one gene and one drug) you'd get much faster responses. Using the build_standard_query with batch_genes option should allow you to do that. Hope that makes sense. I can also pass you a sample batch query as well as an example if you like!

**Comment by chunyuma** [comment]
Ah, I see, thanks @yakaboskic. I didn't directly use the `build_standard_query` function in chp_client package because this package has to depend on `git+https://github.com/di2ag/reasoner-validator#egg=reasoner-validator` but in our `requirements.txt`, we have another dependent package `git+git://github.com/NCATSTranslator/reasoner-validator@master#egg=reasoner-validator` which causes a name conflict. So I modified your original `build_standard_query` function where I just simply hard-code the `query`. And it seems to work now. Thanks so much for your explanation.

**Comment by chunyuma** [comment]
@finnagin, can we close this issue?

**Comment by finnagin** [comment]
Yes
