### ISSUE TITLE
Add SEMMEDDB sentences?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1444]
Suggestion from Matt Might and Will Byrd: when we display SEMMED edges and publications, include the sentence that SEMMED has. Will says ARAX/KG2 has this info, but it appears that NGD is just not storing this in the TRAPI response. The UI would also need to be changed to display this info if available.

**Comment by amykglen** [comment]
would this apply to regular semmeddb edges from KG2c rather than NGD edges? I had delayed including `publications_info` in KG2c to save space, but maybe it's time to start including it...

and if we can stuff the `publications_info` into TRAPI attribute(s), maybe no UI adjustments will be required?

**Comment by isbluis** [comment]
Hi @dkoslicki .  The UI should be able to display any node/edge `attribute` already.  But I can change the presentation if something more obvious is desired -- just let me know (and of course if for some reason it does not work).

**Comment by edeutsch** [comment]
There's a description field that you can put anything you want in. I suggest breaking out all SEMMEDDB publications into individual attributes (instead of expressing all PMIDs as a list in one attribute) and put that information in the description field like this:
```
    {
      "attribute_type_id": "biolink:has_supporting_publication",  
      "value": "PMID:2012345",       
      "value_type_id": "biolink:Publication",     
      "value_url":  "https://pubmed.ncbi.nlm.nih.gov/2012345",
      "description": "Supporting sentence: We demonstrate that rhinitis symptoms are ameliorated by fluticasone propionate",
      "attribute_source": "infores:SemMedDB",
      "original_attribute_name": "evidence"
    }
```

**Comment by dkoslicki** [comment]
Nice! @finnagin and @amykglen, are Eric’s suggestions straightforward to implement?

**Comment by kvarforl** [comment]
Just a heads up that the `publications_info` slot in KG2 is a bit chaotic and inconsistent: see #1293 for what's currently happening for each source that uses it. I think the general conclusion we came to was to wait for guidance from EPC as to how to properly model scores etc in KGX format, but if we need a fix sooner than that suggestions are welcome :)

**Comment by dkoslicki** [comment]
Resurrecting this issue as it has been identified as high-priority for the December demo. We can either display the extracted sentence next to the NGD PMIDs, and/or the triple + score next to the PMIDs. Comes from Workflows B, C, and D groups

**Comment by isbluis** [comment]
Will do! I'll find a way to display it once that information is in the result(s).

**Comment by amykglen** [comment]
I'll work on getting KG2pre's `publications_info` field into KG2c/Plover, so that Expand can load it into TRAPI attributes.

although, @dkoslicki - are you wanting this info on NGD edges as well? if we need these on NGD edges _and_ KG2 edges, it might make sense to make whatever system we come up with work for both of those... (i.e., maybe we could create a separate database where the sentence(s)/score(s) for a given subject-object combination could be looked up.. further distinction by predicate would also be needed for KG2 edges, but that'd be fairly easy to achieve..)

**Comment by dkoslicki** [comment]
Correct @amykglen the main request was for the NGD edges, so making it work for both seems the best way to go about it

**Comment by amykglen** [comment]
the additions to ARAXDecorator for this issue are done - will be deployed as part of the KG2.7.2 rollout (changes are in `kg2integration`)

it can be used to decorate NGD edges with publication info/sentences like so:
```
decorator = ARAXDecorator()
decorator.decorate_edges(response, kind="NGD")
```
(where `response` is the usual `ARAXResponse`)

**Comment by finnagin** [comment]
31b172f948999fff80363909cdb3067ad36502d5

**Comment by isbluis** [comment]
Please let me know if/when there is a response that contains these sentences so I can work on displaying them in the UI.
Thanks!

**Comment by dkoslicki** [comment]
@finnagin I see in 31b172f you added the NGD decorator, but on the recent deployment: https://arax.ncats.io/?r=23862 They are not showing up. Is something else required in order to display the sentences?

**Comment by amykglen** [comment]
changes for this issue are still in a branch - will be deployed with the next KG2 rollout. there'll be discussion about when that can happen at today's AHM.

**Comment by amykglen** [comment]
I'll be sure to share an example here for @isbluis when it's ready!

**Comment by amykglen** [comment]
alright, these are in production now! an example for @isbluis: https://arax.ncats.io/?r=27365 (just click on either of the edges and look for the `bts:sentence` attribute)

**Comment by isbluis** [comment]
Thank you, @amykglen !

Is this close to what you had in mind, @dkoslicki ?
https://arax.ncats.io/devLM/index.html?r=27365
https://arax.ncats.io/devLM/index.html?r=27363

Do note that there are other metrics that could potentially be shown, but don't want to add unnecessary clutter -- look at the data under the `bts:sentence` attribute to see what else is available.

Easy to adjust/improve/re-style, so let me know.

**Comment by dkoslicki** [comment]
I definitely like how clean the display is for this part:


attribute_source: | infores:semmeddb
-- | --
attribute_type_id: | biolink:publications
value_type_id: | biolink:Uriorcurie
value: | PMID:8659683 "In this study, to clarify the influence of CYP2E1 genotype on alcohol metabolism, we analyzed acetaminophen metabolism in subjects with different CYP2E1 genotypes."PMID:31885815 "However, cells in the alveolar space, including the pulmonary epithelium and resident macrophages, express the APAP-metabolizing enzyme CYP2E1 and are a potential source of toxic metabolites and subsequent distal lung injury."PMID:21130154 "Our results indicated that when acetaminophen or ethanol were used as CYP2E1 substrates, the exclusive localization of CYP2E1 within mitochondria was sufficient to induce reactive oxygen species overproduction, depletion of reduced glutathione, increased expression of mitochondrial Hsp70, mitochondrial dysfunction and cytotoxicity."

The only other relevant pieces of information appear to be the date (is it a recent pub, or old) as well as the (subject score+object score)/2 (perhaps divided by 1000 or whatever. This actually brings up the following: @finnagin do we know what the maximum subject and object scores are? If so, there might be a natural way to rank the PMIDs based on quality of the prediction (eg. Instead of just taking 30 arbitrary PMIDs, we could take the top 30 according to subject/object score).

In any case @isbluis , I think what you have looks good for now until we figure out how/if we want to show the scores too

**Comment by isbluis** [comment]
Great, thank you for the prompt feedback!

**Comment by dkoslicki** [comment]
I like the dates you’ve added just now @isbluis!

**Comment by isbluis** [comment]
I do notice the list of publication PMIDs for many/most NGD edges do not fully correlate to those in `bts:sentence` . 

e.g. Result 1 in https://arax.ncats.io/devLM/index.html?r=27363

Perhaps this is by design, but thought I'd point it out just in case.

**Comment by dkoslicki** [comment]
Was that the intended result @isbluis ? I'm getting the following error with that link:
```
Response with id=27363 was not found (404)
```

**Comment by isbluis** [comment]
Yea, my bad.  Fixed my temporary bug; please try again when you are able to.  Thanks!

**Comment by amykglen** [comment]
> I do notice the list of publication PMIDs for many/most NGD edges do not fully correlate to those in `bts:sentence` .
> 
> e.g. Result 1 in https://arax.ncats.io/devLM/index.html?r=27363
> 
> Perhaps this is by design, but thought I'd point it out just in case.

yes - many of NGD's PMIDs come from sources other than SemmedDB, and thus we don't have associated sentences for them. thanks for checking!

**Comment by amykglen** [comment]
also note that it's possible for there to be a sentence in `bts:sentence` for a PMID that does not appear in the `biolink:publications` list - this is because we truncate the `biolink:publications` list (to 20 or 30, I think)

**Comment by isbluis** [comment]
Excellent, thank you for the clarifications, @amykglen !

**Comment by isbluis** [comment]
This has been released to our production server:  https://arax.ncats.io/

Please let us know if other changes are desired, such as displaying scores in a certain way etc.

**Comment by amykglen** [comment]
@dkoslicki are we good to close this issue?

**Comment by dkoslicki** [comment]
Yes indeed!
