### ISSUE TITLE
We are discarding a bunch of helpful BTE information

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1450]
When we expand a query using _just_ BTE, we get a lot of helpful info (that practitioners ask for) about drugs. Eg. Click on the Acetaminophen node here: https://arax.ncats.io/beta/?r=9380 and note the clinical phase, drug categories, contraindications, indications, etc.. However, when we query with KG2 + BTE, this is discarded. Take a look at acetaminophen at https://arax.ncats.io/beta/?r=9394. The DSL for that last query is:
```
add_qnode(id=CHEMBL.COMPOUND:CHEMBL112, key=n0, category=biolink:ChemicalSubstance)
add_qnode(key=n1)
add_qedge(subject=n0, object=n1, key=e0)
expand(kp=BTE)
expand(kp=ARAX/KG2)
filter_kg(action=remove_edges_by_property,edge_property=is_defined_by,property_value=ARAX/KG2,remove_connected_nodes=true,qnode_key=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=150)
```

**Comment by amykglen** [comment]
ah - I think what's happening is that it's kind of arbitrary which version of a node is kept when multiple KPs return it - so in this case, the KG2 version of acetaminophen is being kept, and not the BTE one.

sounds like you would rather nodes were 'merged' in this situation? (i.e., their attributes combined?)

**Comment by dkoslicki** [comment]
Correct: if two KPs return the same attribute keys, then either flip a coin or take the longest. But if they return disjoint attribute keys, return them all. Does that sound reasonable/realistic?

**Comment by dkoslicki** [comment]
Oh interesting! Maybe just take the union, make it unique, and call it good? That way if one has different publications than the other, they are all returned.

**Comment by amykglen** [comment]
> Maybe just take the union, make it unique, and call it good? That way if one has different publications than the other, they are all returned.

hmm, I'm not completely following what you mean here... but I went ahead and pushed a 'crude' version of node attribute merging to `NewFmt` that only keeps distinct attributes (based on names). (so right now, if multiple attributes had the same name, we would only keep one of them.) 

though allowed, I don't think it's very common at the moment for two node attributes to have the same name but contain different information (haven't seen it yet), but I added a couple questions on this topic to the [google doc](https://docs.google.com/document/d/1TrbHBtERoZlhzgdCrpf4RCyJhAaJEc4tzRerkQICupg/edit#) for issue #1414, as it seems like the eventual discussion we plan to have for that issue would be a good time to work out the details!

**Comment by dkoslicki** [comment]
>though allowed, I don't think it's very common at the moment for two node attributes to have the same name but contain different information 

Ah, that was what my idea was to address. Things like, from KP1: `prop_name: prop_val1, prop_val2` and from KP2 ``prop_name: prop_val1, prop_val3`, the union would be `prop_name: prop_val1, prop_val2,prop_val3`. But if this is rarely/never the case, then I guess we can ignore it. I was thinking it might happen frequently with publications since we truncate to 30 (and those 30 are randomly chosen, iirc).

**Comment by amykglen** [comment]
ah, I see what you're saying. yeah, maybe that's a possible approach. we'd also have to figure out how to merge the other TRAPI 1.1 attribute properties (like `attribute_source`, `value_url`, `description`).. indeed I think it's rarely/never the case for now, so sounds good to punt to #1414!

**Comment by amykglen** [comment]
nice - I actually happened to add that into the google doc as one of my questions for #1414 :). there's not an obvious slot to put that info in in the TRAPI 1.1 attributes, but I agree it'd be nice to have.

**Comment by amykglen** [comment]
not working as expected on NewFmt yet (still missing BTE attributes in some cases). will fix.

**Comment by amykglen** [comment]
looks good on production now https://arax.ncats.io/?r=15708
