### ISSUE TITLE
make ARAX Dockerfile

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1459]
Need to create a Dockerfile for building the Ubuntu 16.04-based image that is used to run ARAX inside a container. For a template you can see the [KG2 build system Dockerfile](https://github.com/RTXteam/RTX/blob/master/code/kg2/Dockerfile). This is due to NCATS by COB May 21.

**Comment by saramsey** [comment]
Note, the KG2 build system Dockerfile is for Ubuntu 18.04. But it does nicely illustrate how to set up a Dockerfile for an Ubuntu instance with passwordless sudo.

**Comment by saramsey** [comment]
See also the [NCATS ITRB Standard CI CD Policy](https://docs.google.com/document/d/1DEHrRH-euvYCO8PrF4eyQjlOVp63mRFx99YvKYIjGR8/edit) document.

**Comment by finnagin** [comment]
Closing this until any issues arise from ITRB trying to get it up and running.
