### ISSUE TITLE
Cache GUI

### ISSUE THREAD

**Issue by jaredroach** [RTXteam/RTX#146]
Need to switch from a slider to some other visual like a checkbox or a radio box. I cannot tell if it is off or on.

**Comment by jaredroach** [comment]
If cache is on and the question has not been answered, GUI returns "undefined" asa result. Instead, the GUI should automatically switch to "cache is off" and return an uncached answer. Otherwise, the end user assumes that the Reasoner cannot answer the question - it is not intuitive to try the question again with the cache off.

**Comment by edeutsch** [comment]
the first problem reported by be fixed by making the widget longer physically.

The seond problem is this:
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1040, 'Too many connections')
that's mine to figure out.

**Comment by edeutsch** [comment]
"undefined" issue is a MySQL problem that is separate.

Let's return this issue back to the slider.
I suggest making it longer.
I also suggest hiding it much better. There's rather little reason to use it except me while testing and maybe in an emergency at the hackathon if something is corrupt. Jared, you really oughtn't to be fiddling with it. If you're getting an error, fiddling with that switch isn't likely to help.

Luis, I suggest hiding it really well.
good camouflage. don't tempt users to flick it when things don't go right.

**Comment by dkoslicki** [comment]
@isbluis did you see this issue? You weren't tagged, so I wasn't sure.

**Comment by isbluis** [comment]
Thanks @dkoslicki 

I made the slider longer and the text label also changes color to indicate current state -- hope this clears the confusion.  If so, I can replace with a checkbox, but this looks nicer IMO.  

I also moved it to the far left to avoid tempting users.  Could eventually hide it in an "advanced options" block if desired.

(sorry, did not tag commit, but already in code)

**Comment by dkoslicki** [comment]
As @isbluis changed the slider to make it more clear when it's on or off, let's go ahead and close this issue.
