### ISSUE TITLE
Create class to translate from Operations/Workflow to ARAXi

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1463]

**Comment by edeutsch** [comment]
This worked very nicely, thanks.
I forgot to tag the issue, but I updated the class to emit a list of actions rather than a multi-line string buffer since it is needed in a list. https://github.com/RTXteam/RTX/commit/0511c1627858c56f2f96ee53d78b68a9b4eb4a24

**Comment by edeutsch** [comment]
@dkoslicki okay, I think the workflow system seems to be wired up at least in a rudimentary manner in the NewFmt branch v1.1 endpoint in production. Bugs probably abound. I will do some more testing. Here's an example of a simple client tool that works. It retrieves a previous message of 100 results, and then sends it to ARAX for processing using the nascent workflow language. Behold:
https://github.com/RTXteam/RTX/blob/NewFmt/code/UI/ClientExamples/Python/ExampleQuery_Workflow_1.py

I am wondering if it is doing too much? I notice this in the logs:
```
2021-05-13T23:13:13.325312: INFO: KG successfully pruned to match results
```
I have a vague recollection that `filter_results_top_n` isn't supposed to do that? That is a separate function? I don't know.

Anyway, there it is. The workflow runner can't be far behind!

**Comment by dkoslicki** [comment]
Great! And yes, I do think it might be doing too much: it's the 'ol balance between verbosity/atomicity and pragmatism. I.e. do we want to _just_ filter the top `n`, or also prune the KG since that's probably what the user wants. We can switch back if anyone raises a fuss, I assume

**Comment by dkoslicki** [comment]
@edeutsch Am I doing something dumb with the following? I tried posting
```
{
  "bypass_cache": false,
  "enforce_edge_directionality": false,
  "log_level": "DEBUG",
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "object": "n01",
          "predicates": [
            "biolink:physically_interacts_with"
          ],
          "subject": "n00"
        }
      },
      "nodes": {
        "n00": {
          "categories": [
            "biolink:ChemicalSubstance"
          ],
          "ids": [
            "CHEMBL.COMPOUND:CHEMBL112"
          ]
        },
        "n01": {
          "categories": [
            "biolink:Protein"
          ]
        }
      }
    }
  },
"workflow": [{ "id": "filter_results_top_n", "parameters": { "max_results": 15 } }]
}
```
to https://arax.ncats.io/api/arax/v1.1/query and received the following error:
`{
      "code": "UncaughtARAXiError",
      "level": "ERROR",
      "message": "An uncaught error occurred: object of type 'NoneType' has no len(): ['Traceback (most recent call last):\\n', '  File \"/mnt/data/orangeboard/NewFmt/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py\", line 529, in execute_processing_plan\\n    response.debug(f\"Before filtering, there are {len(response.envelope.message.results)} results\")\\n', \"TypeError: object of type 'NoneType' has no len()\\n\"]",
      "timestamp": "2021-05-14T03:12:29.429159"
    }`

**Comment by edeutsch** [comment]
Well, sorta, yes. ;-)
You are giving it only a query_graph and then telling it to filter results. this is equivalent to the ARAXi program:
```
add_qnode(ids=CHEMBL.COMPOUND:CHEMBL112, key=n00)
add_qnode(categories=biolink:Protein, key=n01)
add_qedge(subject=n01, object=n00, key=e00)
filter_results(action=limit_number_of_results,max_results=15,prune_kg=true)
```

If you give it a workflow, you can't assume that ARAX can know that you'd like it to run the QueryGraphInterpreter and do stuff before you run your workflow. Your workflow needs to tell ARAX exactly what to do since you're taking control.

**Comment by edeutsch** [comment]
@dkoslicki  I had originally coded things up so that operations and workflow were mutually exclusive. But after pondering things for a while, I have now switched it so that workflow[] runs *after* operations. So you can run some ARAXi (including add_qnode() and expand() etc. and THEN it will work on workflow commands.

This may not be a final end state, but it occurs to me that this will make testing and development easier for now.

I just commited this as an example:
https://github.com/RTXteam/RTX/blob/NewFmt/code/UI/ClientExamples/Python/ExampleQuery_ARAXi__Workflow_Combo.py

**Comment by dkoslicki** [comment]
Ah, I see. I didn't know how coupled/decoupled the workflow processing was to the query graph interpreter. I would assume this would work though:
```
{
  "bypass_cache": false,
  "enforce_edge_directionality": false,
  "log_level": "DEBUG",
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "object": "n01",
          "predicates": [
            "biolink:physically_interacts_with"
          ],
          "subject": "n00"
        }
      },
      "nodes": {
        "n00": {
          "categories": [
            "biolink:ChemicalSubstance"
          ],
          "ids": [
            "CHEMBL.COMPOUND:CHEMBL112"
          ]
        },
        "n01": {
          "categories": [
            "biolink:Protein"
          ]
        }
      }
    }
  },
"workflow": [{"id":"fill"}, {"id":"bind"},{"id":"filter_results_top_n", "parameters": { "max_results": 15 } }]
}
```
as it's equivalent to:
```
add_qnode(ids=CHEMBL.COMPOUND:CHEMBL112, key=n00)
add_qnode(categories=biolink:Protein, key=n01)
add_qedge(subject=n01, object=n00, key=e00)
expand()
resultify()
filter_results(action=limit_number_of_results,max_results=15,prune_kg=true)
```
but now I'm getting an internal server error:
```{
  "detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
  "status": 500,
  "title": "Internal Server Error",
  "type": "about:blank"
}```

**Comment by edeutsch** [comment]
yeah, this came up on the logs:
```
  File "/mnt/data/orangeboard/NewFmt/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py", line 36, in query
    envelope = araxq.query_return_message(query)
  File "/mnt/data/orangeboard/NewFmt/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 136, in query_return_message
    self.query(query, mode=mode)
  File "/mnt/data/orangeboard/NewFmt/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 178, in query
    self.convert_workflow_to_ARAXi(query)
  File "/mnt/data/orangeboard/NewFmt/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 274, in convert_workflow_to_ARAXi
    araxi = converter.translate(query['workflow'])
  File "/mnt/data/orangeboard/NewFmt/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/operation_to_ARAXi.py", line 64, in translate
    ARAXi.extend(getattr(self, '_' + self.__class__.__name__ + '__translate_' + operation['id'])(operation['parameters']))
KeyError: 'parameters'
```

not sure the cause yet, I should wrap it in a try except so these errors can be seen.

**Comment by dkoslicki** [comment]
> @dkoslicki I had originally coded things up so that operations and workflow were mutually exclusive. But after pondering things for a while, I have now switched it so that workflow[] runs _after_ operations. So you can run some ARAXi (including add_qnode() and expand() etc. and THEN it will work on workflow commands.
> 
> This may not be a final end state, but it occurs to me that this will make testing and development easier for now.
> 
> I just commited this as an example:
> https://github.com/RTXteam/RTX/blob/NewFmt/code/UI/ClientExamples/Python/ExampleQuery_ARAXi__Workflow_Combo.py

Ah yes, that will make it quite a bit easier to work with before we fully move to the workflow being "in control"

**Comment by dkoslicki** [comment]
Looks like I was passing the parameters even if they didn't exist. f9f6882 may fix it

**Comment by edeutsch** [comment]
line 67 is missing a close parens. I added one at the end of the line. is that right?
deployed with that now. done.

**Comment by edeutsch** [comment]
pushed. you can fix and push

**Comment by dkoslicki** [comment]
Ah, thanks! That's what I get for committing straight from my iPad without testing. :P

**Comment by edeutsch** [comment]
ha, np

**Comment by edeutsch** [comment]
wow, it all seems to be working. amazing!
I left some examples that I've been testing with here:
https://github.com/RTXteam/RTX/tree/NewFmt/code/UI/ClientExamples/Python

**Comment by dkoslicki** [comment]
@edeutsch Ok to close this one? Seems to be working currently.

**Comment by edeutsch** [comment]
sure, fine with me to close. I think the operations currently implemented are working fine. There are probably more operations that could be implemented by extending this class, but I assume you'll take care of that whenever you're ready. Technically I need to update the schema when you add new operations. All of the following operations are listed in our schema, as snatched from the Op&Wf repo a few weeks ago:
https://arax.ncats.io/api/arax/v1.1/ui/
(scroll down 2/3rds to find Operation****)

Also, technically to "advertise" that we can do these, we need to add the ones we support into the x-trapi construct at the top of the YAML:
https://github.com/RTXteam/RTX/blob/master/code/UI/OpenAPI/python-flask-server/RTX_OA3_TRAPI1.1_ARAX.yaml
(line ~25)

- Adding additional "advertised" operations in x-trapi that are already in our schema is trivial
- Adding/changing the schema of operations is more involved and would ideally be done less frequently and in batches
