### ISSUE TITLE
UI error for Q4

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#147]
As [Jared noted](https://github.com/RTXteam/RTX/issues/118#issuecomment-389333412) in #118, "What proteins are in the Phenylketonuria pathway" returns
```
An error was encountered:
undefined
```

But the dev info correctly gives:
```
{
  "known_query_type_id": "Q4",
  "original_question": "What proteins are in the Phenylketonuria pathway",
  "restated_question": "What proteins are in the pathway Phenylketonuria",
  "terms": {
    "pathway": "R-HSA-2160456",
    "rel_type": "participates_in",
    "target_label": "protein"
  }
}
```

So @edeutsch, something is going wrong on the UI side (or the response is not being parsed correctly).

**Comment by dkoslicki** [comment]
Error is returned if the cache is active *and* if the cache is not active.

**Comment by edeutsch** [comment]
MySQL is retching sadly in a corner. Trying to help it. Please don't start many issues on thsi same error with different questions...

**Comment by dkoslicki** [comment]
@edeutsch Sorry about that! Didn't see that Jared's #146 had more in it than a slider question. I'll close this as #146 already covers it.

**Comment by edeutsch** [comment]
MySQL is back on line and the the UI is working again. But the problem isn't ultimately solved. But since the error has nothing to do with Q4 and UI, closing this for now.
