### ISSUE TITLE
TRAPI 1.1 validation failing 

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1471]
In this KP: 22cb3843-ae8d-4aef-9ecf-658890ecb109 it says we’re failing the TRAPI 1.1 format validation. Patrick said it may be due to using the 1.0 validator instead of the 1.1 or something like that.

**Comment by edeutsch** [comment]
oops, due to last night's work.
Try again now?

**Comment by dkoslicki** [comment]
Ah, there we go, thanks!
