### ISSUE TITLE
KP reasoning target date floated

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1472]
I think there's already an issue related to this, but I couldn't find it..

As a KP, we are obligated perform some reasoning as stated in the architecture rules:
(9.2) Making categories in a query more specific. e.g. responding to a query for a biolink:NamedThing with a particular biolink:ChemicalSubstance.
(9.3) Making predicates more specific, e.g. responding to a query for “affects expression of” with an edge with predicate “increases expression of”. In the response, the more specific edge must occur in the knowledge_graph portion of the response, and in individual results, that more specific edge will be bound to the less specific query edge. Query Graph and Knowledge Graph edges need not match in either predicate or direction to be bound in an answer.

In today's Architecture call, a target date of June 1 was set for implementing these (kinda like a deadline but soft I suppose)

I think 9.2 is done?

But 9.3 not quite done? Or is it also done?

Can we/should we prioritize this completion around June 1?

What is our position on this?

**Comment by amykglen** [comment]
we've already done 9.2 and [9.3](https://github.com/RTXteam/RTX/issues/1268#issuecomment-817464822), so a June 1 deadline sounds fine to me for those! the only one we haven't yet done is 9.1.

**Comment by edeutsch** [comment]
Terrific! I have made a note in the Architecture agenda that 9.2 and 9.3 are complete for RTX KG2, thanks!
9.1 is still a topic of debate on how to express the results, so no rush on that for now I guess.
Thanks!

**Comment by saramsey** [comment]
What is 9.1?

**Comment by edeutsch** [comment]
Predicate inversion was 9.4, but it seems like the resolution is: Thou shalt not use inverses. I assume you and KG2 are down and on board with that?

9.1 is: Making identifiers more specific, e.g. responding to a query involving an entity with information related to a subclass of that entity.
