### ISSUE TITLE
Switch Expand's name for the KG2 KP from 'ARAX/KG2' to 'RTX-KG2'

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1475]
so the new command will be `expand(kp=RTX-KG2)` vs. `expand(kp=ARAX/KG2)`

figuring I'll do this in `master`, unless anyone objects!

**Comment by amykglen** [comment]
alright, switch is complete in `master`! (including updated documentation)

will the 'Select DSL Command' dropdown in the UI automatically be updated, or does something special need to happen for that? (@isbluis or @edeutsch)

**Comment by isbluis** [comment]
Hi @amykglen .  I'll need to make a small update to the interface.  Thanks!

**Comment by amykglen** [comment]
looks good on production, including the 'Select DSL Command' dropdown. closing!
