### ISSUE TITLE
Ranking concern?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1476]
I noticed [this concern](https://github.com/RTXteam/RTX/blob/88e4adce4d57fca70db5d0323bf5d216eb0f048b/code/ARAX/ARAXQuery/ARAX_ranker.py#L48) in the ranker. It appears this is just making a weighted networkx graph. Is this causing ranking issues?

**Comment by edeutsch** [comment]
I'm thinking that @finnagin found and fixed the problem (that I noted but did not understand) here:

https://github.com/RTXteam/RTX/commit/bf916457a3e1a3cad4a110670df958adc46164d5

So unless @finnagin has any concerns, I think we can assume my bleating for help was answered and the comment should be removed.

**Comment by finnagin** [comment]
Yeah I believe I fixed that during the TRAPI 1.0 move.

**Comment by finnagin** [comment]
I think this can be closed unless you are seeing issues arising from the fix.
