### ISSUE TITLE
Check for huge numbers of equivalent nodes during synonymizer build?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1477]
inspired by some brief brainstorming with @kvarforl about ways to detect problems in KG2/c:

in addition to identifying synonym groups with clashing categories (which it puts in Problems.tsv), could the synonymizer build also record somewhere any synonym groups with what seem to be way too many equivalent curies? (some of these groups will also have conflicting categories, but not all)

would help with catching #1423, #1432, and #1445

according to cypher, there are 89 nodes in kg2c-6-3 with more than 200 equivalent curies (and 70 in kg2c-5-2). I imagine this number was a lot higher in kg2c-6-2 and kg2c-6-1, so we might've recognized the problem sooner (before we even did a KG2c build) if we had recorded/inspected such info.

**Comment by edeutsch** [comment]
I regenerated the NodeSynonymizer build from KG2.5.2 as a reference. The output Problems.tsv has 2850 lines, which is more than I remember. but anyway, it would be great to work toward making the size of this file go down.

I have put it in:
/mnt/data/orangeboard/databases/KG2.5.2/
for reference.

**Comment by amykglen** [comment]
oversized clusters are now written up in an artifact of the synonymizer build

which is automatically uploaded to arax-databases.rtx.ai at:
```
/home/rtxconfig/KG2.8.0.1/extra_files/5_report_oversized_clusters.tsv
```
