### ISSUE TITLE
Filtering no longer works

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1478]
It appears with the TRAPI 1.1 re-working of attributes, the attribute filtering no longer works. Eg, in TRAPI 1.0, the following worked:
```
add_qnode(id=CHEBI:17754, category=biolink:ChemicalSubstance, key=n0)
add_qnode(category=biolink:Gene, key=n1)
add_qedge(subject=n1, object=n0, key=e0,predicate=biolink:negatively_regulates_entity_to_entity)
expand(kp=ARAX/KG2,continue_if_no_results=false,enforce_directionality=true,use_synonyms=true)
filter_kg(action=remove_edges_by_property,edge_property=provided_by,property_value=SEMMEDDB:,remove_connected_nodes=false)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```
Note the 0 results due to all being SEMMEDB.
But now in TRAPI 1.1, it doesn’t not:
```
add_qnode(ids=CHEBI:17754, categories=biolink:ChemicalSubstance, key=n0)
add_qnode(categories=biolink:Gene, key=n1)
add_qedge(subject=n1, object=n0, key=e0,predicates=biolink:negatively_regulates_entity_to_entity)
expand(kp=ARAX/KG2,continue_if_no_results=false,enforce_directionality=true,use_synonyms=true)
filter_kg(action=remove_edges_by_property,edge_property=provided_by,property_value=SEMMEDDB:,remove_connected_nodes=false)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```
Note the 30 results here.

I suggest:

- [x] Update the filter class to work with the new TRAPI 1.1 property format
- [x] Update the documentation to reflect this (eg. The UI should have a brief description about what you need to put where to filter things out)
- [x] Put a test case in that tests if filter is actually filtering (such as the one above that should provide 0 results).

**Comment by finnagin** [comment]
Looks like the attribute now looks like this:

attribute_type_id: | biolink:original_source
-- | --
value_type_id: | biolink:InformationResource
attribute_source: | infores:rtx_kg2_kp
value: | infores:semmeddb

Since filter currently looking at `original_attribute_name` but it looks like it should look for `attribute_type_id` instead. Will neeed to change this...

Also, it looks like the value  in the query should now be `infores:semmeddb` instead of `SEMMEDDB:` and the property should now be `biolink:original_source`


https://arax.ncats.io/?r=10548

**Comment by finnagin** [comment]
This should work now but the query has to be slightly different now since the names of some things have changed:

```
add_qnode(ids=CHEBI:17754, categories=biolink:ChemicalSubstance, key=n0)
add_qnode(categories=biolink:Gene, key=n1)
add_qedge(subject=n1, object=n0, key=e0,predicates=biolink:negatively_regulates_entity_to_entity)
expand(kp=RTX-KG2,continue_if_no_results=false,enforce_directionality=true,use_synonyms=true)
filter_kg(action=remove_edges_by_property,edge_property=biolink:original_source,property_value=infores:semmeddb,remove_connected_nodes=false)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```

Mainly `SEMMEDDB:` -> `infores:semmeddb`, `provided_by` -> `biolink:original_source`, and `ARAX/KG2` -> `RTX-KG2`

**Comment by finnagin** [comment]
Note to self: change filter by property to filter by discrete attribute and filter by attribute to filter by continuous attribute
