### ISSUE TITLE
Uncaught expand error

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1480]
DSL:
```
add_qnode(ids=MONDO:0005301, key=n0)
add_qnode(categories=biolink:ChemicalSubstance, key=n1)
add_qedge(subject=n0, object=n1, key=e0, predicates=biolink:related_to)
add_qedge(subject=n0, object=n1, key=e1, predicates=biolink:correlated_with,option_group_id=1)
expand(kp=ClinicalRiskKP,edge_key=e0)
expand(kp=COHD,edge_key=e1,continue_if_no_results=true,use_synonyms=true,COHD_method=paired_concept_freq,COHD_method_percentile=99)
#overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n0, object_qnode_key=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```

`ERROR: An uncaught error occurred: 'NoneType' object is not subscriptable: ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 524, in execute_processing_plan\n expander.apply(response, action[\'parameters\'], mode=mode)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 427, in apply\n user_specified_kp, force_local, log)]\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 542, in _expand_edge\n answer_kg = kp_querier.answer_one_hop_query(edge_qg)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Expand/COHD_querier.py", line 72, in answer_one_hop_query\n final_kg = self._answer_query_using_COHD_paired_concept_freq(query_graph, COHD_method_percentile, log)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Expand/COHD_querier.py", line 137, in _answer_query_using_COHD_paired_concept_freq\n if self.synonymizer.get_canonical_curies(target_preferred_key)[target_preferred_key][\'preferred_category\'] in target_qnode.categories:\n', "TypeError: 'NoneType' object is not subscriptable\n"]`

**Comment by amykglen** [comment]
looks like a COHD issue so I'm unassigning myself (I see @chunyuma has assigned himself)

**Comment by chunyuma** [comment]
Hi @amykglen, regarding this issue, I'm wondering if `expand` would automatically assign the preferred category to a query node before it called `COHD_querier.py` when the user didn't specify the category (like in this case, `add_qnode(ids=MONDO:0005301, key=n0)`). Thank you!

**Comment by amykglen** [comment]
hey Chunyu - yeah, `ARAXExpander` does automatically infer categories before `COHDQuerier` is called - you can see what it does in these log messages from the query:
```
2021-05-21T20:21:37.706016 DEBUG: Inferred category for qnode n0 is ['biolink:Disease']
2021-05-21T20:21:37.706055 DEBUG: Expand will consider qnode n0's category to be ['biolink:DiseaseOrPhenotypicFeature', 'biolink:Disease', 'biolink:PhenotypicFeature']
2021-05-21T20:21:37.706087 DEBUG: Expand will consider qnode n1's category to be ['biolink:Drug', 'biolink:ChemicalSubstance']
2021-05-21T20:21:37.706245 DEBUG: Query graph for this Expand() call is: {'nodes': {'n0': {'ids': ['MONDO:0005301'], 'categories': ['biolink:DiseaseOrPhenotypicFeature', 'biolink:Disease', 'biolink:PhenotypicFeature'], 'is_set': False, 'constraints': None, 'option_group_id': None}, 'n1': {'ids': None, 'categories': ['biolink:Drug', 'biolink:ChemicalSubstance'], 'is_set': False, 'constraints': None, 'option_group_id': None}}, 'edges': {'e0': {'predicates': ['biolink:related_to'], 'relation': None, 'subject': 'n0', 'object': 'n1', 'constraints': None, 'exclude': False, 'option_group_id': None}}}
```
so you can see for qnode n0, it detects that the preferred category is biolink:Disease, and then it further converts this to ['biolink:DiseaseOrPhenotypicFeature', 'biolink:Disease', 'biolink:PhenotypicFeature'] (because it considers those categories equivalent).

**Comment by chunyuma** [comment]
Thanks @amykglen. This issue is solved in `NewFmt` branch. I'm wondering if I should merge it to `master` branch.

**Comment by edeutsch** [comment]
Development in `NewFmt` was completed and merged into `master` last week, and the branch is now dormant.

**Comment by chunyuma** [comment]
Thanks @edeutsch, so is it ok for me to merge it again to `master` for this fix because I fixed it under `NetFmt`.

**Comment by edeutsch** [comment]
yes, please do.
`NewFmt` is dormant.

**Comment by chunyuma** [comment]
I merge `NetFmt` to `master` now.

**Comment by edeutsch** [comment]
It is deployed to all locations now.

**Comment by chunyuma** [comment]
@dkoslicki, can we close this issue?

**Comment by dkoslicki** [comment]
Yes! Guess this slipped my radar without the "verify in next deployment" tag
