### ISSUE TITLE
Filter by stats not correctly displayed in UI

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1482]
It appears that the documentation has quite a few options for `filter_kg(action=remove_edges_by_stats)`, but the UI only has `type`, `remove_connected_nodes` and `qnode_key`. Looks like documentation somewhere needs to be updated. @finnagin LMK if this is something that Luis needs to address as well, or if you can do it on your end.

**Comment by finnagin** [comment]
Hmmm... @isbluis where does the UI look to populate the parameter info? Though I'm vaguely remembering this getting not included into the UI due to the complicated nature of the parameters causing issues. Do you remember if this was the case?

**Comment by isbluis** [comment]
Hi @dkoslicki . I typically need to run a command (`dsl2json.py`) in the UI area to update the helper file (`araxi.js`) that drives this portion of the UI.
I have updated it in master, but please let me know if anything is missing, or if I misunderstood what you were looking for.
Thanks!

**Comment by isbluis** [comment]
Hi @finnagin .  The UI gets the info from the `describe_me()` method from each of the commands under each module; similar to what is done for the DSL documentation page.
