### ISSUE TITLE
Remove edges by stat appears not to work

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1483]
In this DSL:
```
# Multiple sclerosis -> chemical substance with "related_to" from Clinical Risk KP
add_qnode(ids=MONDO:0005301, key=n0)
add_qnode(categories=biolink:ChemicalSubstance, key=n1)
add_qedge(subject=n0, object=n1, key=e0, predicates=biolink:related_to)
expand(kp=ClinicalRiskKP,edge_key=e0)
overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n0, object_qnode_key=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=10)
# Then look for proteins that are shared with these chemical substances and MS
add_qnode(categories=biolink:Protein, key=n2, is_set=True)
add_qedge(subject=n0, object=n2, key=e1)
add_qedge(subject=n1, object=n2, key=e2)
expand(edge_key=[e1,e2])
# rank drugs by Jaccard
overlay(action=compute_jaccard,start_node_key=n0,intermediate_node_key=n2,end_node_key=n1,virtual_relation_label=J1)
filter_kg(action=remove_edges_by_stats,edge_attribute=jaccard_index,type=n, threshold=10,remove_connected_nodes=true,qnode_key=n2)
overlay(action=compute_ngd, virtual_relation_label=N2, subject_qnode_key=n1, object_qnode_key=n2)
overlay(action=compute_ngd, virtual_relation_label=N3, subject_qnode_key=n0, object_qnode_key=n2)
resultify()
```
I get the error:
`2021-05-21T22:36:28.764728 ERROR: [TypeError]    Traceback (most recent call last): File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Filter_KG/remove_edges.py", line 337, in remove_edges_by_stats values = values[edge_params['threshold']:] TypeError: slice indices must be integers or None or have an __index__ method    2021-05-21T22:36:28.764773 ERROR: [UnknownError]    Something went wrong removing edges from the knowledge graph`

This is part of a workflow to be executed during the December demo.

**Comment by finnagin** [comment]
This has now been fixed and I've added a test for it.

**Comment by dkoslicki** [comment]
@finnagin , take a look at the comment on the commit. The docs say that `5 and 0.45 are examples of valid inputs.` while wrapping it in `int()` seems to not work with Jaccard and the like

**Comment by finnagin** [comment]
I commented on the commit comment (lol) but I'll also mention here that this is in the `edge_params['stat'] == 'n'` section so in this case threshold should in fact be treated like an int since it refers to the top/bottom n values.

**Comment by dkoslicki** [comment]
Hmmm, here again the documentation say `threshold specified by a floating point number` and gives an example of `filter_kg(action=remove_edges_by_stats, edge_attribute=jaccard_index, type=std, remove_connected_nodes=f, threshold=0.25, top=f, direction=above)`
I think perhaps we should:
1. Better specify when different types are required by different parameters or
2. Split this function into a few different ones so the parameters don't have such dependencies. 
Otherwise, it's not entirely clear that they type of `threshold` depends on `type`.
Thoughts?

**Comment by finnagin** [comment]
I think I like the idea of splitting `type=n` into it's own action. Since that is the only one where threshold changes and then leaving percentile and std in the same action.

**Comment by finnagin** [comment]
Change the parameter threshold to be n in `remove_by_top_n` and make it an int rather than float

**Comment by dkoslicki** [comment]
This DSL works for me:
```
# Multiple sclerosis -> chemical substance with "related_to" from Clinical Risk KP
add_qnode(ids=MONDO:0005301, key=n0)
add_qnode(key=n1)
add_qedge(subject=n0, object=n1, key=e0, predicates=biolink:related_to)
expand(kp=ClinicalRiskKP,edge_key=e0)
overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n0, object_qnode_key=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=10)
# Then look for proteins that are shared with these chemical substances and MS
add_qnode(categories=biolink:Protein, key=n2, is_set=True)
add_qedge(subject=n0, object=n2, key=e1)
add_qedge(subject=n1, object=n2, key=e2)
expand(edge_key=[e1,e2])
# rank drugs by Jaccard
overlay(action=compute_jaccard,start_node_key=n0,intermediate_node_key=n2,end_node_key=n1,virtual_relation_label=J1)
filter_kg(action=remove_edges_by_top_n,edge_attribute=jaccard_index, threshold=10,remove_connected_nodes=true,qnode_key=n2)
overlay(action=compute_ngd, virtual_relation_label=N2, subject_qnode_key=n1, object_qnode_key=n2)
overlay(action=compute_ngd, virtual_relation_label=N3, subject_qnode_key=n0, object_qnode_key=n2)
resultify()
```

**Comment by finnagin** [comment]
TODO: Need to remove type parameter form docstrigs so ui does not populate
