### ISSUE TITLE
Jaccard index not TRAPI 1.1 compliant?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1484]
I noticed that with any Jaccard index query, we get the following error:
`ERROR: TRAPI validator reported an error: 'biolink:has_jaccard_index_with' is not of type 'array' Failed validating 'type' in schema[0]: {'items': {'$ref': '#/components/schemas/BiolinkPredicate'}, 'minItems': 1, 'type': 'array'} On instance: 'biolink:has_jaccard_index_with' --- Normal completion`
We should check that our non-biolink predicates pass the validator (eg. `has_jaccard_index_with`, `probably_treats`, etc.)

Tagging @edeutsch so he can let @finnagin what needs to be changed.

**Comment by edeutsch** [comment]
When you add a predicate to a QEdge it must now be predicates[ ], an array. So instead of adding 'biolink:has_jaccard_index_with' to a QEdge (not Edge), add [ 'biolink:has_jaccard_index_with' ]
Same for all other additions to QEdges.

**Comment by finnagin** [comment]
Ah that makes sense. I didn't realize it had to be a list since add_qedge handles the case when you pass it one item without brackets. Thank you @edeutsch ! I think I know what I need to update now.

**Comment by dkoslicki** [comment]
This appears to be fixed on a recent deployment, so closing.
