### ISSUE TITLE
Incorporate feature_coefficient in ranker for ClincalRiskKP

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1485]
Eg. In this query:
```
# Multiple sclerosis -> chemical substance with "related_to" from Clinical Risk KP
add_qnode(ids=MONDO:0020066, key=n0)
add_qnode(categories=biolink:ChemicalSubstance, key=n1)
add_qedge(subject=n0, object=n1, key=e0, predicates=biolink:related_to)
expand(kp=ClinicalRiskKP,edge_key=e0)
overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n0, object_qnode_key=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```
Check out the edges that come from ClincalRiskKP which include the `bts:feature_coefficnet`. Higher is better. Negatives are possible (indicates a negative relationships), so just take absolute value.

**Comment by dkoslicki** [comment]
@dmkoslicki to ping Ryan Roper re: the logistic chosen

**Comment by dkoslicki** [comment]
@finnagin Here is what Ryan had to say:

>Hi David - Thanks for the code. I actually like having the log in there (I assume you're talking about np.log(abs(x))), because it skews the function to the right rather than making it symmetric about the transition point. I've played around with it and I think a logistic_midpoint of -0.15 will be good. That corresponds to a breakpoint feature_coefficient value of 0.86. In the printout below, left of the colon is the feature_coefficient value and right of the colon is the normalized 0-1 value. This fits pretty well with how I would weight feature_coefficient values on a 0 to 1 scale.
![image (1)](https://user-images.githubusercontent.com/6362936/122608141-ba329800-d049-11eb-9d7c-2717810d7956.png)

**Comment by finnagin** [comment]
Awesome! I'll change the midpoint value to -0.15.
