### ISSUE TITLE
In SmartAPI page for RTX-KG2 API, "source URL" is showing up as "not found"

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1486]
<img width="1444" alt="Screen Shot 2021-05-25 at 12 24 21 PM" src="https://user-images.githubusercontent.com/5562107/119556750-3a6c2300-bd54-11eb-8b84-110e855cfb96.png">

**Comment by edeutsch** [comment]
Note that this is the TRAPI v1.0 endpoint which will shortly be deleted. but I fixed it anyway. so it is now fixed.
But you should be using the v1.1 endpoint for anything that matters.

**Comment by edeutsch** [comment]
![image](https://user-images.githubusercontent.com/12707718/119579112-9d6cb280-bd72-11eb-9ba0-69d1b6d0f7e8.png)

**Comment by edeutsch** [comment]
okay to close?

**Comment by edeutsch** [comment]
deemed okay to close.
