### ISSUE TITLE
Get all pytests off of KG1 (use RTX-KG2 instead)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1488]
thought I'd create an issue for this so we have something to reference in commit messages!

this is necessary for #1459, though is something we were already planning to do

changes can go in `master` (after the test is adjusted as needed so that it works with KG2)

**Comment by amykglen** [comment]
ok, `expand` and `resultify`'s pytests no longer use KG1. looks like it's just the overlay, filter, and `test_ARAX_workflows` tests that remain?

**Comment by amykglen** [comment]
looks like the rest of the tests were moved off KG1 in #1521!

**Comment by finnagin** [comment]
Oops! Didn't see this issue when I opened that one lol.
