### ISSUE TITLE
Not getting results from BTE?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1489]
From the recent standup meeting (PK: 33732257-d60c-40a3-a02a-33e0e7821799), it looks like BTE is returning results (though they aren't respecting predicates, which is a known bug), but `expand()` says BTE returns no results, even if you use the old or new predicates:
old predicate:
```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "object": "n0",
                    "subject": "n1",
                    "predicates":["biolink:negatively_regulates_entity_to_entity"]
                }
            },
            "nodes": {
                "n0": {
                    "ids":["NCBIGene:23221"],
                    "categories": [
                        "biolink:Gene"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:Gene"
                    ]
                }
            }
        }
    }
}

```
new predicate:
```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "object": "n0",
                    "subject": "n1",
                    "predicates":["biolink:entityt_negatively_regulates_entity"]
                }
            },
            "nodes": {
                "n0": {
                    "ids":["NCBIGene:23221"],
                    "categories": [
                        "biolink:Gene"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:Gene"
                    ]
                }
            }
        }
    }
}
```

**Comment by amykglen** [comment]
hmm - yesterday they were returning 429 errors, but I see that's no longer happening today. there's one little typo in your second query graph (`entityt`), but even after fixing that they still don't return anything.

I'm not sure why they wouldn't respond with anything, but I don't see anything wrong on our end. we're still using their TRAPI 1.0 endpoint behind the scenes - maybe that could have to do with the difference vs. what they returned to the ARS? (I'll be switching to KPs' 1.1 endpoints soon #1467 - was waiting for them to be finalized.)

**Comment by dkoslicki** [comment]
Apologies for the typo (what I get for not copy and pasting). Andrew Su said he was going to send a curl command that returns BTE results, so when he does, we’ll be able to compare endpoints to see if it’s a 1.0 vs 1.1 issue.

**Comment by amykglen** [comment]
sounds good. yeah, playing around I can see that, very strangely, when I send the TRAPI 1.1 version of the QG to their TRAPI 1.0 endpoint, it _does_ seem to return results. but when I send a TRAPI 1.0 version of the QG to their TRAPI 1.0 endpoint, it doesn't return results. which doesn't make sense to me, but will go away once we switch to their 1.1 endpoint, I'm guessing.

**Comment by amykglen** [comment]
oh, actually, it seems like maybe they didn't keep their TRAPI 1.0 endpoint up? it looks like maybe their TRAPI 1.1 endpoint is at the same URL as their 1.0 was: https://api.bte.ncats.io/v1/query

**Comment by dkoslicki** [comment]
Indeed, I think this is the case: they are expecting TRAPI 1.1. Via Andrew Su:
```
BTE returns a non-zero result. curl command below -- are you seeing something different?
curl --silent --location --request POST "https://api.bte.ncats.io/v1/query" --header "Content-Type: application/json" --data-raw "{
    \"message\": {
        \"query_graph\": {
            \"edges\": {
                \"e01\": {
                    \"object\": \"n0\",
                    \"subject\": \"n1\",
                    \"predicates\":[\"biolink:negatively_regulates_entity_to_entity\"]
                }
            },
            \"nodes\": {
                \"n0\": {
                    \"ids\":[\"NCBIGene:23221\"],
                    \"categories\": [
                        \"biolink:Gene\"
                    ]
                },
                \"n1\": {
                    \"categories\": [
                        \"biolink:Gene\"
                    ]
                }
            }
        }
    }
}"

```

**Comment by amykglen** [comment]
thanks @dkoslicki - ok, I sorted it out on Slack with Andrew Su - their TRAPI 1.0 endpoint was moved from `https://api.bte.ncats.io/v1` to `https://bte.ncats.io/v1` when they rolled out their TRAPI 1.1 endpoint, so I just adjusted that URL on our end. and confirmed the query is now returning results from BTE.

(I'll be switching to KP 1.1 endpoints within the next couple of days, at which point I'll update this again to point to their 1.1 endpoint.)

**Comment by amykglen** [comment]
verified the query produces BTE results now! https://arax.ncats.io/?r=11438 good to close?

**Comment by dkoslicki** [comment]
Looks great to me, thanks Amy!
