### ISSUE TITLE
Ranker: store ranker values in score property instead of confidence property

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1493]
Just need to change confidence to score in ARAX_ranker.py

**Comment by edeutsch** [comment]
@isbluis is the GUI ready to handle Result.score values?

**Comment by isbluis** [comment]
Hi @edeutsch and @finnagin .  I have made some preliminary changes in my dev area, but ideally would like a test case.

Can you point me to a response_id that has this new score attribute?  Thanks!

**Comment by edeutsch** [comment]
@isbluis if you pull up cdfad6fa-c0b7-4e40-9df2-332b6cb8c972
and then click on the Aragorn response, you'll have scores

**Comment by isbluis** [comment]
Great, thank you @edeutsch .
I have pushed changes to the UI to capture result.score, but will still fallback to result.confidence if score is not present.

**Comment by finnagin** [comment]
Awesome! Thank you @isbluis !

**Comment by edeutsch** [comment]
thanks, I have rolled this out to all deployments. scores from all services that provide them should be visible at the next standup on Tuesday
