### ISSUE TITLE
Clean up requirements.txt 

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1494]
We may have cruft left over from the 'ol days resulting in things in requirements.txt that aren't actually needed. Ablate to discover which can be removed perhaps?

**Comment by edeutsch** [comment]
Maybe the Docker build process when it's finished can be used to easily test with a leave-one-out approach? ;-)
Or maybe using Travis CI would be even better.

**Comment by finnagin** [comment]
I'm thinking Travis might be best. I'll just make a new branch and just start removing modules one by one and see which ones cause tests to fail.

**Comment by finnagin** [comment]
Though are there any packages that we need that might not be caught by our tests?

**Comment by dkoslicki** [comment]
I like the Travis idea (as long as it’s turned on in the branch)! Let’s partition the requirements into “cause tests to fail” and “do not cause tests to fail”, since there may indeed be packages that are used (for things like the ResponseCach, Node synonymizer, DTD stuff, etc) that aren’t tested for.

**Comment by finnagin** [comment]
That sounds good to me. And I believe Travis automatically runs on all new commits to any branch unless you tell it not to run for a specific branch.

**Comment by amykglen** [comment]
> Though are there any packages that we need that might not be caught by our tests?

I think a few of the packages are needed for build processes whose code lies within ARAX - like the NGD build and KG2c. so I don't think any tests would fail if you removed those packages, but those build processes wouldn't work next time someone went to use them... should those few packages be moved to separate `requirements.txt` files? one file for each build process or something?

**Comment by dkoslicki** [comment]
Nice to have, but too low of priority
