### ISSUE TITLE
How do we encode FDA status of drugs?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1497]
It came up at today's Txl8r mini-hackathon about FDA status of drugs. It seems to be a plan to discuss this further at next week's Arch call.

How do we encode FDA status? How do we know when a ChemicalSubstance is FDA approved? In phase 2? in phase 3? Approved by the EU? etc.

How can we currently filter by status?

Should we try to support this via QNode.constraints?

**Comment by saramsey** [comment]
I think REPODB has this information encoded in its drug-to-indication edges in KG2, at least for the 9,701 drug-indication edges that come from REPODB

<img width="839" alt="Screen Shot 2021-06-03 at 9 14 55 AM" src="https://user-images.githubusercontent.com/5562107/120677671-2e671c00-c44c-11eb-8392-d6eaeadd03ca.png">

It is overwhelmingly probable that FDA approval information is available as some kind of attribute in one of the various sources for which we have ETL scripts, such as DrugBank, DrugCentral, ChEMBL, etc. We would just need to determine how specifically this information is supposed to be encoded in a Biolink-compliant KG. Node attribute, I assume?  Tagging @ericawood @acevedol @kvarforl

**Comment by kvarforl** [comment]
We also have the FDA approval status for Drugbank nodes, encoded with edges to nodes from MI:
from https://github.com/RTXteam/RTX/issues/1050#issuecomment-792049455
> Looks good in kg2.5.2:
> 
> ```
> match p=(n)-[e]-(m:`biolink:ChemicalSubstance`) where n.id in ["MI:2099", "MI:2100", "MI:2150", "MI:2148", "MI:2102", "MI:2149"] return n.id, n.name, count(m)
> ```
> 
> n.id 	n.name 	count(m)
> "MI:2148" 	"investigational drug" 	3762
> "MI:2102" 	"nutraceutical drug" 	97
> "MI:2099" 	"fda approved drug" 	3411
> "MI:2100" 	"experimental drug" 	6189
> "MI:2150" 	"illicit drug" 	204
> "MI:2149" 	"withdrawn drug" 	238

The predicate in kg2.5.2 for these edges is `biolink:has_attribute` and `biolink:related_to` for kg2.6.4

**Comment by edeutsch** [comment]
I think this is an important topic since a lot of queries involve "Which ChemicalSubstance...." and knowing their FDA (et al.) approval status seems important.

The choice seems to be between using edges or using node properties.

I expect that the strategy should and will be decided Translator-wide.

I think it is on the agenda for Tuesday's Architecture call.

Our preference could influence the decision.

**Comment by edeutsch** [comment]
Closing in favor of #1599
