### ISSUE TITLE
Application info summary for NCATS

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1499]
creating this issue for the info NCATS requested on today's dev/ops check-in

here's a start for PloverDB:

* **Name**: PloverDB
* **Repo**: https://github.com/RTXteam/PloverDB
* **Depends on**:
    * Applications: None
    * Remote files: An 8GB JSON file containing KG2c, auto-downloaded during image build (based on URI specified in config file)
* **Depended on by**:
    * Applications: ARAX
* **Config file**: Located in the repo at `PloverDB/app/kg_config.json`
    * TODO: Specify which slot points to the path to fetch KG2c JSON file from (after we work out where it will live with Noel)
* **How to build Docker image/run**: https://github.com/RTXteam/PloverDB#to-serve-the-latest-production-kg2c
* **How to test**: https://github.com/RTXteam/PloverDB#how-to-test

not sure if I missed anything they wanted? revisions welcome from anyone...

and here's a start for ARAX:

* **Name**: ARAX
* **Repo**: https://github.com/RTXteam/RTX
* **Depends on**:
    * Applications: PloverDB
    * Remote files: ?
* **Depended on by**:
     * Applications: None
* **Config file**: Located at ?
* **How to build Docker image/run**: ?
* **How to test**: ?

**Comment by saramsey** [comment]
It's good. A few gentle suggestions:

1. The `Config file` location should specify whether this is a source relative to repo location or an installed location for the config file in the container?
2.  Not sure if we are constrained by a NCATS template, but I feel that the dependency on `kg2c.json` should be noted somewhere. NCATS will want to where (inside the container) that file gets put.

**Comment by amykglen** [comment]
one thing I realized writing this up - if NCATS wants their NCATS-hosted ARAX to hit up their NCATS-hosted KG2 API, I think something will need to change with how `expand` decides what URL to send queries to... (otherwise, at the moment, their NCATS-hosted ARAX would just hit up our own KG2 API) 

could programmatically getting API URLs from SmartAPI as is planned in #1466 address that? will the KG2 API's SmartAPI registration point to NCATS' KG2 API endpoint or ours? not positive how that will work...

**Comment by saramsey** [comment]
> one thing I realized writing this up - if NCATS wants their NCATS-hosted ARAX to hit up their NCATS-hosted KG2 API, I think something will need to change with how `expand` decides what URL to send queries to... (otherwise, at the moment, their NCATS-hosted ARAX would just hit up our own KG2 API)
> 
> could programmatically getting API URLs from SmartAPI as is planned in #1466 address that? will the KG2 API's SmartAPI registration point to NCATS' KG2 API endpoint or ours? not positive how that will work...

NCATS IT seemed to favor using environment variables for runtime configuration. Perhaps we can arrange for an environment variable to be passed to the ARAX service running inside the ARAX container. If the variable is not set, then ARAX can do its default thing and query the default PloverDB hosted in the OSU COE-sponsored AWS EC2 instance. If the variable _is_ set, ARAX can use the endpoint URI specified in the variable, to construct the full URI for querying PloverDB (which presumably we could arrange to be the NCATS-hosted PloverDB endpoint URI).

**Comment by amykglen** [comment]
thanks @saramsey! adjusted the OP for your items 1-3... for the second part of item 2 - I did hear them say they want to know where that file gets put, but I thought they walked that back after Eric explained that it would be irrelevant to them since the code will handle fetching that file and putting it in the right place itself...

**Comment by edeutsch** [comment]
As soon as ITRB has the PloverDB instance up good, I'd think we should update our own ARAX instances to point to that, right? And then we can even turn our own PloverDB instance off?

**Comment by finnagin** [comment]
Closing as the config file now has the KG2 location as well as the ploverDB location.
