### ISSUE TITLE
regression test suite

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#15]
Hi Yao & Zheng,

You know how each of the “QueryXXXXX.py” modules has test code? Can you update all these modules so that the test methods can be run (all at once) as a set of regression tests, perhaps using the ‘test.regrtest’ or ‘unittest” package?

**Comment by saramsey** [comment]
RamseyMacBook:reasoningtool sramsey$ python3 -m unittest tests/QueryModuleTestSuite.py
..................HTTP response status code: 500 for URL:
http://www.geneprof.org/GeneProf/api/gene.info/regulation/binary/by.target/human/14428.json?with-sample-info=true
FHTTP response status code: 500 for URL:
http://www.geneprof.org/GeneProf/api/gene.info/regulation/binary/by.target/human/16269.json?with-sample-info=true
F..................................https://scigraph-ontology.monarchinitiative.org/scigraph/graph/neighbors/MESH:D005199
Status code 404 for url: https://scigraph-ontology.monarchinitiative.org/scigraph/graph/neighbors/MESH:D005199
...
======================================================================
FAIL: test_gene_symbol_to_transcription_factor_gene_symbols (tests.QueryGeneProfTests.QueryGeneProfTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sramsey/Work/Proj/rt/git/code/reasoningtool/tests/QueryGeneProfTests.py", line 42, in test_gene_symbol_to_transcription_factor_gene_symbols
    self.assertSetEqual(ret_set, known_set)
AssertionError: Items in the second set but not the first:

**Comment by saramsey** [comment]
see this original thread:
https://github.com/dkoslicki/NCATS/issues/131

**Comment by dkoslicki** [comment]
Closing due to #788 and #781
