### ISSUE TITLE
Integration of Autocompletion System into RTX UI

### ISSUE THREAD

**Issue by arnabdotorg** [RTXteam/RTX#150]
Trying to achieve parity with Google, breaking down the concept into pieces
- [ ] large, wide text box
- [ ] suffix term highlighting
- [ ] multi-token querying: if prefix match yields zero results, trigger match with just current word as prefix
- [ ] combine fuzzy match and prefix match in a smart fashion

Integrating into RTX's UI:
- [ ] locate points of integration (@edeutsch we will need your input on this)
- [ ] Have the RTX UI include the autocompletion javascript (`described in code/autocompletion/README`)

Testing and validation:
- [ ] Ensure we autocomplete the right questions
- [ ] Ensure that all questions shown by autocompletion can be answered by RTX

![image](https://user-images.githubusercontent.com/421604/40154188-28e4b4b8-595b-11e8-8425-05410d7c9a56.png)

**Comment by edeutsch** [comment]
yes, this is a nice decomposition of the project, excellent.
I am looping in @isbluis since he is the point person on the web page and JavaScript.

One technical point, can Javascript fetched from rtx.ncats.io do AJAX calls to http://rtxcomplete.ixlab.org? I am vaguely under the impression that this is disallowed. Oh, unless you configure your web server to explicitly allow cross-domain AJAX! There's a thing for that. Have you enabled that?

**Comment by edeutsch** [comment]
ah good, thanks. After Googling JSONP, I found a reference to CORS, which is what I was thinking of but couldn't recall exactly. whatever.

**Comment by arnabdotorg** [comment]
Also, in case we want to run the server locally to avoid crossdomain: the [autocomplete code README](https://github.com/RTXteam/RTX/blob/master/code/autocomplete/README.md) has instructions of how to use the code both through a frontend, or as a backend through python.

**Comment by edeutsch** [comment]
We will eventually want to install and run this on rtx.ncats.io, but I would propose that for the hackathon at least, let's see if we can get the cross-domain thing working. Developing on rtx.ncats.io is a bit awkward and I think it will be easier for @Palzer and @benjaminstrauss to be the captains of their own server for faster development.

**Comment by Palzer** [comment]
Done. No spellfix currently as it was unneeded, and the autocomplete suggestion server is running on an ixlab domain, can be moved to rtx domain later.
