### ISSUE TITLE
ARAX ERROR and halt on June 4 query

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1500]
Following up on Sarah's email, ARAX is generating an error on this query:
```
{
  "edges": {
    "e0": {
      "object": "n1",
      "subject": "n0"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:ChemicalSubstance"
      ]
    },
    "n1": {
      "categories": [
        "biolink:Gene"
      ],
      "ids": [
        "HGNC:6284"
      ]
    }
  }
}
```
The final error is:
```
2021-06-04T02:29:59.778162 INFO: Expanding qedge e0 using CHP
2021-06-04T02:30:01.107653 DEBUG: Processing query results for edge e0 by using CHP client
2021-06-04T02:30:01.107971 ERROR: The curie ids of ['HGNC:6284'] are not allowable based on CHP client
```
It kinda looks like processing is proceeding fine but then an error from a KP causes a halt to the whole thing? Needlessly?

This also looks a little suspicious:
```
2021-06-04T02:29:57.564813 DEBUG: Doing a refresh of local meta map for all KPs
2021-06-04T02:29:57.593069 DEBUG: No endpoint for NGD. Skipping for now.
2021-06-04T02:29:58.516532 DEBUG: No endpoint for COHD. Skipping for now.
2021-06-04T02:29:58.516591 DEBUG: No endpoint for DTD. Skipping for now.
2021-06-04T02:29:58.659486 DEBUG: No endpoint for CHP. Skipping for now.
2021-06-04T02:29:58.659542 DEBUG: No endpoint for ARAX/KG1. Skipping for now.
```
Maybe no problem, dunno...

**Comment by amykglen** [comment]
yeah, I think ideally the `CHPQuerier` wouldn't report an error in this case (maybe a warning instead, @chunyuma?) - but I'll also try to add some code to `expand` so a single KP returning an error doesn't halt the whole thing when multiple KPs are used. I just added some code that allows it to keep proceeding if an individual KP thread has an uncaught error, but since this error is actually entered in the log - meaning `respons.status != 'OK'` - that won't help this situation... will figure something out though

**Comment by edeutsch** [comment]
You can probably override the response.status. i.e. after merging the callee response into the current response, if the response.status is ERROR, but you decide that it's okay to continue, you could just do response.status = 'OK' and then keep going. Is that the issue? Does that work? The ERROR would remain in the log, but setting the response.status should allow things to keep going?

**Comment by chunyuma** [comment]
I will change these kinds of errors from `CHPQuerier ` to warning.

**Comment by amykglen** [comment]
> You can probably override the response.status. i.e. after merging the callee response into the current response, if the response.status is ERROR, but you decide that it's okay to continue, you could just do response.status = 'OK' and then keep going. Is that the issue? Does that work? The ERROR would remain in the log, but setting the response.status should allow things to keep going?

yep - I was thinking of doing that, or because that seemed a little messy, perhaps just grabbing the error and reporting it in a warning and then not merging the KP's individual response. but I think I like the first option better.

**Comment by chunyuma** [comment]
ok, now this kind of errors is changed to warnings under `master` branch.

**Comment by amykglen** [comment]
great! I also just pushed the change mentioned above so Expand forces the log status to `'OK'` in the event that one of multiple KPs reports an error (and verified that that fixes this issue prior to @chunyuma's changes).

**Comment by edeutsch** [comment]
super, thanks everyone! I have deployed this in test and it returns a reasonable answer:
https://arax.ncats.io/test/?r=11640

anyone object to rolling current state of master out to all deployments including main production?

**Comment by amykglen** [comment]
nice! no objections from me. although heads up @chunyuma that it looks like maybe your fix is throwing an uncaught error?

https://arax.ncats.io/test/?r=11640:
<img width="1066" alt="Screen Shot 2021-06-03 at 8 13 04 PM" src="https://user-images.githubusercontent.com/49423686/120740520-30f75f00-c4a8-11eb-8756-dc69c0a5c8d4.png">

**Comment by chunyuma** [comment]
oh, oops, I'm sorry for this error. I should double check that change.

**Comment by edeutsch** [comment]
oh yes, would be good to fix that first. the warning() method does not allow an error_code parameter

**Comment by chunyuma** [comment]
thanks @edeutsch, it should fix that error now.

**Comment by dkoslicki** [comment]
Y'all are fast! I'm just now catching up and it looks like you've got it handled! @edeutsch perhaps we can get this deployed before tomorrow?

**Comment by edeutsch** [comment]
The latest `master` is now deployed. All set.

**Comment by edeutsch** [comment]
The JSON query_graph in OP confirmed working in production, thanks everyone!
