### ISSUE TITLE
Remove KG2 from Travis?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1501]
Taking a look at a recent [build](https://travis-ci.com/github/RTXteam/RTX/builds/227940616), it looks like the ARAX tests passed, but the KG2 ones did not. Eg. `The command "bash -x ./code/kg2/setup-kg2-build.sh travisci" exited with 1.`

Perhaps ARAX Travis and KG2 Travis can be disconnected?

**Comment by saramsey** [comment]
That seems sensible.

**Comment by saramsey** [comment]
IIRC, the plan was to have RTXteam/RTX-KG2 have its own Travis CI.

**Comment by saramsey** [comment]
ok, I have updated `RTX/.travis.yml` to remove the KG2 stuff

**Comment by saramsey** [comment]
That last commit seems to have kicked off a new run of Travis CI. It may be awhile before we know definitively whether this commit improved things. I'm assuming just removing those three lines from the `.travis.yml` file should not break anything, right @finnagin ?

**Comment by saramsey** [comment]
Thank you for bringing this issue to my attention. This is yet another reason why it was a wise decision to split the repos, I think.

**Comment by finnagin** [comment]
Yup! That's exactly what I would have done. Thanks @saramsey !

**Comment by dkoslicki** [comment]
Confirmed tests now passing! Thanks @saramsey !
