### ISSUE TITLE
Queries from Users to Translate to ARAXI

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1502]
I pulled these questions from the notes documents on each user interview. Not all of them necessarily need to be translated, but I included them just in case!

From [Theo Knijnenburg](https://docs.google.com/document/d/1SqMXvv2spDyUVQcAbDvWZXlej2Q5sk1nr9Uf1DcisOU/edit?usp=sharing):

- which genes are the building blocks of organelle X?
- what are the regulators of the shapes and sizes and locations of organelle X in cell type Y?
- Which organelles are disrupted when the cell is treated with compounds X? (where X could be a cancer drugs, especially chemo drugs)
- Paths from genome to phenotype (can that connection be made on the organelle level?)

From [Samuel Handelman](https://docs.google.com/document/d/1PW6GW_0AZdZQgpsIIDGeN4_oZqBUCaF9I-7rz7QyV1U/edit?usp=sharing):
*note that these user notes also include two example workflows
- Drugs that hit protein interaction partners of SCN9A
- “Find me drugs that link to the genes perturbed in my experiment” (vs drugs that link to a disease)

**Comment by finnagin** [comment]
@saramsey Is this still something that we should look at or is it good to close?

**Comment by saramsey** [comment]
I've noted these in my use-case notes, and they are also in the Google Drive folder

NCATS/user-engagement-plan/User Interviews/

so I think we are good to close the issue. Thank you.
