### ISSUE TITLE
kg2c_meta_kg.json not found

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1503]
I've started seeing some errors like this in production:

```
127.0.0.1 - - [07/Jun/2021 22:15:51] "POST /api/arax/v1.1/query HTTP/1.1" 200 -
ERROR [get_meta_knowledge_graph]: File '/mnt/data/orangeboard/production/RTX/code/ARAX/KnowledgeSources/kg2c_meta_kg.json' not found
```

I think this is new, but I'm not certain.

anyone know anything about why this may be happening?

**Comment by saramsey** [comment]
That file doesn't exist:
```
sramsey@ip-172-31-53-16:/data/orangeboard/production/RTX/code/ARAX/KnowledgeSources$ sudo docker exec -it rtx1 bash
root@6d6766e08a31:/# su - rt
rt@6d6766e08a31:~$ ls -alh /mnt/data/orangeboard/production/RTX/code/ARAX/KnowledgeSources/kg2c_meta_kg.json
ls: cannot access '/mnt/data/orangeboard/production/RTX/code/ARAX/KnowledgeSources/kg2c_meta_kg.json': No such file or directory
```

**Comment by saramsey** [comment]
I think this is the "Meta Knowledge Graph", according to information that @amykglen posted in [issue 1412](https://github.com/RTXteam/RTX/issues/1412#issuecomment-828807361).

**Comment by saramsey** [comment]
Looks like we have a few to choose from:
```
ces$ locate kg2c_meta_kg.json
/translator/data/orangeboard/NewFmt/RTX/code/ARAX/KnowledgeSources/kg2c_meta_kg.json
/translator/data/orangeboard/databases/KG2.5.2/kg2c_meta_kg.json
/translator/data/orangeboard/databases/KG2.6.3/kg2c_meta_kg.json
/translator/data/orangeboard/kg2NewFmt/RTX/code/ARAX/KnowledgeSources/kg2c_meta_kg.json
```

**Comment by saramsey** [comment]
I'm not seeing this in the apache2 logs:

![Screen Shot 2021-06-07 at 4 26 00 PM](https://user-images.githubusercontent.com/5562107/121099639-132e4080-c7ad-11eb-8ff2-2fb20a63ba87.png)

Am I looking in the wrong place?

**Comment by edeutsch** [comment]
It seems like the answer is just that I created sym links in the NewFmt area but neglected to make sym links in the other deployments. So I will go ahead and do that. Thanks!

**Comment by edeutsch** [comment]
Actually I'm now thinking this might be better managed like other KG2 product files. @finnagin would you set up this file as part of the ARAX_database_manager.py mechanism?

**Comment by edeutsch** [comment]
So I'm thinking that when ARAX_database_manager.py is run on arax.ncats.io, it should create a sym link:

$RTX/code/ARAX/KnowledgeSources/kg2c_meta_kg.json   --> /mnt/data/orangeboard/databases/KG2.5.2/kg2c_meta_kg.json

Does that seem right and doable?

**Comment by finnagin** [comment]
So currently for any path included in the config.yml file. If you replace translator with mnt and that resulting path exists locally it will create a symlink instead of downloading. So on arax.ncats.io it should always make symlinks since that is where we are storing the files.

**Comment by finnagin** [comment]
https://github.com/RTXteam/RTX/blob/62bee3f6d947a30404ca5824fee1894b68a96063/code/ARAX/KnowledgeSources/knowledge_source_metadata.py#L82

^ location of hardcoded filepath

**Comment by edeutsch** [comment]
confirmed working in production in the application logs:
```
127.0.0.1 - - [10/Jun/2021 03:10:05] "GET /api/arax/v1.1/meta_knowledge_graph HTTP/1.1" 200 -
127.0.0.1 - - [10/Jun/2021 03:10:05] "GET /api/arax/v1.1/meta_knowledge_graph HTTP/1.1" 200 -
127.0.0.1 - - [10/Jun/2021 03:10:05] "GET /api/arax/v1.1/meta_knowledge_graph HTTP/1.1" 200 -
```
Closing, thanks, @finnagin !
