### ISSUE TITLE
Filter issue

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1504]
For this DSL:
```
add_qnode(ids=MONDO:0005301, key=n00)
add_qnode(categories=biolink:ChemicalSubstance, key=n01)
add_qedge(subject=n01, object=n00, key=e00, predicates=biolink:related_to)
expand(kp=ClinicalRiskKP, edge_key=e00)
overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n01, object_qnode_key=n00)
resultify()
filter_results(action=sort_by_edge_attribute, edge_attribute=feature_coefficient, direction=descending, max_results=30, prune_kg=true)
```
I get this error:
`2021-06-09T15:27:42.947664 ERROR: [UncaughtARAXiError]    An uncaught error occurred: 'NoneType' object is not subscriptable: ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 540, in execute_processing_plan\n filter_results.apply(response, action[\'parameters\'])\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_filter_results.py", line 307, in apply\n self.response = self.report_response_stats(self.response)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_filter_results.py", line 219, in report_response_stats\n response.debug(f"Number of nodes in KG by type is {Counter([x.categories[0] for x in message.knowledge_graph.nodes.values()])}") # type is a list, just get the first one\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_filter_results.py", line 219, in <listcomp>\n response.debug(f"Number of nodes in KG by type is {Counter([x.categories[0] for x in message.knowledge_graph.nodes.values()])}") # type is a list, just get the first one\n', "TypeError: 'NoneType' object is not subscriptable\n"]`

**Comment by finnagin** [comment]
I've added a test and this should be fixed now

**Comment by dkoslicki** [comment]
Great, thank you @finnagin !

**Comment by dkoslicki** [comment]
Closing this one, but found the sorting is not actually sorting. Will open new issue
