### ISSUE TITLE
Allow sort based on edge attribute specified in attribute_type_id

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1506]
For this DSL:
```
add_qnode(ids=MONDO:0005301, key=n00)
add_qnode(categories=biolink:ChemicalSubstance, key=n01)
add_qedge(subject=n01, object=n00, key=e00, predicates=biolink:related_to)
expand(kp=ClinicalRiskKP, edge_key=e00)
overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n01, object_qnode_key=n00)
resultify()
filter_results(action=sort_by_edge_attribute, edge_attribute=feature_coefficient, direction=descending, max_results=30, prune_kg=true)
```
the results are not actually being sorted. In https://arax.ncats.io/?r=12103 note that result 3 has

attribute_type_id: | feature_coefficient
-- | --
value: | 0.9076

But result 4 has:

attribute_type_id: | feature_coefficient
-- | --
value: | 8.158

**Comment by dkoslicki** [comment]
Oh, and the `max_results` is not being respected

**Comment by dkoslicki** [comment]
Very minor: looks like `filter` is being called `overlay` in the debugs: 
`2021-06-09T20:52:07.521884 DEBUG: Applying Overlay to Message with parameters {'action': 'sort_by_edge_attribute', 'edge_attribute': 'feature_coefficient', 'direction': 'descending', 'max_results': 30, 'prune_kg': 'true'}`

**Comment by dkoslicki** [comment]
Ah, here we go: 
`2021-06-09T20:52:07.521846 WARNING: Supplied value feature_coefficient is not permitted. In action {'sort_by_edge_attribute'}, allowable values to edge_attribute are: ['normalized_google_distance', 'provided_by', 'is_defined_by', 'defined_datetime', None, 'publications']`

Looks like `feature_coefficient` isn't being recognized, might be due to a name change of attribute->attribute_type_id+value

**Comment by dkoslicki** [comment]
Looks like this is due to using `attribute_type_id` instead of `original_attribute_name` to specify the edge attribute. We can either:
1. Add a new sort that accepts attributes specified in `attribute_type_id` or
2. Look at `attribute_type_id`, `original_attribute_name`, etc. to see if the edge attribute given in the parameter (`feature_coeficient` in this case) can be found and just sort on this

**Comment by dkoslicki** [comment]
(sorry for all the short updates)
After this is addressed, this should be deployed to master before 11AM EDT tomorrow (6/10)

**Comment by edeutsch** [comment]
I'm available to deploy for most of the rest of the evening

**Comment by dkoslicki** [comment]
That's great @finnagin! Is the sorting now working properly? I'm not in front of a desktop

**Comment by finnagin** [comment]
Looks like it to me. There are 30 results and the first 5 feature coefficients are: 8.366, 8.158, 3.2812, 3.2478, & 2.5673

**Comment by dkoslicki** [comment]
Awesome! @edeutsch can you deploy to production?

**Comment by finnagin** [comment]
If he is busy I can also deploy it there after dinner.

**Comment by dkoslicki** [comment]
Perfect! LMK and I can let the appropriate parties know before the hackathon tomorrow

**Comment by edeutsch** [comment]
okay, the current 'master' is now rolled out to all deployments. Care to test and then let everyone know if fixed?

**Comment by dkoslicki** [comment]
Confirmed and looking great! Thanks all!

**Comment by rtroper** [comment]
Thanks @dkoslicki (and ARAX team) for your work on this! Looks great.
