### ISSUE TITLE
DSL works, but query graph does not

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1508]
This DSL runs just fine:
```
add_qnode(key=n0, categories=biolink:Gene, is_set=True)
add_qnode(key=n1, ids=CHEBI:45783, categories=biolink:ChemicalSubstance)
add_qedge(key=e01, subject=n0, object=n1, predicates=biolink:related_to)
add_qnode(key=n2, ids=MONDO:0005301, categories=biolink:Disease)
add_qedge(key=e02, subject=n0, object=n2, predicates=biolink:related_to)
add_qnode(key=n3, categories=biolink:ChemicalSubstance)
add_qedge(key=e03, subject=n0, object=n3, predicates=biolink:related_to)
expand()
overlay(action=compute_jaccard,start_node_key=n1,intermediate_node_key=n0,end_node_key=n3,virtual_relation_label=J1)
overlay(action=compute_jaccard,start_node_key=n2,intermediate_node_key=n0,end_node_key=n3,virtual_relation_label=J2)
overlay(action=compute_ngd,default_value=inf,virtual_relation_label=N1,subject_qnode_key=n3,object_qnode_key=n2)
overlay(action=compute_ngd,default_value=inf,virtual_relation_label=N2,subject_qnode_key=n3,object_qnode_key=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=50, prune_kg=true)
```
But the associated query graph (sans the overlay) does not:
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:Gene"]
                },
                "n1": {
                    "ids": ["CHEBI:45783"],
                    "categories": ["biolink:ChemicalSubstance"]
                },
                "n2": {
                    "ids": ["MONDO:0005301"],
                    "categories": ["biolink:Disease"]
                },
                "n3": {
                    "categories": ["biolink:ChemicalSubstance"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:related_to"]
                },
                "e02": {
                    "subject": "n0",
                    "object": "n2",
                    "predicates": ["biolink:related_to"]
                },
                "e03": {
                    "subject": "n0",
                    "object": "n3",
                    "predicates": ["biolink:related_to"]
                }
            }
        }
    }
}

```
with the message ` 2021-06-10T16:10:20.144391 ERROR: [NoResults]    No paths were found in {'RTX-KG2'} satisfying qedge e02`
Pining @edeutsch and @amykglen since I don't know if this is a query graph interpreter issue, or an `expand` issue.

**Comment by amykglen** [comment]
might this be the same problem as [this](https://github.com/RTXteam/RTX/issues/1429#issuecomment-849236857)? (not sure whether the QGI was ever tweaked for that one?)

**Comment by dkoslicki** [comment]
Ah yup, same issue. For some reason I thought @edeutsch tweaked the query graph interpreter...

**Comment by dkoslicki** [comment]
@edeutsch the issue is that the Query graph is saying "no paths found" yet the same DSL does indeed find paths. So I didn't know if the QGI was modifying the query in such a way that caused it to not find results

**Comment by amykglen** [comment]
I think the problem is that qnodes with a single curie specified are being forced to `is_set=true`. see this message in the log for the query - you can see `n2` has `is_set=true`:

![Screen Shot 2021-06-10 at 10 54 26 AM](https://user-images.githubusercontent.com/49423686/121573614-4f92b400-c9da-11eb-96f0-e2d9d95f4cc5.png)

**Comment by dkoslicki** [comment]
Yeah, looks like [this block](https://github.com/RTXteam/RTX/blob/88e4adce4d57fca70db5d0323bf5d216eb0f048b/code/ARAX/ARAXQuery/query_graph_info.py#L344-L353) should only set `is_set=True` if the node is unspecified (i.e. no CURIE specified).

**Comment by edeutsch** [comment]
okay, I believe I have pushed and deployed a fix for this. Test and close?

**Comment by dkoslicki** [comment]
Confirmed working, thanks @edeutsch !
