### ISSUE TITLE
Add node properties in O/W

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1512]
Request from Chris Bizon: create an operation to add node properties. We can initiate this by making an operation for [add_node_pmids](https://github.com/RTXteam/RTX/blob/master/code/ARAX/Documentation/DSL_Documentation.md#overlayactionadd_node_pmids).

**Comment by dkoslicki** [comment]
Update: break out annotate into `annotate_nodes` and `annotate_edges`, add PMID as one of the parameters for node annotation

**Comment by finnagin** [comment]
Closing since this was already done
