### ISSUE TITLE
Remove category/predicate ancestors from meta_knowledge_graph

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1514]
need to stop including expanded categories/predicates in our meta KG... (should just be a matter of removing some code from the KG2c build script that creates the meta KG)

@edeutsch - did you ever hear whether or not we should still include conflations (like 'gene' and 'protein') in our meta KG?

**Comment by edeutsch** [comment]
yes, this would be great! Technically this is due today, but not a big deal.

> @edeutsch - did you ever hear whether or not we should still include conflations (like 'gene' and 'protein') in our meta KG?

hmm, I can't recall now. I think this might have been dropped. I will ask.
For now, I would suggest yes, do include them. Because this is not an obvious inheritance issue.

thanks!

**Comment by amykglen** [comment]
ok, I regenerated the meta KG without ancestors (but still with conflations) and updated the master config file to point to the new version (`meta_kg_v1.1_KG2.5.2c.json`), so if we just delete the KG2 endpoint's `configv2.json` (to force it to download the new copy), I think all should be set...

**Comment by amykglen** [comment]
verified it's working! (I refreshed the kg2 endpoint's `configv2.json` and made sure that the new, smaller meta KG is returned when hitting up `/meta_knowledge_graph`)

**Comment by edeutsch** [comment]
@amykglen this is terrific, thank you very much! I have deployed this functionality to all active deployments and it seems to work very well.
