### ISSUE TITLE
Another query graph interpreter issue

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1515]
I thought this issue had been addressed in #1429, and this time is returning a different error `ERROR: QueryGraphInterpreter finds more nodes than supported in this QueryGraph`:
```
{
  "edges": {
    "e0": {
      "object": "n1",
      "predicates": [
        "biolink:correlated_with"
      ],
      "subject": "n0"
    },
    "e1": {
      "object": "n2",
      "predicates": [
        "biolink:condition_associated_with_gene"
      ],
      "subject": "n1"
    },
    "e2": {
      "object": "n3",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n2"
    }
  },
  "nodes": {
    "n0": {
      "ids": [
        "MONDO:0005359"
      ],
      "name": "drug-induced liver injury"
    },
    "n1": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ],
      "name": "Disease Or Phenotypic Feature"
    },
    "n2": {
      "categories": [
        "biolink:Gene"
      ],
      "name": "Gene"
    },
    "n3": {
      "categories": [
        "biolink:ChemicalSubstance"
      ],
      "name": "Chemical Substance"
    }
  }
}
```
Was the plan to run a query as is if it doesn't match a template, or am I misremembering?

**Comment by edeutsch** [comment]
I think you're remembering right, although I am still quite concerned about many hop queries completely bogging down the system.

However, I think this issue is not an absolute limit, but rather some weird bad interaction with query_graph_info.py.
I will investigate.

**Comment by dkoslicki** [comment]
Just an FYI: this corresponds to December demo workflow B (Kara was asking for a progress update).

**Comment by edeutsch** [comment]
I have added a crude additional query graph template here:
https://github.com/RTXteam/RTX/blob/380508325d5e0ccb1fee4612b9a36dfca4e7dabc/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter_templates.yaml#L214

The idea is that the query graph templates can be augmented with DSL programs that are suitable for answering various kinds of questions.

If you encounter queries that are not supported, it is just a matter of adding a template for what you'd like to support.
