### ISSUE TITLE
Uncaught expand error

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1516]
For this DSL:
```
add_qnode(key=n0,ids=MONDO:0005359) 
add_qnode(key=n1, categories=biolink:DiseaseOrPhenotypicFeature)
add_qnode(key=n2,categories=biolink:Gene)
add_qnode(key=n3,categories=biolink:ChemicalSubstance)
add_qedge(key=e01,subject=n0,object=n1,predicates=biolink:correlated_with)
add_qedge(key=e02,subject=n1,object=n2)
add_qedge(key=e03,subject=n2,object=n3,predicates=biolink:related_to)
expand()
resultify()
filter_results(action=limit_number_of_results,max_results=50,prune_kg=true)
```
The following error is thrown:
![image](https://user-images.githubusercontent.com/6362936/122252924-b6601380-ce99-11eb-98ce-e1683272e1a0.png)
(screenshot since it also crashed my browser)

**Comment by amykglen** [comment]
ok, this is fixed in `master` - the problem was that some node IDs (e.g., `ttd.target:2'3'-Dideoxyinosine`) apparently include single quotes, which needed to be escaped in the decorator's SQL query.

**Comment by amykglen** [comment]
verified the error is resolved on production: https://arax.ncats.io/?r=12973 (or a perhaps more useful version of the query with `is_set=true` for intermediate nodes: https://arax.ncats.io/?r=12974)

good to close, @dkoslicki?

**Comment by dkoslicki** [comment]
Yes indeed!
