### ISSUE TITLE
Handle knowledge_source constraint in expand

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1518]
this is a good first constraint to start with

effectively lets someone specify the KP(s) to use for a particular edge through a JSON QG

a single constraint with an array of values (e.g., `[RTX-KG2, BTE]`] means OR/union, separate constraints means AND/intersection - the OR/union is probably most relevant for our expected use case, but can begin to work out how the AND/intersection would work

**Comment by amykglen** [comment]
from today's AHM - how to encode allowlists and denylists in constraints:

https://github.com/NCATSTranslator/ReasonerAPI/blob/1.3/ImplementationRules.md#specifying-permitted-and-excluded-kps-to-an-ara

making this work for KPs is pretty easy; making it work for non-KP knowledge sources is a bit more involved (probably have to query KPs and then filter down their results based on what the 'allowed' knowledge sources are)

**Comment by amykglen** [comment]
examples of KP allowlist/denylists: https://github.com/NCATSTranslator/ReasonerAPI/commit/82218fc86be74755ec1ffa9b8679eac0075df364

**Comment by amykglen** [comment]
attribute constraint documentation: https://github.com/NCATSTranslator/ReasonerAPI/blob/1.3/docs/reference.md#attributeconstraint-

**Comment by amykglen** [comment]
we're going to tackle this issue in two parts:
1. handle KP allowlists/denylists
2. handle knowledge source (non-Translator KP) allowlists/denylists

**Comment by rcpeene** [comment]
Item 1 of the above comment has been completed and tested and pushed to branch `NewFmt`. Working on implementing Item 2 right now.

**Comment by amykglen** [comment]
this is awesome, @rcpeene! for anyone who wants to try it out, running this query on https://arax.ncats.io/NewFmt makes it use only KG2 and BTE:
```
{
   "nodes":{
      "n00":{
         "ids":[
            "CHEMBL.COMPOUND:CHEMBL945"
         ]
      },
      "n01":{
         "categories":[
            "biolink:ChemicalEntity"
         ]
      }
   },
   "edges":{
      "e00":{
         "object":"n00",
         "subject":"n01",
         "attribute_constraints":[
            {
               "id":"biolink:knowledge_source",
               "name":"knowledge source",
               "value":[
                  "infores:rtx-kg2",
                  "infores:biothings-explorer"
               ],
               "operator":"==",
               "not":false
            }
         ]
      }
   }
}
```

one thing we should probably do is update the 'query plan' with an indication of why the KPs that were skipped were skipped - right now they just say 'Waiting', even after the query has completed:

![Screen Shot 2022-07-27 at 7 08 27 PM](https://user-images.githubusercontent.com/49423686/181404843-75d05ff6-ca71-46ff-8037-0365e4fed536.png)

this is an example of updating the 'query plan' (when KPs were skipped for another reason):
https://github.com/RTXteam/RTX/blob/3f4899048e9c617836425b300a427e496cf1feff/code/ARAX/ARAXQuery/ARAX_expander.py#L328-L330

(changes for that can go in the `issue1518` branch)

**Comment by edeutsch** [comment]
Agreed, would be nice to have a nice message explaining why it was skipped.

While we're at it, can we change "Waiting for previous expansion step" to something like "Preparing query" or something? In some cases it is truly waiting for the previous expansion step, but very frequently that is not the reason (for example in this query, there is only one expansion step)

**Comment by rcpeene** [comment]
If there is a value in the attribute constraint that wasn't already selected to expand an edge, it will be ignored. I could change the implementation to cause an error if that is preferred. Additionally, I can also add a debug message and update the query plan. Will update here when that's done.

**Comment by rcpeene** [comment]
Updating to confirm that the aforementioned changes were made. And pushed to branch `Issue1518`. We can pull it into NewFmt when it is deemed ready.

**Comment by edeutsch** [comment]
great, thanks! Shall we go ahead and do the merge? Or should something happen first?

**Comment by rcpeene** [comment]
I think it is good to merge if it hasn't been already, but best to get @amykglen's perspective first.

**Comment by amykglen** [comment]
if you've fully tested it that's fine with me. you should merge `NewFmt` into your branch (since your branch was created off of `NewFmt`), then make sure `pytest -v` is passing in your branch (as well as any 'slow' pytests that involve constraints). if it is, then we should be good to merge it to `NewFmt` at that point.

**Comment by amykglen** [comment]
if you run into conflicts when merging `NewFmt` into your branch, feel free to run them by me

**Comment by amykglen** [comment]
are we good to close this issue, @rcpeene?

**Comment by rcpeene** [comment]
I was planning on waiting for https://arax.ncats.io/ to be updated to TRAPI 1.3 to fully verify our functionality. If you think it's sufficient to test in staging, then we can close it.

**Comment by amykglen** [comment]
yep, I think as long as it's verified working on either arax.ci.transltr.io, arax.ncats.io/beta, or arax.ncats.io/test, we can close.

thanks so much for implementing this!
