### ISSUE TITLE
Use new official 'infores' curies in expand (due July 1)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1519]
this is for the [Source provenance standards](https://togithub.com/NCATSTranslator/TranslatorArchitecture/issues/48) Architecture requirement (implementation deadline is **July 1** for KPs, July 7 for ARAs)

need to update the infores curies that `expand` adds to edges (both for knowledge_provider_source and original_source/aggregator_source kinds of things) now that official versions of them have been put out 

eventually KG2 itself should use these infores curies as `provided_by`s, but other KG2 dev work is more pressing, so we'll just have a patch in `expand` for this for now

- - - 

official infores curies (on 'InfoResourcesv3' tab - column F):
https://docs.google.com/spreadsheets/d/1Ma4U3aY16mJushsW74vf9mWVacFvf7FiTEdlVqaUi5g
our provided by to infores spreadsheet:
https://docs.google.com/spreadsheets/d/1h4MNiGCkiEfc8iFn3cN0mI0cY85KjjjBRT2D1ni0jJE/edit#gid=0
types of knowledge sources (aggregator, original, etc.):
https://togithub.com/biolink/biolink-model/issues/716#issuecomment-825827588
Clear definitions of primary, original, and aggregator knowledge sources are provided here (latest):
https://togithub.com/NCATSTranslator/TranslatorArchitecture/issues/48#issuecomment-866045076
 - - - - 
FINAL ruling: https://docs.google.com/document/d/177sOmjTueIK4XKJ0GjxsARg909CaU71tReIehAp5DDo/edit#

**Comment by amykglen** [comment]
alright, infrastructure is fully in place for this (expand uses the KG2 repo's `provided_by_curie_to_infores_curie.tsv` for KG2 knowledge sources) and we're using the latest KP infores curies - suppose I'll leave this issue open for a few more days to see if they tweak any of the KP infores curies in their final revisions.

**Comment by edeutsch** [comment]
Terrific!
I think I successfully lobbied to skip the version numbers on the resources.
It's still up in the air, unfortunately.

I still have questions on exactly this is to be done. I need to get some of Matt's time to really understand this better.
One thing that came out of Thursday's call is that RTX-KG2 should be entirely responsible for declaring itself the knowledge_provider. ARAX shouldn't have to say anything about RTX-KG2. Rather, it declares itself a ??? called ARAX. I don't even know.

**Comment by amykglen** [comment]
yeah, I lurked on Thursday's DM call and was also a bit confused about who should create which attributes...

in my mind there are two kinds of relevant attributes here (from ARAX's perspective)...

those passed on from KPs, like this one from MolePro:
```
            {
              "attribute_type_id": "biolink:Publication",
              "original_attribute_name": "link",
              "value": "https://drug-interactions.medicine.iu.edu/Main-Table.aspx",
              "value_type_id": null,
              "attribute_source": "DrugBank",
              "value_url": "https://drug-interactions.medicine.iu.edu/Main-Table.aspx",
              "description": null
            },
```
and `biolink:knowledge_provider_source` attributes, which we currently create and tack onto each edge to indicate which KP we got that edge from:
```
            {
              "attribute_type_id": "biolink:knowledge_provider_source",
              "original_attribute_name": null,
              "value": "infores:molecular-data-provider",
              "value_type_id": "biolink:InformationResource",
              "attribute_source": "infores:arax-reasoner-ara",
              "value_url": null,
              "description": null
            }
```
which are needed for #1518.

I'm not sure where people were thinking KPs should 'label' answers as coming from them. are KPs going to create their own `biolink:knowledge_provider_source` attributes? or something else?

**Comment by amykglen** [comment]
alright, the plan formulated at today's minihackathon has been implemented, changes are in `master`. I also checked in an updated copy of the infores spreadsheet to the KG2 repo (thanks @ericawood for all your help on that). 

one relatively minor thing I'm not totally sure about is what the "I'm KP ___" kind of attributes should look like for our in-house KPs (i.e., DTD and NGD). this is what I went with:
 
          {'attribute_source': 'infores:arax-reasoner-ara',
                 'attribute_type_id': 'biolink:knowledge_source',
                 'description': "ARAX's in-house drug-treats-disease (DTD) "
                                'database (built from GraphSage model).',
                 'original_attribute_name': None,
                 'value': 'infores:arax-drug-treats-disease',
                 'value_type_id': 'biolink:InformationResource',
                 'value_url': None},

not sure if we should request infores curies for these? currently using:
```
"DTD": "infores:arax-drug-treats-disease"
"NGD": "infores:arax-normalized-google-distance"
```

also, it appears all these changes broke the pytest `test_ARAX_filter_kg.py::test_provided_by_filter` (sorry about that @finnagin). I thought updating the test case so that the filter command looks for `biolink:aggregator_knowledge_source` instead of `biolink:knowledge_source` should fix it, but it doesn't, for some reason..

**Comment by amykglen** [comment]
as an fyi - here's an example edge from KG2 using the new attribute paradigm:
```
'RTX-KG2:CHEMBL.COMPOUND:CHEMBL112-biolink:entity_positively_regulates_entity-UniProtKB:A8MT33': {'attributes': [
                {'attribute_source': 'infores:rtx-kg2',
                 'attribute_type_id': 'biolink:aggregator_knowledge_source',
                 'description': None,
                 'original_attribute_name': None,
                 'value': 'infores:rtx-kg2',
                 'value_type_id': 'biolink:InformationResource',
                 'value_url': None},
                {'attribute_source': 'infores:rtx-kg2',
                 'attribute_type_id': 'biolink:aggregator_knowledge_source',
                 'description': None,
                 'original_attribute_name': None,
                 'value': 'infores:semmeddb',
                 'value_type_id': 'biolink:InformationResource',
                 'value_url': None},
                {'attribute_source': 'infores:semmeddb',
                 'attribute_type_id': 'biolink:has_supporting_publications',
                 'description': None,
                 'original_attribute_name': None,
                 'value': ['PMID:16177239'],
                 'value_type_id': 'biolink:Publication',
                 'value_url': None},
                {'attribute_source': 'infores:arax-reasoner-ara',
                 'attribute_type_id': 'biolink:aggregator_knowledge_source',
                 'description': None,
                 'original_attribute_name': None,
                 'value': 'infores:arax-reasoner-ara',
                 'value_type_id': 'biolink:InformationResource',
                 'value_url': None}],
 'object': 'UniProtKB:A8MT33',
 'predicate': 'biolink:entity_positively_regulates_entity',
 'relation': None,
 'subject': 'CHEMBL.COMPOUND:CHEMBL112'}}
```
and one from MolePro:
```
'MolePro:HGNC:9379-biolink:correlated_with-CHEBI:93885': {'attributes': [
               {'attribute_source': 'CMAP',
                 'attribute_type_id': 'CMAP:similarity score',
                 'description': None,
                 'original_attribute_name': 'CMAP similarity score',
                 'value': '96.93',
                 'value_type_id': 'number',
                 'value_url': None},
                {'attribute_source': 'CMAP',
                 'attribute_type_id': 'biolink:Publication',
                 'description': None,
                 'original_attribute_name': 'reference',
                 'value': 'PMID:29195078',
                 'value_type_id': 'string',
                 'value_url': None},
                {'attribute_source': 'CMAP',
                 'attribute_type_id': 'SIO:000811',
                 'description': None,
                 'original_attribute_name': 'about CMAP',
                 'value': 'https://clue.io/cmap',
                 'value_type_id': 'string',
                 'value_url': 'https://clue.io/cmap'},
                {'attribute_source': 'CMAP',
                 'attribute_type_id': 'SIO:000653',
                 'description': None,
                 'original_attribute_name': 'CMAP touchstone data version',
                 'value': '1.1.1.2',
                 'value_type_id': 'string',
                 'value_url': 'https://api.clue.io/api/touchstone-version'},
                {'attribute_source': 'infores:arax-reasoner-ara',
                 'attribute_type_id': 'biolink:knowledge_source',
                 'description': 'ARAX inserted this attribute because the KP '
                                '(MolePro) did not seem to provide such an '
                                'attribute (indicating that this edge came '
                                'from them).',
                 'original_attribute_name': None,
                 'value': 'infores:molecular-data-provider',
                 'value_type_id': 'biolink:InformationResource',
                 'value_url': None},
                {'attribute_source': 'infores:arax-reasoner-ara',
                 'attribute_type_id': 'biolink:aggregator_knowledge_source',
                 'description': None,
                 'original_attribute_name': None,
                 'value': 'infores:arax-reasoner-ara',
                 'value_type_id': 'biolink:InformationResource',
                 'value_url': None}],
 'object': 'CHEBI:93885',
 'predicate': 'biolink:correlated_with',
 'relation': None,
 'subject': 'UniProtKB:O43741'}}
```

**Comment by edeutsch** [comment]
I have rolled out the latest `master` to all deployments and it is looking very good in simple queries.
Including the insertion of appropriate attributes when the remote KP does not provide the correct attribute. Very nice!
I will mark this as complete in the tally sheet in case anyone is checking.

I'm fine with just blithely using these without a request:
```
"DTD": "infores:arax-drug-treats-disease"
"NGD": "infores:arax-normalized-google-distance"
```
If we request official curies for these, there may be pressure to make them public TRAPI endpoints, which we may like to avoid for now.

**Comment by amykglen** [comment]
awesome! closing since this looks good on production
