### ISSUE TITLE
Edges found: but expand reports no edges found

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1520]
This DSL worked for me the other day (https://arax.ncats.io/beta/?r=12696), but is now erroring out:
```
add_qnode(key=n0,ids=MONDO:0005359) 
add_qnode(key=n1, categories=biolink:DiseaseOrPhenotypicFeature)
add_qnode(key=n2,categories=biolink:Gene)
add_qnode(key=n3,categories=biolink:ChemicalSubstance)
add_qedge(key=e01,subject=n0,object=n1,predicates=biolink:correlated_with)
add_qedge(key=e02,subject=n2,object=n1,predicates=biolink:gene_associated_with_condition)
add_qedge(key=e03,subject=n2,object=n3,predicates=biolink:related_to)
expand()
resultify()
filter_results(action=limit_number_of_results,max_results=50,prune_kg=true)
```
Relevant messages include:
`GeneticsKP: Query for edge e02 completed (e02: 2, n1: 2, n2: 2)`
` BTE: Query timed out (waited 15 seconds)
BTE: Query for edge e02 completed (no answers)`
`ERROR: [NoResults]    No paths were found in {'GeneticsKP', 'RTX-KG2', 'BTE'} satisfying qedge e02`
But GeneticsKP found 2 `e02` edges.

**Comment by amykglen** [comment]
hmm - so the two edges found by GeneticsKP are turned into self-edges after they're synonymized/deduplicated. i.e., these are the raw edges GeneticsKP returns for qedge e02:
```
NCBIGene:5130--biolink:gene_associated_with_condition->MONDO:0012160
NCBIGene:9131--biolink:gene_associated_with_condition->MONDO:0010378
```
but this is what they're converted to after they're run through the synonymizer:
```
MONDO:0012160--biolink:gene_associated_with_condition->MONDO:0012160
MONDO:0010378--biolink:gene_associated_with_condition->MONDO:0010378
```
and then those edges are removed during `expand`, because they're now self-edges. 

so basically it seems the root issue is that the two genes are conflated with their diseases:
https://arax.ncats.io/?term=NCBIGene:5130
https://arax.ncats.io/?term=NCBIGene:9131

and as for why you got answers the other day but not today - I think that's because BTE returned some results the other day but didn't today (seems to be having some issues). 

maybe these conflations will be fixed in KG2.6.5?

**Comment by edeutsch** [comment]
I agree, let's leave this open and check when the new KG2.6.5C is built.

**Comment by ericawood** [comment]
Based on Amy's notes in the spreadsheet, I ran a few cypher queries:

### **`NCBIGene:5130`**
KG2.6.7c:
```
match (n) where 'NCBIGene:5130' in n.equivalent_curies return n
```
```
{
  "iri": "http://purl.obolibrary.org/obo/MONDO_0012160",
  "expanded_categories": [
    "biolink:Disease",
    "biolink:PhenotypicFeature",
    "biolink:DiseaseOrPhenotypicFeature",
    "biolink:BiologicalEntity",
    "biolink:NamedThing"
  ],
  "name": "spondylometaphyseal dysplasia-cone-rod dystrophy syndrome",
  "description": "Choline-phosphate cytidylyltransferase A (367 aa, ~42 kDa) is encoded by the human PCYT1A gene. This protein is involved in the biosynthesis of phosphatidylcholine.; UMLS Semantic Type: UMLS_STY:T126; UMLS Semantic Type: UMLS_STY:T116",
  "equivalent_curies": [
    "ENSEMBL:ENSG00000161217",
    "OMIM:123695",
    "PathWhiz.ProteinComplex:414",
    "NCBIGene:5130",
    "HGNC:8754",
    "REACT:R-HSA-1498771",
    "PathWhiz.ProteinComplex:10081",
    "MESH:C563825",
    "UMLS:C3538970",
    "OMIM:608940",
    "ORPHANET:85167",
    "PR:P49585",
    "UMLS:C1837073",
    "UniProtKB:P49585",
    "CHEMBL.TARGET:CHEMBL4105855",
    "PathWhiz.ProteinComplex:9673",
    "MONDO:0012160",
    "UMLS:C1418396",
    "PathWhiz.ProteinComplex:8469",
    "NCIT:C104957",
    "PR:000012446",
    "PathWhiz.ProteinComplex:7116",
    "PathWhiz.ProteinComplex:9123",
    "NCIT:C104953"
  ],
  "id": "MONDO:0012160",
  "category": "biolink:Disease",
  "all_names": [
    "choline-phosphate cytidylyltransferase A",
    "Choline-phosphate cytidylyltransferase A",
    "PCYT1A (human)",
    "spondylometaphyseal dysplasia-cone-rod dystrophy syndrome",
    "PCYT1A Gene",
    "PCYT1A",
    "Genetic locus associated with PCYT1A",
    "PCYT1A [endoplasmic reticulum membrane]",
    "Spondylometaphyseal dysplasia - cone-rod dystrophy",
    "Choline-Phosphate Cytidylyltransferase A",
    "choline-phosphate cytidylyltransferase A (human)",
    "Spondylometaphyseal Dysplasia with Cone-Rod Dystrophy",
    "PCYT1A gene",
    "Spondylometaphyseal dysplasia with cone-rod dystrophy related phenotypic feature"
  ],
  "all_categories": [
    "biolink:GenomicEntity",
    "biolink:Disease",
    "biolink:Gene",
    "biolink:PhenotypicFeature",
    "biolink:Protein",
    "biolink:MolecularEntity"
  ],
  "publications": [
    "DOI:10.1016/j.ajhg.2013.11.022",
    "DOI:10.1021/ac9004309",
    "PMID:24387990",
    "PMID:8155650",
    "PMID:19690332",
    "PMID:19413330",
    "DOI:10.1074/jbc.m403311200",
    "PMID:7918629",
    "DOI:10.1016/j.jprot.2013.11.014",
    "DOI:10.1021/pr300630k"
  ]
}
```

KG2.6.7:
```
match (n) where n.id in ["ENSEMBL:ENSG00000161217","OMIM:123695","PathWhiz.ProteinComplex:414","NCBIGene:5130","HGNC:8754","REACT:R-HSA-1498771","PathWhiz.ProteinComplex:10081","MESH:C563825","UMLS:C3538970","OMIM:608940","ORPHANET:85167","PR:P49585","UMLS:C1837073","UniProtKB:P49585","CHEMBL.TARGET:CHEMBL4105855","PathWhiz.ProteinComplex:9673","MONDO:0012160","UMLS:C1418396","PathWhiz.ProteinComplex:8469","NCIT:C104957","PR:000012446","PathWhiz.ProteinComplex:7116","PathWhiz.ProteinComplex:9123","NCIT:C104953"] return n.id, n.name, n.full_name
```

n.id | n.name | n.full_name
-- | -- | --
"UMLS:C1418396" | "PCYT1A gene" | "phosphate cytidylyltransferase 1, choline, alpha"
"HGNC:8754" | "PCYT1A (human)" | "phosphate cytidylyltransferase 1, choline, alpha"
"UMLS:C1837073" | "Spondylometaphyseal Dysplasia with Cone-Rod Dystrophy" | null
"MESH:C563825" | "Spondylometaphyseal Dysplasia with Cone-Rod Dystrophy" | null
"UMLS:C3538970" | "Choline-Phosphate Cytidylyltransferase A" | null
"NCIT:C104957" | "Choline-Phosphate Cytidylyltransferase A" | null
"NCIT:C104953" | "PCYT1A Gene" | null
"OMIM:608940" | "Spondylometaphyseal dysplasia with cone-rod dystrophy related phenotypic feature" | null
"OMIM:123695" | "PCYT1A" | null
"ORPHANET:85167" | "Spondylometaphyseal dysplasia - cone-rod dystrophy" | null
"MONDO:0012160" | "spondylometaphyseal dysplasia-cone-rod dystrophy syndrome" | null
"PR:P49585" | "choline-phosphate cytidylyltransferase A (human)" | null
"PR:000012446" | "choline-phosphate cytidylyltransferase A" | null
"UniProtKB:P49585" | "PCYT1A" | "Choline-phosphate cytidylyltransferase A"
"ENSEMBL:ENSG00000161217" | "PCYT1A" | "phosphate cytidylyltransferase 1, choline, alpha [Source:HGNC Symbol;Acc:HGNC:8754]"
"CHEMBL.TARGET:CHEMBL4105855" | "Choline-phosphate cytidylyltransferase A" | "Choline-phosphate cytidylyltransferase A"
"NCBIGene:5130" | "Genetic locus associated with PCYT1A" | "phosphate cytidylyltransferase 1A, choline"
"PathWhiz.ProteinComplex:10081" | "Choline-phosphate cytidylyltransferase A" | "Choline-phosphate cytidylyltransferase A"
"PathWhiz.ProteinComplex:7116" | "Choline-phosphate cytidylyltransferase A" | "Choline-phosphate cytidylyltransferase A"
"PathWhiz.ProteinComplex:9673" | "Choline-phosphate cytidylyltransferase A" | "Choline-phosphate cytidylyltransferase A"
"PathWhiz.ProteinComplex:9123" | "Choline-phosphate cytidylyltransferase A" | "Choline-phosphate cytidylyltransferase A"
"PathWhiz.ProteinComplex:414" | "Choline-phosphate cytidylyltransferase A" | "Choline-phosphate cytidylyltransferase A"
"PathWhiz.ProteinComplex:8469" | "Choline-phosphate cytidylyltransferase A" | "Choline-phosphate cytidylyltransferase A"
"REACT:R-HSA-1498771" | "PCYT1A [endoplasmic reticulum membrane]" | "PCYT1A [endoplasmic reticulum membrane]"

### **`NCBIGene:9131`**

KG2.6.7c:
```
match (n) where 'NCBIGene:9131' in n.equivalent_curies return n
```

```
{
  "iri": "http://purl.obolibrary.org/obo/MONDO_0010437",
  "expanded_categories": [
    "biolink:Disease",
    "biolink:PhenotypicFeature",
    "biolink:DiseaseOrPhenotypicFeature",
    "biolink:BiologicalEntity",
    "biolink:NamedThing"
  ],
  "name": "severe X-linked mitochondrial encephalomyopathy",
  "description": "Severe X-linked mitochondrial encephalomyopathy is an extremely rare mitochondrial respiratory chain disease resulting in a neurodegenerative disorder characterized by psychomotor delay, hypotonia, areflexia, muscle weakness and wasting in the two patients reported to date.",
  "equivalent_curies": [
    "OMIM:300169",
    "HGNC:8768",
    "DOID:0111502",
    "UMLS:C0795910",
    "UMLS:C3151753",
    "OMIM:300816",
    "OMIM:310490",
    "MESH:C536450",
    "ENSEMBL:ENSG00000156709",
    "UniProtKB:O95831",
    "MONDO:0010437",
    "NCBIGene:9131",
    "ORPHANET:238329"
  ],
  "id": "MONDO:0010437",
  "category": "biolink:Disease",
  "all_names": [
    "AIFM1 (human)",
    "Combined oxidative phosphorylation deficiency 6",
    "Combined oxidative phosphorylation deficiency 6 related phenotypic feature",
    "Charcot-marie-tooth disease, x-linked recessive, 4, with or without cerebellar ataxia related phenotypic feature",
    "Cowchock syndrome",
    "Severe X-linked mitochondrial encephalomyopathy",
    "AIFM1",
    "combined oxidative phosphorylation deficiency 6",
    "severe X-linked mitochondrial encephalomyopathy",
    "Genetic locus associated with AIFM1"
  ],
  "all_categories": [
    "biolink:Gene",
    "biolink:Protein",
    "biolink:Disease",
    "biolink:PhenotypicFeature"
  ],
  "publications": [
    "PMID:16365034",
    "DOI:10.1074/jbc.m601751200",
    "PMID:10913597",
    "PMID:16644725",
    "PMID:27178839",
    "PMID:25583628",
    "DOI:10.1007/s10048-017-0520-x",
    "PMID:17094969",
    "DOI:10.1016/j.ymgme.2011.09.020",
    "PMID:15772651"
  ]
}
```

KG2.6.7:
```
match (n) where n.id in ["OMIM:300169","HGNC:8768","DOID:0111502","UMLS:C0795910","UMLS:C3151753","OMIM:300816","OMIM:310490","MESH:C536450","ENSEMBL:ENSG00000156709","UniProtKB:O95831","MONDO:0010437","NCBIGene:9131","ORPHANET:238329"] return n.id, n.name, n.full_name
```



n.id | n.name | n.full_name
-- | -- | --
"HGNC:8768" | "AIFM1 (human)" | "apoptosis inducing factor mitochondria associated 1"
"UMLS:C0795910" | "Cowchock syndrome" | null
"MESH:C536450" | "Cowchock syndrome" | null
"UMLS:C3151753" | "Combined oxidative phosphorylation deficiency 6" | null
"OMIM:300169" | "AIFM1" | null
"OMIM:300816" | "Combined oxidative phosphorylation deficiency 6 related phenotypic feature" | null
"OMIM:310490" | "Charcot-marie-tooth disease, x-linked recessive, 4, with or without cerebellar ataxia related phenotypic feature" | null
"ORPHANET:238329" | "Severe X-linked mitochondrial encephalomyopathy" | null
"MONDO:0010437" | "severe X-linked mitochondrial encephalomyopathy" | null
"DOID:0111502" | "combined oxidative phosphorylation deficiency 6" | null
"UniProtKB:O95831" | "AIFM1" | "Apoptosis-inducing factor 1, mitochondrial {ECO:0000305}"
"ENSEMBL:ENSG00000156709" | "AIFM1" | "apoptosis inducing factor mitochondria associated 1 [Source:HGNC Symbol;Acc:HGNC:8768]"
"NCBIGene:9131" | "Genetic locus associated with AIFM1" | "apoptosis inducing factor mitochondria associated 1"

**Comment by amykglen** [comment]
the two culprit clusters appear fixed in KG2.6.7.1c:

https://arax.ncats.io/?term=NCBIGene:5130
https://arax.ncats.io/?term=NCBIGene:9131

good to close, @dkoslicki?
