### ISSUE TITLE
KG2 API v1.1 Swagger \query example doesn't work

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1522]
looks like the 'Try it out' example query still uses TRAPI 1.0 format?

https://arax.ncats.io/kg2/api/rtxkg2/v1.1/ui/#/query/query

**Comment by edeutsch** [comment]
oops, thanks, will fix.

**Comment by amykglen** [comment]
looks like this is still an issue, fyi

**Comment by edeutsch** [comment]
closing in favor of newer issue #1852
