### ISSUE TITLE
Error building synonymizer from KG2.6.5

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1525]
not yet sure what's going on here... any insight @edeutsch?

```
2021-06-21 19:11:16,864 INFO: Building node synonymizer off of specified KG2..
+ set -e
+++ dirname /home/ubuntu/RTX/code/kg2c/build-synonymizer.sh
++ cd /home/ubuntu/RTX/code/kg2c
++ pwd
+ script_dir=/home/ubuntu/RTX/code/kg2c
+ arax_dir=/home/ubuntu/RTX/code/kg2c/../ARAX
+ cd /home/ubuntu/RTX/code/kg2c/../ARAX/NodeSynonymizer
+ rm -f sri_node_normalizer_requests_cache.sqlite
+ python3 -u dump_kg2_node_data.py
Sending cypher query to KG2 neo4j (bolt://kg2endpoint-kg2-6-5.rtx.ai:7687)
Got 9781698 results back from neo4j
Successfully created file 'kg2_node_info.tsv'.
Sending cypher query to KG2 neo4j (bolt://kg2endpoint-kg2-6-5.rtx.ai:7687)
Got 446493 results back from neo4j
Successfully created file 'kg2_equivalencies.tsv'.
Sending cypher query to KG2 neo4j (bolt://kg2endpoint-kg2-6-5.rtx.ai:7687)
Got 3331984 results back from neo4j
Successfully created file 'kg2_synonyms.json'.
Done dumping KG2 node data!
+ python3 -u sri_node_normalizer.py --build
INFO: Beginning SRI Node Normalizer cache building process for KG2. Make sure you have a good network connection as this will download ~2 GB of data.
INFO: Note that requests-cache is used, so the sri_node_normalizer_requests_cache.sqlite file should be deleted first if it might be stale.
ERROR returned with status 404 while retrieving supported types
<Response [404]>
INFO: Reading kg2_node_info.tsv to pre-fill the normalizer cache
Traceback (most recent call last):
  File "sri_node_normalizer.py", line 472, in <module>
    if __name__ == "__main__": main()
  File "sri_node_normalizer.py", line 447, in main
    normalizer.fill_cache()
  File "sri_node_normalizer.py", line 135, in fill_cache
    if normalizer_curie_prefix in self.supported_prefixes:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by amykglen** [comment]
I copied the `kg2_node_info.tsv` and other artifacts thus far to arax.ncats.io (in `/data/orangeboard/databases/KG2.6.5/synonymizer`), in case that's helpful.

**Comment by edeutsch** [comment]
The likely cause is the SRI Node Normalizer changed there API. I don't know anything about it, although I think there was some Slack traffic about this earlier today? from Michel?
I'm kinda slammed at the moment. If you want to try to figure out how they changed their API, that would be great, otherwise I can take a look in a day or two.

**Comment by amykglen** [comment]
ah, yep, I see. looks like they moved the service to `https://nodenormalization-sri.renci.org/1.1/` for TRAPI 1.1, so the base URL no longer works. (Michel suggested they redirect the base URL to the 1.1 service and it sounds like they plan to do that, though it hasn't happened yet.)

switched to the 1.1 URL in `master` and confirmed it's not throwing this error anymore. thanks! (not sure if there were changes to their response format with this TRAPI 1.1 version, but I guess we'll find out!)

**Comment by edeutsch** [comment]
This is a bit puzzling to me because the previous service that I was using was not speaking TRAPI at all.

**Comment by amykglen** [comment]
yeah, I'm not sure what part of the service needed to be updated for TRAPI 1.1. so far in what I've looked at things seem the same as they were...
