### ISSUE TITLE
knowing which Certificate Authorities to trust for fetchIbuprofenTargets.pl

### ISSUE THREAD

**Issue by jaredroach** [RTXteam/RTX#1526]
I get this error when I try to run  [fetchIbuprofenTargets.pl](https://github.com/RTXteam/RTX/blob/master/code/UI/ClientExamples/Perl/fetchIbuprofenTargets.pl):

`500 Can't verify SSL peers without knowing which Certificate Authorities to trust`

I gather the solution is indicated on StackOverflow here:

[how-to-accept-self-signed-certificates-with-lwpuseragent](https://stackoverflow.com/questions/47662461/how-to-accept-self-signed-certificates-with-lwpuseragent) 

but I can't quite understand the solution well enough to implement it myself. Is it obvious how to modify fetchIbuprofenTargets.pl to avoid this error?

**Comment by jaredroach** [comment]
I got it to run well by adding this code, but am not sure that is "safe" to do:
$lwp->ssl_opts(
    SSL_verify_mode => IO::Socket::SSL::SSL_VERIFY_NONE, 
    verify_hostname => 0
);

**Comment by edeutsch** [comment]
I did not have to do this on my test machine, but it seems like a reasonable fix. I think the likelihood of a security breach and invalid results due to not validating the SSL cert is extremely small.
