### ISSUE TITLE
How do we handle symmetric relationships?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1527]
There's a new PR over on Translator Architecture:
https://togithub.com/NCATSTranslator/TranslatorArchitecture/pull/43/files

I assume that we do this already mostly, but I have a few questions:
1) Are there any objections to this PR or can I approve?
2) How do we know which relationships are symmetric?
3) How do we handle symmetrics relationships, at the KG2 level or at the Expander code level?
4) Do we fall short anywhere on this topic that we want to address?

**Comment by amykglen** [comment]
1. no objections from me - makes sense
2. just realized that I think these are encoded in the Biolink model - predicates have a boolean property called `symmetric`
3. right now the system considers everything to be symmetric, but PloverDB does have an option to enforce edge direction (I dropped the ball on #1406 and haven't quite yet plugged everything in)
4. PloverDB currently expects a parameter in the QG indicating whether or not to enforce edge direction but I think it would make more sense to have it simply check whether each predicate is 'symmetric' in Biolink. if enforcing edge direction indeed always follows the Biolink model's `symmetric` ruling (i.e., we never want to enforce edge direction for predicates with `symmetric: true`), then this could even be encoded directly into Plover's main index.

**Comment by edeutsch** [comment]
Thanks, these seem like terrific answers. Unless there are objections by the end of the AHM tomorrow, I will approve the issue quoted above. 

Does anyone want this topic on the agenda to discuss? I'm fine to skip. but go ahead and put it on the agenda if you want to discuss.

**Comment by amykglen** [comment]
think it's safe to close this issue - #1611 tracks work for item 4) above
