### ISSUE TITLE
no dash in p-value?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1528]
As seen in this result:
https://arax.ncats.io/beta/?r=12700

having a dash in p-value is not compliant with the schema.
Should we:
1) See if there is an appropriate predicate that is already in BioLink (I'm assuming this one is made up and really in BioLink?)
2) Just keep using this one by replace - with _
3) Lobby to have - in the schema?

Are there other BioLink curies that have - in them?

**Comment by saramsey** [comment]
Does this mean it is failing TRAPI validation?

<img width="1184" alt="Screen Shot 2021-06-22 at 9 07 07 PM" src="https://user-images.githubusercontent.com/5562107/123034129-d44bdd80-d39d-11eb-91e5-068e5e7af275.png">

**Comment by saramsey** [comment]
I'm not seeing an association or attribute in Biolink called `biolink:has_fisher_exact_test_p-value`.

**Comment by saramsey** [comment]
But as far as W3C CURIE syntax is concerned, I believe a hyphen in the `reference` part of the CURIE is valid syntax, per the [CURIE Syntax 1.0 document](https://www.w3.org/TR/2010/NOTE-curie-20101216/).

**Comment by edeutsch** [comment]
> Does this mean it is failing TRAPI validation?

correct. And the reason is that our curie does match the pattern (shown in the error)

> I'm not seeing an association or attribute in Biolink called biolink:has_fisher_exact_test_p-value.

I think we probably made it up.

**Comment by saramsey** [comment]
Ah, OK. Should be straightforward to get `biolink:has_fisher_exact_test_p-value` added as an "association slot" to Biolink by submitting a GitHub issue to the [biolink-model issue page](https://github.com/biolink/biolink-model/issues). I don't know of other association slot names that have hyphens in them, however. Unclear whether having one with a hyphen would break some downstream processing of the Biolink YAML file into the zillion different serializations they offer. I note that the association slot `p value` is [unhyphenated in the Biolink model](https://github.com/biolink/biolink-model/blob/763c53f5e656bb5c47d99fe893a2bc60bae70b8c/biolink-model.yaml#L5914).

**Comment by edeutsch** [comment]
This has surfaced again, any TRAPI we produce with `biolink:has_fisher_exact_test_p-value` is called invalid by the TRAPI validator. What should the best solution be here? I don't know.
https://togithub.com/NCATSTranslator/minihackathons/issues/182

**Comment by amykglen** [comment]
can we just replace the hyphen with an underscore? so it's `biolink:has_fisher_exact_test_p_value`? @chunyuma @dkoslicki 

then the TRAPI validator would stop complaining, right?

**Comment by edeutsch** [comment]
> then the TRAPI validator would stop complaining, right?

correct.

Although that still doesn't make it a valid BioLink predicate. but maybe that is not high priority.

**Comment by amykglen** [comment]
yeah - I think all of our Overlay predicates (NGD, etc.) are still things we made up, and should technically be requested.. but agree it's not high priority.

**Comment by chunyuma** [comment]
I've replaced the hyphen with an underscore for `biolink:has_fisher_exact_test_p_value`.

**Comment by isbluis** [comment]
I am also seeing no provenance information for this predicate:

![image](https://user-images.githubusercontent.com/37852256/128096140-53e13fb7-340c-4b8f-98ad-9d38a4c4a796.png)

Is it worth adding now?  (or maybe already done but not released yet?)

**Comment by edeutsch** [comment]
yes, would be great to add provenance to this. Maybe been done but not released, I don't know. I'll deploy latest master in a few minutes..

**Comment by dkoslicki** [comment]
@finnagin Did you update FET provenance values when you were doing the other virtual edges?

**Comment by finnagin** [comment]
@dkoslicki I did. Should be there whenever we next deploy.

**Comment by edeutsch** [comment]
deployed and apparently working in production. closing. thanks!
