### ISSUE TITLE
Autocompletion Improvements 

### ISSUE THREAD

**Issue by arnabdotorg** [RTXteam/RTX#153]
- [x] switch bash script to python for speed and can call Question scripts if need be later.
- [ ] prefetch initial file for low latency
- [ ] Speed up FTS4 ranking to allow for large bigram support

**Comment by arnabdotorg** [comment]
Alternative option : tradeoff recall vs corpus size -- reduce the number of unigrams / bigrams

**Comment by Palzer** [comment]
Dropped pubmed data, no need for fst, no need for prefetch, caching can be turned on (currently off), but may make autocomplete out of date.
