### ISSUE TITLE
Synonymizer enhancements to help debugging/detecting conflations

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1531]
starting to collect a wish list for the synonymizer.. mostly about improved reporting of potential problems and some interface improvements that would be helpful for debugging.. (credit to @ericawood for these as well)

1. output warnings/a report (ideally saved to some kind of file) for any synonym groups with more than `n` equivalent curies (maybe n should be 50? higher? lower?) #1477 
    * would be nice if these could be ordered from highest to lowest, and showed the name/curie for the cluster
2. enhance `Problems.tsv` a bit to give counts of the number of category conflations by type (e.g., how many gene/disease conflations, how many gene/drug conflations, etc.)
3. add CLI options to build without SRI, name-based merging, or `same_as` edges (or a combination of those)
4. add a CLI method to easily get the list of equivalent curies for an input concept (so, like `--lookup`, but way less verbose - just output a list like ["CHEMBL.COMPOUND:CHEMBL112", "CHEBI:XXX", ...] which can easily be pasted into a cypher query
    * this would go a long way for debugging, and I think actually may remove the temptation to do a KG2c build for every synonymizer build...

**Comment by finnagin** [comment]
@amykglen @edeutsch is this still relevant?

**Comment by amykglen** [comment]
I'll try to work on this along with #2003

**Comment by amykglen** [comment]
these are pretty much all addressed with the new synonymizer

notably, you can easily get the list of equivalent curies for a concept by doing:
```
python node_synonymizer.py DOID:14330 -e
```
various reports - including about oversized clusters - are output by the synonymizer build and uploaded to arax-databases.rtx.ai (in the `extra_files` subdirectory within a given KG2 directory)

and the synonyms tab in the UI now/soon will contain more info helpful for debugging
