### ISSUE TITLE
"ERROR: 500 read timeout" on remote JSON queries involving highly connected nodes

### ISSUE THREAD

**Issue by jaredroach** [RTXteam/RTX#1533]
If I submit an exhaustive one-hop query on any of these highly connected nodes, I get a timeout error.
e.g., using a derivative script of fetchIbuprofenTargets.pl

Cytidine-5'-monophosphate 		CHEBI:17361
Dopamine		CHEBI:18243
Histamine 		CHEBI:18295
Phosphoric acid 		CHEBI:26078
S-Adenosyl-homocysteine 		CHEBI:16680
Tryptophan		CHEBI:27897
Serotonin		CHEBI:28790

e.g.,
```
{
   "edges": {
      "e00": {
         "subject":   "n00",
         "object":    "n01"
      }
   },
   "nodes": {
      "n00": {
         "ids":        ["CHEBI:28790"]
      },
      "n01": {
         "categories":  ["biolink:Pathway","biolink:BiologicalProcess","biolink:MolecularActivity", "biolink:CellularComponent", "biolink:InformationContentEntity", "biolink:NamedThing"]
      }
   }
}
```

**Comment by jaredroach** [comment]
The error message is coming from inside the "`$response variable`", so I don't think it is local to my computer.
`my $response = JSON::Parse::parse_json($lwp_response->content());`

**Comment by edeutsch** [comment]
stale, closing.
