### ISSUE TITLE
Add patch to Expand that makes KG edges use canonical predicates (due July 1)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1534]
this is for the [Canonical predicate direction](https://togithub.com/NCATSTranslator/TranslatorArchitecture/issues/49) Architecture requirement - due July 1 for KPs and ARAs

we'll achieve this with a patch until KG2 itself only uses canonical predicates (should be ready with the Biolink 2.0 changes)

**Comment by amykglen** [comment]
ok, code for this is in place in `master`. holding off committing a pytest for it until the code is rolled out to the KG2 endpoint (the test would just fail until then). 

and to clarify what's going on behind the scenes:
1. ARAX transforms any predicates in the QG into their canonical versions (just in case the ARS sent a non-canonical one)
2. the KG2 KP will accept either canonical or non-canonical predicates in the QG, but its answers only ever use canonical predicates

**Comment by amykglen** [comment]
verified this looks good on production - closing

**Comment by amykglen** [comment]
briefly reopening this - I realized we should probably check other KPs' answers and make sure they're only using canonical predicates as well (and correct them if not). so I just added some code to `master` that does that. will verify on next rollout.

a warning is logged if any non-canonical predicates are detected in a KP's response:
```
2021-07-01T10:35:43.459537 DEBUG: [] MolePro: Sending query to MolePro API
2021-07-01T10:35:49.154746 DEBUG: [] MolePro: Got results from MolePro.
2021-07-01T10:35:49.169185 WARNING: [] MolePro: Found edges in MolePro's answer that use non-canonical predicates: {'biolink:affected_by'}. I corrected these.
```

**Comment by edeutsch** [comment]
great idea!

**Comment by amykglen** [comment]
confirmed it looks good on production!
