### ISSUE TITLE
Should Expand do some auto-pruning to tame combinatorial explosion?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1535]
I planted a seed about this at the mini-hackathon last week, but thought I'd create an issue to document it...

right now when ARAX gets multihop JSON queries, it'll happily keep expanding qedges no matter how many answers each qedge expansion might produce, until it takes the whole system down.

with DSL you can add in some overlay/filter steps (like FET) to help tame this, but nothing like that is done for JSON queries. 

might it make sense for `expand` to automatically do some pruning? (using FET or NGD, or maybe by even just running the answers-thus-far through the ranker?) maybe it has a rule that if the previous qedge produced more than N answers, it will do this special pruning to bring things back into a reasonable range. (I think an N of something like 2000 would prevent system overload...)

we could make it so that this pruning can be turned off by DSL users.. i.e., maybe expand could have an `auto_prune` parameter that defaults to true.

will require some thought as to the best way to prune, but thought I'd get the idea out there..

**Comment by edeutsch** [comment]
I think this is a great idea and we should do it. `auto_prune` sounds good.

**Comment by amykglen** [comment]
ok, initial version of this is in `master`. in summary, before expanding each qedge, Expand checks to see if there are too many nodes fulfilling either of the two qnodes for that qedge, and if there are, it will prune them down and keep only the top N. it chooses the best answers using FET and the Ranker.

by default, N is determined somewhat intelligently depending on which qedge is about to be expanded: in general N=1000, but if the unpinned qnode for the qedge about to be expanded is a `biolink:NamedThing`, it is more strict and sets N=200 (NamedThing really blows up results). and if both qnodes for the qedge about to be expanded are pinned, it's more lenient and sets N=5000. these numbers may need to be tweaked but seemed reasonable based on fiddling I did.

N can optionally be controlled through DSL via the new `prune_threshold` parameter (e.g., `expand(prune_threshold=200)`. when you do this the `prune_threshold` you specify will be used for _every_ (intermediate) qnode.

right now the KG2 API doesn't do this pruning (only ARAX), but as an enhancement I was thinking of possibly calling it there as well... was toying with the idea of maybe making it look for a constraint on each qnode that specifies the 'prune threshold' (max number of nodes allowed) for that qnode? then when ARAX calls the KG2 API it can put whatever thresholds it wants in the QG.

**Comment by amykglen** [comment]
verified this is working on production, although realizing I probably should decrease the default prune threshold (still producing borderline too-large answers). but here's a two-hop example with prune_threshold set to 100: https://arax.ncats.io/?r=17132

and also thinking I will add the KG2 API pruning which obeys qnode constraints - then we can avoid having to return huge numbers of results from the KG2 API to ARAX, which will never be used anyway.

**Comment by dkoslicki** [comment]
I’m curious how the score is being calculated; I see the message `INFO:    Kept top 100 answers for n1. Best score was 0.91816, worst kept was 0.8793.` Is this from the ranker? If so, are there “data” edges (NGD, etc.)? If not, the best score will simply be those pairs of nodes connected with many edges, if I understand correctly how the Frobenius norm is being used.

**Comment by amykglen** [comment]
yeah, it uses FET - it overlays with FET, resultifies, and feeds the results into the Ranker, and that's where the score comes from. open to other suggestions there though!

currently the overlaid FET edges aren't retained (I was thinking they wouldn't really be wanted since the user didn't ask for them), although I suppose they could be.

**Comment by dkoslicki** [comment]
Ah, yes, I see now you mentioned that above (don’t know how I missed it). FET edges make sense to me! I don’t have strong feelings either way re: keeping/throwing away the FET edges. They would help in ranking (especially if no other data edges were asked for), but as you say, the user didn’t ask for them. Then again, we often decorate with NGD even though the user didn’t ask for those either.

**Comment by amykglen** [comment]
true! yeah, maybe it would make sense to keep them around. also a plus that it'd be a bit more transparent.

**Comment by amykglen** [comment]
ok, just merged changes to the KG2 API's pruning/self-preservation strategy as discussed at today's mini-hackathon into `master`.

upon some testing I went with an overall max edge limit of 1,000,000 and a per-input-curie edge limit of 1,000 (though the latter is only enforced when the overall 1,000,000 limit is exceeded). perhaps these will need tweaking, but a start!

**Comment by amykglen** [comment]
I'm going to consider this complete; any tweaks to prune thresholds or the like can be written up in new issues
