### ISSUE TITLE
Add subclass_of KP reasoning (due July 15)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1536]
this is for the [Entity subclass semantic operations](https://togithub.com/NCATSTranslator/TranslatorArchitecture/issues/51) Architecture requirement - due July 15th

we'll start by implementing some sort of code work around for #1367 (which we expect to take longer to fix), so we can at least have some level of subclass_of reasoning to start

**Comment by amykglen** [comment]
just posting an update on this for the record:

I tried out building an index for PloverDB that maps nodes to their descendants based on KG2.6.7 `subclass_of` edges from MONDO, PR (protein ontology), and DrugBank. (I chose these three sources because they seemed to be perhaps the most reliable while also giving the best coverage of diseases/proteins/drugs.)

I set a recursion depth limit of 20 and called anything that tried to recurse beyond that a 'problem' node (indicative of a cycle).

there appeared to be very few cycles, even though I think the depth limit of 20 may have been too strict... report was as follows:
```
{
  "total_edges_in_kg": 34754035,
  "num_subclass_of_edges_from_approved_sources": 483875,
  "num_problem_nodes": 34,
  "num_nodes_with_descendants": 67344,
  "average_num_descendants_per_node": 162,
  "num_nodes_with_descendants_by_prefix": {
    "PR": 36531,
    "UniProtKB": 12701,
    "MONDO": 7632,
    "UMLS": 3168,
    "MESH": 1783,
    "UBERON": 1712,
    "CHEBI": 1019,
    "CHEMBL.TARGET": 681,
    "NCIT": 264,
    "CHEMBL.COMPOUND": 248,
    "FMA": 223,
    "NCBITaxon": 172,
    "CL": 169,
    "ENVO": 154,
    "GO": 151,
    "RO": 105,
    "OMIM": 95,
    "FOODON": 81,
    "VANDF": 58,
    "ECTO": 56,
    "biolink": 49,
    "MOD": 42,
    "PATO": 41,
    "RXNORM": 39,
    "SO": 33,
    "ORPHANET": 26,
    "HP": 21,
    "UMLS_STY": 14,
    "BFO": 11,
    "PO": 10,
    "LOINC": 10,
    "BSPO": 10,
    "DRUGBANK": 9,
    "MF": 4,
    "NCBIGene": 3,
    "MGI": 3,
    "PCO": 3,
    "IAO": 3,
    "DOID": 2,
    "CARO": 2,
    "RGD": 1,
    "ZFIN": 1,
    "FBgn": 1,
    "EFO": 1,
    "OGMS": 1,
    "owl": 1
  },
  "problem_nodes": [
    "PR:P46002-1",
    "MONDO:0021047",
    "MONDO:0020702",
    "UMLS:C3935912",
    "MONDO:0037003",
    "MONDO:0005460",
    "PR:000001501",
    "MONDO:0002486",
    "MONDO:0024879",
    "MONDO:0044913",
    "MONDO:0002083",
    "PR:000039789",
    "MONDO:0006184",
    "MONDO:0041447",
    "MONDO:0004562",
    "MONDO:0005357",
    "MONDO:0001718",
    "MONDO:0041448",
    "UMLS:C1070909",
    "MONDO:0024674",
    "MONDO:0001914",
    "MONDO:0034976",
    "PR:Q62035-1",
    "PR:P55088-2",
    "MONDO:0021102",
    "MONDO:0037002",
    "MONDO:0024883",
    "MONDO:0018695",
    "MONDO:0001965",
    "MONDO:0044912",
    "OMIM:MTHU052756",
    "UMLS:C1070911",
    "MONDO:0007012",
    "MONDO:0044742"
  ]
}
```
the average number of descendants per node of 162 seems a little alarming to me (seems really large?), so planning to look into that a bit more. (will look at median/mode/max to see if the mean is being skewed or something..)

also planning to analyze how good of coverage this seems to provide and if there might be better/other KG2 sources to use. thinking the 80/20 rule may be at play here (i.e., relatively few sources could get us almost all of the mappings we need in practice..)

**Comment by amykglen** [comment]
just an update here: this is coming along well using MONDO and CHEBI - seeming like it provides good coverage for realistic use cases. basically all that remains is some fine-tuning/testing - expect to have it done by end of day July 15.

**Comment by amykglen** [comment]
ok, so changes for this have been merged into `master` - are @edeutsch or @finnagin available to roll `master` out at some point today? (will need to be rolled out to the KG2 endpoint as well as ARAX endpoints)

a few notes:
1. I marked three `overlay` tests (all involving `predict_drug_treats_disease`) as `slow` temporarily (they're each marked with a 'TODO' as well). because they use the node "cancer", KG2 now produces **a lot** more answers for them which means the overlaying takes a lot longer. I think a more specific disease should probably be used for these tests (@finnagin or @chunyuma)
2. as people have time, they may want to review all of their 'slow' pytests to see if they're now insanely slow due to KG2 producing more answers than before
3. while right now subclasses are automatically being used for pinned query nodes, Plover respects an `allow_subclasses` parameter on qnodes, so if we do introduce some sort of qnode property to control this, that should be easy to hook up 
3. note that using `is_set=true` on pinned query nodes might make for more intuitive results. if pinned query nodes instead have `is_set=false`, there can be sort of 'duplicate' results (i.e., for the query `(Adams-Oliver syndrome)--related_to--(biolink:Gene)`, there may be one result for `(Adams-Oliver syndrome 3)--related_to-->(NOTCH1)` and another for `(Adams-Oliver syndrome 2)--related_to-->(NOTCH1)`, etc.). if there were an `allow_subclasses` qnode property, perhaps we could consider forcing `is_set=true` in the QGI for `allow_subclasses=true` qnodes. but at the moment there is no such property.

**Comment by finnagin** [comment]
@amykglen I'm not sure how to roll out changes to the KG2 endpoint but I can roll out the current code to any of the ARAX endpoints. Do they need to be rolled out together?

**Comment by amykglen** [comment]
nice, thanks! yeah, they should be rolled out together, ideally. I think it's the same deal for rolling out to the KG2 endpoint, but instead of `test` or `beta` the directory is called `kg2`

**Comment by finnagin** [comment]
Ah I'll go try doing the same thing I do for the others then. Just going to check with everyone on slack since I assume updating the KG2 endpoint will disrupt all endpoints at once so we can't do something like deploy to `/beta` first then see how it is working.

**Comment by finnagin** [comment]
@amykglen There is a December demo meeting going on today so I'm going to wait until sometime this evening to update the endpoints. Does that work for you?

**Comment by amykglen** [comment]
sounds good to me, thanks!

**Comment by finnagin** [comment]
You're welcome!

**Comment by amykglen** [comment]
ok, this seems to be working as expected on production - an example with Adams-Oliver syndrome: https://arax.ncats.io/?r=16346 (I see the TRAPI validator is complaining about something, but that's unrelated to this issue..)

the first few results are weird because of disease/gene conflations (not the subclass_of stuff), but ignoring those, you can see many more proteins are now returned. (the same query prior to deployment of the subclass_of reasoning is here: https://arax.ncats.io/?r=16340)

**Comment by amykglen** [comment]
closing this issue since things seem to be ok on production

(also - I did update the Architecture tracking spreadsheet to indicate we've completed this)
