### ISSUE TITLE
Do CURIE prefix translation for KPs?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1537]
At today's Txl8r mini-hackathon, the following issue came up:

https://arax.ncats.io/?source=ARS&id=64f1182b-3463-4321-ac41-8715a14995e6

ARAX is returning two results (no one else returns anything) for this query:
```
{
  "edges": {
    "e2": {
      "object": "n3",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n2"
    }
  },
  "nodes": {
    "n2": {
      "categories": [
        "biolink:Gene"
      ],
      "ids": [
        "NCBIGene:60412"
      ],
      "is_set": false
    },
    "n3": {
      "categories": [
        "biolink:Drug"
      ],
      "is_set": false
    }
  }
}
```

In instead we use the Ensembl identifier:

```
{
  "edges": {
    "e2": {
      "object": "n3",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n2"
    }
  },
  "nodes": {
    "n2": {
      "categories": [
        "biolink:Gene"
      ],
      "ids": [
        "ENSEMBL:ENSG00000131558"
      ],
      "is_set": false
    },
    "n3": {
      "categories": [
        "biolink:Drug"
      ],
      "is_set": false
    }
  }
}
```

This returns 30: https://arax.ncats.io/?r=14673

So it seems that we could/should be doing is consulting CHPs /meta_knowledge_graph:
http://chp.thayer.dartmouth.edu/meta_knowledge_graph/

that for genes, they only support id_prefix of ENSEMBL, and so we should be transforming the NCBIGene: to ENSEMBL: and sending that to them. If we did that we would get more results from CHP. They don't do normalization/transformation I suppose so it's up to us to do it?

**Comment by amykglen** [comment]
thanks - yes, have this on the list now that `expand` uses KPs' /meta_knowledge_graph vs. /predicates. will do soon!

**Comment by amykglen** [comment]
done in `master` (the original QG indeed produces 30-something results now) - will verify it looks good on production after the next deployment.

**Comment by amykglen** [comment]
looks to be working as expected on production: https://arax.ncats.io/?r=15709

good to close, @edeutsch?

**Comment by edeutsch** [comment]
terrific, many thanks, closing.
