### ISSUE TITLE
probable name conflation issue showing up in an ARS query to ARAX

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1538]
in today's mini-hackathon session looking for diseases/phenotypes that are related to drug-induced liver injury (DILI), the following JSON query was sent to ARAX by the ARS:
```
{
  "edges": {
    "N1": {
      "object": "n1",
      "predicates": [
        "biolink:has_normalized_google_distance_with"
      ],
      "relation": "N1",
      "subject": "n0"
    },
    "e0": {
      "object": "n1",
      "predicates": [
        "biolink:correlated_with"
      ],
      "subject": "n0"
    }
  },
  "nodes": {
    "n0": {
      "ids": [
        "MONDO:0005359"
      ],
      "is_set": false
    },
    "n1": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ],
      "is_set": false
    }
  }
}
```
The [results](https://arax.ncats.io/?r=14662) include stuff like "Immunology", which was flagged as questionable.  This was brought to our attention through issue 65 in the NCATSTranslator/minihackathons repo.

**Comment by amykglen** [comment]
looks to me like the problem causing "Immunology" to be returned as a result is that this node has the category 'biolink:PhenotypicFeature' in KG2.5.2:
```
{
  "iri": "http://purl.obolibrary.org/obo/OMIM_MTHU000067",
  "category_label": "phenotypic_feature",
  "deprecated": "False",
  "name": "Immunology",
  "description": "UMLS Semantic Type: UMLS_STY:T091",
  "provided_by": "umls_source:OMIM",
  "id": "OMIM:MTHU000067",
  "category": "biolink:PhenotypicFeature",
  "update_date": "2020"
}
```
however, it looks like its category is now `biolink:NamedThing` in KG2.6.7, so I think that particular issue has already been addressed!
```
{
  "iri": "http://purl.obolibrary.org/obo/OMIM_MTHU000067",
  "category_label": "named_thing",
  "deprecated": "True",
  "name": "Immunology",
  "description": "UMLS Semantic Type: UMLS_STY:T091",
  "provided_by": "umls_source:OMIM",
  "id": "OMIM:MTHU000067",
  "category": "biolink:NamedThing",
  "update_date": "2020"
}
```

**Comment by saramsey** [comment]
Thank you @amykglen. I have reported this potential fix in the original issue in the `NCATSTranslator/minihackathons` GitHub project area.

**Comment by saramsey** [comment]
fixed

https://github.com/NCATSTranslator/minihackathons/issues/65
