### ISSUE TITLE
ICEES integration?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1539]
What is our status/plan on ICEES integration?

A new issue over on the minihackathons repo indicates that we are not drawing expected information from ICEES. I didn't know the status at the call.

https://github.com/NCATSTranslator/minihackathons/issues/67

**Comment by amykglen** [comment]
we currently use ICEES for overlaying, not expanding. but planning to do #1509 soon.

**Comment by saramsey** [comment]
If we need any help with the ICEES API, @meghasin can help

**Comment by edeutsch** [comment]
thanks, I posted an update on the upstream issue with this status.

**Comment by amykglen** [comment]
ICEES was plugged into Expand as a KP a while back in #1509 - closing
