### ISSUE TITLE
Add workflow to ARAXi translation

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1542]
In [this file](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/operation_to_ARAXi.py), add translations for filter kgraph operations (top n, percentile, std dev) and overlay Jaccard.

**Comment by finnagin** [comment]
SOP:

1. Manually update implemented operations in OA3 ARAX yaml
2. Run workflow2yaml.py and look at printed output
3. copy printed output to OA3 ARAX yaml
4. Do this in both the query section and response section
5. $defs -> components/schema
6. copy other workflow printed output: Everything after Components: schema: then paste at the bottom of the file replacing what is already there
7. Copy all the above changes into openapi/openapi.yaml

**Comment by finnagin** [comment]
Run the replaceall for each endpoint:

```
cd ../../UI/OpenAPI/python-flask-server
cd openapi_server/openapi
mv openapi.yaml openapi.yaml-prev1
git pull
replaceall.pl 'arax.ncats.io/' 'arax.ncats.io/devED/' openapi.yaml
```

**Comment by finnagin** [comment]
9. restart endpoint and check it is updated in swagger ui
