### ISSUE TITLE
Which are the exact CURIEs that yield the edges?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1544]
A question from today's standup:

In this result:
https://arax.ncats.io/?r=15218

We have for example a result:
CHEMBL.COMPOUND:CHEMBL577 biolink:causes MONDO:0006945
This comes from SEMMEDDB

The question is: exactly which CURIEs does SEMMEDDB have for this?
Since we do such heavy synonymization, the original CURIEs that SEMMEDDB uses are obscured (it is obviously one of the synonyms of A and one of the synonyms for B, but which?)

Other groups don't do such heavy synonymization and are not finding these edges and so they're wondering how they could have found them.

Can we manually figure this out in KG2?

It is possible/worth somehow encoding in the edges what (at least one of) the original CURIE pair is? to be able to easily answer such questions?

The latter seems like a useful question to be able to easily answer. It comes up frequently, especially when there is over-synonymization.

**Comment by amykglen** [comment]
starting with KG2.6.7c, edges have a property called `kg2_ids` which technically captures this info, I think:
```
{
  "predicate": "biolink:subclass_of",
  "kg2_ids": [
    "UMLS:C0014412---SEMMEDDB:isa---UMLS:C0010957---SEMMEDDB:"
  ],
  "subject": "MESH:D004781",
  "object": "UMLS:C0010957",
  "provided_by": [
    "SEMMEDDB:"
  ],
  "id": "24386157",
  "publications": [
    "PMID:24069824"
  ]
}
```
so you can see in this case the KG2c edge's subject is MESH:D004781, but the original KG2 edge's subject was UMLS:C0014412. (I think the KG2 edge IDs are like `[subject]---[original predicate]---[object]---[provided by]`, although I'm likely slightly off with my terminology there..)

this `kg2_ids` property currently isn't being returned from Plover, but it could be... is it something we want for every edge, always? or more just 'on demand', when someone is perusing results in the UI?

**Comment by edeutsch** [comment]
Great, thank you!
1) Yes, I think it would be quite useful to always return this because this comes up frequently. Could be provided as a TRAPI Attribute in the Response?
2) Would be able to look up the edge in the original post? So we can report on Slack?

thanks!
Eric

**Comment by amykglen** [comment]
1. ok - we can start including such attributes once KG2.6.7 is rolled out
2. the `kg2_ids` property isn't present in KG2.5.2, but I traced it back via other methods to this KG2 edge:
```
{
  "predicate": "biolink:causes",
  "negated": "False",
  "relation_label": "causes",
  "publications_info": "{'PMID:9843884': {'publication date': '1998 Dec', 'sentence': 'Male Wistar rats received 0.02% enalapril, 0.02% losartan, or tap water for 1 day before and for 48 h after the induction of renal artery stenosis or sham operation.', 'subject score': 827, 'object score': 1000}}",
  "subject": "UMLS:C0014025",
  "predicate_label": "causes",
  "provided_by": [
    "SEMMEDDB:"
  ],
  "update_date": "2019-04-29 16:56:33",
  "publications": [
    "PMID:9843884"
  ],
  "relation": "SEMMEDDB:causes",
  "object": "UMLS:C0035067"
}
```
so subject was UMLS:C0014025 and object was UMLS:C0035067.

**Comment by edeutsch** [comment]
brilliant, many thanks!
I have relayed the info here https://togithub.com/NCATSTranslator/testing/issues/82

**Comment by amykglen** [comment]
this is fully implemented - will be deployed as part of the KG2.7.2 rollout (changes are in `kg2integration`)

**Comment by amykglen** [comment]
are we good to close this issue, @edeutsch? it was addressed by the `biolink:original_edge_information` attribute:

![Screen Shot 2021-09-23 at 10 18 27 AM](https://user-images.githubusercontent.com/49423686/134554103-5f568427-cfa8-4039-9dbb-c19bf57e23bb.png)

**Comment by edeutsch** [comment]
yes, perfect, thanks, closing!
