### ISSUE TITLE
add_node_pmids using NCBI eUtils?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1547]
I noticed that this message appears in the log for tests that do `overlay(action=add_node_pmids)`:
```
2021-06-30T11:05:16.960370 WARNING: [] Utilizing API calls to NCBI eUtils, so this may take a while...
```
is it actually using NCBI eUtils? and if so, is there a reason why it doesn't use the NGD database instead (`curies_to_pmids.sqlite`)?

**Comment by dkoslicki** [comment]
Looking into it, it appears so. I think the rational was we might be asked to add PMIDs for bioentities not in our KG2. But a more refined, two step process that hits `curies_to_pmids.sqlite` makes sense to employ here

**Comment by finnagin** [comment]
Yeah that makes sense to me. I can implement that.

Note to self: looks like compute_ngd gets the pmids on [these lines](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Overlay/compute_ngd.py#L82-L84).
