### ISSUE TITLE
Non-compliant `attribute_source`

### ISSUE THREAD

**Issue by patrickkwang** [RTXteam/RTX#1548]
_Some_ returned knode `attribute_source` values are arrays of strings instead of strings.

Example:
```bash
curl -X 'POST' \
  'https://arax.ncats.io/api/rtxkg2/v1.1/query' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "message": {
        "query_graph": {
            "nodes": {
                 "n1": {
                    "ids": [
                        "NCBIGene:100188832"
                    ]
                },
                "n2": {
                    "categories": [
                        "biolink:PhenotypicFeature"
                    ]
                }
            },
            "edges": {
                "e1": {
                    "subject": "n1",
                    "object": "n2"
                }
            }
        }
    }
}
```

If you look at the KG edge “16125176”, its attribute_source is an array of strings rather than a string as expected. There are a few others like that, too.

**Comment by amykglen** [comment]
alright, this has been rolled out to production (we now omit `attribute_source` when there are multiple sources and we can't distinguish which information came from which source).

I verified it's working on production with this query: https://arax.ncats.io/?r=15717

will close but feel free to reopen if there are any issues.
