### ISSUE TITLE
Is this an ARAX error, or a user error?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1550]
For this result, I see both a `QueryGraphInterpreter finds more nodes than supported in this query graph` and an `ARS info: tr_ars.reason: BAD REQUEST`, so I don't know where the problem lies:
https://arax.ncats.io/?source=ARS&id=d8f00ee8-28ee-42c7-af06-d47bc1ac2eb6

**Comment by dkoslicki** [comment]
Ah ha, appears to be a query graph interpreter issue again: `2021-07-01T16:57:55.211889 ERROR: [QueryGraphInterpreterUnsupportedGraph]    QueryGraphInterpreter finds more nodes than supported in this QueryGraph` when trying this query:
```
{
  "edges": {
    "e0": {
      "object": "n1",
      "predicates": [
        "biolink:correlated_with"
      ],
      "subject": "n0"
    },
    "e1": {
      "object": "n2",
      "predicates": [
        "biolink:condition_associated_with_gene"
      ],
      "subject": "n1"
    },
    "e2": {
      "object": "n3",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n2"
    }
  },
  "nodes": {
    "n0": {
      "ids": [
        "MONDO:0005359"
      ],
      "name": "drug-induced liver injury"
    },
    "n1": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ],
      "name": "Disease Or Phenotypic Feature"
    },
    "n2": {
      "categories": [
        "biolink:Gene"
      ],
      "name": "Gene"
    },
    "n3": {
      "categories": [
        "biolink:ChemicalSubstance"
      ],
      "name": "Chemical Substance"
    }
  }
}
```

**Comment by edeutsch** [comment]
I have added a crude additional query graph template here:
https://github.com/RTXteam/RTX/blob/380508325d5e0ccb1fee4612b9a36dfca4e7dabc/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter_templates.yaml#L214

The idea is that the query graph templates can be augmented with DSL programs that are suitable for answering various kinds of questions.

If you encounter queries that are not supported, it is just a matter of adding a template for what you'd like to support.
