### ISSUE TITLE
UI HTTP 400 vs 500 error

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1552]
See [this issue](https://github.com/NCATSTranslator/minihackathons/issues/83) differentiating between "we can't do it" vs "error"

**Comment by edeutsch** [comment]
The ARS does not return this information. If it did, we could display it, no problem.
https://ars-dev.transltr.io/ars/api/messages/8278ab41-a0b1-4d27-9665-642c47ed9b85?trace=y

**Comment by dkoslicki** [comment]
I see! Do you want me to update this issue in the minihackathon repo, or shall I?

**Comment by edeutsch** [comment]
already done

**Comment by edeutsch** [comment]
Fixed a while ago.
