### ISSUE TITLE
Another query graph interpreter issue

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1553]
In the Translator minihackathon issues, I'm seeing another `[QueryGraphInterpreterUnsupportedGraph]    QueryGraphInterpreter finds more nodes than supported in this QueryGraph` for https://arax.ncats.io/?source=ARS&id=d8f00ee8-28ee-42c7-af06-d47bc1ac2eb6 as noted here: https://togithub.com/NCATSTranslator/minihackathons/issues/75 (which is certainly not a one-hop query, as reported in that issue)

**Comment by edeutsch** [comment]
I have added a crude additional query graph template here:
https://github.com/RTXteam/RTX/blob/380508325d5e0ccb1fee4612b9a36dfca4e7dabc/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter_templates.yaml#L214

The idea is that the query graph templates can be augmented with DSL programs that are suitable for answering various kinds of questions.

If you encounter queries that are not supported, it is just a matter of adding a template for what you'd like to support.
