### ISSUE TITLE
Speed up test suite and travis build time

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1555]
Looks like we are butting up against the time limit for [travis builds](https://travis-ci.com/github/RTXteam/RTX/builds/231583044). We should start looking into how we might speed up our test suite a bit. 

Also, might be a good idea to look into making slim versions of other database files. Looks like `curie_to_pmids_v1.0_KG2.6.7.sqlite` takes ~7 minutes to download and `node_synonymizer_v1.0_KG2.6.7.sqlite` takes almost 10 minutes.

Does anyone have any other suggestions on how we might go about speeding this up a bit?

**Comment by finnagin** [comment]
There have been some issues with api calls to the SRI so we might be running out of time right because they are taking a while to respond but I'm thinking this is a good idea regardless.

**Comment by finnagin** [comment]
Marking as low priority for now since I'm pretty sure this is due to the SRI api. But going to add it to next weeks AHM for more discussion.

**Comment by dkoslicki** [comment]
Not relevant due to rolling our own CI, right @finnagin ?

**Comment by finnagin** [comment]
Yeah, closing
