### ISSUE TITLE
FMA:264825 might have a wrong category

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1557]
Just noticed that `FMA:264825` is categorized as `biolink:AnatomicalEntity` in kg2.6.7:

However, based on SRI Normalizer and all its categories (most of its synonyms are `biolink:Disease`), it seems like this curie should be `biolink:Disease`. 

<img width="1408" alt="Screen Shot 2021-07-05 at 8 57 55 PM" src="https://user-images.githubusercontent.com/20031672/124527506-b639a080-ddd3-11eb-81bb-01a19cf84d1a.png">

**Comment by ericawood** [comment]
![image](https://user-images.githubusercontent.com/36611732/124834824-362b4c00-df35-11eb-9d5c-16f5291622db.png)

![image](https://user-images.githubusercontent.com/36611732/124834871-47745880-df35-11eb-81fb-272098670e44.png)

**Comment by chunyuma** [comment]
Thanks @ericawood. I think the problem here is that `FMA:264825` is conflated with disease `rheumatoid arthritis`. There is no mapping curie for `rheumatoid arthritis`

**Comment by ericawood** [comment]
I think you're right, though we are fixing it so that Interleukin-10 isn't mapped as an anatomical entity (which isn't very accurate). @amykglen said that this conflation is a known issue and to see #1070

**Comment by saramsey** [comment]
Thank you @chunyuma for the issue report

**Comment by finnagin** [comment]
closing since #1070 is closed
