### ISSUE TITLE
July 6 Standup ARAX CHP

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1558]
There was some question at today's standup if ARAs are using CHP. Seems like people stopped asking by the time we got to ARAX, but I did notice that although we tried CHP, it looks like it was not successful. I'm wondering if we had tried a different CURIE, would it have worked?

![image](https://user-images.githubusercontent.com/12707718/124641991-2718a100-de44-11eb-8a41-74df2ad3b27e.png)

**Comment by edeutsch** [comment]
I should have posted the ARS pk to repro:
60a8a463-c2d4-4f88-98b6-a38d8ad3ff96

**Comment by amykglen** [comment]
if `master` has been rolled out to production within the last two days, it should already be doing curie prefix translation to the kinds CHP wants (https://github.com/RTXteam/RTX/issues/1537#issuecomment-873663693).

but if it hasn't been rolled out yet, doing so might fix this!

**Comment by edeutsch** [comment]
aha, great! I had not rolled out, sorry. I just rolled out and retested:
![image](https://user-images.githubusercontent.com/12707718/124643109-81663180-de45-11eb-867c-562a196dc193.png)

Seems like it tried, but didn't quite succeed?
https://arax.ncats.io/?r=15689

**Comment by amykglen** [comment]
nice - so it looks like the curie prefix translation is happening properly (the main `expand` code converted the UniProt curie to an ENSEMBL curie, the prefix CHP says it supports for genes/proteins). 

but I'm not sure why there's that warning message (coming from `CHPQuerier`) - that's a question for @chunyuma. why isn't `ENSEMBL:ENSG00000102172` allowable for CHP?

**Comment by chunyuma** [comment]
I guess this might be a problem from CHP team. [Here](http://chp.thayer.dartmouth.edu/curies/) is all curies supported by CHP right now and `ENSEMBL:ENSG00000102172` is not there. I will post an issue regarding this problem on CHP github.

**Comment by finnagin** [comment]
@edeutsch @amykglen @chunyuma Is this good to close?

**Comment by chunyuma** [comment]
Close it as we didn't support CHP anymore.
