### ISSUE TITLE
Query graph template complaining again

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1561]
For this  NCATS minihackathon query:
```
{
  "edges": {
    "e00": {
      "object": "n01",
      "subject": "n00"
    },
    "e01": {
      "object": "n02",
      "subject": "n01"
    },
    "e02": {
      "object": "n03",
      "subject": "n02"
    }
  },
  "nodes": {
    "n00": {
      "categories": [
        "biolink:ChemicalSubstance"
      ],
      "ids": [
        "DRUGBANK:DB00150"
      ]
    },
    "n01": {
      "categories": [
        "biolink:Protein"
      ]
    },
    "n02": {
      "categories": [
        "biolink:MolecularActivity"
      ]
    },
    "n03": {
      "categories": [
        "biolink:ChemicalSubstance"
      ],
      "ids": [
        "KEGG.COMPOUND:C02700"
      ]
    }
  }
}
```
I'm getting the usual `2021-07-08T19:58:56.512510 ERROR: QueryGraphInterpreter finds more nodes than supported in this QueryGraph`
Related to #1553, #1550, and #1515

**Comment by dkoslicki** [comment]
Labeling `high priority` since I see many such issues in the minihackathon repo: https://github.com/NCATSTranslator/minihackathons/issues

**Comment by edeutsch** [comment]
I have added a crude additional query graph template here:
https://github.com/RTXteam/RTX/blob/380508325d5e0ccb1fee4612b9a36dfca4e7dabc/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter_templates.yaml#L214

The idea is that the query graph templates can be augmented with DSL programs that are suitable for answering various kinds of questions.

If you encounter queries that are not supported, it is just a matter of adding a template for what you'd like to support.

**Comment by dkoslicki** [comment]
Ah, I see, thanks! Since I didn't see that error message in the `ARAX_query_graph_interpreter_templates.yaml` and didn't dig into the logic around the [associated python code](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter.py#L73), I didn't realize it was such a straightforward fix. I'll address this and the other related issues.
