### ISSUE TITLE
infores:diseases?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1562]
Does anyone know what to do with this report:
https://github.com/NCATSTranslator/minihackathons/issues/127

Should infores:diseases be changed to infores:biothings-diseases?

Or what is the source infores:diseases intended to identify?

**Comment by amykglen** [comment]
do you know what query that's in reference to? I'm wondering if it's coming from an external KP.

**Comment by edeutsch** [comment]
I do not know. I received 5000 emails from GitHub this morning and am totally adrift.
I can ask.

**Comment by amykglen** [comment]
aha! found it - it does seem to be a KG2 thing. it looks like there's an entry in [`kg2-provided-by-curie-to-infores-curie.tsv`](https://docs.google.com/spreadsheets/d/1h4MNiGCkiEfc8iFn3cN0mI0cY85KjjjBRT2D1ni0jJE/edit#gid=0) for `JensenLab:` that points to `infores:diseases`. @ericawood do you know the story behind that?

**Comment by amykglen** [comment]
it looks like `infores:diseases` is actually a real thing? from the 'External Resources' tab of the [landscape spreadsheet](https://docs.google.com/spreadsheets/d/1Ma4U3aY16mJushsW74vf9mWVacFvf7FiTEdlVqaUi5g/edit#gid=1644976602):

![Screen Shot 2021-07-08 at 2 49 44 PM](https://user-images.githubusercontent.com/49423686/124995189-d3e94e80-dffb-11eb-89ab-8079860b5702.png)

so it seems our mapping is correct?

**Comment by ericawood** [comment]
That was the infores curie that it was assigned on the spreadsheet. I have no idea who picked it or why, but I believe that the actual name of the source is JensenLab Diseases. Does that help?

**Comment by amykglen** [comment]
yep, thanks @ericawood! 

so in summary, @edeutsch - `infores:diseases` is in fact a valid infores curie according to the spreadsheet, and we're using it correctly. although it might be prudent for them to give it a more descriptive name, like `infores:jensen-diseases` or something.

**Comment by edeutsch** [comment]
perfect, thanks, I will report this back in the original post in the other repo. thanks!

**Comment by amykglen** [comment]
closing since this was resolved a while back (`infores:diseases` is a real thing, we use it correctly)
