### ISSUE TITLE
Create OW PR for `sort` operations

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1563]
Both [edge attribute](https://github.com/RTXteam/RTX/blob/master/code/ARAX/Documentation/DSL_Documentation.md#filter_resultsactionsort_by_edge_attribute) and [node attribute](https://github.com/RTXteam/RTX/blob/master/code/ARAX/Documentation/DSL_Documentation.md#filter_resultsactionsort_by_node_attribute).

**Comment by finnagin** [comment]
For sort by edge attribute: 
add a ascending/descending parameter and when using ascending take the min of all edges in result (max for decending)

**Comment by finnagin** [comment]
Breakout a second operation to sort by node attributes

**Comment by finnagin** [comment]
add ascending/descending to all sorts

**Comment by finnagin** [comment]
closing since this is now merged
