### ISSUE TITLE
Update OpenAPI schema to implement new operations

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1564]
@finnagin work with @edeutsch to figure out how to change [this file](https://github.com/RTXteam/RTX/blob/master/code/UI/OpenAPI/python-flask-server/RTX_OA3_TRAPI1.1_ARAX.yaml) (if that's even the right one) to properly advertise which operations we [have implemented](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/operation_to_ARAXi.py).

Bonus points if this can be done automatically any time operation_to_ARAXi.py is updated.

**Comment by edeutsch** [comment]
Yes, this is basically the correct file, although it is a template for code generation is not the actual live file. The live file lives a bit deeper down. Do we have the schema definitions for each of these workflows? I am on vacation and am trying to keep up but not managing very well.

**Comment by finnagin** [comment]
@edeutsch by schema definitions do you mean [these](https://github.com/NCATSTranslator/OperationsAndWorkflows/blob/main/operations/overlay_compute_jaccard.yml)?

**Comment by finnagin** [comment]
@edeutsch Just following up on this now that you are back from vacation. Was the OW repo definitions what you meant by the schema definitions?

**Comment by edeutsch** [comment]
Thanks for the reminder, Finn, the answer is yes.

I started the update, but I think I am now blocked by this:
https://github.com/NCATSTranslator/OperationsAndWorkflows/issues/44

I might be able to press ahead, but I'm fearing an explosion from the OpenAPI framework if I try to deploy it as is.

**Comment by dkoslicki** [comment]
Removing Finn, but this issue is still relevant, since we implement some additional operations but don't advertise it. See [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/operation_to_ARAXi.py#L8-L28) for the ones we implement

**Comment by dkoslicki** [comment]
So assigning @edeutsch to updated the OpenAPI schema

**Comment by edeutsch** [comment]
It looks to me like we are advertising exactly this list here:
https://github.com/RTXteam/RTX/blob/9cf40f7aeab1b4674556d18c29fa3003926a87d1/code/UI/OpenAPI/python-flask-server/openapi_server/openapi/openapi.yaml#L26-L47

So I am thinking this is done? Agree and close? Or let me know what is missing?

**Comment by edeutsch** [comment]
This is already fixed, closing.
