### ISSUE TITLE
Other virtual edges dashed in UI

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1566]
The dashed edge for NGD is great from a user perspective, so can we do the same for all the other [overlay edges](https://github.com/RTXteam/RTX/blob/master/code/ARAX/Documentation/DSL_Documentation.md#arax_overlay) too? I just noticed that the FET edges `biolink:has_fisher_exact_test_p-value_with` and the like are solid.

**Comment by edeutsch** [comment]
Is there a concise list of "virtual edges" somewhere? It would be helpful in several places in the application to have a get_virtual_edge_predicates() method. If someone could code that up and make it easy to maintain, that would make it easy to distinguish between virtual edges and real edges.

One little problem I've mused about, though, if we ever get the NGD expand() working, then the NGD edge might become a real edge. I wonder how to handle that.

**Comment by dkoslicki** [comment]
There is a list of attributes that we rank on [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_ranker.py#L176-L196) that covers all (most?) of the virtual edges, but that might differ slightly from the predicates (prepending `has_` and appending `_with` perhaps). 

Good point about NGD expand, hadn't thought about that

**Comment by isbluis** [comment]
I concur that having a call that enumerates the known virtual edges would be better than hard-coding them into the UI.  Or perhaps adding some sort of "is_virtual" attribute to the edge?

In the meantime, using the list from the code block that @dkoslicki pointed out, I was able to find the following virtual edges elsewhere in ARAX code,:
```
biolink:has_chi_square_pvalue_with
biolink:has_chi_square_with
biolink:has_fisher_exact_test_p-value_with
biolink:has_jaccard_index_with
biolink:has_normalized_google_distance_with
biolink:has_observed_expected_ratio_with
biolink:has_paired_concept_frequency_with
biolink:probability_treats *
biolink:probably_treats *
```
 _(*) Note that the last two appear to be interchangeable in parts of the code -- is this correct?_

Predicates in the list above are now recognized by the UI as virtual in my dev area:   https://arax.ncats.io/devLM/

The following attributes were not found as having `biolink:` predicates in ARAX code:
```
Genetics-quantile
MAGMA-pvalue
Richards-effector-genes
feature_coefficient
pValue
probability
```

Does anyone know what they are?
Good to ignore, at least for now?

**Comment by amykglen** [comment]
I think these four are attributes passed along from the GeneticsKP:
```
Genetics-quantile
MAGMA-pvalue
Richards-effector-genes
pValue
```
so edges that use those aren't virtual (good to ignore).

> I was able to find the following virtual edges elsewhere in ARAX code,:
> 
> biolink:has_chi_square_pvalue_with
> biolink:has_chi_square_with
> biolink:has_fisher_exact_test_p-value_with
> biolink:has_jaccard_index_with
> biolink:has_normalized_google_distance_with
> biolink:has_observed_expected_ratio_with
> biolink:has_paired_concept_frequency_with
> biolink:probability_treats *
> biolink:probably_treats *

beware that some (or many?) of these are also used for edges created by `expand`, in which case they're not virtual. for example, if you expand using DTD, the resulting edges will have the predicate `biolink:probability_treats` or if you expand using COHD, edges will have the predicates `biolink:has_chi_square_pvalue_with` and `biolink:has_paired_concept_frequency_with`, etc. (similar situation with attributes.) but none of those edges are virtual in this case. so I don't think predicates/current attributes alone can distinguish virtual from real edges. 

maybe having some sort of `is_virtual` attribute (which `overlay` sticks onto edges), as you suggested, might be the best solution?

**Comment by isbluis** [comment]
Just to note that I have pulled this feature from the UI (including devLM) until there is a resolution to this.

I can easily add it back if the benefits of having the dashed lines for all instances of these edge types outweigh the concerns raised by @amykglen  and @edeutsch .  Just let me know.

Agree that having an `is_virtual` attribute (or equivalent) would be best.

**Comment by edeutsch** [comment]
My opinion is that the benefits outweigh my concerns. I was just musing about future edge cases that don't exist yet.

But that said, it would be a nice practice to start adding a special attribute to "virtual edges"
What should the attribute_type_id be? Suggestions?
We could just use "biolink:is_virtual", but maybe we should step back and think about an elegant solution rather than a crufty patch.

What's the distinction between a "real edge" and a "virtual edge"?
Well, they were added by ARAX to augment the original query_graph
I was originally thinking they were an "informational edge" rather than a "relationship edge" but after pondering that for a while, that doesn't seem like a useful distinction.

I dunno. It seems like an elegant concept should be out there, but I cannot think of it.

**Comment by edeutsch** [comment]
After discussion on the call on 7/28, we concluded that all "virtual edges" should get an Attribute with attribute_type_id="biolink:computed_value" and value=true

The UI can then make all edges with that attribute dashed. And perhaps useful for other cases.

right?

**Comment by amykglen** [comment]
so does this look good for the new attribute?
```
                {'attribute_source': 'infores:arax-reasoner-ara',
                 'attribute_type_id': 'biolink:computed_value',
                 'description': None,
                 'original_attribute_name': None,
                 'value': True,
                 'value_type_id': 'metatype:Boolean',
                 'value_url': None}
```
not positive about the `value_type_id` - got it from this page: https://biolink.github.io/biolink-model/docs/types/Boolean.html

**Comment by edeutsch** [comment]
Since we're just making this up, I suggest a description of:

This edge is a container for a computed value between two nodes that is not directly attachable to other edges.

Does that seem like an accurate description?

**Comment by amykglen** [comment]
seems good to me! changes are in `master` for COHD, DTD, and NGD Expand.

the final attribute looks like this:
```
                {'attribute_source': 'infores:arax-reasoner-ara',
                 'attribute_type_id': 'biolink:computed_value',
                 'description': 'This edge is a container for a computed value '
                                'between two nodes that is not directly '
                                'attachable to other edges.',
                 'original_attribute_name': None,
                 'value': True,
                 'value_type_id': 'metatype:Boolean',
                 'value_url': None}
```
easy to tweak pending any changes from @dkoslicki or others.

**Comment by isbluis** [comment]
Is there a response id that already contains this so I can get it into the UI?

**Comment by isbluis** [comment]
Does this look good with the latest deployment, @dkoslicki ?

**Comment by dkoslicki** [comment]
Is this on the standard deployment? If so, it appears to still only have NGD edges dashed. See:
```
# This program creates two query nodes and a query edge between them, looks for matching edges in the KG,
# overlays NGD metrics, and returns the top 30 results
add_qnode(ids=CHEMBL.COMPOUND:CHEMBL112, key=n0, categories=biolink:ChemicalEntity)
add_qnode(categories=biolink:DiseaseOrPhenotypicFeature, key=n1)
add_qedge(subject=n0, object=n1, key=e0)
expand()
overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n0, object_qnode_key=n1)
overlay(action=fisher_exact_test,subject_qnode_key=n0,virtual_relation_label=F1,object_qnode_key=n1)
overlay(action=overlay_clinical_info,COHD_method=paired_concept_frequency,virtual_relation_label=C1,subject_qnode_key=n0,object_qnode_key=n1)
overlay(action=predict_drug_treats_disease,virtual_relation_label=P1,subject_qnode_key=n0,object_qnode_key=n1,threshold=0.8,slow_mode=false)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```

**Comment by isbluis** [comment]
The UI code triggers on the `biolink:computed_value` edge attribute:

![image](https://user-images.githubusercontent.com/37852256/130301363-a232a324-8390-4932-bf83-7957faa21d83.png)

Not sure if other modules need to add this, or if it is still pending a merge or deployment:

![image](https://user-images.githubusercontent.com/37852256/130301533-8cfd94ce-a077-4da2-b22b-37b0cc4a85a0.png)

Or maybe these edges become "real", @amykglen ?  (sorry, not sure who else to tag).

**Comment by dkoslicki** [comment]
Oh, interesting! @edeutsch (and perhaps @amykglen) should we (expand people) be adding that attribute (`biolink:computed_value`) to each of the overlay edges? I don’t know who has been on the data modeling calls (or if this is TRAPI)

**Comment by amykglen** [comment]
yeah, the `biolink:computed_value` attribute is intended to be used for all Overlay edges and for Expand edges from DTD/COHD/NGD (per @dkoslicki). I think we (ARAX team) settled on that at an AHM or mini-hackathon a while back and it looks like the attributes just aren't yet being added to Overlay edges (@finnagin?)

**Comment by dkoslicki** [comment]
Oh right, thanks @amykglen for clarifying (I should have just scrolled up; >3 weeks ago means it left my brain RAM). @finnagin mind if I assign this to you for all the `overlay` components (save for the DTD and FET edges that @chunyuma will cover)?

**Comment by amykglen** [comment]
no problem! pasting in the attribute here for easy access for @finnagin and @chunyuma:
```
                {'attribute_source': 'infores:arax-reasoner-ara',
                 'attribute_type_id': 'biolink:computed_value',
                 'description': 'This edge is a container for a computed value '
                                'between two nodes that is not directly '
                                'attachable to other edges.',
                 'original_attribute_name': None,
                 'value': True,
                 'value_type_id': 'metatype:Boolean',
                 'value_url': None}
```

**Comment by dkoslicki** [comment]
In short @chunyuma and @finnagin , the overlay edges need to have the following attribute added to them:
```
                {'attribute_source': 'infores:arax-reasoner-ara',
                 'attribute_type_id': 'biolink:computed_value',
                 'description': 'This edge is a container for a computed value '
                                'between two nodes that is not directly '
                                'attachable to other edges.',
                 'original_attribute_name': None,
                 'value': True,
                 'value_type_id': 'metatype:Boolean',
                 'value_url': None}
```

**Comment by dkoslicki** [comment]
Ninja'd!

**Comment by chunyuma** [comment]
I've added the following attribute to all overlay edges:
```
                {'attribute_source': 'infores:arax-reasoner-ara',
                 'attribute_type_id': 'biolink:computed_value',
                 'description': 'This edge is a container for a computed value '
                                'between two nodes that is not directly '
                                'attachable to other edges.',
                 'original_attribute_name': None,
                 'value': True,
                 'value_type_id': 'metatype:Boolean',
                 'value_url': None}

```

**Comment by finnagin** [comment]
Thanks @chunyuma !

**Comment by isbluis** [comment]
Good to close, @dkoslicki ?

**Comment by dkoslicki** [comment]
Yup, looks good to me!
