### ISSUE TITLE
Speed up multi-hop queries in QGI

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1568]
Perhaps incrementally expand + FET instead of saving FET for the end

**Comment by dkoslicki** [comment]
Issue is the following: For these long queries, I would like to do intermediate FET expansions via:
```
add_qnode(key=n00,ids=DRUGBANK:DB00150,categories=biolink:ChemicalSubstance)
add_qnode(key=n01,categories=biolink:Protein)
add_qedge(key=e00,subject=n00,object=n01)
expand(edge_key=e00)
overlay(action=fisher_exact_test,subject_qnode_key=n00,virtual_relation_label=F0,object_qnode_key=n01,filter_type=top_n,value=30)
resultify()
add_qnode(key=n02,categories=biolink:MolecularActivity)
add_qedge(key=e01,subject=n01,object=n02)
expand(edge_key=e01)
overlay(action=fisher_exact_test,subject_qnode_key=n01,virtual_relation_label=F1,object_qnode_key=n02,filter_type=top_n,value=30)
resultify()
add_qnode(key=n03,categories=biolink:ChemicalSubstance)
add_qedge(key=e02,subject=n02,object=n03)
expand(edge_key=e02)
overlay(action=fisher_exact_test,subject_qnode_key=n02,virtual_relation_label=F2,object_qnode_key=n03,filter_type=top_n,value=30)
resultify()
overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n00, object_qnode_key=n01)
overlay(action=compute_ngd, virtual_relation_label=N2, subject_qnode_key=n01, object_qnode_key=n02)
overlay(action=compute_ngd, virtual_relation_label=N3, subject_qnode_key=n02, object_qnode_key=n03)
resultify()
filter_results(action=limit_number_of_results, max_results=100)
```
However, the QGI creates the QG and expects operations to be added on top of this. Will need to find some way to nuke the QG and incrementally construct it (while preserving categories, types, and curies).

**Comment by dkoslicki** [comment]
Option 2: overlay fisher on everything, and then just use filter by top n to reduce the KG size before expanding again. No need to do intermediate resultifies that way

**Comment by amykglen** [comment]
is there a benefit to having the FET steps explicitly laid out by the QGI, or is that something `expand` could do automatically when there are lots of answers? (over a certain threshold #1535)

that would let `expand` continue to decide for itself what order to expand `qedges` in, which can be beneficial..

**Comment by dkoslicki** [comment]
@amykglen I could imagine that it would be helpful for `expand` to do FET-like a la #1535 (thanks for reminding me about that idea), I just wonder about the following: for multi-hop queries with >=3 hops, the top `n` threshold that "should" be used to get good results really depends on the path length. Eg. for 3 hops, a general `n=100` seems find for the last two hops (as 10K isn't _too_ big), but for 4 hops, one would want to decrease the number of edges/nodes kept in each hop to something much smaller as now it would grow like `n^3`. If there is a way for `expand` to be aware of how many more subsequent errors there would need to be expanded, I imagine heuristics could be put into place. Is that a possibility?

**Comment by edeutsch** [comment]
I don't know if this is still relevant, but regarding:
> However, the QGI creates the QG and expects operations to be added on top of this. Will need to find some way to nuke the QG and incrementally construct it (while preserving categories, types, and curies).

I don't think the above statement is compatible with what actually happens. QGI doesn't create a QG. It *starts* with a QG. It just adds operations on top. of that. In the example DSL in the original post, the add*() functions are interspersed with operations, but no reason that they need to be or should be (I think?) The DSL where all the add*() functions come first is just as valid. And thus, if the incoming QC is the equivalent of the add*() functions above, then running the subsequent DSL will give the same result. All that needs to happen is that the QGI needs to match the incoming QG to a template in the YAML that provides the subsequent operations.

i.e. I think this is all possible now with an improved YAML.

**Comment by dkoslicki** [comment]
>In the example DSL in the original post, the add*() functions are interspersed with operations, but no reason that they need to be or should be (I think?)

Actually, it is important here since `resultify` attempts to fulfil the _full_ QG, so if things are added and not expanded, one would get no results.

I think, however, that this point might become moot after #1570 since I can use a `filter` command (instead of leveraging `resultify`'s "filtering" which throws away things that don't satisfy the QG, like the added FET edges in this case). Basically: FET with `top_n` introduces a QG edge and only populates `n` such edges in the KG, so `resultify` throws away any paths in the KG that don't have FET edges (as they wouldn't fulfill the QG). But come to find out, this is the same as filtering the KG using `filter_top_n`, so after the #1570 bug is/was addressed, I shouldn't need to rely on `resultify` to do the filtering

**Comment by edeutsch** [comment]
> > In the example DSL in the original post, the add*() functions are interspersed with operations, but no reason that they need to be or should be (I think?)
> 
> Actually, it is important here since `resultify` attempts to fulfil the _full_ QG, so if things are added and not expanded, one would get no results.

ah, I get it, right. I agree that removing that requirement to rely on resultify() to do the filtering would be a benefit so that such that QG and processing can be separated. Perhaps an alternative hack is to give resultify() a parameter that tells it to only consider certain qnodes and qedges (and completely ignore the rest)

> I think, however, that this point might become moot after #1570 since I can use a `filter` command (instead of leveraging `resultify`'s "filtering" which throws away things that don't satisfy the QG, like the added FET edges in this case). Basically: FET with `top_n` introduces a QG edge and only populates `n` such edges in the KG, so `resultify` throws away any paths in the KG that don't have FET edges (as they wouldn't fulfill the QG). But come to find out, this is the same as filtering the KG using `filter_top_n`, so after the #1570 bug is/was addressed, I shouldn't need to rely on `resultify` to do the filtering

**Comment by amykglen** [comment]
> @amykglen I could imagine that it would be helpful for expand to do FET-like a la #1535 (thanks for reminding me about that idea), I just wonder about the following: for multi-hop queries with >=3 hops, the top n threshold that "should" be used to get good results really depends on the path length. Eg. for 3 hops, a general n=100 seems find for the last two hops (as 10K isn't too big), but for 4 hops, one would want to decrease the number of edges/nodes kept in each hop to something much smaller as now it would grow like n^3. If there is a way for expand to be aware of how many more subsequent errors there would need to be expanded, I imagine heuristics could be put into place. Is that a possibility?

hmm, I'm not sure I'm seeing your concerns. the approach I was thinking of is pretty agnostic to the length of the query path, I think - it just would prevent each hop from ever retaining more than N answers, where N is the max number of curies that we know (empirically) the system doesn't get overloaded with _when_ they're fed into a subsequent hop. (this number seems to be somewhere around 2,000, maybe a little smaller.)

so it would work something like this:

1. expand the first hop - let's say it produces 600 curies
1. since 600 is less than 2,000, go ahead and expand the second hop without any FET
1. now let's say the second hop produced 4,200 curies
1. since that's more than 2,000, filter those down using FET so we only keep 2,000
1. then expand the third hop (feeding in those 2,000 curies we kept) - say it produces 11,000 curies
1. since 11,000 is more than 2,000, filter those down using FET so we only keep 2,000
1. then expand the fourth hop (feeding in the 2,000 curies we kept) - say it produces 10,000 curies

so generally with this approach, doing 4 hops vs. 3 hops would only result in about 2,000 more nodes in your answer (since that's how many curies we keep for each hop). so it's a linear increase with the number of hops.

**Comment by dkoslicki** [comment]
@amykglen While it is true that this approach will only linearly increase the number of _nodes_, I’m concerned about the number of _paths_. I have seen some of the biggest slow downs happening when resultify needs to work it’s way through O(\product_{layer i=1}^n (# nodes in layer i)) possible paths in an n-hop query.

**Comment by amykglen** [comment]
hm, interesting, I haven't observed that. in the experimentation I've done this approach has seemed to be fast for resultify, though I haven't done a ton of testing of it. (which makes sense as I think resultify is O(n + e).) will see if I can reproduce that though. (edges that are orphaned by throwing out the excess nodes on each hop are of course also filtered out.)

**Comment by dkoslicki** [comment]
Closing since `expand` now uses FET
