### ISSUE TITLE
FET error when non-RTX-KG2 kp's called

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1569]
The following results in an error:
```
add_qnode(key=n00,ids=DRUGBANK:DB00150,categories=biolink:ChemicalSubstance)
add_qnode(key=n01,categories=biolink:Protein)
add_qedge(key=e00,subject=n00,object=n01)
expand(edge_key=e00)
overlay(action=fisher_exact_test,subject_qnode_key=n00,virtual_relation_label=F0,object_qnode_key=n01,filter_type=top_n,value=30)
resultify()
filter_results(action=limit_number_of_results, max_results=100)
```
with the message ` 2021-07-13T18:47:49.262491 ERROR: [IndexError]    Traceback (most recent call last): File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Overlay/fisher_exact_test.py", line 212, in fisher_exact_test edge_expand_kp.append(temp_kp[0]) IndexError: list index out of range `

However, the following executes without issue:
```
add_qnode(key=n00,ids=DRUGBANK:DB00150,categories=biolink:ChemicalSubstance)
add_qnode(key=n01,categories=biolink:Protein)
add_qedge(key=e00,subject=n00,object=n01)
expand(edge_key=e00, kp=RTX-KG2)
overlay(action=fisher_exact_test,subject_qnode_key=n00,virtual_relation_label=F0,object_qnode_key=n01,filter_type=top_n,value=30)
resultify()
filter_results(action=limit_number_of_results, max_results=100)
```

**Comment by amykglen** [comment]
maybe related to #1438 :)

**Comment by chunyuma** [comment]
You're right @amykglen. It is related to #1438. I fixed this issue now.
