### ISSUE TITLE
sample.py is not working

### ISSUE THREAD

**Issue by arnabdotorg** [RTXteam/RTX#157]
https://github.com/RTXteam/RTX/blob/master/code/autocomplete/sample.py

**Comment by Palzer** [comment]
Working for me. Run with 'python sample.py'.

**Comment by dkoslicki** [comment]
@Palzer Is the code also python3 compliant? Most(?) all the code we have is python3, so I just wanted to check.

**Comment by Palzer** [comment]
Its currently python2, but there is minimal python code. I'll create an issue for porting it.
