### ISSUE TITLE
Predicates in summary table

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1572]
From the minihackathons: https://github.com/NCATSTranslator/minihackathons/issues/73
>Ask from Chris B - it would be nice to add predicates to the results summary table (currently Chris has to write code to get that information out of the results, time consuming process.)
Create a ticket for Eric to build that into the ARAX UI.

For when you are back from vacation @isbluis

**Comment by isbluis** [comment]
Hi @dkoslicki .  At the moment, ARAX results are post-processed by @edeutsch , he adds the _Score_, _Essence_, and _Essence_Category_ to an ad-hoc data structure before sending the enhanced response to the UI, where it just displays what is in that structure.  For non-ARAX responses, the UI guesses an essence (hence "Guessence") via very simple node-counting.

I can work on adding predicates to the latter, but will need Eric's help for the former.

Also, there are often multiple edges connected to the "essence" node -- what would they like displayed in that table?  Just the first one in the array?  Exclude certain ones?

**Comment by dkoslicki** [comment]
Sounds good: hopefully the script @finnagin writes will work on any TRAPI response, so shouldn't be too difficult to get for non-ARAX queries. And this KP info isn't for a particular edge, but rather all edges (what KPs contributed to any of the answers being displayed)

**Comment by isbluis** [comment]
Did you mean the above comment for #1575, @dkoslicki ?

In the meantime, I have added the **predicate** column to the Summary table, at:  https://arax.ncats.io/devLM/index.html
Dead-simple method, simply extracts the predicate from the first edge in the result.

Please let me know if this is sufficient, at least for now.

Thanks!

**Comment by dkoslicki** [comment]
Whoops, that’s what I get for trying to respond on mobile :P Here again though, I’m thinking that a list of predicates might be in order: basically a (sorted? Somehow ordered?) list of all predicates in each answer/result

**Comment by isbluis** [comment]
Hi  @dkoslicki .  I saw your comment on https://github.com/NCATSTranslator/minihackathons/issues/73 .  

If this is still a desired feature, the UI could certainly have multiple predicates in that column (perhaps not too pretty, as some results have 10+ predicates).

What would be preferable is if the edges (and nodes) were labeled at source as being part of the "essence", instead of having the UI guess -- which is prone to do it incorrectly and thus mislead.

Alternatively, if we can get a hold of Chris B. 's code that extracts this info, I could plug it into the UI so that we provide the same result.

**Comment by dkoslicki** [comment]
Yeah, I'm on the fence about this one: given that the provenance feature you added does show the edge types, I don't know the value-add of also having them in the summary table (and potentially cluttering things up). I can ask Chris B. tomorrow during the standup to see if what you've done is already sufficient.

**Comment by isbluis** [comment]
Hi @dkoslicki .   Ok to close since the original request has been marked as resolved/closed?

**Comment by dkoslicki** [comment]
Yes indeed!
