### ISSUE TITLE
TRAPI validator complaining about "biolink:undefined"

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1576]
see this query: https://arax.ncats.io/?r=16346

<img width="1264" alt="Screen Shot 2021-07-16 at 10 30 06 AM" src="https://user-images.githubusercontent.com/49423686/125986572-684cb50e-810b-471e-a853-b5278c84351c.png">

think maybe just need to change it to `biolink:Undefined`

**Comment by edeutsch** [comment]
yes, changing it to biolink:Undefined would fix the validation error. But is that valid BioLink? biolink:NamedThing would be the most generic category I think?

**Comment by amykglen** [comment]
oh, yeah, that's strange that it's being used as a node category - before reading the error message closely I was assuming it must be an attribute type of some sort. there aren't any nodes with the category `biolink:undefined` in KG2/c... so maybe this is coming from another KP?

yep, confirmed it seems to be some other KP that's the problem - here's the same query using only KG2: https://arax.ncats.io/?r=16386

hmm... not great if an external KP is making ARAX fail TRAPI validation... should we try to do a check to correct this kind of thing? or not worth it?

**Comment by amykglen** [comment]
looks like Multiomics KP might be the culprit: https://arax.ncats.io/?r=16389

**Comment by edeutsch** [comment]
It's actually really easy to do validation. Just need a try except block like this:
https://github.com/RTXteam/RTX/blob/90e1676736643208ee90de1b77f3d33d1f596026/code/ARAX/ResponseCache/response_cache.py#L367

But the validation seems rather slow, so I wonder if it introduces an unpleasant delay. Plus, what would you do?
- Add a WARNING to the logs (which probably isn't read) but continue and still include it and suffer the TRAPI FAIL (although the reason would be clearer after studying the logs)?
- Add a WARNING to the logs (which probably isn't read) and exclude the information from that KP?
- Fix the problems? Probably extremely hard.

I'm under the impression that we're already suffering from WARNING fatigue. Many responses have warnings and they are rarely checked. Or?

I'm thinking it might be a nice addition to do validation but then include as is, but it's not obvious that it needs to be done.

**Comment by amykglen** [comment]
yep, good points. I'm not sure it's worth doing any extra validation.

I did just report this issue to Ryan Roper though. perhaps that's all we should do when we see things like this!

**Comment by amykglen** [comment]
Ryan said they weren't aware of this problem and that they'll fix it.

guess I'll close this issue since it seems there isn't anything further to do on our end.
