### ISSUE TITLE
Inconsistent values in description of slow_mode parameter in overlay->predict_drug_treats_disease 

### ISSUE THREAD

**Issue by isbluis** [RTXteam/RTX#1577]
The parameter description returned by the `describe_me()` function of `overlay(action=predict_drug_treats_disease)` returns this for `slow_mode`:

```
      "slow_mode": {
        "is_required": false,
        "examples": [
          "T",
          "t",
          "True",
          "F",
          "f",
          "False"
        ],
        "enum": [
          "True",
          "False"
        ],
        "type": "string",
        "description": "Whether to call DTD model directly rather than the precomputed DTD database to do a real-time calculation for DTD probability (default is False)",
        "default": 0.8
      }

```
1. type should be `"boolean"`
2. the values for `examples` and `enum` should be swapped
3. `default` value (0.8) seems incorrect

I think this affects the user documentation as well as the build-a-query in the UI.

**Comment by chunyuma** [comment]
Thanks @isbluis for pointing this out. I've modified the description.

**Comment by isbluis** [comment]
No worries, thanks for the update, @chunyuma !

One minor detail: can you please make the default a string (`"false"`) instead of a boolean?  It's how the UI is able to know which option to auto-select in the pull-down menu.

**Comment by chunyuma** [comment]
I change it to a string "false" now.

**Comment by isbluis** [comment]
Sorry it was unclear and somewhat odd; it should be as follows:

```
        "type": "boolean",
        "default": "false"
```

It is done like this for all other boolean types in the documentation.

Thanks!

**Comment by chunyuma** [comment]
ok, I changed it to what you told me above. Sorry for misunderstanding what you said.

**Comment by isbluis** [comment]
Looks good; thank you @chunyuma !
