### ISSUE TITLE
COHD errors out with chi square

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1581]
For this query:
```
add_qnode(key=n0,ids=NCBIGENE:1956,categories=biolink:Gene)
add_qnode(key=n1,categories=biolink:ChemicalSubstance)
add_qedge(key=e0,subject=n0,object=n1,predicates=[biolink:entity_negatively_regulates_entity,biolink:negatively_regulates_entity_to_entity, biolink:decreases_activity_of, biolink:decreases_expression_of,biolink:disrupts,biolink:increases_degradation_of,biolink:negatively_regulates])
# Cytotoxic node
add_qnode(key=n2,ids=UMLS:C1511636,categories=biolink:InformationContentEntity)
# Exclude drugs that are cytotoxic
add_qedge(key=e1,subject=n1,object=n2,exclude=true)
# FDA approved drug
add_qnode(key=n3,ids=MI:2099,categories=biolink:InformationContentEntity)
add_qedge(key=e2,subject=n1,object=n3)
# Acanthosis nigricans node
add_qnode(key=n4,ids=MONDO:0007035,categories=biolink:Disease,option_group_id=1)
add_qedge(key=e3,subject=n1,object=n4,option_group_id=1)
# Direct query
expand(kp=RTX-KG2)
# Look at EHR data
expand(kp=COHD,edge_key=e3,COHD_method=chi_square,COHD_method_top_N=1000)
# ML model for drug-treats-disease
expand(kp=DTD,edge_key=e3,DTD_threshold=0.6,DTD_slow_mode=true)
resultify()
```
I get the following error: `ERROR: An uncaught error was thrown while trying to Expand using COHD. Error was: Traceback (most recent call last): File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 320, in _expand_edge answer_kg = kp_querier.answer_one_hop_query(edge_qg) File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Expand/COHD_querier.py", line 76, in answer_one_hop_query final_kg = self._answer_query_using_COHD_chi_square(query_graph, COHD_method_top_N, log) File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Expand/COHD_querier.py", line 709, in _answer_query_using_COHD_chi_square res = self.cohdIndex.get_chi_square(concept_id_pair=omop_pairs, domain="", dataset_id=3) # use the hierarchical dataset AttributeError: 'COHDQuerier' object has no attribute 'cohdIndex'`

However, replacing `COHD_method=chi_square` with `COHD_method=paired_concept_freq` it executes without issue: https://arax.ncats.io/?r=16634

**Comment by chunyuma** [comment]
Sorry for this bug. It should be fixed now.

**Comment by dkoslicki** [comment]
Verified in production, so closing. Thanks @chunyuma
