### ISSUE TITLE
How to handle NOT edges when subclass_of reasoning is in play

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1582]
so our new `subclass_of` reasoning interacts in interesting ways with the handling of `exclude=True` (NOT) edges... here's the situation:

consider this QG:
<img src="https://user-images.githubusercontent.com/49423686/126827088-65399fac-163c-42c6-ad91-89372290308e.png" width="350">
there are 16 chemical substances in KG2c that both `treat` and `predispose` MONDO:0004985 (bipolar disorder):

['(+/-)NICOTINE', 'ALCOHOL', 'ANAKINRA', 'ATOMOXETINE HYDROCHLORIDE', 'Antidepressants', 'CHOLECALCIFEROL', 'FOLIC ACID', 'LEVOTHYROXINE SODIUM', 'LITHIUM ION', 'METHYLPHENIDATE', 'NITRIC OXIDE', 'OMEGA-3 FATTY ACIDS', 'TRASTUZUMAB EMTANSINE', 'agonists', 'antioxidant', 'antipsychotic agent']

(_as a side note: the quality of this list seems a little questionable? but that's separate from this issue.. 🙂_)

before `subclass_of` reasoning was implemented, all 16 of those chemical substances were excluded from the results for this query, due to the NOT edge.

but now that we have `subclass_of` reasoning, two of those chemical substances (Antidepressants and LITHIUM ION) are still actually appearing in the results for this query, because they have a `treats` edge to a _child_ of bipolar disorder (bipolar II disorder - MONDO:0000693), but no `predisposes` edge to that child.   https://arax.ncats.io/?r=16819

is this the way we want it to work? or should those `treats` edges between Antidepressants/LITHIUM ION and bipolar II disorder _also_ be blown away, since Antidepressants and LITHIUM ION `predispose` bipolar disorder (the parent)?

I suppose I'm thinking our current handling is best, but thought I'd raise the issue for anyone else's input..

**Comment by edeutsch** [comment]
Tough question. I think I agree current handling is best, but I'm not at all certain about that.

**Comment by finnagin** [comment]
@edeutsch @amykglen is this okay to close?
