### ISSUE TITLE
Synonymizer made with updated SRI NodeNormalizer

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1584]
fantastic news on the synonymization front - in the synonymizer built using the updated (but still Biolink 1.8) SRI NodeNormalizer and KG2.6.7 (thanks @acevedol!), we're down from 3001 entries in `Problems.tsv` to only **76**!! 

almost all of our known conflations have been resolved - I added a new column to the mis-synonymizations spreadsheet documenting this: https://docs.google.com/spreadsheets/d/1fi0HY_Obe-5LJ6m84Rv4HhhlUr0oPTCbHPvwlH8YThQ/edit#gid=0

(the build artifacts are on arax.ncats.io at `/data/orangeboard/databases/KG2.6.7/synonymizer_new-sri`)

because we're about to be able to start building a synonymizer/KG2c from KG2.7.X as soon as the Biolink 2.X SRI NodeNormalizer is ready (which was expected to happen last week... should be any day now?) and we ideally will have that rolled out by July 28 (the Architecture deadline), it seems like we probably shouldn't roll out this improved synonymizer...?

but I would think we should see a similar low level of mis-synonymization in the KG2.7.Xc build!

**Comment by edeutsch** [comment]
This is fantastic news, thank you!

How close are we to have KG2.7.X ready for deployment?

If it's still going to be a while, then I'm thinking that getting KG2.6.7 deployed would be a good so that we can stop serving up bad conflations that still appear in standups and such. And we can close some issues and tidy up.

**Comment by amykglen** [comment]
KG2.7.0 has been ready for a while now (@ericawood may do a minor rebuild to create KG2.7.1, but that's not critical) - we're just waiting on a couple things for the NodeSynonymizer:
1. the new Biolink 2.1 SRI NodeNormalizer service to be released (since the NodeSynonymizer depends on this service) - Chris B. said it would hopefully be released last week and that he was going to post updates on slack, but that hasn't happened yet
2. the NodeSynonymizer code to be updated for Biolink 2.1  - I don't know everything that will need to be updated, but one example is its hard-coded category conflations: ChemicalSubstance no longer exists in Biolink 2.1, so the ChemicalSubstance == Drug conflation needs to be tweaked

**Comment by amykglen** [comment]
I think it was mentioned in last week's Architecture meeting that at this week's call we'd check in about the Biolink 2.1 deadline and potentially push it out depending on how people are doing. I guess since the Biolink 2.1 SRI NodeNormalizer still hasn't been released, which many KPs/ARAs depend on, it's seeming unlikely to me that the July 28 deadline will hold..

so I'm up for rolling out this KG2.6.7c rebuild. these are huge improvements - would be nice to get them out.

**Comment by amykglen** [comment]
guess I'll close this since we've rolled it out now
