### ISSUE TITLE
ngd should have proper provenance

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1585]
Now that provenance is so easy to see because of #1575
![image](https://user-images.githubusercontent.com/12707718/126925538-27076aa1-eb9a-407a-8c54-17ecf1b7ac32.png)

I now notice that NGD edges don't have the new style of provenance. Instead of this:
```
            {
              "attribute_type_id": "biolink:provided_by",
              "original_attribute_name": "provided_by",
              "value": "ARAX"
            }
```
it should now be:
```
            {
              "attribute_source": "infores:arax-reasoner-ara",
              "attribute_type_id": "biolink:aggregator_knowledge_source",
              "value": "infores:arax-reasoner-ara",
              "value_type_id": "biolink:InformationResource"
            }
```

Would someone make that change?

**Comment by dkoslicki** [comment]
Thanks for pointing this out! I’ve assigned @finnagin

**Comment by finnagin** [comment]
Looks like it is working: https://arax.ncats.io/test/?r=16933

the ngd edges have this attribute now:

```
attribute_type_id: biolink:aggregator_knowledge_source
original_attribute_name: provided_by
value_type_id: biolink:InformationResource
attribute_source: infores:arax-reasoner-ara
value: infores:arax-reasoner-ara
```

Though I don't see any provenance info in the provenance tab. How do you get that to show up @edeutsch ?

**Comment by edeutsch** [comment]
excellent, confirmed working, thanks!

Until I manage to change the OpenAPI schema, you can only see results in the provenance tab if the query comes through the ARS. So I submitted you query to ARS and here are the results for ARAX:
https://arax.ncats.io/test/?source=ARS&id=1164c9b5-d24e-4fe2-9d7c-7000309cf439
(here the Provenance tab works)

and the results for everyone so that everyone can compare provenance from everyone with @isbluis 's whizzy new UI features:
https://arax.ncats.io/test/?source=ARS&id=a91b6205-c88a-434e-acb2-a397f4d8dbda

(note that there is a long delay before anything appears to happen. This is an ARS problem and has been reported to them)
