### ISSUE TITLE
Roll KG2.6.7.1 out to production

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1586]
This is for the KG2c built from KG2.6.7, using the updated (but still Biolink 1.8) SRI NodeNormalizer

- [x] build a new KG2c (available at http://kg2-6-7-1c.rtx.ai:7474/browser/)
- [x] load it into plover (available at http://kg2-6-7-1cplover.rtx.ai:9990)

Rebuild or edit and put copies in `/translator/data/orangeboard/databases/KG2.6.7.1` on arax.ncats.io:

- [x] configv2.json (should point to the new KG2c/plover)
        * note: saved this as `config_local.json`, since we want it to be used over `configv2.json` during testing
- [x] KG2c meta knowledge graph
- [x] NodeSynonymizer
- [x] KG2c sqlite
- [x] NGD database
- [x] COHD database @chunyuma
- [x] refreshed DTD @chunyuma
- [ ] DTD model @chunyuma
- [ ] DTD database @chunyuma - think we can skip a full rebuild this time since KG2.7.x will be rolled out soon?
- [x] 'slim' databases (used for Travis) @chunyuma / @finnagin

**Note**: As databases are rebuilt, the new copy of `config_local.json` will need to be updated to point to their new paths.

Other things:

- [x] test everything together (entire pytest suite should pass when using the new `config_local.json` - must set `force_local=True` in `ARAX_expander.py` to avoid using the old KG2 API)
- [ ] update the test triples that go in some NCATS repo @finnagin

**Comment by amykglen** [comment]
does anyone object to me deleting these directories on arax.ncats.io, to free up space? (2.5.2 is quite an outdated KG2 version)
```
/data/orangeboard/databases/KG2.5.2
/data/orangeboard/databases/KG2.5.2_test
```

**Comment by finnagin** [comment]
No objections here @amykglen

**Comment by amykglen** [comment]
`pytest -v` is passing in `master` using KG2.6.7.1 without any code changes! and slow tests seem to be passing too, except one or two that I think were already failing, and one that I tweaked (some of these have become _ultra_-slow/large, so I haven't run _all_ of the slow tests... as a separate issue sometime soon I think owners of the various pytest files should speed up or eliminate their ultra-slow tests.. a max of 5 minutes for a single test would be a big improvement!)

so all that really remains is updating COHD and refreshing DTD, although it seems like doing so isn't super critical since tests are already passing...

so I think we can flip the switch at any point. since no code changes were needed to get the pytest suite passing, all that really needs to happen is for me to put the new config file on `araxconfig.rtx.ai`.

**Comment by edeutsch** [comment]
Sounds good to me. Shall we do it sometime Monday morning? My schedule is pretty free.

**Comment by amykglen** [comment]
sure! works for me. I'm also open.
