### ISSUE TITLE
When is a hundred not enough?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1588]
Our default limit for query_graph initiated queries is 100 results. We do want to limit it because huge results can be detrimental to the web browser experience. Although Luis has optimized the UI sufficiently that this is now less of an issue.

I'm thinking it would be a good idea to increase the 100 limit to 300 or 500.

What do yinz think?

**Comment by dkoslicki** [comment]
I say go for it as well!

**Comment by amykglen** [comment]
agreed - did a little testing and indeed the UI seems to handle 300 and 500 results fine..

**Comment by edeutsch** [comment]
okay, I will up the ante to 500 and we'll see how it goes!

**Comment by edeutsch** [comment]
New limit is 500. Seems all good on production.
