### ISSUE TITLE
Overlay FET errors relating to negative values

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1590]
this query seems to produce a bunch of errors during the FET step (on production): 
```
add_qnode(ids=DOID:14330, key=n0, categories=biolink:ChemicalSubstance)
add_qnode(categories=biolink:Gene, key=n1)
add_qedge(subject=n0, object=n1, key=e0, predicates=biolink:related_to)
expand()
overlay(action=fisher_exact_test, virtual_relation_label=N1, subject_qnode_key=n0, object_qnode_key=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```
<img width="1250" alt="Screen Shot 2021-07-26 at 7 42 55 PM" src="https://user-images.githubusercontent.com/49423686/127086832-4a535c5e-8c5a-4716-abbc-1765fd050705.png">

**Comment by amykglen** [comment]
realized I had the wrong category set for qnode `n0`, but even with it corrected, still seeing one of the same errors:
```
add_qnode(ids=DOID:14330, key=n0, categories=biolink:Disease)
add_qnode(categories=biolink:Gene, key=n1)
add_qedge(subject=n0, object=n1, key=e0, predicates=biolink:related_to)
expand()
overlay(action=fisher_exact_test, virtual_relation_label=N1, subject_qnode_key=n0, object_qnode_key=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```
<img width="1275" alt="Screen Shot 2021-07-26 at 8 40 07 PM" src="https://user-images.githubusercontent.com/49423686/127091743-42c5a511-0cd9-4fdc-ab3e-0a867aeb1a79.png">

**Comment by chunyuma** [comment]
@amykglen, could you please try it again? I guess the reason might be due to the unmatched edge count from different kps. I've modified the code to skip these cases. Please let me if it works. Thanks!

**Comment by amykglen** [comment]
yes, it seems to run ok now after pulling from `master`. thanks!

**Comment by amykglen** [comment]
confirmed it looks good on production: https://arax.ncats.io/?r=17040
