### ISSUE TITLE
Make sure all overlay edges have proper provenance

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1592]
Similar to the update to ngd in issue #1585

**Comment by finnagin** [comment]
@edeutsch I wrote the id for `ICEES+` as `infores:icees` as per the X-InfoResourcesv3 sheet on [this document.](https://docs.google.com/spreadsheets/d/1Ma4U3aY16mJushsW74vf9mWVacFvf7FiTEdlVqaUi5g/edit#gid=1213175775)

Is this correct?

**Comment by edeutsch** [comment]
@finnagin I think the latest document is here:
https://docs.google.com/spreadsheets/d/1Ak1hRqlTLr1qa-7O0s5bqeTHukj9gSLQML1-lg6xIHM

and that seems to suggest it should be one of:
infores:icees-asthma
infores:icees-covid19
infores:icees-dili

Is one of those appropriate?

**Comment by finnagin** [comment]
I'm not sure. This is for overlay_exposures_data.py. I don't know enough about the ICEES data to know one way or the other.

@dkoslicki Do any of those look appropriate to you?

**Comment by amykglen** [comment]
just a note that it looks like ARAX's infores curie changed from `infores:arax-reasoner-ara` to `infores:arax` in the spreadsheet Eric linked - I just updated Expand for that, but it looks like Overlay may need to be adjusted too...

**Comment by finnagin** [comment]
Note to self: can get the info needed from expand to know which icees infores curie to use.
