### ISSUE TITLE
Upgrade to Biolink 2.1 (KG2.7.1) - due Aug. 11

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1593]
associated code changes should go in the `kg2integration` branch

first update NodeSynonymizer:

- [x] change SRI NodeNormalizer URL to Biolink 2.1 endpoint
- [x] specify `version=2.1.0` in Biolink Lookup tool URL
- [x] adjust NodeSynonymizer conflations
- [x] adjust any other mentions of ChemicalSubstance
- [x] try doing a synonymizer build

once we have what seems to be a good synonymizer:

- [x] update conflations hard-coded in KG2c build (`record_kg2c_meta_info.py`)
- [x] build a new KG2c (put it at http://kg2-7-1c.rtx.ai:7474/browser/) @acevedol
- [x] load it into plover (available at http://kg2-7-1cplover.rtx.ai:9990)

rebuild or edit and put copies in `/translator/data/orangeboard/databases/KG2.7.1` on arax.ncats.io:

- [x] configv2.json (should point to the new KG2c/plover)
        * note: saved this as `config_local.json`, since we want it to be used over `configv2.json` during testing
- [x] KG2c meta knowledge graph
- [x] NodeSynonymizer
- [x] KG2c sqlite
- [x] NGD database
- [x] COHD database @chunyuma
- [x] refreshed DTD @chunyuma
- [x] DTD model @chunyuma
- [ ] DTD database @chunyuma
- [x] 'slim' databases (used for Travis) @chunyuma / @finnagin

**note**: As databases are rebuilt, the new copy of `config_local.json` will need to be updated to point to their new paths.

update ARAX codebase:

- [x] make updates to the ARAX codebase:
    - [x] change usages of `biolink:ChemicalSubstance` to `biolink:ChemicalEntity` (lots of tests use this)
        - [x] Expand/Resultify @amykglen 
        - [x] CHP/DTD/COHD Expand @chunyuma 
        - [x] Overlay @finnagin ?
        - [x] Other?
    - [x] update Expand's hard-coded conflations
    - [x] specify version 2.1.0 in every place Expand grabs the Biolink model
- [x] test everything together (entire ARAX pytest suite should pass when using the new `config_local.json` - must locally set `force_local=True` in `ARAX_expander.py` to avoid using the old KG2 API)

other things:

- [x] update the test triples that go in some NCATS repo @finnagin
- [x] update Biolink version (2.1.0) and KG2 version (2.7.1) in openapi yaml @edeutsch ?
- [x] update SmartAPI registration for ARAX
- [x] after main roll-out is complete, rename `config_local.json` to `config_local.json_FROZEN_DO-NOT-EDIT-FURTHER` (any remaining edits to the config file, such as when the DTD build is complete, should be made directly to the master `configv2.json` on araxconfig.rtx.ai)

**Comment by amykglen** [comment]
well the synonymizer build appeared to go well - artifacts are uploaded to arax.ncats.io at `/data/orangeboard/databases/KG2.7.1/synonymizer`.

only 56 problems listed in `Problems.tsv` (down from 76 for KG2.6.7.1). 

going to do some spot-checking tomorrow to make sure things look ok.

**Comment by edeutsch** [comment]
terrific!

**Comment by amykglen** [comment]
things seem good in the synonymizer based on some spot-checking... although wondering about one thing - is it normal for the `SRI_normalizer_category` and other SRI fields here to be `null`?
```
python3 node_synonymizer.py --lookup CHEMBL.COMPOUND:CHEMBL112
```
```
...
    "id": {
      "SRI_normalizer_category": null,
      "SRI_normalizer_curie": null,
      "SRI_normalizer_name": null,
      "category": "biolink:SmallMolecule",
      "identifier": "CHEMBL.COMPOUND:CHEMBL112",
      "name": "ACETAMINOPHEN"
    },
...
```

**Comment by edeutsch** [comment]
It could happen if the concept is not known to the SRI Node Normalizer, but that is not the case here. Looks like a bug. What happens if you run this:
```
python3 sri_node_normalizer.py -c CHEMBL.COMPOUND:CHEMBL112
```
in the location where the SRI NN and NodeSyn was built?

**Comment by amykglen** [comment]
it returns this:
```
==========================================================
Native SRI Node Normalizer results:
{
  "CHEMBL.COMPOUND:CHEMBL112": {
    "equivalent_identifiers": [
      {
        "identifier": "PUBCHEM.COMPOUND:1983",
        "label": "Acetaminophen"
      },
      {
        "identifier": "CHEMBL.COMPOUND:CHEMBL112",
        "label": "ACETAMINOPHEN"
      },
      {
        "identifier": "UNII:362O9ITL9D",
        "label": "ACETAMINOPHEN"
      },
      {
        "identifier": "CHEBI:46195",
        "label": "paracetamol"
      },
      {
        "identifier": "DRUGBANK:DB00316"
      },
      {
        "identifier": "MESH:D000082",
        "label": "Acetaminophen"
      },
      {
        "identifier": "CAS:103-90-2"
      },
      {
        "identifier": "CAS:360769-21-7"
      },
      {
        "identifier": "DrugCentral:52",
        "label": "paracetamol"
      },
      {
        "identifier": "GTOPDB:5239",
        "label": "paracetamol"
      },
      {
        "identifier": "HMDB:HMDB0001859",
        "label": "Acetaminophen"
      },
      {
        "identifier": "KEGG.COMPOUND:C06804",
        "label": "Acetaminophen"
      },
      {
        "identifier": "INCHIKEY:RZVAJINKPMORJF-UHFFFAOYSA-N"
      }
    ],
    "id": {
      "identifier": "PUBCHEM.COMPOUND:1983",
      "label": "Acetaminophen"
    },
    "type": [
      "biolink:SmallMolecule",
      "biolink:MolecularEntity",
      "biolink:ChemicalEntity",
      "biolink:PhysicalEssence",
      "biolink:NamedThing",
      "biolink:Entity",
      "biolink:PhysicalEssenceOrOccurrent"
    ]
  }
}
==========================================================
Local more compact and useful formatting:
{
  "curie": "CHEMBL.COMPOUND:CHEMBL112",
  "equivalent_identifiers": [
    {
      "identifier": "PUBCHEM.COMPOUND:1983",
      "label": "Acetaminophen"
    },
    {
      "identifier": "CHEMBL.COMPOUND:CHEMBL112",
      "label": "ACETAMINOPHEN"
    },
    {
      "identifier": "UNII:362O9ITL9D",
      "label": "ACETAMINOPHEN"
    },
    {
      "identifier": "CHEBI:46195",
      "label": "paracetamol"
    },
    {
      "identifier": "DRUGBANK:DB00316"
    },
    {
      "identifier": "MESH:D000082",
      "label": "Acetaminophen"
    },
    {
      "identifier": "CAS:103-90-2"
    },
    {
      "identifier": "CAS:360769-21-7"
    },
    {
      "identifier": "DrugCentral:52",
      "label": "paracetamol"
    },
    {
      "identifier": "GTOPDB:5239",
      "label": "paracetamol"
    },
    {
      "identifier": "HMDB:HMDB0001859",
      "label": "Acetaminophen"
    },
    {
      "identifier": "KEGG.COMPOUND:C06804",
      "label": "Acetaminophen"
    },
    {
      "identifier": "INCHIKEY:RZVAJINKPMORJF-UHFFFAOYSA-N"
    }
  ],
  "equivalent_names": [
    "Acetaminophen",
    "ACETAMINOPHEN",
    "ACETAMINOPHEN",
    "paracetamol",
    "Acetaminophen",
    "paracetamol",
    "paracetamol",
    "Acetaminophen",
    "Acetaminophen"
  ],
  "preferred_curie": "PUBCHEM.COMPOUND:1983",
  "preferred_curie_name": "Acetaminophen",
  "status": "OK",
  "type": "biolink:SmallMolecule"
}
```

**Comment by edeutsch** [comment]
hmm, okay, definitely seems like a bug. do you use those fields for anything?

**Comment by amykglen** [comment]
no, I don't use them. so unless it's indicative of a larger issue, not a problem for the KG2c build.

**Comment by amykglen** [comment]
so I think we're at a point now where @chunyuma can start building COHD/DTD databases from KG2.7.1. all necessary files should be on arax.ncats.io at: `/data/orangeboard/databases/KG2.7.1`

I'm going to work next on loading KG2.7.1c into Plover (may require a little bit of tweaking to remove mixins from the `expanded_categories` property)

**Comment by edeutsch** [comment]
At the moment the category_manager skips biolink:Entity. But I think it is true that all mixins come after this in the list. So it would be an easy tweak to STOP processing at biolink:Entity. This would exclude biolink:Entity and mixins I think.

Do we want to do that?

**Comment by edeutsch** [comment]
ah, but now Chris has responded that we want mixins in there. From Slack:

Yes, I think we want to include mixins in ancestors / descendents.   One of the main reasons to have these mixins is to make querying easy by grouping similar concepts that are not direct ancestors in the model.  That relies on applying ancestor logic to mixins....

**Comment by chunyuma** [comment]
Hi @finnagin, @dkoslicki and @jaredroach, 

To build the COHD database and DTD model/database for kg2.7.1c based on the Biolink Model 2.1, I plan to use the `biolink:Drug` and `biolink:SmallMolecule` to replace the original `bilink:Drug` , `biolink:ChemicalSubstance`  and `biolink:Metabolite`  used in kg2.6.7.1 as drug. Based on this, I simply compared the total number of `drug` nodes in kg2.7.1 (which is `2039306`) and the total number of `drug` nodes used in kg2.6.7.1 (which is `2010011 `). Using only those two classes even have more `drug` nodes. So any objection for only treating `biolink:Drug` and `biolink:SmallMolecule as `drug` for COHD and DTD?

**Comment by amykglen** [comment]
well surprisingly it worked to just load KG2c into Plover as is! (with mixins included as labels.) it did increase baseline memory usage by a decent amount, but not enough for it to cause a problem I think.

**Comment by edeutsch** [comment]
Terrific! It looks like @chunyuma has several to dos in the list, but otherwise, do we just sit tight until you're back and then make the switch?

**Comment by chunyuma** [comment]
I've already started building COHD and DTD now. Both of them should be able to complete next week except for DTD probability precomputed database which might need more time.

**Comment by amykglen** [comment]
yeah, I think that sounds fine to wait to roll it out until I'm back - but in the meantime other codeowners could go in and fix any usages of `biolink:ChemicalSubstance` in their code/tests (in the `kg2integration` branch).  (I created a couple subtasks for this above.)

and if anyone wants to test their changes, they just need to:
1. download the `config_local.json` from `arax.ncats.io:/translator/data/orangeboard/databases/KG2.7.1/config_local.json` (put it into your local `RTX/code/` directory)
2. locally change [this line](https://github.com/RTXteam/RTX/blob/af4a77e97cb76094a88fce9ffa79e78f750440c7/code/ARAX/ARAXQuery/ARAX_expander.py#L62) in Expand to say `force_local = True`
3. run the pytest suite (from the `kg2integration` branch)

**Comment by amykglen** [comment]
ok, I'm back and catching up with things. 🙂  

it looks like everything is done on my end here - these are the remaining (fast) tests failing (in the `kg2integration` branch with `force_local` set to True):
```
=========================================================== short test summary info ===========================================================
FAILED test_ARAX_filter_kg.py::test_warnings - assert 0 == 20
FAILED test_ARAX_filter_kg.py::test_error - AssertionError: assert 'OK' == 'ERROR'
FAILED test_ARAX_filter_kg.py::test_default_std_dev - ValueError: zero-size array to reduction operation minimum which has no identity
FAILED test_ARAX_filter_kg.py::test_std_dev - assert 0 > 0
FAILED test_ARAX_filter_kg.py::test_default_top_n - assert 0 == 50
FAILED test_ARAX_filter_results.py::test_n_results - assert 0 == 20
FAILED test_ARAX_filter_results.py::test_prune - AssertionError: assert 0 < 0
FAILED test_ARAX_filter_results.py::test_warning - assert 0 == 20
FAILED test_ARAX_filter_results.py::test_sort - assert 0 == 20
FAILED test_ARAX_overlay.py::test_jaccard - AssertionError: assert 'biolink:has_jaccard_index_with' in Counter()
FAILED test_ARAX_overlay.py::test_add_node_pmids - assert 0 > 0
FAILED test_ARAX_overlay.py::test_compute_ngd_virtual - AssertionError: assert 'biolink:has_normalized_google_distance_with' in Counter()
FAILED test_ARAX_overlay.py::test_compute_ngd_attribute - assert 0 > 0
FAILED test_ARAX_overlay.py::test_FET_ex1 - AssertionError: assert 'biolink:has_fisher_exact_test_p_value_with' in Counter()
```
think these are mostly for @finnagin?

and for @chunyuma, how are database rebuilds going? I see you checked off the COHD rebuild as done, but I don't see it pointed to in the `config_local.json`.

**Comment by amykglen** [comment]
ok got it, no worries! thanks for the update. are you having issues doing the refreshed DTD, or only the full rebuild?

**Comment by chunyuma** [comment]
Ah, yes, I think I can I can do the refreshed DTD first. It should be done tomorrow.

**Comment by amykglen** [comment]
ok, great. I think the refreshed DTD should be enough to roll out KG2.7.1, which hopefully we can do tomorrow during the team mini-hackathon.

**Comment by finnagin** [comment]
Looks like all of the fast tests pass now but some slow tests are still failing. Though it looks like those are all cohd and dtd tests so they will probably pass after the database refresh.

**Comment by amykglen** [comment]
awesome! hmm, looks like the slow COHD tests are still having issues even when the new COHD 2.7.1 database is used. @chunyuma - can you take a look and fix them when you have a chance? (note that this is all in the `kg2integration` branch)
```
FAILED test_ARAX_expand.py::test_cohd_expand_all - AssertionError: assert (False or False or False)
FAILED test_ARAX_expand.py::test_cohd_expand_paired_concept_freq - AssertionError: assert (False or False or False)
FAILED test_ARAX_expand.py::test_cohd_expand_observed_expected_ratio - AssertionError: assert (False or False or False)
```

**Comment by chunyuma** [comment]
ok, I've refreshed dtd and uploaded to arax.ncats.io and updated the config_loca.json file. I will build the slim version tonight.

As for changing `biolink:ChemicalSubstance` to `biolink:ChemicalEntity`, should I change it to `biolink:ChemicalEntity` or `biolink:SmallMolecule`? I used `biolink:SmallMolecule` to replace `biolink:ChemicalEntity` for dtd/chod database build as I said [here](https://github.com/RTXteam/RTX/issues/1593#issuecomment-893022091). So if we need to use `biolink:ChemicalEntity` instead of `biolink:SmallMolecule`, I'm afraid we have to redo everything.

**Comment by chunyuma** [comment]
Should we change all `add_qnode(categories=biolink:Chemicalsubstance` to `add_qnode(categories=biolink:SmallMolecule)` in test query? I think we have to determine this before we can build a slim version of dtd/cohd databases.

**Comment by amykglen** [comment]
we decided a couple meetings ago that `add_qnode(categories=biolink:ChemicalSubstance)` should generally be replaced with `add_qnode(categories=biolink:ChemicalEntity)`.

as for what you think works best for building COHD/DTD, I think that can probably be handled separately from how we update our test queries? I was assuming that which KG2 nodes you choose to include in your DTD build is kind of a separate matter. i.e., if you chose to only include SmallMolecules and Drugs from KG2 when you built DTD, queries for `ChemicalEntity` will still produce results from DTD, since `ChemicalEntity` is a parent of those. but I don't know enough about the DTD/COHD components to really say.

**Comment by chunyuma** [comment]
ah, I see, thanks @amykglen. If the `expand` will consider all children of `ChemicalEntity` as `ChemicalEntity`, then perhaps it might work because within the code of chp/dtd/chod queriers, it will check the category of the node. So if all children of `ChemicalEntity ` will keep its original category, I think it should still work for `add_qnode(categories=biolink:ChemicalEntity)`

**Comment by chunyuma** [comment]
Hi @edeutsch and @amykglen, do we have some synonymizer functions or utility functions that can return all children of a category in kg2.7.1? Thanks!

**Comment by amykglen** [comment]
I just messaged Chunyu about this in slack but posting here as well so others are aware it was addressed: the `CategoryManager` may work to find category ancestors (see [this function](https://github.com/RTXteam/RTX/blob/master/code/ARAX/NodeSynonymizer/category_manager.py#L106)) or the Biolink Lookup Service could be used to find category descendants (`curl -X GET "https://bl-lookup-sri.renci.org/bl/ChemicalEntity/descendants?version=2.1.0" -H  "accept: application/json"` - although you may want to cache answers in this case).

**Comment by finnagin** [comment]
Do we want to try to implement a local way of getting descendents? I'm asking because we currently we cannot run the DTD tests on Travis because of it's lack of a cache for when it hits the SRI and I'm worried having SRI calls for cohd too might make those tests impossible to run as well.

**Comment by amykglen** [comment]
actually, I just remembered I already have a local method for category descendants in the `KPSelector`, so you could use that if you want, @chunyuma. you could create a `KPSelector` object and call this method:
https://github.com/RTXteam/RTX/blob/8c95253a3a9681cb1cc3975c27c909dfe35b68f3/code/ARAX/ARAXQuery/Expand/kp_selector.py#L300

**Comment by chunyuma** [comment]
@amykglen, I met a similar problem like you got when I tested `test_chp_expand_1 `:

```
Traceback (most recent call last):
  File "/home/cqm5886/anaconda3/envs/RTX_env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/cqm5886/anaconda3/envs/RTX_env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/cqm5886/anaconda3/envs/RTX_env/lib/python3.7/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/cqm5886/anaconda3/envs/RTX_env/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/cqm5886/anaconda3/envs/RTX_env/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/cqm5886/anaconda3/envs/RTX_env/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/cqm5886/anaconda3/envs/RTX_env/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/cqm5886/anaconda3/envs/RTX_env/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/cqm5886/anaconda3/envs/RTX_env/lib/python3.7/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/home/cqm5886/anaconda3/envs/RTX_env/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc6259aac90>: Failed to establish a new connection: [Errno 110] Connection timed out
```

I think the problem might come from chp team's server. Right now, when I called their APIs, I met `Connection timed out` by running `r = requests.get('http://chp.thayer.dartmouth.edu/predicates/')`.

**Comment by chunyuma** [comment]
Hi @yakaboskic, could you please help us take a look if there is something wrong with CHP APIs? Currently, we can't call the `chp` server by using `r = requests.get('http://chp.thayer.dartmouth.edu/predicates/')`. Thanks!

**Comment by yakaboskic** [comment]
Hi @chunyuma, so I am currently working on a server rebuild right now, but should be back up tonight. However, we have depreciated the predicates endpoint.

**Comment by chunyuma** [comment]
Thanks for reply @yakaboskic. Please let us know when it is back. Thanks again!

**Comment by finnagin** [comment]
I've created [a pull request](https://github.com/NCATSTranslator/testing/pull/100) for the new predicate tuples in the NCATS testing repo. @dkoslicki when you get a chance could you approve and merge it?

**Comment by yakaboskic** [comment]
Hi @chunyuma, CHP server is back up as of around 12AM EST last night.

**Comment by chunyuma** [comment]
Thanks @yakaboskic!

**Comment by chunyuma** [comment]
Hi @yakaboskic, I tried calling the CHP APIs via `r = requests.post('http://chp.thayer.dartmouth.edu/query/', json=query)` for the following query:

```
{'message': {'query_graph': {'nodes': {'n0': {'ids': ['MONDO:0007254'],
     'categories': ['biolink:Disease'],
     'constraints': []},
    'n1': {'ids': ['ENSEMBL:ENSG00000162419'],
     'categories': ['biolink:Gene'],
     'constraints': []},
    'n2': {'ids': ['CHEMBL.COMPOUND:CHEMBL88'],
     'categories': ['biolink:Drug'],
     'constraints': []},
    'n3': {'ids': ['EFO:0000714'],
     'categories': ['biolink:PhenotypicFeature'],
     'constraints': []}},
   'edges': {'e0': {'predicates': ['biolink:gene_associated_with_condition'],
     'relation': None,
     'subject': 'n1',
     'object': 'n0',
     'constraints': []},
    'e1': {'predicates': ['biolink:treats'],
     'relation': None,
     'subject': 'n2',
     'object': 'n0',
     'constraints': []},
    'e2': {'predicates': ['biolink:has_phenotype'],
     'relation': None,
     'subject': 'n0',
     'object': 'n3',
     'constraints': [{'name': 'survival_time',
       'id': 'EFO:0000714',
       'operator': '>',
       'value': 500.0,
       'unit_id': None,
       'unit_name': None,
       'not': False}]}}},
  'knowledge_graph': {'nodes': {}, 'edges': {}},
  'results': []},
 'max_results': 10,
 'trapi_version': '1.1',
 'biolink_version': None}
```

But I got a warning message saying `'Passed category for n2: biolink:Drug, did not match our preferred category biolink:ChemicalSubstance for this curie. Going with our preferred category.'` and the returned status is `Bad request. See description.` with description `Problem during interface setup. No CHP core supported queries where found in passed query.` Could you please help me see how to solve this issue? I think `CHEMBL.COMPOUND:CHEMBL88` belongs to `biolink:SmallMolecule` based on biolink model 2.1 so it should be assigned to the `drug`, right?

I generated the standard query by using the following function:
```
    def _build_standard_query(
            gene=None,
            drug=None,
            outcome=None,
            outcome_name=None,
            outcome_op=None,
            outcome_value=None,
            disease=None,
            trapi_version='1.1',
            ):

        query = "{'message': {'query_graph': {'nodes': {'n0': {'ids': ['" + disease + "'], 'categories': ['biolink:Disease'], 'constraints': []}, 'n1': {'ids': ['" + gene + "'], 'categories': ['biolink:Gene'], 'constraints': []}, 'n2': {'ids': ['" + drug + "'], 'categories': ['biolink:Drug'], 'constraints': []}, 'n3': {'ids': ['" + outcome + "'], 'categories': ['biolink:PhenotypicFeature'], 'constraints': []}}, 'edges': {'e0': {'predicates': ['biolink:gene_associated_with_condition'], 'relation': None, 'subject': 'n1', 'object': 'n0', 'constraints': []}, 'e1': {'predicates': ['biolink:treats'], 'relation': None, 'subject': 'n2', 'object': 'n0', 'constraints': []}, 'e2': {'predicates': ['biolink:has_phenotype'], 'relation': None, 'subject': 'n0', 'object': 'n3', 'constraints': [{'name': '" + outcome_name + "', 'id': '" + outcome + "', 'operator': '" + outcome_op + "', 'value': " + str(outcome_value) + ", 'unit_id': None, 'unit_name': None, 'not': False}]}}}, 'knowledge_graph': {'nodes': {}, 'edges': {}}, 'results': []}, 'max_results': 10, 'trapi_version': '" + trapi_version + "', 'biolink_version': None}"

        return eval(query)
```

**Comment by yakaboskic** [comment]
Hi @chunyuma! Oh no! So... we actually turned off support for our weird muli-hop query structure and have transitioned everyone (we thought) to a fully one hop query structure in order to hopefully help teams better integrate with us. I am sorry that this was not communicated!!

So in light of that function you used to build those standard queries, I have made an equivalent python script to build equivalent one hop queries that will answer the same question as above. 

Basically the change is that we have Gene to Disease, Drug to Disease, Gene to Drug, Drug to Gene, and Gene to Gene edges, and you can specify what we call a predicate proxy (EFO for survival) and predicate context (i.e. more gene or drug curies). Here is the equivalent build script and I have checked and it works. Here is the code below (and also attached as a txt file, can't upload python here).
[chp_onehop_simple_build_script.py.txt](https://github.com/RTXteam/RTX/files/6979678/chp_onehop_simple_build_script.py.txt)

Please let me know if you have any questions/concerns/issues! **And many apologies for any unexpected work this may have caused!**
```
import requests
import json

def _build_standard_query(
        gene=None,
        drug=None,
        outcome=None,
        outcome_name=None,
        outcome_op=None,
        outcome_value=None,
        disease=None,
        trapi_version='1.1',
        ):

    """Two options, both are equivalent in terms of CHP analysis.
    """
    # Option 1
    query_1 = {
            'message': { 
                'query_graph': {
                    'nodes': {
                        'n0': {
                            'ids': [gene], 
                            'categories': ['biolink:Gene'],
                            'constraints': []}, 
                        'n1': {
                            'ids': [disease],
                            'categories': ['biolink:Disease'],
                            'constraints': []
                            },
                        }, 
                    'edges': {
                        'e0': {
                            'predicates': ['biolink:gene_associated_with_condition'],
                            'relation': None,
                            'subject': 'n0',
                            'object': 'n1',
                            "constraints": [
                                {
                                    "id": "CHP:PredicateProxy",
                                    "not": False,
                                    "name": "predicate_proxy",
                                    "value": [
                                        outcome
                                    ],
                                    "unit_id": None,
                                    "operator": "==",
                                    "unit_name": None
                                    },
                                {
                                    "id": outcome,
                                    "not": False,
                                    "name": outcome_name,
                                    "value": outcome_value,
                                    "unit_id": None,
                                    "operator": outcome_op,
                                    "unit_name": None
                                    },
                                {
                                    "id": "CHP:PredicateContext",
                                    "not": False,
                                    "name": "predicate_context",
                                    "value": [
                                        "drug"
                                    ],
                                    "unit_id": None,
                                    "operator": "==",
                                    "unit_name": None
                                    },
                                {
                                    "id": "drug",
                                    "not": False,
                                    "name": "drug",
                                    "value": [
                                        drug
                                    ],
                                    "unit_id": None,
                                    "operator": "matches",
                                    "unit_name": None
                                    }
                                ]     
                            }
                        },
                    },
                'knowledge_graph': {
                    'nodes': {},
                    'edges': {}
                    }, 
                'results': []
                }, 
                'max_results': 10, 
                'trapi_version': trapi_version, 
                'biolink_version': None
                }

    # Option 2
    query_2 = {
            'message': { 
                'query_graph': {
                    'nodes': {
                        'n0': {
                            'ids': [drug], 
                            'categories': ['biolink:SmallMolecule'],
                            'constraints': []
                            }, 
                        'n1': {
                            'ids': [disease],
                            'categories': ['biolink:Disease'],
                            'constraints': []
                            },
                        },
                    'edges': {
                        'e0': {
                            'predicates': ['biolink:treats'],
                            'relation': None,
                            'subject': 'n0',
                            'object': 'n1',
                            "constraints": [
                                {
                                    "id": "CHP:PredicateProxy",
                                    "not": False,
                                    "name": "predicate_proxy",
                                    "value": [
                                        outcome
                                    ],
                                    "unit_id": None,
                                    "operator": "==",
                                    "unit_name": None
                                    },
                                {
                                    "id": outcome,
                                    "not": False,
                                    "name": outcome_name,
                                    "value": outcome_value,
                                    "unit_id": None,
                                    "operator": outcome_op,
                                    "unit_name": None
                                    },
                                {
                                    "id": "CHP:PredicateContext",
                                    "not": False,
                                    "name": "predicate_context",
                                    "value": [
                                        "gene"
                                    ],
                                    "unit_id": None,
                                    "operator": "==",
                                    "unit_name": None
                                    },
                                {
                                    "id": "gene",
                                    "not": False,
                                    "name": "gene",
                                    "value": [
                                        gene
                                    ],
                                    "unit_id": None,
                                    "operator": "matches",
                                    "unit_name": None
                                    }
                                ]     
                            }
                        },
                    },
                'knowledge_graph': {
                    'nodes': {},
                    'edges': {}
                    }, 
                'results': []
                }, 
                'max_results': 10, 
                'trapi_version': trapi_version, 
                'biolink_version': None
                }
        
    r1 = requests.post('http://chp.thayer.dartmouth.edu/query/', json=query_1)
    r2 = requests.post('http://chp.thayer.dartmouth.edu/query/', json=query_2)
    return r1, r2

if __name__ == '__main__':
    r1, r2 = _build_standard_query(
            gene='ENSEMBL:ENSG00000162419',
            drug='CHEMBL.COMPOUND:CHEMBL88',
            outcome='EFO:0000714',
            outcome_name='EFO:0000714',
            outcome_op=">",
            outcome_value=500,
            disease='MONDO:0007254',
            trapi_version='1.1',
            )
    print(json.dumps(r1.json(), indent=2))
    print(json.dumps(r2.json(), indent=2))
```

**Comment by chunyuma** [comment]
Thanks @yakaboskic! I really appreciate your help for figuring out the issue! I will have a try later today based on your code and suggestions.

**Comment by chunyuma** [comment]
@amykglen, thanks to the help of @yakaboskic, both `chp` tests in `test_ARAX_expand.py` pass now.

```
test_ARAX_expand.py::test_chp_expand_1 PASSED                                                                                                        [ 50%]
test_ARAX_expand.py::test_chp_expand_2 PASSED                                                                                                        [100%]
```

**Comment by amykglen** [comment]
awesome, thanks everyone!

I guess after the full DTD rebuild is done you can go ahead and close this issue, @chunyuma.

**Comment by chunyuma** [comment]
Also, thanks @amykglen for developing the `biolinkHelper` module to access the biolink model information, I replaced the original CategoryManger with BiolinkHelper and it works well.

> I guess after the full DTD rebuild is done you can go ahead and close this issue, @chunyuma.
I will complete it as soon as possible.
