### ISSUE TITLE
Central place where 'production' Biolink version is stored/accessible

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1594]
this came up at today's team mini-hackathon: 

right now there are several places in the ARAX codebase that need to know the current 'production' Biolink Model version we're on (e.g., when the synonymizer and Expand send requests to the Biolink Model Lookup service, they need to specify the Biolink version in the request URL)

right now these are just hard-coded, scattered about. but it'd be nice if our current Biolink Model version number was stored in one central place, with an easy way to access it.

Eric mentioned that the Biolink version number has to be hard-coded in `openapi.yaml`. he suggested that maybe a `get_biolink_version()` method or the like could be added to `RTXConfiguration` that parses the version number out of there?

**Comment by edeutsch** [comment]
agreed.

This will also perhaps help us keep it up-to-date, which I suspect it is currently not?
This:
https://github.com/RTXteam/RTX/blob/86a1376533592a4f146c12673fe8118c8f58d067/code/UI/OpenAPI/python-flask-server/openapi_server/openapi/openapi.yaml#L17
says it is currently 1.7.0, which I think was true until our recent update to KG2.7.6.1?

Would someone confirm what it should be and I can update it? This gets propagated to Smart-API then.

**Comment by amykglen** [comment]
It should be 1.8.1 (KG2.6.7 was actually also 1.8.1, there was just some confusion and we thought it was 1.7.0 for a bit)

**Comment by edeutsch** [comment]
okay, all deployments updated to 1.8.1 and pushed to Smart-API
master is now rolled out to all deployments.

**Comment by amykglen** [comment]
this was addressed with the `BiolinkHelper` - you can access the current ARAX Biolink version (parsed from the openapi yaml) like so:
```
biolink_helper = BiolinkHelper()
biolink_helper.get_current_arax_biolink_version()
```
