### ISSUE TITLE
`Bind` operation not working

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1595]
With respect to the operations and workflow stuff, the following message errors out when sent to the [workflow runner](https://translator-workflow-runner.renci.org/docs), but not when sent to ARAX directly:
```
{
    "workflow": [
        {
            "id": "fill"
        },
        {
            "id": "bind"
        },
        {
            "id": "overlay_compute_ngd",
            "parameters": {
                "qnode_keys": [
                    "n0",
                    "n1"
                ],
                "virtual_relation_label": "NGD1"
            }
        },
        {
            "id": "complete_results"
        },
        {
            "id": "filter_results_top_n",
            "parameters": {
                "max_results": 50
            }
        }
    ],
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": [
                        "biolink:Gene"
                    ]
                },
                "n1": {
                    "ids": [
                        "CHEBI:45783"
                    ],
                    "categories": [
                        "biolink:ChemicalSubstance"
                    ]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": [
                        "biolink:related_to"
                    ]
                }
            }
        }
    }
}
```
Patrick W. looked at the logs on the WF runner, and here is his summary:
>Looks like we successfully make the first fill call to ARAX - it returns a 200 anyway. But something goes wrong when we then send the result back to ARAX with the bind operation. We get a 400 response saying “‘Node’ object has no attribute ‘qnode_keys’“.
The fill response that we get looks reasonable to me. As I recall, there is some extra metadata that ARAX uses internally to smooth out the transition from fill to bind. Is that being stripped out when it bounces to and from the workflow runner?
Or maybe there’s extra stuff. I’m not sure what the error message means exactly.

So it could be the `qnode_keys` being stripped out that is the issue. I don't know where exactly in the system these are required, so tagging a variety of people as it might be `resultify`, the query graph interpreter, the O/W translator, etc. Feel free to un-assign if you think it's not relevant.

**Comment by edeutsch** [comment]
I recall the discussion, but I have forgotten the outcome. I vaguely recall that we thought we would need a routine to recompute the qnode_keys when they are not present. Easy it many cases, but potentially becoming hard in some cases. I hope someone else remembers.

**Comment by amykglen** [comment]
yeah, I think the solution Eric's thinking of was implemented in issues  #1193 / #1462

basically resultify has a `recompute_qg_keys()` method, described [here](https://github.com/RTXteam/RTX/issues/1193#issuecomment-767896662), which needs to be run on external messages before ARAX can do its thing (all ARAX modules require `Node.qnode_keys` and `Edge.qedge_keys`)

**Comment by edeutsch** [comment]
ah excellent, thanks for finding it.

So should I run this method automatically when a message with knowledge graph with a non-zero numbers of edges in it arrives?

Or is is better if each ARAX component that needs qnode_keys/qedge_keys checks and runs the method if they're not there?

**Comment by amykglen** [comment]
I think automatically running it when there's a knowledge graph with any edges or nodes would make sense. I know at least Expand, Overlay, and Resultify require qnode/qedge_keys, so I think it'd make sense to just do it up front.

**Comment by amykglen** [comment]
was this issue addressed by using `recompute_qg_keys()`, or is there still a problem here?

**Comment by dkoslicki** [comment]
@amykglen I think this may still be an issue (given #1634). I can't verify since pasting in the above JSON gives an error of `An error was encountered while contacting the server (SyntaxError: Unexpected end of JSON input)`. Is this a UI issue @isbluis or @edeutsch?

**Comment by amykglen** [comment]
thanks, yeah, reviewing the comment history and #1634 I think it's that the `recompute_qg_keys()` method hasn't been plugged in yet as @edeutsch mentioned needing to do [here](https://github.com/RTXteam/RTX/issues/1595#issuecomment-888806377). I do think it makes sense to call it up front whenever a message has edges/nodes in it, though not sure where exactly that should happen in the code (I'm assuming @edeutsch had a plan for that).

**Comment by dkoslicki** [comment]
Yeah, I think @edeutsch put that method in [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_messenger.py#L753) just before results are returned, but I think it should also be done before trying to do anything else (like in this case where just an overlay NGD is asked for).

**Comment by edeutsch** [comment]
okay, sorry, looks like I dropped this ball. I will add this in when I return from the trip.

**Comment by edeutsch** [comment]
This appears to work now:
https://arax.ncats.io/?source=ARS&id=9f288363-afc3-49f9-9893-611a8c023053

closing. Please let me know if there's still any issue and we can reopen.
