### ISSUE TITLE
Question from CHP

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1597]
I received this question from Gregory Hyde. I don't know how to response. Does anyone know the answers here?

Gregory Hyde  9:39 AM
Hi Eric. I just wanted to inform you that our KP has added a new edge for gene->gene relationships, since we know this was limited to some degree from the consortium. This is of course inferenced over clinical data rather than curated from a database. I think ARAs are scraping off of the meta_knowledge_graph to find what teams can answer what so I've included this information in there: http://chp.thayer.dartmouth.edu/meta_knowledge_graph/. As a side note I'm not sure that Expander agent has been returning our responses since our last update? Its possible this is entirely on our end, though we seem to return from the ARS directly. I know mark had updated our endpoint link a couple weeks ago and this may potentially be why? Not sure if theres anything you see on your end for something like that. For example: https://arax.ncats.io/?source=ARS&id=84786df1-d417-482b-a6fd-ad16beec7a94 we return answers directly but I'm no longer seeing our responses in aragorn, arax or explanatory agent.

**Comment by edeutsch** [comment]
Greg followed up:

Gregory Hyde  10:21 AM
Hi Eric. Chris was able to help me out on as to why CHP was not getting hit in ranking agent queries. They updated their KP Registry and on our smartapi registry we have our server link as http://chp.thayer.dartmouth.edu/ to which they would concatenate /meta_knowledge_graph leading to http://chp.thayer.dartmouth.edu//meta_knowledge_graph which 404s. I'm not sure if this might also be our issue with Expander Agent depending on how you guys scrape the meta_knowledge_graph information. Regardless we truncated the trailing forward slash from our server link.

**Comment by dkoslicki** [comment]
@chunyuma 
I see two issues with this:
1. For the ARS link above, I think the CHP results are just so far down they are cutoff by taking the top 500 (no need to address this issue).
2. When querying CHP directly as in: https://arax.ncats.io/?r=17550, the provenance appears to be incorrect:

<html>
<body>


attribute_type_id: | biolink:knowledge_source
-- | --
value_type_id: | biolink:InformationResource
attribute_source: | infores:arax
description: | ARAX inserted this attribute because the KP (CHP) did not seem to provide such an attribute (indicating that this edge came from them).
value: | infores:connections-hypothesis
 
attribute_type_id: | biolink:aggregator_knowledge_source
value_type_id: | biolink:InformationResource
attribute_source: | infores:arax
value: | infores:arax


</body>
</html>

The `attribute_source` under `biolink:knowledge_source` (not the `aggregator` one) should be `infores:connections-hypothesis` instead of `infores:arax`.

@edeutsch Did I get that right? The format of the attribute provenance is still a bit wonky to me.

**Comment by amykglen** [comment]
no, I think `attribute_source` should be `infores:arax` here - that property is meant to capture who actually created the attribute. in this case we did (since CHP didn't provide such an attribute themselves, as noted in the `description`).

**Comment by dkoslicki** [comment]
Ah, gotcha! In that case, there is not problem here. Everything appears to be in order. Ok to close?

**Comment by dkoslicki** [comment]
Running it in DSL (and not specifying the KP) does indeed result in CHP being queried: https://arax.ncats.io/?r=17554
```
<snip>
 2021-08-04T21:22:36.501219 INFO:    CHP: Query for edge e0 completed (e0: 29, n0: 1, n1: 29)
<snip
```
However, running the TRAPI JSON through gives:
`The KPs Expand decided to answer e01 with are: {'MolePro', 'BTE', 'WellnessKP', 'RTX-KG2'}`
So looks like `expand` isn't hitting CHP in that case. Any ideas why not @amykglen ?

The JSON is:
```
{
  "edges": {
    "e01": {
      "object": "n0",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n1"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:Gene"
      ],
      "ids": [
        "ENSEMBL:ENSG00000132155"
      ],
      "is_set": false
    },
    "n1": {
      "categories": [
        "biolink:Drug"
      ],
      "is_set": false
    }
  }
}
```

**Comment by amykglen** [comment]
hmm - ah! it looks like your JSON query has `n1` as the subject and `n0` as the object, while the DSL has `n0` as the subject and `n1` as the object. apparently CHP (according to their meta_knowledge_graph) can answer queries where a gene is the subject and drug is the object, but not vice versa.

you can see CHP is used (and produces answers) when you flip the subject/object:
```
{
  "edges": {
    "e01": {
      "object": "n1",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n0"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:Gene"
      ],
      "ids": [
        "ENSEMBL:ENSG00000132155"
      ],
      "is_set": false
    },
    "n1": {
      "categories": [
        "biolink:Drug"
      ],
      "is_set": false
    }
  }
```
https://arax.ncats.io/?r=17562

**Comment by amykglen** [comment]
I think it's that `CHPQuerier` isn't even being called with one direction because the main `ARAXExpander` code chooses not to use CHP in that case, since CHP doesn't say they can answer that kind of query in their `meta_knowledge_graph`.

**Comment by chunyuma** [comment]
Ah, I see, thanks @amykglen

**Comment by amykglen** [comment]
can we close this issue? think everything is resolved with CHP's meta KG

**Comment by chunyuma** [comment]
Yes, I think this issue should be resolved now. I will close it.
