### ISSUE TITLE
Workflow B answers - suggested tweak

### ISSUE THREAD

**Issue by karafecho** [RTXteam/RTX#1601]
ARAX was the only ARA to return results to [this query](https://github.com/NCATSTranslator/minihackathons/blob/karafecho-patch-2/2021-12_demo/workflowB/B.1c_DILI_three-hop-from-disease-or-phenotypic-feature_trapi.json), submitted through the ARS. 
PK = 934102e5-35e4-4c28-9fea-ca02daedafd7

I am super excited about this and pleased with the answers. That said, I think we can improve the output a bit by filtering or improving the ranking algorithm such that answers like '5' flanking region', 'exons', etc.

**Comment by karafecho** [comment]
![image](https://user-images.githubusercontent.com/26254388/128529412-1d6d0837-f790-4b32-9337-938f565637b9.png)

**Comment by dkoslicki** [comment]
@amykglen, @acevedol or other KG2 peeps (@saramsey) re-running this query, I get no results for edge e3 with KG2. Has something changed in prod since 2 weeks ago that results in no edges being found for this query?

**Comment by amykglen** [comment]
I think it's because `biolink:ChemicalSubstance` is no longer a valid node category now that we're on Biolink 2.1.

when I change the QG to this (use `biolink:ChemicalEntity` instead):
```
{
            "nodes": {
                "n0": {
                     "ids": ["MESH:D056487"],
                     "categories": ["biolink:DiseaseOrPhenotypicFeature"]
                },
                "n1": {
                    "categories": ["biolink:DiseaseOrPhenotypicFeature"]
                },
                "n2": {
                    "categories": ["biolink:Gene"]
                },
                "n3": {
                    "categories": ["biolink:ChemicalEntity"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:correlated_with"]
                },
                "e02": {
                    "subject": "n2",
                    "object": "n1",
                    "predicates": ["biolink:gene_associated_with_condition"]
                },
                "e03": {
                    "subject": "n2",
                    "object": "n3",
                    "predicates": ["biolink:related_to"]
                }
            }
        }
```
it produces results: https://arax.ncats.io/?r=19681

**Comment by dkoslicki** [comment]
Ah, thanks @amykglen !

**Comment by karafecho** [comment]
Thanks, folks!

**Comment by finnagin** [comment]
Closing since this is resolved
