### ISSUE TITLE
Workflow B - suggest tweak 2

### ISSUE THREAD

**Issue by karafecho** [RTXteam/RTX#1602]
This issue is related to #1601 and [this ARS query](https://github.com/NCATSTranslator/minihackathons/blob/karafecho-patch-2/2021-12_demo/workflowB/B.1c_DILI_three-hop-from-disease-or-phenotypic-feature_trapi.json). 
PK = 934102e5-35e4-4c28-9fea-ca02daedafd7

I suggest including an additional feature(s) to allow users to view not only a list of answers from the third hop, but also a list of answers from the first and second hops, perhaps as a direct chain, ie, node 1- node 2 - node 3.

**Comment by dkoslicki** [comment]
@karafecho You may be able to get the desired results by adding `is_set=true` for some/all of the intermediate nodes. Then the list of results would be categorized uniquely on the last node (the ChemicalSubstance) and for each ChemicalSubstance, you could see all genes or diseases that connect to it. I would give an example, but blocking on the absence of the 3rd edge in issue #1601

**Comment by karafecho** [comment]
Perfect! I'll give a try. Thanks, David.

**Comment by finnagin** [comment]
Closing since this looks resolved
