### ISSUE TITLE
Odd triple in edge from Translator Standup query 39

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1604]
See Result #8 (`carcinogenicity`) here:
https://arax.ncats.io/?r=17996

Original JSON here:
```
{
            "nodes": {
                "n0": {
                    "ids": [
                        "PUBCHEM.COMPOUND:241"
                    ],
                    "categories": [
                        "biolink:SmallMolecule"
                    ]
                },
                "n1": {
		             "categories":[
                         "biolink:DiseaseOrPhenotypicFeature"
                        ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates":["biolink:related_to"]

                }
            }
}

```

**Comment by saramsey** [comment]
For some reason, I cannot add a screen cap image to the comment thread here. Some kind of transient GitHub issue I guess?

**Comment by saramsey** [comment]
<img width="811" alt="add-to-rtx-issue-1604" src="https://user-images.githubusercontent.com/5562107/128897459-92f3cf3c-9e30-4a72-bf33-f03586283246.png">

**Comment by saramsey** [comment]
This report is from the standup meeting on Tuesday Aug. 10, 2021 at 0900 PDT. Link to the standup meetings results sheet is here:  
https://docs.google.com/spreadsheets/d/1Y2yfUFl2SIgv5KkyxdQB94UE3HtVdJNJ7KdnwQgZcYI/edit#gid=0&range=BS:BS

**Comment by finnagin** [comment]
@saramsey Is this issue okay to close?

**Comment by saramsey** [comment]
let me have a look at it

**Comment by saramsey** [comment]
We now have SemMedDB sentences and scores, so I am closing out this issue.
