### ISSUE TITLE
Determine the source of errors for the Dec Demo workflows

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1606]
As posted in the `general` channel on the Translator Slack, [this document](https://docs.google.com/spreadsheets/d/1O1cMmYGxoIqP6xbzj6FG5owiKQVg57wx2O_XIA_hN_A/edit) is tracking the progress on the workflow queries. ARAX has a fair number of errors and “no results.” Let’s see if we can triage these and make new issues so the appropriate team members can start addressing them.

Assigning many people just so more people are aware of this. I don’t expect each error to be relevant to everyone, but there’s a possibility that at least one is.

**Comment by saramsey** [comment]
Thank you @dkoslicki. I wonder if this could be a good mini-hackathon topic.

**Comment by finnagin** [comment]
Closing since the demo is over
