### ISSUE TITLE
Refresh the NodeNamesDescriptions.tsv for the synonyms autocomplete

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1608]
It looks like the autocomplete build relies on a file that is no longer exists, see [here](https://github.com/RTXteam/RTX/blob/master/code/autocomplete/create_load_db.py#L28). The [data folder](https://github.com/RTXteam/RTX/tree/master/data) hasn't been updated in a while as well.

Perhaps we can connect this up with KG2 so that whenever a new build is created, the autocomplete database is updated?

**Comment by finnagin** [comment]
This got done as part of #1614 so I'm adding the needs testing on production tag.

**Comment by amykglen** [comment]
@finnagin can we close this issue? the autocomplete database is regenerated automatically during KG2c builds now - everything seemed to work fine for the KG2.7.3 build.

**Comment by finnagin** [comment]
Sure!
