### ISSUE TITLE
COHD predicates

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1610]
I don't know if there is already an issue here in the repo, I couldn't find it, but there is an issue that has been around for a while and came up again in the Translator mini-hackathon this morning:

https://togithub.com/NCATSTranslator/minihackathons/issues/165

It looks to me that Kara committed a change to make a COHD predicate now biolink:has_real_world_evidence_of_association_with
https://togithub.com/NCATSTranslator/minihackathons/pull/189/files

So I think the right strategy is for us to start using biolink:has_real_world_evidence_of_association_with
But I am uncertain.
Can we do that?
Comments welcome.

**Comment by saramsey** [comment]
Thanks for the heads-up, I did not know about this predicate.

**Comment by dkoslicki** [comment]
@saramsey it's a brand new predicate from https://togithub.com/NCATSTranslator/minihackathons/issues/47

**Comment by edeutsch** [comment]
I am being asked for updates on this topic. Does anyone know what the status of this issue is?

https://togithub.com/NCATSTranslator/minihackathons/issues/165

What shall I say?

**Comment by amykglen** [comment]
verified this seems to be working on production: https://arax.ncats.io/?r=23658

good to close?

**Comment by dkoslicki** [comment]
Looks good to me!
