### ISSUE TITLE
PLACEHOLDER:placeholder

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1612]
This issue:
https://togithub.com/NCATSTranslator/minihackathons/issues/173#issuecomment-897840771

reminds me that we still have these PLACEHOLDER:placeholder values, which are a bit unsightly.
Perhaps we can change these to EDAM:data_1187 or something like that?

**Comment by dkoslicki** [comment]
I like the idea of that identifier. For others curious, [here](https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fdata_1187) is the description of that EDAM CURIE. Adding @finnagin as this might be a simple NGD change

**Comment by edeutsch** [comment]
As a good repro, there are a whole bunch of biolink:Unknown and PLACEHOLDER:placeholder entries that are visible here:
https://arax.ncats.io/?r=19693
(e.g. in the first result, first node, lots of these)
We should put our heads together and come up with some elegant for all these values or request what we don't find.

**Comment by amykglen** [comment]
ok, changes from the mini-hackathon are pushed!

you can use the Decorator to create NGD's publications attribute like so, @finnagin:
```
pmid_list = ["PMID:1", "PMID:2"]
decorator = ARAXDecorator()
attribute = decorator.create_attribute("publications", pmid_list)
```

**Comment by edeutsch** [comment]
deployed to production

**Comment by amykglen** [comment]
will keep this issue open until another rollout of `master` happens and we can confirm all the 'foo's are gone

**Comment by amykglen** [comment]
the `foo`s are indeed all gone from production now!

good to close this, @edeutsch?

**Comment by edeutsch** [comment]
yes, many thanks!
