### ISSUE TITLE
TRAPI 1.2 migration

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1613]
We need to migrate KG2 and then ARAX to TRAPI 1.2. Copying agenda notes to an issue to track progress and problems.

Development release schedule.
Wed Aug 4: TRAPI 1.2-beta declared complete and implementations begin. Fixes possible
Wed Aug 18 KPs have completed v1.2 implementations and registered in SmartAPI
Wed Sep 1 ARAs have completed v1.2 implementations and registered in SmartAPI
Wed Sep 1 TRAPI 1.2 is merged into master, tagged, and released
Wed Sep 15 ARS has completed v1.2 implementation and v1.2 is fully production
Wed Sep 15 All TRAPI 1.1 endpoints are turned off/no longer available

ChangeLog for TRAPI 1.2
https://github.com/NCATSTranslator/ReasonerAPI/blob/v1.2/ChangeLog.md 

Autogen schema docs for TRAPI 1.2
https://github.com/NCATSTranslator/ReasonerAPI/blob/v1.2/docs/reference.md 

TRAPI 1.1 -> 1.2 diffs are here:
https://github.com/NCATSTranslator/ReasonerAPI/pull/277/files 

All teams to signal commencement of implementation here:
https://docs.google.com/spreadsheets/d/1LEV3FyXBt3xm4bC5TQkVbrZalrr6OV2LnPtuLj1RVB4

**Comment by edeutsch** [comment]
Summary of Change log: https://github.com/NCATSTranslator/ReasonerAPI/blob/v1.2/ChangeLog.md 
/predicates endpoint is REMOVED https://github.com/NCATSTranslator/ReasonerAPI/pull/261/files

Removed all 'relation' properties in Edge, QEdge, MetaEdge
TODO: This has implications for filter and Overlay operations. Switch to start using an attribute instead of relation property

/meta_knowledge_graph allows optional attributes[] property (encouraged but not required) https://github.com/NCATSTranslator/ReasonerAPI/pull/259/files

Add support for workflow and operations v1.0.0 (encouraged but not yet required) https://github.com/NCATSTranslator/ReasonerAPI/pull/262/files

/asyncquery endpoint added (recommended but not required) https://github.com/NCATSTranslator/ReasonerAPI/pull/255/files https://github.com/NCATSTranslator/ReasonerAPI/pull/263/files

Add result.score (highly encouraged but not required) https://github.com/NCATSTranslator/ReasonerAPI/pull/247/files

/meta_knowledge_graph should only include specific relationships, not ancestor-inferred relationships (policy clarification)

Add one level of subattributes to Attribute https://github.com/NCATSTranslator/ReasonerAPI/pull/268/files

Add attributes[] to EdgeBinding to complement Edge and Node https://github.com/NCATSTranslator/ReasonerAPI/pull/269/files

**Comment by finnagin** [comment]
Closing as ARAx and KG2 are on TRAPI 1.2 everywhere
