### ISSUE TITLE
KG2 API complains about '_not' for query with constraint sent from ARAX

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1616]
when running this query on ARAX (production):
```
{
  "nodes":{
    "n0":{
      "categories":[
        "biolink:SmallMolecule"
      ],
      "constraints":[
        {
          "id":"biolink:highest_FDA_approval_status",
          "name":"highest FDA approval status",
          "operator":"==",
          "value":"regular approval"
        }
      ]
    },
    "n1":{
      "ids":[
        "NCBIGene:1956"
      ]
    }
  },
  "edges":{
    "e0":{
      "subject":"n0",
      "object":"n1",
      "predicates":[
        "biolink:decreases_abundance_of",
        "biolink:decreases_activity_of",
        "biolink:decreases_expression_of",
        "biolink:decreases_synthesis_of",
        "biolink:increases_degradation_of",
        "biolink:disrupts",
        "biolink:entity_negatively_regulates_entity"
      ]
    }
  }
}
```
the KG2 API returns a strange error:
```
 2021-08-17T04:11:36.099551 WARNING:    RTX-KG2 API returned response of 400. Response from KP was: { "detail": "Additional properties are not allowed ('_not' was unexpected) - 'message.query_graph.nodes.n0.constraints.0'", "status": 400, "title": "Bad Request", "type": "about:blank" }
```
but when you send that exact query above _directly_ to the KG2 API, it happily answers it and produces 100-something results. 

I'm wondering if maybe something about loading the query graph into the object model in the ARAX code creates some `_not` property somewhere in the QG that is then transmitted along when ARAX forwards the QG to the KG2 API, and the KG2 API doesn't like that property?

wondering if @edeutsch might know what's going on with the `_not` property..

**Comment by edeutsch** [comment]
yeah, looking at the autogen code classes, it is stored as _not, probably because 'not' is a reserved word.
ugh.
We should have gone with 'negated'.
I suppose we might need some custom code in the serializer/deserializer.

**Comment by edeutsch** [comment]
ah, I may have a solution, hang on.

**Comment by edeutsch** [comment]
I just pushed to master a attempt to fix. Does that work?

**Comment by amykglen** [comment]
hmm - I'm actually not sure how to test without the code being rolled out to the KG2 API - this error can't happen with the `force_local` mechanism in Expand since it never actually sends a query to the KG2 API...

**Comment by edeutsch** [comment]
I just rolled out the code to /test. and I think that fixed it. Try there. I'll roll out everywhere because I think that fixed it.

**Comment by amykglen** [comment]
ohh, I see. so it was a change on the ARAX end, so I could've tested it from `master`, sorry.

yep, looking good now!

**Comment by amykglen** [comment]
confirmed it looks good on ARAX production now: https://arax.ncats.io/?r=18477

will close - thanks!

**Comment by edeutsch** [comment]
okay, rolled out to all deployments. 
Although it worked in test, I got a 503 from KG2 when testing on production
Trying /beta and that seemed to work
Trying production now works again. Dunno what the 503 was about.
But I think the issue is fixed.

and yes, the issue was with ARAX serializing the constraint.
