### ISSUE TITLE
Q4 #2 not working

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#162]
The second Q4 example: What proteins are in the phenylketonuria pathway?
is not working:
The most similar question I can answer is: What proteins are in the pathway $pathway But I was unable to fill the following parameters: ['pathway']

simple fix? or remove from list of example questions?

**Comment by dkoslicki** [comment]
Hmm... looks like the KG recently added nodes of phenylketonuria as both pathways and diseases. This may take a bit to fix

**Comment by jaredroach** [comment]
You can rephrase the question as 
"What genes predispose to phenylketonuria?"
and get a good answer.

fwiw, the following questions do not work
What proteins are related to phenylketonuria?
What proteins are in the pathway phenylketonuria?
What proteins are in the phenylketonuria pathway?

sort of interesting because, as I understand it, the official RTX stance is that genes and proteins are the same thing...

**Comment by edeutsch** [comment]
But your suggested question:
What genes predispose to phenylketonuria?
is mapped to Q14 by the NLP:
What diseases involve similar genes to phenylketonuria

which is not the intent of Q4 I don't think. Q4 really is supposed to be exploring a pathway. And I don't think phenylketonuria is a pathway.
so I think we're back to square 1 on Q4. We need to find a pathway that the translator can recognize as a pathway and assign to Q4 and the reasoner and answer the question.

Can you cypher for a recognizable pathway that fits the bill?

**Comment by jaredroach** [comment]
I am happy calling the phenylketonuria pathway a pathway. If you rank all the entities in the KG that are currently classified as pathways based on their path worthiness, phenylketonuria would be in the top 20%, if not the top 5%. Notably, it is a largely linear biochemical pathway. It is hard to have more a pathway quality than that.

**Comment by edeutsch** [comment]
hmm, okay, I am a bit mystified by pathways. I feel like I sort of understand KEGG pathways based on what I see here:
https://db.systemsbiology.net/sbeams/cgi/PeptideAtlas/showPathways
It seems reassuring that:
path:hsa00010    Glycolysis / Gluconeogenesis
is the first one! Number 2 seems familiar, too.

It seems like Reactome has two relevant things:
R-HSA-5173105   O-linked glycosylation
R-HSA-446203    Asparagine N-linked glycosylation

Why is KEGG and reactome so far apart?
I can't find anything resembling a phenylketonuria pathway in KEGG.

**Comment by dkoslicki** [comment]
Fixed due to progress on #170. Pathway correctly identified, results look reasonable to a mathematician. Closing (discussion of KEGG vs Reactome in a different issue?)
