### ISSUE TITLE
Uncaught error in ranker

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1621]
For this query:
```
add_qnode(ids=CHEMBL.COMPOUND:CHEMBL112, key=n0, categories=biolink:ChemicalEntity)
add_qnode(categories=biolink:DiseaseOrPhenotypicFeature, key=n1)
add_qedge(subject=n0, object=n1, key=e0)
expand()
overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n0, object_qnode_key=n1)
overlay(action=fisher_exact_test,subject_qnode_key=n0,virtual_relation_label=F1,object_qnode_key=n1)
overlay(action=overlay_clinical_info,COHD_method=paired_concept_frequency,virtual_relation_label=C1,subject_qnode_key=n0,object_qnode_key=n1)
overlay(action=predict_drug_treats_disease,virtual_relation_label=P1,subject_qnode_key=n0,object_qnode_key=n1,threshold=0.8,slow_mode=false)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```
I get the following error (thought the results are rendered in the UI, but without a response ID):
```
ERROR: [UncaughtARAXiError]    An uncaught error occurred: could not convert string to float: 'no value!': ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 585, in execute_processing_plan\n ranker.aggregate_scores_dmk(response)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_ranker.py", line 551, in aggregate_scores_dmk\n value = float(edge_attribute.value)\n', "ValueError: could not convert string to float: 'no value!'\n"]
```
Looks like an attribute is missing a `value`

**Comment by finnagin** [comment]
The attributes causing this error are the COHD attributes. This looks to be coming from [this line in the COHD querier.](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Expand/COHD_querier.py#L168) I'm guessing this is the default value to return if nothing is found. Should we change this behavior or leave "no value!" as the default?

In the meantime I added in some code to skip all attributes that can't be converted to a float in the ranker.

**Comment by dkoslicki** [comment]
I see, let's definitely change that to something more standard (such as NaN, None, or whatever works with the rest of the code). Skipping attributes that can't be converted to floats (but should be) makes sense.

**Comment by finnagin** [comment]
The fix for this may now be causing a different ranker issue: https://arax.ncats.io/?r=23658
