### ISSUE TITLE
Import 'response' issue

### ISSUE THREAD

**Issue by karafecho** [RTXteam/RTX#1626]
This issue is to report a potential bug with the import 'response' option. Specifically, I was told that I could view JSON output from an ARAGORN query by uploading/copying-and-pasting the output to the import 'response' option in the ARAX UI. However, when I attempt to do that either [here](https://arax.ncats.io/) or [here](https://arax.ci.transltr.io/), my browser crashes. I tried this several times, using two different browsers, so I think the issue may be on the ARAX end.

**Comment by karafecho** [comment]
Okay, thanks for the explanation, Luis. Makes sense to me.

**Comment by isbluis** [comment]
Hi @karafecho .  Just checking in to see if you were able to view this response via some other way, or if you would like further assistance.  Otherwise, is this issue good to close?  Thanks!

**Comment by karafecho** [comment]
Thanks for checking, @isbluis. We can close this issue.
