### ISSUE TITLE
Display categories in results view?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1629]
here in https://arax.ncats.io/?r=23280
I notice that in the results view, when you click on the node, you can't actually see what categories it belongs to in the detail information? Or am I missing it? Can that be added?

**Comment by edeutsch** [comment]
The fix looks good, thanks, push it!
We should fix the biolink:Unknown and PLACEHOLDER:placeholders
And, yes, I don't know why the essence_category broke. That was working at one point.
The score for these seem kinda broken as well. Unless maybe there are no NGDs available.

**Comment by isbluis** [comment]
Will do, thanks!

The essence_category seems broken for only certain responses; maybe it has something to do with all of the essences being of Category "biolink:NamedThing" ?  Or the special characters (comma etc) throw off the look-up?

I assume no UI action on the PLACEHOLDER and score issues, but let me know otherwise.

**Comment by edeutsch** [comment]
I don't know. I think this happens in the Ranker. Is anyone familiarish with that part of the code willing to try to fix the missing essenence_categories?

Correct, no UI action on PLACEHOLDER and score issues.
But I wonder if we should reinstate the tentative 2pm hackathon time today to work on PLACEHOLDER and biolink:Unknown issues?

**Comment by amykglen** [comment]
I can make the 2pm minihackathon time - have a number of biolink:Unknowns in Expand that need fixing..

**Comment by edeutsch** [comment]
okay, maybe we also want to drag in @finnagin and anyone else?

**Comment by finnagin** [comment]
I can show up for either time.

**Comment by amykglen** [comment]
1pm would be nice for me!

**Comment by edeutsch** [comment]
1pm then, see y'all then! I assume at the PSU zoom link

**Comment by isbluis** [comment]
Good to close this, @edeutsch ?

**Comment by edeutsch** [comment]
Yes, this is good, thanks, closing!
It might be a nice touch sometime to make the Name/Id/Categories stand out from the attributes in some interesting way. not important.
