### ISSUE TITLE
Q10 example not working

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#163]
Q10: What proteins are associated with anemia?
yields:
The most similar question I can answer is: What proteins are associated with similar phenotypes to $protein But I was unable to fill the following parameters: ['protein']

fix? or retire from example questions?

**Comment by dkoslicki** [comment]
This is really odd: on my end, it's being parsed correctly:
```python
p.parse_question("What proteins are associated with anemia")[0].restated_question_template.template
Out[39]: 'What genes are associated with $disease'
```
@edeutsch is the code the newest version?

**Comment by edeutsch** [comment]
yes, production is on the latest master codebase

**Comment by dkoslicki** [comment]
@edeutsch on the server wherever the code is being run, can you run the following in python3 and let me know what the result is?
```python
import ParseQuestion
p = ParseQuestion.ParseQuestion()
print(p.parse_question("What proteins are associated with anemia")[0].restated_question_template.template)
```

**Comment by edeutsch** [comment]
ha.
What proteins are associated with anemia
works fine
What proteins are associated with anemia?
fails.

In my original questions parsing code, one of the first steps was to strip off the ?
I don't know anything about the NLP package you're using, but somehow it is being thrown off by the ?
Maybe it should always be stripped off first?
In my imagination, a really nice NLP package would have an is_question flag that would be set by a trailing ? or a leading "what".. but otherwise ignore it.

**Comment by dkoslicki** [comment]
Just pushed stripping the "?" Ridiculous that ``nltk`` doesn't handle this properly. Another example of needing "real" NLP

**Comment by edeutsch** [comment]
excellent, thanks!
Q10 works now as in the offered examples. in devED. will roll to production later tonight when the smoke clears.
