### ISSUE TITLE
Super slow/stuck CHP Expand?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1633]
this morning arax.ncats.io was working fine for me until I ran a query that happened to use CHP as one of the KPs, and for that query, it's still just hanging (several minutes in) waiting for the KPs to finish, even though it was a simple one-hop query.

the targeted version of the query using just CHP is this:
```
add_qnode(ids=DOID:1588, key=n0)
add_qnode(categories=biolink:ChemicalEntity, key=n1)
add_qedge(subject=n0, object=n1, key=e0)
expand(kp=CHP)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```
which is hanging at the point where CHPQuerier starts:
```
2021-08-30T17:59:55.349592 DEBUG: Prefixes CHP supports for ['biolink:DiseaseOrPhenotypicFeature', 'biolink:PhenotypicFeature', 'biolink:Disease'] are: {'MONDO', 'NCIT', 'UMLS', 'DOID'}
2021-08-30T17:59:55.350864 DEBUG: CHP: Converted n0's 1 curies to a list of 5 curies with prefixes CHP supports
```
I don't think any messages are logged at the beginning of CHPQuerier, so it's a little unclear where exactly in there it's hanging, but I confirmed the last log message is the last thing the main ARAXExpander did prior to calling CHPQuerier.

I wonder if the problem is when this function is called?
```
    def _query_CHP_curies():

        with requests_cache.disabled():
            r = requests.get('http://chp.thayer.dartmouth.edu/curies/')
            allowable_curies = eval(r.content)

        return allowable_curies
```
because no timeout is specified, it could technically hang forever if they weren't responding..

(I wonder if this could be contributing to the performance issues arax.ncats.io has been having?)

**Comment by edeutsch** [comment]
I'm thinking it could be the cause of lots of extra processes that shouldn't be there that is causing one set of problems (extra processes that prevent a clean restart of the production server)

But also that it shouldn't be taking up any CPU time, so I don't think it is the cause of the server becoming unresponsive (because it is bogged down with something CPU expensive in the main thread)

**Comment by chunyuma** [comment]
Hi @amykglen, sorry for late response for this issue. I tried to run the query that you posted locally and it ran fast. I'm not sure if this hanging issue only occurred on arax.ncats.io. Have you tried running it locally?

**Comment by amykglen** [comment]
yeah, very strange, it seems to be working normally now on production. I'm not sure what the issue was. I did verify that other queries were working on production at the same time that this one wasn't, so I don't think it was purely due to server overload. but don't know that we have a way to diagnose the problem now! so I guess I'll close.
