### ISSUE TITLE
Allow pasting of full queries

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1635]
Current the ARAX GUI requires that the pasted JSON be the query_graph object. And the GUI puts it into a Query object before submission. It would be a nice touch if a user could also paste in a Query object directly, and the GUI would realize that it doesn't need to wrap it in a Query object but rather just submit it directly.

For example, it would be groovy if a user could paste in the standup JSONs like this one:
https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.1/workflow.json

(as well as preserve current behavior)

**Comment by isbluis** [comment]
Implemented in devLM.  Iff the JSON input contains a `message` element, then the UI assumes it is a full Query object and passes it straight through with no other manipulation.

Let me know if this is what you were thinking about, @edeutsch .

https://arax.ncats.io/devLM/

**Comment by edeutsch** [comment]
Brill! Push it!

**Comment by isbluis** [comment]
Pushed as part of Favorable Porcupine!

**Comment by edeutsch** [comment]
Great, thanks, Favorable Porcupine is now deployed to all TRAPI 1.1 endpoints. Has not yet been integrated into 1.2 endpoints.
