### ISSUE TITLE
Use KP infores curies as KP 'names'

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1636]
now that KPs each have an official infores curie (e.g., `infores:rtx-kg2`, `infores:molepro`, etc.), it seems like maybe Expand/ARAX should use those curies to refer to KPs instead of our invented shorthand names? (e.g., `RTX-KG2`, `MolePro`, etc.)

so usage in DSL would look something like this:
```
expand(kp=infores:rtx-kg2)
```
instead of the current:
```
expand(kp=RTX-KG2)
```
any thoughts or objections about this?

**Comment by edeutsch** [comment]
it would be a bit unsightly, but I agree it would be the right way to do it. Invented shorthand names are not good.

**Comment by amykglen** [comment]
hey @rcpeene - I just merged your PR for this issue into `master`. (thanks for that!) the last thing I thought of is could you regenerate the auto-documentation in light of the changes for this issue? basically if you do:
```
cd code/ARAX/Documentation
python3 document_dsl_commands.py
```
that will regenerate it, so all you have to do then is check in/push the changes that it made to `DSL_Documentation.md` (you can do that directly in `master`).

(regenerating the auto-documentation is needed for this issue since the KP names changed, and those are used throughout the documentation, like here:)
![Screen Shot 2022-02-15 at 3 15 41 PM](https://user-images.githubusercontent.com/49423686/154166395-efde1a01-d290-4a52-9a0c-8ab7235e478d.png)

**Comment by rcpeene** [comment]
After the last rollout of master, these new kp names appear to be working in the test suite and via the UI beta.
The DSL documentation has also be regenerated.
