### ISSUE TITLE
parentdivnum and trapiversion in query_graph JSON?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1639]
I haven't been able to repro it in a consistent way, but sometimes I stumble into a state where the JSON window in the Gui contains weird properties that I suspect are being injected by the GUI, notably parentdivnum and trapiversion:
```
{
  "edges": {
    "e0": {
      "constraints": [],
      "object": "n1",
      "predicates": [
        "biolink:decreases_abundance_of",
        "biolink:decreases_activity_of",
        "biolink:decreases_expression_of",
        "biolink:decreases_synthesis_of",
        "biolink:increases_degradation_of",
        "biolink:disrupts",
        "biolink:entity_negatively_regulates_entity"
      ],
      "subject": "n0",
      "id": "e0",
      "parentdivnum": 99999,
      "trapiversion": "1.2.0",
      "source": "n0",
      "target": "n1",
      "type": "biolink:decreases_abundance_of"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:SmallMolecule"
      ],
      "constraints": [],
      "is_set": false,
      "parentdivnum": 99999,
      "trapiversion": "1.2.0",
      "fulltextname": "n0",
      "id": "n0",
      "name": "biolink:SmallMolecules?"
    },
    "n1": {
      "constraints": [],
      "ids": [
        "NCBIGene:1956"
      ],
      "is_set": false,
      "parentdivnum": 99999,
      "trapiversion": "1.2.0",
      "fulltextname": "n1",
      "id": "n1",
      "name": "NCBIGene:1956"
    }
  }
}
```

Here's what the URL is of the current example:

https://arax.ncats.io/?source=ARS&id=71ebf73c-5923-44a6-8e29-e02c687096ff

**Comment by isbluis** [comment]
Placing this for future reference:
I was able to repro this issue by pasting `71ebf73c-5923-44a6-8e29-e02c687096ff` into the `Import-->id` box, and hitting `Load`.

**Comment by isbluis** [comment]
Fixed in devLM.

Turns out this was an issue when displaying "cached" responses already in memory.

To repro:
1. Paste a response id into the `Import-->id` box, and hit `Load`  (e.g. `71ebf73c-5923-44a6-8e29-e02c687096ff` )
2. Examine the JSON under `Query-->JSON` -- should be original
3. Go back and hit `Load` again (using the same Id)
4. Notice that the Status shows the result is being pulled "_...from cache_"
5. Examine JSON as above; find extra properties

**Comment by edeutsch** [comment]
excellent! That seems plausible. I was noticed it while bumbling around perhaps doing such things, but could not repro it while trying

**Comment by isbluis** [comment]
Another more plausible scenario would be if you have an ARS response with multiple actors, and you click around to examine individual results.  If you go back to see one you have already seen (and thus likely in cache) you'll likely run into this issue.

Might wait to push this along with other changes unless urgent.

**Comment by edeutsch** [comment]
Chris struggled with some weirdness (sticky nodes, attributes not displaying {I did not report because I have no repro}) at the last standup that may or may not be related to this, so I'd be inclined to roll out before tomorrow's standup so if there's weirdness, we know it's not related to this.

**Comment by isbluis** [comment]
My original "fix" created a new bug, so did not commit.  New bug has been fixed in devLM.

**Comment by isbluis** [comment]
Should have been fixed in `master` / _Courageous Muskox_.   Let me know if this persists, @edeutsch .

**Comment by edeutsch** [comment]
I have not seen this recent, so closing, thanks!
