### ISSUE TITLE
Do we need to conform to SRI Node Normalizer more?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1641]
I suspect that we need to conform to the SRI Node Normalizer more. There seems to be increased pursing of lips when we present our results using CURIEs that are not Node Normalizer ones. This is somewhat related to #1622.

As another example, there seems to be a new mechanism to judge automatically whether results being returned are good (which is a good thing I think): https://docs.google.com/spreadsheets/d/1Aa8hqW49vAACoTwz5EWWJ-r_hHuF5Zhfb8yszBrDAxc/edit#gid=0

But they will apparently be looking for PUBCHEM.COMPOUND:2950270, but ARAX would be returning CHEMBL.COMPOUND:CHEMBL2139402

Since when did PUBCHEM become more hip than CHEMBL?

https://arax.ncats.io/?term=PUBCHEM.COMPOUND:2950270

Maybe we should go through and re-set all our preferred identifiers and names to SRI Node Normalizer's id and names when possible. It would probably save us some headaches.

Or alternatively, Expand could choose to report the SRI_normalizer* values when available. They are provided by the NodeSynonymizer as seen here:
https://arax.ncats.io/?term=CHEMBL.COMPOUND:CHEMBL2139402

**Comment by amykglen** [comment]
good points... hm. I'd think that making the NodeSynonymizer's preferred curies/names match the SRI's preferred curies/names up front would be the most elegant solution, vs. Expand having to do those mappings over and over for every query.

**Comment by finnagin** [comment]
@edeutsch is this issue still relevant?

**Comment by amykglen** [comment]
going to close this issue since we now strictly conform to the SRI NN (for curies that they recognize)
