### ISSUE TITLE
Add lookup operation

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1642]
https://github.com/NCATSTranslator/testing/issues/115

**Comment by edeutsch** [comment]
We should review the operations that we currently support. Here is what we currently advertise that ARAX can do:
https://github.com/RTXteam/RTX/blob/cc1e98f9bf163cfe2fad18444928cf3b6d80093b/code/UI/OpenAPI/python-flask-server/openapi_server/openapi/openapi.yaml#L25

Note that `lookup` is not there.
So in this particular case, the correct response should have been a 400 UnsupportedOperation. 

If we want to start supporting lookup, then we need to amend the supported operations list linked to from above.

**Comment by finnagin** [comment]
@edeutsch I was actually just in the process of updating the operations following [these steps.](https://github.com/RTXteam/RTX/wiki/ARAX-Workflow#updating-the-workflow-operations-that-arax-knows-about)

So I believe once I'm done it will be added and working.

**Comment by edeutsch** [comment]
great!
That intrux set looks pretty good EXCEPT all references to 1.1 should now be changed to 1.2 since we have now moved to that.

**Comment by finnagin** [comment]
Ah good catch. Thank you!

**Comment by finnagin** [comment]
@edeutsch looks like I can't do a git pull on arax.ncats.io due to unpushed changes that were made to ARAX_query.py. Looks like some query tracker stuff was added in devED? Is this something that is ready to push or should I hold off on updating this until then?

Also, do I have to do all of these in devED specifically? I was just going to work in devED because it is specifically mentioned on step 8.

**Comment by edeutsch** [comment]
See Slack

**Comment by finnagin** [comment]
looks to be working in production: https://arax.ncats.io/?r=25052
