### ISSUE TITLE
visual query plan/progress?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1646]
I've been thinking about experimenting with a visual query plan/progress. Something like:
```
        +-- CHP: Not suitable
        +-- COHD: Not suitable
e0 -----+-- BTE: Timed out after 15 seconds
        +-- MolePro: Waiting for response...
        +-- RTX-KG2: Returned 96 results
        +-- Genetics: Not suitalble
```

We could try to pack some information in the log entries, that is then parsed by the GUI
Or we could have a separate structure that is really just a dict of edge ids and the conclusion for each KP. Those structures could also be streamed and then also included in the Response.

Does this seems worth it/interesting/fun?
@isbluis relatively easy to viz as it's coming and then also for reloaded results?
@amykglen fairly easy to add perhaps via response.query_plan_update('e0','MolePro','Returned 15 results') ?

**Comment by isbluis** [comment]
This seems quite useful and fun; should be easy enough to display/update in the UI as the response is streamed or retrieved.
Ideally a full list of KPs would be furnished early on so that the UI can display a little table with progress that gets updated.  Or something like that.  Is that close to what you envision?

**Comment by edeutsch** [comment]
yes, exactly. I was vaguely hoping for something graphy similar to the ascii art. a jiggling dynamically updated graph!

But a table would be fine.

**Comment by edeutsch** [comment]
The most amazingly awesome thing is complete and deployed. Many thanks @amykglen @isbluis . closing.
