### ISSUE TITLE
Where should API tests be?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1647]
Under test/api there are a (small) set of tests that hit the production API both for success and for failure handling.
These get run every time someone runs pytest in the test directory (it apparently automatically does subdirs)

But this strikes me as a little silly. The main use (?) of the tests is to make sure that current code is still working (usually before checking in code changes). But the api tests are testing *production* via the API, not local code. The local code could be completely trashed and these tests would all be fine because they're testing deployed production. Conversely if I bork production, these tests on your dev machine would start failing even if your code was fine.

So I'm thinking that we ought to move api somewhere else.
But we still want to run it occasionally, so we need to figure out how to do that.
But it seems out of place in the "test suite".

What do you all think?

**Comment by finnagin** [comment]
We could move the api tests directory so that is on the same level as the test suite directory. 

Something like `RTX/code/ARAX/api_test`.

**Comment by edeutsch** [comment]
Yes, good idea. I'm thinking `RTX/code/ARAX/test_production_api`
so that it sorts next to the main tests.

**Comment by edeutsch** [comment]
Moved to `RTX/code/ARAX/test_production_api` in master
