### ISSUE TITLE
ARAX providing edge_attribute_source without infores id information

### ISSUE THREAD

**Issue by vgardner-renci** [RTXteam/RTX#1649]
See the most recent version of the workflow progress tracker --> edge attribute source sheet.

https://docs.google.com/spreadsheets/d/1O1cMmYGxoIqP6xbzj6FG5owiKQVg57wx2O_XIA_hN_A/edit#gid=642301883

Rows at the top indicate in which workflows ARAX is returning edge attribute sources without infores id information.

**Comment by edeutsch** [comment]
I'm not really understanding where there's a deficiency to be fixed here. Is there an implication that something needs to be fixed?

Can you provide an example of something that needs to be fixed?

**Comment by finnagin** [comment]
closing for #1776
