### ISSUE TITLE
Second Q14 

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#165]
The second Q14:
What diseases involve similar genes to sickle cell anemia?
top hit: The disease sickle cell anemia involves similar protein's as SICKLE CELL ANEMIA with similarity value 0.360000

One is from OMIM and one has a DOID. KG issue, I guess.

Also, protein's is overapostrophed

And why only a confidence of 0.36 for what is the same thing?

Result 2 doesn't appear to depict any genes in common, so that similarity is puzzling.
oops, wait, that is a Cytoscape display problem. since they're all linear, the connections are not apparent. If you manaully remove the linearity, the answer becomes clearer. Fine. Minor issue for @isbluis 

But the answer number 1 is awkward.

fix? or remove from list for now?

**Comment by saramsey** [comment]
I think this will be solved (mostly) as a side effect of implementing #37 (slated for post-hackathon work)

**Comment by saramsey** [comment]
In the meantime is this causing huge issues?  What's the severity level?

**Comment by dkoslicki** [comment]
Correct, one is a DOID and the other is an OMIM and they have different associated edges, hence the low similarity. As @saramsey says, this will be fixed by #37

**Comment by edeutsch** [comment]
Q21 also suffers from this problem:
The disease RETINITIS PIGMENTOSA; RP involves similar protein's as retinitis pigmentosa with similarity value 0.233333

As a side node, I'm seeing a pattern where some OMIM names seem to include a synonym after a semi-colon. Maybe the KG builder should look for a semi-colon in the OMIM name and insert what follows as as the node symbol? So "RETINITIS PIGMENTOSA; RP" becomes node.name="RETINITIS PIGMENTOSA" and node.symbol becomes "RP". Might be a nice touch to de-shout the node.name for OMIM.

**Comment by edeutsch** [comment]
Regarding severity/huge issues: we are recommending this question as something that users should try. Seems like we can:
1) fix it
2) retire this Qnn until such a time as it works
3) replace the particular instance of the Qnn to use a disease that does not display the problem

It think it;s fine to have problems, but I suggest we don't display them in public if we can help it.

Suggestions?

**Comment by dkoslicki** [comment]
I vote: if I can't get it fixed by Sunday evening, retire this Qnn until it works

**Comment by dkoslicki** [comment]
Problem confirmed: OMIM and DOID redundancies. Making this one ``false`` in ``QuestionExamples.tsv``. Closing.
