### ISSUE TITLE
Why are we not reaching out to GeneticsKP?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1651]
Today a received a PM from Marc Duby of GeneticsKP about why ARAX is not reaching out to them for one of the workflow queries. and I can't figuring it out. I hoping you can help. Here's his post:

I am trying to debug why our KP doesn't seem to be accessed for the workflow B queries, in particular
(https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowB/B.1a_DILI-three-hop-from-disease-or-phenotypic-feature_trapi.json)
I ran the first part of the query (diseases clinically linked to DILI) through ARAX (https://arax.ncats.io/api/arax/v1.2/query), collected the disease IDs and ran the subsequent query payload
```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n01",
                    "object": "n00",
                    "predicates": ["biolink:gene_associated_with_condition"]
                }
            },
            "nodes": {
                "n00": {
                    "ids": [
                        "CHEBI:59683",
                        "CHEMBL.COMPOUND:CHEMBL2108558",
                        "LOINC:55275-2",
                        "MESH:C040391",
                        "MESH:C064613",
                        "MESH:C069356",
                        "MESH:C071458",
                        "MESH:C093154",
                        "MESH:C110500",
                        "MESH:C115528",
                        "MESH:C518324",
                        "MESH:C519298",
                        "MESH:D000071020",
                        "MESH:D006679",
                        "MESH:D016031",
                        "MESH:D053218",
                        "MONDO:0000775",
                        "MONDO:0001475",
                        "MONDO:0002184",
                        "MONDO:0004335",
                        "MONDO:0005071",
                        "MONDO:0005267",
                        "MONDO:0005354",
                        "MONDO:0005359",
                        "MONDO:0005366",
                        "MONDO:0005790",
                        "MONDO:0007745",
                        "MONDO:0013209",
                        "MONDO:0013282",
                        "MONDO:0013433",
                        "MONDO:0018229",
                        "MONDO:0043693",
                        "NCIT:C29933",
                        "OMIM:MTHU002997",
                        "OMIM:MTHU012757",
                        "OMIM:MTHU013583",
                        "OMIM:MTHU021860",
                        "OMIM:MTHU030933",
                        "OMIM:MTHU034288",
                        "OMIM:MTHU045723",
                        "OMIM:MTHU048033",
                        "OMIM:MTHU048989",
                        "SCITD:143472004",
                        "SCITD:406104003",
                        "SCITD:86259008",
                        "SCTID:207471009",
                        "SCTID:64411004",
                        "UMLS:C0149709",
                        "UMLS:C0262505",
                        "UMLS:C0342271",
                        "UMLS:C0455417",
                        "UMLS:C0455540",
                        "UMLS:C0473117",
                        "UMLS:C0552479",
                        "UMLS:C0948251",
                        "UMLS:C4049267",
                        "UMLS:C4554323"
                    ],
                    "categories": [
                        "biolink:DiseaseOrPhenotypicFeature"
                    ]
                },
                "n01": {
                    "categories": [
                        "biolink:Gene"
                    ]
                }
            }
        }
    }
}
```
I don't see any activity on our genetics KP end for this query or its inverse, even though when I hit our KP directly we do have results to offer.
I am wondering if there is an issue with our configuration or the data we are returning and how we can modify our service to be more relevant in gene/disease queries we can answer
Please let me know if there is someone else I should be contacting in reference to the ARAX ARA

[Eric] I ran his query and here's the result:
https://arax.ncats.io/?r=25144

I verified in the logs:
```
2021-09-14T23:25:29.096079 DEBUG: Expanding qedge e00
2021-09-14T23:25:29.096499 DEBUG: Modified QG for this qedge is (n00:['biolink:PhenotypicFeature', 'biolink:Disease', 'biolink:DiseaseOrPhenotypicFeature'] [57 curies])-['biolink:gene_associated_with_condition']-(n01:['biolink:Gene', 'biolink:Protein'])
2021-09-14T23:25:29.096556 DEBUG: For e00, pre-prune threshold is 500, post-prune threshold is 10000
2021-09-14T23:25:29.096891 DEBUG: Loading record of KP timeouts
2021-09-14T23:25:29.097114 DEBUG: Loading meta map (already exists and isn't due for a refresh)
2021-09-14T23:25:29.793110 DEBUG: Selecting KPs to use for qedge e00
2021-09-14T23:25:29.793893 INFO: The KPs Expand decided to answer e00 with are: {'RTX-KG2'}
```

GeneticsKP meta_knowledge_graph is here:
https://translator.broadinstitute.org/genetics_provider/trapi/v1.2/meta_knowledge_graph

and I see:
```
    {
      "object": "biolink:Disease",
      "predicate": "biolink:gene_associated_with_condition",
      "subject": "biolink:Gene"
    },
```
there.  So it looks like that stated pattern in the ARAX log matches an entry in the GeneticsKP MKG.

So why aren't we reaching out to them? A bug? Something I'm missing? ideas?

thanks!

**Comment by edeutsch** [comment]
AH, one this I just noticed is: in the origin query_graph we have:
```
            "edges": {
                "e00": {
                    "subject": "n01",
                    "object": "n00",
                    "predicates": ["biolink:gene_associated_with_condition"]
                }
            },
```
Thus: n01 (Gene) biolink:gene_associated_with_condition n00 (Disease)
So the n01 and n00 are kind of out of order, but semantically correct (I think)?

But in the ARAX log line:
```
2021-09-14T23:25:29.096499 DEBUG: Modified QG for this qedge is (n00:['biolink:PhenotypicFeature', 'biolink:Disease', 'biolink:DiseaseOrPhenotypicFeature'] [57 curies])-['biolink:gene_associated_with_condition']-(n01:['biolink:Gene', 'biolink:Protein'])
```
assuming it's subject - predicate - object, then the sense it reversed?
So maybe ARAX is looking up the reverse of the intended relationship and doesn't find it?

**Comment by amykglen** [comment]
I think you're right that that subject/object mix up would cause what we're seeing.

though I think Expand may also avoid using them for this query because of how many input curies there are. there's still some logic in place that checks how many curies are in the QG and then only uses KG2 if there are more than a certain number (for speed reasons). perhaps we should up that limit.

**Comment by edeutsch** [comment]
yeah, I think I agree. maybe we can up that to 100 CURIES for the purposes of helping with the demo workflows?

Also, I wonder what our timeout is? maybe we could increase that to be a little more patient with our KPs?
It seems like for our example query we always send the query to BTE but we give up on it 80% of the time.

**Comment by amykglen** [comment]
yeah, I think you're right we should start being a bit more patient - our timeout for a simple one-hop query (with <20 input curies) has been 15 seconds, but BTE, ICEES, and CHP (sounds like we're going to start using their TRAPI API) sometimes can't meet that.

I just upped the batch limit to 100 curies, as you suggested, and also upped our timeout to 30 seconds for simple one-hop queries (<20 input curies), and 60 seconds for queries with <100 input curies. do those seem reasonable? 

fyi, timeouts are defined here (for one-hop queries):
https://github.com/RTXteam/RTX/blob/ea6c42d7a025a8a18e41d8f62eb1d45ce63e0117/code/ARAX/ARAXQuery/Expand/trapi_querier.py#L230-L254

**Comment by edeutsch** [comment]
Great, these limits sound pretty reasonable to me. It will mean that our queries will seem to take longer, but that's fine I think. I will deploy the new settings.

I got a follow up message from Marc:
```
Marc Duby (Genetics Provider, Molecular Data Provider)  7:52 AM
Our limit now is 100,000 curie ids, which it seems at least one ARA is making use of.
We modified our code to handle batch sql which mysql handles well in the current version, so we can easily handle 10,000 curie ids (or more). (edited) 
```

**Comment by amykglen** [comment]
ok, I re-ran your ARAX query on production just now and this time it used GeneticsKP (and indeed they returned answers very quickly!) https://arax.ncats.io/?r=25615

the query overall took a long time though because it waited 180 seconds for a couple KPs to respond - I forgot that the counting of curies when determining timeouts is done _after_ equivalent curies have been added to the QG... (which resulted in >200 curies in this case, hence why the 180-second timeout tier was reached...) hm.

**Comment by edeutsch** [comment]
ah. well if GeneticsKP responded quickly, then maybe keeping a shorter timeout around 30 seconds is still fine. dunno.

**Comment by edeutsch** [comment]
Should I respond to Marc that he should try it again? Or do you want to adjust first?

**Comment by amykglen** [comment]
I just tweaked them in `master` - maybe roll that out before we let him know.

**Comment by edeutsch** [comment]
latest `master` is rolled out to all deployments (as of this afternoon. forgot to announce at the time)

**Comment by amykglen** [comment]
great - reran the query: it used GeneticsKP and Expand only waited 30 seconds, as intended: https://arax.ncats.io/?r=26404

as a side note: strangely, Overlay/Resultify each took about 4 minutes, which seems awfully high to me... setting `is_set=true` on `n00` sped it up to 3 seconds for Resultify, but it still took 4 minutes for Overlay..

**Comment by amykglen** [comment]
actually, sorry, read the log wrong - Resultify never took 4 minutes - only Overlay.

**Comment by edeutsch** [comment]
> great - reran the query: it used GeneticsKP and Expand only waited 30 seconds, as intended: https://arax.ncats.io/?r=26404

waited 30 seconds and then timed out?

> as a side note: strangely, Overlay/Resultify each took about 4 minutes, which seems awfully high to me... setting `is_set=true` on `n00` sped it up to 3 seconds for Resultify, but it still took 4 minutes for Overlay..

hmm.. any ideas why?
Is that perhaps FastNGD? I wonder if we should/can track what is the most expensive part of each query. Expand may be long-running but it's mostly just waiting around for responses. Maybe overlay is what is gobbling up lots of CPU time to the point where Expand struggles to get get timeslices to finish its processing...?

**Comment by amykglen** [comment]
> great - reran the query: it used GeneticsKP and Expand only waited 30 seconds, as intended: https://arax.ncats.io/?r=26404
> 
> waited 30 seconds and then timed out?

I thought I checked and it actually got results from GeneticsKP (didn't time out for them). did you see otherwise? maybe I saw wrong. can't load that query response right now to verify as it seems arax.ncats.io is still struggling

**Comment by edeutsch** [comment]
> > great - reran the query: it used GeneticsKP and Expand only waited 30 seconds, as intended: https://arax.ncats.io/?r=26404
> > waited 30 seconds and then timed out?
> 
> I thought I checked and it actually got results from GeneticsKP (didn't time out for them). did you see otherwise? maybe I saw wrong. can't load that query response right now to verify as it seems arax.ncats.io is still struggling

Did not see otherwise, but wondering if your statement implied timeout. Now I presume not.

arax.ncats.io is not merely struggling it is dead as a doornail.

**Comment by edeutsch** [comment]
Closing in favor of #1676
