### ISSUE TITLE
Modify CHP module in ARAX exapnder

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1653]
From Gregory Hyde of CHP team:
_Hi Chunya, I'm a member of Connections Hypothesis Provider (CHP). I just wanted to reach out about integration. I know you've probably spent more time speaking to Chase Yakaboski, and that you two had some success in integrating CHP into Expander Agent, but I currently don't see CHP appearing in many of your results. It is possible that we are either timing out or are truncated out in your results if you filter out the top X answers. I wanted to know if this was something you were seeing on your end or if you had some insight into this. As it stands CHP will take ~30 seconds to return an answer for a 1 hop where only 1 node has a curie. If this is outside of some timeout threshold you have let us know_

Based on my investigation, the CHP kp wasn't called in some queries in ARAX because some of their functions in `chp_client` have been replaced by the meta kg and some new functions. I generate this issue to modify the current CHP module in our ARAX expander and make it fit with the meta kg and their new functions.

**Comment by chunyuma** [comment]
By replacing CHPQuerier with TRAPIQuerier (`chp_client` is deprecated soon so we can only use CHP api in the future), right now all CHP tests fail due to the timeout issue:
```
test_ARAX_expand.py::test_chp_expand_1 FAILED                                                                                                                                        [ 50%]
test_ARAX_expand.py::test_chp_expand_2 FAILED                                                                                                                                        [100%]
```

I'm asking CHP team to speed it up.

**Comment by amykglen** [comment]
hey @chunyuma - is this issue good to close now that we use `TRAPIQuerier` for CHP?

**Comment by chunyuma** [comment]
Yes, I think it is good to close. Thanks @amykglen for replacing CHPQuerier with TRAPIQuerier for CHP?
