### ISSUE TITLE
Query.submitter = 'infores:arax'

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1654]
TRAPI 1.2.1 (which we now support) provides for the specification of Query.submitter
It would be groovy if ARAX would provide a Query.submitter = 'infores:arax' when sending to RTX-KG2
This will be nice for our internal tracking of what the KG2 endpoint is up to.

In principle it would be nice to do the same for all KPs. There is some risk that it would cause harm at the remote site and interfere with normal operation of the KPs. This will be supported eventually but perhaps premature.

**Comment by amykglen** [comment]
ok, this is in `master` (can already see it being used on https://arax.ncats.io/devLM/index.html?recent=1 as I run the test suite from my laptop!)

**Comment by edeutsch** [comment]
The latest `master` is rolled out to all TRAPI 1.2 deployments.
production would not restart due to other processes holding onto the port so I resorted to a killall.
Unclear if they were stuck or I interrupted an ongoing query.

**Comment by edeutsch** [comment]
excellent! thanks! closing!
