### ISSUE TITLE
downrank SEMMEDDB?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1658]
After looking at a bunch of results from ARAX at today's Transltr mini-hackathon, there seemed to be a general sentiment that we are going astray by giving so much weight to SemMedDB. many of the results we see are many different predicates from SemMedDB often conflicting, etc. General sentiment seemed to be that there's a lot of noise there. And that our high-quality results from say CHEMBL are being drowned out by SemMedDB. i.e. CHEMBL has 10 nice high quality relationships with one edge each, and then SemMedDM comes along with 100s of relationships each with 7 edges treats, causes, related_to, involved_in, affects, etc., and these get weighted very highly because wow look at all the edges, but most seem to be suspect. It seems that maybe one good edge from CHEMBL should perhaps outrank a pile of conflicting information from SemMedDB. We shouldn't throw it away, but maybe not proudly show it at the top.

We may be at the point where we need to start looking at our results more carefully and thinking about how to weight and rank better.

**Comment by edeutsch** [comment]
They have added an issue now:
https://togithub.com/NCATSTranslator/minihackathons/issues/282

**Comment by dkoslicki** [comment]
@finnagin Do you mind lowering the weight on the NGD edges [here (I think)](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_ranker.py#L179) and seeing if that improves what Eric observed above?

**Comment by finnagin** [comment]
Sure! How low do you think I should adjust it? 0.5?

**Comment by dkoslicki** [comment]
As far as necessary to make the above issue Eric relayed go away (i.e. it will take some trial and error, and you'll want to keep an eye on the result rankings for other queries to make sure you haven't picked too low of a value)

**Comment by finnagin** [comment]
@edeutsch am I missing something with this issue you linked? https://togithub.com/NCATSTranslator/minihackathons/issues/282

In the query posted I only see 2 arax results and neither seem to have causes edges.

**Comment by edeutsch** [comment]
Try this query instead: https://arax.ncats.io/?source=ARS&id=d1fe78a8-0f74-43ad-a13f-573a348e3472

**Comment by finnagin** [comment]
Just posting the json here for easy testing:

```
{
  "edges": {
    "F1": {
      "constraints": [],
      "object": "n2",
      "predicates": [
        "biolink:has_fisher_exact_test_p_value_with"
      ],
      "subject": "n1"
    },
    "F2": {
      "constraints": [],
      "object": "n3",
      "predicates": [
        "biolink:has_fisher_exact_test_p_value_with"
      ],
      "subject": "n2"
    },
    "N1": {
      "constraints": [],
      "object": "n1",
      "predicates": [
        "biolink:has_normalized_google_distance_with"
      ],
      "subject": "n0"
    },
    "N2": {
      "constraints": [],
      "object": "n2",
      "predicates": [
        "biolink:has_normalized_google_distance_with"
      ],
      "subject": "n1"
    },
    "N3": {
      "constraints": [],
      "object": "n3",
      "predicates": [
        "biolink:has_normalized_google_distance_with"
      ],
      "subject": "n2"
    },
    "e01": {
      "constraints": [],
      "object": "n1",
      "predicates": [
        "biolink:has_real_world_evidence_of_association_with"
      ],
      "subject": "n0"
    },
    "e02": {
      "constraints": [],
      "object": "n1",
      "predicates": [
        "biolink:gene_associated_with_condition"
      ],
      "subject": "n2"
    },
    "e03": {
      "constraints": [],
      "object": "n3",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n2"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ],
      "constraints": [],
      "ids": [
        "MONDO:0005359"
      ],
      "is_set": false
    },
    "n1": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ],
      "constraints": [],
      "is_set": false
    },
    "n2": {
      "categories": [
        "biolink:Gene"
      ],
      "constraints": [],
      "is_set": false
    },
    "n3": {
      "categories": [
        "biolink:ChemicalEntity"
      ],
      "constraints": [],
      "is_set": false
    }
  }
}
```

**Comment by edeutsch** [comment]
note that the NGD edges should be stripped before submission

**Comment by finnagin** [comment]
As in remove edges N1, N2, and N3 them from the json query? Do I need to also remove the fisher exact ones?

**Comment by edeutsch** [comment]
ah yes, those too. i.e. I think this should be the submission QG:
```
{
  "edges": {
    "e01": {
      "constraints": [],
      "object": "n1",
      "predicates": [
        "biolink:has_real_world_evidence_of_association_with"
      ],
      "subject": "n0"
    },
    "e02": {
      "constraints": [],
      "object": "n1",
      "predicates": [
        "biolink:gene_associated_with_condition"
      ],
      "subject": "n2"
    },
    "e03": {
      "constraints": [],
      "object": "n3",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n2"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ],
      "constraints": [],
      "ids": [
        "MONDO:0005359"
      ],
      "is_set": false
    },
    "n1": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ],
      "constraints": [],
      "is_set": false
    },
    "n2": {
      "categories": [
        "biolink:Gene"
      ],
      "constraints": [],
      "is_set": false
    },
    "n3": {
      "categories": [
        "biolink:ChemicalEntity"
      ],
      "constraints": [],
      "is_set": false
    }
  }
}
```

**Comment by finnagin** [comment]
Thanks!

**Comment by finnagin** [comment]
Here is the result from changing the ngd weighting from 0.8 to 0.5: https://arax.ncats.io/test/?r=26906

What would I be looking for exactly? I see that the results are moved around a bit but they still look like results with tons of edges near the top and I feel like the second result (RNA, Small Interfering) which is now higher up is probably not what we want.

**Comment by dkoslicki** [comment]
Thanks Finn; this appears to be more nuanced than I originally thought: the *number* of edges is also affecting the score due to the Frobenious norm (and potentially the max flow and longest paths as well). It's not immediately obvious to me how to solve this. In particular, I don't think we want to say "we don't trust results that have a lot of SemMedDB edges" since that would make results that have, say, a single SemMedDB edge (whose removal would disconnect the graph) percolate towards the top. 

@edeutsch was there a particular solution you had in mind? Eg. take a look at the provenance of all the edges (eg. `infores:semmeddb`), and down-weight ones that only have semmeddb edges and up-weight results that have a plurality of different provided_by's?

**Comment by edeutsch** [comment]
I don't have a specific solution in mind. I was thinking about something along the lines where no matter how many SemMedDB edges there are, the confidence maxes out at 0.5 or some number.

Maybe something like compute all flow first just for SemMedDB edges and cut in half so the max is 0.5. Then recompute for all other edges and then combine? Dunno, just musing, but something like that. Something so that non-SemMedDB edges outcompete SemMedDB edges in most cases.

**Comment by dkoslicki** [comment]
Closing in favor of #1695
