### ISSUE TITLE
Q22 problem

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#166]
Q22 yields:

 What genetic conditions involve similar micrornas to SICKLE CELL ANEMIA?
Please ensure that this is an accurate restatement of the intended question.

Sorry, the disease OMIM:603903 is not connected to any microRNA.

fix? different disease? @jaredroach, why did you select this disease?

**Comment by jaredroach** [comment]
As I understand it, there is no reason to select a different disease, as microRNAs are not implemented. I think the question may actually have worked in the previous release b/c microRNAs were semantically replaced with genes.

So by fixing the duality of gene and microRNA in our parsing, the example question is now broken.

Note that this question actually works:
"What genetic conditions involve similar genes to sickle cell anemia?"

I note that 
"What genetic conditions involve similar micrornas to breast cancer?"
also fails.

Is the system now designed that if we choose a disease that had an edge to a microRNA, we wold actually get an answer? If so, we probably have to find that disease with a Cypher query.

**Comment by dkoslicki** [comment]
Hmm... I don't think we had duality between microRNAs and genes (@saramsey, correct me if I'm wrong). Looks like sickle cell anemia is genuinely not connected to any microRNAs (and wasn't in the previous KG either), so I don't know why this was selected as an example.

And yes, given a disease that's actually connected to a microRNA, it _should_ return a result. Examples:
```
match p=(n:disease)-[]-(:microRNA) return n.name limit 10
"fatty liver disease"
"drug-induced hepatitis"
"liver cirrhosis"
"drug-induced hepatitis"
"liver cirrhosis"
"BONE MINERAL DENSITY QUANTITATIVE TRAIT LOCUS 15; BMND15"
"BONE MINERAL DENSITY QUANTITATIVE TRAIT LOCUS 15; BMND15"
"HEPATOCELLULAR CARCINOMA"
"cocaine dependence"
```
Sometimes the number of overlapping nodes is low enough to be below the optional threshold (here 0.0002). I'll investigate more...

**Comment by dkoslicki** [comment]
Ok, I think I found the issue: the target was set to ``omim_disease`` where it should have been ``disease``. See fc7d491.
@edeutsch I suggest waiting until I pin a few more of these down before bouncing the flask

**Comment by edeutsch** [comment]
Using latest checked-in code base:
What genetic conditions involve similar microRNAs to fatty liver disease?
returns:
No disease were found with similarity crossing the threshold of 0.000200.

**Comment by dkoslicki** [comment]
Ok, I think it's fixed now. Problem was multiple relationship types and I was picking the wrong one. On my end, confirmed to work with fatty liver disease DOID:9452.

**Comment by edeutsch** [comment]
great, yes, works in devED. will roll later.
