### ISSUE TITLE
Need to address ARAX host instability

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1663]
I think ARAX host crashing needs urgent attention. I didn't have a top running this time, but the logs don't seems to show great load. But in any case, I'm thinking that there should be no reason for the host OS to lock up no matter what strain there is inside the Docker container. And as far as I can tell these are blue-sky host lockup events.

We seem to be running Ubuntu 18.04 as a host OS and inside the container.

Maybe the least disruptive thing to try it install all OS updates which are surely piling up and see if that helps things?

Failing that, perhaps an upgrade or fresh reinstall to Ubuntu 20 would be helpful.

But I think we need to try something.

If we were to upgrade all stale packages, how does that work with the Docker container? Do we upgrade all packages both inside and outside? or?

**Comment by finnagin** [comment]
@edeutsch You would only need to upgrade inside the container and you would do that just like any other ubuntu machine. 

Though it's possible we would also want to try to update Docker itself on the host machine.

Though I'm not entirely sure that this will fix the issue. Maybe another potential way to fix it is to limit the memory and cpus docker is allowed to use leaving a bit so the host os doesn't run out?

**Comment by edeutsch** [comment]
okay, I really don't know anything about Docker configuration. it seems to me that the host OS is locking up without due cause. Not obvious to me that updating anything inside the container would affect that. but limiting the memory sounds reasonable. Is the idea that currently we don't limit the memory at all, so this could get us into trouble? I started the container with:

sudo docker start rtx1

(following the wiki instructions)

Would it be advisable to do:

sudo docker start --memory=55g rtx1

instead? Should I attempt that?

**Comment by saramsey** [comment]
Seems worth trying!

**Comment by finnagin** [comment]
It looks like it is a docker run option rather than a docker start option so it might be a little more involved. 

We will have to make an image of the current container, stop/remove the current container, and then run a new container from the image.

**Comment by edeutsch** [comment]
ah, okay. I don't know this stuff. If you are able to formulate a plan that would do this, that would be much appreciated! If there's an updated Docker package on the host OS, seems like it would be a good idea to update that too while surgery is being performed on our Docker system as well.

Maybe put together a plan and discuss and plan a time to execute it when minimally disruptive.

**Comment by finnagin** [comment]
Yeah that's a good idea. We could run the update after we shut down the current container but before we start the new one.

Sure I can do that. I'll formulate a plan and post it here. Then maybe I can do it sometime in the evening this week.

**Comment by saramsey** [comment]
@finnagin thanks for the info. 

On `arax.ncats.io`, do we have sufficient free space in the root filesystem to make a second container?

**Comment by finnagin** [comment]
Looks like this is the container and image sizes of rtx1:
```
Images space usage:

REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE                SHARED SIZE         UNIQUE SIZE         CONTAINERS
openapitools/openapi-generator-cli   latest              9b63464d3323        5 weeks ago         325.5MB             0B                  325.5MB             0
rtx1                                 travis-test         3651d64afaca        6 months ago        14.37GB             14.11GB             262.7MB             0
<none>                               <none>              6642fa269bb4        7 months ago        135.2MB             107.9MB             27.37MB             0
openapitools/openapi-generator-cli   v5.0.1              4d492bfa739b        7 months ago        135.9MB             107.9MB             28.05MB             0
<none>                               <none>              1367c1735ffa        8 months ago        135.7MB             107.9MB             27.85MB             0
rtx1                                 20200829            d9e8d256e9d5        12 months ago       14.11GB             14.11GB             0B                  1

Containers space usage:

CONTAINER ID        IMAGE               COMMAND             LOCAL VOLUMES       SIZE                CREATED             STATUS              NAMES
6d6766e08a31        rtx1:20200829       "bash"              0                   1.14GB              12 months ago       Up 4 hours          rtx1
```

**Comment by finnagin** [comment]
And it looks like we have 108 GB left on the machine so we should be fine making a new one. as the new image should only take ~14-15GB and then the new container will take an additional ~1GB.

**Comment by edeutsch** [comment]
I am neutral on waiting. I am uncertain why it would matter. I would suggest we try this tonight or tomorrow night. Either is fine. That would be before or after the planned roll out.

**Comment by finnagin** [comment]
That's fair. I could do it tonight.

**Comment by edeutsch** [comment]
okay, want to suggest a time? I'd like to be on hand. Any time after 7 is fine with me.
Anyone else have concerns?

**Comment by finnagin** [comment]
7 pm tonight works for me.

**Comment by finnagin** [comment]
We just updated the container and everything seems to be running smoothly. Should I close this issue out @edeutsch ?

**Comment by edeutsch** [comment]
Yes, let's close it out. Just for the record essentially two things were done:
1) The problem may have been at least partially removed at the source by limiting the number of concurrent connections to 40 and by blocking two IP addresses that seemed to be abusing the system. They may return under a different IP though
2) The Docker RAM limit is now 55 GB and so hopefully the host OS won't run out of memory.

I will note that while running `top` inside the container, I don't see obvious evidence of this new limit:
```
top - 02:41:02 up 12:13,  0 users,  load average: 0.06, 0.10, 0.14
Tasks:  30 total,   1 running,  29 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 64705984 total,  7169968 free,  1524452 used, 56011564 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 62297720 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                         
    1 root      20   0   18420   3432   2816 S   0.0  0.0   0:00.03 bash                                                                                            
  339 root      20   0   80012   4668   3304 S   0.0  0.0   0:00.01 apache2                                                                                         
  342 www-data  20   0  746224   5208   3012 S   0.0  0.0   0:00.13 apache2                                                                                         
  343 www-data  20   0 1271080   8396   3140 S   0.0  0.0   0:00.65 apache2                                                                                         
  423 mysql     20   0    4508   1696   1540 S   0.0  0.0   0:00.28 mysqld_safe                                                                                     
  863 mysql     20   0 1817788 237804  18328 S   0.0  0.4   0:01.26 mysqld                                                                                          
  974 rt        20   0  105332  22024   8832 S   0.0  0.0   0:00.36 python3                                                                                         
 1034 rt        20   0 1042644 102068  28740 S   0.0  0.2   0:04.19 python3                                                                                         
 1079 rt        20   0 1161824 126908  37780 S   0.0  0.2   0:05.78 python3               
```

But we'll see.
closing.
thanks.
