### ISSUE TITLE
Add existing workflow operations

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1664]
Looks like we have a couple operations that we can do but are not implemented:

 - [x] Sort edge attribute
 - [x] Sort node attribute
 - [x] Sort results score
 - [x] Annotate nodes
 - [x] Lookup and Score

**Comment by dkoslicki** [comment]
Any status update on this?

**Comment by dkoslicki** [comment]
Indeed, don't know how that happened. Sorry @edeutsch

**Comment by finnagin** [comment]
Oops, I think this fell off my radar. I'll get at least most of this done before the next OW meeting on Tuesday.
