### ISSUE TITLE
Tuesday's RHOBTB2 query

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1666]
I think this is a slight revisitation of a previous query. I didn't mention it before, but this time will:

https://github.com/NCATSTranslator/testing/pull/121/files#diff-81022c561b4ab80e31cf06c7a9aa42461fb7917a61d8adfb61e67435d1998cf5

In order results we return the name of NCBIGene:23221 as "Genetic locus associated with RHOBTB2"
https://arax.ncats.io/?term=NCBIGene:23221
I seem to recall that we programmically insert "Genetic locus associated with" in cases where the NCBIGene entity is named after a disease or something. I forget details now exactly, but I thought somehow we had some NCBIGene entries that were named something like "Huntington disease" and the gene would get conflated with the disease. And we concluded that the NCBIGene entry was really just an entry for the "Genetic locus associated with disease X"

But if this case it looks to me that a real gene is running afoul of this code gene X is getting turned into "Genetic locus associated with gene X" which is a little silly.

I don't know if this part of the code should be tweaked or if an exception should be made. This gene in particular has come up before in queries.

It might be useful to have an answer for this issue if we get called on it tomorrow.

**Comment by finnagin** [comment]
@edeutsch is this issue okay to close?
