### ISSUE TITLE
Result names not displayed in 1-hop query

### ISSUE THREAD

**Issue by CaseyTa** [RTXteam/RTX#1669]
In [Workflow Query B.3a](https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowB/B.3a_DILI-fourth-one-hop-from-CHEBI:41879_Dexamethasone.json) (copied below), COHD and MolePro provide results, but the results shown in ARAX UI only show "Result 1", "Result 2", etc. 

https://arax.ncats.io/?source=ARS&id=402bcdbf-84e0-485f-ae56-0adea2734f69

This is a simple one-hop query with one fixed node and one open node:
```
{
	"message": {
		"query_graph": {
			"nodes": {
				"n0": {
					"ids": ["CHEBI:41879"],
					"categories": [
						"biolink:ChemicalEntity"
					]
				},
				"n1": {
					"categories": [
						"biolink:DiseaseOrPhenotypicFeature"
					]
				}
			},
			"edges": {
				"e0": {
					"subject": "n0",
					"object": "n1",
					"predicates": ["biolink:has_real_world_evidence_of_association_with"]
				}
			}
		}
	}
}
```

**Comment by CaseyTa** [comment]
[Workflow Query B.4a](https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowB/B.4a_DILI-fourth-one-hop-from-CHEBI:41879_Dexamethasone.json) is the same query, except with `biolink:related_to` as the predicate. This also has results from Aragorn and Improving Agent. Results from Improving Agent also don't show names (trying to load results from Aragorn killed my browser). 

https://arax.ncats.io/?source=ARS&id=457a61c1-feb4-4437-a787-96bbaaf4b6e9

**Comment by isbluis** [comment]
Hi @CaseyTa .  We have identified and fixed the issue; the next release of the UI will contain this fix.  In the meantime, you can view results using my dev area (which is prone to occasional  dev-related failures) :

https://arax.ncats.io/devLM/index.html?source=ARS&id=0d43fe3d-c9a3-4d24-aa01-5d1046f98b93

Thanks for reporting this!

**Comment by CaseyTa** [comment]
Excellent! Thanks, @isbluis, for the quick resolution! The results look great, and I didn't encounter any dev-related failures ^_^

**Comment by isbluis** [comment]
Great, thank you for having a look and verifying!  I'll update here when the new version has been released.

**Comment by isbluis** [comment]
This has been now released to our production server, @CaseyTa :  https://arax.ncats.io/

Please let us know if the issue persists, or otherwise ok to close the issue.

**Comment by CaseyTa** [comment]
@isbluis Looks good, thanks!
