### ISSUE TITLE
Are Q24 and Q27 really any different?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#167]
Our example Q24: What drugs target proteins expressed in the retina? 
Our example Q27: What drugs target proteins associated with the kidney?

i.e. is "expressed in" and "associated with" really different?

Also, in the answers, there's an extra apostrophe:
The chemical_substance azelaic acid involves similar protein's as kidney with similarity value 0.004783

Although trivial, maybe there's an easy fix. For many of these questions (which is presumably calling the same script), the confidence scores are super low. For example:
   What drugs target proteins associated with the kidney?
yields an answer that looks pretty good (to a coder that doesn't know a lectin from a tomato)
but yet the confidence is 0.04. Bug or feature?

**Comment by dkoslicki** [comment]
1. Apostrophe issue has been fixed.
2. Q27 has been removed from ``Questions.tsv`` a while ago due to this exact reason. Don't know why it wasn't updated in ``QuestionExamples.tsv``
3. The "confidence" is merely the Jaccard index: so in this case, while the results look good, they don't actually share a lot of bioentities in common. I didn't/don't see any other way to shoe-horn a confidence score here except perhaps some transformation of the Jaccard index.

**Comment by dkoslicki** [comment]
Closing as addressed (unless anyone has good ideas in using something besides Jaccard for confidence).

**Comment by edeutsch** [comment]
Well, I've got ideas.

1) The easiest idea is to limit the numerator to the smaller of the two sets. Most drugs probably target a limited number of proteins. Most tissues probably have thousands of proteins. There seems little point in penalizing the score with the thousands of proteins in each tissue. If all of the protein targets for drug X are all found in tissue Y, it doesn't get any better than that! Call that 100%

**Comment by dkoslicki** [comment]
Makes sense, but actually somewhat difficult to do in code (cypher is computing the intersection directly, so a new command will need to be crafted). I'll make a different issue and mark it for post-hackathon. I hope people aren't taking too seriously the "confidence" scores anyway...

**Comment by edeutsch** [comment]
2. But what we really want is a confidence, not a Jaccard distance, eh? So for the question:
What drugs target proteins expressed in the retina?
the confidence here really is the combination of confidences that a) the proteins are in retina and b) the drug targets that protein.
Right?
So imagine oxybenzone and retina. Let's pretend there are two proteins that overlap: TDP1 and HTT.
If oxybenzone --> TDP1 with P1  (probability or confidence something 0.0-->1.0)
and oxybenzone --> HTT with P2
and retina --> TDP1 with P3
and retina --> HTT with P4
then, I would say the the final confidence is the combined for each protein all combined in quadrature, like:
1-1/sqrt( 1/(1-p1*p3)^2 + 1/(1-p2*p4)^2 )
eh?

**Comment by edeutsch** [comment]
so really the answer is probably always 1.00. Because all it takes is 1.
Maybe a better question (and what you're actually answering) is: Which drugs target **the most** proteins expressed in the retina?
