### ISSUE TITLE
Increase timeout (or make it user-specifiable)

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1670]
From @rtroper:
>Submitting workflow query C.1a directly to BTE (https://api.bte.ncats.io/v1/query) or the clinical risk KP endpoint (https://api.bte.ncats.io/v1/smartapi/d86a24f6027ffe778f84ba10a7a1861a/query) yields results in about 5 seconds. When submitted to the ARS, expected results from the clinical risk KP are returned via BTE, but not ARAX.

>For workflow C, we're interested in the ranked results from clinical KPs that ARAX provides. However, a timeout of 30 seconds is imposed and this does not end up being enough to get the results back from the clinical risk KP.

>Below, is what we see when submitting the query directly to ARAX. I noticed in the status description (while waiting for results) that the query is submitted to the KPs/ARAs with 18 curies (presumably as a result of expanding the curie to synonyms). Perhaps the delay in getting results back within 30 seconds is due to this batch query. In any case, it seems our KP needs more time to get results back to ARAX. @dkoslicki @edeutsch - Would it be possible to have the timeout cutoff increased? Or would another solution be better?

![image](https://user-images.githubusercontent.com/6362936/134419265-13560742-09f9-45e1-9ccf-d9fd72795d12.png)

Feel free to assign/unassign as appropriate

**Comment by edeutsch** [comment]
Feature allowing the user to specify a longer (or shorter) timeout is implemented and rolled out to production. Under the Settings tab, you can do:
![image](https://user-images.githubusercontent.com/12707718/134743539-9fb0ef79-081c-41b8-95ce-332a255ff604.png)
and this will affect all remote KP timeouts:
![image](https://user-images.githubusercontent.com/12707718/134743590-65252c1e-428b-4d44-840e-644013cffe05.png)
If you like it, close it!
Thanks to @amykglen and @isbluis for making it happen to rapidly!

**Comment by dkoslicki** [comment]
Awesome! That was quick, thanks all!

**Comment by rtroper** [comment]
Very cool! Looking forward to trying it out.

**Comment by amykglen** [comment]
@edeutsch - all pytests started failing for me I think after your above commit - this is the error (ARAXQuery.py line 603):
```
  - 2021-09-24T15:25:44.428523 INFO: [] Processing action 'add_qedge' with parameters {'subject': 'n00', 'object': 'n01', 'key': 'e00', 'predicates': 'biolink:affects'}
  - 2021-09-24T15:25:44.428553 INFO: [] Adding a QueryEdge to Message with parameters {'key': 'e00', 'subject': 'n00', 'object': 'n01', 'predicates': 'biolink:affects', 'option_group_id': None, 'exclude': None}
  - 2021-09-24T15:25:44.428580 INFO: [] Processing action 'expand' with parameters {'kp': 'RTX-KG2'}
  - 2021-09-24T15:25:44.428918 ERROR: [UncaughtARAXiError] An uncaught error occurred: argument of type 'NoneType' is not iterable: ['Traceback (most recent call last):\n', '  File "/Users/amyglen/Projects/RTX-A1/RTX/code/ARAX/test/../ARAXQuery/ARAX_query.py", line 605, in execute_processing_plan\n    if \'kp_timeout\' in response.envelope.query_options:\n', "TypeError: argument of type 'NoneType' is not iterable\n"]
```

**Comment by edeutsch** [comment]
yikes! sorry! fixed! I hope?

**Comment by amykglen** [comment]
yes, seems to be working now!
