### ISSUE TITLE
ARS broken in UI?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1673]
To reproduce, go to the ARAX UI, click on JSON, click on example, then submit to the ARS. After a bit, you'll see the message:
```
Posting JSON. Looking for answer...
- contacting ARS...
- ERROR:: TypeError: Failed to fetch
```
Is this our error, or the ARS's?

**Comment by dkoslicki** [comment]
Ok, might be their issue: due to the great new `settings` feature from @isbluis , the error occurs if you use `https://ars.ci.transltr.io/ars/api/submit` for the ARS, but not if you use `https://ars.transltr.io/ars/api/submit`. Do we want to avoid the ITRB instance as default, or alert Trung/Mark/et al.?

**Comment by edeutsch** [comment]
I think Trung/Mark are aware that it's broken. It's been broken for a long time.
I seems that most people are using ars-dev.transltr.io (see https://arax.ncats.io/devLM/?recent=1)
I didn't think that was really supposed to be the default, but if that's what's working and what is being used, I suppose we might as well just go ahead and make that the default.

**Comment by edeutsch** [comment]
oops, I was wrong. ars-dev is only for use with /asyncquery.

https://ars.transltr.io/ars/api/submit
is correct.

In other news, I have figured out how to detect the main ARS in the activity log so that will begin showing up there now I hope.

**Comment by isbluis** [comment]
I have updated the default ARS url to:  `https://ars.transltr.io/ars/api/submit`

https://arax.ncats.io/devLM/index.html

Will be in the next UI release.  Thanks, @dkoslicki !

**Comment by isbluis** [comment]
This has been now released to our production server, @dkoslicki  :  https://arax.ncats.io/

Please let us know if the issue persists, or otherwise ok to close the issue.

**Comment by dkoslicki** [comment]
Looks good to me (no more error)! One quibble though: the new button reads “Post to other TRAPI”, did you intend “post to other API” instead?

**Comment by isbluis** [comment]
I think this wording was suggested by @edeutsch -- perhaps to underscore that we only support TRAPI responses?
But easy to change to whatever makes most sense.

**Comment by dkoslicki** [comment]
Hmmm… I think that may cause confusion: I was thinking to myself “other TRAPI? Is this meant for a different version of TRAPI, or perhaps some non-NCATS TRAPI thing I’m not aware of?”

IMHO, something like “Post TRAPI to other API” might work. Even “Post to other API” would make sense given the directions on the top making it clear only TRAPI (or parts thereof) should be entered in the field.

**Comment by edeutsch** [comment]
"Post to other API" is fine with me. Although "Other API" makes me think of a "non-TRAPI API"
I was trying to think of a succinct way of saying "Post to a non-ARAX TRAPI-supporting API endpoint"
and ended up at "Post to other TRAPI"
maybe "Post to other TRAPI endpoint" would be clearer?
maybe "Post to non-ARAX TRAPI endpoint" would be clearer?
I dunno, whatever you think is clearest is fine with me.

**Comment by isbluis** [comment]
I have updated the buttons to read "Post to OTHER" / "Query OTHER" and added mouse-over descriptive text.
Hopefully this, as well as context from other buttons will help avoid confusion.

**Comment by edeutsch** [comment]
good. deployed. closing.
