### ISSUE TITLE
Battle vs. the web crawlers

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1678]
Hi everyone, it seems that the heavy load problems that we've been having is due to web crawlers. Somehow web crawlers are posting QueryGraphs to /query with great exuberance and highly stressing and/or killing over services.

1) Based on limited data, it appears that we are no longer suffering from host OS freezes (yay!)
2) However, we may have traded that in for production service deaths. Twice now the production service (and maybe kg2 too?) has been found stopped. This has never happened before and appears to be new behavior
3) I have added several more blocked IPs in the nginx config:
```
        deny 66.27.73.63;
        deny 18.236.105.98;
        deny 54.149.211.163;
        deny 76.119.57.87;
        deny 35.161.155.225;
```
but they are starting to sprout quite prodigiously and it is hard to react to these.
Additional hands and ideas on keeping these problems out would be most welcome.

a substantial problem is that IP addresses are not visible inside the docker container. It would be really readly super if someone can figure out how to make IP addresses visible inside the contain, because then it would be easier to write code that reacts to these web crawlers and denies them.

**Comment by finnagin** [comment]
@edeutsch is this issue okay to close?

**Comment by edeutsch** [comment]
okay to close.
