### ISSUE TITLE
Status and plans of constraint support?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1682]
Something I forgot to ask at today's AHM:

What is the current state and plans for constraint support?
- I know that we support ChemicalEntity drug approval status (correct?)
- Do we support KP selection via constraints?
- Do we support or have plans to support any additional constraints?
- I'm trying to think of some other compelling constraints that we could support but coming up a little dry
- We could do an NGD constraint, e.g. NGD < 0.5 or something. But that would be in the Overlay step not in the Expand step. And it's not quite clear what that means exactly. If the NGD for a pair of nodes is 0.51, do we delete just the NGD edge? or do we also delete all edges between those two nodes?

Mostly wondering if there's a roadmap that we should ponder.

**Comment by finnagin** [comment]
@edeutsch is this still relevant?

**Comment by edeutsch** [comment]
No longer relevant, closing.
