### ISSUE TITLE
Make Overlays work if called after `bind` and/or `complete_results` 

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1687]
Goal is to make the following workflow executable with ARAX:
```
fill
bind
complete _results
score
overlay_ngd
```
Don't nuke existing results, merely add the new edges that `overlay` generates to both the results and the KG, as well as add the Qedge in the QG.

**Comment by finnagin** [comment]
Verified that this is now working: https://arax.ncats.io/?r=31268
