### ISSUE TITLE
Why don't we reference the `request_body` parameter at this line in the query_controller.py code?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1688]
In `query_controller.py`, even though a parameter `request_body` of type `Dict[str]` is passed, we use the member variable `connexion.request` to get the query information in JSON format. Please pardon my ignorance; I am wondering, why bypass the function parameter?  (I am trying to better educate myself about how connexion/flask work). Hope it is OK to pose this as an issue, just so I won't forget to ask about it later.

https://github.com/RTXteam/RTX/blob/ff9f6687dbfbe3f9550b841ae476c035b74697e7/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py#L27

**Comment by edeutsch** [comment]
Unfortunately any possible logical reason for this is lost to me. It is possible that there is some benefit to doing it this way over using json.loads(). It does avoid needing to import another module (json), but that seems minor. I don't know. I suspect there may be some fancy internal functionality that connexion gives you that the equivalent
```
import json
query = json.loads(request_body)
```
doesn't. I don't know.

https://connexion.readthedocs.io/en/latest/request.html

**Comment by edeutsch** [comment]
The fancy OO methods also gives you access to the HTTP headers and such

**Comment by saramsey** [comment]
Thanks.

**Comment by edeutsch** [comment]
seems like this can be closed.
