### ISSUE TITLE
Issue with canonical, non-canonical, and asymmetric predicates

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1689]
From Chris Bizon:
>Hi all - I am trying to merge a couple of queries for workflow A. (this and this ).   The problem is that the canonical versions of the predicates point in different directions.   So to get them to point the same way (for combining into a single query) I have to de-canonicalize one predicate, causing ARAX to throw a 400.  Any chance of ARAX loosening that requirement?

Here's the query:
```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "object": "n0",
                    "subject": "n1",
                    "predicates": [
                        "biolink:entity_negatively_regulates_entity",
                        "biolink:decreases_abundance_of",
                        "biolink:decreases_expression_of",
                        "biolink:decreases_stability_of",
                        "biolink:decreases_uptake_of",
                        "biolink:increases_degradation_of",
                        "biolink:decreases_synthesis_of",
                        "biolink:decreases_activity_of",
                        "biolink:response_affected_by"
                    ]
                }
            },
            "nodes": {
                "n0": {
                    "ids": [
                        "NCBIGene:23221"
                    ],
                    "categories": [
                        "biolink:Gene"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:SmallMolecule"
                    ]
                }
            }
        }
    }
}
```
Which returns the error message: `Qedge e01 has asymmetric predicates in both canonical and non-canonical forms, which isn't allowed. Non-canonical asymmetric predicates are: {'biolink:response_affected_by'}`

I can't find this error message in the codebase, so don't know if it's an ARAX, RTX-KG2, or plover thing.

Is this desired behavior, or is there anything we want to address this? The issue appears to be predicates on the edge which are descendants of `affects` as well as `affected_by`.

**Comment by amykglen** [comment]
this might be a good issue for discussion - it's surprisingly tricky to address (I think Expand would have to split the qedge into two qedges behind the scenes - one using all but `biolink:response_affected_by` and the other using only `biolink:affects_response_to`, but with flipped subject/object - run queries for those two qedges separately, and then merge their answers once done)

the error is coming from `ARAX_expander.py`, by the way: https://github.com/RTXteam/RTX/blob/c3414e766c04669025da55170c241c732bf52f16/code/ARAX/ARAXQuery/ARAX_expander.py#L197-L199

and for those who aren't aware: technically we're not _required_ to support usage of non-canonical predicates in QGs, though it definitely may be in our interest to do so. currently we do support usage of non-canonical predicates, except for in twisted situations such as this one where Expand can't work out how to handle it without splitting the qedge in two.

**Comment by cbizon** [comment]
Any further thoughts on this?  It would be nice to be able to merge two of the workflow A queries.

**Comment by edeutsch** [comment]
I think this was addressed years ago. closing.
