### ISSUE TITLE
Suggested Q39 returns Sorry

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#169]
Our suggested Q39:
What conditions are commonly treated by norepinephrine in any form?
first of all is restated as:
What conditions are most frequently treated by norepinephrine?
which I'm I'm uncertain if that is precisely the same question.. (I suppose it is, except in the first case there is an explicit acknowledgement that there may be several forms and RTX should not ask for possible clarification)

but in any case, the answer returned is:
Sorry, Columbia Open Health Data has no data on the use of norepinephrine

can we find a better example? or fix a possible glitch that is preventing a good example from working?

**Comment by dkoslicki** [comment]
I removed the example questions causing the issue. Has to do with the NLP. Will address post-hackathon (for now, everything is to be "in any form").
