### ISSUE TITLE
Delete module code/ARAX/ARAXQuery/response.py

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1690]
Per this comment:

https://github.com/RTXteam/RTX/issues/1680#issuecomment-932647667

I have tested deletion of `response.py` in the `fork-test` DEVAREA on https://arax-backup.rtx.ai/  and it seems to not break anything.

**Comment by saramsey** [comment]
fixed in master branch, in a14b1b6

**Comment by edeutsch** [comment]
deployed everywhere and no problems observed.

**Comment by saramsey** [comment]
also the test suite looked good, FWIW
