### ISSUE TITLE
modify Flask query_controller.py to use fork internally

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1691]
This is a follow-up to #1680.

To restate the purpose, executing the ARAXQuery inside a child process will hopefully prevent cumulative memory bloat/leakage in the query controller process.

**Comment by saramsey** [comment]
doing this work in [branch `fork-test`](https://github.com/RTXteam/RTX/tree/fork-test)

**Comment by saramsey** [comment]
OK, commits e55840c and 2bc7e1b (in the [`fork-test` branch](https://github.com/RTXteam/RTX/tree/fork-test)) implement the changes to make `query_controller.py` use an internal Linux `fork()` to create a child process, carry out all of the query operations within the child process, and communicate the results back to the parent process via a POSIX pipe. In my testing, it works with both streaming and non-streaming queries. I've tested it using both a command-line script that queries the API using `curl` (specifically, that script is inside the `rtx1` Docker container on `arax-backup.rtx.ai` and it is located in `/mnt/data/orangeboard/fork-test/run-curl.sh`. Its contents are:
```
#!/usr/bin/env bash
curl -X POST "https://arax-backup.rtx.ai/fork-test/api/arax/v1.2/query" \
     -H "accept: application/json" \
     -H "Content-Type: application/json" \
     -d @kg2-test2.json
```
whereas the file `kg2-test2.json` is in the same directory and contains:
```
{
    "message": {},
    "operations": {
	"operations": 	{
	    "actions": [
		"add_qnode(ids=[CHEMBL.COMPOUND:CHEMBL112], key=n00)",
		"add_qnode(ids=[UniProtKB:P55000], key=n01)",
		"add_qedge(subject=n00, object=n01, key=e00)",
		"expand(edge_key=e00,kp=RTX-KG2)",
		"resultify()",
		"return(message=true, store=false)"
	    ]
	}
    },
    "submitter": "sramsey via fork-test curl script (issue 1680)",
    "stream_progress": true
}
```

I've also tested these code modifications by adapting the `query_controller.py` script to run in command-line mode, like this (all commands inside the `rtx1` Docker container as user `rt`)
```
cd /mnt/data/orangeboard/fork-test/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers
python3.7 query_controller.py
```
which uses streaming by default (but can be switched to non-streaming by changing `_stream` to `_nonstream` on [line 94 of that python module](https://github.com/RTXteam/RTX/blob/2bc7e1b77069f1bd921615cf5cd9d0beec0eab8f/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py#L94).

In addition, I've tested these code modifications using the ARAX browser UI, by pointing the browser to `https://arax-backup.rtx.ai/fork-test`. The code for the `fork-test` DEVAREA on that ARAX server instance is set to the `fork-test` git branch, with the only modifications being that it is using TCP port 5010 (thus there is a one-line change to `__main__.py`) and `production` is set to False in `RTXConfiguration.py`, just as in the `devED` DEVAREA on the same ARAX server.

I could use some help in testing out this code. Thank you!

**Comment by saramsey** [comment]
Some technical notes. First, I found it in`__main__.py` to install signal handlers for `SIGCHLD` and `SIGPIPE`. Second, I had to temporarily install some connexion/Flask logging code (in `__main__.py`) in order to see what was going on before ARAXQuery is instantiated (and thus, before ARAX logging kicks in). That logging code has been removed but you'll see it in the commit history for `__main__.py` in the `fork-test` branch.

**Comment by saramsey** [comment]
You can verify that `arax-backup.rtx.ai/forktest` is running exactly the code in the `fork-test` branch except for the aforementioned changes, by doing a `git status` and a `git diff` inside the container as user `rt` in the `/mnt/data/orangeboard/fork-test/RTX` directory:
```
rt@5d5ebba937d1:/mnt/data/orangeboard/fork-test/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers$ git status
On branch fork-test
Your branch is up-to-date with 'origin/fork-test'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ../../../../../RTXConfiguration.py
	modified:   ../__main__.py
	modified:   ../openapi/openapi.yaml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	../../../../../ARAX/ARAXQuery/Overlay/ngd/curie_to_pmids_v1.0_KG2.7.3.sqlite
	../../../../../ARAX/ARAXQuery/Overlay/predictor/retrain_data/GRAPH_v1.0_refreshed_KG2.7.3.sqlite
	../../../../../ARAX/ARAXQuery/fork_example.py
	../../../../../ARAX/ARAXQuery/test_fork.py
	../../../../../ARAX/KnowledgeSources/COHD_local/data/COHDdatabase_v1.0_KG2.7.3.db
	../../../../../ARAX/KnowledgeSources/KG2c/
	../../../../../ARAX/KnowledgeSources/NormalizedGoogleDistance/
	../../../../../ARAX/KnowledgeSources/Prediction/
	../../../../../ARAX/KnowledgeSources/db_versions.json
	../../../../../ARAX/KnowledgeSources/fda_approved_drugs_v1.0_KG2.7.3c.pickle
	../../../../../ARAX/KnowledgeSources/meta_kg_v1.0_KG2.7.3c.json
	../../../../../ARAX/NodeSynonymizer/category_manager.cache.sqlite
	../../../../../ARAX/NodeSynonymizer/node_synonymizer_v1.0_KG2.7.3.sqlite
	../../../../../ARAX/ResponseCache/ResponseCache.sqlite
	../../NGDCache.sqlite
	../../QueryMeSH.requestCache.sqlite
	../../RTX_OpenAPI_fork-test
	../../RTX_OpenAPI_fork-test.start
	../../cache.sqlite
	../__main__.py.SAVE
	query_controller.py.SAVE
	../openapi/openapi.yaml.SAVE
	../../orangeboard.sqlite
	../../../../../autocomplete/autocomplete_v1.0_KG2.7.3.sqlite
	../../../../../../data/responses_1_0/
```
and the `git diff`:
```
diff --git a/code/RTXConfiguration.py b/code/RTXConfiguration.py
index 519dcad..6cbf9c0 100644
--- a/code/RTXConfiguration.py
+++ b/code/RTXConfiguration.py
@@ -45,7 +45,7 @@ class RTXConfiguration:
         self.is_production_server = False
         if ( ( 'HOSTNAME' in os.environ and os.environ['HOSTNAME'] == '6d6766e08a31' ) or
             ( 'PWD' in os.environ and 'mnt/data/orangeboard' in os.environ['PWD'] ) ):
-            self.is_production_server = True
+            self.is_production_server = False


     # ### Define attribute version
diff --git a/code/UI/OpenAPI/python-flask-server/openapi_server/__main__.py b/code/UI/OpenAPI/python-flask-server/openapi_server/__main__.py
index 761139f..a99d1e4 100644
--- a/code/UI/OpenAPI/python-flask-server/openapi_server/__main__.py
+++ b/code/UI/OpenAPI/python-flask-server/openapi_server/__main__.py
@@ -27,7 +27,7 @@ def main():
     CORS(app.app)
     signal.signal(signal.SIGCHLD, receive_sigchld)
     signal.signal(signal.SIGPIPE, signal.SIG_DFL)
-    app.run(port=5001, threaded=True)
+    app.run(port=5010, threaded=True)


 if __name__ == '__main__':
diff --git a/code/UI/OpenAPI/python-flask-server/openapi_server/openapi/openapi.yaml b/code/UI/OpenAPI/python-flask-server/openapi_server/openapi/openapi.yaml
index 6402da0..c1a6c98 100644
--- a/code/UI/OpenAPI/python-flask-server/openapi_server/openapi/openapi.yaml
+++ b/code/UI/OpenAPI/python-flask-server/openapi_server/openapi/openapi.yaml
@@ -48,22 +48,22 @@ externalDocs:
   url: https://github.com/NCATSTranslator/ReasonerAPI
 servers:
 - description: ARAX Translator Reasoner API
-  url: https://arax.ncats.io/api/arax/v1.2
+  url: https://arax.rtx.ai/fork-test/api/arax/v1.2
 tags:
     description: Documentation for the reasoner predicates function
-    url: http://arax.ncats.io/overview.html#predicates
+    url: http://arax.rtx.ai/fork-test/overview.html#predicates
   name: meta_knowledge_graph
 - description: Initiate a query and wait to receive the response
   externalDocs:
     description: Documentation for the reasoner query function
-    url: http://arax.ncats.io/overview.html#query
+    url: http://arax.rtx.ai/fork-test/overview.html#query
   name: query
 - description: Initiate a query with a callback to receive the response
   externalDocs:
     description: Documentation for the reasoner asynchquery function
-    url: http://arax.ncats.io/overview.html#asyncquery
+    url: http://arax.rtx.ai/fork-test/overview.html#asyncquery
   name: asyncquery
 - description: Required for SmartAPI validation of x-translator
   name: translator
@@ -72,28 +72,28 @@ tags:
 - description: Request a previously stored response from the server
   externalDocs:
     description: Documentation for the reasoner response function
-    url: https://arax.ncats.io/overview.html#response
+    url: https://arax.rtx.ai/fork-test/overview.html#response
   name: response
 - description: Translate natural language question into a standardized query
   externalDocs:
     description: Documentation for the reasoner translate function
-    url: https://arax.ncats.io/overview.html#translate
+    url: https://arax.rtx.ai/fork-test/overview.html#translate
   name: translate
 - description: Return identifier and type of some entity in the knowledge graph
   externalDocs:
     description: Documentation for the reasoner entity function
-    url: https://arax.ncats.io/overview.html#entity
+    url: https://arax.rtx.ai/fork-test/overview.html#entity
   name: entity
 - description: Return a list of example questions that the reasoner can answer
   externalDocs:
     description: Documentation for the reasoner exampleQuestions function
-    url: https://arax.ncats.io/overview.html#exampleQuestions
+    url: https://arax.rtx.ai/fork-test/overview.html#exampleQuestions
   name: exampleQuestions
 - description: Query to get the Normalized Google Distance between two MeSH terms
     based on co-occurance in all PubMed article annotations
   externalDocs:
     description: Documentation for the reasoner PubmedMeshNgd function
-    url: https://arax.ncats.io/overview.html#PubmedMeshNgd
+    url: https://arax.rtx.ai/fork-test/overview.html#PubmedMeshNgd
   name: PubmedMeshNgd
 - description: Return status information about the endpoint
   name: status
@@ -658,7 +658,7 @@ components:
         tool_version: ARAX 0.8.0
         context: https://rtx.ncats.io/ns/translator.jsonld
         reasoner_id: ARAX
-        id: https://arax.ncats.io/api/rtx/v1.2/response/123
+        id: https://arax.rtx.ai/fork-test/api/rtx/v1.2/response/123
         logs:
         - code: code
           level: ""
.....
```

**Comment by saramsey** [comment]
Note, this code runs python 3.7.4 internally, just as the root DEVAREA `https://arax-backup.rtx.ai` does.

**Comment by saramsey** [comment]
Note, the `end=""` was _really_ important here: 
https://github.com/RTXteam/RTX/blob/0ba6725fc3f80cf3b0eb70d99b83bf64f16646a9/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py#L36

or else we get JSON parsing errors, but that only show up when I run the code via the ARAX browser UI (so this is an example of where it was very helpful to have introduced a "command-line" testing option for `query_controller.py`).

**Comment by saramsey** [comment]
This code:
https://github.com/RTXteam/RTX/blob/0ba6725fc3f80cf3b0eb70d99b83bf64f16646a9/code/UI/OpenAPI/python-flask-server/openapi_server/__main__.py#L28

seems to be needed to avoid accumulation of zombie processes. And it has to be in `__main__` or else you will get errors that you can't install a signal handler except in the "main thread" (probably because we are running Flask with `threading=True`).

**Comment by saramsey** [comment]
This code:
https://github.com/RTXteam/RTX/blob/0ba6725fc3f80cf3b0eb70d99b83bf64f16646a9/code/UI/OpenAPI/python-flask-server/openapi_server/__main__.py#L29

is to guard against uncaught `SIGPIPE` exceptions. We are currently just using the default handler in which the signal is ignored. Perhaps we should consider logging it if this occurs with any regularity; that could be done with a custom handler. This `signal.signal` call needs to be in `__main__` for the same reason the `signal.signal` call for `SIGCHLD` needs to be in` __main__` (see above).

**Comment by saramsey** [comment]
I suggest we keep this code for testing purposes, if possible:
https://github.com/RTXteam/RTX/blob/0ba6725fc3f80cf3b0eb70d99b83bf64f16646a9/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py#L78-L95

I managed to fix a bunch of bugs by using this feature to run `query_controller.py` at the command-line.

**Comment by saramsey** [comment]
This comment is a bit redundant, because the question has already been answered in [Issue 1688](https://github.com/RTXteam/RTX/issues/1688). We could probably remove the comment:
https://github.com/RTXteam/RTX/blob/0ba6725fc3f80cf3b0eb70d99b83bf64f16646a9/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py#L59

**Comment by saramsey** [comment]
So, the parentheses and comma here are important:
https://github.com/RTXteam/RTX/blob/0ba6725fc3f80cf3b0eb70d99b83bf64f16646a9/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py#L22

I am turning the JSONified `response.Response` object into a one-element tuple, which meets our requirements of the return value for the function being an `Iterable[str]` type.

**Comment by saramsey** [comment]
In the end, I realized we only needed a Linux pipe, not a named pipe:
https://github.com/RTXteam/RTX/blob/0ba6725fc3f80cf3b0eb70d99b83bf64f16646a9/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py#L29

A named pipe is more specialized like for cases where multiple processes need to access it, like the "mailbox" abstraction in the VMS operating system (yes I really am that old).

**Comment by saramsey** [comment]
It's very important not to use a `with` block here:
https://github.com/RTXteam/RTX/blob/0ba6725fc3f80cf3b0eb70d99b83bf64f16646a9/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py#L40

otherwise it will close the file at the end of the block, which is definitely not what we want in the case of streaming!

**Comment by saramsey** [comment]
h/t to @edeutsch for telling me how to do DSL like this:
https://github.com/RTXteam/RTX/blob/0ba6725fc3f80cf3b0eb70d99b83bf64f16646a9/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py#L87

which enabled me to specify _only_ the RTX-KG2 KP. That made the "minimum test" query go *much* faster, which saved me countless hours in debugging. Thank you sir!

**Comment by saramsey** [comment]
If running at the command-line, we don't have `__main__.py` being run, so need to handle the signal ourselves:
https://github.com/RTXteam/RTX/blob/0ba6725fc3f80cf3b0eb70d99b83bf64f16646a9/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py#L80

Hmm, there is no `SIGCHLD` handler so that might leave a zombie process, but only when the script is run at the command-line in testing, so we probably don't care (do we?).

**Comment by saramsey** [comment]
The `next` here is because we put the JSONified `response.Response` object into a single-element tuple:
https://github.com/RTXteam/RTX/blob/0ba6725fc3f80cf3b0eb70d99b83bf64f16646a9/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py#L72

**Comment by saramsey** [comment]
Have submitted this as a PR #1692.

**Comment by saramsey** [comment]
Note that the use of `os._exit(0)` here is quite intention, and (I believe) correct vs. using `exit` or `sys.exit`.
https://github.com/RTXteam/RTX/blob/0ba6725fc3f80cf3b0eb70d99b83bf64f16646a9/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py#L37

https://www.geeksforgeeks.org/python-os-_exit-method/

**Comment by edeutsch** [comment]
I'm overwhelmed by the sheet volume of it all for the moment, but I'll get to it eventually, thanks!

**Comment by edeutsch** [comment]
> Note that the use of `os._exit(0)` here is intentional, and (I believe) correct vs. using `exit` or `sys.exit`.
> 
> https://github.com/RTXteam/RTX/blob/0ba6725fc3f80cf3b0eb70d99b83bf64f16646a9/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py#L37
> 
> https://www.geeksforgeeks.org/python-os-_exit-method/

I don't think I fully understand, but will assume you're right. A relevant question then is should this code:
https://github.com/RTXteam/RTX/blob/a14b1b65babd08546fbbdf668978855538f18bc3/code/ARAX/ARAXQuery/ARAX_query.py#L789
also use os._exit(0)?
Do you understand enough to know? This is for /asyncquery

**Comment by saramsey** [comment]
> Do you understand enough to know? This is for /asyncquery

If line 789 is only in the client process (which I assume it is; can't imagine why we would exit in the parent process), then I think the answer is "yes". My reasoning is that we don't want to close down resources that the parent process may still need, and that got copied with the fork (e.g.,  Flask app resources?). TBH I don't fully understand it, but everyone says "use os._exit in a fork".
