### ISSUE TITLE
Change how we handle SemMedDB edges in ranking

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1695]
SemMedDB seems to be returning lots of odd edges and bad results that get pushed higher in rankings.

Lots of potential options to address this:
 - [x] Use subject and object confidence scores in ranking
 - [ ] Use [subject and object novelty](https://github.com/RTXteam/RTX/issues/1684) in ranking
 - [x] [Condense SemMedDB edges](https://github.com/RTXteam/RTX/issues/1658) into one edge
 - [ ] SemMedDB antonym handling

**Comment by finnagin** [comment]
Should look into averaging semeddb edge publication counts using:
- harmonic mean
- geometric mean
- median
- arithmetic mean
- L-infinity

**Comment by dkoslicki** [comment]
On branch [issue1695](https://github.com/RTXteam/RTX/compare/issue1695). Should test out the different averaging methods when combining multiple SemMedDB edges and see which ones we like. Issue #1684 is needed for the other items

**Comment by dkoslicki** [comment]
Closing as @mfl15 's approach for filtering SemMedDB will likely fix this issue
