### ISSUE TITLE
RHOBTB2 has mangled name?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1699]
One of the workflow queries that keeps coming up very often involves RHOBTB2. For example:
https://togithub.com/NCATSTranslator/testing/issues/123

In ARAX's result:
https://arax.ncats.io/?r=29560
The name for NCBIGene:23221 is given as "Genetic locus associated with RHOBTB2"
https://arax.ncats.io/?term=NCBIGene:23221

I vaguely recall that there was code inserted into the KG2 build process that tried to find NCBIGene curies that were actually genetic diseases and we prepended "Genetic locus associated with " in front of the disease name. But it looks like we went too far.

Maybe this is something that could be fixed systematically.

Maybe this is just something that we should patch for the one gene because it is coming up all the time.

Or maybe no one else thinks this is weird enough to fix.

**Comment by saramsey** [comment]
Logged as [RTX-KG2 issue 164](https://github.com/RTXteam/RTX-KG2/issues/164).

**Comment by finnagin** [comment]
Closing as this has been moved to the KG2 repo
