### ISSUE TITLE
Try to run workflow B.1 and not have it explode

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1703]
query: https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowB/B.1_DILI-three-hop.json

1. For edge e1 filter on attribute provided by COHD and ICEES
2. Go through edge by edge experimenting with overlaying fisher exact, Jaccard, and ngd as well as filtering on those
3. Experiment with adding in is_set = True

**Comment by finnagin** [comment]
@dkoslicki does this issue do a good job of capturing what you were requesting at the OW meeting?

**Comment by edeutsch** [comment]
Workflow B.1 seems to run fine with the recent changes and tests, so I think this can be closed? @finnagin ?
