### ISSUE TITLE
Node categories missing in "Build-a-DSL"

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1706]
To reproduce: go to arax.ncats.io, click "DSL", select "add_qnode" and note there is nothing in the "categories" dropdown. Predicates appear to be unaffected.

**Comment by edeutsch** [comment]
There was a plan the next time I'm in tinkering with the API to add a an option to the /meta_knowledge_graph to just provide a slim version of the data. Enough for the build-graph/workflow to work. Hasn't been done yet. That would make it faster.
