### ISSUE TITLE
Okay to make boto3 a requirement?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1707]
I'm testing out some code that will use S3 as the new unified storage medium for stored responses, as proposed at the last RTX hackathon. It uses boto3, which is rather heavyweight I think. I would need to add this to the list of requirements. Is there any concern out there with adding boto3 as a requirement? I could potentially wall it off so that the code that imports and needs boto3 only gets run on servers that identify themselves as deployed servers rather than development instances (i.e. your desktops/laptops). Alternatively if everyone is happy to have boto3 on their machines, then you'd have easy access to all past Responses from your devbox, which hasn't been easy before, because they're all stored on arax.ncats.io. But with this they'd all just be an easy S3 call away from anywhere. What do you think?

**Comment by saramsey** [comment]
Pandas is 96 MB, so boto3 (at 32.7 MB) isn't even cruiserweight, right?
