### ISSUE TITLE
Investigating mysterious KG2 dying issue

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1708]
I was alerted by the watchdog that the KG2 service was dead at 12m. Restarted. The STDERR log was saved here: /tmp/RTX_OpenAPI_kg2.elog-foundDead1

No obvious sign of trauma. In fact, the last records events were quite sedate. Just a lot of checking of /meta_knowledge_graph by some service apparently with a very short memory. Here's what Flask showed for requests:
```
127.0.0.1 - - [21/Oct/2021 06:10:07] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 200 -
127.0.0.1 - - [21/Oct/2021 06:10:07] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 200 -
127.0.0.1 - - [21/Oct/2021 06:10:07] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 200 -
127.0.0.1 - - [21/Oct/2021 06:10:08] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 200 -
127.0.0.1 - - [21/Oct/2021 06:11:28] "POST /api/rtxkg2/v1.2/query HTTP/1.1" 200 -
127.0.0.1 - - [21/Oct/2021 06:19:02] "POST /api/rtxkg2/v1.2/query HTTP/1.1" 200 -
127.0.0.1 - - [21/Oct/2021 06:19:29] "POST /api/rtxkg2/v1.2/query HTTP/1.1" 200 -
127.0.0.1 - - [21/Oct/2021 06:20:05] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 200 -
127.0.0.1 - - [21/Oct/2021 06:20:08] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 200 -
127.0.0.1 - - [21/Oct/2021 06:20:08] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 200 -
127.0.0.1 - - [21/Oct/2021 06:20:08] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 200 -
127.0.0.1 - - [21/Oct/2021 06:30:06] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 200 -
127.0.0.1 - - [21/Oct/2021 06:30:07] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 200 -
```

Here's what nginx showed:
```
35.161.155.225 - - [21/Oct/2021:06:30:06 +0000] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 200 18045432 "-" "axios/0.21.4"
54.149.211.163 - - [21/Oct/2021:06:30:06 +0000] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 499 0 "-" "axios/0.21.4"
54.189.90.50 - - [21/Oct/2021:06:30:07 +0000] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 502 530 "-" "axios/0.21.4"
52.4.10.150 - - [21/Oct/2021:06:30:07 +0000] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 502 530 "-" "axios/0.21.4"
209.97.185.16 - - [21/Oct/2021:06:34:25 +0000] "GET / HTTP/1.1" 302 170 "http://35.81.149.105:80/left.html" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"
54.189.90.50 - - [21/Oct/2021:06:40:01 +0000] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 503 378 "-" "axios/0.21.4"
35.161.155.225 - - [21/Oct/2021:06:40:02 +0000] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 503 378 "-" "axios/0.21.4"
54.149.211.163 - - [21/Oct/2021:06:40:03 +0000] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 503 378 "-" "axios/0.21.4"
52.4.10.150 - - [21/Oct/2021:06:40:04 +0000] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 503 378 "-" "axios/0.21.4"
```

This is a bit puzzling.

**Comment by saramsey** [comment]
OK, perhaps we should get the specific JSON query that Chunlei's team is running, so we can test it ourselves?

**Comment by edeutsch** [comment]
So it would appear that the KG2 API was running until this request came in:
```
54.149.211.163 - - [21/Oct/2021:20:30:07 +0000] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 200 0 "-" "axios/0.21.4"
35.161.155.225 - - [21/Oct/2021:20:30:08 +0000] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 200 0 "-" "axios/0.21.4"
99.150.229.254 - - [21/Oct/2021:20:30:08 +0000] "GET /api/rtxkg2/v1.2/meta_knowledge_graph HTTP/1.1" 502 530 "-" "python-httpx/0.18.2"
```

at which point it died.

I wonder if high concurrency to the /meta_knowledge_graph endpoint is a killer?

**Comment by edeutsch** [comment]
> OK, perhaps we should get the specific JSON query that Chunlei's team is running, so we can test it ourselves?

All incoming queries are logged here:
https://arax.ncats.io/?recent=1

unless the failure occurs so early that it doesn't reach ARAXQuery.query()

**Comment by edeutsch** [comment]
So the bad news is that the upgrade of packages and Python 3.7.12 did not fix the problem.

But perhaps the good news is that I just switched us back to non-forking mode in test and it still dies. So it would seem that forking is not the source of our problem.

**Comment by saramsey** [comment]
Let's check out `socketio.on('disconnect')`
https://www.reddit.com/r/flask/comments/i7e5rz/af_using_flasksocketio_how_to_correctly_use_a/

**Comment by saramsey** [comment]
OK, so it is looking like  `socketio` will not enable us to immediately detect a client disconnect.

**Comment by saramsey** [comment]
I have managed to reproduce this bug on `arax-backup.rtx.ai` (in the `production` DEVAREA), using the JSON query file `query.json`:
```
{ "stream_progress": true,
  "message": { "query_graph":
{
   "edges": {
      "e00": {
         "subject":   "n00",
         "object":    "n01",
         "predicates": ["biolink:physically_interacts_with"]
      }
   },
   "nodes": {
      "n00": {
         "ids":        ["CHEMBL.COMPOUND:CHEMBL112"]
      },
      "n01": {
         "categories":  ["biolink:Protein"]
      }
   }
}}}
```
and the script `run-test.sh`:
```
#!/bin/bash

curl -s -X POST https://arax-backup.rtx.ai/api/arax/v1.2/query \
     -H  "accept: application/json" \
     -H  "Content-Type: application/json" \
     -d @query.json
```
and the test-running command:
```
bash -x ./run-test.sh | head
```

**Comment by saramsey** [comment]
creating a branch `issue-1708` to work this issue

**Comment by saramsey** [comment]
OK I have switched the `production` DEVAREA on `arax-backup.rtx.ai` to branch `issue-1708`

**Comment by saramsey** [comment]
OK, neither tracing using the `trace` module not setting an exit handler with the `atexit` module in python can catch control before cpython exits. My feeling is that there is something with thread corruption causing instant death of cpython.

Confirming that this bug happens even when Flask is run with threading turned off and even when fork-mode is turned off in `query_controller.py`.

**Comment by saramsey** [comment]
OK, I believe that commit 14575ef fixes the issue.
