### ISSUE TITLE
Need a ranking summary slide for next week's Architecture

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1710]
On today's Architecture Call, the topic of ranking was started, although didn't get too far. Chris Bizon would like to have one slide from each ARA summarizing their ranking strategy.

1. Would someone put together a single slide summarizing ARAX's ranking?
2. Would someone be on hand to present it at next week's Architecture Call (Tuesday 11am)?

I really don't know very much about it in its current form.

**Comment by edeutsch** [comment]
Just a reminder that today at 11a / 2p is the Architecture call where this is meant to be presented

**Comment by dkoslicki** [comment]
Yup, I'm on it!

**Comment by dkoslicki** [comment]
Completed and no longer relevant
