### ISSUE TITLE
Unusual pause in Expansion?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1711]
Marc Duby reported an issue where the traffic light table was showing some long KP query times:
![image](https://user-images.githubusercontent.com/12707718/138953379-f8095450-b593-40f7-b0e7-8c0c51ab36e5.png)

You'll notice that all KPs including RTX-KG2 took at least 60 seconds.

BUT, the weird thing is here:
![image](https://user-images.githubusercontent.com/12707718/138953706-2c7507de-365b-456c-9053-c3205aaebfc6.png)

Although I'm not completely certain, I think the corresponding KG2 query is this:
![image](https://user-images.githubusercontent.com/12707718/138954497-2b8e94f3-c58a-4af1-9f67-240440c9d21d.png)

The first odd thing is that it is only 4 seconds. but the second is that it is only 30 results instead of 14692.

It may be that I'm the one who's confused.
https://arax.ncats.io/?r=30835

```
{
  "edges": {
    "e00": {
      "subject": "n00",
      "object": "n01"
    },
    "e01": {
      "subject": "n01",
      "object": "n02"
    }
  },
  "nodes": {
    "n00": {
      "ids": [
        "DOID:14330"
      ],
      "is_set": false,
      "categories": [
        "biolink:Disease"
      ],
      "name": "DOID:14330"
    },
    "n01": {
      "is_set": false,
      "categories": [
        "biolink:NamedThing"
      ]
    },
    "n02": {
      "ids": [
        "DOID:8778"
      ],
      "is_set": false,
      "categories": [
        "biolink:Disease"
      ],
      "name": "DOID:8778"
    }
  }
}
```

Hmm, so I just ran it again and the same thing happened with the above query.
![image](https://user-images.githubusercontent.com/12707718/138955240-dea67c0d-564f-46f3-85b4-8fe472f4c82d.png)

ARAX didn't send the query for some 80 seconds. And then after sending it, it only took 5 seconds and returned 30 results. but the traffic light says:
![image](https://user-images.githubusercontent.com/12707718/138955440-8a9d6665-12a6-4ccc-bd9b-9357e1ae82c9.png)

ah, I suppose there's a distinction between results and edges, but still, that's a pretty big different.

Something weird is going on, but I'm not quite sure what.

**Comment by finnagin** [comment]
@edeutsch @amykglen is this still relevant or good to close?

**Comment by edeutsch** [comment]
sufficiently stale that I think this is good to close.
