### ISSUE TITLE
divide by zero

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1712]
Observed in the ARAX log:
```
2021-10-27T04:44:43.280477 INFO: [] Summary of available edge metrics: {'feature_coefficient': {'minimum': 0.409, 'maximum': 8.5112}, '
probability': {'minimum': 0.9992597228172253, 'maximum': 0.9992597228172253}, 'fisher_exact_test_p-value': {'minimum': 1.128901511e-314
, 'maximum': 1.127672485123937e-174}, 'normalized_google_distance': {'minimum': 0.18913763263710018, 'maximum': 1.0422377263996836}}
/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_ranker.py:489: 
RuntimeWarning: divide by zero encountered in log
  value = -np.log(value)  # FIXME: could divide by zero
```

**Comment by dkoslicki** [comment]
@edeutsch Do you know what query this was attached to so I can verify it works on prod?

**Comment by edeutsch** [comment]
I do not know. The problem was just by chance observed in the logs and I did not try to determine which query triggered it. If you think it's fixed, it fine to close.

> This is odd: it appears to already be wrapped in a try/except

I'm pretty sure that warnings are not caught by try-except because warnings are not exceptions.

thanks, closing.

**Comment by dkoslicki** [comment]
Oh geeze, I read that as `RuntimeError` not `RuntimeWarning`
