### ISSUE TITLE
Unusual UncaughtARAXiError

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1714]
Noticed in the System Activity logs:

![image](https://user-images.githubusercontent.com/12707718/139106328-1b3fe424-b775-44bd-9bcc-4c9a234bf405.png)

An uncaught error occurred: max() arg is an empty sequence: ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 664, in 

Triggered by this query coming from the ARS:
https://arax.ncats.io/api/arax/v1.2/status?id=48409

**Comment by finnagin** [comment]
Reran that query and it looks like this has been fixed: https://arax.ncats.io/?r=36241
