### ISSUE TITLE
update versions of old modules used by ARAX

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1715]
motivated by boto3 / urllib3 / requests run-time warning (@edeutsch knows the details)

**Comment by finnagin** [comment]
@edeutsch looks like the lockfile version you updated to in the requirements.txt is incorrect. It is [set to version 0.12.6](https://github.com/RTXteam/RTX/blob/2ea6e1f03a436f2bf56213480a60a8978e14946e/requirements.txt#L21) but it looks like in [pypi the newest version is 0.12.2](https://pypi.org/project/lockfile/). Do you mind if I change this or is there something I'm missing and this is the correct version?

**Comment by edeutsch** [comment]
Yes, sorry, looks like I botched it. Thanks for fixing!
