### ISSUE TITLE
ARAX not returning a response for workflow C query

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1718]
This is posted as minihackathon issue: https://github.com/NCATSTranslator/minihackathons/issues/347

The workflow C group is trying to do a query:
https://arax.ncats.io/api/arax/v1.2/status?id=50077

Other ARAs seem to rapidly return a response. ARAX wanders off in the moors for hours. It's still running, having used 40 GB of RAM. I don't actually know where it is stuck, I can't seem to see that.

But I suspect it is stuck in resultify, same problem as this issue #1683

**Comment by saramsey** [comment]
OK, after discussing with @amykglen it sounds like there are potentially two issues here, one issue that the behavior is different when run via asyncquery vs. via sync; and the second issue is NGD using a lot of RAM leading to OOM death. Either way, current thinking seems to be that this issue does not involve resultify (though we are well aware that some queries can lead to resultify memory bloat and OOM death, for example #1683). Please LMK if I have mis-summarized the state of this issue.

**Comment by saramsey** [comment]
> The first slight hint of trouble is:
> sync: 2021-10-29T01:36:34.149058 INFO: BTE: Query for edge e01 completed (e01: 757, n1: 9, n2: 714)
> asyn: 2021-10-29T03:22:43.637429 INFO: [] BTE: Query for edge e01 completed (e01: 1256, n1: 9, n2: 1040)
> (slightly different answer, why is that?)

Doesn't this mean that BTE is simply returning different data when we query them via async vs. sync?  If so, that seems completely testable, with a single-hop query, right?

**Comment by edeutsch** [comment]
> Please LMK if I have mis-summarized the state of this issue.

I think your summary is good. Weird.

> Doesn't this mean that BTE is simply returning different data when we query them via async vs. sync? If so, that seems completely testable, with a single-hop query, right?

I have not tried this, but yes, this would be a good thing to do.

**Comment by amykglen** [comment]
> Doesn't this mean that BTE is simply returning different data when we query them via async vs. sync? If so, that seems completely testable, with a single-hop query, right?

I could be missing something here, but as far as I know `expand` never queries a KP at `/asyncquery` (only at `/query`). so I don't think that should be a factor here?

**Comment by edeutsch** [comment]
Solved and deployed. closing.
