### ISSUE TITLE
literature co-occurence Biolink term

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1725]
Just as a useful transcript for everyone to see. This was a private Slack conversation that should have been public IMO:

![image](https://user-images.githubusercontent.com/12707718/140851351-efeaef3d-2afd-4b6a-b1a2-79385db0e54a.png)

Chris Bizon (SRI, Ranking Agent)  10:38 AM
Aragorn was not yet using the new literature co-occurrence biolink predicate.  So I'm in the process of changing that over, and I'm running into a biolink/trapi mismatch.  In biolink the predicate at hand is: biolink:co-occurs_in_literature_with .
But in TRAPI, the biolink predicates must conform to this regex: ^biolink:[a-z][a-z_]*$, which doesn't allow any non-alphabetic characters (aside from the underscore).

10:38
What's the right place to fix this mismatch?

Sierra Moxon (SRI)  11:04 AM
It seems like we've gone pretty far having no dashes in the model, I can make a change to something like
11:05
biolink:occurs_together_in_literature_with -- will it be ok to put this out in another release of the model (thinking of code freeze here)?
11:06
I'll add a check in the model to remind me of this requirement going forward.
11:06
Is there a technical reason why dashes are excluded from TRAPI?

Chris Bizon (SRI, Ranking Agent)  11:07 AM
Not that I know of... so I think we could choose either direction here & I don't have a strong feeling either way
11:08
I don't think that there's a lot of dependence on the particular string here, so I think minorest biolink revision would not cause any churn

Eric Deutsch (Expander Agent)  11:08 AM
This topic came up before in the context of p-value I think. and the decided solution was to change p-value to p_value in the model
11:10
I assumed the overall strategy was to eliminate all dashes from Biolink model. but I don't know any more than that.

Chris Bizon (SRI, Ranking Agent)  11:10 AM
I think it's nice to have those terms as punctution-free as possible
:+1:
1

Sierra Moxon (SRI)  2:12 PM
fixed in 2.2.9.
New

Chris Bizon (SRI, Ranking Agent)  5:11 PM
Thanks!

**Comment by finnagin** [comment]
@edeutsch is this still relevant?

**Comment by edeutsch** [comment]
no longer relevant, closing.
