### ISSUE TITLE
stripping whitespace?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1726]
Should ARAX be more robust and strip whitespace before and after string when confronted with:
```
                    "ids": [
                        " MONDO:0005301"
                    ],
```
?

https://github.com/NCATSTranslator/testing/pull/139/files

**Comment by isbluis** [comment]
My opinion is that this is something to be done on initial input (e.g. UI), but the rest of the system should not attempt to re-interpret / "clean" provided input values.

**Comment by edeutsch** [comment]
okay, we'll just leave it as is then.
