### ISSUE TITLE
To do after the December Demo

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1730]
Things to tidy up after the December Demo (code unfreeze)
- [ ] Switch production and RTX-KG2 back to `master` branch
- [ ] Remove the config_local.json on production and RTX-KG2

**Comment by saramsey** [comment]
I'm curious, was there a particular config change that needed to be made in `config_local.json` for the code freeze or the switch to the `production` branch, that will have to be reverted after the demo?

**Comment by edeutsch** [comment]
I don't think so. I think we just wanted to guard against a change made during continuing development in parallel to the freeze.

**Comment by amykglen** [comment]
I think there was, right? it's that the `RTX-KG2` url should point to the production KG2 for production ARAX, whereas it should point to the beta KG2 for the beta ARAX

**Comment by edeutsch** [comment]
aha, you're right! I'm so confused.

**Comment by amykglen** [comment]
hah, very fair. it is also needed to guard against any future changes though, as you said.

**Comment by finnagin** [comment]
@edeutsch is this something we are still doing?

**Comment by edeutsch** [comment]
Completed long ago, just not closed. closing.
