### ISSUE TITLE
Runup to December Demo code freeze

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1733]
Final tasks for the December code freeze:

- [x] Fully synchronize `production` and `master` brnaches
- [x] Roll out current `master` to all deployments on arax.ncats.io
- [x] Register both production and both development endpoints on Smart-API
- [x] Switch production ARAX and RTX-KG2 endpoints to the `production` branch
- [x] Declare that we are frozen at https://docs.google.com/spreadsheets/d/1LEV3FyXBt3xm4bC5TQkVbrZalrr6OV2LnPtuLj1RVB4
- [x] Tag the current state in production with "Dec2021Demo"
- [x] Declare that we have done so in the tracking sheet
- [x] Fame and fortune

We're almost there. Does anyone have any planning work or testing that would impact the completion of the remaining items?

I would plan to complete these 10am latest. Earlier if no objections.

**Comment by saramsey** [comment]
So @edeutsch I believe you are correct and I was incorrect. On Linux, it appears that parent and child process _can_ share a common entry in the kernel file table, and under the following conditions, they can be guaranteed that parent process writes and child process writes to the single shared output file will not corrupt the file:
1. Neither parent nor child is using buffered writes (both streams must be set to  autoflush or must flush on every write)
2. We are on Linux (for other OS's, I have no idea if line writes are atomic)
 and apparently, as long as a process writes a _line_ at a time (not a character)

Further, I was wrong about closing. If the child process closes the file, it doesn't affect the parent process's ability to write to the file. So... I think we could go back to having both parent and child process write to `RTX_OpenAPI_production.elog`. I will work on a PR for your consideration.

**Comment by saramsey** [comment]
OK, I have coded up the changes to `query_controller.py` to save all STDERR output to a common logfile, for both the ARAX and KG2 query controllers. See the [`issue-1735` branch](https://github.com/RTXteam/RTX/tree/issue-1735) and the associated PR #1736.

**Comment by saramsey** [comment]
I have installed the `issue-1735` branch code on `arax-backup.rtx.ai` in all three devareas (`production`, `fork-test`, and `kg2`) and they seem to work fine.

**Comment by saramsey** [comment]
If you wish to have the single-logfile logging prior to the demo (after which presumably the freeze will lift), we could aim to freeze this afternoon, I suppose?

**Comment by saramsey** [comment]
I don't _think_ it is necessary for the S5 init scripts for ARAX/KG2 to have the append (`>>`) redirects for this branch to work. But I am pretty sure autoflush _is_ necessary for it to work, and thus I have added commit c86a71a to update the `RTX_OpenAPI.start` template file (in the `issue-1735` branch of course).

**Comment by saramsey** [comment]
On balance, the `issue-1735` branch changes simplify `query_controller.py` quite a bit, basically gets rid of all the code to de-install the default logger and make a new one, in the child process. So that part of the logic is essentially back to what it was before.

**Comment by edeutsch** [comment]
okay, I am ready to freeze. Roll call is in one hour. The decision is whether we merge this code before or after the freeze.

**Comment by saramsey** [comment]
> okay, I am ready to freeze. Roll call is in one hour. The decision is whether we merge this code before or after the freeze.

OK, let me ask, how irritating will the "two logfiles" issue be, if we are stuck with it through the demo? (I mean, I know it is irritating, but just trying to weigh the cost/benefit here ).

**Comment by saramsey** [comment]
By "after the freeze" merge, do you mean on Dec. 15?

**Comment by edeutsch** [comment]
> > okay, I am ready to freeze. Roll call is in one hour. The decision is whether we merge this code before or after the freeze.
> 
> OK, let me ask, how irritating will the "two logfiles" issue be, if we are stuck with it through the demo? (I mean, I know it is irritating, but just trying to weigh the cost/benefit here ).

I dunno, not that irritating, it just means that no one will be looking at them.

**Comment by edeutsch** [comment]
> 
> 
> By "after the freeze" merge, do you mean on Dec. 15?

no, after the freeze is in 30 minutes.

**Comment by saramsey** [comment]
OK, I propose to merge to `production` before the freeze in that case. Best case (and I'm fairly confident), we won't have to revert anything.

**Comment by edeutsch** [comment]
okay, I almost tagged it, but can wait a few more minutes. Please merge to master and production

**Comment by saramsey** [comment]
merging now....

**Comment by saramsey** [comment]
part one done (merging from `issue-1735` to `master`)

**Comment by saramsey** [comment]
part two done (merging from `master` to `production`)
<img width="791" alt="Screen Shot 2021-11-16 at 10 21 38 AM" src="https://user-images.githubusercontent.com/5562107/142043220-10360744-ab14-4479-92e8-4edc6595eb70.png">

**Comment by saramsey** [comment]
Should we do a `git pull` in `/mnt/data/orangeboard/production/RTX` on `arax.ncats.io` inside the `rtx1` container?

**Comment by edeutsch** [comment]
okay, the latest `master` and `production` have been deployed everywhere. I have added the tag Dec2021Demo. I have updated the tracking sheet.

**Comment by saramsey** [comment]
Thank you for doing this, Eric.

Fame and fortune shall be yours!

**Comment by edeutsch** [comment]
You're welcome.
Either that or great notoriety.
