### ISSUE TITLE
Need to match "What diseases share the same proteins as arthritis?" to a template.

### ISSUE THREAD

**Issue by jaredroach** [RTXteam/RTX#174]
The question "What diseases share the same proteins as arthritis?" is not currently interpreted.

**Comment by dkoslicki** [comment]
Used the following re-wording:
"what diseases share similar proteins as arthritis"

as the code doesn't look for diseases that share the _exact_ same proteins as arthritis (just a subset thereof). Can use "the same" if you prefer.
