### ISSUE TITLE
question about RTX/code/DockerBuild/000-default.conf

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1740]
Hi @finnagin, in `RTX/code/DockerBuild/000-default.conf`, on on line 33, the Apache2 is configured to attempt to connect to the ARAX API on TCP port 5001: 
https://github.com/RTXteam/RTX/blob/4fbab97bb35582020a36cc75ef6ad054b1efecc1/DockerBuild/000-default.conf#L33

But in `RTX/code/UI/OpenAPI/python-flask-server/openapi_server/__main__.py`, on line 37,
the TCP port number for the ARAX API service is set to 5000:
https://github.com/RTXteam/RTX/blob/4fbab97bb35582020a36cc75ef6ad054b1efecc1/code/UI/OpenAPI/python-flask-server/openapi_server/__main__.py#L37

aren't those two things inconsistent?  Apologies in advance that I am probably missing something.

**Comment by saramsey** [comment]
OK, when I change the port number in the Apache2 config file, the UI can now query the ARAX API. 

<img width="813" alt="Screen Shot 2021-11-18 at 9 14 46 AM" src="https://user-images.githubusercontent.com/5562107/142464038-5b0df7e7-d237-4d27-a6cc-3a67d5e6ffaa.png">


There is still some (seemingly unrelated) remaining issue with KG2 that I am tracking down. Please let me know if you see any issue with changing L33 of the Apache config file (reference above) to specify port 5000 and to commit that change to the master branch.

**Comment by saramsey** [comment]
Unfortunately, hmm, the docker file clones the `production` branch, so committing that fix to the `master` branch won't solve this issue. But due to the code freeze, I am hesitant to modify even the Merged-Dockerfile in the production branch. I will do some hacking in my shell script to `sed -i` the Dockerfile, and comment why I am doing it. :-)

**Comment by saramsey** [comment]
So @finnagin will commit ffbd287 affect ITRB deployment in any way?

**Comment by finnagin** [comment]
This does not. Good to close.
