### ISSUE TITLE
warning in Merged-Dockerfile build

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1742]
At Step 28/53,
```
Step 28/53 : RUN apt-get update && apt-get install -y python3.7 python3.7-dev python3.7-venv
```
I am seeing this warning:
```
debconf: delaying package configuration, since apt-utils is not installed
```

**Comment by saramsey** [comment]
commit 93e8d24 should fix the issue, I hope

**Comment by saramsey** [comment]
@finnagin can you please check if commit 93e8d24 resolves the issue?

**Comment by finnagin** [comment]
So it kinda fixes the issue. It still spits out the error when first installing apt-utils but then after that does not spit out the error for any of the other installs that is previously did.

**Comment by saramsey** [comment]
Per this [issue on github.com](https://github.com/tianon/docker-brew-ubuntu-core/issues/59), I think the fix might be to add
```
ARG DEBIAN_FRONTEND=noninteractive
```
before 
```
RUN apt-get update
```
(i.e., right here: https://github.com/RTXteam/RTX/blob/4bebe169bc014813d6d2e0a6a74661ffe6c87890/DockerBuild/Merged-Dockerfile#L10

can you try it out?

**Comment by finnagin** [comment]
So, I actually already did that for another issue on line 4. It does not get rid of the first error message.

**Comment by saramsey** [comment]
what about this?
```
RUN export DEBIAN_FRONTEND=noninteractive && apt-get -yq install apt-utils
```

**Comment by saramsey** [comment]
If _that_doesn't work, then I guess we just have to ignore it.

**Comment by finnagin** [comment]
I'll try but I I'm unsure if that will fix it since I already know that DEBIAN_FRONTEND=noninteractive from the ARG command since I used that to fix a different error message later in the dockerfile.

**Comment by saramsey** [comment]
Sorry, you are right-- I didn't read the linked GitHub issue closely enough. Upon more careful reading, they do state that even _with_ that "fix", there is still a single one-time warning. I guess we live with it. 

Thanks for responding.

**Comment by finnagin** [comment]
You're welcome! I'll go ahead and close this one then.
