### ISSUE TITLE
configure syslog inside the rtx1 container on arax.ncats.io

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1745]
Should we configure syslog inside the `rtx1` container on `arax.ncats.io`?   I note that `syslog` _is_ configured inside the `rtx1` container on `arax-backup.rtx.ai` and does not seem to create problems for ARAX running. And there could be useful logging information in there, but we will never know if we don't capture the data, I suppose?

**Comment by edeutsch** [comment]
I don't even know what "configure syslog" means. How does one configure a syslog and what impact does it have to do that?

**Comment by finnagin** [comment]
I'm actually not sure what that means either. @saramsey ?

**Comment by saramsey** [comment]
syslog is the *nix centralized OS-level logging service.

For whatever reason, it is not configured by default inside a Docker Ubuntu container.

This might do it, in a Dockerfile:
```
RUN apt-get install -y rsyslog
```
or the equivalent command to implement this in an already-running container, from the host OS:
```
sudo docker exec apt-get install -y rsyslog
```

**Comment by saramsey** [comment]
To see the kinds of things that syslog logs, see `/var/log/syslog` inside the `rtx1` container on `arax-backup.rtx.ai`. A snippet:
```
ubuntu@ip-172-31-48-139:~$ sudo docker exec rtx1 head -100 /var/log/syslog
Oct  4 04:47:35 5d5ebba937d1 rsyslogd: [origin software="rsyslogd" swVersion="8.16.0" x-pid="31217" x-info="http://www.rsyslog.com"] start
Oct  4 04:47:35 5d5ebba937d1 rsyslogd-2039: Could not open output pipe '/dev/xconsole':: Permission denied [v8.16.0 try http://www.rsyslog.com/e/2039 ]
Oct  4 04:47:35 5d5ebba937d1 rsyslogd-2222: command 'KLogPermitNonKernelFacility' is currently not permitted - did you already set it via a RainerScript command (v6+ config)? [v8.16.0 try http://www.rsyslog.com/e/2222 ]
Oct  4 04:47:35 5d5ebba937d1 rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
Oct  4 04:47:35 5d5ebba937d1 rsyslogd-2145: activation of module imklog failed [v8.16.0 try http://www.rsyslog.com/e/2145 ]
Oct  4 04:47:35 5d5ebba937d1 rsyslogd: rsyslogd's groupid changed to 115
Oct  4 04:47:35 5d5ebba937d1 rsyslogd: rsyslogd's userid changed to 108
Oct  4 04:47:36 5d5ebba937d1 rsyslogd-2007: action 'action 9' suspended, next retry is Mon Oct  4 04:48:06 2021 [v8.16.0 try http://www.rsyslog.com/e/2007 ]
Oct  5 18:26:27 5d5ebba937d1 /etc/init.d/mysql[5367]: ERROR: The partition with /mnt/data/mysql is too full!
Oct  5 18:26:50 5d5ebba937d1 /etc/init.d/mysql[5439]: ERROR: The partition with /mnt/data/mysql is too full!
Oct  5 18:28:24 5d5ebba937d1 /etc/init.d/mysql[5497]: ERROR: The partition with /mnt/data/mysql is too full!
Oct  5 20:59:30 5d5ebba937d1 /regrtest.py: test message from python test_syslog
```

**Comment by saramsey** [comment]
Would we see all this stuff mirrored in other services' logs?  Hard to say. My sense is, it may be in our interest to log it unless doing so incurs a performance or space issue.

**Comment by edeutsch** [comment]
sure, fine with me. Go for it!

**Comment by saramsey** [comment]
done (on `arax.rtx.ai` in the `rtx1` container):

<img width="650" alt="Screen Shot 2021-11-18 at 9 28 58 PM" src="https://user-images.githubusercontent.com/5562107/142570296-28688d6f-7a9e-485f-bc5a-ed8815ab3f2b.png">
