### ISSUE TITLE
Lost queries

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1747]
This problem was first highlighted in #1744, specifically here:
https://github.com/RTXteam/RTX/issues/1744#issuecomment-973717892
but it is really a separate problem I think.

the current state is this:
```
rt       31070  4.0  3.2 4012476 2118248 ?     Sl   Nov16 172:30 python3 -u -m openapi_server
rt       20780  0.0  2.4 3459124 1568828 ?     S    Nov18   0:10  \_ python3 -u -m openapi_server
rt       29444  0.0  2.4 3465780 1596272 ?     S    Nov18   0:02  \_ python3 -u -m openapi_server
rt       10260  1.2  0.7 1968956 459636 ?      S    01:16  12:07 python3 -u -m openapi_server
rt       27723  0.5  0.0      0     0 ?        Z    17:01   0:01  \_ [python3] <defunct>
rt       27725  0.6  0.0      0     0 ?        Z    17:01   0:01  \_ [python3] <defunct>
rt       27729  0.7  0.0      0     0 ?        Z    17:02   0:01  \_ [python3] <defunct>
rt       27779  2.9  0.0      0     0 ?        Z    17:04   0:01  \_ [python3] <defunct>
```

We are slowly acquiring some zombies, which is issue #1744.

But the other problem is the two ARAX queries (children of 31070) that are still languishing. They've been active for 20 hours and I don't think they're doing anything useful (but I'm not positive).

I propose we kill them and reset ARAX.

Unless someone wants to perform from forensics on them. These were the query ids in case someone has time to try to repro the problems:
<html><body>

66959 | 2021-11-18 21:09:01 | 72936 | ars.transltr.io | arax.ncats.io | d1fd345478a0 | ARAX | 29444 | -- | ➜ Running Async | Running | Query executing via /asyncquery
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
66900 | 2021-11-18 20:21:48 | 75769 | ars.transltr.io | arax.ncats.io | d1fd345478a0 | ARAX | 20780 | -- | ➜ Running Async | Running | Query executing via /asyncquery

</body>
</html>

i.e. query ids 66900 and 66959.

OKAY TO KILL?

**Comment by saramsey** [comment]
I wish to perform forensics. Can we wait a bit?

**Comment by saramsey** [comment]
Eric, I propose to kill those two queries (and I concur with you-- they seem unrelated to the zombie problem) but if we can possibly avoid restarting ARAX, that would be helpful, as I would like to work on the zombie problem.

**Comment by edeutsch** [comment]
Sure, no problem. I am tangled in some other calls for a while now this morning. Feel free to kill the two children whenever you like. Would be interesting to monitor the production elog to see if there is a chirp when you kill them. Note that the system activity monitor will not know they are killed and will continue to show them running until ARAX is fully reset:
https://arax.ncats.io/?recent=1

**Comment by edeutsch** [comment]
This is solved I hope. But can be reopened if necessary. closing.
