### ISSUE TITLE
Update DrugResponseKP's infores curie

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1749]
apparently DrugResponseKP's infores curie was changed in October from:
```
infores:biothings-multiomics-drug-response
```
to:
```
infores:biothings-multiomics-biggim-drugresponse
```
(discovered this via [this slack message](https://ncatstranslator.slack.com/archives/C01CM3LQQLA/p1635371609001100))

we'll need to update this in Expand here:
https://github.com/RTXteam/RTX/blob/4bc774fb1210d4aefe439526940baeb3f1109ea7/code/ARAX/ARAXQuery/Expand/expand_utilities.py#L556

**Comment by rcpeene** [comment]
Will check after the next push to production

**Comment by amykglen** [comment]
in testing this issue @rcpeene discovered that our (previously working) Multiomics Drug Response KP test case currently produces 0 results: https://github.com/RTXteam/RTX/blob/5146fe04d0159fe8c8911560326b17b15aeb5af1/code/ARAX/test/test_ARAX_expand.py#L764-L773
here's that query run in the UI: https://arax.ncats.io/?r=35722

and this is the query Expand sends to the KP for it:
```
curl -X 'POST' \
  'https://api.bte.ncats.io/v1/smartapi/adf20dd6ff23dfe18e8e012bde686e31/query' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "exclude": false,
          "object": "n01",
          "predicates": [
            "biolink:related_to"
          ],
          "subject": "n00"
        }
      },
      "nodes": {
        "n00": {
          "categories": [
            "biolink:Gene",
            "biolink:Protein"
          ],
          "ids": [
            "NCBIGene:7157"
          ],
          "is_set": false
        },
        "n01": {
          "categories": [
            "biolink:SmallMolecule"
          ],
          "is_set": true
        }
      }
    }
  }
}'
```
not sure if this is a temporary/known problem on their end, or if something with their content/curies changed? the output when running the above `curl` command says something about a 404... wondering if @edeutsch knows anything about this, or if there's another example query we can use?

**Comment by edeutsch** [comment]
All I know if that they were planning on updating their API with a fresh set of data through Service Provider, but there were some complications. I don't know where it ended up. It's possible that they're updating it now.

**Comment by amykglen** [comment]
ok, thanks. I reported this to Guangrong, who's looking into it

**Comment by rcpeene** [comment]
Currently having difficulties confirming this change didn't cause any problems because we are presently having difficulty finding a query that returns more than 0 results. Will close the issue when such a query is found.

**Comment by amykglen** [comment]
ok, some progress here in that the Drug Response KP once again returns results for our standard test query! (i.e., the CURL command I posted [here](https://github.com/RTXteam/RTX/issues/1749#issuecomment-1020776435) works once again.)

however, as part of their API update that fixed that, they apparently upgraded to a new Biolink version (beyond what ARAX is on), because their meta KG now uses predicates that don't exist in the Biolink we're on (2.2.6): https://api.bte.ncats.io/v1/smartapi/adf20dd6ff23dfe18e8e012bde686e31/meta_knowledge_graph
(looks like those predicates were added in Biolink 2.2.10)

I think this means our hierarchical predicate reasoning during KP selection isn't working correctly for them (so for a `related_to` query, Expand won't choose to use Drug Response KP, since it doesn't realize the predicates they use are descendants of `related_to`).

I think we can make our Drug Response KP pytest work again by just specifying the particular predicate (e.g., `biolink:associated_with_sensitivity_to`), but in general Expand won't select that KP for use very often. basically only when one of the four predicates they list in their meta KG is used.

not sure if this is something we should worry about, or just let it be resolved whenever we next up our biolink version? I think the next KG2 build (2.7.5) would get us there? (think it uses Biolink 2.2.11?)

but in any case I think this issue is testable now @rcpeene (and should work on `/beta`), as long as you use one of the predicates specified in their meta KG. e.g.:
```
add_qnode(ids=NCBIGene:7157, categories=biolink:Gene, key=n00)
add_qnode(categories=biolink:SmallMolecule, key=n01)
add_qedge(subject=n00, object=n01, key=e00, predicates=biolink:associated_with_sensitivity_to)
expand(kp=infores:biothings-multiomics-biggim-drug-response)
resultify()
```
feel free to close this issue after you confirm the new infores curie looks good in the results. and also it'd be great if you could add the predicate to our pytest to get this test passing again!

**Comment by rcpeene** [comment]
The above query works on the UI beta and in the pytest suite and the results look good.
