### ISSUE TITLE
Comparing Reactome and KEGG's value for identifying specific pathway steps

### ISSUE THREAD

**Issue by jaredroach** [RTXteam/RTX#175]
They tend to offer similar information. Ease of parsing, and finding the right synonyms varies.

Consider
glutamate + acetyl CoA => N-acetyl glutamate + CoA
Reactome:
https://reactome.org/content/detail/R-HSA-70542
KEGG:
http://www.kegg.jp/dbget-bin/www_bget?rn:R00259

In theory, either one can give the precursors, products, and enzyme for a given reaction.
KEGG's use of EC numbers is useful because unambiguous and easy to parse: e.g. 
EC 2.3.1.1 for N-acetylglutamate synthase
whereas Reactome uses R-HAS-70528 for N-acetylglutamate synthetase

So at least in this case, the same knowledge appears in both databases, and it is primarily a matter of parsing. 

Reactome specifies cellular location; I am not sure if KEGG has that information as readily. But maybe not important.

**Comment by dkoslicki** [comment]
Per #788, is this still revenant? @saramsey are both KEGG and Reactome in KG2 now?

**Comment by saramsey** [comment]
I'd like to try Reactome, noted in #636. As for doing a full ETL of KEGG, we would need to pay for an academic subscription, and I think that's probably a non-starter.
