### ISSUE TITLE
Plug SPOKE KP into Expand

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1750]
(we discussed this a while back, but I never created an issue for it)

see: https://smart-api.info/registry?q=spoke for their API documentation

there are four places we need to update the code to plug a new KP into Expand:

1. we need to add a line for SPOKE here:
https://github.com/RTXteam/RTX/blob/4bc774fb1210d4aefe439526940baeb3f1109ea7/code/ARAX/ARAXQuery/Expand/expand_utilities.py#L525-L540

2. and also here:
https://github.com/RTXteam/RTX/blob/4bc774fb1210d4aefe439526940baeb3f1109ea7/code/ARAX/ARAXQuery/Expand/expand_utilities.py#L543-L561

3. add SPOKE to this list (probably somewhere in the middle):
https://github.com/RTXteam/RTX/blob/4bc774fb1210d4aefe439526940baeb3f1109ea7/code/ARAX/ARAXQuery/Expand/expand_utilities.py#L567-L568

4. add a command definition entry for SPOKE analogous to this one:
https://github.com/RTXteam/RTX/blob/4bc774fb1210d4aefe439526940baeb3f1109ea7/code/ARAX/ARAXQuery/Expand/expand_utilities.py#L751-L756

and once the changes/testing are complete, we need to regenerate the auto-documentation by doing:
```
cd code/ARAX/Documentation/
python document_dsl_commands.py
```
and then check in the changes that script makes to `DSL_Documentation.md`

**Comment by rcpeene** [comment]
Will check after the next rollout of master

**Comment by edeutsch** [comment]
master has been rolled out to /beta. Would you test there? (not rolled out to production yet)

**Comment by amykglen** [comment]
does anyone know who the best contact would be for asking the SPOKE team about their meta knowledge graph? Sergio? Sui? or do they have a software developer?

**Comment by edeutsch** [comment]
We could try Brett Smith, he seems to be the technical person

**Comment by amykglen** [comment]
thanks! ok, I reached out to Brett on Slack - will see what he says. interestingly, today I think there's a bit more info under the `nodes` slot of their meta KG, but `edges` still only lists `biolink:PhenotypicFeature--biolink:interacts_with--biolink:PhenotypicFeature` meta edges
```
curl -X 'GET' \
  'https://spokekp.healthdatascience.cloud/api/v1.2/meta_knowledge_graph' \
  -H 'accept: application/json'
```

**Comment by rcpeene** [comment]
Here's a sample query that should return results.
```
add_qnode(ids=OMIM:603903, categories=biolink:PhenotypicFeature, key=n00)
add_qnode(categories=biolink:PhenotypicFeature, key=n01)
add_qedge(subject=n00, object=n01, key=e00)
expand()
resultify()
```

**Comment by amykglen** [comment]
ok, so apparently I'm going crazy(??), but SPOKE's meta knowledge graph appears to be fine, with many different kinds of meta edges in it. not sure how I saw what I saw with it only including phenotypic feature edges.

and I figured out why SPOKE isn't being selected for our classic example acetaminophen query - the reason is slightly intricate and is unrelated to the particulars of the SPOKE integration, so I'm going to write it up in a separate issue.

**Comment by rcpeene** [comment]
I've just tested the following spoke Query on the UI and received 294 Results. Seems to be working fine.

`add_qnode(ids=NCBIGene:7157, categories=biolink:Gene, key=n00)
add_qnode(categories=biolink:ChemicalEntity, key=n01)
add_qedge(subject=n01, object=n00, key=e00)
expand(kp=SPOKE)
resultify()
return(message=true, store=false)`
