### ISSUE TITLE
Make instance setup scripts work for both ubuntu 20.04 & 18.04

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1751]

**Comment by finnagin** [comment]
Confirmed to work for 20.04. Need to make a new instance to test on 18.04. @saramsey what size of instance should I use?

**Comment by saramsey** [comment]
@finnagin you can actually use a `t2.micro` instance to do a basic test of ARAX deployment, just make sure to allocate 200 GiB for the root filesystem storage.  Of course, the t2.micro instance may not be able to run multi-hop queries and such, but I presume that's beyond the scope of the testing one would do specifically for issue 1751.

**Comment by saramsey** [comment]
Hi @finnagin how is the testing for this issue going?

**Comment by finnagin** [comment]
Verified to work on Ubuntu 18.04. I think we can close this issue.
