### ISSUE TITLE
Change fresh install scripts to allow a different port number, install python with apt-get, and use config_local.json

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1753]
- [x] remove [these lines](https://github.com/RTXteam/RTX/blob/0a921547c98a5daa731f7b096ceac86f2b8fd1ca/DockerBuild/test-instance-scripts/build-test-arax-from-fresh-instance.sh#L20-L21) 
- [x] change [this line](https://github.com/RTXteam/RTX/blob/0a921547c98a5daa731f7b096ceac86f2b8fd1ca/DockerBuild/test-instance-scripts/build-test-arax-from-fresh-instance.sh#L22) to download python using apt-get
- [x] change [this line](https://github.com/RTXteam/RTX/blob/0a921547c98a5daa731f7b096ceac86f2b8fd1ca/DockerBuild/test-instance-scripts/build-test-arax-from-fresh-instance.sh#L48) to call python3.7 when rinning the database download
- [x] unwind [this config loop](https://github.com/RTXteam/RTX/blob/0a921547c98a5daa731f7b096ceac86f2b8fd1ca/DockerBuild/test-instance-scripts/build-test-arax-from-fresh-instance.sh#L78-L82) to only us config_local.json
- [x] change [the build-test script](https://github.com/RTXteam/RTX/blob/master/DockerBuild/test-instance-scripts/build-test-arax-from-fresh-instance.sh) to pull the port number out of argument 1
- [x] change [the remote-setup script](https://github.com/RTXteam/RTX/blob/master/DockerBuild/test-instance-scripts/remote-setup-build-test-arax-from-fresh-instance.sh) to ask for the port number defaulting to 80 on enter
- [x] Test on ubuntu 20.04
- [x] Test on ubuntu 18.04
- [x] merge master into issue1753
- [x] merge into master

**Comment by saramsey** [comment]
thank you for making the checklist!
