### ISSUE TITLE
Problem with workflow D.4?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1755]
Brett Smith reported to me via email:

I noticed ARAX has stopped returning results for the Demo query D.4. By "stopped returning results," I mean that ARAX never seems to complete the query. It is a long-running query with undefined protein-protein interactions, so it's reasonable that it might continue running. However, in the past, it was returning the expected results. I wanted to see if you had any insight or suggestions ahead of the big demo next week.

Here are some (ARS) PKs to check from the last couple days:
1350910b-fe14-4896-a188-3c8e65b0661b
b9d879a3-3490-41bf-b38d-015277b4975b
08fae4f8-15e1-447c-aeac-e120032e20d6

Anyone able to look into this?
Maybe the problem will be revealed in working issue #1754 ?
I also just reset all services on arax.ncats.io so it's possible that such a reset could have fixed the problem.

**Comment by finnagin** [comment]
query:
```
{
  "edges": {
    "e00": {
      "constraints": [],
      "object": "n01",
      "subject": "n00"
    },
    "e01": {
      "constraints": [],
      "object": "n02",
      "subject": "n01"
    },
    "e02": {
      "constraints": [],
      "object": "n03",
      "subject": "n02"
    },
    "e03": {
      "constraints": [],
      "object": "n04",
      "subject": "n03"
    }
  },
  "nodes": {
    "n00": {
      "categories": [
        "biolink:SmallMolecule"
      ],
      "constraints": [],
      "ids": [
        "DRUGBANK:DB00150"
      ],
      "is_set": false
    },
    "n01": {
      "categories": [
        "biolink:Protein"
      ],
      "constraints": [],
      "is_set": false
    },
    "n02": {
      "categories": [
        "biolink:MolecularActivity"
      ],
      "constraints": [],
      "is_set": false
    },
    "n03": {
      "categories": [
        "biolink:MolecularActivity"
      ],
      "constraints": [],
      "is_set": false
    },
    "n04": {
      "categories": [
        "biolink:SmallMolecule"
      ],
      "constraints": [],
      "ids": [
        "KEGG.COMPOUND:C02700"
      ],
      "is_set": false
    }
  }
}
```

**Comment by finnagin** [comment]
smaller 3-hop version to test guard rails:
```
{
  "edges": {
    "F1": {
      "constraints": [],
      "object": "n02",
      "predicates": [
        "biolink:has_fisher_exact_test_p_value_with"
      ],
      "subject": "n01"
    },
    "N1": {
      "constraints": [],
      "object": "n01",
      "predicates": [
        "biolink:has_normalized_google_distance_with"
      ],
      "subject": "n00"
    },
    "N2": {
      "constraints": [],
      "object": "n02",
      "predicates": [
        "biolink:has_normalized_google_distance_with"
      ],
      "subject": "n01"
    },
    "N3": {
      "constraints": [],
      "object": "n04",
      "predicates": [
        "biolink:has_normalized_google_distance_with"
      ],
      "subject": "n02"
    },
    "e00": {
      "constraints": [],
      "object": "n01",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n00"
    },
    "e01": {
      "constraints": [],
      "object": "n02",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n01"
    },
    "e02": {
      "constraints": [],
      "object": "n02",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n04"
    }
  },
  "nodes": {
    "n00": {
      "categories": [
        "biolink:SmallMolecule"
      ],
      "constraints": [],
      "ids": [
        "DRUGBANK:DB00150"
      ],
      "is_set": false
    },
    "n01": {
      "categories": [
        "biolink:Protein"
      ],
      "constraints": [],
      "is_set": false
    },
    "n02": {
      "categories": [
        "biolink:MolecularActivity"
      ],
      "constraints": [],
      "is_set": false
    },
    "n04": {
      "categories": [
        "biolink:SmallMolecule"
      ],
      "constraints": [],
      "ids": [
        "KEGG.COMPOUND:C02700"
      ],
      "is_set": false
    }
  }
}
```

**Comment by finnagin** [comment]
Looks like the guard rails are not working in master since on the third hop in the above query 4500 curies are sent to RTX-KG2.

**Comment by finnagin** [comment]
@amykglen Is there an option to make the pre-prune more stringent?

**Comment by amykglen** [comment]
the pre-prune thresholds can certainly be made more stringent, although the qedge you showed where it was set to 5,000 is effectively "pinned" on both ends at this point in the expansion. meaning there couldn't be more than 5,000 nodes returned that fulfill that qedge, which isn't all that many. for edges where only one end is pinned, those thresholds are all much lower (500 or less).

if the 4-hop query is blowing up in Expand, I'm guessing it's likely happening before the last qedge?

**Comment by amykglen** [comment]
ok, so I just ran the 4-hop query from `master` locally (by setting `force_local = True` in `ARAX_expander.py`), and things ran ok - all pre-pruning seemed to happen as expected. the query took a few minutes and produced 44 results. these were the counts after Expand finished:
```
2021-12-03T14:40:09.006042 INFO: [] After Expand, the KG has 18 nodes and 112 edges (e00: 87, e01: 17, e02: 4, e03: 4, n00: 3, n01: 9, n02: 1, n03: 5, n04: 1)
```
going to try running it from the `production` branch as well.

**Comment by amykglen** [comment]
same thing happens in the `production` branch - completes in 5 minutes with 44 results.

and I also confirmed that when I don't do `force_local = True`, and instead actually use the KG2 API (the production one), it gives the same results. 

given that I see no problems in testing, I went ahead and ran it on production - also looks good there: https://arax.ncats.io/?r=33385

**Comment by amykglen** [comment]
so I have no idea why those few ARS PKs never seemed to complete. could it have to do with `/async_query` vs. `/query`?

**Comment by edeutsch** [comment]
> so I have no idea why those few ARS PKs never seemed to complete. could it have to do with `/async_query` vs. `/query`?

maybe that's it. We've had inklings in the past that an /async_query would go off the rails when the corresponding /query version completed fine and we never got to the bottom of that, I think. For example #1718 it seemed that that query completed fine with /query but died an embarrassing death trying to look up 15 million node pairs when called with /async_query.

**Comment by amykglen** [comment]
yeah, I'm baffled by the differences between `/query` and `/asyncquery`. is the only real way to play with async queries by hitting the production/beta `/asyncquery`endpoints? or I guess on arax backup, perhaps

**Comment by saramsey** [comment]
Doesn't asyncquery use different code for handling forking?  Could that be part of the issue?

**Comment by edeutsch** [comment]
It could be, but it seems unlikely to me. If you examine the reports in #1718 carefully, you'll notice that Expander seems to be getting different results from its KPs that appears to be causing the issue. The /async_query log clearly shows ARAX cheerily declaring that it is about to do 15 million NGD lookups right before if wanders off to its doom. Whereas the /async version somehow doesn't get to that point. I don't see how that difference could possibly be due to forking differences, but I can't say for sure. I would suggest start looking to see where the logged information starts to diverge between the two modes rather than pulling apart the forking stuff.

**Comment by finnagin** [comment]
So I ran this on arax-backup using async query and it seems to have been killed after using too much ram. When using async query does it output to the elog like normal @edeutsch ? If so I have it downloaded but just need to figure out where it starts to get all the output of the query.

**Comment by finnagin** [comment]
From what you said in #1756 it sounds like it does print to the normal elog file.

**Comment by finnagin** [comment]
@amykglen Looks like pruning is not working in the async setting like you suspected:
`2021-12-07T05:58:12.401369 DEBUG: [] After merging KPs' answers, total KG counts are: e00: 2340, e01: 100269, n00: 3, n01: 1391, n02: 16943`

100,000+ edges between 17,000 after expanding on edge `e01`!

**Comment by finnagin** [comment]
In case anyone wants to look over the elog, I can link the elog file were bit it's a bit too long to paste in the chat:
[workflowd4.elog.txt](https://github.com/RTXteam/RTX/files/7666304/workflowd4.elog.txt)

**Comment by edeutsch** [comment]
Is there any setting anywhere where Expand is willing to do more work while in async mode because there is presumed to be more time? Maybe that is going off the rails?

**Comment by edeutsch** [comment]
Fix for this has been deployed. #1761. Closing.
