### ISSUE TITLE
Added crude callback handler for /asyncquery

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1756]
I related this earlier to Finn, but for anyone else who wants to test /async_query:

1) You'll need a callback URL. I set up a crude system that enables the callback: https://arax.ncats.io/devED/api/arax/v1.2/response
When ARAX POSTs a TRAPI Response to that URL, it will be stored on the system here:
/mnt/data/orangeboard/Cache/callbacks/
for your inspection.

2) You can
```
tail -f /tmp/RTX_OpenAPI_devED.elog
```
to watch when they come in.

3) Note that you if you:
```
tail -f /tmp/RTX_OpenAPI_XXXXXXXX.elog
```
where XXXXXXX is the instance you submit your asyncquery to, you can watch the async query progress.  An /asyncquery inspects your query and returns an error is there is a problem with your query. But if the query is okay, then a child process is spawned and the work is actually performed there while the parent simply returns a simple TRAPI message that logs all the thoughts until it is ready to start working the problem. Note that child also writes to STDERR so probably the only way to watch what the child is doing is via
```
tail -f /tmp/RTX_OpenAPI_XXXXXXXX.elog
```
because the initial request just returns an "OK, working on it" and the callback only gets hit when work is complete.. which may not happen in the case of D.4 and other killer queries.

that is all. FYI only.

**Comment by saramsey** [comment]
Nice, thank you for doing this, @edeutsch !

**Comment by saramsey** [comment]
Tagging @finnagin

**Comment by saramsey** [comment]
this was super helpful @edeutsch; I used this approach in #1759

**Comment by edeutsch** [comment]
A note on how to find this documentation is now mentioned in the wiki. Closing.
