### ISSUE TITLE
this debugging code perhaps should be made conditional on debug mode?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1757]
in ARAX_query.py, see L497:

https://github.com/RTXteam/RTX/blob/8e30189ce0ddd125afe70ff5945d094077a077a6/code/ARAX/ARAXQuery/ARAX_query.py#L497

**Comment by saramsey** [comment]
Tagging @edeutsch as it looks like it was his commit, in case I have misunderstood the intent of this code.

**Comment by edeutsch** [comment]
sure, it can just be removed, it was just some testing at some point long ago.

**Comment by finnagin** [comment]
Sweet. I went ahead and removed it. Should we go ahead and close this issue?
