### ISSUE TITLE
ARAX no longer returning results for a specific query?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1758]
Hi everyone, @MarkDWilliams sent me a Slack message. I'm somewhat tied up today and a bit Slack-challenged for weird reasons, maybe we can continue the convo here? Does someone have time to look into it? From Mark:

Looks like ARAX is returning 0 results for some queries that it returned results for in the past.  Are there any issues happening that you're aware of?  This query previously had 2 results that I believe came through text mining
```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "object": "n0",
                    "subject": "n1",
                    "predicates": [
                        "biolink:entity_negatively_regulates_entity",
                        "biolink:decreases_abundance_of",
                        "biolink:decreases_expression_of",
                        "biolink:decreases_stability_of",
                        "biolink:decreases_uptake_of",
                        "biolink:increases_degradation_of",
                        "biolink:decreases_synthesis_of",
                        "biolink:decreases_activity_of"
                    ]
                }
            },
            "nodes": {
                "n0": {
                    "ids": [
                        "NCBIGene:23221"
                    ],
                    "categories": [
                        "biolink:Gene"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:SmallMolecule"
                    ]
                }
            }
        }
    }
}
```

@MarkDWilliams I just gave it a quick query and got two results:
https://arax.ncats.io/?r=33734

I do note that the only two results we get are from BTE:
![image](https://user-images.githubusercontent.com/12707718/145279433-e6632196-98b0-488c-808a-f7163c0224fc.png)

I will note that it is very common for BTE to time out.

So: it seems to work for me. And I can imagine a plausible cause: if BTE times out (which is very common) then ARAX will have nothing.

**Comment by saramsey** [comment]
I have responded to Mark via Slack DM with CC to Eric.

**Comment by edeutsch** [comment]
The going theory is the BTE just timed out. which led to no results. I think it is safe to close. Closing.
