### ISSUE TITLE
add "description" field for metabolite nodes to the KG using script

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#176]

**Comment by DeqingQu** [comment]
@saramsey The description of metabolite nodes can be retrieved through three steps.
1. Get Pub_Chem ID from KEGG API. http://rest.kegg.jp/conv/pubchem/compound:C00190
2. Get HMDB ID from Pub_Chem API. https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/123689/description/JSON
3. GET description from HMDB. http://www.hmdb.ca/metabolites/HMDB0002189.xml
However, for now, only 10% of metabolite nodes can retrieve descriptions from HMDB.

**Comment by saramsey** [comment]
@DeqingQu is the following post from Vlado Dancik useful for addressing this issue?

> Hi Richard, Steve
> 
> I now have a knowledge beacon for Human Metabolomics Database (HMDB) running on ncats server, https://translator.ncats.io/hmdb-knowledge-beacon. Please give it a try and see if it works for you. Let me know if you have any questions. I will put the code on github but it may take some time as I am traveling for the rest of the week (and might not make the call Thursday).
> 
> I tried to map HMDB disease list to UMLS ids, but I could not to do so for 71 of their diseases, they have empty id: https://translator.ncats.io/hmdb-knowledge-beacon/concepts?keywords=&categories=disease
> 
> There are a couple of API issues that you may encounter. The auto-generated code (java-play) does not properly handle arrayed parameters. Before that gets fixed, only single string parameters are supported, e.g
> 
> //translator.ncats.io/hmdb-knowledge-beacon/concepts?keywords=&categories=disease
> 
> will work, but
> 
> //translator.ncats.io/hmdb-knowledge-beacon/concepts?keywords=&categories=disease,metabolite
> 
> will not. Also I have not configured Access-Control-Allow-Origin header yet so there may be issues accessing API from a browser.
> 
> 
> Best,
> Vlado

**Comment by DeqingQu** [comment]
Thank you, @saramsey. I will try it.

**Comment by saramsey** [comment]
seems fixed

![screen shot 2018-11-05 at 1 05 16 pm](https://user-images.githubusercontent.com/5562107/48026632-75a59880-e0fb-11e8-8990-c77235b509f2.png)
