### ISSUE TITLE
Now that we have the fix for the killer query problem, what do we do?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1761]
As of tonight we have the fix for the killer async_query problem.
The question is: what do we do?

It seems like we have several options:

1) Apply the patch (after seeking the necessary approvals on short notice). This will fix the current non-answers by ARAX for D.4 and possibly others queries. But it may also change many answers at least a little bit. Maybe for the better, maybe not

2) Just leave well enough alone. We're 6 days from the demo and we're not getting frantic messages from Mark that things are not working (even though a few aren't) so don't rock the boat without an invitation

3) Ask Mark to repoint from /async_query to /query. This is technically not a code change on our part, but a config change in ARS. But it might cause some timeouts where there are currently not. And it may change many answers as in scenario 1

It might be good to contact Mark and discuss the situation and let him decide. It's his show.

Ideally what we really need is, like last time, a detailed documentation of all the workflow answers, before and after. Some will be identical, but unlike last time, some will be different. We need links to before and after results to decide whether things improve or get worse and/or adversely affect the demo.

**Comment by saramsey** [comment]
Can we discuss at the AHM today?

**Comment by edeutsch** [comment]
We can. Mark indicated that he can meet to discuss as early as noon PST today.

**Comment by saramsey** [comment]
To recap from the Slack thread, we are meeting to discuss this issue at 11 AM PST today (Thursday Dec. 9) to discuss, on the PSU zoom.  Yes?

**Comment by edeutsch** [comment]
Mark approved. The workflow owners approved (were thrilled in fact). The fix has been deployed. closing.
