### ISSUE TITLE
configure ARAX nginx to pass-through client IP addresses, somehow

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1767]
Amplifying a proposal first made by @edeutsch:  I am not sure how feasible this is, but it would be nice if apache2 could "see" the client IP address so that it shows up in `/var/log/apache2/access.log`, inside the Docker container. The way things are set up currently, the client IP address only shows up in the host OS logfile `/var/log/nginx/access.log`. 

While not urgent, this would be a "nice to have" feature if someone can do some nginx config wizardry. Since the apache2 logs are more frequently checked than the nginx logs, this would save time having to connect entries between the two logfiles.

**Comment by edeutsch** [comment]
This would appear to be the recipe: https://gist.github.com/patrocle/43f688e8cfef1a48c66f22825e9e0678

Has this already been tried? Would someone try it?

**Comment by saramsey** [comment]
Thank you @finnagin for looking into this!

**Comment by finnagin** [comment]
@edeutsch I've implemented this on finndev.rtx.ai but when I look at access.log I still don't see the correct ip address.

**Comment by edeutsch** [comment]
hmm, it looks like you configured it for php scripts?
https://github.com/RTXteam/RTX/commit/023db700da240d05da924a8e4f02c9bddbad8c4b

We don't have PHP scripts. Those adjustments should go in the location /

I suppose you can't follow that recipe *exactly*, it needs to some tweaking to make it work.

**Comment by finnagin** [comment]
@edeutsch Sorry I should have been more explicit in what I had tried. I started by trying to follow the recipe exactly but that didn't work so I also tried modifying the location / section.
I changed this:
```
location / {
	proxy_read_timeout 3000s;
        add_header 'X-Frame-Options' 'SAMEORIGIN';
        proxy_buffering off;

	include proxy_params;
	proxy_pass http://localhost:8080;
	proxy_set_header  X-Forwarded-Proto $scheme;
	proxy_set_header  X-Real-IP         $remote_addr;
	proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
	proxy_set_header  X-Real-IP-AWS	    $remote_addr;

        deny 66.27.73.63;
        deny 18.236.105.98;
    }
```
To more closely match the php section in the link like this:
```
location / {
	proxy_read_timeout 3000s;
        add_header 'X-Frame-Options' 'SAMEORIGIN';
        proxy_buffering off;

	include proxy_params;
	proxy_pass http://localhost:8080;
	proxy_set_header  X-Forwarded-Proto $scheme;
	proxy_set_header  X-Real-IP                 $remote_addr;
	proxy_set_header  X-Forwarded-For     $remote_addr;
	proxy_set_header  X-Real-IP-AWS	    $remote_addr;
        proxy_set_header Host                         $host;

        deny 66.27.73.63;
        deny 18.236.105.98;
    }
```
But this caused me to get 400 codes bach when ever I submitted a query so I remove the line `proxy_set_header Host                         $host;` which allowed me to submit queries again but I was not getting the real ip address.

**Comment by edeutsch** [comment]
okay, hmm. did you do all the Apache config changes outlined in the recipe, too?

**Comment by finnagin** [comment]
I did. I was wondering if maybe those might need to be modified too?

**Comment by edeutsch** [comment]
I don't know. That recipe looked plausible, but I don't know for sure that it is the solution we need. Maybe it still needs some tweaking, or maybe it just won't work.

Do you have any more experimenting that you can do? Or are you out of ideas?

**Comment by finnagin** [comment]
I can experiment more but wasn't sure exactly what to try. I was going to try to google a bit and see if maybe I can find some other options to try.

**Comment by finnagin** [comment]
Looks like changing the `RemoteIPTrustedProxy` line in the apache2 config file ti 172.17.0.1 fixed this issue and now I get the real ip address. Ready to try on arax.ncats.io.

**Comment by finnagin** [comment]
Possibly related when I run `apache2 -M` inside the container on arax.ncats.io I get the following output:
```
[Thu Jan 13 03:30:12.097390 2022] [core:warn] [pid 1426] AH00111: Config variable ${APACHE_LOCK_DIR} is not defined
[Thu Jan 13 03:30:12.097460 2022] [core:warn] [pid 1426] AH00111: Config variable ${APACHE_PID_FILE} is not defined
[Thu Jan 13 03:30:12.097473 2022] [core:warn] [pid 1426] AH00111: Config variable ${APACHE_RUN_USER} is not defined
[Thu Jan 13 03:30:12.097476 2022] [core:warn] [pid 1426] AH00111: Config variable ${APACHE_RUN_GROUP} is not defined
[Thu Jan 13 03:30:12.097496 2022] [core:warn] [pid 1426] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
[Thu Jan 13 03:30:12.101188 2022] [core:warn] [pid 1426:tid 139903586011008] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
[Thu Jan 13 03:30:12.101653 2022] [core:warn] [pid 1426:tid 139903586011008] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
[Thu Jan 13 03:30:12.101674 2022] [core:warn] [pid 1426:tid 139903586011008] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
AH00526: Syntax error on line 74 of /etc/apache2/apache2.conf:
Invalid Mutex directory in argument file:${APACHE_LOCK_DIR}
```

**Comment by finnagin** [comment]
This is line 74 in apache2.conf:
```
Mutex file:${APACHE_LOCK_DIR} default
```

**Comment by finnagin** [comment]
Oops that was a red herring, the error was because I ran `apache2` instead of `apachectl`. After running `apachectl` it looks as though the remote_ip module is running correctly but we are still not getting the correct ip address.

**Comment by edeutsch** [comment]
@finnagin I was able to get it to work! with:
```
- LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
+ LogFormat "%a %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
```
as suggested here:
https://serverfault.com/questions/888151/apache-doesnt-log-remoteip-when-remoteipheader-x-forwarded-for-is-present

**Comment by finnagin** [comment]
Awesome!

**Comment by finnagin** [comment]
@edeutsch  Where is that config file located?

**Comment by edeutsch** [comment]
I put it in remoteip.conf
although now that you mention it (i.e. didn't find it), maybe it should be moved to the main apache2.conf?
I didn't put it there because it seems so pristine and unchanged. It didn't want to soil it.

**Comment by finnagin** [comment]
@edeutsch Is this working and good to close now?

**Comment by dkoslicki** [comment]
Closing since we have seen it in action
