### ISSUE TITLE
finncicd LetsEncrypt SSL cert to expire on January 11

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1768]
FYI:

> 
> Hello,
> 
> Your certificate (or certificates) for the names listed below will expire in 11 days (on 11 Jan 22 21:32 +0000). Please make sure to renew your certificate before then, or visitors to your web site will encounter errors.
> 
> We recommend renewing certificates automatically when they have a third of their total lifetime left. For Let's Encrypt's current 90-day certificates, that means renewing 30 days before expiration. See https://letsencrypt.org/docs/integration-guide/ for details.
> 
> finncicd.rtx.ai
> 
> For any questions or support, please visit: https://community.letsencrypt.org/ Unfortunately, we can't provide support by email.
> 
> For details about when we send these emails, please visit: https://letsencrypt.org/docs/expiration-emails/ In particular, note that this reminder email is still sent if you've obtained a slightly different certificate by adding or removing names. If you've replaced this certificate with a newer one that covers more or fewer names than the list above, you may be able to ignore this message.
> 
> If you are receiving this email in error, unsubscribe at:
>  
> Please note that this would also unsubscribe you from other Let's Encrypt service notices, including expiration reminders for any other certificates.
> 
> Regards,
> The Let's Encrypt Team

**Comment by finnagin** [comment]
Didn't we terminate finncicd.rtx.ai?

**Comment by finnagin** [comment]
![finncicd rtx ai](https://user-images.githubusercontent.com/20198864/147841828-11efacba-a575-4b0d-9949-85de0d0f7241.png)

Looks like maybe we didn't terminate it? Though there are no ip addresses assigned to it.

**Comment by saramsey** [comment]
No, it has not been terminated. What do you want to do with the instance?

**Comment by finnagin** [comment]
finncicd.rtx.ai was terminated
