### ISSUE TITLE
ChemicalEntity query returning non-chemical entities

### ISSUE THREAD

**Issue by cbizon** [RTXteam/RTX#1772]
Run this query
```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n01",
                    "object": "n00",
                    "predicates": [
                        "biolink:risk_affected_by"
                    ]
                }
            },
            "nodes": {
                "n00": {
                    "categories": [
                        "biolink:ChemicalEntity"
                    ]
                },
                "n01": {
                    "categories": [
                        "biolink:Disease"
                    ],
                    "ids": [
                        "MONDO:0021117"
                    ]
                }
            }
        }
    }
}
```

against RTX KG2: https://arax.ncats.io/api/rtxkg2/v1.2/query

The query returns many results, but a number of them are UniProts:
```
UniProtKB:P04637
UniProtKB:P31749
UniProtKB:Q00987
UniProtKB:P00533
...
```

These are proteins, which in biolink is not a subclass of ChemcialEntity (they are under BiologicalEntity)

**Comment by saramsey** [comment]
Thanks for the bug report, Chris. I think I have found the issue, in the script that we use to ETL Reactome. I will file a bug report in RTX-KG2 and we will aim to get this fixed in RTX-KG2.7.6.

**Comment by saramsey** [comment]
Hi Chris, I have coded a fix for this in the RTX-KG2 build system. Should be fixed in the next KG2 build. @acevedol can provide details on the build timeline, as needed. Thanks again for the bug report; very helpful.

**Comment by finnagin** [comment]
Closing since this was moved to RTXteam/RTX-KG2#192
