### ISSUE TITLE
KP selection sensitive to 'preferred' category of pinned QNodes

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1773]
so it was puzzling that Expand doesn't select SPOKE for our standard acetaminophen query:
```
{
   "edges": {
      "e00": {
         "subject":   "n00",
         "object":    "n01",
         "predicates": ["biolink:physically_interacts_with"]
      }
   },
   "nodes": {
      "n00": {
         "ids":        ["CHEMBL.COMPOUND:CHEMBL112"]
      },
      "n01": {
         "categories":  ["biolink:Protein"]
      }
   }
}
```
https://arax.ncats.io/beta/?r=35328

because it seems like the kind of thing SPOKE should be able to answer.

it turns out that the problem lies in the category assigned to qnode `n00` behind the scenes. Expand, when it's examining KPs' meta knowledge graphs to select KPs, gives `n00` the preferred category according to the synonymizer ([here](https://github.com/RTXteam/RTX/blob/46ee1cc3fe084fc5d7175444f6cd60fba5e96fc0/code/ARAX/ARAXQuery/ARAX_expander.py#L166-L169)), which is `biolink:SmallMolecule`. 

but SPOKE's meta KG doesn't indicate that it can answer `(SmallMolecule)--[physically_interacts_with]-->(Protein)` queries. it can, however, answer `(ChemicalEntity)--[physically_interacts_with]-->(Protein)` queries, so this query that forces `n00`'s category to ChemicalEntity does use SPOKE (they return 32 edges):
```
{
   "edges": {
      "e00": {
         "subject":   "n00",
         "object":    "n01",
         "predicates": ["biolink:physically_interacts_with"]
      }
   },
   "nodes": {
      "n00": {
         "ids":        ["CHEMBL.COMPOUND:CHEMBL112"],
         "categories": ["biolink:ChemicalEntity"]
      },
      "n01": {
         "categories":  ["biolink:Protein"]
      }
   }
}
```
https://arax.ncats.io/beta/?r=35329

(note that Expand does do hierarchical reasoning when examining KPs' meta KGs, but in this case, SmallMolecule is more specific than ChemicalEntity, so the fact that SPOKE can answer ChemicalEntity for these queries doesn't imply it can answer SmallMolecule for such queries. though the reverse would be true.)

should we change the categories that Expand considers pinned qnodes to have? use more than just the 'preferred' category?

**Comment by saramsey** [comment]
Interesting. Thank you for the summary. Let's discuss it soon.

**Comment by amykglen** [comment]
after discussing with Steve: we're thinking a sufficient approach may be to have a little patch of sorts for the `ChemicalEntity` subtree of the Biolink model only (since I don't _think_ we're having this issue in other subtrees really, since we already force conflations for gene/protein and disease/phenotypic feature) - basically if a curie's preferred category is a descendant of `ChemicalEntity`, just consider it a `ChemicalEntity`.

also would probably be worth pointing this out to SPOKE, in case they want to get more specific with their categories.

note to whoever works on this issue: please document the reasoning for this in a comment in the code, and reference this issue! might appear like a strange decision otherwise.

**Comment by edeutsch** [comment]
Very interesting. good discussion. I think the proposed solution sounds very sensible.
When biolink:ChemicalSubstance was removed, they may have just thrown up their hands and switched all those to biolink:ChemicalEntity as the closest equivalent.

**Comment by rcpeene** [comment]
Issue was patched. Now when determining which KPs to use, any biolink category of a pinned node which is a descendent of of ChemicalEntity is now just considered ChemicalEntity. Will be tested with the next rollout of master.

**Comment by amykglen** [comment]
fyi @rcpeene - I think your code for this didn't make it into the rollout of `master` Eric just did since it looks like the PR still hasn't been merged into `master` - you can merge it whenever (I approved it)

**Comment by edeutsch** [comment]
lemme know when it is merged and I can roll out again.

**Comment by rcpeene** [comment]
Should be merged now.

**Comment by edeutsch** [comment]
rolled out to non-production endpoints
