### ISSUE TITLE
Links between OMIM diseases and phenotypes?

### ISSUE THREAD

**Issue by jaredroach** [RTXteam/RTX#178]
Is there a way to get phenotypes for these diseases, perhaps by leveraging Columbia Open Health Data (COHD)?

What are the phenotypes of RENAL CYSTS AND DIABETES SYNDROME; RCAD?

_Your question has been interpreted and is restated as follows:
   What are the phenotypes of the disease RENAL CYSTS AND DIABETES SYNDROME; RCAD?
Please ensure that this is an accurate restatement of the intended question.

No path between OMIM:137920 and phenotypic_feature via relationship has_phenotype_

**Comment by dkoslicki** [comment]
Closing due to #788 and current integration with COHD
