### ISSUE TITLE
Symmetric predicates and KP selection

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1784]
thanks to @rcpeene, we realized that some KPs (e.g., SPOKE) that can answer queries with predicates deemed 'symmetric' by the Biolink model only advertise being able to answer one direction for such queries. 

for example, SPOKE says it can answer this kind of query:
```
(ChemicalEntity)--[physically_interacts_with]-->(Protein)
```
but not this kind of query:
```
(Protein)--[physically_interacts_with]-->(ChemicalEntity)
```
but `physically_interacts_with` is symmetric, which implies they actually _can_ (or _should_ be able to) answer the latter kind of query as well.

when Expand is selecting KPs, it should probably be smart and consider this fact. (i.e., for symmetric predicates, it should look for KPs that advertise being able to answer that edge in _either_ direction.)

(one note: thinking about this further, I think even KG2's meta KG actually doesn't automatically advertise being able to answer both directions for symmetric predicates, although KG2 has **so** many meta edges that I think both directions almost always happen to be present...)

**Comment by rcpeene** [comment]
Code has been added in kp_selector.py, which for one hop queries, will check the given triple and its symmetrical triple. I wrote tests for SPOKE which seem to indicate it works. Merge request has been issued.
