### ISSUE TITLE
Test some reranking before the Relay

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1785]
Starting a new issue, although related to #1782 

Chris B has provided some results to play with. From his Slack post in general:
Eric Deutsch suggested that  I make the queries for the answer ranking session next week available ahead of time.   If you want to pre-rank some, you can find the answers in this repo https://github.com/TranslatorSRI/RankingComparison.   Specifically, we will want ARAs to rank the "result.json" files in input/*.   I'll be adding some two hops as well over the next day or two.

Would be good to test those.

**Comment by finnagin** [comment]
Looks like this works for the clinical_DCP example: https://arax.ncats.io/beta/?r=36497

**Comment by finnagin** [comment]
And the asthma example: https://arax.ncats.io/beta/?r=36498

**Comment by finnagin** [comment]
And the hyperlipidemia example: https://arax.ncats.io/beta/?r=36499

**Comment by edeutsch** [comment]
Can you explain what you're doing? When I try it, I get errors.

**Comment by finnagin** [comment]
I've pushed my changes to the `ExampleQuery_ReRankTest.py ` script. I'm running the result.json files in the sub-directories here: https://github.com/TranslatorSRI/RankingComparison/tree/main/inputs

**Comment by edeutsch** [comment]
Yes, your query seems to complete successfully. I was testing with 99adc6b5-0803-4c52-972e-fe587744a7aa
Does that one work for you?

**Comment by finnagin** [comment]
Nope, I'm getting errors too. What's weird is it says that specific edge binding id is not in the KG but when I search for it it comes up. I'll have to dig in a bit more to figure out what is going on here.

**Comment by finnagin** [comment]
@edeutsch I figured out what is happening in `99adc6b5-0803-4c52-972e-fe587744a7aa`. Even though we do not run resultify we are still recomputing the qedge keys using resultify somewhere. (maybe when we first get the query?) 

This then deletes edges in the knowledge graph that do not appear in the query graph. But, since we still have the old results their keys still exist in the edge bindings of the results. So, when we loop through each results edge bindings (while adding the rankings) we then try to get them from the knowledge graph which causes a key error since they were removed during the qedge key recompute step.

**Comment by edeutsch** [comment]
Would it be sensible to first check if the keys exist and if they do not, then just ignore them with a warning?

**Comment by finnagin** [comment]
Maybe, though I wonder if maybe we should be rethinking how we are removing edges from the knowledge graph since this seems to happen on possibly any query. Or maybe we should be checking for and removing the edge binding from the results as well whenever we remove edges from the knowledge graph.

**Comment by edeutsch** [comment]
I agree that removing the edge binding from the results as well whenever we remove edges from the knowledge graph would be a good strategy.

**Comment by dkoslicki** [comment]
Since #1793 is fixed and has a re-rank in it, can this be closed @edeutsch ?

**Comment by edeutsch** [comment]
yes, thanks, closing.
