### ISSUE TITLE
Provide a nice description of how we compute normalized google distance

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1789]
Related (but not the same as #1788), when we provide normalized google distances, the SME thought we should have a link out with more information on what it means.
At the moment, the attribute is:
attribute_type_id: | EDAM:data_2526
original_attribute_name: | normalized_google_distance
value_url: | https://arax.ncats.io/api/rtx/v1/ui/#/PubmedMeshNgd
value: | 0.151

First, the existing URL leads to a 404. which could be corrected to https://arax.ncats.io/api/arax/v1.2/ui/#/PubmedMeshNgd
But that link is not very informative.
something far more informative would be nice.

**Comment by dkoslicki** [comment]
done and merged
