### ISSUE TITLE
Need a fast query option

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1791]
I think today's event solidified in my mind that we need a "fast query" option (as opposed to a "thorough query" option) that should be the default for the UI. While 1 hop query are nearly always okay, two or more hop queries very often take a very long time unless the predicates are very carefully constrained. And the novice user will not know how to do that. Most of queries I tried today turned out to be pretty expensive queries and I got emails from other breakout sessions that had the same problem. I re-learned today that David always reaches for ARAXi to do FET filtering after intermediate steps so that queries finish in reasonable times. Novice users will not know how to do this. I can't even remember that I need to do this to get results in a reasonable time during a demo.

I think we need to implement a quick/thorough option in the system, where the default from the UI is quick. With this option, we don't wait around for 2 minutes for BTE to timeout and we do aggressive FET filtering (or something) after each step so that the user gets back a result quickly. If they like what they see and want more, then they can choose the "thorough" option.

What do you think?

**Comment by dkoslicki** [comment]
I do like this idea! I imagine we could also just reach out to RTX-KG2 instead of other KPs. Then @amykglen has knobs in `expand` she can twiddle to speed things up.

As for aggressive application of FET, I like this idea, but don't know how technically to do this outside of the query graph interpreter. I.e. if `expand` goes edge by edge, we could do FET immediately after expanding a query edge. Otherwise, we'd need to re-tool the query graph interpreter to expand a single edge, do FET + filter, and then repeat until all q_edges are exhausted. It would take a bit of care for figuring out the edge order (for non-linear queries)

**Comment by edeutsch** [comment]
I think Expander already has some code to do some ranking and filtering after each expansion to handle cases when there are 1000+ nodes. Maybe all we need to do is tweak that node filter to a much smaller number like 50 or even less when in "fast" mode?

**Comment by amykglen** [comment]
yeah, that would be easy to use a different 'threshold' for Expand's pruning when we're in 'fast' mode! 

definitely like this idea for a fast query mode.

**Comment by rcpeene** [comment]
On [this branch](https://github.com/RTXteam/RTX/tree/issue1791), ARAXExpander.apply() has been modified to take an optional impatient_mode parameter. When impatient_mode is set to true, the pre-prune threshold is set to 50 and the trapi querier's timeout is set to 30 seconds as opposed to 2 minutes. These could be tested and tweaked later.

To utilize this, [this block of code](https://github.com/RTXteam/RTX/blob/a298e8e1b8710fb802e673bb2e428dcefe90de18/code/ARAX/ARAXQuery/ARAX_query.py#L708) from ARAX_querier.py; line 708 will probably have to modified along with changes to the UI which I'm unfamiliar with.

**Comment by rcpeene** [comment]
After today's mini-hackathon, we decided to discard the changes made that added the impatient_mode option to ARAXExpander.apply(). We observed that, currently, we can manually set the user_timeout value from the ARAX UI via the "settings" tab, and we can set the pre-prune threshold as a parameter to expand() in the DSL.

Knowing this, we elected to stop using "user_timeout" as a separate traditional parameter of ARAX_expander.py: ARAXExpander.apply, and instead utilize it as a value in the "input_parameters" parameter of ARAXExpander.apply. 

We also intend to modify the ARAX UI to take both the timeout value and the pre-prune threshold in the "settings" tab and then pass those into the "input_parameters" argument of ARAXExpander.apply. This way, we can give these settings default values which are sufficiently small enough for a generally fast query, but which can also be manually set for a more robust query.

I will undo the previous changes to branch issue1791, and make the new changes to ARAX_expander.py. Changes will then have to made to ARAXQuery and the UI to utilize this.

**Comment by dkoslicki** [comment]
One example of a long running query:
```
{
  "edges": {
    "e00": {
      "constraints": [],
      "object": "n01",
      "subject": "n00"
    },
    "e01": {
      "constraints": [],
      "object": "n02",
      "subject": "n01"
    },
    "e02": {
      "constraints": [],
      "object": "n03",
      "subject": "n02"
    },
    "e03": {
      "constraints": [],
      "object": "n04",
      "subject": "n03"
    }
  },
  "nodes": {
    "n00": {
      "categories": [
        "biolink:SmallMolecule"
      ],
      "constraints": [],
      "ids": [
        "DRUGBANK:DB00150"
      ],
      "is_set": false
    },
    "n01": {
      "categories": [
        "biolink:Protein"
      ],
      "constraints": [],
      "is_set": false
    },
    "n02": {
      "categories": [
        "biolink:MolecularActivity"
      ],
      "constraints": [],
      "is_set": false
    },
    "n03": {
      "categories": [
        "biolink:MolecularActivity"
      ],
      "constraints": [],
      "is_set": false
    },
    "n04": {
      "categories": [
        "biolink:SmallMolecule"
      ],
      "constraints": [],
      "ids": [
        "KEGG.COMPOUND:C02700"
      ],
      "is_set": false
    }
  }
}
```

And the "killer" query:
```
{
  "message": {
    "query_graph": {
      "edges": {
        "e01": {
          "object": "n1",
          "predicates": [
            "biolink:has_real_world_evidence_of_association_with"
          ],
          "subject": "n0"
        },
        "e02": {
          "object": "n1",
          "predicates": [
            "biolink:gene_associated_with_condition"
          ],
          "subject": "n2"
        },
        "e03": {
          "object": "n3",
          "predicates": [
            "biolink:related_to"
          ],
          "subject": "n2"
        },
        "e04": {
          "object": "n4",
          "predicates": [
            "biolink:related_to"
          ],
          "subject": "n2"
        }
      },
      "nodes": {
        "n0": {
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ],
          "ids": [
            "MONDO:0005359",
            "SNOMEDCT:197358007",
            "MESH:D056487",
            "SNOMEDCT:197354009",
            "SNOMEDCT:427399008"
          ]
        },
        "n1": {
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ]
        },
        "n2": {
          "categories": [
            "biolink:Gene"
          ]
        },
        "n3": {
          "categories": [
            "biolink:ChemicalEntity"
          ]
        },
        "n4": {
          "categories": [
            "biolink:BiologicalProcessOrActivity"
          ]
        }
      }
    }
  },
  "stream_progress": true,
  "submitter": "ARAX GUI"
}
```
