### ISSUE TITLE
ARAX UI failing to issue queries

### ISSUE THREAD

**Issue by rcpeene** [RTXteam/RTX#1801]
When trying to issue queries on [the ARAX UI beta](https://arax.ncats.io/beta/) the query does not go work and an error is given:

`An error was encountered while contacting the server (SyntaxError: Unexpected end of JSON input)`

The status logs show:
```
2022-02-23T23:26:56.858521 DEBUG: in asynchronous_query
2022-02-23T23:26:56.858612 DEBUG: In query_return_stream
2022-02-23T23:26:56.858966 INFO: ARAX Query launching on incoming Query
2022-02-23T23:26:56.859051 INFO: Creating an empty template TRAPI Response
```

The error occurs on the examples for both JSON and DSL input.
It appears that some changes from @edeutsch's latest rollout of master were not functional.

**Comment by edeutsch** [comment]
hmm, strange because I tested it.
devED and /test are working.
ah, maybe /beta lost its MySQL connection? I see an error like that..
I just restarted /beta and it seems to work now?

Errors were:
```
INFO:root:[query_controller]: child process detected a SIGPIPE; exiting python
```

**Comment by rcpeene** [comment]
Works on my end now too.
