### ISSUE TITLE
Roll out KG2.7.5 (Biolink 2.2.11)

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX#1810]
_NOTE: To create a new issue based on this template, simply go to: https://github.com/RTXteam/RTX/issues/new?template=kg2rollout.md_

##### 1. Build and load KG2c:

- [x] merge `master` into the `kg2integration` branch
- [x] update the hardcoded biolink version numbers in the `kg2integration` branch (as applicable):
  - [x] for ARAX [here](https://github.com/RTXteam/RTX/blob/0107502d7da4f1ee70d76c2ca5e406a07b8012d1/code/UI/OpenAPI/python-flask-server/openapi_server/openapi/openapi.yaml#L18)
  - [x] for the KG2 API [here](https://github.com/RTXteam/RTX/blob/0107502d7da4f1ee70d76c2ca5e406a07b8012d1/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/openapi/openapi.yaml#L18)
- [x] build a new KG2c on `buildkg2c.rtx.ai` from the `kg2integration` branch (how-to is [here](https://github.com/RTXteam/RTX/tree/master/code/kg2c#build-kg2canonicalized))
  - [x] make sure to choose to build a new synonymizer in `kg2c_config.json`, as described in the how-to
  - [x] verify the build looks ok:
    - [x] the synonymizer sqlite should be around 15-17GB
    - [x] the entire build process (synonymizer + KG2c) shouldn't have taken more than about 16 hours
    - [x] the synonymizer and KG2c artifacts should have been auto-uploaded into the proper directory on `arax.ncats.io` (`/data/orangeboard/databases/KG2.X.Y`)
- [x] load the new KG2c into neo4j at http://kg2-X-Yc.rtx.ai:7474/browser/ (how to is [here](https://github.com/RTXteam/RTX/tree/master/code/kg2c#host-kg2canonicalized-in-neo4j))
- [x] upload the new `kg2c_lite_2.X.Y.json.gz` file to the [translator-lfs-artifacts](https://github.com/ncats/translator-lfs-artifacts/tree/main/files) repo
- [x] load the new KG2c into plover (available at http://kg2-X-Ycplover.rtx.ai:9990)

##### 2. Rebuild downstream databases:

Copies of all of these should be put in `/data/orangeboard/databases/KG2.7.5` on arax.ncats.io.

- [x] configv2.json (should point to the new KG2/KG2c/plover)
    - note: save this as `config_local.json`, since we want it to be used over `configv2.json` during testing
- [x] NodeSynonymizer
- [x] KG2c meta knowledge graph
- [x] KG2c sqlite
- [x] KG2c TSV tarball
- [x] KG2c neo4j dump (this is created on the neo4j hosting instance when loading KG2c, at `/home/ubuntu/kg2-build/kg2c.dump`)
-  [x] FDA-approved drugs pickle
- [x] NGD database
- [x] COHD database @chunyuma
- [x] refreshed DTD @chunyuma
- [ ] DTD model @chunyuma _(may be skipped - depends on the KG2 version)_
- [ ] DTD database @chunyuma _(may be skipped - depends on the KG2 version)_

**NOTE**: As databases are rebuilt, the new copy of `config_local.json` will need to be updated to point to their new paths. However, if the rollout of KG2 has already occurred, then you should update the master `configv2.json` directly. 

##### 3. Update the ARAX codebase:

All code changes should go in the `kg2integration` branch.

- [x] update the KG2 version number (to 2.X.Y) in the KG2 openapi.yaml
- [x] update Expand code as needed
- [x] update any other modules as needed
- [x] test everything together (entire ARAX pytest suite should pass when using the new `config_local.json` - must locally set `force_local = True` in `ARAX_expander.py` to avoid using the old KG2 API)

##### 4. Do the rollout:

- [x] merge `master` into `kg2integration`
- [x] merge `kg2integration` into `master`
- [x] make `config_local.json` the new master config file on araxconfig.rtx.ai (rename it to `configv2.json`)
- [x] roll `master` out to the various arax.ncats.io endpoints and delete their `configv2.json`s
- [x] run the pytest suite on the various endpoints

##### 5. Final items/clean up:

- [ ] update the CI/CD instance:
  - [ ] replace the `configv2.json` file on `cicd.rtx.ai` with the new one
  - [ ] download the new database files to `cicd.rtx.ai`
- [ ] generate KGX files and upload them to the KGE Archive @acevedol 
- [ ] update the test triples that go in some NCATS repo @finnagin
- [x] rename the `config_local.json` on arax.ncats.io to `config_local.json_FROZEN_DO-NOT-EDIT-FURTHER` (any additional edits to the config file should be made directly to the master `configv2.json` on araxconfig.rtx.ai going forward)
- [x] turn off the old KG2c version's neo4j instance
- [x] turn off the old KG2 version's plover instance
- [x] turn off the new KG2pre version's neo4j instance
- [x] upgrade the NCATS-hosted Plover endpoint (https://kg2cploverdb.ci.transltr.io) to this KG2 version and make the KG2 API start using it (instead of our self-hosted endpoint): 
    - [x] update `kg_config.json` in the `main` branch of the Plover repo to point to the new `kg2c_lite_2.X.Y.json.gz` file (push this change)
    - [x] wait about 45 minutes for the endpoint to rebuild and then run Plover tests to verify it's working
    - [x] run the ARAX pytest suite with the NCATS endpoint plugged in: use a `config_local.json` that points to it and locally set `force_local = True` in Expand
    - [x] if all tests pass, update the master `configv2.json` on araxconfig.rtx.ai to point to this Plover endpoint (used by beta endpoints)
    - [x] also update production ARAX/KG2's config files to point to this Plover endpoint
    - [x] delete the arax.ncats.io `kg2` endpoint's `configv2.json` to force it to download the new copy and then verify it's working correctly by running a query
    - [x] verify production ARAX/KG2 are working as well
    - [x] turn off our plover endpoint and verify once more that ARAX is still working ok

**Comment by finnagin** [comment]
FYI we should replace the step "'slim' databases (used for Travis)" with:
- [ ] replace the config file on cicd.rtx.ai with the new one
- [ ] download the new database file to cocd.rtx.ai

**Comment by acevedol** [comment]
Thanks, Finn! I corrected that step.

**Comment by chunyuma** [comment]
Hi @acevedol, I want to check with you to see if the new version KG2c is loaded into bolt://kg2-7-5c.rtx.ai:7687 instead of http://kg2-x-yc.rtx.ai:7474/browser/. Thanks!

**Comment by finnagin** [comment]
Fyi not sure if this is part of the process normally or when we do the node synonymizer step we should refresh the sri_node_normalizer database by running sri_node_normalizer.py with --build to get the newest sri node normalizer data. 

Should we add that as a check box above the node synonymizer step @acevedol or is that already a part the standard process for rebuilding the node normalizer?

**Comment by edeutsch** [comment]
It is already part of the process. It has to be.

**Comment by finnagin** [comment]
Ah that makes sense. Ignore my last comment then.

**Comment by amykglen** [comment]
hey @chunyuma - everything is now ready for you to start rebuilding the DTD and COHD databases for KG2.7.5. (we're tentatively planning to do the final KG2.7.5 rollout at this Wednesday's mini-hackathon)

**Comment by chunyuma** [comment]
Thanks @amykglen. I will start rebuilding them later tonight. I'm not sure if I can finish it on Wednesday since I'm recently busy for my comprehensive exam.  But I will try it.
