### ISSUE TITLE
Name parsing bug in ARAX UI

### ISSUE THREAD

**Issue by sandrine-m** [RTXteam/RTX#1813]
@isbluis @edeutsch Using the [ARAX UI](https://arax.ncats.io/), when I try to put "MT-CO2" and "MT-CYB" (two gene symbols) separated by a comma in the input list queries, it does not parse properly:
Input:
MT-CO2
MT-CYB
output:
![image](https://user-images.githubusercontent.com/66342541/159287055-d22308c9-c068-4815-8cee-65fbc5cda35f.png)
Looks like it is parsing "MT-CYB" as "Mt" and "CYB" and "MT-CO2" as "MT" and "CO2". However, other mitochondrial genes like "MT-ND1" are working fine.

Also, the HLA family genes (HLA-A, HLA-B, HLA-C) are not parsed properly.

**Comment by isbluis** [comment]
Making a note here that commas that are part of the node name also break the call to the /entity API endpoint.

**Comment by isbluis** [comment]
Hello @sandrine-m .  There can be issues when certain special characters (non-alphanumeric) are part of a node name.  It will work if you place the each name within quotes, separated by commas:
![image](https://user-images.githubusercontent.com/37852256/159804151-829ec70c-30f5-4833-b00d-73dc17b938ed.png)

![image](https://user-images.githubusercontent.com/37852256/159804017-1f67b02a-8d2c-4ac8-bc82-53ec2812940d.png)


Thank you for reporting this, and let us know if this works and is okay to close.

**Comment by sandrine-m** [comment]
Hello @isbluis, thank you! the trick works!
