### ISSUE TITLE
RED ALERT: RTX-KG2 is down?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1814]
I received an error alert.
ARAX was in a snit and I restarted it. Seems better
But RTX-KG2 was also not working. I restarted the process on arax.ncats.io, but that did not seem to help. I suspect ITRB killed off PloverDB but am just guessing. I see this on the arax.ncats.io error logs.
```
022-03-29T22:10:04.715889 DEBUG: [] Sending batch 1 to Plover (has 1 input curies)
2022-03-29T22:10:05.016173 WARNING: [] Plover returned a status code of 502. Response was: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.21.1</center>
</body>
</html>

2022-03-29T22:10:05.016288 ERROR: [RequestFailed] Plover returned response of 502. Answer was: {}
```

HELP!

And maybe this is frequent enough that we need a process to deal with this.

**Comment by saramsey** [comment]
I have contacted Amy on Slack

**Comment by saramsey** [comment]
Should we follow this procedure? 

https://github.com/RTXteam/PloverDB/wiki/Deployment-how-tos

**Comment by saramsey** [comment]
Tagging Amy and Carter

**Comment by saramsey** [comment]
I don't see any kg2cplover instance running in `us-west-2`, which suggests that the current production RTX-KG2 is (as I would expect) using the ITRB PloverDB; so all signs seem to indicate an outage of ITRB PloverDB.
<img width="784" alt="Screen Shot 2022-03-29 at 3 19 45 PM" src="https://user-images.githubusercontent.com/5562107/160716534-db63c4c4-a3f1-4cef-a740-71bd8d364744.png">

**Comment by amykglen** [comment]
yes, that's the classic sign that ITRB blew away their Plover endpoint again. and yes, that link Steve shared is how to start up our own Plover (generally used temporarily until the ITRB Plover is back up)

**Comment by amykglen** [comment]
I'm starting up our own Plover now

**Comment by amykglen** [comment]
ok, both `/kg2` and `/kg2beta` are back up now, using our own Plover. and I notified ITRB of their broken endpoint via the Translator slack.

**Comment by edeutsch** [comment]
It seems we agreed on Wednesday to switch back to ITRB Plover? However, it looks to me that the production server still is using our local Plover instance? But I'm not certain, since I'm not so familiar with this. And I don't think I can control our Plover.

Maybe we should also have agreed on Wednesday who will do the switch?

Would someone familiar with this subsystem switch us if it hasn't already been done and then close this issue when everything is taken care of?

**Comment by amykglen** [comment]
ha, yep, I just took care of it - I was waiting because Kanna said they were doing another update to their Plover instance, but I got the all clear this morning.
