### ISSUE TITLE
UncaughtError in Expand/kg2

### ISSUE THREAD

**Issue by isbluis** [RTXteam/RTX#1816]
The following query keeps getting posted by Explanatory Agent and generates an **UncaughtError**:
`An uncaught error was thrown while trying to Expand using infores:rtx-kg2 (local). Error was: Traceback (most recent call last): File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/controllers/../../../../../../AR
`

The query:
```
{
  "message": {
    "query_graph": {
      "edges": {
        "e0": {
          "object": "n1",
          "predicates": [
            "biolink:entity_negatively_regulates_entity"
          ],
          "subject": "n0"
        }
      },
      "nodes": {
        "n0": {
          "categories": [
            "biolink:ChemicalEntity"
          ]
        },
        "n1": {
          "categories": [
            "biolink:Gene"
          ]
        }
      }
    }
  },
  "remote_address": "52.188.146.150",
  "submitter": "infores:explanatory-agent"
}
```

![image](https://user-images.githubusercontent.com/37852256/161628588-52f9f3c8-630c-4656-864b-64b4ebe8b358.png)

It might be worth noting that this error does not occur if posting via the UI:
![image](https://user-images.githubusercontent.com/37852256/161628938-52b90d43-d8d0-43d9-ba78-3ac643f118cd.png)

**Comment by edeutsch** [comment]
From the web logs, the full error is:
```
2022-03-31T05:17:36.884740 DEBUG: [] Expanding e0 by querying Plover directly
2022-03-31T05:17:37.195021 ERROR: [UncaughtError] An uncaught error was thrown while trying to Expand using infores:rtx-kg2 (local). Error was: Traceback (most recent call last):
  File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/controllers/../../../../../../ARAX/ARAXQuery/ARAX_expander.py", line 543, in _expand_edge_kg2_local
    answer_kg = kg2_querier.answer_one_hop_query(one_hop_qg)
  File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/controllers/../../../../../../ARAX/ARAXQuery/Expand/kg2_querier.py", line 70, in answer_one_hop_query
    input_curie_set = set(input_curies)
TypeError: 'NoneType' object is not iterable
```

**Comment by amykglen** [comment]
hmm, so it looks like for ARAX, the error is caught in `query_graph_info.py`:
https://github.com/RTXteam/RTX/blob/7427abd9a0960b82d365db21c44e76e04868ab84/code/ARAX/ARAXQuery/query_graph_info.py#L123-L126

so I guess that code must not be being run when in KG2 mode? should we think about running it for KG2 too? or should Expand do special validation when in KG2 mode?

**Comment by edeutsch** [comment]
I put that code in there for ARAX so that ARAX doesn't even attempt a query such as this: which ChemicalEntities negatively regulate which Genes?

Perhaps KG2 could answer that? If the predicate is specific enough?
Should it try?

**Comment by amykglen** [comment]
hmm.. if we want KG2 to be able to answer that kind of query it'd require some significant code changes, since Plover and the rest of the system is set up to always expect at least one "pinned" curie. (Plover's indexes heavily rely on that fact.)

would it be very useful?

**Comment by edeutsch** [comment]
Then I think it is best to leave it the way it already is. Except maybe do an explicit check that at least one node is pinned, and return an error if not.

**Comment by amykglen** [comment]
@rcpeene - do you want to work on this? (add a check somewhere early on in `ARAX_expander.py` that makes sure at least one QNode has a non-empty `ids` property - I think this check could be run regardless of what 'mode' we're in (RTXKG2 vs. ARAX))

**Comment by edeutsch** [comment]
query_graph_info.py already does this on the ARAX side. You could just call query_graph_info. But it also does a lot of other stuff that is probably unnecessary. Maybe just easier to add a couple lines to existing code, I don't know.
