### ISSUE TITLE
Missing category for FET expand

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1817]
For this query:
```
add_qnode(ids=[UMLS:C0220914,CHEMBL.COMPOUND:CHEMBL2108117,HMDB:HMDB0304735], categories=[biolink:ChemicalEntity], key=n0)
add_qnode(key=n1)
add_qedge(key=e0,subject=n0,object=n1,predicates=biolink:affects)
expand()
overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n0, object_qnode_key=n1)
overlay(action=fisher_exact_test,subject_qnode_key=n0,virtual_relation_label=F1,object_qnode_key=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=100)
```
I am getting the following error: `Object node with qnode key n1 was set to None in Query Graph. Please specify the node type`. This is likely the FET step in expand not liking the generic middle node. Would be nice to find some way around this (say, for each returned n1, when FET is used, take the category of that current n1).

**Comment by amykglen** [comment]
if the logic wasn't added to FET itself, I think the `overlay(action=fisher_exact_test..)` step in @dkoslicki's example query would produce the same error

**Comment by dkoslicki** [comment]
I think having FET populate the category of the more to NamedThing if it's not present makes the most sense. @chunyuma would you be able to do this at some point? And @amykglen , would that mean expand() wouldn't need to be modified?

**Comment by amykglen** [comment]
yes, that's right - in that case Expand shouldn't need to be modified

**Comment by chunyuma** [comment]
So @dkoslicki and @amykglen, if I understand correctly, your conclusion is when a query node is not given a specific type, we assume it to be `NamedThing`, right? If so, one thing I might need to mention is that setting it to NamedThing doesn't mean FET will consider all subtypes under NamedThing, it will only consider `NamedThing` itself. If you think this makes sense, then I will do this.

**Comment by dkoslicki** [comment]
Ah, I see. @amykglen do you know if every node in RTX-KG2 has the category `NamedThing` in addition to its more specific types? If so, then @chunyuma that should be fine. If not, then I do see what you mean about this possibly causing and issue: a particular node could be, say, a `ChemicalEntity` satisfying qnode n1, but if we have FET treat it as a NamedThings, it would be compared to other NamedThings, not other ChemicalEntities. In this case, do you think it would be easy/difficult to have FET fill in the category on-the-fly by using the category for the actual nodes used to satisfy qnode n1?

**Comment by chunyuma** [comment]
>  In this case, do you think it would be easy/difficult to have FET fill in the category on-the-fly by using the category for the actual nodes used to satisfy qnode n1?

@dkoslicki, I don't quite understand what you meant in this sentence for `using the category for the actual nodes used to satisfy qnode n1`? Could you please give me an example?

Actually, whether setting a specific qnode type in the FET will involve two issues. One is the accuracy of FET results. If we set a qnode type, then the FET contingency table only considers this specific type. This error occurs because I didn't allow the cases without a specified qnode type. So this can be modified. But if no qnode type is specified, then the running time will need to be considered. I am just concerned that using all types might make FET run slower.

**Comment by amykglen** [comment]
> @amykglen do you know if every node in RTX-KG2 has the category NamedThing in addition to its more specific types?

so nodes in KG2c are labeled with their categories as well as all ancestors of those categories (so every node in KG2c is labeled with NamedThing). however, I just looked at the code that tallies up the category/neighbor counts in the KG2c sqlite (that I believe FET uses), and it looks like it's _not_ considering all ancestors of a node's categories (only the raw contents of `all_categories`). but this could be changed pretty easily.

**Comment by chunyuma** [comment]
Thanks @amykglen. I think it will be pretty helpful if you can change the KG2c sqlite by considering all ancestors of a node's categoreis.

**Comment by dkoslicki** [comment]
I think the "treat every node as a NamedThing" and "assign NamedThing to query nodes without categories" is the most straightforward. 

To clarify my alternate idea @chunyuma , here is what I was thinking: say the query graph is (n0)-[r:`biolink:related_to`]-(n1:Disease). So n1 has its category specified, but n0 does not. Say there are two nodes that satisfy query node n0: (n0_a:ChemicalEntity{id:"ABC:123"})  and (n0_b:BiologicalEntity{id:"DEF:456"}). Since n0_a has the category ChemicalEntity, when overlaying a FET edge from n0_a to n1, use `ChemicalEntity` as the category to form the contingency tables. Since n0_b has category BiologicalEntity, use `BiologicalEntity` as the category to form its FET contingency table.

**Comment by amykglen** [comment]
ok, we can make that tweak to the KG2c sqlite. depending on where the KG2.7.5 build is at maybe I'll just do a partial rebuild to regenerate the sqlite.

**Comment by amykglen** [comment]
just to clarify where this issue is at: back in April I made the change discussed - so that the category/neighbor counts in the KG2c sqlite _do_ consider ancestors of a node's categories.

it looks like maybe FET hasn't been updated though because @dkoslicki's original DSL still errors in FET with: `Object node with qnode key n1 was set to None in Query Graph. Please specify the node type`

**Comment by chunyuma** [comment]
Sorry @amykglen, I didn't realize that you have finished the partial rebuild of KG2c sqlite. So does the KG2c sqlite now consider all ancestors of a node's categories? Thanks @amykglen.

**Comment by amykglen** [comment]
yep, that's right

**Comment by chunyuma** [comment]
Sorry for fixing this bug so late. Now the node without a specified node type will be set to 'biolink:NamedThing'. I tested it locally and it works for FET. Once it still works in production, I think this issue can be closed.

**Comment by chunyuma** [comment]
Close it as it has been completed.
