### ISSUE TITLE
Duplicate proteins

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#182]
There exist duplicate proteins:
```
match (n{rtx_name:"I3NI32"}) return n
```
```
match (n{rtx_name:"Q02127"}) return n
```
on http://rtxdev.saramsey.org:7674/browser/

Appears to be a problem in Uniprot itself.

**Comment by saramsey** [comment]
Yes I am aware of this issue. Is this going to mess up RTX performance at the hackathon?  Trying to gauge severity.

**Comment by dkoslicki** [comment]
No, not priority: I can always fall back on the python scripts themselves and disambiguate by hand. Post-hackathon issue.

**Comment by saramsey** [comment]
this is a duplicate of #214 ; closing this issue as the latter issue has more comments and has the commit hooks for code changes to address the issue
