### ISSUE TITLE
Supposedly BTE now has a ARA and KP endpoint. Which do we use?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1821]
At the architecture call, I learned that that BTE now supposedly has an "ARA endpoint" and a "KP endpoint".

I think this is the "KP endpoint":
https://smart-api.info/ui/36f82f05705c317bac17ddae3a0ea2f0
(which we should be calling)

and I think this is the "ARA endpoint":
https://smart-api.info/ui/dc91716f44207d2e1287c727f281d339
(which I think we should not be calling because it's another ARA).

Do I have this right?
Are we indeed calling the KP endpoint and not the ARA endpoint?

**Comment by amykglen** [comment]
it looks like we're calling the ARA endpoint, but I agree we should probably instead be calling the KP endpoint. (this is the first I've heard of it)

https://github.com/RTXteam/RTX/blob/7427abd9a0960b82d365db21c44e76e04868ab84/code/ARAX/ARAXQuery/Expand/expand_utilities.py#L527

**Comment by rcpeene** [comment]
With the changes addressed in [issue 1466](https://github.com/RTXteam/RTX/issues/1466), the bte KP (named in SmartAPI as infores:service-provider-trapi) does show up from the smartapi.py module results. Once those changes are pushed to production, this KP will be fully used by ARAX.
