### ISSUE TITLE
Uncaught error during synonymizer build

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1822]
the synonymizer build for KG2.7.5 made it through about 70% of the SRI node normalizer cache filling process, and then errored out with this:
```
................................71%.................................................................
....................Uncaught error during web request to SRI normalizer
Traceback (most recent call last):
  File "sri_node_normalizer.py", line 462, in <module>
    if __name__ == "__main__": main()
  File "sri_node_normalizer.py", line 437, in main
    normalizer.fill_cache()
  File "sri_node_normalizer.py", line 144, in fill_cache
    results = self.get_node_normalizer_results(batch)
  File "sri_node_normalizer.py", line 299, in get_node_normalizer_results
    status_code = response_content.status_code
UnboundLocalError: local variable 'response_content' referenced before assignment
```

**Comment by amykglen** [comment]
ok, I think I addressed the issue where `response_content` was being accessed before assignment, and at the same time I switched to POST requests instead of GET (as Eric had mentioned needed to happen in slack)

the commits are linked above if you want to take a peek @edeutsch (they're in the `kg2integration` branch)

**Comment by amykglen** [comment]
I'm going to close this out because the build completed successfully with these changes

**Comment by edeutsch** [comment]
Hi Amy, thanks so much for fixing this! I was unable to get to it.
