### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by JamieSlome** [RTXteam/RTX#1823]
Hey there!

I belong to an open source security research community, and a member (@deleterepo) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by saramsey** [comment]
Hi Jamie,

Thank you, I have added a SECURITY.md file.

We are working on this security issue that your team reported. Thank you for bringing this to our attention.

Stephen Ramsey

On Apr 16, 2022, at 8:04 PM, Jamie Slome ***@***.******@***.***>> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


Hey there!

I belong to an open source security research community, and a member ***@***.***<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdeleterepo&data=04%7C01%7Cstephen.ramsey%40oregonstate.edu%7C9b67d4ceb5204e0ef9ce08da201efeac%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637857614745549655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cigwit9SSjfcJjvDyKRvFfmYj7IU%2BOGogvBVhwrlKrE%3D&reserved=0>) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a SECURITY.md file with an email, or another contact method? GitHub recommends<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.github.com%2Fen%2Fcode-security%2Fgetting-started%2Fadding-a-security-policy-to-your-repository&data=04%7C01%7Cstephen.ramsey%40oregonstate.edu%7C9b67d4ceb5204e0ef9ce08da201efeac%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637857614745549655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iEo2dUYhBDJJU7zF%2F1augJ0pu5iM874QLONNyjngPL0%3D&reserved=0> this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhuntr-helper&data=04%7C01%7Cstephen.ramsey%40oregonstate.edu%7C9b67d4ceb5204e0ef9ce08da201efeac%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637857614745549655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eegOE4PehldKaXQ1x7v1C1gTwh%2BoCotm0%2B7EthV%2B4XU%3D&reserved=0>)
