### ISSUE TITLE
New layout for graphs

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1831]
Luis and Eric: I know you have been looking for a new/better way to render graph layouts, so wanted to pass [this approach](https://nbviewer.org/gist/dkoslicki/397fc8022b7f279f7d770cb165185d6e) from Chunyu along for your consideration.

**Comment by edeutsch** [comment]
Thanks for passing it along. This looks like a static image mechanism to me. Which would add a lot of complexity wrt generating and caching static images. If there is to be any sort of clicking for more information, which seems necessary, some sort of clickable imagemap mechanism would be needed. I'm thinking this would be tough to implement in a pleasing way. I Googled around a little and found a GraphViz for JS:
http://webgraphviz.com/
The layout engine seems pretty cool here. but no clickability.
Doesn't look like the right thing to me..

**Comment by edeutsch** [comment]
although better graph layouts might be nice, this hasn't been discussed in years and probably not a priority for this phase. closing.
