### ISSUE TITLE
add maturity_level, domain, and instance_name as attributes to RTXConfiguration class

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1839]

**Comment by edeutsch** [comment]
The master table of our instances and their maturity levels is here:
https://docs.google.com/spreadsheets/d/1eC3GrRW6gw5zn7XKjvaHD9KCulO-GqEaTJ3mG6PgOOY/edit#gid=0

**Comment by finnagin** [comment]
Removing myself from this. Eric an finish up if needed.

**Comment by dkoslicki** [comment]
From 6/5 meeting with Finn: @edeutsch to finish it

**Comment by edeutsch** [comment]
appears done. closing.
