### ISSUE TITLE
ITRB Plover down again

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1841]
the ITRB CI plover (which `kg2` and `kg2beta` are pointed to) seems to have gone down in the last hour or so (returning 502 bad gateway errors again)

pinging Kanna. the production Plover seems to be working though, so I'll point us to that one for now.

**Comment by amykglen** [comment]
both `kg2` and `kg2beta` are working again, now that they're pointed to the prod ITRB Plover

**Comment by edeutsch** [comment]
thank you!
