### ISSUE TITLE
subclass reasoning/inference for UBERON

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1849]
From the Relay, it appears RTX-KG2 is not doing subclass inference for UBERON

**Comment by amykglen** [comment]
I'll be addressing this soon along with #1812

**Comment by edeutsch** [comment]
try to fix for end of Sprint 6?
@amykglen

**Comment by amykglen** [comment]
this is live on KG2 Plover CI! for instance, submitting this query for molecular activities related to 'exocrine gland' to kg2cploverdb.ci.transltr.io returns results involving 'exocrine gland' but also 'liver':
```
{
  "edges": {
    "e00": {
      "object": "n01",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n00"
    }
  },
  "nodes": {
    "n00": {
      "ids": [
        "UBERON:0002365"
      ]
    },
    "n01": {
      "categories": [
        "biolink:MolecularActivity"
      ]
    }
  }
}
```
closing
