### ISSUE TITLE
Add Human Phenotype Ontology as a knowledge source

### ISSUE THREAD

**Issue by jaredroach** [RTXteam/RTX#185]
http://human-phenotype-ontology.github.io/tools.html

seems to be a svelte source of disease-phenotype edges
recommended by Miriam Udler of Broad/MGH on Indigo (Gray) team.

**Comment by dkoslicki** [comment]
@jaredroach Actually, I think this is what we're using:
```
MATCH (n:phenotypic_feature) RETURN n LIMIT 25
```
Returns stuff that points to:
http://www.ontobee.org/ontology/HP?iri=http://purl.obolibrary.org/obo/HP_0003071
Which is part of the Human Phenotype Ontology
@saramsey, correct me if I've wrong, but we're already using, right?

**Comment by jaredroach** [comment]
Interesting. Yes it appears that both these websites are different implementations of UIs to the same raw data.

I thought we were using COHD to get the disease-phenotype edges.

**Comment by dkoslicki** [comment]
Not quite: we use COHD to add "frequencies" to disease-phenotype edges (obtained from HPO).

**Comment by dkoslicki** [comment]
Closing, as we already use Human Phenotype Ontology (unless @saramsey objects).
