### ISSUE TITLE
initial support for knowledge_type inferred

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1853]
I have updated the master branch to have initial support for knowledge_type "inferred".
It is rolled out to /devED, /test, and kg2beta only.
And it appears to work, in that if you specify something like:
```
   "edges": {
      "e00": {
         "subject":   "n00",
         "object":    "n01",
         "predicates": ["biolink:physically_interacts_with"],
         "knowledge_type": "inferred"
      }
   },
```
to ARAX, it accepts it without throwing an error, and Expand receives it, and in fact Expand passes it along to the KPs but otherwise ignores it. kg2beta receives it successfully but otherwise ignores it. All other KPs apparently ignore it.

So I think that's working.
Now we just need to decide how we're going to deploy the resource and what Expand will do when it sees "knowledge_type": "inferred".

**Comment by amykglen** [comment]
good to close this @edeutsch? (since we have ARAXInfer now)

**Comment by edeutsch** [comment]
absolutely, thanks!
