### ISSUE TITLE
QGI not interpreting query graph correctly

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1857]
In this result: https://arax.ncats.io/?r=50233
This query:
```
{
        "edges": {
            "e00": {
                "subject": "n00",
                "object": "n01"
            }
        },
        "nodes": {
            "n00": {
                "ids": ["MONDO:0021783"],
                "categories": ["biolink:Disease"]
            },
            "n01": {
                "categories": ["biolink:ChemicalEntity"]
            }
        }
    }
```
Should match [this template](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter_templates.yaml#L117-L132). However, it appears to be matching [this template](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter_templates.yaml#L63-L75) instead.

@edeutsch Is the QGI greedy, in that it selects the first template it sees and just runs with it? I figured since this query matched a more specific one, it would have triggered that.

**Comment by edeutsch** [comment]
It's been a long time since I looked at this code, but I'm pretty sure to computes a goodness-of-match for all possible templates and selects the closest. Not the just first.

**Comment by dkoslicki** [comment]
Ok, I'll keep poking at it

**Comment by dkoslicki** [comment]
So I figured out what was going on: a) categories were being ignored if curies were present and b) the template requires categories like `categories=['biolink:Disease']` not `categories=biolinkDisease`.

The question now is: do we want `master` to have these changes? My concerns are:
1. If there are operations and workflow, we don't want the QGI overriding these (I don't think it does currently, but not 100% sure)
2. Make sure that the `inferred` is handled correctly, since this property is likely ignored by the QGI when doing template matching

**Comment by dkoslicki** [comment]
See PR #1858

**Comment by dkoslicki** [comment]
Associated PR was closed, and this is also depreciated due to the `inferred` mode
