### ISSUE TITLE
Need to pick one interpretable instance of a query

### ISSUE THREAD

**Issue by jaredroach** [RTXteam/RTX#186]
on rtx.ncats.io/beta

What diseases are similar to cystic fibrosis?

-> The most similar question I can answer is: What diseases have similar phenotypes to $disease But I found: "Multiple terms found for disease: ['DOID:1485', 'OMIM:219700']"

**Comment by dkoslicki** [comment]
I've added the ability to use identifiers in the UI, so you can make the (informed) decision yourself. So in this example:
"What diseases are similar to DOID:1485"
This was much more straightforward to implement, can work on making the decision automatically at some later point. @edeutsch Do you want to implement these changes in one of the UI URL's?

**Comment by dkoslicki** [comment]
Closing due to #788
