### ISSUE TITLE
Test suite over-writes message ids

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1868]
I've noticed this when running `test_ARAX_expand.py`, that the log includes messages like `2022-07-07T15:11:05.177757 INFO: [] Result was stored with id 231. It can be viewed at https://arax.ncats.io/?r=231`
Going to https://arax.ncats.io/?r=231, indeed this result exists and was the one that the test created, thereby overwriting what used to be response 231.

**Comment by amykglen** [comment]
from discussion on 8/3: @edeutsch to look into turning off the uploading of responses to S3 when locally running test suite

**Comment by edeutsch** [comment]
I think this was fixed with #2203
