### ISSUE TITLE
Upgrade to TRAPI 1.3

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1871]
RTX-KG2 and ARAX need to upgrade to TRAPI 1.3 soon. RTX-KG2 deadline is July 14. ARAX deadline is July 28.
Work is occurring in the `NewFmt` branch

To do list:
- [x] Catch up NewFmt to master
- [x] Create new TRAPI 1.3 schema YAMLs
- [x] Autogenerate and update models (classes) and controllers
- [x] Update instances of 1.2 to 1.3 in UI components
- [x] Update messenger and other hard-coded 1.2 mentions
- [x] Update expander and other components to use new classes (@amykglen )
- [x] Update ARAX UI to handle TRAPI 1.3 changes (@isbluis )
- [x] Test and deploy (@edeutsch )

**Comment by edeutsch** [comment]
https://arax.ncats.io/devED/ is running on the NewFmt branch and thus running TRAPI 1.3 with some limited success. Queries don't currently work. First error is:

```
  File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_expander.py", line 31, in <module>
    from openapi_server.models.query_constraint import QueryConstraint
ModuleNotFoundError: No module named 'openapi_server.models.query_constraint'
```

This is expected because QueryConstraint has been renamed AttributeConstraint.

```
	renamed:    query_constraint.py -> attribute_constraint.py
	new file:   qualifier.py
	new file:   qualifier_constraint.py
	deleted:    sub_attribute.py
	modified:   attribute.py
	modified:   edge.py
	modified:   meta_edge.py
	modified:   meta_knowledge_graph.py
	modified:   node_binding.py
	modified:   q_edge.py
	modified:   q_node.py
```

Next step: Update expander for TRAPI 1.3 changes, tagging @amykglen

**Comment by amykglen** [comment]
ok, I fixed the `QueryConstraint` problem @edeutsch reported and Expand tests _mostly_ seem to be passing in `NewFmt` now. @edeutsch - is it correct that `QEdge.constraints` has been renamed to `QEdge.attribute_constraints` in TRAPI 1.3, but `QNode.constraints` was **not** renamed to `QNode.attribute_constraints`?

also, I thought that [this](https://github.com/NCATSTranslator/ReasonerAPI/blob/1.3/docs/reference.md#qedge-) page should be the best place to look for TRAPI 1.3 class descriptions, but that doesn't appear updated for TRAPI 1.3, even though it's in the `1.3` branch. is that intended?

**Comment by edeutsch** [comment]
> ok, I fixed the `QueryConstraint` problem @edeutsch reported and Expand tests _mostly_ seem to be passing in `NewFmt` now. @edeutsch - is it correct that `QEdge.constraints` has been renamed to `QEdge.attribute_constraints` in TRAPI 1.3, but `QNode.constraints` was **not** renamed to `QNode.attribute_constraints`?

It is true. But is it wise? I don't think we carefully considered whether to change that. And just did not. I will inquire with the group.

> also, I thought that [this](https://github.com/NCATSTranslator/ReasonerAPI/blob/1.3/docs/reference.md#qedge-) page should be the best place to look for TRAPI 1.3 class descriptions, but that doesn't appear updated for TRAPI 1.3, even though it's in the `1.3` branch. is that intended?

No, that is an oversight. Our documentation generation guru was Patrick and he left. I will attempt to update it. thanks for pointing this out.

**Comment by edeutsch** [comment]
> > also, I thought that [this](https://github.com/NCATSTranslator/ReasonerAPI/blob/1.3/docs/reference.md#qedge-) page should be the best place to look for TRAPI 1.3 class descriptions, but that doesn't appear updated for TRAPI 1.3, even though it's in the `1.3` branch. is that intended?
> 
> No, that is an oversight. Our documentation generation guru was Patrick and he left. I will attempt to update it. thanks for pointing this out.

fixed! (mostly)

**Comment by amykglen** [comment]
great! I'm making progress on updating Plover/the KG2 Expand code to populate the new `query_id` property as appropriate. it's seeming like I should finish tonight or tomorrow, and I think that's the main piece remaining on my end for the KG2 API implementation (more for me to do for the ARAX side, but we have a couple more weeks for that, of course)

**Comment by edeutsch** [comment]
awesome, thanks!

**Comment by amykglen** [comment]
@edeutsch - one question I have about `NodeBinding.query_id` is what to do when a node in a result fulfills multiple curies given in the QG. for instance, consider this theoretical query (I'm listing names in `n00` instead of curies for readability):
```
(n00: "diabetes", "autoimmune disease")<--treats--(n01: "biolink:Drug")
```
and suppose one of the results look like this:
```
("type 1 diabetes")<--treats--("insulin")
```
in this case, "type 1 diabetes" is a subclass of both "diabetes" and "autoimmune disease". but the `NodeBinding.query_id` property expects only a single curie. are we supposed to create two otherwise identical results that have different `query_id` values? for now I'm just ignoring all but one curie in such cases.

maybe not super pressing since this kind of query is likely rare(?), but worth thinking about...

**Comment by edeutsch** [comment]
yes, a good point that we hadn't thought of.
I suggest that if there are multiple, then just pick one.
Maybe with a nice flag in the code that makes it easy to find if we ever decide on a different approach.
but for now, since this is so rare, I suggest we just stay low and keep it simple.
Sound sensible?

**Comment by amykglen** [comment]
sounds fine to me! that approach could cause issues for ARAs for multi-hop queries, but again, such queries are probably rare.

I also have some major questions about how ARAX should handle `query_ids` when resultifying (specifically when it comes to multi-hop queries) - but I'm saving those for a mini-hackathon since they're rather complex and ARAs' TRAPI 1.3 implementations aren't due until the 28th. (I'm out tomorrow but maybe the July 20 mini-hackathon?)

**Comment by amykglen** [comment]
fyi - I'm close with the KG2 implementation but have a couple lingering bugs (I think in the Plover portion). probably won't finish today but will have it done by Thursday

**Comment by amykglen** [comment]
(note that if you run the code in `NewFmt` probably many tests will fail for you, unless you do `force_local = True` in `ARAX_expander.py` and point your config file to `kg2cplover.rtx.ai`, since changes have been made to the KG2 API in that branch)

**Comment by edeutsch** [comment]
Awesome, thanks so much @amykglen. I think I will try to set up a set of deployments now on with the latest code so that we can test more quickly

**Comment by edeutsch** [comment]
I now have the following sites up:
https://arax.ncats.io/NewFmt
https://arax.ncats.io/kg2NewFmt

and the following endpoints are active:
https://arax.ncats.io/api/arax/v1.3/ui/
https://arax.ncats.io/api/rtxkg2/v1.3/ui/

It's not all quite working correctly, probably because I did not do what @amykglen suggested above, but maybe on Thu or Fri we can polish this up and get it up running properly.

**Comment by edeutsch** [comment]
> (I'm out tomorrow but maybe the July 20 mini-hackathon?)

sure

**Comment by amykglen** [comment]
actually that URL (https://arax.ncats.io/kg2NewFmt) doesn't seem to work after all for API queries... I'll wait for @edeutsch's direction on that

**Comment by edeutsch** [comment]
hi, just catching up now.
yes, I know what causes that. will fix.

**Comment by edeutsch** [comment]
Hi @amykglen , I have just push a fix for this (forgot to tag issue) and rolled it out to the 1.3 endpoints.

I don't quite follow all your questions above, but with URLs, the situation is:
Point your web browser to these URLs:
https://arax.ncats.io/NewFmt
https://arax.ncats.io/kg2NewFmt

But you should point your code to these endpoint patterns:
https://arax.ncats.io/api/arax/v1.3/
https://arax.ncats.io/api/rtxkg2/v1.3/

These are "production-appearing" endpoints, which maybe isn't the way we want to leave this, but this is how I set it up for now. Feel free to suggest what endpoint URLs seem best.

**Comment by amykglen** [comment]
ahh, I see now about the URLs, thanks. so is the arax.ncats.io directory `/data/orangeboard/NewFmt` the one that corresponds to this TRAPI 1.3 endpoint?

**Comment by edeutsch** [comment]
> ahh, I see now about the URLs, thanks. so is the arax.ncats.io directory `/data/orangeboard/NewFmt` the one that corresponds to this TRAPI 1.3 endpoint?

yes, I didn't specify that, the corresponding directories are:
cd /mnt/data/orangeboard/NewFmt
cd /mnt/data/orangeboard/kg2NewFmt
(like the browser URLs) (the /api is funneled through a complex Apache proxying to the application)

**Comment by edeutsch** [comment]
just to beat the dead horse a little more, endpoints
https://arax.ncats.io/api/arax/v1.3/
https://arax.ncats.io/api/rtxkg2/v1.3/
are routed by Apache to the NewFmt areas somewhat transparently

while endpoints
https://arax.ncats.io/api/arax/v1.2/
https://arax.ncats.io/api/rtxkg2/v1.2/
are routed by Apache to the normal production areas.

**Comment by amykglen** [comment]
got it now, great, thanks. ok, so that means I did edit `/NewFmt`'s `config_local.json` file correctly to point to the KG2 at `https://arax.ncats.io/api/rtxkg2/v1.3/`. what's strange is that I'm not sure if it's actually using that URL for KG2, based on some fiddling around I did... I just pushed some logging that will make that more clear..

**Comment by amykglen** [comment]
but in any case, that doesn't affect the KG2 endpoint itself, so I believe the KG2 TRAPI 1.3 implementation is complete from my end.

**Comment by edeutsch** [comment]
@amykglen outstanding, thanks so much!

So, from your standpoint, I can now register the RTX-KG2 TRAPI 1.3 endpoint in SmartAPI and thus fulfill the nominal deadline for today?

**Comment by amykglen** [comment]
yep!

**Comment by edeutsch** [comment]
super, it is done!
https://smart-api.info/registry?q=rtx
(notice two RTX-KG2 records, one of which is TRAPI 1.3.0)

And see the result in the blisteringly awesome SmartAPI system with big thanks to Carter and Luis:
https://arax.ncats.io/NewFmt/?smartapi=1
notice:
![image](https://user-images.githubusercontent.com/12707718/179067763-d395880c-9b5b-4b98-ad9e-e0431a81d292.png)

thanks everyone!

**Comment by edeutsch** [comment]
The deadline for ARAX (and all other ARAs) implementing TRAPI 1.3 is Thursday, the 28th. What are the next steps and plans to meet this?
As far as I'm aware the latest NewFmt code is deployed already and testable, but has not been registered in SmartAPI. I am unaware of what open issue remain to be resolved.

**Comment by amykglen** [comment]
the only real remaining piece I'm aware of is implementing the `query_ids` handling that we brainstormed at last week's mini-hackathon in Expand/Resultify. I'm planning to do that today and tomorrow

**Comment by amykglen** [comment]
ok, I believe I've finished implementing all of the `node_binding.query_id` stuff - all changes are in `NewFmt`. still want to do a little more thorough testing (haven't been able to get my local UI to work yet).

I just ran all the 'fast' pytests in `NewFmt`, and there are a few tests currently failing (I haven't investigated yet):
```
test_ARAX_connect.py::test_connect_nodes_subgraph_2_hop
test_ARAX_messenger.py::test_create_message_basic
test_ARAX_query.py::test_query_by_query_graph_2
```

other than the above failing tests, these are the remaining TRAPI 1.3-related items I know of:

1. when a query has qualifiers, we currently issue a warning saying that we don't support them, and then answer the query ignoring them. is this proper? I believe @edeutsch was going to ask the group if this is ok
2. our KG2 meta KG does *not* include implied ancestor relationships. is this proper? I believe @edeutsch was going to remove the statement from TRAPI 1.3 that meta KGs _should_ include implied ancestor relationships...?
3. we do not currently provide an ARAX meta KG that is a union of all of its KPs' meta KGs, though I believe doing so is not required. so we could address this a bit later? when we do so we will also need to add `knowledge_type: 'inferred'` info to relevant meta edges.

**Comment by edeutsch** [comment]
Regarding, item 1, here is the issue: https://github.com/NCATSTranslator/TranslatorArchitecture/issues/76

**Comment by edeutsch** [comment]
Regarding item 2: https://github.com/NCATSTranslator/ReasonerAPI/pull/354/files
answer is NO

**Comment by edeutsch** [comment]
Reagarding item 3, it is recommended but not required, right. https://github.com/NCATSTranslator/ReasonerAPI/pull/354/files

**Comment by amykglen** [comment]
@edeutsch - ok, ready for another rollout to `NewFmt` when you have a chance. 

all 'fast' pytests are passing now.

**Comment by edeutsch** [comment]
Branch NewFmt has just been rolled out to both KG2 and ARAX v1.3 endpoints

**Comment by amykglen** [comment]
@edeutsch - ready for another roll out of `NewFmt`. (pretty major result merging bug fix)

**Comment by amykglen** [comment]
great, thanks! things are look good as far as I can tell..

**Comment by edeutsch** [comment]
@isbluis are there any outstanding tasks that prevent us from checkmarking this:
![image](https://user-images.githubusercontent.com/12707718/182697736-97c0c9bd-eea6-4d7e-979b-17d3df1b5f3c.png)

Or can we check and close out this issue?

**Comment by edeutsch** [comment]
completed a while back. closing..
