### ISSUE TITLE
DTD not returning results when used as a KP

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1875]
I don't know when this happened, but it appears that DTD (not the new, explainable version) is no longer returning results. Here are a few attempts to get it to return something, all returning 0 results:
https://arax.ncats.io/?r=53244
https://arax.ncats.io/?r=53237
https://arax.ncats.io/?r=53236

Maybe the results are getting dumped somewhere?

**Comment by edeutsch** [comment]
One clue is:
![image](https://user-images.githubusercontent.com/12707718/180287594-2bedab0f-bf7c-4543-b427-aa31193fc361.png)

**Comment by dkoslicki** [comment]
Right: with different curies and categories, I can't manage to get DTD to return stuff. It always says 0 results, when previously it would actually return things

**Comment by chunyuma** [comment]
I have a few questions regarding this problem:

1. For this KP in production, what version of KG is used?

2. I saw the issue #1838 that we have refreshed the DTD for the new rollout. However, I don't remember I did this for this version of KG. I'm wondering whether we now have a new method to update all databases as a whole.

**Comment by amykglen** [comment]
I believe the group decided not to refresh DTD for 2.7.6, since 2.7.6 has minor changes. but regardless, we haven't completed the KG2.7.6 rollout anyway, so that shouldn't be the issue. (i.e., production and all endpoints are still using KG2.7.5)

**Comment by chunyuma** [comment]
This issue has been fixed. [Here](https://arax.ncats.io/?r=210) is the test result for https://arax.ncats.io/?r=53244.
