### ISSUE TITLE
Test triples for SRI

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX#1876]
Per meeting with Tim Putnam and Amy, I need to update the test triples file and it will be hosted in this repository. In the future, the test file will be generated for each build of KG2C. Tim asked for the URL to the generated file to be added to our SmartAPI as "test_data_location". 

- [x] Run the existing script on KG2.7.5C, name output `RTX_KG2c_test_triples.json`, and place in RTX/code/ARAX/KnowledgeSources
- [x] Ask Eric to update SmartAPI

Future tasks:
- [ ] Create copy and clean up [create_csv_of_kp_predicate_triples.py](https://github.com/RTXteam/RTX/blob/master/code/ARAX/KnowledgeSources/create_csv_of_kp_predicate_triples.py)
- [ ] Rename script to `create_json_of_kp_predicate_triples.py` and move to this repo. 
- [ ]  Edit the script to load `kg2c_lite.json` instead of neo4j so it can be included in the build process in the future.

**Comment by amykglen** [comment]
awesome, thanks @acevedol! and also - don't worry about doing the first two steps you listed in the short-term - I know you're busy with the new Biolink version and KG2.7.7. those steps could be part of the longer-term project to clean up the script and make it part of the KG2c build process.

**Comment by amykglen** [comment]
documenting this for when we're ready to update the RTX-KG2 SmartAPI registration:

we'll need to put the raw GitHub link to the test triples JSON file (stored in the RTX repo) under `info` --> `x-trapi` --> `test_data_location` in the KG2 SmartAPI registration.

example:
![Screen Shot 2022-07-21 at 1 55 30 PM](https://user-images.githubusercontent.com/49423686/180313921-632c0108-996a-4232-8706-bbfccdcca4fa.png)

**Comment by acevedol** [comment]
I just pushed `RTX_KG2c_test_triples.json` to `RTX/code/ARAX/KnowledgeSources`.

The "test_data_location" is `https://raw.githubusercontent.com/RTXteam/RTX/master/code/ARAX/KnowledgeSources/RTX_KG2c_test_triples.json`

**Comment by amykglen** [comment]
@edeutsch (or anyone opinionated on the matter) - until they develop a fancier system (that uses SmartAPI to pull this info), the SRI team wants us to provide them with a production URL for the RTX-KG2 API that they can use for their testing suite. 

I'm thinking maybe we should give them the **ITRB production** endpoint? vs. our own production endpoint? wondering if that seems reasonable.

**Comment by amykglen** [comment]
awesome, thanks @acevedol!

**Comment by edeutsch** [comment]
> @edeutsch (or anyone opinionated on the matter) - until they develop a fancier system (that uses SmartAPI to pull this info), the SRI team wants us to provide them with a production URL for the RTX-KG2 API that they can use for their testing suite.
> 
> I'm thinking maybe we should give them the **ITRB production** endpoint? vs. our own production endpoint? wondering if that seems reasonable.

Sorry, this slipped under the flood. I agree, let's point them to ITRB instances.

And let's chat a bit more about this at the next AHM, I see it's on the agenda, great.

**Comment by amykglen** [comment]
production `test_data_location`: `https://raw.githubusercontent.com/RTXteam/RTX/production/code/ARAX/KnowledgeSources/RTX_KG2c_test_triples.json`

**Comment by amykglen** [comment]
so I was wrong about ARAX's registration not having a `test_data_location` - it actually does need one, though pointing to a different, much smaller file (which we need to create based on [this](https://github.com/TranslatorSRI/SRI_testing/blob/main/tests/onehop/templates/ARA/Expander_Agent/ARAX_Translator_Reasoner.json) template, but stored in our own repo, and using KP infores curies).

I'll plan to add this file in the next couple days. will let Eric know after that when we're ready to update the ARAX SmartAPI registration.

**Comment by amykglen** [comment]
@edeutsch - ok, I added a hard-coded list of KPs (for now, until we have dynamic KP selection) - the `test_data_location` we need to add to our ARAX SmartAPI registration is: 
```
https://raw.githubusercontent.com/RTXteam/RTX/master/code/ARAX/Documentation/arax_kps.json
```

**Comment by edeutsch** [comment]
I have added this to the ARAX endpoint. and refreshed smartapi. confirmed that both KG2 and ARAX now have test_data_location data in their SmartAPI records.

**Comment by amykglen** [comment]
awesome! I'm going to close out this issue then and I'll create a separate one to document how we'd like to eventually incorporate the test triples file generation into the KG2c build process
