### ISSUE TITLE
notes from discussion with Jared about clinician use of RTX

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#188]
Jared says that in terms of RTX being used by clinicians (and researchers as well), it would be beneficial to have RTX capable of operating in two modes, one which is "just answer the question" (no question refinement allowed) and the other mode in which RTX would ask the user questions to refine the user-query.  For example, if the user types

    What diseases are similar to schizophrenia?

RTX could respond with:

    I know of a few ways to define similarity for diseases, did you mean any of these? 
        overlap of phenotypes
        overlap of genetic factors
        overlap of underlying molecular pathways
        overlap of therapeutic interventions

@dkoslicki  what do you think?
@jaredroach thank you very much for the feedback; please let me know if I did not capture the gist of our conversation correctly.

**Comment by edeutsch** [comment]
So this would be a function of the reasoner? not the translator? The translator would understand the question and forward it to the reasoner. But then the reasoner would think it too vague and what to ask for clarification? Or maybe the translator would already know it is too vague?

In any case, I can imagine adding a new list item to the Query or the Response class schemas like "clarified_questions": [ ]. Such that the message attribute could have a sentence like "Your question is a bit too broad to answer in a meaningful way. Would you write your question a bit more specifically, perhaps like one of these:" and then the "clarified_questions" list could encode a list of more specific questions (as furnished by David's code). The GUI could make them easy to click on to paste into the box and ASK.

Or we could consider going a bit further with human-in-the-loop-ish  interaction.

What do you think?

**Comment by dkoslicki** [comment]
Closing due to #788 and DSL proving HIL interaction, as well as the templates queries in [ARAX_query_graph_interpreter.py](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter.py)
