### ISSUE TITLE
`connect` not showing up in the UI

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1880]
We have a new-ish ARAXi command [connect](https://github.com/RTXteam/RTX/blob/master/code/ARAX/Documentation/DSL_Documentation.md#connectactionconnect_nodes) that is implemented and in the DSL documentation, but it appears to not be in the DSL query builder in the UI.

**Comment by isbluis** [comment]
Thanks for the heads-up @dkoslicki .  I just updated my dev area with the new definitions.
When you have a minute, could you please verify that the commands and parameters look good?  I'll then commit to master.

https://arax.ncats.io/devLM/index.html   <shift> + <reload> to get newest JS files

**Comment by dkoslicki** [comment]
Awesome! Looks good to me!

**Comment by isbluis** [comment]
In master now, pending deployment.

**Comment by edeutsch** [comment]
So this has been deployed a while back. I see it there in production now.
Okay to close this?
Or would it be sensible to alpha sort the list of DSL commands?
