### ISSUE TITLE
glucose synonymization issue

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1882]
Take a gander at:
https://arax.ncats.io/?term=glucose 
And notice the many mis-synonymizations. Genes, peptides, drugs, proteins, etc. all mixed in

**Comment by edeutsch** [comment]
yeah, tracing these highly connected things is always difficult. I've mused about trying to record the information to construct a graph to see how these things got all glomed together. I definitely have work to do on the NodeSynonymizer. Having trouble allocating time for it.

**Comment by amykglen** [comment]
it looks like this one was actually already cleaned up with our current production synonymizer, so I'm not sure what curies were being conflated:

<img width="568" alt="Screen Shot 2023-05-03 at 4 17 12 PM" src="https://user-images.githubusercontent.com/49423686/236071822-ceb4a3a8-3931-448a-9628-55855ef03e9c.png">

but it also looks pretty good in the new synonymizer (#2003):

Cluster for RXNORM:4850 (PUBCHEM.COMPOUND:10954115) has 27 nodes:

| id                                   | category       | name                                        | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:-------------------------------------|:---------------|:--------------------------------------------|:---------|:------------|:-----------------|
| ATC:B05CX01                          | ChemicalEntity | glucose                                     |          | X           |                  |
| ATC:V04CA02                          | ChemicalEntity | glucose                                     |          | X           |                  |
| ATC:V06DC01                          | ChemicalEntity | glucose                                     |          | X           |                  |
| CAS:41846-87-1                       | SmallMolecule  |                                             | X        |             |                  |
| CAS:921-60-8                         | SmallMolecule  |                                             | X        |             |                  |
| CHEBI:17234                          | SmallMolecule  | glucose                                     | X        | X           |                  |
| CHEBI:37626                          | SmallMolecule  | aldehydo-L-glucose                          | X        | X           |                  |
| DRUGBANK:DB09341                     | ChemicalEntity | Dextrose, unspecified form                  | X        | X           |                  |
| DRUGBANK:DB12970                     | SmallMolecule  | Levoglucose                                 | X        | X           |                  |
| GTOPDB:4719                          | SmallMolecule  | L-glucose                                   | X        |             |                  |
| INCHIKEY:GZCGUPFRVQAUEE-VANKVMQKSA-N | SmallMolecule  |                                             | X        |             |                  |
| LOINC:LP14635-4                      | ChemicalEntity | Glucose                                     |          | X           |                  |
| LOINC:LP32534-7                      | ChemicalEntity | Glucose                                     |          | X           |                  |
| LOINC:MTHU001675                     | ChemicalEntity | Glucose                                     |          | X           |                  |
| MESH:D005947                         | SmallMolecule  | Glucose                                     | X        | X           |                  |
| NCIT:C175113                         | Drug           | Levoglucose                                 |          | X           |                  |
| NCIT:C2831                           | Drug           | Glucose                                     |          | X           |                  |
| NDDF:002597                          | ChemicalEntity | glucose                                     |          | X           |                  |
| PSY:21160                            | ChemicalEntity | Glucose                                     |          | X           |                  |
| PUBCHEM.COMPOUND:10954115            | SmallMolecule  | (2S,3R,4S,5S)-2,3,4,5,6-pentahydroxyhexanal | X        |             | X                |
| RXNORM:1788981                       | Drug           | levoglucose                                 |          | X           |                  |
| RXNORM:4850                          | Drug           | glucose                                     |          | X           |                  |
| UMLS:C0017725                        | SmallMolecule  | glucose                                     | X        | X           |                  |
| UMLS:C1165603                        | ChemicalEntity | Dextrose solution                           | X        | X           |                  |
| UNII:02833ISA66                      | SmallMolecule  | LEVOGLUCOSE                                 | X        |             |                  |
| UNII:IY9XDZ35W2                      | SmallMolecule  | DEXTROSE, UNSPECIFIED FORM                  | X        |             |                  |
| VANDF:4019541                        | ChemicalEntity | Glucose                                     |          | X           |                  |

**Comment by amykglen** [comment]
looks good on test instances: https://arax.ncats.io/devLM/?term=glucose
