### ISSUE TITLE
Add icees-pcd kp

### ISSUE THREAD

**Issue by karafecho** [RTXteam/RTX#1887]
This issue is to politely request that Expander Agent adds icees-pcd as a new KP. Dev and prod versions of the service are registered in SmartAPI [here](https://smart-api.info/registry?q=icees%20pcd).

**Comment by rcpeene** [comment]
With the changes addressed in [issue 1466](https://github.com/RTXteam/RTX/issues/1466), icees-pcd will be accounted for in ARAX's automatic usage of SmartAPI kps once that branch is pushed to production!

**Comment by karafecho** [comment]
Fantastic! Thank you.
