### ISSUE TITLE
Update predicates in the UI?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1888]
From Jenn Hadlock:
Would it be possible to add new predicates from 2.4.8?

Basazin Belhu (Bassa)
For instance, my team updated the predicate to "associated_with_increased_likelihood" and associated_with_decreased_likelihood".  I could not find these predicates in the ARAX UI. Here is the screenshot I was looking on
Screen Shot 2022-08-08 at 2.47.25 PM.png 
Screen Shot 2022-08-08 at 2.47.25 PM.png

**Comment by isbluis** [comment]
Hi @edeutsch .  The UI populates this list via the `/meta_knowledge_graph?format=simple` API call.  Once that is updated, the UI should automatically display that with no further code changes.  Only potential snag is to make sure that `config.js` has the correct API settings.

**Comment by edeutsch** [comment]
okay, great, thanks, I think what we need to do is make ARAX's /meta_knowledge_graph be the union of all its KPs, which I think is planned, but not done, and that might solve this issue. @amykglen probably knows more.

Alternatively, we would need to figure out how to get all Biolink predicates and display those.

**Comment by edeutsch** [comment]
Seems like this has not been an issue for years, closing.
