### ISSUE TITLE
hard tabs in QueryPubChem.py

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#189]

**Comment by DeqingQu** [comment]
The hard tabs issue is fixed now. I also added some test cases [(tests/QueryPubChemTests.py)](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/kg-construction/tests/QueryPubChemTests.py) for all public methods of QueryPubChem.

**Comment by DeqingQu** [comment]
The hard tabs issue of NormGoogleDistance is fixed. Test cases for this module are missing.
