### ISSUE TITLE
Plover down?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1890]
I received an alert that ARAX and KG2 are malfunctioning. I think PloverDB may be down? Is @amykglen available to investigate?

**Comment by amykglen** [comment]
sorry, just seeing this. I see you alerted Kanna and he's fixing it. do you want us to temporarily switch to a self-hosted plover? (might be good while Kanna is working on making Plover auto-deploy from `production`/`itrb-test` branches..)

**Comment by amykglen** [comment]
I switched `kg2` and `kg2beta` to a self-hosted Plover while this gets sorted out

**Comment by amykglen** [comment]
and `kg2NewFmt`. all three endpoints seem to be working now.

**Comment by edeutsch** [comment]
tagged with "ITRB" to track our running count of mid-air collisions and closing..
