### ISSUE TITLE
Pytests failing locally; not on arax.ncats.io (I think)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1900]
strangely, since merging `NewFmt` into `master` this afternoon, a bunch of pytests now seem to fail for me locally in `master`, complaining with this error from `ARAX_query.py`:

```
pytest -vsk test_curie_list_query
```
```
 .....
            # Fill out the message with data
            response.envelope.status = response.error_code
            response.envelope.description = response.message
            if response.envelope.operations is None:
                response.envelope.operations = operations
    
            #### Provide the total results count in the Response if it is available
            try:
                response.envelope.total_results_count = response.total_results_count
            except:
                pass
    
            #response.envelope.operations['actions'] = operations.actions
    
            # Update the reasoner_id to ARAX if not already present
            for result in response.envelope.message.results:
                if result.reasoner_id is None:
                    result.reasoner_id = 'ARAX'
    
            # Store the validation and provenance metadata
            trapi_version = '1.2.0'
            try:
                validate(response.envelope,'Response',trapi_version)
                if 'description' not in response.envelope or response.envelope['description'] is None:
                    response.envelope['description'] = 'reasoner-validator: PASS'
                response.envelope['validation_result'] = { 'status': 'PASS', 'version': trapi_version, 'message': '' }
    
            except ValidationError as error:
                timestamp = str(datetime.now().isoformat())
>               if 'logs' not in response.envelope or response.envelope['logs'] is None:
E               TypeError: argument of type 'Response' is not iterable

../ARAXQuery/ARAX_query.py:864: TypeError
```
I tried out this same query on arax.ncats.io/test, and it seems to complete without errors there (https://arax.ncats.io/test/?r=56728), so I'm assuming the other failing queries are probably ok on arax.ncats.io as well. not sure what might be going on? (@edeutsch) 
I don't have any local changes, so that couldn't be the cause.

**Comment by edeutsch** [comment]
oh, oops, thanks, this is my issue. I was rushing to resolve a conflict before my next meeting and botched it. will fix.

**Comment by edeutsch** [comment]
Did that push fix your problem?

**Comment by edeutsch** [comment]
So I think I fixed it, and devLM is now up and running fine as far as I can tell, but I did get another Run Failed message, so there may still be a problem on ITRB

**Comment by amykglen** [comment]
hm, ok, I'll check on ITRB

**Comment by amykglen** [comment]
it seems to be working for me locally

**Comment by amykglen** [comment]
huh, yeah ITRB CI ARAX and KG2 seem unhappy, even though Jenkins says they successfully built at about 5:30pm

![Screen Shot 2022-08-17 at 5 35 48 PM](https://user-images.githubusercontent.com/49423686/185267117-de673fd4-c495-4bc4-9e66-ce78b5f37048.png)

**Comment by amykglen** [comment]
strangely, I'm seeing a different error on kg2.ci.transltr.io:

![Screen Shot 2022-08-17 at 5 37 37 PM](https://user-images.githubusercontent.com/49423686/185267267-967a91f9-c102-406f-9d45-7a3e7f83037c.png)

**Comment by amykglen** [comment]
do we see these errors when rolling out the current `master` to our arax.ncats.io endpoints? I'm guessing we would?

**Comment by edeutsch** [comment]
So I just did a rollout of `master` to /test, expecting there to be nothing new, but instead there was lots new:
```
 .github/workflows/pytest.yml                                            |  5 +++--
 code/ARAX/ARAXQuery/ARAX_database_manager.py                            | 25 +++++++++++++++++++++++--
 code/ARAX/ARAXQuery/ARAX_infer.py                                       | 16 ++++++++++++----
 code/ARAX/ARAXQuery/ARAX_query.py                                       | 25 ++++++++++++++++++++++---
 code/ARAX/ARAXQuery/Overlay/GraphSage_train/py_scripts/BuildMapID.py    | 18 +++++++++++++++---
 code/ARAX/test/test_ARAX_expand.py                                      |  1 +
 code/RTXConfiguration.py                                                |  3 ---
 code/UI/OpenAPI/python-flask-server/openapi_server/openapi/openapi.yaml | 10 +++++-----
 code/UI/interactive/cytoscape.min.js                                    | 11 +----------
 code/UI/interactive/rtx.js                                              |  7 +++++--
 code/UI/interactive/rtx.version                                         |  2 +-
```

But now when I go to test:
https://arax.ncats.io/test/

I see:
![image](https://user-images.githubusercontent.com/12707718/185283549-e54d11aa-fdad-4867-8593-4f665fb78fc8.png)
which is new.

and I also don't get the usual tabs:
![image](https://user-images.githubusercontent.com/12707718/185283608-76043c58-3570-45a1-be97-0f4a6724ad38.png)

So I think Luis and I need to do some troubleshooting tonight.
Some is definitely wrong with `master`. Will fix.

**Comment by edeutsch** [comment]
okay, a change has been pushed to master fixing my observed problem above.
But it's not obvious that that would fix itrb

**Comment by amykglen** [comment]
nice! huh, so https://kg2.ci.transltr.io/ **is** now working normally, apparently. 

but https://arax.ci.transltr.io/ is still unhappy. complaining about `ERROR: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.` (without starting query processing).

**Comment by amykglen** [comment]
aha! so after arax.ci.transltr.io finished rebuilding from the latest commit in master (at about 8:40pm pacific), now it seems to work!

although strangely it's request to get KG2's meta knowledge graph failed, so it doesn't have results from KG2. not sure why that was. guessing it was bad timing, when KG2 was very briefly down (for a few seconds I think) during the auto-deployment?

**Comment by amykglen** [comment]
and now even it's query of KG2 seems to work! magically. so I think we're all good again!

**Comment by edeutsch** [comment]
hmm, I'm not getting ci to work..
https://arax.ci.transltr.io/api/arax/v1.3/ui/

**Comment by amykglen** [comment]
really? the UI just worked for me https://arax.ci.transltr.io

**Comment by edeutsch** [comment]
yes, but does this work? https://arax.ci.transltr.io/api/arax/v1.3/ui/

**Comment by edeutsch** [comment]
It's a bit of a mystery why the UI works if that API url doesn't work...

**Comment by amykglen** [comment]
yeah, that's strange...

**Comment by amykglen** [comment]
does that page ever work for the ITRB instances? it also seems not to work for the Prod ITRB ARAX v1.2:

https://arax.transltr.io/api/arax/v1.2/ui/

**Comment by edeutsch** [comment]
oh, maybe the Dockerfile doesn't install the UI widget. if everything else works, then we're good.

**Comment by edeutsch** [comment]
I think sometimes doing a pip3 install -r requirements.txt skips this one:
```
connexion[swagger-ui]
```
for some unknown reason

**Comment by amykglen** [comment]
oh strange. I just confirmed that directly curl querying the ITRB ARAX CI API works. so I think we're ok?
```
curl -X 'POST' \
  'https://arax.ci.transltr.io/api/arax/v1.3/query' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "object": "n01",
          "predicates": [
            "biolink:physically_interacts_with"
          ],
          "subject": "n00"
        }
      },
      "nodes": {
        "n00": {
          "ids": [
            "CHEMBL.COMPOUND:CHEMBL112"
          ]
        },
        "n01": {
          "categories": [
            "biolink:Protein"
          ]
        }
      }
    }
  }
}'
```

**Comment by edeutsch** [comment]
yes, I agree, we're good! thank you!

**Comment by amykglen** [comment]
awesome! I'll close this issue out then
