### ISSUE TITLE
uncaught error in queries with overlay_fisher_exact_test operation

### ISSUE THREAD

**Issue by CaseyTa** [RTXteam/RTX#1908]
In queries with an `overlay_fisher_exact_test` operation, ARAX shows an uncaught error in the logs, and ARAX stops processing any operations following the `overlay_fisher_exact_test` operation. 

Here's a simple query example where I'm seeing the error:
```
{
  "workflow": [
    {
      "id": "fill"
    },
    {
      "id": "bind"
    },
    {
      "id": "overlay_fisher_exact_test",
      "parameters": {
        "subject_qnode_key": "n0",
        "object_qnode_key": "n1",
        "virtual_relation_label": "F1"
      }
    }
  ],
  "message": {
    "query_graph": {
      "edges": {
        "e01": {
          "subject": "n0",
          "object": "n1",
          "predicates": [
            "biolink:has_real_world_evidence_of_association_with"
          ]
        }
      },
      "nodes": {
        "n0": {
          "ids": [
            "MONDO:0009061"
          ],
          "is_set": false,
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ],
          "name": "MONDO:0009061"
        },
        "n1": {
          "is_set": false,
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ]
        }
      }
    }
  }
}
```

Error in TRAPI log: 
```ERROR: [UncaughtARAXiError]    An uncaught error occurred: max() arg is an empty sequence: ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_query.py", line 747, in execute_processing_plan\n overlay.apply(response, action[\'parameters\'])\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 534, in apply\n \'action\'])() # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 957, in __fisher_exact_test\n response = FTEST.fisher_exact_test()\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/fisher_exact_test.py", line 283, in fisher_exact_test\n max_index = max([(value, index) for index, value in enumerate(occurrences.values())])[1] # if there are more than one kp having the maximum number of edges, then the last one based on alphabetical order will be chosen.\n', 'ValueError: max() arg is an empty sequence\n']```

**Comment by amykglen** [comment]
thanks for the bug report.

@chunyuma - could you help debug what's going on in FET? it seems to be that the `edge_expand_kp` variable is empty, which then causes this error. but I'm not sure why it's empty.

Gregory Hyde also reported the same error with this query today:
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": [
                        "biolink:Disease"
                    ],
                    "ids": [
                        "MONDO:0009061"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:GrossAnatomicalStructure"
                    ]
                },
                "n2": {
                    "categories": [
                        "biolink:Gene"
                    ]
                },
                "n3": {
                    "categories": [
                        "biolink:Drug",
                        "biolink:SmallMolecule"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": [
                        "biolink:located_in"
                    ]
                },
                "e1": {
                    "subject": "n1",
                    "object": "n2",
                    "predicates": [
                        "biolink:expresses"
                    ],
                    "attribute_constraints": [
                        {
                            "id": "biolink:knowledge_source",
                            "name": "knowledge source",
                            "value": [
                                "infores:connections-hypothesis"
                            ],
                            "operator": "==",
                            "not": false
                        }
                    ]
                },
                "e2": {
                    "subject": "n3",
                    "object": "n2",
                    "predicates": [
                        "biolink:affects"
                    ]
                }
            }
        }
    }
}
```

**Comment by CaseyTa** [comment]
Thanks in advance, @amykglen and @chunyuma!

**Comment by dkoslicki** [comment]
@chunyuma it appears that [here](https://github.com/RTXteam/RTX/blob/c0904451fc860ef3f83702c5c70d1a26121824f8/code/ARAX/ARAXQuery/Overlay/fisher_exact_test.py#L190-L193), when looking at knowledge graph such as this one: https://arax.ncats.io/?r=63305, the edges are only coming from COHD, as such, we have two attributes:
<html>
<body>


attribute_source: | infores:cohd
-- | --
attribute_type_id: | biolink:original_knowledge_source
description: | The COHD KP defines associations between biomedical concepts based on statistical analysis of clinical/EHR data.
value_type_id: | biolink:InformationResource
value_url: | http://cohd.io/api/query
value: | infores:cohd


</body>
</html>

and 
<html>
<body>


attribute_source: | infores:arax
-- | --
attribute_type_id: | biolink:aggregator_knowledge_source
value_type_id: | biolink:InformationResource
value: | infores:arax


</body>
</html>
Since [this line](https://github.com/RTXteam/RTX/blob/c0904451fc860ef3f83702c5c70d1a26121824f8/code/ARAX/ARAXQuery/Overlay/fisher_exact_test.py#L193) removes any ARAX edges, that results in `edge_expand_kp` being empty. However, I don't know if the better thing would be to add `biolink:original_knowledge_source` [here](https://github.com/RTXteam/RTX/blob/c0904451fc860ef3f83702c5c70d1a26121824f8/code/ARAX/ARAXQuery/Overlay/fisher_exact_test.py#L190) or handle empty lists later in the code. Do you mind taking a look?

**Comment by chunyuma** [comment]
Thanks @dkoslicki and @chunyuma. I will look into it later today.

**Comment by amykglen** [comment]
not sure if it's helpful @chunyuma, but if you need a way of distinguishing which infores curies are for KPs vs. other knowledge sources/ARAs, you can get the set of KP infores curies like so:
```
from kp_selector import KPSelector
kp_selector = KPSelector()
kp_infores_curies = kp_selector.valid_kps
```
(I'd just make sure to instantiate KPSelector() only once per FET run because it can take a few seconds)

**Comment by chunyuma** [comment]
I've fixed this bug and pushed it to the master branch. The new push passes all FET-associated tests.

**Comment by dkoslicki** [comment]
Great, thank you for the quick work!
@CaseyTa , there has been a fair bit of development work aside from this on the `master` branch, so I don't know how long it will take for us to get this to production.
@chunyuma do you want to try your hand at [git cherry-pick](https://stackoverflow.com/questions/881092/how-to-merge-a-specific-commit-in-git) to merge this single commit b7fa1b9 into the ITRB `test` branch? i.e. just merge your commit into ITRB test, but none of the commits between 62cf12d8e3de95e062a11fe74ab8cac55dcd8975 and 4bad24cbdab7ffb19f141af293850eb790d7dc03?

**Comment by amykglen** [comment]
@dkoslicki - I think @edeutsch and I are planning to roll master out to itrb-test and production this evening, so I think this fix will get rolled out then

**Comment by CaseyTa** [comment]
Thanks, all, for the quick work on this! I don't think we're in need of special effort to deploy the new changes to test/prod. I was able to use @dkoslicki's workaround to test the desired workflows already. Thanks again, everyone!

**Comment by dkoslicki** [comment]
I see everything has been rolled out to https://arax.test.transltr.io/ and https://arax.transltr.io/ and can confirm it is working on those endpoints: https://arax.transltr.io/?r=63648
