### ISSUE TITLE
no results for ARAX from today's stand-up meeting query

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1909]
Today's stand-up meeting involved a "creative mode" query graph pertaining to autism (`MONDO:0005260`),

https://github.com/NCATSTranslator/testing/issues/232

that returned no results for ARAX. Mark W. speculated that maybe it is because there wasn't an XDTD entry for `MONDO:0005260`.

**Comment by saramsey** [comment]
When this JSON query graph is posted directly to ARAX, we get results:

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": [
                        "MONDO:0005260"
                    ],
                    "categories": [
                        "biolink:Disease"
                    ]
                },
                "n1": {
		             "categories":[
                         "biolink:ChemicalEntity"
                        ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n1",
                    "object": "n0",
                    "predicates":[
                        "biolink:treats"],
                    "knowledge_type": "inferred"

                }
            }
        }
    }
}
```

https://arax.ncats.io/?r=62968

**Comment by edeutsch** [comment]
One possibility is that ITRB production instance is not working?

Or another possibility is that they were still trying to use our TRAPI 1.2 endpoint.? All ARAX endpoints are now TRAPI 1.3 and TRAPI 1.2 is de-registered from SmartAPI, etc.

I somewhat unintentionally did not leave TRAPI 1.2 endpoints running (since we're all supposed to be switched).

Maybe that is the culprit. Or maybe not.

**Comment by dkoslicki** [comment]
I can't replicate this error; I just ran it again and things looked fine: https://arax.ncats.io/?r=63143, as well as the ITRB endpoint https://arax.transltr.io/?r=63144

**Comment by saramsey** [comment]
Are we good to close this issue?
