### ISSUE TITLE
Timeout message has changed?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1912]

**Comment by edeutsch** [comment]
Instead of a simple timeout message, we now have an ex exception shown:
![image](https://user-images.githubusercontent.com/12707718/190497907-3d2c89be-7732-4733-b5a0-0bfa5c1fdc26.png)

**Comment by amykglen** [comment]
interesting, I didn't think anyone had touched that code. wondering if maybe it had to do with our upgrading to Python 3.9... I'll take a look

**Comment by amykglen** [comment]
pushed a fix - verified working on the ITRB CI instance: https://arax.ci.transltr.io/?r=64698
