### ISSUE TITLE
Fix automatic database downloads in CICD system's Github actions

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1914]
@sundareswarpullela and I discussed this in detail today - documenting a summary here

we had a step in [RTX/.github/workflows/pytest.yml](https://github.com/RTXteam/RTX/blob/master/.github/workflows/pytest.yml) that automatically downloads databases as needed (and deletes old ones as needed) via the ARAX Database Manager; that Database Manager function works correctly but Github actions wasn't able to run it, saying it was unable to import `RTXConfiguration`. (this step is commented out for now.)

it seems to be that the `sys.path.append([abs_path])` method for imports doesn't work for Github actions - it uses a $GITHUB_PATH... though we also weren't successful today when trying to use that.

we have two options for a fix:
1. resolve the import error
2. instead run the Database Manager command from within the Docker container and then copy the downloaded databases out to the host machine. we'd likely need to add another Database Manager function that's made for running from within a Docker container... and not sure whether permissions would be an issue when trying to write out of the Docker container.

but before we can work on a fix, we should get set up so we can run Github Actions locally. (which seems to be weirdly hard to do...) [this](https://github.com/nektos/act) might help? being able to run the actions locally will allow us to do some real debugging..

**Comment by amykglen** [comment]
this is an example of the import error we get, fyi

https://github.com/RTXteam/RTX/actions/runs/3107811327/jobs/5036326534

**Comment by amykglen** [comment]
just an fyi for everyone - as discussed at today's AHM, I added an explanation to the ARAX wiki of the manual step that needs to happen until this issue is addressed.

https://github.com/RTXteam/RTX/wiki/CI-system-(via-GitHub-actions)
![Screen Shot 2022-10-21 at 11 04 07 AM](https://user-images.githubusercontent.com/49423686/197260752-f31ffa7b-a484-415f-b07b-1ac064ad9711.png)

**Comment by sundareswarpullela** [comment]
Hey @amykglen I know this has been sitting forever but I think it is now solved and all the pytest.yml commands are running with no import error. 
I just changed 
```

     - name: Append code dir to GITHUB_PATH                # Causing RTXConfiguration import error
       run: echo "$HOME/RTX" >> $GITHUB_PATH

    - name: Download databases as needed
      run: python3 code/ARAX/ARAXQuery/ARAX_database_manager.py --mnt --skip-if-exists --remove_unused
```


To:
```
    - name: Download databases as needed
      run: python3 $HOME/RTX/code/ARAX/ARAXQuery/ARAX_database_manager.py --mnt --skip-if-exists --remove_unused

```

**Comment by sundareswarpullela** [comment]
I will update the docs and close this issue once you've given it a once-over.

**Comment by sundareswarpullela** [comment]
Link to test build https://github.com/RTXteam/RTX/actions/runs/5139600151

**Comment by sundareswarpullela** [comment]
Closing issues
