### ISSUE TITLE
Conflicting dependency versions in requirements.txt

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1919]
@sundareswarpullela and I ran into this issue today when running `pip install -r requirements.txt` on a fresh python setup:

```
ERROR: Cannot install Flask, connexion and markupsafe==2.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested markupsafe==2.0.1
    jinja2 3.0.0 depends on MarkupSafe>=2.0.0rc2
    werkzeug 2.2.2 depends on MarkupSafe>=2.1.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

bumping the `markupsafe` version to 2.1.1 in `requirements.txt` fixed the problem. 2.1.1 appears to be the latest default version for that package.

any objections to changing `markupsafe==2.0.1` to `markupsafe==2.1.1` in `requirements.txt`?

**Comment by edeutsch** [comment]
sounds good to me. It is not even installed at all on arax.ncats.io. I wonder what we need it for? Maybe one of the doc generation tasks that we don't normally run? I'll install 2.1.1 on arax.ncats.io
Or maybe we don't even need it?

**Comment by edeutsch** [comment]
oh err, well, I tried installing 2.1.1 on arax.ncats.io:
```
# pip3 install markupsafe
Requirement already satisfied: markupsafe in /mnt/data/python/Python-3.9.13/lib/python3.9/site-packages (2.1.1)
```

so I dunno..
anyway, it seems fine.

ah, it seems there was a capitalization change, too, how fun:
```
requirements-newfreeze.txt:MarkupSafe==2.1.1
requirements-old.txt:markupsafe==2.0.1
```

That probably caused a problem with the old vs. new comparison.

**Comment by amykglen** [comment]
ah, that makes sense (the capitalization change).

ok, I just changed the relevant line in `requirements.txt` to `MarkupSafe==2.1.1`. and tested to make sure it's working in a fresh install.

closing, thanks!
