### ISSUE TITLE
Update KG2c build code for Biolink 3.0

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1922]
all changes should go in the `kg2integration` branch

Biolink 3.0 apparently breaks the BiolinkHelper module - Amy will work on this

Sundar will work on updating `create_kg2c_files.py` (after BiolinkHelper is fixed)

**Comment by amykglen** [comment]
it appears that in Biolink 3.0.3, `exposure event` is a mixin, but it `is_a: named thing`, which I didn't think was possible. (I thought that for mixins, the value in `is_a` had to also be a mixin - I believe that was true prior to Biolink 3.0.)

this seems to be what is tripping up BiolinkHelper with Biolink 3.0. I asked about this in the Translator slack just now.

**Comment by amykglen** [comment]
Nomi created this issue about the mixin/is_a question: https://github.com/biolink/biolink-model/issues/1111

**Comment by amykglen** [comment]
ran into one other issue in BiolinkHelper - a couple pairs of inverse predicates seem to be missing an indication of which is the `canonical_predicate` in Biolink 3.0.3. I filed this issue about that: https://github.com/biolink/biolink-model/issues/1112

and then added a temporary patch in our code that works around it.

so @sundareswarpullela - BiolinkHelper now appears to be working properly with Biolink 3.0.3, so you can proceed with working on the rest of the KG2c code changes. thanks!

**Comment by sundareswarpullela** [comment]
Got it, thanks. Will proceed with working on it @amykglen.

**Comment by sundareswarpullela** [comment]
Required changes are done. Waiting for test files with  `qualified_object_aspect` and `qualified_object_direction` predicates, which were missing in the current kg2pre test files for further testing. Lili working on the issue with the kg2pre test files.

**Comment by amykglen** [comment]
hey @sundareswarpullela - I'm starting to work on the changes to Plover for Biolink 3.0 - I've been using the file output by your test KG2c build called `kg2c_lite_test.json`. I noticed that when an edge doesn't have a value for one of the new properties, it's value in that JSON file is `None` in quotes, like so:
```
{
   "predicate":"biolink:affects",
   "qualified_object_direction":"None",
   "object":"NCIT:C1526",
```
but that isn't ideal for parsing the JSON file. really in the JSON file we would want that value to be null, like this:
```
{
   "predicate":"biolink:affects",
   "qualified_object_direction":null,
   "object":"NCIT:C1526",
```
Python automatically converts `None` to `null` when dumping a dictionary to JSON, so I think somewhere in the KG2c code, before creating the JSON file, the `None` value is somehow being converted to a string? it'd be awesome if you could try to debug what's going on there.

**Comment by sundareswarpullela** [comment]
Looking into it @amykglen

**Comment by saramsey** [comment]
Thank you @amykglen for notifying the SRI team.

**Comment by amykglen** [comment]
@sundareswarpullela - are we safe to close this issue since the KG2.8.0c build is complete?

**Comment by sundareswarpullela** [comment]
Yes @amykglen, closing this ticket now.
