### ISSUE TITLE
Error: result contains more than one node that is a candidate for the essence

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1923]
Pursuant to the "ATP1A3" Question of the Month Challenge (see [github:NCATSTranslator/testing/issues/233](https://github.com/NCATSTranslator/testing/issues/233)), I ran the following three-hop DSL query through the UI on `arax.rtx.ai` on the morning of Thu. Oct. 20, at 8:50 AM PDT:
```
add_qnode(name=ATP1A3, key=n0)
add_qnode(categories=biolink:PhenotypicFeature, key=n1)
add_qnode(categories=biolink:Protein, key=n2)
add_qnode(categories=biolink:ChemicalSubstance, key=n3)
add_qedge(subject=n0, object=n1, key=e0)
add_qedge(subject=n1, object=n2, key=e1)
add_qedge(subject=n2, object=n3, key=e2)
expand()
resultify()
filter_results(action=limit_number_of_results, max_results=50))
```
and the system gave the following error message:
```
2022-10-20T15:52:17.246094 DEBUG: Loading final result graphs into TRAPI object model
2022-10-20T15:52:17.246498 ERROR: Result contains more than one node that is a candidate for the essence: {'UniProtKB:P29350', 'UniProtKB:P18031', 'REACTO:REACTO_R-HSA-162563', 'UniProtKB:Q06124'}
```
Can we please modify the code to give a warning and just pick one of the CURIES arbitrarily, somehow?  Or am I doing something wrong with the DSL query?

**Comment by amykglen** [comment]
that seems strange to me that it has trouble with that query graph, but I don't know that bit of code very well (I think it's still @saramsey's code that finds the essence node in a QG). I agree issuing a warning and picking one arbitrarily sounds like a good idea... happy to make that change

**Comment by amykglen** [comment]
ohh, I bet it's subclass reasoning that is leading to there being more than one node fulfilling the essence qnode in a result... hmm, I think ideally the 'essence' node in such situations would be the 'parent' concept they're fulfilling (of which there should be only one per result...) I'll work on getting this fixed

**Comment by saramsey** [comment]
Thank you, and sorry that my code just threw up its hands and raised an error!

**Comment by amykglen** [comment]
ok, this has been fixed, tested, and merged into `master`. I'm not sure whether our ITRB CI ARAX instance automatically deploys at the moment, due to the issues they've been having? I'm guessing not.. (it appears our Jenkins login isn't working, so I can't check on build statuses.)

so I'll plan to verify this is working as expected after `master` is next rolled out to one of our instances.

**Comment by amykglen** [comment]
pushed a fix for the new error to `master` (it was due to a KP returning `Node`s without any `categories`, which I don't think is valid TRAPI, but still shouldn't cause the entire query to error out)

will verify next time `master` is rolled out

**Comment by edeutsch** [comment]
`master` has been deployed in all the usual master places

**Comment by amykglen** [comment]
this issue appears fixed on /beta; there's a different issue occurring with this query near the end of processing - wrote that up in #1989
