### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement reasoner-validator==2.2.13

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1924]
It appears that `cicd.rtx.ai` is unable to install the `reasoner-validator` package specified in `requirements.txt`:

![Screen Shot 2022-10-21 at 11 24 38 AM](https://user-images.githubusercontent.com/49423686/197265384-41ddefd4-3186-4807-9073-7f94c8c26b55.png)

https://github.com/RTXteam/RTX/actions/runs/3299527438/jobs/5442993890#step:7:2046

(our build will show as failed in GitHub until we fix this)

maybe @edeutsch knows what's going on here? maybe related to the release of `reasoner-validator` 3.0?

**Comment by edeutsch** [comment]
I am puzzled, but I know Richard has been working on this a lot. As part of work with him earlier in the week, I am now running 2.2.14 on arax.ncats.io. Strange that 2.2.13 is gone, though.

Would you try switching to 2.2.14 and see how that goes? I am stuck in an all-day meeting today.

**Comment by amykglen** [comment]
that seems to have worked, thanks!
