### ISSUE TITLE
KG2 down??

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1927]
I received an alert that ARAX is having a problem. It appears that KG2 is down?
![image](https://user-images.githubusercontent.com/12707718/199072308-48dbbc10-49d6-4b3a-9399-42e0ff511333.png)

Curiously, BTE also returned an error?

Is anyone available to troubleshoot KG2? Perhaps @amykglen ?

**Comment by edeutsch** [comment]
I received a response from BTE upon another test. But RTX-KG2 is still returning 503

**Comment by amykglen** [comment]
hmm, it looks to me like the production kg2 endpoint is the only one having problems (https://arax.ncats.io/kg2/). it gives an 'unexpected syntax error' before any log messages appear (upon running the example query).... should we try restarting that endpoint?

I guess the ITRB production kg2 instance is also having trouble (https://kg2.transltr.io/), though it doesn't log an actual error for me - just keeps saying 'Posting JSON, looking for answer..." after I run the example query.

the other three KG2 endpoints (kg2beta, ITRB CI, and ITRB test) seem to be working properly.

**Comment by amykglen** [comment]
I wonder if `/kg2` maybe got overloaded this morning? looks like Aragorn was sending a bunch of queries based on the 'System Activity' tab...

**Comment by edeutsch** [comment]
I can try restarting

**Comment by edeutsch** [comment]
thanks, that's all it was. Sorry, I should have tried that before raising the alarm. The logs did not show anything illuminating, except that child processes were being killed. maybe it was an overload situation, dunno. Seems unlikely this the load is nowhere near as high as I've seen it in the past.

Anyway, resolved, I think.
