### ISSUE TITLE
Don't update meta map if SmartAPI returns nothing

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1929]
this stems from #1928

from @edeutsch:
> I wonder if it is worth putting in a little snippet of code into ARAX that IF SmartAPI yields NOTHING (or perhaps just less than some floor number of results from the query, e.g 10 or 20), then do nothing to the current cache. Just reuse it because SmartAPI is clearly not running correctly and instead of damaging existing metaKG information, just continue to operate with previous values.
> ?

this is a great idea. think we'll just need to update `KPSelector` (and possibly `smartapi.py`) to make it skip deleting 'stale' KPs from the meta map if SmartAPI returns nothing (or something tiny).

**Comment by saramsey** [comment]
@amykglen can we close this issue?

**Comment by amykglen** [comment]
It looks like we have a basic check for this now: https://github.com/RTXteam/RTX/blob/a3dc16464d542996f79b07d4bf88411a7a7cdfbe/code/ARAX/ARAXQuery/Expand/kp_info_cacher.py#L66-L69

closing
