### ISSUE TITLE
Automatic deployment to ITRB not working

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1931]
Just this morning I rolled out the content of branch `master` to branches `itrb-test` and `production`. This includes a change to the UI, which should now identify as "Free Kite", as can be seen in the lower left of arax.cats.io production:
https://arax.ncats.io/

However, all three ITRB instances are still stuck on "Arctic Bedbug":
https://arax.transltr.io/
https://arax.test.transltr.io/
https://arax.ci.transltr.io/

It would seem that none of the auto deployment systems are functioning. I suppose we need to open this with ITRB? Anyone have any insight?

thanks,
Eric

**Comment by amykglen** [comment]
from Ke's [latest message](https://ncatstranslator.slack.com/archives/C023J4P0Y1M/p1666793049515699) in the Slack `devops-teamexpanderagent` channel, it sounds like ITRB is only doing manual deployments currently? sounds like they are working to be able to resume automated deployments.

**Comment by edeutsch** [comment]
ah, great, thanks, I lost track of that. I will ask them to do a manual deployment
