### ISSUE TITLE
Let's not go the way of Meta's Galactica

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1935]
If you've seen the [new](https://www.cnet.com/science/meta-trained-an-ai-on-48-million-science-papers-it-was-shut-down-after-two-days/), this language model was shut down rather quickly due to its ridiculous answers. Trying out one similar test query (with vaccines and autism), on our system, I got: https://arax.ncats.io/?r=99378 .

This came from RTX-KG2 (don't know if you want to cross-post this issue @saramsey @amykglen @acevedol).

The underlying SemMedDB snippets look reasonable, but the predicates sure are unfortunate.

**Comment by saramsey** [comment]
@dkoslicki thank you for bringing this up. Yeah, that's awkward:

<img width="1120" alt="Screen Shot 2022-11-21 at 9 44 15 PM" src="https://user-images.githubusercontent.com/5562107/203234354-482c5964-d1a5-4827-8897-e27f419f61aa.png">

But perhaps a useful use-case to figure out how to improve ARAX?

**Comment by dkoslicki** [comment]
Precisely: an example to sanity check our ranking and filtering

**Comment by edeutsch** [comment]
I wonder if this is a case where we need some special logic in the KG2 build process to correct some known problems. And this is also a case where we want to use the "NOT" modifier to statements. So that that statement is "vaccines NOT biolink:causes autism spectrum disorder".

**Comment by dkoslicki** [comment]
Just checked and while this particular query now returns zero results, a modification (different CURIEs) does: https://arax.test.transltr.io/?r=247697. Technical debt, or....?

**Comment by dkoslicki** [comment]
closing in favor of #2303
