### ISSUE TITLE
Qualified predicates?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1938]
Hi @saramsey @amykglen @acevedol @edeutsch , do you know the status of qualified predicates? They were the subject of the standup meeting today: https://github.com/NCATSTranslator/testing/issues/244 and while the [query runs](https://arax.rtx.ai/?r=107940) on arax.rtx.ai, I don't see the qualifiers being respected.

Is this perhaps blocking on the newest KG2?

**Comment by amykglen** [comment]
yep, qualifiers will come with KG2.8.0.

**Comment by amykglen** [comment]
and as for the status of that - I'm working on getting Plover updated, and then it will basically be a matter of doing the rollout - hopefully we'll have access to arax.ncats.io again soon. I think we'll need Eric for the rollout, so it'll probably happen next week after he's back.
