### ISSUE TITLE
New creative/templated query

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1939]
Per the last Architecture call, the next templated query will be: `Chemical-[affects; up or down]-gene`.

We need to:

1. See if there exists sufficient training data to use a model similar to xDTD
2. If not, devise an alternative approach

**Comment by dkoslicki** [comment]
Idea from 1/11/23 meeting:
1. Use the GraphSage + RF for the prediction of which chemicals to choose
2. For the explanation, look for shortest path(s) through a transcription factor

Might also consider MolePro has info that could help with step 1

**Comment by dkoslicki** [comment]
TF database: http://bioinfo.life.hust.edu.cn/hTFtarget/#!/download

**Comment by dkoslicki** [comment]
Adding @kvnthomas98 as he might work with @chunyuma to get the (shortest) paths through transcription factors or (mi)RNAs, not just the shortest paths.

**Comment by dkoslicki** [comment]
@kvnthomas98 Any update on this issue? It would be good to get the second part implemented: for the explanation, look for shortest path(s) through a transcription factor or miRNA

**Comment by dkoslicki** [comment]
@kvnthomas98 This one has been around for a while. Do you have a plan for it to be implemented & finished in the next sprint or two?

**Comment by edeutsch** [comment]
This is xCRG implementation. Complete.
