### ISSUE TITLE
Add temporary patch to KG2c build code that fixes missing qualified_predicates

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1942]
this stems from issue RTXTeam/RTX-KG2#250

basically we want to add a patch to the KG2c build code that, for any edge that has `predicate` == "regulates" **and** `qualified_direction` is not None **and** `qualified_predicate` is None, set their `qualified_predicate` to "causes" and their `qualified_aspect` to "activity_or_abundance".

I think it's probably worth adding this patch (it could be done early in the build process, maybe even right after loading the KG2pre edges?) and then doing a rebuild of KG2.8.0c, since we want these changes reflected in the KG2c JSON as well as all other output files (sqlite, etc.)

(all code changes should go in the `kg2integration` branch, along with the rest of the Biolink 3.0-related changes)

**Comment by sundareswarpullela** [comment]
Made the necessary changes for the patch. Currently building kg2.8.0c with the latest changes.

**Comment by amykglen** [comment]
hey @sundareswarpullela - I just re-loaded KG2c into Neo4j, but it doesn't look like your fix is present in the data (still 2.4 million edges that have a qualified_object_direction but no qualified_predicate).

were the rebuilt KG2c files for sure uploaded to the S3 bucket? it looks like the kg2c-tsv.tar.gz in the S3 bucket was uploaded on December 15, 2022, 23:25:53 (UTC-08:00). is that the right version?

**Comment by amykglen** [comment]
(I suppose an easier way of checking whether the build date seems right is by looking at the build node in Neo4j)

![Screen Shot 2023-01-05 at 3 01 07 PM](https://user-images.githubusercontent.com/49423686/210896598-6fb836e3-a6f1-4f14-a102-3e92790d18dc.png)

**Comment by sundareswarpullela** [comment]
I'll check ASAP @amykglen

**Comment by amykglen** [comment]
cool, no worries. thanks @sundareswarpullela!

**Comment by sundareswarpullela** [comment]
Build completed and verified. 
`CHEBI:27912     UniProtKB:P28482        biolink:regulates       infores:semmeddb        PMID:23734186ǂPMID:16533608     {'PMID:16533608': {'publication date': '2006 Sep', 'sentence': 'Exposure of the cells in suspension to PMA, LPS and mannan triggered an activation of p38 and ERK2.', 'subject score': 1000, 'object score': 1000}, 'PMID:23734186': {'publication date': '2013', 'sentence': 'This increased secretion of TNF-alpha and IL-6 and activation of NF-kB, ERK, and JNK was significantly inhibited by the addition of either mannan or mannose.', 'subject score': 861, 'object score': 1000}}     UMLS:C0024727---SEMMEDDB:stimulates---None---None---increased---UMLS:C1366882---SEMMEDDB:ǂUMLS:C0024727---SEMMEDDB:stimulates---None---None---increased---NCBIGene:5594---SEMMEDDB:     biolink:causes  activity_or_abundance   increased       8562104 biolink:regulates       CHEBI:27912     UniProtKB:P28482`

**Comment by amykglen** [comment]
I loaded the new KG2c into neo4j and confirmed the patch seems to have worked. thanks @sundareswarpullela!
