### ISSUE TITLE
Answering queries with qualifiers (in Plover)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1943]
so while some aspects of the logic behind answering queries with qualifiers is obvious to me, others are not.

for example, imagine there is a hypothetical edge in KG2 like this:
```
subject: nodeA
object: nodeB
predicate: affects
qualified_predicate: causes
qualified_object_direction: increased
qualified_object_aspect: degradation
```
which can be represented with shorthand notation like so:
```
nodeA--affects--causes--increased--degradation--nodeB
```

now it's obvious that if someone submits a TRAPI query like this, we should return the hypothetical KG2 edge:
```
nodeA--affects--causes--increased--degradation--X
```

and I'm also assuming we need to handle hierarchical reasoning for all of these 'qualified' properties; so, for instance, we should also return the hypothetical KG2 edge for all of these queries:
```
nodeA--affects--contributes_to--increased--degradation--X    (contributes_to is ancestor of causes)
nodeA--affects--causes--increased--abundance--X              (abundance is ancestor of degradation)
nodeA--affects--causes--upregulated--degradation--X          (upregulated is ancestor of increased)
nodeA--related_to--causes--increased--degradation--X         (related_to is ancestor of affects)
```
as well as all possible _combinations_ of ancestors in the different properties.

but what if someone submits a query such that the hypothetical KG2 edge fulfills the _qualified_ portion of the QG, but the regular `predicate` in their query does not match the KG2 edge? e.g., their query is:
```
nodeA--interacts_with--causes--increased--degradation--X     (interacts_with is NOT ancestor of affects)
```
I'm assuming we shouldn't return the hypothetical KG2 edge in this case, but not positive? I'm not sure whether the `predicate` should just be ignored when the query specifies a `qualified_predicate`? the regular `predicate` does seem kind of irrelevant in that situation...

wondering if @edeutsch or @saramsey know whether the TRAPI/Biolink groups have discussed such details of what it means to fulfill qualified queries...

**Comment by amykglen** [comment]
also, does anyone know whether we're supposed to be referring to 'aspects' and 'directions' with the `biolink:` prefix? (e.g., `biolink:increased`, `biolink:degradation`, etc.)

I'm assuming so, although the KG2pre files seem not to (though they do refer to `predicate`/`qualified_predicate` using that prefix)

**Comment by amykglen** [comment]
based on discussion with Steve just now - we're thinking if a query provides a `qualified_predicate`, the `predicate` should just be ignored when answering that query, since in our understanding `qualified_predicate` inherently provides more detailed information than `predicate`.

but it might be useful (perhaps in the ARAX code) to throw an error if someone specifies both a `qualified_predicate` and a `predicate` in their query, otherwise the system might return edges that don't necessarily match the QG's `predicate`, which could confuse users... (maybe that is a TRAPI decision?)

**Comment by amykglen** [comment]
also, I wrote up [this issue](https://github.com/biolink/biolink-model/issues/1206) in the Biolink repo about the strange situation Steve pointed out earlier that results from 'abundance' being an ancestor of 'degradation'

**Comment by edeutsch** [comment]
I'm thinking it would be nice to just plow ahead with a reasonable interpretation and make a list of such questionable decisions. We should ask them, but we probably shouldn't hold up the works until we get an answer. We may not get an answer soon.

I am thinking that if the qualified_predicate matches, then the predicate can be ignored. maybe just issue a warning if they seem to be mismatching somehow.

**Comment by amykglen** [comment]
closing since no one has objected to our interpretation of how to answer qualifier queries
