### ISSUE TITLE
Ignore qualifiers: []

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1945]
In our standard test query (except with physically_interacts_with replaced with interacts_with), there is a result like this:
![image](https://user-images.githubusercontent.com/12707718/211908942-edc1f069-2dd2-4c89-acdc-4ec1297f7926.png)
![image](https://user-images.githubusercontent.com/12707718/211908974-e01f8ac6-d703-44f2-b1ac-f13dd4a781e7.png)

This comes from:
```
        "infores:molepro:DRUGBANK:DB00316-biolink:interacts_with-None--None--None--CHEMBL.TARGET:CHEMBL230": {
          "object": "CHEMBL.TARGET:CHEMBL230",
          "predicate": "biolink:interacts_with",
          "qualifiers": [],
          "subject": "CHEMBL.COMPOUND:CHEMBL112"
        },
```

where qualifiers is an empty list.

I think it would be best to update the UI so that is treats:
```
          "qualifiers": [],
```
the same as:
```
          "qualifiers": null,
```
i.e. no qualifiers flagging or rendering

**Comment by isbluis** [comment]
I have fixed this in my dev area:  https://regis-web.systemsbiology.net/~lmendoza/ARAX/

Let me know if this should go in soon (before) or after the merge of NewFmt.

**Comment by edeutsch** [comment]
great, thanks, yes please merge into master right away, thanks!

**Comment by isbluis** [comment]
Is this okay to close, @edeutsch ?

**Comment by edeutsch** [comment]
yes, thanks, closing!
