### ISSUE TITLE
Replace icees (asthma), icees-pcd, and icees-dili with icees-kg as Translator KP

### ISSUE THREAD

**Issue by karafecho** [RTXteam/RTX#1947]
This issue is to report that Exposures Provider has redesigned ICEES into two separate services: the fully featured ICEES+, which **is not** a Translator service, and the less fully featured ICEES KG, which **is** a Translator service (see SmartAPI registration below). As such, we are asking ARAs to update all relevant code accordingly. Thanks!

SmartAPI registration: https://smart-api.info/ui/44e7a1147ca8657f50af6bb25982762d

![image](https://user-images.githubusercontent.com/26254388/211891788-ad7c65e7-326a-4127-9ec0-893dc641fc46.png)

**Comment by amykglen** [comment]
thanks for letting us know! since ARAX now dynamically selects KPs from the SmartAPI registry for each query, we're already using ICEES KG, so I'll close this issue.

**Comment by karafecho** [comment]
Excellent! I did not realize that ARAX is now dynamically selecting KPs from the SmartAPI registry. That's great!
