### ISSUE TITLE
araxconfig.rtx.ai out of disk space

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1948]
`araxconfig.rtx.ai` seems to be out of disk space, even though I deleted several archived files and rebooted the instance...

maybe we need to increase the space a little bit?

![Screen Shot 2023-01-12 at 10 23 37 AM](https://user-images.githubusercontent.com/49423686/212148085-2d24153d-d56f-49e5-9498-12bf64e73a93.png)

**Comment by amykglen** [comment]
I enlarged the volume from 8G to 12G so that I could add @kvnthomas98's RSA public key

seems fine now, closing

**Comment by edeutsch** [comment]
Perhaps this obvious and was addressed, but I'm thinking there may be a unaddressed fundamental reason why the disk was full. Perhaps there are rampant unrotated error logs, such it will fill 12 GB in a few months? i.e. perhaps this is but a temporary patch on what is a more fundamental problem? Given the role of the server, it seems that 8 GB would have been sufficient for normal operation?
