### ISSUE TITLE
Ensure database file naming follows the names mentioned in config_dbs.json

### ISSUE THREAD

**Issue by sundareswarpullela** [RTXteam/RTX#1949]
Right now, the database files are not following the naming convention mentioned in the `config_dbs.json`, file. 
The following file changes are being done manually ones the files are saved:
`kg2c.sqlite  --> kg2c_v1.0_KG2.8.0.sqlite`
`fda_approved_drugs.pickle --> fda_approved_drugs_v1.0_KG2.8.0c.pickle`
`kg2c_meta_kg.json --> meta_kg_v1.0_KG2.8.0c.json`
`autocomplete.sqlite --> autocomplete_v1.0_KG2.8.0.sqlite`

**Comment by sundareswarpullela** [comment]
This has been tested on a test build with the versioning implementation through `kg2c_config.json`.

**Comment by amykglen** [comment]
awesome, thanks! should we close this issue since it's done and tested?

**Comment by sundareswarpullela** [comment]
Yes this is tested. This can be closed. Apologies for the delay
