### ISSUE TITLE
"Post to OTHER" doesn't work, although the query succeeds

### ISSUE THREAD

**Issue by gaurav** [RTXteam/RTX#1950]
At https://arax.ncats.io/, I tried setting the `EXTERNAL API (post query):` to `https://cam-kp-api-dev.renci.org/1.3.0/` and then running the following query using the "Post to OTHER" option:

<details><summary>Query to run</summary>

```json
{
  "edges": {
    "e0": {
      "object": "n1",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n0"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:NamedThing"
      ],
      "fulltextname": "n0"
    },
    "n1": {
      "categories": [
        "biolink:NamedThing"
      ],
      "ids": [
        "CHEBI:8382"
      ],
      "fulltextname": "n1"
    }
  }
}
```
</details>

I get the error "An error was encountered while parsing the response from the remote server (no log; code:Success)". However, when using the network debugger, I can see that my TRAPI endpoint is being queried correctly. If I copy the JSON response into the ARAX Response Input box, it parses it correctly and displays my results correctly.

Is my endpoint returning something incorrectly?

**Comment by isbluis** [comment]
Hello @gaurav .  Please update the `status` in the response to "OK" instead of "Success" and see if that solves the issue.

**Comment by isbluis** [comment]
Hello @gaurav , did this work and can we close the issue?  Otherwise let us know if you are still getting an error.

**Comment by gaurav** [comment]
Sorry for my very late reply, @isbluis! I haven't had a chance to try this out yet, but you can close this issue -- I'll reopen it if this doesn't fix the problem.

Do you know where "OK" as the appropriate `status` is recorded? The TRAPI documentation refers to "e.g. Success, QueryNotTraversable, KPsNotAvailable" -- if "OK" is the correct expected value, I think it should be added to that list.

https://github.com/NCATSTranslator/ReasonerAPI/blob/c5d101ab95719da62b2ee375469c9b19160dd30c/TranslatorReasonerAPI.yaml#L318

**Comment by gaurav** [comment]
Thanks, @isbluis! This fix works great for us :)
