### ISSUE TITLE
Cache KP SmartAPI and meta KG info in a background task

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1952]
right now all of Expand's querying of the SmartAPI registry and caching of KPs' `meta_knowledge_graph` info happens at query runtime (I think the meta KG cache is refreshed upon running a query if it's been more than 24 hours; I'm not sure whether the SmartAPI info is cached at all).

it'd be ideal if we had a background task that would regularly (maybe every hour?) grab and cache all of the SmartAPI/meta KG information for us, so queries only ever use cached information.

@edeutsch is going to think about the best way to set up the background task, but in the meantime the Expand team can work on writing a function that the task will call.

note that we already have code that grabs all the SmartAPI/meta KG info we need, all of which is called in [KPSelector](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Expand/kp_selector.py); I think what we'll probably want to do is kind of rewrite `KPSelector` to separate the caching from the actual KP selection.

**Comment by amykglen** [comment]
also we should take care of #1929 while working on this issue

**Comment by amykglen** [comment]
caching SmartAPI info is high priority per the June relay! important that ARAX doesn't go down if the SmartAPI is down.

**Comment by edeutsch** [comment]
maybe a good topic for next week's mini-hackathon to plan out how to do this. There are multiple aspects to this and a good plan that we all agree on would be good.

**Comment by edeutsch** [comment]
Let's meet at 1pm. Eric will send zoom.

**Comment by amykglen** [comment]
ok, so I cleaned things up in the `issue1952` branch

and now the only file that @sundareswarpullela needs to add to is a new file called `kp_info_cacher.py`

I marked the locations where the waiting/pid code we discussed yesterday needs to go with 'TODO: FOR SUNDAR'. 

here' s an example:
https://github.com/RTXteam/RTX/blob/81c7050ac459e93feba7b6e82dff8e2d08585380/code/ARAX/ARAXQuery/Expand/kp_info_cacher.py#L109-L114

I believe there are only three TODOs Sundar needs to address.

I verified that everything is running smoothly as is in the branch - the meta map and smart api info appears to be generated, cached, and loaded from cache correctly (all pytests are passing). 

you'll see that there are two auto-generated cache files now, named using their trapi version and maturity level:
<img width="404" alt="Screen Shot 2023-06-15 at 7 24 09 PM" src="https://github.com/RTXteam/RTX/assets/49423686/2b539d48-ecea-4196-a787-330312ea7aea">

when @edeutsch writes the background task, he will only need to call one method (on one class):
```
from kp_info_cacher import KPInfoCacher
kpic = KPInfoCacher()
kpic.refresh_kp_info_caches()
```
that handles refreshing both the meta map and the Smart API caches. (I realized these need to be refreshed together because the meta map depends on the SmartAPI info..)

**Comment by edeutsch** [comment]
Many thanks, Amy!

**Comment by sundareswarpullela** [comment]
Thanks Amy!

**Comment by sundareswarpullela** [comment]
Work is done and it is tested. I tested running the Following two scripts one after the other:
```
from kp_info_cacher import KPInfoCacher
kpic = KPInfoCacher()
kpic.refresh_kp_info_caches()
```
and 
```
from kp_info_cacher import KPInfoCacher
kpic = KPInfoCacher()
smart_api_info, meta_map = kpic.load_kp_info_caches(ARAXResponse())
```
The load script is waiting for the caches to be refreshed before trying to read the cache files and return the results.

**Comment by edeutsch** [comment]
Hi @sundareswarpullela I fixed a couple things
https://github.com/RTXteam/RTX/commit/cd7f89f0ff4b171c17308a9660ed96b793a25153
https://github.com/RTXteam/RTX/commit/8c942d91f29e7915fb34f45aef13bd02a0a58d1a

and it is now being called in the Background Tasker process and seems like it may be working.
However, when I issue a query in test on branch 1952, the query just hangs, perhaps waiting for something?
```
2023-07-05T19:14:09.940268 INFO: Processing action 'expand' with parameters {'': 'true'}
2023-07-05T19:17:10.426190 DEBUG: Query is still progressing...
2023-07-05T19:20:10.856007 DEBUG: Query is still progressing...
```

Can you fix?

**Comment by edeutsch** [comment]
@sundareswarpullela have you seen this? Any plans to address it?

**Comment by sundareswarpullela** [comment]
@edeutsch Yes, I think its because we are not deleting the process ID file after refreshing is done. Testing the changes now.

**Comment by edeutsch** [comment]
I'm thinking we need to have some kind of alternative path. Suppose the refresher crashes? (which it was doing sometimes before I fixed it) or hangs? and the ID file never gets deleted? We can't afford to have all queries just hang forever waiting for some work to complete that never will.

I think the system needs to be more robust here

Thinking about it a bit more, why were the queries hanging at all? If there is a cache, they should just go ahead and use it. Why were they waiting?

**Comment by sundareswarpullela** [comment]
I think the OS re-assigns the PID to another process and it is also running, but it is not actually refreshing the databases.

**Comment by sundareswarpullela** [comment]
Yeah I'm working on some additional logic to avoid the issue you pointed out.

**Comment by sundareswarpullela** [comment]
@edeutsch, if the process is running for over 5 seconds, we can skip the wait step.

**Comment by edeutsch** [comment]
hmm, I don't understand. A query should almost never wait

**Comment by edeutsch** [comment]
I went ahead and merged `issue1952` into `master` and deployed to all the usual places. It appears to be working reasonably well. Thank you. Closing.
