### ISSUE TITLE
What is ARAX's official infores curie?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1954]
I noticed that in our code we use `infores:arax` in some places (e.g., Expand) and `infores:arax-reasoner-ara` in other places (e.g., Overlay). 

but interestingly, the best resource I can find seems to say ARAX's infores curie is actually _neither_ of those, but instead `infores:arax-reasoner`? (see the 'Translator SmartAPI Resources' tab in [this](https://docs.google.com/spreadsheets/d/1Ma4U3aY16mJushsW74vf9mWVacFvf7FiTEdlVqaUi5g/edit#gid=1644860829) spreadsheet)

is anyone more in the loop on this than me? or do we need to change our code to use `infores:arax-reasoner`?

**Comment by edeutsch** [comment]
I think that sheet is deprecated? I think this is the current one:
https://docs.google.com/spreadsheets/d/1Ak1hRqlTLr1qa-7O0s5bqeTHukj9gSLQML1-lg6xIHM/edit

and that one says that "infores:arax" is the right one
I'm not 100% certain, but it looks current.

**Comment by amykglen** [comment]
ah, thanks! ok, that does look current.

so I guess that means we should update Overlay to use `infores:arax`? (@dkoslicki, @chunyuma)

![Screen Shot 2023-01-20 at 9 13 32 AM](https://user-images.githubusercontent.com/49423686/213761994-cc55221c-72e4-4731-8703-60651a8fc76f.png)

**Comment by edeutsch** [comment]
I think we should yes

**Comment by chunyuma** [comment]
ok, all Overlay scripts are updated to use `infores:arax`.

**Comment by amykglen** [comment]
cool, thanks! I added the 'verify in next deployment' tag

**Comment by edeutsch** [comment]
sorry for the delay, the latest master is deployed to /test and /beta

**Comment by amykglen** [comment]
verified this appears to be correct on `/beta` now. thanks!
