### ISSUE TITLE
Questions about the creative mode of xCRG

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1959]
For the creative mode of xCRG (explainable Chemical Regulate Gene), I'm working on adding a new action `chemical_regulation_gene_graph_expansion` into the `ARAX_infer` module to answer the following four questions:

1. What chemical `increases` a particular gene's activity or abundance?
2. What chemical `decreases` a particular gene's activity or abundance?
3. What gene's activity or abundance is `increased` by a particular chemical?
4. What gene's activity or abundance is `decreased` by a particular chemical?

Here I have a few questions:
1. What `attribute_type_id` (e.g., EDAM:data_0951) should we use for the virtual edge generated by the creative mode of xCRG?
2. What `predicate` should we use? `biolink:probability_increase_activity` and  biolink:probability_decrease_activity`?
3. What `predicate` should we use in the query graph to distinguish the `increase-type` model and the `decrease-type` model? For example, in the `xDTD` creative mode, we use the [biolink:treats](https://github.com/RTXteam/RTX/blob/951fadfadfa9b51e7dfd908fd2e3c87b5f5aaa7e/code/ARAX/test/test_ARAX_infer.py#L174) and [all its ancestors](https://github.com/RTXteam/RTX/blob/951fadfadfa9b51e7dfd908fd2e3c87b5f5aaa7e/code/ARAX/ARAXQuery/ARAX_expander.py#L366-L367). Note that we have two regulation direction (increase or decrease). It seems like there is [no biolink predicate](https://tree-viz-biolink.herokuapp.com/predicates) for both increase and decrease directions.

Any ideas for these questions?

**Comment by dkoslicki** [comment]
1. How about `operation_2423` as this stands for `Predict, recognise, detect or identify some properties of a biomolecule`
2. How about `biolink:probably_affects`? The direction is specified in the qualifiers
3. I think this needs to be handled via the qualifier attributes. See [this example](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/mvp2dEstrogen.json) and note the predicate is `biolink:affects`, and the up-or-down is in the `qualifier_set`. @amykglen or others who are more familiar with the qualified constraints work may know more

**Comment by amykglen** [comment]
re: item 3: yeah, I think the kinds of qualified edges you're interested in are these ones (from [this](https://github.com/biolink/biolink-model/blob/v3.0.0/images/predicate_transformation.pdf) pdf, which maps from Biolink 2.x to 3.x):

![Screen Shot 2023-02-02 at 5 29 18 PM 1](https://user-images.githubusercontent.com/49423686/216489546-0f480786-0f10-453a-ab0d-8a47a5e12783.png)

so as for your logic, I suppose you definitely want to inspect the `object_aspect_qualifier` to see if it is `activity_or_abundance` (see below example KG2 query, under the `qualifier_set` slot).. (note that aspects also lie on a [hierarchy](https://tree-viz-biolink.herokuapp.com/aspects))

I'm not sure if you need to look for anything else? I think the regular `predicate` could be `affects` or `regulates` (a descendant of `affects`), and the `qualified_predicate` would be `causes`, but neither of those (`predicate` or `qualified_predicate`) _have_ to be specified in a query.


```
{
        "nodes": {
            "n0": {
                "ids": ["NCBIGene:375"]
            },
            "n1": {
                "categories": ["biolink:Gene"]
            }
        },
        "edges": {
            "e0": {
                "subject": "n0",
                "object": "n1",
                "qualifier_constraints": [
                    {"qualifier_set": [
                        {"qualifier_type_id": "biolink:qualified_predicate",
                         "qualifier_value": "biolink:causes"},
                        {"qualifier_type_id": "biolink:object_direction_qualifier",
                         "qualifier_value": "decreased"},
                        {"qualifier_type_id": "biolink:object_aspect_qualifier",
                         "qualifier_value": "activity_or_abundance"}
                    ]}
                ],
                "attribute_constraints": [
                    {
                        "id": "biolink:knowledge_source",
                        "name": "knowledge source",
                        "value": ["infores:rtx-kg2"],
                        "operator": "==",
                        "not": false
                    }
                ]
            }
        }
    }
```

**Comment by chunyuma** [comment]
> How about operation_2423 as this stands for Predict, recognise, detect or identify some properties of a biomolecule

@dkoslicki where can I find the information about `operation_2423`? I'm wondering if we can keep using the prefix `EDAM`. Or we should use others.

**Comment by dkoslicki** [comment]
https://www.ebi.ac.uk/ols/search?q=operation_2423&ontology=edam

and I think `EDAM` is the correct prefix (though @edeutsch may know better than I)

**Comment by chunyuma** [comment]
Hi @amykglen and @edeutsch,

For the current [Edge class](https://github.com/RTXteam/RTX/blob/master/code/UI/OpenAPI/python-flask-server/openapi_server/models/edge.py) used in ARAX, I found that there is a property of `qualifiers` but no property of `qualifiied_constraints` like:
```
{'attributes': [{'attribute_source': 'infores:arax',
                 'attribute_type_id': 'biolink:aggregator_knowledge_source',
                 'attributes': None,
                 'description': None,
                 'original_attribute_name': 'provided_by',
                 'value': 'infores:arax',
                 'value_type_id': 'biolink:InformationResource',
                 'value_url': None},
                {'attribute_source': 'infores:arax',
                 'attribute_type_id': 'biolink:computed_value',
                 'attributes': None,
                 'description': 'This edge is a container for a computed value '
                                'between two nodes that is not directly '
                                'attachable to other edges.',
                 'original_attribute_name': None,
                 'value': True,
                 'value_type_id': 'metatype:Boolean',
                 'value_url': None},
                {'attribute_source': None,
                 'attribute_type_id': 'EDAM:operation_2423',
                 'attributes': None,
                 'description': None,
                 'original_attribute_name': 'biolink:probability_increase_activity',
                 'value': '0.9664287974033743',
                 'value_type_id': None,
                 'value_url': None}],
 'object': 'UniProtKB:Q8NER1',
 'predicate': 'biolink:probably_increase_activity',
 'qualifiers': None,
 'subject': 'CHEMBL.COMPOUND:CHEMBL1097205'}
```
This result is from `message.knowledge_graph.edges`.

In the [example](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/mvp2dEstrogen.json) given by David and the query given by Amy above, they both use `qualifier_constraints` instead of `qualifiers`.  What is the difference between `qualifier_constraints` and `qualifiers`? I'm wondering whether we can add `qualifiied_constraints` into the Edge class. I saw we indeed have [this class](https://github.com/RTXteam/RTX/blob/master/code/UI/OpenAPI/python-flask-server/openapi_server/models/qualifier_constraint.py). Do you just simply add qualifier into the `qualifiers` attribute in the Edge class now?

**Comment by amykglen** [comment]
so the difference is that `qualifier_constraints` belong on `QEdge`s, while `qualifiers` belong on `Edge`s. that is all defined by TRAPI, which you can see the spec for here: 

https://github.com/NCATSTranslator/ReasonerAPI/blob/master/docs/reference.md#edge-

(that explains what `QualifierConstraint` is, and etc.)

**Comment by edeutsch** [comment]
> https://www.ebi.ac.uk/ols/search?q=operation_2423&ontology=edam
> 
> and I think `EDAM` is the correct prefix (though @edeutsch may know better than I)

EDAM:operation_2423 is the correct syntax for such a CURIE, yes. Although I am unclear on what you are trying to convey with the attribute referencing that particular CURIE..

**Comment by chunyuma** [comment]
Thanks everyone! All problems have been resolved. Now the creative mode of xCRG is ready for test in Production. I will close this issue.
