### ISSUE TITLE
Any SemMedDB edges must have PMIDs associated with them

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1965]
Per the Feb. 2023 relay. We should check if this is the case or not for our SemMedDB-derived edges

**Comment by saramsey** [comment]
Thank you for passing the message. This is likely already the case. I have opened [RTX-KG2 issue 258](https://github.com/RTXteam/RTX-KG2/issues/258), that will remind us to check.

**Comment by saramsey** [comment]
So, @acevedol has followed up on this in https://github.com/RTXteam/RTX-KG2/issues/258 

It appears that the answer is "no", we do not have any SemMedDB edges with zero publications, in RTX-KG2.8.1pre.
