### ISSUE TITLE
Edges not showing up in the UI

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1968]
This came up today during the standup. For this PK: https://arax.ncats.io/?r=30fa40cd-e74d-4532-ada1-9914c87db20a
The 4 ARAX results have no edges. However, taking the corresponding ARAX ID: https://arax.ncats.io/?r=129958, the edges do show up. I reckon it's either a UI issue, or else something has gone wrong in parsing ARS results (or feeding them to the ARS).

Tentatively assigning Luis and Eric since it may be front end or middleware related.

**Comment by dkoslicki** [comment]
Looks like it might be a mangled JSON thing, since taking the resulting message's raw JSON: https://arax.ncats.io/api/arax/v1.3/response/043ab683-e12b-4157-980f-f22b792e3d93 and then pasting it in our response viewer, there are still no edges, but this time a lot more nodes

**Comment by edeutsch** [comment]
They have been talking about this for a while and I suspect they have implemented "node normalization" at the ARS. So they are changing out CHEMBL identifiers to PUBCHEM identifiers. But only partially. And ARS is therefore emitting corrupted documents. I don't think this is an ARAX or ARAX GUI issue, but rather an ARS bug that they need to fix.

**Comment by dkoslicki** [comment]
I see; thanks for the perspective! I'll pass that along the chain.

**Comment by edeutsch** [comment]
We think that ARS fixed this problem, so closing.
