### ISSUE TITLE
Answer quality review

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1969]
While testing the results of Chunyu's fix for #1925 (which seem to be working nicely as designed) I decided to examine the current answer quality and ranking for our example query. Here's the latest:
https://arax.ncats.io/devED/?r=130263

The top answer is Desmopressin. hmm.
Expected high answer PTGS1 is eighth.
Why is that?

Although the NGD for PTGS1is substantially better than Desmopressin, Desmopressin appears to win because it seems to have two identical edges pointing in opposite ways. While PTGS1 only has a single edge.

What do we think of this?
I'm thinking two identical edges pointing in opposite directions should not count twice in ranking.

**Comment by dkoslicki** [comment]
Revisiting this one (https://arax.test.transltr.io/?r=247695) it appears that Desmopressin isn't even in the results anymore, and we get things like Cytochrome p450, PTGS1, COX3, etc. Closing for now, but point taken about the multiple edge issue. If/when we get around to modifying the ranker, we can try to keep this in mind
