### ISSUE TITLE
Autocomplete doesn't give node name suggestions

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#197]
eg. "What drugs have similar protein targets to daratumumab" This is a question that hasn't been asked before, and the autocomplete should suggest an autocomplete of the prefix "darat" (it's in ``NodeNamesDescriptions.tsv``.

**Comment by Palzer** [comment]
If I type in "darat" I get daratumumab as a suggestion. Questions don't have {diseases, drugs, proteins} yet as the questions have variables instead of whatever the user wants to reference.

If you can provide that NodeNamesDescriptions.tsv with types then I can tackle this. I'll need the types as I don't want to suggest a {protein, disease} where a drug should go.

**Comment by saramsey** [comment]
yes I think we need to look at inspecting (and if necessary, regenerating) NodeNamesDescriptions.tsv.

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On May 23, 2018, at 7:18 PM, David Koslicki <notifications@github.com<mailto:notifications@github.com>> wrote:


eg. "What drugs have similar protein targets to daratumumab" This is a question that hasn't been asked before, and the autocomplete should suggest an autocomplete of the prefix "darat" (it's in NodeNamesDescriptions.tsv.

**Comment by dkoslicki** [comment]
@Palzer I've added a column of node labels to the ``NodeNamesDescriptions.tsv``, so it's updated on master. (good idea to not suggest a node type that wouldn't work)

**Comment by saramsey** [comment]
OK at least for proteins, this is my bug. It appears that for a protein node (say, P05231), the "name" property in the KG isnt what we would expect/want, which is "interleukin-6". Instead the "name" property contains the gene symbol, IL6 (which is already provided by the "symbol" property). Lemme have a think about how to handle this....

**Comment by dkoslicki** [comment]
Ok, but in the meantime, we can go ahead with incorporating the autocomplete with the gene symbols. I'd really like to have this up and running for the presentation tomorrow evening, so @Palzer can go ahead and work with the current ``NodeNamesDescriptions.tsv`` knowing that this will eventually be updated.

**Comment by Palzer** [comment]
Done.  Autocomplete currently follows a preference in the following order where it moves to the next group if there is no match for the current group. Preferences: common questions, templates, questions relevant {drug, disease, etc}.
