### ISSUE TITLE
Primary knowledge source: deadline 3/24/2023

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1974]
From Tyler on March 7th: of utmost priority (ASAP) is having a `primary_knowledge_source` on _every_ edge which indicates the original data source that provided the assertion leading to the edge. We should check that:

1. All RTX-KG2 edges have this
2. All ARAX virtual edges have this
3. All edges `expand` gets preserves this information

See page 2 of [this](https://docs.google.com/document/d/177sOmjTueIK4XKJ0GjxsARg909CaU71tReIehAp5DDo/edit#heading=h.9mu3cpnwwefy) re: format (basically, infores)

@chunyuma , can you check the xDTD and DTD edges? This is related to #1970. I will have Kevin start on the other edges when he gets onboarded.

**Comment by chunyuma** [comment]
@dkoslicki, it is easy to add `primary_knowledge_source` to all ARAX virtual edges and `expand` edges once we decide what `primary_knowledge_sources` should be. I can work on them because Kevin needs some time to be familiar with the ARAX system but this seems like a top priority for us.  In issue #1970, it seems like `primary_knowledge_sources` is not the same as `knowledge_sources` based on Amy's [comment](https://github.com/RTXteam/RTX/issues/1970#issuecomment-1460837919). Our decision seems like we need a map because KG2 edges are from multiple data sources, and all ARAX `virtual` and `expand` edges are based on KG2 edges. Do I wait for such a map to add `primary_knowledge_source` on ARAX virtual edges and `expand` edges, Or we can add something as `primary_knowledge_source` now?

**Comment by dkoslicki** [comment]
@chunyuma I think for the ARAX virtual edges, we can do the following for the overlays:
NGD: infores:
Jaccard: infores:rtx-kg2
clinical info: infores:cohd
exposures: infores:icees
DTD: infores:arax
xDTD: infores:arax
FET: infores:rtx-kg2

**Comment by dkoslicki** [comment]
Andrew Su shared the authoritative list of infores's: https://github.com/biolink/biolink-model/blob/master/infores_catalog_nodes.tsv
So it looks like NGD should be infores:pubmed

**Comment by edeutsch** [comment]
Who is generating the values? Is it us? I thought we were doing the computation? If the numbers are coming from PubMed, then infores:pubmed is right. But if we're going the calculation, then I think it should be infores:arax

**Comment by chunyuma** [comment]
Temporarily, for each virtual edge, I will do the following:

I add both `knowledge_source`  and `primary_knowledge_source` attributes to them. For `knowledge_source`, I set `value="infores:arax"` and `attribute_source="infores:arax"`. For `primary_knowledge_source`, I assigned the `infores` that @dkoslicki suggested to its value but  `infores:arax` to its attribute_source.

Here is an example:
```
EdgeAttribute(original_attribute_name=None, value="infores:arax", attribute_type_id="biolink:knowledge_source", attribute_source="infores:arax", value_type_id="biolink:InformationResource"),
EdgeAttribute(original_attribute_name=None, value="infores:icees", attribute_type_id="biolink:primary_knowledge_source", attribute_source="infores:arax", value_type_id="biolink:InformationResource")
```
@dkoslicki @edeutsch, please let me know if we should use `infores:arax` as value for NGD.

**Comment by edeutsch** [comment]
I do not really recall exactly where our NGD numbers come from, but if my impression is correct that our own code is taking PubMed citation counts and we are computing the NGD number 0.482 ourselves, then I think `infores:ARAX` is appropriate.

**Comment by dkoslicki** [comment]
Yeah, I was thinking of `primary_knowledge_source` of `pubmed` since we downloaded pubmed and computed the NGD scores ourselves. So while we calculated it, the underlying data source was pubmed. I'm fine with `arax` though

**Comment by chunyuma** [comment]
ok, thanks @edeutsch @dkoslicki. Now we use `infores:arax` as primary_knowledge_source's value for NGD.

**Comment by edeutsch** [comment]
super, thanks!

**Comment by saramsey** [comment]
@acevedol and I are planning a build of KG2.8.2 next week, to address the compliance issues of RTX-KG2 with respect to Biolink (specifically, the non-multivalued `primary_knowledge_source` edge property and the multivalued `provided_by` node property). See [RTX-KG2 issue 263](https://github.com/RTXteam/RTX-KG2/issues/263).

**Comment by amykglen** [comment]
ok, I pushed a couple changes to Expand that make it so that every (TRAPI) KG2 edge now has a `primary_knowledge_source` (which currently contains the value in KG2's `knowledge_source` property)

so we should be considered compliant while we're waiting for a new KG2pre build

**Comment by amykglen** [comment]
hey @chunyuma - thanks for adding `primary_knowledge_source` to Overlay edges! 

I see right now that we have three attributes per NGD edge capturing `infores:arax` as the source. I think the only one we need for NGD edges is the `primary_knowledge_source` one.

![Screen Shot 2023-03-16 at 8 57 15 AM](https://user-images.githubusercontent.com/49423686/225680335-45b625b5-4635-4bff-ad01-ee976547a39a.png)

I don't think it really makes sense to also call ARAX an `aggregator_knowledge_source` in this setting, and calling it a `knowledge_source` is simply redundant with/less specific than calling it a `primary_knowledge_source`.

**Comment by amykglen** [comment]
hmm, for Jaccard, how is it dependent on KG2? I thought that was one that could be applied to any KP's edges, and doesn't rely on KG2? if that's true, I'd think the `primary_knowledge_source` should be `infores:arax`, and there should be no `aggregator_knowledge_source` or `knowledge_source`.

we probably need to work out on a case-by-case basis what makes the most sense for each Overlay sub-module.

**Comment by amykglen** [comment]
maybe it's worth creating a google doc/spreadsheet and laying out what these attributes are for each Overlay sub-module? that would make it easy to review and revise them

**Comment by dkoslicki** [comment]
Even though I implemented it, I apparently had forgotten that I had written 

>This can be applied to an arbitrary knowledge graph as possible edge types are computed dynamically (i.e. not just those created/recognized by the ARA Expander team).

So in that case, yes, I think `primary_knowledge_source` as `infores:arax` makes sense (and remove the `aggregator_knowledge_source` and `knowledge_source`

**Comment by dkoslicki** [comment]
@chunyuma this all looks good save for Jaccard and FET, which should be ARAX instead of rtx-kg2

**Comment by edeutsch** [comment]
So here's what I suggest. First a few comments:

1) I stared at the Biolink association slots for inspiration and came up pretty dry: https://biolink.github.io/biolink-model/docs/association_slot.html

2) By looking at the Biolink YAML more closely I realized that they do EDAM differently than we started doing it (before they even had it?). The YAML defines this:
```
  EDAM-DATA: 'http://edamontology.org/data_'
  EDAM-FORMAT: 'http://edamontology.org/format_'
  EDAM-OPERATION: 'http://edamontology.org/operation_'
  EDAM-TOPIC: 'http://edamontology.org/topic_'
```
Therefore, instead of `EDAM:data_1669`, we should use `EDAM-DATA:1669`. Would you make that change throughout?
So from your spreadsheet:
```
EDAM:data_1669   ==>  EDAM-DATA:1669
EDAM:data_0951    ==> EDAM-DATA:0951
DAM:operation_2423    ==> EDAM-OPERATION:2434
```

3) The for the remaining ones, I stared at the options for a long time, but didn't find anything I liked. but I suggest we just go ahead with this:
```
biolink:computed_value              ==> EDAM-DATA:1772   (Score)
virtual_relation_label  is using biolink:Unknown     ==> EDAM-OPERATION:0226   (Annotation)
```
Although not ideal, I think we are at least compliant.

Sounds good?

did I miss any?

**Comment by amykglen** [comment]
thanks for creating the spreadsheet, @chunyuma!

I think we should get rid of all of the `knowledge_source` == `infores:arax` attributes, and instead always list ARAX either as a `primary_knowledge_source` or `aggregator_knowledge_source`.

also - I think the `provided_by` attributes are quite old/deprecated (this was what we used before `knowledge_source`/`primary_knowledge_source`/`aggregator_knowledge_source` existed) - are those still used for anything, or can we get rid of them?

**Comment by chunyuma** [comment]
Thanks @edeutsch @amykglen @dkoslicki. 
Summarize what I update:
1. I changed the attributes according to Eric's [suggestions](https://github.com/RTXteam/RTX/issues/1974#issuecomment-1473085584).
2. I removed all `knowledge_source` attributes.
3.  Set `provided_by` to None.

**Comment by edeutsch** [comment]
great, thanks!

by "Set provided_by to None" do you mean that there's still a TRAPI attribute but the value is None? Or do you mean that there's no longer a TRAPI attribute of provided_by? I think we want the latter, no attribute like this.

**Comment by chunyuma** [comment]
Hi @edeutsch, the "provided_by" is the value of `original_attribute_name` of `biolink:aggregator_knowledge_source`. 

Here is an example:
```
EdgeAttribute(original_attribute_name="provided_by", value="infores:arax",
                                        attribute_type_id="biolink:aggregator_knowledge_source",
                                        attribute_source="infores:arax", value_type_id="biolink:InformationResource")
```

So What I did is to change `original_attribute_name="provided_by"` to `original_attribute_name=None`. Did I do it correctly?

**Comment by edeutsch** [comment]
oh, I see, I misunderstood. Yes, I think `None` is fine. original_attribute_name does not seem like a relevant property for aggregator_knowledge_source

**Comment by chunyuma** [comment]
Hi @edeutsch, I add a few in all test suites for checking if all edges have 'biolink:primary_knowledge_source'. Now, all test suites pass, indicating all edges should have an attribute 'biolink:primary_knowledge_source'. Thanks!

**Comment by edeutsch** [comment]
great! I have just rolled out `master` to all the usual places, please test!
```
 code/ARAX/ARAXQuery/Expand/DTD_querier.py                  |  2 +-
 code/ARAX/ARAXQuery/Expand/ngd_querier.py                  |  2 +-
 code/ARAX/ARAXQuery/Overlay/add_node_pmids.py              |  2 +-
 code/ARAX/ARAXQuery/Overlay/compute_jaccard.py             |  2 +-
 code/ARAX/ARAXQuery/Overlay/compute_ngd.py                 |  8 ++++----
 code/ARAX/ARAXQuery/Overlay/overlay_clinical_info.py       |  2 +-
 code/ARAX/ARAXQuery/Overlay/overlay_exposures_data.py      |  2 +-
 code/ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py |  5 +++--
 code/ARAX/test/test_ARAX_connect.py                        |  6 ++++--
 code/ARAX/test/test_ARAX_expand.py                         |  4 ++--
 code/ARAX/test/test_ARAX_infer.py                          | 14 ++++++++------
 code/ARAX/test/test_ARAX_overlay.py                        | 73 +++++++++++++++++++++++++++++++++++++++----------------------------------
 code/ARAX/test/test_ARAX_standup_queries.py                |  6 ++++--
 code/ARAX/test/test_ARAX_translate.py                      |  6 ++++--
 code/ARAX/test/test_ARAX_workflows.py                      | 58 ++++++++++++++++++++++++++++++----------------------------
```
