### ISSUE TITLE
NGD predicate for TRAPI 1.3 validation?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1975]
Does anyone (@saramsey, @edeutsch, @amykglen, etc.) know what we should use for the NGD predicate? That's causing our TRAPI 1.3 validator to say we aren't compliant:
```
{
  "errors": {
    "error.query_graph.edge.predicate.unknown": {
      "biolink:has_normalized_google_distance_with": null
    }
  },
  "information": {},
  "warnings": {
    "warning.trapi.response.status.unknown": {
      "OK": null
    }
  }
}
```

**Comment by amykglen** [comment]
is it `biolink:occurs_together_in_literature_with`? (found that [here](https://github.com/RTXteam/RTX/issues/1925#issuecomment-1295408637))

that indeed seems to be a valid predicate in biolink (see [here](https://github.com/biolink/biolink-model/blob/24efce8b69c8210c0d98f30534b7d2736c19a57b/biolink-model.yaml#L3385-L3395))

**Comment by edeutsch** [comment]
agreed. Didn't Chunyu fix this already?
I thought he did. It's possible that this problem is just still showing up in production because we haven't merged into production yet? (but should do so tomorrow)

**Comment by dkoslicki** [comment]
Yeah, I think he did; just waiting to close this issue when it's deployed

**Comment by dkoslicki** [comment]
Checked at arax.ncats.io and arax.rtx.ai, those are using the old predicates. Looks like arax.ncats.io/beta and https://arax.ci.transltr.io/ do have the new predicate. @edeutsch Do you know if/when the first two endpoints will be updated?

**Comment by edeutsch** [comment]
I think the plan is to merge branch `itrb-test` into `production` this week and request a rollout tomorrow, and thus the rollout will happen next Tuesday or so.

@amykglen can you do the same with Plover?

**Comment by amykglen** [comment]
yes, `production` rollouts are complete now... and indeed the proper NGD predicate appears on production now (example: https://arax.ncats.io/?r=132517)

good to close this issue?

**Comment by edeutsch** [comment]
yes, thanks! Closing!
There are still some other validation errors. Are they from other KPs?

**Comment by edeutsch** [comment]
perfect, thanks! Yes, production is still behind for now
