### ISSUE TITLE
Empty 'biolink:publications' attributes on NGD edges causing TRAPI validation errors

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1980]
currently, NGD edges with no publications still have a `biolink:publications` attribute, whose value is an empty list:

![Screen Shot 2023-03-16 at 9 07 13 AM](https://user-images.githubusercontent.com/49423686/225682629-22f485c6-256c-4711-bfec-e992f751b466.png)

(above example is from: https://arax.ncats.io/beta/api/arax/v1.3/response/131259)

this is causing TRAPI validation errors (reported by @edeutsch in #1978), because `Attribute.value` is not allowed to be empty. 

**can we just not append any `biolink:publications` attribute to NGD edges that have 0 publications?**

(not sure who is best to assign; starting with @chunyuma, but please reassign as you see fit)

**Comment by chunyuma** [comment]
@amykglen, thanks for letting me know this bug. I've fixed this bug. Please check it.
