### ISSUE TITLE
Overlay's 'biolink:computed_value' attribute_type_id doesn't exist in Biolink

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1981]
this was originally reported in #1978

the TRAPI validator doesn't like our `biolink:computed_value` attributes (added by Overlay), I believe because that isn't an actual thing in the Biolink model (I think we made it up, figuring we'd request it be added to Biolink at some point?)

![Screen Shot 2023-03-16 at 9 22 36 AM](https://user-images.githubusercontent.com/49423686/225686188-32e04ba4-afc8-4766-add6-064786193010.png)

(example edges in: https://arax.ncats.io/beta/api/arax/v1.3/response/131259)

I think for the validator to be happy, we need an `attribute_type_id` here that actually exists in Biolink... I'm not aware of any equivalents in Biolink currently? (I could've missed them though...) is our best approach to request that `biolink:computed_value` is added to Biolink?

(not sure who is best to assign; starting with @chunyuma, but please reassign as you see fit)

**Comment by chunyuma** [comment]
I give a spreadsheet on issue #1974. Previously Finn or David probably use this attribute to distinguish the virtual edge and the real edge. I let @dkoslicki help me go through the spreadsheet to see what attribute should be kept and what should be removed. After that, I will fix this issue.

**Comment by edeutsch** [comment]
See https://github.com/RTXteam/RTX/issues/1974#issuecomment-1473085584
I suggest EDAM-DATA:1772

**Comment by chunyuma** [comment]
I updated it. See #1974. Thanks @edeutsch.

**Comment by chunyuma** [comment]
It was fixed in the production. So I close it.
