### ISSUE TITLE
P-values for LilGim?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#199]
Does Lil'Gim also provide p-values for the correlations? I was under the impression that BigGim did...

**Comment by saramsey** [comment]
I don't think LilGIM provides them. Here is the result data I am seeing from LilGIM:
![screen shot 2018-05-23 at 7 25 37 pm](https://user-images.githubusercontent.com/5562107/40462274-25a2e48c-5ec4-11e8-9882-f3c5c5bfd53d.png)

**Comment by saramsey** [comment]
I've asked @tknijnen about this
