### ISSUE TITLE
Rho related protein racE conflated with the term "Race"

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1994]
See 
https://github.com/NCATSTranslator/Feedback/issues/111

**Comment by amykglen** [comment]
ok, this conflation no longer appears in the latest version of the new synonymizer (#2003):

Cluster for UMLS:C3853635 has 6 nodes:

| id               | category                        | name   | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:-----------------|:--------------------------------|:-------|:---------|:------------|:-----------------|
| LOINC:LP71009-2  | PopulationOfIndividualOrganisms | Race   |          | X           |                  |
| LOINC:LP7528-5   | PopulationOfIndividualOrganisms | Race   |          | X           |                  |
| LOINC:MTHU009923 | PopulationOfIndividualOrganisms | Race   |          | X           |                  |
| LOINC:MTHU051585 | PopulationOfIndividualOrganisms | Race   |          | X           |                  |
| NCIT:C17049      | PopulationOfIndividualOrganisms | Race   |          | X           |                  |
| UMLS:C3853635    | PopulationOfIndividualOrganisms | Race   | X        | X           | X                |

Cluster for PR:Q23862 (NCBIGene:8623000) has 4 nodes:

| id                     | category   | name                                                | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:-----------------------|:-----------|:----------------------------------------------------|:---------|:------------|:-----------------|
| NCBIGene:8623000       | Gene       | racE                                                | X        |             | X                |
| PR:Q23862              | Protein    | Rho-related protein racE (Dictyostelium discoideum) | X        | X           |                  |
| UniProtKB:Q23862       | Protein    | RACE_DICDI Rho-related protein racE (sprot)         | X        |             |                  |
| dictyBase:DDB_G0280975 | Gene       |                                                     | X        |             |                  |

**Comment by amykglen** [comment]
confirmed fixed on test: https://arax.ncats.io/test/?term=NCBIGene:8623000

and I posted a comment on https://github.com/NCATSTranslator/Feedback/issues/111 letting them know
