### ISSUE TITLE
Geneprof 500 response

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#2]
_From @erikyao on January 12, 2018 18:59_

When running `test_geneprof_id_to_transcription_factor_gene_symbols` of `tests/QueryGeneProfTestCase`, `QueryGeneProf.geneprof_id_to_transcription_factor_gene_symbols` sometimes returns an empty set due to Genprof's 500 response.

Test code:

```python
ret_set = QueryGeneProf.geneprof_id_to_transcription_factor_gene_symbols(16269)  # 'HMOX1'
```

Debugging message:

> HTTP response status code: 500 for URL:
http://www.geneprof.org/GeneProf/api/gene.info/regulation/binary/by.target/human/16269.json?with-sample-info=true

Cause of 500 reported by Geneprof:

> java.lang.OutOfMemoryError: unable to create new native thread

We may need to add exception-handling code in this case.

_Copied from original issue: dkoslicki/NCATS#134_

**Comment by saramsey** [comment]
GeneProf is currently down and the maintainers haven't yet responded to email.  Thoughts?

**Comment by dkoslicki** [comment]
Geesh! They're still down! Cross our fingers and hope?

**Comment by dkoslicki** [comment]
@saramsey Is this still relevant?

**Comment by dkoslicki** [comment]
Close due to #788
