### ISSUE TITLE
protein names in the KG should be the actual *names* not the gene symbols

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#200]

**Comment by saramsey** [comment]
@DeqingQu can you add a feature to the UpdateNodesInfo.py script that does the following additional work:

    for each protein node in the Knowledge Graph, get the UniProt accession number of that protein node (like "P05231"):
        query MyGene to get the MyGene "name" field of the protein, like this:  real_name = mgo.query("uniprot:P05231")["hits"][0]["name"]
        update the "name" property of the node for that protein in the Knowledge Graph, to put the "real_name" string in it (so for this example, the "name" property would get changed from its default string of "IL6", to the correct string "interleukin 6")

**Comment by saramsey** [comment]
or maybe you could do this by changing UpdateNodesName.py, actually

**Comment by DeqingQu** [comment]
@saramsey You can run 'python3 [rtx-repo]/code/reasoningtool/kg-construction/UpdateNodesName.py' to update all protein names.
