### ISSUE TITLE
Ready to merge master into itrb-test?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2000]
We need to button up master, merge into itrb-test, and notify NCATS/ITRB that we wish to deploy to TEST today

1) Anything else needing to go into master?

2) Please do a little testing in /test and /beta and in your own master so we don't merge any obvious problems into test.

I am planning on merging into itrb-test this afternoon

Let me know what you think.

**Comment by amykglen** [comment]
sounds good to me! just did some testing on /beta and don't see any issues. amazing how much #1998 sped up ARAX and KG2... 🎉

**Comment by amykglen** [comment]
actually - hold on, I'm seeing semmeddb edges from KG2 KP that are missing publications - I think maybe edge decoration isn't happening as it should...

**Comment by amykglen** [comment]
ok, I just fixed that issue. that was a pretty big bug, actually - I don't think any KG2 edges were being decorated with EPC since the rollout of KG2.8.0 (they only had their `primary_knowledge_source`, and no other attributes..). I added a pytest that should catch this in the future

**Comment by edeutsch** [comment]
oh great, okay, I have deploy master to the usual places. Good now?

**Comment by amykglen** [comment]
thanks - yes, looks good now

**Comment by edeutsch** [comment]
I have pushed master to itrb-test
@amykglen would you push plover to itrb-test? 
or no changes there?

**Comment by amykglen** [comment]
no changes to Plover this time - it doesn't need to be redeployed or anything

**Comment by edeutsch** [comment]
all taken care of. closing.
