### ISSUE TITLE
Improve node synonymizer (reduce conflations)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2003]
finally creating an issue for this... right now work is in a private repo but I'll soon copy it over... (into a branch, to start)

**Comment by amykglen** [comment]
I noticed yesterday that, strangely, the SRI NodeNormalizer dump seems to only include Genes and Proteins... I'm assuming that's not intentional. I wrote up the issue in https://github.com/TranslatorSRI/NodeNormalization/issues/185

hopefully that is resolved soon. as backup I could revert back to a querying-their-API-for-all-KG2-nodes approach, but would rather not do that...

**Comment by amykglen** [comment]
a note for the record: for now we are using **both** the SRI NodeNormalizer's bulk download and their RestAPI because the bulk download doesn't currently include any indication of the "preferred" identifier for each cluster (and their RestAPI only provides expanded categories, and doesn't provide actual `same_as` edges)

but I requested that they add preferred identifiers to their bulk download: https://github.com/TranslatorSRI/NodeNormalization/issues/187

which, if they implement, will mean we can stop querying their RestAPI

**Comment by amykglen** [comment]
ok, I think we're at a point where we have something that is better than our current synonymizer. I'm still spot-checking clusters, but known 'problem' clusters appear fixed so far (I'll post on the issues for each of those). 

here's acetaminophen:

| id                                   | category       | name                     | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:-------------------------------------|:---------------|:-------------------------|:---------|:------------|:-----------------|
| ATC:N02BE01                          | ChemicalEntity | paracetamol              |          | X           |                  |
| CAS:103-90-2                         | SmallMolecule  |                          | X        |             |                  |
| CHEBI:46195                          | SmallMolecule  | paracetamol              | X        | X           |                  |
| CHEMBL.COMPOUND:CHEMBL112            | SmallMolecule  | ACETAMINOPHEN            | X        | X           |                  |
| DRUGBANK:DB00316                     | SmallMolecule  | Acetaminophen            | X        | X           |                  |
| DrugCentral:52                       | SmallMolecule  | paracetamol              | X        | X           |                  |
| GTOPDB:5239                          | SmallMolecule  | paracetamol              | X        |             |                  |
| HMDB:HMDB0001859                     | SmallMolecule  | Acetaminophen            | X        | X           |                  |
| INCHIKEY:RZVAJINKPMORJF-UHFFFAOYSA-N | SmallMolecule  |                          | X        |             |                  |
| KEGG.COMPOUND:C06804                 | SmallMolecule  | Acetaminophen            | X        | X           |                  |
| KEGG.DRUG:D00217                     | Drug           |                          |          | X           |                  |
| LOINC:LP14712-1                      | ChemicalEntity | Acetaminophen            |          | X           |                  |
| LOINC:MTHU003399                     | ChemicalEntity | Acetaminophen            |          | X           |                  |
| MESH:D000082                         | SmallMolecule  | Acetaminophen            | X        | X           |                  |
| NCIT:C198                            | Drug           | Acetaminophen            |          | X           |                  |
| NDDF:001605                          | ChemicalEntity | acetaminophen            |          | X           |                  |
| PDQ:CDR0000039129                    | ChemicalEntity | acetaminophen            |          | X           |                  |
| PUBCHEM.COMPOUND:1983                | SmallMolecule  | Acetaminophen            | X        |             | X                |
| PathWhiz.Compound:1233               | SmallMolecule  | Acetaminophen            |          | X           |                  |
| RXNORM:161                           | Drug           | acetaminophen            |          | X           |                  |
| UMLS:C0000970                        | SmallMolecule  | acetaminophen            | X        | X           |                  |
| UMLS:C1258986                        | SmallMolecule  | p-hydroxyphenolacetamide | X        | X           |                  |
| UNII:362O9ITL9D                      | SmallMolecule  | ACETAMINOPHEN            | X        |             |                  |
| VANDF:4017513                        | ChemicalEntity | Acetaminophen            |          | X           |                  |

as a summary, this synonymizer was built using these rules:
* nodes that are recognized by the SRI NodeNormalizer are **never** re-clustered, and they always have the SRI NN's 'preferred' identifier
    - the only nodes that are clustered during the synonymizer build are nodes from KG2pre that are not recognized by the SRI NN; they might be assigned to existing SRI NN clusters, or they could form new clusters
* nodes with categories from different 'major branches' of the Biolink tree (with some light heuristics/modifications employed here) cannot be in the same cluster
    - because nodes labeled NamedThing don't really belong to a branch, they can only be clustered with each other
    - same with BiologicalEntity nodes (they can only be clustered with each other), because we don't consider BiologicalEntity a 'major branch', since it's so broad (has gene/protein-like things, disease-like things, etc.)
* when name or category for an identifier differ in the SRI NN vs. KG2pre, we default to the SRI NN's data

(note: many of these rules are rather crude, but were a 'quick and dirty' way to get something better than what we have)

my next steps are to hook this thing up to our existing NodeSynonymizer interface; the data is stored in sqlite, and I think indexed appropriately already, but its structure is a little different than the existing `node_synonymizer.sqlite`, so I'll need to tweak `node_synonymizer.py`.

(all work on this issue is in the branch called `synonymize` - all the build code is in `RTX/code/kg2c/synonymizer_build`)

**Comment by amykglen** [comment]
so the new synonymizer is ready and tested, but rolling it out requires a rebuild of KG2c. which in turns requires rebuilding other databases, like DTD.

I could do this off of KG2.8.0pre, but since it sounds like KG2.8.2c is getting close, maybe we should do it with that?

@sundareswarpullela @acevedol - after the code changes are finished for KG2.8.2c (#2010), can you let me know and we can then merge our branches and run the full KG2c build from there?

**Comment by sundareswarpullela** [comment]
Hey @amykglen, that sounds doable. The code changes will be validated over the weekend and we can merge the branches and run the full build.

**Comment by amykglen** [comment]
perfect! ok, just let me know when the validation is done, @sundareswarpullela. thanks!
