### ISSUE TITLE
ARAX crashing with SmartAPI error

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2007]
Would someone look into this soon? Monitoring system shows watchdog query is failing every hour. ARAX is probably almost completely inop at this point. I suspect a change somewhere in SmartAPI now causes this crash on every query:

      "message": "An uncaught error occurred: string indices must be integers: ['Traceback (most recent call last):\\n', '  File
\"/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQue
ry/ARAX_query.py\", line 742, in execute_processing_plan\\n    expander.apply(response, action[\\'parameters\\'], mode=mode)\\n',
 '  File \"/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARA
X/ARAXQuery/ARAX_expander.py\", line 187, in apply\\n    kp_selector = KPSelector(kg2_mode=True, log=log) if mode == \"RTXKG2\" e
lse KPSelector(log=log)\\n', '  File \"/mnt/data/orangeboard/production/RTX/code/ARAX/ARAXQuery/Expand/kp_selector.py\", line 33,
 in __init__\\n    self.kp_urls, self.kps_excluded_by_version, self.kps_excluded_by_maturity = self.get_all_kps()\\n', '  File \"
/mnt/data/orangeboard/production/RTX/code/ARAX/ARAXQuery/Expand/kp_selector.py\", line 51, in get_all_kps\\n    kp_info = smartap
i.get_kps(version=minor_version,req_maturity=maturity)\\n', '  File \"/mnt/data/orangeboard/production/RTX/code/ARAX/ARAXQuery/Ex
pand/smartapi.py\", line 235, in get_kps\\n    endpoints = self.get_trapi_endpoints(version=version, whitelist=whitelist, blackli
st=blacklist)\\n', '  File \"/mnt/data/orangeboard/production/RTX/code/ARAX/ARAXQuery/Expand/smartapi.py\", line 79, in get_trapi
_endpoints\\n    url = hit[\"servers\"][0][\"url\"]\\n', 'TypeError: string indices must be integers\\n']",

**Comment by amykglen** [comment]
I think I just pushed a fix for this; indeed the format/structure of SmartAPI's JSON response seems to have been tweaked. I doubt _all_ of the methods in our `smart_api.py` are working right now, but the one that ARAX uses at runtime should be...

**Comment by amykglen** [comment]
uhh, actually I'm still seeing failing tests locally, maybe there's another issue to fix too... looking into it

**Comment by amykglen** [comment]
hmm, well those tests are magically ok now. maybe smartAPI was temporarily down when I tested the fix a few minutes ago... (it was giving connection errors)

so I think rolling `master` out should fix the issue

**Comment by edeutsch** [comment]
Sure, I can do that. Will the new code work with either the new way or the old way?

I think it is probably true that our itrb-test and production code will suffer the same problem and we cannot fix that quickly? Is it true that our production servers are broken now too?

I am wondering if we should post/describe the issue in detail in official channels to say that ARAX is broken because SmartAPI changed its format?

**Comment by amykglen** [comment]
new code only handles the new format at this point. I opted for a quick fix...

but you're right all of our ARAX endpoints are broken, including ITRB production, which we can't fix quickly.

yeah, we probably should report this and confirm whether this is permanent. I can do that... in the Translator slack I suppose?

**Comment by amykglen** [comment]
great - I also just pushed a change to master that makes `smartapi.py` work with either the old or new format. 

I'm very confused because, currently, when I go to this URL, which smartapi.py uses, it's showing the old format: https://smart-api.info/api/query?limit=1000&q=TRAPI

(where `components` and `servers` are not nested under `_source` for each hit...)

yet our fix that expects the new format is working (prior to me making it backwards-compatible)? super strange..

**Comment by edeutsch** [comment]
could there be some caching? or is caching turned off?

**Comment by edeutsch** [comment]
okay, `master` is deployed in all the usual placed just now.

**Comment by edeutsch** [comment]
This issue to resolved for the moment because SmartAPI folks also noticed the issue and rolled back while they investigate. They are also puzzled.

**Comment by edeutsch** [comment]
From ars channel: 
![image](https://user-images.githubusercontent.com/12707718/232261342-cac5dc0c-2ce4-4c2c-a35c-1975c71db571.png)
