### ISSUE TITLE
Work with SRI to add missing KG2 nodes to SRI Node Normalizer

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2013]
on the TAQA call today, Tyler, Chris B., and Will B. were all very interested in adding our ~20% of KG2 nodes that are currently unrecognized by the SRI NodeNormalizer to the SRI NodeNormalizer so that other teams who might use those missing curies could benefit as well

this was the issue this came up in: https://github.com/NCATSTranslator/Feedback/issues/172

I wonder if providing the SRI with our mappings (node ID --> cluster ID) for those nodes might be helpful? or perhaps a full table of those nodes... (with node ID, cluster ID, name, category). If they incorporated that data that would create a bit of a circular dependency though, in that our assignment of those nodes to clusters depends on the SRI's assignment of other nodes to clusters... but I suppose it's only one loop around the circle. :) 

or maybe they simply want us to report which nodes are unrecognized and they will figure out clustering themselves. we should probably discuss with SRI

**Comment by saramsey** [comment]
I suppose they might be interested in the CURIE to cluster associations. Thanks for bringing this to my attention. Once we know exactly what they want, can we give them a Cypher command and a login so they can get the latest info, any time they need it?

**Comment by amykglen** [comment]
that's true, that's low-effort on our end. I'll be finding out exactly what they want next week

**Comment by amykglen** [comment]
I met with Chris B. and Gaurav a couple weeks ago and we decided that the easiest option was to give them one of our TSV artifacts from the synonymizer build. I shared this with them by uploading it to the Translator Git LFS repo (https://github.com/ncats/translator-lfs-artifacts/blob/main/files/kg2.8.0.1_nodes_not_in_sri_nn.tsv.gz) and added a step to our KG2c rollout issue template to remind us to do so for each build
