### ISSUE TITLE
Need `lookup` too whenever `inferred` is asked for

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#2022]
See:
https://github.com/NCATSTranslator/TranslatorArchitecture/pull/88

I imagine we can just tack on `lookup` results from `expand` after calling xDTD.

@chunyuma can you assist @kvnthomas98 (if he needs help navigating your xDTD code)?

@kvnthomas98 This can be next on your priority list after you're finished with your current task. This should be done in a different branch as we'll need to make sure this is TRAPI 1.4 _and_ incorporate any other changes specified in [that PR](https://github.com/NCATSTranslator/TranslatorArchitecture/pull/88) or the surrounding [discussion](https://docs.google.com/document/d/16agzJB0OlR8z-zU3nTivYYIo09sdayN-tu8lbrZyTXY/edit?usp=sharing).

**Comment by chunyuma** [comment]
Hi @dkoslicki, sorry for the late reply. Sure, @kvnthomas98, please just slack me if you need any help from me.

**Comment by dkoslicki** [comment]
Any status update on this @kvnthomas98 ?

**Comment by edeutsch** [comment]
What's the state of this effort? Seems like we ought to get this going as soon as we can. Should we prioritize this for the next week so that @amykglen can still advise/help?

**Comment by dkoslicki** [comment]
I'm meeting with @kvnthomas98 and @chunyuma on Friday at 10am EDT to discuss this and #1961 as those are both the priority: likely #2022 and then #1961.
It would be great to get @amykglen's input as how best to engineer this.

**Comment by edeutsch** [comment]
Maybe if XDTD/XCRG behaved like ordinary KPs, Expander wouldn't need to make any special decisions, but rather just try to answer the query by passing along the query_graphs and this would naturally combine lookup and inferred together simply based on the the merging of results from all KPs (including XDTD/XCRG)

**Comment by amykglen** [comment]
yeah, I like your thinking - that's basically what David and I landed on yesterday. there's a mechanism in Expand to handle 'local' KPs (like the original DTD) that we were thinking of using. though it'd be even easier from the Expand end if XDTD/XCRG were registered web services in SmartAPI!

**Comment by saramsey** [comment]
As discussed in the AHM on 6/28, @sundareswarpullela will be moving this issue forward for the time being.

**Comment by dkoslicki** [comment]
@kvnthomas98 Any update on this issue?

**Comment by kvnthomas98** [comment]
Hi All,

This is being worked on branch [issue2022](https://github.com/RTXteam/RTX/tree/issue2022).

As discussed with @dkoslicki for scoring of the merged results. Inferred results will be scored with the probabilities returned from the creative model

**Comment by kvnthomas98** [comment]
Changes are pushed to master and deployed

**Comment by edeutsch** [comment]
When I run the old system under production with the "Example 2" JSON query
![image](https://github.com/RTXteam/RTX/assets/12707718/b120b4ec-f76a-4282-bfbe-0b53b5bec8d5)
I get 45 results:
![image](https://github.com/RTXteam/RTX/assets/12707718/4561c7b9-185a-44ae-87b2-24a7f512f024)
https://arax.transltr.io/?r=158533

When I run the new code under beta with the "Example 2" JSON query, I get 266 results:
![image](https://github.com/RTXteam/RTX/assets/12707718/fd4519c0-43e4-44da-99cd-12bd0cf021dd)
https://arax.ncats.io/beta/?r=158535

Clearly quite different.
Looking at Prednisone, the new code has lots of "[sg]" edges while the old has one. That's a bit strange.
All the support graphs appear to be the same to the casual observer.

I also see this, which is a little concerning:
![image](https://github.com/RTXteam/RTX/assets/12707718/015f3ab8-1c8a-4dea-bd0e-08899a0e007e)

I'm a little concerned it may not be working quite right, but I'm not certain.

**Comment by dkoslicki** [comment]
@edeutsch I'm only seeing the [sg] edges in the first link not the second one. So was it the old code or the new code that's returning those edges?

**Comment by dkoslicki** [comment]
And in either case, the only place in the code base I find that text is at the UI level: https://github.com/search?q=repo%3ARTXteam%2FRTX%20%5Bsg%5D&type=code

**Comment by dkoslicki** [comment]
I'm fairly certain that the `[sg]` is only part of the UI: it only shows up in the code base in `rtx.js`, and not in the actual TRAPI response: https://arax.ncats.io/beta/api/arax/v1.4/response/158535

**Comment by dkoslicki** [comment]
From @isbluis : the `[sg]` indicates that there is a support graph associated with that edge and is indeed just a UI thing

**Comment by edeutsch** [comment]
> Looking at Prednisone, the new code has lots of "[sg]" edges while the old has one. That's a bit strange.

My point was that instead of ONE inferred edge, there are now SEVEN apparently identical ones. They all have sg, yes, but that's fine.

**Comment by kvnthomas98** [comment]
Hi @edeutsch , Thanks for pointing this out. The reason the multiple edges had [sg] was because the support graph of the inferred edge was being added to even the lookup edges. I've committed the fix to master, on deployment now, we shouldn't have the support graph being added to the lookup edges now.

**Comment by saramsey** [comment]
Great, this commit (185a7a5) should have gone out to most of the servers today, and will go out (I hope) to ITRB TEST tomorrow.

**Comment by kvnthomas98** [comment]
On https://arax.ncats.io/beta/?r=159380 now

<img width="1021" alt="image" src="https://github.com/RTXteam/RTX/assets/17030839/14454ada-ba8f-460e-b5ea-72bd803408b4">

**Comment by kvnthomas98** [comment]
It looks to be pushed through to ITRB Test and I can see the merged results there. Are we good to close?

**Comment by saramsey** [comment]
@kvnthomas98 thank you for this update. Would you mind also doing the same check on the ITRB production ARAX service, i.e., `arax.transltr.io`?  If it is working there, I think we can close.

**Comment by kvnthomas98** [comment]
Sorry for the late response @saramsey . It is working on `arax.transltr.io`

**Comment by saramsey** [comment]
Thank you @kvnthomas98. In that case, can we close out this issue?

**Comment by kvnthomas98** [comment]
I think so. Thanks everyone
