### ISSUE TITLE
XDTD KG2 edges have incorrect sources

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2033]
for an example, go to this response: https://arax.ncats.io/NewFmt/?r=138478

then in the first Result, click on Support Graph 1. 

clicking on pretty much any edge in that Support Graph should give an example of what I'm referring to. 

here's an example edge:

<img width="811" alt="Screen Shot 2023-05-17 at 5 14 01 PM" src="https://github.com/RTXteam/RTX/assets/49423686/049fb10d-8f72-4451-b389-7d3122b0ee82">

for this example, the **Edge.sources should instead look like this**:

```
  'sources': [{'resource_id': 'infores:dgidb',
               'resource_role': 'primary_knowledge_source'},
              {'resource_id': 'infores:rtx-kg2',
               'resource_role': 'aggregator_knowledge_source',
               'upstream_resource_ids': ['infores:dgidb']},
              {'resource_id': 'infores:arax',
               'resource_role': 'aggregator_knowledge_source',
               'upstream_resource_ids': ['infores:rtx-kg2']}]
```

please push code changes to `master` for this issue (after testing)

**Comment by edeutsch** [comment]
The general rule is that the primary_knowledge_source MUST NOT have an upstream_resource_ids, and there SHOULD only be one primary_knowledge_source. And all other sources MUST have at least one upstream_resource_ids.

**Comment by chunyuma** [comment]
Thanks @amykglen and @edeutsch. I've added xDTD KG2 edge sources based on TRAPI 1.4 format.  And all its associated tests pass as well.

@amykglen, I found that after using TRAPI 1.4, some test_xcrg_* tests in `test_ARAX_infer.py` fail. 

Here is an example:
```
query = {"operations": {"actions": [
        "create_message",
        "infer(action=chemical_gene_regulation_graph_expansion, subject_curie=CHEMBL.COMPOUND:CHEMBL1097205, regulation_type=increase, threshold=0.6, path_len=2, n_result_curies=1, n_paths=1)",
        "return(message=true, store=true)"
]}}
``` 

When I ran this query, I got the error: 
```
ERROR: [NoOriginalQG] The original QG was never saved before ARAX edited it! So we can't transform results to TRAPI 1.4 format (i.e., support_graphs).
```

Could you please help me figure out the reason? Thanks!

**Comment by isbluis** [comment]
Hi all,
Currently the ARAX UI flags (in angry red! as seen above) when `upstream_resource_ids` is empty/null _unless_ `resource_role` is `biolink:primary_knowledge_source`.

Is the "biolink:" prefix not required?  Or is it missing from the Edge.sources given above?  Should the (ARAX) UI care?

**Comment by amykglen** [comment]
@chunyuma - I'll take a look at that NoOriginalQG error. thanks for reporting!

**Comment by edeutsch** [comment]
> @isbluis - we're specifically _not_ supposed to use a biolink prefix on resource roles, per Sierra and others in Slack. we had been using a prefix but just fixed that yesterday...

ideally the GUI would flag in angry red if the biolink prefix *IS* there (in this context only; other contexts do require biolink prefix)

**Comment by amykglen** [comment]
confirmed this appears fixed on /test! https://arax.ncats.io/test/?r=139996
