### ISSUE TITLE
XCRG not always working with ResultTransformer

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2034]
@chunyuma reported this problem in #2033:

> @amykglen, I found that after using TRAPI 1.4, some test_xcrg_* tests in `test_ARAX_infer.py` fail. 
> 
> Here is an example:
> ```
> query = {"operations": {"actions": [
>         "create_message",
>         "infer(action=chemical_gene_regulation_graph_expansion, subject_curie=CHEMBL.COMPOUND:CHEMBL1097205, regulation_type=increase, threshold=0.6, path_len=2, n_result_curies=1, n_paths=1)",
>         "return(message=true, store=true)"
> ]}}
> ``` 
> 
> When I ran this query, I got the error: 
> ```
> ERROR: [NoOriginalQG] The original QG was never saved before ARAX edited it! So we can't transform results to TRAPI 1.4 format (i.e., support_graphs).
> ```

**Comment by chunyuma** [comment]
Hi @amykglen, I think I fixed this bug now. So I close this issue.
