### ISSUE TITLE
Move KG2 path support_graphs for inferred queries onto Edges

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2035]
discussion/decision on this happened in slack: https://araxteam.slack.com/archives/C023JNE4VS5/p1684454016710589

started in this issue: https://github.com/NCATSTranslator/ReasonerAPI/issues/434

right now supporting KG2 edges for creative/XDTD queries are stored in Analysis.support_graphs (on Results), but really those support graphs belong on Edges, since they're helping to justify the existence of an edge.

all other 'virtual' edges (like NGD) should remain on Results though... 

this should just be a matter of updating ResultTransformer...

this example shows format for how support graphs should be stored on Edges (in an Attribute): https://github.com/uhbrar/ReasonerAPI/blob/update_guide/MigrationAndImplementationGuide1-4.md#trapi-14-example-message

**Comment by edeutsch** [comment]
@amykglen is this something you could change fairly soon? The UI is asking

**Comment by amykglen** [comment]
yes - I'll try to do it this weekend

**Comment by edeutsch** [comment]
super, thanks!

**Comment by edeutsch** [comment]
It would be really beneficial to have this deployed before the Relay

**Comment by amykglen** [comment]
yes - ran out of time over the weekend. but giving it a go now from the plane!

**Comment by edeutsch** [comment]
oh sorry, I completely forgot you were on vacation this week!

**Comment by amykglen** [comment]
ok, just pushed this to `master` - the pytest suite passed for me with these changes, but should verify it looks good once it's rolled out to one of our UIs as well

right now it relies on the fact that inferred queries' `option_group_id`s start with "creative_DTD_" or "creative_CRG_" to identify which 'virtual' edges belong on Edges vs. Results...

**Comment by edeutsch** [comment]
Outstanding, thanks!
I rolled out to /devED, /devLM, and /test (not /beta)
And it seems to work superficially. The GUI still needs a bit more work to display it.
https://arax.ncats.io/test/?r=140532

thank you!

**Comment by edeutsch** [comment]
looks great, thanks, closing!
