### ISSUE TITLE
Database manager sometimes creates empty files instead of symlinks

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2040]
when rolling out new databases to arax.ncats.io, sometimes the database manager creates a 0 length file instead of a symlink for a new database

if you then delete that 0 length file and rerun the database manager, it creates the symlink normally

**Comment by amykglen** [comment]
this might only happen for the node synonymizer sqlite - think we've only seen it with that database?

one thing to check on might be whether it happens if an `/entity` query is run prior to the database manager being run?

(this is low priority though - not a blocker)

**Comment by edeutsch** [comment]
I added code to check for this problem and resolve it, I hope
