### ISSUE TITLE
Update synonyms tab in UI for new synonymizer data format

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2042]
@isbluis - with the new synonymizer (now in `master`), the output data format for `node_synonymizer.get_normalizer_results()` has changed a bit

the 'Synonyms' tab in the UI isn't angry about it, but there's some new info not currently being displayed that would be nice to show

specifically, in the 'Nodes' table (like in below screenshot), could we:
1. get rid of the `original_label` column (that field is always null now)
2. add "In KG2pre" and "In SRI NodeNormalizer" columns that show True/False (or even better - a checkmark when true, blank when false?) - these would correspond to the "in_kg2pre" and "in_sri" properties on nodes
3. possibly add columns for KG2pre name, SRI name, KG2pre category, and SRI category? that might be too much to fit, but it's helpful for debugging to see where different names/categories came from... 

![Screen Shot 2023-05-24 at 3 17 30 PM](https://github.com/RTXteam/RTX/assets/49423686/64a0e812-e33a-4429-a3f2-dbdcb16b8de4)

this is an example of what the data for a concept looks like now:
```
{
  "PTGS1": {
    "id": {
      "identifier": "NCBIGene:5742",
      "name": "PTGS1",
      "category": "biolink:Gene",
      "SRI_normalizer_name": "PTGS1",
      "SRI_normalizer_category": "biolink:Gene",
      "SRI_normalizer_curie": "NCBIGene:5742"
    },
    "categories": {
      "biolink:Gene": 7,
      "biolink:Protein": 8
    },
    "nodes": [
      {
        "identifier": "NCBIGene:5742",
        "category": "biolink:Gene",
        "label": "PTGS1",
        "major_branch": "GeneticOrMolecularBiologicalEntity",
        "in_sri": true,
        "name_sri": "PTGS1",
        "category_sri": "biolink:Gene",
        "in_kg2pre": true,
        "name_kg2pre": "PTGS1",
        "category_kg2pre": "biolink:Gene"
      },
      {
        "identifier": "ENSEMBL:ENSG00000095303",
        "category": "biolink:Gene",
        "label": "PTGS1",
        "major_branch": "GeneticOrMolecularBiologicalEntity",
        "in_sri": true,
        "name_sri": null,
        "category_sri": "biolink:Gene",
        "in_kg2pre": true,
        "name_kg2pre": "PTGS1",
        "category_kg2pre": "biolink:Gene"
      },
      {
        "identifier": "HGNC:9604",
        "category": "biolink:Gene",
        "label": "PTGS1",
        "major_branch": "GeneticOrMolecularBiologicalEntity",
        "in_sri": true,
        "name_sri": "PTGS1",
        "category_sri": "biolink:Gene",
        "in_kg2pre": true,
        "name_kg2pre": "PTGS1 (human)",
        "category_kg2pre": "biolink:Gene"
      },
      {
        "identifier": "OMIM:176805",
        "category": "biolink:Gene",
        "label": "PTGS1",
        "major_branch": "GeneticOrMolecularBiologicalEntity",
        "in_sri": true,
        "name_sri": null,
        "category_sri": "biolink:Gene",
        "in_kg2pre": true,
        "name_kg2pre": "PTGS1",
        "category_kg2pre": "biolink:Gene"
      },
      {
        "identifier": "UMLS:C1335271",
        "category": "biolink:Gene",
        "label": "PTGS1 gene",
        "major_branch": "GeneticOrMolecularBiologicalEntity",
        "in_sri": true,
        "name_sri": "PTGS1 gene",
        "category_sri": "biolink:Gene",
        "in_kg2pre": true,
        "name_kg2pre": "PTGS1 gene",
        "category_kg2pre": "biolink:BiologicalEntity"
      },
      {
        "identifier": "UMLS:C5574837",
        "category": "biolink:Protein",
        "label": "Cyclooxygenase 3, human",
        "major_branch": "GeneticOrMolecularBiologicalEntity",
        "in_sri": true,
        "name_sri": "Cyclooxygenase 3, human",
        "category_sri": "biolink:Protein",
        "in_kg2pre": false,
        "name_kg2pre": null,
        "category_kg2pre": null
      },
      {
        "identifier": "UniProtKB:A0A087X296",
        "category": "biolink:Protein",
        "label": "A0A087X296_HUMAN Prostaglandin G/H synthase 1 (trembl)",
        "major_branch": "GeneticOrMolecularBiologicalEntity",
        "in_sri": true,
        "name_sri": "A0A087X296_HUMAN Prostaglandin G/H synthase 1 (trembl)",
        "category_sri": "biolink:Protein",
        "in_kg2pre": false,
        "name_kg2pre": null,
        "category_kg2pre": null
      },
      {
        "identifier": "ENSEMBL:ENSP00000483540",
        "category": "biolink:Protein",
        "label": null,
        "major_branch": "GeneticOrMolecularBiologicalEntity",
        "in_sri": true,
        "name_sri": null,
        "category_sri": "biolink:Protein",
        "in_kg2pre": false,
        "name_kg2pre": null,
        "category_kg2pre": null
      },
      {
        "identifier": "ENSEMBL:ENSP00000483540.2",
        "category": "biolink:Protein",
        "label": null,
        "major_branch": "GeneticOrMolecularBiologicalEntity",
        "in_sri": true,
        "name_sri": null,
        "category_sri": "biolink:Protein",
        "in_kg2pre": false,
        "name_kg2pre": null,
        "category_kg2pre": null
      },
      {
        "identifier": "UniProtKB:P23219",
        "category": "biolink:Protein",
        "label": "PGH1_HUMAN Prostaglandin G/H synthase 1 (sprot)",
        "major_branch": "GeneticOrMolecularBiologicalEntity",
        "in_sri": true,
        "name_sri": "PGH1_HUMAN Prostaglandin G/H synthase 1 (sprot)",
        "category_sri": "biolink:Protein",
        "in_kg2pre": true,
        "name_kg2pre": "PTGS1",
        "category_kg2pre": "biolink:Protein"
      },
      {
        "identifier": "PR:P23219",
        "category": "biolink:Protein",
        "label": "prostaglandin G/H synthase 1 (human)",
        "major_branch": "GeneticOrMolecularBiologicalEntity",
        "in_sri": true,
        "name_sri": "prostaglandin G/H synthase 1 (human)",
        "category_sri": "biolink:Protein",
        "in_kg2pre": true,
        "name_kg2pre": "prostaglandin G/H synthase 1 (human)",
        "category_kg2pre": "biolink:Protein"
      },
      {
        "identifier": "NCIT:C26596",
        "category": "biolink:Gene",
        "label": "PTGS1 Gene",
        "major_branch": "GeneticOrMolecularBiologicalEntity",
        "in_sri": false,
        "name_sri": null,
        "category_sri": null,
        "in_kg2pre": true,
        "name_kg2pre": "PTGS1 Gene",
        "category_kg2pre": "biolink:Gene"
      },
      {
        "identifier": "ENSEMBL:LRG_639",
        "category": "biolink:Gene",
        "label": "PTGS1",
        "major_branch": "GeneticOrMolecularBiologicalEntity",
        "in_sri": false,
        "name_sri": null,
        "category_sri": null,
        "in_kg2pre": true,
        "name_kg2pre": "PTGS1",
        "category_kg2pre": "biolink:Gene"
      },
      {
        "identifier": "REACT:R-HSA-2314694",
        "category": "biolink:Protein",
        "label": "O-acetyl-L-serine-PTGS1 [endoplasmic reticulum membrane]",
        "major_branch": "GeneticOrMolecularBiologicalEntity",
        "in_sri": false,
        "name_sri": null,
        "category_sri": null,
        "in_kg2pre": true,
        "name_kg2pre": "O-acetyl-L-serine-PTGS1 [endoplasmic reticulum membrane]",
        "category_kg2pre": "biolink:Protein"
      },
      {
        "identifier": "REACT:R-HSA-428931",
        "category": "biolink:Protein",
        "label": "PTGS1 [endoplasmic reticulum membrane]",
        "major_branch": "GeneticOrMolecularBiologicalEntity",
        "in_sri": false,
        "name_sri": null,
        "category_sri": null,
        "in_kg2pre": true,
        "name_kg2pre": "PTGS1 [endoplasmic reticulum membrane]",
        "category_kg2pre": "biolink:Protein"
      }
    ]
  }
}
```
and as a side note - the synonymizer now has the ability to return a TRAPI knowledge graph for a concept cluster, where the nodes are all equivalent nodes and the edges are all of the 'same_as' and other similarity edges that exist within that cluster (which helps explain why different nodes were added to a cluster). If you're up for it I think it would be really helpful if we could visualize that graph on the /synonyms tab... was hoping the fact that it's in TRAPI KG format might make that easier, since you already visualize `message.knowledge_graph` elsewhere for query responses.. :)

**Comment by isbluis** [comment]
Hi @amykglen .  Do you have an example of a node (or JSON) that includes the knowledge graph?  Thanks!

**Comment by isbluis** [comment]
In the meantime, the other items have been incorporated in _devLM_,, e.g.:
https://arax.ncats.io/devLM/index.html?term=Adams%20Oliver%20syndrome
https://arax.ncats.io/devLM/index.html?term=PTGS1

Let me know if you notice any other anger from the updated tab!

**Comment by amykglen** [comment]
the updated table really looks awesome, by the way! super helpful..

**Comment by isbluis** [comment]
Great, thanks!  Glad to re-arrange as needed.

And I think adding the graph to the same method is probably the most straightforward -- at least for me.  But I can make an extra call if it makes more sense to detach it.

**Comment by amykglen** [comment]
cool - I'll add it to that same method - will let you know when it's pushed..

**Comment by edeutsch** [comment]
it might be possible to re-use the format= mechanism
format=with_graph
or something
instead of format=minimal
although that might only currently work with POST and not GET

**Comment by amykglen** [comment]
@isbluis - ok, I added a `knowledge_graph` slot for each concept in the output of `get_normalizer_results()`. let me know if you run into any issues or if I can tweak anything to make it easier for you!

currently the `knowledge_graph` slot is returned unless format == "minimal"

**Comment by edeutsch** [comment]
arax.ci.transltr.io and kg2.ci.transltr.io both went down hard and have not recovered right around the time of the previous post. Maybe this is related? maybe not. I am able to deploy the code fine on arax.ncats.io, so there's nothing clearly wrong with the commit. Maybe related to #2043?

**Comment by amykglen** [comment]
sounds like it was Pouyan doing deployments (based on Slack) - neither arax.ci.transltr.io nor kg2.ci.transltr.io had been working since we deployed KG2.8.0.1c - he was working on fixing that

**Comment by isbluis** [comment]
Hi @amykglen .  I have added the Concept Graph to the Synonyms tab.  Very beta, so please pass on any suggestions, shortcomings, errors, or anger -- real or perceived.  I'll do my best to tame the beast.  Thanks!

**Comment by edeutsch** [comment]
Nice!
https://arax.ncats.io/devLM/?term=ibuprofen

Since they're almost always named the name thing, I wonder if it would be better to label the nodes with the ids..

**Comment by isbluis** [comment]
Thanks!

> Since they're almost always named the name thing, I wonder if it would be better to label the nodes with the ids..

That seems reasonable.  Though it does require some plumbing work...

**Comment by isbluis** [comment]
> label the nodes with the ids

Never mind, only a minor valve adjustment was needed.  Done!


Also: do we prefer a black (or red) cross when `in_xxxx` is false, or leave it blank (as-is)?

**Comment by edeutsch** [comment]
Nice!

What does it means when they're not connected?
https://arax.ncats.io/devLM/?term=ABCG2

**Comment by amykglen** [comment]
cool, this is awesome!! thanks @isbluis!

as for when terms aren't connected - that means that even though the SRI put them in the same cluster, the bulk SRI NN download didn't include edges between them, for whatever reason. I've seen this a few times.. it's strange because Chris told me that when they create edges for their bulk download, they essentially create a complete graph of same_as edges for each cluster, which doesn't align with what we see here. I haven't pointed this out to Chris/Gaurav yet.. 

worth noting that nodes that are _solely_ in KG2 (and not the SRI) could never be entirely disconnected in a cluster due to how the clustering algorithm works. such non-SRI nodes will only ever be added to a cluster if they're connected to one or more nodes in that cluster.

as for what to do with False values @isbluis - I suppose maybe a black cross would be good. (sorry for requesting otherwise at first!)

**Comment by amykglen** [comment]
I think maybe the disconnected nodes thing from the SRI happens only with Gene/Protein nodes - perhaps it's due to their conflations? maybe they don't consider the conflation between Gene and Protein when creating their same_as edges for the bulk download... (I'm totally speculating)

**Comment by amykglen** [comment]
@isbluis - this might be more work than it's worth, but it'd be super nice if the edges were color-coded according to their `primary_knowledge_source`, specifically with three colors: one for `infores:sri-node-normalizer`, one for `infores:arax`, and one for anything else (which corresponds to KG2 edges)

**Comment by isbluis** [comment]
No worries at all, @amykglen !  I initially also thought that leaving it blank for False would look better and be simpler.  I added the black cross; let me know if you think this is good, or if another color would be preferable.  Or back to blank!

Also added the edge colors, but only to this graph and not the others (results, KG, etc).

Happy to adjust anything, so please send suggestions, as well as any issues.

**Comment by amykglen** [comment]
wow, this looks great!! thanks @isbluis! could you swap the colors of the infores:arax and 'everything else' edges? (so that the infores:arax edges are grey - I think that's most intuitive because those edges are sort of the weakest evidence source - just name string similarity)

and I like the black crosses. let's stick with that!

thanks again!

**Comment by isbluis** [comment]
Thank you!

I have updated the colors.  I think @edeutsch will deploy tomorrow.

**Comment by isbluis** [comment]
Is this ok to close, @amykglen ?  Or let me know what else I can add to the display.

**Comment by amykglen** [comment]
yes it's great, thanks!
