### ISSUE TITLE
SemMedDB publications filtering due July 31 for RTX-KG2

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2045]
according to the TAQA call today, we are supposed to update RTX-KG2 to exclude SemmedDB edges with fewer than some threshold number of publications by July 31

this will be easy to do for the RTX-KG2 API

what may be harder to do is update XDTD/Infer to exclude such SemmedDB edges from support graphs. not sure what will be involved there (we'll need @chunyuma)

but this doesn't need to be addressed until after the relay

**Comment by amykglen** [comment]
whoops - guess this might be a duplicate of #1972.. though that issue was kind of more about brainstorming...

**Comment by chunyuma** [comment]
The xDTD training has included some filtering steps for SemMedDB. For example, we excluded SemmedDB edges whose two end nodes has #pmid < 10 and NGD score > 0.6.

**Comment by saramsey** [comment]
From @amykglen by Slack DM:

> Hmm, the only tricky part about that is that KG2 doesn't always 'decorate' edges with their publications - that is controlled via a user-specified query parameter (Plover doesn't include publications). ARAX always asks KG2 not to decorate edges/nodes it returns because it's faster to send less data in the response, and ARAX has a decorate step after it gets results from all KPs anyway.
> But I suppose you could just always 'decorate' semmed edges using ARAX_decorator.py when in KG2 mode, and then go through and remove those edges with fewer than N publications. I think maybe doing that around here would make sense? https://github.com/RTXteam/RTX/blob/f93f7c5352bfae3652c6525fd78bb45d9ae2b84c/code/ARAX/ARAXQuery/ARAX_expander.py#L647

(thank you Amy!)

**Comment by saramsey** [comment]
Perhaps if we are in the code fixing this, we could also implement the requested filtering based on SemMedDB novelty score [NCATSTranslator/Feedback issue 432](https://github.com/NCATSTranslator/Feedback/issues/432) at the same time.

**Comment by dkoslicki** [comment]
Steve mentions the threshold is: delete all edges that have support _only_ from SemMedDB and have 3 or fewer PMID support articles.

**Comment by dkoslicki** [comment]
A simple DSL [filter command](https://github.com/RTXteam/RTX/blob/master/code/ARAX/Documentation/DSL_Documentation.md#filter_kgactionremove_edges_by_discrete_attribute) might work, or [this one](https://github.com/RTXteam/RTX/blob/master/code/ARAX/Documentation/DSL_Documentation.md#filter_kgactionremove_edges_by_top_n).

**Comment by edeutsch** [comment]
I notice the latest commit changes max results from 20 to 8. Is that intended and okay and desirable?
https://github.com/RTXteam/RTX/commit/3993d8eaf53939de52a4a30fd878b565c5cbc97e

**Comment by kvnthomas98** [comment]
It was intended, the reason being with the filtering of the semmeddb edges while running locally, i was getting 10 results and to test the filtering result count ability I was selecting 8 testcases. However, while running on the workflow only 4 results were returned causing the test to fail.

**Comment by saramsey** [comment]
@kvnthomas98 when you have a moment, can you please verify that this is working, on `arax.transltr.io` (ITRB production)?  Thanks.

**Comment by kvnthomas98** [comment]
I have checked and verified it is working on https://kg2.transltr.io/
