### ISSUE TITLE
xDTD returns some very generic therapeutics

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2047]
I think this has been discussed elsewhere, but while trying queries again, I am struck by a few nodes that come up in the ARAX top 10.
For example:
- Agonists
- Therapeutic agent (substance)

I wonder if an easy win is to implement a manual black list of drugs that should be excluded from the calculation. There are probably only a dozen or two.

![image](https://github.com/RTXteam/RTX/assets/12707718/b66435aa-bbf2-4883-bd2c-49ca3a9eec22)

**Comment by edeutsch** [comment]
Discuss at next week's AHM

**Comment by saramsey** [comment]
See also [NCATSTranslator/Feedback issue 336](https://github.com/NCATSTranslator/Feedback/issues/336), which seems related.

**Comment by saramsey** [comment]
I'm thinking maybe the short-term solution here is via [RTX issue 2069](https://github.com/RTXteam/RTX/issues/2069)?

**Comment by dkoslicki** [comment]
Closed in favor of #2069
