### ISSUE TITLE
Questions.tsv needs re-statements to include $variables.

### ISSUE THREAD

**Issue by Palzer** [RTXteam/RTX#205]
Not sure if autogen or manual. Question restatements need the variable included for parsing.

If manual, I can tackle this tomorrow.

**Comment by dkoslicki** [comment]
I don't think I understand this issue: the restatement templates contain the variables:
```python
import ParseQuestion
p = ParseQuestion.ParseQuestion()
import ParseQuestion
p = ParseQuestion.ParseQuestion()
p._question_templates[0].restated_question_template.template
Out[100]: 'What is $term'
p._question_templates[1].restated_question_template.template
Out[101]: 'Which genetic conditions might offer protection against $disease'

```

**Comment by dkoslicki** [comment]
They only get grounded if the ``restate_question`` method is called:
```python
p._question_templates[0].restate_question({"term": "dog"})
Out[102]: 'What is dog'
```

**Comment by dkoslicki** [comment]
The third column (contained in ``[ ]``) are **not** the restatements, they are the corpora that the NLP matches to. The restatements will always be in column 2 (the ones with the ``$`` in it).

**Comment by Palzer** [comment]
Okay, so I'll ignore those then. Closed.
