### ISSUE TITLE
Remove infores:arax-drug-treats-disease as a KP for ARAX for the presentation to Council

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2052]
Per conversation with David, we should remove `infores:arax-drug-treats-disease` as a KP in ARAX for the presentation to NCATS Council at end of summer, to avoid results like the ones attached below, potentially showing up in the Translator UI:

**Comment by saramsey** [comment]
<img width="1198" alt="Screen Shot 2023-06-06 at 8 41 55 AM" src="https://github.com/RTXteam/RTX/assets/5562107/981bccab-0e87-45b2-acba-e29e1ed96b93">

https://arax.ncats.io/?r=141606

**Comment by saramsey** [comment]
<img width="1195" alt="Screen Shot 2023-06-06 at 8 42 27 AM" src="https://github.com/RTXteam/RTX/assets/5562107/3cf645fc-9f3c-4b55-8ae9-1fb43b1c784f">

https://arax.ncats.io/?r=141606

**Comment by saramsey** [comment]
<img width="1215" alt="Screen Shot 2023-06-06 at 8 44 20 AM" src="https://github.com/RTXteam/RTX/assets/5562107/ad25fc43-2479-4039-9dab-72233644aeaa">

https://arax.ncats.io/?r=141606

**Comment by edeutsch** [comment]
Won't removing the whole thing majorly degrade ARAX answers for the primary UI use case? Do we really want to do that??
Might it be better to implement a blocklist either in training or is providing answers? As a part of the Relay, the "red team" came up with a whole lot of "diseases" that will be simply blocked to avoid unfortunate answers being shown. So some of this is being handled already at the UI level. But it might be sensible to take that block list and apply it to xDTD as well? For example, maybe we should use exclude death from xDTD, assuming that won't lead to sensible answers. Maybe we should also just exclude cocaine, assuming that no sensible answers should suggest cocaine as a treatment.

**Comment by saramsey** [comment]
OK @edeutsch fair enough. And we should remove "Death" as a disease. ;-)

**Comment by edeutsch** [comment]
2 outcomes:
1) We can remove DTD today because we now have xDTD? Let's wait for input from David to be sure.
NOTE: Overlay still queries DTD and that requires more thought before we take that out.
https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py
@Chunyu will evaluate what it would take to completely retire DTD. What needs to be removed (or switched to xDTD) and be ready to discuss next AHM

2) Consider and discuss with David if we should integrate the Translator Blocklist (of drugs and conditions) into the next xDTD build process
Let's not worry about this problem in the current pre-computation effort. just proceed with that as planned.

Let's bring up these 2 topics again at next week's AHM with David present.

**Comment by chunyuma** [comment]
For 1, I will generate a new branch on GitHub from the current master and try to retire DTD from ARAX to see if it affects. If it works, then we can simply merge it to the master branch later.

**Comment by chunyuma** [comment]
I have retired DTD model in the branch `retire_DTD` and skip all associated tests. All the remaining non-slow tests still pass. So once we decide to finally retire this model in the next AHM. We can merge this branch to master.

**Comment by saramsey** [comment]
@chunyuma can we close out this issue now?

**Comment by isbluis** [comment]
Has it been decided to permanently retire DTD?   If so, it seems that some code clean-up might be beneficial both in terms of performance as well as cleaning the logs.  At the moment, we are logging this, which makes it seem like a temporary state:
`log.warning(f"DTD KP has been replaced with xDTD and thus is currently disabled.")`

I am thinking that `infores:arax-drug-treats-disease` could be removed from this line in ARAX_expander:
`use_custom_querier = kp_to_use in {'infores:arax-drug-treats-disease', 'infores:arax-normalized-google-distance'}`
...as well as related code.

Glad to do this myself, but paging @chunyuma and @amykglen to make sure this is the intent.

**Comment by amykglen** [comment]
that sounds very logical to me assuming that we wanted to entirely get rid of the old DTD (which was my understanding), but @chunyuma would know those plans better than me

**Comment by chunyuma** [comment]
Hi @amykglen. Since I'm not very familiar with ARAX_expander, I'm afraid my change in this script could have a significant impact. Could you please assist me in forbidding the use of `infores:arax-drug-treats-disease` in ARAX_expander? Thank you!

**Comment by isbluis** [comment]
I can make some of the changes and have them reviewed before commit.
My main concern was with whether DTD is officially dead with no revival plans, and this seems to be the case.

**Comment by chunyuma** [comment]
Thanks @isbluis. Yes, DTD is officially retired.

**Comment by edeutsch** [comment]
I suggest that it would be nice to "traffic light" the new xDTD instead.

**Comment by isbluis** [comment]
Already on it, @edeutsch !
