### ISSUE TITLE
Update SmartAPI YAML file's test_data_location to point to an existing triples file

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2055]
In this SmartAPI registration file for the RTX-KG2 KP service:
https://raw.githubusercontent.com/RTXteam/RTX/NewFmt/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/openapi/openapi.yaml

(which seems to be currently active), the `test_data_location` variable under the `development` maturity level seems to point to a non-existing file:
<img width="1001" alt="Screen Shot 2023-06-07 at 1 15 18 PM" src="https://github.com/RTXteam/RTX/assets/5562107/1f50d406-9b45-46df-9df0-be24d341b327">

I wonder if instead it should be updated to point to:
https://raw.githubusercontent.com/RTXteam/RTX/master/code/ARAX/KnowledgeSources/RTX_KG2c_test_triples.json

Thank you to Richard B. for bringing this to my attention.

**Comment by edeutsch** [comment]
Done.
https://github.com/RTXteam/RTX/commit/385ee70866e8a856bf0ae1b3a281390cfe897b51
