### ISSUE TITLE
xDTD return more results requested for MVP1

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#2057]
Instead of returning the top 10 predicted drugs from xDTD, there was overwhelming requests at the relay that ARAX return a lot more (something like 100 or 200).

**Comment by edeutsch** [comment]
First very quick fix is to request the top 25 of the current. Trivial.

**Comment by edeutsch** [comment]
Can the next version of xDTD return 100 or 200?
What are the size implications?

**Comment by edeutsch** [comment]
Chunyu will start building a new version with top 200 answers starting today

**Comment by chunyuma** [comment]
I've set the default the number of top predicted drugs to 25. We can't have more until we have the new xDTD.

**Comment by edeutsch** [comment]
I suppose I didn't appreciate the difference between drugs and paths before.

> I will store top 200 drug prediction with top 50 predicted paths into the xDTD pre-computed database for the new xDTD based on kg2.8.0.1c. Is it ok?

This means that would see 200 answer drugs, and each one might have a support graph with up to 50 paths in that graph, right?

I think this is good.

btw, if there is some metric of goodness, and we had some sense that below a score of X, the quality is so low that it is really not work showing, I would be fine with cutting it down to fewer. But I suppose the goal is: if there are more than 25 plausible answer drugs, it would be nice to store and show more. But we don't have to store and show trash if we know it's trash.

**Comment by chunyuma** [comment]
Yes @edeutsch. We will generate up to 200 answer drugs with each up to 50 paths in the KG2 (if available).

I now set 0.6 as a threshold to cut it down. It might also reduce the computation time.

**Comment by chunyuma** [comment]
close it as it has been completed.
