### ISSUE TITLE
Support/analysis graphs missing in new deployment for xDTD

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#2059]
This may be related to #2054, but I noticed that in arax.ncats.io/test and other "freshly deployed" endpoints have somehow lost all/most of the MOA paths from xDTD. Contrast the same query on the old deployment: https://arax.ncats.io/?r=142469
versus the new one: https://arax.ncats.io/test/?r=142468. The same results (with different scores), but the paths are now gone.

**Comment by dkoslicki** [comment]
Amy informed me that this is due to the MOA paths have been moved to the edge property support graph from the "treats" edge.

@isbluis what's the difference between the top level "support graphs" (seen right underneath the result name) and the one that decorates the edge?
i.e. 
<img width="423" alt="Screenshot 2023-06-08 at 2 30 42 PM" src="https://github.com/RTXteam/RTX/assets/6362936/ebb6f21e-6134-49ac-b31c-de137f52af8c">
vs
<img width="503" alt="Screenshot 2023-06-08 at 2 31 02 PM" src="https://github.com/RTXteam/RTX/assets/6362936/f4c18152-787c-4a42-803b-b739b26c26a5">

**Comment by isbluis** [comment]
Hi @dkoslicki .  There are two kinds of support graphs: those that are part of a result, and thus attached to a specific analysis (which is an array), and those that are part of an edge.  The former are the ones you see at the top (first image), and the latter in the bottom one.

I do plan on cleaning up this display now that my other conference is over.

**Comment by edeutsch** [comment]
This has been mostly fixed. Closing. Please reopen if still an issue. Both kinds of support graphs are accessible, e.g. at
https://arax.ncats.io/test/?r=142468

not yet in full production.
