### ISSUE TITLE
ARAX should always identify itself when querying KPs

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2061]
currently ARAX only identifies itself when querying KG2. we need to change that so that ARAX identifies itself when querying _any_ KP. 

this will just be a matter of removing the 'if' clause around this line:
https://github.com/RTXteam/RTX/blob/66ba3cbe63b946151920547780c18df91c66352a/code/ARAX/ARAXQuery/Expand/trapi_querier.py#L323-L324

(i.e., we should _always_ fill out the 'submitter' when sending TRAPI queries)

thinking maybe @sundareswarpullela wants to tackle this one? this is a good opportunity to practice the workflow for changing ARAX/Expand code (described here: https://github.com/RTXteam/RTX/wiki/Dev-info#best-practice-dev-workflow)

**Comment by sundareswarpullela** [comment]
Tests are passed and changes are complete.

**Comment by edeutsch** [comment]
This has been deployed to all the usual `master` places. I don't really know how to test, but fine with me to close.
