### ISSUE TITLE
Bug in multi-hop when pruning knowledge graph.

### ISSUE THREAD

**Issue by GregHydeDartmouth** [RTXteam/RTX#2064]
Using the following multihop:
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": [
                        "biolink:Disease"
                    ],
                    "ids": [
                        "MONDO:0005100"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:GrossAnatomicalStructure"
                    ]
                },
                "n2": {
                    "categories": [
                        "biolink:Gene"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": [
                        "biolink:located_in"
                    ]
                },
                "e1": {
                    "subject": "n1",
                    "object": "n2",
                    "predicates": [
                        "biolink:expresses"
                    ]
                }
            }
        }
    }
}
```
and sending a the query directly to the ARAX (staging and test), ARAX completes the first hop, but then crashes with the following:
"2023-06-15T17:05:47.270696 ERROR: An uncaught error occurred: '<' not supported between instances of 'NoneType' and 'NoneType': ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 754, in execute_processing_plan\n expander.apply(response, action[\'parameters\'], mode=mode)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 489, in apply\n overarching_kg = self._prune_kg(qnode_key, pre_prune_threshold, overarching_kg, query_graph, log)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 1211, in _prune_kg\n results.sort(key=lambda x: x.score, reverse=True)\n', "TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'\n"]

Before proceeding to the next hop.

**Comment by edeutsch** [comment]
It would be helpful to know which instance this was run on. Our production instances are still running TRAPI 1.3. and test was different than CI (at least at the time of posting, that's about to change and be sync'ed)

**Comment by GregHydeDartmouth** [comment]
> It would be helpful to know which instance this was run on. Our production instances are still running TRAPI 1.3. and test was different than CI (at least at the time of posting, that's about to change and be sync'ed)

Currently this appears to be happening on Staging and Test

**Comment by edeutsch** [comment]
perfect, thanks. This is the latest master, TRAPI 1.4

**Comment by amykglen** [comment]
I was able to reproduce the issue locally; it's now fixed in `master`.

**Comment by edeutsch** [comment]
Thanks! I have just deployed the fix to https://arax.ncats.io/beta/
It should make its way to arax.ci.transltr.io automatically within about 20 minutes, although will be difficult to know when exactly.
It will not make its way to test or production any time soon.

**Comment by amykglen** [comment]
thanks! it looks good to me on https://arax.ncats.io/beta/.

though when running my test query with the default KP timeout setting in the UI (30 seconds), I noticed another entirely separate error stemming from resultify, which I also just fixed in `master`.

**Comment by edeutsch** [comment]
re-deployed!

**Comment by amykglen** [comment]
looks good to me! feel free to close the issue if you agree, @GregHydeDartmouth

**Comment by GregHydeDartmouth** [comment]
Looks great. I appreciate the quick turn around!
