### ISSUE TITLE
Stuck processes seem to have become more common

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2072]
In recent deployments, it seems that zombie processes have become more common. For example, now on arax.ncats.io:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                  
 8169 rt        20   0 2442044 782872  53128 S 104.3  1.2  12:14.62 python3                                                                  
12263 rt        20   0 1793100 239200   9396 R  99.7  0.4   2418:27 python3                                                                  
12888 rt        20   0 1763916 226468   9396 R  99.7  0.3   2238:51 python3                                                                  
 8244 rt        20   0 1727804 193372  47908 S   0.3  0.3   7:31.03 python3                           
```

The ongoing query tracker shows:
![image](https://github.com/RTXteam/RTX/assets/12707718/e19b91cf-96e0-401d-90db-62d9fc843316)

It seems that two trivial "acetaminphen" queries are running after hours of processing and still consuming 100% of one CPU. Yet there is nothing visible in the logs that anything is still happening.

There is also another problem of zombie entries in the active query table. But that may be different.

I'm uncertain about what is going on and how to address it.

**Comment by edeutsch** [comment]
First correction: when I said "Zombie", I meant "Stuck", not in the true Linux Z state.

**Comment by edeutsch** [comment]
I think I have just witnessed the problem:

![image](https://github.com/RTXteam/RTX/assets/12707718/2b30966f-4565-4cf0-bfb8-e7c48912eb23)

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                  
23311 rt        20   0 2397004 938408  53352 S 102.0  1.5  39:09.61 python3                                                                  
 9825 rt        20   0 1786580 246804   9196 S  99.7  0.4  11:10.92 python3                                                                  
 9845 rt        20   0 1876180 284368   9132 S  99.7  0.4  10:57.07 python3             
```

**Comment by edeutsch** [comment]
I suspect that somewhere between 
```
2023-07-26T16:44:48.652828 INFO: Processing action 'expand' with parameters {'': 'true'}
```

and the very next expected log message, the code gets stuck in an infinite loop

**Comment by edeutsch** [comment]
Infinite loop is here:
https://github.com/RTXteam/RTX/blob/42cc7c755732855e52aff072c32d895c417243c7/code/ARAX/ARAXQuery/Expand/kp_info_cacher.py#L120

@saramsey will work on it.

Notes:
- cache user should NOT care what the cache refresher is doing and should NOT wait of the refresher PID
- cache user should only ever loop if there is NO CACHE at all (possible at very first launch or other weird failure {disk full?})
- when the cache user loops to wait for the existence of a cache, there must be a timeout. After perhaps 60 seconds, if there is no cache, then something is terribly wrong and the query should be aborted with an error message
-

**Comment by saramsey** [comment]
I'm working on this issue now. Eric has outlined three specific changes to the `kp_info_cacher.py` that need to be made. I will do this work in the code enlistment in the `devED` DEVAREA on `arax.ncats.io`, test it there, and then (if it works) commit to GitHub from there.

**Comment by saramsey** [comment]
I've pushed commit [eabed27](https://github.com/RTXteam/RTX/commit/eabed275b4a08f689644c77dddbb937b2c283ea3)  to try and fix this.

**Comment by saramsey** [comment]
Have deployed this hotfix to the `devED` DEVAREA on `arax.ncats.io`. Seems to work.

**Comment by saramsey** [comment]
[Have previously tested the updated `kp_info_cache.py` module locally and it seems to work.]

**Comment by edeutsch** [comment]
Ready to deploy everywhere?

**Comment by saramsey** [comment]
I'm back and doing some more testing. So ARAX seems to be working in the `devED` DEVAREA on `arax.ncats.io`, after I restarted ARAX. Specifically, here is the output from running the standard test query in the ARAX web UI:

<img width="1003" alt="Screenshot 2023-07-26 at 2 57 16 PM" src="https://github.com/RTXteam/RTX/assets/5562107/788e699f-f137-44a0-bf17-a2de17c8c5df">

Looks like the last time ARAX was restarted was on July 26 at 21:48 GMT, 

```
root@d1fd345478a0:/tmp# grep 'INFO: ARAXBackgroundTasker created' /tmp/RTX_OpenAPI_devED.elog
2023-07-26T21:48:03.138820: INFO: ARAXBackgroundTasker created
```

**Comment by edeutsch** [comment]
I have deployed to all instances that track master now

**Comment by saramsey** [comment]
Are we good to close this out?

**Comment by saramsey** [comment]
I'm not seeing any pinned processes on arax.ncats.io, FWIW

**Comment by edeutsch** [comment]
still fiddling a little. CI is currently broken, but I think the problem is a different one. working on it....

**Comment by saramsey** [comment]
Thank you for commit 17ae68f. Good idea.

**Comment by saramsey** [comment]
See also the epic "stuck processes" issue #2114
