### ISSUE TITLE
sometimes a new ITRB node will have corrupted databases

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2074]
I added some code to inspect the databases area at service launch time and find that currently on CI the databases are in a bad state and so the instance doesn't work. This happens not infrequently. A fix is to ask ITRB to redeploy and that often fixes it.

I don't understand how the databases get set up initially when a pod is first created. Does anyone understand this process? How can we make this more robust?

Here's what the databases area looks like on ITRB CI:
```
  /mnt/data/orangeboard/databases/KG2.8.3
total 204928
-rwxrwxrwx 1 rt rt         0 Jul 26 16:19 autocomplete_v1.0_KG2.8.3.sqlite
-rwxrwxrwx 1 rt rt  13664256 Jul 12 08:53 curie_to_pmids_v1.0_KG2.8.3.sqlite
-rwxrwxrwx 1 rt rt         0 Jul 26 16:18 fda_approved_drugs_v1.0_KG2.8.3c.pickle
-rwxrwxrwx 1 rt rt         0 Jul 26 16:18 kg2c_v1.0_KG2.8.3.sqlite
-rwxrwxrwx 1 rt rt         0 Jul 26 16:18 meta_kg_v1.0_KG2.8.3c.json
-rwxrwxrwx 1 rt rt 196182016 Jul 12 06:35 node_synonymizer_v1.0_KG2.8.3.sqlite
```

Complete train wreck. How did it get to be that way?

How can we ensure that the databases get set up correctly the first time?

The database copy potentially takes a long time the first time.

I'm a bit concerned that when we launch our service for the first time, the databases are initially not there, and so a database manager gets run. But then if a query comes in and things are not set up yet, another database manager may get run and we potentially have multiple processes or database managers all trying to do the same copying in parallel and making a huge mess. How do we avoid that?

Can anyone help?

**Comment by saramsey** [comment]
Would it help if ARAX was set up to refuse to answer any queries until the database manager has been run for the first time?

**Comment by saramsey** [comment]
Why can't we run the database manager in the Dockerfile, between line 56 and line 59?

https://github.com/RTXteam/RTX/blob/b2c21983eef767b44fe608e351ccd6ffb8640079/DockerBuild/Dockerfile#L56-L59

**Comment by edeutsch** [comment]
> Why can't we run the database manager in the Dockerfile, between line 56 and line 59?

Well, I don't know that we can't. But I'm thinking that the ARAX_database_manager.py depends on the whole RTXConfig code and other stuff that normally runs INSIDE the container, so it may be that we can't run the database manager while creating the container. It may have to be run after the container is complete and then run inside the container after it is running.

**Comment by edeutsch** [comment]
> Would it help if ARAX was set up to refuse to answer any queries until the database manager has been run for the first time?

Yes, that is I am thinking may be what we want. We may want to launch the database manager in a blocking fashion BEFORE we launch the ARAX web application.

OR, maybe we could run the database manager as part of the background tasker, but build in some smarts to decline to handle any queries (or synonym lookups or ...) until the database manage is complete and has successfully done its job.

I just don't quite understand the whole docker build and launch and CI relaunch-on-push architecture to feel confident in what to do. And I lack understanding on how to test our Docker build and launch and relaunch system.

**Comment by edeutsch** [comment]
> > Why can't we run the database manager in the Dockerfile, between line 56 and line 59?
> 
> Well, I don't know that we can't. But I'm thinking that the ARAX_database_manager.py depends on the whole RTXConfig code and other stuff that normally runs INSIDE the container, so it may be that we can't run the database manager while creating the container. It may have to be run after the container is complete and then run inside the container after it is running.

in retrospect, I suppose the code in the Dockerfile is running "inside" the container as it builds itself? The one change I would then add is that the database manager depends on RTXConfig which in turn depends on config.domain, which is the last thing set in the file. So I'm now thinking that we can probably run the database manager after config.domain is set, i.e. the last thing in the file. that might work. I'm uncertain. I don't know how best to test. I'd be great if someone could teach me how to test that.

**Comment by saramsey** [comment]
In the non-ITRB pushbutton ARAX deployment system that I developed (for testing), the `ARAX_database_manager.py` script is run on the host OS before the image is built, as shown in this shell script,

https://github.com/RTXteam/RTX/blob/b2c21983eef767b44fe608e351ccd6ffb8640079/DockerBuild/test-instance-scripts/build-test-arax-from-fresh-instance.sh#L51

When `ARAX_database-manager.py` is invoked as it is in the shell script (i.e., with the `--mnt` option), I believe the database files get copied from `arax-databases.rtx.ai` to a subdirectory underneath `/mnt/data/orangeboard/databases/`. That directory is then mounted into the Docker container, as shown here:

https://github.com/RTXteam/RTX/blob/b2c21983eef767b44fe608e351ccd6ffb8640079/DockerBuild/test-instance-scripts/build-test-arax-from-fresh-instance.sh#L70

The details are hazy now, but I believe that I did that in order to avoid having to bloat the image with 161 GiB of database files (which is what would happen if instead I had called `ARAX_database_manager.py` in the Dockerfile). Of course, I could have also chosen to run it inside the _container_ but doing it in the host OS and then mounting it into the container seemed a bit easier to debug, I suppose.

**Comment by saramsey** [comment]
Now, when it comes to ITRB deployment, the situation seems a bit different. We have to contend with the Jenkinsfile,

https://github.com/RTXteam/RTX/blob/master/deploy/arax/Jenkinsfile

It seems like there is a shell-scripty section in the Jenkins file 

https://github.com/RTXteam/RTX/blob/b2c21983eef767b44fe608e351ccd6ffb8640079/deploy/arax/Jenkinsfile#L79-L81

where we might be able to slip in a call to `ARAX_database_manager.py`. I am not sure if it would work, and even less sure about how to test it. I guess we would have to set up our own Jenkins.

**Comment by saramsey** [comment]
Actually I just noticed that there is some shell script `download_database.sh` in the `RTX/deploy/arax/scripts/` directory. This script _seems_ to be run by the `RTX/deploy/arax/templates/deployment.yaml` script,

https://github.com/RTXteam/RTX/blob/b2c21983eef767b44fe608e351ccd6ffb8640079/deploy/arax/templates/deployment.yaml#L25

**Comment by saramsey** [comment]
Looks like Pouyan would know the most about the `download_database.sh` script, from looking at the GitHub commit history for that script.

**Comment by saramsey** [comment]
I wonder if this issue (#2074) is just a manifestation of this issue? https://github.com/RTXteam/RTX/issues/2040

**Comment by edeutsch** [comment]
> I wonder if this issue (#2074) is just a manifestation of this issue? #2040

I think #2040 is a different issue, and I think I have added code to automatically fix #2040 when it happens. But this one #2074 is a different problem.

**Comment by saramsey** [comment]
OK, understood. Is it possible that #2074 is a consequence of a fault in `download_database.sh`?

**Comment by saramsey** [comment]
Admittedly I don't understand the ITRB/Jenkins/Kubernetes deployment system at all, but what evidence I do see in GitHub suggests that `download_database.sh` is used to stage the database files in a new ARAX instance. Perhaps it's not working right, intermittently?

**Comment by saramsey** [comment]
But perhaps if a zero-length database file is getting put in there by some other cause (e.g., `download_database.sh`), maybe `ARAX_database_manager.py` won't overwrite it?

**Comment by edeutsch** [comment]
> OK, understood. Is it possible that #2074 is a consequence of a fault in `download_database.sh`?

based on your descriptions, this sounds highly plausible, yes.

EXCEPT, from a brief glance through `download_database.sh` it looks like it is very diligent with checking md5sums and all, so it seems rather surprising that it would end up as 0-length files. I wonder if they could be 0 length due to a disk-full event? Maybe we should loop in Pouyan to see if they have time to debug?

HOWEVER, I am thinking that while this is an interesting problem, we really need to get this resolved. So I think we should ask Pouyan to redeploy CI tomorrow and then I need to get itrb-test deployed as well and then put in the request to get production updated. I feel that our current code is better than what is deployed on test and production and we need to get it out. So unless I hear otherwise, I will request that they try to redeploy CI and test tomorrow, and put in the request for production.

**Comment by saramsey** [comment]
Sorry I am just now seeing this GitHub comment. I am working on provisioning a larger root volume for `arax-databases.rtx.ai`.

**Comment by sundareswarpullela** [comment]
Database copying has been done and ITRB CI instances have been re-deployed.

**Comment by edeutsch** [comment]
Closing this issue as resolved. It turned out that there wasn't a problem copying the databases to the running instances, but rather that the files weren't correct on the sftp server. Once that was corrected, the deployments seemed to go fine.
