### ISSUE TITLE
NGD service broken

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2088]
https://arax.ncats.io/api/arax/v1.4/PubmedMeshNgd/PTGS2/acetaminophen

causes:

```
ERROR:__main__:Exception on /api/arax/v1.4/PubmedMeshNgd/PTGS2/acetaminophen [GET]
Traceback (most recent call last):
  File "/mnt/data/python/Python-3.9.16/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/data/python/Python-3.9.16/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/data/python/Python-3.9.16/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/mnt/data/python/Python-3.9.16/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/data/python/Python-3.9.16/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/mnt/data/python/Python-3.9.16/lib/python3.9/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
  File "/mnt/data/python/Python-3.9.16/lib/python3.9/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "/mnt/data/python/Python-3.9.16/lib/python3.9/site-packages/connexion/decorators/validation.py", line 399, in wrapper
    return function(request)
  File "/mnt/data/python/Python-3.9.16/lib/python3.9/site-packages/connexion/decorators/parameter.py", line 120, in wrapper
    return function(**kwargs)
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/pubmed_mesh_ngd_controller.py", line 28, in pubmed_mesh_ngd
    response = ngd.api_ngd(term1,term2)
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../reasoningtool/kg-construction/NormGoogleDistance.py", line 231, in api_ngd
    value = QueryNCBIeUtils.multi_normalized_google_distance([mesh_term1, mesh_term2])
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../reasoningtool/kg-construction/QueryNCBIeUtils.py", line 431, in multi_normalized_google_distance
    counts = QueryNCBIeUtils.multi_pubmed_hits_count(search_string, n_terms=len(name_list))
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../reasoningtool/kg-construction/QueryNCBIeUtils.py", line 397, in multi_pubmed_hits_count
    for a in range(len(res.json()['esearchresult']['translationstack'])):
KeyError: 'translationstack'
INFO:werkzeug:127.0.0.1 - - [07/Aug/2023 22:11:59] "GET /api/arax/v1.4/PubmedMeshNgd/PTGS2/acetaminophen HTTP/1.1" 500 -
```

**Comment by isbluis** [comment]
While looking into this issue, I find an (unrelated) inconsistency in `Overlay/compute_ngd.py`:

        self.ngd_normalizer = 2.2e+7 * 20  # From PubMed home page there are 27 million articles; avg 20 MeSH terms per article

Shouldn't that first factor be `2.7e+7` as per the comment, as well as the description below that? (and note typo on "**numbver**"):

        ngd_description = """
        Normalized google distance is a metric based on edge subject/object node co-occurrence in abstracts of all [PubMed](https://pubmed.ncbi.nlm.nih.gov/) articles.
        The formula can be found here on [wikipedia.](https://en.wikipedia.org/wiki/Normalized_Google_distance)
        Where in this case f(x,y) is the number of PubMed abstracts both concepts apear in, f(x)/f(y) are the number of abstracts individual concepts apear in, and N is the number of pubmed articles times the average numbver of search terms per article (27 million * 20).
        """
Tagging @chunyuma and @dkoslicki , since I am not sure who can best answer and determine if it is relevant.  Glad to make the fix if so.  Thanks!

**Comment by isbluis** [comment]
It seems that `translationstack` is no longer(?) a key under the `esearchresult` element in the JSON returned from `https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch`:

![image](https://github.com/RTXteam/RTX/assets/37852256/81bde201-f767-43dd-8f85-96179291f6e4)

(or maybe an issue with the provider?)

That key is referenced multiple times in the code, so this appears to break all functionality therein.
Is this something you can look into, @saramsey ?

**Comment by dkoslicki** [comment]
> While looking into this issue, I find an (unrelated) inconsistency in `Overlay/compute_ngd.py`:
> 
> ```
>     self.ngd_normalizer = 2.2e+7 * 20  # From PubMed home page there are 27 million articles; avg 20 MeSH terms per article
> ```
> 
> Shouldn't that first factor be `2.7e+7` as per the comment, as well as the description below that? (and note typo on "**numbver**"):
> 
> ```
>     ngd_description = """
>     Normalized google distance is a metric based on edge subject/object node co-occurrence in abstracts of all [PubMed](https://pubmed.ncbi.nlm.nih.gov/) articles.
>     The formula can be found here on [wikipedia.](https://en.wikipedia.org/wiki/Normalized_Google_distance)
>     Where in this case f(x,y) is the number of PubMed abstracts both concepts apear in, f(x)/f(y) are the number of abstracts individual concepts apear in, and N is the number of pubmed articles times the average numbver of search terms per article (27 million * 20).
>     """
> ```
> 
> Tagging @chunyuma and @dkoslicki , since I am not sure who can best answer and determine if it is relevant. Glad to make the fix if so. Thanks!

@isbluis I think changing it to 2.7 works. In actuality, it shouldn't much matter since it affects each score equally

**Comment by dkoslicki** [comment]
It indeed would affect absolute thresholding, but I don't immediately recall anywhere where we do that in the system. Fingers crossed this ~20% change in score doesn't affect the ranker too much (I can't imagine it will given it does relative ranking)

**Comment by saramsey** [comment]
> It seems that `translationstack` is no longer(?) a key under the `esearchresult` element in the JSON returned from `https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch`:

Very nice sleuthing, @isbluis

**Comment by saramsey** [comment]
Sorry I didn't respond when I got tagged on this, back in August. But it looks like we're all set now?

**Comment by isbluis** [comment]
Hi @saramsey.  Yes, someone still needs to figure out what the correct/updated call should be to this `utils` resource.  I could not find an answer as to where/how to find the missing elements, and moved on to fixing other items pre-code freeze.

**Comment by saramsey** [comment]
Thank you @isbluis. @dkoslicki would it be possible for @kvnthomas98 to take a look?

**Comment by dkoslicki** [comment]
@kvnthomas98 what do you think, something you have bandwidth to attempt?

**Comment by kvnthomas98** [comment]
Hi @dkoslicki, @saramsey , I can look into this, this week.

**Comment by kvnthomas98** [comment]
This should be fixed now. It looks to be working on https://arax.ci.transltr.io/api/arax/v1.4/ui/#/PubmedMeshNgd/pubmed_mesh_ngd


<img width="1404" alt="image" src="https://github.com/RTXteam/RTX/assets/17030839/5df81b7e-c35c-45f3-a904-e590d5430e3f">

**Comment by kvnthomas98** [comment]
![image](https://github.com/RTXteam/RTX/assets/17030839/96653bb2-d71d-4a6e-b6cc-63267d5ec247)
Its working on arax.ncats.io/beta
@saramsey are we good to close?

**Comment by saramsey** [comment]
Yes, it looks like the commit that fixes this issue is in master, deployed to `/beta`, and it is working in `/beta` (just tested it). Thank you @kvnthomas98
