### ISSUE TITLE
ARAX still generating ARS errors and TRAPI errors

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2089]
If we take a look at the last 10 queries sent from ARS to ARAX in TEST, the results don't look so good:
![image](https://github.com/RTXteam/RTX/assets/12707718/97dc4ff4-4708-49a2-b8ee-05afd9a2ba9b)

Here's one: It seems that ARS listed ARAX a 598. Why? Yet there seems to be a response from us
https://arax.ci.transltr.io/?r=21cdbda8-2640-4c55-b577-b71828e03623
But this response has a validation error. Where did that validation error come from and can we fix it?

**Comment by isbluis** [comment]
Hi @edeutsch .  For the PK you give as an example, ARAX is listed as a `200`, not `598`?  (number 3. on the screenshot)

As for the validation error, maybe someone understands what this means:
```
Errors:
* Knowledge Graph Edge Sources Retrieval Source Resource Id Infores Not:
=> One (or more) Infores value(s) is not a valid well-formed CURIE
	$ global
		# ara-arax:
		- edge_id: 
```

**Comment by edeutsch** [comment]
> Hi @edeutsch . For the PK you give as an example, ARAX is listed as a `200`, not `598`? (number 3. on the screenshot)

@isbluis  It's true. How about we look at number 2 then:

https://arax.ci.transltr.io/?r=119e948b-d26f-4fdf-8a9e-3f97a06f082d

**Comment by edeutsch** [comment]
> As for the validation error, maybe someone understands what this means:
> 
> ```
> Errors:
> * Knowledge Graph Edge Sources Retrieval Source Resource Id Infores Not:
> => One (or more) Infores value(s) is not a valid well-formed CURIE
> 	$ global
> 		# ara-arax:
> 		- edge_id: 
> ```

The error is "One (or more) Infores value(s) is not a valid well-formed CURIE"

A CURIE is a namespace:accession like UniProtKB:P07264 or infores:chembl

The value "ara-arax" is not a well-formed curie because (at minimum) is has no namespace.

The edge_id value is cut off from your snippet, but a way to find and fix the problem would be to look into the TRAPI to find the edge_id in question and determine where that edge is coming from and fix it.

**Comment by isbluis** [comment]
From the ten ARAX queries above:

- Query 5 only has a validation warning since there are no results.  Expected.
- Queries 3, 4, and 9 yield the previously reported "ara-arax" bad CURIE.  I recreated the queries in dev, and this issue is not present, so it should get resolved on the next KG release?
![image](https://github.com/RTXteam/RTX/assets/37852256/eb5e3d38-49e9-4b72-a168-237403e08ef2)

- All other queries are in a "Running" state.  Perhaps zombie processes?  Not sure how to get to those:
![image](https://github.com/RTXteam/RTX/assets/37852256/2818d588-8900-46a7-9919-e18d6426e854)

![image](https://github.com/RTXteam/RTX/assets/37852256/46ec6ed0-a684-4808-82db-4000c91c3fa6)

**Comment by edeutsch** [comment]
great! Can you post here a repro query that we can use to test this?

**Comment by isbluis** [comment]
To verify/repro the "bad CURIE" issue, post the following query on the JSON input of the UI, open the first result (Resveratrol), and click on the single edge; you should **not** see the "ara-arax" entry.

```
{
  "edges": {
    "t_edge": {
      "attribute_constraints": [],
      "knowledge_type": "inferred",
      "object": "on",
      "predicates": [
        "biolink:treats"
      ],
      "qualifier_constraints": [],
      "subject": "sn"
    }
  },
  "nodes": {
    "on": {
      "categories": [
        "biolink:Disease"
      ],
      "constraints": [],
      "ids": [
        "MONDO:0004975"
      ],
      "is_set": false
    },
    "sn": {
      "categories": [
        "biolink:ChemicalEntity"
      ],
      "constraints": [],
      "is_set": false
    }
  }
}
```

**Comment by isbluis** [comment]
Verified this is working in CI:  https://arax.ci.transltr.io/?r=155769

![image](https://github.com/RTXteam/RTX/assets/37852256/cb46e983-fd97-4670-965b-cccc608adbd1)
