### ISSUE TITLE
Rewiring ITRB instances to use rtx.ai Plover

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2090]
Since the resolution of the problem where all ITRB hosted Plover instances are serving the wrong KG2 (#2079) are not easily resolved and many problems are fixed with KG2.8.3 and the consortium code freeze deadline is looming, I will rewire the PloverDB setting in config_dbs.json from
```
   "plover": {
      "dev": "http://kg2cplover.rtx.ai:9990",
      "test": "https://kg2cploverdb.test.transltr.io",
      "prod": "https://kg2cploverdb.transltr.io"
   },
```
to:

```
   "plover": {
      "dev": "http://kg2cplover.rtx.ai:9990",
      "test": "http://kg2cplover.rtx.ai:9990",
      "prod": "http://kg2cplover.rtx.ai:9990"
   },
```

Ideally PloverDB in ITRB will be fixed very soon and we can back this out.

Any objections?

**Comment by edeutsch** [comment]
I can confirm that running query graph
```
{"nodes": {"n00": {"ids": ["RTX:KG2c"]}}, "edges": {}}
```
on https://arax.ci.transltr.io/ now yields:
![image](https://github.com/RTXteam/RTX/assets/12707718/02c99310-0e09-42d3-a2a7-b1dfeb9a6d75)

**Comment by isbluis** [comment]
When I run that same query on prod, I get this:
![image](https://github.com/RTXteam/RTX/assets/37852256/66f55ce1-aca4-4ade-b086-b7344aa298db)

Why the discrepancy, and what is the actual version?

https://arax.ncats.io/index.html?r=155879

**Comment by edeutsch** [comment]
So I got it wrong when I declared elsewhere that we were at KG2.8.3 everywhere. A full KG2.8.3 has not made it to TEST and PROD yet.

We are in a weird state where the KG2 front end code thinks it is serving 2.8.3, but the back end PloverDB is not working as intended due to ongoing saga with Plover. But it looks like resolution to that is very close.

**Comment by edeutsch** [comment]
This is now reverted in `master`

I will request deployment to TEST tonight.

@saramsey please get all your latest code merged into `itrb-test` branch in PloverDB repo tonight if at all possible.

If it looks look in TEST tomorrow, we will request deployment to PROD on Friday

**Comment by saramsey** [comment]
Can we close this out now?

**Comment by edeutsch** [comment]
yes, this is all resolved, closing.
