### ISSUE TITLE
Retire DTD model in ARAX expand and ARAX overlay modules

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#2091]
Hi all,

As we discussed previously in one of our AHM meeting, it seems like people are now more interested in using xDTD (the creative mode) and seldomly use DTD model (the model without RL, the model mentioned in ARAX paper). I'm wondering if we can retire this model (please see this [comments](https://github.com/RTXteam/RTX/issues/2056#issuecomment-1633194634)). Any objections about this idea.

**Comment by chunyuma** [comment]
Hi @edeutsch, the old DTD is mainly used in [ARAX expand](https://github.com/RTXteam/RTX/blob/7d3ed66262415c18cc48fae2b0bc4b23c7f79ab1/code/ARAX/ARAXQuery/ARAX_expander.py#L737-L739) and [ARAX Overlay](https://github.com/RTXteam/RTX/blob/7d3ed66262415c18cc48fae2b0bc4b23c7f79ab1/code/ARAX/ARAXQuery/ARAX_overlay.py#L802-L861) modules.

**Comment by chunyuma** [comment]
I've merged the branch KG2.8.4c and retire_DTD. Now in the branch KG2.8.4c, the old DTD model has been retired.

**Comment by saramsey** [comment]
@chunyuma: thank you! Can this issue be closed out then?

**Comment by saramsey** [comment]
Just checking back on this @chunyuma ?
