### ISSUE TITLE
Add a few more example queries

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2092]
There are a rather limited set of query types that are going to be in production. Let's get them front and center for easier smoke testing. In addition to our one core example (which isn't even one that the Translator UI asks),
![image](https://github.com/RTXteam/RTX/assets/12707718/b79a22ed-fa8a-4759-a759-adf7352cf505)

let's add queries contained within these real UI examples:
2d1c6078-13a6-43b8-bc43-03b48b72f21b	___ treats Castleman disease
3f943262-5c04-4f28-877a-9c12f20bee7b	___ affects ZBTB7A

(i.e. extract the submitted queries from those historical queries and make those {or similar} additional example queries for ARAX GUI)

**Comment by isbluis** [comment]
Shall we also update the DSL example?  How about the list of `ids` in the pull-down menu?  Those look quite old.

**Comment by edeutsch** [comment]
Go for it if you want, but I don't use those.

**Comment by isbluis** [comment]
Added the examples
