### ISSUE TITLE
Database manager needs the ability to *optionally* download files via a CLI option (default off)

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2098]
https://github.com/RTXteam/RTX/blob/af5482d5bdc74dac9926462bcc6dab495ba6e6de/code/ARAX/ARAXQuery/ARAX_database_manager.py#L342

**Comment by saramsey** [comment]
nevermind, looks like it is debug code

**Comment by edeutsch** [comment]
I commented this out and replaced it with the following line:
https://github.com/RTXteam/RTX/blob/af5482d5bdc74dac9926462bcc6dab495ba6e6de/code/ARAX/ARAXQuery/ARAX_database_manager.py#L343

I thought we agreed that it was never going to work properly on most instances due to lack of credentials. And even if there are credentials we probably don't want the code to be doing this. This code was being triggered a lot during ITRB deployments because download_databases.py wasn't doing what we wanted. And since that didn't work, this code was being triggered, but just causing problems.

Are there any cases where we **do** want this code to be run?

**Comment by saramsey** [comment]
I don't know, I wanted to run the ARAX test suite on a fresh new instance and thus wanted to use `ARAX_database_manager.py` to (in a CLI-commanded mode) download the databases. I ran `python3 ARAX_database_manager.py -f` and it refused to download the databases unless I uncommented that line 343. Perhaps I ran it wrong.

**Comment by saramsey** [comment]
Current thinking is that in order to be able to deploy new database versions (i.e., for a new KG2c release) to `cicd.rtx.ai`, it would be nice to have ARAX_database_manager.py be able to do downloads, at least with an optional (default off) argument.

**Comment by saramsey** [comment]
Maybe somewhere in there, the database manager already has this capability?  I am not sure. I have added an agenda item to Wednesday's AHM to discuss. I am very confused about the state of the database manager. It is a rather pleiotropic software module.

**Comment by saramsey** [comment]
I've created a branch[ `issue-2098`](https://github.com/RTXteam/RTX/tree/issue-2098) to work on this issue.

**Comment by saramsey** [comment]
@edeutsch, what if we just change these two lines of code to issuing an ERROR message and returning a status code 500?

https://github.com/RTXteam/RTX/blob/2e7c407f2ba4ac6e531add174515fba98c84df0f/code/ARAX/ARAXQuery/ARAX_query.py#L89-L90

My reasoning is that I think maybe we don't want any updating of databases at query time. Rather, I wonder if we want the database symlinks (if at all) to be updated only at application start-up. However, the `ARAXQuery` object is created at _query_ time, as we can see here in `query_controller.py`:  

https://github.com/RTXteam/RTX/blob/2e7c407f2ba4ac6e531add174515fba98c84df0f/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py#L72

**Comment by edeutsch** [comment]
I agree, moving this call just to only at startup sounds good.
There are probably lots of things that we do with every single query that could probably done at startup and stored for later use instead. Optimization opportunity!

**Comment by saramsey** [comment]
Done; the call to `check_databases` has been moved to app startup and out of `ARAX_query.py`.

But I will keep this issue open until we can figure out what to do with this line of code:
https://github.com/RTXteam/RTX/blob/993f192cfeb68885be1352f00fa15e74dad319c5/code/ARAX/ARAXQuery/ARAX_database_manager.py#L342

**Comment by saramsey** [comment]
Commit 1bc2ad8 should fix this, at least for ARAX_overlay. 

Here is a baseline elog excerpt showing the unwanted behavior, on `/beta`:
```
2023-08-30T21:26:24.722749 DEBUG: (1231) [] Applying Overlay to Message with parameters {'actio
n': 'compute_ngd', 'virtual_relation_label': 'N1', 'subject_qnode_key': 'n00', 'object_qnode_ke
y': 'n01'}
ARAX_database_manager is performing check_versions()
Local version of cohd_database matches the remote version
Local version of graph_database matches the remote version
Local version of log_model matches the remote version
Local version of curie_to_pmids matches the remote version
Local version of node_synonymizer matches the remote version
Local version of dtd_prob matches the remote version
Local version of kg2c_sqlite matches the remote version
Local version of kg2c_meta_kg matches the remote version
Local version of fda_approved_drugs matches the remote version
Local version of autocomplete matches the remote version
Local version of explainable_dtd_db matches the remote version
Local version of xcrg_embeddings matches the remote version
Local version of xcrg_increase_model matches the remote version
Local version of xcrg_decrease_model matches the remote version
2023-08-30T21:26:24.736793 DEBUG: (1231) [] Computing NGD
```
and the same log snippet on `/test`, after the above commit is deployed:
```
2023-08-30T21:23:55.646984 DEBUG: (887) [] Applying Overlay to Message with parameters {'action
': 'compute_ngd', 'virtual_relation_label': 'N1', 'subject_qnode_key': 'n00', 'object_qnode_key
': 'n01'}
2023-08-30T21:23:55.661214 DEBUG: (887) [] Computing NGD
```

**Comment by saramsey** [comment]
Since this works, I'm going to merge this commit into `master`

**Comment by saramsey** [comment]
There is one other script that seems to reference the Database Manager, but I think it is only run via the CLI and not via ARAXQuery, right?

https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Infer/scripts/ExplianableDTD_db.py

**Comment by saramsey** [comment]
I did a code audit to see if there are other references to `ARAXDatabaseManager` that may come from "inside" ARAX (i.e., downstream of `ARAXQuery`), and I didn't see any. I think Overlay was the one that slipped through the cracks.

**Comment by saramsey** [comment]
superseded by #2171
