### ISSUE TITLE
Move to BioThingsExplorer?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#210]
Per the presentation of @erikyao: see the [Github Repo](https://github.com/kevinxin90/RTX_BioThings_Explorer) and [the presentation](https://docs.google.com/presentation/d/1AgncJ1jlI-_gPry6LdRWRqmkQx1F4fzcG-gnTXqTS0o/edit?usp=sharing).

Should we explore moving to this completely?

**Comment by edeutsch** [comment]
Sounded to me like this was a done deal for some reason. I don't really know the answer here. It sounded like Steve was very positive on this.

But I do have some concerns that we should chat about sometime.

**Comment by saramsey** [comment]
The question mark was intended to convey exploratory discussions and to suggest some preliminary testing to assess performance.

**Comment by erikyao** [comment]
Just FYI:

- Query modules in BioThings backend are hosted at [RTX_BioThings_Explorer](https://github.com/kevinxin90/RTX_BioThings_Explorer)
- Their server side code is at [biothings_explorer_web](https://github.com/biothings/biothings_explorer_web)

**Comment by dkoslicki** [comment]
Closing due to #788 and current integration with BTE per #722
