### ISSUE TITLE
upload new KG2.8.Xpre and KG2.8.Xc artifacts to translator-lfs-artifacts repo

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2101]
This is a leftover task from the KG2.8.3c rollout checklist ([RTXteam/RTX issue 2056](https://github.com/RTXteam/RTX/issues/2056)), which we could not complete because I don't have write access to the [`ncats/translator-lfs-artifacts` ](https://github.com/ncats/translator-lfs-artifacts/)project area. Saving this for @amykglen when she returns in mid-Sept. 2023.

**Comment by sundareswarpullela** [comment]
Hey Amy, can you upload kg2 artifacts for KG2.8.4c to [translator artifacts repo](https://github.com/ncats/translator-lfs-artifacts/) for the completion of all checkpoints in KG2.8.4c build and deployment issue [#2073](https://github.com/RTXteam/RTX/issues/2073). 
Note: The above issue has been closed and these steps are moved to the current issue #2101

**Comment by amykglen** [comment]
hi @sundareswarpullela - do you still not have the ability to push to the NCATS translator lfs repo? I see you're already listed in the `CODEOWNERS`, and I just added you as a 'collaborator' on the repository with write access. so I think you should be able to upload those files now?

**Comment by sundareswarpullela** [comment]
Sounds good, thanks! I'll try uploading the files now.

**Comment by amykglen** [comment]
also, just to clarify - Steve and Lili were already entered as collaborators for that repo with 'write' access, though Steve is not listed in `CODEOWNERS`, which probably means he can't push successfully.

**Comment by sundareswarpullela** [comment]
@acevedol can you please approve this [PR](https://github.com/ncats/translator-lfs-artifacts/pull/8) to merge KG2.8.4 artifacts to main branch of [translator-ifs-artifacts](https://github.com/ncats/translator-lfs-artifacts) repo.

**Comment by sundareswarpullela** [comment]
The files have been uploaded. Completed the KG2.8.4c rollout checklist #2073.

**Comment by saramsey** [comment]
Thank you @sundareswarpullela and @amykglen
