### ISSUE TITLE
please review updated issue template for correctness

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2108]
I've extensively modified (and I hope improved) the ARAX KG2c roll-out issue template. Need to have someone review these changes for technical correctness. Thanks.

https://github.com/RTXteam/RTX/blob/master/ISSUE_TEMPLATES/kg2rollout.md

**Comment by saramsey** [comment]
any progress on this @sundareswarpullela ?

**Comment by sundareswarpullela** [comment]
Reviewed and checked for issues. Everything seems to be good. I think we can close this issue.

**Comment by amykglen** [comment]
looks awesome to me! thanks, @saramsey!
