### ISSUE TITLE
Uncaught IndexError if ARAX queries a KP that doesn't implement domain_range_exclusion

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2110]
The standard acetaminophen TRAPI query is giving errors on `arax.ncats.io/kg2`:

> 2023-08-22T16:42:54.893244 ERROR: [UncaughtError]    An uncaught error was thrown while trying to Expand using infores:rtx-kg2 (local). Error was: Traceback (most recent call last): File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/../../../../../ARAX/ARAXQuery/ARAX_expander.py", line 822, in _expand_edge_kg2_local answer_kg = kg2_querier.answer_one_hop_query(one_hop_qg) File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/../../../../../ARAX/ARAXQuery/Expand/kg2_querier.py", line 82, in answer_one_hop_query filtered_plover_answer = eu.filter_response_domain_range_exclusion(plover_answer, query_graph, log) File "/mnt/data/orangeboard/kg2/RTX/code/ARAX/ARAXQuery/Expand/expand_utilities.py", line 609, in filter_response_domain_range_exclusion edge_keys_to_filter = {edge_id for edge_id, edge in plover_answer['edges'][qg_edge_key].items() if edge[7] == "True"} File "/mnt/data/orangeboard/kg2/RTX/code/ARAX/ARAXQuery/Expand/expand_utilities.py", line 609, in <setcomp> edge_keys_to_filter = {edge_id for edge_id, edge in plover_answer['edges'][qg_edge_key].items() if edge[7] == "True"} IndexError: list index out of range

**Comment by sundareswarpullela** [comment]
Is production on the latest Plover @saramsey?

**Comment by sundareswarpullela** [comment]
This error should go away once production Plover is updated to the latest Plover code, Expand doesn't seem to be receiving `domain_range_exclusion` key from Plover.

**Comment by saramsey** [comment]
Sundar, you are right. However, I feel that `expand_utilities.py` could handle this problem more gracefully than an uncaught error, right?  Maybe give a specific error message about the missing `domain_range_exclusion` edge property?  This is not a urgent priority, however. But seems worth doing.

**Comment by sundareswarpullela** [comment]
This issue has been fixed 
<img width="923" alt="Screenshot 2023-08-24 at 11 44 04 AM" src="https://github.com/RTXteam/RTX/assets/110754869/8c819e41-c5e3-49d1-8ef9-576554a58a16">

Instead of erroring out, it will generate the above warning.

**Comment by saramsey** [comment]
Thank you Sundar. This is good.
