### ISSUE TITLE
Smoke test viewer

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2116]
@isbluis can you put together a viewer for Shervin's testing results in the ARAX GUI?

So a new tab on the left or bottom.
See Slack convo for more details.
A few key URLs here:
https://utility.ci.transltr.io/arstest/api/

Two tables, one for smoke and one for load. Looking something like this:
![image](https://github.com/RTXteam/RTX/assets/12707718/7bd10790-fae5-416a-a8c5-f41aaf75a535)

**Comment by isbluis** [comment]
An initial version is available in _devLM_:  https://arax.ncats.io/devLM/index.html?systest=1

![image](https://github.com/RTXteam/RTX/assets/37852256/77b66174-8763-4241-bfda-702cd8b90b4b)

**Comment by edeutsch** [comment]
Looks great!

To me "n/a" means not applicable, which is not really appropriate I think. If it's an Error, can you write "Error" there?

Translating the CURIEs to names would be a nice touch, although I think it would be great to Shervin would do it instead and provide it in the data.

I think the "deny" should be red. And then any non-zero value in that row should be red. Because these are not wanted.

Otherwise, great! Ship it! There might be an opportunity to show it off at the Tuesday Architecture call.

**Comment by isbluis** [comment]
Thanks!

I do tend to interpret "n/a" as "not available", but I have changed that to display "E" for error.

Also added translation of CURIES to names, and updated some of the formatting.

Still a few things to update, but should be good enough to show.

**Comment by edeutsch** [comment]
looks great, thanks.

ARAX is showing the effects of the overlimit:
![image](https://github.com/RTXteam/RTX/assets/12707718/4563dc1d-b26e-429e-a7c9-3f8a4ea1d75b)

ARAX results from the smoke test is reasonable, although some issues that bear investigation:
![image](https://github.com/RTXteam/RTX/assets/12707718/a01994db-824f-4de7-94d8-e7079c2b4501)

**Comment by isbluis** [comment]
Updated the viewer based on latest ARS JSON format and added links to historical results.
Are there other pending aspects to this issue, or is it good to close?

**Comment by edeutsch** [comment]
Looks good to me, thanks
https://arax.ci.transltr.io/?systest=1

The smoke test doesn't seem to be working much anymore, just a single result from one agent
![image](https://github.com/RTXteam/RTX/assets/12707718/65e74a66-dece-4da2-850b-04261a40ab43)

but I assume that is an ARS problem not a viewer problem.
Closing.
