### ISSUE TITLE
upload KG2.8.3c TSV tarball to Knowledge Graph Exchange

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2117]
The Knowledge Graph Exchange (KGE) still seems to be up and running. Team Unsecret Agent would like to have our KG2c TSV files archived if possible. So can we please archive the KG2.8.3c TSV tarball on the KGE?

Thanks,
Steve

**Comment by edeutsch** [comment]
I'm curious what's in the knowledge graph exchange. What does it look like? I can't login. Maybe I should ask for a login..

**Comment by saramsey** [comment]
Different dump files for different large knowledge graphs. List of KGs available is: 

<img width="533" alt="Screenshot 2023-08-28 at 8 16 18 PM" src="https://github.com/RTXteam/RTX/assets/5562107/7715c64d-7958-432d-b391-92d6ea7df136">

**Comment by saramsey** [comment]
Not sure how frequently anyone is adding updates to KGs via the KGE. Last I heard from Richard it was now unsupported. On the other hand, we got a request to host a TSV tarball for KG2c and it beats hosting our own (due to licensing concerns).

**Comment by sundareswarpullela** [comment]
To do this, I am following the steps [here](https://github.com/RTXteam/RTX/tree/master/code/kg2c#upload-kg2c-to-kge-knowledge-graph-exchange-deprecated) but the file `content_metadata.json` is not getting generated when I run `bash -x kgx-validation-and-metagraph.sh` which uses the `kgx` module.

**Comment by saramsey** [comment]
@sundareswarpullela Did using the latest version of python help with this?

**Comment by sundareswarpullela** [comment]
The KGX code is currently running on `buildkg2c.rtx.ai`. I think it'll work now. Will update here.

**Comment by saramsey** [comment]
Thank you for the update, @sundareswarpullela !

**Comment by sundareswarpullela** [comment]
The `content_metadata.json` file is not getting generated by `kgx` package. Is it mandatory to have that?

**Comment by saramsey** [comment]
Hmm, thank you for letting me know. I think maybe it is.  Is this a known bug in kgx?  Would using the latest version of kgx help?  Forgive me, the details are hazy but I have a feeling you explained this all to me before.

**Comment by saramsey** [comment]
So... using the latest kgx package does not help?

**Comment by saramsey** [comment]
Does this command not work?
```
```

**Comment by sundareswarpullela** [comment]
`content_metadata.json` has been generated. The issue is with the `kgx validate` command that runs before the `kgs graph-summary` function in the `kgx-validation-and-metagraph.sh` file.

**Comment by saramsey** [comment]
Thank you @sundareswarpullela can you please update the issue template to reflect this updated information about how to generate the file?

**Comment by sundareswarpullela** [comment]
KG2.8.4c has been updated, will generate `content_metadata.json` for KG2.8.3c within the week.

**Comment by saramsey** [comment]
Thanks, Sundar

**Comment by sundareswarpullela** [comment]
`content_metadata.json` has been generated for `KG2.8.3c`. The files `nodes.tsv`, `edges.tsv` and `content_metadata.json` are present in the instance `buildkg2c.rtx.ai` in the directory `~/kg2.8.3_kgx`. @sundareswarpullela and @saramsey will upload the files on 10/26/2023 at 10am PST during their one on one meeting.
