### ISSUE TITLE
investigate whether RTXConfiguration class can be a singleton

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2121]
The first time we call `import RTXConfiguration` it takes 80 ms to run, and each subsequent time we run `import RTXConfiguration, it takes 40 ms to run. 

Verified using this test:
```
(venv) sramsey-laptop:code sramsey$ cat test_rtxconfig.py
#!/usr/bin/env python3

import timeit

print(timeit.timeit('import RTXConfiguration'))
print(timeit.timeit('import RTXConfiguration'))
print(timeit.timeit('import RTXConfiguration'))
print(timeit.timeit('import RTXConfiguration'))
print(timeit.timeit('import RTXConfiguration'))
```
which produced this output:
```
(venv) sramsey-laptop:code sramsey$ python3 test_rtxconfig.py
0.08143983299669344
0.0494159999943804
0.04950341700168792
0.04939062499033753
0.04940991698822472
```
(with `DEBUG=False` in `RTXConfiguration.py`).

**Comment by edeutsch** [comment]
I think it would be groovy if the first time an object was created it would gather all information into class variables, and then all subsequent object creations would look and simply pull the information out of the class variables without doing any "work".

**Comment by saramsey** [comment]
We call the `RTXConfiguration` constructor in at least 45 places in the code-base underneath `RTX/code/ARAX`. I'm looking into whether any of them are in performance-critical code. I expect some of them are.

**Comment by saramsey** [comment]
On average, it takes ~700-730 ms to run the code
```
import RTXConfiguration
x = RTXConfiguration.RTXConfiguration()
```
based on this test (with `DEBUG = False` in the `RTXConfiguration.py` module:
```
(venv) sramsey-laptop:code sramsey$ python -m timeit 'import RTXConfiguration; x = RTXConfiguration.RTXConfiguration()'
500 loops, best of 5: 704 usec per loop
(venv) sramsey-laptop:code sramsey$ python -m timeit 'import RTXConfiguration; x = RTXConfiguration.RTXConfiguration()'
500 loops, best of 5: 733 usec per loop
```

**Comment by edeutsch** [comment]
I hypothesize that we could do:

```
class RTXConfiguration:

    _GET_FILE_CMD = "scp araxconfig@araxconfig.rtx.ai:config_secrets.json "

    config_data = None

    # ### Constructor
    def __init__(self):
...
```

and in __init__() if config_data is None, then do all the hard work and populate config_data.

and if config_data is not None, then __init__() should just pull the needed information out of config_data and return it without further ado.

Because of the flatness of self attributes, it's a pretty big refactor...

**Comment by saramsey** [comment]
Yes, potentially a big refactor. I'll open a branch. Worst case, I completely mess up the branch and we abandon it.

**Comment by saramsey** [comment]
I've created branch [`issue-2121`](https://github.com/RTXteam/RTX/tree/issue-2121) to experiment with this

**Comment by saramsey** [comment]
OK, commit `06e9048` turns `RTXConfiguration` into a classic singleton class.  

First instantiation takes nearly two seconds, second is instantaneous:
```
ARAX 1.4.3
Total elapsed time: 1.94 ms
ARAX 1.4.3
Total elapsed time: 0.00 ms
```

**Comment by saramsey** [comment]
Thank you David!

**Comment by saramsey** [comment]
I've coded up a fix for the five places where @dkoslicki helpfully found calls to RTXConfiguration mutator methods.  All pytest tests passing in 618.74 seconds:
```
========================== 135 passed, 129 skipped, 62692 warnings in 618.74s (0:10:18) ===========================
```

**Comment by saramsey** [comment]
> I hypothesize that we could do:
> 
> ```
> class RTXConfiguration:
> 
>     _GET_FILE_CMD = "scp araxconfig@araxconfig.rtx.ai:config_secrets.json "
> 
>     config_data = None
> 
>     # ### Constructor
>     def __init__(self):
> ...
> ```
> 
> and in **init**() if config_data is None, then do all the hard work and populate config_data.
> 
> and if config_data is not None, then **init**() should just pull the needed information out of config_data and return it without further ado.
> 
> Because of the flatness of self attributes, it's a pretty big refactor...

Yes, the solution I implemented is along these lines (classic singleton class).

**Comment by saramsey** [comment]
Well, I spoke too soon. There was a flaw in my empirical testing. I ended up having `force_local=True` for the test of the new code and `force_local=False` for the test of the current master-branch code, which I think invalidates the benchmarking. Sorry.

**Comment by saramsey** [comment]
OK, I'm getting 378 sec for the issue-2121 branch and 489 sec for the master branch. Need to repeat the test a few times but it still looks like we are a bit faster with the singleton class (which is what I would expect).
