### ISSUE TITLE
Some ARAX queries never terminate properly

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2123]
In addition to #2114, there is also a problem with ARAX

For example, right now it seems that there are two ARAX processes that are stuck:
![image](https://github.com/RTXteam/RTX/assets/12707718/3bc22200-8124-4b11-84e7-088ef68b88ed)

Where are they sticking?
Now that we have PID tracking in the logs, it may be easier to figure this out.
Following PID 2581, the final entry in the captain's log is:
```
2023-08-30T17:17:40.624985 INFO: (2581) [] Attempting to send to callback URL: https://ars.ci.transltr.io/ars/api/messages/3237cf2e-f4e3-415a-8ecd-587a7110635b
```

Following PID 2562, the final entry in the captain's log is:
```
2023-08-30T17:17:32.498733 INFO: (2562) [] Attempting to send to callback URL: https://ars.ci.transltr.io/ars/api/messages/03de6046-f6cf-4f23-8ef0-d7846d2dc8b9
```

It looks like we need to make this more robust with some timeouts and retries and such. and then a graceful exit if it doesn't work.

**Comment by saramsey** [comment]
See issue #2128 which may or may not be a clue in this saga.

**Comment by edeutsch** [comment]
I think this is fixed in dev and CI, but test and prod is still very much plagued by it. Hopefully when test and prod are unfrozen, and these fixes are propagated there, this will be resolved.

**Comment by saramsey** [comment]
Well, I suppose Tyler can always run queries against CI for the purpose of generating results for his presentation (there will not be a live demo as I understand).

**Comment by saramsey** [comment]
In today's meeting, did we determine that we have an issue with asyncqueries, in which invalid query TRAPI leads to an error message being returned to the client, but for some reason the query tracker doesn't record that the system responded to the client?

**Comment by saramsey** [comment]
Thanks, @edeutsch.

**Comment by edeutsch** [comment]
Production and all other instances are running the latest code. But still a problem. Created a fresh issue #2245 and closing this one.
