### ISSUE TITLE
module estimate_coverage.py references "sqlitedict" which is not in the requirements.txt

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2125]
This module:
https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Overlay/ngd/estimate_coverage.py

at line 16 imports a python package "sqlitedict" which is not in the requirements.txt:
https://github.com/RTXteam/RTX/blob/806859c1ea02cf77f53747d9e09543fd6ce22ed9/code/ARAX/ARAXQuery/Overlay/ngd/estimate_coverage.py#L16

I'm wondering if it should be added to the [requirements.txt](https://github.com/RTXteam/RTX/blob/master/requirements.txt)?

**Comment by chunyuma** [comment]
Hello @saramsey, I'm so sorry for the late response. For some reasons, I don't know why I can't receive the message from Github. I just saw this issue.

For this issue, it seems like we indeed need to add the `sqlitedict` to requirements.txt. This is a line added by Amy and I think she forgot to add it to the requirements.txt. I have added it to that file.

**Comment by amykglen** [comment]
I'd suggest maybe just deleting the entire `estimate_coverage.py` script - it's a very old script that is not used by running ARAX code or by the NGD build code - it was used when we were determining the best ngd build strategy, years ago. I don't think it's been maintained and likely isn't working for various reasons now..

**Comment by saramsey** [comment]
Good idea, if it's deprecated let's delete it.

**Comment by amykglen** [comment]
I just deleted that old script (in the `dev` branch, since we're in a freeze) - closing

**Comment by amykglen** [comment]
I also deleted `sqlitedict` from `requirements.txt` in the `dev` branch since none of our code uses it anymore
