### ISSUE TITLE
kg2_querier.py is double-querying ploverdb

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2128]
At this line of code,
https://github.com/RTXteam/RTX/blob/6fbe3171f66bc4fd7a842fcbbde66679cf6e47b9/code/ARAX/ARAXQuery/Expand/kg2_querier.py#L187

`kg2_querier.py` is querying PloverDB with the `/query` function, but it should have a trailing slash or else (as currently built and deployed) PloverDB returns a 308 (permanent redirect) status code, forcing poor Python requests to do a second query. See the long thread about this in the `#deployment` channel in the `ARAXTeam` Slack workspace. Tagging @edeutsch and @amykglen so they are in the loop on this.

**Comment by saramsey** [comment]
I've already tested the fix _in situ_ on `arax.ncats.io/kg2test`, so I am going to do the fix in the `master` branch.

**Comment by edeutsch** [comment]
@saramsey  So while this seems to fix the problem, I can't help but wonder if this is a config error on the PloverDB deployment setup. It feels to me like we have switched from doing the correct thing to do the incorrect thing because the remote is misconfigured.

Maybe the ploverdb host Apache ProxyPass config error? A trailing slash *should* be present when the entity before is a directory, but it should *not* be present for a query endpoint like this, right?
We don't have this issue with ARAX and KG2 /query endpoints, right? or do we?

**Comment by saramsey** [comment]
I agree, by changing from `/query` to `/query/`, we are catering to an odd server behavior in this case. 

KG2 and ARAX do not behave that way. If they did, the following command would not work (since the `-L` option is not included which would specify to follow redirects):
```
curl -s -I -X GET -H 'accept: application/json'  https://arax.ncats.io/api/rtxkg2/v1.4/status | grep 'HTTP/'
HTTP/1.1 200 OK
```
but in fact, it does work. Same goes for ARAX:
```
curl -s -I -X GET -H 'accept: application/json'  https://arax.ncats.io/api/arax/v1.4/status | grep 'HTTP/'
HTTP/1.1 200 OK
```
You can see, on PloverDB, it doesn't work:
```
 curl -s -I -X POST -H 'accept: application/json' https://kg2cploverdb.ci.transltr.io/query
HTTP/2 308
date: Wed, 13 Sep 2023 02:42:04 GMT
content-type: text/html; charset=utf-8
content-length: 271
location: https://kg2cploverdb.ci.transltr.io/query/
server: nginx/1.23.2
```

**Comment by edeutsch** [comment]
I think it would be a good idea to ask Amy to fix this in the PloverDB implementation sometime.

**Comment by saramsey** [comment]
Tagging @amykglen let's see if we can get this fixed in the next release of PloverDB

**Comment by saramsey** [comment]
@edeutsch this is now logged as [RTXteam/PloverDB issue 51](https://github.com/RTXteam/PloverDB/issues/51)

I've already committed a fix to the RTXteam/PloverDB `main` branch:
https://github.com/RTXteam/PloverDB/commit/4bd64040c302fcee9c22560d1a60895c73d72833

**Comment by saramsey** [comment]
fixed PloverDB on the server-side (issue 51), but now this breaks KG2.

**Comment by edeutsch** [comment]
great! yes, if merged into master, then probably gets auto-deployed and we need to update KG2 to unfix the workaround

**Comment by saramsey** [comment]
working on it now

**Comment by saramsey** [comment]
OK, commit `974c989` should do the trick. I'm going to manually deploy it to `/kg2beta` to try it out.

**Comment by saramsey** [comment]
see posts on `#deployment` slack channel...

**Comment by saramsey** [comment]
I believe `/kg2beta` and `/kg2test` are working fine now after the patch. And `/kg2` is working with with unpatched code since it is evidently querying the production PloverDB.
