### ISSUE TITLE
Example 1 query has orphan nodes

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2132]
New in TRAPI validator 3.9.2 is the checking for orphan nodes (i.e. nodes not connected to any edges)

Apparently in our example 1 query, there are a lot of them. It's possible that they come from MolePro, who stated today they don't feel this is a problem. so far this is a warning. Is it something we should fix? I don't know.

https://arax.ncats.io/test/?r=167964

```
Warnings:
* Knowledge Graph Node Id Unmapped:
=> Node identifier found unmapped to target categories for node
	$ global
		# ['biolink:Protein']:
		- node_id: 
			CHEMBL.COMPOUND:CHEMBL783
			CHEMBL.TARGET:CHEMBL2243
			CHEMBL.TARGET:CHEMBL4523964
			CHEMBL.TARGET:CHEMBL4794
			PUBCHEM.COMPOUND:10150081
			PUBCHEM.COMPOUND:10909430
			PUBCHEM.COMPOUND:16139605
			PUBCHEM.COMPOUND:24795069
			PUBCHEM.COMPOUND:3010818
			PUBCHEM.COMPOUND:34755
			PUBCHEM.COMPOUND:38853
			PUBCHEM.COMPOUND:5486971
			PUBCHEM.COMPOUND:71306834
			PUBCHEM.COMPOUND:90472060
			PUBCHEM.COMPOUND:9811834
			UNII:09495UIM6V
			UNII:37CQ2C7X93
			UNII:56588OP40D
			UNII:6SC756X51V
			UNII:7XL5ISS668
			UNII:8K80YB5GMG
			UNII:9013DUQ28K
			UNII:91X1KLU43E
			UNII:A57KX1VL5P
			UNII:B72HH48FLU
			UNII:DLG4EML025
			UNII:G8RGG88B68
			UNII:JX56W9N61Q
			UNII:M89N0Q7EQR
			UNII:T4H8FMA7IM
			UNII:TTD90R31WZ
			UNII:XRO4566Q4R
```

**Comment by edeutsch** [comment]
Clearly not just from MolePro, as evidenced by this:
https://arax.ncats.io/test/?r=2a167dcf-4994-49a2-8a08-b57b8b667e8b

Do we think that we have a process to clean up orphan nodes?

Should we?

**Comment by saramsey** [comment]
How would I find the orphan node from the linked query results?  (Sorry for this dumb question).

**Comment by edeutsch** [comment]
You can bring up a Response in the ARAX GUI, click on Dev Info on the left and then click view raw response, and then CTRL+F for the node_id.

I just tried it, and it works.

But it also seems to reveal the the first one I tried *IS* linked in the KG.
So either I'm confused or there's a bug in the validator.
I will follow up with Richard.

**Comment by edeutsch** [comment]
OH, nevermind, sorry, that warning does NOT mean what I thought it meant.

This is NOT orphan nodes.
The orphan node message is:
```
Warnings:
* Knowledge Graph Nodes:
=> Dangling nodes
	$ global
```

So we do not have dangling nodes, my error.

I think what the above error message is saying is that UNII: is not a valid CURIE prefix for a biolink:Protein according to Biolink. I don't think we care about that warning. 

Nevermind.
