### ISSUE TITLE
Can we shut down arax-responses2.rtx.ai?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2142]
@edeutsch is it OK to shut down `arax-responses2.rtx.ai` at this point?  I mean, nothing is pointing to it, right?

**Comment by edeutsch** [comment]
I an under the belief that everything is pointing to arax-responses and nothing to arax-responses2

**Comment by saramsey** [comment]
Instance stopped.

Scheduled an AHM agenda item to discuss terminating the instance.

**Comment by saramsey** [comment]
Terminated.
