### ISSUE TITLE
SmartAPI challenges

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2144]
Hi everyone, I'm just stumbling back into things after the trip.
I did a `git pull` in devED and saw:
```
 code/ARAX/ARAXQuery/ARAX_query.py                     |  1 +
 code/ARAX/ARAXQuery/ARAX_query_tracker.py             |  2 ++
 code/ARAX/ARAXQuery/Expand/kg2_querier.py             | 27 +++++++++++++++++----------
 code/UI/interactive/rtx.js                            | 55 +++++++++++++++++++++++++++++--------------------------
 code/UI/interactive/rtx.version                       |  2 +-
 code/reasoningtool/kg-construction/QueryNCBIeUtils.py | 88 +++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------
 deploy/arax/scripts/download_database.sh              | 16 +++++++++++++++-
 deploy/arax/templates/deployment.yaml                 |  6 +++++-
 deploy/arax/values.yaml                               | 15 +++++++++++----
 deploy/kg2/scripts/download_database.sh               |  2 +-
 requirements.txt                                      |  1 +
```

and restarted the service. It restarted okay (although seemed quite slow to start) but when I do our example 1 query, I see:

![image](https://github.com/RTXteam/RTX/assets/12707718/1c39957c-7ffc-4365-a529-54246d7dc4d1)

I've not seen the "KP does not have a development TRAPI 1.4 endpoint" message before
and it is weird that we claim that MolePro does not support this edge. This is a classic MolePro query I think?

Anyone know what might be going on?
https://arax.ncats.io/devED/?r=171450

It works much better in CI:
https://arax.ci.transltr.io/?r=171451

I just tried running on /beta with the same problem as devED.
It seems that the KP selector system is broken on multiple endpoints on arax.ncats.io.
Does anyone know anything about this?

**Comment by edeutsch** [comment]
it does seem like a lot of services are missing development maturity:
https://arax.ncats.io/devED/?smartapi=1

Is our code confused or is there a systemic problem with many Translator services not having an development maturity?

**Comment by isbluis** [comment]
I am not sure if this is related, but there seem to be two different KPs with the _infores:molepro_ identifier right now:

![image](https://github.com/RTXteam/RTX/assets/37852256/f5e6a76b-5699-4747-a611-438ae7c4287e)

It does appear that none of the _automat_ KPs have a dev endpoint:
https://arax.ncats.io/index.html?smartapi=1

**Comment by edeutsch** [comment]
aha, good eye!
I wonder if there would be a good way to detect such duplication and flag it red! with animated blood spattering, even.

**Comment by isbluis** [comment]
Something like this?     https://arax.ncats.io/devLM/?smartapi=3

![image](https://github.com/RTXteam/RTX/assets/37852256/56d88c49-c608-482c-81f5-15c64494f1d8)

**Comment by edeutsch** [comment]
sure, looks good.

There's a chance that we may have to accept this as the new normal, in which case we'll have to change our code, which I assume somewhere assumes that there is only one entry per infores key per TRAPI version or something..

**Comment by isbluis** [comment]
This seems counterintuitive, since, among other issues, it would obfuscate provenance.

In any case, let me know if/when this should be pushed to master.

**Comment by edeutsch** [comment]
I would agree, but I can imagine arguments against..

push it!

**Comment by isbluis** [comment]
Awful Prairie dog pushed!

**Comment by edeutsch** [comment]
great, thanks! deployed to instances tracking `master`

**Comment by isbluis** [comment]
Looks like MolePro is no longer duplicated:

![image](https://github.com/RTXteam/RTX/assets/37852256/4868816c-339f-45b3-a296-fab270cc8778)

And the Automat ones also have a 1.4 dev endpoint.

Are you able to run your test again?

**Comment by edeutsch** [comment]
sure, but I see somewhat unusual results.

at devED, I see:
https://arax.ncats.io/devED/?r=172032
![image](https://github.com/RTXteam/RTX/assets/12707718/1bd32481-60c0-49c0-ae67-060a3827ed37)

But at CI, I see: 
https://arax.ci.transltr.io/?r=172031
![image](https://github.com/RTXteam/RTX/assets/12707718/2d7f1287-252f-4ca4-81ef-1e1e38a62abc)

(no gelinea!!)

I wonder if a restart is needed to pick up changes to SmartAPI?
I assumed that this would automatically refresh after 10 minutes?
I suppose it possible that the refresher died on CI.

**Comment by isbluis** [comment]
gelinea only has a _dev_ endpoint, and no _staging_ -- is this what CI is?

![image](https://github.com/RTXteam/RTX/assets/37852256/b3d28f0e-974c-4dff-8fd2-a3a2c4f23dfe)

**Comment by edeutsch** [comment]
ah yes, you are right, exactly!

**Comment by edeutsch** [comment]
With all that considered, this has been fixed, closing.
