### ISSUE TITLE
1 minute delay on startup

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2145]
I notice there's now a 1 minute delay on startup. It appears to be here:
```
2023-09-26T06:03:16.469685: DEBUG: ARAXQueryTracker initialized
2023-09-26T06:04:14.526598: DEBUG: ARAXQueryTracker disconnecting session
```

I am guessing this might be the step where the query tracker checks to make sure that this instance doesn't have any unfinished business in the query log table. What worked well when there were 1000s of entries now is too slow when there are 40000000s of entries.

To investigate and fix.

**Comment by edeutsch** [comment]
My hunch was wrong. the query filters down to only the relevant rows so should not be majorly affected by a large table. So I'm pretty sure my hunch was NOT the reason for the 1-minute pause.

Today when I deployed, the 1-minute pause was not there. I don't know why.
Closing until it shows up again.

**Comment by saramsey** [comment]
Yeah, I've seen delays on start-up, too.  Maybe the KP info cacher?
