### ISSUE TITLE
add "pharmacologic agent" to blocklist of overly general terms

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2147]
Per report from Chris B. of this concept showing up in query results from RTX-KG2:

<img width="889" alt="Screenshot 2023-09-27 at 9 22 50 AM" src="https://github.com/RTXteam/RTX/assets/5562107/c7387d84-6edb-44c9-9a96-1d8dd14885f0">

CC: @edeutsch @dkoslicki

**Comment by dkoslicki** [comment]
@kvnthomas98 Can you add "pharmacolog*" to the ARAX blocklist? There's a bunch like "pharmacology, Other", "Pharmacologic Substance", etc.

Also, does the blocklist remove results that have items from the blocklist _anywhere_ in the answer, or only those who have as the _essence_ items from the blocklist?

**Comment by kvnthomas98** [comment]
@dkoslicki  sure i can work on this. The blocklist removes the general term nodes from the KnowledgeGraph. So as a consequence we won't have any results from the blocklist.

**Comment by dkoslicki** [comment]
So the blocklist is applied before `resultify` then? Pardon my ignorance, I haven't looked at the code for the blocklist

**Comment by kvnthomas98** [comment]
Yes exactly! In `ARAX_query_graph_interpreter_templates.yaml ` the new DSL `filter_kg(action=remove_general_concept_nodes,perform_action=True)` was added before `resultify`
![image](https://github.com/RTXteam/RTX/assets/17030839/3f36924d-2cfe-4fae-9af6-af680a36c500)

**Comment by kvnthomas98** [comment]
This has been deployed to CI

**Comment by saramsey** [comment]
Thanks, @kvnthomas98 !  OK to close?

**Comment by kvnthomas98** [comment]
Yes
