### ISSUE TITLE
Does KG2 need meta_kg_info?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2148]
One thing that might be somewhat wasteful:

Both KG2 and ARAX run all the same BackgroundTasker things. Including fetching of meta_kgs from all KPs.
Is this necessary for the KG2 service? OR can we disable meta_kg fetching for KG2?

**Comment by saramsey** [comment]
Paging @amykglen. The module that seems to use the KP info cache is 

https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Expand/kp_selector.py

In that module, I think if `kg2_mode=True`, then the KP info cache is not used. See this code block:

https://github.com/RTXteam/RTX/blob/1d843c18b3d8d5fce7ce485124112273860cc40d/code/ARAX/ARAXQuery/Expand/kp_selector.py#L32-L34

But of course, I defer to @amykglen on this.

**Comment by amykglen** [comment]
good point - KG2 doesn't have any need for meta KG or SmartAPI info. and in fact, we already skip loading both of those caches when in RTXKG2 mode ([here](https://github.com/RTXteam/RTX/blob/1d843c18b3d8d5fce7ce485124112273860cc40d/code/ARAX/ARAXQuery/Expand/kp_selector.py#L32-L34)). 

so I think all we need to do is stop the background tasker from running those tasks on KG2 endpoints.

**Comment by saramsey** [comment]
Amy can you please remove that code from 

https://github.com/RTXteam/RTX/blob/master/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/__main__.py

**Comment by saramsey** [comment]
@amykglen please let me know if you have questions

**Comment by edeutsch** [comment]
I'm wondering what code you want to remove from __main__.py

**Comment by amykglen** [comment]
I'm in the same boat as @edeutsch - what code in that file do you mean, @saramsey? I don't think we want to entirely stop running the BackgroundTasker on KG2 endpoints, right? I was assuming maybe we need to pass a parameter of some sort to BackgroundTasker that tells it whether we're in KG2 mode or not, and if we are, it could skip refreshing the KP info caches.

**Comment by saramsey** [comment]
Ah, I didn't understand. Thank you for explaining. 

So, we just want Background Tasker to not run the `kp_info_cacher.py` on KG2 endpoints, right?  But we still want Background Tasker to keep running so it does its other jobs (e.g.., Query tracking?).  Makes sense. I'm going to delete my previous suggestion to @amykglen in that case.

**Comment by saramsey** [comment]
@amykglen for this issue, I have created a branch `issue-2148`. I will attempt to code a fix in that branch.

**Comment by saramsey** [comment]
Fix committed. Testing now on `/beta` and `/kg2beta`.

**Comment by saramsey** [comment]
Testing looks good. Merging to `master`. YOLO.

**Comment by saramsey** [comment]
Rolling `master` out to `/test` and `/kg2test`. YOLO.

**Comment by saramsey** [comment]
Issue looks fixed. @amykglen @edeutsch please let me know if you see any issues.

Summary: KP info cacher is no longer running on KG2 endpoints, but the background tasker is running (it just skips the KP info cacher stuff).  Rolled out to `/test`, `/kg2test`, `/beta`, and `/kg2beta`. I recommend rolling it out to `/devED` and `/devLM` but I'll wait for your permission before doing that.

**Comment by saramsey** [comment]
Deleting the branch `issue-2148` as it has been merged to `master`.
