### ISSUE TITLE
How do better manage the master -> test -> prod merges?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2149]
So the current process for getting our code out to TEST and PROD is as follows:

1. Merge `master` into `itrb-test`
2. Request deployment and wait
3. Then, by a Friday or Monday 9am PT latest, merge `master` into `production` and request deployment
4. Wait

The potential snag is during the time interval between 1 and 3, `master` might change. i.e. somebody might check something in. If that happened, we would be rolling out to RPOD a change that never went through TEST 

How shall we solve this?

I am wondering if it makes sense to have another branch called `master-frozen` or something, such that the process would be:

1a. Merge `master` into `master-frozen`
1b. Merge `master-frozen` into `itrb-test`
2. Request deployment and wait
3. Then, by a Friday or Monday 9am PT latest, merge `master-frozen` into `production` and request deployment
4. Wait

This way if there are additional check-ins into master during the interval of step 2, there is no problem.

What do you think?
Better ideas?

**Comment by saramsey** [comment]
I recommend that before step 1, we make a tag on `master` whose tag name is a concatenation of the prefix `itrb-deployment-` and the ISO 8601 date, like this:  `itrb-deployment-20231002`.

We then merge _that_ tag to `itrb-test`, and later, to `production`, like this:
```
git checkout itrb-test
git merge itrb-deployment-20231002
```

The tag would be a useful persistent checkpoint as to what code-base was deployed when.

**Comment by saramsey** [comment]
Note, I have not tested the above two git commands together. But I think it should work?

**Comment by saramsey** [comment]
I think it is not necessary to create a branch to ensure consistency between Eric's step 1 and 3; I think a tag should do it. A branch would only be indicated if we intended to commit some code changes into that branch and _not_ have them go immediately into `master`.

**Comment by edeutsch** [comment]
great, thanks, that sounds very sensible. I have created a tag from current master as described and will try the PROD deployment from the tag. 
thanks, closing.
