### ISSUE TITLE
Restate question restatements

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#215]
From @edeutsch:

>now that we have kind of a graph and some pretty definitions, maybe it would be a nice touch to start writing something a little nicer and prosier in the text field? So instead of:

>The proposed mechanism of action for RHEUMATOID ARTHRITIS; RA (OMIM:180300) is: (OMIM:180300:RHEUMATOID ARTHRITIS; RA)--[associated_with_condition]-->(HLA-DRB1:P01912:protein)--[associated_with_condition]-->(DOID:12365:malaria:disease). Confidence: 0.991089

>Maybe something a little nicer like:

>With a confidence score of 0.99, the genetic condition RHEUMATOID ARTHRITIS; RA may confer some protection against malaria in the following way: RHEUMATOID ARTHRITIS; RA is associated with condition HLA-DRB1, which is associated with condition malaria.

**Comment by dkoslicki** [comment]
@edeutsch This is actually going to be much harder than I anticipated. Q1 doesn't return paths of known structure. So I can't anticipate in advance if it goes through proteins/pathways/symptoms/etc. I could look into trying to detect the node types and relationship types and dynamically come up with a re-statement, but it could take some time. Any idea how priority this is?

**Comment by edeutsch** [comment]
not at a high priority, really. Just that the current description is a bit unsightly. the eye is usually drawn to the graph I think, so the description may not be read much, I don't know,

**Comment by dkoslicki** [comment]
Closing due to #788
