### ISSUE TITLE
DTD status never emerges from "Waiting for response"

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2153]
Whenever I run a "treats" inferred query, KP "infores:arax-drug-treats-disease" never emerges from "Waiting for response" status:
https://arax.test.transltr.io/?r=172328
![image](https://github.com/RTXteam/RTX/assets/12707718/17fae624-39a7-4719-b000-bc74747c187b)

I assume that the usual "signal" that is raised when a query completes is never performed for this special query?

Would someone tidy that up so that the "traffic lights" are accurate?

**Comment by isbluis** [comment]
Hi @edeutsch .  I have tracked this down and patched it in my dev area.  But there is a larger issue of whether we should even be logging that given that DTD has been retired.  If DTD is dead, then a better solution is to update code so that that log line is not even emitted (among other DTD-specific code in ARAX).

Please see my comments on issue 2052; I am just awaiting a reply at the moment before moving forward:
https://github.com/RTXteam/RTX/issues/2052#issuecomment-1744041513

**Comment by edeutsch** [comment]
I don't know the answer.

But I was under the impression that this traffic light was for xDTD, which is NOT retired, and indeed crucial for this particular query.

But I may be confused. It is common.

**Comment by isbluis** [comment]
The traffic light is for DTD; here is the relevant part of _ARAX_expander.py_ (with my own added line to update the query_plan highlighted in red) :
![image](https://github.com/RTXteam/RTX/assets/37852256/67d6983b-56f9-4740-b6f6-ec1b895b0529)

Perhaps we should also add a traffic-light update for xDTD?

**Comment by edeutsch** [comment]
Maybe. In my query I see:
![image](https://github.com/RTXteam/RTX/assets/12707718/7df0085e-a769-45b1-9cf2-d289843e35b4)
as might be expected.

but I also see:
![image](https://github.com/RTXteam/RTX/assets/12707718/2233c6c8-a2d5-4274-bd94-5d554fe3147c)
which seems like a very unlikely state to be in given the code that you show above.

and I also see:
![image](https://github.com/RTXteam/RTX/assets/12707718/bad3a7d1-76cd-4bb2-b4bb-7345b8223f90)

I wonder if there is other code somewhere else responsible for:
![image](https://github.com/RTXteam/RTX/assets/12707718/2233c6c8-a2d5-4274-bd94-5d554fe3147c)

**Comment by isbluis** [comment]
Did you run this in _devLM_?  The code is not pushed yet, pending guidance on the actual state of DTD...

e.g.  https://arax.ncats.io/devLM/index.html?r=172060

![image](https://github.com/RTXteam/RTX/assets/37852256/3c9d63bd-8c5d-4aa4-839c-e149a35cae5a)

**Comment by edeutsch** [comment]
Ah, I see, yes, I see what you see in devLM.
So it seems like my original problem will be fixed when you commit, thanks.

Although this brings up two different issues:

1. Why even bother having it there in the first place if it is disabled? Why not remove it from the anonymous set at the top of your code block?

2. It seems like a good idea to have a traffic light for xDTD so that one can readily see a full list of KPs consulted.

**Comment by isbluis** [comment]
I agree.  Hence my [request for clarification](https://github.com/RTXteam/RTX/issues/2052#issuecomment-1744041513) on this issue (as well as my reply, [above](https://github.com/RTXteam/RTX/issues/2153#issuecomment-1745515666)) before making those changes.

**Comment by edeutsch** [comment]
Great, you're way ahead. I hope you get an answer. closing.
