### ISSUE TITLE
Add interface for uploading a list of entities

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#216]
Picking up where #196 leaves off..

I mused about this a little. I could see a [File Upload] button and/or a little paste text box and/or a drag and drop if we wanted to be fancy for a list of bioentities. And then maybe in the question area you could refer to "this list"? As in:

Which diseases are most influenced by the proteins in this list?

where "this list" or "the list" or "my list" would be a trigger point for inserting the list of entities uploaded into that question.

What do you think?

**Comment by isbluis** [comment]
Going through some old notifications...is this considered done/closed?

Thanks!

**Comment by edeutsch** [comment]
yes, thanks!
