### ISSUE TITLE
Feedback: ARAX ignores a node in a query where subject and object is fixed

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2160]
Would someone familiar with the inferred query operation have a look at this report and investigate/address?

https://github.com/NCATSTranslator/Feedback/issues/574

**Comment by saramsey** [comment]
I just queried `kg2cploverdb.ci.transltr.io` with a one-hop query graph with `ids` specified for both subject and object, and it worked fine (though it returned no results):
```
    query = {
        "edges": {
            "e00": {
                "subject": "sn",
                "object": "on",
                "predicates": ["biolink:treats"]
            }
        },
        "nodes": {
            "sn": {
                "categories": ["biolink:SmallMolecule"],
                "ids": ["PUBCHEM.COMPOUND:23931"]
            },
            "on": {
                "categories": ["biolink:Disease"],
                "ids": ["MONDO:0019600"]
            }
        },
        "include_metadata": True
    }
```
<img width="952" alt="Screenshot 2023-10-06 at 11 54 39 AM" src="https://github.com/RTXteam/RTX/assets/5562107/8e8359eb-cce8-4236-a1ba-31b89aff6406">

So PloverDB seems to be behaving as expected.

**Comment by saramsey** [comment]
Paging @chunyuma can you please look at this query in xDTD?  Thanks.

**Comment by chunyuma** [comment]
For this issue, the main reason is that our `ARAX_infer` module currently doesn't support the query where both subject and object are fixed. Please see[ our DSL document](https://github.com/RTXteam/RTX/blob/master/code/ARAX/Documentation/DSL_Documentation.md#inferactiondrug_treatment_graph_expansion). By default, if both are provided, in `ARAX_expander`, only the object node is used to query top 50 drugs with top 25 paths. So, the subject node would be ignored.

**Comment by edeutsch** [comment]
So what's the resolution then? answer that we don't want to support this use case? or add support for this use case?

**Comment by saramsey** [comment]
> For this issue, the main reason is that our `ARAX_infer` module currently doesn't support the query where both subject and object are fixed. Please see[ our DSL document](https://github.com/RTXteam/RTX/blob/master/code/ARAX/Documentation/DSL_Documentation.md#inferactiondrug_treatment_graph_expansion). By default, if both are provided, in [ARAX_expander](https://github.com/RTXteam/RTX/blob/d5e9a471db7a3cbb646e3ac4e16689945083c2f9/code/ARAX/ARAXQuery/ARAX_expander.py#L388), only the object node is used to query top 50 drugs with top 25 paths. So, the subject node would be ignored.

FWIW, I'm inclined to think that this behavior should be changed. If the user is fixing both subject and object, it is (IMO) better to not return any inferred results than to return inferred results that disregard the subject node. I note that we still can (and should) also return lookup results in this case (if there are any), so it's not like xDTD refusing to return results means that ARAX altogether doesn't support that kind of use-case. @dkoslicki what do you think?

**Comment by chunyuma** [comment]
Yes, we can change the code to support this use case. @dkoslicki what is your thought? I'm wondering if another use case that given a drug, predicting its top N diseases should also be supported. If so, it seems like the current code needs a big change.

**Comment by dkoslicki** [comment]
@chunyuma I think it better to just support the case: if the query fixes the subject and object node, if both exist in the xDTD precomputed database, return that creative result as well as the lookups. Otherwise, just return the lookups (with no creative results that ignore the subject node). 

LMK if this is in your wheelhouse, or if @kvnthomas98 can do this

**Comment by chunyuma** [comment]
I think I need to talk with @kvnthomas98 first as I am not familiar with how Kevin handles the lookups. I would like to see if Kevin has bandwidth to work on this. So just want to clarify: we don't consider the case: given a drug, predicting its top N diseases, right?

**Comment by dkoslicki** [comment]
Correct: _no need_ to do the query "given a drug, predict its top N diseases"

**Comment by kvnthomas98** [comment]
This has been fixed and been deployed to CI. The query from https://github.com/NCATSTranslator/Feedback/issues/574 now returns 0 results because `PUBCHEM.COMPOUND:23931` isn't in the top 50 xDTD predictions and lookups also return 0 results.
![image](https://github.com/RTXteam/RTX/assets/17030839/f9a4f100-4bd0-4cd2-a51c-4b4ac02648af)

**Comment by edeutsch** [comment]
I tried for a drug-disease pair that should return a result and it worked, thanks!
https://arax.ci.transltr.io/?r=173216
