### ISSUE TITLE
Make the resource_id bigger and bolders?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2162]
A possible user confusion is that the most important information is not the big and bolded information:
![image](https://github.com/RTXteam/RTX/assets/12707718/49851143-de10-4eba-806e-cf588feb6f5d)

Here, the most important bit of information is the resource_id in each of the three blocks. Yet, the upstream_resource_ids is the big and bold piece. Perhaps related to a confusion in a recent Feedback issue?

I suggest that the resource_id be big and bold and what draws the users eyes, rather than the upstream tag.

**Comment by isbluis** [comment]
This has been updated in _devLM_ -- please let me know if it looks good enough to push.

**Comment by edeutsch** [comment]
looks great, thanks, push it!
https://arax.ncats.io/devLM/?r=173222

![image](https://github.com/RTXteam/RTX/assets/12707718/dcf74aba-4534-42b4-b510-385eba469103)
