### ISSUE TITLE
resource_id translation for ARAX not working?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2163]
A trivial item, but reporting while investigating another issue. Looking at:
https://arax.ci.transltr.io/?r=740fb674-e601-4a25-8cb0-bd87ee6d239b

BTE results:
![image](https://github.com/RTXteam/RTX/assets/12707718/c18e435c-d39c-4a16-830b-f358dc3da95d)

Unsecret results:
![image](https://github.com/RTXteam/RTX/assets/12707718/387c0f6f-c55a-4600-8bd0-8377af4e45f5)

ARAX results:
![image](https://github.com/RTXteam/RTX/assets/12707718/e385878f-25be-441b-9cfe-d788394d2ec0)

..shows the un-pretty-translated infores key.

**Comment by isbluis** [comment]
The UI does not do any translation of IDs; it simply displays what is in the JSON response.

For the ARAX result referenced above, here is the relevant part of the response:
![image](https://github.com/RTXteam/RTX/assets/37852256/a7103847-7b4e-4b74-adaf-80e6eb75946c)

The BTE response:
![image](https://github.com/RTXteam/RTX/assets/37852256/40c3f6a1-31ea-4b4a-8918-2649790eacce)


My understanding is that the UI should preserve fidelity when displaying results, as this aids in debugging and troubleshooting.
Glad to add special logic to override this if necessary.

**Comment by edeutsch** [comment]
ah okay, thanks. I was thinking that the GUI was doing the pretty translation.

It turns out that the situation is a lot more complex.
Technically each Analysis must have a resource_id, but each Result does not have a resource_id defined in the schema. ARAX appears to be the only actor to put it there (which is allowed but not defined).

Meanwhile the ARAX validator code looks for Result.resource_id. If it's there, then it leaves it as is (as in the case of infores:arax), but if it is not there at all (most other cases), the the validator code has special code to insert an inferred value like "Unsecret".

Options seem to be:
1) Just leave it as is
2) Update ARAX Expander to not put a Result.resource_id at all like the others
3) Make it clearer when the validator is inferring a value but otherwise leave it as is
4) Just have the validator go ahead and translate infores:arax to ARAX

All this seems to be related to the merging of results perhaps.

I'm uncertain what the best strategy is.
In any case, it is now clear that it is not a GUI issue, thanks for checking.
