### ISSUE TITLE
Validation errors reported in Metformin query

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2167]
See [NCATSTranslator/Feedback issue 586](https://github.com/NCATSTranslator/Feedback/issues/586).

**Comment by saramsey** [comment]
Here is the TRAPI query graph. It is of type `"inferred"`:
```
{
  "edges": {
    "t_edge": {
      "attribute_constraints": [],
      "knowledge_type": "inferred",
      "object": "on",
      "predicates": [
        "biolink:affects"
      ],
      "qualifier_constraints": [
        {
          "qualifier_set": [
            {
              "qualifier_type_id": "biolink:object_aspect_qualifier",
              "qualifier_value": "activity_or_abundance"
            },
            {
              "qualifier_type_id": "biolink:object_direction_qualifier",
              "qualifier_value": "decreased"
            }
          ]
        }
      ],
      "subject": "sn"
    }
  },
  "nodes": {
    "on": {
      "categories": [
        "biolink:Gene"
      ],
      "constraints": [],
      "is_set": false,
      "fulltextname": "on"
    },
    "sn": {
      "categories": [
        "biolink:ChemicalEntity"
      ],
      "constraints": [],
      "ids": [
        "PUBCHEM.COMPOUND:4091"
      ],
      "is_set": false,
      "fulltextname": "sn"
    }
  }
}
```
Looks like the ARAX query result includes two result nodes of category `biolink:GenomicEntity`:
https://arax.ncats.io/beta/?r=173466

**Comment by edeutsch** [comment]
Looks like this is coming from the SRI NodeNormalizer, so maybe we can bounce this issue to the SRI NodeNormalizer folks?

**Comment by saramsey** [comment]
In KG2.8.4pre/Neo4j, we have `biolink:BiologicalEntity`:
![Screenshot 2023-10-17 at 10 42 48 AM](https://github.com/RTXteam/RTX/assets/5562107/7cffe6f9-11d5-420f-86dc-9d9f9e8e58ca)

Similarly for the other node:
![Screenshot 2023-10-17 at 10 43 52 AM](https://github.com/RTXteam/RTX/assets/5562107/bd11accb-5a04-4668-b19b-c0117c3a1367)

This makes me think that the appearance of `biolink:GenomicEntity` in KG2.8.4c for these two nodes may be due to the node normalizer. Tagging @amykglen .

**Comment by saramsey** [comment]
To summarize, one issue that is causing a validation error in the originally reference ARAX TRAPI result is that there are two result nodes, `UMLS:C1709820` ("ROS1 wt Allele") and `UMLS:C3890397` ("PRKAA1 wt Allele") both of which are annotated in the TRAPI result as having a `category` of `biolink:GenomicEntity` (which is not allowed because `GenomicEntity` is a "mixin" per the [Biolink YAML model](https://github.com/biolink/biolink-model/blob/85d7dab438ac54411550aa3a19e706553c55fc37/biolink-model.yaml#L6792). 

So, where is the "genomic entity" category coming from?  Based on my investigation, I do not think it is coming from the current production RTX-KG2 graph (i.e., RTX-KG2.8.4c).  But I notice that when I query the SRI Node Normalization service with this request:
```
https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=UMLS%3AC1709820&conflate=true&drug_chemical_conflate=false&description=false
```
I get back "Genomic Entity" in the response:
```
{
  "UMLS:C1709820": {
    "id": {
      "identifier": "UMLS:C1709820",
      "label": "ROS1 wt Allele"
    },
    "equivalent_identifiers": [
      {
        "identifier": "UMLS:C1709820",
        "label": "ROS1 wt Allele"
      }
    ],
    "type": [
      "biolink:GenomicEntity"
    ]
  }
}
```
The same goes for when I query with the other CURIE:
```
https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=UMLS%3AC3890397&conflate=true&drug_chemical_conflate=false&description=false
```

I get back a response with "Genomic Entity":
```
{
  "UMLS:C3890397": {
    "id": {
      "identifier": "UMLS:C3890397",
      "label": "PRKAA1 wt Allele"
    },
    "equivalent_identifiers": [
      {
        "identifier": "UMLS:C3890397",
        "label": "PRKAA1 wt Allele"
      }
    ],
    "type": [
      "biolink:GenomicEntity"
    ]
  }
}
```
So in [NCATSTranslator/Feedback issue 586](https://github.com/NCATSTranslator/Feedback/issues/586),  I tagged and assigned @gaurav on the node normalization issue.

But I'll keep myself assigned on that issue for now, since there are other validation errors to investigate.

**Comment by saramsey** [comment]
> Looks like this is coming from the SRI NodeNormalizer, so maybe we can bounce this issue to the SRI NodeNormalizer folks?

Ah, now I see how you did that. Apparently if I had just studied the output of the ARAX-UI Synonyms tool more closely, I could have avoided a bunch of querying Neo4j endpoints. Thank you!

**Comment by saramsey** [comment]
This has been traced to an SRI Node Normalizer issue. I've updated the original NCATSTranslator/Feedback issue with the results of our investigation. Seems like nothing left to do here. Yes, `biolink:BiologicalEntity` is an abstract class but when we roll out KG2.8.6c, this will get fixed).
