### ISSUE TITLE
Database manager not working on local dev machine

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2171]
So I'm finally getting my local dev machine updated with the latest databases after my summer away, and running `python ARAX_database_manager.py` on my machine in `master` fails to update databases and instead prints a bunch of errors like these:
```
kg2c_sqlite has a local version, '1.0_KG2.8.0.1', which does not match the remote version, '1.0_KG2.8.4'.
downloading remote version...
ERROR: Wanted to run the following rsync, but it isn't going to work anyway. Skipping: rsync -Lhzcvv --progress rtxconfig@arax-databases.rtx.ai:/home/rtxconfig/KG2.8.4/kg2c_v1.0_KG2.8.4.sqlite /Users/amyglen/Projects/RTX/code/ARAX/KnowledgeSources/KG2c/kg2c_v1.0_KG2.8.4.sqlite
Error downloading kg2c_sqlite leaving local copy.
```
I dug into ARAX_database_manager.py, and it looks like @edeutsch commented out the `rsync` command in August and replaced it with the 'ERROR: Wanted to run..' message here:
https://github.com/RTXteam/RTX/commit/c87c238a660315a18e627901fa169a1218e58404#diff-6c5ef8a6fc1a29e4d6b0769025a7776adf87952fcc3814d3d45b6e9015687b65R342

when I undo that change (uncomment the `rsync` line and remove the error line), the database manager works normally for me.

is there a reason why the `rsync` line is commented out in `master`? was there an issue with it on one of our instances or something?

**Comment by edeutsch** [comment]
Yes, there was a long saga over the summer here, that to make a long story short, the running ITRB instances were trying to download databases via this mechanism and this was causing big problems. I applied that quick hack, not realizing that others were using it.

In the mean time, I thought @saramsey had already fixed this issue more robustly. What happened to that? Is that languishing in a branch, or is there a needed command-line flag?

**Comment by amykglen** [comment]
Ah, I see. What if we only skip the `rsync` line if `rtxConfig.is_itrb_instance == False`? I think then ITRB would still never run the rsync line, but things would still work on local dev machines?

**Comment by amykglen** [comment]
apologies - skip the rsync line if `rtxConfig.is_itrb_instance == True`, not False

**Comment by saramsey** [comment]
Yeah, we can probably uncomment that line of code at this point. @amykglen can you please do that?

**Comment by saramsey** [comment]
See [RTXteam/RTX issue 2098](https://github.com/RTXteam/RTX/issues/2098)

**Comment by saramsey** [comment]
Also consider that `ARAX_filter.py` has a method that instantiates a `QueryGraphInfo` object, and the latter class's initializer (as describe above) calls the database manager's `update_databses` method. So that's another potential case where `ARAXDatabaseManager.update_databases` could get called at query time, if we simply uncomment the rsync line of code.

**Comment by saramsey** [comment]
My feeling is that NodeSynonymizer's initializer should just fail if a database file is missing. It should under no circumstances attempt to download database files. But that's not the case as things stand currently.

**Comment by saramsey** [comment]
I think there may be more code paths at query time that indirectly could call `ARAXDatabaseManager.update_databases()`, but I would need to audit the code more carefully to be sure.

**Comment by saramsey** [comment]
So, what do we want to do?  Apologies I didn't push this (i.e., 2098) through earlier. But I guess it's probably for the best that we discuss the specific proposed solution before implementing.

**Comment by saramsey** [comment]
I should say @amkglen that I have just locally uncommented that line of code, when I have wanted to install databases. Which is not ideal but was my work-around until we can get this issue put to rest more definitively.

**Comment by edeutsch** [comment]
I propose that we just update the class so that it will only actually download files if run from the CLI, e.g., 
```
python3 ARAX_database_manager.py --rsync
```

Any other ways that the database manager is called, it will decline to do an actual rsync but be noisy about the fact that it got into a state where it would have.

**Comment by saramsey** [comment]
> I propose that we just update the class so that it will only actually download files if run from the CLI, e.g.,
> 
> ```
> python3 ARAX_database_manager.py --rsync
> ```
> 
> Any other ways that the database manager is called, it will decline to do an actual rsync but be noisy about the fact that it got into a state where it would have.

I'd also like it to rsync when it is called at Flask application start-up (we can have a special initializer parameter for that, of course)

**Comment by saramsey** [comment]
Do you want me to code that up?

**Comment by saramsey** [comment]
I can do it right now.

**Comment by saramsey** [comment]
I'm working on this in branch `issue-2171`

**Comment by edeutsch** [comment]
okay, thanks.

**Comment by saramsey** [comment]
Can you all please check commit 63e0449 to see if it looks sane?

**Comment by saramsey** [comment]
In that commit, I've done a few things:
- used underscores to identify  methods on ARAX_database_manager.py that should not be called from outside the module
- added a boolean class member variable `allow_downloads` that controls whether downloads are allowed; it is set via a parameter to the class initializer
- when the `ARAX_database_manager.py` module is run via the CLI, the `allow_downloads` boolean is set to `True`, so downloads are permitted
- the code in `node_normalizer.py` that creates an instance of `ARAXDatabaseManager` has been removed.

**Comment by edeutsch** [comment]
> Can you all please check commit [63e0449](https://github.com/RTXteam/RTX/commit/63e04491fe397a947201761b771d393e47232a30) to see if it looks sane?

The line we wanted to uncomment is still commented out?

https://github.com/RTXteam/RTX/blob/63e04491fe397a947201761b771d393e47232a30/code/ARAX/ARAXQuery/ARAX_database_manager.py#L351

**Comment by saramsey** [comment]
D'oh!  Done.

**Comment by saramsey** [comment]
Seems to work on my Mac.

**Comment by saramsey** [comment]
Do you want to test the branch on `/beta` or something or just merge it and be legends?

**Comment by edeutsch** [comment]
Legends!

**Comment by saramsey** [comment]
Merged.

https://github.com/RTXteam/RTX/pull/2173

**Comment by saramsey** [comment]
Testing on `arax.ncats.io` in `/test`. See updates on Slack in `#deployment`.

**Comment by saramsey** [comment]
Testing looks good. I have moved `/test` back to the latest `master` branch (which includes the `issue-2171` commits) and restarted ARAX.

**Comment by saramsey** [comment]
I'm now going to delete the `issue-2171` branch.

**Comment by saramsey** [comment]
Deleted. Closing this issue out for now (just reopen if anything looks amiss).

**Comment by saramsey** [comment]
@amykglen can you confirm that with the latest code in `master`, this issue is fixed for you on your local machine?

**Comment by saramsey** [comment]
> the database manager is no longer run automatically when we run ARAX pytests (without running the whole Flask application), so we should run python ARAX_database_manager.py on dev machines when databases change?

Near as I can tell, the only way `ARAXDatabaseManager::update_databases()` was being automatically run before during the pytest suite would have been via `ARAXQuery::__init__`, is that right?  

If so, you correct. That's gone, as of commit e528c6c. It happened on Aug. 29, when you were away.

I think (and others at the time concurred) that we don't want the database manager being run in the initializer for ARAXQuery. The `update_databases` method is slow and we would incur that tax on _every single query_. Does that make sense?

If you want the old automation back, it's perfectly fine to check in a shell script like `RTX/code/ARAX/test/check-db-and-run-tests.sh` that runs the database manager and then runs the tests. But my $0.02 is that I don't think the default behavior of the pytest suite should be to automatically download and update databases locally. When I run pytest, my expectation would be that it runs tests on whatever installation I have set up. Downloading databases can take _hours_ over a broadband, and I frequently test at home. Again, just my $0.02.

**Comment by amykglen** [comment]
thanks @saramsey - no, I'm content running the database manager manually as needed. just wanted to clarify that that's the SOP now
