### ISSUE TITLE
can we archive this file on our public S3 bucket or on Figshare?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2172]
We've got a 96 MB file in the repo that I wonder if it might be better to archive on Figshare or on our public S3 bucket? 

https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/MLDrugRepurposing/FWPredictor/rel_max.emb.gz

If approved to move, I could do the work. But if we need it here in the project area, it's not a problem to keep it. 

Just looking to make our "git clone" a little faster, especially when I'm working over a VPN.

**Comment by dkoslicki** [comment]
I'm 99.5% sure this can just be deleted. I'm checking with @chunyuma for a confirmation (as all the old DTD stuff is depreciated in favor of xDTD)

**Comment by chunyuma** [comment]
Hi Steve, sorry for the late response. Yes, we can delete this file.

**Comment by saramsey** [comment]
done
