### ISSUE TITLE
Remove (abandoned) NGD KP

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2176]
NGD is supposed to be used as a KP for qedges with the `biolink:occurs_together_in_literature_with` predicate, although I don't think it's been in a working state for a while. we weren't really using it at all (it had some serious limitations) so I let it slide a ways back... I've been meaning to just remove it from the code base.

any objections? I think we have plans to eventually create a new NGD KP that is much more useful (#1346)

**Comment by saramsey** [comment]
Is there old code for this that can be removed?  I've been on a low-key crusade to clean out unneeded modules in `RTX/code/reasoningtool` for a while.

**Comment by amykglen** [comment]
@saramsey - not sure what you mean by 'old', but I removed all related code in a branch ([here](https://github.com/RTXteam/RTX/commit/14fef5dbb355fb990c5473d00909508047f4c045)).

**Comment by isbluis** [comment]
Pardon my ignorance -- does this have anything to do with #2088 and/or #2088 ?

**Comment by amykglen** [comment]
I don't think so @isbluis - there's core code for computing NGD, which is definitely not deprecated/abandoned - it's used by Overlay (and maybe other modules?) and is also what Expand used to expose the NGD KP. It looks like that issue you linked relates to the core NGD code (which is still used/maintained), whereas this issue is just about exposing NGD as a KP

**Comment by saramsey** [comment]
> @saramsey - not sure what you mean by 'old', but I removed all related code in a branch ([here](https://github.com/RTXteam/RTX/commit/14fef5dbb355fb990c5473d00909508047f4c045)).

Thanks. By "old" I meant obsoleted by this change.

**Comment by isbluis** [comment]
Great, thank you @amykglen .  (and of course I tag issues like a potato: I meant to also mention #2124 above)

**Comment by amykglen** [comment]
I just merged the removal to `master`. closing!

**Comment by amykglen** [comment]
suppose I should leave this open until it's rolled out to our dev instances

**Comment by amykglen** [comment]
verified on /beta! closing
