### ISSUE TITLE
investigate why ARAX has no results for myopia.json "smoke test"

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2179]
https://arax.ncats.io/devLM/index.html?systest=1

**Comment by edeutsch** [comment]
I think @isbluis has already reached out to Shervin for her to fix this.

**Comment by edeutsch** [comment]
oops, sorry, that was a different issue, nevermind..

**Comment by saramsey** [comment]
Per the latest "smoke test" results viewed on arax.ncats.io/devLM, there is no error for this test:
![Screenshot 2024-01-03 at 9 20 33 AM](https://github.com/RTXteam/RTX/assets/5562107/0a1a50e2-5d0d-4a93-841b-f6f7b4e432e9)

**Comment by saramsey** [comment]
By going to the BTE results page of the above-linked, cached ARS result ID, I managed to get what seems to be the JSON query for this smoke test:
```
{
  "edges": {
    "e0": {
      "knowledge_type": "inferred",
      "object": "n0",
      "predicates": [
        "biolink:treats"
      ],
      "subject": "n1"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:Disease"
      ],
      "ids": [
        "MONDO:0011300"
      ]
    },
    "n1": {
      "categories": [
        "biolink:ChemicalEntity"
      ]
    }
  }
}
```
When I run that JSON query through ARAX on `arax.ncats.io/beta`, I get zero results.

**Comment by saramsey** [comment]
So, the disease ID for the above-shown query, `MONDO:0011300`, corresponds to a rare autosomal dominant myopia,

![Screenshot 2024-01-03 at 9 25 34 AM](https://github.com/RTXteam/RTX/assets/5562107/63a49482-2fff-4075-aff0-cc4432af9571)

It is not surprising that we have no results for this rare disease (lookup or inferred). Closing this issue.

**Comment by edeutsch** [comment]
BTE came up with 135 results. Are they any good?
https://arax.ci.transltr.io/?r=0acdc59f-05bf-4678-9f5b-7631311b708e
