### ISSUE TITLE
Expand calls cohd with unsupported predicate

### ISSUE THREAD

**Issue by isbluis** [RTXteam/RTX#2180]
ARAX Expand in **dev** often gets a 400 error from COHD due to an unsupported predicate:
![image](https://github.com/RTXteam/RTX/assets/37852256/c9421440-273e-4c1d-8a15-b8b12499393b)

Is there a reason why Expand tries to query this resource?  Their _meta_knowledge_graph_ seems to indicate support only for `biolink:positively_correlated_with` and `biolink:negatively_correlated_with` .

Sample query sent by ARAX (taken from https://arax.ncats.io/devLM/index.html?r=174131 ) :

```
{
  "message": {
    "query_graph": {
      "edges": {
        "t_edge": {
          "knowledge_type": "lookup",
          "object": "disease",
          "predicates": [
            "biolink:treats"
          ],
          "subject": "chemical"
        }
      },
      "nodes": {
        "chemical": {
          "categories": [
            "biolink:ChemicalEntity"
          ],
          "is_set": true
        },
        "disease": {
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature",
            "biolink:PhenotypicFeature",
            "biolink:Disease"
          ],
          "ids": [
            "MONDO:0015564"
          ],
          "is_set": false
        }
      }
    }
  },
  "submitter": "infores:arax"
}
```

**Comment by saramsey** [comment]
Wild guess here-- is COHD giving out a bad (as in, incorrect) metagraph?  Paging @amykglen

**Comment by saramsey** [comment]
Let's ask @amykglen for her thoughts. I am not sure.

**Comment by amykglen** [comment]
that's very odd - seems like maybe a bug. I'll look into it! thanks @isbluis

**Comment by amykglen** [comment]
ok, figured this one out. it was a bug in `KPSelector` related to how symmetric predicates were handled (it was happening only when none of the predicates/descendant predicates in a QG were symmetric)

fixed in `master` (and I updated the changelog)

**Comment by isbluis** [comment]
Great, thank you @amykglen !

**Comment by amykglen** [comment]
verified fixed on /beta! https://arax.ncats.io/beta/?r=174297

good to close, @isbluis?

**Comment by isbluis** [comment]
Looks good, many thanks!
