### ISSUE TITLE
Noe4j import error due to an issue in the :LABEL column in nodes_c.tsv file

### ISSUE THREAD

**Issue by sundareswarpullela** [RTXteam/RTX#2184]
During the Neo4j deployment of KG2.8.6c. We observed that the import was failing with the following error 
```
(1/4) Node import 2023-10-12 02:01:39.724+0000
  Estimated number of nodes: 3.39 M
  Estimated disk space usage: 4.86 GB
  Estimated required memory usage: 1.04 GB
.......... .......... .......... .......... ..........   5% ∆559ms
.......... .......... .......... .......... ..........  10% ∆2ms
.......... .......... .......... .......... ..........  15% ∆1ms
.......... .......... .......... .......... ..........  20% ∆1ms
.......... .......... .......... .......... ..........  25% ∆1ms
.......... .......... .......... .......... ..........  30% ∆1ms
.......... .......... .......... .......... ..........  35% ∆1ms
.......... .......... .......... .......... ..........  40% ∆2ms
.......... .......... .......... .......... ..........  45% ∆1ms
.......... .......... .......... .......... ..........  50% ∆1ms
.......... .......... .......... .......... ..........  55% ∆0ms
.......... .......... .......... .......... ..........  60% ∆1ms
.......... .......... .......... .......... ..........  65% ∆0ms
.......... .......... .......... .......... ..........  70% ∆1ms
.......... .......... .......... .......... ..........  75% ∆0ms
.......... .......... .......... .......... ..........  80% ∆1ms
.......... .......... .......... .......... ..........  85% ∆0ms
.......... .......... .......... .......... ..........  90% ∆1ms
.......... .......... .......... .......... ..........  95% ∆1ms
.......... .......... .......... .......... .......... 100% ∆0ms


IMPORT FAILED in 1s 268ms.
Data statistics is not available.
Peak memory usage: 0.00 B
Import error: null
Caused by:null
java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at org.neo4j.unsafe.impl.batchimport.NodeImporter.labels(NodeImporter.java:113)
        at org.neo4j.unsafe.impl.batchimport.input.InputEntity.replayOnto(InputEntity.java:324)
        at org.neo4j.unsafe.impl.batchimport.input.csv.EagerCsvInputChunk.next(EagerCsvInputChunk.java:45)
        at org.neo4j.unsafe.impl.batchimport.input.csv.CsvInputChunkProxy.next(CsvInputChunkProxy.java:75)
        at org.neo4j.unsafe.impl.batchimport.ExhaustingEntityImporterRunnable.run(ExhaustingEntityImporterRunnable.java:57)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:122)

WARNING Import failed. The store files in /var/lib/neo4j/data/databases/graph.db are left as they are, although they are likely in an unusable state. Starting a database on these store files will likely fail or observe inconsistent records so start at your own risk or delete the store manually
unexpected error: null
```
First we thought the issue could be a latent backslash in the `nodes_c.tsv` file based on other instances of this error online. Upon running the following command `nl nodes_c.tsv | grep -P '\\\t'` we found one node entry that matched the backslash hypothesis. 
```
nl nodes_c.tsv | grep -P '\\\t'
6341800	PathWhiz.NucleicAcid:71	Putative type II secretion system protein I	biolink:NucleicAcidEntity	Putative type II secretion system protein IǂPutative type II secretion system protein I\	biolink:NucleicAcidEntityǂbiolink:MolecularEntity	https://pathbank.org/lims#/nucleic_acids/71		PathWhiz.NucleicAcid:71ǂPathWhiz.ProteinComplex:13588		biolink:PhysicalEssenceOrOccurrentǂbiolink:ChemicalEntityOrGeneOrGeneProductǂbiolink:NamedThingǂbiolink:MolecularEntityǂbiolink:OntologyClassǂbiolink:ChemicalEntityOrProteinOrPolypeptideǂbiolink:ChemicalOrDrugOrTreatmentǂbiolink:ChemicalEntityǂbiolink:NucleicAcidEntityǂbiolink:GenomicEntityǂbiolink:ThingWithTaxonǂbiolink:PhysicalEssence
```

Upon modifying the `nodes_c.tsv` file and removing the backslash using the command `sed -i 's/\\\t/\t/' nodes_c.tsv`, the IMPORT ERROR still persisted. 

@saramsey upon carefully bisecting the `nodes_c.tsv` file, found few nodes with very very long values for the `:LABEL` column (i.e., column 10 in the `nodes_c.tsv` file). For example, row 2001 of `nodes_c.tsv` which has this in the `:LABEL` column:
```
biolink:PhysicalEssenceOrOccurrentǂbiolink:Drugǂbiolink:ChemicalEntityOrGeneOrGeneProductǂbiolink:NamedThingǂbiolink:Proteinǂbiolink:MolecularEntityǂbiolink:OntologyClassǂbiolink:ChemicalEntityOrProteinOrPolypeptideǂbiolink:BiologicalEntityǂbiolink:ChemicalOrDrugOrTreatmentǂbiolink:ChemicalEntityǂbiolink:GeneOrGeneProductǂbiolink:MolecularMixtureǂbiolink:SmallMoleculeǂbiolink:MacromolecularMachineMixinǂbiolink:GenomicEntityǂbiolink:ThingWithTaxonǂbiolink:PhysicalEssenceǂbiolink:GeneProductMixinǂbiolink:ChemicalMixtureǂbiolink:Geneǂbiolink:Polypeptide
```
When we shorten the `:LABEL` field to this value:
```
biolink:PhysicalEssenceOrOccurrentǂbiolink:Drugǂbiolink:ChemicalEntityOrGeneOrGeneProduct
```
the error goes away.

We could also reproduce this problem with a single node with only two properties (`id` and `:LABEL`) and zero relationships (i.e., an empty edges file). For the node: 
```
PUBCHEM.COMPOUND:452550	biolink:PhysicalEssenceOrOccurrentǂbiolink:Drugǂbiolink:ChemicalEntityOrGeneOrGeneProductǂbiolink:NamedThingǂbiolink:Proteinǂbiolink:MolecularEntityǂbiolink:OntologyClassǂbiolink:ChemicalEntityOrProteinOrPolypeptideǂbiolink:BiologicalEntityǂbiolink:ChemicalOrDrugOrTreatmentǂbiolink:ChemicalEntityǂbiolink:GeneOrGeneProductǂbiolink:MolecularMixtureǂbiolink:SmallMoleculeǂbiolink:MacromolecularMachineMixinǂbiolink:GenomicEntityǂbiolink:ThingWithTaxonǂbiolink:PhysicalEssenceǂbiolink:GeneProductMixinǂbiolink:ChemicalMixtureǂbiolink:Geneǂbiolink:Polypeptide
```
When @sundareswarpullela tried to reproduce the same issue with a different node with just as many labels in the `:LABEL` column, the IMPORT worked successfully. Nothing seems obviously wrong with the label column of the example @saramsey used that would trigger an IMPORT Error. 

The specific node files and edge files that can minimally reproduce the error are: (on `kg2canonicalized.rtx.ai`): 
```
/home/ubuntu/steve/nodes-bad-2-header.tsv
/home/ubuntu/steve/nodes-bad-2.tsv
/home/ubuntu/steve/edges_c_header.tsv
/home/ubuntu/steve/edges-bad.tsv
```
run this script as user `ubuntu`:
```
bash -x /home/ubuntu/steve/run-test-bad-2.sh
```
The above information is a consolidation from this https://github.com/RTXteam/RTX/issues/2143#issuecomment-1773087365 onwards in the [KG2.8.6c rollout issue](https://github.com/RTXteam/RTX/issues/2143).

**Comment by amykglen** [comment]
@sundareswarpullela @saramsey - thanks for sharing the files that minimally reproduce this issue on `kg2canonicalized.rtx.ai`. do you have similar files that capture the cases you mentioned above where the error went away? (i.e., when you changed the node ID, or shortened the `:LABEL` field)

**Comment by amykglen** [comment]
thanks! so one difference I see between those files is the last (hidden) character -a carriage return (I think?) in the file that produces the error? which is absent in the one that works fine.

> ubuntu@ip-172-31-50-129:~/steve$ cat -v nodes-bad-2_1.tsv 
> PUBCHEM.COMPOUND:10909430 biolink:PhysicalEssenceOrOccurrentM-GM-^Bbiolink:DrugM-GM-^Bbiolink:ChemicalEntityOrGeneOrGeneProductM-GM-^Bbiolink:NamedThingM-GM-^Bbiolink:ProteinM-GM-^Bbiolink:MolecularEntityM-GM-^Bbiolink:OntologyClassM-GM-^Bbiolink:ChemicalEntityOrProteinOrPolypeptideM-GM-^Bbiolink:BiologicalEntityM-GM-^Bbiolink:ChemicalOrDrugOrTreatmentM-GM-^Bbiolink:ChemicalEntityM-GM-^Bbiolink:GeneOrGeneProductM-GM-^Bbiolink:MacromolecularMachineMixinM-GM-^Bbiolink:SmallMoleculeM-GM-^Bbiolink:MolecularMixtureM-GM-^Bbiolink:GenomicEntityM-GM-^Bbiolink:ThingWithTaxonM-GM-^Bbiolink:PhysicalEssenceM-GM-^Bbiolink:GeneProductMixinM-GM-^Bbiolink:ChemicalMixtureM-GM-^Bbiolink:GeneM-GM-^Bbiolink:Polypeptide

> ubuntu@ip-172-31-50-129:~/steve$ cat -v nodes-bad-2.tsv
> PUBCHEM.COMPOUND:452550	biolink:PhysicalEssenceOrOccurrentM-GM-^Bbiolink:DrugM-GM-^Bbiolink:ChemicalEntityOrGeneOrGeneProductM-GM-^Bbiolink:NamedThingM-GM-^Bbiolink:ProteinM-GM-^Bbiolink:MolecularEntityM-GM-^Bbiolink:OntologyClassM-GM-^Bbiolink:ChemicalEntityOrProteinOrPolypeptideM-GM-^Bbiolink:BiologicalEntityM-GM-^Bbiolink:ChemicalOrDrugOrTreatmentM-GM-^Bbiolink:ChemicalEntityM-GM-^Bbiolink:GeneOrGeneProductM-GM-^Bbiolink:MolecularMixtureM-GM-^Bbiolink:SmallMoleculeM-GM-^Bbiolink:MacromolecularMachineMixinM-GM-^Bbiolink:GenomicEntityM-GM-^Bbiolink:ThingWithTaxonM-GM-^Bbiolink:PhysicalEssenceM-GM-^Bbiolink:GeneProductMixinM-GM-^Bbiolink:ChemicalMixtureM-GM-^Bbiolink:GeneM-GM-^Bbiolink:Polypeptide^M

**Comment by amykglen** [comment]
maybe it's worth creating a copy of `nodes-bad-2.tsv` where you remove that last carriage return character, and see if the issue persists?

**Comment by dkoslicki** [comment]
Yup, I saw that too, but downloaded the files to my windows machine, so wasn't 100% certain if they were present in the original file

**Comment by saramsey** [comment]
Yeah, I think `RTX/code/kg2c/create_kg2_files.py` uses the `csv` package which implements RFC 4180 by default (unfortunately), which means it is putting out CRLF on each line. But AFAIK there was no change to the TSV formatting in this release. HTH.

I will say that in `RTX-KG2/kg_json_to_tsv.py`, we (as of June 21) are useing `newline=''` in using the `csv` package to write the TSV files, which means it will use a standard Unix `\n` (i.e., LF) for line termination.

**Comment by sundareswarpullela** [comment]
@saramsey and I found out that there is a 20 label limit for nodes in neo4j version 3.5.13, this can be seen in the source code for neo4j [here](https://github.com/neo4j/neo4j/blob/15f73639acdbcc28388588033e3dc545f34f3412/community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/NodeImporter.java#L113). Currently testing removing Mixins and limiting the number of labels to 20.

**Comment by saramsey** [comment]
nice!  thank you for fixing this, @sundareswarpullela
