### ISSUE TITLE
Do we still need the dtd database and the rest of these databases?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2191]
There are still issues with the databases on the ITRB instances and Pouyan is asking if we still need all the databases in config_dbs.json (https://github.com/RTXteam/RTX/blob/master/code/config_dbs.json).

can anyone confirm (or not) that we still need all these?

I'm wondering if maybe we don't need:
```
      "dtd_prob": "/translator/data/orangeboard/databases/KG2.8.0.1/DTD_probability_database_v1.0_KG2.8.0.1_refreshed.db",
```
since we retired DTD?

What about the rest of these old databases with version stamps << 2.8.4?
```
      "cohd_database": "/translator/data/orangeboard/databases/KG2.8.0/COHDdatabase_v1.0_KG2.8.0.db",
      "graph_database": "/translator/data/orangeboard/databases/KG2.8.0.1/GRAPH_v1.0_KG2.8.0.1_refreshed.sqlite",
      "dtd_prob": "/translator/data/orangeboard/databases/KG2.8.0.1/DTD_probability_database_v1.0_KG2.8.0.1_refreshed.db",
      "log_model": "/translator/data/orangeboard/databases/KG2.7.6/LogModel_v1.0_KG2.7.6.pkl",
      "rel_max": "/translator/data/orangeboard/databases/KG2.7.6/rel_max_v1.0_KG2.7.6.emb.gz",
      "map_txt": "/translator/data/orangeboard/databases/KG2.7.6/map_v1.0_KG2.7.6.txt",
      "xcrg_embeddings": "/translator/data/orangeboard/databases/KG2.8.0.1/chemical_gene_embeddings_v1.0.KG2.8.0.1.npz",
      "xcrg_increase_model": "/translator/data/orangeboard/databases/KG2.8.0.1/xcrg_increase_model_v1.0.KG2.8.0.1.pt",
      "xcrg_decrease_model": "/translator/data/orangeboard/databases/KG2.8.0.1/xcrg_decrease_model_v1.0.KG2.8.0.1.pt"
```

**Comment by chunyuma** [comment]
Hi @edeutsch, we don't need `dtd_prob`, `log_model`, `rel_max`, `map_txt`, `graph_database` anymore. So, they can be removed.

**Comment by edeutsch** [comment]
Pouyan has asked that we remove databases that we don't need anymore from the sftp server. Is anyone able to to do that?

**Comment by edeutsch** [comment]
I found out that removing the databases that I proposed to remove in this PR: https://github.com/RTXteam/RTX/pull/2192/files
broke the system. It seems that these databases are referred to with hard-coded variables in RTXConfig and possibly other places. Therefore additional work will be necessarily to remove these databases from the system. They cannot merely be deleted from the config file.

**Comment by amykglen** [comment]
ok, I have the five databases removed from the codebase in the branch `issue2191` and have verified that the ARAX pytest suite and `DatabaseManager` still run successfully.

ok to merge these changes to `master`?

**Comment by edeutsch** [comment]
okay by me, yes, thanks!

**Comment by amykglen** [comment]
cool - merged to master!

**Comment by amykglen** [comment]
ok, I'm also done deleting all of the no-longer-used database files (and their md5sums) on the ITRB SFTP server.

**Comment by edeutsch** [comment]
great, thanks so much! I'll let Pouyan know. closing.

**Comment by edeutsch** [comment]
oh wait, did you delete the just recently removed databases?

**Comment by edeutsch** [comment]
perfect, thank you!
