### ISSUE TITLE
Ability to dynamically exclude a KS

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#220]
Christine approached me as the hackathon was ending and requested a feature where the user could exclude one or more knowledge sources from the reasoning. I didn't promise anything, but said we would try to do this. We should consider how it might be done. It seems a bit tricky because it seems that our general model is to include only best-of-breed KSs, and if one is excluded, then there's nothing to connect the dots. We might have to consider adding in several similar knowledge sources. dunno.

On the UI side, it seems that first we'll need to have a complete list of KSs that we're currently using. It seems that would be a nice thing to have anyway. A simple tsv file in kg-construction area could describe the current state of KSs. The the UI would pull that and display that and give the user to select any to exclude. We would need to augment the query endpoint to pass along this user input. The caching system would need to use these constraints as a cache hit/miss decision point.

Then David would need to consider how tricky it is to honor such hints in the reasoning components. Perhaps as simple as disallowing edges with a certain type. Maybe not hard to implement, but I won't if it will break most queries.

I suppose for our test case of "Which proteins does ibuprofen target", we have edges from both ChEMBL and Pharos, and thus excluding one or the other would yield a pleasantly different result. But I suspect most would end with "No results"

What do you think?

**Comment by saramsey** [comment]
EBI STRING kind of has such a feature.

Thanks for putting it in the Git issues.

**Comment by dkoslicki** [comment]
Closing due to #788 and `filter_kg` now providing this
