### ISSUE TITLE
We need to prototype potential next query types for UI

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2207]
From Architecture issue 95, the proposed mandate is:

Nov 16, 2023: To provide guidance in choosing the next features for Translator, teams are going to produce prototypes falling broadly into one of two classes:

1. Multi-Curie Queries. Example: What chemical may upregulate these N genes? What chemical may lead to this collection of N Phenotypes?  The goal is to find a good, probably creative answer that satisfies as many of the N inputs as possible, but may not satisfy all of them.
2. Pathfinder Queries: How are entities A and B related? Or, find a path that explains a particular relationship between A and B.

These are left intentionally vague to allow room for experimentation.  The goal is not to produce polished tools that are already incorporated into existing components, but to produce something experimental.

These prototypes need to be completed by the winter relay.  We will have a session to review the prototypes, and these will feed into our prioritization and roadmap discussions.

All teams are invited to create prototypes.

**Comment by dkoslicki** [comment]
@mohsenht is working on the pathfinder query
