### ISSUE TITLE
rename Docker containers on rtx.ncats.io to RTX1 and RTX2

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#222]
@dkoslicki and @edeutsch is this OK with you?

**Comment by dkoslicki** [comment]
Should be fine from my end!

**Comment by edeutsch** [comment]
I suppose I would advocate RTX and KG2. Since RTX (nee PRODUCTION is where all main RTX stuff lives). The second container (nee DEV) is just where our alternate neo4j KG is. So KG2 was my suggested name. but it doesn't matter that much. whatever helps us recognize the situation best.

**Comment by dkoslicki** [comment]
Closing due to #788
