### ISSUE TITLE
Can we add medicament to our block list?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2224]
What is our procedure for adding generic things to our block list?

Sarah is pointing out a answer of 'medicament' from ARAX:

https://github.com/NCATSTranslator/Feedback/issues/655

can we adjust ARAX to drop that?

**Comment by edeutsch** [comment]
@kvnthomas98 would you add medicament to our block list for ARAX?

**Comment by kvnthomas98** [comment]
We can add more items to the blocklist by adding items to the json file [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/KnowledgeSources/general_concepts.json) you can add them to the `synonyms `list where we can use regular expressions to remove nodes matching the particular pattern mentioned or we can add identifiers under the `curies` key

**Comment by saramsey** [comment]
Thanks for fixing this, @kvnthomas98

**Comment by dkoslicki** [comment]
Are we good to close on this one?
