### ISSUE TITLE
Bug in `connect`

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#2229]
When work is performed on improving the `connect` DSL command, keep in mind that the current implementation has a bug. The following inpu:
```
# This program creates two query nodes and a query edge between them, looks for matching edges in the KG,
# overlays NGD metrics, and returns the top 30 results
## Basal cell carcinomas, Basal cell carcinoma, spitz nevus, Molluscum Contagiosum, Warts
add_qnode(name= spitz nevus, key=n0)
add_qnode(name=Basal cell carcinomas, key=n1)
add_qnode(name=Basal cell carcinoma, key=n2)
add_qnode(name=Molluscum Contagiosum, key=n3)
add_qnode(name=Warts, key=n4)
connect(action=connect_nodes,max_path_length=3,qnode_keys=[n0,n1,n2,n3,n4])
resultify()
filter_results(action=limit_number_of_results, max_results=50)
```
Results in: `2023-12-14T19:38:14.852034 ERROR: [UncaughtARAXiError]    An uncaught error occurred: 'subclass:arax_connect_node_14--arax_connect_node_14': ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 793, in execute_processing_plan\n connect.apply(response, action[\'parameters\'])\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_connect.py", line 196, in apply\n getattr(self, \'_\' + self.__class__.__name__ + \'__\' + parameters[\'action\'])() # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_connect.py", line 402, in __connect_nodes\n new_response = expander.apply(new_response, expand_params, mode=mode)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 518, in apply\n self._apply_any_kryptonite_edges(overarching_kg, message.query_graph,\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 1080, in _apply_any_kryptonite_edges\n current_qedge = full_query_graph.edges[qedge_key]\n', "KeyError: 'subclass:arax_connect_node_14--arax_connect_node_14'\n"]`

It might be best to start afresh with the connect code (or be judicious in what is retained).

**Comment by mohsenht** [comment]
The implementation of the connect command has been completely changed since this issue was created.
