### ISSUE TITLE
consider adding CliXO ontology to the KG

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#223]
https://www.nature.com/articles/srep39237

**Comment by dkoslicki** [comment]
@saramsey should we close per #788?

**Comment by saramsey** [comment]
Recording the link to the user guide here:
https://mhk7.github.io/clixo_0.3/

**Comment by saramsey** [comment]
after thinking about it, data-driven ontology inference is probably not something we want to integrate into KG2 at this time.
