### ISSUE TITLE
Missing scores sometimes?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2234]
As reported to me via Slack by the sponsor's ARS team:

It seems that some of our responses are missing a score where there should be one:
For example for PK e2d175b3-d191-4492-973c-0e31c313b981
There is not an Analysis.score as seen here:
https://arax.ci.transltr.io/?r=fec60262-c79d-40e8-baa3-71713b5c9290
![image](https://github.com/RTXteam/RTX/assets/12707718/45136dde-4731-4fcc-a2cf-78f3aa28c837)
The top score is the Result.score, which we like, but is not formally part of TRAPI. The Analysis.score is the part that is formally TRAPI and is what is used by ARS to merge results. And you can see that it is "n/a" here, i.e. null.

Yet, a similar but different inferred query *does* have the desired Analysis.score:
https://arax.ci.transltr.io/?r=188605
![image](https://github.com/RTXteam/RTX/assets/12707718/d63c9726-4390-4566-8490-b93b265eb243)

Can we fix?

**Comment by saramsey** [comment]
Here is the query graph, it seems:
```
{
  "edges": {
    "N1": {
      "attribute_constraints": [],
      "object": "DrugID",
      "predicates": [
        "biolink:occurs_together_in_literature_with"
      ],
      "qualifier_constraints": [],
      "subject": "ConditionID"
    },
    "creative_DTD_qedge_0": {
      "attribute_constraints": [],
      "exclude": false,
      "object": "creative_DTD_qnode_0",
      "option_group_id": "creative_DTD_option_group_0",
      "qualifier_constraints": [],
      "subject": "DrugID"
    },
    "creative_DTD_qedge_1": {
      "attribute_constraints": [],
      "exclude": false,
      "object": "creative_DTD_qnode_1",
      "option_group_id": "creative_DTD_option_group_0",
      "qualifier_constraints": [],
      "subject": "creative_DTD_qnode_0"
    },
    "creative_DTD_qedge_2": {
      "attribute_constraints": [],
      "exclude": false,
      "object": "ConditionID",
      "option_group_id": "creative_DTD_option_group_0",
      "qualifier_constraints": [],
      "subject": "creative_DTD_qnode_1"
    },
    "e01": {
      "attribute_constraints": [],
      "knowledge_type": "inferred",
      "object": "ConditionID",
      "predicates": [
        "biolink:treats"
      ],
      "qualifier_constraints": [],
      "subject": "DrugID"
    },
    "subclass:ConditionID--ConditionID": {
      "attribute_constraints": [],
      "object": "ConditionID",
      "option_group_id": "option_group-subclass:ConditionID--ConditionID",
      "predicates": [
        "biolink:subclass_of"
      ],
      "qualifier_constraints": [],
      "subject": "ConditionID"
    }
  },
  "nodes": {
    "ConditionID": {
      "categories": [
        "biolink:Disease"
      ],
      "constraints": [],
      "ids": [
        "MONDO:0005301"
      ],
      "is_set": false
    },
    "DrugID": {
      "categories": [
        "biolink:Drug",
        "biolink:SmallMolecule"
      ],
      "constraints": [],
      "is_set": false
    },
    "creative_DTD_qnode_0": {
      "constraints": [],
      "is_set": true,
      "option_group_id": "creative_DTD_option_group_0"
    },
    "creative_DTD_qnode_1": {
      "constraints": [],
      "is_set": true,
      "option_group_id": "creative_DTD_option_group_0"
    }
  }
}
```
Hmm, the query graph looks kind of complex

**Comment by saramsey** [comment]
When I run the above query graph in `arax.ncats.io/test`, I'm seeing this error:

> UnknownError message: No query node with object qnode key creative_DTD_qnode_0 detected in QG for Fisher's Exact Test -

**Comment by saramsey** [comment]
And the final error in the Message log seems to be:

>    2024-01-10T17:51:30.891790 ERROR: [PruneError]    Ran into an issue using Resultify when trying to prune creative_DTD_qnode_0 answers: Response: status: ERROR n_errors: 7 n_warnings: 1 n_messages: 67 error_code: SubclassProblem message: Result contains more than one 'parent' concept fulfilling the essence qnode (creative_DTD_qnode_0, which has is_set=False). This shouldn't be possible! - 2024-01-10T17:50:36.391119 ERROR: [TypeError] Traceback (most recent call last): File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Overlay/fisher_exact_test.py", line 186, in fisher_exact_test edge_attribute_list = [x.value for x in self.message.knowledge_graph.edges[edge_key].attributes if x.attribute_type_id == 'EDAM-DATA:1772'] TypeError: 'NoneType' object is not iterable - 2024-01-10T17:50:36.391187 ERROR: [UnknownError] Something went wrong with retrieving edges in message KG - 2024-01-10T17:50:36.475715 ERROR: [UnknownError] No query node with object qnode key creative_DTD_qnode_0 detected in QG for Fisher's Exact Test - 2024-01-10T17:51:29.359658 ERROR: [SubclassProblem] Result contains more than one 'parent' concept fulfilling the essence qnode (creative_DTD_qnode_0, which has is_set=False). This shouldn't be possible! - 2024-01-10T17:51:30.165128 ERROR: [SubclassProblem] Result contains more than one 'parent' concept fulfilling the essence qnode (creative_DTD_qnode_0, which has is_set=False). This shouldn't be possible! - 2024-01-10T17:51:30.182490 ERROR: [SubclassProblem] Result contains more than one 'parent' concept fulfilling the essence qnode (creative_DTD_qnode_0, which has is_set=False). This shouldn't be possible! - 2024-01-10T17:51:30.210304 ERROR: [SubclassProblem] Result contains more than one 'parent' concept fulfilling the essence qnode (creative_DTD_qnode_0, which has is_set=False). This shouldn't be possible! - 2024-01-10T17:51:30.506488 WARNING: [] No non-infinite value was encountered in any edge attribute in the knowledge graph.

**Comment by saramsey** [comment]
At first glance, this looks like an ARAX-Overlay issue?

**Comment by dkoslicki** [comment]
Couple of notes:

1. The standard MVP1 template returns scores and results as expected: https://arax.ncats.io/?r=188612
2. Adding the workflow:
```
"workflow": [
{
"id": "lookup"
}
]
```
does omit the scores: https://arax.ncats.io/?r=188613. This is [expected](https://github.com/NCATSTranslator/OperationsAndWorkflows/blob/main/operations/lookup.yml#L3) since `lookup` is equivalent to fill + bind + complete_results (i.e. no "score").

3. I'm unable to replicate this error; no modification of the returned query graph results in the observed behavior.

@edeutsch Can you let me know who contact you so I can report these findings to?

**Comment by dkoslicki** [comment]
4. Using the query graph returned by other ARAs does not reproduce the error

**Comment by dkoslicki** [comment]
@ShervinAbd92 
Do you mind updating that issue with a few more details about how that "missing score" result came up? I can't replicate the error. The query graph is very odd (including a workflow field, which is odd for an MVP question) leading me to believe this may have been submitted external to the ARS or something like that.

**Comment by dkoslicki** [comment]
Ok, I've found the culprit: the query
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "ConditionID": {
                    "ids": [
                        "MONDO:0005301"
                    ],
                    "categories": [
                        "biolink:Disease"
                    ]
                },
                "DrugID": {
                    "categories": [
                        "biolink:ChemicalEntity"
                    ]
                }
            },
            "edges": {
                "e01": {
                    "object": "ConditionID",
                    "subject": "DrugID",
                    "predicates": [
                        "biolink:treats"
                    ],
                    "knowledge_type": "inferred"
                }
            }
        }
    }
}
```

Runs successfully on arax.ncats.io, _but fails_ on https://arax.test.transltr.io/ and https://arax.ci.transltr.io/
The failure message "Something went wrong removing nodes from the knowledge graph" shows up [here](https://github.com/RTXteam/RTX/blob/776b1f300f1219def1e07f67020808f3d4f06e27/code/ARAX/ARAXQuery/Filter_KG/remove_nodes.py#L50) in the code base.

1. The xDTD/creative code hasn't changed in a while (right @chunyuma?) and [Filter_KG/remove_nodes.py](https://github.com/RTXteam/RTX/tree/776b1f300f1219def1e07f67020808f3d4f06e27/code/ARAX/ARAXQuery/Filter_KG/remove_nodes.py) hasn't been changed in 3 months. This leads me to believe:
2. @saramsey and @edeutsch were there any changes in the recent deployments that could explain this? I've lost track of which of arax.ncats.io, arax.test.transltr.io, or arax.ci.transltr.io is "the most recent code"

**Comment by edeutsch** [comment]
Plain arax.ncats.io (with no suffix) is the ancient production code that is the same as arax.transltr.io. This is many months old. All the other instances such as arax.test.transltr.io, arax.ci.transltr.io, arax.ncats.io/beta, et al. are all running the newest code from this past development cycle.

**Comment by edeutsch** [comment]
production was last deployed 3 months ago:
https://github.com/RTXteam/RTX/commits/production/code

So it would seem that this bug has been introduced since then.

**Comment by dkoslicki** [comment]
@kvnthomas98 Mind looking into this? I don't know if this is related to your regex filtering that you added a few months ago or not

**Comment by chunyuma** [comment]
@dkoslicki , yes, the xDTD/creative code hasn't changed in a while.

**Comment by kvnthomas98** [comment]
@saramsey or @edeutsch ,
should I push the fix to master?

**Comment by edeutsch** [comment]
I don't know anything about the fix, but if you have determined the problem of the missing scores and have fixed the problem, then yes, please push to master and let's test and get it deployed.

**Comment by kvnthomas98** [comment]
Thanks @edeutsch I pushed the change to master and it has been deployed to CI and I have verified that the above query doesn't fail anymore. [https://arax.ci.transltr.io/?r=188801](https://arax.ci.transltr.io/?r=188801)

**Comment by edeutsch** [comment]
thank you!

**Comment by edeutsch** [comment]
The latest code has been deployed to test.
@kvnthomas98 would you perform your tests again at https://arax.test.transltr.io/
?

**Comment by ShervinAbd92** [comment]
Sure, i can run my test again. i know we ran one on Saturday on the Test environment and it failed with that error. was the latest code deployed today?

**Comment by edeutsch** [comment]
@ShervinAbd92 that would be great, thanks! The latest code was just deployed by ITRB in the past hour. (Tuesday 2pm EST)

**Comment by ShervinAbd92** [comment]
Great, thanks for clarifying @edeutsch
