### ISSUE TITLE
Update ARAX Example Notebooks?

### ISSUE THREAD

**Issue by GitHubbit** [RTXteam/RTX#2237]
Is it possible to update the ARAX example notebooks? Unless I am doing this wrong....
[https://github.com/RTXteam/RTX/blob/master/code/ARAX/Examples/ARAX_Example1.ipynb](url)
I get:
```
Executing query at https://arax.rtx.ai/api/rtx/v1/query
Please wait...
ERROR returned with status 404
```

**Comment by dkoslicki** [comment]
In terms of Translator, 3 years is essentially ancient history. For example, the main API interface is now up to 1.4.2 whereas that one is 1.0.0. You might be able to fix it by replacing the URL with something like https://arax.test.transltr.io/api/arax/v1.4/ui/#/query/query.

However, is there something in particular you would like to accomplish or learn about? If so, I might be able to point you in a better direction.

**Comment by dkoslicki** [comment]
I've updated the first three jupyter notebooks
