### ISSUE TITLE
swap /mnt/data and /mnt/data2 on rtx.ncats.io

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#224]

**Comment by saramsey** [comment]
@edeutsch when did we decide that we wanted to do this?

**Comment by edeutsch** [comment]
I was waffling a little and wondering if it's possible to move the KG2 neo4j data files or other big things to the second filesystem.

but it's probably best just to do the wholesale change as you suggest. Will require a major brain transplant. I think we should schedule it in advance and have all hands on deck in case of a problem.

**Comment by saramsey** [comment]
@edeutsch and @dkoslicki OK please let me know when would be a good day to do this.  I cannot do it June 18-19 as I am going to Seattle.  I'll be back in Corvallis on the 20th.

**Comment by saramsey** [comment]
@flashkicker @DeqingQu Are you available on Thursday the 9th or Friday the 10th to work on this file system migration with me? It would be a good opportunity for you to learn about how we have set up rtx.ncats.io (as well as two more pairs of eyes sanity checking what I am doing).

**Comment by saramsey** [comment]
@edeutsch I assume Aug. 9-10 are fine with you for the migration?

**Comment by edeutsch** [comment]
fine for me!

**Comment by DeqingQu** [comment]
@saramsey I am fine with both Aug. 9th and 10th.

**Comment by saramsey** [comment]
OK, the maintenance work on rtx.ncats.io seems to have been completed successfully(*), as far as I can tell.  Thanks to Ujjval and Deqing for their help. 
 
The RTX installation that is normally externally accessible at:
 
http://rtx.ncats.io
 
seems to be working normally again. So far as we can tell it has services in the "rtx1" docker container behind it. Please let me know if you see any issues with RTX accessed at the above URL, and CC Deqing and Ujjval. 
 
The "/mnt/data" file system on rtx.ncats.io is now 393 GB in total available space. The old file system is mounted (read-only now) as /mnt/data2.  I figure we will keep it around as a back-up just in case something got corrupted in the rsync, that we are not able to discover from the limited testing of RTX that I did. IMPORTANT NOTE: I did not realize until it was too late to abort the maintenance work, that the original /mnt/data was an "xfs" file system. The new /mnt/data had been initialized as an ext4 file system. I only discovered the discrepancy after the rsync was complete, and there wasn't time to perform another rsync during the maintenance window. What does this mean? It means that the actual file system type underlying Neo4j and RTX has changed from xfs to ext4. I'm hoping that will have no effect, and would have modest effect (if any) on performance of services running in rtx1. I note that we have been using ext4 with Neo4j and SQLite extensively on other EC2 instances and have not seen a problem. By all accounts, ext4 is reputed to be extremely robust, probably more robust than xfs.  Also most software is tested with ext4 as it is still more a more dominant FS type in Linux-land, so I think we should be fine.  But if we find that there is some issue with RTX running on an ext4 data file system, we can always roll back. That is one of the reasons why we opted to leave /mnt/data2 in place. 
 
(*) IMPORTANT COMMENT:  @ERIC:  I note that I cannot start MySQL inside the "rtx2" docker container. Are those two MySQL services (inside rtx1 and rtx2, respectively) not supposed to be run at the same time?  Some of your help to troubleshoot this would be most appreciated.

**Comment by saramsey** [comment]
I will leave this issue open until we are convinced that the new /mnt/data is working properly and that we are ready for the next steps:  (1) umount /mnt/data2 and (2) ask Trung to disassociate the EBS volume that is associated as /dev/xvdf1 on rtx.ncats.io.

**Comment by saramsey** [comment]
All, are we OK with unmountining /mnt/data2 on rtx.ncats.io?  Or should we keep it around for a while?
