### ISSUE TITLE
Ranking method may need a refresh; estradiol not showing up high up in these results

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2242]
https://arax.ncats.io/?r=215699

**Comment by saramsey** [comment]
Note that Estradiol (result 52) has two edges supporting it that come from human-curated databases, one of which has knowledge-level set to "manual agent". Consensus of the team at the AHM was that this should automatically lead to a 0.99 score for the result (or something close to that).

**Comment by dkoslicki** [comment]
Similarly for the test: Asset_79 “progestin_treats_Premature_Menopause”. Should be in top 10% as observed by Jared

**Comment by saramsey** [comment]
Created new branch for this issue (off of master, since we are still technically in a coding sprint at this time):
https://github.com/RTXteam/RTX/tree/issue-2242

**Comment by dkoslicki** [comment]
Consider using the `manual` attribute raise the scores:
```
attribute_source:	infores:sider
attribute_type_id:	biolink:agent_type
original_attribute_name:	biolink:agent_type
value_type_id:	string
value:	manual_agent  # <-----
(sub)attributes:	
```

**Comment by dkoslicki** [comment]
Also add specific `NeverShow` bioentities to the blocklist. @kvnthomas98 to provide directions on how to do this

**Comment by saramsey** [comment]
@dkoslicki please see this PR:
https://github.com/RTXteam/RTX/pull/2244

could I get some help to test this out on arax.ncats.io?  I tested it on my laptop and I think these changes to ARAX_ranker.py work (i.e., I'm seeing that the score for Estradiol goes up as one would expect).

**Comment by edeutsch** [comment]
Thanks, Steve.
I have deployed your potential enhancement to /devED and tried to test it
I was initially disappointed that nothing had changed.
But Murphy has smoothly stepped in:
![image](https://github.com/RTXteam/RTX/assets/12707718/550d2121-e340-48a8-ad48-63d3180f7965)

We'll have to wait for MolePro to come back up before this fix can be tested since MolePro is the only place returning the kind of metadata that we look for.

**Comment by dkoslicki** [comment]
@saramsey I see no difference in the ranking for our example DSL query, which was reassuring to me. MolePro seemed to be working just now when I tested it: 
![image](https://github.com/RTXteam/RTX/assets/6362936/c864ed89-87f4-4ea6-804d-6c0ca09d1ecf)
but estradiol appears to still be low down in the list: https://arax.ncats.io/devED/?r=221387

I imagine there could be a couple of reasons for this: a) by default all edges are given a confidence of 1 and then penalized as we go (see [here](https://github.com/RTXteam/RTX/blob/01fa88ec5ac2fc1d4da743d522300188c6bba168/code/ARAX/ARAXQuery/ARAX_ranker.py#L260) and the following) so we might consider giving a smaller initial confidence score and/or 2) perhaps the [attribute scraper/combiner](https://github.com/RTXteam/RTX/blob/01fa88ec5ac2fc1d4da743d522300188c6bba168/code/ARAX/ARAXQuery/ARAX_ranker.py#L520) isn't correctly handling the new attributes (eg. the new/temporary KP confidence scores).

Apologies I haven't been able to work on this myself; bummer of timing with Spring break, parents visiting, etc. etc.

**Comment by edeutsch** [comment]
Agreed, I now see the same. I also saw the default confidence and was wondering about that. I wonder if one aspect at play is that we might use number of publications as a component of the confidence. And this edge from molepro, although claiming to be manual agent asserted knowledge, there are no publications attached. That might be knocking down the edge.

I was thinking for development, it might be useful to add our own visible attribute to each edge of the final weight. That way we can see the weights in the UI and debate about what they should be.

**Comment by saramsey** [comment]
OK I'm working on this issue now, using `/devED` on `arax.ncats.io` (hope that's OK).

**Comment by saramsey** [comment]
I think the current code has a bug, in that it only works if `ARAXRanker.aggregate_scores_dmk` is run _twice_ (!). I think I know why.....  need to test it out.

**Comment by saramsey** [comment]
Guys, the patch 76dd2ff seems to work well if we just set `knowledege_type` to `lookup` in the query graph:

![Screenshot 2024-03-07 at 7 34 02 PM](https://github.com/RTXteam/RTX/assets/5562107/3e4b87d1-8866-4ac7-af1f-f409e22b0411)

**Comment by saramsey** [comment]
Let me check a couple more things, but I think we have a working solution (at least for when we are not in creative mode).

To get this kind of result in  _creative mode,_ I'm going to need @dkoslicki to help since in that case, the result scores are _overwritten_ (in the ranker) after they are computed using the usual frobenius/max-flow/longest-path combined approach.

**Comment by edeutsch** [comment]
Unfortunately all queries from the Translator UI are creative mode queries, so lookup isn't really used at the ARA level much.

**Comment by saramsey** [comment]
Fair enough, but overriding how creative mode does its result scoring seems like it won't be quite so straightforward. That's sorta beyond the scope of what I understood was the request to get coded up by 3/8. I did update ranker so it strengthens the edge scores, as requested. The issue is, for creative mode, I have come to understand (from studying the code this evening) that further down in `ARAXRanker.aggregate_scores_dmk(response)`, the result score that was computed based on edge confidence scores for the KG that the QG is bound to for this result, is replaced entirely by the xDTD model's output score for this result node, as shown here:

https://github.com/RTXteam/RTX/blob/1473ab2a25d9feb0c15b4169b724e384ec4844d0/code/ARAX/ARAXQuery/ARAX_ranker.py#L651

What should we do?  Should I back my three commits for this issue out of master?

**Comment by saramsey** [comment]
I guess I'll keep hacking for a bit, until my laptop battery dies (I'm midway through a cross-country flight at the moment).

**Comment by edeutsch** [comment]
I confess I don't understand the ranker, but I'm thinking if you're forcing manually curated edges to get a weight of 0.999, then xDTD edges should top out at 0.75 or something. I was envisioning that we would do something like manually curated edges are 0.999 and xDTD are 0.75 and modern text mined edges might be 0.6 and SemMedDB edges would be 0.4 or something and then they can compete together, and the most confident knowledge rises to the top? I'm getting the sense that that's not how things work, but that's what I was thinking it was.

**Comment by saramsey** [comment]
Are we currently also showing lookup results when running in creative mode, for the current code on the master branch?

**Comment by dkoslicki** [comment]
Lookups and creative mode queries are both shown for ARS "inferred" queries (right @chunyuma? This was from quite a while ago when we merged the two).

The merger of the two scores (creative vs. lookup) is rather gnarly, given how extremely different the scoring/rankings of these are.

I also predict its a "beyond 3/8" issue to address. In any case, improving the "lookup" scores will help, but only to the extent that the final score is high in comparison to the "creative mode" result scores. And it's not at all obvious to me how to resolve that.

**Comment by saramsey** [comment]
Guys, I'm making progress on fixing this issue for creative-mode. I'm not sure if I will have it done by tomorrow, but hopefully so. But I have to pause for tonight since the flight is landing soon and I have to drive back to Corvallis.

**Comment by edeutsch** [comment]
Well, how about this for a crazy suggestion (and doesn't seem to hard?)
1) We have a module whose job it is to assign each edge a confidence score (0-1) based on some evolving heuristics, something like:
a) manual curator assertions get a max of 0.95 (if the source provides one, it can be multiplied into this)
b) xDTD edges (the final drug treats edge, not the support graph edges) get a max of 0.75
c) modern text mined edges get a max of 0.6
d) SemMedDb get a max of 0.4
e) further refinement as is possible
If a source actually provides a confidence, we can consider how to adjust these a bit based on how reliable we feel the sources are.

2) then for each result, we gather the confidences for each of the edges:
![image](https://github.com/RTXteam/RTX/assets/12707718/c0a85b9d-b410-43d4-a76c-7d5ac1bbbd3e)

and simply combine them by multiplying the 1-confidence scores to achieve a result confidence score
i.e. 1 - ( 1-C1) * (1-C2) ... * (1-Cn)

Here are some scenarios:
![image](https://github.com/RTXteam/RTX/assets/12707718/7121fe9f-707d-494d-bd00-8fa94b34f3ab)

What do you think?

**Comment by chunyuma** [comment]
> Lookups and creative mode queries are both shown for ARS "inferred" queries (right @chunyuma?

@dkoslicki, if I understand how lookups function work, it should be automatically called each time the expander is called. The "inferred" queries will trigger calling creative mode in the expander, and so they will also trigger the lookups. But please correct me if I am wrong about how the lookups work within the expander @amykglen and @kvnthomas98?

**Comment by saramsey** [comment]
@chunyuma Thank you for your reply. So if that is true, it sounds like when a query is run through ARAX with `knowledge type = inferred` in the query graph, then _every_ result has its score assigned based on the creative-mode logic in ARAX_ranker, i.e., 
https://github.com/RTXteam/RTX/blob/1473ab2a25d9feb0c15b4169b724e384ec4844d0/code/ARAX/ARAXQuery/ARAX_ranker.py#L651

Is that right? @dkoslicki can you please confirm?

**Comment by saramsey** [comment]
Thank you @chunyuma. That is helpful. I think I've figured out how ARAX_ranker is working, in creative mode (sort of). Testing a patch for this issue now, on `arax.ncats.io/devED`....

**Comment by saramsey** [comment]
OK gentlemen, this is with creative mode:

![Screenshot 2024-03-08 at 9 58 00 AM](https://github.com/RTXteam/RTX/assets/5562107/f80bd152-2b06-4aa9-839b-0051efb75b53)

Please see this PR:
https://github.com/RTXteam/RTX/pull/2247

**Comment by saramsey** [comment]
Closing this issue for now. We can re-open at some point if we want to do further work on the ranker.
