### ISSUE TITLE
ATQLTrait curie id node in KG

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#225]
It looks like there is a single node with an ATQLTrait curie id. You can find it using the cypher query `match (n) where split(n.id,':')[0] = 'AQTLTrait' return n.id as id, n.name as name` which returns:

id | name
-- | --
"AQTLTrait:1085" | "Degree of Spotting"

@saramsey Is this supposed to be in there?

I think this is probably a low priority issue so I am going to mark it as such.

**Comment by saramsey** [comment]
This is a bug.  Might be hard to track down.  Thanks for putting this in GitHub.

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On May 31, 2018, at 2:00 PM, Finn Womack <notifications@github.com<mailto:notifications@github.com>> wrote:


It looks like there is a single node with an ATQLTrait curie id. You can find it using the cypher query match (n) where split(n.id,':')[0] = 'AQTLTrait' return n.id as id, n.name as name which returns:

id      name
"AQTLTrait:1085"        "Degree of Spotting"

@saramsey<https://github.com/saramsey> Is this supposed to be in there?

I think this is probably a low priority issue so I am going to mark it as such.

**Comment by finnagin** [comment]
Also, if it helps the node is a phenotypic_feature node.
