### ISSUE TITLE
xDTD errors in CI

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#2257]
While all tests passed locally for me and @kvnthomas98 , it appears that xDTD tests are throwing errors on the Jenkins CI/CD. I assume this is something back-end. Assigning to @chunyuma or @kvnthomas98 depending on who has time/bandwidth.

**Comment by chunyuma** [comment]
@dkoslicki, I will take a look in the next few days.

**Comment by chunyuma** [comment]
Hi @edeutsch or @amykglen, for this issue, I found [this](https://github.com/RTXteam/RTX/actions/runs/8368801824/job/22913483823#step:12:576) message saying the update xdtd database not present locally. I'm wondering if we need to manually update xdtd model somewhere for CI/CD.

**Comment by amykglen** [comment]
hi @chunyuma - yes, I believe the database manager still needs to be run manually once upon changes to config_dbs.json. see this part of the wiki: https://github.com/RTXteam/RTX/wiki/CI-system-(via-GitHub-actions)#the-runners-workflow

![Screen Shot 2024-03-27 at 1 29 49 PM](https://github.com/RTXteam/RTX/assets/49423686/7eb5be0c-889a-47bf-a625-053ffaa5b597)
(@sundareswarpullela can correct me if I'm wrong)

**Comment by chunyuma** [comment]
Ah, I see. It is good to know about this. Thanks so much @amykglen. I will try seeing if it can fix this issue.

**Comment by chunyuma** [comment]
I close this issue because it has been fixed after updating the xdtd database on cicd.rtx.ai. Thanks @amykglen.
