### ISSUE TITLE
`create_envelope()` DSL command returns an error

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#2258]
Apparently xDTD requires you create a message before using `infer(action=drug_treatment_graph_expansion)`, but doing so returns
```
ERROR: Unrecognized command create_envelope
```
for the input
```
create_envelope()
infer(action=drug_treatment_graph_expansion,node_curie=MONDO:0007827)
```
It appears that `create_message` _does_ work though. Any thoughts @isbluis if this is just a mis-naming of a DSL command that the UI slurped up?

**Comment by saramsey** [comment]
@dkoslicki which is the correct DSL syntax, `create_message` or `create_envelope`?  Please pardon my ignorance.

**Comment by dkoslicki** [comment]
It should be `create_message`, but `create_envelope` is available from the UI DSL dropdown. So this is either a UI think (@isbluis ) or wherever that info is being pulled from. Luis, if you remind me where this comes from, (eg. the DSL readme or somewhere else in the code), I would appreciate it.

**Comment by edeutsch** [comment]
I'm not seeing it?
![image](https://github.com/RTXteam/RTX/assets/12707718/9e64acb0-bafc-4546-aa97-06a35ecf2cf9)

**Comment by dkoslicki** [comment]
DSL, not workflow

<img width="639" alt="image" src="https://github.com/RTXteam/RTX/assets/6362936/aa4957da-f950-4dcf-9bd8-e4ddcb4a8538">

**Comment by isbluis** [comment]
`create_envelope()` is defined in `ARAX_messenger.py` , but there is no mention of `create_message()` .  The UI gathers the DSL requirements from calling the `describe_me` method.

I can see that `create_message()` is only present in `ARAX_query.py`, but I don't gather any info from it, and it does not have a `describe_me` method. 

Not sure what should be done here; maybe discuss at the next AHM?

**Comment by dkoslicki** [comment]
Yeah, next AHM would be good, as it's not clear to me if we should be exposing those on the UI, and/or if `create_message` even does anything outside of `ARAX_query.py`

**Comment by isbluis** [comment]
Submitted a fix (tested in my dev area).  Feel free to close once you verify fix in CI/Test.

**Comment by edeutsch** [comment]
looks like the fix works, thanks, closing!
