### ISSUE TITLE
Bug in QueryPC2::pathway_id_to_uniprot_ids

### ISSUE THREAD

**Issue by erikyao** [RTXteam/RTX#226]
```python
    def pathway_id_to_uniprot_ids(pathway_reactome_id):
        query_str = "uri=http://identifiers.org/reactome/" + pathway_reactome_id + "&format=TXT"
        res = QueryPC2.send_query_get("get", query_str)
        res_set = set()
        if res is not None:
            start_capturing = False
            res_text = res.text
            for line_str in res_text.splitlines():
                if start_capturing:
                    unification_xref_str = line_str.split("\t")[3]
                    unification_xref_namevals = unification_xref_str.split(";")
                    for unification_xref_nameval in unification_xref_namevals:
                        unification_xref_nameval_fields = unification_xref_nameval.split(":")
                        if unification_xref_nameval_fields[0] == "uniprot knowledgebase":
                            res_set.add(unification_xref_nameval_fields[1])
                            if line_str.split("\t")[0] == "PARTICIPANT":
                                start_capturing = True
        return res_set
```

`start_capturing` can NEVER be `True` in this case, so this function always returns an empty set.

And however, do you really need this function? It's not used anywhere.

**Comment by saramsey** [comment]
Not used currently.  Unclear if it will ever be used in the future.

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On May 31, 2018, at 6:31 PM, Yao Yao <notifications@github.com<mailto:notifications@github.com>> wrote:


    def pathway_id_to_uniprot_ids(pathway_reactome_id):
        query_str = "uri=http://identifiers.org/reactome/" + pathway_reactome_id + "&format=TXT"
        res = QueryPC2.send_query_get("get", query_str)
        res_set = set()
        if res is not None:
            start_capturing = False
            res_text = res.text
            for line_str in res_text.splitlines():
                if start_capturing:
                    unification_xref_str = line_str.split("\t")[3]
                    unification_xref_namevals = unification_xref_str.split(";")
                    for unification_xref_nameval in unification_xref_namevals:
                        unification_xref_nameval_fields = unification_xref_nameval.split(":")
                        if unification_xref_nameval_fields[0] == "uniprot knowledgebase":
                            res_set.add(unification_xref_nameval_fields[1])
                            if line_str.split("\t")[0] == "PARTICIPANT":
                                start_capturing = True
        return res_set

start_capturing can NEVER be True in this case, so this function always return an empty set.

And however, do you really need this function? It's not used anywhere.

**Comment by erikyao** [comment]
BioThings will keep this function anyway. I'll skip the test case for it.
