### ISSUE TITLE
CypherError

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#227]
Traceback (most recent call last):
  File "BuildMasterKG.py", line 125, in <module>
    running_time = timeit.timeit(lambda: run_function(), number=1)
  File "/usr/lib/python3.5/timeit.py", line 213, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "/usr/lib/python3.5/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "BuildMasterKG.py", line 125, in <lambda>
    running_time = timeit.timeit(lambda: run_function(), number=1)
  File "BuildMasterKG.py", line 107, in make_master_kg
    ob.neo4j_push()
  File "/mnt/data/orangeboard/RTX/code/reasoningtool/kg-construction/Orangeboard.py", line 551, in neo4j_push
    self.neo4j_run_cypher_query(command)
  File "/mnt/data/orangeboard/RTX/code/reasoningtool/kg-construction/Orangeboard.py", line 476, in neo4j_run_cypher_query
    res = session.run(query, parameters)
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 340, in run
    self._connection.fetch()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 283, in fetch
    return self._fetch()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 323, in _fetch
    response.on_failure(summary_metadata or {})
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/result.py", line 69, in on_failure
    raise CypherError.hydrate(**metadata)
neo4j.exceptions.ClientError: There already exists an index for label 'Base' on property 'UUID'. A constraint cannot be created until the index has been dropped.

**Comment by finnagin** [comment]
Weird. I replaced the lines that create the index on UUID in orangeboard.py with that line which creates the constraint so assuming this is pushing a new graph then there shouldn't be an index already there. @saramsey Is there another script that could be adding this index upstream or is it possible that we are removing nodes/relationships from the graph but not the indexes? In the meantime I can add a line that calls an apoc procedure to remove all the indexes and constraints before adding the new ones.

**Comment by finnagin** [comment]
@saramsey I added the line that should drop all of the existing indexes and constraints just before adding these new ones in as long as apoc is on the neo4j instance this is run on. Let me know if this still causes an error.

**Comment by finnagin** [comment]
I revert to the previous state removing all the code I changed like we talked about on the phone.

**Comment by finnagin** [comment]
The one thing I don't understand, however, is why this worked before if this particular exception is being raised. Since the line that my code replaced `self.neo4j_run_cypher_query('CREATE INDEX ON :Base(UUID)')` should also throw the same exception if (as it says in the exception) there is already a constraint on :Base(UUID). Thus, I'm a bit worried that something else upstream is going wrong to cause this error and even though I changed the code back to how it was before I added anything it will still throw this error when it gets to this part of the code the next time you run it.

**Comment by saramsey** [comment]
Finn -- please make a separate script for adding indexes to the bolt://localhost:7687 Neo4j. 
(rather than having this code in Orangeboard.py).  Adding relationships in Orangeboard.py is not our bottleneck, and it is safer and preferred to break this code out to a separate script.

**Comment by saramsey** [comment]
@finnagin what's the latest on this issue?  Can we close it out?

**Comment by finnagin** [comment]
Yeah, I believe everything is resolved so we can close it out.
