### ISSUE TITLE
block METRIC

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2278]
Could we please add METRIC (`CHV:0000044508`) to the blocklist of overly general or problematic concept IDs? 

![Screenshot 2024-05-15 at 10 25 04 AM](https://github.com/RTXteam/RTX/assets/5562107/88b845c4-f939-4821-80d9-a8718f68ba35)

**Comment by edeutsch** [comment]
In addition to "metric", also add these to the blocklist:

Anesthetics
vaccines
Anti-inflammatory_agents	
Antibodies
Anti-anxiety_agents
Antibodies,_monoclonal
Antidepressive_agents

Prescribed_medications
Vitamin_supplementation
Biological_products
Neuroprotective_agents

**Comment by kvnthomas98** [comment]
Sure will add these
