### ISSUE TITLE
Every push to master causes 2-3hr of downtime on ITRB CI

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2284]
For quite some time, it has been noticed that every push to `master` causes 2-3 hr of downtime while arax.ci.transltr.io automatically refreshes.

One hypothesis is that the instance is needlessly downloading the databases every time.

**Comment by saramsey** [comment]
This has been fixed, right?  (and thank you for that, @edeutsch !)  Can we close it out?

**Comment by edeutsch** [comment]
Yes, ITRB fixed this. Closing.
