### ISSUE TITLE
Limit to 250 results 

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#2288]
Tyler stipulates that ARAs should return no more than 250 results. I think we can address this in the query graph interpreter (change all the filter results from 500 to 250)

**Comment by edeutsch** [comment]
Where/when was this stipulated? I know it was discussed, and we decided to try it to see if it improved speed of the system at all. But it seems like there should be some timing tests before we all do this.

**Comment by dkoslicki** [comment]
https://ncatstranslator.slack.com/archives/C068DQ6688L/p1718113199119099

**Comment by dkoslicki** [comment]
Closing as implemented and the tests now look at top X% or in top ~30 results
