### ISSUE TITLE
autocomplete server at Ohio State seems to be down

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#229]
http://rtxcomplete.ixlab.org/bootstrap.js

http://rtxcomplete.ixlab.org/

https://rtxcomplete.ixlab.org/

**Comment by arnabdotorg** [comment]
Moved to #230

**Comment by arnabdotorg** [comment]
@edeutsch  @dkoslicki  @saramsey Autocompletion server is back up as HTTP.

#230 will contain the HTTPS tasks.
