### ISSUE TITLE
Changelog since 2024-06-21 deployment to TEST (Fugu)

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2295]
Please add your substantial commits since master was deployed to TEST on the date in the title by EDITING this post with a terse Changelog entry.
- Fixed bug that broke single-node queries ([#2306](https://github.com/RTXteam/RTX/issues/2306))
- Rolled out RTX-KG2.9.2c
- Added treats refactor, knowledge level/agent type support.
- Revise ranker per #2300 resulting in much better test performance
- Improved KG2c/synonymizer build systems and added automated tests #2283 
- Added patch to filter Chembl `biolink:applied_to_treat` edges out of KG2c #2320
- Rolled out RTX-KG2.10.0c
- Add patch to address KG2's non-responsiveness to 'treats' queries #2328
- Update requirements.txt to more explicitly list all versions of opentelemetry packages to fix 2024-07-26 debacle

**Comment by amykglen** [comment]
should we close this and create a changelog issue for Guppy?

**Comment by edeutsch** [comment]
yes, absolutely, I thought I already did this, but clearly forgot.
Please add your new changes here: https://github.com/RTXteam/RTX/issues/2344

Closing this in favor of #2344
