### ISSUE TITLE
Develop a script to build a NGD Database

### ISSUE THREAD

**Issue by mohsenht** [RTXteam/RTX#2311]

**Comment by dkoslicki** [comment]
@chunyuma @amykglen don't we have an NGD/FastNGD database builder somewhere?

**Comment by chunyuma** [comment]
[This script ](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Overlay/ngd/build_ngd_database.py)should be what you need. Correct me if I am wrong @amykglen.

**Comment by chunyuma** [comment]
But it seems like that script is not for building a database to store the NGD scores but for storing the PMID mapping only.

**Comment by amykglen** [comment]
yes, that's right - the script Chunyu shared is the one we use for building the `curie_to_pmids.sqlite` database - ARAX doesn't do any further precomputation for NGD scores than that (so far). FYI there is also a README with instructions on how to use that script: https://github.com/RTXteam/RTX/tree/master/code/ARAX/ARAXQuery/Overlay/ngd
