### ISSUE TITLE
Filtering out any results that depend on biolink:applied_to_treat

### ISSUE THREAD

**Issue by sundareswarpullela** [RTXteam/RTX#2320]
This is a short term workaround to filter out result edges coming from `infores:chembl` that depend on `biolink:applied_to_treat` until the edges are removed in the KG2.10.1pre build stage.

**Comment by amykglen** [comment]
I just pushed a patch for this in the `kg2.10.0c` branch because I was in the code and will be starting that build soon - but if @sundareswarpullela or @saramsey think that this patch should be added elsewhere, I can easily remove the two lines of code

**Comment by sundareswarpullela** [comment]
Awesome @amykglen , this will avoid `infores:chembl` edges that depend on `biolink:applied_to_treat` in the KG2.10.0c build itself.

**Comment by amykglen** [comment]
confirmed that no `biolink:applied_to_treat` edges from `infores:chembl` exist in KG2.10.0c, as desired. closing
