### ISSUE TITLE
Instant answers as part of autocomplete

### ISSUE THREAD

**Issue by arnabdotorg** [RTXteam/RTX#234]
Small definitions such as *`what is lovestatin`* that yields 1-2 sentences should show an "instant answer" underneath the autocompletion suggestions.
- [x] Generate list of definitions (TSV, first column phrase, second column definition)
- [x] Figure out way to compress and load this at loadtime in the frontend
- [x] use `/define?q=` to pull the definition from the autocompletion server

**Comment by arnabdotorg** [comment]
![image](https://user-images.githubusercontent.com/421604/43743654-bbb07a5a-99a4-11e8-8de5-37ddb55f15f5.png)

Waiting for @Palzer to implement task 3, otherwise this is completed.

**Comment by Palzer** [comment]
![quick_def](https://user-images.githubusercontent.com/2496884/43979834-049e99a0-9cba-11e8-92b5-287b6a87faee.png)

**Comment by edeutsch** [comment]
Is it checked in? I'm running the latest in trunk at rtx.ncats.io/devED/ but I'm not seeing the definitions:
![image](https://user-images.githubusercontent.com/12707718/43980357-b5763a84-9ca2-11e8-91f3-d0024ec62ae1.png)

**Comment by edeutsch** [comment]
thanks for checking it in. Seems to work! https://rtx.ncats.io/devED/
