### ISSUE TITLE
ARAX UI thinks false values are empty

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2343]
while working on hosting CTKP, I noticed that when an `attribute.value` is `false`, the UI appears to think that value is empty and highlights it red - see the three red 'empty / no value!' lines here:

![Screenshot 2024-08-07 at 12 32 00 PM](https://github.com/user-attachments/assets/a79c75d3-fdfa-4b6e-a89c-06fc58d0e638)

you can see in the raw JSON response that those values are actually false, not null/empty:
```
                {
                  "attribute_type_id": "child",
                  "value_type_id": "metatype:Boolean",
                  "value": false
                }, ...
                {
                  "attribute_type_id": "older_adult",
                  "value_type_id": "metatype:Boolean",
                  "value": false
                }, ...
            {
              "attribute_type_id": "elevate_to_prediction",
              "attribute_source": "infores:multiomics-clinicaltrials",
              "value_type_id": "metatype:Boolean",
              "value": false
            },
```

to reproduce this example, go to the `Settings` tab in the UI and change the 'External API' url to `https://ctkp.rtx.ai:9990`. then submit this query to 'OTHER' and click on the edge in the result: 
```
{
  "edges": {
    "e00": {
      "subject": "n01",
      "object": "n00",
      "predicates": [
        "biolink:in_clinical_trials_for"
      ]
    }
  },
  "nodes": {
    "n00": {
      "ids": [
        "MONDO:0004992"
      ]
    },
    "n01": {
      "ids": [
        "CHEBI:46081"
      ]
    }
  }
}
```
thanks!

**Comment by isbluis** [comment]
Hy @amykglen .  Thanks for the report.  By any chance, so you have the UUID (or ARAX id) for that response?

**Comment by amykglen** [comment]
uhh, since it was submitted to an External API (in Settings tab), I don't think it has one? or at least I don't see one (and it says `[no response_id]` in the page title)

**Comment by isbluis** [comment]
I think I have fixed this in _devLM_ -- please let me know if you are able to check/verify before I push the changes.
https://arax.ncats.io/devLM/index.html
Thanks!

**Comment by edeutsch** [comment]
Looks good to me, thanks
![image](https://github.com/user-attachments/assets/7c75cb71-20c2-44b6-9359-533f34688dab)

**Comment by isbluis** [comment]
Closing as completed
