### ISSUE TITLE
Need an explanation for Loss of results in Fugu

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2347]
Hi, does anyone have some time to investigate and write a summary of why the number of results from ARAX has dropped precipitously in Fugu for Castleman?

https://github.com/NCATSTranslator/Feedback/issues/910

**Comment by dkoslicki** [comment]
@chunyuma any thoughts?

**Comment by chunyuma** [comment]
Do we have deployed the KG2.10.0? If so, the reason is because we are still using the refreshed xDTD which causes lots of results lost. Please see more details in [issue 2327](https://github.com/RTXteam/RTX/issues/2327).

Now the full version of xDTD is estimated to be ready on this Friday.

**Comment by edeutsch** [comment]
Fixed with new xDTD.
