### ISSUE TITLE
should this not be python 3.9.18, in the production branch?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2348]
https://github.com/RTXteam/RTX/blob/20beebcba4284478ae7e28f93d0e8bf3c470fa73/code/UI/OpenAPI/python-flask-server/RTX_OpenAPI.start#L20

**Comment by edeutsch** [comment]
yes, I suppose it probably should in all branches. Based on how things are today after our transition to us-east:

arax.ncats.io has a custom Python compiled here:
/mnt/data/python/Python-3.9.18
and there is no 3.9.16

So yes, it should be:
```
export PATH=/mnt/data/python/Python-3.9.18/bin:$PATH 
```

But all the custom "start" scripts on arax.ncats.io all already have
```
export PATH=/mnt/data/python/Python-3.9.18/bin:$PATH 
```

so what is in the repo is most irrelevant.

As a side node, as far as I can tell, all of the ITRB instances do NOT have a custom compiled Python, they use a Ubuntu python, although they do do some fancy workaround to run and older version (3.9):
```
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt-get update && apt-get install -y python3.9 python3.9-dev python3.9-venv
RUN rm /usr/bin/python3 && ln -s /usr/bin/python3.9 /usr/bin/python3
RUN su rt && cd /mnt/data/orangeboard/production/RTX && python3.9 -m pip install click==8.1.3 && python3.9 -m pip install -r requirements.txt && python3.9 -m pip install connexion[swagger-ui]
```

So I think the ITRB instances are also doing:
```
export PATH=/mnt/data/python/Python-3.9.16/bin:$PATH 
```

but there is no /mnt/data/python I think, so it is all irrelevant.

So I am going to update the scripts to Python-3.9.18, but as far as I understand, this will have no practical effect. I will do it first in `master` --> CI and make sure nothing breaks, and then it will eventually get to TEST and PROD in due time. I won't do it to `production` itself.

As a side note, we would probably upgrade to Python 3.10 sometime soon. Perhaps as part of technical debt amelioration efforts.

**Comment by edeutsch** [comment]
Updated to 3.9.18, although I don't think this has any practical impact on arax.ncats.io or ITRB instances. closing.
