### ISSUE TITLE
Improve quality of xCRG Paths

### ISSUE THREAD

**Issue by kvnthomas98** [RTXteam/RTX#2352]
- [x] Find paths through nodes belonging to the below node categories:

    
    'BiologicalProcess', 'BiologicalProcessOrActivity', 'Cell', 'CellularComponent', 'ChemicalEntity',
    'Drug', 'Disease', 'DiseaseOrPhenotypicFeature', 'Exon', 'Gene', 'GeneProduct',
    'GeneFamily', 'GeneGroupingMixin', 'GeneOrGeneProduct', 'MolecularActivity',
    'NoncodingRNAProduct', 'PathologicalProcess', 'PhenotypicFeature', 'Pathway',
    'PhenotypicFeature', 'Protein', 'ProteinDomain', 'ProteinFamily', 'PhysiologicalProcess',
    'RNAProduct', 'SmallMolecule', 'Transcript'
    

- [x] Prioritize edges as low as possible in the biolink hierarchy

**Comment by dkoslicki** [comment]
And just FYI, in the node category list, it's implied to also include/allow children of these nodes as well.
