### ISSUE TITLE
a few concept nodes to add to the Blocklsit

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2354]
The Example 2 search results bring up a few overly general concepts:  "Introns", "antioxidant", and "Oils". Can we please add these three concept nodes to the blocklist of overly general concept nodes?

![Screenshot 2024-08-23 at 5 17 18 PM](https://github.com/user-attachments/assets/9bb2e38d-0b41-42c6-bf3e-cfd47026409b)

**Comment by dkoslicki** [comment]
And additional ones to add:
Vitamin supplementation
Adjuvants, immunologic
Anti-anxiety agents
prescribed medications

**Comment by edeutsch** [comment]
The latter set of 5 are already added. The new 3 will be added today
