### ISSUE TITLE
Some KG2 entries still sit in the active queries table

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2356]
Luis reports that there are still some queries that never seem to get removed from the active queries table. 

![image](https://github.com/user-attachments/assets/89582227-5f02-408d-8d7b-f21722402400)

Unclear if it causing any substantial problems, but is untidy. This was discussed in an issue long ago, but never 100% addressed.

**Comment by saramsey** [comment]
Hmm, is this potentially issue #2114 coming back?

**Comment by edeutsch** [comment]
yep, although it never really went away. It was just seen less frequently with less traffic.

I vaguely recall that the next and final resort was going to be to spawn a subprocess, wait a certain amount of time and then if it hadn't finished, shoot it and update the active query entry.

**Comment by isbluis** [comment]
Just updating current state: we have several dozen "long-running" queries according to the active queries table, including one started on Aug.6:
![image](https://github.com/user-attachments/assets/033b3c63-a4f3-4ac3-a08f-6d1b084cb09c)

**Comment by edeutsch** [comment]
I think the plan/hope is that as we deploy Amy's new PloverDB 2.0 to additional maturity levels, these problems will go away, so probably no action needed at this time on this issue.
