### ISSUE TITLE
Add 'Post to CTKP' and 'Post to DAKP' buttons to UI for the relay

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2366]
for the CTKP/DAKP/Plover session at the relay, to make it easier for people to query those KPs and review results, I was wondering about the feasibility of adding two buttons to the main 'Queries' tab in the ARAX UI: `Post to CTKP` and `Post to DAKP`, that are configured to use the proper urls for those KPs… would that be easy to do? these buttons needn’t be rolled out to our regular ARAX endpoints - maybe just do it in a branch and have them on an endpoint like /devED or something?

the URLs code be hardcoded as:
* CTKP: `https://multiomics.rtx.ai:9990/ctkp`
* DAKP: `https://multiomics.rtx.ai:9990/dakp`

thank you!!

**Comment by isbluis** [comment]
Hi @amykglen .  I have added a temporary page here:   https://arax.ncats.io/devLM/relay.html

Please let me know if there are any issues with it, or if you'd like other changes or features added.

**Comment by amykglen** [comment]
awesome, thank you!!

**Comment by isbluis** [comment]
No worries!  Glad that it worked.

I can also add a more "permanent" link to the Settings page in the UI alongside the other KPs -- is it worth doing?  Or best wait?  Or...?
![image](https://github.com/user-attachments/assets/be29099f-022d-4465-a58b-ec3c3a4ef526)

**Comment by amykglen** [comment]
that'd be great, thanks!

**Comment by isbluis** [comment]
Added in https://github.com/RTXteam/RTX/commit/641d570da2acbabcf6e80ffcd34f9b608cbf380f (but mistagged the issue...)
