### ISSUE TITLE
ChEMBL CURIE IDs need to be fixed

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#237]
From Julie McMurry:

> I don't see why Biolink shouldn't have these 4 missing prefixes in the yaml. The corresponding sources mightn't yet be in Monarch but that doesn't preclude their inclusion in the prefix map. It would be nice if we didn't have yet another map to reconcile; it isn't a big deal per se, just probably not really worth the effort. Just my 2c. 
> Note that the assembled chembl curies are going to be a bit heavy by necessity as their local IDs have baked in branding. This does look a little weird in the end but it is better than the alternative: let's *not* :) get into the business of parsing out the baked-in fragment from the local IDs or it will only make matters worse. This will just have to do...
> CHEMBL.TARGET:CHEMBL3467
> CHEMBL.COMPOUND:CHEMBL308052

**Comment by saramsey** [comment]
fixed in code; testing now on rtxsteve.saramsey.org

**Comment by dkoslicki** [comment]
Steve: have the ``chemical_substance`` ``id``'s been changed in the KG? If so, can you let me know what they've been changed to?
