### ISSUE TITLE
Profiling Example 1 Query: how could we be faster?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2372]
Hi everyone, I just put in a little effort profiling a run of Example 1 through ARAX. This is just once instance of course
https://arax.ci.transltr.io/?r=293759

Here's my analysis:

0.15s Launch, setup, and start launching queries to KPs and begin waiting for responses. wow, fast!
------- 0.3s since KP request: MolePro responds already!
------- 0.8s since KP request: RTX-KG2 responds, nice!
----- <1.0s 8 other KPs are queried and respond with no edges, but do so in less than a second
------- 6.5s since KP request: Service Provider lumbers across the finish line panting heavily
------- 24.5s since KP request: SPOKE finally limps across the finish line
0.5s Add NGD edges to the graph
0.6s Remove general concepts from the knowledge graph
<0.1s Other steps like Resultify seem negligible
0.3s Writing the Response to the S3 bucket

26.6s: Total processing time from receipt to begin streaming Response
24.5s: Time spent waiting for KPs to respond: MolePro, RTX-KG2 are sub-second. Service provider slowish. SPOKE a turtle
  2.1s: Other processing of data

Two local processing steps appear to stand out:
1) Computing NGD edges. 0.5 seconds seems pretty reasonable, but could it be 0.05 seconds?
2) Removing general concepts: 0.6 second is okay, but this seems like our slowest general processing step. Could this be 0.06 seconds?

Conclusion: How could we be faster?
1) We could timeout our KPs faster. I think I overheard that Aragorn times out their KPs at 10s
2) We could remove general concepts faster? My sense is that that could be a lot faster, knowing nothing about what's actually happening here.
3) We could cache the whole initial query. If this same exact query has been done before very recently, why do it again?
4) We could cache KP queries/results. If we sent an exact same query to a KP very recently, why do it again?

**Comment by isbluis** [comment]
I will add that some of these KPs are not responding well, and seem to take a long time (30-60 sec) to return an error.
See issues:
https://github.com/NCATSTranslator/Feedback/issues/946
https://github.com/NCATSTranslator/Feedback/issues/947
https://github.com/NCATSTranslator/Feedback/issues/948

**Comment by edeutsch** [comment]
Closing this after spawning issue #2388 
and #2374
