### ISSUE TITLE
issue with description field in some metabolites

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#238]
Here is an example of a metabolite node, for which the description field doesn't seem to be correct:

> <id>:422760UUID: 8e918920-69c4-11e8-9cf9-0242ac110002
> accession: C00022
> category: metabolite
> description: Famciclovir is a guanine analogue antiviral drug used for the treatment of various herpes virus infections, most commonly for herpes zoster (shingles). It is a prodrug form of penciclovir with improved oral bioavailability. Famciclovir is marketed under the trade name Famvir (Novartis).
> expanded: true
> id: KEGG:C00022
> name: Pyruvate
> rtx_name: KEGG:C00022
> seed_node_uuid: 87105c30-69c4-11e8-9cf9-0242ac110002
> uri: http://www.genome.jp/dbget-bin/www_bget?C00022

the above came from the following Cypher query on rtxsteve.saramsey.org:7474:

    match (n:metabolite {name: "Pyruvate"}) return n

**Comment by DeqingQu** [comment]
@saramsey  I have tested the latest UpdateNodesInfo.py module. The crash bug of Issue 239 has been fixed and never happens again.
The "Pyruvate" node can retrieve the description from HMDB correctly. Here is the latest result.
```
{
  "expanded": true,
  "rtx_name": "KEGG:C00022",
  "name": "Pyruvate",
  "description": "Pyruvic acid is an intermediate compound in the metabolism of carbohydrates, proteins, and fats. In thiamine deficiency, its oxidation is retarded and it accumulates in the tissues, especially in nervous structures (From Stedman, 26th ed.). Biological Source: Intermediate in primary metabolism including fermentation processes. Present in muscle in redox equilibrium with Lactic acid. A common constituent, as a chiral cyclic acetal linked to saccharide residues, of bacterial polysaccharides. Isolated from cane sugar fermentation broth and peppermint. Constituent of Bauhinia purpurea, Cicer arietinum (chickpea), Delonix regia, Pisum sativum (pea) and Trigonella caerulea (sweet trefoil) Use/Importance: Reagent for regeneration of carbonyl compdounds from semicarbazones, phenylhydrazones and oximes. Flavoring ingredient (Dictionary of Organic Compounds). Pyruvic acid is found to be associated with Fumarase deficiency, which is an inborn error of metabolism.",
  "accession": "C00022",
  "id": "KEGG:C00022",
  "UUID": "e3d0367a-5907-11e8-95d6-060473434358",
  "category": "metabolite",
  "uri": "http://www.genome.jp/dbget-bin/www_bget?C00022",
  "seed_node_uuid": "dbf1734c-5907-11e8-95d6-060473434358"
}
```

However, only 3635 / 18300 nodes' descriptions can be retrieved from HMDB.

**Comment by saramsey** [comment]
Above-reference MWE Cypher query shows that this issue appears to be resolved.
