### ISSUE TITLE
test_ARAXRanker_test9_asset614 failing in `master` since Saturday

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2389]
since Saturday `test_ARAX_ranker.py::test_ARAXRanker_test9_asset614` has been failing in `master`

for instance, see the test build for my latest commit:
https://github.com/RTXteam/RTX/actions/runs/11111007504/job/30869985003#step:13:1302

on Saturday I noticed that this test was failing when I ran the pytest suite locally, so I tried running the test without any local changes over what was already in `master` (as of Friday), and it still failed, so I don't think it's due to changes I made?

**Comment by chunyuma** [comment]
No sure what change causes no result for this test. It seems like it seems to be due to the xDTD fixes in #2160. I am working on it.

**Comment by chunyuma** [comment]
The issue has been resolved in the latest commit. It now passes, but because it takes too long to run, I marked it as slow. All non-slow tests have passed except for `test_xdtd_issue2160` due to #2392, which requires your help to resolve the issue. Thank you!

**Comment by chunyuma** [comment]
Hi @amykglen, can we close this issue as well?

**Comment by amykglen** [comment]
yes, thanks!
