### ISSUE TITLE
ARAX suddenly returning zero results for Test Case 17

### ISSUE THREAD

**Issue by isbluis** [RTXteam/RTX#2395]
The [latest CI testing results](https://arax.ncats.io/devLM/index.html?systest=107) show that ARAX [returns zero results ](https://arax.ci.transltr.io/?r=db68f1f7-16e6-4463-89f2-2044f3ef295d)for the query in _Test Case 17_.

You can see that in [previous runs ](https://arax.ncats.io/devLM/index.html?systest=103)of the same query, ARAX did return results.

**Comment by amykglen** [comment]
also appears to be fixed on CI after the fix for #2397 - good to close?

https://arax.ci.transltr.io/?r=309957

**Comment by isbluis** [comment]
Excellent, thanks!
