### ISSUE TITLE
ARAX suddenly returning zero results for Test Case 21

### ISSUE THREAD

**Issue by isbluis** [RTXteam/RTX#2396]
The [latest CI testing results](https://arax.ncats.io/devLM/index.html?systest=107) show that ARAX [returns zero results ](https://arax.ci.transltr.io/?r=992a4547-bce6-44ce-8c4f-3ec9f2917f78)for the query in _Test Case 21_.

You can see that in [previous runs ](https://arax.ncats.io/devLM/index.html?systest=103)of the same query, ARAX did return results.

**Comment by isbluis** [comment]
In case this helps as a clue, the response also reports a non-zero `total_results_count`

![image](https://github.com/user-attachments/assets/e7f99a86-16d4-4797-bf2b-85b9720782c9)

**Comment by amykglen** [comment]
this appears to be fixed on CI now (after the fix to Plover in #2397) - good to close?

**Comment by isbluis** [comment]
Excellent, thank you!

**Comment by isbluis** [comment]
Not sure if this is directly related to this issue, but I notice that some publications have Amazon S3 URLs -- is this expected?
![image](https://github.com/user-attachments/assets/9baaf2c7-753a-4109-8100-d11540936242)

**Comment by amykglen** [comment]
interesting, good question - that's unrelated to this issue, and from what I can tell so far it looks like those are coming from other KPs. for instance, node `CHEBI:187893` is one with such s3 urls (JSON response [here](https://arax.ci.transltr.io/api/arax/v1.4/response/309958)), and in KG2.10.1c its `publications` property only includes PMIDs. 

whoever it is that's providing those doesn't appear to fill out the `attribute_source`, so I don't know who it is, but we could track it down. would that be good to do?

**Comment by isbluis** [comment]
Looks like it is coming from MolePro.  I'll open an issue for them.  Thanks!
