### ISSUE TITLE
Speeding up QueryNCBIeUtils

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#24]
Just a note that when you query two MeSH terms, it give the joint and the marginals:
Note that with ``https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=%28%22malaria%22%5BMeSH%20Terms%5D%29%20AND%20%22osteoarthritis%22%5BMeSH%20Terms%5D&retmode=json&retmax=1000``
You get back three counts corresponding to joint, marginal, marginal:
```
{
    "header": {
        "type": "esearch",
        "version": "0.3"
    },
    "esearchresult": {
        "count": "4",
        "retmax": "4",
        "retstart": "0",
        "idlist": [
            "16425715",
            "11775318",
            "3300734",
            "5982767"
        ],
        "translationset": [
        ],
        "translationstack": [
            {
                "term": "\"malaria\"[MeSH Terms]",
                "field": "MeSH Terms",
                "count": "60405",
                "explode": "Y"
            },
            {
                "term": "\"osteoarthritis\"[MeSH Terms]",
                "field": "MeSH Terms",
                "count": "54506",
                "explode": "Y"
            },
            "AND"
        ],
        "querytranslation": "\"malaria\"[MeSH Terms] AND \"osteoarthritis\"[MeSH Terms]"
    }
}
```

**Comment by saramsey** [comment]
Nice catch!!

**Comment by finnagin** [comment]
I added an optional argument (defaults to False if not ) to pubmed_hits_count that tells it if it is a joint search which if True will return a list of hit counts as follows: [joint, marginal1, marginal2]. Then in the google distance function if both terms are flagged as mesh terms it will use this option to search all 3 in one query.

**Comment by dkoslicki** [comment]
@finnagin Looks like a found a bug in the pubmed_hit_counts:
```python
python3 Q2Solution.py -r 'ritonavir' -d 'DOID:526'
Traceback (most recent call last):
  File "Q2Solution.py", line 280, in <module>
    main()
  File "Q2Solution.py", line 277, in main
    res = answerQ2(drug, disease, k, use_json)
  File "Q2Solution.py", line 107, in answerQ2
    RU.weight_graph_with_google_distance(g)
  File "/home/dkoslicki/Dropbox/Repositories/RTX/code/reasoningtool/QuestionAnswering/ReasoningUtilities.py", line 822, in weight_graph_with_google_distance
    gd_temp = QueryNCBIeUtils.normalized_google_distance(source_mesh_term, target_mesh_term, mesh1=mesh1, mesh2=mesh2)
  File "/home/dkoslicki/Dropbox/Repositories/RTX/code/reasoningtool/QueryNCBIeUtils.py", line 283, in normalized_google_distance
    mesh2=mesh2_str_decorated),joint=True)
  File "/home/dkoslicki/Dropbox/Repositories/RTX/code/reasoningtool/QueryNCBIeUtils.py", line 252, in get_pubmed_hits_count
    res_int += [int(res.json()['esearchresult']['translationstack'][0]['count'])]
KeyError: 'translationstack'
```
I tracked down the error to the following:
``` python
q.get_pubmed_hits_count("(lymph node[MeSH Terms]) AND (IL6[MeSH Terms])", joint=True)
```
For your convenience, here's [the corresponding NCBI link](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=%28lymph%20node%5BMeSH%20Terms%5D%29%20AND%20%28IL6%5BMeSH%20Terms%5D%29&retmode=json&retmax=1000).

**Comment by finnagin** [comment]
@dkoslicki For some reason searching "IL6[MeSH Terms]" on db=pubmed returns "phrase not found" even though searching on db=mesh returns a result (and thus would return a true result when passed to is_mesh_term) but, when I search "IL6" with out labelling it as a mesh term it returns results on db=pubmed. (Maybe this is an error on their end?) 

To fix this I could add an extra check that checks if "phrase not found" is returned in the result and then retries the search as a non mesh term.

**Comment by finnagin** [comment]
@dkoslicki It does. Since the error result conveniently outputs which phrases were not found in the order that they were searched my fix uses that output and then checks it against the original search terms to change only the one not found (or both if both were not found).

Something else to consider though is that if a term is not classified as a mesh term (on pubmed) when it actually is one and is searched individually (as it is when the other term is not a mesh terms) then the search results will return a count of zero (for ni and nij) as opposed to spitting this error like this. 
i.e. If we search "IL6[MeSH Terms]" by itself rather than as a joint search the pubmed hit count function will return 0 instead of spitting an error like when searching with joint=True.

If we want to make the google distance function more robust to this type of error we might consider retrying the search without the addition of "[MeSH Terms]" whenever a pub med hit count of zero is returned for a single mesh term search.

**Comment by dkoslicki** [comment]
Hmmm... Do you mind checking with Steve to see if there's a better way to be going about this? The unfortunate thing is that the API calls are relatively slow, so going the "just try it a bunch of ways and see what sticks" will lead to a general slowdown of the reasoning code. Steve might know of an approach where multiple API calls can be combined into one, or some other way to handle these sorts of cases...

**Comment by finnagin** [comment]
@saramsey I added a methods to test and time the fixes for the error and then compare the times to a baseline time where no error is encountered.

Here is the fix I implemented that fixes both errors by retying the search with the problem term being searched again as a non-mesh term
```
    @staticmethod
    @CachedMethods.register
    def get_pubmed_hits_count(term_str, joint=False):
        term_str_encoded = urllib.parse.quote(term_str, safe='')
        res = QueryNCBIeUtils.send_query_get('esearch.fcgi',
                                             'db=pubmed&term=' + term_str_encoded)
        res_int = None
        if res is not None:
            status_code = res.status_code
            if status_code == 200:
                res_int = int(res.json()['esearchresult']['count'])
                if joint:
                    res_int = [res_int]
                    if 'errorlist' in res.json()['esearchresult'].keys():
                        if 'phrasesnotfound' in res.json()['esearchresult']['errorlist'].keys():
                                if len(res.json()['esearchresult']['errorlist']['phrasesnotfound']) == 1:
                                    res_int += 2*res.json()['esearchresult']['errorlist']['phrasesnotfound']
                                else:
                                    res_int += res.json()['esearchresult']['errorlist']['phrasesnotfound']
                    else:
                        res_int += [int(res.json()['esearchresult']['translationstack'][0]['count'])]
                        res_int += [int(res.json()['esearchresult']['translationstack'][1]['count'])]
            else:
                print('HTTP response status code: ' + str(status_code) + ' for query term string {term}'.format(term=term_str))
        return res_int

    @staticmethod
    @CachedMethods.register
    def normalized_google_distance(mesh1_str, mesh2_str, mesh1=True, mesh2=True):
        """
        returns the normalized Google distance for two MeSH terms
        :param mesh1_str_decorated: mesh string
        :param mesh2_str_decorated: mesh string
        :param mesh1: flag if mesh1_str is a MeSH term
        :param mesh2: flag if mesh2_str is a MeSH term
        :returns: NGD, as a float (or math.nan if any counts are zero, or None if HTTP error)
        """

        if mesh1:  # checks mesh flag then converts to mesh term search
            mesh1_str_decorated = mesh1_str + '[MeSH Terms]'
        else:
            mesh1_str_decorated = mesh1_str

        if mesh2:  # checks mesh flag then converts to mesh term search
            mesh2_str_decorated = mesh2_str + '[MeSH Terms]'
        else:
            mesh2_str_decorated = mesh2_str

        if mesh1 and mesh2:
            [nij, ni, nj] = QueryNCBIeUtils.get_pubmed_hits_count('({mesh1}) AND ({mesh2})'.format(mesh1=mesh1_str_decorated,
                                                                                     mesh2=mesh2_str_decorated),joint=True)
            if type(ni) == str:
                if mesh1_str_decorated == ni:
                    mesh1_str_decorated = ni[:-12]
                if mesh2_str_decorated == nj:
                    mesh2_str_decorated = nj[:-12]
                [nij, ni, nj] = QueryNCBIeUtils.get_pubmed_hits_count('({mesh1}) AND ({mesh2})'.format(mesh1=mesh1_str_decorated,
                                                                                         mesh2=mesh2_str_decorated), joint=True)

        else:
            nij = QueryNCBIeUtils.get_pubmed_hits_count('({mesh1}) AND ({mesh2})'.format(mesh1=mesh1_str_decorated,
                                                                                         mesh2=mesh2_str_decorated))
            ni = QueryNCBIeUtils.get_pubmed_hits_count('{mesh1}'.format(mesh1=mesh1_str_decorated))
            nj = QueryNCBIeUtils.get_pubmed_hits_count('{mesh2}'.format(mesh2=mesh2_str_decorated))
            if (ni == 0 and mesh1) or (nj == 0 and mesh2):
                if (ni == 0 and mesh1):
                    mesh1_str_decorated = mesh1_str
                if (nj == 0 and mesh2):
                    mesh2_str_decorated = mesh2_str
                nij = QueryNCBIeUtils.get_pubmed_hits_count('({mesh1}) AND ({mesh2})'.format(mesh1=mesh1_str_decorated,
                                                                                         mesh2=mesh2_str_decorated))
                ni = QueryNCBIeUtils.get_pubmed_hits_count('{mesh1}'.format(mesh1=mesh1_str_decorated))
                nj = QueryNCBIeUtils.get_pubmed_hits_count('{mesh2}'.format(mesh2=mesh2_str_decorated))
        N = 2.7e+7 * 20  # from PubMed home page there are 27 million articles; avg 20 MeSH terms per article
        if ni is None or nj is None or nij is None:
            return math.nan
        if ni == 0 or nj == 0 or nij == 0:
            return math.nan
        numerator = max(math.log(ni), math.log(nj)) - math.log(nij)
        denominator = math.log(N) - min(math.log(ni), math.log(nj))
        ngd = numerator/denominator
        return ngd
```
Along with the results I received from the test method for this fix:
```
----------
Result and time of fix for 1st error (joint search):
----------
0.7251347330782937
0.7012622356414795
----------
Result and time of fix for 2nd error (individual search):
----------
0.7251226713189755
2.019613742828369
----------
Result and time for potential curve ball:
----------
0.718880181098562
2.239304542541504
----------
Time with no error:
----------
0.31258416175842285
```
(**note:** To clarify these the first number is the resulting normalized google distance for the terms and the second number is the time the function took to complete. The potential curveball section preforms a search where one of the strings has a bunch of '|' deliminators to simulate a search with several synonyms where one "synonym" is just random letters so that the response will contain a phrase not found message for that one synonym but also will contain usable results. The last section is the time it takes for a joint mesh term search that encounters no error to get the google distance)

**Comment by saramsey** [comment]
@dkoslicki  I'm happy to dig deeper to see if there is a way to optimize this. I've asked @finnagin to run his timing/testing code (shown above) *twice* to see if python requests-caching renders the timing difference negligible after the first time.

**Comment by finnagin** [comment]
@dkoslicki @saramsey It worked, after the second run it was instant (note the e-05 at the end of the time):

```
----------
Result and time for 1st error (joint search):
----------
0.7251347330782937
2.384185791015625e-05
----------
Result and time for 2nd error (individual search):
----------
0.7251226713189755
1.8358230590820312e-05
Result and time for potential curve ball:
----------
0.718880181098562
7.152557373046875e-06
----------
Time with no error:
----------
9.5367431640625e-07
```

I'm going to go ahead and close this as it looks like this is solved.

**Comment by saramsey** [comment]
Good

Sent from my iPhone

On Apr 6, 2018, at 17:44, Finn Womack <notifications@github.com<mailto:notifications@github.com>> wrote:


@dkoslicki<https://github.com/dkoslicki> @saramsey<https://github.com/saramsey> It worked, after the second run it was instant (note the e-05 at the end of the time):

----------
Result and time for 1st error (joint search):
----------
0.7251347330782937
2.384185791015625e-05
----------
Result and time for 2nd error (individual search):
----------
0.7251226713189755
1.8358230590820312e-05
Result and time for potential curve ball:
----------
0.718880181098562
7.152557373046875e-06
----------
Time with no error:
----------
9.5367431640625e-07


I'm going to go ahead and close this as it looks like this is solved.
