### ISSUE TITLE
Branch merge NewFmt

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#240]
Hi everyone @dkoslicki @isbluis I have merged the NewFmt branch into master again. This is includes the rather major changes to the API schema that were made during the hackathon.

In the process I destroyed QuestionAnsweringTestSuite.py. But I think I have now correctly restored it. @dkoslicki maybe you can check that it is now okay

In a couple days if all is well with master, I plan to deleted the NewFmt branch.
Please let me know if there are any big problems with the merged master

**Comment by dkoslicki** [comment]
Interestingly, it seemed like the parameters in the last column of ``Questions.tsv`` were no longer being returned by ``ParseQuestion.py``. I fixed this in e7a5e983dab0ebfcb7bd5c345449a9a15247bfc4 by adding the additional parameters back into the return variable ``parameters`` returned by ``parse_question``. @edeutsch Does this go against your philosophy of having ``parse_question`` only return the actual bioentity name as the parameter? If so, where should I insert the additional parameters (such as the ``$target``, ``$association``, and ``$threshold`` parameters)?
