### ISSUE TITLE
Edges with both a qualifier and a support graph should have both [q] and [sg] as a decoration?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2400]
In this result:
https://arax.ncats.io/devED/?r=310318

In Result 5:
![image](https://github.com/user-attachments/assets/b669e424-435c-41d9-8c67-938f089897ae)

There is both a qualifier and a support graph.
I think it would be a nice added feature if the edge had both decorations, i.e. "biolink:affects [q] [sg]"

**Comment by isbluis** [comment]
This is ready in _devLM_:   https://arax.ncats.io/devLM/index.html?r=310318

**Comment by isbluis** [comment]
Should be fixed with last commit.  Closing.
