### ISSUE TITLE
Move cicd.rtx.ai to `us-east-1`

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2401]
this came up at the KG2 rollout party today

it's been taking the cicd.rtx.ai instance a really long time to download databases, and we imagine a big part of that is because it is still in `us-west-2` while arax-databases.rtx.ai is in `us-east-1`. 

at some point we should probably move cicd.rtx.ai to `us-east-1` as well

**Comment by saramsey** [comment]
making an AMI now....

**Comment by saramsey** [comment]
excellent idea Amy and Sundar!

**Comment by saramsey** [comment]
copying the AMI to `us-east-1` now...

![Screenshot 2024-10-22 at 10 58 31 AM](https://github.com/user-attachments/assets/b291246b-09d5-42a5-b765-8733c16c1075)

**Comment by saramsey** [comment]
OK, the AMI has been copied, but we are now waiting on availability of an elastic IP address

![Screenshot 2024-10-22 at 11 25 50 AM](https://github.com/user-attachments/assets/577bc90d-b649-4732-8842-0e0f96df8cc2)

I've sent a request to COE IT to get the elastic IP address limit raised, for the `us-east-1` region.

**Comment by saramsey** [comment]
Request to raise the quota has been logged via the AWS CLI:

![Screenshot 2024-10-22 at 12 10 08 PM](https://github.com/user-attachments/assets/34effb47-f486-4142-b870-5846b6de334e)

following these instructions from AWS:
https://repost.aws/knowledge-center/request-service-quota-increase-cli

**Comment by saramsey** [comment]
I anticipate we should have a response from AWS within a day or so.

**Comment by saramsey** [comment]
OK, we got our quota raised:
![Screenshot 2024-10-22 at 12 36 09 PM](https://github.com/user-attachments/assets/b785bf4d-3b45-4299-999d-d6c6971ee94c)

**Comment by saramsey** [comment]
I can now ssh into `cicd2.rtx.ai` in `us-east-1`: 

![Screenshot 2024-10-22 at 12 40 25 PM](https://github.com/user-attachments/assets/93ce68f1-d130-4485-aae8-345f7d6183e9)

**Comment by saramsey** [comment]
OK, I believe I have set up the new CI/CD server in `us-east-1` with hostname `cicd.rtx.ai` (the old CI/CD server in `us-west-2` has been stopped, and its hostname is now `cicd-old.rtx.ai`). I ran `/home/ubuntu/actions-runner/run.sh` inside a `screen` session on that instance, as user `ubuntu` . It seems happy?
```
(base) ubuntu@ip-172-31-42-117:~/actions-runner$ ./run.sh

√ Connected to GitHub

Current runner version: '2.320.0'
2024-10-22 20:09:53Z: Listening for Jobs

```

**Comment by saramsey** [comment]
Running a manually triggered Test Build now on the new `cicd.rtx.ai`...

![Screenshot 2024-10-22 at 1 20 12 PM](https://github.com/user-attachments/assets/0e755e6a-758b-4cb2-819f-bf402d1542fb)

**Comment by saramsey** [comment]
Test Build completed successfully. Closing this issue.

![Screenshot 2024-10-22 at 2 13 41 PM](https://github.com/user-attachments/assets/553b6bb3-e873-4d43-a2d9-80bc768c132c)

**Comment by saramsey** [comment]
The `cicd-old.rtx.ai` instance in `us-west-2` has been terminated.
