### ISSUE TITLE
Add button to ARAX UI for querying KG2?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2413]
so given that our KG2 UIs (like kg2.ci.transltr.io) will soon be deprecated, I was wondering if maybe we'll want to add a way to easily query KG2 from the ARAX UI...

people can always use the 'External API'/'Post to OTHER' method, but I was wondering what others think about something like adding a 'Post to RTX-KG2' button to the ARAX UI? or any other ideas?

(sorry I've been making lots of button requests lately) 😂

![Screenshot 2024-11-08 at 10 12 04 AM](https://github.com/user-attachments/assets/38f6abe0-2d28-43d9-8cec-c4e5ac6e9a12)

**Comment by edeutsch** [comment]
Seems like a useful feature.

But *which* KG2 instance should it query? Always CI? or PROD? Or somehow differ based on the particular GUI instance?

**Comment by amykglen** [comment]
yeah, that part is a bit weird - I guess ideally it would differ based on the GUI instance? but if that's difficult, maybe just always query the CI version? I don't think having it always be PROD would be very useful

**Comment by isbluis** [comment]
No worries, @amykglen , please keep the suggestions coming!  :)

This is quite easy to add, of course, but the main question I have is: who will be the main user of this?  Do we expect this button to be of widespread use within Translator, or is it mostly for our team?

I'm tempted to suggest that if it is the latter, I could just make the "Other" button post to RTX-KG2 by default (currently it is MolePro for no reason at all), and only would be changed by the user in Settings.  This way we keep the number of distracting buttons to a minimum.

But open to whatever makes lives easier...

**Comment by amykglen** [comment]
good idea! yeah, I was thinking this will largely just be used within our team. I'm fine with just having 'Other' default to KG2 - I suppose we should use the CI KG2 (https://kg2cploverdb.ci.transltr.io)

**Comment by isbluis** [comment]
Great!  Here it is for a test drive:   https://arax.ncats.io/devLM/index.html
Let me know if that works or prefer some other solution.

**Comment by amykglen** [comment]
looks great to me! thank you!
