### ISSUE TITLE
Creative DTD/CRG edges missing knowledge_level and agent_type

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2422]
I noticed the other day that creative DTD (and also CRG) edges like the one shown below don't appear to have any attributes indicating their `biolink:knowledge_level` and `biolink:agent_type`. I know KPs are required to include those attributes on every edge, and I imagine ARAs are supposed to as well on any edges they create? (not sure whether or not it's required by translator, but even if not, I think it would be nice for users)

<img width="1343" alt="Screenshot 2024-11-18 at 5 10 52 PM" src="https://github.com/user-attachments/assets/5a47ed8f-0ca5-4d4c-afd4-627603065322">

(that edge is from the siltuximab result for our [example 2 query](https://arax.ci.transltr.io/?r=315570))

here's an example of what the knowledge_level/agent_type attributes are supposed to look like, from a CTKP edge:

<img width="308" alt="Screenshot 2024-11-18 at 5 24 46 PM" src="https://github.com/user-attachments/assets/e4c38dca-0232-4a82-a082-ff4783f2ca30">

we would of course need to figure out what the proper values for these are for DTD/CRG - Biolink model definitions are [here](https://github.com/biolink/biolink-model/blob/db265a8ffa0903b478a1c6232fb3a2aec4a5dff9/biolink-model.yaml#L11980-L12151).

what do others think? something we should add? (@chunyuma @kvnthomas98)

**Comment by edeutsch** [comment]
I'm thinking that yes they should be labeled, probably with 'computational model' & 'prediction'

**Comment by chunyuma** [comment]
Thank you @amykglen. I totally agree with @edeutsch's suggestion after looking at the Biolink model definitions (thank you @edeutsch). 

So for each xDTD/xCRG generated edge, I will add the following knowledge_level/agent_type attributes:

```
attribute_source: infores:arax
attribute_type_id: biolink:agent_type
value: computational_model
```
and
```
attribute_source: infores:arax
attribute_type_id: biolink:knowledge_level
value: prediction
```

@edeutsch, if I update the code in the `master` branch, is there an endpoint that I can evaluate if it works? https://arax.test.transltr.io/? Or, I need to wait for you to deploy the code in the next cycle?

**Comment by edeutsch** [comment]
great, thanks, @chunyuma, about 10 minutes after you check in to `master`, the code is live on https://arax.ci.transltr.io/

**Comment by chunyuma** [comment]
thanks @edeutsch. I have pushed the updates to `master`. Will wait and check it on https://arax.ci.transltr.io/

**Comment by chunyuma** [comment]
I have added the `biolink:agent_type` and `biolink:knowledge_level` attributes to the xDTD/xCRG edges (see [this](https://github.com/RTXteam/RTX/commit/1efa3d14bc1cd80f3457146d1f4168f8fcf33a69) commit). 
![Screenshot 2024-11-19 at 11 58 17 AM](https://github.com/user-attachments/assets/94e47e49-7d23-4a04-af5c-aaf5b187dfcd)

However, one interesting observation: I found some `creative_expand_treats` edges show me `not_provided` value for `biolink:knowledge_level`. I indeed added values to both attributes to all xDTD/xCRG edges, otherwise it would not show the `computational_model` for `biolink:agent_type` attribute. So, I am wondering if there is other module in the expand that causes this? Any idea for this (@amykglen)?

![Screenshot 2024-11-19 at 12 02 01 PM](https://github.com/user-attachments/assets/ec75eb6c-43db-4ba1-93e9-7a1bb420e8ea)

**Comment by amykglen** [comment]
@chunyuma - yes, those are the edges created by Expand for #2412 , and I chose "not_provided" as the value for those because it wasn't clear to me if any of the other knowledge level options fit.

**Comment by chunyuma** [comment]
I see. That makes sense. So. please see if my commit has solved this issue? I think now all xDTD/xCRG generated edges should have these two attributes. Thank you!

**Comment by amykglen** [comment]
yes, it looks great. thank you!

**Comment by edeutsch** [comment]
I'm thinking that "automated agent" making a "prediction" seems most appropriate for ARAX Expand inference? ARAX is an automated agent and has determined that there are some edges from clinical trials, etc. that support possible use of the drug to treat the disease, and ARAX is essentially making a prediction that the drug might treat the disease based on some relevant information?

**Comment by amykglen** [comment]
I like that, thanks! I was a bit put off by the definition of 'prediction' at first since this method isn't numeric/probabilistic, but I agree it's still a 'prediction' of sorts. And agree automated_agent seems more accurate than computational_model.

just tweaked those values in `master`! (for the Expand-created creative edges)
