### ISSUE TITLE
answer question "what pharm class is drug [drug] in?"

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#243]
look at the rxnorm database

**Comment by saramsey** [comment]
NCATS has asked if it is possible (in the RTX presentation layer) to group (or collapse) chemical_compounds (drugs) in results by class similarity; maybe incorporate some kind of ontology like the Drug Ontology?

**Comment by dkoslicki** [comment]
@saramsey close due to #788?

**Comment by finnagin** [comment]
@saramsey is this still relevant or should we close?

**Comment by saramsey** [comment]
as this functionality is already present in the Translator UI, I am closing this issue.
