### ISSUE TITLE
need python method to map from a drug to a list of diseases for which the drug is "indicated"

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#245]
input:  a drug identified by its CHEMBL compound ID

output: a list of Disease Ontology IDs and/or Human Phenotype Ontology IDs that the drug is supposed to treat

Implementation:  see if you can use Mychem to do this

**Comment by DeqingQu** [comment]
@saramsey 
The indication of a drug can be retrieved from MyChem. I guess they are what you want.
Here is the 'drug_use' field of the response from http://mychem.info/v1/chem/CHEMBL521?fields=drugcentral.
```
"drug_use": [
      {
        "relation": "contraindication",
        "snomed_id": "24526004",
        "snomed_name": "Inflammatory bowel disease"
      },
      {
        "relation": "indication",
        "snomed_id": "315642008",
        "snomed_name": "Influenza-like symptoms"
      },
      {
        "relation": "contraindication",
        "snomed_id": "449868002",
        "snomed_name": "Smokes tobacco daily"
      },
      {
        "relation": "indication",
        "snomed_id": "76948002",
        "snomed_name": "Severe pain"
      },
    ...]
```
If I dropped of all 'contraindications', I can get the indications of CHEMBL521(ibuprofen).
```
{'relation': 'indication', 'snomed_id': '315642008', 'snomed_name': 'Influenza-like symptoms'}
{'relation': 'indication', 'snomed_id': '76948002', 'snomed_name': 'Severe pain'}
{'relation': 'indication', 'snomed_id': '69896004', 'snomed_name': 'Rheumatoid arthritis'}
{'relation': 'indication', 'snomed_id': '107401000119105', 'snomed_name': 'Acute postoperative pain'}
{'relation': 'indication', 'snomed_id': '22253000', 'snomed_name': 'Pain'}
{'relation': 'indication', 'snomed_id': '386661006', 'snomed_name': 'Fever'}
{'relation': 'indication', 'snomed_id': '230461009', 'snomed_name': 'Headache disorder'}
{'relation': 'indication', 'snomed_id': '266599000', 'snomed_name': 'Dysmenorrhea'}
{'relation': 'indication', 'snomed_id': '396275006', 'snomed_name': 'Osteoarthritis'}
{'relation': 'indication', 'snomed_id': '410795001', 'snomed_name': 'Juvenile rheumatoid arthritis'}
{'relation': 'indication', 'snomed_id': '4969004', 'snomed_name': 'Sinus headache'}
```
I am working on mapping from the SNOMED_id to HP_id or UMLS_id. It is very easy to map from HP_id to SNOMED_id. We can find the SNOMED_id from the 'database_cross_reference' field in http://www.ontobee.org/ontology/HP?iri=http://purl.obolibrary.org/obo/HP_0001945. 
But the mapping from SNOMED_id to HP_id is not straightforward. I got stuck on it and hope to solve it soon.

**Comment by finnagin** [comment]
Hey @DeqingQu You can map directly from SNOMED ids to UMLS using EMBL OXO. Like in issue #244 you can do so using SynonymMapper.py like this:

```
from SynonymMapper import SynonymMapper
sm = SynonymMapper()
umls_id = sm.get_all_from_oxo('SNOMEDCT:76948002', 'UMLS')
```
and you get `['UMLS:C0278140']` in return. 

Unfortunately though oxo doesn't seem to map from Snomed to HP as often as Snomed to UMLS e.g. if we try the above example of severe pain with HP instead of UMLS we get nothing but if we try instead with fever, `sm.get_all_from_oxo('SNOMEDCT:386661006', 'HP')`, we get `['HP:0001945']` in return.

I changed SynonymMapper so that it can handle lists of prefixes now so it might be useful to run these trough a list of prefixes we might want. e.g. for Osteoarthrisis:
```
sm.get_all_from_oxo('SNOMEDCT:396275006', ['DOID', 'HP', 'OMIM', 'UMLS'])
```
will give us `['DOID:381', 'UMLS:C0029408', 'HP:0002758']` in return.

**Comment by DeqingQu** [comment]
Thank you, @finnagin 
Now I can get the mapping results using get_all_from_oxo and it is really a big progress. 

Take ibuprofen as an example again. When I feed all indications of ibuprofen into get_all_from_oxo and  I got `['HP:0002758', 'HP:0001370', 'HP:0100607', 'HP:0012531', 'HP:0005681', 'HP:0001945', 'DOID:381', 'DOID:7148']` in return.

Let's have a look at the result in detail.

| Ontology IDs | name |
| ------------- |:-------------:|
| HP:0002758 | Osteoarthritis | 
| HP:0001370 | Rheumatoid arthritis | 
| HP:0100607 | Dysmenorrhea | 
| HP:0012531 | Pain | 
| HP:0005681 | Juvenile rheumatoid arthritis | 
| HP:0001945 | Fever | 
| DOID:381 | arthropathy |
| DOID:7148 | rheumatoid arthritis | 

Comparing to the indications retrieved from MyChem, the results seem not accurate enough.
Some indications ('Influenza-like symptoms', 'Severe pain', 'Acute postoperative pain', 'Headache disorder' and 'Sinus headache') are missed and some indications ('arthropathy' and 'rheumatoid arthritis') should not be in results.

| snomed_id | snomed_name |
| :-------------: |:-------------:|
| 315642008 | Influenza-like symptoms | 
| 76948002 | Severe pain | 
| 69896004 | Rheumatoid arthritis | 
| 107401000119105 | Acute postoperative pain | 
| 22253000 | Pain | 
| 386661006 | Fever | 
| 230461009 | Headache disorder |
| 266599000 | Dysmenorrhea |
| 396275006 | Osteoarthritis |
| 266599000 | Juvenile rheumatoid arthritis |
| 4969004 | Sinus headache |

BTW, I tried to map SNOMEDCT ID to UMLS ID. However, the result is also not accurate as I expected. "Headache disorder" and "Osteoarthritis" are missed.

| UMLS ID | NAME |
| ------------- |:-------------:|
| C0392171 | Influenza-like symptoms |
| C0278140 | Severe pain | 
| C0003873 | Rheumatoid arthritis | 
| C2215257 | Acute postoperative pain | 
| C0030193 | Pain |
| C0015967 | Fever | 
| C0013390 | Dysmenorrhea |
| C3714757 | Juvenile rheumatoid arthritis |
| C0037195 | Sinus headache |

**Comment by finnagin** [comment]
@DeqingQu Huh, when I try osteoarthritis and headache disorder I get the correct response. If I run the following: 
```
sm.get_all_from_oxo('SNOMEDCT:396275006', 'UMLS')
sm.get_all_from_oxo('SNOMEDCT:230461009', 'UMLS')
```
I get
```
['UMLS:C0021390']
['UMLS:C0393735']
```
And upon looking those up in UMLS I found the first one is Degenerative polyarthritis (a synonym for osteoarthritis) and the second one is headache disorders. Is it possible those results got mixed up somehow?

**Comment by DeqingQu** [comment]
@finnagin Never mind about the UMLS resuls. I applied the `get_cui_from_string_precision` method (in QueryUMLS module) to retrieve the UMLS ids at first, but the result is not as good as using get_all_from_oxo. I will use get_all_from_oxo instead.

I have defined a method called 'map_drug_to_ontology(cheml_id)' (in the DrugMapper module) to do the task you needed. 
```
def map_drug_to_ontology(chembl_id):
"""
mapping between a drug and Disease Ontology IDs and/or Human Phenotype Ontology IDs corresponding to indications
:param chembl_id: The CHEMBL ID for a drug
:return: A dictionary with two fields ('indication' and 'contraindication'). Each field is a set of strings containing the found hp / omim / doid ids or empty set if none where found
"""
```

**Comment by finnagin** [comment]
Hey @DeqingQu I ran into an error when using DrugMapper.py:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/womackf/Dropbox/pyUMLS/kg-construction/DrugMapper.py", line 163, in build_csv
    ont_dict = DrugMapper.map_drug_to_ontology(drug)
  File "/home/womackf/Dropbox/pyUMLS/kg-construction/DrugMapper.py", line 102, in map_drug_to_ontology
    drug_use = QueryMyChem.get_drug_use(chembl_id)
  File "/home/womackf/Dropbox/pyUMLS/kg-construction/QueryMyChem.py", line 217, in get_drug_use
    if 'relation' in drug_use.keys() and 'snomed_id' in drug_use.keys():
AttributeError: 'str' object has no attribute 'keys'
```
It looks like what happened is that when get_drug_use queries my chem and there is only one result instead of multiple the response is a single dict (not in a list) and thus the line `for drug_use in drug_uses:` runs through the keys of the single response instead of the expected list of responses.

Two chembl ids that I have found that cause this are:
```
CHEMBL2107884
CHEMBL250270
```
Here is the drug_use section in the drugcentral part of one of the above responses:
```
{
    ...,
    "drug_use": {
        "relation": "indication",
        "snomed_id": "38341003",
        "snomed_name": "Hypertensive disorder"
    },
    ...
}
```

**Comment by DeqingQu** [comment]
@finnagin Thank you for pointing out the bug. I just fixed it and added them to the test cases.

**Comment by finnagin** [comment]
@DeqingQu No problem! Thanks for fixing it!

**Comment by saramsey** [comment]
@DeqingQu is this issue ready to be closed?

**Comment by DeqingQu** [comment]
@saramsey Yes, it can be closed. The map_drug_to_ontology can map from a drug to a list of indications and contraindications now.
