### ISSUE TITLE
Start using "score" attributes where appropriate

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#246]
The new Result class now has these 4 attributes:
**confidence** (number, optional): Confidence metric for this result, a value 0.0 (no confidence) and 1.0 (highest confidence) ,
**score** (number, optional): Any type of score associated with this result (highest confidence) ,
**score_direction** (string, optional): Sorting indicator for the score: one of higher_is_better or lower_is_better ,
**score_name** (string, optional): Name for the score ,

Previously all there was was **confidence**. But this was being abused a bit by putting scores other than confidences there.

@dkoslicki , please still put confidences in **confidence**. But please now put other scores into the score attribute and describe the score with the attributes above.

@isbluis , if/when @dkoslicki cooks up an example, please update the UI to display these nicely.

Or, feel free to suggest something different. I just stuffed these new attributes into the schema the last time I was updating it (I try to minimize schema changes as these are now getting numbered). We could do something different.

**Comment by dkoslicki** [comment]
Closing due to #788 and #783
