### ISSUE TITLE
need a python method to map from OMIM IDs to HP IDs

### ISSUE THREAD

**Issue by DeqingQu** [RTXteam/RTX#248]
input: OMIM IDs
output: a set of HP IDs
implementation: see if I can use BioLink to do it first

**Comment by saramsey** [comment]
Yes, exactly. this was requested by @dkoslicki  so I am referencing his account here so that he can get updates.  We have some kind of analysis that David needs to do by next Wednesday so if we can have this method by Monday (or even earlier) that would be ideal.

**Comment by saramsey** [comment]
This database might be helpful?
http://phenominer.mml.cam.ac.uk/

**Comment by DeqingQu** [comment]
@saramsey Luckily, We can find the mapping result from a Disease ID to a list of HP IDs easily through BioLink. The method map_disease_to_phenotype has been done and tested.

I am working on creating a relationship between a disease node and a phenotype node. What should the name of the relationship be called?

**Comment by dkoslicki** [comment]
@DeqingQu we should call it ``has_phenotype``

**Comment by DeqingQu** [comment]
@dkoslicki Thanks!

**Comment by DeqingQu** [comment]
> I think you can use the seed_node_uuid property from the Node that is the source node for the relationship.


Thank you, @saramsey. 
@dkoslicki The PatchKG.add_disease_has_phenotype_relations() function is completed and tested on small-size dataset (1000 nodes). I am going to run the code on the whole graph on my laptop. I guess it needs more than 6 hours to run on the whole graph. When the test on the whole graph is passed, I will let you know.

**Comment by dkoslicki** [comment]
Excellent! Are we planning on adding these relationships to the KG, or just generating them on the fly using the class you mentioned?

**Comment by DeqingQu** [comment]
@dkoslicki @saramsey What is the meaning of 'generating them on the fly'?

The whole graph test just completed and it took nearly 7 hours. The number of original relations from disease nodes to phenotype nodes is 661,559. The number of relations queried from BioLink is 711,335. Then the duplicated relations are deleted and the number of final relations is 808,684.

If you want to add these relations to the KG, you can run the following command.
```
$ cd [git repo]/code/reasoningtool/kg-construction
$ python3 PatchKG.py
```

**Comment by dkoslicki** [comment]
I meant to ask if you’re planning on adding these relationships to the neo4j instance itself, or have them accessed some other way (on the fly=getting them from a class/method instead of the neo4j instance). @saramsey, I would prefer these added to the neo4j instance. Can we do that without needing to re-run the whole KG generation?

**Comment by DeqingQu** [comment]
Yes, my code is just a patch to add the relations to the KG. There is no need to re-generate the whole KG.

**Comment by DeqingQu** [comment]
It will take about 7 hours.

**Comment by dkoslicki** [comment]
Can you check with @saramsey and go ahead and do this on Monday morning? I need this for code that is to be implemented by Tuesday at noon.

**Comment by DeqingQu** [comment]
The code is running now.

**Comment by DeqingQu** [comment]
The Ctrl-C bug is fixed now. The script cannot be stopped by Ctrl-C before, because the KeyboardInterrupt exception is blocked by accident. In the API get request, I used 'BaseException' at the end of try-catch to handle all exceptions we don't know. So the 'KeyboardInterrupt' is also handled by the 'BaseException' case and only return None instead of stopping the script.

```
try:
    res = requests.get(url, timeout=QueryBioLink.TIMEOUT_SEC)
except requests.exceptions.Timeout:
    print(url, file=sys.stderr)
    print('Timeout in QueryBioLink for URL: ' + url, file=sys.stderr)
    return None
except KeyboardInterrupt:    # handle KeyboardInterrupt and stop the script
    sys.exit(0)
except BaseException as e:
    print(url, file=sys.stderr)
    print('%s received in QueryBioLink for URL: %s' % (e, url), file=sys.stderr)
    return None
```

**Comment by saramsey** [comment]
running now on rtxdev inside the rtxsteve container.....

**Comment by DeqingQu** [comment]
@dkoslicki The relations are added to the neo4j instance. The number of 'has_phenotype' relations are 808,684 now.

**Comment by dkoslicki** [comment]
Excellent! I've already been using them and things look to be in order. I'll go ahead and close this issue.
