### ISSUE TITLE
add edges for "indicated for" and "contraindicated for" to the KG

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#249]
use the method DrugMapper.map_drug_to_ontology

**Comment by DeqingQu** [comment]
@saramsey DrugMapper.map_drug_to_ontology used MyChem to query the indication and contraindication. But the format of the response data from MyChem has been modified, so the function 'MyChem.get_drug_use' could not work as we expected. I will fix this bug ASAP.

**Comment by saramsey** [comment]
Thanks, @DeqingQu

**Comment by saramsey** [comment]
please make sure that map_drug_to_ontology can return a ontology term as a CURIE ID, like this: DO:12345 or HPO:23456

**Comment by DeqingQu** [comment]
@saramsey I have fixed the bug and push the codes to the Github repo. 
```
onto_set = DrugMapper.map_drug_to_ontology("CHEMBL2107884")
print(onto_set)

onto_set = DrugMapper.map_drug_to_ontology("CHEMBL33")
print(onto_set)
```
It can return the correct CUIRE ID as we expected.
```
{'indications': {'DOID:5870', 'DOID:9498'}, 'contraindications': set()}
{'indications': {'HP:0012330', 'DOID:11400', 'DOID:7427', 'DOID:2050', 'DOID:874', 'DOID:9700'}, 'contraindications': {'DOID:9351', 'HP:0001392', 'HP:0001664', 'HP:0000819', 'DOID:0060185', 'DOID:971', 'HP:0001913', 'HP:0002900', 'HP:0001662', 'HP:0009830', 'HP:0000738', 'DOID:437', 'DOID:574', 'HP:0001657', 'HP:0001250', 'HP:0001882', 'DOID:3393', 'DOID:2355', 'DOID:1588', 'DOID:12987', 'DOID:409', 'HP:0000759', 'HP:0003201', 'DOID:12450', 'HP:0001873', 'HP:0001271', 'DOID:615', 'HP:0001903', 'HP:0100550', 'HP:0012234', 'DOID:1826', 'HP:0001876'}}
```

Before calling any methods in DrugMapper.py, please delete the 'SynonymCache.sqlite' file in 'kg-construction' directory on the server.  Because the format of response data has been changed, the previous cache in the 'SynonymCache.sqlite' file is not valid anymore.

**Comment by saramsey** [comment]
@flashkicker Can you update on how this issue is going?

**Comment by saramsey** [comment]
I'm getting this error when I run:

   python3 -u BuildMasterKG.py -u neo4j -p XXXXXXX 1>stdout.log 2>stderr.log

`Traceback (most recent call last):
  File "BuildMasterKG.py", line 137, in <module>
    running_time = timeit.timeit(lambda: run_function(), number=1)
  File "/usr/lib/python3.5/timeit.py", line 213, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "/usr/lib/python3.5/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "BuildMasterKG.py", line 137, in <lambda>
    running_time = timeit.timeit(lambda: run_function(), number=1)
  File "BuildMasterKG.py", line 94, in make_master_kg
    bne.expand_all_nodes()
  File "/mnt/data/orangeboard/RTX/code/reasoningtool/kg-construction/BioNetExpander.py", line 609, in expand_all_nodes
    self.expand_node(node)
  File "/mnt/data/orangeboard/RTX/code/reasoningtool/kg-construction/BioNetExpander.py", line 597, in expand_node
    expand_method(self)
  File "/mnt/data/orangeboard/RTX/code/reasoningtool/kg-construction/BioNetExpander.py", line 207, in expand_chemical_substance
    res_dict = DrugMapper.map_drug_to_ontology(node.name)
  File "/mnt/data/orangeboard/RTX/code/reasoningtool/kg-construction/DrugMapper.py", line 114, in map_drug_to_ontology
    drug_use = QueryMyChem.get_drug_use(chembl_id)
  File "/mnt/data/orangeboard/RTX/code/reasoningtool/kg-construction/QueryMyChem.py", line 232, in get_drug_use
    if 'contraindication' in drug_uses.keys():
AttributeError: 'list' object has no attribute 'keys'`

**Comment by DeqingQu** [comment]
@saramsey The BuildMasterKG.py has been running for more than 12 hours. The bug has not appeared so far and I think the 'AttributeError' bug has been fixed.
The 'AttributeError' bug is caused by dirty cache. Please pull the latest code on 'issue249-253' branch and delete the 'SynonymCache.sqlite' file in 'kg-construction' directory on the server. Because the format of response data of MyChem has been changed, the previous cache in the 'SynonymCache.sqlite' is not valid anymore.

**Comment by saramsey** [comment]
indicated_for looks good:

![screen shot 2018-07-26 at 1 08 08 pm](https://user-images.githubusercontent.com/5562107/43285809-fefdb1a2-90d4-11e8-8d84-c4d96bbcbb68.png)

**Comment by saramsey** [comment]
![screen shot 2018-07-26 at 1 08 51 pm](https://user-images.githubusercontent.com/5562107/43285830-1089e2f6-90d5-11e8-8aaa-28649ba561ac.png)

looks good
