### ISSUE TITLE
parameterize Neo4j username and password for Python scripts on the project

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#252]
OK we have eight places in our code base where a Neo4j password is found in a Python module. I think it is time that we started to fix this. In general, rather than having the Neo4j username and password passed as a JSON file, I'd prefer that they are passed as command-line arguments (thus we can use Python argparse and the script can provide "help" on the syntax of the arguments). 

I suggest that we start with fixing this issue in DumpNeo4jToCSV.py, since I am sure that nothing depends on it currently.

Then Orangeboard.py; for that, we want to make BuildMasterKG.py use argparse to get the username/password from the command-line, and then BuildMasterKG.py can pass the username/password to Orangeboard  via the Orangeboard.set_auth() method.

For the other six scripts that have the neo4j database password embedded in them, we should talk to David before making *any* code changes.

**Comment by DeqingQu** [comment]
@saramsey 
When I run DumpNeo4jToCSV.py, I got an error. I guess the structure of the relation is modified and the 'sourcedb' is not a property of a relation anymore.

```
Traceback (most recent call last):
  File "DumpNeo4jToCSV.py", line 96, in <module>
    make_rels_file()
  File "DumpNeo4jToCSV.py", line 54, in make_rels_file
    sourcedb = rel_properties['sourcedb']
KeyError: 'sourcedb'

```

**Comment by saramsey** [comment]
Sorry Deqing, I guess there is also a bug in DumpNeo4jToCSV.py that needs to be fixed.  I think "sourcedb" is now "provided_by".

Also can you please make "URL" an optional argument to the script?  Default can be bolt://localhost:7687

**Comment by DeqingQu** [comment]
Yes, I have already done that. I used the '-a' as the parameter for URL, is it fine?

```
10-248-18-67:kg-construction alex$ python3 DumpNeo4jToCSV.py -h
usage: DumpNeo4jToCSV.py [-h] [-a ADDRESS] [-u USERNAME] [-p PASSWORD]

optional arguments:
  -h, --help            show this help message and exit
  -a ADDRESS, --address ADDRESS
                        address and port to connect to.
                        (default:bolt://localhost:7687)
  -u USERNAME, --username USERNAME
                        username to connect as. (default: )
  -p PASSWORD, --password PASSWORD
                        password to connect with. (default: )
```

**Comment by saramsey** [comment]
@DeqingQu  It is fine. Although your documentation should describe the content of the "-a" command-line argument as a "URL" and not an "address".  An IP address is different from a URL.

**Comment by edeutsch** [comment]
So I thought that we already had a solution for this, but it turns out that it is incomplete. We already have the class:
code/RTXConfiguration.py
However, I thought it already got some of its information from a file, but it turns out it does not. Everything is hard-coded in the py code.
I suggest we augment RTXConfiguration.py to pull some information from a static file that is NOT checked in the repo. We could/should have a template file that is in the repo, but not the actual file. Something like config.json.template would be checked in, but config.json is never checked in and would contain the actual information. IMO it would be unnecessary to have some formal mechanism for scp'ing the file, but rather just an informal agreement on where the "master" is. Note that some local instances may wish to override certain values, so it's not clear that all sites need to have this file perfectly in sync.

I also suggest that only RTXConfiguration.py reads this file. Everyone else should use the RTXConiguration class.

What do you think?

**Comment by dkoslicki** [comment]
I like the idea of keeping it in RTXConfiguration.py (perhaps pulling from a json via scp as suggested by @saramsey).

**Comment by DeqingQu** [comment]
Hi @saramsey,
I am planning to refactor our code by the following steps:
1. use code/RTXConfiguration.py to read the 'conf.json' file. Other modules will get the Neo4j username and password through the RTXConfiguration.py
2. The 'conf.json' is read at runtime. If the file doesn't exist, scp the file from somewhere on rtx.ncats.io (we need to set up the ssh keys first).
3. remove the conf.json from our repo and introduce conf.json.template to our repo.

**Comment by edeutsch** [comment]
This sounds good to me, with the minor exception that I don't think there is a conf file yet, so that will need to be created from scratch.

**Comment by saramsey** [comment]
@DeqingQu sounds good

**Comment by DeqingQu** [comment]
Hi @saramsey ,

I generated a new branch issue252 for meeting the requirements of this issue. The code is tested on the 'ISSUE259' docker container on the 'rtx.ncats.io' instance.

The original config.json is located in the '/mnt/temp/config.json' on the 'rtx.ncats.io' instance. The config file is created by the new user 'rtxconfig'. The file permission of the config file is set to 600 and only the user 'rtxconfig' can read and write the file.

For the test, I only add the public key of the 'ISSUE259' container to the /home/rtxconfig/.ssh directory of the 'rtx.ncats.io' instance. So only the 'ISSUE259' container can SSH to the 'rtx.ncats.io' instance now and SCP the config.json file. Please let me know which container or instance can SCP the config file from the 'rtx.ncats.io' instance. I will add the public keys to the .ssh directory and make sure the SCP works.

**Comment by DeqingQu** [comment]
After adding the SSH public key to the user 'rtxconfig' on 'rtx.ncats.io' instance, we can scp files from the 'rtx.ncats.io' instance remotely. But we need to input the password every time. If we want to avoid being asked password every time, we can add the SSH key to ssh-agent.

Here are some tips for generating a new SSH key and adding it to the ssh-agent.
https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

BTW, if you are using MacOS Sierra 10.12.2 or later, you will need to modify your ~/.ssh/config file to automatically load keys into the ssh-agent and store passphrases in your keychain. You can find more details on the previous link.

**Comment by saramsey** [comment]
We will discuss this issue on the Jan. 14 X-ray all-hands meeting; need everyone's SSH public key.

**Comment by saramsey** [comment]
next step after the aforementioned isolation tests for the nine modules would be an "integration test". we should try to do this totally separately from the production installation

**Comment by dkoslicki** [comment]
@DeqingQu I noticed you added a new Neo4j location in RTXConfiguration.py: 
```
self.live = "local"
self.bolt = "bolt://localhost:7687"
self.database = "localhost:7474/db/data"
```
I'm curious about what this is for. in particular, @saramsey will this interfere with our production/KG2 paradigm? I'm just concerned that branch 252 is merged with master, it would now point to a new/local KG.

**Comment by DeqingQu** [comment]
@dkoslicki When we construct a new KG, it is possible that the server/docker we used is a local server which is not in the previous configuration lists. So I added the 'local' configuration for generating a local KG.

The branch Issue252 has not been merged with master, so it will not point to a new/local KG now. 

The program for constructing a new KG (issue299) is still running now. I am planning to merge the branch Issue299 after the new KG is constructed and then merge the branch Issue255 at last. (There will be some conflicts between the branch Issue252 and Issue299, because some files are modified in both branches.)

**Comment by dkoslicki** [comment]
Just FYI @DeqingQu, I've tested the reasoning code, and there seems to be no issues with regard to this issue. @edeutsch @saramsey just so you're aware, you'll want to ``pip install -r requirements.txt``as a few new packages will be required.
From my perspective, it's safe to merge this to master.

**Comment by dkoslicki** [comment]
@DeqingQu Iirc, this has been fully implemented and tested, so do you think it's ok to close this issue?

**Comment by edeutsch** [comment]
Well, I'm not sure this has not been deployed on rtx, so I suggest leaving it open and i will assign this to myself to see if I can get it deployed fully.

**Comment by edeutsch** [comment]
and once it is deployed everywhere, we should actually *change* the password(s)

**Comment by DeqingQu** [comment]
It is not deployed on rtx. Before we deployed it on the production environment, could we do some more tests on rtx?

Here is my plan:
1. Add the linux username who run the QuestionAnswering module to the white list for SCP
2. Test it on the development environment (maybe ‘devED’ , ‘beta’ or a new endpoint)
3. Merge the issue252-cur branch to master and deploy it on the production environment

@edeutsch Could you help me to check which linux user on rtx will run the QuestionAnswering module on the development and production environment?

I checked the server and found the linux user ‘rt’ on ‘rtx1’ container ran the ‘swagger_server' and ‘openapi_server’ process. But I am not sure whether it is the linux user I need to add to the white list for SCP. Or maybe there are other linux users I missed.

```
root@0c3e50fe562a:/# ps aux | grep python
rt         5313  0.0  0.1 2269508 327908 ?      S    05:18   0:25 /usr/bin/python3 -m openapi_server
root       5606  0.0  0.0  11284   928 pts/129  S+   20:39   0:00 grep --color=auto python
rt        22114  0.0  0.1 2425764 201988 ?      Sl    2018  32:17 /usr/bin/python3 -m swagger_server
rt        43388  0.0  0.2 2478476 390824 ?      S     2018  27:28 /usr/bin/python3 -m swagger_server
rt       124212  0.0  0.1 2575204 278528 ?      Sl   Mar07   4:36 /usr/bin/python3 -m swagger_server
rt       124309  0.1  2.4 5893256 4006408 ?     S    Mar07  39:20 /usr/bin/python3 -m swagger_server
rt       126108  0.0  0.0 2328316 155856 ?      S    Mar07   4:24 /usr/bin/python3 -m swagger_server
rt       131071  0.0  0.0  88716 25828 ?        S    Mar08   0:16 /usr/bin/python3 server.py
```

**Comment by saramsey** [comment]
Hi @edeutsch just pinging you about this. We would like to close out this issue next week if possible.  Thanks.

**Comment by edeutsch** [comment]
okay, apologies for not following up on this. Here are my thoughts:
1) It looks like branch issue252-cur is 310 commits behind master. I think this will go more smoothly if we get issue252-cur aligned with master first. Would you get issue252-cur aligned to master first?
2) I'm a little concerned that performing an scp every day is a good idea. What happens if I want to run this on my laptop not connected to the Internet. If it's been more than a day, then is will want to sync and it can't and that means no code will run? Maybe a manual script to perform a sync as desired would be better?

**Comment by edeutsch** [comment]
Also, I'd like to get the MySQL passwords in here as well. So maybe we can augment the format of the config.json file to have usernames and passwords for difference resources rather than just a single one?

**Comment by DeqingQu** [comment]
Hi @edeutsch 
1. In the issue252-cur branch, the username and password are obtained from remote config file. So I think it's better to set up the SCP on the production environment before merging the branch to master. 
2. A cronjob to perform a sync every day would be a good idea. I will write a cronjob script for this requirement. However, the current version could cover the situation that the laptop is not connected to the Internet. If the laptop was connected to the Internet before, the config file would exist in the folder. Then if the laptop is not connected to the Internet, the SCP operation will fail, but the previous configure file is still there and the RTX code will run.

**Comment by DeqingQu** [comment]
It seems there are three major tasks for this issue now.
1. to set up SCP on the production environment
2. to merge the issue252-cur branch to master 
3. to augment the format of config.json and add more interfaces in RTXConfiguration.py

Should I do the tasks in sequence (1->2->3) or do the task 3 first?

**Comment by edeutsch** [comment]
There are now two sets of numbers, so I will refer to the first set as A1,A2,A3, and the second set as B1,B2,B3.

A1. I don't quite understand what you mean by "set up SCP". I performed an scp command to pull the file to devED and it worked fine.

A1b. I was requesting merging all the latest master code into your branch so that we know that all your changes don't cause conflicts in master, and if they do resolve them first. I'm under the impression that if you first merge master into your branch, then it will be easy for me or merge that into master and NewFmt when the time comes.

2. I'm not in favor of setting up cron jobs for this. You can do that in your dev environment, but on rtx I would rather pull when I know I need to. If someone needs to fiddle with the parameters for testing, then cron may stomp on those.

3. I recommend that each current possible value of self.live have an entry in the file. then it's easy to add other resources such as mysql or whatever.

Then regarding B:

B1. Don't understand what this really means
B2. I suggest merge master into branch first so that your branch is not so far behind
B3. Yes.

I suggest do ask B3 first because the format of the file will be different before and after B3, so let's not deploy something when we know the format has to change, otherwise old code and new code and old format and new format will be incompatible. Let's get the format extensible first and then we can add additional resources as necessary.

**Comment by DeqingQu** [comment]
Hi @edeutsch.

A1. "set up scp" means 'add the Linux user (rt in our case) to the whitelist, so the user rt can have the permission to do the SCP operation'. I have added the user rt to the whitelist for scp. Now the user rt can run the scp command to pull the config file to its own folder.

A1b. I have merged the master branch to 'issue252-cur' branch. Now the 'issue252-cur' branch is 60 commits ahead of the master.

A3 / B3. I would like to augment the config.json to the following format. Just like your recommendation, each value of self.live will have an entry in the file. Could you have a look at my draft version and check if I have missed any attributes?
If the format of the config file has been decided, I will add/modify interfaces in the RTXConfiguration.py according to its format.
```
{
    "Production": {
        "neo4j": {
            "bolt": "bolt://rtx.ncats.io:7687",
            "database": "rtx.ncats.io:7474/db/data"
            "username": "xxxx",
            "password":"xxxx"
        },
        "mysql": {
            "host": "rtxdev.saramsey.org",
            "port": "3306",
            "username": "xxxx",
            "password":"xxxx"
        }
    },
    
    "KG2": {
        "neo4j": {
            "bolt": "bolt://rtx.ncats.io:7787",
            "database": "rtx.ncats.io:7574/db/data"
            "username": "xxxx",
            "password":"xxxx"
        },
        "mysql": {
            "host": "rtxdev.saramsey.org",
            "port": "3306",
            "username": "xxxx",
            "password":"xxxx"
        }
    },
    
    "rtxdev": {
        "neo4j": {
            "bolt": "bolt://rtxdev.saramsey.org:7887",
            "database": "rtxdev.saramsey.org:7674/db/data"
            "username": "xxxx",
            "password":"xxxx"
        },
        "mysql": {
            "host": "rtxdev.saramsey.org",
            "port": "3306",
            "username": "xxxx",
            "password":"xxxx"
        }
    },
    ....
}
```

**Comment by edeutsch** [comment]
Hi Deqing, I like the new format, I think this will give us good flexibility. Fine to proceed, thanks.

**Comment by DeqingQu** [comment]
Hi @finnagin and @edeutsch ,

I am refactoring our code and would like to remove all the hardcoded MySQL username and password. When I go through the SemMedInterface.py, in the construction function the module will connect to two different MySQL databases (same host, but different ports).  

```
self.smdb = QuerySemMedDB("rtxdev.saramsey.org",3306,"rtx_read","rtxd3vT3amXray","semmeddb", mysql_timeout)
self.umls = QueryUMLSSQL("rtxdev.saramsey.org",3406, "rtx_read","rtxd3vT3amXray","umls")
```

So I think we have two different MySQL databases (SemMedDB and UMLS) on 'rtxdev.saramsey.org'. If so, in the config.json do I need to split the 'mysql' property into two different properties (mysql_semmeddb and mysql_umls)?
```
{
    "Production": {
        "neo4j": {
            "bolt": "bolt://rtx.ncats.io:7687",
            "database": "rtx.ncats.io:7474/db/data"
            "username": "xxxx",
            "password":"xxxx"
        },
        "mysql_semmeddb": {
            "host": "rtxdev.saramsey.org",
            "port": "3306",
            "username": "xxxx",
            "password":"xxxx"
        },
        "mysql_umls": {
            "host": "rtxdev.saramsey.org",
            "port": "3406",
            "username": "xxxx",
            "password":"xxxx"
        }
    },
    
    "KG2": {
        "neo4j": {
            "bolt": "bolt://rtx.ncats.io:7787",
            "database": "rtx.ncats.io:7574/db/data"
            "username": "xxxx",
            "password":"xxxx"
        },
        "mysql_semmeddb": {
            "host": "rtxdev.saramsey.org",
            "port": "3306",
            "username": "xxxx",
            "password":"xxxx"
        },
        "mysql_umls": {
            "host": "rtxdev.saramsey.org",
            "port": "3406",
            "username": "xxxx",
            "password":"xxxx"
        }
    },
```

**Comment by edeutsch** [comment]
Yes, agreed. I wasn't even aware of those. I was concerned about the MySQL instance that is accessed via the code in UI/Feedback. That is perhaps yet another MySQL server?

**Comment by DeqingQu** [comment]
> Hey Deqing,
> 
> That is correct. Those were read-only login credentials for two different MySQL databases that were on  'rtxdev.saramsey.org'.
> 
> Best,
> Finn

Yes, in my understanding, we have three MySQL databases now, one for UI/Feedback, one for SemMedDB, and one for UMLS). The two databases for SemMedDB and UMLS are located on 'rtxdev.saramsey.org' and the one for UI/Feedback is located on 'localhost'.

**Comment by DeqingQu** [comment]
The code for the new config.json format has been completed (the parameters for Neo4j and MySQL are achieved from the config file now) and the new config.json has been uploaded to ncats.rtx.io.

Could I merge 'issue252-cur' branch to the 'NewFmt' branch now?

**Comment by edeutsch** [comment]
yes, let's do that, thanks. Then I will test later this week.

**Comment by DeqingQu** [comment]
Hi, @edeutsch, the 'issue252-cur' branch has been merged to the 'NewFmt' branch. If you meet any problems in the test, please feel free to let me know.

**Comment by edeutsch** [comment]
Hi everyone, I have remerged master into issue252-cur with no problems.
I have remerged issue252-cur into NewFmt and tested. All seems to work.
I have merged issues252-cur into master and tested. All seems to work.
Therefore, issue 252 development is complete as far as I can tell. Thank you, Deqing.
@everyone: when you next do a git pull either on master or on NewFmt, you will be switched to the new password in config file system. When you next run some code, the code will automatically try to pull the latest password file. If it succeeeds, all will be well. If it fails, then everything may fail. Be prepared for a little troubleshooting after your next git pull on your dev machines.
Let's wait a few days, clean up any broken pieces on the floor, and then close this issues and delete the issue branches.
Thank you!

**Comment by edeutsch** [comment]
oh, any before we close this issue, we should change all he neo4j and mysql passwords and listen for broken glass.

**Comment by DeqingQu** [comment]
Some hints if we want to change the neo4j and mysql passwords.
1. The remote config file is located on the rtx.ncats.io webserver (not docker container). Its path is /mnt/temp/config.json
2. If you want the password changes to take effect immediately, please delete the local config.json file. (It is located in $RTX_PROJECT_FOLDER/code/config.json)
3. If you don't delete the local config.json, the password changes will take effect automatically in the next day.

**Comment by saramsey** [comment]
@DeqingQu has recommended that we keep this issue open until a test of the "change password" procedure has been successfully completed.

**Comment by saramsey** [comment]
@DeqingQu can we schedule the "change password" test before you leave?

**Comment by DeqingQu** [comment]
Of course! How about tomorrow or next week?

**Comment by finnagin** [comment]
@dkoslicki and anyone else who is interested. To add your rsa key to the list of authorized keys do the following:

1. ssh into rtx.ncats.io
2. Navigate to `/home/rtxconfig/.ssh`
3. In this directory there is a file called `authorized_keys`, simply add your rsa key to the bottom of the file with a short descriptor comment above it e.g.
```
# My new computer
<your key>
``

**Comment by dkoslicki** [comment]
@saramsey @finnagin shall we close due to this being implemented and working afaik (and #788)?

**Comment by finnagin** [comment]
@dkoslicki Yeah his is implemented I think we can close this.

**Comment by dkoslicki** [comment]
Ok, closing due to #788
