### ISSUE TITLE
update BioNetExpander to map OMIM diseases directly to phenotypes

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#253]
Use method QueryBioLink.map_disease_to_phenotype.

**Comment by DeqingQu** [comment]
@saramsey 
I found the original codes in BioNetExpander have mapped diseases to phenotypes using `QueryBioLink.get_phenotypes_for_disease_desc`. 
```
phenotype_id_dict = QueryBioLink.get_phenotypes_for_disease_desc(disont_id)
        for phenotype_id_str in phenotype_id_dict.keys():
            phenotype_node = self.add_node_smart("phenotypic_feature", phenotype_id_str,
                                                 desc=phenotype_id_dict[phenotype_id_str])
            if phenotype_node is not None:
                self.orangeboard.add_rel("has_phenotype", 'BioLink', node, phenotype_node, extended_reltype="has_phenotype")
```
I read get_phenotypes_for_disease_desc method and found it used the same API (`disease/{disease_id}/phenotypes`) as `QueryBioLink.map_disease_to_phenotype`.

The number of 'has_phenotype' relationships has increased by about 140,000 after running PatchKG.py. It is very weird. I don't think that BioLink backend added so many relations during the time. I will check our codes more carefully.

**Comment by DeqingQu** [comment]
@saramsey 
A new disease node could be added to the KG by 'expand_microRNA', 'expand_protein' and 'expand_disease' and the new node is not expanded in this process. I noticed that 'bne.expand_all_nodes()' is called three times. I am not sure whether all nodes are expanded after the function is called three times. I am running 'BuildMasterKG.py' and I guess it will cost many hours.

**Comment by DeqingQu** [comment]
@saramsey The codes are done and are pushed to the 'issue249-253' branch. All test cases are passed on the 'rtxsteve' docker container.

**Comment by saramsey** [comment]
![screen shot 2018-07-26 at 1 06 41 pm](https://user-images.githubusercontent.com/5562107/43285744-c7254312-90d4-11e8-9da3-9ecbdaf36816.png)

looks good to me
