### ISSUE TITLE
define metagraph file and have BioNetExpander.py and QuestionAnswering code reference this file

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#260]
@dkoslicki

**Comment by saramsey** [comment]
every relationship in the metagraph should also have a human-readable explanatory sentence for what it "means"

**Comment by dkoslicki** [comment]
Idea is to replace code inside ``QuestionAnswering/`` such as:
```python
(symptoms_dict, symptoms) = RU.top_n_fisher_exact([disease_id], "disease", "phenotypic_feature", rel_type="has_phenotype", n=num_input_disease_symptoms)
```
so I don't need to keep hard-coding things like "disease", "phenotypic_feature", and "has_phenotype", but can populate this with a call to some other class (in a human-friendly way).

**Comment by saramsey** [comment]
@DeqingQu let's discuss this issue next week. Here, a "metagraph file" means a text file (maybe JSON or YAML, I am not sure what would be best) that describes what the node categories are that we use, and which relationship types are allowed between the node categories.

**Comment by saramsey** [comment]
@DeqingQu the purpose of this file is to eliminate the (currently) strong coupling that we have between semantics in the Knowledge Graph and the Question Answering code. In other words, we want to ensure that if in the future (due to the Knowledge Graph standard evolving) we have to change the KG node category name "phenotypic feature" to "phenotype", we will then only have to update the YAML file (i.e., metagraph file), regenerate the KG, and we won't have to update any Python code. That is the idea, anyhow.

**Comment by saramsey** [comment]
what's the status of this issue?

**Comment by saramsey** [comment]
@dkoslicki I'm assuming this is still high priority, is that right?

**Comment by dkoslicki** [comment]
Closing due to #788 and #780
