### ISSUE TITLE
How is [gene] related to [disease]?

### ISSUE THREAD

**Issue by jaredroach** [RTXteam/RTX#261]
Hi all. 
I guess this is failing because we don't have an appropriate question template.
e.g., How is $protein related to $disease?
But it seems like this question is simpler than many of the other questions (which would implicitly need to answer this question as a subroutine), e.g., "What diseases involve similar proteins/genes to $disease"
I had asked this of Biograph some years ago, and I have Biograph's output network for this question. It might be interesting to compare.

**Question**
How is the ADRBK1 gene related to Marfan syndrome?

**Status**
The most similar question I can answer is: What drugs target proteins associated with $disease But I found: "Multiple terms found for disease: ['DOID:14323', 'OMIM:154700']"

{
  "message": "The most similar question I can answer is: What drugs target proteins associated with $disease But I found: \"Multiple terms found for disease: ['DOID:14323', 'OMIM:154700']\"",
  "original_question": "How is the ADRBK1 gene related to Marfan syndrome?",
  "query_type_id": "Q23",
  "restated_question": "What drugs target proteins associated with $disease"
}

**Comment by dkoslicki** [comment]
@jaredroach Do you have a suggested line of reasoning to answer how a protein is related to a disease? I can imagine many such ways to define "is related", so I need some guidance about what a biologist would expect the answer to return.

**Comment by jaredroach** [comment]
David,

	Here is Biograph’s output. I think the basic idea is to find all shortest (or most evidenced/supported) paths and report them back.
	One could prune by quality.

-Jared

**Comment by dkoslicki** [comment]
Self-assigning since I think we could easily spin up a question to do this, and can then return the "neighborhood graph."

**Comment by edeutsch** [comment]
the layout here is really fantastically good. It doesn't look like cytoscape.js provides any similarly great layout engine. I wonder how we could get a similar cool layout.. I perused the original BioGraph paper again, but I don't see any details of how they layout:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3218845/

**Comment by edeutsch** [comment]
I suppose it's probably just a dump from Rgraphviz.

**Comment by jaredroach** [comment]
Would it be reasonable to have a relatively "low level" question template. Along the lines of "What is the shortest path in the KG between node A and node B?" Where ideally any reasonable synonym for node A or node B could be recognized.

Another query that would be useful. "List all the nodes of type $node_type". [see footnote] This is useful when struggling with the UI. It is time consuming and frustrating to come up with a question the UI recognizes. For example, when I enter "How does glucose treat hypoglycemia?" It returns with the suggested question "The most similar question I can answer is: Which biological processes does $protein participate in But I was unable to fill the following parameters: ['protein']"
Which in turn means the user has to fill a value for protein. It would be useful to have a dictionary of all proteins so the user could pick one to go in the slot rather than have to keep guessing to find one that the UI recognizes.

footnote: ideally even allowing more specific questions like "List all the nodes of type $node_type that match regex $regex" or perhaps "List all the nodes of type $node_type that start with the letters 'plasmin'"

**Comment by dkoslicki** [comment]
Relevant to #788, but would still be nice to get this sort of thing in the DSL (so we don’t need to try multiple hops until they get a result)

**Comment by dkoslicki** [comment]
Closing for the more specified version of this issue in #1387
