### ISSUE TITLE
Test complete build of KG

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#263]
Hi Ujjval,

Can you and Deqing please work together to test out a complete KG build on rxtsteve.saramsey.org, incorporating the new code that you pushed in issue #90 ?

I’d like for you to learn the procedure for running, monitoring, and quality-checking the KG build — that is why I’m suggesting that you and Deqing do it together. 

Cheers,
Steve

**Comment by saramsey** [comment]
Looks good, just need descriptions

**Comment by saramsey** [comment]
@DeqingQu can you check your records, to see where the newest KG is hosted?

**Comment by DeqingQu** [comment]
The newest KG is hosted on the production environment (bolt://rtx.ncats.io:7687). It is built on the ISSUE259 container of 'rtx.ncats.io'. All test cases for the newest KG are passed.

**Comment by dkoslicki** [comment]
So this corresponds to "KG2":
```python
self.live = "Production"
		#self.live = "KG2"
		#self.live = "rtxdev"
		#self.live = "staging"

		if self.live == "Production":
			self.bolt = "bolt://rtx.ncats.io:7687"
			self.database = "rtx.ncats.io:7474/db/data"

		if self.live == "KG2":
			self.bolt = "bolt://rtx.ncats.io:7787"
			self.database = "rtx.ncats.io:7574/db/data"
```

**Comment by saramsey** [comment]
HTTP port for this Neo4j is 7474.

**Comment by saramsey** [comment]
@dkoslicki instructions: replace KG2 with this new KG, and *LEAVE KG1 ALONE*

**Comment by saramsey** [comment]
Steve and Deqing to work on this

**Comment by dkoslicki** [comment]
I.e. according to [RTXConfiguration.py](https://github.com/RTXteam/RTX/blob/master/code/RTXConfiguration.py):
```python
		self.live = "Production"
		#self.live = "KG2"
		#self.live = "rtxdev"
		#self.live = "staging"

		if self.live == "Production":
			self.bolt = "bolt://rtx.ncats.io:7687"
			self.database = "rtx.ncats.io:7474/db/data"

		if self.live == "KG2":
			self.bolt = "bolt://rtx.ncats.io:7787"
			self.database = "rtx.ncats.io:7574/db/data"
```
Put this newly constructed KG in "KG2" leaving "Production" alone.

**Comment by saramsey** [comment]
> root@ip-172-31-13-205:/home/sramsey# docker container ls -a
> CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                                                            NAMES
> 384a477cea2c        rtx2:version2       "bash"              8 weeks ago         Up 8 weeks          80/tcp, 7473-7474/tcp, 7687/tcp                                                  ISSUE259
> a173bfcd58a9        rtx2:version2       "bash"              6 months ago        Up 4 months         7473/tcp, 0.0.0.0:8080->80/tcp, 0.0.0.0:7574->7474/tcp, 0.0.0.0:7787->7687/tcp   rtx2
> 0c3e50fe562a        rtx1:version1       "bash"              6 months ago        Up 4 months         0.0.0.0:7474->7474/tcp, 7473/tcp, 0.0.0.0:7687->7687/tcp, 0.0.0.0:8081->80/tcp   rtx1

**Comment by DeqingQu** [comment]
The newest KG has been deployed on the 'rtx2' container (on 'rtx.ncats.io'). There are 130,043 nodes and 3,468,844 relationships in the newest KG. The testcases for the newest relationships have been added to the KGTests.py.

If you want to access the newest KG by Neo4j browser, please input the URL http://rtx.ncats.io:7574/browser/. If it is connected to the neo4j database automatically, it will connect to the production KG by mistake. (I don’t know why. I guess the bolt address ‘bolt://rtx.ncats.io:7687’ is used by default)

We can disconnect the database first, then input the correct bolt address.
1. in the ‘Neo4j Browser Sync’ tab, click the ‘clear local data’ to disconnect the production DB.
<img width="370" alt="screen shot 2018-12-18 at 6 36 30 pm" src="https://user-images.githubusercontent.com/2810578/50195682-0378c400-02f5-11e9-94b4-b7baf38c2e32.png">
2. in the ‘connect to neo4j’ panel, input the bolt address (bolt://rtx.ncats.io:7787), username and password.
<img width="1016" alt="screen shot 2018-12-18 at 6 37 52 pm" src="https://user-images.githubusercontent.com/2810578/50195692-096ea500-02f5-11e9-8cd4-2afe35503e5c.png">

**Comment by DeqingQu** [comment]
The backup file of the previous KG2 is located at /mnt/data/backup/12172018-rtx2.dump on the 'rtx.ncats.io' instance.

**Comment by saramsey** [comment]
@dkoslicki Can you take a look at the new KG (this is a ground-up rebuild of the RTX KG using the existing code in reasoningtool/kg-construction) and comment in this issue if you see any issues or weirdness with the rebuilt KG? @DeqingQu has included instructions for how to connect to it, above. Thanks, Steve

**Comment by dkoslicki** [comment]
@saramsey @DeqingQu 
I'm showing
http://rtx.ncats.io:7574/browser/
and
http://rtx.ncats.io:7474/browser/
return the same number of nodes. Which browser contains the new KG?

**Comment by DeqingQu** [comment]
Hi @dkoslicki,
By default, either http://rtx.ncats.io:7574/browser/ or http://rtx.ncats.io:7474/browser/ will connect to the database with the default bolt address (bolt://rtx.ncats.io:7687). So we need to disconnect the default database first, then connect to our newest datatabse (bolt://rtx.ncats.io:7787)

If you don't familiar with how to disconnect the database, please read my previous post. There are some intructions and images which could help you.

You can use either http://rtx.ncats.io:7574/browser/ or http://rtx.ncats.io:7474/browser/ to connect our latest database, but please remember to disconnect the default datbase first.

**Comment by dkoslicki** [comment]
Thanks Deqing, I forgot to flush the local cache, so that was causing the issue. Is a node count of 130,043 more accurate for this newest KG?

**Comment by DeqingQu** [comment]
Yes, it is the newest KG.

**Comment by dkoslicki** [comment]
Curious observation: this new KG has fewer edges, even though it's ingested SIDER:
new KG (7787): 3,468,844
old KG (7687): 3,804,435
Any idea where the missing ~340K edges went?

**Comment by saramsey** [comment]
@DeqingQu reports this issue may have been fixed; will confirm

**Comment by saramsey** [comment]
Hi Steve,

I dumped the latest KG on rtx1 docker and pushed it to our new “KG dump” web server. The name of the file is 052519-195046.tar.gz.
I also dumped the latest KG on rtx2 docker and pushed it to “KG dump”. The file is 052519-201727.tar.gz.


Best Regards,
Deqing Qu
