### ISSUE TITLE
Update protein names

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#264]
The script UpdateNodesName.py is working great. However, I wonder if we can just update the method BioNetExpander.add_node_smart() to use QueryMyGene to query the protein name (e.g., "Interleukin 18") and to set as the Node object "description" field it at the time that the Node object is created in Orangeboard. Then (I think) we will no longer need to have a separate UpdateNodesName.py script, right?

@DeqingQu can you please look into this to see if it is feasible?

**Comment by saramsey** [comment]
If this is an easy change then please go ahead and include the code change before implementing #263

**Comment by saramsey** [comment]
can we close this issue?

**Comment by DeqingQu** [comment]
Yes, it can be closed.
