### ISSUE TITLE
cypher log feature for RTX?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#266]
Purple Team (Mark Williams) has requested that we add a feature where we (Team X-ray) can capture (i.e., to a log file) the cypher queries that are run in response to a particular user query in the RTX system. This came up in the context of they want to know *how* we got our answers for the 25 diabetes drugs.  Should we discuss this at the next X-ray meeting?  Or just in this github issue?

**Comment by edeutsch** [comment]
Might be good to discuss, because, sure, we can log them to a file, but if someone besides us wants to actually examine the file, then some extra work might need to be done. Although I suppose the log file can go into a web-accessible place and someone can just download it. Another option is to be more verbose with the returned "messsage" to describe what was being done, including cypher queries.

I suppose I'm implying that a discussion might reveal a more satisfying way to get the user what he really wants.

Do we have an test case in mine? i.e. is there an example context in which Mark wants this?

**Comment by dkoslicki** [comment]
This is interesting, because as I view it, cypher queries are the backbone, but I use a whole bunch of other things to “flesh out” the answer. I don’t have an objection of sending them a dump of cypher queries, but I don’t think it will too insightful (but may spark a conversation).

**Comment by edeutsch** [comment]
I wonder if it would be fun, interesting, tedious, hateful to develop a logging mechanism for what you do and append that to the message log? Perhaps every method/function you call can append something like:
- Select a set of paths with "MATCH n...."
and then:
- Re-sort the list using weights from a Jaccard-Hochberg hyperdistribution
and:
- Trim list based on the current wind direction

Each function could have a bullet statement about what its doing. They all get appended to the message to let the user see a peek into what's going on.

Might be interesting to some. but maybe tedious to implement..

**Comment by dkoslicki** [comment]
:) would be somewhat tedious to implement for EVERY question type, but not so bad for the SME workflow. Equivalently, just take a look at the comments in the solution scripts, as they recapitulation basically the same information. It would be straightforward for me to expose these if some sort of logging mechanism existed.

**Comment by dkoslicki** [comment]
Moving to low-priority while we figure out how priority this is from NCATS perspective (as it's non-trivial). @finnagin looking into if there is a back-end logging feature of neo4j.

**Comment by finnagin** [comment]
Looks like this might be as simple as turning it on in the [configuration file.](https://neo4j.com/docs/operations-manual/current/monitoring/logging/query-logging/)

I can go ahead and set this up. Which neo4j instances do we want this turned on for?

Also, it looks like we set a limit for the amount of space to use before auto-rotation (I took this to mean it will rotate out oldest logs by deleting them when space limit is reached and new logs are added) and we also have to specify a maximum number of query logs to keep. Any idea on good values for these options?

**Comment by dkoslicki** [comment]
@finnagin Let's turn it on for rtx.ncats.io:7474 initially. Let's go ahead and keep at least 1,000 (they can't be too big since they're just text, right?)

**Comment by finnagin** [comment]
I was talking to David about this on slack but I'll post this here as well.

So unfortunately [query logging only works on the enterprise edition.](https://stackoverflow.com/questions/47099080/how-do-you-configure-query-logging-for-neo4j-community-edition-3-10-on-os-x?rq=1)

I have already talked to a representative of neo4j about educational licences for the enterprise edition when I was looking into Bloom and she said that they were currently in the process of reworking their educational licensing model and thus are not currently giving them out until they are done.

**Comment by dkoslicki** [comment]
Note to self: Will Byrd would like a selection of cypher queries we're using to see the kinds of queries that are relevant to our KG

**Comment by dkoslicki** [comment]
Note that there were 18,073 unique cypher calls in answering these 53 questions.

**Comment by saramsey** [comment]
What's the status of this issue?  Can we close it?

**Comment by dkoslicki** [comment]
I think we can close it as it served its main purpose: passing off cypher commands to team alpha/Will Byrd. I see no reason to turn logging on permanently. I have the log files in case NCATS wants to take a look at them.
