### ISSUE TITLE
Update predicates in code to match new KG predicates

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#267]
Basic idea: use
```
match ()-[r]-() return distinct type(r) as a order by a
```
To get the predicates. Use
```
match (n)-[r]-(m) return distinct labels(n)[1] as a, type(r) as b, labels(m)[1] as c order by a
```
To identify source/target nodes. Put replacements in ``replacements.txt``, then run ``do_replacements.sh``.

**Comment by dkoslicki** [comment]
Note: identified that some of the example questions reference protein symbols, so needed to update ``dumpdata.py`` to also dump protein symbols. This will require every ``KGNodeIndex`` sqlite database to be updated.

**Comment by dkoslicki** [comment]
@saramsey @edeutsch @isbluis Just FYI, with the predicate change and an updated ``NodeNamesDescriptions.tsv``, your ``KGNodeIndex`` SQL databases will need to be updated for the code to work.

**Comment by dkoslicki** [comment]
All example questions passing with no error. Closing

**Comment by edeutsch** [comment]
Code and KGNodeIndex and KG must all be in sync. It looks like the code in trunk has moved to the new KG, but what is the prognosis for getting the new KG into production, so that we can deploy the new code? What's the plan @saramsey ?

**Comment by dkoslicki** [comment]
@saramsey Go ahead and push from steveneo4j.saramsey.org to:
self.bolt = "bolt://rtx.ncats.io:7687"
self.database = "rtx.ncats.io:7474/db/data"

I can then make sure the ``NodesNamesDescriptions.tsv`` is updated (once I do, @edeutsch you'll have to update your KGNodeIndex as well).

**Comment by edeutsch** [comment]
All updated and looks good.
