### ISSUE TITLE
eutils messages to stderr

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#270]
While running 
   Q1: Which genetic conditions might offer protection against malaria?
During query, STDERR is spewing lots of stuff like:
HTTP response status code: 414 for URL:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=%28Guillain-Barre%20Syndrome%5BMeSH%20Terms%5D%7CGuillain%20Barre%20Syndrome%5BMeSH%20Terms%5D%7CSyndrome%2C%20Guillain-Barre%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Polyneuropathy%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Polyneuropathies%5BMeSH%20Terms%5D%7CInflammatory%20Polyneuropathies%2C%20Acute%5BMeSH%20Terms%5D%7CInflammatory%20Polyneuropathy%2C%20Acute%5BMeSH%20Terms%5D%7CPolyneuropathies%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CGuillain-Barre%20Syndrome%2C%20Familial%5BMeSH%20Terms%5D%7CGuillain-Barr%C3%A9%20Syndrome%5BMeSH%20Terms%5D%7CGuillaine-Barre%20Syndrome%5BMeSH%20Terms%5D%7CGuillaine%20Barre%20Syndrome%5BMeSH%20Terms%5D%7CSyndrome%2C%20Guillaine-Barre%5BMeSH%20Terms%5D%7CInflammatory%20Demyelinating%20Polyradiculoneuropathy%2C%20Acute%5BMeSH%20Terms%5D%7CInflammatory%20Polyneuropathy%20Acute%5BMeSH%20Terms%5D%7CAcute%2C%20Inflammatory%20Polyneuropathy%5BMeSH%20Terms%5D%7CInflammatory%20Polyneuropathy%20Acutes%5BMeSH%20Terms%5D%7CPolyneuropathy%20Acute%2C%20Inflammatory%5BMeSH%20Terms%5D%7CLandry-Guillain-Barre%20Syndrome%5BMeSH%20Terms%5D%7CLandry%20Guillain%20Barre%20Syndrome%5BMeSH%20Terms%5D%7CSyndrome%2C%20Landry-Guillain-Barre%5BMeSH%20Terms%5D%7CPolyneuropathy%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CPolyneuropathy%2C%20Inflammatory%20Demyelinating%2C%20Acute%5BMeSH%20Terms%5D%7CPolyradiculoneuropathy%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CPolyradiculoneuropathy%2C%20Acute%20Inflammatory%20Demyelinating%5BMeSH%20Terms%5D%7CAcute%20Autoimmune%20Neuropathy%5BMeSH%20Terms%5D%7CAcute%20Autoimmune%20Neuropathies%5BMeSH%20Terms%5D%7CAutoimmune%20Neuropathies%2C%20Acute%5BMeSH%20Terms%5D%7CAutoimmune%20Neuropathy%2C%20Acute%5BMeSH%20Terms%5D%7CNeuropathies%2C%20Acute%20Autoimmune%5BMeSH%20Terms%5D%7CNeuropathy%2C%20Acute%20Autoimmune%5BMeSH%20Terms%5D%7CAcute%20Infectious%20Polyneuritis%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Demyelinating%20Polyneuropathy%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Demyelinating%20Polyradiculoneuropathy%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Polyradiculoneuropathy%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Polyradiculoneuropathies%5BMeSH%20Terms%5D%7CInflammatory%20Polyradiculoneuropathies%2C%20Acute%5BMeSH%20Terms%5D%7CPolyradiculoneuropathies%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CDemyelinating%20Polyradiculoneuropathy%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CGuillain-Barre%20Syndrome%5BMeSH%20Terms%5D%7CGuillain%20Barre%20Syndrome%5BMeSH%20Terms%5D%7CSyndrome%2C%20Guillain-Barre%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Polyneuropathy%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Polyneuropathies%5BMeSH%20Terms%5D%7CInflammatory%20Polyneuropathies%2C%20Acute%5BMeSH%20Terms%5D%7CInflammatory%20Polyneuropathy%2C%20Acute%5BMeSH%20Terms%5D%7CPolyneuropathies%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CGuillain-Barre%20Syndrome%2C%20Familial%5BMeSH%20Terms%5D%7CGuillain-Barr%C3%A9%20Syndrome%5BMeSH%20Terms%5D%7CGuillaine-Barre%20Syndrome%5BMeSH%20Terms%5D%7CGuillaine%20Barre%20Syndrome%5BMeSH%20Terms%5D%7CSyndrome%2C%20Guillaine-Barre%5BMeSH%20Terms%5D%7CInflammatory%20Demyelinating%20Polyradiculoneuropathy%2C%20Acute%5BMeSH%20Terms%5D%7CInflammatory%20Polyneuropathy%20Acute%5BMeSH%20Terms%5D%7CAcute%2C%20Inflammatory%20Polyneuropathy%5BMeSH%20Terms%5D%7CInflammatory%20Polyneuropathy%20Acutes%5BMeSH%20Terms%5D%7CPolyneuropathy%20Acute%2C%20Inflammatory%5BMeSH%20Terms%5D%7CLandry-Guillain-Barre%20Syndrome%5BMeSH%20Terms%5D%7CLandry%20Guillain%20Barre%20Syndrome%5BMeSH%20Terms%5D%7CSyndrome%2C%20Landry-Guillain-Barre%5BMeSH%20Terms%5D%7CPolyneuropathy%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CPolyneuropathy%2C%20Inflammatory%20Demyelinating%2C%20Acute%5BMeSH%20Terms%5D%7CPolyradiculoneuropathy%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CPolyradiculoneuropathy%2C%20Acute%20Inflammatory%20Demyelinating%5BMeSH%20Terms%5D%7CAcute%20Autoimmune%20Neuropathy%5BMeSH%20Terms%5D%7CAcute%20Autoimmune%20Neuropathies%5BMeSH%20Terms%5D%7CAutoimmune%20Neuropathies%2C%20Acute%5BMeSH%20Terms%5D%7CAutoimmune%20Neuropathy%2C%20Acute%5BMeSH%20Terms%5D%7CNeuropathies%2C%20Acute%20Autoimmune%5BMeSH%20Terms%5D%7CNeuropathy%2C%20Acute%20Autoimmune%5BMeSH%20Terms%5D%7CAcute%20Infectious%20Polyneuritis%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Demyelinating%20Polyneuropathy%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Demyelinating%20Polyradiculoneuropathy%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Polyradiculoneuropathy%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Polyradiculoneuropathies%5BMeSH%20Terms%5D%7CInflammatory%20Polyradiculoneuropathies%2C%20Acute%5BMeSH%20Terms%5D%7CPolyradiculoneuropathies%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CDemyelinating%20Polyradiculoneuropathy%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CPolyradiculoneuropathy%2C%20Chronic%20Inflammatory%20Demyelinating%5BMeSH%20Terms%5D%7CCIDP%5BMeSH%20Terms%5D%7CPolyneuropathy%2C%20Inflammatory%20Demyelinating%2C%20Chronic%5BMeSH%20Terms%5D%7CInflammatory%20Polyradiculopathy%2C%20Chronic%5BMeSH%20Terms%5D%7CChronic%20Inflammatory%20Polyradiculopathies%5BMeSH%20Terms%5D%7CChronic%20Inflammatory%20Polyradiculopathy%5BMeSH%20Terms%5D%7CInflammatory%20Polyradiculopathies%2C%20Chronic%5BMeSH%20Terms%5D%7CPolyradiculopathies%2C%20Chronic%20Inflammatory%5BMeSH%20Terms%5D%7CPolyradiculopathy%2C%20Chronic%20Inflammatory%5BMeSH%20Terms%5D%7CPolyradiculoneuropathy%2C%20Chronic%20Inflammatory%5BMeSH%20Terms%5D%7CChronic%20Inflammatory%20Polyradiculoneuropathy%5BMeSH%20Terms%5D%7CChronic%20Inflammatory%20Polyradiculoneuropathies%5BMeSH%20Terms%5D%7CPolyradiculoneuropathies%2C%20Chronic%20Inflammatory%5BMeSH%20Terms%5D%7CChronic%20Inflammatory%20Demyelinating%20Polyradiculoneuropathy%5BMeSH%20Terms%5D%29%20AND%20%28malaria%5BMeSH%20Terms%5D%29&retmode=json&retmax=1000

HTTP response status code: 414 for URL:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=Guillain-Barre%20Syndrome%5BMeSH%20Terms%5D%7CGuillain%20Barre%20Syndrome%5BMeSH%20Terms%5D%7CSyndrome%2C%20Guillain-Barre%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Polyneuropathy%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Polyneuropathies%5BMeSH%20Terms%5D%7CInflammatory%20Polyneuropathies%2C%20Acute%5BMeSH%20Terms%5D%7CInflammatory%20Polyneuropathy%2C%20Acute%5BMeSH%20Terms%5D%7CPolyneuropathies%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CGuillain-Barre%20Syndrome%2C%20Familial%5BMeSH%20Terms%5D%7CGuillain-Barr%C3%A9%20Syndrome%5BMeSH%20Terms%5D%7CGuillaine-Barre%20Syndrome%5BMeSH%20Terms%5D%7CGuillaine%20Barre%20Syndrome%5BMeSH%20Terms%5D%7CSyndrome%2C%20Guillaine-Barre%5BMeSH%20Terms%5D%7CInflammatory%20Demyelinating%20Polyradiculoneuropathy%2C%20Acute%5BMeSH%20Terms%5D%7CInflammatory%20Polyneuropathy%20Acute%5BMeSH%20Terms%5D%7CAcute%2C%20Inflammatory%20Polyneuropathy%5BMeSH%20Terms%5D%7CInflammatory%20Polyneuropathy%20Acutes%5BMeSH%20Terms%5D%7CPolyneuropathy%20Acute%2C%20Inflammatory%5BMeSH%20Terms%5D%7CLandry-Guillain-Barre%20Syndrome%5BMeSH%20Terms%5D%7CLandry%20Guillain%20Barre%20Syndrome%5BMeSH%20Terms%5D%7CSyndrome%2C%20Landry-Guillain-Barre%5BMeSH%20Terms%5D%7CPolyneuropathy%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CPolyneuropathy%2C%20Inflammatory%20Demyelinating%2C%20Acute%5BMeSH%20Terms%5D%7CPolyradiculoneuropathy%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CPolyradiculoneuropathy%2C%20Acute%20Inflammatory%20Demyelinating%5BMeSH%20Terms%5D%7CAcute%20Autoimmune%20Neuropathy%5BMeSH%20Terms%5D%7CAcute%20Autoimmune%20Neuropathies%5BMeSH%20Terms%5D%7CAutoimmune%20Neuropathies%2C%20Acute%5BMeSH%20Terms%5D%7CAutoimmune%20Neuropathy%2C%20Acute%5BMeSH%20Terms%5D%7CNeuropathies%2C%20Acute%20Autoimmune%5BMeSH%20Terms%5D%7CNeuropathy%2C%20Acute%20Autoimmune%5BMeSH%20Terms%5D%7CAcute%20Infectious%20Polyneuritis%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Demyelinating%20Polyneuropathy%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Demyelinating%20Polyradiculoneuropathy%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Polyradiculoneuropathy%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Polyradiculoneuropathies%5BMeSH%20Terms%5D%7CInflammatory%20Polyradiculoneuropathies%2C%20Acute%5BMeSH%20Terms%5D%7CPolyradiculoneuropathies%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CDemyelinating%20Polyradiculoneuropathy%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CGuillain-Barre%20Syndrome%5BMeSH%20Terms%5D%7CGuillain%20Barre%20Syndrome%5BMeSH%20Terms%5D%7CSyndrome%2C%20Guillain-Barre%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Polyneuropathy%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Polyneuropathies%5BMeSH%20Terms%5D%7CInflammatory%20Polyneuropathies%2C%20Acute%5BMeSH%20Terms%5D%7CInflammatory%20Polyneuropathy%2C%20Acute%5BMeSH%20Terms%5D%7CPolyneuropathies%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CGuillain-Barre%20Syndrome%2C%20Familial%5BMeSH%20Terms%5D%7CGuillain-Barr%C3%A9%20Syndrome%5BMeSH%20Terms%5D%7CGuillaine-Barre%20Syndrome%5BMeSH%20Terms%5D%7CGuillaine%20Barre%20Syndrome%5BMeSH%20Terms%5D%7CSyndrome%2C%20Guillaine-Barre%5BMeSH%20Terms%5D%7CInflammatory%20Demyelinating%20Polyradiculoneuropathy%2C%20Acute%5BMeSH%20Terms%5D%7CInflammatory%20Polyneuropathy%20Acute%5BMeSH%20Terms%5D%7CAcute%2C%20Inflammatory%20Polyneuropathy%5BMeSH%20Terms%5D%7CInflammatory%20Polyneuropathy%20Acutes%5BMeSH%20Terms%5D%7CPolyneuropathy%20Acute%2C%20Inflammatory%5BMeSH%20Terms%5D%7CLandry-Guillain-Barre%20Syndrome%5BMeSH%20Terms%5D%7CLandry%20Guillain%20Barre%20Syndrome%5BMeSH%20Terms%5D%7CSyndrome%2C%20Landry-Guillain-Barre%5BMeSH%20Terms%5D%7CPolyneuropathy%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CPolyneuropathy%2C%20Inflammatory%20Demyelinating%2C%20Acute%5BMeSH%20Terms%5D%7CPolyradiculoneuropathy%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CPolyradiculoneuropathy%2C%20Acute%20Inflammatory%20Demyelinating%5BMeSH%20Terms%5D%7CAcute%20Autoimmune%20Neuropathy%5BMeSH%20Terms%5D%7CAcute%20Autoimmune%20Neuropathies%5BMeSH%20Terms%5D%7CAutoimmune%20Neuropathies%2C%20Acute%5BMeSH%20Terms%5D%7CAutoimmune%20Neuropathy%2C%20Acute%5BMeSH%20Terms%5D%7CNeuropathies%2C%20Acute%20Autoimmune%5BMeSH%20Terms%5D%7CNeuropathy%2C%20Acute%20Autoimmune%5BMeSH%20Terms%5D%7CAcute%20Infectious%20Polyneuritis%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Demyelinating%20Polyneuropathy%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Demyelinating%20Polyradiculoneuropathy%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Polyradiculoneuropathy%5BMeSH%20Terms%5D%7CAcute%20Inflammatory%20Polyradiculoneuropathies%5BMeSH%20Terms%5D%7CInflammatory%20Polyradiculoneuropathies%2C%20Acute%5BMeSH%20Terms%5D%7CPolyradiculoneuropathies%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CDemyelinating%20Polyradiculoneuropathy%2C%20Acute%20Inflammatory%5BMeSH%20Terms%5D%7CPolyradiculoneuropathy%2C%20Chronic%20Inflammatory%20Demyelinating%5BMeSH%20Terms%5D%7CCIDP%5BMeSH%20Terms%5D%7CPolyneuropathy%2C%20Inflammatory%20Demyelinating%2C%20Chronic%5BMeSH%20Terms%5D%7CInflammatory%20Polyradiculopathy%2C%20Chronic%5BMeSH%20Terms%5D%7CChronic%20Inflammatory%20Polyradiculopathies%5BMeSH%20Terms%5D%7CChronic%20Inflammatory%20Polyradiculopathy%5BMeSH%20Terms%5D%7CInflammatory%20Polyradiculopathies%2C%20Chronic%5BMeSH%20Terms%5D%7CPolyradiculopathies%2C%20Chronic%20Inflammatory%5BMeSH%20Terms%5D%7CPolyradiculopathy%2C%20Chronic%20Inflammatory%5BMeSH%20Terms%5D%7CPolyradiculoneuropathy%2C%20Chronic%20Inflammatory%5BMeSH%20Terms%5D%7CChronic%20Inflammatory%20Polyradiculoneuropathy%5BMeSH%20Terms%5D%7CChronic%20Inflammatory%20Polyradiculoneuropathies%5BMeSH%20Terms%5D%7CPolyradiculoneuropathies%2C%20Chronic%20Inflammatory%5BMeSH%20Terms%5D%7CChronic%20Inflammatory%20Demyelinating%20Polyradiculoneuropathy%5BMeSH%20Terms%5D&retmode=json&retmax=1000

and seems quite slow. Maybe these many calls are being cached and will be faster next time?
 
Can we quiet down these noisy dumps to STDERR?

**Comment by dkoslicki** [comment]
@finnagin This is probably a result of your normalized google distance code. Can you investigate?

**Comment by finnagin** [comment]
Those messages are coming from the method `send_query_get` in QueryNCBIeUtils.py
 which prints to stderr every time a url either times out or a response code other than 200 is returned. I believe Steve wrote this method so I'll double check with him before I change anything. 

@saramsey would it be OK if I change `send_query_get` in QueryNCBIeUtils.py so that it no longer prints to stderr? If so, should this be changed to print to some kind of log file or just removed entirely? 

If you want me to leave it in I could also add a optional argument to suppress it so that when it gets called in the normalized google distance method it won't print out to stderr fixing this issue.

**Comment by dkoslicki** [comment]
@edeutsch Is it a problem to have a bunch of stuff printed to stderr? Looks like @finnagin has a fix in mind, but from my perspective, it's nice to be able to see when I'm getting errors (leading to things like issue #317).

**Comment by edeutsch** [comment]
It is not a problem. Everything on stderr is logged to disk, so GB of content could be an issue. Might also slightly impede my efforts at debugging if there is tons of stuff spewed to stderr, but those quibbles aside, it's fine.

**Comment by dkoslicki** [comment]
Ok, until an issue from this arrises, let's close this for now (keeping @finnagin's fix in mind).
