### ISSUE TITLE
Time to prune branches?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#272]
We seem to have gathered quite a lots of branches. Time to prune (delete) some branches?

git branch -a
  NewFmt
* master
  metabolites
  remotes/origin/HEAD -> origin/master
  remotes/origin/NewFmt
  remotes/origin/NewStdAPI
  remotes/origin/Q4
  remotes/origin/ReplacePredicates08082018
  remotes/origin/issue249-253
  remotes/origin/issue264
  remotes/origin/master
  remotes/origin/metabolites
  remotes/origin/new-ngd
  remotes/origin/newkg
  remotes/origin/newkg2
  remotes/origin/rtx_name

**Comment by dkoslicki** [comment]
I see no issue with deleting branches that have already been merged. However, I would keep the last one or two around (in case we later discover bugs that need to be rolled back, and I think that's easier to do if the branch still exists).

**Comment by saramsey** [comment]
These branches appear to have been merged, and thus, may be safe to remove:
![screen shot 2018-09-17 at 1 28 35 pm](https://user-images.githubusercontent.com/5562107/45648518-a8c59700-ba7d-11e8-9822-5086df353a13.png)

**Comment by saramsey** [comment]
This branch does not appear to have been merged, and I believe is actively being worked in, for #260:
![screen shot 2018-09-17 at 1 29 22 pm](https://user-images.githubusercontent.com/5562107/45648569-c72b9280-ba7d-11e8-8dc2-6648be514c12.png)

**Comment by dkoslicki** [comment]
Still relevant (so won’t close a per #788) as we have a lot of branches hanging around...

**Comment by finnagin** [comment]
closing in favor of #1777
