### ISSUE TITLE
documenting process for creating, testing, and deploying the KG

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#273]
We need a markdown file that documents step-by-step how to build, test, and deploy the Neo4j KG for RTX. All steps should be included. Imagine someone new coming onto the project, who doesn't know anything about how our systems are set up. How would you document the process explaining to her/him how to build and test a new KG? The locations where we save backup copies of the KG and the SQLite cache (and the procedures for running the scripts used to make the backups) should also be documented.

**Comment by saramsey** [comment]
If this file already exists in our system, please update it with the latest information, and post the link as a comment on this issue.

**Comment by saramsey** [comment]
If  (as I think) a documentation file regarding KG construction doesn't already exist in our repo, please post a link to the new file that you have created (once it is done), here in the issue.

**Comment by dkoslicki** [comment]
+1 to this. For posterity's sake, I think this is quite important to do (and have similarly been emphasizing for @finnagin's work with the machine learning).

**Comment by flashkicker** [comment]
The document has been pushed to master here - https://github.com/RTXteam/RTX/blob/master/team-private/neo4j-kg.md

The part about testing newly generated KGs is incomplete as the test cases for checking relationships has not yet been added to the KGTests.py
