### ISSUE TITLE
Example SME workflow #1 code for notebook

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#276]
Here's what I suggest we could stand up in an iPython notebook as a first easy toss

https://github.com/RTXteam/RTX/blob/master/code/UI/ClientExamples/Python/Query_SMEworkflow1.py

@saramsey , can you notebookerize this?

One mysterious leap of magic is where DOID:9352 comes from. Maybe we should show a separate step where that comes from?

Or we could start at the translate() step, too, to be a little more complete? which would come up with the DOID:9352

**Comment by dkoslicki** [comment]
Yup, this is basically what I had in mind!
