### ISSUE TITLE
Adding knowledge sources for increase/decrease expression of, sequester, consume, etc.

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#277]
In a call with Will Byrd today, it became apparent that the bread-and-butter question type for precision medicine is as follows:
How can I increase the expression of $gene?
What drugs/compounds decrease/inhibit/down-regulate) $gene?
What drugs/compounds increase/up-regulate) $gene?
What proteins consume/sequester $chemical_substance?
What drugs increase (activate / promote ) $protein?

Some of this information may be available using current knowledge sources. @saramsey Do you know if this is the case? Will mentioned that if we have this in our KG, it would be immediately useful for clinical practitioners.

**Comment by saramsey** [comment]
Checked PharmGKB: doesn't appear to have this information, at least not in a readily-apparent form.

**Comment by saramsey** [comment]
DGIdb has some of this information. It seems like it would be a good starting point.

**Comment by saramsey** [comment]
http://www.dgidb.org/downloads

**Comment by saramsey** [comment]
I am working on this, using DGIdb as a starting point....

**Comment by saramsey** [comment]
I have backported the content of the DGI datbase (dgidb.org) (about 25k tuples) into the KG on steveneo4j.saramsey.org, including publications and including upregulation/downregulation type predicates. 

See: http://steveneo4j.saramsey.org:7474/browser/

**Comment by dkoslicki** [comment]
@saramsey close due to #788? Or keep open?
