### ISSUE TITLE
mistaken provided_by?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#278]
One of the notes of feedback that was given today's call is that users of our tools really want to know where our information came from. The easiest is to provide the sources of our assertions (edges).

Taking as an example our example for Q3 at the interface "What proteins are the target of acetaminophen"

I notice two things:
1) for the first response, the edge is this:
        "edge_list": [
          {
            "is_defined_by": "RTX",
            "provided_by": "http://identifiers.org/uniprot/O00519",
            "source_id": "UniProtKB:O00519",
            "target_id": "CHEMBL.COMPOUND:CHEMBL112",
            "type": "physically_interacts_with"
          }
        ],

Here, provided_by is "http://identifiers.org/uniprot/O00519"
But we concluded at today's meeting that this assertion actually comes from ChEMBL. so it would seem that provided_by is not being filled in correctly. @dkoslicki would you look into this?

2) This information is not being displayed. @isbluis would you add this to the GUI to display the provided_by information when a user clicks on an edge?

**Comment by dkoslicki** [comment]
Yes, this is a bug. I was using the wrong entity to populate the ``provided_by`` field in [this line of code](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/FormatOutput.py#L158). I'll push a fix once I'm back with my Unix box (Mac decided to stop playing nice with my IDE).

**Comment by edeutsch** [comment]
great, thanks!

Taking a peek at the code there, I think these lines can be deleted:
edge.origin_list = []
edge.origin_list.append(edge_source_db[(u, v)]) # TODO: check with eric if this really should be a list and if it should contain the source DB('s)

origin_list[ ] was a noble idea that was voted down by the rabble and replaced with provided_by.

The rabble also seemed to agree that the properties is_defined_by and provided_by were inconsistent and semantically switched but there was not enough motivation to change it.
