### ISSUE TITLE
assertion best before date?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#279]
One feedback item from today's KG standardization call (although not in the context of KG standardization) is that users want to know from where assertions (edges) came from and how fresh is the information. 

Are we able to add a freshness date to the KG, perhaps an attribute to each edge in KG to state the datetime associated with the assertion? Ideally this would be the datetime when the original WS query was cached. A less accurate substitute would be the datetime stamp of the building of the KG.

What do you think?

**Comment by saramsey** [comment]
OK, so we are currently using the `requests-cache` python package for our HTTP cache, and it is pretty minimal:

https://github.com/reclosedev/requests-cache

According to the documentation, requests-cache doesn't look at cache-control directives in the HTTP headers at all. So I *think* our cache is "permanent" which is not good (I mean, it was fine for the demo back in November, but we need to move beyond that).

I will start looking at httpcache and CacheControl as alternatives.

**Comment by saramsey** [comment]
OK, I have done some testing. I think we should be able to get timestamps of when the data were *originally* provided by the server, from our python-requests sqlite cache, but it will not be easy to map them to relationships. To do so systematically will require extensive code rework. Realistically, this is a "do it in 2019" kind of issue.

**Comment by dkoslicki** [comment]
@saramsey @edeutsch close due to #788?

**Comment by edeutsch** [comment]
I don't think this was ever solved in a good way, but I am uncertain.

**Comment by saramsey** [comment]
see issue #556
