### ISSUE TITLE
eliminate calls to requests_cache.install_cache in non-main-script Python modules

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#282]
In various modules in kg-construction that are _not_ main scripts (i.e., not called at the command-line except in testing), we are calling requests_cache.install_cache. This breaks modularity because the cache is not scoped locally to the module. Worst case, if  `BioNetExpander.py` were to import `QueryNCBIeUtils.py` (for example), we would be saving *all* our KG-building queries into a SQLite cache `QueryNCBIeUtilsCache.sqlite`, rather than orangeboard.sqlite. This is *not* what we want.

**Comment by finnagin** [comment]
Main:
* [AddProtToGo.py](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/kg-construction/AddProtToGO.py)
* [BuildMasterKG.py](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/kg-construction/BuildMasterKG.py)
* [BuildMeshCache.py](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/kg-construction/BuildMeshCache.py)

**Comment by saramsey** [comment]
can this issue be closed?

**Comment by dkoslicki** [comment]
Closing due to #788
