### ISSUE TITLE
Write question "solution scripts" for COHD endpoints

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#284]
Currently, we are not exposing @DeqingQu's COHD code to the reasoning interface. Similar to [CommonlyTreatsSolution.py](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/CommonlyTreatsSolution.py), we need python scripts that _answer biological questions while leveraging COHD data_.

1. Take as input nodes/node types/edges/edge types from our KG
2. Query COHD to answer the question
3. convert identifiers to things in our KG
4. Format the output in the JSON output specification

It would be good to interface with Casey Ta about the kinds of biological questions that can be answered with COHD.

**Comment by dkoslicki** [comment]
After this has been tested, please put an example in [QuestionExamples.tsv](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/QuestionExamples.tsv). Of course, in Questions.tsv as well.

**Comment by DeqingQu** [comment]
Hi @finnagin. As you added get_surprising_conditions_treating function to the COHDUtilities.py in the reasoning_lists branch and I implemented a similar method in the master branch, I would like to rollback the COHDUtilities.py in the master branch to avoid any conflict when merging the reasoning_lists branch to master branch. Is it fine?

**Comment by finnagin** [comment]
@DeqingQu Yeah go ahead and do that. Also, I'll add an example for SurprisingSolution.py to QuestionsExamples.tsv in the reasoning_lists branch.

**Comment by DeqingQu** [comment]
Thank you, @finnagin. COHDUtilities.py is reverted to the previous version on the master branch.

**Comment by saramsey** [comment]
what's the status of this?  can we close the issue?

**Comment by saramsey** [comment]
@finnagin I am going to put you on this issue, with @DeqingQu advising as needed. Is that cool with you?  (Deqing is graduating this winter so I am having him focus on a few remaining high-priority issues that he is already working on).

**Comment by finnagin** [comment]
@saramsey I believe we can close this issue as this was implemented at the hackathon.
