### ISSUE TITLE
Add list functionality to question answering scripts

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#285]
Currently we only accept single inputs in most of the questions in [Questions.tsv](https://github.com/RTXteam/RTX/blob/reasoning_lists/code/reasoningtool/QuestionAnswering/Questions.tsv). This issue is for updating these to accept lists starting with all single and double hop questions.

**Comment by dkoslicki** [comment]
Can you both use [QuestionAnsweringTestSuite.py](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/QuestionAnsweringTestSuite.py) to make sure of the following:

- [ ] The newly added questions do not cause mis-classification of other questions (eg. "What drugs have similar protein targets to naproxen" should classify to Q16 and only Q16")
- [ ] The newly added questions correctly classify themselves (eg. take a corpus sentence from Q89 and make sure it classifies to Q89)
- [ ] Make sure that the *.py code correctly handles lists:
```python
import ParseQuestion
p=ParseQuestion.ParseQuestion()
question, parameters, error_message, error_code = p.parse_question("what are the protein targets of naproxen")
to_run = question.solution_script.safe_substitute(parameters)
print(to_run)
```
Then make sure the printed ``to_run`` command executes successfully from the command line.
After doing this, we can import this branch into master.

**Comment by finnagin** [comment]
Also, there are subclass_of questions in the tsv. Should we remove those or keep them in?

**Comment by dkoslicki** [comment]
@finnagin I think leaving the subclass questions in are fine. May not be used too frequently, but better to be more complete than not.

As for the mis-classified questions, it appears that trying the top 3 templates was not enough, so I increased it to 5 and some of those misclasifications went away. As for the commonly treats and microrna questions, those are known bugs that will remain bugs for the foreseeable future.

**Comment by finnagin** [comment]
Finished checking classifications after the Questions.tsv fix. Here are the results that involve the new questions:


Question | Classification | Question Text | Classification Text
-- | -- | -- | --
Q36 | Q65 | What proteins involve similar biological processes as $protein | Which biological process is the protein $protein involved in
Q80 | Q8 | Which protein is the anatomical entity $anatomical_entity expressed in | What genes are expressed in $anatomical_entity
Q82 | Q30 | Which protein is the disease $disease gene associated with | What diseases are associated with proteins targeted by $chemical_substance
Q84 | Q68 | Which anatomical entity is the biological process $biological_process capable of | Which biological process is the anatomical entity $anatomical_entity capable of
Q87 | Q86 | Which cellular component does the anatomical entity $anatomical_entity have | Which cellular component is the cellular component $cellular_component a subclass of
Q90 | Q69 | Which phenotypic feature is the chemical substance $chemical_substance contraindicated for | Which chemical substance is the phenotypic feature $phenotypic_feature contraindicated for
Q94 | Q81 | Which disease does the protein $protein gene mutations contribute to | Which protein gene mutations contribute to the disease $disease 

Next step will be to change these questions and their corpuses so that these misclassifications are no longer happening and then recheck to make sure no new misclassifications are introduced.

**Comment by dkoslicki** [comment]
@finnagin @jlmcclelland This seems to have fallen off my radar. Do either of you know the status of this and if/when we would want to merge this with master?

**Comment by dkoslicki** [comment]
Closing due to #788 and this being implemented (but then depreciated) during some hackathon (Portland iirc)
