### ISSUE TITLE
relationship "publications" property should have CURIE IDs

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#288]
Per Chris Mungall, relationship "publications" property should have CURIE IDs for PubMed articles, not just the numeric PubMed IDs.

At the moment, I think this only pertains to the code in QueryDGIdb.py

**Comment by dkoslicki** [comment]
We should also be aware that these will probably be returned as a list, not a string (as in the current spec). Cc @edeutsch

**Comment by dkoslicki** [comment]
@saramsey close due to #788?
