### ISSUE TITLE
"relation" relationship property should be RO CURIE IDs

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#289]
According to Chris Mungall, the "relation" property of relationships in our Neo4j DB should be CURIE IDs from the Relationship Ontology.

We should discuss this in the KG Standardization meeting.

**Comment by saramsey** [comment]
From Chris Mungall:

> https://biolink.github.io/biolink-model/about/mapping-neo4j.html
> 
> The wording could be clearer..
> 
> "Each edge in the neo4j graph should have an edge label / relationship type that is a subproperty of related to.
> For example, two protein nodes may be related via physically_interacts_with relationship types.
> snake_case is always used for edge labels.""
> 
> ^^ this refers to the actual edge label in Neo4J. It's human readable to facilitate readable cypher
> 
> Edges SHOULD have a relation property which encodes the most specific relationship type for the relationship. This MAY correspond to the edge label, or it MAY be more specific. The relation property MUST be encoded as a CURIE or IRI.
> 
> ^^ this is for the 'relation' property on an edge.
> 
>

**Comment by dkoslicki** [comment]
@saramsey close due to #788?

**Comment by finnagin** [comment]
@saramsey should we close this or movie it to the RTX-KG2 repo?

**Comment by saramsey** [comment]
This issue has been superseded by Biolink's decision to not use RO.
