### ISSUE TITLE
Need a generic is/isn't contraindicated for function

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#290]
It would be nice (perhaps placed in ``ReasoningUtilities.py``) to have a function that generically looks for drug/disease pairs that are contraindicated. This is not a simple "check if (n:chemical_substance)-[:contraindicated_for]-(m:disease)" as sometimes the drug is contraindicated for some of the phenotypes of a disease, or the disease is a subclass of another disease, and the drug is contraindicated for that disease. as an example:
```
match p=allShortestPaths((n:chemical_substance{name:"megestrol"})-[*1..4]-(m:disease{id:"DOID:9352"})) return p
```
which results in the following:
![graph](https://user-images.githubusercontent.com/6362936/46040443-2b290900-c0c5-11e8-969d-58dbf63e7209.png)

@jaredroach might want to weigh in on this, but I was thinking:
1. If (drug)-[:contraindicated_for]-(disease) then its definitely contraindicated
2. If (drug)-[:contraindicated_for]-(d1:disease)-[:subclass_of]-(d2:disease) then the drug is also contraindicated for disease d2.
3. If there are many paths of the type (drug)-[:contraindicated_for]-(:phenotypic_feature)-[:has_phenotype]-(d1:disease) then the drug is contraindicated for the disease d1. Though we may want to be careful since our KG lists ALL possible phenotypes for a disease, so we may want to: a) set a threshold for how many phenotypes it's contraindicated for b) weight the disease-phenotype relationship based on the frequency in COHD (to get a sense of how common this symptom actually is), and then set a threshold, or c) just report how many/the total COHD freq of such contraindicated symptoms.

@finnagin @jlmcclelland Any takers for this task? Not super high priority, but would be quite useful to have when the workflows start getting rolled out. Don't want to be returning bad results.

**Comment by jlmcclelland** [comment]
I can make this happen.

**Comment by dkoslicki** [comment]
Closing due to #788
