### ISSUE TITLE
Q103 example misinterpreted

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#292]
When I select example question 103:
Which pathways are most enriched by [PCNA,WRN,RMI1,RMI2]?

The response is:
Your question has been interpreted and is restated as follows:
   What monogentic conditions are most enriched for phenotypes shared with WERNER SYNDROME; WRN?
Please ensure that this is an accurate restatement of the intended question.

**Comment by dkoslicki** [comment]
BIG JIM API changed, and list parsing is not high-prio for ARAX given we have other mechanisms to handle this now (see `is_set`). Closing if no objections
