### ISSUE TITLE
Orphaned nodes

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#296]
It looks like there are a good deal of nodes with no relationships connecting them:
```
match (n) where not (n)--() return count(n)
```
Here's a breakdown by node type:
```
match (n) where not (n)--() return distinct labels(n), count(*)
```
type | count
-- | --
["Base", "disease"] | 5783
["Base", "pathway"] | 1503
["Base", "metabolite"] | 15880
["Base", "phenotypic_feature"] | 2
["Base", "anatomical_entity"] | 11
["Base", "molecular_function"] | 983
["Base", "chemical_substance"] | 138
["Base", "biological_process"] | 1093
["Base", "protein"] | 817
["Base", "cellular_component"] | 202

**Comment by saramsey** [comment]
Hi David, thank you for letting me know. 

Do you happen to recall, in which KG (i.e., in which Neo4j instance) are you seeing this issue?

Thanks,
Steve

**Comment by dkoslicki** [comment]
http://rtx.ncats.io:7574/, I believe.

**Comment by dkoslicki** [comment]
Closing due to #788
