### ISSUE TITLE
Cache hit/miss matching needs to take into account options

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#297]
When we start using the [options] component as part of the queries, the cache hit/miss detection algorithm should look at [options] as well. Might be potentially tricky to figure out if an [option] affects the result or not. I suppose we have to assume that it will.

**Comment by dkoslicki** [comment]
Closing due to #788, right @edeutsch?

**Comment by edeutsch** [comment]
sure, fine to close
