### ISSUE TITLE
make all the kg-construction code use CacheControl and to transparently have cache expiration

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#299]
Hi Deqing,

Can you please investigate whether it is possible to get (from requests-cache) the _timestamp_ of when a given HTTP response was first put into the cache?

See this page (link provided by @dkoslicki )
https://requests-cache.readthedocs.io/en/latest/api.html

Thanks,
Steve

Proposed by:  @edeutsch

**Comment by DeqingQu** [comment]
Hi Steve,

I wrote a helper function which could get the timestamp of an HTTP GET request using request_cache. I uploaded the code on the request_cache branch.

https://github.com/RTXteam/RTX/blob/request_cache/code/reasoningtool/kg-construction/request_cache_helper.py

I test the code on the ISSUE259 instance with the 63G cache. I thought the get_timestamp function would take a long time to query the timestamp, but in fact, the timestamp querying only costs about 0.005s.

**Comment by saramsey** [comment]
Great!  I suppose then that in order to use this, some refactoring would be required, is that right?  My reasoning is that we currently use the requests module in many different modules under kg-construction. If the above is correct, then I have a second question for you: how extensive do you think the required refactoring would be?

**Comment by DeqingQu** [comment]
Yes, the refactoring would be required.

I have a rough idea about how to do the refactoring. Can you give me some advice on it?

I would like to write our own requesst_cache class which is inherited from the original requests_cache class. For the new requests_cache class, we can add some new methods like 'get_timestamp(URL)', 'refresh_cache(URL)', and also rewrite the 'requests.get' method which can refresh the cache item according to the timestamp (for example, if the timestamp of the URL is too old, refresh it). 
The refactoring work on the QueryXXX modules would be not too much. We only need to import our own requests_cache.

**Comment by saramsey** [comment]
@DeqingQu provided the following update:

- some testing is required in order to work around the issue that the GeneProf site is now down (apparently permanently). We are hoping to just use the old requests-cache sqlite cache but *only* for QueryGeneProf. 
- need to re-implement QueryMyGene.py because that module uses the "mygene" python package, and the latter uses requests-cache internally. This is not good because it bypasses our chosen cache system (CacheControl). @DeqingQu has a workaround for this, basically re-implementing QueryMyGene.py so that it uses the Mygene.info REST API rather than using the "mygene" package.
- plan is to wrap up the development work next week, and then it is estimated that building a new KG from scratch will take another whole week.  So probably week 2 or week 3 in Februrary, we hope to have this issue closed.

**Comment by DeqingQu** [comment]
@saramsey The new KG using CacheControl has been generated and I have deployed it on RTX2 (The previous KG on RTX2 has been backed up in the /mnt/data/backup folder). There are more nodes and relations comparing to our old KG.
new KG (7787): 128,860 nodes and 3,812,956 edges
old KG (7687): 124,811 nodes and 3,804,435 edges

**Comment by saramsey** [comment]
current plan: more testing to make sure that the KG in RTX2 is complete and accurate

**Comment by saramsey** [comment]
please try running Finn's indexing script on the new KG

**Comment by saramsey** [comment]
@finnagin  you may wish to update your repo if it is on the master branch, to get the changes that have just been merged for module QueryUMLSApi.py. Thank you Deqing for doing this work.

**Comment by saramsey** [comment]
Next steps: 
1. clone the RTX repository somewhere and do a full build of the KG using the code in the master branch.
2. @DeqingQu @saramsey and @dkoslicki should all look at the resulting KG in the Neo4j web client to make sure that it looks sane.
3. We need a README.md in code/reasoningtool/kg-construction that explains how to build the KG and deploy it into production.
4. then we are ready to close out this issue, I think.

**Comment by DeqingQu** [comment]
Step 1:
A KG is built using the latest code in the master branch on 'ISSUE299' container on 'rtx.ncats.io' server. The number of nodes is as same as the KG built using the code in the 'issue299' branch. The number of relations is almost the same (3,812,957 vs 3,812,714).
