### ISSUE TITLE
add ChEMBL drug->target probability scores for target predictions to the KG

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#3]
_From @saramsey on January 10, 2018 1:10_

_Copied from original issue: dkoslicki/NCATS#133_

**Comment by dkoslicki** [comment]
@saramsey I noticed you closed this. Is this now a node property in the new KG?

**Comment by saramsey** [comment]
relationship property, specifically for drug-to-protein relationships

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Mar 29, 2018, at 12:44 AM, David Koslicki <notifications@github.com<mailto:notifications@github.com>> wrote:


@saramsey<https://github.com/saramsey> I noticed you closed this. Is this now a node property in the new KG?
