### ISSUE TITLE
Update Knowledge Source Registry with list of which Translator KSs we are using

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#302]
@edeutsch and @dkoslicki asked us to update the Translator Knowledge Source Registry (which is a Google Doc: https://docs.google.com/spreadsheets/d/1pNJdntyi6IRXehvIdekNRAlbRhuL4ATUq5yBSVOkPWc/edit#gid=0) to indicate which "Translator" knowledge sources (each of which is a row in that Google sheet) we are using in the construction of our Neo4j knowledge graph. That information should go into Column N of the Google Sheet).

**Comment by DeqingQu** [comment]
Finn wrote a module called 'QueryUMLSAPI.py', so the 'UMLS API' was used in our project.

The 'UMLS API' was the only missing thing I found in the google doc and I have added it to our team.

**Comment by dkoslicki** [comment]
Just cleaning up old issues. Shall we close this one?

**Comment by dkoslicki** [comment]
Closing due to #788
