### ISSUE TITLE
For reactome nodes in the KG, switch to using "Reactome" as the CURIE prefix.

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#304]
According to this standards document:

https://docs.google.com/spreadsheets/d/1BCtJWyz9WpwI-myN3HwWkwsjxvUNr1OrdGU60QCs2Uw/edit#gid=0

**Comment by saramsey** [comment]
marking this low priority

**Comment by dkoslicki** [comment]
Closing due to #788, unless @saramsey objects
