### ISSUE TITLE
Time to update Python/modules on rtx?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#308]
Hi everyone, I have been trying to update RTX for the latest 0.9.0 API proposal and it has been mostly going okay, but I have run into some issues where code that works on my test machine is failing on rtx.ncats.io and vice versa.

For example, here:
https://github.com/RTXteam/RTX/commit/a3ffece686a22ce115db41d6a05ba11790e933ba#diff-f905001efbb924f306f9d08f30229c52
in ReasoningUtilities.py I'm having a bit of a struggle coming up with code that runs on my test machine which I believe has the latest Python 3.7.2 and the latest cypher packages vs. rtx which has Python 3.5.2 and an older cypher package (I assume either neo4j-driver or ipython-cypher but I'm not even sure which)

As an aside there was discussion at the Monday KG/API call about setting Python 3.6 as a minimum Translator-wide.

So my question is: are other people struggling with this as well, or am I just confused? Do we want to attempt to get all of us on the latest versions of these things across all our dev and deployment machines?

As a separate alert, I've mucked around with get_node_property() and added get_node_properties() in a way that may have implications greater than I can comprehend (so far just in the NewFmt branch), and a interactive consult would be helpful when you have time.

**Comment by dkoslicki** [comment]
@edeutsch Hmm... I think there are two things going on here:
1. I am using Python 3.5.2 for dev stuff, neo4j python package version 1.5.3, and ipython-cypher version 0.2.6
2. The branch NewFmt is 88 commits behind master. You'll notice that in the commit you referenced (a3ffece), master now uses ``return res[0]['n.%s' % node_property]`` instead of 
```python
if record:
            for key in record.keys():
                if key == "n.%s" % node_property: return(record[key])
```
This may or may not complicate the issue you're seeing.

In any case, upgrading to a new cypher makes sense, but will take quite a bit of work (if this is only the tip of the iceberg).

**Comment by edeutsch** [comment]
1. So you are more in line with what's on rtx.ncats.io. I recently installed python and modules on a new machine and everything is newer, which is causing me the troubles. I could try to downgrade or we could all upgrade. I'm not sure what's best. Thus this thread.
2. Right, this is one of the problems I ran into. I don't recall the exact details, but I think the latest neo4j code rejects:
    2\. `return res[0]['n.%s' % node_property]`
So it's not that master "now uses" that syntax. It's actually the other way around that NewFmt no longer uses res[0] syntax because a machine with the latest python and modules won't tolerate referring to bolt records as if they were just arrays or dicts. But rather you're supposed to use OO methods like .single() and .key() and .value(). I think. But for example, the rather elegant record.value() that I started using on my new/latest software test machine (which I did because the old:
     res = [i for i in res] # consume the query
     return res[0]['n.%s' % node_property]
did not work anymore) did not work/wasn't supported back under the old version.

So what you see now under NewFmt is inelegant but works with both the latest and the older modules. this is my conundrum.

**Comment by saramsey** [comment]
> As an aside there was discussion at the Monday KG/API call about setting Python 3.6 as a minimum Translator-wide.

I would tend to want to push back on some kind of minimum python version requirement for all Translator software. There are some software tools that I need to use, that require python 2.7 (`umls2rdf` is an example). I don't have time to fix `umls2rdf` to bring it up to python3.

**Comment by saramsey** [comment]
I don't have a strong feeling about updating python3 on rtx.ncats.io. I confess I tend to be in the "if it's not broken, don't mess with it" school of thought.  If you decide to keep rtx.ncats.io at 3.5.2, you can always set up a virtualenv on your test machine and install python 3.5.2 into the virtualenv, so you can test any python module on your test machine and be confident that it will work on rtx.ncats.io (at least from the standpoint of python interpreter version). 

If you decide to update python on rtx.ncats.io, you might want to commit the docker container before doing the python upgrade so that you have a relatively easy rollback option.

**Comment by edeutsch** [comment]
A complete separate check in recently by @finnagin seems like valid Python 3.6+, but fails on rtx.ncats.io Python 3.5.

Pressure is mounting to be on modern Python. It seems like several of us are developing and testing and checking in from machines with newer/more capable Python that on production.

Unless there are fresh protests, I will attempt to upgrade Python on rtx.ncats.io to the latest 3.7.3 as well as update all modules to the latest.

**Comment by dkoslicki** [comment]
Per our discussion earlier today, @finnagin , @edeutsch and I are in agreement that we should update to a more recent python. Especially given that we are now incorporating code from other reasoning teams, and this will make it much easier to integrate their code.

**Comment by edeutsch** [comment]
The /devED endpoint is now successfully running on Python 3.7.3, the latest.
There was one little incompatibility that was detected so far on 3.5 -> 3.7 that was easily fixed.
I did not disturb the existing 3.5 in /usr/bin, so all other endpoints are still using that.
Any new endpoints running from NewFmt and eventually trunk when it gets updated will use 3.7.3 at that point, although 3.5 will remain available on the server.

Note that the code requiring 3.6 is in ReasoningUtilities.py which is use by pretty much everything, so NewFmt will no longer even compile under 3.5

The only minor 3.7.3 issue is just in the deserializer in the API interface, and so that is unlikely to affect anyone on your dev machines.

Please do post any other 3.5 - 3.7 incompatibilities you run into.

**Comment by edeutsch** [comment]
rtx.ncats.io has both the original 3.5 Python and separately in /mnt/data/python/Python-3.7.3 the latest Python. All instances running NewFmt and newer will require the newer Python.
@Everyone, in all your dev instances, you will need to run Python 3.6 or newer when running NewFmt or newer.

**Comment by edeutsch** [comment]
Hi everyone, just to inform you all, I am using Python 3.7.x on my various machines. arax.rtx.ai is running 3.7.3 in production. David and I were just struggling with a weird error message related to conversion of a dict to an object using a from_dict method. After thrashing around for a while and coming up dry, David upgraded his Python 3.6.8 (and perhaps some outdated modules) to Python 3.7.? and all new modules (right?) and the code that was previously mysteriously failing on his machine - but not mine - is now working just fine.

So... Python 3.7.x+ and fresh modules are recommended for ARAX development, although the true nature of the problem on David's machine is not really known.

**Comment by dkoslicki** [comment]
Closing due to #788. TLDR use python 3.7.x
