### ISSUE TITLE
update kg-construction code to obtain a timestamp for every relationship

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#309]
this issue depends on completion of issue #299 

we will discuss this issue after the hackathon

**Comment by saramsey** [comment]
@DeqingQu to help in a consulting capacity on this issue

@erikyao to take the lead on implementing the code refactoring needed for this issue

**Comment by saramsey** [comment]
@DeqingQu can you please make an assessment of how much time this might take to implement, based on your current understanding of how CacheControl works and the number of QueryXXXXX modules that we have in the kg-construction directory?

**Comment by saramsey** [comment]
To find the latest release date for ChEMBL, look on this page:
https://chembl.gitbook.io/chembl-interface-documentation/downloads

**Comment by saramsey** [comment]
To find the latest release date for DrugBank, look on this page:
https://www.drugbank.ca/release_notes

**Comment by saramsey** [comment]
To find the latest release date for UniProt, look on this page:
ftp://ftp.uniprot.org/pub/databases/uniprot/relnotes.txt

**Comment by saramsey** [comment]
COHD appears to be a single release that is not updated:
http://smart-api.info/ui/9fbeaeabd19b334fa0f1932aa111bf35

**Comment by saramsey** [comment]
For DisGeNET, you can find version information at the bottom of this page:
http://www.disgenet.org/dbinfo

**Comment by saramsey** [comment]
KEGG:
https://www.genome.jp/kegg/docs/relnote.html

**Comment by saramsey** [comment]
For OMIM, it appears to update on the first of every month:
https://www.omim.org/statistics/update

**Comment by saramsey** [comment]
EWD asks for this information to *ultimately* propagate to each relelationship in the Neo4j KG, as a relationship property.

**Comment by DeqingQu** [comment]
BioLink (missing)
https://api.monarchinitiative.org/api/

DGIdb
http://www.dgidb.org/downloads

Disont (Disease Ontology)
http://www.disease-ontology.org/news/

EBIOLS
https://www.ebi.ac.uk/ols/index

GeneProf (stopped)

HMDB
http://www.hmdb.ca/release-notes

MiRBase
http://www.mirbase.org/

MiRGate (missing)

MyChem
https://mychem.info/

MyGene
https://mygene.info

NCBI
https://www.ncbi.nlm.nih.gov/books/NBK25499/#chapter4.Release_Notes

PC2 (missing)
https://www.pathwaycommons.org/pc2/home

Pharos
https://pharos.ncats.io/index

PubChem
https://pubchemdocs.ncbi.nlm.nih.gov/pug-rest

Reactome
https://reactome.org/

SciGraph (missing)
https://scigraph-ontology.monarchinitiative.org/scigraph/docs/

**Comment by saramsey** [comment]
For Monarch:
https://archive.monarchinitiative.org/201702/ttl/

**Comment by saramsey** [comment]
For MirGate, just hard-code this date:  2015 Apr 8;2015:

**Comment by saramsey** [comment]
For PC2, just use the date for BioGrid on this page:
https://www.pathwaycommons.org/pc2/datasources

**Comment by saramsey** [comment]
From Kent Shefchek (this looks very helpful for Monarch and SciGraph):
```
Hi Steve,

Deepak recently added this endpoint: https://api-dev.monarchinitiative.org/api/metadata/datasets, but it hasn't yet been pushed to production.  In most cases "version" represents the date in which we fetched data from a source.  We're working on adding more informative metadata for our sources such as versions and general stats about the data fetched from each source.

Hope this helps!
Kent
```

**Comment by dkoslicki** [comment]
@saramsey still relevant? Or close due to #788?
