### ISSUE TITLE
RTX UI:  when the cursor is in the "JSON responses" textbox, map <ctrl-A> to selecting *only* the JSON

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#310]
Paul Clemons asked for this feature; just wants ctrl-A to select the text in the red box shown below:

<img width="1352" alt="screen shot 2019-03-05 at 11 14 40 am" src="https://user-images.githubusercontent.com/5562107/53830737-f6ed2a80-3f37-11e9-93ad-23dbce1449af.png">

**Comment by edeutsch** [comment]
Seems reasonable. And presumably just the *response* JSON, not the other JSON. I'll leave this one to Luis.

**Comment by edeutsch** [comment]
Does this seem rather urgentish? And do we want this to apply to the production 0.8.0 UI? (presumably what Paul is using?)

**Comment by dkoslicki** [comment]
@edeutsch @isbluis Would it be easier to just make this link clickable:
[https://rtx.ncats.io/api/rtx/v1/response/1515](https://rtx.ncats.io/api/rtx/v1/response/1515)
as this gives just the JSON result

**Comment by isbluis** [comment]
I have implemented this in my dev area -- can you please test and give feedback when you get a chance?

Just click on the button at the top of the "Dev" page; response text will get copied to clipboard, ready to be pasted.  So far tested it in Chrome only.

https://rtx.ncats.io/devLM/n.html

Can easily be ported to older versions of UI and/or production.

**Comment by isbluis** [comment]
Is this issue considered closed?  Or is any functionality missing?

**Comment by edeutsch** [comment]
closed I think, thanks.
