### ISSUE TITLE
cache_control_helper?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#316]
@DeqingQu in testing for issue #252, I'm getting an error about no module named cachecontrol or  cache_control_helper, this is apparently inside [QueryCOHD.py](https://github.com/RTXteam/RTX/blob/issue252-cur/code/reasoningtool/kg-construction/QueryCOHD.py#L24). Can you add whatever package you need to install to get this to work inside [requirements.txt](https://github.com/RTXteam/RTX/blob/issue252-cur/requirements.txt)?

**Comment by dkoslicki** [comment]
@DeqingQu I think I found it:
```
requests
CacheControl
lockfile
```
But please correct me if I'm wrong

**Comment by DeqingQu** [comment]
@dkoslicki Sorry for my late reply. I just went back for lunch. Please let me know if you have any other problems with the tests.
