### ISSUE TITLE
HTTP 429 response for Q1

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#317]
Finn, I'm running into more issues with 429 responses from NCBI eUtils (I think this is from your google distance code) just like what happened at the hackathon. Eg, running:
```bash
python Q1Solution.py -i 'DOID:12365' -j
```
Results in a bunch of errors like:
```bash
HTTP response status code: 429 for URL:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=mesh&term=Rhabdomyosarcoma%2C%20Embryonal%2C%201%5BMeSH%20Terms%5D&retmode=json&retmax=1000
```
Can you look into this?

**Comment by finnagin** [comment]
Sure I can take a look. Are you trying from the same laptop?

**Comment by finnagin** [comment]
My guess is either your computer got blacklisted at the hackathon or they reduced the api call rate limit. I could add something into the eUtils code that if it gets a 429 response code it retries after waiting an extra second or two and see if that works. Right now I'm seeing if I can recreate the error and then I'll try adding that in and see if it works.

**Comment by finnagin** [comment]
I'm not getting any 429 status codes. I'm getting several errors like this:
```
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=mesh&term=Astrocytomas%2C%20Subependymal%5BMeSH%20Terms%5D&retmode=json&retmax=1000
unable to open database file received in QueryMiRGate for URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=mesh&term=Astrocytomas%2C%20Subependymal%5BMeSH%20Terms%5D&retmode=json&retmax=1000
```
or
```
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=mesh&term=Subependymal%20Astrocytomas%5BMeSH%20Terms%5D&retmode=json&retmax=1000
[('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')] received in QueryMiRGate for URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=mesh&term=Subependymal%20Astrocytomas%5BMeSH%20Terms%5D&retmode=json&retmax=1000
```
Then ends up crashing from some OpenSSL error:
```
OpenSSL.SSL.Error: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]
```
I'm gonna head home for the day but I'll look into this more tomorrow

**Comment by dkoslicki** [comment]
Odd! And no, I was not trying from the same computer (this time it was a desktop on campus). In any case, definitely deserves more investigation...

**Comment by edeutsch** [comment]
FWIW, I clicked on the link at the top of the thread and got:
{
    "header": {
        "type": "esearch",
        "version": "0.3"
    },
    "esearchresult": {
        "count": "0",
        "retmax": "0",
        "retstart": "0",
        "idlist": [
        ],
        "translationset": [
        ],
        "querytranslation": "(Rhabdomyosarcoma, Embryonal, 1[MeSH Terms])",
        "errorlist": {
            "phrasesnotfound": [
                "Rhabdomyosarcoma, Embryonal, 1[MeSH Terms]"
            ],
            "fieldsnotfound": [
            ]
        },
        "warninglist": {
            "phrasesignored": [
            ],
            "quotedphrasesnotfound": [
            ],
            "outputmessages": [
                "No items found."
            ]
        }
    }
}

**Comment by edeutsch** [comment]
I did in the browser, so can't actually see what the response code is..

**Comment by dkoslicki** [comment]
Apparently HTTP code 429 is "too many requests". @finnagin I'm also getting HTTP code 414 "URI too long" when running ``python Q1Solution.py`` which seems to originate from the normalized google distance code as well. See below:
```bash
HTTP response status code: 414 for URL:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=Congenital%20Hyperinsulinism%5BMeSH%20Terms%5D%7CCongenital%20Hyperinsulinisms%5BMeSH%20Terms%5D%7CHyperinsulinisms%2C%20Congenital%5BMeSH%20Terms%5D%7CHyperinsulinemia%20Hypoglycemia%20of%20Infancy%5BMeSH%20Terms%5D%7CInfancy%20Hyperinsulinemia%20Hypoglycemias%5BMeSH%20Terms%5D%7CHyperinsulinemic%20Hypoglycemia%2C%20Persistent%5BMeSH%20Terms%5D%7CHyperinsulinemic%20Hypoglycemias%2C%20Persistent%5BMeSH%20Terms%5D%7CHypoglycemia%2C%20Persistent%20Hyperinsulinemic%5BMeSH%20Terms%5D%7CHypoglycemias%2C%20Persistent%20Hyperinsulinemic%5BMeSH%20Terms%5D%7CPersistent%20Hyperinsulinemic%20Hypoglycemias%5BMeSH%20Terms%5D%7CHyperinsulinism%2C%20Congenital%5BMeSH%20Terms%5D%7CHyperinsulinism%2C%20Familial%5BMeSH%20Terms%5D%7CFamilial%20Hyperinsulinisms%5BMeSH%20Terms%5D%7CHyperinsulinisms%2C%20Familial%5BMeSH%20Terms%5D%7CPHHI%20Hypoglycemia%5BMeSH%20Terms%5D%7CHypoglycemia%2C%20PHHI%5BMeSH%20Terms%5D%7CHypoglycemias%2C%20PHHI%5BMeSH%20Terms%5D%7CPHHI%20Hypoglycemias%5BMeSH%20Terms%5D%7CHypoglycemia%2C%20Hyperinsulinemic%2C%20of%20Infancy%5BMeSH%20Terms%5D%7CInfancy%20Hyperinsulinemia%20Hypoglycemia%5BMeSH%20Terms%5D%7CNeonatal%20Hyperinsulinism%5BMeSH%20Terms%5D%7CPersistent%20Hyperinsulinemia%20Hypoglycemia%20of%20Infancy%5BMeSH%20Terms%5D%7CPersistent%20Hyperinsulinemic%20Hypoglycemia%5BMeSH%20Terms%5D%7CFamilial%20Hyperinsulinism%5BMeSH%20Terms%5D%7CHyperinsulinism%2C%20Neonatal%5BMeSH%20Terms%5D%7CHyperinsulinisms%2C%20Neonatal%5BMeSH%20Terms%5D%7CNeonatal%20Hyperinsulinisms%5BMeSH%20Terms%5D%7CHyperinsulinemic%20Hypoglycemia%2C%20Familial%2C%202%5BMeSH%20Terms%5D%7CFamilial%20Hyperinsulinemic%20Hypoglycemia%201%5BMeSH%20Terms%5D%7CHyperinsulinemic%20Hypoglycemia%2C%20Familial%2C%201%5BMeSH%20Terms%5D%7CHyperinsulinemic%20Hypoglycemia%20Due%20to%20Focal%20Adenomatous%20Hyperplasia%5BMeSH%20Terms%5D%7CCongenital%20Hyperinsulinism%5BMeSH%20Terms%5D%7CCongenital%20Hyperinsulinisms%5BMeSH%20Terms%5D%7CHyperinsulinisms%2C%20Congenital%5BMeSH%20Terms%5D%7CHyperinsulinemia%20Hypoglycemia%20of%20Infancy%5BMeSH%20Terms%5D%7CInfancy%20Hyperinsulinemia%20Hypoglycemias%5BMeSH%20Terms%5D%7CHyperinsulinemic%20Hypoglycemia%2C%20Persistent%5BMeSH%20Terms%5D%7CHyperinsulinemic%20Hypoglycemias%2C%20Persistent%5BMeSH%20Terms%5D%7CHypoglycemia%2C%20Persistent%20Hyperinsulinemic%5BMeSH%20Terms%5D%7CHypoglycemias%2C%20Persistent%20Hyperinsulinemic%5BMeSH%20Terms%5D%7CPersistent%20Hyperinsulinemic%20Hypoglycemias%5BMeSH%20Terms%5D%7CHyperinsulinism%2C%20Congenital%5BMeSH%20Terms%5D%7CHyperinsulinism%2C%20Familial%5BMeSH%20Terms%5D%7CFamilial%20Hyperinsulinisms%5BMeSH%20Terms%5D%7CHyperinsulinisms%2C%20Familial%5BMeSH%20Terms%5D%7CPHHI%20Hypoglycemia%5BMeSH%20Terms%5D%7CHypoglycemia%2C%20PHHI%5BMeSH%20Terms%5D%7CHypoglycemias%2C%20PHHI%5BMeSH%20Terms%5D%7CPHHI%20Hypoglycemias%5BMeSH%20Terms%5D%7CHypoglycemia%2C%20Hyperinsulinemic%2C%20of%20Infancy%5BMeSH%20Terms%5D%7CInfancy%20Hyperinsulinemia%20Hypoglycemia%5BMeSH%20Terms%5D%7CNeonatal%20Hyperinsulinism%5BMeSH%20Terms%5D%7CPersistent%20Hyperinsulinemia%20Hypoglycemia%20of%20Infancy%5BMeSH%20Terms%5D%7CPersistent%20Hyperinsulinemic%20Hypoglycemia%5BMeSH%20Terms%5D%7CFamilial%20Hyperinsulinism%5BMeSH%20Terms%5D%7CHyperinsulinism%2C%20Neonatal%5BMeSH%20Terms%5D%7CHyperinsulinisms%2C%20Neonatal%5BMeSH%20Terms%5D%7CNeonatal%20Hyperinsulinisms%5BMeSH%20Terms%5D%7CHyperinsulinemic%20Hypoglycemia%2C%20Familial%2C%202%5BMeSH%20Terms%5D%7CFamilial%20Hyperinsulinemic%20Hypoglycemia%201%5BMeSH%20Terms%5D%7CHyperinsulinemic%20Hypoglycemia%2C%20Familial%2C%201%5BMeSH%20Terms%5D%7CHyperinsulinemic%20Hypoglycemia%20Due%20to%20Focal%20Adenomatous%20Hyperplasia%5BMeSH%20Terms%5D%7CNesidioblastosis%5BMeSH%20Terms%5D%7CNesidioblastoses%5BMeSH%20Terms%5D%7CPancreatic%20Nesidioblastosis%5BMeSH%20Terms%5D%7CNesidioblastoses%2C%20Pancreatic%5BMeSH%20Terms%5D%7CNesidioblastosis%2C%20Pancreatic%5BMeSH%20Terms%5D%7CPancreatic%20Nesidioblastoses%5BMeSH%20Terms%5D%7CHyperinsulinism%2C%20Familial%2C%20with%20Pancreatic%20Nesidioblastosis%5BMeSH%20Terms%5D%7CNesidioblastosis%20of%20Pancreas%5BMeSH%20Terms%5D%7CPancreas%20Nesidioblastoses%5BMeSH%20Terms%5D%7CPancreas%20Nesidioblastosis%5BMeSH%20Terms%5D&retmode=json&retmax=1000
```

**Comment by dkoslicki** [comment]
Note in the issue252-cur branch commit 5807d50 fixes a missing ``requests`` module in QueryNCBIeUtils.py. Won't fix this issue, but just good to know

**Comment by DeqingQu** [comment]
Hi @dkoslicki. To support the time-based caching strategy, @saramsey and I decided to use the 'CacheControl' library instead of the 'request-cache' library. So I refactored all the QueryXXX.py modules in the code. The request module should not be imported in the latest version of QueryXXX.py. We need to import the cache_control_helper module instead.
```
from cache_control_helper import CacheControlHelper
```
The cache_control_helper module encapsulates the methods of 'CacheControl' library to handle the caching strategy for HTTP requests. There is no need to modify the previous HTTP request code in QueryXXX.py. We only need to import the cache_control_helper module instead of the request module.

**Comment by dkoslicki** [comment]
Roger that @DeqingQu. Without importing ``requests``, in QueryNCBIeUtils.py, I get the following error:
```bash
File "QueryNCBIeUtils.py", line 551, in get_uniprot_names
    r = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})  # send get request
NameError: name 'requests' is not defined
```
what should we replace ``requests`` with in order to use the CacheControl library?

**Comment by DeqingQu** [comment]
@dkoslicki I made a quick fix on it. For better practice, the 'get_uniprot_names' and 'get_reactome_names' methods should use the 'send_query_get' to make an HTTP GET request,  because all excepts will be handled in the 'send_query_get' method. I will refactor the code later.

When I run all test cases in the main function, I got a lot of HTTP 429 response for the first time. But when I run it again, I can get the correct results. In the second time, many requests are cached so only the requests which are failed in the first time did real HTTP requests.

**Comment by finnagin** [comment]
@dkoslicki The 414 error is happening when we have too many synonyms for a set of terms searched for the pubmed hit count. The example causing the error here had I tried putting a limit on the number of synonyms to allow by just taking the first n synonyms found and this fixed the 414 errors for me. If you think that is a reasonable fix I can push the code and they should go away. 

Also, I still seem to be getting getting "unable to open database file" errors originating from QueryMiRGate when I run this. Is that just happening on my system or is it happening to you too?

**Comment by dkoslicki** [comment]
Yeah, that seems reasonable (too bad there's no way to figure out which synonyms are the "important" ones to use, save for querying over them all individually to see which ones return hits, which seems like it would take way too long (unless we somehow got our hands on a local copy of the pubmed database, which may exist somewhere)).

I have not seen any database files errors, so it might just be your system.

**Comment by finnagin** [comment]
Ok I'll push it then. 

Wierd. Maybe I've got the wrong version of some dependency. I'll look into it.

Also, are you still getting 429 (too many requests) errors or did running it a few times like @DeqingQu suggested work? If it's still an issue we could try adding something into `send_query_get`  method that checks if it got a 429 error and if so sleeps for a second and then tries 1 more time.

**Comment by dkoslicki** [comment]
I don't think the "just run it twice" method will be good long-term: either users will experience errors (unless they ask twice), or we double the run-time if we make it run through everything twice. I imagine a ``try catch`` is appropriate here as you mentioned. And we can figure out what's best to do with the 429's (either wait and incur a run-time penalty), or discard and move on (since NGD is only really used for heuristic purposes anyway. A bit of testing would be good here

**Comment by finnagin** [comment]
@dkoslicki I pushed the code for sleeping for a second retrying once after getting a 429 error. When you get a chance could you try running on your machine after clearing the cache and see if you still get any more 429 errors?

**Comment by dkoslicki** [comment]
@finnagin with the new cache being use:
```python
import CachedMethods
# import requests_cache
from cache_control_helper import CacheControlHelper
```
how does one clear the cache?

**Comment by finnagin** [comment]
That is a good question. @DeqingQu How do you clear the cache now?

**Comment by dkoslicki** [comment]
@finnagin without cache clearing, I get no more 429's, but do get 414 errors (URI too long)...
The Q1solution completes without error though, so it may be a non-issue...

**Comment by DeqingQu** [comment]
@dkoslicki @finnagin By default, the cache will be out of date in 30 days. For now, there is no API for clearing cache. But if you want to clear the cache for testing, you can manually delete the '.web_cache' folder.
I will add an API for cache clearing in class CacheControlHelper soon

**Comment by dkoslicki** [comment]
Thanks @DeqingQu !

**Comment by dkoslicki** [comment]
Closing due to #788
