### ISSUE TITLE
New NodeNamesDescriptions?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#318]
I notice that there is a new NodeNamesDescriptions.tsv file.
This normally needs to trigger a new index file. What are the changes? Is this to the master KG, or a development KG?
Update was 14 days ago with comment "Update KG metadata"

**Comment by dkoslicki** [comment]
It was due to changes in the master KG that never got updated in the descriptions file (new nodes, edges, and even edge types).

**Comment by edeutsch** [comment]
okay, I will drop and recreate the kgnodeindex then

**Comment by dkoslicki** [comment]
Sounds good! Also, @finnagin, @jlmcclelland , @DeqingQu , @erikyao , @saramsey be sure to drop and recreate the KG Node index for any local dev purposes:
```python
import KGNodeIndex
kgNodeIndex = KGNodeIndex()
kgNodeIndex.createDatabase()
kgNodeIndex.createNodeTable()
```
of course, after a ``git pull``

Closing this issue.

**Comment by edeutsch** [comment]
okay, a new KGNodeIndex is build on rtx.ncats.io. Let me know if there are any issues with the KGNodeIndex on that server in any of the endpoints.

Also, note that you can just rebuild your index from the command line with:
`cd reasoningtool/kg-construction`
`python3 KGNodeIndex.py --build`
