### ISSUE TITLE
Can I delete metabolites branch?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#319]
In trying to tidy up stale branches, I notice that the "metabolites" branch appears to be obsolete. No checkins in 11 months. 989 commits behind. Apparently nothing ahead:
https://github.com/RTXteam/RTX/branches
Any objections to me blowing away this branch? Appears to be obsolete.

**Comment by saramsey** [comment]
@DeqingQu do we still need this branch?

**Comment by DeqingQu** [comment]
Yes, I think it can be deleted.

**Comment by edeutsch** [comment]
okay, I will delete the metabolites branch then!

**Comment by edeutsch** [comment]
done
