### ISSUE TITLE
Why does BuildMasterKG.py use so much memory?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#32]
Is it possibly a requests-cache memory leak?

https://github.com/requests/requests/issues/1685

**Comment by finnagin** [comment]
For reference:
requests-cache==0.4.13
sqlite3==2.6.0

**Comment by saramsey** [comment]
Thanks, Finn.  This might be "normal" in-memory footprint for a SQLite3 database with a 63 GB (on-disk) data store, IDK.  It would be great if SQLite had some kind of tuning parameter or PRAGMA directive to restrict its in-memory footprint.  Maybe this page has some config options?
https://www.sqlite.org/malloc.html

**Comment by dkoslicki** [comment]
Closing due to #788
