### ISSUE TITLE
Improvements to KG node and edge attributes

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#321]
Since I am in the thick of mapping KG node and edge attributes to the latest API, I thought I'd point out a few opportunities for improvement for KG2. The API attributes:
https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI/tree/master/API

In node:
- What we call `category` is `type` in the API. I assume we don't want to switch that this point.
- Are there ever extra properties on the nodes that I should handle?

In edge:
- The following properties are missing (at least for the edges that I saw; do some have it where appropriate?)
* defined_datetime
* weight
* publications
* evidence_type
* qualifiers
* negated
- There is also a slot for extra edge properties. Should I be looking for these?
- Also, there is an edge properties call `predicate`. I don't know what to do with that one. There appears to be no place in the API attributes to put it

**Comment by saramsey** [comment]
Hmm, AFAIK, in the BioLink standard for the KG, it is called `category`:

![Screen Shot 2019-04-18 at 9 05 24 AM](https://user-images.githubusercontent.com/5562107/56374943-2048d980-61b9-11e9-8812-60314d5e7f2a.png)

**Comment by edeutsch** [comment]
ah yes, you're quite right.
I compared the other fields now as well to NamedThing, and the comparison isn't too favorable.
uri vs iri
symbol
synonym
Is there a thought to try to implement synonym?

**Comment by saramsey** [comment]
yes I have synonyms in `kg2`:

![Screen Shot 2019-06-13 at 10 08 02 AM](https://user-images.githubusercontent.com/5562107/59452694-2925e800-8dc3-11e9-8727-7bcb134509d3.png)
