### ISSUE TITLE
please check RTX2 KG

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#323]
Hi @dkoslicki we (thanks @DeqingQu ) have a new build of the KG. Can you please take a look?  Thanks

bolt://rtx.ncats.io:7787

**Comment by dkoslicki** [comment]
It seems to be in order, though APOC is not installed (which I use to do a number of tests). Note that the orphaned nodes issue #296 appears to still be an issue (though nominal improvements have been made).

It appears that a few more nodes and edges have been added (~4k more nodes, ~10k more edges).

**Comment by edeutsch** [comment]
I thought there were supposed to be 100s of thousands more nodes? and millions more edges?

**Comment by dkoslicki** [comment]
@saramsey @DeqingQu I'm a bit confused as well: is this KG the ETL KG mentioned in #301 ?

**Comment by DeqingQu** [comment]
@dkoslicki  This KG is built using web-crawling, not ETL.

**Comment by DeqingQu** [comment]
@dkoslicki APOC is installed on rtx2 now. The APOC plugin file is 'apoc-3.2.3.6-all.jar' (same as rtx1)

**Comment by dkoslicki** [comment]
Thanks @DeqingQu! It's awesome to note that we now have ``positively/negatively_regulates`` for edges between drugs and proteins!
