### ISSUE TITLE
move docker to /mnt/docker on rtx.ncats.io

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#324]
Hi @DeqingQu,

Can you please look at the Docker documentation to determine exactly what steps it would take to move Docker to a new file system, on Debian?

At this point I would just like to have a written list of steps in the procedure that we can study; I don't want to actually execute the procedure yet.

Thanks,
Steve

**Comment by saramsey** [comment]
OK, on rtx.ncats.io, I have made an ext4 file system in /dev/xvdh and mounted it as /mnt/docker.

**Comment by DeqingQu** [comment]
\# check all running containers
docker ps

\# stop service on rtx1 and rtx2
docker exec rtx1 service apache2 stop
docker exec rtx2 service apache2 stop
docker exec rtx1 service RTX_OpenAPI_production stop
docker exec rtx2 service RTX_OpenAPI_production stop
docker exec rtx1 service mysql stop
docker exec rtx2 service mysql stop
docker exec rtx1 service neo4j stop
docker exec rtx2 service neo4j stop

\# stop all containers
docker stop $(docker ps -aq)

\# stop the docker daemon
service docker stop

\# copy data to /mnt/dockder, and rename the original /var/lib/docker
cp -r /var/lib/docker/* /mtn/docker  
mv /var/lib/docker{,.bak}

\# link the old filesystem
ln -s /mtn/docker /var/lib/docker

\# start the docker daemon
service docker start

\# restart the rtx1 and rtx2
docker run -it rtx1:version1 /bin/bash
docker run -it rtx2:version2 /bin/bash

\# restart the service on rtx1 and rtx2
docker exec rtx1 service apache2 start
docker exec rtx2 service apache2 start
docker exec rtx1 service RTX_OpenAPI_production start
docker exec rtx2 service RTX_OpenAPI_production start
docker exec rtx1 service mysql start
docker exec rtx2 service mysql start
docker exec rtx1 service neo4j start
docker exec rtx2 service neo4j start

\# if everything works fine, we can delete the /var/lib/docker.bak to save space
rm -r /var/lib/docker.bak

**Comment by saramsey** [comment]
Hi Steve,

I made some changes of the steps (https://github.com/RTXteam/RTX/issues/324) to move Docker to a new file system. I have done some tests on the new EC2 instance and the steps I posted on Github work fine. I think we can shut down the test instance now (the docker containers and the service docker have been stopped).

Here are what I did in the tests:
1. Install Docker on the EC2 instance
2. Pull two different images ubuntu:18.04 and ubuntu:16.04
3. Run two containers with the two images
4. Modify some files on the two containers
5. Follow the steps to move the docker folder to a new folder (/mnt/docker)
6. Restart the docker containers and check the modified files in containers (the files are modified as I expected)

Best Regards,
Deqing Qu

**Comment by saramsey** [comment]
Current plan is to do this maintenance work on rtx.ncats.io on Monday April 29 in the afternoon.

**Comment by edeutsch** [comment]
What is the current plan with this maintenance? Would you keep us up to date on development with this?

**Comment by DeqingQu** [comment]
Hi all,

I am going to start the maintenance event 30 minutes later. The maintenance event will last in 2 hours. So our websites will be out of work from 4:30 PM to 6:30 PM.

If you have any task needs in that time period, please let me know.

**Comment by edeutsch** [comment]
Great, this is good for me. I just synced the latest code from master into NewFmt and rolled out NewFmt to /devED and to /beta. It all seems to be stable and functioning fine. I am stopping work on this now and hope to see it all working fine on the other side of the maintenance. I think I have logged out of all my sessions, but if any remain open, they can be killed.
thanks!

**Comment by edeutsch** [comment]
So what is the state of the system? Is it ready to bring all services back up?

**Comment by edeutsch** [comment]
Looks like the mission had to be aborted? but is it safe to start all the RTX services again?

**Comment by DeqingQu** [comment]
Some problems occurred in the maintenance process. MySQL and Neo4j could not startup as I expected. The service RTX_OpenAPI_production has been started on the rtx1 container. Other RTX services should be safe to start.

**Comment by edeutsch** [comment]
I have started all other services so everything is back up. What's the plan going forward?

**Comment by DeqingQu** [comment]
I will reproduce the error in the test environment and find how to fix it. Then we could schedule another time for the maintenance.

**Comment by DeqingQu** [comment]
I have fixed the error on the test EC2 instance. The start error of MySQL and Neo4j is caused by user permission. For example, when Neo4j is started, it needs permission to create a temporary folder in /var/lib/mysql and to write the log file /var/log/mysql/error.log. If the ‘-p’ option is added to the cp command, the mode, ownership, and timestamps of the folders and files will be preserved. After the ‘-p’ option is added, all services in the containers can be started as I expected.

Should we schedule a time to continue the maintenance?

**Comment by edeutsch** [comment]
great, thanks. Thursday after 10am is fine with me. Need to avoid the mini-hackathon on Friday.

**Comment by DeqingQu** [comment]
Ok, I will start the maintenance after 10am tomorrow.

**Comment by DeqingQu** [comment]
I will start the maintenance after 15 mins.

**Comment by DeqingQu** [comment]
The maintenance is starting now. Planning to be done in 1 hour.

**Comment by DeqingQu** [comment]
All done. RTX_OpenAPI_production and RTX_OpenAPI_devED have been started on rtx1. Please check the services.

The original docker folder is moved to /mnt/docker/container_backup/docker.bak. The original rtx1 and rtx2 container are exported in /mnt/docker/container_backup/ folder. 

The available space on the root file system is 15G now.

**Comment by edeutsch** [comment]
Great, thanks, I have started all other services.

**Comment by saramsey** [comment]
rtx.ncats.io is looking like it is working now.  /mnt/docker has 87% free space. root file system has 74% free space. closing out issue
