### ISSUE TITLE
Neo4j algorithms library

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#325]
It looks like APOC has depreciated a bunch of their graph algorithms and have moved (and expanded) them to [noe4j-graph-algorithms](https://github.com/neo4j-contrib/neo4j-graph-algorithms). There are a few additions there that would significantly improve our run time (eg. [Jaccard index](https://neo4j.com/docs/graph-algorithms/current/algorithms/similarity-jaccard/)), as well as new algorithms that would be interesting to try on our KG.

I propose that we look into [installing this](https://github.com/neo4j-contrib/neo4j-graph-algorithms#installation).

@finnagin I suggested you as you got APOC working in the first place, but let me know if you need someone else to look into this.

**Comment by finnagin** [comment]
@dkoslicki I read into this a bit over the weekend and it looks like with our version of neo4j (3.2.6) we can only install an earlier version of this plugin according to their versions page (https://github.com/neo4j-contrib/neo4j-graph-algorithms/blob/master/versions.json). Unfortunately, it looks like jaccard index algorithm was added in 3.4.7.0 (https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases/tag/3.4.7.0) which means according to the version link we would have to update neo4j to at least version 3.4.4 before we can get that functionality.

**Comment by saramsey** [comment]
kg2endpoint2.rtx.ai is running neo4j version 3.5.11.

**Comment by finnagin** [comment]
This is currently running in kg2endpoint2 so I think this is safe to close now.
