### ISSUE TITLE
Entire metagraph?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#327]
Hi everyone, one item from the follow up from the Monday call is the need to have an endpoint that exports a metagraph for our whole KG. What I need is a dict where each key is a node type that we have in the KG (all of them). Then each value for each key within that dict is a dict of all the node types that the level 1 node type can connect to. Then the value of the level 2 dict is an array of all of the edge types that connect that pair of node types.

Is there something in ReasoningUtilities.py that already does that? If not, can an enterprising individual write the cypher for that and put it in the function in ReasoningUtilities.py? (ideally in NewFmt branch)

thanks!
Eric

**Comment by saramsey** [comment]
Isn't it something like apoc.meta.graph?

**Comment by dkoslicki** [comment]
Yes, apoc.meta.graph is the trick. Then just delete the "base" node. It'll need a touch of format conversion to fit Steve's spec, but should be quite straightforward.

Sent from my mobile device, please excuse my brevity and/or typos

________________________________

**Comment by edeutsch** [comment]
Essentially we need to mimic this:
http://robokop.renci.org:6010/api/predicates

**Comment by edeutsch** [comment]
So can I just send that string as the query? i.e.:
	query = "apoc.meta.graph"
	with driver.session() as session:
		res = session.run(query)

**Comment by edeutsch** [comment]
Apparently not..
neobolt.exceptions.CypherSyntaxError: Invalid input 'a': expected <init> (line 1, column 1 (offset: 0))
"apoc.meta.graph"
 ^

**Comment by edeutsch** [comment]
hmm, I think I've figured this out, thanks
