### ISSUE TITLE
Not many diseases have phenotypes attached, many are orphaned

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#328]
It looks like about half of diseases have phenotypes attached to them:
```
match (n:disease) return count(distinct n)
```
19573 diseases. Yet
```
match (n:disease)-[]-(:phenotypic_feature) return count(distinct n)
```
9952 have phenotypes connected to them.

In fact, 5783 of them are _completely orphaned_ (i.e. no connections at all)
```
match (n:disease) where not (n)-[]-() return count(distinct n)
```
Maybe this will be addressed with #301?

**Comment by saramsey** [comment]
to be fixed in KG2

**Comment by dkoslicki** [comment]
Now, for `match (n:disease)-[]-(:phenotypic_feature) return count(distinct n)`
KG1: 9,968, KG2: 31,896
closing
