### ISSUE TITLE
OMIM disabling non-SSL access to their API in Nov. 2019

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#329]
We are contacting our API users to let them know that we will be turning off non-SSL access to the OMIM API on November 15th, 2019. 

If you are accessing the OMIM API using 'http://api.omim.org/api/...' you should switch to 'https://api.omim.org/api/...' as soon as possible.

If you are already using 'https://api.omim.org/api/...' then you don't need to take any action.

Best regards

OMIM

**Comment by DeqingQu** [comment]
We are using the SSL version, so I think we are fine.
