### ISSUE TITLE
Add CSV parser to SemDB 

### ISSUE THREAD

**Issue by power10dan** [RTXteam/RTX#335]
We will need a CSV parser to be able to convert and parse data from SemDB to Neo4J. The data from SemDB is in the form of a CSV file. Because the current RTX algorithm doesn't have the ability to parse CSV files and feed it to Neo4J, it would be a nice enhancement if we do.

**Comment by saramsey** [comment]
This might be doable with additional function(s) added to `build_kg2.py`. Maybe we can have `owl-load-inventory.yaml` generalized to `ks-file-load-inventory.yaml` and we can make `XXX.csv` an allowed filetype. And maybe we can make `build_kg2.py` (after it finishes building the OWL-based KG) call a new function to parse each CSV input file (of triples) and merge the triples into the KG before exporting `kg2.json`.

**Comment by power10dan** [comment]
I think that's a good start for approaching this problem. One thing that I am concerned about would be how big the CSV is, and how much merging to we need to do. From my understanding, 11 million relationships is a lot, and merging the data might require carefully thought-out algorithm in order to make sure that it doesn't break the current dependencies on the graph and be efficient. 

So my idea is quite similar to yours, but I think that we should, instead of simply do a direct merge to the graph, keep tab on a separate DB or data structure or anything a list of nodes and relationships, and then update the nodes that needs to be updated with the introduction to the CSV file. This prevents us from directly merging all possible data in the CSV with all possible relationships in the graph. Further, this is much easier to verify for correctness during testing phase, as we do have a graph's previous state, and be able to quickly identify mistakes caused by the merge.

**Comment by saramsey** [comment]
this is done (at least a first version); see `semmeddb_mysql_to_json.py`
