### ISSUE TITLE
Report Summary Statistics of the Graph

### ISSUE THREAD

**Issue by power10dan** [RTXteam/RTX#336]
This issue is related to adding new features into the RTX. We would like to have a function that is able to summarize how many nodes and edges there are in Neo4J,  the nodes' semantic types and the types of each edges connecting them, and a customized diff function that we are able to run should we update the graph.

**Comment by saramsey** [comment]
This could be a script that operates on `kg2.json`. Want statistics on:
(1) number of nodes by CURIE prefix
(2) number of nodes by provid3r
(3) number of relationships by predicate
(4) number of relationships by provider
etc...

**Comment by power10dan** [comment]
I agree. It could be as simple as that, which I think would be a great project for beginners just
starting out on this project  :-)

**Comment by saramsey** [comment]
see script `report_stats_on_kg.py` that I just checked into the repo

**Comment by saramsey** [comment]
done; see `report_stats_on_kg.py`
