### ISSUE TITLE
Customized Diff. Function for 2 KG graphs 

### ISSUE THREAD

**Issue by power10dan** [RTXteam/RTX#337]
Given two KG graphs, we want a function to be able to generate the differences between them and output to a log file. This diff. must include differences in nodes and edges between two graphs. The results of the function should be outputted to a log file.

**Comment by saramsey** [comment]
I think @dkoslicki implemented something very much like this at the last hackathon (right, David?). That would be a starting point for discussion of this issue.  Actually if we output pretty-printed (and ordered) `kg2.json`, wouldn't an ordinary Unix `diff` satisfy this requirement?

**Comment by power10dan** [comment]
We can definitely use diff; I think it's the simplest way to go. One thing that I am thinking about is what are the specific requirements of this "diff" function? Do users want to run custom query diffs comparing the two graphs? (e.g How many types of mutations does gene 1 in KG1 have versus in KG2?) If we simply just use a diff function, it won't allow us to run such complicated query. I brought this up because I am thinking that users might want to answer specific research questions using the differences of the same graph. In fact, the differences might even yield something interesting. 

I wrote this requirements really generally based on our discussion from last week. Again, this really depends on the requirements that the you guys want out of this diff. Further, I think discussing about what types of research questions / functionalities / user story  this diff is designed to achieve (besides telling the differences of two graphs) would be extremely helpful (e.g. As a doctor, I want to use the diff function to see how does the KG graph change after a new breaking study have been published in SemDB).

**Comment by saramsey** [comment]
sounds like @dkoslicki has code for this
