### ISSUE TITLE
drug or chemical_substance?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#339]
Back in the beginning we had drugs. Then the Lord said Thou shalt use chemical_substance. And we switched to chemical_substance.. And it was good. And then the Lord said, oh wait, drug would be okay, too, see:
https://biolink.github.io/biolink-model/docs/Drug.html.

What will we use for drugs in in KG2: drug or chemical_substance?

**Comment by saramsey** [comment]
OK, I guess we will use both. "drug" where it is sensible to do so, and "chemical substance" for things like 'ispropanol' where it is not really sensible to call it a drug.
