### ISSUE TITLE
When should NewFmt be merged into master?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#360]
Hi everyone, /beta and /devED are running branch NewFmt and are functional and stable and using the new password system.

Production and /test are running master and are functional and stable using the new password system

rtx.ncats.io/legacy is running master and is functional and stable using the new password system.

I propose to merge NewFmt into master and roll this out to /test and then to production. This should be functional and stable, but not feature complete. A few features will be available only in /legacy until we finish porting all desirable features to master.

Comments? concerns? Shall I do this merge and roll out this week yet? or wait until next week? (I will be away traveling next Monday through Thursday, so it could happen this Friday or next Friday). Preferences?

**Comment by edeutsch** [comment]
Hi everyone, I have not yet carried out my threat to merge NewFmt into master. But today I sync'ed master into NewFmt, tested, and everything seemed fine. I then deployed NewFmt to /test and production, and tested and it all seems good.

So, the major change is that we are now running API 0.9.1 and the latest code, including the QueryGraphReasoner in production.

/legacy is still available running API 0.8.0. And a few queries like Q1 and Q2 are only functional under legacy for now.

The next step is to fully merge NewFmt into master in GitHub and stop using the branch NewFmt. Anything holding me back?

**Comment by dkoslicki** [comment]
Closing due to #788
