### ISSUE TITLE
need a method to convert MeSH tree number to MeSH UID

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#38]
see issue #22 for the back-story

**Comment by saramsey** [comment]
maybe this can be done with the NCBI eUtils API?

**Comment by saramsey** [comment]
Link to the fine manual here:

https://www.ncbi.nlm.nih.gov/books/NBK25501/

**Comment by finnagin** [comment]
It looks like it can be done using NCBI eUtils. From the [mesh tree structure](https://www.nlm.nih.gov/mesh/intro_trees.html) page Congenital Abnormalities is listed with with the id C16.131.

If we then search this using esearch,fcgi we get the [following result.](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=mesh&term=C16.131&retmode=json&retmax=1000) And if we search the resulting mesh id using esummary.fcgi we can see that this is this is indeed [congenital abnormalities.](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=mesh&id=68000013&retmode=json&retmax=1000)

**Comment by saramsey** [comment]
nice, thanks Finn.  can you expose this as a new method in QueryNCBIeUtils.py ?

**Comment by finnagin** [comment]
Actually looking at the method `get_mesh_uids_for_mesh_term` it looks like this method already doing what I described above so I think if we just plug the tree number into that it will work. I'll test on a few mesh tree numbers and report back.

**Comment by finnagin** [comment]
So it almost works. That method adds [MeSH Terms] to the search so it doesn't work for tree numbers but I made a new method that does the same thing without the addition of [MeSH Terms] called `get_mesh_uids_for_mesh_tree` so that should work going forward.

Another thing to consider: This method should work for other searches of the mesh database not just mesh tree numbers so would it be better to call it something like `get_mesh_uids_for_mesh_query` instead?

**Comment by saramsey** [comment]
OK, but generally I prefer a method being explicit about what are the allowed identifier types that can be passed.

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Mar 27, 2018, at 1:04 PM, Finn Womack <notifications@github.com<mailto:notifications@github.com>> wrote:


So it almost works. That method adds [MeSH Terms] to the search so it doesn't work for tree numbers but I made a new method that does the same thing without the addition of [MeSH Terms] called get_mesh_uids_for_mesh_tree so that should work going forward.

Another thing to consider: This method should work for other searches of the mesh database not just mesh tree numbers so would it be better to call it something like get_mesh_uids_for_mesh_query instead?

**Comment by saramsey** [comment]
excellent

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Mar 27, 2018, at 11:39 AM, Finn Womack <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually looking at the method get_mesh_uids_for_mesh_term it looks like this method already doing what I described above so I think if we just plug the tree number into that it will work. I'll test on a few mesh tree numbers and report back.

**Comment by dkoslicki** [comment]
@finnagin What's the status of this issue? Has the new code been implemented and thoroughly tested?

**Comment by finnagin** [comment]
New code has been implemented but has only had limited testing. I can test it some more I'll just need to generate a list of mesh tree numbers to try. 

@dkoslicki Are there any tree numbers that I should try to make sure that they work or should I just find some tree numbers arbitrarily from the mesh website?

**Comment by dkoslicki** [comment]
If I recall correctly, one of the get_mesh functions in QueryNCBIeUtils was returning MeSH tree numbers (for anatomy and/or phenotypes). You might try there for testing (but just some from the website should work too). After you run a few more tests, you can go ahead and close this issue.

**Comment by finnagin** [comment]
I did more testing and every example I tried worked so I'm going to go ahead and close this issue.
