### ISSUE TITLE
Clean up stale branches before Deqing departs?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#392]
Hi, do we want to resolve and delete branches before @DeqingQu departs? I notice that branch `issue305` is 2 commits ahead of master and branch `metagraph` is 5 commits ahead of master. What should be done with those?

**Comment by saramsey** [comment]
I've asked Deqing.

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org


On Jun 18, 2019, at 4:22 PM, Eric Deutsch <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, do we want to resolve and delete branches before @DeqingQu<https://github.com/DeqingQu> departs? I notice that branch issue305 is 2 commits ahead of master and branch metagraph is 5 commits ahead of master. What should be done with those?

**Comment by DeqingQu** [comment]
Thank you, Steve. I will check this issue tonight and let you know.

**Comment by edeutsch** [comment]
And make a list of other loose ends? Shall we still change all the passwords this week?

**Comment by DeqingQu** [comment]
I have checked the branch 'issue305' and the branch 'metagraph'. Both branches can be deleted.

I am very glad to schedule a time to change the passwords this week. :-)

**Comment by saramsey** [comment]
Thank you, @DeqingQu . That would be great if you could help with the password change.  Someone else on the team can handle deleting the branches.

**Comment by saramsey** [comment]
OK, I have deleted the "issue305" and "metagraph" branches.

![Screen Shot 2019-06-19 at 8 58 37 AM](https://user-images.githubusercontent.com/5562107/59781325-71845080-9270-11e9-960b-e67eefe2be06.png)
