### ISSUE TITLE
add MeSH definitions into the knowledge graph

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#4]
_From @saramsey on January 9, 2018 22:32_

_Copied from original issue: dkoslicki/NCATS#132_

**Comment by dkoslicki** [comment]
@edeutsch @edeutsch  Did we want to pursue this issue anymore? The rational IIRC was so that the "description" field of the output format could be filled by using a call to the KG. But in light of #59, ``KG "description" => reasoner output "name" (except for proteins, where it maps to output."symbol")`` it appears we aren't going this way anymore...

**Comment by edeutsch** [comment]
@dkoslicki @saramsey : I think this is very much relevant. Maybe we need to discuss further, but in my view, in both the KG and the API we should do this:
"name" should be the full English name of the entity
"symbol" should be a suitable abbreviation if there is one
"description" should be 1-3 sentences of description/definition of the entity

**Comment by saramsey** [comment]
@edeutsch Looks good....If that is the "node property standard" that the KG Standardization group chooses, my team will be happy to implement it. I'm also happy to suggest this to the KG standardization group. 

Having said that, if the KG standardization group chooses something different, then I think we should implement the standard, even if we don't like it (provided we can still work with it).

**Comment by edeutsch** [comment]
ah well, you're right, I was forgetting the KG standard. Does the current KG standard specify this level of detail or what does it say?

**Comment by dkoslicki** [comment]
Alternatively, we could always add a new property to nodes (say ``mesh_description``) as the standard is just a minimal standard. Imo, having some sort of 1-2 sentence natural language description would be a nice thing to have in the KG standard.

**Comment by dkoslicki** [comment]
Close due to #788
