### ISSUE TITLE
Errant debug statements

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#40]
QueryNCBIeUtils is printing out a list of ints, causing problems with the JSON parsing of QXSolution.

**Comment by dkoslicki** [comment]
@finnagin and @saramsey Just as a case in point for the dangers of leaving debug commands in main (see the now fixed [#40](https://github.com/RTXteam/RTX/issues/40) problem).

**Comment by saramsey** [comment]
Thanks for the heads-up, and for pushing a fix
