### ISSUE TITLE
rename `multi_owl_to_kg.py` to a name that is less confusing

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#400]
since the script also reads Turtle files, should probably rename it to something less confusing

(this is a placeholder issue; will probably fix this after the September hackathon)

**Comment by dkoslicki** [comment]
Closing due to #788 Unless @saramsey objects

**Comment by saramsey** [comment]
still intending to do this, but given its low priority, haven't gotten to it yet

**Comment by saramsey** [comment]
Coded. Just need to test in the next KG2 build.
