### ISSUE TITLE
make sure that protein, gene, and RNA nodes have 'organism' property defined

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#405]

**Comment by saramsey** [comment]
need to assess the probability that absence of this property information would lead to incorrect query results for the main types of path-based queries that we do @dkoslicki

**Comment by saramsey** [comment]
@dkoslicki says that the organism may be inferrable from information in edges connecting a gene

**Comment by dkoslicki** [comment]
Close due to #788?

**Comment by saramsey** [comment]
seems to be no required node property called `organism` in the current biolink model

**Comment by saramsey** [comment]
it looks like there should be an association between the Gene object and an OrganismTaxon object,
see this page on the Biolink Model website:

https://biolink.github.io/biolink-model/docs/Gene.html

**Comment by saramsey** [comment]
already doing this with the `in_taxon` biolink edge

https://biolink.github.io/biolink-model/docs/in_taxon.html
