### ISSUE TITLE
HTTP responses potentially mess up output format?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#42]
@edeutsch @saramsey I've noticed that we occasionally get the following printed out to screen when using ``QueryNCBIeUtils``:
```
HTTP response status code: 502 for URL:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=%28Van%20Buchem%20disease%20type%202%29%20AND%20%28Osteoporosis%5BMeSH%20Terms%5D%29&retmode=json&retmax=1000
```
This does not necessarily mean that the ``QXSolution.py`` will fail (since I will just then put in the max google distance), but I imagine that having something besides the JSON formatted response printed may mess up the UI/API. Will this be an issue? I don't know if requests is using stdout or stderr to print these as I'm not familiar with the requests package.

**Comment by dkoslicki** [comment]
Btw, those sorts of HTTP responses happen periodically for well-formed queries (I haven't been able to come up with a MWE), it seems to just be the NCBI's eutils isn't the most reliable.

**Comment by saramsey** [comment]
This is being printed to STDERR, which I think is a reasonable use of STDERR.  Nothing should be scraping STDERR looking for structured output.  Of course we could use a logging system but I preferred not to couple the QueryXXXXXX.py modules to some logging system unless we have a good reason why printing to STDERR is not working.

**Comment by saramsey** [comment]
It's also possible that the issue isn't on the e-Utilities service per se, it could be some networking issue in between us and them.

**Comment by dkoslicki** [comment]
Ok, since I'm pretty sure that Eric is only ever using stdout, I'll mark this as closed.
