### ISSUE TITLE
mysql issue when running snakemake build of KG2

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#432]
Hi Steve,
I wanted to let you know that kg2ase.rtx.ai has a mysql bug again. Semmed tried to run first, and after it failed, I tried the steps you sent last time. Then ChemBL failed, and I deleted the chembl database. Then UMLS failed, which is making me suspect that there is an issue with MySQL. Let me know if you have any suggestions. I am turning off the instance for now.

UMLS Output:
```
./populate_mysql_db_configured.sh: 80: exit: Illegal number: -1
```

ChemBL Output:
```
ERROR 1050 (42S01) at line 25: Table '`chembl`.`action_type`' already exists
```

SemmedDB Output:
```
ERROR 1030 (HY000) at line 25: Got error 168 from storage engine
```
Thank you,
Erica Wood

**Comment by saramsey** [comment]
This may be relevant, recording for future reference:
https://stackoverflow.com/questions/12196996/mysql-error-dropping-database-errno-13-errno-17-errno-39

**Comment by saramsey** [comment]
@BluePiggy49  is this issue resolved, do you think?

**Comment by BluePiggy49** [comment]
This is resolved
