### ISSUE TITLE
port umls2rdf to python3

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#435]
python2.7 EOL is January 1, 2020.
https://www.anaconda.com/end-of-life-eol-for-python-2-7-is-coming-are-you-ready/

**Comment by saramsey** [comment]
@BluePiggy49 is working on this issue

**Comment by saramsey** [comment]
@BluePiggy49 is this issue done?  Can we close it out?

**Comment by BluePiggy49** [comment]
The python 2 and python 3 json files have been created on kg2dev.rtx.ai. I am comparing them now.

**Comment by saramsey** [comment]
The python3 version of `umls2rdf.py` is in the branch `python3` in the `RTXTeam` forked repo of `umls2rdf`:

https://github.com/RTXteam/umls2rdf/tree/python3

**Comment by dkoslicki** [comment]
@saramsey close due to #788?

**Comment by saramsey** [comment]
keep open; @ericawood is back this summer so we'll get this issue closed this summer

**Comment by saramsey** [comment]
Just an FYI, I am working on this issue.

**Comment by saramsey** [comment]
the code changes to actually use version 2.0 of `umls2rdf` are in the `kg2-curie-refactoring` branch
