### ISSUE TITLE
ETL DrugBank into KG2

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#436]
Start with the XML download:
https://www.drugbank.ca/releases/latest

Team Alpha has requested this.

**Comment by saramsey** [comment]
Marcin Joacimiak has expressed interest in an ETL script (or service) for DrugBank, as well.

**Comment by saramsey** [comment]
From Sebastian Paz Vivas at DrugBank:

> Yes, the free database will come in XML format. In it, each drug card is interconnected with DB ids and external IDs. I am sending the documentation of the XML format here for you to take a look at to see what it looks like. https://docs.drugbankplus.com/xml/
> 
> Additionally, we have a small tool that you might find useful called Advanced Search. If you have an approved academic account with us then you can also export the results from the search.
>

**Comment by dkoslicki** [comment]
Close due to #788 and this perhaps already being accomplished in current KG2?
