### ISSUE TITLE
Script that can generate a report based on KG2 in Neo4j

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#438]
@veronicaflores this GitHub issue is just to track code commits (etc.) pertaining to the reporting script that you are working on.

**Comment by saramsey** [comment]
just need to automate the running of this script and the copying of the results to S3

**Comment by saramsey** [comment]
hmm let's add code to `tsv-to-neo4j.sh to run this procedure

**Comment by dkoslicki** [comment]
Closing due to #788

**Comment by dkoslicki** [comment]
@saramsey FYI @veronicaflores got auto-unassigned by github when I closed it, so feel free re-assign if necessary/desired.

**Comment by saramsey** [comment]
The script is called `report_stats_on_neo4j_kg.py`. It exists, but needs to be tested since it hasn't been run in about 11 months, and KG2 has changed substantially.

**Comment by saramsey** [comment]
> @saramsey FYI @veronicaflores got auto-unassigned by github when I closed it, so feel free re-assign if necessary/desired.

Thanks for the heads-up.

I am in communication with @veronicaflores discussing possible work on KG2 this summer
