### ISSUE TITLE
reset Neo4j and Mysql passwords on all X-ray systems

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#439]
OK, our Neo4j and Myslq password has been the same since forever, and it is compromised by being in our GitHub codebase.

So now that we have deployed Deqing's module for dynamically retrieving database authentication credentials (#252), we should change our database passwords.

Let's do this after the hackathon, and after Luis & Eric return from Australia.

EWD says that the three of us (EWD, SAR, FW) should have point on managing this password change's effect on the production system. But I am including @isbluis and @dkoslicki as an FYI so they can be in the loop.

**Comment by BluePiggy49** [comment]
I was not intending to reference this issue in that commit, and amended it to say #349.

**Comment by dkoslicki** [comment]
@saramsey @edeutsch we still haven’t changed passwords, so I won’t close this per #788

**Comment by saramsey** [comment]
just need to look at the `config.json` file to enumerate all databases that need to have their passwords changed; @edeutsch confirms that we will need to change the password for the mysql feedback database

**Comment by saramsey** [comment]
@finnagin reports that there were no issues at the time that the mini-hackathon adjourned, so I am closing out this issue
