### ISSUE TITLE
link to orphanet ORDO ontology is failing

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#447]
reported by @BluePiggy49 

> Hi Steve,
> The snakemake file ran overnight and hit an error this morning in build-multi-owl-kg.sh. I've attached a screen shot with part of the error message. (It is so long, I wasn't able to go up far enough into the screen -r to see it all.) Let me know if you have any questions or suggestions.
> 
> Thank you,
> Erica Wood

**Comment by BluePiggy49** [comment]
The script failed again with the same error.

**Comment by saramsey** [comment]
I see that you reopened the issue; did the bug come back?
