### ISSUE TITLE
Need to get restatedQuestion returned from translate()

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#45]
@dkoslicki In order for the restatedQuestion to be properly filled in for query results, the translate() function needs to return that information. It did under the old system, but no longer does.
The relevant code is line 669 or search for FIXME

I can't figure out how to get the restated question into that slot. Would you fix that?
do git pull in NewStdAPI first.

**Comment by dkoslicki** [comment]
Fixed: fc77d68ede4c0a5070d2775140bb5f88c3b0e174
