### ISSUE TITLE
KG1 to KG2 has predicate field

### ISSUE THREAD

**Issue by BluePiggy49** [RTXteam/RTX#450]

**Comment by BluePiggy49** [comment]
{
        "edge label": "physically_interacts_with",
        "negated": false,
        "object": "UniProtKB:P00533",
        "predicate": "physically_interacts_with",
        "provided by": "http://pathwaycommons.org/pc11",
        "publications": [],
        "publications info": {},
        "relation": "http://w3id.org/biolink/vocab/PhysicallyInteractsWith",
        "relation curie": "BioLink:physically_interacts_with",
        "subject": "UniProtKB:P53350",
        "update date": null
    }

**Comment by BluePiggy49** [comment]
There is also an odd probability field:

{
        "edge label": "targets",
        "negated": false,
        "object": "CHEMBL.COMPOUND:CHEMBL636",
        "predicate": "physically_interacts_with",
        "probability":

**Comment by saramsey** [comment]
testing my code change now, on `kg2dev.rtx.ai`

**Comment by saramsey** [comment]
still testing on `kg2dev.rtx.ai` (code crashed due to unrelated issue #452)
