### ISSUE TITLE
semmeddb tuple to edges takes 28 hours to run

### ISSUE THREAD

**Issue by ericawood** [RTXteam/RTX#451]

**Comment by dkoslicki** [comment]
Closing due to #788

**Comment by ericawood** [comment]
Based on the build currently going on on kg2steve, it only takes approximately 732 minutes (about 12 hours) to run. The rest of the 28 hours is spent doing nothing but hanging as it holds onto approximately 59% of the memory on a `r5a.8xlarge` instance. Even when the build is run in parallel, this script is adding an extra 16 hours to the build process.

**Comment by saramsey** [comment]
Excellent detective work!

**Comment by saramsey** [comment]
Bumping the priority level. If we can fix this, this would speed up the build time.

**Comment by saramsey** [comment]
You are correct, it looks like `/home/ubuntu/kg2-build/kg2-semmeddb-edges.json` was written at 08:53 UTC on Aug. 17. Current time in the instance is 20:46 UTC:
<img width="623" alt="Screen Shot 2020-08-17 at 1 49 15 PM" src="https://user-images.githubusercontent.com/5562107/90443051-74efb380-e090-11ea-810d-86320e517778.png">

**Comment by saramsey** [comment]
Hi @ericawood can you take a look at 0834c5c to see if that might help?  First I think it would make sense to run it with `--test` to see if this "fix" has a trivial bug. If not, perhaps we could run it without `--test` to see if it helps?

**Comment by saramsey** [comment]
see also bfce940

**Comment by ericawood** [comment]
Hi @saramsey, I have tested this with test versions of SemMedDB up to 5.7 GB (I put a whole bunch - about 1320 of SemMedDB test files - only 3.9M large - together) and there was no hanging. I'm going to move onto running a partial build on kg2steve.

**Comment by saramsey** [comment]
> Hi @saramsey, I have tested this with test versions of SemMedDB up to 5.7 GB (I put a whole bunch - about 1320 of SemMedDB test files - only 3.9M large - together) and there was no hanging. I'm going to move onto running a partial build on kg2steve.

Great news!  I assume you  mean you tested 0834c5c and bfce940?

**Comment by ericawood** [comment]
> > Hi @saramsey, I have tested this with test versions of SemMedDB up to 5.7 GB (I put a whole bunch - about 1320 of SemMedDB test files - only 3.9M large - together) and there was no hanging. I'm going to move onto running a partial build on kg2steve.
> 
> Great news! I assume you mean you tested [0834c5c](https://github.com/RTXteam/RTX/commit/0834c5cf7f056a46c57a2ac788a636e585671eb9) and [bfce940](https://github.com/RTXteam/RTX/commit/bfce940cd1245b14e1dd983d9ab7ce186a2b671e)?

Yes, I tested both of those commits.

**Comment by ericawood** [comment]
Data from Partial Build on kg2Steve:
Start of SemMedDB Conversion: Tue Aug 18 19:17:15 2020

Last Modification of kg2-semmeddb-edges.json: 2020-08-19 12:27:34.317697851 +0000

End of SemMedDB Conversion: Wed Aug 19 12:27:34 2020

Total Time: Approximately 17 hours
