### ISSUE TITLE
not all KG2 nodes have a "creation date" field

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#458]

**Comment by saramsey** [comment]
From @BluePiggy49:

> Hi Steve,
> I fixed the missing nodes issue. Not all of the nodes had an update date field, so I made it so if a node is ever missing a field is should have, that field is replaced with a space in the TSV file.......
> 
> Thank you,
> Erica Wood

**Comment by BluePiggy49** [comment]
Correction: the nodes are missing the creation date field

Node Count:  7631118
Update Count:  7631118
Creation Count:  7610280
No Update Date:  0
No Creation Date:  20838

**Comment by saramsey** [comment]
OK, thanks
