### ISSUE TITLE
Remove dependency on mailutils from the snakefile

### ISSUE THREAD

**Issue by BluePiggy49** [RTXteam/RTX#459]

**Comment by saramsey** [comment]
I assume that the dependency on mailutils is to send a notification email, is that right?

If so, I wonder if we should just use SNS. The build system already depends on AWS CLI being installed, so we could just use SNS (which can be configured to send an email) without requiring another package installation that requires manual intervention.

**Comment by BluePiggy49** [comment]
The purpose of mailutils is to send a notification email when it finishes. We could consider using SNS, but it requires an account number and a confirmation email. See: https://docs.aws.amazon.com/cli/latest/userguide/cli-services-sns.html

Once we are finished testing, I am not sure that a notification system is still necessary.

**Comment by saramsey** [comment]
OK, when testing is complete, let's remove the dependency on mailutils.

We can consider the possibility of adding SNS notifications under a separate GitHub issue.

**Comment by saramsey** [comment]
@BluePiggy49  I believe this is done, right? 

OK to close the issue?

**Comment by BluePiggy49** [comment]
Yes, it is completed
