### ISSUE TITLE
Multiple duplicate edges in KG2

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#463]
Examples:
```match p=(:protein)-[r:has_gene_template]-(:gene) return p limit 10```
![graph (2)](https://user-images.githubusercontent.com/6362936/62493363-e8cd5f80-b79e-11e9-9540-376009254479.png)
Only difference between them is the "provided by" link: cl.owl, hp.owl, pr.owl. Maybe combine them and make "provided by" a list?

**Comment by saramsey** [comment]
Can we add this to the agenda for the next X-ray AHM?

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org


On Aug 5, 2019, at 1:35 PM, David Koslicki <notifications@github.com<mailto:notifications@github.com>> wrote:


Examples:
match p=(:protein)-[r:has_gene_template]-(:gene) return p limit 10
[graph (2)]<https://user-images.githubusercontent.com/6362936/62493363-e8cd5f80-b79e-11e9-9540-376009254479.png>
Only difference between them is the "provided by" link: cl.owl, hp.owl, pr.owl. Maybe combine them and make "provided by" a list?

**Comment by dkoslicki** [comment]
Done! With other issues I've found

**Comment by dkoslicki** [comment]
A more extreme example:
```match p=(n:semantic_type{id:"TUI:T130"})-[]-(m:semantic_type{id:"TUI:T120"}) return p``

**Comment by saramsey** [comment]
This is an excellent topic for an in-person discussion. I'm open to providing a condensed (non-multigraph) KG2.

**Comment by saramsey** [comment]
this is causing path combinatoric explosion

**Comment by saramsey** [comment]
see #477 and #476

**Comment by dkoslicki** [comment]
It may be that the sources of all the duplicate edges is constrained to same edges coming from the same ontology, as well as the SemMedDB issue with two edges differing just with pubmed ids:
```
match p=(n)-[r1]-(m) where not n:semantic_type match (n)-[r2]-(m) where r1<>r2 and type(r1)=type(r2) and r1.provided_by<>"https://skr3.nlm.nih.gov/SemMedDB" return p limit 5
```
No results returned after 10min

**Comment by saramsey** [comment]
Seems fixed now?
![Screen Shot 2019-12-17 at 2 09 24 PM](https://user-images.githubusercontent.com/5562107/71038521-dc56fd00-20d6-11ea-8fd2-c351d18a6785.png)
