### ISSUE TITLE
Frequently dropped connection to KG2

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#464]
I've noticed that even with relatively simple queries, KG2 frequently experiences ``ERR_CONNECTION_REFUSED``, ``Neo.TransientError.General.DatabaseUnavailable``, and other such unavailability errors. Any guesses as to what's causing the instability?

**Comment by saramsey** [comment]
@finnagin or @BluePiggy49 maybe someone could check the Neo4j debug.log?

**Comment by saramsey** [comment]
looks like the Neo4j is configured to use all available system RAM, if I understand the config file lines correctly:

```
# calculated based on available system resources.
# Uncomment these lines to set specific initial and maximum
# heap size.
#dbms.memory.heap.initial_size=512m
#dbms.memory.heap.max_size=512m

# The amount of memory to use for mapping the store files, in bytes (or
# kilobytes with the 'k' suffix, megabytes with 'm' and gigabytes with 'g').
# If Neo4j is running on a dedicated server, then it is generally recommended
# to leave about 2-4 gigabytes for the operating system, give the JVM enough
# heap to hold all your transaction state and query context, and then leave the
# rest for the page cache.
# The default page cache memory assumes the machine is dedicated to running
# Neo4j, and is heuristically set to 50% of RAM minus the max Java heap size.
#dbms.memory.pagecache.size=10g
```

**Comment by saramsey** [comment]
Just checking back... is this issue still happening?

**Comment by dkoslicki** [comment]
Not yesterday during the "live coding" time, thankfully. I'll downgrade to "low priority" and will update the issue if it crops back up.

**Comment by saramsey** [comment]
doubled the amount of memory in the Neo4j host AWS instance
