### ISSUE TITLE
Fewer connections (and missing miRNA's) in KG2

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#466]
For some bioentities (such a GLDC, something talked about during one of the calls), there are few edges (and apparently no micro RNAs):

On KG1:
```match p=(n:protein{id:"UniProtKB:P23378"})-[]-(m) return distinct labels(m), count(*) order by count(*) desc```

label|count
-- | --
["Base", "protein"] | 42
["Base", "microRNA"] | 23
["Base", "metabolite"] | 20
["Base", "anatomical_entity"] | 20
["Base", "pathway"] | 12
["Base", "phenotypic_feature"] | 11
["Base", "molecular_function"] | 8
["Base", "biological_process"] | 6
["Base", "cellular_component"] | 6
["Base", "disease"] | 3
total|151

On KG2:

label|count
-- | --
["protein"] | 42
["anatomical_entity"] | 26
["metabolite"] | 20
["biological_process"] | 13
["pathway"] | 11
["phenotypic_feature"] | 6
["named_thing"] | 4
["disease"] | 3
["gene"] | 2
["organism_taxon"] | 1
["information_entity_type"] | 1
total|129

**Comment by dkoslicki** [comment]
Added to the agenda for next week

**Comment by saramsey** [comment]
OK, some HPO terms are not being assigned "phenotypic feature" as their category:

![Screen Shot 2019-09-05 at 12 50 19 PM](https://user-images.githubusercontent.com/5562107/64375871-be5c0580-cfdb-11e9-9118-444d4cb7a842.png)

**Comment by saramsey** [comment]
we should probably revisit this bug and rerun the above Cypher, since there have been so many changes to KG2 since Aug. 2019.

**Comment by dkoslicki** [comment]
Closing due to #788

**Comment by saramsey** [comment]
<img width="831" alt="Screen Shot 2020-07-07 at 5 41 29 PM" src="https://user-images.githubusercontent.com/5562107/86860115-1ab70800-c079-11ea-94b2-32accbdba37d.png">
