### ISSUE TITLE
KG2 has both "drugs" and "chemical_substances", is there a difference?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#468]
```match (n) where n:drug or n:chemical_substance return distinct labels(n), count(*)```

label|count
-- | --
["drug"] | 420934
["chemical_substance"] | 2797284

**Comment by edeutsch** [comment]
I think the consensus in past translator discussions is yes. A drug is probably a chemical_substance with some potential therapeutic value. There's probably a good definition at BioLink. Poisons are probably good examples of chemical_substances that are not drugs. maybe? In any case, we should probably try to make sure that the same entity does not appear both as a drug and a chemical substance. I would argue that the KG2 builds should put all entities that are potentially drugs as a drug and not repeat them as a chemical_substance. But if they don't seem to match the definition of a drug, then just a chemical_substance. So perhaps everything in Chembl might be a chemical_substance unless it also in DrugBank, in which case it should be classified as a drug?

**Comment by saramsey** [comment]
+1 to the definition from @edeutsch:

> A drug is probably a chemical_substance with some potential therapeutic value. 

However, this still leaves open the possibility that some nodes in KG2 are misclassified as "drug" when they should be "chemical_substance". My prior on the probability that some are misclassified , is like 0.999. If any specific examples arise, I will try to accordingly refine the code that I use to assign semantic types.

**Comment by saramsey** [comment]
Leaving this issue open for now, until we have a chance to look at some examples and to discuss.

**Comment by dkoslicki** [comment]
And pertinent to the NCATS call today, many chemical_substances are actually drugs used for treatment. Note that KG2 has many, many more chemical_substances than drugs. Examples following tomorrow.

Sent from my mobile device, please excuse my brevity and/or typos

________________________________

**Comment by dkoslicki** [comment]
Examples of chemical_substances being used as drugs (apparently, according to the last chemistry/drug call):
Sodium Benzoate CUI:C0142805
Imipramine CUI:C0020934
Dextromethorphan CUI:C0011816
etc.

**Comment by saramsey** [comment]
OK, this bug is turning out to be interesting. I am working on a fix....

**Comment by saramsey** [comment]
OK, I think the root cause may be that some UMLS clusters have *multiple* semantic types. For example, consider cluster `C0011816`, which is described in the file `umls-drugbank.ttl` thus:

```
<https://identifiers.org/umls/DRUGBANK/DB00514> a owl:Class ;
        skos:prefLabel """Dextromethorphan"""@en ;
        skos:notation """DB00514"""^^xsd:string ;
        skos:altLabel """Dex"""@en , """DM"""@en , """Dextrométhorphane"""@en , """Dextromethorfan"""@en , """Dextrometorfano"""@en , """D-methorphan"""@en , """(+)-dextromethorphan"""@en , """delta-Methorphan"""@en , """Dextromethorphanum"""@en ;
        <https://identifiers.org/umls/DRUGBANK/SID> """APRD00655"""^^xsd:string ;
        <https://identifiers.org/umls/DRUGBANK/FDA_UNII_CODE> """7355X3ROTS"""^^xsd:string ;
        umls:cui """C0011816"""^^xsd:string ;
        umls:STY """T109"""^^xsd:string ;
        umls:STY """T121"""^^xsd:string ;
        umls:hasSTY <https://identifiers.org/umls/STY/T109> ;
        umls:hasSTY <https://identifiers.org/umls/STY/T121> ;
```

Now, semantic type `T109` is `Organic Chemical` and semantic type `T121 is `Pharmacologic Substance`. In our code, only one of them will win out, depending on the order in which the semantic types appear when we iterate over basic property values.

**Comment by dkoslicki** [comment]
I can see now why Orange team does clique collapsing. A blunt hammer, but at least one way to deal with these multiple labels, identifiers, synonyms, etc.

**Comment by saramsey** [comment]
CUI:C0011816 now shows up correctly as a "drug":

<img width="513" alt="Screen Shot 2019-09-03 at 12 48 04 PM" src="https://user-images.githubusercontent.com/5562107/64203782-16163780-ce49-11e9-92c5-3fcfeeab8cc9.png">
