### ISSUE TITLE
Make a script to build of our standards-compliant RTX KG and publish a gzipped tar archive on the web

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#47]

**Comment by saramsey** [comment]
Steps for the script to perform:
0. generate the neo4j database by running run_build_master_kg.sh
1. use neo4j-admin to dump the database to a file
2. (if the .dump file is compressible), compress it
3. push (using passwordless ssh) the gzipped dump file to a micro EC2 instance that I provide to you 

the script should run on rtxsteve.saramsey.org inside the "kgdump" container.

**Comment by saramsey** [comment]
A few more guidelines:  this script should be committed into the github repo (under "kg-construction") and it should have header comments that clearly explain (1) what the script does; (2) how to run the script; (3) in which docker container it should be run, (4) what EC2 instance it should be run on; (5) what current-working-directory the user should be in when running the script; (6) what user should run the script within the docker container; (7) where (as in which EC2 instance) the script is pushing the dump file to; and (8) the URL for accessing the dump file via HTTP (we are not planning to support HTTPS for web access to the dump file).

**Comment by DeqingQu** [comment]
@saramsey Yes, it is done.

**Comment by saramsey** [comment]
Can you work on issue #49 please?

Sent from my iPhone

On Apr 8, 2018, at 13:31, Deqing Qu <notifications@github.com<mailto:notifications@github.com>> wrote:


@saramsey<https://github.com/saramsey> Yes, it is done.

**Comment by DeqingQu** [comment]
Sure! I will start to work on it tomorrow.
