### ISSUE TITLE
Need Indexes on Relationships

### ISSUE THREAD

**Issue by BluePiggy49** [RTXteam/RTX#471]

**Comment by BluePiggy49** [comment]
Potentially use "db.index.explicit.addRelationship"?

**Comment by BluePiggy49** [comment]
Nevermind, just use create index on like with nodes.

**Comment by BluePiggy49** [comment]
@dkoslicki Which edge properties do you want indexes on?

**Comment by dkoslicki** [comment]
All of them, preferably. Let me know if that would cause some sort of issue wrt space or some other constraint

Sent from my mobile device, please excuse my brevity and/or typos

________________________________

**Comment by BluePiggy49** [comment]
Ok, I have code that will now generate an index on:
- edge label
- negated
- object
- provided by
- publications
- publications info
- relation
- relation curie
- subject
- update date

It will only do it for edges that don't have a ":" in their edge label (CREATE INDEX ON :BFO:0000050 (edge_label) gives an error). I can make these indexes tonight if that is what you would like. @dkoslicki @saramsey

**Comment by dkoslicki** [comment]
No need to create an index for those with ":" on their name (as they will be removed most likely). 
A few more questions:

1. Are those all the edge properties?
2. Can we do the same for node properties? 
3. Let's be sure to preserve the code to do this so we can rerun with futur iterations of the KG.

**Comment by BluePiggy49** [comment]
1. I believe that is all of the edge properties (I was looking at a smaller kg2 json file while I was making the list).
2. I added the other node properties in as well in the latest commit (except id because it has a unique constraint).
3. I committed and pushed my code with the new indexes recently. It is currently partially untested. It will be tested once we regenerate the endpoint.

**Comment by BluePiggy49** [comment]
@dkoslicki @saramsey When would you like me to run the update?

**Comment by dkoslicki** [comment]
@BluePiggy49 Sure, I think running the update would be good. I realize it can't be fully tested before being deployed, but you may try running it on a small, separate instance just so it's "mostly tested" before running on the full KG2.

**Comment by BluePiggy49** [comment]
Ok, I have tested it on a test size graph on my laptop and there were no errors. Please email me if you would like access to the test graph so that you can make that it is correct. @dkoslicki

**Comment by dkoslicki** [comment]
No need to share the test graph. Go ahead and run on the full graph

**Comment by BluePiggy49** [comment]
@dkoslicki I have continued to work with the test graph and all of the indexes. With all of the indexes, neo4j shows as being on, but the cypher shell and neo4j browser are inaccessible. In the case that I have to drop some indexes, which ones are the most important?

**Comment by BluePiggy49** [comment]
On the test graph, I got it to create an index on the following (at the same time):
- category
- category label
- deprecated
- full name
- iri
- name
- provided by
- replaced by
- update date

- edge label
- negated
- object
- provided by
- publications
- publications info
- relation
- relation curie
- subject
- update date

This is everything except description, publications (for nodes), and synonym. What are your thoughts on this? If this is not enough, I will try to make them work for the other ones too. Thank you! @dkoslicki

**Comment by dkoslicki** [comment]
If we index the synonyms, does it do exact matching on the synonym list, or do you know if that speeds up questions like: find me edges/nodes with X in the synonym_list?

**Comment by BluePiggy49** [comment]
@dkoslicki I do not know the answer to that question. I am going to add in the indexes for the others now.

**Comment by saramsey** [comment]
@BluePiggy49 that seems reasonable; we should be able to get clarity on the question of how indexing works on "list" type properties, tomorrow.

**Comment by BluePiggy49** [comment]
@dkoslicki It appears that indexing synonyms would only do exact matches rather than find nodes with a name in the synonym list (at least with the current setup of using cypher's CREATE INDEX ON). See:
https://community.neo4j.com/t/index-on-array/4625
https://community.neo4j.com/t/multi-valued-field-indexing/3873
https://community.neo4j.com/t/most-efficient-way-check-for-value-in-an-array/1045

**Comment by dkoslicki** [comment]
Just FYI @finnagin 
``
EXPLAIN match (n:chemical_substance) where n.id contains "CHEMBL" return n limit 5
``

``Index cannot execute wildcard query efficiently
If the performance of this statement using `CONTAINS` doesn't meet your expectations check out the alternative index-providers, see documentation on index configuration. (index is: index on :chemical_substance(id))
``

**Comment by dkoslicki** [comment]
Note that b-trees may be able to solve the array indexing thing: https://neo4j.com/docs/operations-manual/current/performance/index-configuration/schema-indexes/#index-configuration-index-providers

**Comment by saramsey** [comment]
It appears that property indexes are only possible on nodes, not relationships:
https://neo4j.com/docs/cypher-manual/current/schema/index/#schema-index-create-a-single-property-index

but it might be possible to set up a full-text schema index.
