### ISSUE TITLE
develop a classification system for our 1,100 predicate types in KG2

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#480]

**Comment by saramsey** [comment]
describe the mappings between "edge_label" and "edge_label_simplified" as a set of nodes and relationships in the KG2 Neo4j (it would be a separate connected component from the main KG2)

**Comment by finnagin** [comment]
google sheet for classifying predicates:

https://docs.google.com/spreadsheets/d/18e6H0kV4XHvbe4OIrB1K25W9zKbpqkAwCgPq30oJ5gc/edit?usp=sharing
