### ISSUE TITLE
Node and relationship properties

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#49]
@saramsey Here is a prioritized list of node types and relationship types for which it's desirable to explore what sorts of properties we can pull from various KS's:

Nodes:
1. Anatomy
2. phenotype
3. microRNA
4. pathway
5. protein
6. disease

(source node type, relationship type, target node type):
1. (phenotype, phenotype assoc with, anatomy) example desired property: what sort of association?
2. (phenotype, phenotype assoc with, disease) example desired property: probability/prevalence in population (since some phenotypes seem to be very rare to me and it would be good to have this indicated)
3. (protein, is expressed in, anatomy)
4. (protein, gene assoc with, disease) example desired property: what sort of association is this? What's the strength of the association? 
5. (microRNA, gene assoc with, disease)
6. (microRNA, gene assoc with, phenotype)
7. (microRNA, is expressed in, anatomy)
8. (microRNA, controls expression of, protein) example desired property: what sort of control is exerted? What's the strength?

If for each of these you let me know what sort of data is being returned by the KS, I can take a look and we can pick/choose which properties to include.

**Comment by saramsey** [comment]
@DeqingQu I have assigned this to you.  Tomorrow you and I can discuss how to do this.  Cheers, Steve

**Comment by dkoslicki** [comment]
@DeqingQu Let me know what sorts of properties you find. I'd appreciate a (somewhat exhaustive) list of properties that can be returned through the API calling code Query<DB name>.py. As Steve probably already mentioned, we should start by looking at the API documentation ([such as here](https://www.ebi.ac.uk/chembl/api/data/docs)), and then enumerating the kind of properties that can be had. I am particularly interested in numerical properties.

**Comment by saramsey** [comment]
@dkoslicki Deqing is making process.  The node types that you listed 1-6 are done. Next up is "chemical_substance" and then "biological_process" and then we'll be done with the node types.
Relationship types will be harder.  I propose that we deploy to the rtxdev KG as soon as the node type info is complete, so that you will have something to work with, while we are working on the additional properties for the relationships. Make sense?

**Comment by dkoslicki** [comment]
That sounds like a good plan to me!

**Comment by saramsey** [comment]
closing this issue for now, after conversation with @dkoslicki
