### ISSUE TITLE
Unused node labels

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#492]
There appear to be node labels in the database that aren't actually used for any of the nodes. For example, `access_of` is listed as a node label, but `match (n:access_of) return count(n)` returns `0`.

**Comment by saramsey** [comment]
how to reproduce this issue?  i.e., what cypher command lists all node labels even those not assigned to nodes?

**Comment by saramsey** [comment]
![Uploading Screen Shot 2019-09-03 at 7.01.41 PM.png…]()
