### ISSUE TITLE
set up full-text search index on KG2 Neo4j

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#500]

**Comment by finnagin** [comment]
This query will create a full text index that will apply to all node types and properties:
```
call db.labels() yield label with collect(label) as labels call db.propertyKeys() yield propertyKey with collect(propertyKey) as keys, labels as labels call db.index.fulltext.createNodeIndex("FullTextIndex",labels,keys) return count(*)
```

**Comment by finnagin** [comment]
You can then search it using the following command: (e.g. when looking for malaria)
```
CALL db.index.fulltext.queryNodes("FullTextIndex", "malaria") YIELD node, score RETURN node.name as name, node.id as id, labels(node) as labels, score
```

This will return results sorted by score, The above query gives us the following:


name | id | labels | score
-- | -- | -- | --
"malaria" | "DOID:12365" | ["disease"] | 5.678920745849609
"Malaria, susceptibility to" | "OMIM:611162" | ["phenotypic_feature"] | 4.167004108428955
"mixed malaria" | "DOID:14325" | ["disease"] | 4.020905494689941
"obsolete avian malaria" | "DOID:14326" | ["disease"] | 3.8702492713928223
"Plasmodium malariae malaria" | "DOID:14324" | ["disease"] | 3.8455417156219482
... | ... | ... | ...

It seems pretty performant. The above gave me 576 results in 1544 ms.

**Comment by finnagin** [comment]
Looks like the fulltext index doesn't play well with setting `dbms.read_only=true`. When trying to restart it gives me the error "Can't create populator for read only index".

**Comment by saramsey** [comment]
thanks, @finnagin

**Comment by dkoslicki** [comment]
Done at some point, then disappeared. @finnagin want to give an update and potentially close as per #788?

**Comment by saramsey** [comment]
@dkoslicki and @edeutsch do we still want this?  Or are we good with the node synonymizer?

**Comment by edeutsch** [comment]
I do not see any need for Neo4j full text search.

**Comment by saramsey** [comment]
Hi @dkoslicki can I close this issue out?

**Comment by dkoslicki** [comment]
Yes, I think we can!
