### ISSUE TITLE
make `create_indexes_constraints.py` test if database is read-only

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#502]

**Comment by saramsey** [comment]
is there a way to do this using Cypher?

**Comment by finnagin** [comment]
@saramsey it looks like you can get a list of all the config setting from `dbms.listConfig()` so something like this should work:
```
call dbms.listConfig() yield name, value where name = "dbms.read_only" return value
```

**Comment by dkoslicki** [comment]
@saramsey @finnagin Close due to #788?
