### ISSUE TITLE
search for gene symbol in rtx.ncats.io web UI

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#506]
This feature request is from Noel Southall and Will Byrd at the Seattle Hackathon. They want to be able to search on a gene symbol, like "MAVS", in the "Enter new query node" text box. Currently, when we type "MAVS" in the search box, we get two results that are not what we want:
<img width="1096" alt="Screen Shot 2019-09-16 at 2 49 40 PM" src="https://user-images.githubusercontent.com/5562107/64995893-4d490780-d891-11e9-9531-d5bab50de489.png">

what we want is the node whose *symbol* is "MAVS".

**Comment by edeutsch** [comment]
Bug in entity loader now fixed.
![image](https://user-images.githubusercontent.com/12707718/65004056-e71fad00-d8af-11e9-8d2e-618ab2ed1a95.png)

**Comment by dkoslicki** [comment]
Holy cow @edeutsch, that was quick! Was it a front-end bug, or a back end one? Don't see a commit associated to this, so assume it's a front end one?

**Comment by edeutsch** [comment]
Just pushed the commit. It was merely a problem in the node table definition. there was a UNIQUE index which prevented more than one name of a node. Since the full protein names always came first, the protein symbol was quietly dropped and did not make it into the node list for the autocomplete.

**Comment by saramsey** [comment]
WOW!   

Eric this was very very very very helpful. Have a Foster's on us!
