### ISSUE TITLE
encode SemMedDB sentences and scores as a "provenance" node

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#509]

**Comment by saramsey** [comment]
![IMG_3480](https://user-images.githubusercontent.com/5562107/65082250-50f49100-d95a-11e9-9586-5cf606b03970.jpg)

**Comment by dkoslicki** [comment]
@saramsey keep open, or close due to #788?

**Comment by saramsey** [comment]
we should check with the Data Modeling Group before implementing this; there is a good chance that the draft "standard" has evolved

**Comment by saramsey** [comment]
going to close this for now; Data Modeling Group is now actively revisiting how to model provenance so the above is likely to change in any event
