### ISSUE TITLE
make it possible to view node description from the build-a-graph screen

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#514]
<img width="920" alt="Screen Shot 2019-09-18 at 8 28 49 AM" src="https://user-images.githubusercontent.com/5562107/65162675-77fca280-d9ee-11e9-864e-0d616de6fb8d.png">

this request is from Noel Southall

**Comment by edeutsch** [comment]
indeed not possible yet from the build-a-graph screen, but this is a good suggestion, and we will try to get this done soon.

Note that you can see the definitions after clicking [QUERY]. i.e. in the query interface, type in "insulin", click [Add], then [QUERY], and then [Results]. Now when you click on a node, you'll see the definition. But you knew that. Seeing it in the query interface would be a nice enhancement. We'll try to get it done soon.

**Comment by edeutsch** [comment]
The /entity endpoint now also returns a description from the KG.
e.g.:
https://rtx.ncats.io/devED/api/rtx/v1/entity/insulin
@isbluis, would you implement some nice way of displaying that new information?
Perhaps a mouse-over popup?

**Comment by edeutsch** [comment]
Can now mouse over a node name in node table during graph building to see the description if available in the KG.
Rolled out to production.
