### ISSUE TITLE
Edit GST-Neurodegeneration graph gives 500 error

### ISSUE THREAD

**Issue by southalln** [RTXteam/RTX#516]
Start with:
https://rtx.ncats.io/beta/?m=1982

<img width="778" alt="Screen Shot 2019-09-18 at 9 34 09 AM" src="https://user-images.githubusercontent.com/1583338/65167477-800d1000-d9f7-11e9-9aa1-414aa7d18ab8.png">

Then change the graph by deleting the node:
Name: neurodegenerative disease ID: DOID:1289
and replacing it with:
Parkinson's disease  ID: DOID:14330

By doing:
qg9 | neurodegenerative disease (DOID:1289) | DOID:1289 | disease | [Remove]
Enter new query node:  Parkinson's disease  (DOID:14330 | disease)
Enter new relationship:    protein    DOID:14330    unspecified

Click 'Query'
Status
Posting graph. Looking for answer...
An error was encountered while contacting the server (500)

**Comment by edeutsch** [comment]
I have repro'd this successfully

After replaying the instructions, above I get:
![image](https://user-images.githubusercontent.com/12707718/65799210-64f17d00-e128-11e9-9fba-07fcb978d3ee.png)

Note that the two edges both have the number 7

Submitted JSON is this:
posted to QUERY:
{
  "message": {
    "query_graph": {
      "edges": [
        {
          "id": "qg7",
          "negated": null,
          "relation": null,
          "source_id": "qg3",
          "target_id": "qg2",
          "type": "capable_of"
        },
        {
          "id": "qg7",
          "negated": null,
          "relation": null,
          "source_id": "qg6",
          "target_id": "qg3",
          "type": null
        }
      ],
      "nodes": [
        {
          "id": "qg2",
          "name": "glutathione transferase activity (GO:0004364) (GO:0004364) (GO:0004364)",
          "curie": "GO:0004364",
          "type": "molecular_function"
        },
        {
          "id": "qg3",
          "name": "proteins?",
          "type": "protein"
        },
        {
          "id": "qg6",
          "is_set": null,
          "name": "Parkinson's disease",
          "curie": "DOID:14330",
          "type": "disease"
        }
      ]
    }
  },
  "max_results": 100
}

Note that both edges have the same ID.
This causes downstram Cypher error.
There should be better error checking at the server.
But the UI should ensure no repeated ids during a sequence such as this.
Need help from @isbluis for that.

**Comment by edeutsch** [comment]
Bug fixed by Luis. Fix rolled out to production.
