### ISSUE TITLE
users of KG2 want resolvable URLs for nodes and provided_by info

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#520]

**Comment by saramsey** [comment]
many of the semantic-web-approved URLs don't actually resolve to real web pages that real people would want to access "for more information", e.g., this:

https://identifiers.org/umls/cui/C0031965

**Comment by amykglen** [comment]
is this the kind of "real web page" the above example might link to instead? 

https://identifiers.org/umls:C0031965

(came across that type of URL on this page: https://registry.identifiers.org/registry/umls)

**Comment by saramsey** [comment]
currently working hard on this issue

**Comment by saramsey** [comment]
> is this the kind of "real web page" the above example might link to instead?
> 
> https://identifiers.org/umls:C0031965
> 
> (came across that type of URL on this page: https://registry.identifiers.org/registry/umls)

Yes, I am following your advice. Thank you! `identifiers.org` is going to simplify this a lot. Nevertheless, fully implementing #520 will be a challenge.

**Comment by saramsey** [comment]
@amykglen I am currently making modifications to these files, in order to address this issue (and the related issue #747):

- `multi_owl_to_json_kg.py`
- `curies-to-urls-lookaside-list.yaml`
- `kg2_util.py`
- `curies-to-categories.yaml`
- `ensembl_json_to_kg_json.py`
- `ncbigene_tsv_to_kg_json.py`
- `requirements-kg2-build.txt`

The modifications to the first three above are fairly extensive.
