### ISSUE TITLE
new ontologies to consider adding to KG2

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#522]
Environmental Exposures Ontology
Drug-Drug Interaction and Drug-Drug Interaction Evidence Ontology (DIDEO)
Interaction Network Ontology (ino.owl)

See more here:
http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/RO_0002408

**Comment by saramsey** [comment]
Genotype Ontology (GENO)

**Comment by saramsey** [comment]
Drug-drug Interaction and Drug-Drug-Interaction Evidence Ontology (DIDEO)

**Comment by dkoslicki** [comment]
Keep open, or close due to #788 @saramsey ?

**Comment by saramsey** [comment]
keep open; but marking LOWPRI

**Comment by saramsey** [comment]
going to close this for now, unless someone requests ETL of DIDEO, ExO, or ECTO

**Comment by saramsey** [comment]
Also Brenda Tissue Ontology (see #970)

**Comment by saramsey** [comment]
going to mothball this issue for now, as we have much more pressing priorities for KG2 development
