### ISSUE TITLE
add edges between MESH terms and PMIDs in KG2

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#523]
requested by team Alpha

**Comment by saramsey** [comment]
also include:
title
authors
date
journal

**Comment by dkoslicki** [comment]
Old info from Arnab:

```
wget -r ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline
 
for file in *.gz ; do time cat $file | gunzip | xmlstarlet sel -T -t -m "/PubmedArticleSet/ 
PubmedArticle/MedlineCitation" -v "concat(PMID,'$TAB$',Article/Abstract,'$TAB$', Article/ArticleTitle)" -n >> data.tsv 
 ```
Note that the $TAB$ needs to be replaced with actual tabs (ctrl v , then tab)
 
This generates a tsv file of pmid, abstract, and title -- it will be a 23GB file
 
The step after that is to import into MySQL.

**Comment by edeutsch** [comment]
Want me to try this on rtx.ncats.io?

**Comment by dkoslicki** [comment]
@saramsey still relevant? Or close per #788?

**Comment by ericawood** [comment]
What biolink standard edge label would work well for PMID -> MESH edges? This is all we know about a MESH to PMID relationship per the XML files: (this dictionary is contained by a larger dictionary with the PMID)
![image](https://user-images.githubusercontent.com/36611732/88211922-41de0f80-cc0b-11ea-8adb-fd3832472e6f.png)

**Comment by ericawood** [comment]
> also include:
> title
> authors
> date
> journal

What KG2 properties would journal/authors fall under? Is abstract wanted as well (more likely on the PMID nodes instead, per #646)? @saramsey

**Comment by saramsey** [comment]
Hi @ericawood I can't remember, are you using `bigmem.rtx.ai` for this work?

**Comment by ericawood** [comment]
Hi @saramsey, yes, I am using `bigmem.rtx.ai` for this work (it is all included in the pubmed ETL script `pubmed_xml_to_kg_json.py`).

**Comment by ericawood** [comment]
Documenting that relation will be "biolink:has_attribute"

**Comment by saramsey** [comment]
Merging this issue into #646
