### ISSUE TITLE
make a list of upstream KSs for KG2 and KG1 and their redistribution licenses

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#526]
make this a section in the README.md file in kg2

**Comment by amykglen** [comment]
@saramsey - took a first shot at compiling this info for KG2 based on the sources you sent me in Slack at the hackathon (googled to find what license info I could):

**KG2 knowledge sources** (linked to redistribution license info):
* [UMLS](https://www.nlm.nih.gov/research/umls/knowledge_sources/metathesaurus/release/license_agreement.html)  (+ [SNOMED CT](https://www.nlm.nih.gov/healthit/snomedct/snomed_licensing.html))
* [SemMedDB](https://github.com/OHDSI/KnowledgeBase/tree/master/LAERTES/SemMED) 
* [CheMBL](https://chembl.gitbook.io/chembl-interface-documentation/about#data-licensing) (without metabolism)
* [Ensembl Genes](https://uswest.ensembl.org/info/about/legal/code_licence.html)
* [NCBI Genes](https://www.ncbi.nlm.nih.gov/home/about/policies/)
* UniChem (partial)
* [DrugBank](https://www.drugbank.ca/legal/terms_of_use) (partial)
* [UniProtKB](https://www.uniprot.org/help/license) (human + pathogens)
* [DGIdb](https://github.com/griffithlab/dgi-db/blob/master/LICENSE)
* [OBO Foundry](http://www.obofoundry.org/principles/fp-001-open.html) (~20 ontologies)

**Comment by dkoslicki** [comment]
@amykglen Do you happen to know which OBO foundry ontologies were added? I think this would be useful information

**Comment by amykglen** [comment]
I don't know, sorry - all I know from Steve is that there were about 20... :) But sounds good to add that info in!

**Comment by dkoslicki** [comment]
Ah, I see! It might be helpful to go to [http://kg2endpoint.rtx.ai:7474/browser/](http://kg2endpoint.rtx.ai:7474/browser/) and use the command ```match (n) return distinct split(n.id,':')[0]```
Using [identifiers.org](http://identifiers.org/) or similar can then help figure out the KS it was pulled from.
Alternately, dig through [https://github.com/RTXteam/RTX/tree/master/code/kg2](https://github.com/RTXteam/RTX/tree/master/code/kg2) to get the URLs of the KS's used

**Comment by dkoslicki** [comment]
Alternately:
```match (n) with distinct n.provided_by as p return p order by p```

**Comment by amykglen** [comment]
Ah, cool, thanks! Will do some digging and get that info added in.

**Comment by amykglen** [comment]
Is there a safe place to put/share a google sheet for this list? Started working on it that way, since it's still easy to convert to markdown for the README...

(Been compiling the info like this...):

| Knowledge source              | Type     | KG1 | KG2 |
|-------------------------------|----------|-----|-----|
| BFO                           | ontology |     | x   |
| BigCLAM                       | data     | x   | x   |
| BigGIM                        | data     | x   | x   |
| biolink                       | data     | x   | x   |
| BSPO                          | ontology |     | x   |
| Cell Ontology                 | ontology | x   | x   |
| ChEBI                         | ontology |     | x   |
| Chembl (without metabolism)   | data     | x   | x   |
| Columbia Open Health Data     | data     | x   | x   |

..etc...

**Comment by dkoslicki** [comment]
Nice! The team Google drive should be a good place: https://drive.google.com/folderview?id=0B-4lBWsz5q29ZVJtRi12Q1ZWSVU

Maybe in the (quite old) Rtx-kowledge-graph folder:https://drive.google.com/folderview?id=0B-4lBWsz5q29ZVJtRi12Q1ZWSVU

But @saramsey would know better

**Comment by amykglen** [comment]
Cool, thanks! Put it there (for now at least): https://docs.google.com/spreadsheets/d/163IzxKxQE7NC9DSxiPM8ZPGu2iihyJA-0ZIWm-FTrSw/edit?usp=sharing

Added a couple questions as comments in there for whoever feels like answering... :)

**Comment by saramsey** [comment]
Thanks, @amykglen . I have added this to the KG2 README.md. What questions were there that I should answer (I didn't see any comments in the Google sheet).

**Comment by amykglen** [comment]
Nice! I think I resolved those myself somewhere down the line, so no questions to answer, thanks.

**Comment by saramsey** [comment]
Great work on this issue, @amykglen, closing it out
