### ISSUE TITLE
there are 164k nodes for which both "name" and "full_name" are NULL

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#529]
it apparently has a ‘full_name’, but not a ‘name’

![Screen Shot 2019-09-30 at 8 53 58 AM](https://user-images.githubusercontent.com/49423686/65895794-e03d7380-e360-11e9-8f16-0844923bebc2.png)

**Comment by saramsey** [comment]
Are there a lot of these nodes with no name field, or just one?

**Comment by amykglen** [comment]
I only happened across this one

**Comment by saramsey** [comment]
also this one:


WARNING: node with NULL for the 'name' field; id=HP:0001578

**Comment by amykglen** [comment]
and this node as well (missing a `name`):

```
{ 
   "iri":"https://www.ncbi.nlm.nih.gov/gene/100188340",
   "synonym":"['AOS']",
   "category_label":"gene",
   "deprecated":"False",
   "description":"Adams-Oliver syndrome; Type:unknown; NameStatus:unofficial",
   "provided_by":"https://www.ncbi.nlm.nih.gov/gene",
   "id":"NCBIGene:100188340",
   "category":"http://w3id.org/biolink/vocab/Gene",
   "update_date":"20170402",
   "publications":"[]"
}
```
(just randomly came across it in neo4j)

**Comment by saramsey** [comment]
See this code:
```
match (n) where n.name is Null and n.full_name is not Null return count(*)
```
which seems to imply that there are 46,811 such nodes:

![Screen Shot 2019-11-27 at 1 48 54 PM](https://user-images.githubusercontent.com/5562107/69761590-b0220f00-111c-11ea-9670-58b4975a91d2.png)

**Comment by saramsey** [comment]
also want to check for nodes that have null name and null full_name (hopefully there are few of these)

**Comment by saramsey** [comment]
![Screen Shot 2019-11-27 at 1 52 35 PM](https://user-images.githubusercontent.com/5562107/69761762-2fafde00-111d-11ea-8c70-361e8b6599a7.png)

**Comment by saramsey** [comment]
so this issue seems to be coming in from umls-hgnc.ttl, maybe?

**Comment by saramsey** [comment]
if that is true, then it suggests that the place to fix this is in `multi_owl_to_json_kg.py`

**Comment by saramsey** [comment]
steve has pushed a code change for this; ready to test when there is time

**Comment by amykglen** [comment]
hmm.. apparently there are even more nodes with **both** a null `name` AND a null `full_name`:

<img width="658" alt="Screen Shot 2019-11-29 at 11 46 43 AM" src="https://user-images.githubusercontent.com/49423686/69889664-b3dd9f00-129e-11ea-8e88-326dde112c50.png">

here's where they're coming from:

<img width="863" alt="Screen Shot 2019-11-29 at 12 00 27 PM" src="https://user-images.githubusercontent.com/49423686/69889906-dfad5480-129f-11ea-91f9-681339bd68c8.png">

**Comment by amykglen** [comment]
verified that all of the nodes missing a `name` and `full name` **do** have an `id`

![Screen Shot 2019-12-03 at 10 41 25 AM](https://user-images.githubusercontent.com/49423686/70079403-8738c880-15b9-11ea-8558-3d4628ef2e17.png)

**Comment by saramsey** [comment]
there should definitely not be any gene nodes in KG2 that have no "name"

**Comment by saramsey** [comment]
<img width="1030" alt="Screen Shot 2019-12-20 at 1 53 30 PM" src="https://user-images.githubusercontent.com/5562107/71295290-20910a00-2330-11ea-8dc3-db4c9892a2c8.png">

**Comment by saramsey** [comment]
it looks likely that the issue is in the script `ncbigene_tsv_to_kg_json.py`, right?

**Comment by amykglen** [comment]
yes, I believe so... (for the affected nodes that are genes, of course...)

**Comment by saramsey** [comment]
I've asked Lindsey Kvarfordt to take a look at this issue, since this looks like it could be a good issue by which to get introduced to KG2 (just an FYI)

**Comment by edeutsch** [comment]
See also #652, which may be a symptom of this problem. The KGNodeIndex system and systems that rely on it pretty much assume that every node has a non-null CURIE, name, and type.
If this is not true, things will break.
What should the policy be?

**Comment by edeutsch** [comment]
(my vote is that every node has a non-null CURIE, name, and type)

**Comment by saramsey** [comment]
> See also #652, which may be a symptom of this problem. The KGNodeIndex system and systems that rely on it pretty much assume that every node has a non-null CURIE, name, and type.
> If this is not true, things will break.
> What should the policy be?

I see a problem with this proposal: there are plenty of cases where we could have two nodes with different CURIEs and the same `name`. I'm fine with requiring CURIE to be non-null (in Neo4j) and unique (in fact, we use CURIE ID as the unique node identifier so it sort of has a "unique constraint" in the way KG2 is designed). But `name`?  I think we should allow Null and allow not unique. I think it is OK to require `category_label` to be non-empty. Just my $0.02.

**Comment by saramsey** [comment]
![Screen Shot 2020-02-28 at 10 23 50 AM](https://user-images.githubusercontent.com/5562107/75575160-78c14800-5a14-11ea-8a5e-5cf1ec21d9d1.png)

**Comment by saramsey** [comment]
I believe @dkoslicki has a work-around for this issue, but he has said that the work-around is not optimal from an overall system functionality standpoint. But that takes some off the pressure off, on this issue. So I will focus on documentation and slide-deck issues for the time being, and will circle back to this issue when we have made progress on the top-level `README.md` (#657) and the demo slide deck (#655).

**Comment by dkoslicki** [comment]
Yes, the workaround is in place: basically `ARAX_query.py` just doesn’t know these nodes exist (since they aren’t included in the KGNodeIndex), as I ignore these “problem” nodes and they aren’t added to the index. Ref: commits in #652.

**Comment by kvarforl** [comment]
Some of the null names are definitely coming from `ncbigene_tsv_to_kg_json.py` as Steve suggested. Basically line 64 ( `fields = [(field if field.strip() != '-' else None) for field in fields]`) changes any field of `Homo_sapiens_gene_info.tsv` that's a '-' to be None, and a bunch of the name fields of that .tsv file are '-' . 
A possible (but probably not optimal)  solution is to add a conditional to the `ncbigene_tsv_to_kg_json.py` script that skips nodes with null names until we can figure out how to pull down a more complete version of `Homo_sapiens_gene_info.tsv` (a change to `extract-ncbigene.sh` ?)

**Comment by saramsey** [comment]
thank you @kvarforl for the helpful debugging!

**Comment by saramsey** [comment]
I note that currently, in the Biolink metamodel, the `node` property `name` is not required. See 
https://github.com/biolink/biolink-model/blob/70a73ad20dee03e24b559e5eaef81c3eb0f4ee0b/biolink-model.yaml#L493

The `required: true` is commented out.

<img width="568" alt="Screen Shot 2021-02-03 at 12 40 57 PM" src="https://user-images.githubusercontent.com/5562107/106806689-1ce84180-661d-11eb-849a-f0d8bafb9f3b.png">
