### ISSUE TITLE
Feedback mechanism

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#53]
Placeholder issue to remind us to work on the feedback mechanism for the UI.

**Comment by dkoslicki** [comment]
Just so we keep it on our radar, @edeutsch and @saramsey, this is something we promised by the May hackathon, so we should probably make this a high priority item.

**Comment by edeutsch** [comment]
Agreed. I have a design. I have one more week of craziness and then I will set about getting this implemented.

**Comment by edeutsch** [comment]
more that could be done, but sufficiently functional now, closing.
