### ISSUE TITLE
Drop SemMedDB negated edges

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#535]

**Comment by saramsey** [comment]
have pushed a change to address this issue; just need to test it on kg2dev.rtx.ai

**Comment by dkoslicki** [comment]
@saramsey still relevant, or closer per #788?

**Comment by finnagin** [comment]
Closing since the kg2 code has moved an this file is marked as [depreciated in the RTX-KG2 repo.](https://github.com/RTXteam/RTX-KG2/blob/master/build-kg2-DEPRECATED.sh)
