### ISSUE TITLE
Fix edges that use a retired CUI without a 'synonym' remapping in MRCUI.RRF

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#537]
Some (~200k) of the orphan edges in kg2 that use a retired CUI **don't have a 'synonym' remapping** to a current CUI (in kg2-build/umls/META/MRCUI.RRF).

The other types of remappings these retired CUIs might have (as listed in UMLS [ref manual](https://www.ncbi.nlm.nih.gov/books/NBK9685/)) include:
* Broader (RB)
* Narrower (RN)
* Other related (OR)

And a retired CUI may have multiple such remappings, in which case it's not obvious which remapping we should use....

**Comment by saramsey** [comment]
this issue is currently on the back-burner pending resolution of higher-priority development tasks

**Comment by dkoslicki** [comment]
@amykglen @saramsey still relevant, or close per #788?

**Comment by amykglen** [comment]
@ericawood to copy the log file from her test build of the new SemMedDB over to kg2dev; then I'll inspect it to see if that helped resolve this issue

**Comment by ericawood** [comment]
@amykglen The orphan edges file from the build of SemMedDB are now on kg2dev at ~/kg2-orphans-edges-semmeddb42.json. Please let me know if this isn't the correct file.

**Comment by saramsey** [comment]
Hi @ericawood and @amykglen can you help test this in the current KG2 build?

**Comment by ericawood** [comment]
Using Amy's report_problem_cuis_in_kg_edges.py (modified the new KG2) and the orphan edges file from the latest build (by Lindsey), I got the following results:
```
{  
    "_report_datetime": "2020-08-10 23:25:04",
    "_total_number_of_edges": 3479661,
    "number_of_edges_with_invalid_cui": 0,
    "number_of_edges_with_retired_cui": 229652,
    "number_of_edges_with_retired_cui_with_synonym": 81
}
```

**Comment by saramsey** [comment]
Nice, thank you @ericawood 

These numbers look good!

Hey @amykglen can we close out this issue?

**Comment by amykglen** [comment]
sounds good to me. thanks @ericawood!
