### ISSUE TITLE
Error in kg2 test build when awscli tries to upload empty file to s3

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#538]
Getting this error when I try to do a test build on kg2dev:

```
+ BUILD_MULTI_OWL_STDERR_FILE=/home/ubuntu/kg2-build/build-kg2-owl-test-stderr.log
+ aws s3 cp --no-progress --region us-west-2 /home/ubuntu/kg2-build/build-kg2-owl-test-stderr.log s3://rtx-kg2-public/
upload failed: ./build-kg2-owl-test-stderr.log to s3://rtx-kg2-public/build-kg2-owl-test-stderr.log seek() takes 2 positional arguments but 3 were given
```

In this case, `build-kg2-owl-test-stderr.log` is empty. 

Apparently this is an issue with awscli, and using pip to install awscli supposedly fixes it: https://github.com/aws/aws-cli/issues/2403

**Comment by saramsey** [comment]
Nice job finding the root cause.  OK, let's try using pip to install awscli. I prefer to do this via the `requirements-kg2-build.txt` file.

**Comment by amykglen** [comment]
Ah, gotcha. Cool - went ahead and made the switch (https://github.com/RTXteam/RTX/commit/1bb872ebc04930e1cdd35cdc91f99444a0903f3b).

@saramsey - So in order to utilize these changes on kg2dev, is it correct that I'll need to run `clear-instance.sh`, and then proceed with the usual build instructions per the kg2 README? (but starting with a 'test' (vs. 'all') build)

**Comment by saramsey** [comment]
Let's not run clear-instance.sh if we can possibly avoid it.  Should be possible to uninstall the awscli ubuntu package using apt-get, right?  this might be a more surgically precise way to uninstall it (then we don't have to download and re-extract/re-build a bunch of databases like UMLS).

**Comment by amykglen** [comment]
Ok cool, got it. Yep, think that should work fine.

**Comment by amykglen** [comment]
Ok, I realized that simply upgrading the version of awscli, still using apt-get, fixes this issue (the build script runs successfully with the awscli version you get on a fresh install using apt-get).

And while pip is supposedly the preferred way of installing awscli now, switching to it would involve more extensive changes if we're installing it in the virtual environment like the other packages in `requirements-kg2-build.txt` (?)

So I'm thinking it may be best to just leave the code how it was for now (installing awscli with apt-get), since it actually _is_ working out of the box.

**Comment by amykglen** [comment]
So I realized that simply upgrading awscli using apt-get fixes this issue (the build script runs successfully with the awscli version you get on a fresh install with apt-get).

And it looks like using pip to install awscli would require more extensive changes if we’re installing it into the virtual environment, as we do the other packages in `requirements-kg2-build.txt` (?)

So even though pip is supposedly the preferred way to install awscli now, I’m thinking it probably makes sense to just leave the code as it was for now (using apt-get), since it _is_ still working out of the box.
