### ISSUE TITLE
Network timing out due to not using eutil key from NCAT

### ISSUE THREAD

**Issue by power10dan** [RTXteam/RTX#543]
I ran into this issue while benchmarking the code for the Normalized Google Distance function:

HTTP connection error in QueryNCBIeUtils.py; URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=%28malaria%5BMeSH%20Terms%5D%29%20AND%20%28Urticaria%5BMeSH%20Terms%5D%29&retmode=json&retmax=1000
HTTP connection error in QueryNCBIeUtils.py; URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi

Could this be because NCBI is shutting off my connection due to
some kind of network control (throttling, connecting for too long,
etc)?

**Comment by power10dan** [comment]
Steve responded to me with the following:

Are we using an access key?  (that should be evident from the code). If not, we probably should be using an access key. The rate limit for eutils requests is higher if you are using an access key (still, it is only 10 requests/second).  At 10 requests/second, you could probably annotate 1.5 million edges in the KG in 41 hours. So I am not convinced that NGD is infeasible for KG1.  For KG2, it is probably still feasible, but it would take 38 days (again not impossible, but requires more engineering for failure recovery in case the script dies partway through).

Below is the link that Steve gave me that is really useful in explaining how to 
resolve this issue:
https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/

**Comment by dkoslicki** [comment]
Closing due to #788
