### ISSUE TITLE
ETL ChEMBL metabolism information

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#545]

**Comment by dkoslicki** [comment]
@saramsey still relevant, or close due to #788?

**Comment by saramsey** [comment]
still relevant

**Comment by ericawood** [comment]
This appears to be compete in `KG2.6.0`:

`match (n)-[e]-(m) where "identifiers_org_registry:chembl.compound" in e.provided_by and e.predicate="biolink:has_metabolite" return count(distinct e)`

count(distinct e)
--|
894
