### ISSUE TITLE
ETL RepoDB

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#546]
http://apps.chiragjpgroup.org/repoDB/
https://www.nature.com/articles/sdata201729.pdf

**Comment by saramsey** [comment]
Need to 

1. write a Python script `repodb_csv_to_kg_json.py` that will convert rows from the RepoDB CSV file to edges in the standard KG2 JSON format (kg-build/kg2-repodb.json). See the script `dgidb_tsv_to_kg_json.py` for an example template. 
2. write a shell script `download-repodb-csv.sh` (see the script `extract-dgidb.sh` for an example template). 
3. modify `build-kg2.sh` as follows:
- run `download-repodb-csv.sh` (at line 131 in the current script, inside the if block) 
- run `repodb_csv_to_kg_json.py` at line 199 in the current script
- include `kg2-repodb.json` in the KG2 merge at line 224 in the current `build-kg2.sh` script.

**Comment by saramsey** [comment]
looks like the Status field in the repoDB `full.csv` file is categorical with values `Approved`, `Terminated`, `Suspended`, etc.

We'll have to discuss how to map those Status field categories to KG2 predicates. This will probably be a 10-15 minute conversation.

**Comment by saramsey** [comment]
https://prefixcommons.org/?q=clinical%20trial

![Screen Shot 2019-10-25 at 1 20 46 PM](https://user-images.githubusercontent.com/5562107/67601874-48962f80-f72a-11e9-9c3c-c439729f195a.png)

CURIE ID should be 

clinicaltrials:NCT02661113

**Comment by finnagin** [comment]
test using `filter_kg_and_remap_predicates.py`

**Comment by finnagin** [comment]
I've added the scripts to `kg2-build.sh` and tested the output using `filter_kg_and_remap_predicates.py`.
The output edges (in the simplified json) look like the following:
```
{
  "subject": "DRUGBANK:DB00001",
  "object": "CUI:C0272275",
  "edge label": "clinically_tested_approved_unknown_phase",
  "relation": "http://apps.chiragjpgroup.org/repoDB/#clinicallyTestedApprovedUnknownPhase",
  "relation curie": "REPODB:clinically_tested_approved_unknown_phase",
  "negated": false,
  "publications": [],
  "publications info": {},
  "update date": null,
  "provided by": [
    "http://apps.chiragjpgroup.org/repoDB/"
  ],
  "simplified edge label": "is_substance_that_treats",
  "simplified relation curie": "RO:0002606",
  "simplified relation": "http://www.obofoundry.org/ro/ro.owl#0002606"
}
```

```
{
  "subject": "DRUGBANK:DB00921",
  "object": "CUI:C0019337",
  "edge label": "clinically_tested_terminated_phase_2",
  "relation": "http://apps.chiragjpgroup.org/repoDB/#clinicallyTestedTerminatedPhase2",
  "relation curie": "REPODB:clinically_tested_terminated_phase_2",
  "negated": false,
  "publications": [
    "clinicaltrials:NCT00000330",
    "clinicaltrials:NCT00000331"
  ],
  "publications info": {
    "clinicaltrials:NCT00000330": "https://clinicaltrials.gov/ct2/show/NCT00000330",
    "clinicaltrials:NCT00000331": "https://clinicaltrials.gov/ct2/show/NCT00000331"
  },
  "update date": null,
  "provided by": [
    "http://apps.chiragjpgroup.org/repoDB/",
    "http://apps.chiragjpgroup.org/repoDB/"
  ],
  "simplified edge label": "intent_to_treat",
  "simplified relation curie": "NCIT:C54398",
  "simplified relation": "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C54398"
}
```

**Comment by finnagin** [comment]
I think this is safe to close now.
