### ISSUE TITLE
OMIM key deactivated

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#547]
Just received this in the mail from OMIM:
```
OMIM - Data Account Suspension

This email is to confirm that your data account has been suspended.


Hi, we are suspending this account because the download/API key was leaked on GitHub, please contact us for a new API key.


Online Mendelian Inheritance in Man - OMIM
https://omim.org
```

**Comment by saramsey** [comment]
I think the issue is this code:

![Screen Shot 2019-10-22 at 2 02 19 PM](https://user-images.githubusercontent.com/5562107/67332951-99ace600-f4d4-11e9-86eb-4182bdbc375b.png)

**Comment by fschiettecatte** [comment]
If all you are looking for is MIM # to gene symbol and MIM # to UniProt ID, then you only need these two files which are available publicly:

- https://www.uniprot.org/docs/mimtosp.txt
- https://omim.org/static/omim/data/mim2gene.txt

**Comment by saramsey** [comment]
Thank you, @fschiettecatte !

Cheers,
Steve
