### ISSUE TITLE
mediKanren

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#548]
I propose a couple of modifications to the `README.md` and `setup.sh` in the code/kg2/mediKanren directory:

For `README.md`:

1. the README it should say that Ubuntu 18.04 is required
2. the README should say that passwordless sudo is required
3. it should indicate as what user "setup.sh" should be run (I think unprivileged; see my comments below)
4. the README should prescribe that setup.sh should be run like this:
`bash -x ./setup.sh > setup.log 2>&1`

For `setup.sh`:

1. I prefer that all the `apt-get` statements in `setup.sh` be prepended with `sudo`
2. there is no reason to run the `git` commands as root (and good reason not to). Thus I think we should have `setup.sh` run as an unprivileged user `ubuntu` on EC2 (see point 3 above)
3. `setup.sh` should set up its own virtualenv, and installing packages into it. Installing into the system python is not best practice, as a general rule (unless you are specifically intending to modify the system python for some reason); see `code/kg2/setup-kg2-build.sh`
4. `setup.sh` should have this at the top:  `set -o nounset -o pipefail -o errexit` per best practice and to ensure that the bash script exits and doesn't continue on,  if anything unexpected happens.

**Comment by saramsey** [comment]
Actually, can you also please add 

```
set -o nounset -o pipefail -o errexit
```
to the top of each of the shell scripts in that directory?

**Comment by saramsey** [comment]
the README.md should also state that the Dockerfile is optional, and provided just in case someone wants to run the software inside a Docker container.

As I understand it, `setup.sh` is the "official" way to do it (correct?).

**Comment by saramsey** [comment]
summarizing my conversation with @finnagin on 11/1 about this: next steps are:

- get a mediKanren-indexed version of the latest KG2 dumped from kg2endpoint2.rtx.ai (which I will call "kg2-latest" for short)
- test out "kg2-latest" within the mediKanren GUI, to see how it works (involve @saramsey in this, since I would like to see how it works)
- some updates to the README.md in the mediKanren directory, to complete the directions for testing out the index build, and for loading into mediKanren

**Comment by saramsey** [comment]
can this issue be closed?

**Comment by finnagin** [comment]
Yeah I think it can.
