### ISSUE TITLE
diseases.jensenlab.org: another potential upstream knowledge source for KG2

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#550]
https://diseases.jensenlab.org/Downloads

**Comment by dkoslicki** [comment]
@saramsey still relevant, or close due to #788?

**Comment by saramsey** [comment]
still relevant

**Comment by saramsey** [comment]
Simple TSV format, should be easy to ETL:
```
18S_rRNA        18S_rRNA        DOID:9643       Babesiosis      6.913   3.456   http://diseases.jensenlab.org/Entity?documents=10&type1=9606&id1=18S_rRNA&type2=-26&id2=DOID:9643
18S_rRNA        18S_rRNA        DOID:1398       Parasitic infectious disease    6.622   3.311   http://diseases.jensenlab.org/Entity?documents=10&type1=9606&id1=18S_rRNA&type2=-26&id2=DOID:1398
18S_rRNA        18S_rRNA        DOID:2789       Parasitic protozoa infectious disease   6.619   3.310   http://diseases.jensenlab.org/Entity?documents=10&type1=9606&id1=18S_rRNA&type2=-26&id2=DOID:2789
18S_rRNA        18S_rRNA        DOID:4  Disease 6.464   3.232   http://diseases.jensenlab.org/Entity?documents=10&type1=9606&id1=18S_rRNA&type2=-26&id2=DOID:4
```

**Comment by saramsey** [comment]
not seeing any evidence that this dataset is being updated periodically.

**Comment by saramsey** [comment]
https://jensenlab.org/resources/textmining/

**Comment by saramsey** [comment]
Hmm, actually, the JensenLab site says it is updated "weekly":
<img width="770" alt="Screen Shot 2021-02-01 at 1 02 43 PM" src="https://user-images.githubusercontent.com/5562107/106517807-d57f7b00-648d-11eb-85c6-6be9e0f31448.png">

**Comment by saramsey** [comment]
Let's do a test. I downloaded `human_disease_textmining_filtered.tsv` on Feb. 1, 2021 at 12:53 PST. It has 178,217 lines:
```
(venv) sramsey-laptop:Desktop sramsey$ wc -l human_disease_textmining_filtered.tsv
  178217 human_disease_textmining_filtered.tsv
```
Let's check back in a month and see if the file has changed in size.

**Comment by kvarforl** [comment]
looks like this is being updated! I downloaded a new version of the file today, and it now contains 178,390 lines.

Slowly working my way through the ETL now :)

**Comment by kvarforl** [comment]
Okay I'm working on figuring out the best way to map the identifiers of the genes given in the file to existing nodes in kg2: [this](https://www.sciencedirect.com/science/article/pii/S1046202314003831) paper, linked from the [about](https://diseases.jensenlab.org/About) page, has the following clues:

>"We have developed a highly efficient NER method for diseases and human genes, which are normalized to identifiers from Disease Ontology [23] and STRING v9.1"...
>"For human gene and protein names, we used the alias file from STRING v9.1 [29], which integrates names from Ensembl [39], UniProtKB [6], and HGNC [16]."

Since we don't use the STRING identifiers, I'm thinking I might need to grab the STRING alias file as part of the extraction and remap the jensen lab gene identifiers to sources that we do use as identifiers.

**Comment by kvarforl** [comment]
Okay I've been working on mapping the STRING ids used in the jensenlab tsv to ids from sources that are included in KG2. 
I haven't been able to find specification for the format of Ensembl identifiers, so I haven't been able to generate a regex to find them (the jensen dictionary files don't prefix their synonyms, so its kind of tricky to sort out which synonym came from where).

However, using just the HGNC and UniProtKB synonyms, I've been able to find kg2 ids for 17,259 of the genes used in the tsv file and am only missing kg2 identifiers for 1,914 genes as of today (2/25/2021).

For now I'm going to output this information to stderr so we can keep an eye on it, but push ahead with the rest of the ETL.

**Comment by kvarforl** [comment]
this is the content of `human_disease_textmining_filtered.tsv`:
```
(kg2-venv) lindsey@Lindseys-MacBook-Pro:~/RamseyResearch$ head human_disease_textmining_filtered.tsv
18S_rRNA	18S_rRNA	DOID:9643	Babesiosis	6.960	3.480	http://diseases.jensenlab.org/Entity?documents=10&type1=9606&id1=18S_rRNA&type2=-26&id2=DOID:9643
18S_rRNA	18S_rRNA	DOID:1733	Cryptosporidiosis	5.952	2.976	http://diseases.jensenlab.org/Entity?documents=10&type1=9606&id1=18S_rRNA&type2=-26&id2=DOID:1733
18S_rRNA	18S_rRNA	DOID:12365	Malaria	5.907	2.954	http://diseases.jensenlab.org/Entity?documents=10&type1=9606&id1=18S_rRNA&type2=-26&id2=DOID:12365
18S_rRNA	18S_rRNA	DOID:9640	Sarcocystosis	5.848	2.924	http://diseases.jensenlab.org/Entity?documents=10&type1=9606&id1=18S_rRNA&type2=-26&id2=DOID:9640
18S_rRNA	18S_rRNA	DOID:3733	Theileriasis	5.694	2.847	http://diseases.jensenlab.org/Entity?documents=10&type1=9606&id1=18S_rRNA&type2=-26&id2=DOID:3733
18S_rRNA	18S_rRNA	DOID:162	Cancer	5.469	2.735	http://diseases.jensenlab.org/Entity?documents=10&type1=9606&id1=18S_rRNA&type2=-26&id2=DOID:162
18S_rRNA	18S_rRNA	DOID:0050242	Primary amebic meningoencephalitis	5.033	2.516	http://diseases.jensenlab.org/Entity?documents=10&type1=9606&id1=18S_rRNA&type2=-26&id2=DOID:0050242
18S_rRNA	18S_rRNA	DOID:0111384	Inclusion body myopathy with early-onset Paget disease of bone with or without frontotemporal dementia 2	4.793	2.396	http://diseases.jensenlab.org/Entity?documents=10&type1=9606&id1=18S_rRNA&type2=-26&id2=DOID:0111384
18S_rRNA	18S_rRNA	DOID:850	Lung disease	4.792	2.396	http://diseases.jensenlab.org/Entity?documents=10&type1=9606&id1=18S_rRNA&type2=-26&id2=DOID:850
18S_rRNA	18S_rRNA	DOID:4109	Tick infestation	4.682	2.341	http://diseases.jensenlab.org/Entity?documents=10&type1=9606&id1=18S_rRNA&type2=-26&id2=DOID:4109
```
From what I've deduces, the headers of each column would be:
```
gene_id   gene_name	disease_id	disease_name	zscore	confidence(?)	source_url
```

**Comment by kvarforl** [comment]
okay, I have a few questions:

- The links provided in the TSV file link to a page that helpfully has a list of publications associating the gene and the disease (see [this](http://diseases.jensenlab.org/Entity?documents=10&type1=9606&id1=18S_rRNA&type2=-26&id2=DOID:9643) page for the first row of the tsv shown above). Where should I store this link in the edge? is it enough provenance, or should I contact the JensenLab people and see if I can access this information as a flat file so I could parse it and add the PMIDs themselves to the edges?

- What is the best standardized prefix for the relations? Is `JensenLab` okay?

- What should the relation label be? I was thinking `associated_with`, but am open to suggestions

- For the provided by slot, is it acceptable to just put whatever prefix we decide on there?

**Comment by saramsey** [comment]
> Do you know where the structure for a publications_info dict is at? I was thinking something in there might be a good place to stick the zscore. Let me know if you think somewhere else would be better

See https://github.com/RTXteam/RTX/blob/master/code/kg2/README.md#publications_info-slot

also @ericawood may be helpful, they have done a lot of work with `publications_info`. My hacky way of storing scores is under the `object score` slot. See L232 of `rtx_kg1_neo4j_to_kg_json.py`. That's kind of a icky from an object modeling standpoint but at this juncture it is probably best to follow the "convention", aesthetically unpleasant though it may be. In the medium term, we'll improve how we model those kind of score info when the EPC stuff gets finalized and KG2 gets updated to comply with the new EPC schema using (I presume) edge attributes.

**Comment by saramsey** [comment]
HTH

**Comment by kvarforl** [comment]
Notes for documentation sake from my conversation with Dr. Jensen:

- We should use the full file, not the filtered one, and implement our own confidence score cutoff if we want to limit the amount of information we put into the graph
- The files are updated every Sunday
- We'll need to grab some extra files to get the PMIDS, but it shouldn't be too hard.

>Ok, just dug up the links from the files needed for provenance:
https://download.jensenlab.org/human_textmining_mentions.tsv
https://download.jensenlab.org/disease_textmining_mentions.tsv
These files give you a list of all PMIDs for a human gene/protein and a disease, respectively. To find the documents for a given gene–disease pair, all you have to do is look up the PMIDs for both and calculate the set intersection. That is what the webserver does when you access the link for an interaction.

**Comment by kvarforl** [comment]
Okay, I ran the conversion script and saved the output file using the test flag (so including whitespace) and the output file of edges is 99gb. It adds 25,925,537 edges between genes (from HGNC or UniprotKB or both) and diseases (from DOID). 

We might want to implement a z score cutoff value for edges we include to reduce the size of this; thoughts @ericawood ?

**Comment by kvarforl** [comment]
Some info about the zscores in the current `human_disease_textmining_full.tsv`:
```python
>>> np.mean(zscores)
2.1029629960828027
>>> np.median(zscores)
1.827
>>> np.min(zscores)
1.0
>>> np.max(zscores)
9.818


>>> np.size(zscores)
7832387
>>> np.size(np.where(zscores > 2))
3348023
>>> np.size(np.where(zscores > 3))
1283522
>>> np.size(np.where(zscores > 4))
432195
```

From this, it seems like the number of edges could be pretty significantly reduced by only including edges with a zscore of 2 or above (the typical significance cutoff).

**Comment by kvarforl** [comment]
Something else that's definitely compounding the size of this ETL is the number of equivalent kg2 nodes that are found for each gene in each gene disease association. The Jensenlab file uses identifiers that are not in KG2, but provides equivalent id's from sources that are in KG2, that I've constructed into a gene id dictionary with the jensenlab identifier as the key, and a list of potential kg2 gene node ids as the value:
example: `gene_id_dict['ENSP00000000233'] = ['UniProtKB:P84085', 'HGNC:658', 'UniProtKB:P26437']`

I was originally thinking we could just grab one of these, but it's a bit of a gamble determining whether or not the gene id you choose is definitely in kg2 or not.
From the example above, `UniProtKB:P26437` is not in KG2 because it is obsolete. (https://www.uniprot.org/uniprot/P26437)

```
match (n) where n.id in ['UniProtKB:P84085', 'HGNC:658', 'UniProtKB:P26437'] return n.id, n.name
```

n.id | n.name
-- | --
"HGNC:658" | "ARF5 (human)"

If we choose just one id, we're also gambling on the node we choose to have a kg2 name that's conducive to correct synonimization in KG2c to make sure the edge makes it all the way to production. Not sure how big of a gamble that is, but it is something to think about.
"UniProtKB:P84085" | "ARF5"

**Comment by kvarforl** [comment]
Okay I made the following adjustments as per Steve and I's conversation last week:

- Only use HGNC identifiers in kg2
- Only include associations with a zscore higher than 2

With these changes and not running the file in test mode, the final output file is 6.4gb and contains 1,908,580 edges, which seems more reasonable to me.

**Comment by kvarforl** [comment]
When this change gets tested, need to confirm that we haven't added a bunch of edges that don't connect to nodes in kg2, which would indicate that KG2 doesn't have some of the DOID or HGNC id's that are used in the jensenlab tsv.

**Comment by kvarforl** [comment]
Added to kg2.6.0!
 there are 1436180 pmid packed jensenlab edges now :)
