### ISSUE TITLE
build-kg2.log: 'warning: for key: iri, dropping second value...' - Chembl

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#553]
build-kg2.log has ~7k warnings like this one:

`
warning:  for key: iri, dropping second value: https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL282489; keeping first value: https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL282489
`

**Comment by saramsey** [comment]
it looks like we just need to update the IRI prefix in line 21 of `chembl_mysql_to_kg_json.py` to be `https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL282489`

**Comment by amykglen** [comment]
looks like the fix worked (no more of these warnings from the latest build)
