### ISSUE TITLE
filter_kg2_and_remap_predicates.log warnings: 'could not get IRI for relation curie...'

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#554]
These warnings appeared in filter_kg2_and_remap_predicates.log for the Oct. 28 build:
```
could not get IRI for relation curie: oboInOwl:hasRelatedSynonym
could not get IRI for relation curie: CHEMBL:has_indication
could not get IRI for relation curie: SEMMEDDB:xref
```

**Comment by saramsey** [comment]
going to leave this warning for now: `could not get IRI for relation curie: oboInOwl:hasRelatedSynonym`; maybe fix in the future by adding a node to the KG whose `id` property is `oboInOwl:hasRelatedSynonym`

**Comment by saramsey** [comment]
last git commit should address the oboInOwl warning

**Comment by amykglen** [comment]
all are resolved in the latest build!
