### ISSUE TITLE
start tagging kg2 builds with ISO date?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#556]
think about how to do this, it is not obvious how to encode the build date in Neo4j

**Comment by edeutsch** [comment]
maybe always have a node called "knowledge graph" with all the properties you want to have about the graph itself. Would not be connected to anything. Unless you also wanted to connect it to nodes for each knowledge source and relevant properties there.

**Comment by saramsey** [comment]
Good idea!  @finnagin and I considered and rejected several other ideas. This may be the best way to do this, that is compatible with both the JSON representation of the graph and with Neo4j.

**Comment by dkoslicki** [comment]
Iirc, the dumps we provide are now time stamped, so close due to #788 unless @saramsey or @edeutsch objects

**Comment by edeutsch** [comment]
no objection. are we still providing monthly dumps to collaborators?

**Comment by saramsey** [comment]
Hi @dkoslicki I am still hoping to implement this issue. OK to reopen it?

**Comment by finnagin** [comment]
Closing since kg2 is in it's own repo will make an issue that links to this there.
