### ISSUE TITLE
think about switching KG1 predicates to having the "RTXKG1:" relation CURIE prefix

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#561]
Steve to discuss this with @amykglen

**Comment by saramsey** [comment]
to work on this with @amykglen on 11/27 at 2 PM PST

**Comment by saramsey** [comment]
all that is left to do here (hopefully) is to just update a bunch of keys in the top-level dictionary in `predicate-remap.yaml` that currently start with `Biolink:` to start with `RTXKG1:` instead (see git version history for this file, to see what keys we need to update)

**Comment by amykglen** [comment]
made the changes to `predicate-remap.yaml` - ready to test (I'll do so sometime soon)
