### ISSUE TITLE
node CUI:C1527116 from umls MTH has incorrect name (and category)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#563]
-- separating this issue out from #544 (orphan edges); copying over relevant info  --

Node `CUI:C1527116`, which was previously missing from KG2, **is** now in KG2 after rebuilding with the `umls-mth.ttl` file included, but its name seems off - it should be `Workers` (see: http://linkedlifedata.com/resource/umls/id/C1527116), but instead it's `Delusional disorder`, which is oddly the same name as the troublesome `MTH:NOCODE` node (discussed in #558)...

Here's this node's info from neo4j:
```
"properties": {
          "iri": "https://identifiers.org/umls/cui/C1527116",
          "synonym": "[]",
          "category_label": "protein",
          "deprecated": "False",
          "name": "Delusional disorder",
          "provided_by": "https://identifiers.org/umls/cui",
          "id": "CUI:C1527116",
          "category": "http://w3id.org/biolink/vocab/Protein",
          "update_date": "2019-08-02 10:32:18 GMT",
          "publications": "[]"
        }
```
(Its name is supposed to be `Workers`. And its category label of `protein` also seems incorrect.)

To begin isolating the problem, we ran `multi_owl_to_json_kg.py` with a two-line configuration file (`owl-load-inventory-test.yaml`) containing only `umls_semantictypes.ttl` and `umls-mth.ttl`, and saved the results to the file `kg2-test-mth.json`. In the output, the node indeed has the incorrect name/category:
```
{
  "id": "CUI:C1527116",
  "iri": "https://identifiers.org/umls/cui/C1527116",
  "name": "Delusional disorder",
  "full name": null,
  "category": "http://w3id.org/biolink/vocab/Protein",
  "category label": "protein",
  "description": null,
  "synonym": [],
  "publications": [],
  "creation date": null,
  "update date": "2019-08-02 10:32:18 GMT",
  "deprecated": false,
  "replaced by": null,
  "provided by": "https://identifiers.org/umls/cui"
}
```
It may also be worth noting that there are currently ~150k nodes with the name "Delusional disorder" in KG2 on `kg2endpoint2`:

<img width="524" alt="Screen Shot 2019-11-12 at 7 14 54 PM" src="https://user-images.githubusercontent.com/49423686/68732694-ca86b500-0580-11ea-9583-09353ae603d1.png">

while there are only 5 in the old version of KG2 on `kg2endpoint`:

<img width="480" alt="Screen Shot 2019-11-12 at 7 15 00 PM" src="https://user-images.githubusercontent.com/49423686/68732710-d3778680-0580-11ea-8a97-b56ad43e4326.png">

**Comment by amykglen** [comment]
So it turns out that the only instance CUI `C1527116` appears in `umls-mth.ttl` is as one of ~260k CUIs listed for the `NOCODE` node.
```
<https://identifiers.org/umls/MTH/NOCODE> a owl:Class ;
	skos:prefLabel """Delusional disorder"""@en ;
	skos:notation """NOCODE"""^^xsd:string ;
	skos:altLabel """Superior glenoid labrum lesion of unspecified shoulder, subsequent encounter"""@en , """Kaopectate Reformulated Aug 2006"""@en , """3-trifluoromethyl-4-nitrophenol"""@en , """Mouse Gastric Adenosquamous Carcinoma"""@en , """IRS2 wt Allele"""@en , """Transcription Factor AP-1"""@en , """Washington County, PA"""@en , """UVSSA gene"""@en , """Entire mesenteric artery"""@en , """Fabrol"""@en , """MIR1224 gene"""@en , """indocyanine green videoangiography: hypofluorescent defined areas of temporal aspect of midperipheral retina"""@en , """Mirn337 microRNA, human"""@en , """Drowning and submersion due to being washed overboard from other powered watercraft, subsequent encounter"""@en , """Driver of bus injured in collision with heavy transport vehicle or bus in nontraffic accident, initial encounter"""@en , """P-Tex brand of brompheniramine"""@en , """EHMT1 wt Allele"""@en , """Entire joint"""@en , """Nonexudative age-related macular degeneration, left eye, stage unspecified"""@en , """Hepatitis E antigen"""@en , """Unspecified occupant of snowmobile injured in nontraffic accident, subsequent encounter"""@en , """Nondisplaced comminuted fracture of shaft of radius, unspecified arm, initial encounter for open fracture type IIIA, IIIB, or IIIC"""@en , """CA3-AS1 gene"""@en , """Monoclonal Antibody Therapy"""@en , """Neonatal dehydration"""@en , """Arabic numeral 32"""@en , """Arabic numeral 33"""@en , """PhenX measure - respiratory - sleep apnea:-:Point in time:^Patient:-:PhenX"""@en , """bis(3-bis(4-chlorophenyl)methyl-4-dimethylaminophenyl)amine"""@en , """RNU6-874P gene"""@en , """Unilateral post-traumatic osteoarthritis, unspecified hip"""@en , """Displaced fracture of medial malleolus of left tibia, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing"""@en , """establishment of mitotic spindle localization"""@en , """Arabic numeral 38"""@en , """Frontom  ... [omitting the rest of this field...]
                       
         ...    [omitting many lines here]

	umls:cui """C2840705"""^^xsd:string ;
	umls:cui """C2840706"""^^xsd:string ;
	umls:cui """C2840707"""^^xsd:string ;
	umls:cui """C2905943"""^^xsd:string ;
	umls:cui """C2905940"""^^xsd:string ;
	umls:cui """C2905941"""^^xsd:string ;
	umls:cui """C2605622"""^^xsd:string ;
	umls:cui """C2905947"""^^xsd:string ;
	umls:cui """C2905944"""^^xsd:string ;
	umls:cui """C2905945"""^^xsd:string ;
	umls:cui """C0260453"""^^xsd:string ;
	umls:cui """C2905948"""^^xsd:string ;
	umls:cui """C2905949"""^^xsd:string ;
	umls:cui """C1527116"""^^xsd:string ;
	umls:cui """C1538412"""^^xsd:string ;
	umls:cui """C2862317"""^^xsd:string ;
	umls:cui """C2862316"""^^xsd:string ;
	umls:cui """C2853801"""^^xsd:string ;
	umls:cui """C1879319"""^^xsd:string ;
	umls:cui """C2862314"""^^xsd:string ;
	umls:cui """C3173980"""^^xsd:string ;
	umls:cui """C2700671"""^^xsd:string ;

         ...  [omitting more here - a total of ~260k such CUI lines are listed]
```
This explains why node `CUI:C1527116`'s name is off: `multi_owl_to_json_kg.py` creates a node for each of these CUIs, naming them with what's in `skos:prefLabel` ("Delusional disorder"), because normally additional CUIs would be considered xrefs. (But in the case of `NOCODE`, this is junk information.)

Excluding this `NOCODE` node seems like an obvious fix (#558); this will mean, however, that we're back to having no `CUI:C1527116` node in KG2, because that CUI doesn't appear anywhere else in UMLS .ttl files. Meaning, any edges that reference node `CUI:C1527116` will become orphan edges again (as will ~130k other edges that reference a CUI node in a similar situation to `CUI:C1527116`, I believe - TBD if we can find another way to get these missing CUIs...).

Final note: I modified `multi_owl_to_json_kg.py` to exclude `NOCODE` nodes and ran it again using a two-line configuration file (`owl-load-inventory-test.yaml`) containing only `umls_semantictypes.ttl` and `umls-mth.ttl`: the output (`kg2-test-mth.json`) contains only 6,402 nodes (vs. 262,929 before excluding `NOCODE`). And no instances of the word `NOCODE` (vs. 257,013 instances before).

**Comment by amykglen** [comment]
To think about: How _should_ multiple CUIs for the same node in a umls .ttl file be handled? We want to exclude `NOCODE` anyway so it isn't relevant here, but it seems like using `skos:prefLabel` as the name for all CUIs listed for a given node may not be correct? For example, see node `U000668` from `umls-mth.ttl`:
```
<https://identifiers.org/umls/MTH/U000668> a owl:Class ;
	skos:prefLabel """Diastolic blood pressure"""@en ;
	skos:notation """U000668"""^^xsd:string ;
	skos:altLabel """Daflon"""@en ;
	<https://identifiers.org/umls/MTH/LT> """TRD"""^^xsd:string ;
	umls:cui """C0428883"""^^xsd:string ;
	umls:cui """C0215217"""^^xsd:string ;
	umls:STY """T109"""^^xsd:string ;
	umls:STY """T121"""^^xsd:string ;
	umls:STY """T201"""^^xsd:string ;
	umls:hasSTY <https://identifiers.org/umls/STY/T109> ;
	umls:hasSTY <https://identifiers.org/umls/STY/T121> ;
	umls:hasSTY <https://identifiers.org/umls/STY/T201> ;
```
cui node id | name in kg2 in neo4j | real name for this cui
-- | -- | --
"CUI:C0428883" | "Diastolic blood pressure" | "[Diastolic blood pressure](http://linkedlifedata.com/resource/umls/id/C0428883)"
"CUI:C0215217" | "Diastolic blood pressure" | "[Daflon](http://linkedlifedata.com/resource/umls/id/C0215217)"

**Comment by amykglen** [comment]
opted to remove `umls-mth.ttl` from `owl-load-inventory.yaml` again, which resolved this problem - closing this issue and opened a separate one (#565) to figure out if there's any data in `umls-mth.ttl` we want to use

**Comment by saramsey** [comment]
OK, that seems like a sound decision.

I wonder if it would help to use the config option `load_on_cuis` in the umls2rdf config file.

**Comment by saramsey** [comment]
Latest (from KG 2.3.0:

<img width="580" alt="Screen Shot 2020-08-20 at 7 00 51 PM" src="https://user-images.githubusercontent.com/5562107/90843929-91e9e800-e317-11ea-8f7d-c0a70b1e0db8.png">
