### ISSUE TITLE
return_subgraph_through_node_labels returns empty result

### ISSUE THREAD

**Issue by power10dan** [RTXteam/RTX#564]
When I was using the test_weight_graph_with_google_distance, the return_subgraph_through_node_labels function returns the following:

```
Traceback (most recent call last):
  File "get_mesh_term_bench.py", line 59, in <module>
    bench_mark = Bench_GetMeshForAll()
  File "get_mesh_term_bench.py", line 14, in __init__
    self.g = self.generate_graph()
  File "get_mesh_term_bench.py", line 18, in generate_graph
    ['protein'], directed=False)
  File "../../reasoningtool/QuestionAnswering/ReasoningUtilities.py", line 642, in return_subgraph_through_node_labels
    raise CustomExceptions.EmptyCypherError(query)
CustomExceptions.EmptyCypherError: "No results returned in cypher query: 
MATCH path=(s:drug)-[]-(:protein)-[]-(t:anatomical_entity) 
WHERE s.id='naproxen' and 
t.id='UBERON:0001474' RETURN path"
```

The inputs of the function are the original inputs that were already there in the original RTX code base for the test_weight_graph_with_google_distance, which are souce_node = 'naproxen', source_node_label = 'drug', target_node = 'UBERON:0001474', target_node_label = 'anatomical_entity', and node_list = ['protein']. The graph that the neo4j API is querying from is kg1.

**Comment by dkoslicki** [comment]
On mobile, so this will be brief. KG1 uses 'chemical_substance' not 'drug' and IDs are CURIE IDs not names (eg: CHEMBL.COMPOUND:CHEMBL15939). The KG spec has evolved quite a bit, so some conventions changed and the examples in the doc aren't always up to date. Always good to head to the neo4j browser to verify

**Comment by power10dan** [comment]
Got it. I tried the following query and it worked nicely on the kg1 neo4j browser tool:

MATCH path=(s:chemical_substance {id: 'CHEMBL.COMPOUND:CHEMBL154'})-[]-(:protein)-[]-(t:anatomical_entity {id: 'UBERON:0001474'}) return path limit 100;

Although we should change this in the RTX code in order to reflect what you said, David.

**Comment by dkoslicki** [comment]
Closing due to #788
