### ISSUE TITLE
we should be loading some (~5) UMLS TTL files with load_on_cuis

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#565]
see #563 for the strangeness going on with the file `umls-mth.ttl` (Metathesaurus Names)

**to look into**: could our use of `load_on_codes` for MTH in `umls2rdf-umls.conf` be causing issues?
see this line from https://github.com/ncbo/umls2rdf:

> Note that 'CCS COSTAR DSM3R DSM4 DXP ICPC2ICD10ENG MCM MMSL MMX MTHCMSFRF MTHMST MTHSPL MTH NDFRT SNM' have no code and should not be loaded on loads_on_codes.

all of the `NOCODE` nodes we were getting in kg2 (which we filtered out in #558) came from files that should be using `load_on_cuis` rather than `load_on_codes` (MMSL, MTH, MTHMST, MTHSPL, and NDFRT)

**Comment by saramsey** [comment]
Yes, I like the idea of trying `load_on_cuis` here. Then inspecting the TTL file for weirdness.

**Comment by amykglen** [comment]
so `umls-mth.ttl` looks **good** when it's generated using `load_on_cuis`! no more craziness, it seems...

the `Workers` node we were having trouble with before looks great now:
```
<https://identifiers.org/umls/MTH/C1527116> a owl:Class ;
	skos:prefLabel """Workers"""@en ;
	skos:notation """C1527116"""^^xsd:string ;
	<https://identifiers.org/umls/MTH/RO> <https://identifiers.org/umls/MTH/C0022866> ;
	<https://identifiers.org/umls/MTH/RO> <https://identifiers.org/umls/MTH/C0024752> ;
	<https://identifiers.org/umls/MTH/RO> <https://identifiers.org/umls/MTH/C1306056> ;
	umls:cui """C1527116"""^^xsd:string ;
	umls:STY """T098"""^^xsd:string ;
	umls:hasSTY <https://identifiers.org/umls/STY/T098> ;
```
and here's that same node in `kg2-test-mth-load-on-cuis.json` (it has the correct name and category!):
```
{ 
   "id":"CUI:C1527116",
   "iri":"https://identifiers.org/umls/cui/C1527116",
   "name":"Workers",
   "full name":null,
   "category":"http://w3id.org/biolink/vocab/GroupOfPeople",
   "category label":"group_of_people",
   "description":null,
   "synonym":[  ],
   "publications":[  ],
   "creation date":null,
   "update date":"2019-11-27 23:19:04 GMT",
   "deprecated":false,
   "replaced by":null,
   "provided by":"https://identifiers.org/umls/cui"
}
```

**Comment by amykglen** [comment]
but `multi_owl_to_json_kg.py` might require some tweaks... (?) for example, it creates an 'xref' edge from `MTH:C1527116` to `CUI:C1527116`, which doesn't seem right... ?
```
{ 
   "subject":"MTH:C1527116",
   "object":"CUI:C1527116",
   "edge label":"xref",
   "relation":"http://purl.org/obo/owl/oboFormat#oboFormat_xref",
   "relation curie":"oboFormat:xref",
   "negated":false,
   "publications":[  ],
   "publications info":{  },
   "update date":"2018",
   "provided by":"https://identifiers.org/umls/MTH"
}
```
it seems like `MTH:C1527116` is a nonsensical node ID, since `C1527116` is a CUI?

**Comment by saramsey** [comment]
@amykglen to post list of TTL files that we are currently loading as LOAD_ON_CODE that should be changed to LOAD_ON_CUI

Then we need to fix the issue in `multi_owl_to_kg_json.py`

**Comment by amykglen** [comment]
these are all our TTL files currently using `load_on_codes` that **should** be using `load_on_cuis` (according to [this page](https://github.com/ncbo/umls2rdf)) in `umls2rdf-umls.conf`:

- MMSL
- MMX
- MTHCMSFRF
- MTHMST
- MTHSPL
- NDFRT

NOTE: MTH has already been switched to `load_on_cuis`, but still needs to be added back to `owl_load_inventory.yaml` (once this issue is fixed).

**Comment by amykglen** [comment]
I've made the code changes to address this issue and am in the process of testing/deploying - wanted to document this hurdle for the record:

`umls2rdf.py` was getting stuck on MTHSPL when it was loaded with `load_on_cuis`... even though the [documentation](https://github.com/ncbo/umls2rdf) says that file should use `load_on_cuis`...

switching it back to `load_on_codes` fixed this (the script completed and all appears well) 

I think we shouldn't worry about this (and just continue loading MTHSPL with `load_on_codes`) because:

1. we don't get a `NOCODE` node from this file when it's loaded with `load_on_codes` (but we do from the other 5 files that are supposed to use `load_on_cuis`)
2. on inspection, the file **looks** like it should work with `load_on_codes` (one CUI per ontology node)

perhaps there's just an error in the `umls2rdf` documentation...
