### ISSUE TITLE
Change mediKanren config.yaml setup process

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#567]
Would be nice to handle this using scp with just a prompt to ask which endpoint.

**Comment by dkoslicki** [comment]
@finnagin still relevant, or close due to #788?

**Comment by saramsey** [comment]
still relevant; please do not close

**Comment by dkoslicki** [comment]
Just checking if it it's still relevant @saramsey

**Comment by finnagin** [comment]
@saramsey Is this still relevant and if so should it be moved to the RTX-KG2 repo?

**Comment by finnagin** [comment]
removing myself and assigning @saramsey

**Comment by saramsey** [comment]
Since mediKanren now uses a KGX TSV export of RTX-KG2pre, this issue can be closed I think.
