### ISSUE TITLE
migrate RTX from rtx.ncats.io to arax.rtx.ai

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#574]

**Comment by saramsey** [comment]
TODO: need someone to audit rtx.ncats.io to make sure there isn't anything important in the host OS that we forgot to copy over

TODO: need someone to write a README.md for how to set up RTX in a brand-new Ubuntu 18.04 instance (to get the ball rolling, I saved the "docker run" command in a shell script https://github.com/RTXteam/RTX/blob/master/team-private/arax.md)

**Comment by saramsey** [comment]
Current status (20191206):
"production" RTX appears to be working now on arax.rtx.ai; handoff to ISB for testing to make sure nothing is broken or missing
docker container images (rtx1 and rtx2) copied to our S3 bucket for safe-keeping
copying of "issue259" files (~289 GB) to arax.rtx.ai is ongoing

**Comment by edeutsch** [comment]
Can you make my account edeutsch so it is aligned with all my other accounts?

**Comment by saramsey** [comment]
Oh, sorry, for some reason I thought you wanted ewdeutsch.

Should be done now (please test and LMK if it doesn't work as `edeutsch`).

**Comment by edeutsch** [comment]
Great, thanks, I am able to log in, but I can't run sudo:
edeutsch@ip-172-31-37-37:~$ sudo docker ps
[sudo] password for edeutsch: 

and I have no password. Can you fix that?

**Comment by saramsey** [comment]
TODO: update RTXConfig python code on running systems (e.g., arax.rtx.ai and all test installations) so that it gets the config.json file from:

`ssh:rtxconfig@arax.rtx.ai:/mnt/temp/config.json`

**Comment by saramsey** [comment]
Hi all,

So, I think we are going to have to push out a new version of RTXConfiguration.py. That module is hard-coded to pull the "config.json" file from "rtx.ncats.io", and that hostname is going away in nine days.

See code commit 46d09e5419128f034d7f90aaa846d45ec9c3bdd0.

https://github.com/RTXteam/RTX/commit/46d09e5419128f034d7f90aaa846d45ec9c3bdd0

I'm not entirely sure how to push this out or compile it. I see that under the python-flask-server directory there is a compiled version of this module:

![Screen Shot 2019-12-06 at 4 39 47 PM](https://user-images.githubusercontent.com/5562107/70365786-0e9b6b80-1848-11ea-90b7-e44765add6b4.png)

Can I hand off the task of updating this module on arax.rtx.ai?

Thanks,
Steve
![Screen Shot 2019-12-06 at 4 38 22 PM](https://user-images.githubusercontent.com/5562107/70365794-1bb85a80-1848-11ea-9d8d-f69a1e6a0b02.png)

**Comment by edeutsch** [comment]
It is all fine and install and working as far as I can tell. It is "pushed" out with a simple `git pull` and then restarting the services if necessary.
The compiling is something that is done on the fly by flask I guess. Nothing that the user needs to worry about or do.

As far as I'm concerned, everything is working and this can be closed.
