### ISSUE TITLE
UI can't find genes associated with Fraser syndrome, but such genes exist in KG1 neo4j

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#576]
the RTX UI can't seem to find any genes (proteins) associated with Fraser syndrome, but an analogous query in neo4j shows there are 5 such genes (proteins)...

here are the results of an attempt using the query graph builder (https://rtx.ncats.io/?m=135):

<img width="911" alt="Screen Shot 2019-12-06 at 12 52 44 PM" src="https://user-images.githubusercontent.com/49423686/70355592-65447d80-1827-11ea-9265-597e51a71831.png">

and here's the analogous query in neo4j (on kg1endpoint.rtx.ai; same node ID, etc..):

<img width="788" alt="Screen Shot 2019-12-06 at 12 56 31 PM" src="https://user-images.githubusercontent.com/49423686/70355791-d8e68a80-1827-11ea-8326-f7ff39917875.png">

**Comment by edeutsch** [comment]
I just tried turning off the cache, and even the canned example queries don't work. So it seems like communication with neo4j is perhaps not working correctly. We were lulled into thinking the system was working because the caching was efficiently returning results.

**Comment by amykglen** [comment]
ah, yep, that makes sense...

**Comment by edeutsch** [comment]
So, the problem I commented on now has been fixed.
But this bug reported in this issue persists.
I tried several other diseases. cardiac arrest, cataract, alzheimers, and they all returned reasonable results.
So it remains a mystery to me why Fraser syndrome does not return anything.

Here is the Cypher that is getting run (I think?):
MATCH (qg1:protein {})-[qg2]-(qg0:disease {`id`: 'DOID:0090001'}) WITH qg0.id as qg0, qg1.id as qg1, collect(distinct toString(id(qg2))) as qg2 RETURN {qg0:qg0, qg1:qg1} as nodes, {qg2:qg2} as edges

The following for "cataract" seems to return a useful result:
MATCH (qg0:protein {})-[qg2]-(qg1:disease {`id`: 'DOID:83'}) WITH qg1.id as qg1, qg0.id as qg0, collect(distinct toString(id(qg2))) as qg2 RETURN {qg1:qg1, qg0:qg0} as nodes, {qg2:qg2} as edges

Any reason the first would not work and the second would?

**Comment by edeutsch** [comment]
Escalating this to @finnagin or @dkoslicki because I don't know how to proceed.

**Comment by finnagin** [comment]
Looks like the issue is that the ui points to the neo4j instance in arax.rtx.ai:7474 which is running a slightly older KG build than kg1endpoint.rtx.ai:7474 and does not have the edges for Fraser syndrome.

**Comment by amykglen** [comment]
got it, thanks! that's interesting... is switching the UI/API over to the latest KG1 build something we'd want to do at some point?

**Comment by saramsey** [comment]
subsumed by #591 and #595
