### ISSUE TITLE
Change location of RTX config file from /mnt/temp/config.json to something more sane

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#577]

**Comment by saramsey** [comment]
Save a copy of config.json (WITH THE PASSWORDS XXXX'd OUT) in GitHub as an example

**Comment by saramsey** [comment]
This is mostly tricky from an operations/deployment standpoint. Recommend we do this *after* the demo.

**Comment by dkoslicki** [comment]
@saramsey did we ever get around to doing this? I vaguely recall we did, so LMK if we should close per #788.

**Comment by saramsey** [comment]
yes, fixed per #1101
