### ISSUE TITLE
refactor codes for issue #49

### ISSUE THREAD

**Issue by DeqingQu** [RTXteam/RTX#58]
Some functions in the following files are similar to the functions in QueryBioLink.py and OrangeBoard.py, and are needed to be refactored.

code/reasoningtool/kg-construction/QueryBioLinkExtended.py
code/reasoningtool/kg-construction/UpdateNodesInfo.py
code/reasoningtool/tests/QueryBioLinkExtendedTests.py

**Comment by saramsey** [comment]
this is a good issue for post-hackathon

**Comment by dkoslicki** [comment]
Is this still relevant given #49 is closed?

**Comment by dkoslicki** [comment]
Closing due to #788
