### ISSUE TITLE
networkx node attribute is now nodes

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#581]
Baffling breakage in Q3Solution.py was traced to the apparent situation where the networkx class no longer defines a node attribute. It is now nodes.

See release notes:
https://networkx.github.io/documentation/stable/release/release_2.4.html
under Deprecations.
Graph Object methods removed (marked as deprecated 2.1)
    G.add_path
    G.add_cycle
    G.add_star
    G.nodes_with_selfloops
    G.number_of_selfloops
    G.selfloop_edges
    These are now NetworkX functions, e.g. nx.add_star(G, 5)
    G.node –> use G.nodes
    G.fresh_copy –> use G.__class__

See checkin:
https://github.com/RTXteam/RTX/commit/b6dd4bd36f03cbd192dce8fff71be78b1465ca16

This may well be pervasive in other parts of the code.
This would not be visible until the local machine is running networkx 2.4, which rtx.ncats.io and arax.rtx.ai now are.

**Comment by dkoslicki** [comment]
Closing due to #788
