### ISSUE TITLE
tsv-to-neo4j.sh prompts for a neo4j password; is there any way around this?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#584]
prompting for a password is reasonable from a security standpoint but kinda works against automation; maybe have it check for a password in a local file, and only fall back on prompting for a password to be entered on STDIN if the local file cannot be found?

**Comment by saramsey** [comment]
see #592 which partially (but not fully) addresses this issue with `tsv-to-neo4j.sh`

**Comment by dkoslicki** [comment]
@saramsey close due to #788? Or keep open?

**Comment by saramsey** [comment]
please keep this issue open, thanks

**Comment by kvarforl** [comment]
Added pull request #844 with changes to `prompt_for_password_and_save_to_temp_file.py`

**Comment by saramsey** [comment]
Hi Lindsey, nice work. Can you merge these five commits into the `kg2-curie-refactoring` branch?

**Comment by saramsey** [comment]
OK thanks, I slightly changed things in the `kg2-curie-refactoring` branch, and renamed the script, but it is working now!  Thank you!
