### ISSUE TITLE
update report_stats_on_json_kg.py so that it can optionally analyze edges by simplified predicates

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#586]

**Comment by amykglen** [comment]
Made the changes for this - you can now optionally use the flag `--useSimplifiedPredicates` when running `report_stats_on_json_kg.py` to make it analyze edges by their simplified predicates.

I also went ahead and made `build-kg2.sh` use this flag when running `report_stats_on_json_kg.py` on `kg2-simplified.json`. (That makes sense, right?)
