### ISSUE TITLE
lowercase shell variable names in bash scripts for KG2

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#593]
https://unix.stackexchange.com/questions/42847/are-there-naming-conventions-for-variables-in-shell-scripts

**Comment by dkoslicki** [comment]
@saramsey still an issue? Or close per #788?

**Comment by saramsey** [comment]
still an issue; slated for summer 2020 implementation since we always have higher-priority issues

**Comment by saramsey** [comment]
OK I have merged all the shell script updates for this issue, with everything in `kg2-curie-refactoring`, in a new sub-branch `kg2-curie-refactoring-issue593`. I have asked @kvarforl to test the code in the `kg2-curie-refactoring-issue593` branch with a full build on `kg2steve.rtx.ai`. Once that build completes, we'll look at merging the `kg2-curie-refactoring-issue593` branch into `kg2-curie-refactoring` and then into `master`.

**Comment by saramsey** [comment]
Tagging @ericawood so she is aware of this.

**Comment by ericawood** [comment]
Would you like the Snakefile and build-kg2-snakemake.sh to follow this convention as well?

**Comment by saramsey** [comment]
> @saramsey Would you like the Snakefile and build-kg2-snakemake.sh to follow this convention as well?

For `build-kg2-snakemake.sh`, yes.

For the Snakefile, I suppose we should follow Python coding conventions, in which module-level global constants are typically ALLCAPS. Does that make sense?

**Comment by saramsey** [comment]
Hi @ericawood please note that in the `kg2-curie-refactoring-issue593` branch (which we intend to merge into the `kg2-curie-refactoring` branch as soon as testing is complete), the lowercasing of shell variables is already done (though untested). You may wish to consider doing some kind of "git cherry-pick" to pull those changes into the `kg2-curie-refactoring` branch for your testing?

**Comment by ericawood** [comment]
@saramsey So to clarify, would you prefer if I committed the lowercasing of `build-kg2-snakemake.sh` shell variables work to `kg2-curie-refactoring`? (Those changes are also untested)
