### ISSUE TITLE
write script that generates a slimmed down version of KG2 for easier computation

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#597]
documenting Steve's idea to create a slimmed down or lightweight KG2 that includes only bare-bones node/edge properties (e.g., perhaps only `id`, `name`, `full_name`, `category_label` for nodes...)

this could bring down the graph's size to a couple GB, making it a lot easier to analyze/store/etc... (a lot of KG2's size comes from properties like `description`, `publications`, and `publications_info`, which aren't needed for some use cases)

the (Python) script could take in the full KG2 json file (`kg2-simplified.json`) and output a slimmed down json file.

**Comment by saramsey** [comment]
For edges in the slimmed-down graph, I think all we may need (for now) is 
`simplified_relation_curie`, `subject`, `object`, `simplified_edge_label`, and `provided_by`

**Comment by saramsey** [comment]
See this python script for an example of style and formatting that we use, and for how we use `argparse`:

https://github.com/RTXteam/RTX/blob/master/code/kg2/merge_graphs.py
