### ISSUE TITLE
Full text search now missing

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#598]
On http://arax.rtx.ai:7474/browser/
```
CALL db.index.fulltext.queryNodes("FullTextIndex", "TRIO") YIELD node, score return node
Neo.ClientError.Procedure.ProcedureNotFound
Neo.ClientError.Procedure.ProcedureNotFound: There is no procedure with the name `db.index.fulltext.queryNodes` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
```

**Comment by finnagin** [comment]
@dkoslicki I think we are keeping full text indexing off of arax.rtx.ai since it requires that we have it out of read only mode. 

However, it looks like it is also not currently enabled in either kg2endpoint2.rtx.ai or kg2endpoint.rtx.ai. I'll look into why that is.

**Comment by saramsey** [comment]
@finnagin not sure if I understood you correctly, but it sounds like you are saying that we could (in principle) host two Neo4js with the same underlying KG-- one (call it server-rw) that is read/write and has a full-text index, and that does not have direct web UI / REST API access from anything other than the ARAX server; and another Neo4j (call it server-ro) that is read-only, which does have web UI / REST API access from the outside world. If so, I agree - this might be a workaround. It should be possible to lock down (via host firewall rules perhaps) access to "server-rw" to *just* connections from the ARAX server.

**Comment by finnagin** [comment]
@saramsey Yeah I was thinking that would be the best solution though it might be useful to access it from the browser as well. Maybe we could host a separate instance with rw access but a different user/pass?

**Comment by saramsey** [comment]
if we need to regenerate a full index each time we update Neo4j, this sounds like something that maybe should be put in a new "System Operation SOP" in the Wiki; @finnagin can you help with that?

**Comment by dkoslicki** [comment]
@finnagin @saramsey did we come to a decision about this?

**Comment by saramsey** [comment]
@finnagin  to talk to @dkoslicki  and @edeutsch to see if they want/need full-text indexing in Neo4j for KG2, in light of the existence of a KG2 node index.

**Comment by finnagin** [comment]
@dkoslicki , @edeutsch It this something that KG2 node index can do? 

If it can't, @saramsey and I have been discussing the feasibility of spinning up a new non read only ec2 instance for kg2 so we can have one with full text indexing enabled if needed.

**Comment by edeutsch** [comment]
I do not see any reason that KGNodeIndex needs full text search. It precomputes the index on the list of CURIEs and names. It does not use description.

**Comment by dkoslicki** [comment]
Closing this ancient issue as it's not really relevant any more
