### ISSUE TITLE
Write QueryJASPAR class to query JASPAR's REST API

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#6]
_From @saramsey on December 9, 2017 1:13_

Article describing the REST API for JASPAR is on bioArxiv:

https://www.biorxiv.org/content/early/2017/07/06/160184

_Copied from original issue: dkoslicki/NCATS#126_

**Comment by saramsey** [comment]
I'm going to mark this Enhancement, am thinking it is probably a post-hackathon kind of thing?

**Comment by dkoslicki** [comment]
Not relevant anymore? Closing due to #788, but @saramsey LMK if should keep open
