### ISSUE TITLE
ARAX and DSL

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#600]
Hi everyone, I checked in some stubs for ARAX-Overlay and ARAX-Expander. No functionality yet, but this is my suggested framework for how this could integrate nicely. Feel free to push back and suggest a modification or different approach. I don't have a lot of Python experience. I also put my opinions on how to do this nicely in the README here:
https://github.com/RTXteam/RTX/tree/master/code/ARAX
Again, feel free to discuss and suggest changes. Maybe as a separate issue.

Also, I put a Google doc for the place to start contributing your ideas on how the DSL should work here:
https://docs.google.com/document/d/1VweSOVxZS-7rXMc2ZhaZ6fpqYKaxRH_Vht0-PXRmy84/edit
Please contribute and comment.

**Comment by edeutsch** [comment]
I have checked in a new version of ARAX_expander.py. @amykglen I think this version should be good to start hacking on. Please try running its main() and make sure it works for you, and also if it makes sense. I managed to get on slack, so feel free to ask questions there..

**Comment by dkoslicki** [comment]
Closing due to #788 and the DSL now being implemented
