### ISSUE TITLE
Get COHD working with ARAX_overlay

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#606]
- [x] Make a stub
- [x] create an API registry somewhere that points to COHD as a KP and where our parser for it is
- [x] implement paired concept freq
#~~- [ ] implement associated concept freq~~ **not too useful for reasoning**
- [x] implement chi square
- [x] implement obs exp ratio
#~~- [ ] implement relative frequency~~ **directional, so since KG1 is non-directional edges, not implementing this one (though it would be easy)
#~~- [ ] implement get_datasets~~  **defaulting to dataset 3 as this is the most comprehensive**
- [x] **allow COHD to overlay virtual edges**

**Comment by dkoslicki** [comment]
Need to decide if I only decorate existing edges, or also create new edges (eg. KG has two diseases with no edge between them, but COHD can tell us how frequently they co-occur).

**Comment by edeutsch** [comment]
One might be obligated to add an edge to the query graph to give them a home. Or maybe not if it is ostensibly part of the question. Perhaps such informational edges can just live peacefully in the knowledge graph to be used by scoring algorithms and available to the interested client, even they are not visible in the formal answers. Feel free to add them now, but make a careful note of such creativity and we should have a future discussion about how we would like things to work and then advocate our position to the consortium

**Comment by dkoslicki** [comment]
Sounds good: I put it on the agenda for the mini-hackathon so we can discuss it (and so I'm clear about how exactly those edges are to be added).

**Comment by dkoslicki** [comment]
Note to self: refactor `OCI.decorate()` to basically be the same as `ARAXOverlay.apply()` to avoid the if statements, etc.

**Comment by dkoslicki** [comment]
Closing as b8e8c58 finishes the to do's.
