### ISSUE TITLE
Find a KS that allows for pathway->tissue edges

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#61]
Currently edge types for pathways are only "participates in"

**Comment by saramsey** [comment]
OK, I think I may know how to do this.  Apparently the Uber Ontology has a "capable of" relationship whose source is a UBERON anatomy term and whose target is a Gene Ontology biological process term. See the field "capable of" in the following webpage:

http://bioportal.bioontology.org/ontologies/UBERON?p=classes&conceptid=UBERON%3A0000945

**Comment by dkoslicki** [comment]
Great! I think that will be quite useful (especially if we can connect GO to more than just proteins and microRNAs as it currently is; perhaps GO->phenotype too, will make a separate issue).

**Comment by dkoslicki** [comment]
Closing due to #788 and ARAX/KG2
