### ISSUE TITLE
kg_id field on edge bindings should be a string in QueryGraphReasoner's results

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#612]
In the results returned by [QueryGraphReasoner](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/QueryGraphReasoner.py), an edge binding's `kg_id` is currently a list:
```
 'edge_bindings': [{'kg_id': ['995723'], 'qg_id': 'e01'}],
```
But [according to RTX_0.9.2_Swagger2.0.yaml](https://github.com/RTXteam/RTX/blob/master/code/UI/OpenAPI/python-flask-server/RTX_0.9.2_Swagger2.0.yaml#L668-L670), `kg_id` should be a string.

NOTE: This does not seem to be critical to address for the ARAX demo.

**Comment by dkoslicki** [comment]
@amykglen is this issue still relevant? #788?

**Comment by amykglen** [comment]
It's no longer relevant to me, as Expand doesn't use this property anymore, but it's possible there's still an adjustment needed here. Or maybe there are some changes coming to this field in the ReasonerStd soon anyway? @edeutsch would know.

**Comment by finnagin** [comment]
@edeutsch is this still relevant to you? If not I think we can go ahead and close.

**Comment by edeutsch** [comment]
ancient history. closing.
