### ISSUE TITLE
How to get the UI running on your local machine

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#616]
If you are running ARAX_query and friends on your local machine and are generating nice JSON, but you want to be able to visualize these JSON beasts through the UI, here's how you can do that (at least it worked for me on my Windows box):

Step 1) Install one more needed modules for CORS support
`pip3 install flask_cors`

Step 2) Pull the latest `__main__.py` from the demo branch
Need latest demo for `code/UI/OpenAPI/python-flask-server/swagger_server/__main__.py`

Step 3) Edit the rtx.js to point to your local machine (don't commit this to the repo!)
line 13 of `code/UI/interactive/rtx.js` should become:
`var baseAPI = "http://localhost:5001/devED/";`

Step 4) Start the Flask server (blocks this shell and runs until ^C)
`cd code/UI/OpenAPI/python-flask-server`
`python3 -m swagger_server`

Step 5) Point your web browser to the UI files on your local filesystem, something like:
`file:///Repositories/GitHub/RTX/code/UI/interactive/index.html?m=2`
(the m number is the message id that you want to view in the UI)

By changing the m number, you should be able to view the messages you are creating and storing via ARAQ_Query {make sure you don't have 
return(store=false)
in your DSL otherwise there's no m number}

**Comment by saramsey** [comment]
Thank you Eric!  This looks like good material for a section of the README.md file in code/UI, maybe?

**Comment by dkoslicki** [comment]
Also, @edeutsch , you mind if I add the line `//var baseAPI = "http://localhost:5001/devED/";` at line 14 in rtx.js? Just so I quickly switch back and forth (without accidentally pushing the change to my branch/master/demo with that uncommented)?

**Comment by edeutsch** [comment]
@saramsey, fine with me, although this recipe may just a temporary arrangement

@dkoslicki, yes, sounds like a good idea!

**Comment by dkoslicki** [comment]
@saramsey I copied the info on the wiki under dev info:
https://github.com/RTXteam/RTX/wiki/Dev-info

**Comment by dkoslicki** [comment]
Closing due to #788 and this info now in the wiki
