### ISSUE TITLE
Some drugs missing from new standardized KG

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#62]
Eg. on [old KG](http://rtx.ncats.io:7473/browser/): ``match (n:pharos_drug{name:"gne-493"}) return n`` finds this drug, while on the [new KG](http://rtxdev.saramsey.org:7674/browser/): ``match (n:chemical_substance{description:"gne-493"}) return n`` doesn't return anything.

**Comment by saramsey** [comment]
ETA for new KG to show up on rtxdev:  21:00 PDT April 12

**Comment by dkoslicki** [comment]
Awesome! Thanks Steve!

**Comment by dkoslicki** [comment]
By the way, feel free to do what you need to on rtxdev. I had started the 7674 container earlier today but am finished with it now (so once it’s pushed you can shut down the ec2 instance). Or I can now, just want to make sure it’s not up all night unnecessarily.
