### ISSUE TITLE
ARAX_expander mis-mapping Neo4j node/edge properties to API object model?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#630]
When calling expander, it appears that Neo4j node/edge attributes may be mis-mapped to the API object model. For example, with the following query:
```
query = {"previous_message_processing_plan": {"processing_actions": [
            "create_message",
            "add_qnode(name=CHEMBL.COMPOUND:CHEMBL1276308, id=n00)",
            "add_qnode(type=protein, is_set=true, id=n01)",
            "add_qedge(source_id=n00, target_id=n01, id=e00)", 
            "expand(edge_id=e00)",
            "return(message=true, store=false)"
        ]}}
```
Then `message.knowledge_graph.edges` contains
```
{
    "confidence": 0.01463665774,
    "defined_datetime": null,
    "edge_attributes": null,
    "evidence_type": null,
    "id": "520369",
    "is_defined_by": "RTX",
    "negated": null,
    "provided_by": "ChEMBL",
    "publications": null,
    "qedge_id": "e00",
    "qualifiers": null,
    "relation": "targets",
    "source_id": "CHEMBL.COMPOUND:CHEMBL1276308",
    "target_id": "UniProtKB:Q15746",
    "type": "physically_interacts_with",
    "weight": null
  }
```
However, in [KG1](http://arax.rtx.ai:7474/browser/) with the cypher command
```
match p= (n:chemical_substance{id:"CHEMBL.COMPOUND:CHEMBL1276308"})-[]-(:protein) return p limit 5
```
The drug-target binding probability of `0.01463665774` should really be an `edge_attribute` instead of a `confidence` (especially since it was provided by a different KP on a certain date, etc.). This will become increasingly important with KG2 to map Neo4j node/edge **properties** to API object model **attributes** whenever they fall outside of the standard object model **properties**. 

This is mainly an issue for KG2, so low priority for now, but a thing to keep in mind.

**Comment by amykglen** [comment]
So (for KG1) the 'confidence' property is actually set somewhere within QueryGraphReasoner's realm, I believe when it calls a function in FormatOutput.py - I think [this](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/FormatOutput.py#L319) is the line. (For KG1 expand, all of the property mapping is currently done by QueryGraphReasoner.) So I'm not super familiar with that code, but can change it (to instead add that info as an EdgeAttribute) if desired!

As for the relevance of this for KG2: Yes, definitely sounds good to map neo4j node/edge properties to API object model NodeAttributes/EdgeAttributes when they fall outside the standard object model properties - that's exactly how I've handled it for the new KG2 expand. :)

**Comment by edeutsch** [comment]
I think it was my decision to map the drug binding probability to the confidence attribute. It seemed appropriate that if the binding probability is low, this should translate into a low confidence edge.

**Comment by dkoslicki** [comment]
Maybe post-demo huddle about how to really handle `confidence` in the way we want to (and not just the way QueryGraphReasoner is doing it)? Setting low-prio

**Comment by amykglen** [comment]
sounds good!

**Comment by amykglen** [comment]
I think this issue can be closed: when I moved `expand` away from `QueryGraphReasoner`, I made it map 'probability' on KG1 edges to `EdgeAttribute`s. So now no edges coming from `expand` have a `confidence` filled out.

Here's what the edge you shared from your query looks like now (on beta):
```
      {
        "edge_attributes": [
          {
            "name": "probability",
            "value": 0.01463665774
          }
        ],
        "id": "CHEMBL.COMPOUND:CHEMBL1276308--physically_interacts_with--UniProtKB:Q15746",
        "is_defined_by": "ARAX/KG1",
        "provided_by": "ChEMBL",
        "qedge_id": "e00",
        "relation": "targets",
        "source_id": "CHEMBL.COMPOUND:CHEMBL1276308",
        "target_id": "UniProtKB:Q15746",
        "type": "physically_interacts_with"
      }
```
