### ISSUE TITLE
Document DSL functionality

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#631]
We should start a markdown document somewhere enumerating:
- [x] the capabilities of ARAX
- [x] each of the components
- [x] the KP's utilized in `overlay` 
- [x] the brain underlying `expand`
- [x] and the KP's utilized to construct KG1.

**Comment by dkoslicki** [comment]
API list in `ARAX/KnowledgeSources`

**Comment by dkoslicki** [comment]
@finnagin Note that 04febd2 touched your code, so be sure to merge overlay into filter before doing more work. 

But good news is we have a (very basic) auto-gen documentation of the capabilities of `overlay` and `filter_kg`! See [this markdown doc](https://github.com/RTXteam/RTX/blob/overlay/code/ARAX/Documentation/test.md)

**Comment by dkoslicki** [comment]
TOC added via https://ecotrust-canada.github.io/markdown-toc/

**Comment by dkoslicki** [comment]
Finally got it. thanks `md-toc`

**Comment by saramsey** [comment]
I think this is now done (to first-order approximation) for `ARAX_resultify.py`.

**Comment by dkoslicki** [comment]
Note the [good suggestions](https://github.com/RTXteam/RTX/issues/650#issue-571608423) Eric had in #650 about making this more streamlined. But would take a fair bit of re-factoring that I don't have time before my flights

**Comment by dkoslicki** [comment]
closing in favor of #650. Steve's README documents the capabilities of ARAX
