### ISSUE TITLE
Must all edge attribute values be strings?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#634]
@edeutsch Per [these lines](https://github.com/RTXteam/RTX/blob/demo/code/UI/OpenAPI/python-flask-server/RTX_0.9.3_Swagger2.0.yaml#L954-L957) it appears all edge attribute values should be a string. Is this accurate? For everything @finnagin and I have been doing, they make most sense as floats (or of types specified by [this line](https://github.com/RTXteam/RTX/blob/demo/code/UI/OpenAPI/python-flask-server/RTX_0.9.3_Swagger2.0.yaml#L947)). Mind clarifying?

**Comment by edeutsch** [comment]
This is accurate, but not really intended. Careless modeling I suppose. It really should be a type of `any`, with the type specified in the field `type`. I am uncertain if the framework mandates a string. What happens if you set the value to a float? Does it crash? or does it convert it to a string automatically? Next week I can try adjusting the schema to what it should be.

**Comment by dkoslicki** [comment]
The problem is that `ARAX_filter_kg` and other components sometimes expect the value to be a float (or of the type indicated in the `type` field). But things like `numpy.inf`, `float(-inf)`, etc. don't appear to play well with `print(json.dumps(ast.literal_eval(repr(message.knowledge_graph.edges)), sort_keys=True, indent=2))`. Thankfully, @finnagin has been automatically converting to `float` in his filter code, so it's mainly:
1. a dev debugging issue
2. an issue to address moving forward to figure out what the `type` field should really be given that [the example](https://github.com/RTXteam/RTX/blob/demo/code/UI/OpenAPI/python-flask-server/RTX_0.9.3_Swagger2.0.yaml#L948) in the `yaml` doc is `"localization"` with an [example value of](https://github.com/RTXteam/RTX/blob/demo/code/UI/OpenAPI/python-flask-server/RTX_0.9.3_Swagger2.0.yaml#L954-L957) of a string `"MFC cells"`

**Comment by dkoslicki** [comment]
Moving to low-prio since this seems like a discussion to be had with the standards group post-demo.

**Comment by dkoslicki** [comment]
@edeutsch any recent clarification on this? Or should we continue to have a mix of strings and floats as edge attribute values? #788

**Comment by edeutsch** [comment]
I think a mix of strings, floats, ints should be allowed. This is on the docket for discussion in the coming weeks at the Standard API calls. Probably can close this. I think we agreed to move ahead with these types for ARAX.
