### ISSUE TITLE
ETL of Reactome

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#636]
PMI/UAB team requests that Reactome be ETL'd into KG2, including evidence codes, assay types, and provenance information (including PMIDs) for assertions about interactions and pathways.

**Comment by saramsey** [comment]
Download page for Reactome is here:
https://reactome.org/download-data

Seems like a MySQL dump is available.

**Comment by saramsey** [comment]
In light of #1215, marking #636 as high priority.

**Comment by ericawood** [comment]
This appears to be complete in `KG2.6.0`:

`match (n {provided_by: 'identifiers_org_registry:reactome'}) return count(n)`

count(n)
--|
67306

`match ()-[e]-(m) where "identifiers_org_registry:reactome" in e.provided_by return count(distinct e.id)`

count(distinct e.id)
--|
153717
