### ISSUE TITLE
Interfacing with SemMedDB

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#64]
We need functionality to interface with SemMedDB. @finnagin has already accomplished a lot of this, but we still need to come up with a (quick?) way to map nodes (and any required properties) to entities in SemMedDB. 

This is a placeholder issue for what Finn and I talked about today.

**Comment by dkoslicki** [comment]
@finnagin your slack message indicated that SemMedDB code is (almost?) ready for integration. Please comment on this issue when the code is pushed and ready for me to integrate and test.

**Comment by finnagin** [comment]
@dkoslicki Code is pushed and ready to integrate/test. Let me know if you run into any issues or if there is any functionality I need to add.

**Comment by dkoslicki** [comment]
Awesome! I'll see if I can test it tomorrow or Friday.

**Comment by finnagin** [comment]
Closing this since this was finished a while ago.
