### ISSUE TITLE
ARAX_expander.py should still add nodes if they aren't connected to edges

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#640]
For examples, say the message is:
```
query = {"previous_message_processing_plan": {"processing_actions": [
            "create_message",
            "add_qnode(name=DOID:9406, id=n00)",
            "add_qnode(type=chemical_substance, is_set=true, id=n01)",
            "add_qnode(name=DOID:8394, id=n02)",
            "add_qedge(source_id=n00, target_id=n01, id=e00)",
            "expand(edge_id=e00)"
```
Then `DOID:8394` should still be added to the KG (someone might want to do something with it, say, get a single node just to look at its attributes).
Perhaps there's some feature of `expand()` that I'm not aware of? Like `expand(node_id=n02)`?

**Comment by edeutsch** [comment]
Perhaps a philosophical discussion needs to be had about this? If there is a single node in the QueryGraph, then this is treated as a "What is" question. However, if there are >1 nodes and >0 edges, then I would say that any unconnected nodes should return an error. There used to be some basic checking code to make sure that the QueryGraph was reasonable before sending it to the QueryGraphReasoner:
 https://github.com/RTXteam/RTX/blob/02fd462816a554eeebd820cc8e8e7dcf65ae3775/code/UI/OpenAPI/python-flask-server/RTXQuery.py#L289

but this code isn't called any more I don't think.
I wonder if we should have some QueryGraph sanity checking code before feeding it into our system?

**Comment by dkoslicki** [comment]
I do think having a discussion about this would be great: the mathematician in me says a subgraph is still a subgraph even if it has disconnected components (including one or more single nodes). : )

**Comment by edeutsch** [comment]
It is a valid subgraph, but in the paradigm of a QueryGraph as a question, what would a disconnected node mean? "Which proteins are targeted by ibuprofen, and oh by the way what is hammertoe?"
?

**Comment by dkoslicki** [comment]
I'm imagining that the ARS might pose a question like: "how are bioentities X and Y related"? So given two disconnected nodes, try to find reasonable paths connecting them (without paths/edges being specified in the QG).  Or "are bioentities X and Y well represented in the literature? We could answer that current question now by (given a KG with just the two disconnected nodes X and Y), `overlay` them with the NGD from PubMed. Similarly, "is X every used to treat Y?" even if KG1 and KG2 don't have (X)-[:indicated_for]-(Y), we could reach out to COHD to see from EHR's if doctors are using X to treat Y.

**Comment by edeutsch** [comment]
I agree with everything you're saying *except* that those nodes would be unconnected.

"how are bioentities X and Y related" should be specific nodes X and Y with an edge of type "any" or NULL between them. Perhaps with a QEdge attribute allow_intermediate_nodes_and_edges=true

"are bioentities X and Y well represented [together] in the literature" also same as above but with an edge type=related_by_literature

"is X every used to treat Y?" are definitely connected by edge type=indicated_for

What I do think we need to be ready to do is break the chains of thinking that a QueryGraph edge means we must go to KG1 with cipher. I think we need another layer in ARAXQuery that studies the QueryGraph and then decides how to best answer the question based on all the KSs/KPs at our disposal using our DSL, not just going straight to KG1 cipher ala QueryGraphReasoner.

**Comment by dkoslicki** [comment]
+1 @edeutsch The whole “how to properly study the QG and not just default to KG1/2 and reach out to KP’s instead” has been on my mind  (as can be seen in things like my initial attempts to enumerate KP’s in the `KnowlegeProviders` folder and the comments in the [code](https://github.com/RTXteam/RTX/blob/overlay/code/ARAX/ARAXQuery/Overlay/overlay_clinical_info.py#L28) and other such places)

**Comment by amykglen** [comment]
I think this issue can be closed - Expand (and Resultify) actually now work for such query graphs (see: https://arax.rtx.ai/?m=2327, which corresponds to the original DSL @dkoslicki posted), and I think the debate over whether such query graphs should be allowed is happening in #772.
