### ISSUE TITLE
allowable_parameters seems a bit odd

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#650]
I'm trying to do the documentation thing for ARAX_messenger and struggling to grok this block here:
https://github.com/RTXteam/RTX/blob/93fca5f3d14139f790998f2c62ed6f52e3089a76/code/ARAX/ARAXQuery/ARAX_overlay.py#L239

        if message and parameters and hasattr(message, 'query_graph') and hasattr(message.query_graph, 'edges'):
            allowable_parameters = {'action': {'overlay_clinical_info'},
                                    'paired_concept_freq': {'true', 'false'},
                                    'observed_expected_ratio': {'true', 'false'},
                                    'chi_square': {'true', 'false'},
                                    'virtual_edge_type': {self.parameters['virtual_edge_type'] if 'virtual_edge_type' in self.parameters else None},
                                    'source_qnode_id': set([x.id for x in self.message.query_graph.nodes]),
                                    'target_qnode_id': set([x.id for x in self.message.query_graph.nodes])
                                    }
        else:
            allowable_parameters = {'action': {'overlay_clinical_info'},
                                    'paired_concept_freq': {'true', 'false'},
                                    'observed_expected_ratio': {'true', 'false'},
                                    'chi_square': {'true', 'false'},
                                    'virtual_edge_type': {'any string label (optional, otherwise applied to all edges)'},
                                    'source_qnode_id': {'a specific source query node id (optional, otherwise applied to all edges)'},
                                    'target_qnode_id': {'a specific target query node id (optional, otherwise applied to all edges)'}
                                    }

allowable_parameters seems to be leading a double life here. sometimes documentation, sometimes allowed values. If the allowed values are specified, then there's no documentation. e.g. paired_concept_freq has no documentation, all I know is that it can be true or false, not so helpful.

What about changing it so that both documentation and allowed values can be specified with something like:

        allowable_parameters = {'action': {
                                    'description': 'Action to execute within this domain',
                                    'allowed_values': { 'overlay_clinical_info'} },
                                'paired_concept_freq': {
                                    'description': 'A mysterious parameter',
                                    'allowed_values': {'true', 'false'} },
                                'observed_expected_ratio': {
                                    'description': 'Also a mysterious parameter',
                                    'allowed_values': {'true', 'false'} },
                                'chi_square': {
                                    'description': 'Chi squares are usually floats, but there they should true or false',
                                    'allowed_values': {'true', 'false'} },
                                'virtual_edge_type': {
                                    'description': 'any string label (optional, otherwise applied to all edges)',
                                    'allowed_values': { str() } },
                                'source_qnode_id': {
                                    'description': 'a specific source query node id (optional, otherwise applied to all edges)',
                                    'allowed_values': { str() } },
                                'target_qnode_id': {
                                    'description': 'a specific target query node id (optional, otherwise applied to all edges)',
                                    'allowed_values': { str() } }
                                }

        if message and parameters and hasattr(message, 'query_graph') and hasattr(message.query_graph, 'edges'):
            allowable_parameters['virtual_edge_type']['allowed_values'] = {self.parameters['virtual_edge_type'] if 'virtual_edge_type' in self.parameters else None}
            allowable_parameters['source_qnode_id']['allowed_values'] = set([x.id for x in self.message.query_graph.nodes])
            allowable_parameters['target_qnode_id']['allowed_values'] = set([x.id for x in self.message.query_graph.nodes])

This way there is always a description for the documentation (and a nice error message if the checker deems the value not allowed)

The documentation code could need to be updated a bit to have two components, description and allowed_values.

Not sure about how to express any string.

What do you think?

**Comment by saramsey** [comment]
Huh. In `ARAX_resultify` I don't even *have* a `check_parameters` method. Is it required?

**Comment by saramsey** [comment]
I'm OK with whatever change as long as it doesn't cause people who have already implemented their ARAX modules to have to do a lot of re-work (which doesn't seem to be the case with the suggestion above).

**Comment by edeutsch** [comment]
I assume `check_parameters` is not required, but if one has the nice allowable_parameters mechanism for documentation, using `check_parameters` seems like a nice additional touch.

**Comment by dkoslicki** [comment]
Quick response as might be able to better address during the mini-hackathon:
the intent for that code block @edeutsch was indeed a double life:
1. If a message was passed, populate the allowable parameters based on the information contained in the message KG/QG. Use this for DSL error checking using `check_parameters`
2. If no message was passed, use this for documentation purposes.

`check_parameters` is in there to make sure that the DSL command was:
1. Called with something allowed (eg. add a response.error if a typo was made like `overlay(action=overlay_clinical_info, chi_squared=true)` instead of `overlay(action=overlay_clinical_info, chi_square=true)`
2. Make sure that the DSL command makes sense with the message (i.e. if `source_qnode_id=n01` and `n01` doesn't exist in the message QG, then a response.error should be given).

**Comment by dkoslicki** [comment]
Also, @edeutsch your suggested re-factoring makes sense to me (I won't have time to implement it though, but feel free to do so and refactor the auto-gen documentation accordingly).

And to clarify: `overlay_clinical_information` has sub-actions, so the:

* 'paired_concept_freq' means "overlay with COHD paired concept frequency"
* 'observed_expected_ratio' means "overlay with COHD observed expected ratios
* 'chi_square' means "overlay with COHD chi square values"

Hence the code later down that clarifies these are mutually exclusive parameters. (but that was undocumented since I ran out of time).

**Comment by edeutsch** [comment]
okay, the "double life" I was talking about was not so much populating allowed values generally vs. when a message is present, but rather being either a set of allowed values vs. free-text description/documentation.

**Comment by dkoslicki** [comment]
@saramsey re: 
> Huh. In `ARAX_resultify` I don't even _have_ a `check_parameters` method. Is it required?
your `ARAX_resultify.py` lines:
```python
 # Basic checks on arguments
        if not isinstance(input_parameters, dict):
            response.error("Provided parameters is not a dict", error_code="ParametersNotDict")
            return response

        # Return if any of the parameters generated an error (showing not just the first one)
        if response.status != 'OK':
            return response

        # populate the parameters dict
        parameters = dict()
        for key, value in input_parameters.items():
            parameters[key] = value
```
are basically doing what `check_parameters` is kinda doing.

**Comment by dkoslicki** [comment]
@edeutsch 
> okay, the "double life" I was talking about was not so much populating allowed values generally vs. when a message is present, but rather being either a set of allowed values vs. free-text description/documentation.

Right, hence why I think your re-factoring makes sense. It'd just be an undertaking to get the auto-gen markdown tables to make this look nice, and then re-factoring `check_params` in my and Finn's code to make sure it concentrates only on the keys and `allowed_values` not the `description`. And then updating my and Finn's code to include these descriptions.

**Comment by dkoslicki** [comment]
After the refactoring done in #1080 and #1090, this can be closed
