### ISSUE TITLE
The great merging

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#651]
Moving the discussion from #618 to here as it's not completely related to #618 and will help us keep track of issues and have a place to discuss them.
@edeutsch @amykglen @finnagin @saramsey feel free to reference this issue as you merge so we can keep track.

**Comment by dkoslicki** [comment]
`expander`, `filter`, and `overlay` should now be all synced. Plan is to now merge each into `demo` pending @edeutsch's approval

**Comment by edeutsch** [comment]
go for it! thanks!

**Comment by dkoslicki** [comment]
The great merging is now complete! I will be doing some documentation fixing on demo per #631 and then will merge demo back into each branch separately.
Status now: All branches synced
Plan: DMK to make some changes on demo, then sync all other branches back with demo

**Comment by dkoslicki** [comment]
Ok, I addressed the things I wanted to address, now going to check with all about merging demo into expander, overlay, and filter so everyone has synced code.

**Comment by edeutsch** [comment]
great, green light from me!

**Comment by dkoslicki** [comment]
The great merging is complete! Closing this issue: as of this moment, everyone's code is up to date with everyone else's!
