### ISSUE TITLE
KGNodeIndex needs a refresh

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#652]
Will need to update the KGNodeIndex: [here](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/kg-construction/KGNodeIndex.py#L191) it calls out [NodeNamesDescriptions.tsv](https://github.com/RTXteam/RTX/blob/master/data/KGmetadata/NodeNamesDescriptions.tsv) that hasn't been updated for a year.
Reasons to do this:
1. KG1 may have had new bioentities added
2. We will eventually want to get KG2 nodes recognizable as well
3. We will eventually want to be able to recognize bioentities from other KP's besides KG1/KG2.

Steps:
- [x] re-run [`dumpdata.py`](https://github.com/RTXteam/RTX/blob/master/data/KGmetadata/dumpdata.py)
- [x] make sure the mysql database doesn't complain about any new formatting [as is currently addressed here](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/kg-construction/KGNodeIndex.py#L205-L263).
- [x] make sure everyone does the following
```
cd ~\RTX\code\reasoningtool\kg-construction
python3 KGNodeIndex.py -b
```
- [x] see if we can get it working with KG2
- [x] discuss how to get it to work with external KP's (or move away from the `KGNodeIndex` paradigm altogether

**Comment by dkoslicki** [comment]
Did some experimenting, found out that no new nodes have been added to `NodeNamesDescriptions.tsv` on KG1, which corresponds to:
```
Production
bolt://arax.rtx.ai:7687
```

**Comment by dkoslicki** [comment]
So only thing to address is if we can get it to work on KG2

**Comment by dkoslicki** [comment]
Switching to KG2 in `dumpdata.py` via:
```
from RTXConfiguration import RTXConfiguration
rtxConfig = RTXConfiguration()
rtxConfig.live = 'KG2'
#<snip, and custom change of config.py>
def dump_name_description(file_name, session=session):
	"""
	dump node names and descriptions of all nodes
	:param file_name: name of file to save to (TSV)
	:param session: neo4j session
	:return: None
	"""
	query = "match (n) return properties(n) as p, labels(n) as l"
	res = session.run(query)
	with open(file_name, 'w') as fid:
		for item in res:
			prop_dict = item['p']
			labels = item['l']
			if 'id' in prop_dict and 'name' in prop_dict:
				fid.write('%s\t' % prop_dict['id'])
				fid.write('%s\t' % prop_dict['name'])
				label = list(set(labels) - {'Base'}).pop()
				fid.write('%s\n' % label)
				if label == "protein" and 'id' in prop_dict and 'symbol' in prop_dict:  # If it's a protein, also do the symbol
					fid.write('%s\t' % prop_dict['id'])
					fid.write('%s\t' % prop_dict['symbol'])
					fid.write('%s\n' % label)
	return
```
results in 7,405,496 entries in `NodeNamesDescriptions.tsv`, which matches with `match (n) where exists(n.name) return count(n)` on http://kg2endpoint.rtx.ai:7474/browser/. This is a marked increase from current 145,325 entries.

**Comment by dkoslicki** [comment]
Then running:
```
cd ~\RTX\code\reasoningtool\kg-construction
python3 KGNodeIndex.py -b
```
apparently executes without error until it's added about 6,666,000 entries (took 29min on my machine), and then quits with the following error:
```
 File "KGNodeIndex.py", line 475, in <module>
    main()
  File "KGNodeIndex.py", line 430, in main
    kgNodeIndex.createNodeTable()
  File "KGNodeIndex.py", line 201, in createNodeTable
    type = columns[2]
IndexError: list index out of range
Command exited with non-zero status 1
```
I think this would be a thing for @edeutsch to investigate

**Comment by edeutsch** [comment]
I would need the input file to investigate more thoroughly.
Is it checked into GitHub?
SHOULD it be checked into GitHub?
---Side Note: do we have to worry about some maximum repo size?

Without looking at the data, here's my guess:
KGNodeIndex building relies on the data format:
KEGG:C01667	Bacitracin	metabolite
so the third column is the type. So.. this:
    type = columns[2]
IndexError: list index out of range
suggests to me that around line 6,666,nnn there is a line with no type. i.e. there are fewer than 3 columns.
Our system relies on there being a type for everything. No type would be a bad node?
So I'm thinking this is a data problem to be fixed.
Or else, what should we do? I'm pretty sure there is sample code that relies on there being some sort of type.
The build code could be easily updated to create a type of 'Unknown' if there is none. But is that what we want?

**Comment by dkoslicki** [comment]
A great topic for the mini hackathon @edeutsch ! Please remind me if someone doesn’t come up with a mini-hackathon agenda for tomorrow

**Comment by dkoslicki** [comment]
@edeutsch Remind me to show you how to get a local copy of the `NodeNamesDescriptions.tsv`. I don’t think it should be pushed to github as it will be used for local testing (and we want to check the size of it). But it will be helpful in diagnosing the problem that we noticed.

**Comment by edeutsch** [comment]
okay, sounds good. Except that I'm terrible at reminding. Not to mention remembering. so I put them on the agenda doc. Of course, now we need to remember to look at the agenda doc tomorrow...

**Comment by dkoslicki** [comment]
KG2 NodeNamesDescription.tsv is 569MB exceeding the Github limit of 100MB :(

**Comment by edeutsch** [comment]
No problem. It can be generated on the fly at each instance as part of the KGIndex building process.

**Comment by dkoslicki** [comment]
Right, which will now take ~1hr :(
Found there is one offending nodes in KG2 causing the problem:
CHEMBL.COMPOUND:CHEMBL2259757
it has a tab in it's name. 
@saramsey you might want to run the following cypher query on http://kg2endpoint2.rtx.ai:7474/browser/
```
match (n{id:"CHEMBL.COMPOUND:CHEMBL2259757"}) return n.name
```
And notice that, very subtly `mido)phenyl]methoxy}-5- acetamido-4-` that thing that looks like a space between the `5- acet` is actually a tab. I can get around this issue on my end. But might be good to know for KG2 stuff

**Comment by edeutsch** [comment]
It suggest it get fixed in KG2 since it will surely cause pain in all manner of TSV output. And it likely an error in the original data source anyway.

I think it would be good in KG2 loader enforces several rules before loading:
- name may not be NULL and may not contain TABs
- type may not be NULL and may not contain TABs
- curie may not be NULL and may not contain TABs
- curie must be unique
- I would even do so far as to say that description may not contain TABs as well

Replace TABs with spaces if they exist.

**Comment by dkoslicki** [comment]
And actually, @saramsey @edeutsch just discovered it's a *newline* not a tab

**Comment by dkoslicki** [comment]
> It suggest it get fixed in KG2 since it will surely cause pain in all manner of TSV output. And it likely an error in the original data source anyway.
> 
> I think it would be good in KG2 loader enforces several rules before loading:
> 
> * name may not be NULL and may not contain TABs
> * type may not be NULL and may not contain TABs
> * curie may not be NULL and may not contain TABs
> * curie must be unique
> * I would even do so far as to say that description may not contain TABs as well
> 
> Replace TABs with spaces if they exist.

Right, but I can make a quick workaround in `dumpdata.py` so we don't need to wait for Steve to re-build KG2

**Comment by edeutsch** [comment]
agreed. And update rules to:
- name may not be NULL and may not contain \t\n\r (sub \t\n\r to SPACE)
- type may not be NULL and may not contain any \s+ (sub \s+ to '')
- curie may not be NULL and may not contain any \s+ (sub \s+ to '')
- curie must be unique
- description may not contain \t\n\r (sub \t\n\r to SPACE)

**Comment by dkoslicki** [comment]
Got the wrong commit number, just FYI:
add example 19 in ARAX_query to see what happens if you ask for a node in KG2 but not in KG1 and try to expand. Executes ok, reports no matches found. #651

**Comment by dkoslicki** [comment]
@edeutsch All good for you to test on your end!

**Comment by edeutsch** [comment]
The lights dimmed briefly and then I got this:

Traceback (most recent call last):                                                                                                                                                    
  File "dumpdata.py", line 119, in <module>                                                                                                                                           
    dump_name_description_KG2('NodeNamesDescriptions.tsv', session, 'a')                                                                                                              
  File "dumpdata.py", line 36, in dump_name_description_KG2                                                                                                                           
    fid.write('%s\t' % remove_tab_newlines.sub(" ", prop_dict['name']))  # better approach                                                                                            
  File "C:\Program Files (x86)\Python37-32\lib\encodings\cp1252.py", line 19, in encode                                                                                               
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]                                                                                                                 
UnicodeEncodeError: 'charmap' codec can't encode character '\u03b1' in position 0: character maps to <undefined>                                                                      
Failed to write data to connection Address(host='kg2endpoint2.rtx.ai', port=7687) (Address(host='3.132.37.4', port=7687)); ("0; 'Underlying socket connection gone (_ssl.c:2283)'")   
Failed to write data to connection Address(host='kg2endpoint2.rtx.ai', port=7687) (Address(host='3.132.37.4', port=7687)); ("0; 'Underlying socket connection gone (_ssl.c:2283)'")   
Failed to write data to connection Address(host='kg2endpoint2.rtx.ai', port=7687) (Address(host='3.132.37.4', port=7687)); ("0; 'Underlying socket connection gone (_ssl.c:2283)'")   
                                                                                                                                                               
why did it have to be snakes..

**Comment by edeutsch** [comment]
seems like sprinkling in encoding="utf-8" fixed this.

**Comment by edeutsch** [comment]
Although a 600 MB file was created, the command ended with:

Failed to write data to connection Address(host='kg2endpoint2.rtx.ai', port=7687) (Address(host='3.132.37.4', port=7687)); ("0; 'Underlying socket connection gone (_ssl.c:2283)'")
Failed to write data to connection Address(host='kg2endpoint2.rtx.ai', port=7687) (Address(host='3.132.37.4', port=7687)); ("0; 'Underlying socket connection gone (_ssl.c:2283)'")

unclear if it completed or died.

**Comment by edeutsch** [comment]
@dkoslicki did yours complete without error? On my Windows machine, I got the above errors and a 606638514 byte file. On arax.rtx.ai, I got similar errors:

Failed to write data to connection Address(host='kg2endpoint2.rtx.ai', port=7687) (Address(host='3.132.37.4', port=7687)); ("0; 'Underlying socket connection gone (_ssl.c:2263)'")
Failed to write data to connection Address(host='kg2endpoint2.rtx.ai', port=7687) (Address(host='3.132.37.4', port=7687)); ("0; 'Underlying socket connection gone (_ssl.c:2263)'")

and a 599166226 byte file.

I am speculating that the neo4j connection is dying after N minutes of being open but before the whole result can complete.

Did you see any errors like this?

How big is yours?

**Comment by dkoslicki** [comment]
No such errors on my end. Not in front of dev machine, but iirc, the file is >508MB should be ~600MB after appending KG1 + KG2. Might be a UTF-8 vs. ASCII issue. I tested everything and it passed on my Ubuntu machine just fine...

**Comment by edeutsch** [comment]
okay, i will figure it out.
It may be working okay, actually. Maybe these are just errors closing the neo4j connection after a successful query.

**Comment by dkoslicki** [comment]
Ok, I just tested on a different system (Ubuntu 16.04) and it executed (from the `demo` branch) and resulted in a `NodeNamesDescriptions.tsv` of size 572MB with 7472288 lines. The `python KGNodeIndex.py -b` executed without error. Also, the `ARAX_query.py 12` and `ARAX_query.py 15` (our planned demo examples) executed without error on my end. So no idea what could be causing your errors.

**Comment by edeutsch** [comment]
I have determined that it is running completely. The difference in file size is just the difference in line endings. So it completes just fine, but then burps our the two errors while breaking down everything in memory I guess. I've moved on because it's okay.

**Comment by edeutsch** [comment]
I have almost completely re-written KGNodeIndex. Instead of taking a soul-crushingly long time to build the index, it now only takes a minute or two. All the same functions work as before, but it uses native SQL instead of SQLAlchemy, which was just super slow.

To get it all working on your system, just do:

# Create new NodeNamesDescriptions.tsv
cd $RTX/data/KGmetadata
python3 dumpdata.py

# Create new KGNodeIndex:
cd $RTX/code/reasoningtool/kg-construction
python3 KGNodeIndex.py -b

# Test it
python3 KGNodeIndex.py -t

It's very fast and good and should be a nice complete index of everything in KG2 (except for nodes with NULL names as discussed previously)

My biggest concern is that it now returns a lot of CURIEs for a given concept, e.g. get_curies(name) now returns:

phenylketonuria = ['REACT:R-HSA-2160456', 'DOID:9281', 'OMIM:261600', 'CUI:C0031485', 'LNC:LP56980-3', 'LNC:LA21169-0', 'MEDDRA:10034872', 'MEDCIN:32390', 'MEDLINEPLUS:1231', 'NCIT:C81315', 'NCI_NCI-GLOSS:CDR0000446806', 'NCI_NICHD:C81315', 'Orphanet:716', 'MONDO:0009861']

kidney = ['UBERON:0002113', 'CHV:0000022156', 'CHV:0000007085', 'FMA:7203', 'LNC:LP200461-4', 'LNC:MTHU002935', 'LNC:LP7380-1', 'LNC:LA4591-9', 'MESH:D007668', 'NCIT:C12415', 'NCI_CDISC:C12415', 'NCI_NCI-GLOSS:CDR0000046325', 'CHEMBL.TARGET:CHEMBL613579', 'CHEMBL.TARGET:CHEMBL613638']

and many of those CURIEs are not in KG1. So if you suddenly have code problems where you look something up by name and now are getting a CURIE not in KG1, this might be the reason.

This is checked into demo.

**Comment by dkoslicki** [comment]
>My biggest concern is that it now returns a lot of CURIEs for a given concept, e.g. get_curies(name) now returns:

So pre-demo, just be careful about what KP (KG1 vs KG2) we are using, right? I imagine in the demo vignette's, we'll be calling with CURIE's anyway (see `ARAX_query.py` 12 and 15).

Post-demo:
This might actually be a good thing to have in the future: if the ARS sends us a name like "kidney", we can dynamically check to see (in `expand`) which KP's have knowledge about the various CURIE's that map to it. We may even consider adding KP info associated to CURIEs in KGNodeIndex in the future as well (so we immediately have a mapping about who knows about what). May also want to add in KGNodeIndex all curies from all KP's we know about (not just KG1 and KG2).

**Comment by dkoslicki** [comment]
Closing until we run into the problem of "query by name". In the demo USE CURIE's!
