### ISSUE TITLE
Create a slide deck for ARAX demo

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#655]
- [ ] Brief intro slide reminding NCATS of our DSL implementing the milestones
    - [ ] point to the documentation (screen shot image and link maybe?)
    - [ ] note that this is API standards compliant (given the `processing_actions` in the API std)
- [ ] Proviso slide that since there is no ARS at the moment, we will be creating messages from scratch, but that we **absolutely can** run everything/anything on a populated std API compliant message passed to us that includes (or not) `processing_actions` with the DSL
- [ ] a slide introducing each demo iPython notebook at a high level (so 3x these slides)
    - [ ] pictorially describe the kind of query we are doing
    - [ ] describe the KP's we are reaching out to (if relevant: demo examples 2 and 3)
    - [ ] bullet point takeaway about the biological relevance / result of the example
    - [ ] note the scientific complementary to the project as a whole (eg. No ARA we know of can filter/overlay/etc. and these DSL commands will be significantly expanded)
    - [ ] note how crucial it is to have this functionality to "hone in on" the answers the ARS needs to return relevant items 
    - [ ] bullet point how this maps to milestones
- [ ] one or two final slides that address how 
    - [ ] we hit every milestone + some
    - [ ] how this DSL is extremely flexible, will be able to operate on arbitrary input messages/queries
    - [ ] how we have plans in place to dynamically reach out to KP's to either:
        - [ ] expand QG's if our KG's don't have them
        - [ ] execute more complicated reasoning tasks

**Comment by dkoslicki** [comment]
@saramsey just sketched out my vision for how these slides might look in your comment. Hope you don't mind

**Comment by dkoslicki** [comment]
@saramsey LMK when this starts to be developed. I’d appreciate if it’s done on the google slides/drive, as I will probably have time during my evenings next week to contribute to them.

**Comment by saramsey** [comment]
https://docs.google.com/presentation/d/1oK7ADGDI9IXgWSnznps-Hz0dmzqX5NwWL2EZqgAUiMA/edit?usp=sharing

**Comment by saramsey** [comment]
So sorry for the very slow start on this. I am working the super-helpful and awesome checklist from @dkoslicki

**Comment by saramsey** [comment]
Well, things got derailed by #680. Will resume this afternoon.

**Comment by saramsey** [comment]
done; big thanks to @dkoslicki, @jaredroach, and @edeutsch on this
