### ISSUE TITLE
Change top-level ARAX/README.md

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#657]
The current [README.md](https://github.com/RTXteam/RTX/blob/demo/code/ARAX/README.md) is **not** the first thing we want NCATS seeing when we show them the repo. This need to be redone to something like what was mentioned in the AHM:

Modifying the README.md in the ARAX/ folder that describes the system, capabilities, vision, etc. at a high level and points to where someone can go to look at more info (like where the components live, what docs describe their functionality, what KP’s we use, etc.). The ARAX/Documentation/README.md sketches what I have in mind. Consider adding our demo vignettes to this document (in case we run out of time or NCATS wants to look at it again). And have it have links that point to @edeutsch's planned iPython notebooks.

**Comment by saramsey** [comment]
OK, I can work on this, since #618 is closed and my work on #654 is currently paused pending feedback.

**Comment by saramsey** [comment]
I'm going to do this work in the `demo` branch unless there are objections?

**Comment by edeutsch** [comment]
no objection from me

**Comment by saramsey** [comment]
Have updated the overall title of the RTX repo:

<img width="1121" alt="Screen Shot 2020-02-29 at 3 00 44 PM" src="https://user-images.githubusercontent.com/5562107/75616325-4db62180-5b04-11ea-8d4a-e269b6caa4a9.png">

**Comment by saramsey** [comment]
Changed my mind, going with this instead (top-level):

<img width="1091" alt="Screen Shot 2020-02-29 at 3 02 50 PM" src="https://user-images.githubusercontent.com/5562107/75616343-9a99f800-5b04-11ea-89f4-e789c81c0ec7.png">

**Comment by dkoslicki** [comment]
Works for me Steve!

I would still suggest `ARAX` folder have a README.md, maybe just pointing to the `Documentation` folder and describing the general structure of the ARAX repo/branch/etc.

**Comment by saramsey** [comment]
Yes, I will make a README.md for the ARAX folder
