### ISSUE TITLE
Absence of Non-human nodes in knowledge graph

### ISSUE THREAD

**Issue by jaredroach** [RTXteam/RTX#66]
Absence of Non-human nodes in knowledge graph prevents solutions for these Clinical Outcome Pathways (COPs):

#24 SUXIBUZONE | laminitis   (laminitis is a horse disease)
#14 VALGANCICLOVIR HCL | Cytomegalovirus retinitis

other example:
Helvolic Acid | candidiasis

will also fail for anti-microbials...

**Comment by saramsey** [comment]
Related question:  why are viral proteins excluded from the KG?

**Comment by dkoslicki** [comment]
Per the email discussion, I'm going to close this issue as we're considering non-human nodes as "out of scope".
