### ISSUE TITLE
Confidence scores still appear to be random numbers

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#661]
Maybe don't include them until we decide what they should represent?
High priority if they get displayed in the UI for the demo presentation.

**Comment by edeutsch** [comment]
that was just an simple example to get everyone started. That code can be removed. It should not be called anymore anyway?

It would be highly desirable to compute some kind of confidence or score. Even the jaccard index would be a decent score if nothing else is available. The results look better with some scores attached to them. and we do have the data.

**Comment by dkoslicki** [comment]
@finnagin  would know best what to decorate the confidences with for our demo examples, but will need to work with @saramsey to get them populated in `resultify()`. I unfortunately won't be able to contribute in the next couple days after this big push I did for #615 

I had just noticed that confidence scores were all over the place, so I don't know who is calling it or from where (i.e. I did not thoroughly test it, just noticed it).

**Comment by dkoslicki** [comment]
Non issue currently as not used in the code (not an `allowable_action`). Will leave open to remind myself to implement this in overlay.

**Comment by edeutsch** [comment]
I recommend that the random confidence generator function be deleted. Shall I do it or you?

**Comment by dkoslicki** [comment]
I'll go ahead and do it.
