### ISSUE TITLE
Team Gamma proposing change to Reasoner Standard API

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#662]
From Patrick Wang on March 4, 2020:

> Servers occasionally want to return more information than was asked-for in the query graph. Rather than modifying the query graph and adding bindings, which could be confusing to the client, it may be more sensible to create fields in each result in which to store this "extra" information.
> extra_nodes and extra_edges could be simple lists of knowledge-graph node ids and edge ids, respectively. Then each result is a subgraph of the knowledge graph in which a subset of nodes and edges are bound to elements from the query.
> One potential problem with this approach is that it does not allow specification of exactly where in the result graph an extra edge is used. A result in general may include the same knowledge-graph node bound to multiple query-graph nodes, and an extra edge may be relevant to any number of these node instances. Which one(s) will be ambiguous.

See the thread here:
https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI/issues/95

**Comment by dkoslicki** [comment]
I sent an email about this, but it might not have come through, so it’s copied here for the record:

Personally, I would vote: If you want to add extra information than what was asked for in the query graph, you had better modify the query graph accordingly! I thought modifying the QG was a settled thing, so doing this `extra_nodes` and `extra_edges` sounds like an, imho, ad-hoc/tedious way to go about it.
 
I thought the whole paradigm was “everyone should be able to know what to do with a QG/KG” so clients shouldn’t be confused when a message is passed with a QG that just happens to be different than one that was sent (just throw away things you don’t want if you really need things to be idempotent).

LMK if I should post this to the NCATS-Tangerine thread

**Comment by saramsey** [comment]
OK to close this issue out?  It's 3.5 years old.

**Comment by edeutsch** [comment]
Ancient history.
