### ISSUE TITLE
HPO UMLS derived nodes have incorrect CURIE prefixes

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#665]
See `HPO:HP%3A0002748`. There are 13,502 such nodes in KG2:

![Screen Shot 2020-03-06 at 1 34 58 PM](https://user-images.githubusercontent.com/5562107/76124329-49c84a80-5faf-11ea-8cf2-4cccdd467db0.png)

They seem to come from the UMLS HPO import. Thank you @edeutsch  for reporting this issue.

**Comment by saramsey** [comment]
can this issue be closed out now?

**Comment by amykglen** [comment]
yes (sorry, forgot to post an update) - I just needed to test the fix on `kg2dev`, but I did so this morning.  all looks good.

though these changes haven't yet been incorporated into a build, so won't appear in `kg2endpoint2` yet. not sure if you want to wait to close the issue until that point.
