### ISSUE TITLE
Unresolved reference Txmessage in ARAX_query.py

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#668]
My IDE is showing TxMessage in [this line](https://github.com/RTXteam/RTX/blob/demo/code/ARAX/ARAXQuery/ARAX_query.py#L344) and [this line](https://github.com/RTXteam/RTX/blob/demo/code/ARAX/ARAXQuery/ARAX_query.py#L347) as being unresolved. Haven’t yet experienced it causing an error, but I just noticed that it isn’t imported anywhere in `ARAX_query.py`. I don’t know if this is inherited from some flask server thingy that @edeutsch is running, but thought I would point it out. 

Tentative bug hence the label. @edeutsch feel free to close this if it’s a non-issue, or address if it is.

**Comment by edeutsch** [comment]
This "else" block onto gets triggered when two or more Messages are uploaded/referenced and would trigger some merging code. This is a holdover from the old RTXQuery, which used to be able to try something vaguely sensible with multiple Messages. This is no longer part of our repertoire I think, I have have removed this code and replaced it with a warning. I have also removed a few other unused variables that IDEs complain about the with the latest push to demo.

Can be closed.
