### ISSUE TITLE
COHD 500

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#669]
Was just testing example 15 and saw this:

I have not investigated, but a possible risk for the March demo:

$ python ARAX_query.py 15
http://cohd.nsides.io/api/omop/xrefToOMOP?curie=CHEMBL.COMPOUND:CHEMBL1073&distance=1
Status code 500 for url: http://cohd.nsides.io/api/omop/xrefToOMOP?curie=CHEMBL.COMPOUND:CHEMBL1073&distance=1
http://cohd.nsides.io/api/omop/xrefToOMOP?curie=CHEMBL.COMPOUND:CHEMBL632&distance=1
Status code 500 for url: http://cohd.nsides.io/api/omop/xrefToOMOP?curie=CHEMBL.COMPOUND:CHEMBL632&distance=1
http://cohd.nsides.io/api/omop/xrefToOMOP?curie=CHEMBL.COMPOUND:CHEMBL1370&distance=1
Status code 500 for url: http://cohd.nsides.io/api/omop/xrefToOMOP?curie=CHEMBL.COMPOUND:CHEMBL1370&distance=1
http://cohd.nsides.io/api/omop/xrefToOMOP?curie=CHEMBL.COMPOUND:CHEMBL1544&distance=1
Status code 500 for url: http://cohd.nsides.io/api/omop/xrefToOMOP?curie=CHEMBL.COMPOUND:CHEMBL1544&distance=1
http://cohd.nsides.io/api/omop/xrefToOMOP?curie=CHEMBL.COMPOUND:CHEMBL472&distance=1
Status code 500 for url: http://cohd.nsides.io/api/omop/xrefToOMOP?curie=CHEMBL.COMPOUND:CHEMBL472&distance=1
http://cohd.nsides.io/api/omop/xrefToOMOP?curie=CHEMBL.COMPOUND:CHEMBL1481&distance=1
Status code 500 for url: http://cohd.nsides.io/api/omop/xrefToOMOP?curie=CHEMBL.COMPOUND:CHEMBL1481&distance=1

**Comment by dkoslicki** [comment]
Yeah, yet another issue with using external API's. They sometimes return internal error codes. Hence the importance of pre-running all the demo commands on the system(s) we plan on demoing on (multiple times), so the proper results get cached and these (hopefully) don't show up. 

FWIW, at least this is "not our problem" and could lead to a fruitful discussion about the practical issues of using many external API calls (if/when during/after the demo, that is)

**Comment by saramsey** [comment]
Is there anything actionable here, in the near- or medium-term?  If not, I propose to close this issue.

**Comment by saramsey** [comment]
Hey @finnagin perhaps you could note this error on the Wiki, under a new section "error codes and what they mean"? Then we could close out this issue.

**Comment by finnagin** [comment]
I've added a wikipage section "error messages and what they mean" and added this error message to it. Closing out the issue.
