### ISSUE TITLE
orangeboard everywhere

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#670]
It seems like a mild nuisance and a potential source of slowness that whenever I run any RTX/ARAX code that does web service requests (I think that's the source), an "orangeboard.sqlite" gets created in the CWD. I think what is happening is that the requests cache is just always being put in the CWD? So this means that I have multiple requests caches here and there, probably largely duplicated. And of course the Flask system runs with a different CWD than other testing etc.

Does is seem useful/logical/reasonable to configure the system to always put orangeboard.sqlite in one place (relative to the code tree)? And why "orangeboard"? Does that have some useful significance?

**Comment by dkoslicki** [comment]
I think that's a @saramsey or @finnagin question. I too have been baffled by its ubiquity.

**Comment by saramsey** [comment]
Agreed this is is not good. It's indefensible from a software design standpoint. 

Do we need to deal with this before the demo?

**Comment by edeutsch** [comment]
Need, no. But it would be nice.

**Comment by saramsey** [comment]
Can I get a MWE?

**Comment by saramsey** [comment]
Is it coming from `ReasoningUtilities.py` or `fisher_exact.py`?
```
sramsey-laptop:code sramsey$ find . -name \*.py -exec grep 'requests_cache.install_cache(' {} /dev/null \;  | grep -v '#' | grep orangeboard | grep -v deprecated
./reasoningtool/QuestionAnswering/Q2Solution.py:requests_cache.install_cache('orangeboard')
./reasoningtool/QuestionAnswering/fisher_exact.py:requests_cache.install_cache('orangeboard')
./reasoningtool/QuestionAnswering/ReasoningUtilities.py:requests_cache.install_cache('orangeboard')
./reasoningtool/kg-construction/request_cache_helper.py:requests_cache.install_cache("orangeboard")
./reasoningtool/kg-construction/AddProtToGO.py:requests_cache.install_cache('orangeboard')
./reasoningtool/kg-construction/PatchKGDGIdb.py:requests_cache.install_cache('orangeboard')
./reasoningtool/kg-construction/QueryGeneProf.py:requests_cache.install_cache('orangeboard')
```

**Comment by edeutsch** [comment]
Presumably `ReasoningUtilities.py` is the main culprit since it is called by everything.

**Comment by saramsey** [comment]
Assigning to @dkoslicki 

<img width="830" alt="Screen Shot 2020-03-24 at 9 32 21 AM" src="https://user-images.githubusercontent.com/5562107/77451826-6c7da000-6db2-11ea-8721-05f05cf89c26.png">

**Comment by dkoslicki** [comment]
@dkoslicki Try commenting it out/renaming it, test, see if/what things are slow

**Comment by dkoslicki** [comment]
@edeutsch is this still an issue you are experiencing? Or is our move away from `ReasoningUtilities.py` and other legacy code no longer causing the issue?

**Comment by edeutsch** [comment]
I am still seeing this to some degree:
-rw-r--r-- 1 rt rt    4743168 May 13 05:16 ./ARAX/ARAXQuery/orangeboard.sqlite
-rw-r--r-- 1 rt rt   34505728 May 17 03:22 ./UI/OpenAPI/python-flask-server/orangeboard.sqlite

**Comment by dkoslicki** [comment]
Got it! @chunyuma and I will have a look.

**Comment by dkoslicki** [comment]
@edeutsch @saramsey Is the desire to remove orangeboard.sqlite everywhere, or make sure it only gets created in one (and only one) location?

**Comment by dkoslicki** [comment]
@chunyuma When you have a few spare cycles, can you:
- [ ] find all instances of `requests_cache.install_cache('orangeboard')` in the entire code-base
- [ ] change the file name `'orangeboard'` (using appropriate relative file paths in each instance) such that it gets placed in the directory `RTX/data/`
That way there is one, and only one `orangeboard.sqlite` floating around

TBD @saramsey and @edeutsch about if/when we want the cache to expire

**Comment by chunyuma** [comment]
Sure, I can do it.

**Comment by edeutsch** [comment]
Right. one location. Not relative to the current working directory, which changes depending on how the code is invoked.

**Comment by edeutsch** [comment]
But I thought Steve already fixed this. Is that fix stuck in a branch somewhere?

**Comment by chunyuma** [comment]
I found there are totally 10 python files containing `requests_cache.install_cache('orangeboard')`. I can change it and place it under directory `RTX/data/`. Do you think we should create a specific folder to store it. Or just randomly place it directly under `RTX/data/`.

```
./code/reasoningtool/deprecated_modules/ReasoningTool.py:42:requests_cache.install_cache('orangeboard')
./code/reasoningtool/deprecated_modules/TestSet.py:26:requests_cache.install_cache('orangeboard')
./code/reasoningtool/kg-construction/QueryGeneProf.py:20:requests_cache.install_cache('orangeboard')
./code/reasoningtool/kg-construction/BuildMasterKG.py:31:# requests_cache.install_cache('orangeboard')
./code/reasoningtool/kg-construction/PatchKGDGIdb.py:9:requests_cache.install_cache('orangeboard')
./code/reasoningtool/kg-construction/AddProtToGO.py:40:requests_cache.install_cache('orangeboard')
./code/reasoningtool/kg-construction/request_cache_helper.py:8:requests_cache.install_cache("orangeboard")
./code/reasoningtool/QuestionAnswering/ReasoningUtilities.py:54:requests_cache.install_cache('orangeboard')
./code/reasoningtool/QuestionAnswering/Q2Solution.py:6:requests_cache.install_cache('orangeboard')
./code/reasoningtool/QuestionAnswering/fisher_exact.py:48:requests_cache.install_cache('orangeboard')
```

**Comment by dkoslicki** [comment]
@edeutsch  Steve asked me to assign to @chunyuma , so I assume it hasn't been fixed (and I still see it a problem on master)

**Comment by dkoslicki** [comment]
@chunyuma 

> Do you think we should create a specific folder to store it. Or just randomly place it directly under RTX/data/

It's a single file `orangeboard.sqlite` so I think in `RTX/data` is just fine (no need for another folder)

**Comment by edeutsch** [comment]
ReasoningUtilities is the main culprit I think. Most of the rest are deprecated or part of kg building, which is not really relevant for the production server.

**Comment by chunyuma** [comment]
The problem should have been solved. Before I push the code to Github, how should I test it by any command lines?

**Comment by dkoslicki** [comment]
I’ve found that `ARAX_query.py 5` triggers the creation of `orangeboard.sqlite`, so I would suggest running that command, looking over the code base for the SQLite file, making sure it’s in the right place. Deleting it, run that command again but from a different directory, and repeat until you’re satisfied.

**Comment by chunyuma** [comment]
I updated the master branch by modifying the following files:

```
code/reasoningtool/QuestionAnswering/Q2Solution.py         |  7 ++++++-
code/reasoningtool/QuestionAnswering/ReasoningUtilities.py |  7 ++++++-
code/reasoningtool/QuestionAnswering/fisher_exact.py       |  9 +++++++--
code/reasoningtool/deprecated_modules/ReasoningTool.py     |  7 ++++++-
code/reasoningtool/deprecated_modules/TestSet.py           | 10 ++++++++--
code/reasoningtool/kg-construction/AddProtToGO.py          |  7 ++++++-
code/reasoningtool/kg-construction/PatchKGDGIdb.py         |  7 ++++++-
code/reasoningtool/kg-construction/QueryGeneProf.py        |  9 +++++++--
code/reasoningtool/kg-construction/request_cache_helper.py | 10 +++++++---
```
Right now, the `orangeboard.sqlite` should be only placed under the directory `RTX/data`. Please let me know if there are any problems. Thank you!

**Comment by dkoslicki** [comment]
Awesome, thanks @chunyuma! @edeutsch feel free to test on prod and close if confirmed.

**Comment by edeutsch** [comment]
I am seeing this error on importing ReasoningUtilities:

Traceback (most recent call last):
  File "KGNodeIndex.py", line 14, in <module>
    import ReasoningUtilities as RU
  File "G:\Repositories\GitHub\RTX\code\reasoningtool\kg-construction/../QuestionAnswering\ReasoningUtilities.py", line 52, in <module>
    import fisher_exact
  File "G:\Repositories\GitHub\RTX\code\reasoningtool\kg-construction/../QuestionAnswering\fisher_exact.py", line 52, in <module>
    dbpath = tmppath.search(os.path.realpath(__file__)).group(0) + 'data/orangeboard'
AttributeError: 'NoneType' object has no attribute 'group'

What is the tmppath.search() supposed to be doing? I don't understand this construct.

**Comment by chunyuma** [comment]
Hi @edeutsch, `imppath.search()` is supported to find the path of your RTX directory. Could you show me how you ran this code? I tested it and it seems to work on Linux.

**Comment by chunyuma** [comment]
I just tested `import ReasoningUtilities as RU` and `import fisher_exact` and they worked fine without any errors.

**Comment by edeutsch** [comment]
oh, I see, you used regular expressions on the path. that won't work under Windows because the directory separators are different characters. Instead of regular expressions, I suggest going with the standard os.path() functions which are intended to handle that correctly in a platform independent way. There are example just a few line up in the file, but basically this:

os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'data/orangeboard')

**Comment by chunyuma** [comment]
@edeutsch, thanks for your suggestion. I just fixed this issue and updated the code. Right now it should be able to run without problem under different platforms.

**Comment by edeutsch** [comment]
thank you!
