### ISSUE TITLE
resultify() should fill in essence and essence_type

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#671]
It would be super helpful for the GUI and also for summarizing a Message if the resultify() mechanism would fill in the essence and essence_type attributes of each result{}.

In most cases, the essence of a result is probably the node name that corresponds to the end node that has no CURIE. Maybe you already compute a start_node and an end_node as concepts?

So for our simple example 2, it is n02. This would allow the essence of the results to be displayed in the GUI:

https://arax.rtx.ai/?m=1367

instead of just result 1, result 2, etc.
The essence_type is the BioLink type of the essence.

**Comment by saramsey** [comment]
I have questions:
1. What if there is more than one node in the result, that has no CURIE prefix?
2. What if all nodes in the result have a CURIE prefix?
3. What precisely is the condition implied by "in most cases... is probably the node name..."?

**Comment by edeutsch** [comment]
Assuming you don't already have "start node" and "end node" concepts identified, where the "start node" is the most specified one (like Parkinsons == DOID:14330 == n00 in our example) and the "end node: is the "opposite one", which is usually least specifed (chemical_substance == n02 in our example), then maybe the follow set of rules could be taken:

- Find all single-connection nodes (n00 and n02 in our example)
- Find all the most specific (has a CURIE) and least specific (no CURIE)
- if only one least specific, that's it!
- if only one most specific, then the farthest least specific from the most specific
- If this hasn't triggered anything yet, then this is one complicated scenario. One could concatenate all the farthest least specific node names or something like that. Seems unlikely in the near term.

To your points:
1. Above algorithm should solve this
2. That's a really boring graph. I suppose then the edges are the most interesting thing about the graph . Something about the graph needs to be unspecified or else it's an answer not a question.
3. erm? For the demo I think we will probably be working with fairly simple graphs, so I wouldn't worry about diabolical cases until we stumble over them. Could you have a circular QueryGraph of fully specific nodes? sure, but what would that mean? Would be nice if it didn't fall into an infinite loop or crash outright, but just picked something. Then we can refine it when we find a problem.

**Comment by saramsey** [comment]
Set the "score" field on the results:

- Example 1: see if we can use edge probabilities

- Example 2: set the confidence based on edge type p1 connecting nodes n02 to n00; pull off the edge attribute probability_drug_treats

- Example 3: exp(-NGD_score)?  average with COHD score?  think about this.

**Comment by edeutsch** [comment]
(that is also useful, but separate from the essence and essence_type)

**Comment by saramsey** [comment]
From @edeutsch :  

> May I suggest that you use the name instead of the symbol for the essence? Or if you want to get fancy, if the symbol is not null, then both the symbol and the name? We do have the space there.

**Comment by saramsey** [comment]
have implemented a change to only use the KG node `name` and never `symbol`.

**Comment by saramsey** [comment]
have implemented fancy-pants code to add the KG node `symbol` attribute as a parenthetic after the node `name` attribute, if the `symbol` attribute is not None

**Comment by edeutsch** [comment]
ooo! You so fancy!

**Comment by edeutsch** [comment]
Looks great!
https://arax.rtx.ai/devLM/?m=1411

Note that dual edges are back after a long hiatus. How did they return?

**Comment by saramsey** [comment]
Just pushed a bugfix for the BFS code used to handle a very unusual (and probably very unlikely in practice) of a QG in which there are two "specific" (CURIE-specified) leaf nodes and two non-specific interior nodes that are in series. Using BFS to compute shortest-path distances from the nearest specific leaf node.
