### ISSUE TITLE
set up an info@mail.rtx.ai email account via AWS

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#672]

**Comment by saramsey** [comment]
This is now done. Email to `info@mail.rtx.ai` now goes to my OSU email account. This was rather complicated to set up in AWS (i.e., about three hours of hacking on settings in AWS IAM, SES, Lambda, and S3). I followed this [rough guide from AWS](https://aws.amazon.com/blogs/messaging-and-targeting/forward-incoming-email-to-an-external-destination/) but there were _many_ gotchas along the way. You have been warned. _Hic sunt dracones_.

**Comment by edeutsch** [comment]
AWS? Shouldn't this be a trivial feature of your domain provider like GoDaddy or Namecheap or whatever?

**Comment by saramsey** [comment]
IDK, our domain provider for `rtx.ai` is 101domains. But AWS is our DNS provider. LOL I should have asked around before wandering into the AWS wilderness.

**Comment by saramsey** [comment]
The AWS lambda function that I coded up, can accept multiple email addresses. Eric do you want to get in on the fun, and be added to the list?

**Comment by edeutsch** [comment]
pass, thanks!
