### ISSUE TITLE
proofread README.md documentation; add TOC

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#674]
need some help proofreading and link-checking the top-level README.md documentation in the `demo` branch

**Comment by saramsey** [comment]
also please add a table of contents

**Comment by dkoslicki** [comment]
Also added the contents:

4. RTX could produce results in the Reasoners Standard API format. However, it could not be queried in this API format. In contrast, ARAX can perform all of is capabilities upon receiving any input Reasoners Standard API, while still producing such a standardized output format. As such, ARAX an its capabilities will be accessible to any automated reasoning agent, automated reasoning system, or knowledge provider capable of sending a Reasoners Standard API message.

To section `What is RTX? How does it differ from ARAX?`

**Comment by dkoslicki** [comment]
@amykglen just so you are aware. TOC has been added. Still needs proof-reading

**Comment by edeutsch** [comment]
I wouldn't say this is true:

RTX could produce results in the Reasoners Standard API format. However, it could not be queried in this API format.

RTX was quite capable of receiving a Standard API 0.9.2 QueryGraph in a Message and answering it using the QueryGraphReasoner with a standard Message.

The real difference is that RTX would answer a query like the Example 2 QueryGraph with many bits of magic in the back end (Q3Solution.py I think) that the client had no control over. Now they have the option of full control.


Side note: I think I've mentioned this before, but just so everyone is clear: the mechanism by which we are currently feeding DSL into ARAX *is currently* in the 0.9.2 standard, but it is an innocuous side door that even most people with a passing knowledge of the standard do not realize is even there. I inserted it there around version 0.9.0. Even Patrick may not remember it's there, or at least hasn't thought about it. Just so you know when others profess surprise that that is possible within the standard.

**Comment by dkoslicki** [comment]
>RTX was quite capable of receiving a Standard API 0.9.2 QueryGraph in a Message and answering it using the QueryGraphReasoner with a standard Message.

I had forgotten about that part. While we could indeed receive and return a message using QueryGraphReasoner, none of the "reasoning" stuff Finn/Jason/and I developed ever operated on that. Unless the input message was asking for a specific canned query, iirc, all we could do is expand an input QG with KG1 or KG2. All the "reasoning" was hidden in the "magic" you referred to inside scripts that weren't accessible via an external user sending a message (unless they knew which QNumber to use).

So, @edeutsch would you think it would be fair to say:
"RTX could produce results in the Reasoners Standard API format. However, its more extensive reasoning capabilities could not be queried in this API format without specialized knowledge of the RTX system.  In contrast. ARAX can now perform its complex reasoning capabilities upon receiving any input Reasoners Standard API, while still producing such a standardized output format. As such, ARAX and its reasoning capabilities will be accessible to any automated reasoning agent, automated reasoning system, or knowledge provider capable of sending a Reasoners Standard API message "?

**Comment by edeutsch** [comment]
yes, that's all true. good.

Although the very last sentence probably should be qualified with "....and with deep understanding of ARAXi". But it's fine to leave that out ;-)

**Comment by dkoslicki** [comment]
>and with deep understanding of ARAXi

But now we have actual documentation!! ;)

**Comment by edeutsch** [comment]
true enough!

**Comment by amykglen** [comment]
Ok, I proofread and checked all links - fixes made in [this commit](https://github.com/RTXteam/RTX/commit/cbfc12705ba909c7a4093c43c1e9bdfdf525e03e). Shall I close this issue?

**Comment by saramsey** [comment]
Hey @dkoslicki  and @edeutsch  are you satisfied with the current state of the top-level `README.md`?  Can we close this issue?

**Comment by edeutsch** [comment]
Looks great, feel free to close!

**Comment by dkoslicki** [comment]
Looks good! Made a minor change in `ARAX/code/README.md` (moved dev notes to wiki). Closing
