### ISSUE TITLE
resultify() should fill in confidence scores on results

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#675]
_(Creating an issue for this as I don't think we have one yet - #661 is related, but seems to have come to refer to a slightly different thing)_

Steve's notes about this from the March 10 AHM (posted on #671 ):

> Set the "score" field on the results:
> 
> Example 1: see if we can use edge probabilities
> 
> Example 2: set the confidence based on edge type P1 connecting nodes n02 to n00; pull off the edge attribute probability_drug_treats
> 
> Example 3: exp(-NGD_score)? average with COHD score? think about this.

**Comment by saramsey** [comment]
OK @edeutsch and @dkoslicki how about I first work on slides and then #675?  Does that make sense?  Or if there is someone who wants to work on #675 and has bandwidth, in the near-term (this week)?

**Comment by dkoslicki** [comment]
Slides are highest priority at this point imho, if we want the dry run to go well/be fruitful

Sent from my mobile device, please excuse my brevity and/or typos

________________________________

**Comment by dkoslicki** [comment]
Slides are highest priority at this point imho, if we want the dry run to go well/be fruitful


Sent from my mobile device, please excuse my brevity and/or typos
________________________________

**Comment by edeutsch** [comment]
Agreed, slides more important than scoring.

**Comment by saramsey** [comment]
OK, I am working on the slides.

**Comment by saramsey** [comment]
OK, slides are in good shape. Am assuming this is next-up on the priority list for me?

**Comment by edeutsch** [comment]
I suppose I wouldn't sweat this before the demo. But okay if you want to. If you succeed, would require a rollout even closer to game time, however...

**Comment by saramsey** [comment]
OK @edeutsch and @dkoslicki  is it time to revisit this?  I assume this is still a high priority?

**Comment by edeutsch** [comment]
Yes, this is high priority. I had vague plan of taking a swing at it this week. But haven't started yet. I suppose whoever approaches the plate first should announce it.

**Comment by dkoslicki** [comment]
@edeutsch should we close this due to #783? Or do we still need to address confidences at a lower level (eg in `overlay`)? #788

**Comment by edeutsch** [comment]
I implemented a prototype of this. I'm pretty happy with it. But I need to clean it up and put it in a nice separate class I think. So, not really done completely. But stawman functionality is there.

**Comment by dkoslicki** [comment]
@edeutsch 
> I implemented a prototype of this. I'm pretty happy with it. But I need to clean it up and put it in a nice separate class I think. So, not really done completely. But stawman functionality is there.

Ok, given the similarity of issues, do we want to keep both open, or just continue the discussion on #783?

**Comment by edeutsch** [comment]
oh right, I forgot about that. no need to have more than one!
