### ISSUE TITLE
resultify returning error with no message for demo example #2

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#676]
@saramsey 
For the query `python ARAX_query.py 1212`:
```python
query = { "previous_message_processing_plan": { "processing_actions": [
            "create_message",
            "add_qnode(curie=DOID:14330, id=n00)",
            "add_qnode(type=protein, is_set=true, id=n01)",
            "add_qnode(type=chemical_substance, id=n02)",
            "add_qedge(source_id=n00, target_id=n01, id=e00)",
            "add_qedge(source_id=n01, target_id=n02, id=e01, type=physically_interacts_with)",
            "expand(edge_id=[e00,e01], kp=ARAX/KG1)",
            "overlay(action=compute_jaccard, start_node_id=n00, intermediate_node_id=n01, end_node_id=n02, virtual_edge_type=J1)",
            "filter_kg(action=remove_edges_by_attribute, edge_attribute=jaccard_index, direction=below, threshold=.2, remove_connected_nodes=t, qnode_id=n02)",
            "filter_kg(action=remove_edges_by_property, edge_property=provided_by, property_value=Pharos)",
            "overlay(action=predict_drug_treats_disease, source_qnode_id=n02, target_qnode_id=n00, virtual_edge_type=P1)",  # overlay by probability that the drug treats the disease
            "resultify(ignore_edge_direction=true)",
            #"filter_results(action=sort_by_edge_attribute, edge_attribute=probability_drug_treats, direction=descending, max_results=15)",  
            "return(message=true, store=false)",
            ] } }
```
An error is happening at the `resultify` step (confirmed by running with/without resultify to reproduce). Error message is:
```
 2020-03-11 11:13:02.808469 ERROR: 
```

**Comment by saramsey** [comment]
sorry, I am working on this

**Comment by saramsey** [comment]
OK I *think* I have fixed the issue with Example 2. The edges with relation `jaccard_index` and `probability_drug_treats` were messing `resultify`'s ability to identify "leaf" nodes in the query graph. The following code now seems to work:

```
    query = {"previous_message_processing_plan": {"processing_actions": [
        "create_message",
        "add_qnode(curie=DOID:14330, id=n00)",
        "add_qnode(type=protein, is_set=true, id=n01)",
        "add_qnode(type=chemical_substance, id=n02)",
        "add_qedge(source_id=n00, target_id=n01, id=e00)",
        "add_qedge(source_id=n01, target_id=n02, id=e01, type=physically_interacts_with)",
        "expand(edge_id=[e00,e01], kp=ARAX/KG1)",
        "overlay(action=compute_jaccard, start_node_id=n00, intermediate_node_id=n01, end_node_id=n02, virtual_edge_type=J1)",
        "filter_kg(action=remove_edges_by_attribute, edge_attribute=jaccard_index, direction=below, threshold=.2, remove_connected_nodes=t, qnode_id=n02)",
        "filter_kg(action=remove_edges_by_property, edge_property=provided_by, property_value=Pharos)",
        "overlay(action=predict_drug_treats_disease, source_qnode_id=n02, target_qnode_id=n00, virtual_edge_type=P1)",
        "resultify(ignore_edge_direction=true, debug=true)",
        "return(message=true, store=false)",
    ]}}
    [response, message] = _do_arax_query(query)
    assert response.status == 'OK'
    assert len(message.results) == 38
    assert message.results[0].essence is not None
```
But, be advised that other types of creative "virtual" edges that are added to the query graph will require me to add their relation types to a "filter-out" list that is hard-coded within `ARAX_resultify.py`.  Also, now `_test01` is failing. But.... I think that query graph is kind of odd (LOL it was my first query graph so I didn't really get the gist of it) so I am going to push the latest code since it includes this critical bug fix.

**Comment by saramsey** [comment]
My apologies for breaking ARAX_resultify.py and going to sleep.  Mea culpa!

**Comment by edeutsch** [comment]
no worries, please let me know when it is pushed and I will roll it out to arax.rtx.ai and test.

**Comment by saramsey** [comment]
sorry, it is `_test02` that is currently failing; I'm on it.

But the key thing is -- we now seem to have essences for Example 1 and Example 2  :-)

**Comment by dkoslicki** [comment]
@saramsey 
>But, be advised that other types of creative "virtual" edges that are added to the query graph will require me to add their relation types to a "filter-out" list that is hard-coded within ARAX_resultify.py. Also, now _test01 is failing. But.... I think that query graph is kind of odd (LOL it was my first query graph so I didn't really get the gist of it) so I am going to push the latest code since it includes this critical bug fix

Why would we want virtual edges to be filtered out? These virtual edges have been added to the query graph, so are honest to goodness edges then that satisfy the query graph. And should be included in the results. Right?

**Comment by saramsey** [comment]
OK @dkoslicki and @edeutsch see latest commit (`19a8d8a`). Is this better?  All tests that are currently implemented within `ARAX_resultify.py` are passing.

**Comment by dkoslicki** [comment]
Yes, I just confirmed that all tests are passing. But was just wondering about why the hard-codedness. I'll take a look at that commit in a sec

**Comment by dkoslicki** [comment]
19a8d8a
sans quotes so I can click the link directly to it

**Comment by dkoslicki** [comment]
Right: it's line:
```python
RELATIONS_TO_FILTER_OUT_FOR_DETERMINING_LEAF_NODES = {'jaccard_index',
                                                      'probability_drug_treats'}
```
That has me concerned. Post demo, we should discuss, since the ARS may not always hand us QG's with easily identifiable leaf nodes. But I see why you did it for the demo.

**Comment by edeutsch** [comment]
@dkoslicki, while I'm thinking about it.. in another thread/issue we were discussing Patrick's "extra_nodes" / "extra_edges" idea. I think we agreed we don't like that solution and prefer including things in the QueryGraph. But I was thinking it might be a nice idea to label the QueryGraph nodes and edges that were in the originally in the user-submitted QueryGraph as "original" or some such, and then label any nodes and edges that the reasoner adds as "additional" or similar. So a reader can easily distinguish the original question from things that were added.. just a thought to air out..

**Comment by saramsey** [comment]
> Right: it's line:
> 
> ```python
> RELATIONS_TO_FILTER_OUT_FOR_DETERMINING_LEAF_NODES = {'jaccard_index',
>                                                       'probability_drug_treats'}
> ```
> 
> That has me concerned. Post demo, we should discuss, since the ARS may not always hand us QG's with easily identifiable leaf nodes. But I see why you did it for the demo.

Currently, `resultify` identifies a "leaf node" as a node whose vertex degree in the (undirected) graph is 1. So, a query graph that has both a real edge and a virtual edge between "leafnode01" and "internalnode02" will have a vertex degree of 2, and not be identified as a leaf node.  Hency my hacky filtering feature. Hmm, I guess I could *identify* (in the mathematical sense) all edges with common source and target nodes (regardless of orientation), and then compute vertex degree to identify a leaf node.  Do you like that better?

**Comment by saramsey** [comment]
OK, per @dkoslicki 's feedback I have removed `RELATIONS_TO_FILTER_OUT_FOR_DETERMINING_LEAF_NODES`, which I agree was a bad idea. I now (I hope correctly) map the QG to an undirected graph and use edge-identification to turn multiedges into single edges. It currently passes all tests.

**Comment by saramsey** [comment]
made a slight change to deal with the case if some trickster puts a self-edge in the query graph; all tests currently passing
