### ISSUE TITLE
why does the Example3 python notebook not call `resultify`?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#677]
Please forgive my ignorance; is there a reason why the Example3 python notebook doesn't call `resultify`?  Do we not want resultification for this workflow?

**Comment by edeutsch** [comment]
Just hasn't been updated yet. I'm slow..

https://github.com/RTXteam/RTX/issues/673

**Comment by saramsey** [comment]
I've updated it in my code. It works!
