### ISSUE TITLE
demo Example 2 error

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#678]
Example 2 is failing on arax.rtx.ai:

  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 597, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Overlay/predictor/LogModel.pkl'

**Comment by dkoslicki** [comment]
Will take a look after I get back tonight (late). Does that file exist on the demo branch? May be a merge or forgot to commit issue

Sent from my mobile device, please excuse my brevity and/or typos
________________________________

**Comment by edeutsch** [comment]
After some investigation, I have committed and pushed a fix, please see:
https://github.com/RTXteam/RTX/commit/513779697bce55225d598239f4017908f763683f

IMPORTANT NOTE TO EVERYONE: You cannot assume a current working directory for your code. Please use relative path finding calls similar to the above commit for any code that could be run via the API (back-end code like KG building or KGNodeIndex building or training, etc. excepted)

**Comment by edeutsch** [comment]
Also, any testing code run via main() is exempted. But all class methods should not assume a CWD.

**Comment by dkoslicki** [comment]
Whoops, completely forgot about that. Thanks for pushing the fix @edeutsch 
Tested locally and appears to work there too. Closing.
