### ISSUE TITLE
Example 2 bug: too many proteins in a result?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#680]
In our Demo Example 2, I think there are too many proteins in each result. This is potentially debatable, so we probably need a ruling from @dkoslicki before changing code. I can say it is different from the way we used to do it with RTX. But better or worse is unclear.

In our example 2 output:
https://arax.rtx.ai/devLM/?m=1419
Have a look at the first result.

The issue is that for lenalidomide, the first drug, there are 3 proteins that interact with it. And the result shows those 3 proteins and the edges. But it *also* shows *all* the proteins connected to PD, even the ones not connected to lenalidomide.

In the past (before ARAX), we would only display the proteins that were in common between PD and each drug in each result.

So the questions are:
1) *Should* we return to the way we used to do it (probably yes?)
2) And if so, *how* do we indicate that proteins that are not bi-connected are left out? Probably in reaction to is_set=true? When a QueryGraph node has is_set=true, then it only survives into the result if it is connected to *both* of its neighbors?

**Comment by saramsey** [comment]
I'm confused. Is this a bug in `ARAX_resultify.py`?

**Comment by saramsey** [comment]
Can you please paste the DSL code that produced this result, into the issue?

**Comment by edeutsch** [comment]
yes. If it's a bug at all. David can decide.

Here's what the output of this query used to look like for the RTX canned query:
https://arax.rtx.ai/devED/?m=1423

**Comment by edeutsch** [comment]
DSL is available in the GUI, it is:

add_qnode(curie=DOID:14330, id=n00)
add_qnode(type=protein, is_set=true, id=n01)
add_qnode(type=chemical_substance, id=n02)
add_qedge(source_id=n00, target_id=n01, id=e00)
add_qedge(source_id=n01, target_id=n02, id=e01, type=physically_interacts_with)
expand(edge_id=[e00,e01], kp=ARAX/KG1)
overlay(action=compute_jaccard, start_node_id=n00, intermediate_node_id=n01, end_node_id=n02, virtual_edge_type=J1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=jaccard_index, direction=below, threshold=.2, remove_connected_nodes=t, qnode_id=n02)
filter_kg(action=remove_edges_by_property, edge_property=provided_by, property_value=Pharos)
overlay(action=predict_drug_treats_disease, source_qnode_id=n02, target_qnode_id=n00, virtual_edge_type=P1)
resultify(ignore_edge_direction=true)
filter_results(action=sort_by_edge_attribute, edge_attribute=probability_drug_treats, direction=descending, max_results=15)
return(message=true, store=true)

**Comment by dkoslicki** [comment]
This is definitely a bug/unintended implementation in `resultify()`. The intention is that `resultify()` will return all paths from the drug to the disease through __all proteins that connect them both__. I.e. since `is_set=True` for n01, `resultify()` should strive to go through **all** of the proteins in that set that connect the source & target nodes. I don’t think this sort of filtering could be accomplished through the current DSL.

So: only return those that are bi-connected (I.e. are in the `is_set=True` **and** connect the source/target nodes.

**Comment by saramsey** [comment]
> DSL is available in the GUI, it is:
> 
> add_qnode(curie=DOID:14330, id=n00)
> add_qnode(type=protein, is_set=true, id=n01)
> add_qnode(type=chemical_substance, id=n02)
> add_qedge(source_id=n00, target_id=n01, id=e00)
> add_qedge(source_id=n01, target_id=n02, id=e01, type=physically_interacts_with)
> expand(edge_id=[e00,e01], kp=ARAX/KG1)
> overlay(action=compute_jaccard, start_node_id=n00, intermediate_node_id=n01, end_node_id=n02, virtual_edge_type=J1)
> filter_kg(action=remove_edges_by_attribute, edge_attribute=jaccard_index, direction=below, threshold=.2, remove_connected_nodes=t, qnode_id=n02)
> filter_kg(action=remove_edges_by_property, edge_property=provided_by, property_value=Pharos)
> overlay(action=predict_drug_treats_disease, source_qnode_id=n02, target_qnode_id=n00, virtual_edge_type=P1)
> resultify(ignore_edge_direction=true)
> filter_results(action=sort_by_edge_attribute, edge_attribute=probability_drug_treats, direction=descending, max_results=15)
> return(message=true, store=true)

thank you, checking now

**Comment by saramsey** [comment]
almost done with this bugfix; thank you @edeutsch  and @dkoslicki  for catching this!

**Comment by saramsey** [comment]
@finnagin  Can you please check out (or update your existing) `demo` branch and test `ARAX_resultify.py` by running `python3 ARAX_resultify.py`?
Then please run Example 2 using the new `ARAX_resultify.py` code (from demo branch, latest commit). Please view the results graphs in `arax.rtx.ai` to make sure that a "slimmer" set of proteins is showing up for each result.

**Comment by dkoslicki** [comment]
@edeutsch if you update the code on the UI backend https://arax.rtx.ai/devLM this would be quite easy to check.

**Comment by saramsey** [comment]
Hey @finnagin can you also please carefully check Example 1 and Example 3, to make sure that my code changes to `resultify` have not messed up those examples?  I (obviously) don't expect that the code changes will screw something up, but this bugfix was kind of tricky so I think we should be diligent in making sure that there aren't.... unintended consequences for our demo.

**Comment by edeutsch** [comment]
hmm, sorry, does not look right:
https://arax.rtx.ai/devLM/?m=1426
The first result shows that there are now *no* proteins attached to the drug.

**Comment by saramsey** [comment]
Shoot. I will work on this after class (this afternoon).  Tagging @finnagin  so he is aware.

**Comment by saramsey** [comment]
OK see my latest commit. Seems to be working now!!   @finnagin can you please test?

**Comment by finnagin** [comment]
@saramsey when I run the notebook the results don't look different but is that because the code that the api is running has not been updated with your changes yet?

**Comment by saramsey** [comment]
@finnagin please update the code on the server, thanks.

**Comment by saramsey** [comment]
Fixed!  Thank you @finnagin  for your testing help

<img width="855" alt="Screen Shot 2020-03-12 at 8 26 44 PM" src="https://user-images.githubusercontent.com/5562107/76587039-e3a46180-649f-11ea-82e8-f47bb8accad4.png">

**Comment by edeutsch** [comment]
looks good to me!

**Comment by finnagin** [comment]
Just ran through Examples 1 and 3 as well and they look good to me. Closing this issue.
