### ISSUE TITLE
can we make sqlite vs. mysql a config option for RTXFeedback.py?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#681]
Would be super nice if `RTXFeedback.py` could be (via some kind of runtime config option) set to either sqlite or mysql. Currently, I have to uncomment/comment various lines of code. sqlite is more simple to use for testing purposes.

**Comment by saramsey** [comment]
this is *obviously* a topic for post-demo; I'm just recording it here so I don't forget

**Comment by saramsey** [comment]
I decided to bite the bullet and just use MySQL to avoid having to use a hacked `RTXFeedback.py`. So this issue is less of an... issue for me. However, at some point I still would like to have a discussion about whether we could accommodate Sqlite, for situations where a user (who may be a developer/tester) prefers a more lightweight installation footprint.

**Comment by edeutsch** [comment]
sure, I can do this, should not be hard. I was once concerned about multithreading problems, because I have gotten multithread warnings from SQLite in the past, but I think I figured those out, so should not be an issue. I don't think I can do it this week or next, but after that, sure.

**Comment by saramsey** [comment]
Sweet!  For testing/dev purposes, using a local sqlite embedded DB is very compact, self-contained, and tidy. No pressure, though. I bit the bullet and got a `rtxfeedback` DB set up in mysql today and it is working just fine.

**Comment by saramsey** [comment]
Looks like this was done long ago, in `response_cache.py`:
https://github.com/RTXteam/RTX/blob/e04ae253138225a5c056a2930ed215f8e84ff373/code/ARAX/ResponseCache/response_cache.py#L99

so I'm going to close out this issue.
