### ISSUE TITLE
Link to API docs from devLM site yields Service Unavailable

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#684]
This hyperlink: https://arax.rtx.ai/devLM

Shows this page:

<img width="753" alt="Screen Shot 2020-03-13 at 10 01 26 PM" src="https://user-images.githubusercontent.com/5562107/76675398-37817a00-6576-11ea-937d-a575bc285337.png">

from which the link "API 0.9.3" takes you to this link:

https://arax.rtx.ai/devLM/api/rtx/v1/ui/

which shows this in the browser:

<img width="478" alt="Screen Shot 2020-03-13 at 10 00 03 PM" src="https://user-images.githubusercontent.com/5562107/76675411-52ec8500-6576-11ea-878c-6a098854af5a.png">

**Comment by edeutsch** [comment]
fixed.
