### ISSUE TITLE
Suggest removing output from ipython notebooks

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#685]
Currently, the [ipython notebooks](https://github.com/RTXteam/RTX/tree/demo/code/ARAX/Examples) already show the output. When running in a Jupyter instance, it makes it appear that nothing is happening. During the demo, it may be helpful to have the output text, like:
```python
Executing query at https://arax.rtx.ai/beta/api/rtx/v1/query
Please wait...
Response returned with status 200
```
removed, so it's clear that when we run it, things are actually "happening."

I realize this risks our "backup plan" of just showing the github version, but maybe we could have "pre-run" versions of the demo examples, and "not yet run" versions. And during the demo, show the "not yet run" ones. If *** hits the fan, we can then default to the "pre-run" version on github.

**Comment by saramsey** [comment]
Yes, we absolutely should keep versions of the notebooks "with output included" on-hand.

**Comment by dkoslicki** [comment]
@saramsey @edeutsch Actually, I discovered how to do this pretty quickly within Jupyter itself, so no need to make any changes. I can handle this on my end with Jupyter. Closing
