### ISSUE TITLE
resultify() not checking its parameters

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#686]
The following DSL runs without complaint:

add_qnode(name=acetaminophen, id=n0)
add_qnode(type=protein, id=n1)
add_qedge(source_id=n0, target_id=n1, id=e0)
expand(edge_id=e0)
resultify(ignore_edge_direction=true,transmit=coronavirus)
filter_results(action=limit_number_of_results, max_results=10)

The following results in a crash:

add_qnode(name=acetaminophen, id=n0)
add_qnode(type=protein, id=n1)
add_qedge(source_id=n0, target_id=n1, id=e0)
expand(edge_id=e0)
resultify(transmit=coronavirus)
filter_results(action=limit_number_of_results, max_results=10)

https://arax.rtx.ai/devED/?m=1499

**Comment by edeutsch** [comment]
This still generates a crash for me in /beta with the latest in demo:

An uncaught error occurred: parameter type is not allowed in ARAXResultify: transmit: ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 402, in executeProcessingPlan\n result = resultifier.apply(message, action[\'parameters\'])\n', ' File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_resultify.py", line 127, in apply\n self.__resultify(describe=False)\n', ' File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_resultify.py", line 153, in __resultify\n raise ValueError("parameter type is not allowed in ARAXResultify: " + str(parameter_name))\n', 'ValueError: parameter type is not allowed in ARAXResultify: transmit\n']

add_qnode(name=acetaminophen, id=n0)
add_qnode(type=protein, id=n1)
add_qedge(source_id=n0, target_id=n1, id=e0)
expand(edge_id=e0)
resultify(transmit=coronavirus)
filter_results(action=limit_number_of_results, max_results=10)

**Comment by saramsey** [comment]
oops, give me a second

**Comment by saramsey** [comment]
Sorry, I forgot, I can't throw a `ValueError` in `_resultify`. Fixing now...

**Comment by edeutsch** [comment]
yes, please don't raise any errors, otherwise the client will see a blechy stack trace.
Please check for or catch any potential errors and:
    response.error(f"Nice error message explaining the problem", error_code="SpecificErrorCode")
    return response

thanks!

**Comment by saramsey** [comment]
Yes, I know. This was just an oversight. I have fixed it in code (I think), but for some reason RTXFeedback.py has stopped working for me so it is taking me longer than I would like, to run my tests.

If I push the code change can you test it?

**Comment by saramsey** [comment]
@edeutsch can you please test now?  I need to fix my `RTXFeedback.py` + associated database on my local system but right now it is giving errors.

**Comment by edeutsch** [comment]
Yes, no more crash, thanks.
Although this:

add_qnode(name=acetaminophen, id=n0)
add_qnode(type=protein, id=n1)
add_qedge(source_id=n0, target_id=n1, id=e0)
expand(edge_id=e0)
resultify(ignore_edge_direction=moo)
filter_results(action=limit_number_of_results, max_results=10)

yields this:
The two nodes for KG edge 900006, UniProtKB:P09917 and CHEMBL.COMPOUND:CHEMBL112, have no corresponding edge in the QG

which still seems like not so good checking

and:
add_qnode(name=acetaminophen, id=n0)
add_qnode(type=protein, id=n1)
add_qedge(source_id=n0, target_id=n1, id=e0)
expand(edge_id=e0)
resultify()
filter_results(action=limit_number_of_results, max_results=10)

yields:
parameter type is not allowed in ARAXResultify:

which is a bit odd and doesn't help the user debug.

Related, should
resultify()

be allowed? Seems like we always include the parameter "ignore_edge_direction=true"
Could that just be a default and thus just resultify() be enough?

**Comment by dkoslicki** [comment]
@saramsey In case it helps, I’ve found the following paradigm useful when creating errors in the way Eric suggested:
```python
        try:
            for node in self.message.knowledge_graph.nodes:
                node_curie_to_name[node.id] = node.name
        except:
            tb = traceback.format_exc()
            error_type, error, _ = sys.exc_info()
            self.response.error(f"Something went wrong when converting names")
            self.response.error(tb, error_code=error_type.__name__)
```
That way, you get both an error you can describe, as well as a brief stack trace with the error code as well.

**Comment by saramsey** [comment]
I have a `debug` parameter, which defaults to `false`. If it is set to `true`, then `apply` will raise an exception (which is the pythonic way). If the `debug` parameter is `false`, then error messages are logged using `response.error` as suggested. 

TBH I favor making `ARAX_query` do exception handling using try blocks internally. Calling from `ARAX_query` to `ARAX_resultify` is (always) python to python, so what is the reason not to use the mainstream pythonic method of error handling, for that inter-module call?  

Having said that, I understand why `ARAX_query` methods themselves cannot raise exceptions.

**Comment by dkoslicki** [comment]
Re: Eric’s comment: hence the (non-elegant, but functional) [checking of allowable parameters](https://github.com/RTXteam/RTX/blob/demo/code/ARAX/ARAXQuery/ARAX_overlay.py#L66-L85) and [defining of allowable parameters](https://github.com/RTXteam/RTX/blob/demo/code/ARAX/ARAXQuery/ARAX_overlay.py#L156-L169) which [are then checked](https://github.com/RTXteam/RTX/blob/demo/code/ARAX/ARAXQuery/ARAX_overlay.py#L188-L191).

**Comment by saramsey** [comment]
Yes, `resultify()` should be allowed.

**Comment by saramsey** [comment]
I'll look into the `ignore_edge_direction=moo` issue.

As for `resultify()` causing an error; I suspect an empty parameter is being passed?  Need to investigate. I have a 10:00 meeting though. ETA on a bugfix is 11:30.

**Comment by saramsey** [comment]
never mind, I see that `ARAX_query` is in fact using a try block. Not sure why when ARAX_resultify throws a ValueError it causes problems on the server side, then. But anyhow, I will continue debugging the `ignore_edge_direction=moo` issue.

**Comment by saramsey** [comment]
@edeutsch wrote:

> Although this:

```
add_qnode(name=acetaminophen, id=n0)
add_qnode(type=protein, id=n1)
add_qedge(source_id=n0, target_id=n1, id=e0)
expand(edge_id=e0)
resultify(ignore_edge_direction=moo)
filter_results(action=limit_number_of_results, max_results=10)
```

> yields this:

`The two nodes for KG edge 900006, UniProtKB:P09917 and CHEMBL.COMPOUND:CHEMBL112, have no corresponding edge in the QG`

> which still seems like not so good checking

fixed (see test `_test_issue686c`

**Comment by edeutsch** [comment]
It isn't an inherent problem if any of the modules raise an error, but the result is very inelegant for the user to see a stack trace. There will of course occasionally be errors that go uncaught and that's okay. ARAXQuery does catch them, but all it can say is that something went wrong and here's a stack trace (icky). It would be nicer of the module can report specific problems. Certainly at minimum not crashing on basic parameter flubs seems nice. Not a super high priority. Several modules already have generic examples of parameter checking.

**Comment by saramsey** [comment]
@edeutsch wrote:

> and:

```
add_qnode(name=acetaminophen, id=n0)
add_qnode(type=protein, id=n1)
add_qedge(source_id=n0, target_id=n1, id=e0)
expand(edge_id=e0)
resultify()
filter_results(action=limit_number_of_results, max_results=10)
```

> yields:
```
parameter type is not allowed in ARAXResultify:
```

> which is a bit odd and doesn't help the user debug.

Fixed with a hack. I think there is a parser bug (see #688)
