### ISSUE TITLE
DSL parser passes an empty parameter when the argument list is empty

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#688]
The DSL command
```
resultify()
```
Results in an entry in the `parameters` dictionary that has an empty key. This is causing problems for downstream parameter-checking code. 

Not high priority b/c I can implement a simple workaround to filter this out, but it seems like sub-optimal behavior by the parser.

**Comment by dkoslicki** [comment]
@saramsey I’ve tried `resultify()` a number of times and it appears to be working just fine. Do you want to close due to #788?

**Comment by edeutsch** [comment]
closing ancient history
