### ISSUE TITLE
edge probabilities displayed in the UI have too many significant digits

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#689]

**Comment by saramsey** [comment]
<img width="473" alt="Screen Shot 2020-03-16 at 12 32 08 PM" src="https://user-images.githubusercontent.com/5562107/76793399-34f37000-6782-11ea-898e-28c04e1edf37.png">

**Comment by edeutsch** [comment]
These are just the numbers as presented in the JSON. I would suggest that the GUI has no idea what precision is appropriate. But rather the code that is computing those numbers has the best chance of understanding what precision is appropriate and should round accordingly. I suspect if that code rounds appropriately and puts that in the JSON, it will automatically be displayed right on the screen.

If you push back, we can certainly do this in the presentation layer, but that doesn't seem like the best place to put it.

Are there times when both 0.94 and 0.9998 might be appropriate?

**Comment by dkoslicki** [comment]
Yeah, these are just the numbers that @finnagin ML model spits out. IMHO, 5 significant digits is sufficient. Can push a fix if urgent.

**Comment by saramsey** [comment]
@edeutsch wrote:
> I would suggest that the GUI has no idea what precision is appropriate.
I respectfully disagree.  In a GUI meant for a human, we (the users) probably want to see a default three significant digits. Cases where I want to see more digits than that are relatively rare for this kind of statistical summarization/estimation. (Yes I am aware that in other disciplines there are measurements like speed of light where we care about precision to 10 digits). We can have the precision configurable in the UI if someone really wants more. I think it would be sub-optimal if the reasoning code pre-truncated its significance estimates based on an assumed number of desired significant digits.

**Comment by edeutsch** [comment]
okay, I'm happy to go along with this. @isbluis want to implement this?

**Comment by isbluis** [comment]
Sure thing.

Is there a full list of entities for which we should do this?  e.g. Jaccard index...

**Comment by dkoslicki** [comment]
@isbluis edges that have attributes with the following names:
```
probability_drug_treats
jaccard_index
ngd
paired_concept_freq
observed_expected_ratio
chi_square
```

**Comment by isbluis** [comment]
Great, thanks @dkoslicki

**Comment by saramsey** [comment]
Can we just put the fix in devLM for the time being?  I'm scared of something breaking in /beta, this close to the demo.

**Comment by isbluis** [comment]
Sure thing, though I have a medical appointment in a few minutes and won't be able to do this until tonight.

**Comment by saramsey** [comment]
From my standpoint this is not urgent. LM, please take care of yourself.

**Comment by isbluis** [comment]
Ok, this is ready in devLM.   ( <shift>-reload! )

It only works on the edge_attributes that @dkoslicki listed.  Do we also want to do the same for other values, such as weight, confidence, etc?

**Comment by edeutsch** [comment]
Edge attributes look good to me!
https://arax.rtx.ai/devLM/?m=1552

And for other attributes, I would say yes
e.g. here:
https://arax.rtx.ai/devLM/?m=1553

**Comment by isbluis** [comment]
Ok, I have added weight and confidence as well.

Let me know if it passes muster, and I'll push the changes (if desired)

**Comment by edeutsch** [comment]
3 significant figures it is! Looks fancy!
![image](https://user-images.githubusercontent.com/12707718/76817900-68a1ba80-67c1-11ea-95b3-fceea7dd1502.png)

push it!

**Comment by isbluis** [comment]
Ok, pushed to demo/

**Comment by edeutsch** [comment]
tested and rolled out to beta. Nothing like night-before code rollouts. Would be good to test the examples 1,2,3,4 again in the morning. Seems to be in good shape to me!

thanks!

**Comment by isbluis** [comment]
Hi @dkoslicki , @saramsey ,
 
> 
> @isbluis edges that have attributes with the following names:
> 
> ```
> probability_drug_treats
> jaccard_index
> ngd
> paired_concept_freq
> observed_expected_ratio
> chi_square
> ```

It looks like `ngd` has been renamed to `normalized_google_distance` .  Or perhaps a new metric?  Either way, I suppose I should also add it to the list of values to truncate, but let me know otherwise.  Sorry if I missed this.  

Any others?

![image](https://user-images.githubusercontent.com/37852256/94042643-b4d94300-fd80-11ea-8e8f-b4bb0d1795cc.png)

**Comment by isbluis** [comment]
Closing this unless there are other attributes that require truncation.

nb. `normalized_google_distance` was added to the list with commit e1251c83d92af16f808cbf391e4b298b2b9641b3
