### ISSUE TITLE
No disease or phenotype for "Uterine atony" in the KG 

### ISSUE THREAD

**Issue by jaredroach** [RTXteam/RTX#69]
I cannot find a disease or phenotype for "Uterine atony" in the KG.
I went with "uterus" for the gold standard
for COP #26 
CARBETOCIN | Uterine atony

**Comment by dkoslicki** [comment]
@saramsey shall we add this to the seeds tsv? #48

**Comment by dkoslicki** [comment]
If it's not in MONDO, DO, or HPO, I guess there's not much that can be done at this point. Shall we close this issue or table it until #64 is finished?

**Comment by saramsey** [comment]
Let’s mark it LOWPRIORITY.

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Apr 16, 2018, at 4:27 PM, David Koslicki <notifications@github.com<mailto:notifications@github.com>> wrote:


If it's not in MONDO, DO, or HPO, I guess there's not much that can be done at this point. Shall we close this issue or table it until #64<https://github.com/RTXteam/RTX/issues/64> is finished?

**Comment by dkoslicki** [comment]
done!
