### ISSUE TITLE
can we use NGD in order to expand a KG?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#693]
Question posed by Noel Southall during the March 17 demo.

**Comment by edeutsch** [comment]
Just occurs to me that this is also related to #664

**Comment by saramsey** [comment]
EWD: we should get fastNGD working first; then work on this

**Comment by edeutsch** [comment]
...and by "working" I mean "returning a result (or Inf) in <0.1s for >90% of our KG nodes without needing do the slow consult to eutils."

I wonder if FastNGD distinguishes between "I know these two concepts and their distance is Inf" and "I don't know both of these concepts, go ask eutils"? The former is very fast but the latter is very slow (after hitting eutils)

**Comment by amykglen** [comment]
we're tracking implementation of `expand(kp=NGD)` in issue #975 now, so I think it's safe to close this one
