### ISSUE TITLE
Sync all branches, return to master as main branch

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#697]
- [x] merge master into demo (resolve conflicts, commit, push)
- [x] merge demo into master (commit, push)
- [x] merge master into expander (resolve conflicts, commit, push)
- [x] merge expander into master
- [x] repeat for filter
- [x] repeat for overlay
- [x] switch back to master being main branch of repo

And test, test, test at each step

**Comment by dkoslicki** [comment]
`ARAX_query.py` tests 3, 12, 15, 20, and 1212 all passing. `master` is now again the default branch. All relevant branches in sync with master.

**Comment by dkoslicki** [comment]
@edeutsch No objections here! Out with the old and in with the new!

**Comment by edeutsch** [comment]
Done! The old is out and the in new is in!
production
/beta
/test
/devED
/devLM

have all been switched to the master branch, KGNodeIndex updated, services restarted, etc.

Everything is now running master ARAX.
Let me know if you notice any problems.

**Comment by edeutsch** [comment]
BTW, I also just upgraded all relevant Python modules on arax.rtx.ai's Python 3.7.3 installation.

**Comment by edeutsch** [comment]
...and everything still seems to run fine.
