### ISSUE TITLE
DSL generator

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#699]
I think there is one more necessary component of ARAX that we should put some thought into: the DSL generator. The DSL is nice and great and super flexible, but the reality is probably that the ARS will be sending us just QueryGraphs and we need to answer those query graphs well.

For example, currently if one sends the Parkinsons disease query as an input graph, it gets squirted into the QueryGraphReasoner which just does some sort of cipher query and done.

What we really need (IMO, up for discussion) is a layer that looks at a plain incoming QueryGraph and says "ah, specific disease node, linked to nodes of type A with is_set=true, linked to nodes of type B, hmm, in order to answer that nicely I'm going to generate some DSL that will apply our tools (Expander, Jean Luc Jaccard, Carrie Fisher, NGD, etc) and deliver a nice answer to this query". Same goes for our canned queries. If someone poses a query like canned Q16, instead of calling out to Q3Solution.py, the DSL generator should write some DSL that nicely answers that question and run that instead.

Thoughts?

**Comment by dkoslicki** [comment]
Ideas: Somehow encode in the QG (or in metadata in the API) hints/flags/additional information that somehow indicate:
1. What kind of underlying biological question is desired
2. What sorts of bioentities are "important" 
3. What kinds of bioentities they want more/less of
4. Do they want max/min, short/long, etc.

**Comment by edeutsch** [comment]
Thinking about the Parkinson's query, I struggle to see how to apply these. Specifically:
1. Seems too vague to encode somehow. I don't see how.
2. in the Parkinson's query, there are there are three nodes of different types. I don't see how any are more important than another and how that influences our DSL
3. Again, in this context, I don't see how to apply beyond a general hint "top 10 results" vs. "all results"
4. hmm?

I don't really see how these influence aspects the DSL commands that we selected for our particular case. It seems to me that pretty much all of our non-obvious DSL commands that we used are centered around determining relevance or confidence, which I would argue a) everyone wants but b) will be highly specific to each implementation and few clients could/should know about details of this, unless they really want to roll up their sleeves and get nerdy, which we support with direct DSL.

I can certainly see a distinction between "give me the top 10 most relevant (sorted by most relevant)" and "give me all answers (sorted by most relevant)". Maybe this could be extended by "aggressive pruning during processing" vs. "lax pruning". But again, I don't see how most clients would know how aggressively to prune while working. Maybe the client could specify "efficient" vs. "exhaustive" and that might influence what thresholds are set in the autogenerated DSL.

So, for these I would argue that "top 10" vs. "unlimited" and "efficient" vs. "exhaustive" aren't really decorations to the QG, but rather just general query options. I can visualize our DSL generator taking into account these query options and tweaking the DSL to accommodate these preferences.

Am I missing something? Do we have other questions -> DSL where these aspects 1-4 are more clearly applied?

**Comment by dkoslicki** [comment]
For our discussion on Friday, a few thoughts about how my above comment could apply to the following Parkinson's question (in our DSL as it's easier to grok than a true API QG):
```python
 query = { "previous_message_processing_plan": { "processing_actions": [
            "create_message",
            "add_qnode(curie=DOID:14330, id=n00)",
            "add_qnode(type=protein, is_set=true, id=n01)",
            "add_qnode(type=chemical_substance, id=n02)",  # <--- somehow indicate that this is the desired result (a QG could have many qnodes without curies specified, not all of which are the "essence" of the result).
            # for example, this same QG could be used for the question "what proteins are associated with Parkinsons that have drugs that target them?" and then the desired result is a list of proteins, not drugs
            "add_qedge(source_id=n00, target_id=n01, id=e00)",  # <--- somehow indicate here that you want "many" such connections (i.e. maximize the connections between n00 and n01)
            "add_qedge(source_id=n01, target_id=n02, id=e01, type=physically_interacts_with)",  # <--- same as above: maximize connections between n01 and n02
            "expand(edge_id=[e00,e01], kp=ARAX/KG1)",  # <-- somehow indicate here or elsewhere that the connections you desire relate the disease n00 and the drug n02.
            <snip>
            ] } }
```

**Comment by dkoslicki** [comment]
@edeutsch should we close this in light of the current QG interpreter code?

**Comment by edeutsch** [comment]
agreed, closing.
