### ISSUE TITLE
Reasoner seems to be commonly distracted by a few "promiscuous" nodes

### ISSUE THREAD

**Issue by jaredroach** [RTXteam/RTX#70]
distracted by immune genes and pathways (e.g., b-cell recptors, clotting factors) - Many ludicrous answers include some common bad actors
e.g., immune genes and pathways (e.g., b-cell recptors, clotting factors)

**Comment by dkoslicki** [comment]
Probably a result of pairwise google distance not taking disease context into account. this may improve after #63.

**Comment by dkoslicki** [comment]
@jaredroach It would be helpful to have concrete examples of where/when these nodes are showing up

**Comment by jaredroach** [comment]
It's the list you sent me for the answers to COPs. Algorithm:
set count for every node to zero
for each question, if node occurs in at least one answer, augment count for that node by one
those nodes with a lot of hits are likely to be promiscuous
I also added in multicellular organism which really shouldn't appear in any answers, and since we saw it in at least one, it is likely to be promiscuous.

**Comment by dkoslicki** [comment]
Closing due to #788 and DSL enhancements that ameliorate this
