### ISSUE TITLE
Should Expander have options to control related nodes?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#700]
Initially we had Expander just expand based on the one CURIE it was given.

Now Amy is implementing expanding the scope to expand from all synonyms.
Should there be an explicit option to control that? Or is there already?

And then what about children? Option to expand to children of the requested node? Should that be in Expander() or where? (i.e. if the question is what are the symptoms of malaria? then should/could that be expanded to children of malaria, e.g. cerebral malaria)

And then what about nearly related terms? I suppose we don't have that map yet. But will we soon have a map of highly similar terms?

**Comment by amykglen** [comment]
> Now Amy is implementing expanding the scope to expand from all synonyms.
Should there be an explicit option to control that? Or is there already?

yeah, I've been wondering this as well - I started by making KG2 expands _always_ use synonyms, but I'm not sure what will ultimately be best here. should it only happen with a flag like `use_synonyms=true`? and if so, should that flag exist on expand? or on qnodes?

**Comment by edeutsch** [comment]
I think it ought to be controllable with a parameter. I would for now add a parameter to Expand() to control this. Perhaps the default is `use_synonyms=true`. 

But I can see this as good case where the QueryGraph could be augmented with user preferences.

A QueryNode with a CURIE could allow:
consider_exact_synonyms=true/false
consider_all_children=true/false
consider_related_concepts=true/false

Related concepts is a bit fuzzy, but maybe we can build some sort of a mapping of related things. Perhaps "Plasmodium vivax malaria" is not a direct child of "malaria", but maybe we can infer and tag them as "related" and allow reasoning over those?

**Comment by amykglen** [comment]
Adding a `use_synonyms` parameter to `expand` sounds good to me for now. (Agree it should be controllable.) Although one weird thing about that is that specifying `use_synonyms=true` in an `expand` call wouldn't do anything if `kp=ARAX/KG1` at this point (since synonym functionality has only been added for KG2). Do we want to add synonym functionality for KG1 expands as well?

I like the thoughts about augmenting QueryNodes.

**Comment by edeutsch** [comment]
The KGNodeIndex actually does have synonym information for KG1, I just implemented the synonym method for KG2 only, since if seemed like that is where we are moving to. We can easily add KG1 synonym support for KG1. (but, do we really want to be adding code that can deal with either KG1 or KG2? Or just make a clean break to KG2? #664. Unless we decide that there are multiple more supported KPs and we want to have a KGNodeIndex for all/more of them?)

**Comment by amykglen** [comment]
think we can close this issue? it's quite old and I don't think any action items remain here..

**Comment by edeutsch** [comment]
Agreed, I will close.
There was some talk today at the hackathon about implementing a QueryGraph hint on QNode that was essentially "exact", "narrow", or "wide", where
exact means only that concept
narrow means that concept or any children
wide means ??... any parent? seemed to make sense at the time although I don't get it now.
