### ISSUE TITLE
filter_kg removing all edges in ARAX_query.py 203

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#702]
In `ARAX_query.py 203`
```
query = { "previous_message_processing_plan": { "processing_actions": [
            "create_message",
            #"add_qnode(id=n00, curie=DOID:0050156)",  # idiopathic pulmonary fibrosis
            "add_qnode(curie=DOID:9406, id=n00)",  # hypopituitarism, original demo example
            "add_qnode(id=n01, type=chemical_substance, is_set=true)",
            "add_qnode(id=n02, type=protein)",
            "add_qedge(id=e00, source_id=n00, target_id=n01)",
            "add_qedge(id=e01, source_id=n01, target_id=n02)",
            "expand(edge_id=[e00,e01], kp=ARAX/KG2)",
            "overlay(action=overlay_clinical_info, observed_expected_ratio=true, virtual_edge_type=C1, source_qnode_id=n00, target_qnode_id=n01)",
            "return(message=true, store=false)",
            ] } }
```
We get 120 edges with `observed_expected_ratio` attributes, some with large values: `Max of attribute observed_expected_ratio: 6.495006394548449`
However, applying filter to the command after the overlay:
```
filter_kg(action=remove_edges_by_attribute, edge_attribute=observed_expected_ratio, direction=below, threshold=0, remove_connected_nodes=t, qnode_id=n01)
```
removes __all edges__ in the KG.

This behavior is not observed when using KG1 for expand:
```
"expand(edge_id=[e00,e01], kp=ARAX/KG1)"
```
Consider this a subissue of #698

**Comment by finnagin** [comment]
@dkoslicki Just to clarify is the line `#"add_qnode(id=n00, curie=DOID:0050156)",  # idiopathic pulmonary fibrosis` supposed to be commented out in this example?

**Comment by dkoslicki** [comment]
Yup, it's meant to be commented out, as I want to flip back and forth between trying out these two diseases (as one was for the demo, the other was one that Noel asked us about)

**Comment by finnagin** [comment]
@dkoslicki So it looks like when running that example on kg2 every chemical substance node in the knowledge graph is connected to at least one edge with `observed_expected_ratio` less than 0. Thus every chemical substance node gets removed (since `remove_connected_nodes=t`) and since these are the middle nodes in the query graph this results in removing every edge in the graph.

**Comment by dkoslicki** [comment]
Ah, curious! I wonder if this is due to [the issue that Amy identified](https://github.com/RTXteam/RTX/issues/698#issuecomment-611655193) in #698. Do you know if the KG1 nodes are a subset of the KG2 nodes on this query? If so, then this should not be happening (and we’ll need to investigate further). If not, then we definitely need to address the issue that KG1 is not a proper subset of KG2. Given that COHD only cares about CURIEs, it make me think that this could indeed be the case.
LMK, if this is the case, and if so, I’ll open a separate issue given that this KG1\not \subset KG2 issue has impacted a number of issues in the transition to KG2.

**Comment by finnagin** [comment]
@dkoslicki It looks like the sets of kg1 nodes for n00 (the disease) and n01 (the chemical substances) are a subset of the nodes returned for kg2. However the set of nodes for n02 (the proteins) in kg1 is not a subset of kg2.

Not sure if this is useful but here are the proteins that appear in kg1 that do not appear in kg2:
```
{'UniProtKB:P21462', 'UniProtKB:P04278', 'UniProtKB:Q9Y5N1', 'UniProtKB:Q9UBE8', 'UniProtKB:P49019', 'UniProtKB:Q15418', 'UniProtKB:Q9BUB5', 'UniProtKB:O43174', 'UniProtKB:P22607', 'UniProtKB:P03951', 'UniProtKB:P34995', 'UniProtKB:P49841', 'UniProtKB:O43318', 'UniProtKB:Q9H0K1', 'UniProtKB:P03901', 'UniProtKB:Q9Y5Y4', 'UniProtKB:Q96SB4', 'UniProtKB:P14416', 'UniProtKB:P15538', 'UniProtKB:O95298', 'UniProtKB:P33032', 'UniProtKB:P30872', 'UniProtKB:P98170', 'UniProtKB:P16499', 'UniProtKB:O75676', 'UniProtKB:P05067', 'UniProtKB:Q13822', 'UniProtKB:Q14524', 'UniProtKB:P03952', 'UniProtKB:Q9NY47'}
```

**Comment by amykglen** [comment]
FYI, just checked on this in light of completion of #705 - it looks like now filter is **not** removing all edges in the KG (593 nodes, 1318 edges remain after the `filter_kg` command). So I think this issue might be resolved?

**Comment by dkoslicki** [comment]
Tested on master and appears to work! Adding the "test in production" tag now

**Comment by dkoslicki** [comment]
Test via `ARAX_query.py 203` or with the DSL
```
"create_message",
            "add_qnode(curie=DOID:9406, id=n00)",  # hypopituitarism, original demo example
            "add_qnode(id=n01, type=chemical_substance, is_set=true)",
            "add_qnode(id=n02, type=protein)",
            "add_qedge(id=e00, source_id=n00, target_id=n01)",
            "add_qedge(id=e01, source_id=n01, target_id=n02)",
            "expand(edge_id=[e00,e01], kp=ARAX/KG2)",
            "overlay(action=overlay_clinical_info, observed_expected_ratio=true, virtual_edge_type=C1, source_qnode_id=n00, target_qnode_id=n01)",
            "overlay(action=compute_ngd, virtual_edge_type=N1, source_qnode_id=n01, target_qnode_id=n02)",
            "filter_kg(action=remove_edges_by_attribute, edge_attribute=observed_expected_ratio, direction=below, threshold=2, remove_connected_nodes=t, qnode_id=n01)",
            "filter_kg(action=remove_orphaned_nodes, node_type=protein)",
            "return(message=true, store=false)"
```
Should return a KG with 17 edges with the ` observed_expected_ratio` property

**Comment by amykglen** [comment]
I just checked that DSL on production, and it does indeed return a KG with 17 `observed_expected_ratio` edges:
```
2020-06-29 19:27:34.225660 DEBUG:  Number of edges in KG by attribute Counter({'normalized_google_distance': 5848, 'relation_curie': 817, 'simplified_relation_curie': 817, 'simplified_relation': 817, 'edge_label': 817, 'observed_expected_ratio': 17})
2020-06-29 19:27:34.225718 DEBUG:  Storing resulting Message
2020-06-29 19:27:53.783229 INFO:  Processing is complete. Transmitting resulting Message back to client.
```
https://arax.rtx.ai/?m=2514

so I think this issue can be closed!

**Comment by finnagin** [comment]
Awesome @amykglen thanks for double checking! Closing now.
