### ISSUE TITLE
ingest up to date KG1 into kg2endpoint2.rtx.ai

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#705]
To address [this problem](https://github.com/RTXteam/RTX/issues/698#issuecomment-611655193
) and [this problem](https://github.com/RTXteam/RTX/issues/702#issuecomment-611959256
) in #698 and #702.

- [x] figure out which kg1 is most up to date
- [x] update kg2endpoint2.rtx.ai

**Comment by amykglen** [comment]
documenting for the record: 

- it's a bit unclear whether `arax.rtx.ai` or `kg1endpoint.rtx.ai` is more up to date
- we decided to go with `arax.rtx.ai`, as it has more edges (3.8 million vs. 3.5 million)

I've begun rebuilding KG2 using the `arax.rtx.ai` KG1 (edited the config file on `kg2dev` to point to `arax.rtx.ai` vs. `kg1endpoint.rtx.ai`, re-extracted KG1, and now doing a partial build to incorporate the changes).

will post again when the build is finished and close this issue out.

**Comment by amykglen** [comment]
ok - `kg2endpoint2` has been updated to use the KG1 at `arax.rtx.ai`.

now the [query that was finding only two proteins](https://github.com/RTXteam/RTX/issues/698#issuecomment-611655193) between Parkinson's and cilnidipine finds four:

![Screen Shot 2020-04-15 at 11 10 48 AM](https://user-images.githubusercontent.com/49423686/79366633-c8e36380-7f09-11ea-97e7-c79acd5304d3.png)

**Comment by amykglen** [comment]
Hmm.. reopening this as somehow the latest KG2 build seems to have ingested `kg1endpoint.rtx.ai` again, rather than `arax.rtx.ai`... plan to fix and do a partial build again.

**Comment by amykglen** [comment]
Ok, this is fixed again (and it should stay that way for future builds - it was just a matter of uploading the edited config file to S3)
