### ISSUE TITLE
Make the KG2 provided_by relationship property a list of CURIE strings

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#706]
And see if anything breaks wrt indexing, etc.

**Comment by dkoslicki** [comment]
relevant to #698 and [this comment](https://github.com/RTXteam/RTX/issues/698#issuecomment-611791941
)

**Comment by finnagin** [comment]
Looks like this can be done with neo4j admin-import.

https://neo4j.com/docs/operations-manual/current/tools/import/file-header-format/

https://neo4j.com/docs/operations-manual/current/tutorial/import-tool/  (section B.2.6)

**Comment by finnagin** [comment]
Will need to change the json to tsv file to write arrays as ';' separated and change the import header of the privided_by field as `provided_by:string[]`

**Comment by saramsey** [comment]
nice work, @finnagin and @dkoslicki !

**Comment by finnagin** [comment]
@amykglen If you do a git pull next time you run a new build of kg2 it should encode the provided_by relationship property as a list instead of a string of a list.

**Comment by dkoslicki** [comment]
@finnagin @amykglen after this build, let us know here if successful (and helps with Finn’s issue with odd list parsing in the DSL) and then we can close this (See #721 )

**Comment by amykglen** [comment]
Sounds good - fyi, I [pushed a fix](https://github.com/RTXteam/RTX/commit/9bde9e32b169b66e32da2c549b91a5fb4e861acf) a while back to `expand` that made it so this field is an actual list (and not a string of a list, as it used to be) on `Edge`s from KG2 in `Message.KnowledgeGraph`. So we're not waiting on this build for further ARAX work (it won't change what the property looks like within ARAX - it's already a list).

**Comment by finnagin** [comment]
Thanks @amykglen! I didn't realize you had done that already. I'll see if that fixes the issue.

**Comment by amykglen** [comment]
@finnagin  - Ok, so I just did another KG2 build, and it looks like maybe `edge.provided_by` isn't quite right yet - it does appear to be a list now, but within that list, it's still a string of a list.

An example from `kg2endpoint2` neo4j:
```
{
   "simplified_relation_curie":"RO:0002606",
   "simplified_relation":"http://purl.obolibrary.org/obo/RO_0002606",
   "negated":"False",
   "relation_curie":"SEMMEDDB:treats",
   "subject":"CUI:C0031965",
   "edge_label":"treats",
   "update_date":"2018-03-06 06:22:53",
   "relation":"https://skr3.nlm.nih.gov/SemMedDB#treats",
   "simplified_edge_label":"is_substance_that_treats",
   "publications_info":"{'PMID:9345019': {'publication date': '1997 Nov 1', 'sentence': 'There was a high risk of progression to myelofibrosis in       the patients treated by HU, which was significantly higher than with Pi.', 'subject score': 1000, 'object score': 1000}}",
   "provided_by":[
      "['https://skr3.nlm.nih.gov/SemMedDB']"
   ],
   "publications":"['PMID:9345019']",
   "object":"CUI:C0026987"
}
```

**Comment by finnagin** [comment]
Odd. I'll look into that.

**Comment by finnagin** [comment]
When I run `match (n)-[r]-(m) where length(r.provided_by) > 2 return r.provided_by limit 5` I get the following:


r.provided_by
|--|

["['https://identifiers.org/umls/NDFRT'", "'https://identifiers.org/umls/MTH'", "'https://skr3.nlm.nih.gov/SemMedDB']"]
--
["['https://identifiers.org/umls/NDFRT'", "'https://identifiers.org/umls/MTH'", "'https://skr3.nlm.nih.gov/SemMedDB']"]
["['https://identifiers.org/umls/NDFRT'", "'https://identifiers.org/umls/MTH'", "'https://skr3.nlm.nih.gov/SemMedDB']"]
["['https://identifiers.org/umls/NDFRT'", "'https://identifiers.org/umls/MTH'", "'https://skr3.nlm.nih.gov/SemMedDB']"]
["['https://identifiers.org/umls/NDFRT'", "'https://identifiers.org/umls/MTH'", "'https://skr3.nlm.nih.gov/SemMedDB']"]



So it looks like the square brackets are getting placed in on the outside entries in the list. and the middle entry is getting double quotes around single quotes as well.

**Comment by saramsey** [comment]
Hey @finnagin what's the status of this issue?

**Comment by saramsey** [comment]
Update from Deepak:

> Hi Steve,
> 
> Yes, the provided_by field is now set to be multi-valued. I just merged a long standing PR.
> Of course the discussion on #336 was leaning towards a more complex representation for provided_by, but we hope to iterate on this in the coming weeks alongside our discussion on provenance.
> 
> Cheers,
> 
> Deepk
> 

>

**Comment by saramsey** [comment]
this is waiting on the next KG2 build (estimated 1-2 weeks)

**Comment by saramsey** [comment]
Looks like this is done in KG2, at least in the latest build in the dev/test Neo4j (kg2endpoint.rtx.ai):

<img width="683" alt="Screen Shot 2020-07-23 at 4 09 06 PM" src="https://user-images.githubusercontent.com/5562107/88347128-de350e80-ccfe-11ea-9f87-2e93645a596e.png">

**Comment by finnagin** [comment]
@saramsey can this be closed now? I just double checked on kg2canonicalized2.rtx.ai and kg2endpoint-kg2-3-4.rtx.ai and all looks good to me.

**Comment by saramsey** [comment]
thank you @finnagin
