### ISSUE TITLE
Develop DSL translations for RTX canned queries and improve ARAX

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#708]
In order to further test our DSL, and develop a training set for the proposed QueryGraphInterpreter (#699), and in general think about how to improve ARAX, Eric will create a doc that explores that mapping of RTX canned queries to ARAX DSL.

Document still in progress is here:
https://docs.google.com/document/d/18bbeTlkH-sdeDqqyl8ZFzBHyZSkg8awuUec1H_kff8c/edit#
Not finished, but lots of food for thought and coding here.

**Comment by saramsey** [comment]
thank you for getting the ball rolling on this

**Comment by edeutsch** [comment]
careful what you thank me for!
![image](https://user-images.githubusercontent.com/12707718/79169536-8ef74d80-7da1-11ea-93d7-033deeda59d7.png)

**Comment by dkoslicki** [comment]
@edeutsch Are you happy with the state of things for the QG interpreter? If so, shall we close?

**Comment by edeutsch** [comment]
I think it still needs to be better. Or maybe we don't need it at all. Not sure which. But, yes, we can close this ancient history.
