### ISSUE TITLE
Update KGNodeInex methods to work on either KG1 or KG2

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#709]
We decided on Friday that the KGNodeIndex synonym methods should work on either KG1 or KG2. I think it was because KG1 also has a modest level of synonyms and it would be useful for testing our synonym reasoning on KG1. I confess I can't remember a better reason than that. Was there one? Might be good to document it here.

**Comment by edeutsch** [comment]
I have pushed this to master now. The default is still KG2 since that has the most complete synonym table and was the previous behavior. But if you want to work in the KG1, that is now possible. Let me know if this doesn't work for you. BTW, the ALL CAPS thing is a side effect of trying to do case insensitive lookups. If that ALL CAPS is bothersome, it is possible to fix but will require some code reworking, schema change, and database rebuild.

        kgNodeIndex = KGNodeIndex()
        test = "DOID:9281"
        curies = kgNodeIndex.get_equivalent_curies(test,kg_name='KG1')
        print(f"{test} = " + str(curies))
        curies = kgNodeIndex.get_equivalent_curies(test,kg_name='KG2')
        print(f"{test} = " + str(curies))
        equivalence_mapping = kgNodeIndex.get_equivalent_entities(test,kg_name='KG1')
        print(json.dumps(equivalence_mapping,sort_keys=True,indent=2))
        equivalence_mapping = kgNodeIndex.get_equivalent_entities(test,kg_name='KG2')
        print(json.dumps(equivalence_mapping,sort_keys=True,indent=2))

DOID:9281 = ['REACT:R-HSA-2160456', 'DOID:9281', 'OMIM:261600']

DOID:9281 = ['CUI:C0031485', 'LNC:LP56980-3', 'LNC:LA21169-0', 'MEDDRA:10034872', 'MEDCIN:32390', 'MEDLINEPLUS:1231', 'NCIT:C81315', 'NCI_NCI-GLOSS:CDR0000446806', 'NCI_NICHD:C81315', 'OMIM:261600', 'Orphanet:716', 'MONDO:0009861', 'DOID:9281', 'REACT:R-HSA-2160456']

{
  "DOID:9281": {
    "equivalent_identifiers": [
      {
        "identifier": "REACT:R-HSA-2160456",
        "label": "PHENYLKETONURIA"
      },
      {
        "identifier": "DOID:9281",
        "label": "PHENYLKETONURIA"
      },
      {
        "identifier": "OMIM:261600",
        "label": "PHENYLKETONURIA"
      }
    ],
    "id": {
      "identifier": "REACT:R-HSA-2160456",
      "label": "PHENYLKETONURIA"
    },
    "type": [
      "disease"
    ]
  }
}

{
  "DOID:9281": {
    "equivalent_identifiers": [
      {
        "identifier": "CUI:C0031485",
        "label": "PHENYLKETONURIA"
      },
      {
        "identifier": "LNC:LP56980-3",
        "label": "PHENYLKETONURIA"
      },
      {
        "identifier": "LNC:LA21169-0",
        "label": "PHENYLKETONURIA"
      },
      {
        "identifier": "MEDDRA:10034872",
        "label": "PHENYLKETONURIA"
      },
      {
        "identifier": "MEDCIN:32390",
        "label": "PHENYLKETONURIA"
      },
      {
        "identifier": "MEDLINEPLUS:1231",
        "label": "PHENYLKETONURIA"
      },
      {
        "identifier": "NCIT:C81315",
        "label": "PHENYLKETONURIA"
      },
      {
        "identifier": "NCI_NCI-GLOSS:CDR0000446806",
        "label": "PHENYLKETONURIA"
      },
      {
        "identifier": "NCI_NICHD:C81315",
        "label": "PHENYLKETONURIA"
      },
      {
        "identifier": "OMIM:261600",
        "label": "PHENYLKETONURIA"
      },
      {
        "identifier": "Orphanet:716",
        "label": "PHENYLKETONURIA"
      },
      {
        "identifier": "MONDO:0009861",
        "label": "PHENYLKETONURIA"
      },
      {
        "identifier": "DOID:9281",
        "label": "PHENYLKETONURIA"
      },
      {
        "identifier": "REACT:R-HSA-2160456",
        "label": "PHENYLKETONURIA"
      }
    ],
    "id": {
      "identifier": "REACT:R-HSA-2160456",
      "label": "PHENYLKETONURIA"
    },
    "type": [
      "disease"
    ]
  }
}
Elapsed time: 0.009018100000000029

**Comment by edeutsch** [comment]
Maybe a fun first test of Expand()ing with synonyms in KG1 would be this:

add_qnode(name=PHENYLKETONURIA, id=n00)
add_qnode(id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00)
#overlay(action=compute_ngd, virtual_edge_type=N1, source_qnode_id=n00, target_qnode_id=n01)
resultify(ignore_edge_direction=true)

Currently add_qnode() just picks one. and that's the graph you get back. What *should* the answer be if synonym checking is enabled? ala #698

**Comment by amykglen** [comment]
Nice - this works great for me in `expand`. Think we're good to close this issue now?

**Comment by edeutsch** [comment]
great, thanks! sure, I'll close. Although I'm always a little hesitant to close things before they make it to production. But this issue #709 is in production already, so I'll close. But #711 hasn't made it to master and production yet as far as I can see.

Interesting philosophical question: do we close issues when they are fixed and tested somewhere, perhaps in a branch somewhere? Or do we close issues when they are verified working in production and available to customers?
