### ISSUE TITLE
Trim or group extremely similar answers in ranked output?

### ISSUE THREAD

**Issue by jaredroach** [RTXteam/RTX#71]
Reasoner sometimes puts up a lot of very similar answers - maybe better to make several more distinct guesses (at least with my scoring system, which gives a lot of points for getting right answer somehwere).
Perhaps only report one of these? Or group them together as a single response??
That way, if the true answer is ranking below these chaff, then we can can credit for finding the true answer. As well as other intriguing answers.

e.g. for COP #2 TREPROSTINIL rx of Pulmonary arterial hypertension
these are all "the same":

(CHEMBL1237119,treprostinil) -[directly_interacts_with]- (Q13258,PTGDR) -[participates_in]- (R-HSA-445355,Smooth Muscle Contraction) -[expressed_in]- (UBERON:0000178,blood) -[affects]- (HP:0002092,Pulmonary arterial hypertension) -[has_phenotype]- (DOID:6432,pulmonary hypertension). Distance (smaller is better): 183.270420."
(CHEMBL1237119,treprostinil) -[directly_interacts_with]- (Q13258,PTGDR) -[participates_in]- (R-HSA-445355,Smooth Muscle Contraction) -[expressed_in]- (CL:0000738,leukocyte) -[affects]- (HP:0001882,Leukopenia) -[has_phenotype]- (DOID:6432,pulmonary hypertension). Distance (smaller is better): 197.665111."
(CHEMBL1237119,treprostinil) -[directly_interacts_with]- (Q13258,PTGDR) -[participates_in]- (R-HSA-445355,Smooth Muscle Contraction) -[expressed_in]- (UBERON:0000178,blood) -[affects]- (HP:0000822,Hypertension) -[has_phenotype]- (DOID:6432,pulmonary hypertension). Distance (smaller is better): 202.427667."
(CHEMBL1237119,treprostinil) -[directly_interacts_with]- (Q13258,PTGDR) -[participates_in]- (R-HSA-445355,Smooth Muscle Contraction) -[expressed_in]- (UBERON:0002046,thyroid gland) -[affects]- (HP:0000836,Hyperthyroidism) -[has_phenotype]- (DOID:6432,pulmonary hypertension). Distance (smaller is better): 205.730862."
(CHEMBL1237119,treprostinil) -[directly_interacts_with]- (Q13258,PTGDR) -[participates_in]- (R-HSA-445355,Smooth Muscle Contraction) -[expressed_in]- (UBERON:0000178,blood) -[affects]- (HP:0001409,Portal hypertension) -[has_phenotype]- (DOID:6432,pulmonary hypertension). Distance (smaller is better): 208.568332."
(CHEMBL1237119,treprostinil) -[directly_interacts_with]- (Q13258,PTGDR) -[participates_in]- (R-HSA-445355,Smooth Muscle Contraction) -[expressed_in]- (UBERON:0000178,blood) -[affects]- (HP:0002615,Hypotension) -[has_phenotype]- (DOID:6432,pulmonary hypertension). Distance (smaller is better): 213.242122."

**Comment by dkoslicki** [comment]
@jaredroach do you have a suggestion for what condition we group on? I.e. I'm operating at the path/subgraph level and could write a function that groups "similar" ones together if I have a definition of what "similar" means.

**Comment by jaredroach** [comment]
Obvious solution is to group using a path comparison metric. e.g., some sort of Levenshtein distance.
Perhaps it could be as simple as "if I can make path A equal path B by changing a single node (and the two edges going to it) of A, then they should be grouped."

**Comment by dkoslicki** [comment]
So confirming your definition: paths should be considered "the same" if they differ by only a single node. No condition on the node that differs?

**Comment by jaredroach** [comment]
Sounds like a simple and good definition to start with.

**Comment by dkoslicki** [comment]
Hmm... ok, but I'm concerned that with this definition, if two COP's differ in terms of the protein target, do we really want to consider them "the same"?

**Comment by jaredroach** [comment]
Sure. A simple definitions better for starters than a complex definition. I would think it would be excellent to combine the COX1 & COX2 pathways of naproxen. Also, this would help with the promiscuity of "false" targets created by many edges that seem to be primarily justified by co-expression array analyses. If the pathways "lumps" all of these together as a single node in post-processing, that is almost exactly what a human user would always want. Particularly if all the pathways re-unite at the next node.

**Comment by dkoslicki** [comment]
Ok, fair enough. I just thought of another issue though: one-node-different is not transitive, so will cause issues with cases such as:
p1 = A -> B -> C
p2 = A -> X -> C
p3 = A -> X -> Y
so while p1 "=" p2 and p2 "=" p3 under the operating definition of "=", we do not have p1 "=" p3. So which of these paths would we return to the user? Seems clear to return p1 and p3 in this case, but if we throw in a path like:
p4 = W -> X -> Y
it becomes less clear which ones to return (and seems like an arbitrary choice, something that I prefer to eschew).

**Comment by jaredroach** [comment]
I recommend:
1. Require that the start and end nodes be the same in order to merge
2. Merging all the others (even if that means there are two paths in the same cluster with a mutual distance greater than 1). The result would look something like Team Gamma's answer in Noel's email from this morning. This might be an excellent way to deal with the "high path branching" issue associated with TF cascades that often appear late in the COPs. As long as all the branches reconverge (as constrained by #1 above), it produces the kind of answer almost any human questioner would want.
3. Not necessarily merge all the answers (if the output contains thousands of answers), but rather just enough to populate a "top 10" output list like you currently have provided to me. But it might be fast and easy to merge all, so maybe this recommendation is superfluous.
4. Start with the top scoring answer and merge greedily, working down the scores. Must be within a certain delta score of the best scoring answer in a cluster in order to get merged. Otherwise, start a new cluster (or terminate algorithm, or skip that path – removing it as an answer – and move to next path). This criteria #4 might be equivalent to criterion #3, depending on implementation.

**Comment by dkoslicki** [comment]
@edeutsch How easy would it be to implement this on the UI side of things?

**Comment by edeutsch** [comment]
In principle it doesn't matter a whole lot where trimming and grouping takes place. RTXQuery could call out to some trimming and grouping code immediately after receiving the result. BUT, I think I would push back against this and suggest that it would be better for the reasoner to take care of this. I can imagine that this trimming/grouping code might eventually take some parameters that might be query type dependent. And it seems that it would be better for the reasoner to be in control.

In general, putting such "changing of the data" into the UI is probably a violation of principles of separation of data layer and presentation layer. In general I think I would vote against the UI changing the output of the reasoner data in any substantial way. Although we're straying a bit from these principles, I think we should keep in mind that someday we might like rip out the reasoner out of RTX and have it run with a different UI or UI-less or part of the larger system, and then such refining/trimming of reasoner output should be part of the reasoner and not the UI.

So the answer to your question is: this is not easy for sure, but certainly doable. It is no easier in the UI than in the reasoner components. both have access to the same data structure, it's just a matter to writing code that will alter it according to the rules we set out. But I suggest that it doesn't belong in the UI.

**Comment by edeutsch** [comment]
oops, sorry, just had to restart my browser and this happened.

**Comment by dkoslicki** [comment]
Thinking about this a bit more made me recall the following: when we met at ISB in February, I floated the idea of having the UI show the relevant sub-graph of the KG for a given question, *along* with individual paths. So for a COP question "How does naproxen treat osteoarthritis?" We'd get something like the following:
![cop example](https://user-images.githubusercontent.com/6362936/39501686-241113dc-4d71-11e8-95e4-dae1a7b2adb1.png)
Grouping similar paths seems like moving in this direction.

The reason I'm hesitant with grouping similar paths outright is that this would require an entire re-think of how we return plain text answers. For example, we'd need a way to summarize multiple nodes: "naproxen targets 'some proteins' (COX1, COX2, and PPARG) which are involved with 'some pathways' etc...." 
Of course, summarizing some nodes would be easier than summarizing other nodes, but making the decision about how to summarize groups of nodes in plain text is non-trivial to me.

**Comment by jaredroach** [comment]
I really like that kind of graphical output. Indeed, it is one of the outputs that NCATS folks are encouraging.

**Comment by dkoslicki** [comment]
Yeah, I could get this implemented quite easily. I also like the idea of leveraging the ``result_type`` since not every query type will return this kind of info (eg "what is naproxen?").
@edeutsch What's the difference between "type summary graph" and "neighborhood graph"? As soon as we settle on a naming convention, I can start working on this.

**Comment by edeutsch** [comment]
The "neighborhood graph" was my name for what you depicted above and call "relevant sub-graph". I'm not heavily promoting my name, it just sprang to my mind.

The "type summary graph" is that coalesced graph you were talking about weeks ago where I think you essentially boil down the neighborhood graph by keep just one instance of each node type and each edge type (named by the type). To show what kind of players are involved. I forget what you were calling it at the time and I just made up a name. Is that clear enough? I can searching my email if this doesn't clarify for you what it is.. it was your idea, I can't recall the details though.

**Comment by edeutsch** [comment]
Yes, what I called the "type summary graph" is what I now recall you called a metagraph in the past. maybe this apoc.meta.graph.

I'm actually not implying that you do anything different than what you're already discussed and suggested. I just could not remember that you were calling these things metagraph and subgraph, partly because those terms don't conjure up a mental image for me. Whereas "type summary graph" and "neighborhood graph" conjure up a mental image for me. I'm not suggesting anything different.

**Comment by dkoslicki** [comment]
@edeutsch I don't see ``result_type`` in any of the following:
```
from swagger_server.models.response import Response
from swagger_server.models.result import Result
from swagger_server.models.result_graph import ResultGraph
```
Can you point me to where ``result_type`` lives?

**Comment by dkoslicki** [comment]
@edeutsch I see now that ``result_type`` would be a new/added flag. Do you think you could update the models to include this (and potentially in the API "standardization format" as well)?

**Comment by edeutsch** [comment]
yes, this is a totally new idea for consideration yesterday, so not implemented yet. Sounds like you're enthused about it, so I will go ahead and implement it. I will float the idea for the API standard, although it could be a custom field for us, too.

**Comment by dkoslicki** [comment]
Sounds good! I'll wait to hear from you when it's implemented in the API spec/model.

**Comment by dkoslicki** [comment]
Maybe the more fluffy terms as they're a bit more descriptive. And just to clarify, we're imagining that "individual query answer" is something like a path, correct?

**Comment by edeutsch** [comment]
correct.
okay, I will go with the fluffy terms.

**Comment by edeutsch** [comment]
So, going forward, if a reasoner does not provide a result_type, then a default value of "individual query answer" will be assigned. Please provide result_type=neighborhood graph or result_type=type summary graph when appropriate.

@isbluis, please consider how you will render these different types.

**Comment by dkoslicki** [comment]
@edeutsch Has the output format yaml been updated to allow for these new ``result_type``'s?

**Comment by edeutsch** [comment]
yes, absolutely. just attribute result_type:
https://github.com/RTXteam/RTX/blob/master/code/UI/OpenAPI/python-flask-server/swagger_server/models/result.py

**Comment by edeutsch** [comment]
If it seems desirable, you could leave that field missing if it is just a regular answer and I will fill it in for you. You only specify it if it is 'neighborhood graph' or 'type summary graph' ?

**Comment by dkoslicki** [comment]
Close as this issue is superseded by #100
