### ISSUE TITLE
Figuring out which KP's know about what

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#710]
Due to [a discussion](https://ncatstranslator.slack.com/archives/C011ZDHCQBC/p1587057815008600) on slack, Team "Exploring Agent, Service Provider" has parsed all the KP APIs registered at Smart API with the `translator` tag and nicely presented the results:
https://smart-api.info/registry/translator/meta-kg

Each item under `associations` indicates one type of knowledge edge (subject_type-predicate-object_name) offered from a KP API.

We could/should be able to parse this to at least be able to identify:
1. Which KP's know about which bioentities
2. Which KP's have which kinds of associations

Doesn't fully give us the functionality of all the KP's, but will at least be able for us to replicate a meta-KG of all the SmartAPI's (as pictorially represented [here](https://docs.google.com/presentation/d/1YjeHcr2JRrl6pzrM5Ygf43La8GDWxGuCvk-F3VKV9Gc/edit#slide=id.g7153a08b33_2_31)).

**Comment by dkoslicki** [comment]
One possible idea is to use this to allow @amykglen's `expand` to access other KP as well. Though I have no idea how technically difficult this is; I feel writing the API interfacing code will either be trivial (if they're all in the same format, which I thought was the point of being a "SmartAPI") or very difficult (if each needs a bespoke script to interact with the API).

**Comment by dkoslicki** [comment]
Might also be a non-issue for us to need to address, since I get the vague impression that Andrew Su is positioning their tool to be able to handle this (i.e. we can (eventually?) hit up their single API to get access to all these API's that they've already interfaced with.

**Comment by dkoslicki** [comment]
A few more update on this thread:
https://ncatstranslator.slack.com/archives/C011ZDHCQBC/p1587180857031300?thread_ts=1587057815.008600&channel=C011ZDHCQBC&message_ts=1587180857.031300

https://ncatstranslator.slack.com/archives/C011ZDHCQBC/p1587182831032500?thread_ts=1587057815.008600&channel=C011ZDHCQBC&message_ts=1587182831.032500

**Comment by saramsey** [comment]
Doesn't the Biothings Explorer mostly do this for us?  Can we close this issue in light of the decision (in the April 22 AHM) to try using BTE?

**Comment by dkoslicki** [comment]
Closing in light of #722
