### ISSUE TITLE
resultify ignore_edge_direction default should true?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#712]
All the DSL examples I've seen have this:
resultify(ignore_edge_direction=true)

For most examples I've tried leaving out that resultify option (or setting to false) leads to an error. e.g.:
add_qnode(name=acetaminophen, id=n00)
add_qnode(type=protein, id=n01)
add_qedge(source_id=n00, target_id=n01, type=physically_interacts_with, id=e00)
expand(edge_id=e00)
resultify()

It seems like ignore_edge_direction=true always gives a reasonable result. The default ignore_edge_direction=false rarely gives a result. Can the default be true so that all DSL scripts don't need to set this parameter?

**Comment by saramsey** [comment]
I think the default is `true`?  See L360 in ARAX_resultify.py.

<img width="886" alt="Screen Shot 2020-04-22 at 3 16 51 PM" src="https://user-images.githubusercontent.com/5562107/80039284-50057e00-84ac-11ea-8003-51b9344c7a51.png">
