### ISSUE TITLE
Should we be less fussy about edge directions?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#714]
Consider the following query:
add_qnode(name=mRNA editing, id=n00)
add_qnode(type=protein, id=n01)
add_qedge(source_id=n00, target_id=n01, type=participates_in, id=e00)
expand(edge_id=e00)
resultify(ignore_edge_direction=true)

Seems reasonable. If you execute it, there is not result (see also #713)

The reason it fails is because the edge direction is wrong. Is it beneficial to be sticklers for edge direction here? Or should ARAX think internally "okay, you asked which proteins does mRNA editing participate in, but really you meant which proteins participate in mRNA editing, and I can can answer that"

IF we want to be sticklers for the direction, can the error be more informative than:
the node binding list does not cover all nodes in the query graph

**Comment by amykglen** [comment]
Expand's default behavior is actually already to **ignore** edge directions (for both KG1 and KG2 now), although these changes haven't made it to `master` yet. (see also #627)

I was thinking I'd go ahead and add an optional `enforce_edge_directions` parameter, although it seems like this is something that ultimately maybe should be specified at the `QueryEdge` level, rather than `expand()`. Maybe this is something we would want to bring up with the ReasonerStdAPI, as [David noted](https://github.com/RTXteam/RTX/issues/627#issuecomment-611842963) in #627?

**Comment by edeutsch** [comment]
ah great, thanks, I would encourage that these things get into master.

I'm thinking that maybe such an option should be at the query level rather than the Edge level. Seems like a user preference whether the ARA should be strict about edge directions or be flexible. Controlling that at the Edge level seems like a needless level of granularity.

**Comment by amykglen** [comment]
Ok - I added an optional `enforce_directionality` parameter to `expand` (default is `false`). Setting it to `true` means directionality is enforced for all edges in the query graph. If we decide later on that that belongs at the edge level, it's easy to change from my end. :)

**Comment by amykglen** [comment]
Confirmed this is working on beta - that, is the original DSL @edeutsch posted:
```
add_qnode(name=mRNA editing, id=n00)
add_qnode(type=protein, id=n01)
add_qedge(source_id=n00, target_id=n01, type=participates_in, id=e00)
expand(edge_id=e00)
resultify(ignore_edge_direction=true)
```
does produce results now (since `expand` now ignores edge directions by default). And then if you specify to enforce edge direction:
```
add_qnode(name=mRNA editing, id=n00)
add_qnode(type=protein, id=n01)
add_qedge(source_id=n00, target_id=n01, type=participates_in, id=e00)
expand(edge_id=e00, enforce_directionality=true)
resultify(ignore_edge_direction=true)
```
You get a "No paths were found in KG1 satisfying this query graph" error.
