### ISSUE TITLE
Can Resultify() compute confidences/relevance scores?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#716]
All our results[] from DSL scripts have no result confidences, but this is one place where ARAX could shine. I propose that resultify() should compute a confidence or relevance score for each result. There is already a place in the schema to put it (next to essence) and the UI already can display it. Resultify just needs to compute it and store it.  I propose this crude strawman to produce something reasonable:

- Start with all confidences of 1.0
- Take all the confidences of edges along each result, and multiply times current confidence
- If some confidence of a given QG.edge_id (e.g. e01) are null but some have values, maybe just assign all nulls to be half of lowest value
- If NGD values are provided, multiply current confidence times some black magic numerology transformation like:
( 1 - ( NGD - 0.3) * 0.6 ) < 1.0 > 0.01
- If it feels too icky to call this a confidence, we can label it as a score of 0 to 1 with 1 is best

See page 5 in https://docs.google.com/document/d/18bbeTlkH-sdeDqqyl8ZFzBHyZSkg8awuUec1H_kff8c/edit# for more background and detail.

**Comment by dkoslicki** [comment]
I assume black magic numerology will be required (as we currently have a mix of NGD scores, ML drug-treats-disease probabilities, drug-target binding probabilities, etc.). 

**Unless** the QG contains hints about what scoring/ranking is desired, I imagine we might need to utilize something like Connection Hypothesis Provider (PI: Eugene (Gene) Santos) to provide a global score for an arbitrary QG.

**Comment by edeutsch** [comment]
Although perhaps not ideal, I think black magic would be better than nothing! much better!

**Comment by dkoslicki** [comment]
The problem I've encountered is:

- some edge attributes have bounded range
- some edge attributes have unbounded range
- some edge attributes bigger/lower is better

any combination of these into a single numerical score will be:

- arbitrary
- completely hard coded as to weightings of attributes
- very sensitive to the weightings

Hence why (for better or for worse) I've taken the approach of not touching it until a "good idea" emerges :P would arbitrary, hard coded, sensitive, meaningless scores really be much better than nothing? Just thinking out loud...

**Comment by edeutsch** [comment]
At the risk of sounding like a fool, I think yes! At the moment we often return dozens of results and there is zero indication on which are better than others, even though there is a huge range in NGDs and other scores. Clearly some are better than others. I think two hours spent on implementing a crude combination of these into a crude combined score would lead to a much nicer user experience. And then we can argue about better ways to do it. And have a reference to compare better ways against.

**Comment by edeutsch** [comment]
I have taken a first wild swing at implementing this. I put the code in ARAX_messenger. Which is not a final place, but it seemed like an expedient place for tinkering. I'm thinking I should move it to a separate module so it can expand and become more complex in its own space.

**Comment by amykglen** [comment]
Noticed that this query seems to be hanging during score computation? (https://arax.rtx.ai/beta/?m=2185):
```
add_qnode(id=n00,curie=[UniProtKB:Q96RI1,UniProtKB:O15438,UniProtKB:Q92887], is_set=true)
add_qnode(type=biological_process, id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00, kp=ARAX/KG2)
resultify()
```
These are the last few log messages:
```
2020-05-28 19:16:00.877925 INFO:  After Expand, Message.KnowledgeGraph has 194 nodes and 263 edges
2020-05-28 19:16:00.877973 INFO:  Processing action 'resultify' with parameters {'': 'true'}
2020-05-28 19:16:00.941884 DEBUG:  Applying Resultifier to Message with parameters {'': 'true'}
2020-05-28 19:16:00.941899 INFO:  Running experimental reranker on results
2020-05-28 19:16:00.943118 DEBUG:  Summary of available edge metrics: {}
2020-05-28 19:16:00.943126 DEBUG:  Metrics for result 0 Complication:
```

**Comment by edeutsch** [comment]
ah, I think I see the problem. will fix shortly.

**Comment by edeutsch** [comment]
fixed, I think? Let me know if not.

**Comment by finnagin** [comment]
Closing since this looks to be resolved as of the last comment
