### ISSUE TITLE
Might be useful to have an NGD coverage histogram for node pairs

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#719]
Given all pairs of node types, what's the probability that if I ask for a NGD, I'll get one? QueryGraphInterpreter would want to know if those probabilities have a substantial range (including several pairs that yield a 0). Not crucial yet.

**Comment by finnagin** [comment]
I believe this was done during the work on #729 so I'm closing this issue. Feel free to reopen if still relevant.
