### ISSUE TITLE
Restricted subset of diseases for Q1

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#72]
Currently, we restrict the input diseases to Q1 to be in the [list provided by NCATS](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/Q1Solution.py#L57-L77).

@saramsey @edeutsch Do we want to remove this restriction and allow any disease as input to Q1?

**Comment by edeutsch** [comment]
I think we definitely want to do this, but the question is when. It is certainly fine for me to do this as soon as is feasible, But I think Steve should be the deciding factor here.

**Comment by dkoslicki** [comment]
Ok, it would be straightforward to do in my code. @saramsey let me know if you have any objections to this.

**Comment by saramsey** [comment]
It's OK with me to remove this constraint. But from a UX standpoint you will want to bear in mind that our BuildMasterKG.py script currently doesn't seed all diseases.  If you want me to do seed a much bigger list of diseases, put an issue in GitHub and I'll try to do it when i can.  It's probably an afternoon's work.

**Comment by dkoslicki** [comment]
Ok, I'll change the code tomorrow to remove this constraint and will open an issue re: seeding more disease nodes.
