### ISSUE TITLE
How close?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#721]
Philosophical question: do we close issues when they are fixed and tested somewhere, perhaps in a branch somewhere? Or do we close issues when they are verified working in production (or /beta) and available to customers?

**Comment by edeutsch** [comment]
And maybe the corollary is: are we still being best served by branches? I view branches as being useful when there's parallel development that needs testing and access or possibly checking in possibly broken code without hurting production functionality. But at this point, it seems to me that we're making smaller fixes that are just fixing issues or otherwise improving ARAX. And I don't think we're concerned too much about breaking this. I advocate for "move fast and break things" at this point. I advocate we all play nicely in master. I'll roll things out often. We can all see the latest fixes and code in production and verify that all fixes are working. Perhaps on the eve of the hackathon maybe we want to move back to a strategy where production only gets bug fixes and /beta gets new features. But really, as long as we're all ready to pounce on bugs in production, I don't see the value in getting the fixes into a branch and letting them sit there.

FWIW, it is a little awkward to switch branches on the production server, so I'd prefer to not switch branches very often there to test little things.

**Comment by saramsey** [comment]
I agree. 

Perhaps this might be a useful guideline? 

(1) small code changes that are not expected to leave the system in a broken state, are fine (and encouraged) to do in the master branch.
(2) code changes that are expected to leave the system in a broken state, should be done in some other branch.

As for closing out issues: upon reflection, I wonder if it is best to leave issues open until they are tested (LOL, I recognize that I have not previously been particularly good about this with my KG2 development).

**Comment by edeutsch** [comment]
I had mostly in mind "customer facing" code. If it's not code that's called by the API, then master or branch doesn't matter, to me at least.

**Comment by saramsey** [comment]
> If it's not code that's called by the API, then master or branch doesn't matter, to me at least.

Fair enough. But for KG2, if a code change will break the KG2 build (which could conceivably happen if there is a really significant refactoring going on with the refactoring work shared between people), it should go in a branch.

**Comment by amykglen** [comment]
I wonder if it might be helpful to have a label called `need to test in production` (or similar), to help us keep track of which issues are complete, but still need to be confirmed working for users?

**Comment by edeutsch** [comment]
sure, seems good to me. Or you can just post that it's ready and been pushed to master and ready for rollout, and I'll pull and roll it out and you can finish testing in the production environment and then close.

**Comment by amykglen** [comment]
So does testing fixes on beta count for closing? :)

**Comment by edeutsch** [comment]
I would say yes, because the fixes are publicly and easily available to all in the /beta endpoint, even if we choose not to fully roll out into production because of some short-term stability requirement in production.
