### ISSUE TITLE
Gather information about which KP’s provide “extra information”

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#723]
While BTE (see #722) provides KS’s that provide nodes/edges, some KP’s provide “other information”. I.e. not bioentities and relationships, but rather information about nodes/edges (or groups thereof) like COHD, BIG GIM, BIG CLAM, etc.

The point of this issue is for us to list/gather information about which KP’s provide information that we can leverage to enhance our reasoning capabilities.

All relay attendees: if you become aware of a KP that provides some “interesting information” that we could leverage for ARAX, please comment on this issue.

**Comment by edeutsch** [comment]
I confess it is a lot of work, but I would appreciate if we could organize the universe of available relationships in a simple Google Sheet format of relationships. I started one here:
https://docs.google.com/spreadsheets/d/1TwZIK3K67YgZp2SnVRNZbukpCBGCcAGcOrUX--m0lJk/edit#gid=0
I feel that this structure would provide us a useful way of seeing at a glance and organizing "how can we get from here to there". I feel I don't have a good grasp of what relationships and sources we have available and I think this could help. Maybe there's some way to autogenerate most of this for KG1, KG2, and BTE, and hand-edit the rest? Although I think this is important information that should be carefully thought about by a person, too, not just autogenerated. Or maybe we have something like this already? I don't think we need both forward and reverse, just one direction of each pair seems sufficient.

What do you think? Maybe we can discuss tomorrow.

**Comment by dkoslicki** [comment]
@edeutsch The intent of this issue was to look for KP's that provide "extra information" ala COHD, not so what nodes/edges are provided by which KP. Since, as you pointed out, much of the node/edge-provided-by-who can be auto-generated, while this "extra information" is something that will need to be 100% via humans (us) talking to other KP teams to understand what they provide.

That said, your Google doc idea for nodes/edges would still be nice to have (different issue perhaps?).

**Comment by edeutsch** [comment]
okay, sorry to barge in on this issue. I will open a new issue for my idea, thanks.

**Comment by dkoslicki** [comment]
Talks from Monday:

- Clinical Data Services Provider
    - COHD: wants to incorporate temporal information in their API. _we may need to extend our `Query_COHD.py`_

- Molecular Data Provider
    - MolePro: genes and compounds: annotation, similarity services, enrichment aggregators

- Genetics Provider (new team)
    - provides genetic information: ID genes near a genetic association, ID pathways enriched for genetic association, etc.

- Ranking agent
    - Question augmentation: reformulating questions that adapt them to what the KP’s actually have information about. SUPER COOL! Gives similar/alternate questions/QG’s you could ask
    - Strider: similar to BTE: reaches out to KP’s and aggregates results

- Exposures provider
    - ICEES accessible via OpenAPI and returns ReasonerStd API answers
    - Phenotypes, environmental exposures (PM2.5)

- Text mining provider
    - Maybe a full text replacement for SemMedDB? (was answering questions after the expander talk and wasn't able to fully listen to this talk)

- Connection Hypothesis Provider
    - Bayesian knowledge bases, Knowledge fusion, Probabilistic reasoning?
    - is this a reasoner or a knowledge provider?

**Comment by dkoslicki** [comment]
__importantly__!!! COHD has changed their endpoint: http://tr-kp-clinical.ncats.io/api

**Comment by dkoslicki** [comment]
> **importantly**!!! COHD has changed their endpoint: http://tr-kp-clinical.ncats.io/api

Update from Casey Ta: 
Hi David, just FYI, I've updated the [cohd.io](http://cohd.io/) domain to point to the new NCATS-based resources, so you don't need to access via tr-kp-clinical.ncats.io (but both should work). Also, [this notebook](https://colab.research.google.com/drive/1KSx4gb5xEzq8bGktGUnMuQ8VECemrbfE) has some plots that might help people understand the new temporal data. The new stuff is in the section "Temporal Clinical Data" towards the bottom.

**Comment by saramsey** [comment]
See nice update on Text Mining provider provided by @finnagin #834

**Comment by finnagin** [comment]
Sounds like work is still ongoing for an api from the text mining provider as well as their full kg. However they have a smaller sample KG v0.1 in TSV format located [here.](https://github.com/NCATSTranslator/Text-Mining-Provider-Roadmap/blob/9b641bad6841ca4f6615adfa5457afbccc583176/sample-kg/README.md)

**Comment by dkoslicki** [comment]
@finnagin The cooccurrence info could be quite helpful for our ranking in particular. From the architecture call today, it appears it's still ongoing work to get this Reasoner Std API format compliant, but we may be able to use the TSV's for local querying in the mean time (anything to help our ranking a la #941)

**Comment by amykglen** [comment]
a nice summary of what the Text Mining provider offers for NGD (and otherwise):

![Screen Shot 2020-09-30 at 12 01 43 PM](https://user-images.githubusercontent.com/49423686/94731539-cb037800-0319-11eb-9611-9d01128c8576.png)

(slide from a 9/30/20 presentation by Bill Baumgartner at the KGX working group meeting)

**Comment by dkoslicki** [comment]
This issue served its purpose; closing
