### ISSUE TITLE
Sync all branches (pre-April relay meeting)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#726]
- [x] merge master into expander (resolve conflicts, commit, push)
- [x] merge expander into master (commit, push)
- [x] merge master into demo (resolve conflicts, commit, push)
- [x] merge demo into master (commit, push)
- [x] repeat for filter
- [x] repeat for overlay

(Steps borrowed from #697)

**Comment by amykglen** [comment]
Ok, everything is merged and in `master` (no conflicts), and seems to be running smoothly in tests - it's ready to roll out to beta whenever, @edeutsch.

One note: The server will need networkx 2.3 (rather than 2.4) for BTE queries to work. (`requirements.txt` has been updated to specify `networkx==2.3`)

**Comment by dkoslicki** [comment]
Great! Should we close this issue now, or only after the UI BTE issue you raised earlier today (4/27)?

**Comment by edeutsch** [comment]
fine to close this and leave #722 open.
