### ISSUE TITLE
Resultify throwing error for query where expand ignores edge direction

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#727]
When I run this DSL on beta https://arax.rtx.ai/beta/?m=1763:
```
add_qnode(name=CHEMBL.COMPOUND:CHEMBL1276308, id=n00)
add_qnode(type=protein, id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00)
resultify()
```
Resultify throws this error:
```
The two nodes for KG edge UniProtKB:P10635--physically_interacts_with--CHEMBL.COMPOUND:CHEMBL1276308, UniProtKB:P10635 and CHEMBL.COMPOUND:CHEMBL1276308, have no corresponding edge in the QG
```

I am guessing this is because:

- `expand` now ignores edge directions by default, so one of the answers it found was a triple that goes `(UniProtKB:P10635)-[physically_interacts_with]->(CHEMBL.COMPOUND:CHEMBL1276308)` - which is technically the opposite direction of the edge in the query graph (but is allowed since we want `expand` to ignore edge directions)
- `resultify` is then confused because it doesn't think an edge that goes `(n01)-->(n00)` is valid

**Comment by saramsey** [comment]
@amykglen do you want me to fix this in the demo or master branch?

**Comment by amykglen** [comment]
Uh, I would say master I guess!

**Comment by saramsey** [comment]
I'm on it

**Comment by saramsey** [comment]
OK @amykglen can you try the latest version?  101621c

**Comment by amykglen** [comment]
Nice - working for me now locally!

**Comment by amykglen** [comment]
Should we wait to close this until it's rolled out to production (or beta) and verified?
