### ISSUE TITLE
Since the hackathon is over, shall we rollout everywhere and often?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#732]
For the hackathon we held back on rolling out the latest master to the production web site to ensure that the demo didn't break and in general for stability.

Now that the hackathon is over, I propose we all stay close to master and I roll master out to production, beta, test, et al. frequently.

Agreed? Or alternative positions?

thanks,
Eric

**Comment by edeutsch** [comment]
I've rolled out some new real-time progress code that Luis and I put together to everywhere but production. Still waiting for some signal from others that it is okay to roll out master to production?

**Comment by saramsey** [comment]
IDK, I've added this issue to Wednesday's agenda.

**Comment by edeutsch** [comment]
Hi everyone, I have rolled out the latest code in `master` to production and beta and test. So production is no longer behind. All the latest goodies are available. Try it yourself. Go to:

https://arax.rtx.ai/

and paste in some DSL:

add_qnode(name=yourFavoriteDrugName, id=n0)
add_qnode(type=protein, id=n1)
add_qedge(source_id=n0, target_id=n1, id=e0)
expand(edge_id=e0)
overlay(action=compute_ngd, virtual_edge_type=N1, source_qnode_id=n0, target_qnode_id=n1)
resultify(ignore_edge_direction=true)

(replace yourFavoriteDrugName with your favorite drug name, click POST, and watch it crawl along!
