### ISSUE TITLE
Should cryptography package be in requirements.txt?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#733]
I'm getting this error when I run `ARAX_resultify.py`:
```
RuntimeError: cryptography is required for sha256_password or caching_sha2_password
```
and I'm wondering if we should include the `cryptography` python module in the top-level RTX `reuquirements.txt`?

**Comment by saramsey** [comment]
I should have added, I think this is coming about because ARAX_resultify.py is importing ARAX_query.py, and thus pulling in pymysql or some such via RTXFeedback.py.

**Comment by saramsey** [comment]
tagging @edeutsch to get a second opinion on this

**Comment by edeutsch** [comment]
I don't really know. On arax.rtx.ai, I see:
$ pip3 list | grep cryp
pycrypto               2.6.1       
simple-crypt           4.1.7       

and everything seems to run fine.
I don't know if those are even required, but that's the state of things.

Does that help?

**Comment by edeutsch** [comment]
Amusingly on my home Windows machine, I see this:

$ pip3 list | grep cryp
cryptography           2.8

So, maybe one of the above is required but maybe a couple options are possible? I don't know.

**Comment by edeutsch** [comment]
closing ancient history.
