### ISSUE TITLE
Need to add default functionality to arax filter

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#738]
Going to try 2 implementing different options:

1. Top (or bottom depending on virtual edge type) n values returned.
2. All values at least 1 std away from mean. (again up or down depending on virtual edge type)

**Comment by finnagin** [comment]
@dkoslicki I've got both the standard deviation and ton n functionality implemented on the . I have 'ngd', 'chi_square', 'jaccard_index', 'fisher_exact', 'observed_expected_ratio' in there right now though I need to double check the direction with you.

currently I have:

ngd - lower is better
chi-squared - lower is better
jaccard - higher is better
fisher - higher is better
observed expected ration - higher is better

Is that correct? Also, am I missing any attributes that we use?

Lastly, I have it set that if it sees an attribute that is not listed it defaults to higher is better.

**Comment by dkoslicki** [comment]
@finnagin Great! I assume the DSL documentation will be updated to reflect these changes as well once merged to master?
As for the directions:

>ngd - lower is better
chi-squared - lower is better
jaccard - higher is better
fisher - higher is better
observed expected ration - higher is better

All correct except for the fisher: lower is better (looking for small p-values iirc). But coordinate with @chunyuma to make sure that his code in #623 is returning p-values and not odds-ratios or something like that.

**Comment by finnagin** [comment]
@dkoslicki Yes, I'll update the documentation when I merge to master after double checking with @chunyuma about the fisher exact code. Am I missing any types of virtual edges that we are currently using?

**Comment by dkoslicki** [comment]
>Am I missing any types of virtual edges that we are currently using

None that I can think of off the top of my head!

**Comment by finnagin** [comment]
Note to self: This is implemented but after talking with David needs to be updated to allow specifying the number of standard deviations and the name needs to be changes to something better. Maybe "remove_edge_by_stats"?
