### ISSUE TITLE
Add a filter and/or expand option to only include specific sources

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#739]
Instead of removing a specified source remove all results except a list of sources.

**Comment by finnagin** [comment]
Maybe also add expand functionality to do this in the expand step rather than pulling in everything first and then filtering later.

**Comment by saramsey** [comment]
finn thinks he can find bandwidth to work on this late this week or early next week

**Comment by finnagin** [comment]
Removing myself.

**Comment by finnagin** [comment]
@saramsey is this still relevant?

**Comment by amykglen** [comment]
closing since this has been subsumed by #1518
