### ISSUE TITLE
CUI:C0004572 has no corresponding edge in the QG

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#740]
The following apparently simply query leads to an error. It appears that expand() is working okay but resultify() is not able to create results. But it's possible the original problem is in expand(). @amykglen would you try to figure this one out? Maybe this is due to the synonym_handling?

https://arax.rtx.ai/

add_qnode(name=babesia, id=n00)
add_qnode(id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00, kp=ARAX/KG2)
resultify()

ERROR is from resultify:
The two nodes for KG edge SNOMEDCT:35029001--close_match--CUI:C0004572, SNOMEDCT:35029001 and CUI:C0004572, have no corresponding edge in the QG

**Comment by saramsey** [comment]
I am seeing this issue as well. Now working on isolating the problem.

**Comment by saramsey** [comment]
Here is the QG that resultify is seeing:
```
{'edges': [{'id': 'e00',
            'negated': None,
            'relation': None,
            'source_id': 'n00',
            'target_id': 'n01',
            'type': None}],
 'nodes': [{'curie': 'CUI:C0004572',
            'id': 'n00',
            'is_set': None,
            'type': 'organism_taxon'},
           {'curie': None, 'id': 'n01', 'is_set': None, 'type': None}]}
```

**Comment by saramsey** [comment]
I think this is resultify issue.

**Comment by saramsey** [comment]
fix pushed; @edeutsch can you check this new fix on your end?

**Comment by edeutsch** [comment]
Yes, that seems to have fixed it, thanks!

I see some self edges now, which I suspect was part of the problem. At some point, we should have a discussion about the self edges and how we want to encode this..

**Comment by saramsey** [comment]
OK. Yes, perhaps there could be an option for `resultify` that prevents KG edges that do not map to any QG edges from being included in any result graph.
