### ISSUE TITLE
bare and sticky edges

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#741]
@isbluis For this result:

https://arax.rtx.ai/devED/?m=2041

If you open any result and click on an edge, two things seem odd:

1) there is no metadata displayed for the edge. I think these edges are actually quite metadata rich. with publications and lots of stuff

2) Clicking on an edge make is stick to the cursor! this doesn't usually happen.

This does not happen with something like this:

https://arax.rtx.ai/devED/?m=2043

so something is different/problematic? about the former result that is having a strange effect on the display. Can you figure out what's up?

thanks!

**Comment by isbluis** [comment]
Hi Eric,

This is due to an unexpected change in the composition of the edge attributes.  For provided_by, I heretofore have expected a simple string, but somehow it has changed to an array?  Or perhaps the type is optional??
```
        "evidence_type": null,
        "id": "CUI:C0004572--subclass_of--CUI:C0597305",
        "is_defined_by": "ARAX/KG2",
        "negated": false,
        **"provided_by": [
          "https://skr3.nlm.nih.gov/SemMedDB"
        ],**
        "publications": [
          "PMID:29227211"
        ],
```

I can adjust; just let me know if this is somehow an API error.

Thanks!

**Comment by edeutsch** [comment]
I can now be a string or a list. See #706 and #736

**Comment by isbluis** [comment]
Committed fix into master; also added links to PubMed if pub =~ /^PMID:/
