### ISSUE TITLE
self edges? X is a close match of X?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#742]
This query result:

https://arax.rtx.ai/?m=2041

has some odd self-edges. Is this just the original data source saying this is a close match to itself? Or something more going on here?

  "knowledge_graph": {
    "edges": [
      {
        "confidence": null,
        "defined_datetime": null,
        "edge_attributes": [
          {
            "name": "relation_curie",
            "type": null,
            "url": null,
            "value": "oboFormat:xref"
          },
          {
            "name": "simplified_relation_curie",
            "type": null,
            "url": null,
            "value": "skos:closeMatch"
          },
          {
            "name": "simplified_relation",
            "type": null,
            "url": null,
            "value": "https://www.w3.org/TR/skos-reference/closeMatch"
          },
          {
            "name": "edge_label",
            "type": null,
            "url": null,
            "value": "xref"
          }
        ],
        "evidence_type": null,
        "id": "CUI:C0004572--close_match--CUI:C0004572",
        "is_defined_by": "ARAX/KG2",
        "negated": false,
        "provided_by": [
          "https://identifiers.org/umls/CHV"
        ],
        "publications": [],
        "qedge_id": "e00",
        "qualifiers": null,
        "relation": "http://purl.org/obo/owl/oboFormat#oboFormat_xref",
        "source_id": "CUI:C0004572",
        "target_id": "CUI:C0004572",
        "type": "close_match",
        "weight": null
      },

**Comment by saramsey** [comment]
So the `provided_by` and `subclass_of` edges seem to come from SemMedDB:

<img width="785" alt="Screen Shot 2020-05-15 at 1 29 28 PM" src="https://user-images.githubusercontent.com/5562107/82093552-34a72080-96b0-11ea-9614-902c3b0e77b7.png">

**Comment by saramsey** [comment]
As for the `close_match` predicate, I will have to dig deeper.

**Comment by edeutsch** [comment]
"interacts_with" seems fine. Some things interact with others of their kind.
"subclass_of" seems weird. How could anything be a subclass of itself?
And "close_match" of itself is also weird and what I first noticed.
The GUI has indeed shows all three of these. I only pasted in the first one.

Perhaps a useful question:
- Should scrubbing of self subclasses or self "close matches" happen at KG2 build or should the reasoning (Expanding) have rules in there that just discards this stuff?

I suppose if this comes from SemMedDB, then when we use the BTE as a KP, we might see the same thing. Which suggests that maybe expand() should have the special rules.

Unless it's just an ETL error in KG2 building.

**Comment by saramsey** [comment]
I don't know how the close_match edge is arising. Perhaps via some synonym-mapping going on in expander?

As for an ETL error -- possible but not my first guess. My first guess (knowing SemMedDB) is that this is exactly the tuple from SemMedDB. I can look into filtering options.

**Comment by saramsey** [comment]
Hey @amykglen is it possible that via synonym-mapping this KG2 edge is getting turned (in expander I guess??) into a CUI:C0004572-[close_match]->CUI:C0004572 self-edge?

<img width="872" alt="Screen Shot 2020-05-15 at 1 54 51 PM" src="https://user-images.githubusercontent.com/5562107/82095390-cb291100-96b3-11ea-9785-5ee096ea30bc.png">

**Comment by saramsey** [comment]
To be clear, I do not see any self-edge for `CUI:C0004572` with relationship type `close_match`.

**Comment by saramsey** [comment]
And yes, a "subclass_of" relationship between a node and itself hurts my brain. Hard for me to imagine when we would want that. I'm leaning toward a hard filter, probably in the `filter_kg_and_remap_predicates.py` script. I'll probably print a warning so we have a record of the issue in the KG2 build logfile.

**Comment by amykglen** [comment]
> Hey @amykglen is it possible that via synonym-mapping this KG2 edge is getting turned (in expander I guess??) into a CUI:C0004572-[close_match]->CUI:C0004572 self-edge?

that is definitely possible! I'll look more into it to confirm..

**Comment by saramsey** [comment]
specific remedy for the `subclass_of` issue proposed in #743

**Comment by amykglen** [comment]
Ok - so it is indeed synonym remapping causing the 'close_match' self edge - should I make it so that `expand` automatically throws out all self-edges?

Though technically the other two self edges are due to yet another multiple qnode_ids situation, a la #720 (it was going uncaught due to an oversight I've now fixed) - node CUI:C0004572 is being returned as an answer for both `n00` and `n01`. So I think it makes sense this caused an error in `resultify`, since CUI:C0004572 is being labeled with only one of those qnode_ids currently. (Though now this throws an error in `expand` before making it to `resultify`.)

While we still need to come up with a way to handle multiple qnode_id situations for other queries, if I made expand throw out all self-edges, that would get us around this particular multiple qnode_id situation (which seems to be the most common type)...

**Comment by edeutsch** [comment]
I would be fine with having expand() discard all self-edges as it does its thing. I don't think we will gain anything useful from self-edges in the short term, but longer term we may want to keep some, like "interacts_with". It might be prudent to register an issue "ARAX expand() currently discarding all self-edges; is that a potential problem?" so we can revisit it in 6 months when we may find that that is not serving us so well any more?

**Comment by amykglen** [comment]
Ok - `expand` now throws out all self-edges as it goes. And I just created #754 to remind us to revisit this behavior one day.

**Comment by edeutsch** [comment]
latest `master` rolled out to production. Test away!

**Comment by amykglen** [comment]
Thanks! All seems well now - no self edges appearing for the babesia query in production. https://arax.rtx.ai/?m=2073
