### ISSUE TITLE
Make filter_kg_and_remap_predicates.py filter out all self-edges except 'positively_regulates', 'inhibits', and 'interacts_with'

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#743]
The `filter_kg_and_remap_predicates.py` script, on encountering an edge with a "subclass_of" type and where subject and object node IDs are identical, should print a warning to stderr *indicating the `provided_by` field and the node ID*) and should drop the edge.

**Comment by saramsey** [comment]
this issue is motivated by #742

**Comment by saramsey** [comment]
This DSL is a useful test case:
```
add_qnode(name=babesia, id=n00)
add_qnode(id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00, kp=ARAX/KG2)
resultify()
```
(thank you to @edeutsch). The KG should contain a self-edge for node `CUI:C0004572` with type `subclass_of`:
```
          {
            "confidence": null,
            "defined_datetime": null,
            "edge_attributes": [
              {
                "name": "relation_curie",
                "type": null,
                "url": null,
                "value": "SEMMEDDB:isa"
              },
              {
                "name": "simplified_relation_curie",
                "type": null,
                "url": null,
                "value": "Biolink:subclass_of"
              },
              {
                "name": "simplified_relation",
                "type": null,
                "url": null,
                "value": "http://w3id.org/biolink/vocab/subclassOf"
              },
              {
                "name": "edge_label",
                "type": null,
                "url": null,
                "value": "isa"
              }
            ],
            "evidence_type": null,
            "id": "CUI:C0004572--subclass_of--CUI:C0004572",
            "is_defined_by": "ARAX/KG2",
            "negated": false,
            "provided_by": [
              "https://skr3.nlm.nih.gov/SemMedDB"
            ],
            "publications": [
              "PMID:22579523",
              "PMID:24533742",
              "PMID:24363181"
            ],
            "qedge_id": "e00",
            "qualifiers": null,
            "relation": "https://skr3.nlm.nih.gov/SemMedDB#isa",
            "source_id": "CUI:C0004572",
            "target_id": "CUI:C0004572",
            "type": "subclass_of",
            "weight": null
          },
```

**Comment by isbluis** [comment]
Hi @saramsey ,
For the edge_attributes that have a value that is an obvious URL (e.g. "http://w3id.org/biolink/vocab/subclassOf"), could you populate the "url" property of that element, either instead of, or in addition to its "value"?  Not sure what would be more elegant/simple/correct.
Thanks!

**Comment by saramsey** [comment]
Tested with this JSON snippet (as file `test-issue743.json`):
```
{
    "edges": [
        {
            "edge label": "subclass_of",
            "negated": false,
            "object": "CUI:C0004572",
            "provided by": [
              "https://skr3.nlm.nih.gov/SemMedDB"
            ],
            "publications": [
                "PMID:22579523",
                "PMID:24533742",
                "PMID:24363181"
            ],
            "publications info": {},
            "relation": "https://skr3.nlm.nih.gov/SemMedDB#isa",
            "relation curie": "SemMedDB:isa",
            "subject": "CUI:C0004572",
            "update date": "2019-08-15 20:40:54 UTC"
        }
    ],
    "nodes": [
        {
           "category": "http://w3id.org/biolink/vocab/UnknownCategory",
            "category label": "unknown_category",
            "creation date": null,
            "deprecated": false,
            "description": null,
            "full name": null,
            "id": "CUI:C0004572",
            "iri": "http://purl.obolibrary.org/obo/UMLS_C0004572",
            "name": null,
            "provided by": "https://skr3.nlm.nih.gov/SemMedDB",
            "publications": [],
            "replaced by": null,
            "synonym": [],
            "update date": "2019-08-15 20:40:54 UTC"            
        }
    ]
} 
```
Then ran the test code:
```
python3 filter_kg_and_remap_predicates.py --test --dropNegated predicate-remap.yaml curies-to-urls-lookaside-list.yaml test-issue743.json test-issue743-output.json
```
and
```
python3 filter_kg_and_remap_predicates.py --test --dropSelfSubclass --dropNegated predicate-remap.yaml curies-to-urls-lookaside-list.yaml test-issue743.json test-issue743-output2.json
```
and then did
```
diff test-issue743-output.json test-issue743-output2.json
```
Should see:
```
2,26c2
<     "edges": [
<         {
<             "edge label": "subclass_of",
<             "negated": false,
<             "object": "CUI:C0004572",
<             "provided by": [
<                 [
<                     "https://skr3.nlm.nih.gov/SemMedDB"
<                 ]
<             ],
<             "publications": [
<                 "PMID:22579523",
<                 "PMID:24533742",
<                 "PMID:24363181"
<             ],
<             "publications info": {},
<             "relation": "https://skr3.nlm.nih.gov/SemMedDB#isa",
<             "relation curie": "SemMedDB:isa",
<             "simplified edge label": "subclass_of",
<             "simplified relation": "subclassOf",
<             "simplified relation curie": "SemMedDB:isa",
<             "subject": "CUI:C0004572",
<             "update date": "2019-08-15 20:40:54 UTC"
<         }
<     ],
---
>     "edges": [],
```

**Comment by saramsey** [comment]
> Hi @saramsey ,
> For the edge_attributes that have a value that is an obvious URL (e.g. "http://w3id.org/biolink/vocab/subclassOf"), could you populate the "url" property of that element, either instead of, or in addition to its "value"? Not sure what would be more elegant/simple/correct.
> Thanks!

Hi @isbluis OK I can see this being very useful downstream. I'm just hesitating about where to code it up. Isn't the `KnowledgeGraph` object created by `expand`?  It is just passed to `resultify`. If we were to have `resultify` start modifying the `KnowledgeGraph`, isn't that mixing two somewhat orthogonal operations?  That would add a lot of code in `resultify` to be cycling through KG nodes and modifying them, when presumably expand is already visiting every KG node in the course of generating the KG?  @amykglen and @edeutsch what do you think?

**Comment by saramsey** [comment]
> > Hi @saramsey ,
> > For the edge_attributes that have a value that is an obvious URL (e.g. "http://w3id.org/biolink/vocab/subclassOf"), could you populate the "url" property of that element, either instead of, or in addition to its "value"? Not sure what would be more elegant/simple/correct.
> > Thanks!
> 
> Hi @isbluis OK I can see this being very useful downstream. I'm just hesitating about where to code it up. Isn't the `KnowledgeGraph` object created by `expand`? It is just passed to `resultify`. If we were to have `resultify` start modifying the `KnowledgeGraph`, isn't that mixing two somewhat orthogonal operations? That would add a lot of code in `resultify` to be cycling through KG nodes and modifying them, when presumably expand is already visiting every KG node in the course of generating the KG? @amykglen and @edeutsch what do you think?

I have opened #750 on this request. Please continue discussion about the `url` issue there.

**Comment by saramsey** [comment]
Hi @amykglen I have implemented (and module-level tested) this enhancement in `filter_kg_and_remap_predicates.py`. Can you please test it on kg2dev the next time you do a build?

**Comment by amykglen** [comment]
Yep, will do!

**Comment by saramsey** [comment]
OK, hold on. I am expanding this to filter out all self-edges except `interacts_with`, `positively_regulates`, and `inhibits`.

**Comment by saramsey** [comment]
OK I have updated the code in build-kg2.sh and filter_kg_and_remap_predicates.py so that all self-edges except interacts_with, positively_regulates, inhibits, and increase are deleted.

**Comment by saramsey** [comment]
I have committed the code change to the `master` branch and I think it is ready to test on `kg2dev.rtx.ai`.

**Comment by saramsey** [comment]
Hi @amykglen can I close out this issue?

**Comment by amykglen** [comment]
Sure - I don't think this has made it into a build (?), and thus hasn't been tested on 'production'. But it's fine by me. :)

**Comment by amykglen** [comment]
confirmed this is fixed in the new build on `kg2endpoint`! tested with:
```
match (n)-[e]->(n) return e.simplified_edge_label, count(distinct e)
```
which produces:
e.simplified_edge_label | count(e)
-- | --
"positively_regulates" | 69
"interacts_with" | 130
"increase" | 9
