### ISSUE TITLE
edge colors

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#745]
Would be a nice touch to label "contraindicated_for" edges in red
"indicated_for" edges in green
"interacts_with" maybe also in green
everything else in the current default color is fine

Test graph:
https://arax.rtx.ai/test/?m=2056

**Comment by isbluis** [comment]
Yea, something I had on my list already.  Try it out in devLM and see if you like the scheme.
I also changed the highlight colors a bit, and added a border to nodes for clarity.

nb. I took "interacts_with" as "physically_interacts_with" - let me know if this is not a correct interpretation.

**Comment by edeutsch** [comment]
Great, yes, I like it. Except for the highlight color. It may be my f.luxed screen, but the highlight yellow nearly makes the highlighted edge disappear. I would suggest making it more orangey. Maybe the same color as the warning message orange.

**Comment by isbluis** [comment]
Yea, yellow was hard to make out.  Changed to orange.  It's somewhat similar to red, but perhaps good enough?

**Comment by edeutsch** [comment]
orange is an improvement, yes. Maybe simultaneously changing some other attribute like thickness or dashedness or something might help highlight it. But not important, fine as is. Fine to commit and push AFAIC. Thanks!

**Comment by isbluis** [comment]
Orange it is!
