### ISSUE TITLE
Repositioning Survey for SARS-CoV-2 Antivirals

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#746]
From Jared:

it would be really cool to see if we can automate the 12,000 queries from this article, which HAVE ALREADY BEEN LAB TESTED. I need to read the text more carefully but the actual number appears to be "1,280 plus ~12,000” whatever that sums to.
	"A Large-scale Drug Repositioning Survey for SARS-CoV-2 Antivirals" by Laura Riva et al.
	https://www.biorxiv.org/content/10.1101/2020.04.16.044016v1
	It found 30 “true positives”, so there is some really good training available for both true and false positives for machine learning.

**Comment by dkoslicki** [comment]
Once @finnagin addresses #758 , we could run all them through the machine learning model, focus on the high-probability "treats" ones, and then devise a DSL workflow to try to explain the mechanism of action.

**Comment by finnagin** [comment]
@dkoslicki is this still relevant?

**Comment by dkoslicki** [comment]
Not unless you're particularly interested in this. Happily, we have vaccines and treatments now :)

**Comment by finnagin** [comment]
Fair :) closing then
