### ISSUE TITLE
Edge URLs often point to invalid locations

### ISSUE THREAD

**Issue by isbluis** [RTXteam/RTX#747]
I have come a few examples of URLs within the "relation" edge attribute (and certain edge_attributes) that do not point to useful (or sometimes valid) locations.  A few examples:
````
 "relation": "https://identifiers.org/umls/MSH/isa",  <--- goes to error page
 "relation": "http://www.w3.org/2002/07/owl#sameAs",  <--- downloads a "text/turtle" document
 "relation": "http://purl.org/obo/owl/oboFormat#oboFormat_xref",  <--- opens a large xml doc
 https://biolink.github.io/biolink-model/docs/subclassOf  <--- 404
````

Possibly related to #706?

**Comment by saramsey** [comment]
Hey @isbluis I am not seeing any record of this as a `relation` field in the current KG2 (`kg2endpoint2.rtx.ai`):
```
https://biolink.github.io/biolink-model/docs/subclassOf
```
can you please let me know what query you did, that returned this `relation` string?

**Comment by isbluis** [comment]
Hi @saramsey .  That example was actually from a link embedded within a `node_attribute`, and not a `relation`. Sorry if these are different domains, but I do them inside the same object. Let me know if this should be a separate issue.

Otherwise, and If relevant, this is a fragment (of https://arax.rtx.ai/index.html?m=2041 ) where this comes up, under `simplified_relation` :
```
        "edge_attributes": [
          {
            "name": "relation_curie",
            "type": null,
            "url": null,
            "value": "SEMMEDDB:isa"
          },
          {
            "name": "simplified_relation_curie",
            "type": null,
            "url": null,
            "value": "Biolink:subclass_of"
          },
          {
            "name": "simplified_relation",
            "type": null,
            "url": null,
            "value": "http://w3id.org/biolink/vocab/subclassOf"
          },
          {
            "name": "edge_label",
            "type": null,
            "url": null,
            "value": "isa"
          }
        ],
```
Thanks!

**Comment by saramsey** [comment]
Ah, `simplified_relation` makes more sense.  Thank you for clarifying. I think I can fix this.

**Comment by saramsey** [comment]
Hi @amykglen I've pushed a couple of code changes to `master` to address this issue. They seem slight but I think careful testing will be needed. Can you test these changes out on `kg2dev`?

**Comment by saramsey** [comment]
Hi @isbluis my general plan/hope is to make sure that `simplified_relation` is a useful and resolvable URI; the original `relation` fields come from upstream sources and contain all manner of old URIs. So I guess I am wondering if we can get by using the `simplified_relation` URIs instead, at least for edges that come from KG2?

**Comment by saramsey** [comment]
OK @amykglen  I am testing these two latest commits right now on `kg2dev`. I know it's bad to commit the code changes and then test them but I was in a hurry so didn't have time to make a branch or copy the files by sftp. If the changes break something I will back them out.

**Comment by isbluis** [comment]
> 
> 
> Hi @isbluis my general plan/hope is to make sure that `simplified_relation` is a useful and resolvable URI; the original `relation` fields come from upstream sources and contain all manner of old URIs. So I guess I am wondering if we can get by using the `simplified_relation` URIs instead, at least for edges that come from KG2?

Hi @saramsey , sounds good, and thanks for looking into this!

**Comment by saramsey** [comment]
OK the issue with non-resolvable URLs occurring in the `simplified_relation` edge property field for biolink predicates should be fixed (in the code) now. You won't see it in the production KG2 until our next production build, however (that could be a week out).

**Comment by saramsey** [comment]
Hi @isbluis: so I believe all the biolink relations in the new KG2 build (as in, on kg2endpoint.rtx.ai) now have resolvable URIs,

<img width="999" alt="Screen Shot 2020-07-17 at 10 52 30 AM" src="https://user-images.githubusercontent.com/5562107/87816162-ba179000-c81b-11ea-8cf7-a1c9d56e2282.png">

Unfortunately, URIs for most other relation types are not currently resolvable. Most upstream knowledge sources that provide web pages for individual concepts unfortunately don't provide individual web pages for relation types.

**Comment by saramsey** [comment]
Actually, I will leave this open until we have pushed the new KG2 to the production KG2 server and verified that the working biolink edge URIs are getting all the way to the ARAX UI.

**Comment by isbluis** [comment]
Thanks for all of the hard work tracking down these issues, @saramsey !  I certainly did not want to send you on such a treasure hunt, though I did feel that it was silly to present URLs that pointed nowhere.  Perhaps having a link to the master list of concepts or ontology for the rest might be enough?

**Comment by saramsey** [comment]
> Thanks for all of the hard work tracking down these issues, @saramsey ! I certainly did not want to send you on such a treasure hunt, though I did feel that it was silly to present URLs that pointed nowhere. Perhaps having a link to the master list of concepts or ontology for the rest might be enough?

I totally agree. But `iri` is a required slot in the Biolink data model, so I try my best to provide *something*, LOL. As a general rule, for an edge, you want to look at the URL in `simplified_relation`. And if it is a biolink URL, it *should* resolve. Otherwise, YMMV.

For nodes, the situation is much better. The `iri` field should generally resolve (if not, please report it as it is probably a fixable bug).
