### ISSUE TITLE
Connect GO terms to phenotypes and/or diseases and/or anatomy.

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#75]
Currently GO terms (``biological_process``) are only connected to proteins and microRNA's. It would be great (especially for COP type questions) to have these nodes connected to phenotypes and/or diseases and/or anatomy nodes.

From ``call apoc.meta.graph``:
![graph](https://user-images.githubusercontent.com/6362936/38957850-7408e40c-4310-11e8-8dea-9f88c5da718c.png)

**Comment by saramsey** [comment]
i think we can do this by the UBERON "has capability" predicates which link to biological_process nodes

**Comment by saramsey** [comment]
David views connecting disease to biological process as higher priority than connecting anatomy to biological process

**Comment by saramsey** [comment]
From Chris Mungall:

> Currently we have curated links in MONDO between disease and GO; generally conservative and "obvious". E.g.
> 
> id: MONDO:0019053
> name: peroxisomal disease
> ...
> relationship: disease_has_basis_in_disruption_of GO:0005777  ! peroxisome
> These are queryable via SciGraph
> 
> e.g.
> 
> https://scigraph-ontology.monarchinitiative.org/scigraph/graph/neighbors/MONDO%3A0019053?depth=1&blankNodes=false&direction=BOTH&entail=false
> 
>

**Comment by saramsey** [comment]
superseded by #122 and #123
