### ISSUE TITLE
anyone else seeing an issue with "unclosed SSL socket" when running ARAX?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#753]
I'm seeing this warning when I run ARAX_resultify:
```
ResourceWarning: unclosed <ssl.SSLSocket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.0.1.42', 57272), raddr=('18.223.254.124', 7687)>
```
wondering if maybe somewhere in the Neo4j accessing code, there needs to be a destructor method that disconnects from Neo4j?

**Comment by saramsey** [comment]
Anyone else seeing this issue?  I am seeing it on a 2018 MBP (macOS 10.14.6) under python 3.7.4.

**Comment by edeutsch** [comment]
I have not encountered this issue.
but where are we on upgrading neo4j to a modern version with all the bugfixes since the old version we're using? Maybe this is another symptom of the same problem?

**Comment by amykglen** [comment]
I do see this warning if I run `ARAX_resultify_testcases.py`.

I don't see any `driver.close()` in [ReasoningUtilities.py](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/ReasoningUtilities.py)... could that be a culprit? Just tried adding that in there locally and I don't seem to see the error anymore...

**Comment by saramsey** [comment]
> I do see this warning if I run `ARAX_resultify_testcases.py`.
> 
> I don't see any `driver.close()` in [ReasoningUtilities.py](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/ReasoningUtilities.py)... could that be a culprit? Just tried adding that in there locally and I don't seem to see the warning anymore...

Excellent detective work!  @dkoslicki any objections to us committing this change into the master branch?

**Comment by amykglen** [comment]
Oddly, I'm actually now not seeing this warning anymore even without the changes to ReasoningUtilities... are you still seeing it @saramsey?

**Comment by dkoslicki** [comment]
Curiously, I’ve never seen that particular issue on my end...

**Comment by finnagin** [comment]
@saramsey is this still relevant or should we close? Looks like from the comments above it might be fixed now?

**Comment by saramsey** [comment]
Closing as this issue has been inactive forever.
