### ISSUE TITLE
ARAX expand() currently discarding all self-edges; is that a potential problem?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#754]
Creating this issue to remind us to revisit this topic down the road. We decided to make `Expand` throw out all self-edges for now, but perhaps ultimately some kinds of self-edges would be useful to keep.

From @edeutsch in #742:

> I would be fine with having expand() discard all self-edges as it does its thing. I don't think we will gain anything useful from self-edges in the short term, but longer term we may want to keep some, like "interacts_with". It might be prudent to register an issue "ARAX expand() currently discarding all self-edges; is that a potential problem?" so we can revisit it in 6 months when we may find that that is not serving us so well any more?

**Comment by saramsey** [comment]
For KG2 expanding, I vote to make an exception for `interacts_with`, `inhibits`, and `positively_regulates`.

<img width="908" alt="Screen Shot 2020-05-19 at 9 42 13 AM" src="https://user-images.githubusercontent.com/5562107/82353987-09287c80-99b5-11ea-9312-7ddddb9d0793.png">

**Comment by saramsey** [comment]
OK I have updated the code in `build-kg2.sh` and `filter_kg_and_remap_predicates.py` so that all self-edges except `interacts_with`, `positively_regulates`, `inhibits`, and `increase` are deleted.

**Comment by amykglen** [comment]
no issues seem to have arisen in the last year with Expand discarding all self-edges - closing
