### ISSUE TITLE
'publications' on KG2 nodes sometimes contains an empty string

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#755]
I noticed that sometimes the first element in the 'publications' list on KG2 nodes is an empty string:

![Screen Shot 2020-05-19 at 4 22 04 PM](https://user-images.githubusercontent.com/49423686/82387833-e914af80-99ec-11ea-837a-f6f3538ddf8f.png)

There appear to be about 24k such nodes in kg2endpoint2, all coming from UniProt:

![Screen Shot 2020-05-19 at 4 29 10 PM](https://user-images.githubusercontent.com/49423686/82388241-f7170000-99ed-11ea-97d0-707595887a1c.png)

**Comment by saramsey** [comment]
Confirmed using this code on `kg2endpoint2.rtx.ai`:
```
match (n) where n.publications starts with "[''," return n limit 1;
```

**Comment by saramsey** [comment]
Hi @amykglen sorry I think I introduced this bug with some refactoring that I did in addressing #725. Should be fixed now. Ready to roll into the next KG2 build.

**Comment by amykglen** [comment]
confirmed this is fixed in the new build in `kg2endpoint`!
