### ISSUE TITLE
Fill out 'type' on NodeAttributes/EdgeAttributes Expand creates

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#757]
Forking off from #750 - Expand currently isn't filling out the 'type' field on NodeAttributes/EdgeAttributes it creates. Need to figure out what 'type' should be in different situations and start populating it.

NodeAttributes Expand creates:

- for all nodes:
  - [ ] equivalent_curies
- for nodes from KG2:
  - [ ] publications
  - [ ] synonym
  - [ ] category
  - [ ] provided_by
  - [ ] deprecated
  - [ ] update_date

EdgeAttributes Expand creates:

- for edges from KG2:
  - [ ] relation_curie
  - [ ] simplified_relation_curie
  - [ ] simplified_relation
  - [ ] edge_label
  - [ ] publications_info   (soon to be loaded - isn't yet)
- for edges from KG1:
  - [ ] probability

**Comment by edeutsch** [comment]
If they are the same, calling a concept "publications" on nodes, but "publications_info" on edges seems less than ideal.

**Comment by isbluis** [comment]
Hi @amykglen .  Is `synonym` a _list_ or _scalar_?

In general, what do you think of pluralizing _list_ attributes, and leaving _scalar_ ones in the singular form?
Or is this somehow in violation and/or part of the standard, @edeutsch ?

**Comment by amykglen** [comment]
@edeutsch - no, edge.publications and edge.publications_info are different properties in KG2. but publications is an actual property in the API model for Edges, thus no EdgeAttribute for publications needs to be created (so it doesn't appear on my list above).

**Comment by edeutsch** [comment]
ah, I see. out of curiosity, what's the difference between publications and publications_info?

**Comment by amykglen** [comment]
@isbluis - yes, 'synonym' is a list, and I agree that's definitely not ideal naming. I have it this way because that is what the property is called within KG2, though I could transform that when creating the NodeAttribute in expand, so that it's called 'synonyms' for ARAX's purposes. but perhaps this is something that should be addressed directly within KG2 (@saramsey)?

**Comment by edeutsch** [comment]
@isbluis , seems like a nice convention to make lists plural. But if there's a standard, we should follow that, and we can lobby to change the standard if it doesn't follow the convention. I think it does.

**Comment by edeutsch** [comment]
should that be publications_infos then?

**Comment by amykglen** [comment]
@edeutsch:

publications looks like this:
```
['PMID:9580177']
```
publications info looks like this:
```
{
   "PMID:9580177":{
      "publication date":"1998 Jan",
      "sentence":"The different treatments for PV are       discussed; in addition to venesection, conventional treatment include       chemotherapy with hydroxyurea and pipobroman, as well as the erythropheresis,       -interferon and aspirin.",
      "subject score":1000,
      "object score":1000
   }
}
```

**Comment by isbluis** [comment]
> should that be publications_infos then?

I'd say the _s_ in _publications_ covers the plural?  ESL here....

**Comment by edeutsch** [comment]
@amykglen , thanks, good info.

@isbluis , okay, publications_info is good then.

**Comment by amykglen** [comment]
closing since this is subsumed by #1192
