### ISSUE TITLE
Update reasoner_id from RTX to ARAX?

### ISSUE THREAD

**Issue by isbluis** [RTXteam/RTX#770]
When executing a query, the response message contains a `reasoner_id` field that we are currently still populating with the value "`RTX`".  This is the value that shows up on the UI when exploring results, and I believe gets passed to external agents querying remotely.
`
      "reasoner_id": "RTX",
`

Is there a plan to update/move to "`ARAX`"? 

If so, I suppose the UI should still continue to handle both cases as similar?  (e.g. same color, and other display logic)

**Comment by edeutsch** [comment]
From what I could see the Message.reasoner_id was already 'ARAX', but I did find that the Result.reasoner_id was still 'RTX'. I went through the code and fixed all the instances that I could fine of this issue, but I am uncertain if this was your issue.

Fix checked into master and master rolled out to devED, test, and beta.

Please let me know if this seems to be resolved in those areas.

**Comment by isbluis** [comment]
It was within results.  Looks good now, thanks!
