### ISSUE TITLE
Should DSL-built query graphs be validated?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#773]
We are currently validating incoming query_graphs via the ARAXQueryGraphInterpreter mechanism. However, query_graphs that are built with DSL commands (add_qnode and add_qedge) are NOT subject to any validation. Should they be?

Pros:
- If a naive user builds a non-sensical query_graph, they will be told before the ARAX goes off a cliff

Cons:
- An expert user cannot go off piste to try things not currently understood by the ARAXQueryGraphInterpreter 

Maybe as a middle ground, we could:
- Error out for things we agree are illegal (such as an unconnected graph #772)
- Issue a warning if there are no errors but the query_graph does not match a known template

**Comment by edeutsch** [comment]
Not generally much opinion, so just leave as is for now. Query graphs built via DSL are not validated. Just execute as written, no matter how crazy.

**Comment by finnagin** [comment]
@edeutsch Is this still relevant or should it be closed?

**Comment by edeutsch** [comment]
I think we can close, thanks.
