### ISSUE TITLE
Better type for NGD edges?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#775]
I am trying to write some code that make a decision based on an NGD value and I'm finding it awkward to know which edges those are. Here is what an NGD edge looks like:

```
      {
        "confidence": 1,
        "defined_datetime": "2020-05-27 03:39:11",
        "edge_attributes": [
          {
            "name": "ngd",
            "type": "float",
            "url": "https://arax.rtx.ai/api/rtx/v1/ui/#/PubmedMeshNgd",
            "value": "0.592373804699249"
          }
        ],
        "evidence_type": null,
        "id": "N1_14",
        "is_defined_by": "https://arax.rtx.ai/api/rtx/v1/ui/",
        "negated": null,
        "provided_by": "ARAX/RTX",
        "publications": null,
        "qedge_id": "N1",
        "qualifiers": null,
        "relation": "ngd",
        "source_id": "CHEMBL.COMPOUND:CHEMBL112",
        "target_id": "UniProtKB:P10635",
        "type": "N1",
        "weight": null
      },
```

First quibble:
- It seems that the reliable way to determine what this is an NGD edge is by looking into the relation field and keying on "ngd". I suppose that's okay, but it seems like type is really the thing.
- I suggest that instead of letting the user specify a type "N1", the type should be a universal constant as if it were in BioLink. "physically_interacts_with" has a universal meaning. I suggest we invent a type such as "pubmed_normalized_google_distance" or whatever term we think would could be as concrete as a BioLink type and type it that.
- This becomes even more useful should there be a day when we have an NGD-based expander. Those edges will need a type, and I suggest we need a BioLink style type that means that these two entities are connected via non-infinite co-occurance distance metric as computed over PubMed. What is the best term?

Other quibbles:
- These all have a confidence of 1. What does that mean? Does that mean that we are 100% confident that these two nodes are co-occurring in the literature with the specified score? Is that what we want to convey with a confidence metric here?
- "provided_by": "ARAX/RTX": This is supposed to be the knowledge source (KS). Who really is the knowledge source? Maybe for eutils NGD this should be "NCBI/eutils" or something? I never really understood the exact provider. Or maybe we are? For FastNGD, one could argue that we really are the knowledge source since we computed this ourselves? What should that be?
- "is_defined_by": "https://arax.rtx.ai/api/rtx/v1/ui/": This is supposed to be the knowledge provider (KP) I think. It is unclear exactly what form this should take. A URI seems nice, but maybe just ARAX would suffice. A URL into the API UI probably isn't right.

**Comment by dkoslicki** [comment]
Those all seem reasonable to me! A few comments:

>Those edges will need a type, and I suggest we need a BioLink style type that means that these two entities are connected via non-infinite co-occurance distance metric as computed over PubMed. What is the best term?

No idea what the best term would be, but we could ask the BioLink people if something exists already (or make a PR like [they did for COHD p-values](https://github.com/biolink/biolink-model/issues/338))

- confidence issue: I did mean "100% sure this is the co-occurrence score", but as usual, given "confidence" hasn't been defined by anyone, I'm happy to change it to something else if it makes more sense

- `provided_by` and `is_defined_by`: I was confused by what I should stick in here, so just threw something in. If anyone has clarity about what these should actually be, I'm happy to change it.

**Comment by dkoslicki** [comment]
agreed and closing in favor of #786 to batch all virtual edge types under this change.
