### ISSUE TITLE
make provided_by field on nodes a CURIE and on relationships a list of CURIEs

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#776]
This is to better align KG2 with the biolink model specification.

**Comment by edeutsch** [comment]
I'm curious to know what a CURIE for a provider looks like. Do you have examples?

**Comment by saramsey** [comment]
> I'm curious to know what a CURIE for a provider looks like. Do you have examples?

Yes. I had to get creative. For example, for Ensembl Gene, the provider CURIE is:
```
identifiers_org_registry:ensembl
```
which would expand (using the KG2 CURIE/URL mapper) to:
```
https://registry.identifiers.org/registry/ensembl
```
which is a working, persistent URL.  Another example would be the provider CURIE
```
umlssource:MTH
```
which would expand (using the KG2 CURIE/URL mapper) to:
```
https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/MTH
```
which is a working, persistent URL. A third example would be the provider CURIE
```
biolink:
```
which would expand (using the KG2 CURIE/URL mapper) to:
```
https://w3id.org/biolink/
```
which is a working, persistent URL.

Of course, at the presentation layer, you shouldn't ever have to use the KG2 CURIE/URL mapper. Once I have my spiffy new build of KG2 deployed, you can just take the provided_by CURIE, find the node in KG2 whose ID matches that provided_by CURIE, and then find the IRI of that KG2 node. It should be a working, resolvable URI (else there is a bug which should be reported in GitHub).

**Comment by saramsey** [comment]
I may change `umlssource` to `umls_source` for some semblance of consistency. I should note that neither `umls_source` nor `identifiers_org_registry` is an officially recognized "biolink" standard, but then again, there is no alternative CURIE prefix proposed by Biolink/SRI for those base URLs, so we are kind of on our own (I suppose we can make a PR but it is low priority since if they pick something different, I'll just use what they pick).

**Comment by edeutsch** [comment]
okay, seems reasonable to me. My only nagging concern is that if you showed these things to Chris Mungall and Michel Dumontier that might say, no , no, all wrong, *this* is how you should do it (50% chance they disagree with each other, but that's another story). But the most efficient course of action may be just to go ahead to implement it this way and then change it later if there's ever a consensus on what it should be.

**Comment by saramsey** [comment]
Yes, I agree with you. I am not sure that making a PR is worth it since I have a low percentage success rate of proposing things that are ultimately adopted. But switching the CURIE prefixes for those two base URLs (should standards ever be adopted) would be a one-line change, each.

**Comment by saramsey** [comment]
In fact I just changed from `umlssource` to `umls_source` having realized that it enhances readability and underscores (ahem) that this is a non-standard CURIE prefix.

**Comment by saramsey** [comment]
Coding for this issue is complete (I think). Just need to test via a full KG2 rebuild.

**Comment by saramsey** [comment]
Done

<img width="674" alt="Screen Shot 2020-07-16 at 11 35 00 AM" src="https://user-images.githubusercontent.com/5562107/87708998-71e36980-c758-11ea-90a9-0ee294f022cc.png">
