### ISSUE TITLE
remove force_isset_false parameter from ARAX_resultify

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#779]
- [x] Remove the `force_isset_false` parameter from [ARAXResultify](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_resultify.py)
- [x] Regenerate the auto-documentation so this parameter is no longer listed there (run `python document_dsl_commands.py` to do so)
- [x] Adjust tests in [test_ARAX_resultify.py](https://github.com/RTXteam/RTX/blob/master/code/ARAX/test/test_ARAX_resultify.py) so they no longer use this parameter
- [x] Check for/remove any other usages of this parameter within ARAX code...

**Comment by kvarforl** [comment]
submitted [https://github.com/RTXteam/RTX/pull/839](url) with changes; waiting to verify on production

**Comment by kvarforl** [comment]
verified on /beta using examples 101 and 102 from ARAXQuery.py (the two that originally used force_isset_false in their call to resultify)
