### ISSUE TITLE
predicate triples for all KP's

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#780]
For both https://arax.rtx.ai/api/rtx/v1/predicates and #623 we need all allowable node + edge types, as well all allowable (node, predicate, node) triples.

For now, make scripts that generate these for:
- [ ] KG1
- [ ] KG2
- [ ] BTE

Store these scripts (and their output) in https://github.com/RTXteam/RTX/tree/master/code/ARAX/KnowledgeSources

@edeutsch will be in charge of changing the `predicates` endpoint appropriately.

**Comment by saramsey** [comment]
point of clarification -- who is currently working this issue?

**Comment by amykglen** [comment]
a bit unclear - I believe I was tasked with the BTE step, and @finnagin with the KG1/2 steps? (and @edeutsch with the last step of updating the `predicates` endpoint.) 

but I had to write a very similar thing for KG1/2 as well as BTE for [this script](https://github.com/RTXteam/RTX/blob/master/code/ARAX/KnowledgeSources/create_csv_of_kp_node_pairs.py), so I'm happy to take care of all three if desired.

**Comment by saramsey** [comment]
talked to finn about this and we agreed that the kg2 part can await the rollout of the new kg2 build, in 1-2 weeks; but the kg1 work could happen anytime

**Comment by dkoslicki** [comment]
predicates endpoint has been depreciated
