### ISSUE TITLE
Vote on what we (as an ARA) think KP's MUST/SHOULD/CAN/NOT do

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#782]
Use [this doc](https://docs.google.com/presentation/d/1hoAX5mVszRmRipxo0xeHdzXAnIfbYeH3ZKewTUQM9Hg/edit?usp=sharing) for definition of terms, fill out our votes [on this spreadsheet](https://docs.google.com/spreadsheets/d/1jT1DykBltSsakAYIpyFZ_kfKaGAIcgpUX2eLHwXVO28/edit#gid=0), and if we (Team Expander Agent) have differing opinions, discuss in this issue.

**Comment by dkoslicki** [comment]
Can add rows if we want. **Deadline is next week 6/4/2020**

**Comment by saramsey** [comment]
I suggest "should" for this: "A KP accepts any biolink-allowed CURIE as input"

**Comment by saramsey** [comment]
I suggest "should" for this: "A KP provides metadata around its identifiers"

**Comment by saramsey** [comment]
Suggest "may" for this: "A KP uses biolink-model semantic types only"

**Comment by dkoslicki** [comment]
Forgot to say: I made these changes as suggested by Steve
