### ISSUE TITLE
Strawman ranker is up!

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#783]
It's actually been rolled out for a couple days now, but perhaps we can chat about it at the hackathon and beyond.

Now, if there are probabilities, scores, confidences, etc. the new experimental rank_results() method in the messenger (temporary place) will compute a final score and put it in the "confidence" slot and automatically sort the results[] by this confidence. This is displayed nicely in the GUI.

It is limited in its capability, but tries to take into account confidence, probability, jaccard_index, ngd, probability_drug_treats and roll it all up into one score. It could be better. But I'm happy that our results are now visibly scored and ordered in a sensible way.

Here are two DSL programs for discussion, basically Example 1 and example 2, a bit refined:

#### Example 1
```
add_qnode(name=acetaminophen, id=n0)
add_qnode(type=protein, id=n1)
add_qedge(source_id=n0, target_id=n1, id=e0)
expand(edge_id=e0)
overlay(action=compute_ngd, virtual_edge_type=N1, source_qnode_id=n0, target_qnode_id=n1)
resultify()
```
#### Example 2
```
add_qnode(curie=DOID:14330, id=n00)
add_qnode(type=protein, is_set=true, id=n01)
add_qnode(type=chemical_substance, id=n02)
add_qedge(source_id=n00, target_id=n01, id=e00)
add_qedge(source_id=n01, target_id=n02, id=e01, type=physically_interacts_with)
expand(edge_id=[e00,e01], kp=ARAX/KG1)
overlay(action=compute_jaccard, start_node_id=n00, intermediate_node_id=n01, end_node_id=n02, virtual_edge_type=J1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=jaccard_index, direction=below, threshold=.2, remove_connected_nodes=t, qnode_id=n02)
filter_kg(action=remove_edges_by_property, edge_property=provided_by, property_value=Pharos)
overlay(action=predict_drug_treats_disease, source_qnode_id=n02, target_qnode_id=n00, virtual_edge_type=P1)
resultify()
```

Comments?

**Comment by dkoslicki** [comment]
Just FYI @edeutsch, I’ll hold off from fiddling with this until you’ve moved it into its own class or module.

**Comment by dkoslicki** [comment]
@edeutsch added a few more edge attributes. Will need to be fiddled with since while the order is nice, the overall confidence is rather low...

**Comment by finnagin** [comment]
Closing since the ranker has been in use for a while now
