### ISSUE TITLE
Fix broken demo examples

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#784]
From the mini hack-a-thon. 

Look through ARAX_query.py and find the demo examples then test and fix any filter bugs causing the issue.

**Comment by dkoslicki** [comment]
Note that changes due to #785 and #786 will result in some of the DSL needing to be changed

**Comment by saramsey** [comment]
This issue refers to the internal example methods in ARAX_query.py, not the Jupyter examples. Work on this is ongoing, per update from @finnigan

**Comment by dkoslicki** [comment]
@finnagin And also note, these examples have been moved to [test_ARAX_workflows.py](https://github.com/RTXteam/RTX/blob/master/code/ARAX/test/test_ARAX_workflows.py), so may already be passing/working. If you want to add the variations to these demo examples from `ARAX_query.py` to `test_ARAX_workflows.py`, that would be great.

**Comment by saramsey** [comment]
Keeping this issue open; @finnagin says he still needs to add a few more test cases to workflows
