### ISSUE TITLE
Add option to filter on "relation" property

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#785]
From the mini hack-a-thon.

Currently can filter on the type property to specify which edge to filter on but would be better to have the relation property be unique to the edge and filter on that.

**Comment by saramsey** [comment]
@finnagin says this is implemented and just awaiting testing

**Comment by dkoslicki** [comment]
@finnagin like testing on production? Or testing in the `test` folder for `pytest`? If the former, let’s add the “needs test on production” tag

**Comment by finnagin** [comment]
Just checked and this is working on production.
