### ISSUE TITLE
change all virtual edge DSL commands from allowing type specificiation to relation specification

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#786]
- [x] pick a type for each of the virtual edges and fix it to a certain term
- [x] let the user specify the relation
- [ ] submit issue to BiolinkModel github mentioning we need a relationship type for this
- [x] `is_defined_by` should be a string `ARAX` (TBD for a better value)
- [x] `provided_by` should be a string `ARAX` (TBD for a better value)
- [x] change `type` to an actual machine readable CURIE/IRI/etc. eg [here](http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fdata_1669&jump_to_nav=true)

Subsequent filtering will be on relation as per #785

**Comment by dkoslicki** [comment]
Need to decide on what to names to use for what... discuss on 6/5/20 mini-hackathon

**Comment by dkoslicki** [comment]
Suggestion from discussion:
- [malaria] has_normalized_google_distance_with [acetaminophen] (of value=n.nnn)
- has_fisher_exact_test_p-value_with
- has_jaccard_index_with
- [hydroxychloroquine] probably_treats [covidiocy]
- has_paired_concept_frequency_with
- has_observed_expected_ratio_with
- has_chi_square_with

**Comment by dkoslicki** [comment]
`virtual_edge_type` -> `virtual_relation_label`

**Comment by edeutsch** [comment]
Also from the agenda Google doc:

data:1669
http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fdata_1669&jump_to_nav=true

```
{
        "id": "FET1_1234",
        "is_defined_by": "ARAX",
        "provided_by": "ARAX",
        "relation": "FET1",
        "source_id": "UniProtKB:P14136",
        "target_id": "GO:0045109",
        “qedge_id”: FET1,
        “confidence”: null,
        "type": "has_fisher_exact_test_p-value_with",
        “edge_attribute”: {
   "name":"Fisher exact test p-value",
   "type":"data:1669",
   "url":null,
   "value": 0.001
         }
      },



        “edge_attribute”: {
   "name":"publication",
   "type":"data:1187",
   "url":”https://pubmed.ncbi.nlm.nih.gov/201293829"
   "value": “PMID:201293829”
         }
```
In FET DSL virtual_edge_type -> virtual_relation_label

**Comment by dkoslicki** [comment]
Tests included for all overlay functions in `python ARAX_query.py 7680` and `python ARAX_query.py 7681`
