### ISSUE TITLE
Auto-get documentation not ordered

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#794]
Running `RTX/code/ARAX/Documentation$ python document_dsl_commands.py` results in a reordering of the TOC and commands due to dicts not guaranteed to be sorted. Should sort these somehow so they stay in the same general location (or are somehow sorted).

**Comment by dkoslicki** [comment]
I recall @isbluis mentioning this being an issue at the most recent relay. Shall we add to the technical debt?

**Comment by isbluis** [comment]
It looks like I actually fixed this with 0c7caef (in 2021!)
Closing.
