### ISSUE TITLE
extract-unichem.sh Failing to Get Data using curl

### ISSUE THREAD

**Issue by ericawood** [RTXteam/RTX#796]
While I was working on the Snakefile, I came across extract-unichem.sh failing. I think that the link to the data might be bad. Below shows how it failed on the curl line of the bash script, creating a file that does not have anything in it. I tried the curl line not in the bash script as well, which produced the same result (the second image).

![image](https://user-images.githubusercontent.com/36611732/83817641-24181380-a67a-11ea-8e1f-e5e9f69b2620.png)
![image](https://user-images.githubusercontent.com/36611732/83817867-b7514900-a67a-11ea-9827-ee27d4a8a95f.png)

**Comment by saramsey** [comment]
bumped unichem version number to 280 (in `extract-unichem.sh` in the branch `master`); can you please do a `git pull origin master` and then test it now?

**Comment by ericawood** [comment]
That worked, so I am closing this issue. Thank you!

**Comment by ericawood** [comment]
On a related note, to prevent extract-chembl.sh from failing, I had to change the version number to 27 (I will commit that change later).
