### ISSUE TITLE
Example 12 doesn't work with experimental ranker

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#797]
`python ARAX_query 12` gives:
```
 ERROR: An uncaught error occurred: list index out of range: ['Traceback (most recent call last):\n',
File "ARAX_query.py", line 544, in executeProcessingPlan messenger.rank_results(message, response=response)\n',
File "/home/dkoslicki/Desktop/RTX/code/ARAX/ARAXQuery/ARAX_messenger.py", line 592, in rank_results\n    result = query_graph_info.assess(message)\n', 
File "/home/dkoslicki/Desktop/RTX/code/ARAX/ARAXQuery/query_graph_info.py", line 152, in assess\n    start_node = singletons[0]\n', 'IndexError: list index out of range\n']
```
But if I comment out `result = query_graph_info.assess(message)` in `ARAX_messenger.py`, things work just fine...

**Comment by dkoslicki** [comment]
Blocking until #786 is closed

**Comment by edeutsch** [comment]
Line 94 in query_graph_info needs to be updated to check the types (not relations) of the edges and use the new names you will be using for all virtual edges

**Comment by dkoslicki** [comment]
@edeutsch all changes made for #786, so you're good to go in addressing this issue

**Comment by edeutsch** [comment]
okay, I have updated the query_graph_info.py to know about the new query_edge_type names that we decided on in #786, and test 12 appears to pass now.

**Comment by dkoslicki** [comment]
Excellent! Was this done on `master` (I don’t see an associated commit reference)? I.e. can we close this issue?

**Comment by edeutsch** [comment]
ah, no, I think this was done in the overlay branch, where it was needed for testing prior to merge with master? 
https://github.com/RTXteam/RTX/commit/b62f40fc6142286862529948996662172500b48f

**Comment by edeutsch** [comment]
closing ancient history
