### ISSUE TITLE
Need a few DSL programs to showcase FET

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#798]
My notes say I was supposed to create an issue to request a few different DSL programs that showcase nice examples of using Fisher Exact Test in action.

Maybe this is already done in #623 however. I don't know.

I don't recall exactly what we had in mind with this issue. We can close if this is already done.

**Comment by chunyuma** [comment]
@edeutsch, I think we can close this issue. I added two more DSL examples to ARAX_query.py in `master` branch and give a comment [here](https://github.com/RTXteam/RTX/issues/623#issuecomment-639911173). Please check it to see if this is enough to close this issue.

**Comment by dkoslicki** [comment]
@chunyuma mind posting the DSL commands in this issue for posterity's sake (and so we can close the issue)?

**Comment by chunyuma** [comment]
Here are a few showcase DSL programs for FET.

1. This DSL returns the 10 smallest FET p-values and only add the virtual edge with these 10 FET p-values
```
add_qnode(id=n00, curie=CHEMBL.COMPOUND:CHEMBL521)
add_qnode(id=n01, type=protein)
add_qedge(id=e00, source_id=n00, target_id=n01)
add_qnode(id=n02, type=biological_process)
add_qedge(id=e01, source_id=n01, target_id=n02)
expand(edge_id=[e00, e01], kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n01, virtual_relation_label=FET, target_qnode_id=n02, top_n=10)
resultify()
```
2. This DSL is a two-hop sample. First, find all edges between DOID:14330 and proteins in KG1 and then filter out the proteins with connection having FET pvalue>0.001 to DOID:14330. Second, find all edges between existing proteins and chemical_substances in KG1 and then filter out the chemical_substances with connection having FET pvalue>0.005 to proteins.
```
add_qnode(curie=DOID:14330, id=n00)
add_qnode(type=protein, is_set=true, id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n00, target_qnode_id=n01, virtual_relation_label=FET1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.001, remove_connected_nodes=t, qnode_id=n01)
add_qnode(type=chemical_substance, id=n02)
add_qedge(source_id=n01, target_id=n02, id=e01, type=physically_interacts_with)
expand(edge_id=e01, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n01, target_qnode_id=n02, virtual_relation_label=FET2)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.005, remove_connected_nodes=t, qnode_id=n02)
resultify()
```
  
3. This DSL is a three-hop sample to find the "representative" path in KG1 for DOID:14330 - protein - (physically_interacts_with) - chemical_substance - phenotypic_feature.

```
add_qnode(curie=DOID:14330, id=n00)
add_qnode(type=protein, is_set=true, id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n00, target_qnode_id=n01, virtual_relation_label=FET1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.001, remove_connected_nodes=t, qnode_id=n01)
add_qnode(type=chemical_substance, id=n02)
add_qedge(source_id=n01, target_id=n02, id=e01, type=physically_interacts_with)
expand(edge_id=e01, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n01, target_qnode_id=n02, virtual_relation_label=FET2)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.001, remove_connected_nodes=t, qnode_id=n02)
add_qnode(type=phenotypic_feature, id=n03)
add_qedge(source_id=n02, target_id=n03, id=e02)
expand(edge_id=e02, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n02, target_qnode_id=n03, virtual_relation_label=FET3)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.05, remove_connected_nodes=t, qnode_id=n03)
resultify()
```
More DSL programs for FET can be found [here](https://github.com/RTXteam/RTX/blob/eb674cfd9268b2859b8379015c5dac2bd0aa128b/code/ARAX/ARAXQuery/ARAX_query.py#L1016-L1103).

**Comment by dkoslicki** [comment]
Thanks @chunyuma! Closing
