### ISSUE TITLE
Additional node properties for standardization

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#80]
The [specification](https://docs.google.com/document/d/1TrvqJPe_HwmRJ5HCwZ7fsi9_mwGcwLOZ53Fnjo8Sh4E/edit#) notes these properties:
1. category [required]: A semantic type from the biolink model
2. description [optional]: Narrative text

I'm strongly in favor of including the description property as well.

@saramsey and @DeqingQu, will the node properties you're working on pulling include these?

NOTE BY SAR: Item (2) ("description") is now a separate issue, #81

**Comment by saramsey** [comment]
working on this now

**Comment by saramsey** [comment]
I am breaking out item (2) above to a separate issue (#81) since it is nontrivial; Item (1) is easy and I am doing it now.
