### ISSUE TITLE
result_graph is deprecated and should be removed

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#800]
In the beginning, every result had a result_graph, and it was good. We moved from result_graph to a knowledge_graph and a query_graph and node_bindings and edge_bindings with great trepidation. It was weird. We clung to result_graph in case we ever wanted to scamper back to safety.

But we have reached the point of #NoGoingBack

The result_graph is no longer used by the GUI or any known clients. All it does is bloat the ARAX output (very substantially sometimes).

The FIXME on line 265 of ARAX_resultify.py should be addressed to remove result_graph from the final output of resultify(). But it is not as simple as just fixing that line.

Step 1 is to fix the code. Ready whenever, no big rush, but soonish.

Step 2 is to remove result_graph from the YAML. Will wait a couple months until the dust settles on Step 1.

**Comment by amykglen** [comment]
Step 1 is done for Resultify in the `resultify` branch. (Resultify and its unittests no longer use/populate `result.result_graph`.)

But this can't be merged to `master` until #720 is done and merged. (I needed the changes made to Resultify in `issue720` for this issue, so pulled them into the `resultify` branch. But those can't be merged to master until that issue is complete.)

**Comment by edeutsch** [comment]
okay, @amykglen @dkoslicki I have the code in hand to address #720. I think. It seems to be right according to my testing so far. BUT, of course, it would break `master` because code there expects qedge_id not qedge_ids, etc.

Last time I tried to be clever and check it into overlay, but it seems that I caused more work for @dkoslicki by doing that.

I can check it into `master`, but then `master` will be broken. Which is okay for a short amount of time. It seems there are multiple branches out there that want or alternatively can't handle the schema change. How do we wrestle with this octopus? I'm open for suggestions. Where (i.e. what branch) should I commit the new Node and Edge classes?

**Comment by edeutsch** [comment]
... `master` is easiest for me if yunz can then swoop in and merge all these branches into `master` and we then see if the whole thing works..

**Comment by amykglen** [comment]
nice! I think branch `issue720` makes sense - that's where all the work done on 720 so far (for Expand, Resultify, Filter) has happened. 

I don't think master would be good quite yet because the Overlay/Filter changes for 720 haven't been completed yet, I believe (they're waiting on the new Node/Edge classes).

**Comment by edeutsch** [comment]
okay, unless there are objections, I will see if I can check them into the `issue720` branch.

**Comment by edeutsch** [comment]
okay, done. committed and pushed to `issue720`. It appears to work in brief tests. You'll take care of the rest? Let me know if there are issues with my changes. and let me know when `master` is all sync'ed up and I should `git pull` to /test and /beta for final testing.

**Comment by amykglen** [comment]
awesome - yep, it seems to be working well! no issues... and yes - will let you know once `master` is ready. thanks!

**Comment by amykglen** [comment]
confirmed these Resultify changes appear to be working as expected on /test (code runs smoothly and `result_graph` is now always null in the JSON response).

guess I should assign this to @edeutsch for Step 2?

**Comment by edeutsch** [comment]
Fixed long ago.. closing.
