### ISSUE TITLE
Make BTE Expand work with general qnodes (no type or curie)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#815]
BTE's `SingleEdgeQueryDispatcher` requires all qnodes to have a type (e.g., 'protein'), so a query like `(n00: DOID:14330)-->(n01)`, where n01 is general (no type), isn't currently possible with `kp=BTE` (Expand logs an error explaining that's not allowed).

But we could get around this limitation by doing multiple BTE queries behind the scenes for such a query - one for each possible node type.

Meaning, if the query was like this:
```
(n00: DOID:14330)-->(n01)
```

Behind the scenes, Expand could query BTE for:
```
(n00: DOID:14330)-->(n01: protein)
(n00: DOID:14330)-->(n01: chemical_substance)
(n00: DOID:14330)-->(n01: disease)
etc...
```
and aggregate the results.

**Comment by edeutsch** [comment]
Or maybe just use KGNodeIndex to look up the type? If the CURIE is in KG2, then the type is in KGNodeIndex only 10 ms away.

**Comment by amykglen** [comment]
hmm, no, in the situation I'm describing, there's no curie to use to look up a type. I meant DSL like this:
```
add_qnode(curie=DOID:14330, id=n00)
add_qnode(id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(kp=BTE)
```
where n01 has neither a type nor a curie.

**Comment by edeutsch** [comment]
ah, sorry, I misread. With the understanding that not all KPs can answer all types of questions, I would be content with just returning an error message that BTE can't do that. And we can write the QueryGraphInterpreter to know that if a connected query node has no type, then we need to direct the query to KG2 or something besides BTE. Or looping over all types is okay, too. although slow.

**Comment by amykglen** [comment]
ok cool, yeah, just returning an error message for this kind of query sounds good to me. maybe I'll put in a request with the BTE team to allow this kind of query, and then if/when they implement that we can update our system to not throw an error?

**Comment by amykglen** [comment]
closing since this isn't very important/is out of our hands (many external KPs won't accept category-less qnodes)
