### ISSUE TITLE
Firefox/Chrome difference

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#817]
The following resultset:

https://arax.rtx.ai/beta/?m=2282

Seems to work fine and nice under firefox.But on Chrome, the results go pear-shaped halfway down. Seen by both @amykglen and me on different OSes.

![image](https://user-images.githubusercontent.com/12707718/84468891-aaad9180-ac34-11ea-94cb-7806779b9e9a.png)

**Comment by isbluis** [comment]
Seems good now; please report back and/or close issue once verified.

**Comment by edeutsch** [comment]
`master` rolled out to /test and it seems to be working fine. This works for me fine now on Chrome:
https://arax.rtx.ai/test/?m=2282
