### ISSUE TITLE
ReasoningUtilities.py imports "neo4j.v1" which is from a very old version of neo4j-driver

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#818]
Here is a minimum working example of the problem:
```
cd /tmp
git clone https://github.com/RTXteam/RTX.git
cd RTX
python3 -m virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
cd code/reasoningtool/QuestionAnswering
python
import ReasoningUtilities
```
this gives the following error:
```
>>> import ReasoningUtilities
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/RTX/code/reasoningtool/QuestionAnswering/ReasoningUtilities.py", line 15, in <module>
    from neo4j.v1 import GraphDatabase, basic_auth
ModuleNotFoundError: No module named 'neo4j.v1'
>>>
```
My MWE has been tested on a 2018 15-inch MBP running 10.14.6, running Homebrew python 3.7.6.
I note that the following fixes the problem, albeit with a deprecation warning:
```
pip install neo4j-driver==1.7
python
import ReasoningUtilities
```
What does this all mean?  I think it means that our `requirements.txt` is inconsistent with `ReasoningUtilities.py`, i.e., I cannot test `test_ARAX_resultify.py` (which through `ARAX_query.py` depends on `ReasoningUtilities.py`) from a clean virtualenv install of our package dependencies using `RTX/requirements.txt`.

**Comment by saramsey** [comment]
We are going to fix this through #820

**Comment by saramsey** [comment]
see also #821

**Comment by dkoslicki** [comment]
Not relevant any more, closing
