### ISSUE TITLE
ValueError 'RTX' not in list, in fisher_exact.py

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#819]
This code in fisher_exact.py (lines 51--53)
```
pathlist = os.path.realpath(__file__).split(os.path.sep)
RTXindex = pathlist.index("RTX")
dbpath = os.path.sep.join([*pathlist[:(RTXindex+1)],'data','orangeboard'])
requests_cache.install_cache(dbpath)
```
added 17 days ago in commit 0dd7b5a6313c9ea955e7f3faf94edf2fb987c98a, introduces an unfortunate dependency on the existence of a directory named `RTX` in the path. This causes errors since I typically will rename checkout of the RTX code-base like this:
```
git clone -b foobranch https://github.com/RTXteam/RTX.git
mv RTX git-foobranch
```
to avoid traversing one level directory deeper each time I work with the code. I (perhaps reasonably) assumed that our code-base would only use *relative* path locations to find other RTX python modules, and thus in theory, it would never need to know the actual name of the top-level directory or depend on that directory's name being "RTX" (and always "RTX" in every case). Now, one could certainly argue mine was a poor choice of dev environment setup, but in any event, I thought we were done with using `requests_cache` (in favor of CacheControl) so can the above code be commented out?  Or can we perhaps just modify it as follows?
```
pathlist = os.path.realpath(__file__).split(os.path.sep)
RTXindex = pathlist.index("code")
dbpath = os.path.sep.join([*pathlist[:(RTXindex)],'data','orangeboard'])
```
(warning, my suggested remedy is untested!)

Or perhaps:
```
pathlist = os.path.realpath(__file__).split(os.path.sep)
RTXindex = pathlist[-3]
dbpath = os.path.sep.join([*pathlist[:(RTXindex)],'data','orangeboard'])
```
(again, untested, but you get the idea)

**Comment by chunyuma** [comment]
Actually, I added these few code lines to solve the issue #670. Since multiple scripts use `requests_cache` and locate at different folders. So it is laborious to use the common relative path for all these scripts. But I can do it if you want. Do we comment it out or modify it?

**Comment by saramsey** [comment]
Thank you @chunyuma. This is very helpful.

**Comment by saramsey** [comment]
On reflection, I think @chunyuma 's solution (as documented in #670) is the right way to go. So I am going to close out this issue.
