### ISSUE TITLE
Version specification for all requirements

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#820]
Pip freeze production when all tests passing, post the `requirements.txt` file and other installed modules here, then only bump versions when required and confirmed all tests passing.

**Comment by edeutsch** [comment]
root@1d9f9e25e40a:/# pip3 freeze
aiohttp==3.6.2
async-timeout==3.0.1
atomicwrites==1.3.0
attrs==19.3.0
backcall==0.1.0
beautifulsoup4==4.9.0
biothings-client==0.2.0
biothings-explorer==0.0.1
bleach==3.1.4
CacheControl==0.12.6
certifi==2019.3.9
chardet==3.0.4
Click==7.0
clickclick==1.2.2
connexion==2.6.0
contexter==0.1.4
cycler==0.10.0
decorator==4.4.0
defusedxml==0.6.0
entrypoints==0.3
fastobo==0.7.2
Flask==1.1.2
Flask-Cors==3.0.8
fpyutils==1.1.0
frozendict==1.2
graphviz==0.14
idna==2.8
importlib-metadata==1.6.0
inflection==0.3.1
ipykernel==5.2.1
ipython==7.4.0
ipython-cypher==0.2.6
ipython-genutils==0.2.0
ipywidgets==7.5.1
itsdangerous==1.1.0
jedi==0.13.3
Jinja2==2.10.1
joblib==0.15.1
jsonpath-rw==1.4.0
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==6.1.3
jupyter-console==6.1.0
jupyter-core==4.6.3
kiwisolver==1.2.0
lockfile==0.12.2
lxml==4.5.0
MarkupSafe==1.1.1
matplotlib==3.2.1
md-toc==7.0.1
mistune==0.8.4
more-itertools==8.2.0
msgpack==0.6.1
multidict==4.7.5
mygene==3.1.0
nanoset==0.1.3
nbconvert==5.6.1
nbformat==5.0.6
neo4j-driver==1.7.6
neo4jrestclient==2.1.1
neobolt==1.7.16
neotime==1.7.4
networkx==2.4
nltk==3.4.5
nose==1.3.7
notebook==5.7.5
numpy==1.18.2
openapi-spec-validator==0.2.6
packaging==20.3
pandas==1.0.3
pandocfilters==1.4.2
parso==0.4.0
pathlib==1.0.1
pexpect==4.7.0
pickleDB==0.9.2
pickleshare==0.7.5
pluggy==0.13.1
ply==3.11
prettytable==0.7.2
prometheus-client==0.7.1
prompt-toolkit==2.0.9
pronto==2.1.0
ptyprocess==0.6.0
py==1.8.1
pycrypto==2.6.1
Pygments==2.3.1
PyMySQL==0.9.3
pyparsing==2.4.7
pytest==5.4.1
python-dateutil==2.8.0
python-docx==0.8.10
pytz==2019.1
PyYAML==5.1
pyzmq==19.0.0
qtconsole==4.7.3
QtPy==1.9.0
requests==2.21.0
requests-cache==0.5.2
scikit-learn==0.22.2.post1
scipy==1.4.1
Send2Trash==1.5.0
simple-crypt==4.1.7
singledispatch==3.4.0.3
six==1.12.0
soupsieve==1.9.1
SQLAlchemy==1.3.15
swagger-ui-bundle==0.0.3
terminado==0.8.3
testpath==0.4.4
tomark==0.1.4
tornado==4.5.3
traitlets==4.3.2
urllib3==1.24.1
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.2
widgetsnbextension==3.5.1
yarl==1.4.2
zipp==3.1.0

**Comment by dkoslicki** [comment]
aiohttp==3.6.2
async-timeout==3.0.1
atomicwrites==1.4.0
attrs==19.3.0
backcall==0.2.0
beautifulsoup4==4.9.1
biothings-client==0.2.1
biothings-explorer @ git+https://github.com/biothings/biothings_explorer@b7be98589ea5e4dfee5a80b9cada88fdac128c81
bleach==3.1.5
CacheControl==0.12.6
certifi==2020.4.5.2
chardet==3.0.4
click==7.1.2
clickclick==1.2.2
connexion==2.7.0
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
fastobo==0.7.2
Flask==1.1.2
fpyutils==1.1.2
frozendict==1.2
graphviz==0.14
idna==2.9
importlib-metadata==1.6.1
inflection==0.5.0
ipykernel==5.3.0
ipython==7.15.0
ipython-cypher==0.2.6
ipython-genutils==0.2.0
ipywidgets==7.5.1
itsdangerous==1.1.0
jedi==0.17.0
Jinja2==2.11.2
joblib==0.15.1
jsonpath-rw==1.4.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.3
jupyter-console==6.1.0
jupyter-core==4.6.3
lockfile==0.12.2
lxml==4.5.1
MarkupSafe==1.1.1
md-toc==7.0.2
mistune==0.8.4
more-itertools==8.3.0
msgpack==1.0.0
multidict==4.7.6
mygene==3.1.0
nanoset==0.1.4
nbconvert==5.6.1
nbformat==5.0.7
neo4j-driver==1.7.0
neo4jrestclient==2.1.1
neobolt==1.7.17
neotime==1.7.4
networkx==2.4
nltk==3.5
nose==1.3.7
notebook==5.7.5
numpy==1.18.5
openapi-spec-validator==0.2.8
packaging==20.4
pandas==1.0.4
pandocfilters==1.4.2
parso==0.7.0
pexpect==4.8.0
pickleDB==0.9.2
pickleshare==0.7.5
pluggy==0.13.1
ply==3.11
prettytable==0.7.2
prometheus-client==0.8.0
prompt-toolkit==3.0.5
pronto==2.1.0
ptyprocess==0.6.0
py==1.8.1
pycrypto==2.6.1
Pygments==2.6.1
PyMySQL==0.9.3
pyparsing==2.4.7
pyrsistent==0.16.0
pytest==5.4.3
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
pyzmq==19.0.1
qtconsole==4.7.4
QtPy==1.9.0
regex==2020.6.8
requests==2.23.0
requests-cache==0.5.2
scikit-learn==0.22
scipy==1.4.1
Send2Trash==1.5.0
simple-crypt==4.1.7
six==1.15.0
soupsieve==2.0.1
SQLAlchemy==1.3.17
terminado==0.8.3
testpath==0.4.4
tomark==0.1.4
tornado==4.5.3
tqdm==4.46.1
traitlets==4.3.3
urllib3==1.25.9
wcwidth==0.2.4
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
yarl==1.4.2
zipp==3.1.0

**Comment by dkoslicki** [comment]
@dkoslicki to do diff and update `requirements.txt`

**Comment by amykglen** [comment]
fyi @dkoslicki - I think the commit you have for biothings-explorer is indeed a good one to use (b7be98589ea5e4dfee5a80b9cada88fdac128c81)
