### ISSUE TITLE
Consider moving from requests cache to cache control

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#822]
- [ ] use [this](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/kg-construction/cache_control_helper.py)
- [ ] change [this line](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/kg-construction/cache_control_helper.py#L32) so the cache goes to the data part
- [ ] update all code to use this instead of requests cache

**Comment by finnagin** [comment]
I believe we are no longer using requests cache anymore so I think this is safe to close.
