### ISSUE TITLE
Should add_qnode() be able to accept curies in BTE that aren't in KG2?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#826]
Right now, if one is constructing their query graph using DSL, they can't use `add_qnode` for a curie that isn't in KG2. But BTE contains many curies that aren't in KG2.

Should we adjust `add_qnode` to work in such situations? If so, I'm not sure how we could continue with the paradigm of using a KGNodeIndex for curie verification at that point, since we have no way of knowing all curies in BTE.

And on a related note, since synonyms are typically ultimately used for input curies, is it even a good idea to require that the exact input curie exists in the KP? Wouldn't we really want to know if it _or any of its synonyms_ exist in the KP?

(Maybe letting go of curie verification at the `add_qnode` step and moving it into`expand` would make sense? Since proper verification is dependent on some of `expand`'s parameters - `use_synonyms`, `kp`...?)

**Comment by edeutsch** [comment]
I think the answer to the title is yes, at least for now as we develop. I actually did that briefly late last night and then thought better of it.

But in light of a fresh day, I have now changed add_qnode() to complain with a warning when a curie is not in KG2 but it will not be an error. It it should be fine to proceed with any curies not in KG2.

Changes and all latest changed in`master` rolled out to /test and /beta
I tested with this DSL:
```
add_qnode(curie=[UniProtKB:P02675,UniProtKB:P01903,UniProtKB:I3WAC9,UniProtKB:P09601,UniProtKB:Q02878,UniProtKB:P01375,UniProtKB:Q9BXM7,UniProtKB:P05181,UniProtKB:P50914,UniProtKB:P62241,UniProtKB:O15217,UniProtKB:P09488,UniProtKB:P15559,UniProtKB:P06213,UniProtKB:Q13330,UniProtKB:P38646,UniProtKB:P05231,UniProtKB:Q9BRL8,UniProtKB:P01344,UniProtKB:Q99683,UniProtKB:P11717,UniProtKB:P01308,UniProtKB:P10635,UniProtKB:P23560,UniProtKB:Q01959,UniProtKB:P21728,UniProtKB:O60260,UniProtKB:Q9NQ11,UniProtKB:P21397,UniProtKB:P10636,UniProtKB:P08183,UniProtKB:P09211,UniProtKB:P04062,UniProtKB:P14416,UniProtKB:Q5S007,UniProtKB:Q99497,UniProtKB:P27338,UniProtKB:P37840,UniProtKB:P08069], is_set=true, id=n00)
add_qnode(type=chemical_substance, id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00, type=physically_interacts_with)
expand(edge_id=e00,kp=ARAX/KG1)
resultify()
filter_results(action=limit_number_of_results, max_results=50)
```
![image](https://user-images.githubusercontent.com/12707718/84684493-96e08480-aeed-11ea-9695-b72308ccdc13.png)

**Comment by amykglen** [comment]
nice! that sounds good... although when I run this DSL:
```
add_qnode(id=n00, curie=PR:001111)
add_qnode(id=n01, type=chemical_substance)
add_qedge(id=e00, source_id=n01, target_id=n00)
expand(kp=BTE)
```

I'm getting an error, I think because the qnode added to the query graph for n00 is missing its curie. this is the query graph Expand sees:
```
{'edges': [{'id': 'e00',
            'negated': None,
            'relation': None,
            'source_id': 'n01',
            'target_id': 'n00',
            'type': None}],
 'nodes': [{'curie': None, 'id': 'n00', 'is_set': None, 'type': None},
           {'curie': None,
            'id': 'n01',
            'is_set': None,
            'type': 'chemical_substance'}]}
```

**Comment by edeutsch** [comment]
oops, sorry, careless of me. I have fixed that I think.
I tried your DSL and it still did not work because BTE requires a type. But since KGNodeIndex can't find the CURIE, there's no type to be found.
I fixed it so that a user-specified type is passed through when curie not found, but this DSL doesn't work either:
```
add_qnode(id=n00, curie=PR:001111, type=protein)
add_qnode(id=n01, type=chemical_substance)
add_qedge(id=e00, source_id=n01, target_id=n00)
expand(kp=BTE)
```
But this looks like something you'll need to address.
Changes committed to `master` and rolled out to /test

**Comment by amykglen** [comment]
nice, looks good now, thanks!

(the "No paths were found in BTE satisfying this query graph" error it now results in is actually expected/desired - it shouldn't find any results because 'PR:001111' is a made up curie I was using for testing purposes. so no changes needed from me.)
