### ISSUE TITLE
Many essences from results do not map to entitites via /entity endpoint

### ISSUE THREAD

**Issue by isbluis** [RTXteam/RTX#828]
1. Query message:   https://arax.rtx.ai/index.html?m=2282

2. Go to Summary tab

3. Click on the "+A" (or B) next to the Essence column heading

4. Examine the items under the corresponding List as they get populated with Entity Type; notice that well over half of them are not successfully mapped ("Unknown"), even though they are listed with an Essence Type of "disease" in the Summary table.

Expected behavior is to map all essences to nodes of type "disease" (and perhaps to others, if term maps to multiple types).

**Comment by edeutsch** [comment]
yeah, the issue here is that the query used BioThingsExplorer (BTE), while /entity uses KG1 as its reference. This is a problem stemming from the fact that we have one foot in KG1 and the other foot in KG2. And the third foot in BTE.

I hope this problem will be partly solved by the new KGNodeIndex in development. Just for fun, I switched /entity to KG2 in /devED and ew ew ew.

We'll just leave it open for now and revisit after the new KGNodeIndex is ready.

**Comment by isbluis** [comment]
This is indeed "ew ew ew".  Can you please point /devED back to KG1?  (unless doing work on this, of course...)  Thanks!

**Comment by edeutsch** [comment]
done. back to KG1

**Comment by isbluis** [comment]
Another aspect within this issue is that sometimes the essence contains extra information that breaks the mapping.  For example, if you paste the (new) Example DSL and POST it, you get 32 Results with the following Summary (portion) :

![image](https://user-images.githubusercontent.com/37852256/86417358-94b64e00-bc81-11ea-9350-40dffbf403c4.png)


If you then Click on the "[+A]" (or B), none of the items map to entities due to the extra protein/gene name in parenthesis (e.g. "(CP3A4)" in the first row:

![image](https://user-images.githubusercontent.com/37852256/86417163-0e9a0780-bc81-11ea-8d8c-bfa764067d5c.png)


Perhaps having an extra column for the short name (or removing it altogether) from the Summary might be better?

![image](https://user-images.githubusercontent.com/37852256/86417238-4739e100-bc81-11ea-8bee-2f11a06ba151.png)

**Comment by edeutsch** [comment]
closing ancient history
