### ISSUE TITLE
Improperly populated node_attributes

### ISSUE THREAD

**Issue by isbluis** [RTXteam/RTX#829]
Using this example:  https://arax.rtx.ai/index.html?m=2362
Examine node information for _UniProtKB:P09601_ within the _json_ message; find that:
1.  The `node_attributes` with the name of `publications` and `synonym` are arrays with an **empty** first element  ("")
2. Since there are multiple entries, should the name be pluralized for "`synonym`" ?
3. Some of the information under `synonym `is incorrect, as one of the entries is the protein sequence, and even contains control characters (**\n**; see SEQUENCE, below).  Full values are:
```
            "name": "synonym",
            "type": null,
            "url": null,
            "value": [
              "",
              "Short=HO-1;",
              "HMOX1",
              "SEQUENCE   288 AA;  32819 MW;  AB47827778694064 CRC64;\nMERPQPDSMP QDLSEALKEA TKEVHTQAEN AEFMRNFQKG QVTRDGFKLV MASLYHIYVA\nLEEEIERNKE SPVFAPVYFP EELHRKAALE QDLAFWYGPR WQEVIPYTPA MQRYVKRLHE\nVGRTEPELLV AHAYTRYLGD LSGGQVLKKI AQKALDLPSS GEGLAFFTFP NIASATKFKQ\nLYRSRMNSLE MTPAVRQRVI EEAKTAFLLN IQLFEELQEL LTHDTKDQSP SRAPGLRQRA\nSNKVQDSAPV ETPRGKPPLN TRSQAPLLRW VLTLSFLVAT VAVGLYAM\n",
              "EC=1.14.14.18 {ECO:0000250|UniProtKB:O48782};"
            ]

```

4. Also, the `description` for this entry seems like it could be cleaned up and/or normalized:
`
        "description": "-!- FUNCTION: Heme oxygenase cleaves the heme ring at the alpha    methene bridge to form biliverdin. Biliverdin is subsequently    converted to bilirubin by biliverdin reductase. Under    physiological conditions, the activity of heme oxygenase is    highest in the spleen, where senescent erythrocytes are    sequestrated and destroyed. Exhibits cytoprotective effects since    excess of free heme sensitizes cells to undergo apoptosis.-!- CATALYTIC ACTIVITY:    Reaction=heme b + 3 O2 + 3 reduced [NADPH--hemoprotein reductase]      = biliverdin IXalpha + CO + Fe(2+) + H(+) + 3 H2O + 3 oxidized      [NADPH--hemoprotein reductase]; Xref=Rhea:RHEA:21764, Rhea:RHEA-      COMP:11964, Rhea:RHEA-COMP:11965, ChEBI:CHEBI:15377,      ChEBI:CHEBI:15378, ChEBI:CHEBI:15379, ChEBI:CHEBI:17245,      ChEBI:CHEBI:29033, ChEBI:CHEBI:57618, ChEBI:CHEBI:57991,      ChEBI:CHEBI:58210, ChEBI:CHEBI:60344; EC=1.14.14.18;      Evidence={ECO:0000250|UniProtKB:O48782};-!- INTERACTION:    Q9NUX5:POT1; NbExp=2; IntAct=EBI-2806151, EBI-752420;-!- SUBCELLULAR LOCATION: Microsome {ECO:0000269|PubMed:22419571}.    Endoplasmic reticulum membrane {ECO:0000269|PubMed:22419571};    Peripheral membrane protein {ECO:0000269|PubMed:22419571};    Cytoplasmic side {ECO:0000269|PubMed:22419571}.-!- TISSUE SPECIFICITY: Expressed at higher levels in renal cancer    tissue than in normal tissue (at protein level).    {ECO:0000269|PubMed:20855888}.-!- INDUCTION: Heme oxygenase 1 activity is highly inducible by its    substrate heme and by various non-heme substances such as heavy    metals, bromobenzene, endotoxin, oxidizing agents and UVA.-!- DISEASE: Heme oxygenase 1 deficiency (HMOX1D) [MIM:614034]: A    disease characterized by impaired stress hematopoiesis, resulting    in marked erythrocyte fragmentation and intravascular hemolysis,    coagulation abnormalities, endothelial damage, and iron deposition    in renal and hepatic tissues. Clinical features include persistent    hemolytic anemia, asplenia, nephritis, generalized erythematous    rash, growth retardation and hepatomegaly.    {ECO:0000269|PubMed:9884342}. Note=The disease is caused by    mutations affecting the gene represented in this entry.-!- SIMILARITY: Belongs to the heme oxygenase family. {ECO:0000305}.-!- WEB RESOURCE: Name=SeattleSNPs;    URL=\"http://pga.gs.washington.edu/data/hmox1/\";",
`

**Comment by amykglen** [comment]
Tagging this with `kg2` as these are issues present within KG2 itself, so probably makes sense to fix them there (vs. in `expand`)

Also worth noting: I think half of 1. was addressed in #755 (for `publications` -- but not `synonym`), and is just awaiting incorporation into the next KG2 build.

**Comment by saramsey** [comment]
Regarding point (2) you are correct!  However, the singular `synonym` seems to be Biolink model standard:
https://biolink.github.io/biolink-model/docs/synonym.html

**Comment by saramsey** [comment]
As for (3), I believe I have fixed this in the code (see #755). I will leave this issue open in order to remind me to verify that it is fixed in the next full KG2 build (probably a week out).

**Comment by saramsey** [comment]
As for (4), yes, that is a bug. I will log it as a separate issue and cross-reference it here.

**Comment by isbluis** [comment]
Great, thank you @saramsey !

**Comment by saramsey** [comment]
Seems to be fixed on `kg2endpoint.rtx.ai:7474`.

<img width="805" alt="Screen Shot 2020-07-21 at 3 24 21 PM" src="https://user-images.githubusercontent.com/5562107/88113283-51574d00-cb66-11ea-8689-d4f161f7512b.png">

**Comment by saramsey** [comment]
As for the structured comments in the Description field, I understand that in the ideal these would be parsed out into structured knowledge. But until we have the capability to do that in an automated fashion, I am inclined to think that it is better to keep the structured comments as they have valuable information about metabolic reactions, etc.?
