### ISSUE TITLE
extended_info_json information missing for at least some chemical_substance nodes, and huge generally

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#83]
Note from Steve:  I may have created this bug by implementing the code changes needed for #80. 

Example Cypher query:

     match (n:chemical_substance) where n.name="acetaminophen" return n

**Comment by DeqingQu** [comment]
I executed 'UpdateNodesInfo.py' again and all nodes have the 'extended_info_json' field now. 

Chrome crash problem:
For chemical_substance nodes, it is fine to query one node at once in Chrome.
Example Cyper query:
    match (n:chemical_substance{name:'seratrodast'}) return n
But if we query multiple nodes at once, Chrome will crash.
Example Cyper query:
    match (n:chemical_substance) return n

One possible reason is the size of chemical_substance node is too big (about 150K for each node). Though it is fine to query any numbers of chemical_substance nodes by neo4j-python-driver, it cost too much time (5 seconds for each node). We need to filter the 'extend_json_info' field for chemical_substance nodes.

**Comment by saramsey** [comment]
we may need to filter the JSON object for chemical_substance because in general the object is too big; it is making the Neo4j web UI very slow.  Steve and Deqing to work on this.

**Comment by dkoslicki** [comment]
We've decided to not include this info pre-hackathon, so closing this issue.
