### ISSUE TITLE
Extraneous intermediate nodes in results produced by Resultify

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#833]
In this query: https://arax.rtx.ai/test/?m=2388 (DSL below), which goes like: 
```
(chemical_substance)--(protein)--(biological_process)--(protein)--(disease)
```
it seems each result includes a bunch of extraneous intermediate nodes, that are 'dead ends' (in that they aren't connected all the way through to the final disease):

<img width="1072" alt="Screen Shot 2020-06-16 at 7 43 09 PM" src="https://user-images.githubusercontent.com/49423686/84849334-e87e3180-b009-11ea-8363-d37d6429279b.png">

In this particular result for example, I would think the only `biological_process` nodes should be the two connected to the protein 'adrenoceptor alpha 1A' (which is the only protein connected to the final disease). (That or edges are missing from this result...)

```
add_qnode(id=n00, curie=CHEMBL.COMPOUND:CHEMBL521, type=chemical_substance)
add_qnode(id=n01, type=protein, is_set=true)
add_qedge(id=e00, source_id=n00, target_id=n01)
expand(edge_id=e00, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n00, target_qnode_id=n01, virtual_relation_label=FET1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n01)
add_qnode(type=biological_process, id=n02, is_set=true)
add_qedge(source_id=n01, target_id=n02, id=e01)
expand(edge_id=e01, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n01, target_qnode_id=n02, virtual_relation_label=FET2)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n02)
add_qnode(type=protein, id=n03, is_set=true)
add_qedge(source_id=n02, target_id=n03, id=e02)
expand(edge_id=e02, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n02, target_qnode_id=n03, virtual_relation_label=FET3)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n03)
add_qnode(type=disease, id=n04)
add_qedge(source_id=n03, target_id=n04, id=e03)
expand(edge_id=e03, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n03, target_qnode_id=n04, virtual_relation_label=FET4)
resultify()
```

**Comment by chunyuma** [comment]
Another bug seems like the color of the virtual edges and the real edges. Based on my understanding, the green edges should represent the real edges and the purple edges should be the virtual edges. However, except for the first hop, the edges in the second, third and fourth hops are all purple. They seem to mix together.

**Comment by isbluis** [comment]
Hi @chunyuma .  The edges are colored according to their declared `type` as follows:
```
"contraindicated_for"       => "red"
"indicated_for"             => "green"
"physically_interacts_with" => "green"
all others                  => "#aaf"

```
It can be changed easily if there is a preference or consensus, so let me know.

**Comment by chunyuma** [comment]
@isbluis, I see. Thanks!

**Comment by chunyuma** [comment]
@amykglen, I think I might know why some of edges are missing from the result. It's probably due to this command line 
```
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n03)
```
This might remove some of edges connecting between `n02` (biological_process) and `n03` (protein) due to the fisher exact test p-value not satisfying <0.01 and also remove `n03` but remain `n02` because the edges `e01` connected to `n02` are significant (satisfying <0.01).

**Comment by amykglen** [comment]
thanks @chunyuma - I'm thinking that's probably not causing this though because `resultify` is called _after_ all that filtering is done - so if those edges aren't in the KG, `resultify` wouldn't be trying to create results including them (from `resultify`'s perspective, it doesn't know those ever existed).

I think I understand what's causing the issue in the `resultify` code (just a bug in its algorithm when it's figuring out which of the `is_set=true` nodes to include in each result for 3-hop or greater queries).

**Comment by chunyuma** [comment]
> so if those edges aren't in the KG, resultify wouldn't be trying to create results including them 

@amykglen, I'm a little bit confused about this. In the case that some edges have ever existed but are filtered out by `filter_kg`, does the `resultify ` not generate any results or just generate results without them? Based on the above results, `resultify ` indeed created the final results but just excluded those filtered edges. Perhaps you're right that this should be the issue from the `resultify` code. But I just want to figure out what the `resultify ` will do if the `filter_kg` removes some edges and causes some 'dead ends'.

**Comment by amykglen** [comment]
yeah - resultify still generates results when some edges have been filtered out, and it's built to handle dead-ends in the knowledge graph like those created when these edges are removed.

**Comment by chunyuma** [comment]
@amykglen, so how does it handle dead-ends? Does it remove those dead-ends in the knowledge graph?

**Comment by amykglen** [comment]
no, resultify doesn't alter the knowledge graph at all. it just knows to ignore dead ends when it's creating results (it scans the knowledge graph looking for possible paths that satisfy the query graph; and since dead ends inherently can't be part of a path that fulfills the entire query graph, they will never be included in a result).

but I'm not sure that the filter step would actually end up causing 'dead-ends' in the knowledge graph - it depends on how filter is implemented: perhaps it is designed to clean up 'dead-ends' as it goes. but whether it does so is irrelevant for resultify's functioning.

**Comment by chunyuma** [comment]
@amykglen, I see. Thanks! 

Sorry, I have one more question. I just checked a result from terminal and found a problem.

So here is the query graph:
```
{'edges': [{'id': 'e00',
            'negated': None,
            'relation': None,
            'source_id': 'n00',
            'target_id': 'n01',
            'type': None},
           {'id': 'e01',
            'negated': None,
            'relation': None,
            'source_id': 'n01',
            'target_id': 'n02',
            'type': None}],
 'nodes': [{'curie': 'DOID:14330',
            'id': 'n00',
            'is_set': None,
            'type': 'disease'},
           {'curie': None, 'id': 'n01', 'is_set': True, 'type': 'protein'},
           {'curie': None,
            'id': 'n02',
            'is_set': None,
            'type': 'chemical_substance'}]}
```

Here is one of the results:
```
[{'confidence': 1.0,
 'description': 'No description available',
 'edge_bindings': [{'kg_id': 'UniProtKB:P10636--gene_associated_with_condition--DOID:14330',
                    'qg_id': 'e00'},
                   {'kg_id': 'CHEMBL.COMPOUND:CHEMBL128988--physically_interacts_with--UniProtKB:P10636',
                    'qg_id': 'e01'},
                   {'kg_id': 'UniProtKB:P10636--physically_interacts_with--CHEMBL.COMPOUND:CHEMBL128988',
                    'qg_id': 'e01'}],
 'essence': 'frentizole',
 'essence_type': 'chemical_substance',
 'id': 'https://arax.rtx.ai/api/rtx/v1/result/10883',
 'node_bindings': [{'kg_id': 'DOID:14330', 'qg_id': 'n00'},
                   {'kg_id': 'CHEMBL.COMPOUND:CHEMBL128988', 'qg_id': 'n02'},
                   {'kg_id': 'UniProtKB:P10636', 'qg_id': 'n01'}],
 'reasoner_id': 'ARAX',
 'result_graph': None,
 'result_group': None,
 'result_group_similarity_score': None,
 'result_type': 'individual query answer',
 'row_data': ['1.0', 'frentizole', 'chemical_substance'],
 'score': None,
 'score_direction': None,
 'score_name': None}]
``` 
I found that the id link `https://arax.rtx.ai/api/rtx/v1/result/10883` contains the content which doesn't match to the result. For example, in this case, the id link shows the content of `CHEMBL.COMPOUND:CHEMBL112` and `UniProtKB:P23219`. But the result is about `CHEMBL.COMPOUND:CHEMBL128988` and `UniProtKB:P10636`

**Comment by saramsey** [comment]
> Another bug seems like the color of the virtual edges and the real edges. Based on my understanding, the green edges should represent the real edges and the purple edges should be the virtual edges. However, except for the first hop, the edges in the second, third and fourth hops are all purple. They seem to mix together.

I suggest this might be best reported as a separate issue

**Comment by saramsey** [comment]
> I found that the id link `https://arax.rtx.ai/api/rtx/v1/result/10883` contains the content which doesn't match to the result. For example, in this case, the id link shows the content of `CHEMBL.COMPOUND:CHEMBL112` and `UniProtKB:P23219`. But the result is about `CHEMBL.COMPOUND:CHEMBL128988` and `UniProtKB:P10636`

If the URL `https://arax.rtx.ai/api/rtx/v1/result/10883` is pulling back JSON that doesn't match the result that was returned from `ARAX_resultify`, how certain are we that this is a resultify issue? Suggesting that this may be best logged as a separate issue unless there is evidence that the "result stored on the server does not match the result returned directly from resultify" issue is connected to the "extraneous nodes" issue.

**Comment by amykglen** [comment]
agree [the URL problem](https://github.com/RTXteam/RTX/issues/833#issuecomment-645528642) should probably be logged elsewhere - I don't think that is a `resultify` issue, since `resultify` doesn't populate that field, as far as I know (not sure where that's done).

**Comment by chunyuma** [comment]
> > Another bug seems like the color of the virtual edges and the real edges. Based on my understanding, the green edges should represent the real edges and the purple edges should be the virtual edges. However, except for the first hop, the edges in the second, third and fourth hops are all purple. They seem to mix together.
> 
> I suggest this might be best reported as a separate issue

@saramsey, I don't know if this should be reported as an issue because @isbluis defined the color based on the type of edge. So if this is what we should define, then it should be fine.

**Comment by amykglen** [comment]
strangely, I haven't been able to reproduce this problem locally in `master`.

when I run this DSL in `/test`, it produces 440 results, which do contain extraneous intermediate nodes https://arax.rtx.ai/test/?m=2393 :
```
add_qnode(id=n00, curie=CHEMBL.COMPOUND:CHEMBL521, type=chemical_substance)
add_qnode(id=n01, type=protein, is_set=true)
add_qedge(id=e00, source_id=n00, target_id=n01)
expand(edge_id=e00, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n00, target_qnode_id=n01, virtual_relation_label=FET1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n01)
add_qnode(type=biological_process, id=n02, is_set=true)
add_qedge(source_id=n01, target_id=n02, id=e01)
expand(edge_id=e01, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n01, target_qnode_id=n02, virtual_relation_label=FET2)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n02)
add_qnode(type=protein, id=n03)
add_qedge(source_id=n02, target_id=n03, id=e02)
expand(edge_id=e02, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n02, target_qnode_id=n03, virtual_relation_label=FET3)
resultify()
```
but when I run the exact same DSL in `master` via the command line, it produces 154 results, none of which seem to have extraneous intermediate nodes.

yet I'm pretty sure nothing has been pushed to `master` for `resultify` since it was last rolled out to `/test`. so I guess this must somehow be changes to other module(s) trickling down?

in any case, I suppose maybe we should roll out `master` to `/test` and/or `/beta` and then I can do some investigation to see if this seems to still be an issue...

**Comment by edeutsch** [comment]
Hi, I have just rolled out the latest `master` to /test and /beta (not production). Quite some changes:
```
Fast-forward
 code/ARAX/ARAXQuery/ARAX_expander.py             |   71 +++---
 code/ARAX/ARAXQuery/ARAX_overlay.py              |    7 +-
 code/ARAX/ARAXQuery/ARAX_query.py                |   48 +++-
 code/ARAX/ARAXQuery/ARAX_resultify_testcases.py  | 1246 -------------------------------------------------------------------------------------------------
 code/ARAX/ARAXQuery/Expand/bte_querier.py        |   65 +++---
 code/ARAX/ARAXQuery/Expand/expand_utilities.py   |   35 ++-
 code/ARAX/ARAXQuery/Expand/kg_querier.py         |  146 ++++++------
 code/ARAX/ARAXQuery/Overlay/fisher_exact_test.py |  613 ++++++++++++++++++++++++++++++++++++++----------
 code/ARAX/test/test_ARAX_expand.py               |    7 +-
 code/kg2/chembl_mysql_to_kg_json.py              |   25 +-
 10 files changed, 724 insertions(+), 1539 deletions(-)
 delete mode 100644 code/ARAX/ARAXQuery/ARAX_resultify_testcases.py
```

**Comment by amykglen** [comment]
thanks @edeutsch, that was very helpful.

the example I was using indeed no longer produces this issue, but I found a different one - narrowed it down to this MWE (https://arax.rtx.ai/test/?m=2406):
```
add_qnode(id=n00, curie=CHEMBL.COMPOUND:CHEMBL521, type=chemical_substance)
add_qnode(id=n01, type=protein, is_set=true)
add_qedge(id=e00, source_id=n00, target_id=n01)
expand(edge_id=e00, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n00, target_qnode_id=n01, virtual_relation_label=FET1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n01)
add_qnode(type=biological_process, id=n02, is_set=true)
add_qedge(source_id=n01, target_id=n02, id=e01)
expand(edge_id=e01, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n01, target_qnode_id=n02, virtual_relation_label=FET2)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n02)
add_qnode(type=protein, id=n03, is_set=true)
add_qedge(source_id=n02, target_id=n03, id=e02)
expand(edge_id=e02, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n02, target_qnode_id=n03, virtual_relation_label=FET3)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n03)
add_qnode(type=disease, id=n04, curie=DOID:14067)
add_qedge(source_id=n03, target_id=n04, id=e03)
expand(edge_id=e03, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n03, target_qnode_id=n04, virtual_relation_label=FET4)
resultify()
filter_results(action=limit_number_of_results, max_results=200)
```

I added a test case for this to `test_ARAX_resultify.py` in the `resultify` branch (test_issue833).

**Comment by amykglen** [comment]
this has been fixed and merged into master - `test_issue833` is passing, as well as all other tests in `test_ARAX_resultify.py`.

for the record: I repurposed a pruning algorithm I use in Expand to address this. addition to running time is negligible (~0.00005 seconds per result).

**Comment by amykglen** [comment]
looks good on `/test`! https://arax.rtx.ai/test/?m=2421

<img width="1095" alt="Screen Shot 2020-06-19 at 2 44 49 PM" src="https://user-images.githubusercontent.com/49423686/85181744-89076800-b23b-11ea-9867-0ebe7a72e389.png">

**Comment by dkoslicki** [comment]
@amykglen 
Found an example where nodes are in the KG that are not in the results, due to the calling of the filter command after `resultify()`
```
expand(edge_id=e00, kp=ARAX/KG2, continue_if_no_results=true)
expand(edge_id=e00, kp=BTE, continue_if_no_results=true)
overlay(action=overlay_clinical_info, observed_expected_ratio=true)
overlay(action=predict_drug_treats_disease)
filter_kg(action=remove_edges_by_attribute, edge_attribute=probability_treats, direction=below, threshold=0.75, remove_connected_nodes=true, qnode_id=n01)
overlay(action=compute_ngd)
resultify(ignore_edge_direction=true)
filter_results(action=limit_number_of_results, max_results=50)
```
Only has 50 results, none of which are PIRENZEPINE DIHYDROCHLORIDE, but this node does show up in the KG. This was actually helpful for me in diagnosing another issue, but I see that for other commands, such as:
```
add_qnode(name=DOID:14330, id=n00)
add_qnode(type=protein, is_set=true, id=n01)
add_qnode(type=chemical_substance, id=n02)
add_qedge(source_id=n00, target_id=n01, id=e00)
add_qedge(source_id=n01, target_id=n02, id=e01, type=molecularly_interacts_with)
expand(edge_id=[e00,e01], kp=ARAX/KG2)
overlay(action=compute_jaccard, start_node_id=n00, intermediate_node_id=n01, end_node_id=n02, virtual_relation_label=J1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=jaccard_index, direction=below, threshold=.008, remove_connected_nodes=t, qnode_id=n02)
resultify(ignore_edge_direction=true)
filter_results(action=sort_by_edge_attribute, edge_attribute=jaccard_index, direction=descending, max_results=15)
```
even though only 15 results are being asked for, the system stalls out in storing the message since the KG (which apparently has *everything* and not just the nodes/edges for the 15 results) has 1858 nodes and 13405 edges in it.

Should we pull this out as a separate issue, or do you think it's related to this one?

**Comment by amykglen** [comment]
@dkoslicki - I think you're thinking of issue #874/#912 rather than this one. and in that issue, it was my understanding that the group decided the knowledge graph shouldn't be 'cleaned up' after `filter_results`. but even if we did want that (I tend to think it _would_ be good to do), it couldn't be `resultify` that performs that cleaning of the KG, since `filter_results` is called after `resultify`. it'd have to be `filter_results` itself or some other final 'cleaning' code (perhaps that's automatically called at the very end of execution).

**Comment by dkoslicki** [comment]
Thanks for the clarification and reminder @amykglen (and yes, I think I put this in the wrong issue). Agreed about having `filter_results` do the final cleaning if we ever decide to do it (remains to be seen how frequently the "storing message" delay becomes a pain point and I will open an issue if/when that happens).
