### ISSUE TITLE
reach out to text-mining provider team to ascertain the state of their service

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#834]

**Comment by dkoslicki** [comment]
@finnagin 
Specifically ask:
- [ ] What kind of information does their KP provide?
- [ ] Are they reasoner Std API format compliant? (i.e. do they accept and/or receive this format?)
- [ ] What is their API endpoint?

**Comment by finnagin** [comment]
Heard back from Bill from the text mining provider:

Hi Finn,

Larry forwarded me your questions. Thanks for reaching out. See our responses below:

**What is your api endpoint?**

Our contribution for the July 9th integration goal is going to take the form of two KGs using the KGX TSV format. If there is time we will attempt to stand up a Reasoner Std API endpoint, but that won't be ready for at least another week. I'm hoping to have our KGX files ready by the Thursday architecture zoom call.

**What kinds of information does the text mining provider provide?**

The Text Mining KP will provide two knowledge graphs:
1. One will contain assertions between pairs of ontology concepts that have been mined from the biomedical literature. Our proposal stated that we would tune the text-mined KG to the needs of the Translator community. After speaking with some of the ARAs at the Relay, we have prioritized the following initial targets for the text-mined KG:

  * `chemical regulates gene`
  * `gene regulates gene`
  * `chemical treats disease`
  * `gene to disease association`

Work is underway to build tools to extract these four associations. Each is represented as a GitHub issue. Please feel free to submit requests (as GitHub issues) for new concepts and/or associations if there are others that would benefit the Expander Agent.

2. The second knowledge graph consists of a cooccurrence network where the nodes are ontology concepts and links between nodes indicate that the two concepts cooccur in the same sentence, and that these concepts cooccur together more often than by chance.

For the July 9th integration we will have sample KGs of each variety available (KGX format later this week and hopefully a Reasoner Std API to follow).
* The text-mined KG will contain assertions mined from manual annotation of the CRAFT corpus. Specific relation types may be different from the four initial targets listed above.
* The cooccurrence network is comprised of data from ~40k documents from the CORD19 corpus (this is a COVID19-specific collection of scientific papers) and makes use of ontology concept from 10 of the Open Biomedical Ontologies. The list of ontologies is available here.

**Are you reasoner Std API format compliant? (i.e. do you accept and/or receive this format?)**

See answer to your first question above. No, we are not compliant currently, but hope to be. Initial release for the July 9th integration effort will take the form of KGX TSV files.

Hope that answers your questions. Please let me know if not. I will let you know when the KGX files have been posted. 

We are looking forward to working with you as well!

Best,
Bill
