### ISSUE TITLE
the URL in the message.result pulled back a JSON that doesn't match the result that was returned from ARAXQuery

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#836]
Hi all, I found an issue that the URL in the `message.result` pulled back a JSON that doesn't match the result that was returned from ARAXQuery. One example is as follows:

So here is the query graph:
```
{'edges': [{'id': 'e00',
            'negated': None,
            'relation': None,
            'source_id': 'n00',
            'target_id': 'n01',
            'type': None},
           {'id': 'e01',
            'negated': None,
            'relation': None,
            'source_id': 'n01',
            'target_id': 'n02',
            'type': None}],
 'nodes': [{'curie': 'DOID:14330',
            'id': 'n00',
            'is_set': None,
            'type': 'disease'},
           {'curie': None, 'id': 'n01', 'is_set': True, 'type': 'protein'},
           {'curie': None,
            'id': 'n02',
            'is_set': None,
            'type': 'chemical_substance'}]}
```

Here is one of the results:
```
[{'confidence': 1.0,
 'description': 'No description available',
 'edge_bindings': [{'kg_id': 'UniProtKB:P10636--gene_associated_with_condition--DOID:14330',
                    'qg_id': 'e00'},
                   {'kg_id': 'CHEMBL.COMPOUND:CHEMBL128988--physically_interacts_with--UniProtKB:P10636',
                    'qg_id': 'e01'},
                   {'kg_id': 'UniProtKB:P10636--physically_interacts_with--CHEMBL.COMPOUND:CHEMBL128988',
                    'qg_id': 'e01'}],
 'essence': 'frentizole',
 'essence_type': 'chemical_substance',
 'id': 'https://arax.rtx.ai/api/rtx/v1/result/10883',
 'node_bindings': [{'kg_id': 'DOID:14330', 'qg_id': 'n00'},
                   {'kg_id': 'CHEMBL.COMPOUND:CHEMBL128988', 'qg_id': 'n02'},
                   {'kg_id': 'UniProtKB:P10636', 'qg_id': 'n01'}],
 'reasoner_id': 'ARAX',
 'result_graph': None,
 'result_group': None,
 'result_group_similarity_score': None,
 'result_type': 'individual query answer',
 'row_data': ['1.0', 'frentizole', 'chemical_substance'],
 'score': None,
 'score_direction': None,
 'score_name': None}]
``` 
I found that the id link `https://arax.rtx.ai/api/rtx/v1/result/10883` contains the content which doesn't match the result. For example, in this case, the id link shows the content about `CHEMBL.COMPOUND:CHEMBL112` and `UniProtKB:P23219`. But the result is about `CHEMBL.COMPOUND:CHEMBL128988` and `UniProtKB:P10636`

**Comment by dkoslicki** [comment]
@edeutsch I only just now saw this issue. Appears to be a problem with the RTXFeedback mechanism given the improper result ID. Do you mind looking into this?

**Comment by edeutsch** [comment]
Sure, I can look into it. BUT, this mechanism is slated to be removed completely. Are you using it somehow? When I get around to it, I was planning on completely removing result ids and removing the mechanism to fetch them. This will speed things up and reduce code complexity.

So, I'm surprised you noticed. Are you using this mechanism? Should I not blow it away?

**Comment by dkoslicki** [comment]
@edeutsch I personally am not using it (except for the extremely rare case of when I want to do a demo that takes too long, so I pull an old result id for an NCATS presentation). I just brought your attention to it since @chunyuma noticed it.

Note **importantly** I/we definitely do use the result id's for constructs like the following:
```
sys.path.append(os.path.dirname(os.path.abspath(__file__))+"/../../UI/Feedback")
from RTXFeedback import RTXFeedback
araxdb = RTXFeedback()
message_dict = araxdb.getMessage(1234) #<----- Pull an old result
<do some analysis on this result>
```
For local dev purposes.

Will this mechanism no longer work if you choose to remove the result id's? Or does that only affect the API JSON response, and not actually the RTXFeedback database?

**Comment by edeutsch** [comment]
message ids will certainly not go away. and that is what you're referring to in your most recent post. The original post is about result ids, which are not really used. One message contain multiple results.

**Comment by dkoslicki** [comment]
@edeutsch ah, I misunderstood; thanks for clarifying!

**Comment by edeutsch** [comment]
closing ancient history. 2020 was not a good year.
