### ISSUE TITLE
Some nodes have no edges

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#84]
eg:
```cypher
match (n:disease{name:"OMIM:145270"}) return n
match p=(n:disease{name:"OMIM:145270"})-[]-() return p
match (n) where not (n)--() return n limit 5
match (n) where not (n)--() return count(n)
```
In total, there are 3,593 such disconnected nodes. All of them are shown as expanded.

**Comment by dkoslicki** [comment]
This is true for both ``http://rtxdev.saramsey.org:7674`` and ``http://rtx.ncats.io:7474/browser/``

**Comment by saramsey** [comment]
Why is this a bug?

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Apr 20, 2018, at 3:37 PM, David Koslicki <notifications@github.com<mailto:notifications@github.com>> wrote:


eg:

match (n:disease{name:"OMIM:145270"}) return n
match p=(n:disease{name:"OMIM:145270"})-[]-() return p
match (n) where not (n)--() return n limit 5
match (n) where not (n)--() return count(n)


In total, there are 3,593 such disconnected nodes. All of them are shown as expanded.

**Comment by saramsey** [comment]
OK thanks for elaborating. Yes I agree this should be checked.

**Comment by saramsey** [comment]
Testing has confirmed that at least for OMIM, this does not appear to be a bug.  I tested 10 of these OMIM nodes at random, and none of them returns a result from the method QueryOMIM.disease_mim_to_gene_symbols_and_uniprot_ids().

Switching this to LOWPRI and ENHANCEMENT

**Comment by saramsey** [comment]
absent any evidence that BioNetExpander is not performing as designed, I'm closing this issue; happy to re-open later if it comes to light that these orphan nodes are causing issues with reasoning
