### ISSUE TITLE
For filter_kg(action=remove_edges_by_attribute), can we not filter out a node with multiple qnode ids?

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#846]
Hi @finnagin , @amykglen and @dkoslicki , I know that if we use `qnode_id` in `filter_kg(action=remove_edges_by_attribute)` to specify a query node id to remove, it will remove all nodes with qnode id connected to the edges which don't satisfy the specified filtering criteria. However, is it possible not to filter out a node with multiple qnode ids?

Here is a case that we can consider. Let say we're interested in finding the significant(FET p-value<0.001) paths: (DOID:14330) — (phenotypic_feature) — (disease) by using the following DSL.

```
add_qnode(curie=DOID:14330,id=n00,type=disease)
add_qnode(type=phenotypic_feature,is_set=true,id=n01)
add_qedge(source_id=n00,target_id=n01,id=e00,type=has_phenotype)
expand(edge_id=e00,kp=ARAX/KG1)
overlay(action=fisher_exact_test,source_qnode_id=n00,target_qnode_id=n01,virtual_relation_label=FET1,rel_edge_id=e00)
filter_kg(action=remove_edges_by_attribute,edge_attribute=fisher_exact_test_p-value,direction=above,threshold=0.001,remove_connected_nodes=t,qnode_id=n01)
add_qnode(type=disease,id=n02)
add_qedge(source_id=n01,target_id=n02,id=e01,type=has_phenotype)
expand(edge_id=e01,kp=ARAX/KG1)
overlay(action=fisher_exact_test,source_qnode_id=n01,target_qnode_id=n02,virtual_relation_label=FET2,rel_edge_id=e01)
filter_kg(action=remove_edges_by_attribute,edge_attribute=fisher_exact_test_p-value,direction=above,threshold=0.001,remove_connected_nodes=t,qnode_id=n02)
resultify()
```

 In this case, `DOID:14330` should have two qnode ids `n00` and `n02`.  Since `DOID:14330` significantly connects to certain `phenotypic_feature` nodes in the first hop but the `phenotypic_feature` node doesn't significantly connect to `DOID:14330` in the second hop. Please see [here](https://arax.rtx.ai/test/?m=2451).

![Screen Shot 2020-06-20 at 5 55 18 PM](https://user-images.githubusercontent.com/20031672/85212281-559e0980-b31f-11ea-8e1d-719ce341b10c.png)

Therefore, if we use 
```
filter_kg(action=remove_edges_by_attribute,edge_attribute=fisher_exact_test_p-value,direction=above,threshold=0.001,remove_connected_nodes=t,qnode_id=n02)
```
it will filter out `DOID:14330` even though `DOID:14330` is also `n00`.  This causes an error saying `the node binding list does not cover all nodes in the query graph` in the `resultify` step. I think one solution to this issue is to just remove `n02` from the qnode ids of `DOID:14330`.

**Comment by finnagin** [comment]
@chunyuma I should be able to implement this so that it works this way.

**Comment by chunyuma** [comment]
thanks @finnagin, this is reasonable.

**Comment by saramsey** [comment]
nice summary of the issue, @chunyuma

**Comment by saramsey** [comment]
finn working on implementing this; expects this to take a week unless preempted by the 7/8 demo/selftest thing with ARAX/ARS

**Comment by finnagin** [comment]
@finnagin Reminder that this needs to be addressed

**Comment by dkoslicki** [comment]
@finnagin this appears to be an old one, but it has the “need to test on production”. Can you please do so and report back if this should be closed or if more needs to be done?

**Comment by finnagin** [comment]
Closing as this has been working for some time now
