### ISSUE TITLE
Make expand throw an error for qedges with no curies involved

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#847]
Forking this from #845. From @edeutsch:

> But it also seems to me that we don't want to let expand do an expand step where neither end has a curie? I mean it's okay if the query_graph has no curie specified, but if other expansion doesn't narrow it down, then it probably shouldn't be permitted?
> 
> e.g., a query graph of:
> n01(type=protein)--[e01]--n02(type=disease)
> shouldn't cause expand to expand this whole thing out, should it? I mean it could, but we wouldn't want to let it, would we?

From me:

> I can't really think of someone wanting to do such a query... maybe there's a tiny chance someone might want to once we have the ability to expand on only certain provided by's... e.g., 'give me all the (chemical_substance)-[contraindicated_for]-(disease) triples you know about from MyChem.info'?

**Comment by edeutsch** [comment]
My opinion: ARAX is not the right tool for your last query you describe above. If someone wants long lists of thousands of things (a data dump), better to go straight to MyChem.info or ChEMBL directly. ARAX is for getting a small list of complex logic chains spanning resources for examination.

**Comment by amykglen** [comment]
yeah. sounds good to me! I'll adjust it to prohibit such queries.

**Comment by amykglen** [comment]
to put this requirement another way: we're saying that every incoming query graph sent to ARAX must have at least one QNode with a curie.

**Comment by amykglen** [comment]
changes for this are in `master`, with all tests passing; need to test once `master` is next rolled out.

**Comment by edeutsch** [comment]
`master` is now rolled out to /test

**Comment by amykglen** [comment]
thanks - verified it's working on test with:
```
add_qnode(id=n00, type=protein)
add_qnode(id=n01, type=chemical_substance)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand()
```
https://arax.rtx.ai/test/
