### ISSUE TITLE
(Zhang Xu)Update QueryCOHD.py

### ISSUE THREAD

**Issue by zihangxuspace** [RTXteam/RTX#848]
with new api_base_url and new endpoint/temporal/sourceToTarget

**Comment by dkoslicki** [comment]
@zihangxuspace just making sure you saw my comments and requests on [the PR](https://github.com/RTXteam/RTX/pull/849).

**Comment by finnagin** [comment]
@dkoslicki I noticed the PR for this is still open. Is this still relevant?

**Comment by dkoslicki** [comment]
Nope, closing!
