### ISSUE TITLE
check that these diseases are in our KG

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#85]
amyotrophic lateral sclerosis
Schimke immuno-osseous dysplasia 
Spinocerebellar ataxia with neuropathy type 1 
Fanconi Anemia
asthma
a disorder of sterol metabolism regulating behavior and neural development
infertility
endometrial cancer
lung cancer
Primary Ciliary Dyskinesia
premature birth
congenital heart disease
LCHAD deficiency
VLCAD deficiency
hepatoxicity
Deficiency of N-glycanase 1

**Comment by finnagin** [comment]
So, if these are the exact strings that should be in the node name I checked using the following cypher command: `match(n) where n.name in ["amyotrophic lateral sclerosis","Schimke immuno-osseous dysplasia","Spinocerebellar ataxia with neuropathy type 1","Fanconi Anemia","asthma","a disorder of sterol metabolism regulating behavior and neural development","infertility","endometrial cancer","lung cancer","Primary Ciliary Dyskinesia","premature birth","congenital heart disease","LCHAD deficiency","VLCAD deficiency","hepatoxicity","Deficiency of N-glycanase 1"] return n.name, n.id limit 50;`. 
This returned the following 5 results:


n.name | n.id
-- | --
"infertility" | "DOID:5223"
"congenital heart disease" | "DOID:1682"
"endometrial cancer" | "DOID:1380"
"asthma" | "DOID:2841"
"amyotrophic lateral sclerosis" | "DOID:332"

**Comment by dkoslicki** [comment]
A few more (using ``ParseQuestion.py``):

|   disease  |  id    |
|------------ | ------------|
|amyotrophic lateral sclerosis | DOID:332|
|Fanconi anemia | DOID:13636|
|asthma | DOID:2841|
|infertility | DOID:5223|
|endometrial cancer | DOID:1380|
|lung cancer | OMIM:211980|
|Primary Ciliary Dyskinesia | DOID:9562|
|premature birth | HP:0001622|
|congenital heart disease | DOID:1682|


So it looks like we need:

- Schimke immuno-osseous dysplasia
- Spinocerebellar ataxia with neuropathy type 1
- a disorder of sterol metabolism regulating behavior and neural development
- LCHAD deficiency
- VLCAD deficiency
- hepatoxicity
- Deficiency of N-glycanase 1

**Comment by saramsey** [comment]
thanks @dkoslicki  and also I agree with the priority label

**Comment by saramsey** [comment]
@finnagin can you please get DOIDs for these diseases, by manually searching in Monarch or in disease-ontology.org or in EBI OLS?

- Schimke immuno-osseous dysplasia
- Spinocerebellar ataxia with neuropathy type 1
- a disorder of sterol metabolism regulating behavior and neural development
- LCHAD deficiency
- VLCAD deficiency
- hepatoxicity
- Deficiency of N-glycanase 1

if you post the DOIDs here I will add them to seed_nodes.tsv

**Comment by finnagin** [comment]
@saramsey Here are the disorders I mentioned in my email:

Name | ID
-----|-----
Desmosterolosis |OMIM:602398
CK syndrome|OMIM:300831
CHILD syndrome|OMIM:308050

**Comment by finnagin** [comment]
Here are the remaining sterol metabolism disorders (that have DOID/OMIM ids) I mentioned:

Name|ID
----|----
Greenberg dysplasia |OMIM:215140
Lathosterolosis |OMIM:607330
MEND syndrome |OMIM:300960
Smith-Lemli-Opitz syndrome |DOID:14692
X-linked chondrodysplasia punctata |DOID:0060292
mevalonic aciduria |DOID:0050452
Hyperimmunoglobulinemia d with periodic fever |OMIM:260920
cerebrotendinous xanthomatosis|DOID:4810
microcephaly-congenital cataract-psoriasiform dermatitis syndrome|OMIM:616834

**Comment by saramsey** [comment]
@DeqingQu can you please add these diseases to seed_nodes.tsv ?  File has a simple TSV format with Unix line termination.  Thank you.

**Comment by DeqingQu** [comment]
Done!

**Comment by saramsey** [comment]
verified all of these (except the "TBD" items) are in seed_nodes.tsv

**Comment by dkoslicki** [comment]
@jlmcclelland The bioentities in these comments should be relevant for your investigations.
