### ISSUE TITLE
Implement ICEES+ "Overlay KG" endpoint as a feature to ARAXi `overlay()`

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#851]
After a discussion with Kara, Hao, Steve, and @meghasin, we discovered that ICEES+ has the following endpoint:

https://icees.renci.org:16340/apidocs/#/default/post_knowledge_graph_overlay

That accepts ReasonerStdAPI queries such as:
```
{
       "message": {
           "query_graph": {
               "nodes": [
                   {
                       "node_id": "n00",
                       "curie": "PUBCHEM:2083",
                       "type": "drug"
                   },
                   {
                       "node_id": "n01",
                       "curie": "PUBCHEM:281",
                       "type": "chemical_substance"
                   }  
               ],
               "edges": [
                   {
                       "id": "e00",
                       "type": "association",
                       "source_id": "n00",
                       "target_id": "n01"
                   }
               ]
           }
       }
   }

```

The current CURIES that they "know" about are listed [here](https://github.com/NCATS-Tangerine/icees-api/blob/api/config/identifiers.yml), and is quite limited, but the ICEES team plans to move to utilizing the SRI node normalizer to allow more curies to be available.

I propose we implement/create this as `overlay(action=overlay_exposures_data)` (options and naming TBD) by:
- [x] writing a super thin API wrapper in `/ARAX/ARAXquery/Overlay/ICEES.py` (as the above endpoint accepts ReasonerStdAPI) that will take the message KG, send it to the above endpoint, and:
    - [x] add the returned edges to the message KG
    - [x] and/or decorate the existing message KG edges with the returned edge attributes
- [x] add `overlay_exposures_data` capability to `/ARAX/ARAXquery/ARAX_overlay.py` that calls out to `/ARAX/ARAXquery/Overlay/ICEES.py`
- [ ] document what this does (i.e. so the (DSL_Documentation.md)[https://github.com/RTXteam/RTX/blob/master/code/ARAX/Documentation/DSL_Documentation.md] is updated to reflect this new capability). See [this document](https://docs.google.com/document/d/1Vcpp6ehoq_Ba4NmdRkpSGnWfACfDo4owYqC10hQlE2I/edit?usp=sharing) for more details on ICEES+ ReasonerStd API compliant endpoints.
- [x] add an ICEES specific example (i.e. that will result in a message KG that have CURIES that ICEES can handle) in the `test/test_ARAX_overlay.py` file

Here's the relevant portion:
Overlay KG:
- input parameters:
    - query_options:
        - table: ICEES table
        - year: ICEES year
        - cohort_features: features for defining the cohort
        [Will make table, year, cohort optional, with default being all available years of data for all available patients]
        - maximum_p_value: ICEES maximum P value. The P value is calculated for each ICEES feature in the table that maps to a node in the knowledge_graph, using the pairwise contingency table where the rows are values of one feature and the columns are individual values of that feature. Any feature with P value greater than maximum_p_value is filtered out.
        - regex: filter target node name by regex
        - knowledge_graph
- output:
        - a knowledge_graph with additional edges for P value less than the maximum_p_value
- url: https://icees.renci.org:16340/apidocs/#/default/post_knowledge_graph_overlay
[eventually, endpoint will accept SRI-normalized identifiers]

**Comment by dkoslicki** [comment]
From Kara Fecho:
Here's some info on the overlay query, as well as two example queries:
Overlay KG:
input parameters:
query_options:
table: ICEES table
year: ICEES year
cohort_features: features for defining the cohort
[Will make table, year, cohort optional, with default being all available years of data for all available patients]
maximum_p_value: ICEES maximum P value. The P value is calculated for each ICEES feature in the table that maps to a node in the knowledge_graph, using the pairwise contingency table where the rows are values of one feature and the columns are individual values of that feature. Any feature with P value greater than maximum_p_value is filtered out.
regex: filter target node name by regex
knowledge_graph
output:
a knowledge_graph with additional edges for P value less than the maximum_p_value
url: https://icees.renci.org:16340/apidocs/#/default/post_knowledge_graph_overlay
Example 1: [eventually, endpoint will accept SRI-normalized identifiers]
```
{
       "message": {
           "query_graph": {
               "nodes": [
                   {
                       "node_id": "n00",
                       "curie": "PUBCHEM:2083",
                       "type": "drug"
                   },
                   {
                       "node_id": "n01",
                       "curie": "PUBCHEM:281",
                       "type": "chemical_substance"
                   }  
               ],
               "edges": [
                   {
                       "id": "e00",
                       "type": "association",
                       "source_id": "n00",
                       "target_id": "n01"
                   }
               ]
           }
       }
   }
```
Example 2:
```
{
       "message": {
           "query_graph": {
               "nodes": [
                   {
                       "node_id": "n00",
                       "curie": "PUBCHEM:5865",
                       "type": "drug"
                   },
                   {
                       "node_id": "n01",
                       "curie": "MESH:D052638",
                       "type": "chemical_substance"
                   }  
               ],
               "edges": [
                   {
                       "id": "e00",
                       "type": "association",
                       "source_id": "n00",
                       "target_id": "n01"
                   }
               ]
           }
       }
   }
```
Example 3:
```
{
       "message": {
           "query_graph": {
               "nodes": [
                   {
                       "node_id": "n00",
                       "curie": "PUBCHEM:5865",
                       "type": "drug"
                   },
                   {
                       "node_id": "n01",
                       "curie": "MONDO:0004766",
                       "type": "disease"
                   }  
               ],
               "edges": [
                   {
                       "id": "e00",
                       "type": "association",
                       "source_id": "n00",
                       "target_id": "n01"
                   }
               ]
           }
       }
   }
```
A relatively complete list of ICEES+ identifiers can be found here: https://github.com/NCATS-Tangerine/icees-api/blob/master/docs/ICEES_Identifiers_v8%2001.28.20.xlsx.

**Comment by dkoslicki** [comment]
Couple more updates about change in ICEES+ API changes:
Hao Xu says:
>
i have to change query_graph to knowledge_graph in the queries. So the examples look like:

Example 1:
```
{
       "message": {
           "knowledge_graph": {
               "nodes": [
                   {
                       "node_id": "n00",
                       "curie": "PUBCHEM:2083",
                       "type": "drug"
                   },
                   {
                       "node_id": "n01",
                       "curie": "PUBCHEM:281",
                       "type": "chemical_substance"
                   }  
               ],
               "edges": [
                   {
                       "id": "e00",
                       "type": "association",
                       "source_id": "n00",
                       "target_id": "n01"
                   }
               ]
           }
       }
   }
```
Example 2:
```
{
       "message": {
           "knowledge_graph": {
               "nodes": [
                   {
                       "node_id": "n00",
                       "curie": "PUBCHEM:5865",
                       "type": "drug"
                   },
                   {
                       "node_id": "n01",
                       "curie": "MESH:D052638",
                       "type": "chemical_substance"
                   }  
               ],
               "edges": [
                   {
                       "id": "e00",
                       "type": "association",
                       "source_id": "n00",
                       "target_id": "n01"
                   }
               ]
           }
       }
   }
```
Example 3:
```
{
       "message": {
           "knowledge_graph": {
               "nodes": [
                   {
                       "node_id": "n00",
                       "curie": "PUBCHEM:5865",
                       "type": "drug"
                   },
                   {
                       "node_id": "n01",
                       "curie": "MONDO:0004766",
                       "type": "disease"
                   }  
               ],
               "edges": [
                   {
                       "id": "e00",
                       "type": "association",
                       "source_id": "n00",
                       "target_id": "n01"
                   }
               ]
           }
       }
   }
```
Relevant to PR #881 and @MayankMurali

**Comment by amykglen** [comment]
pushed a bit more work on this today - as a summary of what I've done so far in the `issue851` branch:

- I started by adding an `overlay_exposures_data` action and corresponding `overlay_exposures_data.py`
  - it's currently set up to query ICEES edge-by-edge (though still needs to be plugged into Query_ICEES.py once that's ready) - not sure how the edge-by-edge approach will go performance-wise. I think it would be possible to do batch queries if needed, though may be a little tricky in that it seems ICEES will return an error if it doesn't know about every single curie in the `knowledge_graph` it's sent (perhaps their yaml file would come in handy here if we need to go down this route?)
  - it currently adds the exposures data in `EdgeAttribute`s that it tacks onto existing message KG edges (haven't yet implemented a 'virtual edge' method) - the exact format of these `EdgeAttribute`s still needs to be refined (the `EdgeAttribute`s in ICEES' response aren't really in the format we use. example: `
            {
              "src_feature": "AlopeciaDx",
              "tgt_feature": "AvgDailyAcetaldehydeExposure_2",
              "p_value": 0.000003790881671012495
            }`)
- I added the beginnings of a `test_overlay_exposures_data` to `test_ARAX_overlay.py`, but still need to find a query that results in a KG with curies ICEES can handle :) (bringing `NodeSynonymizer` into the picture will help here I think..)

many unresolved bits and pieces still, but figuring the next most pressing thing is probably to start using the `NodeSynonymizer` in `overlay_exposures_data.py` to try to find curies ICEES likes...

**Comment by dkoslicki** [comment]
Talked with Hao Xu, and he noted that examples 1 and 3 work for him (but 2 timed out).
eg. 
`
curl -X POST "https://icees.renci.org:16340/knowledge_graph_overlay" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{       \"message\": {           \"knowledge_graph\": {               \"nodes\": [                   {                       \"node_id\": \"n00\",                       \"curie\": \"PUBCHEM:2083\",                       \"type\": \"drug\"                   },                   {                       \"node_id\": \"n01\",                       \"curie\": \"PUBCHEM:281\",                       \"type\": \"chemical_substance\"                   }                 ],               \"edges\": [                   {                       \"id\": \"e00\",                       \"type\": \"association\",                       \"source_id\": \"n00\",                       \"target_id\": \"n01\"                   }               ]           }       }   }" -k
`
does return a valid response. Relevant to PR #881

**Comment by amykglen** [comment]
ah, ok - yep, examples 1 and 3 are working for me. thanks!

**Comment by dkoslicki** [comment]
New update from Kara:
>@David Koslicki (Expander Agent): Hao made a few optimization updates and deployed the one-hop endpoint over the weekend: https://icees.renci.org:16340/apidocs/#/default/post_knowledge_graph_one_hop. Just an FYI...

**Comment by amykglen** [comment]
summary of where this issue is at: 

- it is currently working in the `issue851` branch (though some enhancements are needed)
- you can try it out with `pytest -v test_ARAX_overlay.py -k test_overlay_exposures_data`

limitations:

1. it is currently _very_ slow, because it sequentially queries the ICEES+ API for all possible combinations of equivalent curies (for each relevant edge in the KG).  (curies using prefixes ICEES+ doesn't accept are excluded.)
2. it's quite difficult to find pairs of curies it can provide data on due to the limited curies ICEES+ currently 'knows' about
3. only the 'attribute' method is currently implemented (no 'virtual edge' method yet)

to address 1., one idea is to load their [yaml file](https://github.com/NCATS-Tangerine/icees-api/blob/api/config/identifiers.yml) of curies they 'know' about, and only send queries for edges that use such curies (or, more precisely, that use a curie equivalent to one of those according to the `NodeSynonymizer`). a downside to this is that their yaml file could change at any point.

but there are likely many ways to address speed issues (e.g., requesting batch querying, creating our own local ICEES+ database, etc..) not sure of the best path here.

**Comment by dkoslicki** [comment]
Awesome!
@amykglen +1 to loading the yaml file on the fly and don't bother hitting their API for the CURIES not on that list.

Also, am I correct in assuming you've made the edge attribute `icees_p-value`? When doing the virtual edge version (which will actually be pretty vital for other reasons), we could go with relationship type `has_icees_p-value_with`

**Comment by amykglen** [comment]
cool! I pushed some changes so that it now loads the yaml file on the fly, and that has helped _greatly_ with speed problems. 

I also added the virtual edge method (using `has_icees_p-value_with` as the edge type). can be tested with: `pytest -v test_ARAX_overlay.py -k test_overlay_exposures_data_virtual`.

(still need to do some final refinements/testing, but just an fyi that those two things are done.)

**Comment by amykglen** [comment]
@dkoslicki - alright, I'm all done here - just merged `issue851` into `master`. the two pytests I added are:
```
test_overlay_exposures_data_virtual
test_overlay_exposures_data_attribute
```
here's an example of a virtual edge `OverlayExposuresData` adds to the KG:
```
{'confidence': None,
 'defined_datetime': None,
 'edge_attributes': [{'name': 'icees_p-value',
                      'type': 'EDAM:data_1669',
                      'url': None,
                      'value': 0.0009711358570489683}],
 'evidence_type': None,
 'id': 'ICEES:CHEBI:8382--MESH:D052638',
 'is_defined_by': 'ARAX',
 'negated': None,
 'provided_by': 'ICEES+',
 'publications': None,
 'qedge_ids': ['E1'],
 'qualifiers': None,
 'relation': 'E1',
 'source_id': 'CHEBI:8382',
 'target_id': 'MESH:D052638',
 'type': 'has_icees_p-value_with',
 'weight': None}
```


there's one oddity worth noting that both @meghasin and I find curious: ICEES+ sometimes returns many p-values for one edge. for example, sending this query (one of the examples given to us) to their `/knowledge_graph_overlay`:
```
{
  "message": {
    "knowledge_graph": {
      "edges": [
        {
          "id": "icees_e00",
          "source_id": "PUBCHEM:5865",
          "target_id": "MESH:D052638",
          "type": "association"
        }
      ],
      "nodes": [
        {
          "curie": "PUBCHEM:5865",
          "id": "PUBCHEM:5865"
        },
        {
          "curie": "MESH:D052638",
          "id": "MESH:D052638"
        }
      ]
    }
  }
}
```
produces a response in which the edge between `PUBCHEM:5865` and `MESH:D052638` has a whole lot of p-values:
```
{
               "id":"PUBCHEM:5865_MESH:D052638",
               "type":"association",
               "source_id":"PUBCHEM:5865",
               "target_id":"MESH:D052638",
               "edge_attributes":[
                  {
                     "src_feature":"Prednisone",
                     "tgt_feature":"AvgDailyPM2.5Exposure",
                     "p_value":4.225918003362247e-25
                  },
                  {
                     "src_feature":"Prednisone",
                     "tgt_feature":"AvgDailyPM2.5Exposure_2",
                     "p_value":0
                  },
                  {
                     "src_feature":"Prednisone",
                     "tgt_feature":"AvgDailyPM2.5Exposure_2_qcut",
                     "p_value":6.460656288342073e-146
                  },
                  {
                     "src_feature":"Prednisone",
                     "tgt_feature":"AvgDailyPM2.5Exposure_StudyAvg",
                     "p_value":4.225918003362247e-25
                  },
                  {
                     "src_feature":"Prednisone",
                     "tgt_feature":"AvgDailyPM2.5Exposure_StudyAvg_qcut",
                     "p_value":6.866255427309808e-35
                  },
                  {
                     "src_feature":"Prednisone",
                     "tgt_feature":"AvgDailyPM2.5Exposure_StudyMax",
                     "p_value":2.536717151417826e-17
                  },
                  {
                     "src_feature":"Prednisone",
                     "tgt_feature":"AvgDailyPM2.5Exposure_StudyMax_qcut",
                     "p_value":1.0629178156053257e-32
                  },
                  {
                     "src_feature":"Prednisone",
                     "tgt_feature":"AvgDailyPM2.5Exposure_qcut",
                     "p_value":6.866255427309808e-35
                  },
                  {
                     "src_feature":"Prednisone",
                     "tgt_feature":"MaxDailyPM2.5Exposure",
                     "p_value":2.4978460385671823e-9
                  },
                  {
                     "src_feature":"Prednisone",
                     "tgt_feature":"MaxDailyPM2.5Exposure_StudyAvg",
                     "p_value":9.215155320280546e-7
                  },
                  {
                     "src_feature":"Prednisone",
                     "tgt_feature":"MaxDailyPM2.5Exposure_StudyAvg_qcut",
                     "p_value":1.201043213825863e-25
                  },
                  {
                     "src_feature":"Prednisone",
                     "tgt_feature":"MaxDailyPM2.5Exposure_StudyMax",
                     "p_value":2.4978460385671823e-9
                  },
                  {
                     "src_feature":"Prednisone",
                     "tgt_feature":"MaxDailyPM2.5Exposure_StudyMax_qcut",
                     "p_value":0.006797487743730713
                  },
                  {
                     "src_feature":"Prednisone",
                     "tgt_feature":"MaxDailyPM2.5Exposure_qcut",
                     "p_value":0.006797487743730713
                  }
               ]
            }
```
@meghasin and I discussed this a bit and are not totally sure what's going on/if that's intended. currently, I just take the average of the returned p-values and use that to decorate the KG, but perhaps this is worth asking the ICEES team about?

**Comment by amykglen** [comment]
ok, I've tested this out on `/test`, and it seems to be running smoothly, with the exception of the issue I wrote up in #1008. closing
