### ISSUE TITLE
Is Neo4j v4.0 python bolt driver faster?

### ISSUE THREAD

**Issue by ericawood** [RTXteam/RTX#853]

**Comment by ericawood** [comment]
If anyone has any queries that you would like me to run for this test, that would be great. Thank you!

**Comment by saramsey** [comment]
thank you @ericawood

**Comment by dkoslicki** [comment]
Related to #824 in that it will provide data for cost benefit analysis

**Comment by amykglen** [comment]
here are a few test queries (typical of those `expand` would do):

`
MATCH (n01:protein)-[e00]-(n00) WHERE n00.id in ['CUI:C0865475', 'MEDLINEPLUS:85', 'ICD10:G20', 'CUI:C1399358', 'NCI_NCI-GLOSS:CDR0000044140', 'MEDDRA:10061536', 'CUI:C0030567', 'SNOMEDCT:49049000', 'NCI_KEGG:C38845', 'MESH:D010300', 'LNC:MTHU020807', 'CUI:C0865474', 'ICD10CM:G20', 'DOID:14330', 'CHV:0000009319', 'CUI:C0865476', 'MEDCIN:32004', 'EFO:0002508', 'MONDO:0005180', 'CUI:C1521736', 'NCIT:C26845', 'LNC:LA27533-1', 'NANDA-I:03003'] WITH collect(distinct n01) as nodes_n01, collect(distinct n00) as nodes_n00, collect(distinct e00{.*, id:ID(e00), n01:n01.id, n00:n00.id}) as edges_e00 RETURN nodes_n01, nodes_n00, edges_e00
`

`
MATCH (n01:protein)-[e01:molecularly_interacts_with]-(n02:chemical_substance) WHERE n01.id in ['CUI:C0078939', 'CUI:C0085151', 'CUI:C0017789', 'CUI:C0004359', 'CUI:C0003316', 'CUI:C0003320', 'CUI:C0243046', 'CUI:C0019628', 'CUI:C0019932', 'CUI:C0061355', 'CUI:C0060916', 'CUI:C0074358', 'CUI:C0033164', 'CUI:C0012512', 'CUI:C0012177', 'CUI:C0052201', 'CUI:C0301713', 'CUI:C1305923', 'CUI:C0384782', 'CUI:C4042483', 'CUI:C0597298', 'CUI:C0072074', 'CUI:C0021699', 'CUI:C1440666', 'CUI:C0052199', 'CUI:C0047557', 'CUI:C1440058', 'CUI:C1441012', 'CUI:C1257945', 'CUI:C0214599', 'CUI:C0143060', 'CUI:C0021054', 'CUI:C0061596', 'CUI:C0673913', 'CUI:C0058505', 'CUI:C1136161', 'CUI:C0961505', 'CUI:C0071924', 'CUI:C0138515', 'CUI:C0815040', 'CUI:C0259080', 'CUI:C1564139', 'CUI:C0051874', 'CUI:C0913947', 'CUI:C0246490', 'CUI:C0297429', 'CUI:C1510464', 'CUI:C1512488', 'NCIT:C90119', 'NCIT:C90313', 'NCIT:C78156', 'CUI:C0475316', 'CUI:C0312561', 'UniProtKB:P10635', 'UniProtKB:P05181', 'UniProtKB:P21397', 'UniProtKB:P27338', 'UniProtKB:Q9NQ11', 'UniProtKB:P23560', 'UniProtKB:P38646', 'UniProtKB:O15217', 'UniProtKB:P09488', 'UniProtKB:P09211', 'UniProtKB:P01903', 'UniProtKB:P21728', 'UniProtKB:P14416', 'UniProtKB:P02675', 'UniProtKB:P04062', 'UniProtKB:P09601', 'UniProtKB:P08069', 'UniProtKB:P01344', 'UniProtKB:P05231', 'UniProtKB:P06213', 'UniProtKB:P01308', 'UniProtKB:Q5S007', 'UniProtKB:Q99683', 'UniProtKB:P08183', 'UniProtKB:P11717', 'UniProtKB:Q13330', 'UniProtKB:P15559', 'UniProtKB:Q99497', 'UniProtKB:Q9BXM7', 'UniProtKB:O60260', 'UniProtKB:P50914', 'UniProtKB:Q02878', 'UniProtKB:P62241', 'UniProtKB:Q01959', 'UniProtKB:P37840', 'UniProtKB:P10636', 'UniProtKB:P01375', 'UniProtKB:Q9BRL8', 'UniProtKB:I3WAC9'] WITH collect(distinct n01) as nodes_n01, collect(distinct n02) as nodes_n02, collect(distinct e01{.*, id:ID(e01), n01:n01.id, n02:n02.id}) as edges_e01 RETURN nodes_n01, nodes_n02, edges_e01
`

`
MATCH (n00)-[e00]-(n01) WHERE n00.id in ['OMIM:MTHU050182', 'NCI_NCI-GLOSS:CDR0000044911', 'LNC:MTHU040702', 'MEDDRA:10012594', 'LNC:LP128793-9', 'CUI:C0011847', 'LNC:LA10529-8', 'CHV:0000003834', 'MEDLINEPLUS:4'] AND n01.id in ['OMIM:MTHU012088', 'HP:0001993', 'CUI:C0220982', 'SNOMEDCT:56051008', 'CHV:0000021247', 'MEDDRA:10023379'] WITH collect(distinct n00) as nodes_n00, collect(distinct n01) as nodes_n01, collect(distinct e00{.*, id:ID(e00), n00:n00.id, n01:n01.id}) as edges_e00 RETURN nodes_n00, nodes_n01, edges_e00
`

**Comment by ericawood** [comment]
@saramsey: I know @finnagin proposed testing this in a docker container. Would it work to run the v3.x test on kg2endpoint (since it is already set up) and the v4 test on kg2erica?

**Comment by chunyuma** [comment]
@ericawood, here are a few more queries for you to test

__Path__:  (DOID:14330)-[]-(protein)-[]-(chemical_substance)-[]-(phenotypic_feature)
```
match (n00:disease {id:'DOID:14330'})-[]-(n01:protein)-[]-(n02:chemical_substance)-[]-(n03:phenotypic_feature)
with collect(distinct n03.id) as id_03
match (n0)-[]-(n1:chemical_substance)
where n0.id in id_03
with n0.id as n03_curie, collect(distinct n1.id) as n1_id
return n03_curie, size(n1_id) as num_of_all_drugs_connected_to_n03
```

__Path__:  (CHEMBL.COMPOUND:CHEMBL521)-[]-(protein)-[]-(biological_process)-[]-(protein)-[]-(disease)
```
match (n00:chemical_substance {id:'CHEMBL.COMPOUND:CHEMBL521'})-[]-(n01:protein)-[]-(n02:biological_process)-[]-(n03:protein)-[]-(n04:disease)
with collect(distinct n04.id) as id_04
match (n0)-[]-(n1:protein)
where n0.id in id_04
with n0.id as diseases, collect(distinct n1.id) as n1_id
return diseases, n1_id as list_of_all_connected_proteins_in_KG2
```

__Path__:  (DOID:14330)-[has_phenotype]-(phenotypic_feature)-[has_phenotype]-(disease)-[]-(protein)-[]-(pathway)
```
match (n00:disease {id:'DOID:14330'})-[:has_phenotype]-(n01:phenotypic_feature)-[:has_phenotype]-(n02:disease)-[]-(n03:protein)-[]-(n04:pathway)
with collect(distinct n04.id) as id_04
match (n0)-[]-(n1:protein)
where n0.id in id_04
with n0.id as pathways, collect(distinct n1.id) as n1_id
return pathways, size(n1_id) as num_of_all_connected_proteins_in_KG2
```

**Comment by ericawood** [comment]
Data from v4.0.6 Test: (query number refers to the order that the queries were posted)
Starting query  1  at  2020-06-25 17:33:01
Finished query  1  at  2020-06-25 17:33:13
Starting query  2  at  2020-06-25 17:33:13
Finished query  2  at  2020-06-25 17:33:15
Starting query  3  at  2020-06-25 17:33:15
Finished query  3  at  2020-06-25 17:33:27
Starting query  4  at  2020-06-25 17:33:27
Finished query  4  at  2020-06-25 17:34:45
Starting query  5  at  2020-06-25 17:34:45
Finished query  5  at  2020-06-25 17:35:48
Starting query  6  at  2020-06-25 17:35:48
Finished query  6  at  2020-06-25 17:40:42

Total time: 7 minutes and 41 seconds

**Comment by ericawood** [comment]
Data from v3.x Test: (query number refers to the order that the queries were posted)
Starting query  1  at  2020-06-25 18:17:40
Finished query  1  at  2020-06-25 18:17:50
Starting query  2  at  2020-06-25 18:17:50
Finished query  2  at  2020-06-25 18:17:52
Starting query  3  at  2020-06-25 18:17:52
Finished query  3  at  2020-06-25 18:18:01
Starting query  4  at  2020-06-25 18:18:01
Finished query  4  at  2020-06-25 18:18:57
Starting query  5  at  2020-06-25 18:18:57
Finished query  5  at  2020-06-25 18:19:40
Starting query  6  at  2020-06-25 18:19:40
Finished query  6  at  2020-06-25 18:22:55

Total time: 5 minutes and 15 seconds

**Comment by ericawood** [comment]
In addition to this, the size of the data from the queries' text file:

v4.0 = 5.1M
v3.x = 6.1M

Please let me know if you want to see any of the code and/or data files.

**Comment by ericawood** [comment]
In conclusion, it does not appear that the v4.0 python driver ("Neo4j Bolt driver for Python" v4.0.0) is not any faster than the v3.x python driver (in my test v1.7.4).
@dkoslicki

**Comment by dkoslicki** [comment]
@ericawood do you mind re-running the queries multiple times in a loop and taking a look at the min, max, and median execution time? I know there are query caching mechanisms in Neo4j, so I want to make sure the differences are not due to that.

Also, are the Neo4j instances hosted on similar hardware and/similar physical proximity to your test machine (i.e. is it the case that one is hosted on a local machine and one on an EC2 instance, or two different kinds of EC2 instances, or two different EC2 regions)?

**Comment by ericawood** [comment]
The Neo4j instance that ran the 3.x test was kg2endpoint2, which has less disk space and less memory than kg2erica, which ran the 4.0.6 test. For the loop test, I will run them both on kg2erica which is an r5a.8xlarge instance in us-west-2a.

**Comment by ericawood** [comment]
Here is the data from the loop test (please let me know if you would like to see the raw data). Both ran on kg2erica. Both ran 10 loops (so both went query 1-2-3-4-5-6 ten times in a row).

Total |   |   |   |  
-- | -- | -- | -- | --
Version | Minimum Loop Time (sec) | Maximum Loop Time (sec) | Median Loop Time (sec) | Standard Deviation
4.0.6 | 422 | 651 | 428 | 70.816194
3.5.13 | 267 | 277 | 273.5 | 3.627058802
  |   |   |   |  
Query 1 |   |   |   |  
Version | Minimum Time (sec) | Maximum Time (sec) | Median Time (sec) | Standard Deviation
4.0.6 | 15 | 123 | 16 | 33.90919246
3.5.13 | 6 | 12 | 7 | 1.943650632
  |   |   |   |  
Query 2 |   |   |   |  
Version | Minimum Time (sec) | Maximum Time (sec) | Median Time (sec) | Standard Deviation
4.0.6 | 1 | 7 | 1 | 1.897366596
3.5.13 | 0 | 1 | 1 | 0.4830458915
  |   |   |   |  
Query 3 |   |   |   |  
Version | Minimum Time (sec) | Maximum Time (sec) | Median Time (sec) | Standard Deviation
4.0.6 | 11 | 105 | 12 | 29.44976891
3.5.13 | 7 | 9 | 7.5 | 0.994428926
  |   |   |   |  
Query 4 |   |   |   |  
Version | Minimum Time (sec) | Maximum Time (sec) | Median Time (sec) | Standard Deviation
4.0.6 | 70 | 82 | 71 | 3.552776692
3.5.13 | 48 | 55 | 52 | 1.95505044
  |   |   |   |  
Query 5 |   |   |   |  
Version | Minimum Time (sec) | Maximum Time (sec) | Median Time (sec) | Standard Deviation
4.0.6 | 58 | 66 | 59.5 | 2.330951165
3.5.13 | 35 | 40 | 36.5 | 1.712697677
  |   |   |   |  
Query 6 |   |   |   |  
Version | Minimum Time (sec) | Maximum Time (sec) | Median Time (sec) | Standard Deviation
4.0.6 | 264 | 273 | 268 | 2.98142397
3.5.13 | 162 | 172 | 168.5 | 3.091206165

**Comment by dkoslicki** [comment]
Thanks @ericawood! Given they're both now run on the same instance multiple times, this is a firm confirmation that the neo4j python bolt protocol is definitely slower on 4.x than 3.x. Bummer! We will need to keep this in mind for #824.
