### ISSUE TITLE
Add option to overlay() to be applied to all possible pairs of nodes

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#856]
Right now, when you use `overlay(action=overlay_clinical_info, paired_concept_frequency=true)`, it only adds attributes to existing edges. Would be nice if it looked for _all_ possible pairs of nodes it could add this information to, and add virtual edges as necessary (would need to think carefully about how to name these virtual edges).

**Comment by dkoslicki** [comment]
@finnagin This issue has changed slightly: the aim now is to have **all** overlay() commands add virtual edges. So for every appropriate overlay() command (eg. doesn't make sense for Jaccard), have them (quickly) look at all pairs of nodes and add virtual edges with the information attached.
Things to look out for:

1. Re-compute things as little as possible (eg. make sure the translation between CURIE and omop concept isn't being done respectively for COHD).
2. Don't keep trying pairs of nodes when a KP doesn't know about one of the endpoints (or you know a-priori that a `nan` or the like is going to be returned)
3. This "all-pairs" should be the default operation of the DSL. So for example, `overlay(action=predict_drug_treats_disease, virtual_relation_label=DTD)` would apply it to all pairs (making `source/target_qnode_id` optional). You will need to be careful with how this is implemented so `resultify()` still works (eg. putting QG edges in if and only if virtual edges have been created in the KG).
4. The usual "update the docs"

**Comment by finnagin** [comment]
@dkoslicki maybe I'm reading this wrong but it looks like `predict_drug_treats_disease.py` already creates virtual edges for all pairs if `virtual_relation_label` is in parameters. since it iterates through the list generated by `itertools.product(source_curies_to_decorate, target_curies_to_decorate)`. Is this correct?

If so does that mean that in order to create virtual edges for all pair I would simply need to by default generate a `virtual_relation_label` and ensure it is unique then run normally?

**Comment by dkoslicki** [comment]
Note the similarity to #1618 . Perhaps the best way is to add a parameter `all_pairs=True/False` to make the translation to ARAXi in #1618 easier

**Comment by dkoslicki** [comment]
@finnagin We do this currently by just omitting the source/start and target/end nodes in the ARAXi command, correct?

**Comment by finnagin** [comment]
Yes we do. For everything but Fisher exact and jaccard.

**Comment by dkoslicki** [comment]
Great! Closing then
