### ISSUE TITLE
UI TypeError issue 

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#858]
On the UI:
```
add_qnode(name=DOID:1227, id=n00)
add_qnode(type=chemical_substance, is_set=true, id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00)
overlay(action=add_node_pmids, max_num=15)
return(message=true, store=false)
```
returns
```
An error was encountered while contacting the server (TypeError: Cannot read property 'substr' of null)
```

even with/without `resultify()`

**Comment by isbluis** [comment]
This exposed an issue where the UI expected a message_id.  In this case none was present due to the `store=false` directive.
Should be fixed now.

**Comment by dkoslicki** [comment]
Thanks @isbluis! I wonder if having a default example (similar to what you have for the JSON tab) would be helpful so we (i.e. me) don't forget to not include stupid things like `return(message=true, store=false)` and/or forget to `resultify`

I would suggest something simple like one of the overlay tests:
```
"add_qnode(curie=DOID:14330, id=n00)",
        "add_qnode(type=protein, is_set=true, id=n01)",
        "add_qnode(type=chemical_substance, id=n02)",
        "add_qedge(source_id=n00, target_id=n01, id=e00)",
        "add_qedge(source_id=n01, target_id=n02, id=e01, type=physically_interacts_with)",
        "expand(edge_id=[e00,e01], kp=ARAX/KG1)",
        "overlay(action=compute_jaccard, start_node_id=n00, intermediate_node_id=n01, end_node_id=n02, virtual_relation_label=J1)",
        "resultify(ignore_edge_direction=true)"
```

**Comment by isbluis** [comment]
No worries @dkoslicki !  I added a simple JSON example yesterday suggested by @edeutsch (not sure if it's been pushed out yet, but you can see it under /devLM); glad to also add this one either as a second example, or instead of the other one.

https://arax.rtx.ai/devLM/

**Comment by dkoslicki** [comment]
Looks great! Having the examples is definitely quite convenient. Thanks for implementing this!

Sent from my mobile device, please excuse my brevity and/or typos

________________________________
