### ISSUE TITLE
If/Then statements in QueryGraphInterpreter?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#859]
Example use case:
(DOID:1234)--(`p`:protein)--(`c`:chemical_substance)
A few different things could happen:

1. If `count(c)` is reasonable, than querying COHD can be done in a reasonable amount of time (so use one series of DSL commands)
2.  If DOID:1234 does not exist in COHD, then we won't want to use COHD and will instead want to use alternate DSL (eg. ngd + Jaccard)
3. If `count(c)` is large, then querying COHD will take a long time, and will want to use alternate DSL (eg. FET to reduce the size, then do the standard COHD workflow)

Would be great if QueryGraphInterpreter could allow some sort of inspection in the KG after `expand` to allow for some branching logic about what ARAXi to apply.

**Comment by edeutsch** [comment]
Well, here is how I'm imagining that we might implement it. Here is a proposed program. Does this capture what you were intending? There are some questions in the comments:
```
#### Your example from above, but with one of our usual example DOIDs instead of what I assume is a dummy one
#### And I also switched to order of the nodes to demo example 3, since I think that is more amenable to COHD??
#### I'm not certain. Please correct if wrong.
#### This is recreating a query_graph that would be coming from a user
add_qnode(curie=DOID:14330, id=n00)
add_qnode(type=protein, is_set=true, id=n01)
add_qnode(type=chemical_substance, id=n02)
add_qedge(source_id=n00, target_id=n01, id=e00)
add_qedge(source_id=n01, target_id=n02, id=e01)

#### Here is the beginning of the DSL that would be autogenerated for the user
#### based on the pattern node(curie_with_type=disease)-(type=chemical_substance)-(type=protein)
expand(edge_id=[e00,e01], kp=ARAX/KG1)

#### New conditional logic that needs to be supported
#### If the expand produces more than 30 proteins, then we need to trim this down with a different (FET) approach
if count(kg_nodes_with_qnode_id=n02) > 30:

    #### Can we proceed here with the knowledge_graph as already constructed, or do we want to purge it and just do the first step?
    #purge_knowledge_graph()
    #expand(edge_id=e00, kp=ARAX/KG1)

    #### Use FET to reduce the number of intermediate nodes
    overlay(action=fisher_exact_test, source_qnode_id=n00, target_qnode_id=n01, virtual_relation_label=FET1)
    filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n01)
    filter_kg(action=remove_orphaned_nodes, node_type=protein)

    #### If we purged above, we probably need to expand again?
    #expand(edge_id=e01, kp=ARAX/KG1)

    #### Use FET to reduce the number of the final nodes
    overlay(action=fisher_exact_test, source_qnode_id=n01, target_qnode_id=n02, virtual_relation_label=FET2)
    filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n02)
    filter_kg(action=remove_orphaned_nodes, node_type=chemical_substance)

#### Now run a COHD overlay on the 
overlay(action=overlay_clinical_info, observed_expected_ratio=true, virtual_relation_label=C1, source_qnode_id=n00, target_qnode_id=n02)
filter_kg(action=remove_edges_by_attribute, edge_attribute=observed_expected_ratio, direction=below, threshold=3, remove_connected_nodes=t, qnode_id=n02)
filter_kg(action=remove_orphaned_nodes, node_type=protein)

#### If COHD didn't find anything, then just use Jaccard
if count(edges_of_type=has_observed_expected_ratio_with) == 0:
    overlay(action=compute_jaccard, start_node_id=n00, intermediate_node_id=n01, end_node_id=n02, virtual_relation_label=J1)
    filter_kg(action=remove_edges_by_attribute, edge_attribute=jaccard_index, direction=below, threshold=.2, remove_connected_nodes=t, qnode_id=n02)

#### Compute NGD for the start and end nodes for some added ranking leverage
overlay(action=compute_ngd, virtual_relation_label=N1, source_qnode_id=n00, target_qnode_id=n02)

#### Create results and done
resultify()
```

**Comment by dkoslicki** [comment]
@edeutsch Yup! That's exactly the paradigm that I intended! 

> what I assume is a dummy one

That it was!

> And I also switched to order of the nodes to demo example 3, since I think that is more amenable to COHD??

I don't think it should matter (am uncertain), but this is a minor thing.

> Can we proceed here with the knowledge_graph as already constructed, or do we want to purge it and just do the first step?

I don't think we would need to purge the KG. Since the two edge expansion `expand(edge_id=[e00,e01], kp=ARAX/KG1)` already executed, we could then just 
```
# FET filter first edge
overlay(action=fisher_exact_test, source_qnode_id=n00, target_qnode_id=n01, virtual_relation_label=FET1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n01)
filter_kg(action=remove_orphaned_nodes, node_type=protein)

# FET filter second edge
overlay(action=fisher_exact_test, source_qnode_id=n01, target_qnode_id=n02, virtual_relation_label=FET2)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n02)
filter_kg(action=remove_orphaned_nodes, node_type=chemical_substance)
```

Though _I may need to look into this_ as the second `filter_kg(action=remove_edges_by_attribute` might be removing edges e00 in that step, we may need to use `filter_kg(action=remove_edges_by_type)` but I need to check if the FET edge types are `data:####` or if we need a new (@finnagin ) `filter_kg(action=remove_edge_by_relation)` so we can feed it `FET1` or `FET1`.

>If we purged above, we probably need to expand again?

Yes, we would need to expand that second edge as well

**Comment by finnagin** [comment]
@dkoslicki you should be able to use remove_edges_by_property e.g. `filter_kg(action=remove_edge_by_property, edge_property=relation, property_value=FET1, remove_connected_nodes=t, qnode_id=n01)`

**Comment by dkoslicki** [comment]
@edeutsch Given what Finn just said, that means we do **not** need to purge the KG, but will need to insert some filters like `filter_kg(action=remove_edges_by_property, edge_property=relation, property_value=FET1, remove_connected_nodes=t, qnode_id=n01)`

**Comment by dkoslicki** [comment]
I don't think there was much appetite/bandwidth for if/then statements in the DSL. Good to close @edeutsch ?

**Comment by edeutsch** [comment]
I agree, closing.
