### ISSUE TITLE
get metabolic pathways and metabolites into the KG

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#86]

**Comment by DeqingQu** [comment]
note from Steve：  for starters we just need a TSV file with four columns, in which column 2 is the metabolite's KEGG ID (like KEGG:C12345) and column 3 is the human-readable name of the metabolite . so this file can be prepared any way you like, it doesn't need to come from RESTful querying of a web API

**Comment by saramsey** [comment]
Wow, you can get a list of KEGG metabolites using one curl query:
curl http://rest.kegg.jp/list/cpd 

(note they use "cpd:" instead of "kegg:", that is OK)

**Comment by saramsey** [comment]
to get a list of all metabolites, you would do:

curl http://rest.kegg.jp/list/compound

(note that in the resulting TSV, instead of identifiers like "KEGG:C00022" you'll have "CPD:C00022"; this is fine).

to get a list of proteins that are associated a specific compound like KEGG:C00022, you would do:

curl http://rest.kegg.jp/link/ec/C00022

that will return TSV result like this:
cpd:C00022	ec:4.4.1.25
cpd:C00022	ec:4.4.1.28
cpd:C00022	ec:4.4.1.35
cpd:C00022	ec:4.4.1.36
cpd:C00022	ec:4.4.1.6
cpd:C00022	ec:4.4.1.8
cpd:C00022	ec:4.5.1.2
cpd:C00022	ec:4.3.3.7

the "ec:" identifiers are protein identifiers, but in a format called "Enzyme Commission". To convert from "ec:4.4.1.35" to "UniProt", we would do:

curl http://www.uniprot.org/uniprot/?query=(ec%3A+4.4.1.35)&format=tab&columns=id

Can you code this up please?

**Comment by saramsey** [comment]
So you will need to create a Python module QueryKEGG.py to expose a method "map_kegg_compound_to_enzyme_commision_ids"

You will then need to add a method "map_enzyme_commission_id_to_uniprot_ids" to the module QueryUniprot.py

**Comment by saramsey** [comment]
@dkoslicki OK we have a plan for this. I'm 95% sure we can get this done before the hackathon.

**Comment by dkoslicki** [comment]
Awesome!

**Comment by DeqingQu** [comment]
Thank you, @saramsey. Your instructions are very clear and I will finish the task ASAP.

I have two questions about the list of all metabolites.
1. The descriptions of some entities are quite long. For example,
` cpd:C00006	NADP+; NADP; Nicotinamide adenine dinucleotide phosphate; beta-Nicotinamide adenine dinucleotide phosphate; TPN; Triphosphopyridine nucleotide; beta-NADP+
`
It seems that the description consists of many synonyms which are separated by semicolons. Should I only pick the first one before semicolons, or keep all of them?
2. Many of them are not related to human. Do I need to filter them? If so, is there any advice about how to do it?

**Comment by saramsey** [comment]
just to get this in the comment history:  I like your idea of using the text up to the semicolon, as the "name".  Then the complete text (including the text before and after the semicolon) can be the node "description".

**Comment by DeqingQu** [comment]
@saramsey The two methods in QueryKEGG.py and QueryUniprot.py are done and all test cases are passed.
BTW, I fixed a bug in the `uniprot_id_to_reactome_pathways` method in QueryUniprot.py module.  'Assertion Error: assert 200 == res.status_code'.

**Comment by saramsey** [comment]
![screen shot 2018-05-21 at 2 47 28 pm](https://user-images.githubusercontent.com/5562107/40331652-e570265a-5d05-11e8-8b5c-b33c52cf8f27.png)

**Comment by saramsey** [comment]
![screen shot 2018-05-21 at 2 47 48 pm](https://user-images.githubusercontent.com/5562107/40331670-f334b4ae-5d05-11e8-96bc-218d49f32c6c.png)
