### ISSUE TITLE
How aggressive do we want to be in synonymizer?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#861]
The KGNodeIndex has ballooned way beyond its original intent: a simple index of a KG.
It is basically currently functioning as our synonymizer, but has some issues (see e.g. #825) that is causing a complete redesign.
I think it's pretty clear we desperately need a really good synonymizer
I tried the SRI node normalizer and it's okay, but far below what we need.

So the new KGNodeIndex / ARAX Synonymizer is almost ready. The result for KG1 is good. KG2 is underway.
It now consults the SRI node normalizer (https://nodenormalization-sri.renci.org/apidocs/), which has transformed it from a fast 30 second build process, to an agonizing days-long process. Progress!

But there is a fundamental design question that I'd like some advice on:
How aggressive in synonymizing do we want to be. There are several aspects. Here's one:

If you ask the SRI node normalizer about DOID:384, you get:
```
$ python KGNodeIndex.py --lookup=DOID:384 --kg=SRI
{
  "DOID:384": {
    "equivalent_identifiers": [
      {
        "identifier": "MONDO:0008685",
        "label": "Wolff-Parkinson-white syndrome (disease)"
      },
      {
        "identifier": "DOID:384"
      },
      {
        "identifier": "OMIM:194200"
      },
      {
        "identifier": "EFO:1001450",
        "label": "Wolff-Parkinson-White Syndrome"
      },
      {
        "identifier": "NCIT:C35132"
      },
      {
        "identifier": "SNOMEDCT:17869006"
      }
    ],
    "id": {
      "identifier": "MONDO:0008685",
      "label": "Wolff-Parkinson-white syndrome (disease)"
    },
    "type": [
      "disease",
      "named_thing",
      "biological_entity",
      "disease_or_phenotypic_feature"
    ]
  }
}
```

If you ask the current (development) ARAX/KG1 synonymizer, you get:
```
$ python KGNodeIndex.py --lookup=DOID:384 --kg=KG1
{
  "DOID:384": {
    "equivalent_identifiers": [
      {
        "identifier": "HP:0001716",
        "source": "KG1",
        "type": "phenotypic_feature"
      },
      {
        "identifier": "UMLS:C0043202",
        "source": "SRI",
        "type": "phenotypic_feature"
      },
      {
        "identifier": "UMLS:C0877196",
        "source": "SRI",
        "type": "phenotypic_feature"
      },
      {
        "identifier": "MEDDRA:10048015",
        "source": "SRI",
        "type": "phenotypic_feature"
      },
      {
        "identifier": "SNOMEDCT:74390002",
        "source": "SRI",
        "type": "phenotypic_feature"
      },
      {
        "identifier": "MESH:D014927",
        "source": "SRI",
        "type": "phenotypic_feature"
      },
      {
        "identifier": "DOID:384",
        "source": "KG1",
        "type": "disease"
      },
      {
        "identifier": "MONDO:0008685",
        "source": "SRI",
        "type": "disease"
      },
      {
        "identifier": "OMIM:194200",
        "source": "SRI",
        "type": "disease"
      },
      {
        "identifier": "EFO:1001450",
        "source": "SRI",
        "type": "disease"
      },
      {
        "identifier": "NCIT:C35132",
        "source": "SRI",
        "type": "disease"
      },
      {
        "identifier": "SNOMEDCT:17869006",
        "source": "SRI",
        "type": "disease"
      }
    ],
    "id": {
      "SRI_normalizer_curie": "MONDO:0008685",
      "SRI_normalizer_name": "Wolff-Parkinson-white syndrome (disease)",
      "SRI_normalizer_type": "disease",
      "identifier": "MONDO:0008685",
      "kg1_best_curie": "DOID:384",
      "label": "Wolff-Parkinson-white syndrome (disease)",
      "type": "disease"
    },
    "nodes": [
      {
        "identifier": "HP:0001716",
        "label": "Wolff-Parkinson-White syndrome",
        "original_label": "Wolff-Parkinson-White syndrome",
        "type": "phenotypic_feature"
      },
      {
        "identifier": "DOID:384",
        "label": "Wolff-Parkinson-White syndrome",
        "original_label": "Wolff-Parkinson-White syndrome",
        "type": "disease"
      },
      {
        "identifier": "OMIM:194200",
        "label": "WOLFF-PARKINSON-WHITE SYNDROME",
        "original_label": "WOLFF-PARKINSON-WHITE SYNDROME",
        "type": "disease"
      }
    ],
    "synonyms": [
      {
        "label": "Wolff-Parkinson-White syndrome",
        "source": "SRI"
      },
      {
        "label": "Wolff-Parkinson-white syndrome (disease)",
        "source": "SRI"
      }
    ],
    "type": [
      "disease",
      "phenotypic_feature"
    ]
  }
}
```

The main difference here is that I have collapsed Wolff-Parkinson-White syndrome the disease and Wolff-Parkinson-White syndrome the phenotypic feature. Is this wise at this point in time?

Interestingly, if you ask the current ARAX "What are the phenotypic features associates with DOID:384 (Wolff-Parkinson-white syndrome the disease), you get a nice set of 48 answers, one of which is Wolff-Parkinson-white syndrome (the phenotyptic_feature). That particular answer doesn't seem useful to me.
https://arax.rtx.ai/?m=2509

Now, one could argue that the phenotypes of this syndrome are distinct from the diagnosis of this syndrome.

But I will argue that at our current level of reasoning, we would be better off coalescing these two entities into a single shared concept, and thereby easily gathering all edges that link to either the disease or the phenotypic_feature.

It is of course not too hard to separate them because in the above JSON, each CURIE still has its original type and so they can be separated.

Alternatively, we can keep them completely separate, and then either the user or expand() will need to be smart enough to know that there is both a disease and a phenotypic_feature of the same name that are basically the same thing, but yet are not linked by ARAX. We would potentially add a subcomponent of this structure that is a list of cross-type associations (like this case) that expand() or other ARAX components could use for more expansive reasoning only when desired.

What do you think?

Next up: the conflation of gene and protein.

**Comment by amykglen** [comment]
Good question.. I'm in favor of your method of coalescing them. As you said, it's easy enough to separate them. And interestingly, even if `expand` didn't separate them itself, one could still control which were used via the type on the QNode. Meaning, for a QNode like this:
```
add_qnode(id=n00, curie=DOID:834, type=disease)
```
even if `expand` used the entire list of synonyms (diseases and phenotypic_features), only the disease ones would be involved in the results, due to the QNode.type. In contrast, both the diseases and phenotypic_feature synonyms would be considered if the type were left blank (or perhaps we'll eventually have a way of specifying multiple QNode types).

(At least, the above is true with how the new `expand` I've been working on for #823 works... but technically that could be changed.)

**Comment by dkoslicki** [comment]
@jaredroach May want to weigh in re: collapsing diseases and phenotypic features. From my perspective (esp. wrt drug repruposing), I treat them as the same thing, i.e.:
>But I will argue that at our current level of reasoning, we would be better off coalescing these two entities into a single shared concept, and thereby easily gathering all edges that link to either the disease or the phenotypic_feature.

I agree with this approach.

IMHO, the greedier the better: users/the ARS may not be super specific, and we can let downstream "reasoning" filter out the cruft later on.

@edeutsch 
>which has transformed it from a fast 30 second build process, to an agonizing days-long process. Progress!

Maybe the SRI is willing to share a dump of their database? They voted favorably for having KP's do this (and the normalizer is a sort of KP).

**Comment by cbizon** [comment]
Hi all, @dkoslicki referenced this issue on a nodenormalization issue.  I hope you don't mind me popping in here.   Just wanted to mention a couple things:

First, I agree with merging disease/phenotypes like Wolff-....   In the feasibility phase, ROBOKOP kept them separate, and it was a giant nuisance.  Even though you can make an argument for technical correctness, it's never used correctly, so what's the point imo.   If you poke through the normalizer stuff, you will find that we've merged in many cases, things like alzheimers, and t2d.  I'm not sure why this case doesn't merge, but in general, I would like it to.

On the performance of the normalizer, that sounds bad.  We do want these to be efficient services, so if you're seeing that kind of hit, we need to take a look.   Just to start the discussion, are you batching calls?  That does help a lot, and I think you can make the batch size pretty large (10k?).   I don't have a problem sharing the backing data either, but this does sound like a good use case to help shake out performance problems.   We can enlist @patrickkwang and others to help as well.

**Comment by edeutsch** [comment]
I am not batching them. But that clearly is needed. I thought with a little patience I could just power through one at a time, but that is not tenable. Batching will require re-designing my system, which wants to know things and make decisions one at a time, but I'll see if I can redesign things for batching.

**Comment by patrickkwang** [comment]
We'd welcome feedback on the node normalizer's performance. How exactly are you using it?

**Comment by jaredroach** [comment]
It makes sense to merge some diseases and phenotypes, but not others.
In general, the more synonymous the phenotype is with the disease, the more sense it makes to merge them. And the more a phenotype is a rare, incidental, "oh by the way", phenotype sometimes associated with a disease, the less sense it makes to merge them. Or a phenotype that is associated with many diseases. Could be problematic to merge that phenotype with one or all such diseases.

Examples:
1. So, you'd be insane not to merge "leonine facies" (phenotype)  and "lepromatous leprosy" (disease). This is a classic example of a _pathognomic_ phenotype.

2. Also, not necessarily good to merge "opioid overdose" with "itching".

3. But I am not so sure it makes sense to merge "high blood pressure" and "pheochromocytoma". Yes, pretty much all pheos will have HBP, but only a tiny fraction of HBP will have pheos.

But certainly if the phenotype and the disease have the same name (done in the name of health informatics and ontology), of course merge them.

**Comment by edeutsch** [comment]
For the moment, all that happens is that diseases and phenotypic_features are only put together in the same unique concept group if their names are the same (ignoring caps and 's and similar inconsequential differences). Therefore none of your examples are merged (despite the apparent insanity of that). Your rules 1 and 2 are an interesting next step, but also at present not performed. There is a lot of room for further work, but for the moment, grouping will only be triggered if at least one of the synonyms is the same.

There is a risk that if both Alzheimer Disease and arterial dislocation both have a listed synonym AD, they might be grouped together. But I will need to investigate that more and perhaps fix later.

**Comment by jaredroach** [comment]
OK. Sounds good.

btw: I absolutely hate it when I have arterial dislocation. But I can usually get back on track by consulting Google Maps.

**Comment by edeutsch** [comment]
@patrickkwang I do have some feedback for the normalizer. Shall I post it here or maybe better we start an issue in another more appropriate repo?

**Comment by edeutsch** [comment]
> On the performance of the normalizer, that sounds bad. We do want these to be efficient services, so if you're seeing that kind of hit, we need to take a look. Just to start the discussion, are you batching calls? That does help a lot, and I think you can make the batch size pretty large (10k?). I don't have a problem sharing the backing data either, but this does sound like a good use case to help shake out performance problems. We can enlist @patrickkwang and others to help as well.

Just to provide a response here, I rewrote everything to make use of batches and it is much faster. The service seems about equally fast servicing a single call vs. a batch of 1000. So that's great. The round trip time is < 1 sec, so that's fine. The problem was just doing them serially. I am currently using batches of 2000 and it seems efficient. I tried 5000 and it failed. probably a URL length limit perhaps or something. I did not investigate and settled for 2000, which is fine for what I need. I do have some issues with the other endpoints of the system. Maybe we can discuss those on another repo? I suppose I should post it here? https://github.com/TranslatorIIPrototypes/NodeNormalization/issues or elsewhere?

**Comment by patrickkwang** [comment]
Yes, that repo is the right place.

I’m glad the batching helps. I’d like to look into that 2000-curie limit as well. We can make a POST endpoint if it makes more sense to send the curies in the request body.
