### ISSUE TITLE
KG2 build process should produce a data dictionary

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#863]
This request came from the Translator Data Modeling working group on 2020.06.30 (requested by Chris Mungall.  Format TBD.  For now, this could be a JSON file placed on the public S3 bucket.

**Comment by ericawood** [comment]
Hi @saramsey 
From 8dfa8a7:
> `sentence`: a string containing the natural language sentence from which the
    edge was inferred (this is only not `null` for SemMedDB edges, at present)

HMDB->OMIM edges also have the sentence field:
![image](https://user-images.githubusercontent.com/36611732/90039965-37e48500-dc7c-11ea-81bf-19495e249e29.png)

(as does DrugBank, but it doesn't have the PMIDs, so I think they could be removed as they often contain redundant information to the object itself)
