### ISSUE TITLE
CURIE prefixes in SRI node normalizer but not in KG2

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#865]
Related to #862, here are CURIE prefixes that the SRI node normalizer *does* have and KG2 does *not*. This is not inherently a problem, but perhaps something to consider to add or let me know if KG2 *does* have it under a different name:
GTOPDB:
ICD-9:   (KG2 has 10. SRI has both 9 and 10 apparently)
INCHIKEY:
IUPHAR:
MetaCyc:
PANTHER.FAMILY:
PUBCHEM:
RHEA:
SMPDB:
UNII:
medgen:

If we do nothing, the new KGNodeIndex will be able to translate curies in these namespaces to our nodes if the SRI node normalizer has curies that we do have as equivalences.

**Comment by saramsey** [comment]
KG2 has CURIE prefix `ICD9`. There is no record for `ICD-9` or `ICD9` in the Biolink YAML file
https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml

but if you look for the `xref` section on this page,
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?short_form=MONDO_0002009

you can see that EBI OLS uses `ICD9`, and that is why KG2 is using it.

**Comment by saramsey** [comment]
Also, KG2 does have CURIE prefix `smpdb`. Again, Biolink YAML file does not have either prefix so here, KG2 uses a CURIE prefix based on agreement with `identifiers.org`:

https://registry.identifiers.org/registry/smpdb#!

**Comment by saramsey** [comment]
I have previously submitted a link to our complete list of CURIE prefixes to the Biolink Model team here:
https://github.com/biolink/biolink-model/issues/347

but the issue was closed out.

**Comment by saramsey** [comment]
I have opened a new issue on `ICD-9` and `SMPDB` here:
https://github.com/biolink/biolink-model/issues/373

**Comment by saramsey** [comment]
OK, commits c414394 and e3c24dd should take care of this, at least for `SMPDB`. Appreciate the heads-up.

**Comment by saramsey** [comment]
Also, to see the latest CURIE prefixes that KG2 (on the next build) will have, make sure to look in the `kg2-cure-refactoring` branch, file `RTX/code/kg2/curies-to-urls-map.yaml`.

**Comment by saramsey** [comment]
Also, new KG2 has `medgen`; see L177 of this file:
https://github.com/RTXteam/RTX/blob/kg2-curie-refactoring/code/kg2/curies-to-urls-map.yaml

**Comment by edeutsch** [comment]
okay, I am building the index for the production version of KG2, and thus my OP refers to the current contents of production KG2. Based on my reading of your comments, 
- ICD9 will appear in the next version of KG2
- SMPDB will appear in the next version of KG2 
- medgen will appear in the next version of KG2 
and so those can be dismissed from the original list.

**Comment by saramsey** [comment]
Confirmed, `SMPDB` nodes are in the new KG2 on `kg2endpoint.rtx.ai`:  (thank you @ericawood )

<img width="760" alt="Screen Shot 2020-07-16 at 2 40 35 PM" src="https://user-images.githubusercontent.com/5562107/87725571-600ec000-c772-11ea-935a-e466ae0b6e75.png">

**Comment by saramsey** [comment]
Confirmed, `medgen` nodes are in the new KG2 on `kg2endpoint.rtx.ai`, though they have no names yet:

<img width="822" alt="Screen Shot 2020-07-16 at 2 41 36 PM" src="https://user-images.githubusercontent.com/5562107/87725631-85033300-c772-11ea-8029-80dc6f91aeff.png">

**Comment by saramsey** [comment]
OK, `medgen` nodes are in KG2

<img width="822" alt="Screen Shot 2020-07-16 at 2 41 36 PM" src="https://user-images.githubusercontent.com/5562107/87725772-c1cf2a00-c772-11ea-8b4d-e623a70ef7e3.png">

but for some reason they don't have names (yet; I've noted this in #937 and will investigate) which means they probably aren't yet all that useful for the 
node synonymizer.

**Comment by saramsey** [comment]
OK, `ICD9` nodes are in the new KG2 on `kg2endpoint.rtx.ai`:

<img width="900" alt="Screen Shot 2020-07-16 at 2 46 07 PM" src="https://user-images.githubusercontent.com/5562107/87726017-1ffc0d00-c773-11ea-92e2-91fd6c1aff52.png">

**Comment by saramsey** [comment]
The other node types on your original list (top of this issue) are not in the new KG2 under any CURIE prefix, as far as I am aware. So if there is nothing else presently actionable on this issue for me, I will deassign myself in order to declutter my (massive) issue list. Please reassign if there is something else I can do here.

**Comment by edeutsch** [comment]
many thanks, closing!
