### ISSUE TITLE
More complex differences between KG2 and SRI node normalizer

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#866]
Related to #862 and #865, here are some cases where the SRI node normalizer has subcurieprefixes where we only appear to have major curieprefixes. SRI node normalizer has:
HGNC.FAMILY:
KEGG.COMPOUND:
KEGG.PATHWAY:
KEGG.REACTION:

We have HGNC and they have HGNC, but they also have HGNC.FAMILY. I don't know the significance of this.

We just have KEGG. They do not have plain KEGG, but rather these three subcurieprefixes.

What shall we do about this?

**Comment by saramsey** [comment]
Thanks for the heads-up. KEGG has been a struggle, due to their quirky ID nomenclature.  I will see what I can do to fix this on the KG2 ETL side of things.

**Comment by saramsey** [comment]
As for HGNC family, this is the first I've heard of that CURIE prefix. Some investigation required....

**Comment by saramsey** [comment]
see L43 of 
https://github.com/RTXteam/RTX/issues/866

I think `KEGG` is correct. SRI node normalizer seem to be not biolink compliant w/r/t KEGG IDs. I will log an issue in their repo.

**Comment by saramsey** [comment]
OK I have noted this issue with the SRI node normalizer here:
https://github.com/TranslatorIIPrototypes/NodeNormalization/issues/22

**Comment by saramsey** [comment]
SRI confirms it-- they will be switching back to KEGG.

**Comment by saramsey** [comment]
Regarding `HGNC.FAMILY`, I checked and this seems to be a valid CURIE prefix in the biolink `context.jsonld` file and in the `biolink-model.yaml` file.  It even has a resolvable base URL in the `context.jsonld` file. However, when I look this CURIE prefix up in the `identifiers.org` registry, I see this red banner:

<img width="1253" alt="Screen Shot 2020-07-23 at 4 25 55 PM" src="https://user-images.githubusercontent.com/5562107/88348048-4389ff00-cd01-11ea-8501-8e7134dde946.png">

Perhaps the SRI node normalizer lags current upstream sources with respect to the deprecation of `HGNC.FAMILY` (which seems quite recent, July 15th, 2020). But if `identifiers.org` says it is deprecated, that's probably reason enough for me to not go looking for a reason why it isn't in our system.
