### ISSUE TITLE
Make expand consider both 'gene' and 'protein' for QNodes with a type that is either of those

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#873]
Don't need to edit the query graph; just search for both in the KP

**Comment by dkoslicki** [comment]
+1 to this especially considering the ambiguity with with KP’s treat these...

**Comment by amykglen** [comment]
alright - this has been implemented, tested, and pushed to the `node-normalization` branch.

**Comment by amykglen** [comment]
confirmed this is working on `/beta`
