### ISSUE TITLE
Should the final KnowledgeGraph ARAX returns contain only nodes/edges used in the results?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#874]
With the way ARAX currently works, the `KnowledgeGraph` it returns sometimes contains nodes/edges that aren't actually used in the `Results`, depending on what `filter` steps were done.

For example, this DSL (https://arax.rtx.ai/?m=2542):
```
add_qnode(id=n00, curie=DOID:14330)
add_qnode(id=n01, type=protein)
add_qedge(id=e00, source_id=n00, target_id=n01)
expand()
resultify()
filter_results(action=limit_number_of_results, max_results=5)
```
 returns 5 results, each corresponding to a different protein:

![Screen Shot 2020-07-02 at 5 44 42 PM](https://user-images.githubusercontent.com/49423686/86420519-c2a09000-bc8b-11ea-8d85-b0359199af0f.png)

But the `KnowledgeGraph` still contains 39 proteins (vs. only the 5 used in the results):

![Screen Shot 2020-07-02 at 5 39 20 PM](https://user-images.githubusercontent.com/49423686/86420439-8ec56a80-bc8b-11ea-9e24-eff6335c55ef.png)

Not sure if this is desired, or if there should be a clean-up step that makes sure the knowledge graph doesn't have extraneous nodes/edges.

**Comment by saramsey** [comment]
The clean-up step would be in filter, right?

**Comment by edeutsch** [comment]
yes, I think I would vote that filter_results needs to be extended to remove all nodes and edges that are not bound to a result.

**Comment by dkoslicki** [comment]
On the other hand, I have found it helpful to see when the KG contains stuff that aren’t in the answers, as this has helped diagnose problems (like in some issue I can’t recall atm when I used BTE and KG2, but the results only used KG2 nodes even though the KG had BTE stuff in it).

**Comment by amykglen** [comment]
that seems reasonable to me that `filter_results` should remove nodes/edges that aren't bound to a result... but note that this scenario can also arise with `filter_kg`... example (https://arax.rtx.ai/beta/?m=2600):
```
add_qnode(id=n00, type=disease, curie=DOID:12176)
add_qnode(id=n01, type=chemical_substance)
add_qedge(id=e00, source_id=n00, target_id=n01)
expand(edge_id=e00, kp=ARAX/KG2, continue_if_no_results=true)
expand(edge_id=e00, kp=BTE, continue_if_no_results=true)
overlay(action=predict_drug_treats_disease)
filter_kg(action=remove_edges_by_attribute, edge_attribute=probability_treats, direction=below, threshold=0.75, remove_connected_nodes=true, qnode_id=n01)
resultify(ignore_edge_direction=true)
```


125 chemical_substances appear in the `results`, but 196 chemical_substances appear in the `knowledge_graph`.

**Comment by amykglen** [comment]
decision from 7/10 mini-hackathon:

- `resultify` should remove any nodes **not** used in results from the KG
- and then also remove any orphaned edges (but don't worry about enforcing that an edge corresponds to a qedge)
- we won't worry about updating the KG after `filter_results` is used (unless we run into an issue with that)
