### ISSUE TITLE
Q1 and Q2 much slower

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#89]
@dkoslicki I don't have any stats to back it up, but running Q1 and Q2 examples seems to be *much* slower than before. Q2 is glacial now.

**Comment by dkoslicki** [comment]
Is it still slow after running twice? Given the new KG and some other changes, the cache may not be updated. On my local end, I actually measure speed improvements (except for the slowness in the question parsing as, having added more nodes, the issue of matching terms to nodes in the KG is taking quite a bit slower).

**Comment by edeutsch** [comment]
seems to be better tonight. I didn't perform measurements, but Q2 took minutes. I just performed a few tests and I'm now seeing these numbers:
Q0	instant
Q1	30 seconds
Q2	18 seconds
Q3	2 seconds
Q4	18 seconds
