### ISSUE TITLE
Get MEDDRA concept hierarchy into KG2

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#891]
The MEDDRA dictionary from the 2018AB UMLS (source `MDR`) doesn't seem to have parent-child relationships for dictionary terms. More specifically, the `umls-mdr.ttl` file does not have any meaningful `subClassOf` relationships (in that file, all classes are subclasses of `owl:Thing`). But BioOntology, which is based on the 2019 UMLS, seems to have the MEDDRA hierarchy. Need to look into this.

**Comment by saramsey** [comment]
maybe the concept hierarchy is there in UMLS 2020AA?  (see #931)

**Comment by ericawood** [comment]
In 2020AA, there are 74056 instances of "owl:Class" in `umls-mdr.ttl`. There are 27 instances of "owl:Thing" in `umls-mdr.ttl`. (`kg2erica`).
In 2018AB, there are 71982 instances of "owl:Class" in `umls-mdr.ttl`. There are 27 instances of "owl:Thing" in `umls-mdr.ttl`. (`kg2steve`)

However, the MEDDRA nodes without categories issue is more common using 2020AA (47874 occurrences in log file vs 46666). 

2020AA:
```
ubuntu@ip-172-31-23-154:~/kg2-build$ grep -o -i owl:Class umls-mdr.ttl | wc -l
74056
ubuntu@ip-172-31-23-154:~/kg2-build$ grep -o -i owl:Thing umls-mdr.ttl | wc -l
27
ubuntu@ip-172-31-23-154:~/kg2-build$ grep -o -i "Node with ontology_node_id MEDDRA:" ~/kg2-build/build-test-ont.log | wc -l
47874
```

2018AB:
```
ubuntu@ip-172-31-3-188:~/kg2-build$ grep -o -i owl:Class umls-mdr.ttl | wc -l
71982
ubuntu@ip-172-31-3-188:~/kg2-build$ grep -o -i owl:Thing umls-mdr.ttl | wc -l
27
ubuntu@ip-172-31-3-188:~/kg2-build$ grep -o -i "Node with ontology_node_id MEDDRA:" build-kg2-ont-test-stderr.log | wc -l
46666
```

**Comment by ericawood** [comment]
We likely just need to use the TUIs (like in issue #762). Example: (both 2018AB and 2020AA have the same entry in the TTL file, but I've been working with the 2020AA version)
`[http://purl.bioontology.org/ontology/MEDDRA/] Node with ontology_node_id MEDDRA:10007469 does not have a category: MEDDRA:10007469`

The umls-mdr.ttl file says this node has TUI `T191` (I'm not posting the snippet here in case it isn't supposed to be posted per a licensing agreement).

Biolink YAML file links `T191` to the `disease` category.

In KG2 V2.3.1, (notice `category_label`)
```
{
  "iri": "http://purl.bioontology.org/ontology/MEDDRA/10007469",
  "category_label": "named_thing",
  "deprecated": "False",
  "name": "Carcinoma rectum stage IV",
  "description": "UMLS Semantic Type: UMLS_STY:T191",
  "provided_by": "umls_source:MEDDRA",
  "id": "MEDDRA:10007469",
  "category": "biolink:NamedThing",
  "update_date": "2018"
}
```

I am working on learning how many of the MEDDRA nodes missing categories this is the case for.

**Comment by ericawood** [comment]
Hi @saramsey,
After testing with ce126fd:
```
{
            "category": "biolink:Disease",
            "category_label": "disease",
            "creation_date": null,
            "deprecated": false,
            "description": "UMLS Semantic Type: UMLS_STY:T191",
            "full_name": null,
            "id": "MEDDRA:10007469",
            "iri": "http://purl.bioontology.org/ontology/MEDDRA/10007469",
            "name": "Carcinoma rectum stage IV",
            "provided_by": "umls_source:MEDDRA",
            "publications": [],
            "replaced_by": null,
            "synonym": [],
            "update_date": "2020"
}
```

**Comment by ericawood** [comment]
I tested my non-committed fix for this, adapted to use the Biolink Ontology and curies-to-categories.yaml rather than the Biolink YAML. For the fix to be very helpful, we definitely need these TUIs:
```
{'T056', 'T039', 'T037', 'T089', 'T025', 'T029', 'T005', 'T185', 'T062', 'T081', 'T054', 'T058', 'T030', 'T099', 'T101', 'T204', 'T191', 'T064', 'T082', 'T201', 'T060', 'T007', 'T066', 'T018', 'T020', 'T031', 'T041', 'T100', 'T044', 'T097', 'T061', 'T093', 'T098', 'T068', 'T024', 'T046', 'T059', 'T055', 'T091', 'T034', 'T019', 'T080', 'T169', 'T057', 'T069', 'T042', 'T049', 'T023', 'T065', 'T048', 'T070', 'T040', 'T190', 'T063', 'T043'}
```
since they are in MEDDRA. I'm working on adding these to curies-to-categories.yaml.

**Comment by ericawood** [comment]
Got most of those done through manual curation of curies-to-categories.yaml from the Biolink YAML file. Unfortunately, `T091` ("Biomedical Occupation or Discipline") is still missing, as it is not in the Biolink YAML file.

**Comment by kvarforl** [comment]
@saramsey  I'm unsure how to verify this fix for KG2.3.5. Could you document steps for me to follow here?

**Comment by ericawood** [comment]
@kvarforl 

1. In Neo4j, pull the categories of all MEDDRA prefixed nodes and the counts of each.
2. If there are relatively few of category "named_thing" it is fixed!
