### ISSUE TITLE
FET doesn't like it when Expand ignores type for qnodes using curie synonyms

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#897]
so the fix for issue #889 turns out to make FET unhappy sometimes. after that fix was made, `test_FET_example_2` started failing in the `node-normalization` branch. @chunyuma and I have discussed a bit and worked out what the problem is, but it's unclear what the best solution is.

here's an example to illustrate what's happening. imagine this DSL:
```
add_qnode(id=n00, type=disease, curie=DOID:XXX)
add_qnode(id=n01, type=protein
add_qedge(id=e00, source_id=n00, target_id=n01)
expand(edge_id=e00, kp=ARAX/KG1)
```
when `expand` sends a cypher query to neo4j for this, it effectively replaces n00's curie with a list of curie synonyms (`[DOID:XXX, MONDO:XXX, MESH:XXX, CUI:XXX]`) and ignores n00's type of 'disease', because some of the synonyms have other types ('named_thing' and 'unknown_category'), so if the 'disease' type were enforced, we'd miss out on any connections to those synonyms (#889).

but now imagine that the only proteins returned were connected to the synonym CUI:XXX, which had a type of 'named_thing'. that's all fine without FET in the picture, because `expand` uses the 'preferred_curie' of DOID:XXX when processing results, and so that fact is really irrelevant to the user. but if FET is run at this point, it would go through each n01 protein `expand` returned and try to count how many 'disease' neighbors each has in KG1. but in this case, the proteins aren't guaranteed to have any 'disease' neighbors - only a 'named_thing' neighbor. and currently FET throws an error when it can't find any neighbors for a node.

what should give in this situation? should FET somehow skip these nodes? or is `expand`'s ignoring the qnode type for synonyms not worth it? or is there some other next-level solution... :)

**Comment by chunyuma** [comment]
@amykglen, I think one possible solution might be that we can ignore the node types in both end of edge instead of just ignoring the node type in one end of edge. For example, in your example, when we replaces n00's curie with a list of curie synonyms `([DOID:XXX, MONDO:XXX, MESH:XXX, CUI:XXX])` and ignores its `disease` type, can we also replace n01's curie  with a list of curie synonyms? This means that we no longer treat each node as a single node but a set of nodes which are synonyms. 

So in FET, when it goes through each n01 (`protein` and its `synonyms`) expand returned, it tries to count how many `disease` and its `synonyms` neighbors  each has in KG1. In this way, although the proteins aren't guaranteed to have any 'disease' neighbors, their `synonyms` might have connection.

**Comment by amykglen** [comment]
yes, that's actually already how it works, @chunyuma. when FET uses `expand` to look for disease neighbors for each protein, `expand` does consider each protein's synonyms. but still sometimes there are no disease neighbors to the protein or to any of the protein's synonyms.

**Comment by chunyuma** [comment]
@amykglen, does `expand` will consider the disease's synonyms to the protein or to any of the protein's synonyms? What I thought is to not just limit to disease but also consider its synonyms.

**Comment by amykglen** [comment]
well if you're expanding `(protein UniProtKB:123)--(disease)`, I'm not sure how you can consider synonyms for 'disease' when it's just a generic 'disease'. I'm not sure how you could know possible synonyms for a non-specific entity.

I guess you could compute a giant list of every 'disease' curie in the KP, go through and find the synonyms of all of those, and then make that _massive_ list the 'disease' node's curie? I'm not sure if that would work practically though because the list would be so huge.

**Comment by chunyuma** [comment]
@amykglen, I see. My original thought was to first find the `disease` neighbors for each protein and then also consider the synonyms of the connected `disease` curies. But yes, if sometimes there are no disease neighbors to the protein or to any of the protein's synonyms, it is also impossible to find their synonyms

**Comment by amykglen** [comment]
worth noting that I think the potential for this issue also exists in `production` (in the code before any `node-normalization` changes were made), because `expand` also ignores `qnode.type` when synonyms are used in `production`.

**Comment by amykglen** [comment]
from 7/10 mini-hackathon: as a temporary solution, instead of throwing an error, FET could log a warning when this happens, giving some indication of how many nodes were affected. then at least we can start to gauge how common of a problem this is, and FET can still complete for the nodes it can find values for.

**Comment by chunyuma** [comment]
FET was updated to skip the nodes without neighbors and throw out a warning instead in `master` branch. The updated FET passed all the `FET` tests in `test_ARAX_overlay.py` AND `test_ARAX_workflows.py`. 

@amykglen, for the case that we discussed before, right now the `FET` will throw the warning messages below:
```
  - 2020-07-12 19:18:44.725655 WARNING: Fail to query adjacent nodes from ARAX/KG1 for MONDO:0003847 in FET probably because expander ignores node type. For more details, please see issue897.
  - 2020-07-12 19:18:46.234774 WARNING: Fail to query adjacent nodes from ARAX/KG1 for MONDO:0000425 in FET probably because expander ignores node type. For more details, please see issue897.
  - 2020-07-12 19:18:47.634785 WARNING: Fail to query adjacent nodes from ARAX/KG1 for MONDO:0021199 in FET probably because expander ignores node type. For more details, please see issue897.
  - 2020-07-12 19:18:47.704932 WARNING: Fail to query adjacent nodes from ARAX/KG1 for MONDO:0002022 in FET probably because expander ignores node type. For more details, please see issue897.
  - 2020-07-12 19:18:51.245598 WARNING: Fail to query adjacent nodes from ARAX/KG1 for MONDO:0005128 in FET probably because expander ignores node type. For more details, please see issue897.
  - 2020-07-12 19:18:51.396600 WARNING: Fail to query adjacent nodes from ARAX/KG1 for MONDO:0002254 in FET probably because expander ignores node type. For more details, please see issue897.
  - 2020-07-12 19:18:51.500811 WARNING: Fail to query adjacent nodes from ARAX/KG1 for MONDO:0000275 in FET probably because expander ignores node type. For more details, please see issue897.
  - 2020-07-12 19:18:52.696997 WARNING: 7 adjacent nodes which are ['MONDO:0003847', 'MONDO:0000425', 'MONDO:0021199', 'MONDO:0002022', 'MONDO:0005128', 'MONDO:0002254', 'MONDO:0000275'] can't find its neighbors. These nodes will be ignored for FET calculation.
```

**Comment by amykglen** [comment]
awesome! sounds great.

**Comment by amykglen** [comment]
hey @chunyuma - so `expand` uses KG2C by default now, which means that this issue should be resolved. but I can't verify yet because I'm running into a different error - I think it might be related to the fact that `Edge.is_defined_by` is now `ARAX/KG2C` (vs. `ARAX/KG2`) when `expand` uses KG2C.

when I run this test in `master` (it's `test_FET_ex2`, but using `kp=ARAX/KG2` instead of `kp=ARAX/KG1`):
```
    query = {"previous_message_processing_plan": {"processing_actions": [
        "create_message",
        "add_qnode(curie=DOID:12889, id=n00, type=disease)",
        "add_qnode(type=protein, id=n01)",
        "add_qedge(source_id=n00, target_id=n01, id=e00)",
        "expand(edge_id=e00, kp=ARAX/KG2)",
        "overlay(action=fisher_exact_test, source_qnode_id=n00, virtual_relation_label=FET, target_qnode_id=n01, rel_edge_id=e00, top_n=20)",
        "resultify()",
        "return(message=true, store=false)"
    ]}}
```

I get this error:

`
ERROR: Only KG1 or KG2 is allowable to calculate the Fisher's exact test temporally
`

**Comment by amykglen** [comment]
@chunyuma - I just pushed [a fix](https://github.com/RTXteam/RTX/commit/7df9a4b573d77395b6ba7df0900ff914d8d20ea5) for the above to a new branch called `issue897`, with which I no longer get an error. (it was a very minor fix.) I can merge it to `master` if it's alright with you.

**Comment by chunyuma** [comment]
Sorry for late reply @amykglen. Yes, I think the recent commit where you modified the FET scripts is correct. I have no problem for you to merge it to `master`. Thank you so much for helping me fix it!

**Comment by amykglen** [comment]
ok, great - no problem! just merged it into `master`. will verify it looks good on `/test` when `master` is next rolled out.

**Comment by amykglen** [comment]
this seems to look good on production: https://arax.ncats.io/?r=5606

closing!
