### ISSUE TITLE
API in front of KG2 for node synonymization, retrieval, and one-hop expansions

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#899]
Provide a registered Translator API that enables teams to use KG2 (as a KP) to perform one-hop expansions.

**Comment by amykglen** [comment]
worth noting that `expand` contains code that does all the dirty work here already (takes in a query graph, answers it using KG2, and outputs nodes/edges in API model format...even for multi-hop query graphs).

**Comment by saramsey** [comment]
OK, keeping this in our issue tracker for the time being, but removing the `kg2` label from this since I think it is kind of downstream of KG2. Yes, agreed we can use Expander for this.

**Comment by amykglen** [comment]
think we can close this issue - it's a duplicate of #1129
