### ISSUE TITLE
Ingest SIDER via mychem

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#90]
Apparently some of the SMEs are going to be interested in side effects of drugs. These can be obtained from mychem:
https://github.com/NCATS-Tangerine/translator-knowledge-graph/issues/3#issuecomment-382503643
http://mychem.info/v1/chem/KWHRDNMACVLHCE-UHFFFAOYSA-N

The R&I group already has some interesting (and within our reach!) questions that could be asked if we ingested this KS.

**Comment by dkoslicki** [comment]
Priority before the hackathon is TBA depending on what the questions from the SMEs are (will be sent these soon from Christine)

**Comment by dkoslicki** [comment]
UMLS is used to identify terms. We would probably need to map these to HP phenotypes. (Chris Bizon mentioned this)

**Comment by dkoslicki** [comment]
Christine says that this is a priority for the proto-MVP, and not so much for the SMEs.

**Comment by tylerperyea** [comment]
This is really cool! Does mychem support bon small molecule substances as well? Such as monoclonal antibodies, mixtures or other large/disperse drug-likeness entities?

**Comment by dkoslicki** [comment]
@tylerperyea In the [Data Matrix Workflow](https://docs.google.com/spreadsheets/d/1rBwao7TD3grDLdTCINYOgpb_L5_RuZZwfQH_HqiChWI/edit#gid=0) you list Purple team as having a "3" for ``What are the common side effects of [drug]?`` A few questions:
1. Is this information accessible via an API, or is it from a manually constructed query?
2. If we were to ingest SIDER via MyChem, we would be using particular identifiers (HPO, ChEMBL, etc.). Do you want us to be able to return this information in any particular format/identifiers?

**Comment by dkoslicki** [comment]
@tylerperyea per your question about non small molecule substances: @saramsey is looking into this now.

**Comment by dkoslicki** [comment]
See also #243, #244, and #245

**Comment by saramsey** [comment]
@flashkicker can you try to add a method to QueryMyChem.py:

map_chembl_compound_to_side_effects_umls(chembl_id)

that will take a ChEMBL compound ID (like "CHEMBL521") as an argument and return a set of UMLS IDs for side effects for the drug.  In the response JSON object from mychem, you will want to look for "sider".

![screen shot 2018-07-18 at 9 58 41 am](https://user-images.githubusercontent.com/5562107/42896259-37839fba-8a71-11e8-8dd6-94c8ee8adb0e.png)

**Comment by flashkicker** [comment]
We just need to add code to BioNetExpander.py that can map a drug (i.e., a node with label “chemical_substance") to a side effect phenotype (i.e., a node with label “phenotypic_feature”) using the method DrugMapper.map_drug_to_hp_with_side_effects.  The relationship name that it should use is “causes_or_contributes_to”, and the sourcedb argument to the Orangeboard.add_rel method can be “SIDER".

**Comment by flashkicker** [comment]
@saramsey Almost done, just testing it out.

**Comment by saramsey** [comment]
@tylerperyea yes, ChEMBL includes some biologics, like bevacizumab:

![screen shot 2018-07-26 at 9 10 49 pm](https://user-images.githubusercontent.com/5562107/43301306-32d3cbb2-9119-11e8-9353-e0fb0da0670c.png)

**Comment by dkoslicki** [comment]
@tylerperyea Just FYI (see the above comment), it does appear that ChEMBL has biologics!

**Comment by saramsey** [comment]
@flashkicker can you give me an update on this issue, please?

**Comment by saramsey** [comment]
Hi Chunlei,

This is Deqing Qu from Oregon State University and I am working with Steve Ramsey for NCATS translator project. Could you help us answer one question about the MyChem API?

We are trying to use MyChem to map between a drug (specified by its CHEMBL ID) and its side effects (which are specified by UMLS IDs). For example, we can get the expected side effects by querying http://mychem.info/v1/chem/KWHRDNMACVLHCE-UHFFFAOYSA-N?fields=sider

But when we tried many other drugs (like Penicillin or Cetirizine), MyChem API didn’t return any side effects as we expected, no matter we used CHEMBL ID or InChi Key as the parameter of the MyChem API. Is the API designed not to return any side effects for the drugs? Is it possible to add the 'sider' field for the drugs? 

Here are some examples.

Penicillin V
https://www.ebi.ac.uk/chembldb/compound/inspect/CHEMBL615
http://mychem.info/v1/chem/CHEMBL615?fields=sider
http://mychem.info/v1/chem/BPLBGHOLXOTWMN-MBNYWOFBSA-N?fields=sider

Cetirizine
https://www.ebi.ac.uk/chembldb/compound/inspect/CHEMBL1000
http://mychem.info/v1/chem/CHEMBL1000?fields=sider
http://mychem.info/v1/chem/ZKLPARSLTMPFCP-UHFFFAOYSA-N?fields=sider

Amoxicillin
https://www.ebi.ac.uk/chembldb/compound/inspect/CHEMBL1082
http://mychem.info/v1/chem/CHEMBL1082?fields=sider
http://mychem.info/v1/chem/LSQZJLSUYDQPKJ-NJBDSQKTSA-N?fields=sider

Domperidone
https://www.ebi.ac.uk/chembldb/compound/inspect/CHEMBL219916
http://mychem.info/v1/chem/CHEMBL219916?fields=sider
http://mychem.info/v1/chem/FGXWKSZFVQUSTL-UHFFFAOYSA-N?fields=sider

**Comment by saramsey** [comment]
Kevin Xin replies:

> Hi Steve,
> 
> Thanks for pointing that out! 
> 
> I looked into the source file from SIDER (http://sideeffects.embl.de/download/), and found where the problem is. SIDER use pubchem compound ID for their compound ID. And in MyChem.info, we also use these pubchem compound ID provided by SIDER for merging. However, the pubchem Compound ID provided in the SIDER source file are all wrong. (However, the one shown are their web interface is correct)
> 
> For example, 'Amoxicillin' should correspond to CID2171. However, in the source file from SIDER, they put it as CID100002171, while this CID10000217 refers to a totally different compound https://pubchem.ncbi.nlm.nih.gov/compound/100002171. Moreover, 'Amoxicillin' is not a single edge case in SIDER. They arbitrarily added '100000*' to all the pubchem compound IDs in SIDER. So the current SIDER mapping in MyChem.info is all wrong.
> 
> We will add some regex in our MyChem.info parser to fix this issue. That's pretty straightforward. But in order for that change to be reflected on the API, we need more time to do the data reindexing. So just be aware you might not see the new changes instantly, but we will keep you updated! 
> 
> Thanks you and Deqing for reporting that! Really appreciate it!
> 
> Best,
> Kevin

**Comment by saramsey** [comment]
I looked into eHealthMe.com as a possible alternative. Their website claims to have a public REST API for drug adverse event data (which they aggregate from FDA), but the API seems to be down; I just get a 301 error.

**Comment by saramsey** [comment]
Kevin Xin has provided an update:

> Hi Stephen,
> 
> Sorry for the delay. Our expectation is that there will be a full new release of MyChem.info before the Portland hackathon. We are currently also working on a couple of other data issues in MyChem.info related to drugbank, chebi, etc. 
> 
> I will keep you updated on this!
> 
> Thanks!
> 
> Best,
> Kevin

**Comment by saramsey** [comment]
> Hi Steve,
> 
> We have just put forward the new MyChem release. It fixes the previous issue regarding SIDER. Please give a try.
> 
> Thanks!
> 
> Best,
> Kevin
