### ISSUE TITLE
Upgraded QueryGraphInterpreter

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#902]
I have checked into `master` an upgraded QueryGraphInterpreter. It is not tested as well as it should be, but seems to work. The main notable differences are:
- You can now specify specific types in the YAML file via something like type=chemical_substance
- The algorithm employs fuzzy matching of the incoming query_graph attributes to all potential templates and selects the most specific and closely matching one

Please report problems here.

**Comment by dkoslicki** [comment]
@edeutsch  given the current QueryGraphInterpreter seems to be working ok, shall we close this issue in favor of #859?

**Comment by edeutsch** [comment]
sounds good to me!
