### ISSUE TITLE
BTE returns non-existent chemicals?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#903]
I just ran David's example query_graph:
```
{
   "edges": [
      {
         "id": "e00",
         "source_id": "n00",
         "target_id": "n01",
         "type": null
      }
   ],
   "nodes": [
      {
         "id": "n00",
         "curie": "DOID:11830",
         "type": "disease"
      },
      {
         "id": "n01",
         "type": "chemical_substance"
      }
   ]
}
```
and it seems to work, but one notable warning:
2020-07-09 07:03:11.365411 WARNING:  NodeSynonymizer did not return info for: {'CHEMBL.COMPOUND:CHEMBL1200864', 'CUI:C1444689', 'CHEMBL.COMPOUND:CHEMBL1200389'}

Looking for the first one CHEMBL.COMPOUND:CHEMBL1200864:
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1200864/
ChEMBL doesn't even know about it!

hmm, searching more carefully in autocomplete, it seems missing. Deleted?
![image](https://user-images.githubusercontent.com/12707718/87008795-1f62e580-c179-11ea-945d-b0c8b2c77c9e.png)

**Comment by dkoslicki** [comment]
@edeutsch Maybe we should make this an issue on the [BTE repo](https://github.com/biothings/biothings_explorer)?

**Comment by edeutsch** [comment]
maybe. I posted it here to see if anyone can think of an ARAX reason for this. And also, I'm not able to formulate a MWE repro that could demonstrate the problem. All I can tell is that BTE as used by ARAX seems to be causing a problem. Could @amykglen or someone else create a MWE repro that demonstrates the problem for BTE to address?

**Comment by finnagin** [comment]
@edeutsch so you know if this still happens and is still relevant?

**Comment by edeutsch** [comment]
Probably this particular case is not longer of concern, but I wonder how often we can an entity back from a KP that we don't have in the NodeSynonymizer. What happens in that case? I don't know.

**Comment by dkoslicki** [comment]
Looking into this further, it appears this was deleted from Chembl: https://www.ebi.ac.uk/chembl/id_lookup/CHEMBL1200864/
Safe to close give subsequent work on the synonymizer? If not, feel free to reopen
