### ISSUE TITLE
MolePro API registered: investigate using in ARAXi/KG2?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#914]
See [this PR](https://github.com/NCATS-Tangerine/translator-api-registry/pull/34/commits/fa1faf525c336bf12fc811f404c7170c38c9585b) that describes their endpoint.

We should find:
- [x] what info they provide
- [x] how it could be incorporated into ARAXi and/or
- [ ] if KG2 already has all this info in it

Volunteers?

**Comment by dkoslicki** [comment]
IPython notebook available [here](https://www.dropbox.com/s/y8cyl5zle9a8uww/MolePro%206%20-%20reasoner%20API.ipynb?dl=0) showing the endpoint and how to interact with it.

Data is obtained with `correlated_with`, all other ones are "knowledge".

Data will be exposed as edge attributes after Reasoner Std API (aka TRAPI) V1.0 is finalized.

**Comment by saramsey** [comment]
Would be great to have the ability to 

- expand starting from a HGNC gene, to get all the compounds that MolePro says are "correlated" with the gene
- expand starting from a CHEMBL compound, to get all the genes that MolePro says are "correlated" with the gene

(here, correlated means that knockdown of the gene in cell lines causes transcriptome changes that are similar to the effects of the compound on the same cell lines).

**Comment by saramsey** [comment]
From Vlado:
```
query = {
    "message": {
        "query_graph": {
            "edges": [
                {
                    "id": "e00",
                    "source_id": "n00",
                    "target_id": "n01",
                    "type": "affects"
                }
            ],
            "nodes": [
                {
                    "curie": "ChEMBL:CHEMBL25",
                    "id": "n00",
                    "type": "chemical_substance"
                },
                {
                    "id": "n01",
                    "type": "gene"
                }
            ]
        }
    }
}
response = requests.post(base_url+'/query', json=query).json()
response
```

**Comment by saramsey** [comment]
Hey @amykglen would it be easy to add this capability to ARAX-Expand?

**Comment by dkoslicki** [comment]
When data comes out: 100 is better (Z-score-like)

First try: divide by 100.

Associate publication forthcoming from Vlado (?)

**Comment by dkoslicki** [comment]
And @amykglen , see the comment [above](https://github.com/RTXteam/RTX/issues/914#issuecomment-696981239) that points to the API endpoint and all its (current) capability.

**Comment by vdancik** [comment]
Publication describing the assay and similarity score:

https://pubmed.ncbi.nlm.nih.gov/29195078/

**Comment by amykglen** [comment]
nice! yes, I think it should be pretty straightforward to plug it into `expand`. thanks for all the info! will work on it..

**Comment by amykglen** [comment]
alright, MolePro is plugged into `expand` in the `issue914` branch and working on a basic level; the integration is still a bit rough around the edges, but working.

added a test (can be run via `pytest -v test_ARAX_expand.py -k test_molepro`) that looks like:
```
"add_qnode(curie=HGNC:9379, type=gene, id=n00)",
"add_qnode(type=chemical_substance, id=n01)",
"add_qedge(source_id=n00, target_id=n01, id=e00)",
"expand(kp=MolePro)"
```
and I also got multiple input curie functionality working, meaning it can be used for the second+ hop, like so:
```
"add_qnode(name=Fanconi anemia, id=n00)",
"add_qnode(type=protein, id=n01)",
"add_qnode(type=chemical_substance, id=n02)",
"add_qedge(source_id=n00, target_id=n01, id=e00)",
"add_qedge(source_id=n01, target_id=n02, id=e01)",
"expand(edge_id=e00, kp=ARAX/KG1)",
"expand(edge_id=e01, kp=MolePro)"
```
(though this is pretty slow right now because we sequentially hit up MolePro once per every n01 node. but once batch querying is available, this won't be a problem.)

**Comment by amykglen** [comment]
ok, I made some refinements here and merged this into `master`; MolePro queries are fully functioning. will verify things seem to be working well on `/test` next time we roll out.

(some minor adjustments will be needed once the planned new MolePro features are available (e.g., batch querying, additional edge properties), but the integration should be complete for now.)

**Comment by edeutsch** [comment]
Latest `master` just rolled out to /test

**Comment by amykglen** [comment]
thanks! all seems well on `/test`.

an interesting anecdote: for this query (genes/proteins associated with aspirin):
```
add_qnode(curie=CHEMBL.COMPOUND:CHEMBL25, id=n0, type=chemical_substance)
add_qnode(type=gene, id=n1)
add_qedge(source_id=n0, target_id=n1, id=e0)
```
MolePro finds 370 answers and KG2 finds 608, but they only share 17 answers in common! (even though the `NodeSynonymizer` recognized all the curies from MolePro.) so it seems MolePro is contributing quite a bit!
