### ISSUE TITLE
NodeSynonymizer interface needs improvement

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#919]
I just cleaned up much of the NodeSynonymizer interface. The back end is the same, but batching is better and older cruft cleaned out.

I renamed get_equivalent_curies() to get_equivalent_nodes() since it doesn't return all known curies, but rather returns the list of curies of all nodes in the specified kg_name. I left a pass-through for backwards compatibility, but it would be nice to remove the original

I added a method that @amykglen wanted: get_canonical_curies()
This method returns the preferred_curie, name, type of a batch of curies:
```
    canonical_curies = synonymizer.get_canonical_curies(curies)

{
  "CHEBI:5855": {
    "preferred_curie": "CHEBI:5855",
    "preferred_name": "ibuprofen",
    "preferred_type": "chemical_substance"
  },
  "CUI:C0031485": {
    "preferred_curie": "MONDO:0009861",
    "preferred_name": "phenylketonuria",
    "preferred_type": "disease"
  },
  "DOID:14330": {
    "preferred_curie": "MONDO:0005180",
    "preferred_name": "Parkinson disease",
    "preferred_type": "disease"
  },
...
```

One thing left to do: make get_normalizer_results() fully batched. It does batches, but in a slow loop. Needs to do them in parallel.

**Comment by amykglen** [comment]
awesome! I just plugged `get_canonical_curies()` into `expand` - seems to be working great. very speedy!

(I also switched my call to `get_equivalent_curies()` to `get_equivalent_nodes()`, fyi.)

**Comment by edeutsch** [comment]
great, does that mean I can remove `get_equivalent_curies()` from the codebase?

**Comment by dkoslicki** [comment]
@edeutsch quick question: what’s the difference between `get_equivalent_curies` and `get_normalizer_results`?

**Comment by edeutsch** [comment]
`get_equivalent_curies` is now deprecated in favor of `get_equivalent_nodes`.

`get_equivalent_nodes` will give you a list of KG nodes that are equivalent to the input curies. Answers are of course different for KG1 and KG2. It's fast and takes batches of up to 5000 curies at once.

`get_normalizer_results` gives you all relevant information for one or more curies. This is a superset of information than `get_equivalent_nodes`. The return format is compatible with the output of the SRI normalizer and provides more. It includes all equivalent curies, nodes in the specified KG, all name synonyms, preferred names, etc. It can be batched, but the batching is still slow and needs optimization.

**Comment by dkoslicki** [comment]
@edeutsch ah, I see! @chunyuma , perhaps the drug-disease predictions in #758 can be sped up by replacing [this line](https://github.com/RTXteam/RTX/blob/issue758/code/ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py#L67) with `get_equivalent_nodes` (and perhaps batching it) since we only care about KG1 and KG2 nodes (or really, only KG2 since KG1 $\subset$ KG2)

**Comment by finnagin** [comment]
@edeutsch is this something we can close?

**Comment by edeutsch** [comment]
yes, I think this is old. closing.
