### ISSUE TITLE
Need to start versioning our tool

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#92]
As part of the standardized API, *and* for the feedback mechanism to work properly, we need to start versioning RTX. It would be useful to have a centralized class for common attributes and settings and as part of that have a version number. So as new functionality is added, we increase the version number so that I can track answers tied to a specific version.

Maybe a good topic for discussion on Monday or another time.

I plan my feedback mechanism to store responses and the feedback on them. I could do, and was planning, that if a certain question had been asked before and the result stored, and the version of the tool is still the same, I would just return the stored result rather than redo the query. What are the merits of that?

**Comment by dkoslicki** [comment]
I think the idea of using the stored results (if they exist) would be great! Especially since waiting ~30 seconds for a question to be answered is too long imo.

Do you think the whole tool itself should be versioned, or the individual algorithms? I.e do we want an RTX version bump when I change just Q1?

**Comment by edeutsch** [comment]
That is a great question, and I don't know the best answer. At the moment I just have a single "tool_version". But we could track a version per query_type, yes. That would have a the benefit of increasing the cache hit rate for querying code that hasn't changed. But then if a fundamental library common to all/most queries changes, then all would need to be bumped. And what about a change to the KG? Maybe that should trigger a version change as well, because even if the code doesn't change, the answer might change with a different KG. On the flip side, we want each bit of feedback to remain as relevant as long as possible, so there are cases where I need to do the query over again, but if the answer is the same, then reuse the old feedback. It's a tricky problem to which there doesn't seem to be a single brilliant answer. We also need to remember to be diligent about bumping the version number for any checked-in change that might affect the answers. Maybe argue about it on Monday.

**Comment by dkoslicki** [comment]
Yes, it does seem to be a bit nuanced. I see it's on the agenda for the meeting next Monday, so I'll think about it a bit more before then.

**Comment by dkoslicki** [comment]
As per the discussion between @edeutsch and myself, I'll be in charge of bumping the ``RTXConfiguration.py`` version number. [Semantic versioning](https://semver.org/) will be adopted. I.e. for ``x.y.z``:
1. changing ``x`` for MAJOR changes (such as backwards incompatible code/API changes such as major KG updates (renaming/relabeling of node properties), refactoring of code, etc.), 
2. changing``y`` for MINOR changes (such as reasoning code improvements that affect answer results, updates to KG property values)
3. changing ``z`` for PATCHES (such as bug fixes, UI updates, additional nodes added to KG by @saramsey , additions of new query templates, etc). 

These are considered internal, and are in no way associated to the Github releases (i.e. we are still in "alpha" and have yet to create a Github release "1.0" version of the RTX software).

@edeutsch @isbluis I suggest that we dump/clear the cache upon update of ``x`` or ``y`` version numbers (as these are the only that will affect the answers returned by RTX).

If no objections, I will close this issue and adopt this standard.

**Comment by edeutsch** [comment]
Sounds good to me. although item 4 at semver.org still resonates with me at the moment:

4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

I'm still wildly changing the API to better suit the GUI. I would advocate that we continue to poodle around at X=0 until the hackathon.

**Comment by dkoslicki** [comment]
Ok, that's fine with me. I'll keep it ``0.x.y`` until our fist official release.

**Comment by dkoslicki** [comment]
Close in light of #116 and the addition of [RTXConfiguration.py](https://github.com/RTXteam/RTX/blob/master/code/RTXConfiguration.py)
