### ISSUE TITLE
some inverted edges in the new KG2, that have "RO" predicates as the original relations

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#922]
On http://kg2endpoint.rtx.ai:7474/browser/, the very first example I tried: `MATCH (n:disease) RETURN n LIMIT 25` resulted in a (somewhat humorous), issue: are edges `causes` oriented in the correct direction? I see:

`(food intolerance) <-[:causes]- (passing flatus)`

Should this not be:

`(food intolerance) -[:causes]-> (passing flatus)`

Other curious results include:
`(Relaxation:activity_and_behavior)-[:causes]->(Postmortem period:information_content_entity)`
`(Disease:disease)-[:causes]->(growth & development:phenomenon)`
Which all come from SEMMEDDB.

Noting that for "causes" edges:
provided_by | number of edges
-- | --
["SEMMEDDB:"] | 1744522
["OBO:go/extensions/go-plus.owl"] | 724
["OBO:mondo.owl"] | 11150
["monarch.scigraph:"] | 198
["OBO:uberon/ext.owl", "monarch.scigraph:", "OBO:go/extensions/go-plus.owl"] | 32
["OBO:uberon/ext.owl"] | 132
["OBO:uberon/ext.owl", "OBO:go/extensions/go-plus.owl"] | 92
["OBO:nbo.owl"] | 40
["OBO:cl.owl"] | 2
["OBO:doid.owl"] | 1118
["umls_source:NCI"] | 39820
["umls_source:NDFRT"] | 44882
["OMIM:"] | 11538
["umls_source:SNOMEDCT"] | 52510
["ORPHANET:"] | 12164
["EFO:efo.owl"] | 4

And the direction for Non-SEMMEDDB edges are also curious, for example:
`(shellfish allergy:disease)-[:causes]->(Mollusca:organism_taxon)`
comes from OBOLdoid.owl

**Comment by saramsey** [comment]
My investigation of this issue suggests that the edge was not incorrectly inverted in the ETL:

<img width="630" alt="Screen Shot 2020-07-15 at 11 42 42 AM" src="https://user-images.githubusercontent.com/5562107/87583172-688eca00-c690-11ea-9f63-3352fe79978b.png">

**Comment by saramsey** [comment]
See the full sentence from the PMID record:
```
"{'PMID:16984080': {'publication date': '2006 Sep', 'sentence': 'Patients often complain about food intolerances and accuse them of causing diarrhea, constipation, meteorism, flatulence and abdominal pain.', 'subject score': 1000, 'object score': 983}}",
```

**Comment by dkoslicki** [comment]
@saramsey right, so the direction was not correctly ETL'd and the sentence supports this. Did you close this issue because you fixed it? Or did you think it was a non-issue? Didn't see an associated commit...

**Comment by saramsey** [comment]
Er, my mistake, sorry. Didn't read the sentence carefully enough. Let me check....

**Comment by dkoslicki** [comment]
> Er, my mistake, sorry. Didn't read the sentence carefully enough. Let me check....

Ok, no problem! Also, it was at the very bottom, but seems to be an issue not just with SEMMEDDB:

>And the direction for Non-SEMMEDDB edges are also curious, for example:
(shellfish allergy:disease)-[:causes]->(Mollusca:organism_taxon)
comes from OBOLdoid.owl

**Comment by saramsey** [comment]
OK, I have traced the latter issue to the SRI Edge Normalizer, which reported:

<img width="909" alt="Screen Shot 2020-07-15 at 2 28 33 PM" src="https://user-images.githubusercontent.com/5562107/87599430-67699700-c6a8-11ea-950c-a3c1ed80c197.png">

as you can see, the predicate mapping is not correct; there should be some "invert" context passed along, otherwise the mapping is wrong. I have fixed this in `predicate-remap.yaml`, but the larger question is, how many other Relation Ontology (RO) predicates have inverted mappings obtained via the Edge Normalizer?

**Comment by saramsey** [comment]
The original triple from DOID:
```
      "sub" : "http://purl.obolibrary.org/obo/DOID_0060523",
      "pred" : "http://purl.obolibrary.org/obo/RO_0001022",
      "obj" : "http://purl.obolibrary.org/obo/FOODON_00002044"
```

**Comment by saramsey** [comment]
OK, the root cause here is that Relation Ontology has "inversion" in its relationships (see below), and I think these are evidently not being accounted for in the ETL of RO that was done to provide the synonym relationship database used by the Edge NOrmalizer
<img width="284" alt="Screen Shot 2020-07-15 at 2 43 08 PM" src="https://user-images.githubusercontent.com/5562107/87601334-be23a080-c6a9-11ea-918d-2267ad0d3fc1.png">

so I *think* this is a RO-specific issue. Unfortunately, KG2 has a *lot* of RO relations in it. Sigh. It all comes down to manual curation....

**Comment by dkoslicki** [comment]
I don't envy the manual curation... :(
Should we mention this to/open an issue with the SRI Edge Normalizer? Or is this just a problem with how we're using it?

**Comment by saramsey** [comment]
I think it is their issue. I will report it.

**Comment by saramsey** [comment]
Reported https://github.com/TranslatorIIPrototypes/EdgeNormalization/issues/7

**Comment by saramsey** [comment]
Regarding the flatulence issue, see the underlying data in the MySQL database:
```
mysql> select * from PREDICATION where SUBJECT_CUI='C0016204' and OBJECT_CUI='C0149696';
+----------------+-------------+----------+-----------+-------------+--------------+-----------------+-----------------+------------+------------------+----------------+----------------+------------+-----------+-----------+
| PREDICATION_ID | SENTENCE_ID | PMID     | PREDICATE | SUBJECT_CUI | SUBJECT_NAME | SUBJECT_SEMTYPE | SUBJECT_NOVELTY | OBJECT_CUI | OBJECT_NAME      | OBJECT_SEMTYPE | OBJECT_NOVELTY | FACT_VALUE | MOD_SCALE | MOD_VALUE |
+----------------+-------------+----------+-----------+-------------+--------------+-----------------+-----------------+------------+------------------+----------------+----------------+------------+-----------+-----------+
|      119915165 |   113058901 | 16984080 | CAUSES    | C0016204    | Flatulence   | sosy            |               1 | C0149696   | Food intolerance | sosy           |              1 | NULL       | NULL      |      NULL |
+----------------+-------------+----------+-----------+-------------+--------------+-----------------+-----------------+------------+------------------+----------------+----------------+------------+-----------+-----------+
1 row in set (2 min 10.07 sec)

```

**Comment by saramsey** [comment]
I *think* KG2 is doing the right thing here; looks like SemMedDB's algorithm goofed on the edge direction?

**Comment by saramsey** [comment]
labeling this issue as "bug" because of the need to manually curate all the RO entries in `predicate-remap.yaml`.

**Comment by saramsey** [comment]
OK I think we only need to audit RO predicates in `predicate-remap.yaml` that are mapped to an explicitly directional biolink predicate. So we can ignore RO predicates that map to "related to" or "participates in" which are bidirectional.

**Comment by saramsey** [comment]
Manual curation complete. Just need to do a KG2 rebuild and test.

**Comment by saramsey** [comment]
Commencing a rebuild of KG2 starting with `kg2.json`; should take 3-4 hours to get it into Neo4j.

**Comment by saramsey** [comment]
fixed

<img width="476" alt="Screen Shot 2020-07-16 at 11 13 12 AM" src="https://user-images.githubusercontent.com/5562107/87707056-5d51a200-c755-11ea-8adc-6cb47cb06652.png">
