### ISSUE TITLE
Move ARAX over to the NCATS provided server

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#923]
- [x] Email NCATS and let them know we want to take them up on their server offer
- [x] Get NCATS to open necessary ports
- [ ] Figure out solution for RTXConfig which is currently handled on arax.rtx.ai
- [x] Port over image of current Docker container
- [x] rsync /Data from arax.rtx.ai
- [x] Configure container
- [x] Carefully document process
- [ ] Develop dockerfile to replace image porting process

**Comment by finnagin** [comment]
@saramsey who should I be emailing at NCATS to ask for server access?

**Comment by edeutsch** [comment]
Instead of emailing, there is a form:
https://forms.gle/C7jX6n6rANT8WcmZA 
Start there.

**Comment by finnagin** [comment]
Thanks @edeutsch !

**Comment by finnagin** [comment]
1 TB space and AMI should be Ubuntu Server 18.04.

Current Database space requirements - 535 GB

16 cores

current: m5a.4xlarge

ports needed:
7474
7473
7687
80
22
443

**Comment by dkoslicki** [comment]
@finnagin Since we are already on the NCATS server, are we good to close this issue? Were the steps required documented somewhere?

**Comment by finnagin** [comment]
Yes step documented [here.](https://github.com/RTXteam/RTX/blob/master/notes/ARAX/arax-migration-nodes.md) Should be good to close.
