### ISSUE TITLE
write a user engagement plan for ARAX

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#924]

**Comment by dkoslicki** [comment]
To elaborate:

- [ ] find some SME's
- [ ] ask them if [these questions](https://docs.google.com/document/d/1FqbIRCNKQdWZNN92XDdmScTGEsUuFd-6nybBKFbLjXg/edit?usp=sharing) are of interest to them
    - [ ] if they are of interest, ask for the values of `X` and `Y` and try to get some ground truth
    - [ ] if not, ask them what questions would be of interest
- [ ] close the loop and communicate this back to NCATS (in the above doc and on slack or email to NCATS + SRI)

**Comment by saramsey** [comment]
DMK says we need a response to this by "next week" (which I am interpreting to be Wed. 7/22).

**Comment by saramsey** [comment]
[arax-user-engagement-plan.pdf](https://github.com/RTXteam/RTX/files/7212374/arax-user-engagement-plan.pdf)
