### ISSUE TITLE
SEMMEDDB provider node seems to be missing in new build of KG2

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#925]
When I run the following cypher: `match (n) where n.id="SEMMEDDB:" return n` I get `(no changes, no records)`

**Comment by dkoslicki** [comment]
Yeah, I find some nodes, but the id's are definitely messed up:
`match (n) where toLower(n.id) starts with "sem" return n.id limit 15`
returns:

n.id
--
"SEMMEDDB:process_of"
"SEMMEDDB:isa"
"SEMMEDDB:causes"
"SEMMEDDB:location_of"
"SEMMEDDB:part_of"
"SEMMEDDB:produces"
"SEMMEDDB:interacts_with"
"SEMMEDDB:affects"
"SEMMEDDB:treats"
"SEMMEDDB:uses"
"SEMMEDDB:coexists_with"
"SEMMEDDB:diagnoses"
"SEMMEDDB:compared_with"
"SEMMEDDB:inhibits"
"SEMMEDDB:stimulates"

those are relationship types, not CURIES

**Comment by dkoslicki** [comment]
BTW @finnagin , I think you were looking for
`match (n) where n.id starts with "SEMMEDDB:" return count(n)`
which returns 37
instead of `match (n) where n.id="SEMMEDDB:" return n` which would be looking for that _exact_ id

**Comment by saramsey** [comment]
fixed in code (see 909f7a9); thanks @finnagin for reporting this issue

**Comment by saramsey** [comment]
I am working on getting this into the new-new KG2.

**Comment by saramsey** [comment]
doing some graph JSON file surgery to avoid doing a complete new build of SemMedDB from the MySQL source....

**Comment by saramsey** [comment]
Fixed

<img width="1007" alt="Screen Shot 2020-07-16 at 11 05 58 AM" src="https://user-images.githubusercontent.com/5562107/87706459-668e3f00-c754-11ea-9f59-12d94869dad9.png">


Thanks for reporting this issue, @finnagin
