### ISSUE TITLE
in GUI, it would be nice to auto-populate JSON box

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#926]
When one pulls a pre-existing message, or runs something with DSL, or creates a query graphically, etc., it would be a nice touch to populate the JSON input box (tab 3) with the JSON text of the query_graph that comes back from the server.

The only case where this might be undesirable is if the user POSTed JSON, then the returned query_graph might write over what was submitted with a reformatted version that might be slightly different.

Upon reflection, maybe the ideal logic would be:
- If the user submits JSON, then leave it as is
- If the user creates a query_graph via the graphical interface, paste what was submitted into the JSON box
- Otherwise (if the user submits DSL or a canned query or accesses an existing message via ?m=2201) then populate the JSON box with the query_graph that is *returned* from the server.

**Comment by isbluis** [comment]
This is now ready for review in /devLM .

**Comment by edeutsch** [comment]
outstanding!

I just tested with this:
https://arax.rtx.ai/devLM/?m=2650

and see this:
```
{
  "edges": [
    {
      "id": "e00",
      "negated": null,
      "relation": null,
      "source_id": "n00",
      "target_id": "n01",
      "type": null,
      "parentdivnum": 999,
      "source": "n00",
      "target": "n01"
    }
  ],
...
```

First, parentdivnum is a strange interloper. Can that be easily removed?

Second, it would be a nice touch to remove all the null attributes. Not crucial, but maybe it would be relatively easy to iterate through all node and edge attributes and delete the null ones before serializing?

**Comment by isbluis** [comment]
Thanks for testing, @edeutsch !

I have fixed the interloper.

As for the null attributes, would it not be more precise to show exactly what the server received and/or sent?  A more practical issue is: is there a possibility of an attribute being required in the JSON, even if set to null?  In that case, we would be showing potentially incorrect JSON.

**Comment by edeutsch** [comment]
Thanks!

> As for the null attributes, would it not be more precise to show exactly what the server received and/or sent? 

Perhaps more precise. But needlessly I think. And also more unsightly.

> A more practical issue is: is there a possibility of an attribute being required in the JSON, even if set to null? In that case, we would be showing potentially incorrect JSON.

I do not think this is a possibility, but I am not sure. Being absent and having a null value are the same thing as far as the back-end code is concerned I think. When input JSON is marshaled into objects, the expected properties get a default value of None. But then when those objects are serialized by the OpenAPI framework, it serializes them all, not knowing any difference between the user did not provide and the user set to null explicitly. Another valid objection is that the current way allows the user to more easily see all the possible values.

But I thought the pros on cleaning nulls outweighed the cons. But others may disagree.

**Comment by isbluis** [comment]
Ok, null attributes with the JSON returned from the server are now deleted before displaying (and processing).

**Comment by edeutsch** [comment]
looks dandy to me! push it!

**Comment by edeutsch** [comment]
great, rolled out to /beta and /test and seems to work nicely.
