### ISSUE TITLE
Consider using neXtProt instead of UniProt

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#93]
I think I've mentioned this before, we we might do well to consider using neXtProt instead of UniProt for human proteins. They are some degree the same people or at least same place. UniProt is mostly handed over the curation of human proteins to neXtProt, which UniProt mostly focuses on non-human proteins. But not completely. neXtProt tends to be quite web services friendly.

**Comment by saramsey** [comment]
I'm thinking this is an after-hackathon thing, is that right?

**Comment by saramsey** [comment]
OK marking lowpri.  Let's discuss it at the hackathon.

**Comment by dkoslicki** [comment]
Closing due to #788, but @saramsey may have input if neXtProt would be good to use in ARAX/KG2
