### ISSUE TITLE
predict_drug_treats_disease error on beta

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#930]
For this query:
```
{
   "edges": [
      {
         "id": "e00",
         "source_id": "n00",
         "target_id": "n01",
         "type": null
      }
   ],
   "nodes": [
      {
         "id": "n00",
         "curie": "DOID:11830",
         "type": "disease"
      },
      {
         "id": "n01",
         "type": "chemical_substance"
      }
   ]
}
```
at https://arax.rtx.ai/beta/ 
I get the following error:
` 2020-07-16 18:18:59.541734 ERROR:    Traceback (most recent call last): File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py", line 212, in predict_drug_treats_disease all_probabilities = self.pred.prob_all(res) File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/Overlay/predictor/predictor.py", line 241, in prob_all return list(self.prob(X)[:, 1]) File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/Overlay/predictor/predictor.py", line 27, in prob return self.model.predict_proba(X) File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/sklearn/ensemble/_forest.py", line 656, in predict_proba X = self._validate_X_predict(X) File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/sklearn/ensemble/_forest.py", line 412, in _validate_X_predict return self.estimators_[0]._validate_X_predict(X, check_input=True) File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/sklearn/tree/_classes.py", line 380, in _validate_X_predict X = check_array(X, dtype=DTYPE, accept_sparse="csr") File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 556, in check_array "if it contains a single sample.".format(array)) ValueError: Expected 2D array, got 1D array instead: array=[]. Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.`

**Comment by chunyuma** [comment]
@dkoslicki, could you please give me the DSL you ran on beta?

I tested the following DSL and it ran without any problems:
```
add_qnode(curie=DOID:11830, id=n00, type=disease)
add_qnode(type=chemical_substance, id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00,kp=ARAX/KG2)
overlay(action=predict_drug_treats_disease)
resultify()
```

**Comment by chunyuma** [comment]
Problem was solved. Please update the `master` on /beta and I think this issue could be closed.

**Comment by dkoslicki** [comment]
@edeutsch Can you update /beta with the most recent master so we can test there?

**Comment by edeutsch** [comment]
latest code in `master` rolled out to /test and /beta

**Comment by dkoslicki** [comment]
Tested on /beta and confirmed working! closing...
