### ISSUE TITLE
Create a canonicalized KG2 instance

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#944]
As discussed at today's mini-hackathon, having a canonicalized version of KG2 (meaning, a KG2 in which duplicate or synonymous nodes have been collapsed) would be useful in a few ways:

1. Would resolve the FET issue seen in #897 
2. Would provide better data for `predict_drug_treats_disease`
3. Would be nicer for users of the neo4j web browser
4. Would make providing feedback for the `NodeSynonymizer` much easier

So we decided to go for it. The plan for building it is to:

- Use the `NodeSynonymizer` to process the regular KG2 json file to collapse nodes/edges and produce a `kg2-canonicalized.json` file
  - I think we only need bare bones node/edge properties since our current intended use cases don't need info like publications, publications_info, etc., so the input json file could be `kg2-slim.json` (rather than `kg2-simplified.json`) 
- The `kg2-canonicalized` json file can then be translated into tsv files/pushed to its own neo4j instance in a method similar to that of the main KG2 build process (can create modified versions of `kg_json_to_tsv.py` and `tsv_to_neo4j.sh`)
-  Keep its build process separate from the main KG2 build process, since the `NodeSynonymizer` must be rebuilt after completion of a big KG2 build before a canonicalized KG2 build can begin (create a directory within the main `code/kg2` directory for it)

And on the horizon: Maybe one day we can consider whether it might be worth using the canonicalized KG2 instance as our main KG2 instance for ARAX (used by `expand`), but before worrying about that we'll just begin by using it for the above.

**Comment by amykglen** [comment]
@edeutsch - a couple requests for the NodeSynonymizer for this issue:
1. can `get_equivalent_nodes()` be changed to allow an unlimited number of input curies? (like `get_canonical_curies()` does.)  I'm currently running into this error: 
```ERROR: Maximum number of curies is currently 40000. Maybe the limit could be extended```
2. can you add a way to get the list of all node types for each synonym group? (e.g., `[disease, phenotypic_feature, named_thing]`.) FET will need this list. whether that is added to an existing method or to a new one is fine by me. (for building the canonicalized KG2, I currently send all 10 million nodes to both `get_equivalent_nodes()` and `get_canonical_curies()`, fyi.)

**Comment by edeutsch** [comment]
For 1, the answer is yes. I will try to implement this now.

For 2, this is possible, though will slow things down a little. Which current method is closest to how you want to call this? what would be your ideal input and output?

**Comment by amykglen** [comment]
re: 1 - great, thanks!

re: 2 - I think `get_equivalent_nodes()` is closest to how I want to call this...

ideal input:
```
["MONDO:0005520", "NCBITaxon:286"]
```
ideal output:
```
{
   "MONDO:0005520":[
      "disease",
      "unknown_category",
      "phenotypic_feature",
      "biological_process",
      "named_thing"
   ],
   "NCBITaxon:286":[
      "organism_taxon",
      "named_thing",
      "unknown_category"
   ]
}
```
in my current use case, I only plan to input 'preferred' curies to this function (retrieved from `get_canonical_curies()` at an earlier step), but not sure if that matters...

**Comment by edeutsch** [comment]
In you only plan to do this for preferred curries after `get_canonical_curies()`, how about making it an option in get_canonical_curies(), e.g.
```
canonical_curies = synonymizer.get_canonical_curies(curies, return_all_types=True)

{
  "MONDO:0005520": {
    "preferred_curie": "MONDO:0005520",
    "preferred_name": "rickets",
    "preferred_type": "disease",
    "all_types": [
      "disease",
      "unknown_category",
      "phenotypic_feature",
      "biological_process",
      "named_thing"
   ]
  }
```

?

**Comment by amykglen** [comment]
that sounds good to me!

**Comment by amykglen** [comment]
@ericawood @finnagin - would either of you have time/interest in helping to set up/load data into a new neo4j endpoint for the canonicalized KG2?

I've created a script that builds TSV files like those used for the main KG2 build (but called `nodes_c.tsv`, `nodes_c_header.tsv`, `edges_c.tsv`, and `edges_c_header.tsv`) containing the canonicalized KG and uploads them to S3 (rtx-kg2) in a tarball called `kg2-canonicalized-tsv.tar.gz`. 

so I think we'll need a script like `tsv_to_neo4j.sh`, but tailored to this canonicalized KG. and of course we'll need to set up a new instance for this. I also think the `_header.tsv` files will need some modifications (like adding `:TYPE` or whatever else is needed to some columns) - I'm not familiar with importing things to neo4j, so wasn't sure how to set those up properly. I did create a function `_modify_column_headers_for_neo4j()` in [the script that creates the TSVs](https://github.com/RTXteam/RTX/blob/master/code/kg2/canonicalized/create_canonicalized_kg_tsvs.py#L109-L117) where I think any additional modifications could be added..

the final full versions of the TSVs aren't quite ready (I'm waiting on a couple improvements to the NodeSynonymizer before generating the final full files), but I did upload a `kg2-canonicalized-tsv.tar.gz` to S3 containing test versions of the files. (their structure/format is representative of what the full files will look like, so they should work fine for testing/dev work.)

you can also create your own test TSVs by running this (only takes a few seconds):
```
cd RTX/code/kg2/canonicalized
python3 create_canonicalized_kg_tsvs.py --test
```

I've been putting all scripts for this issue in `code/kg2/canonicalized/`.

let me know if you're interested!

**Comment by ericawood** [comment]
@amykglen Thanks for letting me know! I have the time and interest to help. Is there an endpoint that we should use for the canonicalized KG2? Also, when would you like to have the modified `tsv-to-neo4j.sh` ready to go?

**Comment by amykglen** [comment]
awesome, thanks @ericawood! there's not yet an endpoint - maybe we should coordinate with @saramsey to create one? not sure what its name should be... maybe `kg2endpointc` or something like that?

and as far as timing goes - I don't have a hard date in mind, but I know that @dkoslicki is hoping to be able to use this new KG sometime fairly soon for their 'predict drug treats disease' work. does a week from now seem like a reasonable timeframe?

**Comment by ericawood** [comment]
@amykglen That timeline sounds good to me.

**Comment by edeutsch** [comment]
@amykglen new code pushed to `master`:
```
canonical_curies = synonymizer.get_canonical_curies(curies, return_all_types=True)

{
  "MONDO:0005520": {
    "all_types": {                         
      "biological_process": 1,             
      "disease": 14,                       
      "named_thing": 5,                    
      "phenotypic_feature": 1              
    },                                     
    "preferred_curie": "MONDO:0005520",    
    "preferred_name": "rickets",           
    "preferred_type": "disease"            
  }
}
```

How does that work for you?
Note that I opted to make all_types a map instead of list since there's no inherent order and this way I can provide how many of each type there are in case that seems like useful information. OR easy to ignore if not.

Let me know if you;d like changes or have problems.
Note that the node_synonymizer build progress may be broken in this commit. Was in the middle of working on that before I switched to this.

**Comment by amykglen** [comment]
awesome, thanks! hmm, so what does it mean when a canonicalized node it returns doesn't have an `all_types` property? it looks like many are missing such a property. e.g., running this:
```
canonicalized_info = synonymizer.get_canonical_curies(curies=['CUI:C0031965', 'CUI:C0026236', 'CUI:C0010927', 'CUI:C0076080', 'CUI:C0021747', 'CUI:C0009392', 'CUI:C3653438', 'CUI:C0301556', 'CUI:C0024337', 'CUI:C0051080', 'CUI:C0035923', 'CUI:C0025029', 'CUI:C3653163', 'CUI:C0012227', 'CUI:C0360564', 'CUI:C0016301', 'CUI:C3652757', 'CUI:C0011707', 'CUI:C0005308', 'CUI:C3653622', 'CUI:C3653314', 'CUI:C3653542', 'CUI:C0043822', 'CUI:C3653847', 'CUI:C3653224', 'CUI:C0073629', 'CUI:C0209366', 'CUI:C1704311', 'CUI:C0057558', 'CUI:C0025147', 'CUI:C0025175', 'CUI:C0047683', 'CUI:C0028369', 'CUI:C3653753', 'CUI:C3653757', 'CUI:C3652899', 'CUI:C3652895', 'CUI:C3652971', 'CUI:C3652904', 'CUI:C0358590', 'CUI:C3653831', 'CUI:C3652952', 'CUI:C3652998', 'CUI:C3653008', 'CUI:C3652741', 'CUI:C3652496', 'CUI:C3539995', 'CUI:C3653319', 'CUI:C3540023', 'CUI:C3653455', 'CUI:C0024321', 'CUI:C0028356', 'CUI:C0072866', 'CUI:C0023566', 'CUI:C3539994', 'CUI:C3653335', 'CUI:C0003304', 'CUI:C3539975', 'CUI:C2918009', 'CUI:C3652862', 'CUI:C3653108', 'CUI:C0023660', 'CUI:C3653595', 'CUI:C0053114', 'CUI:C0012050', 'CUI:C0058202', 'CUI:C0006405', 'CUI:C0005059', 'CUI:C0025605', 'CUI:C0071810', 'CUI:C0039629', 'CUI:C0772241', 'CUI:C0011892', 'CUI:C3536876', 'CUI:C0065152', 'CUI:C3653602', 'CUI:C0304541', 'CUI:C3652633', 'CUI:C0065988', 'CUI:C0051252', 'CUI:C3653324', 'CUI:C3540793', 'CUI:C3654018', 'CUI:C0051519', 'CUI:C3652662', 'CUI:C0002371', 'CUI:C0002372', 'CUI:C3653283', 'CUI:C0034417', 'CUI:C0025153'], return_all_types=True)
```
returns a bunch of entries with `all_types` listed, like this one:
```
"CUI:C0031965":{
   "preferred_curie":"CHEBI:8242",
   "preferred_name":"pipobroman",
   "preferred_type":"chemical_substance",
   "all_types":{
      "named_thing":3,
      "unknown_category":6,
      "chemical_substance":9,
      "substance":1,
      "metabolite":1
   }
```
but also this entry:
```
"CUI:C0002371":{
   "preferred_curie":"CHEBI:33130",
   "preferred_name":"aluminium hydroxide",
   "preferred_type":"chemical_substance"
}
```
but very strangely, if my input list includes only the above curie that was missing its `all_types`, then `all_types` _does_ appear in the output. e.g.:
```
canonicalized_info = synonymizer.get_canonical_curies(curies=["CUI:C0002371"], return_all_types=True)
```
results in:
```
{
   "CUI:C0002371":{
      "preferred_curie":"CHEBI:33130",
      "preferred_name":"aluminium hydroxide",
      "preferred_type":"chemical_substance",
      "all_types":{
         "named_thing":20,
         "drug":1,
         "unknown_category":61,
         "chemical_substance":51,
         "substance":7,
         "continuant":1,
         "metabolite":1
      }
   }
}
```

**Comment by edeutsch** [comment]
> so what does it mean when a canonicalized node it returns doesn't have an all_types property?

it means I have a bug!

Since I'm trying to do things in parallel, if you provide multiple curies in the same unique concept group, then only one gets the all_types, just because of the way I implemented it. I thought of this while writing the code but then fell asleep and forgot about it.

I will fix.

```
canonicalized_info = synonymizer.get_canonical_curies(curies=["CUI:C0002371", "CUI:C0889200"], return_all_types=True)

{
  "CUI:C0002371": {
    "preferred_curie": "CHEBI:33130",
    "preferred_name": "aluminium hydroxide",
    "preferred_type": "chemical_substance"
  },
  "CUI:C0889200": {
    "all_types": {
      "activity": 2,
      "chemical_substance": 51,
      "continuant": 1,
      "drug": 66,
      "metabolite": 1,
      "named_thing": 14,
      "substance": 7
    },
    "preferred_curie": "CHEBI:33130",
    "preferred_name": "aluminium hydroxide",
    "preferred_type": "chemical_substance"
  }
}
```

**Comment by edeutsch** [comment]
fix pushed to master!

**Comment by amykglen** [comment]
awesome - it's working great now. thanks!

now if `get_equivalent_nodes()` can be given an unlimited batch size, then we'll be good to go!

**Comment by amykglen** [comment]
alright - thanks to @ericawood, KG2 Canonicalized is ready to go at: http://kg2canonicalized.rtx.ai:7474/browser/

the current version is based off of KG2 2.2.0 - it has 60% of the nodes and 72% of the edges of that KG2. it contains minimal node/edge properties (only those needed for our current envisioned use cases).

as a brief tutorial (@dkoslicki, @chunyuma) - here's an example node:
![Screen Shot 2020-08-04 at 3 43 38 PM](https://user-images.githubusercontent.com/49423686/89352773-d021af00-d669-11ea-8c61-e23352dab770.png)

the `preferred_type` is used as the label in neo4j. so these two queries return the same value:
```
match (n:disease) return count(n)                          --> 111424
match (n {preferred_type:'disease'}) return count(n)       --> 111424
```

but note that this one is a bit different:
```
match (n) where 'disease' in n.types return count(n)       --> 206012
```

**Comment by amykglen** [comment]
@finnagin @saramsey - I think we'll need to add an entry to the ARAX `config.json` file for the `kg2canonicalized.rtx.ai` endpoint, so that it can be used by ARAX code. e.g., so that code something like this could work:
```
rtxc = RTXConfiguration()
rtxc.live = "KG2Canonicalized"
driver = GraphDatabase.driver(rtxc.neo4j_bolt, auth=(rtxc.neo4j_username, rtxc.neo4j_password))
```
is that something either of you could help with?

**Comment by chunyuma** [comment]
> as a brief tutorial (@dkoslicki, @chunyuma) - here's an example node:
Thanks @amykglen

**Comment by saramsey** [comment]
OUTSTANDING!

**Comment by amykglen** [comment]
alright, I just edited the master `config.json` on arax.rtx.ai to add the info for `kg2canonicalized`, so now it can be accessed like:
```
rtxc = RTXConfiguration()
rtxc.live = "KG2C"
driver = GraphDatabase.driver(rtxc.neo4j_bolt, auth=(rtxc.neo4j_username, rtxc.neo4j_password))
```
(fyi @chunyuma)

I think that is the final piece here, so I'll close this issue out!
