### ISSUE TITLE
Translator Wave 1 integration use-cases

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#960]
From [this document](https://docs.google.com/document/d/1FqbIRCNKQdWZNN92XDdmScTGEsUuFd-6nybBKFbLjXg/edit?usp=sharing):

We are to:

1. Please comment on the viability of these questions as use-cases that can be answered by ARAs accessing multiple KPs. If you see a potential problem that would make the question difficult to attack, let us know.
2. Please bring these questions to your envisioned potential users, and ask them if these are questions they would like to get answers to. We hope that the users will lead us to any major changes that need to be made to the questions. As well as find particular instances of `X` and `Y` that the SME knows about.

**Comment by saramsey** [comment]
Response 1 from PMI:

> Hi Steve!
> 
> Thanks for your email, and thanks for your work on RTX II, which has
> been invaluable to us!
> 
> I'm cc'ing Matt, Andy, and Jordan as well, since they obviously know
> PMI use cases, along with Michael.
> 
> Here are the NCATS classes of questions:
> 
> 
> Q1. What are some novel treatments that could reduce the symptoms of
> disease X (such as in the context of environmental exposures, genetic
> features, etc)?
> 
> Q2. What genes or proteins may be associated with symptoms of a
> disease X (such as based on drugs that are currently used to treat
> that disease, etc)?
> 
> Q3. What drugs could be repurposed to treat disease X?
> 
> Q4. For a patient with disease X, what are some factors (such as
> genetic features, comorbidities, etc) that could cause sensitivity or
> resistance to drug Y?
> 
> Q5.  If a patient with disease X is treated off-label with drug Y,
> what are some potential side effects?
> 
> 
> Here is my understanding.  Hopefully PMIers can pitch in to correct
> me, or to elaborate.
> 
> Certainly we run Q1 and Q3 queries all the time.
> 
> Q2 is also useful.  Many of our patients already have genes of
> interest identified, so I suspect this query isn't quite as critical
> for us as Q1 and Q2.  Michael, did you run Q2 to get the ARDS gene
> list?  Or was that directly from the literature?
> 
> We would very much like to run Q4 and Q5 queries.  We currently can
> check whether drugs are FDA approved, have passed phase I clinical
> trials, etc.  I'm not sure if we can easily reason about
> patient-specific side effects or drug sensitivity, with the current
> data sets we have.  Do you know if RTX II has data that would be
> useful for Q4 and Q5?  Or which additional data sources we might want
> to bring into RTX II to help with these queries?
> 
> Anyone at PMI running Q4 and Q5 queries, currently?  If so, what do
> those queries look like?
> 
> Thanks!  :)
> 
> Cheers,
> 
> --Will

Response 2 from PMI:

> I see 1,2 and 3 as similar and 4 and 5 as similar.  
>  
> For the first group, you/we are asking how we can impact a disease state through either a symptom or a known treatment of a disease.  When we look at rare genetic disorders, we have a focal point that we start with and work our way out from – that is the gene that has the pathogenic variant.  That patient will also have a phenotype/symptoms to modulate.
> Q1 – what drugs treat symptoms – is very relevant! NOTE – you say ‘novel,’ but it does not have to be.  We would want all information and then decide if it were novel.  (That may be what you meant.)
> Q2 – genes associated with a symptoms – very relevant because it gets to the molecular mechanism possibly underlying the disorder. So, if there were no direct way to attack the disorder, but we could use a symptom-based strategy then that would be useful. 
> Q3 – Drugs that could be repurposed to treat a disorder – in the case of rare diseases, this seems like a big leap that summarizes the analysis of Q1, Q2 plus understanding mechanisms of Q2 and which way to try and later them?  That would be great, but sounds difficult to me.  So, I may be missing something there.  
> One thing that is not called out here, are the gene networks and their regulation related to Q2 genes or the gene with the pathogenic variant.  
>  
> Q4 and Q5 are about safety and efficacy – we would like to do both (as Will said).  At the end of our current process we often have multiple candidates and they need prioritization. We currently have to leave it up to the physician, but that is unrealistic because there is little information to make a decision on.  So, if we could connect dots and create that information, it would be great and helpful in the medical decision support area!
>

**Comment by dkoslicki** [comment]
Closing as use cases/MVP queries were decided a while ago
