### ISSUE TITLE
merge kg2-curie-refactoring branch into master branch

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#962]
This is a reminder to myself to do this some day soon

**Comment by saramsey** [comment]
@dkoslicki and @kvarforl have kindly offered to help with navigating the branch-merging screen(s) in GitHub

**Comment by saramsey** [comment]
@ericawood and @kvarforl have kindly agreed to do the merge when they are ready. Noting this here so others are aware of who to contact if they have questions about the pending merge kg2-curie-refactoring-issue593 -> kg2-curie-refactoring -> master.

**Comment by kvarforl** [comment]
Ran a full build from scratch on KG2, and made it all the way through. Found a bug in tsv_to_neo4j.sh that @ericawood  is tracking down before the merge.
