### ISSUE TITLE
in uniprotkb_dat_to_json.py, convert newlines in "description" field to spaces

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#964]

**Comment by saramsey** [comment]
currently, for text that is going to go into the "description" field, newlines are dropped; they should be converted to spaces

**Comment by ericawood** [comment]
Working on verifying this fix in KG2.5.2 now...

**Comment by ericawood** [comment]
This appears to be fixed in KG2.5.2 based on a test that checked `kg2-uniprotkb.json` for newlines.
