### ISSUE TITLE
Compile list of data/knowledge sources being used by RTX

### ISSUE THREAD

**Issue by parrhesiastic** [RTXteam/RTX#97]
@saramsey Per our discussion at the 2018-04-30 RTX meeting, the NSF EAGER award I am applying for specifically highlights the reuse of data created as a product of NSF-funded research. A list of data/knowledge sources RTX is implementing/ingesting in the knowledge graph/reasoning tool would be helpful to understand what - if any - of these accord with the aforementioned stipulation.

**Comment by saramsey** [comment]
yes, Monarch is NSF supported. NSF-DEB-0956049

https://academic.oup.com/nar/article/45/D1/D712/2605791

**Comment by saramsey** [comment]
Reactome:  The "Plant Reactome" is funded by NSF.  https://www.nsf.gov/awardsearch/showAward?AWD_ID=1127112

**Comment by saramsey** [comment]
UniProt is NSF funded:  DBI-1062520

**Comment by saramsey** [comment]
ChEMBL is probably not NSF funded (it is a European database)

**Comment by parrhesiastic** [comment]
Thanks @saramsey ! This is great for the purposes of the one-pager, which I will circulate to RTX by EOD.

**Comment by saramsey** [comment]
GeneProf is probably not NSF supported; they are in the UK

**Comment by saramsey** [comment]
EBIOLS is probably not NFS supported; they are in Germany & UK

**Comment by saramsey** [comment]
SemMedDB is partly NSF supported:  
https://ischool.illinois.edu/articles/2017/04/schneider-receives-xsede-start-up-award
