### ISSUE TITLE
New DrugBank Download

### ISSUE THREAD

**Issue by ericawood** [RTXteam/RTX#971]
Since DrugBank is locked behind a login, we pull the data from the S3 bucket. There was a new DrugBank database release on July 2nd (Version 5.1.7) vs Version 5.1.6 (from April 22nd), which we are currently using. Should we upgrade?

https://www.drugbank.ca/releases/latest

The release notes indicate there were no significant changes.

https://www.drugbank.ca/release_notes

**Comment by saramsey** [comment]
Good question. Thanks for logging this as a GitHub issue. My inclination is to mark this as "low priority" and for the time being, to focus on (1) getting a clean KG2 build; (2) verifying the integrity of the build, and (3) fixing bugs and verifying the bugfixes.

**Comment by saramsey** [comment]
On the other hand, if it is trivially easy to upgrade DrugBank (I see that it is a a "minor release" so I presume schema shouldn't change?), maybe it is worth just doing it to get it out of the way. IDK.

**Comment by ericawood** [comment]
I'll download it and put it into the S3 bucket under a new name. I will do a test build on kg2erica to see if it still works as intended. I will also generate a reporting script to see if it is worth using.

**Comment by ericawood** [comment]
Version 5.1.7 DrugBank Download:
![image](https://user-images.githubusercontent.com/36611732/88340557-df5f3f00-ccf0-11ea-90a5-97831c0ad250.png)
Version 5.1.6 DrugBank Download:
![image](https://user-images.githubusercontent.com/36611732/88340605-f9991d00-ccf0-11ea-8935-ef014646b43e.png)

Due to the insignificant difference (less edges, but more nodes in the new version), I think that it would be best to stick with the current version for now. Does anyone else have any thoughts?

**Comment by saramsey** [comment]
Hi @ericawood that sounds good. In which case, you can close out this issue, I suppose.
