### ISSUE TITLE
HMDB doesn't link to SMPDB properly

### ISSUE THREAD

**Issue by ericawood** [RTXteam/RTX#976]
Due to mismatches in the number of zeroes preceding the SMPDB IDs, the HMDB IDs did not link to the SMPDB Pathways in KG2. This is a bug within HMDB, but according to support, we can just add two 0's before each ID to make them match.
HMDB Edge:
`        {`
`            "edge label": "in_pathway",`
`            "negated": false,`
`            "object": "SMPDB:SMP00044",`
`            "provided by": "identifiers_org_registry:hmdb",`
`            "publications": [],`
`            "publications info": {},`
`            "relation": "https://identifiers.org/inPathway",`
`            "relation curie": "HMDB:in_pathway",`
`            "subject": "HMDB:HMDB0000001",`
`            "update date": "2019-01-11 19:13:56 UTC"`
`        },`

SMPDB 
https://smpdb.ca/view/SMP0000044

SMP00044 vs SMP**00**00044

**Comment by saramsey** [comment]
Hi @ericawood thanks for bringing this to my attention.

My initial reaction-- my first priority is to make sure that 
1. the HMDB node `iri` URIs correctly resolve
2. the SMPDB node `iri` URIs correctly resolve

So I don't think we should make any changes to the node `id` fields that would make the auto-generated URIs for either of the above-mentioned node types fail to resolve.  And I definitely do not want to have to hack the function that auto-generates the URIs for a node from the node `id` field. I am hoping that we can just fix this in the ETL code for HMDB and fix the cross-reference CURIE ID for the SMPDB node to the format that we *already* have in KG2. Does that make sense?

**Comment by ericawood** [comment]
Yes, as far as I can tell, the URIs are fine for both HMDB and SMPDB (I have not tested everyone, but I have tested multiple). All I am doing is adding the following to the HMDB ETL:
`object_id = "SMP00" + object_id.split("SMP")[1]`
Also, this is only temporary. Their support desk said that they will be fixing this in a later release.

Does that work for you? It is only altering the edges. I could also add the HMDB link into the SMPDB ETL (the PWML files feature HMDB IDs), so that the edges will go both ways.

**Comment by ericawood** [comment]
For future reference, this is the message from HMDB's support team:

> Thank you for reaching out to us. We will be updating the SMPDB IDs in a future download. But it is a predictable change. Two zeroes are added after the "SMP" prefix.

**Comment by saramsey** [comment]
looks good
