### ISSUE TITLE
neo4j-admin set-initial-password doesn't seem to work on a brand-new instance

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#983]
perhaps this is because install-neo4j.sh is auto-starting the neo4j server??

**Comment by ericawood** [comment]
neo4j-admin set-initial-password must be done while Neo4j is **off** (similar to neo4j-admin import). I suggest that we use the same "trick" we are doing in tsv-to-neo4j.sh to read the password from the config file and set the password that way.

**Comment by saramsey** [comment]
Hi @ericawood -- thank you, that is a good point, and helpful to know.

Indeed, the script `setup-kg2-neo4j.sh` (as of last week?) copies the `RTXConfiguration-config.json` file from the S3 bucket to the local EC2 instance and uses that configuration information in attempting to (automatically) set the Neo4j password via `neo4j-admin set-initial-password`. However, it appears that setting the password in this manner is not working, perhaps for the reason you suggest. I suspect that when Neo4j is installed via `apt-get` in the script `install-neo4j.sh`, the Neo4j server is automatically started. I hope you are right, that the issue is just that Neo4j needs to be stopped in order for the `set-initial-password` to work. I will investigate (now that I have Docker working on my MBP, this is much more convenient to test locally).

**Comment by saramsey** [comment]
I am working on this issue now...
