### ISSUE TITLE
Is Relation Ontology's KP Node supposed to be of type relationship_type rather than type data_file?

### ISSUE THREAD

**Issue by ericawood** [RTXteam/RTX#984]
@saramsey, what are your thoughts on this?

![image](https://user-images.githubusercontent.com/36611732/88574802-bba13f00-cff7-11ea-8cff-8e87fc4ad838.png)

![image](https://user-images.githubusercontent.com/36611732/88575183-4eda7480-cff8-11ea-926f-16d080759199.png)

![image](https://user-images.githubusercontent.com/36611732/88575396-a973d080-cff8-11ea-80e8-d012ba903770.png)

**Comment by saramsey** [comment]
This is a bug.

**Comment by saramsey** [comment]
commits 4117ee8 and 64acc5e should fix this; need to more fully test in the next KG2 build to make sure that there are no bugs introduced by this fix, as the fix was kind of complex for such an innocuous-looking issue

**Comment by saramsey** [comment]
Appears to be fixed. This is a query on `kg2erica.rtx.ai`:

<img width="709" alt="Screen Shot 2020-08-11 at 10 15 32 AM" src="https://user-images.githubusercontent.com/5562107/89927779-b2999b80-dbbb-11ea-9993-3ce862416973.png">
