### ISSUE TITLE
Formal names for KG2s?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#988]
I wonder if there are formal names/versions for KG2s? Will Byrd calls it RTX II, but I wonder which version of KG2 he means. And then we have the KG2 that's currently in production, but that may be newer than the older KG2? And then Amy is testing the newer KG2 that seems to be causing a problem for NodeSynonymizer.

I'm wondering if we might benefit from a mechanism by which we have formal release numbers or version dates (2020-07b) so that we can be precise about which KG2 we mean? Or does that already exist?

**Comment by saramsey** [comment]
Hi @edeutsch KG2 now has (per #610) a node with ID `RTX:KG2` which contains the date/timestamp (ISO 8601) of the build.

<img width="491" alt="Screen Shot 2020-07-28 at 3 19 32 PM" src="https://user-images.githubusercontent.com/5562107/88728081-c9cd8900-d0e5-11ea-801e-32559fa26326.png">

This date/timestamp is also embedded in the upstream JSON version of KG2 (which neither ARAX nor mediKanren don't see, but which we may use for other purposes) in the top-level slot `build` (it's sister slots in the JSON file are `nodes` and `edges`).

**Comment by saramsey** [comment]
This infor

**Comment by saramsey** [comment]
We could probably do a better job on branding KG2 and using consistent nomenclature. The "2" in "KG2" is not meant to be a build version, but just to distinguish it from the first-generation knowledge-graph.

**Comment by saramsey** [comment]
Please let me know if there is anything else actionable here for the KG2 team.

**Comment by edeutsch** [comment]
I suppose the action is either to provide formal labels for each of the builds out there or declare that all builds of KG2 have the same label "KG2" and we will continue to make up our own pet names to try to distinguish them. I've been calling the KG2 at kg2endpoint the "new KG2++", whereas the one at kg2endpoint2 is just "KG2". Or maybe I've gotten that backwards.

**Comment by dkoslicki** [comment]
Maybe we should start semantic versioning it?

**Comment by edeutsch** [comment]
As in giving it a URI?

That'd be fine with me, but I would also encourage a short label that we can speak and type when referring to the different versions.

**Comment by dkoslicki** [comment]
>Maybe we should start semantic versioning it?

KG<major>.<minor>.<patch>

KG2.0.0 (that's on arax.rtx.ai)

KG2.1.x (thats on kg2endpoint<whatever>.ai)

Or just:
KG<major>.<minor>

**Comment by edeutsch** [comment]
I like this. Maybe we can agree on exact versions here. Here's my proposal:

Current kg2endpoint2.rtx.ai:7474 we will call it "RTX KG2.1.0"  (this is current production for arax.rtx.ai) (I set it to 2.1 because there were earlier versions of KG2?? now obsolete?)

Current kg2endpoint.rtx.ai:7474 will be "RTX KG2.2.0" (this is undergoing some testing by David and Amy?)

Do we like these versionings? Or do those that are more familiar with the different builds want to alter this?

**Comment by ericawood** [comment]
Should we keep the version number in the S3 bucket and increment it during each build (if not "test" mode)? For example, we could have a script that pulls it down, adds to the minor number (ex. 2.2.0 -> 2.2.1), then pushes it back up in addition to storing it in the JSON dump of KG2.

**Comment by edeutsch** [comment]
sounds good to me!

**Comment by saramsey** [comment]
Erica's ideas about this:
1. Before `filter_kg_and_remap_predicates.py`, a bash script is run (I'll call it `version.sh`)
`version.sh` pulls existing version file from S3 bucket. (All this file has in it is `X.Y.X`, where `X`, `Y`, and `Z` make up the version)
2. `version.sh` passes that file into version.py which increments the minor number (`Z`) using string manipulation if `--increment` flag is run with it
3. `version.sh` puts the updated file into the S3 bucket
4. `filter_kg_and_remap_predicates.py` reads that file (which would be stored locally now) and stores the version in the "name" field of the build node

**Comment by saramsey** [comment]
@ericawood let's put the version string in the `name` field for the `RTX:KG2` node.

**Comment by saramsey** [comment]
As for URIs, that's gonna be more complicated. We don't currently host archival (old) versions of the KG2 JSON file or TSV files, and I'm not sure when we will do so. Maybe at some point we will host them in S3, in which case there could be an S3 URI?

**Comment by saramsey** [comment]
> I like this. Maybe we can agree on exact versions here. Here's my proposal:
> 
> Current kg2endpoint2.rtx.ai:7474 we will call it "RTX KG2.1.0" (this is current production for arax.rtx.ai) (I set it to 2.1 because there were earlier versions of KG2?? now obsolete?)
> 
> Current kg2endpoint.rtx.ai:7474 will be "RTX KG2.2.0" (this is undergoing some testing by David and Amy?)
> 
> Do we like these versionings? Or do those that are more familiar with the different builds want to alter this?

Sure.

**Comment by saramsey** [comment]
Folks, just so everyone understands -- if we implement @ericawood 's excellent proposal outlined above, *not all builds will see the light of day*. I fully expect that many builds, due to bugs which get fixed, will never be deployed to the production system. So the sequence of version numbers of builds that ever get hosted on the production KG2 server might well look like:

`RTX KG2.1.0`
`RTX KG2.2.5`
`RTX KG2.2.12`

etc...  I am personally fine with this, but just wanting to make sure that everyone is aware of how this will work in practice. The current proposal on the table is *not* to just sequentially version deployed KG2 builds, but *all* KG2 builds. 

The virtue of @ericawood 's proposal is that is simple and automated. And we get a human-friendly version number even for builds that we never end up deploying, which is good for the KG2 developers.

**Comment by saramsey** [comment]
I propose that we *only* bump the middle number when the *schema* (or data model) changes.

**Comment by edeutsch** [comment]
This is fine for me.

**Comment by ericawood** [comment]
Here is what the updated build node looks like (though the version number listed is not correct -- I've been running tests and will fix it later):

![image](https://user-images.githubusercontent.com/36611732/88973109-77b67000-d26b-11ea-8989-6554827afb20.png)

**Comment by ericawood** [comment]
Commits 6c2f6a6fe62d7fcf495bc88f9c6091e6e298e773, df7fa71658fa7cb62c7e1f669cf8fa2ff3225193, and a00608a268ed6646e44828a9eb85f3f6e5f73261 should cover this issue. I'm going to add the test in next KG2 build, since I have only tested it in "test" mode. I have also updated kg2-version.txt in the public S3 bucket to specify that we are currently on version 2.2.0. Please let me know if you have any suggestions.

**Comment by ericawood** [comment]
This is from the version of KG2 that Lindsey just built: (currently in kg2erica and I'm 90% sure in the S3 bucket)

![image](https://user-images.githubusercontent.com/36611732/89810044-494d5600-daf1-11ea-8a8f-074f7aaa200f.png)

Can I close this out?

**Comment by ericawood** [comment]
@saramsey One quick note - right now, it increases the version even in a test build. Do we want it that way? Maybe a separate version increment file?

**Comment by saramsey** [comment]
Hi @ericawood can we make is so that if it is a test build, it (1) doesn't increment the version, and (2) just appends "-TEST" or something to the build name?  So if the previous build had `name` field `RT KG2.2.2`, the test build would have `name` field `RT KG2.2.2-TEST` or something?

**Comment by ericawood** [comment]
> (1) doesn't increment the version, and (2) just appends "-TEST" or something to the build name? So if the previous build had name field RT KG2.2.2, the test build would have name field RT KG2.2.2-TEST or something?

Hi @saramsey, that should be addressed in b4349351873989335d85eb6733929c78f15b9363. I have tested it on kg2dev. Thank you for your feedback!

**Comment by saramsey** [comment]
In my Aug. 11 test run on `kg2steve.rtx.ai`, the results are looking good here.

In the `kg2-simplified-test-nodes.json.gz` file, the top-level `build` slot:

<img width="390" alt="Screen Shot 2020-08-11 at 9 46 00 AM" src="https://user-images.githubusercontent.com/5562107/89924907-84b25800-dbb7-11ea-932e-a17bb0fed2b7.png">

and the corresponding node under the `nodes` list is:

<img width="425" alt="Screen Shot 2020-08-11 at 9 47 29 AM" src="https://user-images.githubusercontent.com/5562107/89925140-da870000-dbb7-11ea-8505-e4876891196e.png">

**Comment by ericawood** [comment]
@saramsey It still increased the version to 2.2.3 (see commit b6e2e76eb32cdcfbafaac1b45af139d901122abe) which just fixed that. I'm sorry about this, I will fix the version in AWS S3.

**Comment by saramsey** [comment]
Good catch, @ericawood thank you.

**Comment by saramsey** [comment]
Also, upon reflection, I feel that the top-level `build` slot in the KG is a bit cluttered. Proposing to change it thus:

<img width="711" alt="Screen Shot 2020-08-11 at 9 51 45 AM" src="https://user-images.githubusercontent.com/5562107/89925454-49fcef80-dbb8-11ea-8cea-d5fc93900c32.png">

**Comment by saramsey** [comment]
Hey @ericawood can you update `README.md` to document that the version of KG2 is tracked in S3, and note the specific file in S3 in which the version is tracked? That could be useful information for a future maintainer of KG2.

**Comment by ericawood** [comment]
> can you update README.md to document that the version of KG2 is tracked in S3, and note the specific file in S3 in which the version is tracked? That could be useful information for a future maintainer of KG2.

Yes, I will work on that.

> Also, upon reflection, I feel that the top-level build slot in the KG is a bit cluttered. Proposing to change it thus:

Will that change also impact the build node (not the build info)? Or is this just for the appearance of the JSON file?

**Comment by saramsey** [comment]
> Will that change also impact the build node (not the build info)? Or is this just for the appearance of the JSON file?

I believe this change will only affect the top-level `build` node. Are we depending on the specific format of that data structure, downstream in the build process?

**Comment by ericawood** [comment]
> I believe this change will only affect the top-level build slot in the JSON, not the RTX:KG2 node under nodes. Are we depending on the specific format of that data structure, downstream in the build process?

Ok, kg_json_to_tsv depends on the RTX:KG2 node under node. I don't think that anything depends on the build node, though I know that [create_canonicalized_kg_tsvs.py](https://github.com/RTXteam/RTX/blob/master/code/kg2/canonicalized/create_canonicalized_kg_tsvs.py) does create a new build node (see line 75).

**Comment by saramsey** [comment]
> > I believe this change will only affect the top-level build slot in the JSON, not the RTX:KG2 node under nodes. Are we depending on the specific format of that data structure, downstream in the build process?
> 
> Ok, kg_json_to_tsv depends on the RTX:KG2 node under node. I don't think that anything depends on the build node, though I know that [create_canonicalized_kg_tsvs.py](https://github.com/RTXteam/RTX/blob/master/code/kg2/canonicalized/create_canonicalized_kg_tsvs.py) does create a new build node (see line 75).

Thank you for the heads-up. On quick inspection of `create_canonicalized_kg_tsvs.py`, I don't think my changes to `filter_kg_and_remap_predicates.py` should break anything.

**Comment by saramsey** [comment]
@ericawood :  Please note, I added a ".rstrip()" method call here (L166):

<img width="435" alt="Screen Shot 2020-08-11 at 10 43 07 AM" src="https://user-images.githubusercontent.com/5562107/89930350-7a945780-dbbf-11ea-9f61-9e7efb9a1c4e.png">

to avoid having a newline in the build version in the case of a test build.

**Comment by saramsey** [comment]
Hi @ericawood it looks like `update_version.py` contains mixed spaces and tabs; can you please convert to all spaces when you have a chance?

Also, would it make sense to modify `version.sh` so that if "test" is specified, it doesn't even call `update_version.py` or upload the version file to the S3 bucket?  In the case of a test build, it is unclear why we want to re-generate the local `kg2-version.txt` file or why we want to re-upload it to S3.

**Comment by ericawood** [comment]
@saramsey Yes, that modification would make sense, though I think we should still get the kg2-version.txt from the S3 bucket, in case it is a fresh build and it doesn't already exist.

**Comment by saramsey** [comment]
OK, `kg2endpoint.rtx.ai` now (internally) has version number 2.2.0, as agreed above:

<img width="671" alt="Screen Shot 2020-08-19 at 2 27 53 PM" src="https://user-images.githubusercontent.com/5562107/90691465-3bea4700-e228-11ea-80e8-d3f8a29af5d8.png">

**Comment by saramsey** [comment]
Per minutes from 2020.08.19 AHM,
https://docs.google.com/document/d/1SHMwq1aiqgUmBWhb6c_vHGH8G3VF6ssvL2vlhfMwOCg/edit

I am setting up two CNAME entries as follows:
- `kg2endpoint-kg2-1-0.rtx.ai` `-->` `kg2endpoint2.rtx.ai`
- `kg2endpoint-kg2-2-0.rtx.ai` `-->` `kg2endpoint.rtx.ai`

<img width="654" alt="Screen Shot 2020-08-19 at 2 32 32 PM" src="https://user-images.githubusercontent.com/5562107/90692284-b798c380-e229-11ea-8f8d-c268a4345706.png">

**Comment by edeutsch** [comment]
and shall we update config.json to use the aliases?

**Comment by saramsey** [comment]
<img width="678" alt="Screen Shot 2020-08-19 at 2 40 55 PM" src="https://user-images.githubusercontent.com/5562107/90692612-41e12780-e22a-11ea-83b9-d529b62b77aa.png">

**Comment by saramsey** [comment]
<img width="653" alt="Screen Shot 2020-08-19 at 2 43 57 PM" src="https://user-images.githubusercontent.com/5562107/90692720-6fc66c00-e22a-11ea-8f25-3a5ec90ea1e0.png">

**Comment by saramsey** [comment]
Updated `/mnt/temp/config.json` on `arax.rtx.ai`:
```
$ diff config.json-20200819 config.json
31,32c31,32
<             "bolt": "bolt://kg2endpoint2.rtx.ai:7687",
<             "database": "kg2endpoint2.rtx.ai:7474/db/data",
---
>             "bolt": "bolt://kg2endpoint-kg2-1-0.rtx.ai:7687",
>             "database": "kg2endpoint-kg2-1-0.rtx.ai:7474/db/data",
```

**Comment by saramsey** [comment]
Updated to add a `KG2-test` slot in `config.json`:
```
$ diff config.json-new config.json-20200819
31,32c31,32
<             "bolt": "bolt://kg2endpoint-kg2-1-0.rtx.ai:7687",
<             "database": "kg2endpoint-kg2-1-0.rtx.ai:7474/db/data",
---
>             "bolt": "bolt://kg2endpoint2.rtx.ai:7687",
>             "database": "kg2endpoint2.rtx.ai:7474/db/data",
83c83
<     "KG2-test": {
---
>     "rtxdev": {
85,86c85,86
<             "bolt": "bolt://kg2endpoint-kg2-2-0:7687",
<             "database": "kg2endpoint-kg2-2-0:7474/db/data",
---
>             "bolt": "bolt://rtxdev.saramsey.org:7887",
>             "database": "rtxdev.saramsey.org:7674/db/data",
```
