### ISSUE TITLE
UI points to wrong documentation

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#992]
Currently `One line per DSL command, no quotes or commas; more info here` points to:
https://github.com/RTXteam/RTX/blob/demo/code/ARAX/Documentation/DSL_Documentation.md 
but should point here:
https://github.com/RTXteam/RTX/blob/master/code/ARAX/Documentation/DSL_Documentation.md

**Comment by dkoslicki** [comment]
@isbluis LMK if I fixed this in the right place and feel free to re-open if I did not

**Comment by isbluis** [comment]
That looks good, @dkoslicki .  Thanks for the quick fix!

**Comment by dkoslicki** [comment]
Don’t know how this snuck back in, but @isbluis and @edeutsch, https://arax.rtx.ai/ still has the wrong documentation link listed (see above, not near a desktop otherwise I would fix it myself if it’s a problem in `master`)

**Comment by amykglen** [comment]
I think maybe this code just hasn't made it to production yet? the link is correct on https://arax.rtx.ai/test/. (goes to: https://github.com/RTXteam/RTX/blob/master/code/ARAX/Documentation/DSL_Documentation.md)

**Comment by edeutsch** [comment]
yes, we are due to roll out to production, but there seem to be lingering errors on /test and I am hesitant to roll out to production until we have something that doesn't crash. Would be great to roll out to production later today.

**Comment by isbluis** [comment]
It looks like this has been fixed.  Can you verify and close if ok, @dkoslicki ?

**Comment by dkoslicki** [comment]
Looks good to me! Closing
