### ISSUE TITLE
How should Expand merge non-"core" node properties when coalescing nodes?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#993]
So `expand` currently coalesces/canonicalizes equivalent nodes, but it doesn't yet attempt to do any sort of merging of non-"core" node properties, such as `provided_by`, `description`, or even `uri`. (I'm considering `id`, `name`, and `type` the "core" properties.) This means we end up with some funny looking nodes in the results:

<img width="820" alt="Screen Shot 2020-07-30 at 4 09 01 PM" src="https://user-images.githubusercontent.com/49423686/88983446-ea314b00-d27f-11ea-89bc-3605a1ab2956.png">

You can see how while this node's `id` has a MONDO: curie (the 'preferred' curie for its synonym group according to the synonymizer), its `uri` and `provided_by` refer to SNOMEDCT. And its `category` attribute says it's a phenotypic feature, in contrast to its `type`, which is disease. All this strangeness occurs because, for the non-core properties, `expand` currently just keeps whatever they were on the first node it encounters from each synonym group. So really this node we're looking at might represent three different Parkinson's nodes in KG2, all with different `provided_by`s and etc., but we're only seeing the values of the properties from one of the three (except for the three "core" properties, which have been canonicalized).

Seems like at some point we will probably want to decide what to do about this.. but not sure it's super urgent since these are non-core properties.

**Comment by saramsey** [comment]
Hi @amykglen see `kg2_util.merge_two_dicts`, maybe there is some useful logic in there?

**Comment by amykglen** [comment]
think all of these questions have been handled in KG2c (id, name, category, iri, and description come from the leader of the synonym group; provided_by and publications come from all coalesced nodes. and description is being further discussed in #1316)
