### ISSUE TITLE
Allow unlimited batch size for NodeSynonymizer.get_equivalent_nodes()

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#997]
I requested this in #944, but figured I should pull it out into it's own issue.

We're currently running into this error when attempting to use `NodeSynonymizer.get_equivalent_nodes()` in creating the canonicalized KG2:
```
ERROR: Maximum number of curies is currently 40000. Maybe the limit could be extended
```
It'd be great if this method could be modified to allow unlimited batch size, like was done for `get_canonical_curies()` in #932.

**Comment by edeutsch** [comment]
Sorry for my slothfulness. Definitely a good idea to separate issue.
Fix pushed to `master`. Not well tested. Let me know if it works for you!
Who will win the prize for issue 1000?

**Comment by amykglen** [comment]
awesome - yes, it seems to be working well! thanks!

(the change to the output format in your commit broke `create_canonicalized_kg_tsvs.py`, but @ericawood already fixed that for us.)

**Comment by edeutsch** [comment]
I'm happy to adjust the output format to whatever is most efficient for your use.

**Comment by amykglen** [comment]
thanks - I think the current format is good.

all seems well on `/test`! closing.
