### ISSUE TITLE
In KG2 Neo4j, node publications and synonyms (and relationship publications) are not Neo4j lists?  can we fix that?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#998]
I note that in Neo4j (`kg2endpoint.rtx.ai:7474`), for whatever reason, the `synonyms` property of a node is a Neo4j string and not a Neo4j list:
<img width="431" alt="Screen Shot 2020-08-04 at 11 44 24 AM" src="https://user-images.githubusercontent.com/5562107/89332290-00f0ec80-d648-11ea-8b48-1cb646f71c3b.png">

The same goes for the `publications` property of a node:
<img width="392" alt="Screen Shot 2020-08-04 at 11 45 38 AM" src="https://user-images.githubusercontent.com/5562107/89332307-0cdcae80-d648-11ea-93f1-77bc1f4035a3.png">

In contrast, the `provided_by` relationship property is an actual, honest-to-goodness Neo4j list:
<img width="384" alt="Screen Shot 2020-08-04 at 11 46 18 AM" src="https://user-images.githubusercontent.com/5562107/89332394-2c73d700-d648-11ea-970a-37f554a62bd5.png">

(but note again, on the example relationship record shown, the `publications` property is a Neo4j string and not a Neo4j list).

I would like to fix this in `kg_json_to_tsv.py`. I'm not sure if this would also require some tweaks to `tsv-to-neo4j.sh`. 

But.... I'm mindful that this may cause some code changes in the Node Synonymizer and elsewhere in the code base. So I guess we should start with a conversation about the cost/benefit.

**Comment by ericawood** [comment]
It would not be very difficult to fix in `kg_json_to_tsv.py` and `tsv-to-neo4j.sh` is already set up to work with the fix, due to the `provided_by` edge property.

**Comment by amykglen** [comment]
I'm in favor of making these actual lists; I don't think it will disturb ARAX code. `expand` currently converts these fields to actual lists when populating nodes in the API model. (and I believe even the conversion step wouldn't break if these fields were actual lists to begin with.) so if any other modules are accessing `publications`/`synonym` on nodes/edges in `Message.KnowledgeGraph`, they're already using those fields in their list form.

I also do the same thing when using `synonym` in the script I wrote for the `NodeSynonymizer` (convert it to an actual list using the same method). and I don't believe the `NodeSynonymizer` otherwise touches these properties.

so I think it'd be great to change these to actual lists; I'd happily go into the ARAX code and remove my conversion steps.

**Comment by edeutsch** [comment]
Switching to real lists seems like a good thing from my point of view, but I am minimally affected if at all.

**Comment by saramsey** [comment]
> It would not be difficult to fix in `kg_json_to_tsv.py` and `tsv-to-neo4j.sh` is already set up to work with the fix, due to the `provided_by` edge property.

@ericawood great, can you please make the change?  Let's make this change in the `kg2-curie-refactoring` branch.

**Comment by saramsey** [comment]
@ericawood has generously agreed to take the lead on this issue

**Comment by ericawood** [comment]
I tested this on an older kg2-simplified.json and it appears to be working. (However, now if there are no synonyms/publications for a node, those fields do not show up). Below are some examples from Neo4j:

**Edge with publications**
![image](https://user-images.githubusercontent.com/36611732/89584745-70eea680-d7f1-11ea-82d8-e8749af7f90f.png)

**Edge without publications**
![image](https://user-images.githubusercontent.com/36611732/89585537-ddb67080-d7f2-11ea-9571-f87437561da0.png)

**Node with publications and synonyms**
![image](https://user-images.githubusercontent.com/36611732/89584925-c4f98b00-d7f1-11ea-964f-6050fd12be23.png)

**Node without publications or synonyms**
![image](https://user-images.githubusercontent.com/36611732/89585111-215caa80-d7f2-11ea-8748-71d6e3c8600b.png)

**Node without publications but with synonyms**
![image](https://user-images.githubusercontent.com/36611732/89585262-67197300-d7f2-11ea-8d90-7550bd836791.png)

**Node without synonyms but with publications**
![image](https://user-images.githubusercontent.com/36611732/89585388-9e881f80-d7f2-11ea-930b-721e6a1b827c.png)

**Comment by ericawood** [comment]
This is fixed in the latest build by Lindsey (which is currently in Neo4j on kg2erica and I'm 90% sure the TSV files are in the S3 bucket). Can I close this out?

**Comment by saramsey** [comment]
Looks good, thank you @ericawood.
