### ISSUE TITLE
content of kg2-ont.json is changing from run to run

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#999]

**Comment by saramsey** [comment]
Thank you to @ericawood for bringing this issue to my attention

**Comment by saramsey** [comment]
Report from @ericawood:

> Hi Steve,
> After more digging, here is what I have discovered:
> - As far as I can tell, the JSON files have the same content
> - The `go-plus.owl` files are the same every time
> - The `go-plus.json` and `umls-go.json` files are in a different order each time
> - The resulting KG JSON files appear to have the exact same edges (though not necessarily in the same order)
> - The resulting KG JSON files appear to have the same nodes, though the synonym fields are in different orders, which triggers my JSON equivalency validation code to assume that each file is missing a node that is actually the same node. The wording here is very difficult, so here is a screenshot:

**Comment by ericawood** [comment]
Here's a snapshot of the diff log between go-plus.json files that were generated by the same code one right after the other:
![image](https://user-images.githubusercontent.com/36611732/89341752-a0b57700-d656-11ea-97b8-cd8b717a281d.png)

Here's a chunk of the two go-plus.json files side by side:
![image](https://user-images.githubusercontent.com/36611732/89341923-e2462200-d656-11ea-8369-c42bcc9b6d84.png)

**Comment by saramsey** [comment]
@ericawood I think I've fixed the synonym issue with f84eecc

As for the ordering of the JSON files generated by ROBOT from TTL files, more investigation required...

**Comment by saramsey** [comment]
@ericawood can you test to see if the synonym ordering is now consistent?

**Comment by saramsey** [comment]
Ah, I think I need to make a second tweak to `multi_ont_to_json_kg.py`

**Comment by ericawood** [comment]
@saramsey I ran the test to see if synonym ordering is now consistent. I found that the publications list is also not consistent:
![image](https://user-images.githubusercontent.com/36611732/89444871-3d375200-d707-11ea-9d7c-a542c023fc02.png)

The synonyms issue appears to be resolved though.

**Comment by saramsey** [comment]
@ericawood for the publications issue, can you please see if commits f128541 and 329e973 fix the issue?

**Comment by ericawood** [comment]
@saramsey The publications issue was fixed. However, there is another issue. For multiple CHEBI nodes, two nodes with the same ID have different categories (and category labels) depending on the file. Here is an example:  
![image](https://user-images.githubusercontent.com/36611732/89562309-9fa75580-d7ce-11ea-96b1-8c5ca6403303.png)

**Comment by saramsey** [comment]
Hi @ericawood thanks for bringing the CHEBI example to my attention. I wonder if changing the order of `ont-load-inventory.yaml` so that `chebi.owl` is loaded *before* `go-plus.owl` would solve this issue. I would like to test this idea. Can you please describe for me exactly how to reproduce the CHEBI problem?  i.e., which scripts I should run and which files I should inspect to see the problem?  Thanks.

**Comment by ericawood** [comment]
Hi @saramsey 
> Can you please describe for me exactly how to reproduce the CHEBI problem? i.e., which scripts I should run and which files I should inspect to see the problem?

Here are the steps:
1. `cd ~`

2. `mkdir SnakemakeDebugging` <- This is just a place to put the log files so that you can easily find them, feel free to name it something different

3. `cd SnakemakeDebugging`

4. `~/kg2-venv/bin/python3 -u ~/kg2-code/multi_ont_to_json_kg.py --test ~/kg2-code/curies-to-categories.yaml ~/kg2-code/curies-to-urls-map.yaml ~/kg2-code/ont-load-inventory-test-go.yaml ~/kg2-build/kg2-ont-go1.json >~/kg2-build/build-kg2-ont-go-stderr8-11--1.log 2>&1` <- A few notes here: 
    (1) `~/kg2-build/kg2-ont-go1.json` is the output files that you will be comparing (the 1 refers to it being the first one). If you choose to name it something different, make sure that it is easy to differentiate output files 1 and 2. 
    (2) This is going to take a while. Expect it to take upwards of an hour. 
    (3) In `~/kg2-build/build-kg2-ont-go-stderr8-11--1.log` the `8-11` refers to the date and the `--1` refers to this being the first run. I like to keep the output from each run through separate. 
    (4) You might also choose to put `kg2-ont-go1.json` and `build-kg2-ont-go-stderr8-11--1.log` in `SnakemakeDebugging`. It is your choice, it won't break anything.

5. `~/kg2-venv/bin/python3 -u ~/kg2-code/multi_ont_to_json_kg.py --test ~/kg2-code/curies-to-categories.yaml ~/kg2-code/curies-to-urls-map.yaml ~/kg2-code/ont-load-inventory-test-go.yaml ~/kg2-build/kg2-ont-go2.json >~/kg2-build/build-kg2-ont-go-stderr8-11--2.log 2>&1` <- See notes from step 4 and adjust accordingly for "round" 2

6. Ask Erica for access to check_missing.py (my custom script to produce the output above) and put it in `SnakemakeDebugging`

7. `~/kg2-venv/bin/python3 -u check_missing.py ~/kg2-build/kg2-ont-go1.json ~/kg2-build/kg2-ont-go2.json > g1g2difference.log 2>&1` <- `~/kg2-build/kg2-ont-go1.json` refers to the first file that you generated. **It will be referred to as "A" in the log file.** `~/kg2-build/kg2-ont-go2.json` refers to the second file that you generated. **It will be referred to as "B" in the log file.** `g1g2difference.log` is the file that the data you are looking for will be in.

8. Open two terminals side by side and open `g1g2difference.log` in the editor of your choice **in both**. In one terminal, search for "A MISSING NODES". In the other, search for "B MISSING NODES". Unlike diff, each output shows you a node that is present in one of the two output files and not the other, such that order doesn't matter. "A MISSING NODES" refers to nodes that are in file "A" but not in file "B". "B MISSING NODES" refers to nodes that are in file "B" but not in file "A". 

Please let me know if you have any questions!

**Comment by saramsey** [comment]
Thanks for the detailed instructions.

**Comment by saramsey** [comment]
OK, small progress. I managed to make a simpler test-case. Using this file `ont-load-inventory-issue999.yaml`:
```
- # maps to CURIE prefix: biolink
  url: https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.owl
  file: biolink-model.owl
  download: true
  title: Biolink meta-model
-
  url:  http://purl.obolibrary.org/obo/chebi.owl
  file: chebi.owl
  download: true
  title: Chemical Entities of Biological Interest
- # maps to CURIE prefix: GO
  url:  http://purl.obolibrary.org/obo/go/extensions/go-plus.owl
  file: go-plus.owl
  title: Gene Ontology
  download: true
```
running on my MBP,
```
python -u multi_ont_to_json_kg.py --test curies-to-categories.yaml curies-to-urls-map.yaml ont-load-inventory-issue999.yaml test999-a.json
python -u get_nodes_json_from_kg_json.py --test test999-a.json test999-a-nodes.json
python -u multi_ont_to_json_kg.py --test curies-to-categories.yaml curies-to-urls-map.yaml ont-load-inventory-issue999.yaml test999-b.json
python -u get_nodes_json_from_kg_json.py --test test999-b.json test999-b-nodes.json
diff test999-a-nodes.json test999-b-nodes.json
```
I'm seeing a huge list of differences:
```
---
>             "category": "biolink:Metabolite",
>             "category label": "metabolite",
2223900,2223901c2223900,2223901
<             "category": "biolink:BiologicalEntity",
<             "category label": "biological_entity",
---
>             "category": "biolink:FunctionalAssociation",
>             "category label": "functional_association",
2269022,2269023c2269022,2269023
<             "category": "biolink:BiologicalEntity",
<             "category label": "biological_entity",
---
>             "category": "biolink:FunctionalAssociation",
>             "category label": "functional_association",
2269056,2269057c2269056,2269057
<             "category": "biolink:BiologicalEntity",
<             "category label": "biological_entity",
---
>             "category": "biolink:FunctionalAssociation",
>             "category label": "functional_association",
2326161,2326162c2326161,2326162
<             "category": "biolink:FunctionalAssociation",
<             "category label": "functional_association",
---
>             "category": "biolink:Drug",
>             "category label": "drug",
2365338,2365339c2365338,2365339
<             "category": "biolink:Drug",
<             "category label": "drug",
---
>             "category": "biolink:FunctionalAssociation",
>             "category label": "functional_association",
2365459,2365460c2365459,2365460
<             "category": "biolink:Drug",
<             "category label": "drug",
---
>             "category": "biolink:FunctionalAssociation",
>             "category label": "functional_association",
2376926,2376927c2376926,2376927
<             "category": "biolink:FunctionalAssociation",
<             "category label": "functional_association",
---
>             "category": "biolink:Drug",
>             "category label": "drug",
2392376,2392377c2392376,2392377
<             "category": "biolink:FunctionalAssociation",
<             "category label": "functional_association",
---
>             "category": "biolink:Drug",
>             "category label": "drug",
```

**Comment by saramsey** [comment]
Investigating `CHEBI:75769`, well lookee here, it has two parents in the ontology,
<img width="602" alt="Screen Shot 2020-08-11 at 4 40 35 PM" src="https://user-images.githubusercontent.com/5562107/89959497-6701e480-dbf1-11ea-9544-d59995795576.png">

Notes:
- `CHEBI:50733` is a direct descendent of `CHEBI:23888` which is annotated as `drug` in `curies-to-categories.yaml`.
- `CHEBI:27314` is a descendent of `CHEBI:78295`, which is annotated as `biological entity` in `curies-to-categories.yaml`.

**Comment by saramsey** [comment]
Theory: the order of the items in the list for the outer loop is not consistent from run to run of `multi_ont_to_json_kg.py`, and it terminates on the first time through the loop due to the `break` on line 315:
<img width="897" alt="Screen Shot 2020-08-11 at 4 45 23 PM" src="https://user-images.githubusercontent.com/5562107/89959834-2f476c80-dbf2-11ea-9195-084b1fde7a7a.png">

**Comment by saramsey** [comment]
Trying a fix now....

**Comment by saramsey** [comment]
Hi @ericawood can I close this issue out?

**Comment by ericawood** [comment]
Hi @saramsey, can't quite close this out. For the Snakemake vs Sequential build to ensure that the two build systems line up. Rather than diff-ing the two JSON files, I decided to diff the two edges.tsv and two nodes.tsv files, as they are separated line by line rather than all on one line. Both were using the same version of the code (I didn't `git pull` in between builds) and when I ran `git status`, my local copy was up to date with the exception of a couple of changes I made to `version.sh` and `build-kg2.sh` to prevent the code from updating to the S3 bucket -- I'm not totally sure how that works because I pulled on Friday. Here is some of the output:

For nodes_header.tsv
```
category        :LABEL  creation_date   deprecated      description     full_name       id:ID   iri     name    provided_by     publications:string[]   replaced_by     synonym:string[]        update_date     category_label
```

nodes.tsv diff (snippet of 596M file):
```
6794143c6794143
< biolink:Gene  gene            False   A protein coding gene LPPR1 in human. // COMMENTS: Category=external.; Type:protein-coding; Locus:9q31.1; NameStatus:official   phospholipid phosphatase related 1      NCBIGene:54886  https://identifiers.org/ncbigene:54886  LPPR1 (human)   OBO:pr.owl                      plasticity-related gene 3 protein; LPPR1; PLPPR1; PRG-3; lipid phosphate phosphatase-related protein type 1; phospholipid phosphatase-related protein type 1; plasticity related gene 3 2020-08-03 06:18:13 GMT gene^M
---
> biolink:Gene  gene            False   A protein coding gene LPPR1 in human. // COMMENTS: Category=external.; Type:protein-coding; Locus:9q31.1; NameStatus:official   phospholipid phosphatase related 1      NCBIGene:54886  https://identifiers.org/ncbigene:54886  LPPR1 (human)   OBO:pr.owl                      PRG-3; LPPR1; PLPPR1; lipid phosphate phosphatase-related protein type 1; phospholipid phosphatase-related protein type 1; plasticity related gene 3; plasticity-related gene 3 protein 2020-08-03 06:18:13 GMT gene^M
6796047c6796047
< biolink:Gene  gene            False   A protein coding gene LPPR4 in human. // COMMENTS: Category=external.; Type:protein-coding; Locus:1p21.3-p21.2; NameStatus:official     phospholipid phosphatase related 4      NCBIGene:9890   https://identifiers.org/ncbigene:9890   LPPR4 (human)   OBO:pr.owl                      plasticity related gene 1; LPPR4; LPR4; PHP1; PLPPR4; PRG-1; PRG1; brain-specific phosphatidic acid phosphatase-like protein 1; lipid phosphate phosphatase-related protein type 4; phospholipid phosphatase-related protein type 4; plasticity-related gene 1 protein  2020-08-03 06:18:13 GMT gene^M
---
> biolink:Gene  gene            False   A protein coding gene LPPR4 in human. // COMMENTS: Category=external.; Type:protein-coding; Locus:1p21.3-p21.2; NameStatus:official     phospholipid phosphatase related 4      NCBIGene:9890   https://identifiers.org/ncbigene:9890   LPPR4 (human)   OBO:pr.owl                      PHP1; LPPR4; LPR4; PLPPR4; PRG-1; PRG1; brain-specific phosphatidic acid phosphatase-like protein 1; lipid phosphate phosphatase-related protein type 4; phospholipid phosphatase-related protein type 4; plasticity related gene 1; plasticity-related gene 1 protein  2020-08-03 06:18:13 GMT gene^M
```


For edges_header.tsv
```
edge_label      negated :END_ID provided_by:string[]    publications:string[]   publications_info       relation        edge_label:TYPE simplified_relation     :START_ID       update_date     simplified_edge_label   subject object
```

edges.tsv diff (snippet of 32G file):
```
11143a11143
> xref  False   UMLS:C3703015   umls_source:CPT         {}      oboFormat:xref  close_match     skos:closeMatch CPT:27390       Sat Aug  1 00:43:02 2020        close_match     CPT:27390       UMLS:C3703015^M
11255d11254
< xref  False   UMLS:C3516672   umls_source:CPT         {}      oboFormat:xref  close_match     skos:closeMatch CPT:88381       Sat Aug  1 00:43:02 2020        close_match     CPT:88381       UMLS:C3516672^M
11256a11256
> xref  False   UMLS:C3516672   umls_source:CPT         {}      oboFormat:xref  close_match     skos:closeMatch CPT:88381       Sat Aug  1 00:43:02 2020        close_match     CPT:88381       UMLS:C3516672^M
11498d11497
< xref  False   UMLS:C3702541   umls_source:CPT         {}      oboFormat:xref  close_match     skos:closeMatch CPT:0339T       Sat Aug  1 00:43:02 2020        close_match     CPT:0339T       UMLS:C3702541^M
11500c11499
< xref  False   UMLS:C3517570   umls_source:CPT         {}      oboFormat:xref  close_match     skos:closeMatch CPT:0206T       Sat Aug  1 00:43:02 2020        close_match     CPT:0206T       UMLS:C3517570^M
---
> xref  False   UMLS:C3702541   umls_source:CPT         {}      oboFormat:xref  close_match     skos:closeMatch CPT:0339T       Sat Aug  1 00:43:02 2020        close_match     CPT:0339T       UMLS:C3702541^M
11501a11501
> xref  False   UMLS:C3517570   umls_source:CPT         {}      oboFormat:xref  close_match     skos:closeMatch CPT:0206T       Sat Aug  1 00:43:02 2020        close_match     CPT:0206T       UMLS:C3517570^M
11520d11519
< xref  False   UMLS:C3865608   umls_source:CPT         {}      oboFormat:xref  close_match     skos:closeMatch CPT:27370       Sat Aug  1 00:43:02 2020        close_match     CPT:27370       UMLS:C3865608^M
11521a11521
> xref  False   UMLS:C3865608   umls_source:CPT         {}      oboFormat:xref  close_match     skos:closeMatch CPT:27370       Sat Aug  1 00:43:02 2020        close_match     CPT:27370       UMLS:C3865608^M
11564d11563
< xref  False   UMLS:C0374537   umls_source:CPT         {}      oboFormat:xref  close_match     skos:closeMatch CPT:99058       Sat Aug  1 00:43:02 2020        close_match     CPT:99058       UMLS:C0374537^M
11565a11565
> xref  False   UMLS:C0374537   umls_source:CPT         {}      oboFormat:xref  close_match     skos:closeMatch CPT:99058       Sat Aug  1 00:43:02 2020        close_match     CPT:99058       UMLS:C0374537^M
11588d11587
< xref  False   UMLS:C3517573   umls_source:CPT         {}      oboFormat:xref  close_match     skos:closeMatch CPT:0209T       Sat Aug  1 00:43:02 2020        close_match     CPT:0209T       UMLS:C3517573^M
```

I think that the nodes issue is part of this issue. I am unsure about the edges issue, since I don't remember that being significant before (but I also wasn't running `diff`, I was running a script that compared each element with the other dictionary to see if it was present anywhere).

**Comment by ericawood** [comment]
Viewing the bottom of the nodes.tsv diff, I suspect this is also an issue with the NCBIGene ETL:
```
9135161,9135163c9135161,9135163
< biolink:Gene  gene            False   CD209 promoter region; Type:biological-region; Locus:19p; NameStatus:unofficial CD209 promoter region   NCBIGene:117307477      https://identifiers.org/ncbigene:117307477      CD209 promoter region   identifiers_org_registry:ncbigene                       LOC117307477; DC-SIGN promoter  20200801        gene^M
< biolink:Gene  gene            False   CLEC4M promoter region; Type:biological-region; Locus:19p; NameStatus:unofficial        CLEC4M promoter region  NCBIGene:117307478      https://identifiers.org/ncbigene:117307478      CLEC4M promoter region  identifiers_org_registry:ncbigene                       LOC117307478; DC-SIGNR promoter 20200801        gene^M
< biolink:Gene  gene            False   Type:pseudo; Locus:2q21.2; NameStatus:official  CDRT15 pseudogene 4     NCBIGene:117314529      https://identifiers.org/ncbigene:117314529      CDRT15 pseudogene 4     identifiers_org_registry:ncbigene                       CDRT15P4; CMT1A duplicated region transcript 15 pseudogene 4    20200801        gene^M
---
> biolink:Gene  gene            False   CD209 promoter region; Type:biological-region; Locus:19p; NameStatus:unofficial CD209 promoter region   NCBIGene:117307477      https://identifiers.org/ncbigene:117307477      CD209 promoter region   identifiers_org_registry:ncbigene                       DC-SIGN promoter; LOC117307477  20200801        gene^M
> biolink:Gene  gene            False   CLEC4M promoter region; Type:biological-region; Locus:19p; NameStatus:unofficial        CLEC4M promoter region  NCBIGene:117307478      https://identifiers.org/ncbigene:117307478      CLEC4M promoter region  identifiers_org_registry:ncbigene                       DC-SIGNR promoter; LOC117307478 20200801        gene^M
> biolink:Gene  gene            False   Type:pseudo; Locus:2q21.2; NameStatus:official  CDRT15 pseudogene 4     NCBIGene:117314529      https://identifiers.org/ncbigene:117314529      CDRT15 pseudogene 4     identifiers_org_registry:ncbigene                       CMT1A duplicated region transcript 15 pseudogene 4; CDRT15P4    20200801        gene^M
9135195c9135195
< biolink:Gene  gene            False   Type:pseudo; Locus:Yq11.222; NameStatus:official        elongin C pseudogene 26 NCBIGene:118097967      https://identifiers.org/ncbigene:118097967      elongin C pseudogene 26 identifiers_org_registry:ncbigene                       TCEB1P26; transcription elongation factor B (SIII), polypeptide 1 pseudogene 26; ELOCP26; transcription elongation factor B subunit 1 pseudogene 26; ELOC26     20200627        gene^M
---
> biolink:Gene  gene            False   Type:pseudo; Locus:Yq11.222; NameStatus:official        elongin C pseudogene 26 NCBIGene:118097967      https://identifiers.org/ncbigene:118097967      elongin C pseudogene 26 identifiers_org_registry:ncbigene                       transcription elongation factor B subunit 1 pseudogene 26; ELOC26; ELOCP26; TCEB1P26; transcription elongation factor B (SIII), polypeptide 1 pseudogene 26     20200627        gene^M
9135197c9135197
< biolink:Gene  gene            False   GUCA1ANB-GUCA1A readthrough; Type:protein-coding; NameStatus:unofficial GUCA1ANB-GUCA1A readthrough     NCBIGene:118142757      https://identifiers.org/ncbigene:118142757      GUCA1ANB-GUCA1A readthrough     identifiers_org_registry:ncbigene                       GUCA1A; GUCA1ANB-GUCA1A; guanylyl cyclase-activating protein 1  20200722        gene^M
---
> biolink:Gene  gene            False   GUCA1ANB-GUCA1A readthrough; Type:protein-coding; NameStatus:unofficial GUCA1ANB-GUCA1A readthrough     NCBIGene:118142757      https://identifiers.org/ncbigene:118142757      GUCA1ANB-GUCA1A readthrough     identifiers_org_registry:ncbigene                       guanylyl cyclase-activating protein 1; GUCA1ANB-GUCA1A; GUCA1A  20200722        gene^M
```

**Comment by ericawood** [comment]
FYI, the report files for the two build were identical (with the exception of the report generated time).

**Comment by ericawood** [comment]
> Excellent detective work.
> 
> OK, so it looks like the `synonym` list ordering is variable from run to run, is that correct?

Yes, that was my conclusion as well.

**Comment by saramsey** [comment]
Good idea to diff the `nodes.tsv` files.  Which direction is the diff?  i.e., is `<` the sequential build or is `>` the sequential build?

**Comment by ericawood** [comment]
On kg2-steve in kg2-build:
Edges:
`diff SequentialBuild/edges.tsv SnakemakeBuild/edges.tsv > edges_tsv_diff.log`

Nodes
`diff SequentialBuild/nodes.tsv SnakemakeBuild/nodes.tsv > nodes_tsv_diff.log`

**Comment by saramsey** [comment]
Thanks, this is well organized.

**Comment by saramsey** [comment]
For the moment, I'm focusing on the nodes issue.

**Comment by saramsey** [comment]
Did you mean `ParallelBuild` instead of `SnakemakeBuild` ?

**Comment by saramsey** [comment]
Can you confirm -- you did a test build, is that correct?

**Comment by ericawood** [comment]
Hi @saramsey,
1) The data is in `SnakemakeBuild` on **`kg2steve`**:
![image](https://user-images.githubusercontent.com/36611732/91225378-64ff5180-e6d8-11ea-9d7a-b9d092d62dba.png)
2) No, this was a partial build **without** test flags

**Comment by saramsey** [comment]
Sorry, I was looking on `kg2dev`. My bad.

**Comment by saramsey** [comment]
Switching over to `kg2steve` now....

**Comment by saramsey** [comment]
On `kg2steve`, I am running
```
python ~/kg2-code/get_nodes_json_from_kg_json.py --test kg2-simplified.json kg2-simplified-nodes.json
```
so I can have a look at the `NCBIGene:54886` node

**Comment by saramsey** [comment]
I posit that this (and analogous code in other modules) may be our smoking gun:
<img width="523" alt="Screen Shot 2020-08-25 at 1 49 00 PM" src="https://user-images.githubusercontent.com/5562107/91226407-d1c71b80-e6d9-11ea-9cf6-e7e1fe95b268.png">

**Comment by saramsey** [comment]
I propose the following remedy to `ncbigene_tsv_to_kg_json.py`:
<img width="556" alt="Screen Shot 2020-08-25 at 1 54 36 PM" src="https://user-images.githubusercontent.com/5562107/91226940-8feaa500-e6da-11ea-8c5a-a712008c0bc1.png">

**Comment by saramsey** [comment]
I note that `/home/ubuntu/kg2-build/kg2-ncbigene.json` is also incorrect in the same way:

<img width="632" alt="Screen Shot 2020-08-25 at 1 57 42 PM" src="https://user-images.githubusercontent.com/5562107/91227232-02f41b80-e6db-11ea-92c3-f2bbc1e6dd0a.png">

This increases my suspicion that the problem is in `ncbigene_tsv_to_kg_json.py`.

**Comment by saramsey** [comment]
Looks like my proposed fix is helping:

<img width="632" alt="Screen Shot 2020-08-25 at 1 59 38 PM" src="https://user-images.githubusercontent.com/5562107/91227386-43539980-e6db-11ea-8345-415fb4e220a5.png">

**Comment by ericawood** [comment]
Edges from UniProt:
```
30825334a30825332
> physically_interacts_with     False   CHEBI:57394     identifiers_org_registry:uniprot                {}      biolink:physically_interacts_with       physically_interacts_with       biolink:physically_interacts_with       UniProtKB:Q9NXF8        12-AUG-2020     physically_interacts_with       UniProtKB:Q9NXF8        CHEBI:57394^M
30825337c30825335,30825336
< physically_interacts_with     False   CHEBI:143199    identifiers_org_registry:uniprot                {}      biolink:physically_interacts_with       physically_interacts_with       biolink:physically_interacts_with       UniProtKB:Q9NXF8        12-AUG-2020     physically_interacts_with       UniProtKB:Q9NXF8        CHEBI:143199^M
---
> physically_interacts_with     False   CHEBI:74151     identifiers_org_registry:uniprot                {}      biolink:physically_interacts_with       physically_interacts_with       biolink:physically_interacts_with       UniProtKB:Q9NXF8        12-AUG-2020     physically_interacts_with       UniProtKB:Q9NXF8        CHEBI:74151^M
> physically_interacts_with     False   CHEBI:143200    identifiers_org_registry:uniprot                {}      biolink:physically_interacts_with       physically_interacts_with       biolink:physically_interacts_with       UniProtKB:Q9NXF8        12-AUG-2020     physically_interacts_with       UniProtKB:Q9NXF8        CHEBI:143200^M
30825338a30825338,30825339
> physically_interacts_with     False   CHEBI:143199    identifiers_org_registry:uniprot                {}      biolink:physically_interacts_with       physically_interacts_with       biolink:physically_interacts_with       UniProtKB:Q9NXF8        12-AUG-2020     physically_interacts_with       UniProtKB:Q9NXF8        CHEBI:143199^M
> physically_interacts_with     False   CHEBI:57287     identifiers_org_registry:uniprot                {}      biolink:physically_interacts_with       physically_interacts_with       biolink:physically_interacts_with       UniProtKB:Q9ULC8        12-AUG-2020     physically_interacts_with       UniProtKB:Q9ULC8        CHEBI:57287^M
```

**Comment by saramsey** [comment]
Hi @ericawood just checking back on this... do you think the above commits helped?

**Comment by ericawood** [comment]
Hi @saramsey, I still haven't tested yet (please see my slack message). May I use kg2steve for testing this as it has constant pickle files for the ontologies?

**Comment by ericawood** [comment]
Hi @saramsey,
This issue was fixed in the test build I ran between Snakemake and Sequential. Should I close it out?
